//Auto Generated file
var subset_
	 = [
	
		['Y11_HH2a', 'Pohlaví'],
		['Y11_Incomequartiles_percapita', 'Příjem'],
		['Y11_Agecategory', 'Věk']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Osoby každého věku'],
		['Y11_Agecategory', '1--18-24y', '18 až 24 let'],
		['Y11_Agecategory', '2--25-34y', '25 až 34 let'],
		['Y11_Agecategory', '3--35-49y', '35 až 49 let'],
		['Y11_Agecategory', '4--50-64y', '50 až 64 let'],
		['Y11_Agecategory', '5---64y', '> 64 let'],
		['Y11_HH2a', 'All', 'Obě pohlaví'],
		['Y11_HH2a', '1--Female', 'Žena'],
		['Y11_HH2a', '2--Male', 'Muž'],
		['Y11_Incomequartiles_percapita', 'All', 'Všechny výše příjmu'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Nejnižší'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'Druhý'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'Třetí'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Nejvyšší']
	];
var topic_
	 = [
	
		['', 'vše (127)'],
		['Domov a okolí', 'Domov a okolí (21)'],
		['Kvalita společnosti', 'Kvalita společnosti (14)'],
		['Rodina a sociální život', 'Rodina a sociální život (13)'],
		['Sociální vyloučení a zapojení do komunity', 'Sociální vyloučení a zapojení do komunity (15)'],
		['Subjektivní pohoda', 'Subjektivní pohoda (14)'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Zaměstnanost a rovnováha mezi pracovním a osobním životem (18)'],
		['Zdraví a veřejné služby', 'Zdraví a veřejné služby (17)'],
		['Životní úroveň a deprivace', 'Životní úroveň a deprivace (15)']
	];
var topic_question
	 = [
	
		['Domov a okolí', 'Y11_Accommproblems', 'Řada problémů s ubytováním'],
		['Domov a okolí', 'Y11_Q18', 'Vlastnictví domu/bytu'],
		['Domov a okolí', 'Y11_Q19a', 'Problémy s ubytováním/bydlením: nedostatek místa'],
		['Domov a okolí', 'Y11_Q19b', 'Problémy s ubytováním/bydlením: hniloba v oknech, dveřích nebo podlaze'],
		['Domov a okolí', 'Y11_Q19c', 'Problémy s ubytováním/bydlením: vlhkost / zatékání ve zdech nebo ve střeše'],
		['Domov a okolí', 'Y11_Q19d', 'Problémy s ubytováním/bydlením: bez splachovacího záchodu v domě/bytě'],
		['Domov a okolí', 'Y11_Q19e', 'Problémy s ubytováním/bydlením: chybějící vana nebo sprcha'],
		['Domov a okolí', 'Y11_Q19f', 'Problémy s ubytováním/bydlením: chybějící místo, kam byste se mohl(a) posadit ven'],
		['Domov a okolí', 'Y11_Q20', 'Jak je podle vás pravděpodobné nebo nepravděpodobné, že budete muset své ubytování/bydlení během následujících šesti měsíců opustit, protože si je nadále nebudete moci dovolit?'],
		['Domov a okolí', 'Y11_Q50a', 'Problémy s hlukem v okolí'],
		['Domov a okolí', 'Y11_Q50b', 'Problémy s kvalitou ovzduší v okolí'],
		['Domov a okolí', 'Y11_Q50c', 'Problémy s kvalitou pitné vody v okolí'],
		['Domov a okolí', 'Y11_Q50d', 'Problémy se zločinem, násilím nebo vandalismem v okolí'],
		['Domov a okolí', 'Y11_Q50e', 'Problémy s nepořádkem nebo odpadky na ulici'],
		['Domov a okolí', 'Y11_Q50f', 'Problémy s dopravními zácpami v okolí'],
		['Domov a okolí', 'Y11_Q51a', 'Přístup k poštovním službám'],
		['Domov a okolí', 'Y11_Q51b', 'Přístup k bankovním službám'],
		['Domov a okolí', 'Y11_Q51c', 'Přístup k veřejné dopravě'],
		['Domov a okolí', 'Y11_Q51d', 'Přístup do kina, divadla nebo kulturního centra'],
		['Domov a okolí', 'Y11_Q51e', 'Přístup k rekreačním nebo zeleným plochám'],
		['Domov a okolí', 'Y11_Q52', 'Čas strávený na cestě do práce nebo do školy a zpět domů'],
		['Kvalita společnosti', 'Y11_Q24', 'Řekl(a) byste, že většině lidí lze důvěřovat, nebo že člověk nemůže být při jednání s lidmi nikdy dost opatrný?'],
		['Kvalita společnosti', 'Y11_Q25a', 'Vnímané napětí mezi chudými a bohatými lidmi'],
		['Kvalita společnosti', 'Y11_Q25b', 'Vnímané napětí mezi vedoucími pracovníky (managementem) a pracujícími'],
		['Kvalita společnosti', 'Y11_Q25c', 'Vnímané napětí mezi muži a ženami'],
		['Kvalita společnosti', 'Y11_Q25d', 'Vnímané napětí mezi starými a mladými lidmi'],
		['Kvalita společnosti', 'Y11_Q25e', 'Vnímané napětí mezi různými rasovými a etnickými skupinami'],
		['Kvalita společnosti', 'Y11_Q25f', 'Vnímané napětí mezi různými náboženskými skupinami'],
		['Kvalita společnosti', 'Y11_Q25g', 'Vnímané napětí mezi lidmi s rozdílnou sexuální orientací'],
		['Kvalita společnosti', 'Y11_Q28a', 'Důvěra v parlament'],
		['Kvalita společnosti', 'Y11_Q28b', 'Důvěra v právní systém'],
		['Kvalita společnosti', 'Y11_Q28c', 'Důvěra v tisk'],
		['Kvalita společnosti', 'Y11_Q28d', 'Důvěra v policii'],
		['Kvalita společnosti', 'Y11_Q28e', 'Důvěra ve vládu'],
		['Kvalita společnosti', 'Y11_Q28f', 'Důvěra v místní nebo městské úřady'],
		['Rodina a sociální život', 'Y11_Q33a', 'Osobní kontakt s dětmi, které žijí mimo Vaši domácnost'],
		['Rodina a sociální život', 'Y11_Q33b', 'Osobní kontakt s matkou nebo otcem, kteří žijí mimo Vaši domácnost'],
		['Rodina a sociální život', 'Y11_Q33c', 'Osobní kontakt s jinými příbuznými, kteří žijí mimo Vaši domácnost'],
		['Rodina a sociální život', 'Y11_Q33d', 'Osobní kontakt s přáteli nebo sousedy'],
		['Rodina a sociální život', 'Y11_Q34a', 'Kontakt s dětmi, které žijí mimo Vaši domácnost, po telefonu, přes internet nebo poštou'],
		['Rodina a sociální život', 'Y11_Q34b', 'Kontakt s matkou nebo otcem, kteří žijí mimo Vaši domácnost, po telefonu, přes internet nebo poštou'],
		['Rodina a sociální život', 'Y11_Q34c', 'Kontakt s jinými příbuznými, kteří žijí mimo Vaši domácnost, po telefonu, přes internet nebo poštou'],
		['Rodina a sociální život', 'Y11_Q34d', 'Kontakt s přáteli nebo sousedy po telefonu, přes internet nebo poštou'],
		['Rodina a sociální život', 'Y11_Q35a', 'Od koho byste mohl(a) očekávat podporu, jestliže byste v době své nemoci potřeboval(a) doma pomoc?'],
		['Rodina a sociální život', 'Y11_Q35b', 'Od koho byste mohl(a) očekávat podporu, jestliže byste potřeboval(a) poradit v souvislosti s vážnou osobní nebo rodinnou záležitostí?'],
		['Rodina a sociální život', 'Y11_Q35c', 'Od koho byste mohl(a) očekávat podporu, kdybyste potřeboval(a) pomoc při hledání práce?'],
		['Rodina a sociální život', 'Y11_Q35d', 'Od koho byste mohl(a) očekávat podporu v případě, že byste se cítil(a) trochu depresivně?'],
		['Rodina a sociální život', 'Y11_Q35e', 'Od koho byste mohl(a) očekávat podporu, pokud byste v případě nějaké akutní potřeby potřeboval(a) sehnat částku 1 000 EUR? '],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q21a', 'Návštěva bohoslužeb kromě svateb, pohřbů nebo křtin'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q21b', 'Používání internetu za jiným účelem než pro práci'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q21c', 'Sportování nebo cvičení'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q21d', 'Účast na společenských aktivitách klubu, organizace nebo asociace'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q22_Volunteering', 'Jak často jste v posledních 12 měsících vykonával(a) neplacenou dobrovolnickou práci?'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q23a', 'Navštívil(a) v posledních 12 měsících nějaké jednání odborové organizace, politické strany nebo politicky činné skupiny'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q23b', 'Zúčastnil(a) se v posledních 12 měsících nějaké protestní akce nebo demonstrace'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q23c', 'Podepsal(a) v posledních 12 měsících nějakou petici'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q23d', 'Kontaktoval(a) nějakého politika nebo veřejného činitele (nemyslíme běžný kontakt související s používáním veřejných služeb)'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q29e', 'Cítím se vyřazený(á) ze společnosti'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q29f', 'Život je dnes tak složitý, že se v něm jen stěží mohu orientovat'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q29g', 'Mám pocit, že to, co dělám, není ostatními doceněno'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q29h', 'Někteří lidé se na mě dívají spatra kvůli mému pracovnímu zařazení nebo příjmu'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q29i', 'Cítím se blízko lidem v oblasti, kde žiji'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_SocExIndex', 'Index sociálního vyloučení'],
		['Subjektivní pohoda', 'Y11_Q29a', 'Jsem optimista, pokud jde o budoucnost'],
		['Subjektivní pohoda', 'Y11_Q29b', 'Mám obecně pocit, že to, co dělám v životě, stojí za to'],
		['Subjektivní pohoda', 'Y11_Q29c', 'Mám svobodu v rozhodování o tom, jak žít svůj život'],
		['Subjektivní pohoda', 'Y11_Q29d', 'Ve svém každodenním životě mám zřídka čas dělat věci, které mne opravdu baví'],
		['Subjektivní pohoda', 'Y11_Q30', 'Do jaké míry jste spokojený(á) se svým životem v dnešní době?'],
		['Subjektivní pohoda', 'Y11_Q40a', 'Spokojenost se vzděláním'],
		['Subjektivní pohoda', 'Y11_Q40b', 'Spokojenost se současným zaměstnáním'],
		['Subjektivní pohoda', 'Y11_Q40c', 'Spokojenost se současnou životní úrovní'],
		['Subjektivní pohoda', 'Y11_Q40d', 'Spokojenost s ubytováním/bydlením'],
		['Subjektivní pohoda', 'Y11_Q40e', 'Spokojenost s rodinným životem'],
		['Subjektivní pohoda', 'Y11_Q40f', 'Spokojenost se zdravím'],
		['Subjektivní pohoda', 'Y11_Q40g', 'Spokojenost se společenským životem'],
		['Subjektivní pohoda', 'Y11_Q40h', 'Spokojenost s ekonomickou situací v zemi'],
		['Subjektivní pohoda', 'Y11_Q41', 'Když se vezmou všechny okolnosti, můžete prosím uvést, jak jste šťastný(á)?'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q8_PreferredWorkingHours', 'Kolik hodin týdně byste chtěl(a) pracovat? '],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q10_Partnerprefhours', 'Kolik hodin týdně byste chtěl(a), aby pracoval(a) Váš partner / Vaše partnerka?'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q12a', 'Přišel(a) jsem z práce domů příliš unavený(á) na to, abych mohl(a) dělat domácí práce'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q12b', 'Vzhledem k množství času, které věnuji práci, pro mě bylo těžké plnit povinnosti vůči rodině'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q12c', 'Vzhledem k mým povinnostem v rodině bylo pro mě těžké se soustředit na práci'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q13a', 'Mám volnou pracovní dobu'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q13b', 'Mohu si napracovat hodiny za účelem pracovního volna'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q13c', 'Mohu si vzít narychlo volno, pokud potřebuji'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q15', 'S jakou pravděpodobností by se mohlo stát, že byste v průběhu následujících 6 měsíců přišel(a) o svou práci?'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q16', 'Kdybyste ztratil(a) práci, jak je pravděpodobné, že byste si našel/našla zaměstnání s podobným platem?'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q36a', 'Jak často se zabýváte péčí o své děti nebo vnoučata?'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q36b', 'Jak často se zabýváte vařením nebo domácími pracemi?'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q36c', 'Jak často se zabýváte péčí o staré nebo invalidní příbuzné?'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q38', 'Postoj k podílu na domácích pracích'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q39a', 'Postoj k času strávenému s rodinnými příslušníky'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q39b', 'Postoj k času strávenému s jinými lidmi'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q39c', 'Postoj k času strávenému s vlastními koníčky a zájmy'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q39d_stress', 'Stres'],
		['Zdraví a veřejné služby', 'Y11_Q42', 'Vnímaný zdravotní stav'],
		['Zdraví a veřejné služby', 'Y11_Q46a', 'Cítil(a) jsem se obzvláště napjatý/á'],
		['Zdraví a veřejné služby', 'Y11_Q46b', 'Cítil()a jsem se osaměle'],
		['Zdraví a veřejné služby', 'Y11_Q46c', 'Cítil(a) jsem se skleslý(á) a v depresi'],
		['Zdraví a veřejné služby', 'Y11_Q46d_WHO5', 'Pětistupňová klasifikace duševní pohody podle WHO'],
		['Zdraví a veřejné služby', 'Y11_Q47a', 'Problém s návštěvou lékaře z důvodu vzdálenosti'],
		['Zdraví a veřejné služby', 'Y11_Q47b', 'Problém s návštěvou lékaře z důvodu dlouhé lhůty objednání'],
		['Zdraví a veřejné služby', 'Y11_Q47c', 'Problém s návštěvou lékaře z důvodu doby strávené v čekárně v den objednání'],
		['Zdraví a veřejné služby', 'Y11_Q47d', 'Problém s návštěvou lékaře z důvodu ceny'],
		['Zdraví a veřejné služby', 'Y11_Q47e', 'Problém s návštěvou lékaře z důvodu nedostatku času'],
		['Zdraví a veřejné služby', 'Y11_Q53a', 'Jak byste hodnotil(a) kvalitu zdravotní péče ve Vaší zemi? '],
		['Zdraví a veřejné služby', 'Y11_Q53b', 'Jak byste hodnotil(a) kvalitu vzdělávacího systému ve Vaší zemi? '],
		['Zdraví a veřejné služby', 'Y11_Q53c', 'Jak byste hodnotil(a) kvalitu veřejné dopravy ve Vaší zemi? '],
		['Zdraví a veřejné služby', 'Y11_Q53d', 'Jak byste hodnotil(a) kvalitu péče o děti ve Vaší zemi? '],
		['Zdraví a veřejné služby', 'Y11_Q53e', 'Jak byste hodnotil(a) kvalitu služeb dlouhodobé péče ve Vaší zemi? '],
		['Zdraví a veřejné služby', 'Y11_Q53f', 'Jak byste hodnotil(a) kvalitu sociálních bytů ve Vaší zemi? '],
		['Zdraví a veřejné služby', 'Y11_Q53g', 'Jak byste hodnotil(a) kvalitu státního důchodového systému ve Vaší zemi? '],
		['Životní úroveň a deprivace', 'Y11_Deprindex', 'Index deprivace: Počet položek, které si domácnost nemůže dovolit'],
		['Životní úroveň a deprivace', 'Y11_Q57', 'Finanční situace domácnosti ve srovnání s většinou lidí v zemi '],
		['Životní úroveň a deprivace', 'Y11_Q58', 'Je Vaše domácnost schopna vyjít s penězi?'],
		['Životní úroveň a deprivace', 'Y11_Q59a', 'Můžete si dovolit udržovat v domácnosti přiměřené teplo?'],
		['Životní úroveň a deprivace', 'Y11_Q59b', 'Můžete si dovolit zaplatit ročně za týden dovolené mimo domov?'],
		['Životní úroveň a deprivace', 'Y11_Q59c', 'Můžete si dovolit vyměnit jakýkoliv opotřebovaný nábytek?'],
		['Životní úroveň a deprivace', 'Y11_Q59d', 'Můžete si dovolit mít každý druhý den jídlo s masem, s kuřetem nebo rybou, pokud byste je chtěl(a)?'],
		['Životní úroveň a deprivace', 'Y11_Q59e', 'Můžete si dovolit kupovat si spíše nové oblečení než obnošené oblečení (ze second‐handu)?'],
		['Životní úroveň a deprivace', 'Y11_Q59f', 'Můžete si dovolit alespoň jednou za měsíc pozvat domů přátele nebo rodinu na nějaké pití nebo jídlo?'],
		['Životní úroveň a deprivace', 'Y11_Q60a', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu s placením nájmu nebo hypotéky za bydlení?'],
		['Životní úroveň a deprivace', 'Y11_Q60b', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu s placením účtů za elektřinu, vodu, plyn?'],
		['Životní úroveň a deprivace', 'Y11_Q60c', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu se splácením spotřebitelských úvěrů?'],
		['Životní úroveň a deprivace', 'Y11_Q60d', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu se splácením neformálních půjček?'],
		['Životní úroveň a deprivace', 'Y11_Q65', 'Finanční situace domácnosti ve srovnání s její finanční situací před 12 měsíci'],
		['Životní úroveň a deprivace', 'Y11_Q66', 'Očekávaná finanční situace za dalších 12 měsíců']
	];
var question_
	 = [
	
		['Y11_Accommproblems', 'Řada problémů s ubytováním'],
		['Y11_Q18', 'Vlastnictví domu/bytu'],
		['Y11_Q19a', 'Problémy s ubytováním/bydlením: nedostatek místa'],
		['Y11_Q19b', 'Problémy s ubytováním/bydlením: hniloba v oknech, dveřích nebo podlaze'],
		['Y11_Q19c', 'Problémy s ubytováním/bydlením: vlhkost / zatékání ve zdech nebo ve střeše'],
		['Y11_Q19d', 'Problémy s ubytováním/bydlením: bez splachovacího záchodu v domě/bytě'],
		['Y11_Q19e', 'Problémy s ubytováním/bydlením: chybějící vana nebo sprcha'],
		['Y11_Q19f', 'Problémy s ubytováním/bydlením: chybějící místo, kam byste se mohl(a) posadit ven'],
		['Y11_Q20', 'Jak je podle vás pravděpodobné nebo nepravděpodobné, že budete muset své ubytování/bydlení během následujících šesti měsíců opustit, protože si je nadále nebudete moci dovolit?'],
		['Y11_Q50a', 'Problémy s hlukem v okolí'],
		['Y11_Q50b', 'Problémy s kvalitou ovzduší v okolí'],
		['Y11_Q50c', 'Problémy s kvalitou pitné vody v okolí'],
		['Y11_Q50d', 'Problémy se zločinem, násilím nebo vandalismem v okolí'],
		['Y11_Q50e', 'Problémy s nepořádkem nebo odpadky na ulici'],
		['Y11_Q50f', 'Problémy s dopravními zácpami v okolí'],
		['Y11_Q51a', 'Přístup k poštovním službám'],
		['Y11_Q51b', 'Přístup k bankovním službám'],
		['Y11_Q51c', 'Přístup k veřejné dopravě'],
		['Y11_Q51d', 'Přístup do kina, divadla nebo kulturního centra'],
		['Y11_Q51e', 'Přístup k rekreačním nebo zeleným plochám'],
		['Y11_Q52', 'Čas strávený na cestě do práce nebo do školy a zpět domů'],
		['Y11_Q24', 'Řekl(a) byste, že většině lidí lze důvěřovat, nebo že člověk nemůže být při jednání s lidmi nikdy dost opatrný?'],
		['Y11_Q25a', 'Vnímané napětí mezi chudými a bohatými lidmi'],
		['Y11_Q25b', 'Vnímané napětí mezi vedoucími pracovníky (managementem) a pracujícími'],
		['Y11_Q25c', 'Vnímané napětí mezi muži a ženami'],
		['Y11_Q25d', 'Vnímané napětí mezi starými a mladými lidmi'],
		['Y11_Q25e', 'Vnímané napětí mezi různými rasovými a etnickými skupinami'],
		['Y11_Q25f', 'Vnímané napětí mezi různými náboženskými skupinami'],
		['Y11_Q25g', 'Vnímané napětí mezi lidmi s rozdílnou sexuální orientací'],
		['Y11_Q28a', 'Důvěra v parlament'],
		['Y11_Q28b', 'Důvěra v právní systém'],
		['Y11_Q28c', 'Důvěra v tisk'],
		['Y11_Q28d', 'Důvěra v policii'],
		['Y11_Q28e', 'Důvěra ve vládu'],
		['Y11_Q28f', 'Důvěra v místní nebo městské úřady'],
		['Y11_Q33a', 'Osobní kontakt s dětmi, které žijí mimo Vaši domácnost'],
		['Y11_Q33b', 'Osobní kontakt s matkou nebo otcem, kteří žijí mimo Vaši domácnost'],
		['Y11_Q33c', 'Osobní kontakt s jinými příbuznými, kteří žijí mimo Vaši domácnost'],
		['Y11_Q33d', 'Osobní kontakt s přáteli nebo sousedy'],
		['Y11_Q34a', 'Kontakt s dětmi, které žijí mimo Vaši domácnost, po telefonu, přes internet nebo poštou'],
		['Y11_Q34b', 'Kontakt s matkou nebo otcem, kteří žijí mimo Vaši domácnost, po telefonu, přes internet nebo poštou'],
		['Y11_Q34c', 'Kontakt s jinými příbuznými, kteří žijí mimo Vaši domácnost, po telefonu, přes internet nebo poštou'],
		['Y11_Q34d', 'Kontakt s přáteli nebo sousedy po telefonu, přes internet nebo poštou'],
		['Y11_Q35a', 'Od koho byste mohl(a) očekávat podporu, jestliže byste v době své nemoci potřeboval(a) doma pomoc?'],
		['Y11_Q35b', 'Od koho byste mohl(a) očekávat podporu, jestliže byste potřeboval(a) poradit v souvislosti s vážnou osobní nebo rodinnou záležitostí?'],
		['Y11_Q35c', 'Od koho byste mohl(a) očekávat podporu, kdybyste potřeboval(a) pomoc při hledání práce?'],
		['Y11_Q35d', 'Od koho byste mohl(a) očekávat podporu v případě, že byste se cítil(a) trochu depresivně?'],
		['Y11_Q35e', 'Od koho byste mohl(a) očekávat podporu, pokud byste v případě nějaké akutní potřeby potřeboval(a) sehnat částku 1 000 EUR? '],
		['Y11_Q21a', 'Návštěva bohoslužeb kromě svateb, pohřbů nebo křtin'],
		['Y11_Q21b', 'Používání internetu za jiným účelem než pro práci'],
		['Y11_Q21c', 'Sportování nebo cvičení'],
		['Y11_Q21d', 'Účast na společenských aktivitách klubu, organizace nebo asociace'],
		['Y11_Q22_Volunteering', 'Jak často jste v posledních 12 měsících vykonával(a) neplacenou dobrovolnickou práci?'],
		['Y11_Q23a', 'Navštívil(a) v posledních 12 měsících nějaké jednání odborové organizace, politické strany nebo politicky činné skupiny'],
		['Y11_Q23b', 'Zúčastnil(a) se v posledních 12 měsících nějaké protestní akce nebo demonstrace'],
		['Y11_Q23c', 'Podepsal(a) v posledních 12 měsících nějakou petici'],
		['Y11_Q23d', 'Kontaktoval(a) nějakého politika nebo veřejného činitele (nemyslíme běžný kontakt související s používáním veřejných služeb)'],
		['Y11_Q29e', 'Cítím se vyřazený(á) ze společnosti'],
		['Y11_Q29f', 'Život je dnes tak složitý, že se v něm jen stěží mohu orientovat'],
		['Y11_Q29g', 'Mám pocit, že to, co dělám, není ostatními doceněno'],
		['Y11_Q29h', 'Někteří lidé se na mě dívají spatra kvůli mému pracovnímu zařazení nebo příjmu'],
		['Y11_Q29i', 'Cítím se blízko lidem v oblasti, kde žiji'],
		['Y11_SocExIndex', 'Index sociálního vyloučení'],
		['Y11_Q29a', 'Jsem optimista, pokud jde o budoucnost'],
		['Y11_Q29b', 'Mám obecně pocit, že to, co dělám v životě, stojí za to'],
		['Y11_Q29c', 'Mám svobodu v rozhodování o tom, jak žít svůj život'],
		['Y11_Q29d', 'Ve svém každodenním životě mám zřídka čas dělat věci, které mne opravdu baví'],
		['Y11_Q30', 'Do jaké míry jste spokojený(á) se svým životem v dnešní době?'],
		['Y11_Q40a', 'Spokojenost se vzděláním'],
		['Y11_Q40b', 'Spokojenost se současným zaměstnáním'],
		['Y11_Q40c', 'Spokojenost se současnou životní úrovní'],
		['Y11_Q40d', 'Spokojenost s ubytováním/bydlením'],
		['Y11_Q40e', 'Spokojenost s rodinným životem'],
		['Y11_Q40f', 'Spokojenost se zdravím'],
		['Y11_Q40g', 'Spokojenost se společenským životem'],
		['Y11_Q40h', 'Spokojenost s ekonomickou situací v zemi'],
		['Y11_Q41', 'Když se vezmou všechny okolnosti, můžete prosím uvést, jak jste šťastný(á)?'],
		['Y11_Q8_PreferredWorkingHours', 'Kolik hodin týdně byste chtěl(a) pracovat? '],
		['Y11_Q10_Partnerprefhours', 'Kolik hodin týdně byste chtěl(a), aby pracoval(a) Váš partner / Vaše partnerka?'],
		['Y11_Q12a', 'Přišel(a) jsem z práce domů příliš unavený(á) na to, abych mohl(a) dělat domácí práce'],
		['Y11_Q12b', 'Vzhledem k množství času, které věnuji práci, pro mě bylo těžké plnit povinnosti vůči rodině'],
		['Y11_Q12c', 'Vzhledem k mým povinnostem v rodině bylo pro mě těžké se soustředit na práci'],
		['Y11_Q13a', 'Mám volnou pracovní dobu'],
		['Y11_Q13b', 'Mohu si napracovat hodiny za účelem pracovního volna'],
		['Y11_Q13c', 'Mohu si vzít narychlo volno, pokud potřebuji'],
		['Y11_Q15', 'S jakou pravděpodobností by se mohlo stát, že byste v průběhu následujících 6 měsíců přišel(a) o svou práci?'],
		['Y11_Q16', 'Kdybyste ztratil(a) práci, jak je pravděpodobné, že byste si našel/našla zaměstnání s podobným platem?'],
		['Y11_Q36a', 'Jak často se zabýváte péčí o své děti nebo vnoučata?'],
		['Y11_Q36b', 'Jak často se zabýváte vařením nebo domácími pracemi?'],
		['Y11_Q36c', 'Jak často se zabýváte péčí o staré nebo invalidní příbuzné?'],
		['Y11_Q38', 'Postoj k podílu na domácích pracích'],
		['Y11_Q39a', 'Postoj k času strávenému s rodinnými příslušníky'],
		['Y11_Q39b', 'Postoj k času strávenému s jinými lidmi'],
		['Y11_Q39c', 'Postoj k času strávenému s vlastními koníčky a zájmy'],
		['Y11_Q39d_stress', 'Stres'],
		['Y11_Q42', 'Vnímaný zdravotní stav'],
		['Y11_Q46a', 'Cítil(a) jsem se obzvláště napjatý/á'],
		['Y11_Q46b', 'Cítil()a jsem se osaměle'],
		['Y11_Q46c', 'Cítil(a) jsem se skleslý(á) a v depresi'],
		['Y11_Q46d_WHO5', 'Pětistupňová klasifikace duševní pohody podle WHO'],
		['Y11_Q47a', 'Problém s návštěvou lékaře z důvodu vzdálenosti'],
		['Y11_Q47b', 'Problém s návštěvou lékaře z důvodu dlouhé lhůty objednání'],
		['Y11_Q47c', 'Problém s návštěvou lékaře z důvodu doby strávené v čekárně v den objednání'],
		['Y11_Q47d', 'Problém s návštěvou lékaře z důvodu ceny'],
		['Y11_Q47e', 'Problém s návštěvou lékaře z důvodu nedostatku času'],
		['Y11_Q53a', 'Jak byste hodnotil(a) kvalitu zdravotní péče ve Vaší zemi? '],
		['Y11_Q53b', 'Jak byste hodnotil(a) kvalitu vzdělávacího systému ve Vaší zemi? '],
		['Y11_Q53c', 'Jak byste hodnotil(a) kvalitu veřejné dopravy ve Vaší zemi? '],
		['Y11_Q53d', 'Jak byste hodnotil(a) kvalitu péče o děti ve Vaší zemi? '],
		['Y11_Q53e', 'Jak byste hodnotil(a) kvalitu služeb dlouhodobé péče ve Vaší zemi? '],
		['Y11_Q53f', 'Jak byste hodnotil(a) kvalitu sociálních bytů ve Vaší zemi? '],
		['Y11_Q53g', 'Jak byste hodnotil(a) kvalitu státního důchodového systému ve Vaší zemi? '],
		['Y11_Deprindex', 'Index deprivace: Počet položek, které si domácnost nemůže dovolit'],
		['Y11_Q57', 'Finanční situace domácnosti ve srovnání s většinou lidí v zemi '],
		['Y11_Q58', 'Je Vaše domácnost schopna vyjít s penězi?'],
		['Y11_Q59a', 'Můžete si dovolit udržovat v domácnosti přiměřené teplo?'],
		['Y11_Q59b', 'Můžete si dovolit zaplatit ročně za týden dovolené mimo domov?'],
		['Y11_Q59c', 'Můžete si dovolit vyměnit jakýkoliv opotřebovaný nábytek?'],
		['Y11_Q59d', 'Můžete si dovolit mít každý druhý den jídlo s masem, s kuřetem nebo rybou, pokud byste je chtěl(a)?'],
		['Y11_Q59e', 'Můžete si dovolit kupovat si spíše nové oblečení než obnošené oblečení (ze second‐handu)?'],
		['Y11_Q59f', 'Můžete si dovolit alespoň jednou za měsíc pozvat domů přátele nebo rodinu na nějaké pití nebo jídlo?'],
		['Y11_Q60a', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu s placením nájmu nebo hypotéky za bydlení?'],
		['Y11_Q60b', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu s placením účtů za elektřinu, vodu, plyn?'],
		['Y11_Q60c', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu se splácením spotřebitelských úvěrů?'],
		['Y11_Q60d', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu se splácením neformálních půjček?'],
		['Y11_Q65', 'Finanční situace domácnosti ve srovnání s její finanční situací před 12 měsíci'],
		['Y11_Q66', 'Očekávaná finanční situace za dalších 12 měsíců']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Střední hodnota'],
		['Y11_Deprindex', 'Mean', 'Střední hodnota'],
		['Y11_Q10_Partnerprefhours', '1--Work-less', 'Pracuje méně'],
		['Y11_Q10_Partnerprefhours', '2--Work-the-same', 'Pracuje stejně'],
		['Y11_Q10_Partnerprefhours', '3--Work-more', 'Pracuje více'],
		['Y11_Q12a', '1--Several-times-a-week', 'Několikrát týdně'],
		['Y11_Q12a', '2--Several-times-a-month', 'Několikrát měsíčně'],
		['Y11_Q12a', '3--Several-times-a-year', 'Několikrát ročně'],
		['Y11_Q12a', '4--Less-often-rarely', 'Méně často nebo zřídka'],
		['Y11_Q12a', '5--Never', 'Nikdy'],
		['Y11_Q12b', '1--Several-times-a-week', 'Několikrát týdně'],
		['Y11_Q12b', '2--Several-times-a-month', 'Několikrát měsíčně'],
		['Y11_Q12b', '3--Several-times-a-year', 'Několikrát ročně'],
		['Y11_Q12b', '4--Less-often-rarely', 'Méně často nebo zřídka'],
		['Y11_Q12b', '5--Never', 'Nikdy'],
		['Y11_Q12c', '1--Several-times-a-week', 'Několikrát týdně'],
		['Y11_Q12c', '2--Several-times-a-month', 'Několikrát měsíčně'],
		['Y11_Q12c', '3--Several-times-a-year', 'Několikrát ročně'],
		['Y11_Q12c', '4--Less-often-rarely', 'Méně často nebo zřídka'],
		['Y11_Q12c', '5--Never', 'Nikdy'],
		['Y11_Q13a', '1--Yes', 'Ano'],
		['Y11_Q13a', '2--No', 'Ne'],
		['Y11_Q13b', '1--Yes', 'Ano'],
		['Y11_Q13b', '2--No', 'Ne'],
		['Y11_Q13c', '1--Yes', 'Ano'],
		['Y11_Q13c', '2--No', 'Ne'],
		['Y11_Q15', '1--Very-likely', 'Velmi pravděpodobné'],
		['Y11_Q15', '2--Quite-likely', 'Spíše pravděpodobné'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Není to ani pravděpodobné, ani nepravděpodobné'],
		['Y11_Q15', '4--Quite-unlikely', 'Spíše nepravděpodobné'],
		['Y11_Q15', '5--Very-unlikely', 'Velmi nepravděpodobné'],
		['Y11_Q16', '1--Very-likely', 'Velmi pravděpodobné'],
		['Y11_Q16', '2--Quite-likely', 'Velice pravděpodobné'],
		['Y11_Q16', '3--Neither-likely-nor-unlikely', 'Není to ani pravděpodobné, ani nepravděpodobné'],
		['Y11_Q16', '4--Quite-unlikely', 'Spíše nepravděpodobné'],
		['Y11_Q16', '5--Very-unlikely', 'Velmi nepravděpodobné'],
		['Y11_Q18', '1--Own-without-mortgage', 'Vlastník bez hypotéky'],
		['Y11_Q18', '2--Own-with-mortgage', 'Vlastník s hypotékou'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Nájemník platící nájem v rámci sociálního bydlení nebo v obecním bytě'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Nájemník platící nájem soukromému vlastníkovi nemovitosti'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Ubytování/bydlení je poskytnuto zdarma, bez nutnosti platit nájem'],
		['Y11_Q18', '6--Other', 'Jiné'],
		['Y11_Q19a', '1--Yes', 'Ano'],
		['Y11_Q19a', '2--No', 'Ne'],
		['Y11_Q19b', '1--Yes', 'Ano'],
		['Y11_Q19b', '2--No', 'Ne'],
		['Y11_Q19c', '1--Yes', 'Ano'],
		['Y11_Q19c', '2--No', 'Ne'],
		['Y11_Q19d', '1--Yes', 'Ano'],
		['Y11_Q19d', '2--No', 'Ne'],
		['Y11_Q19e', '1--Yes', 'Ano'],
		['Y11_Q19e', '2--No', 'Ne'],
		['Y11_Q19f', '1--Yes', 'Ano'],
		['Y11_Q19f', '2--No', 'Ne'],
		['Y11_Q20', '1--Very-likely', 'Velmi pravděpodobné'],
		['Y11_Q20', '2--Quite-likely', 'Spíše pravděpodobné'],
		['Y11_Q20', '3--Quite-unlikely', 'Spíše nepravděpodobné'],
		['Y11_Q20', '4--Very-unlikely', 'Velmi nepravděpodobné'],
		['Y11_Q21a', '1--Every-day-or-almost-every-day', 'Denně nebo téměř denně'],
		['Y11_Q21a', '2--At-least-once-a-week', 'Alespoň jednou týdně'],
		['Y11_Q21a', '3--One-to-three-times-a-month', 'Jednou až třikrát měsíčně'],
		['Y11_Q21a', '4--Less-often', 'Méně často'],
		['Y11_Q21a', '5--Never', 'Nikdy'],
		['Y11_Q21b', '1--Every-day-or-almost-every-day', 'Denně nebo téměř denně'],
		['Y11_Q21b', '2--At-least-once-a-week', 'Alespoň jednou týdně'],
		['Y11_Q21b', '3--One-to-three-times-a-month', 'Jednou až třikrát měsíčně'],
		['Y11_Q21b', '4--Less-often', 'Méně často'],
		['Y11_Q21b', '5--Never', 'Nikdy'],
		['Y11_Q21c', '1--Every-day-or-almost-every-day', 'Denně nebo téměř denně'],
		['Y11_Q21c', '2--At-least-once-a-week', 'Alespoň jednou týdně'],
		['Y11_Q21c', '3--One-to-three-times-a-month', 'Jednou až třikrát měsíčně'],
		['Y11_Q21c', '4--Less-often', 'Méně často'],
		['Y11_Q21c', '5--Never', 'Nikdy'],
		['Y11_Q21d', '1--Every-day-or-almost-every-day', 'Denně nebo téměř denně'],
		['Y11_Q21d', '2--At-least-once-a-week', 'Alespoň jednou týdně'],
		['Y11_Q21d', '3--One-to-three-times-a-month', 'Jednou až třikrát měsíčně'],
		['Y11_Q21d', '4--Less-often', 'Méně často'],
		['Y11_Q21d', '5--Never', 'Nikdy'],
		['Y11_Q22_Volunteering', '1--Volunteers-regularly', 'Vykonává dobrovolnickou práci pravidelně '],
		['Y11_Q22_Volunteering', '2--Volunteers-occasionally', 'Vykonává dobrovolnickou práci příležitostně'],
		['Y11_Q22_Volunteering', '3--Does-not-volunteer', 'Nevykonává dobrovolnickou činnost'],
		['Y11_Q23a', '1--Yes', 'Ano'],
		['Y11_Q23a', '2--No', 'Ne'],
		['Y11_Q23b', '1--Yes', 'Ano'],
		['Y11_Q23b', '2--No', 'Ne'],
		['Y11_Q23c', '1--Yes', 'Ano'],
		['Y11_Q23c', '2--No', 'Ne'],
		['Y11_Q23d', '1--Yes', 'Ano'],
		['Y11_Q23d', '2--No', 'Ne'],
		['Y11_Q24', 'Mean', 'Střední hodnota'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Velké napětí'],
		['Y11_Q25a', '2--Some-tension', 'Malé napětí'],
		['Y11_Q25a', '3--No-tension', 'Žádné napětí'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Velké napětí'],
		['Y11_Q25b', '2--Some-tension', 'Malé napětí'],
		['Y11_Q25b', '3--No-tension', 'Žádné napětí'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Velké napětí'],
		['Y11_Q25c', '2--Some-tension', 'Malé napětí'],
		['Y11_Q25c', '3--No-tension', 'Žádné napětí'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Velké napětí'],
		['Y11_Q25d', '2--Some-tension', 'Malé napětí'],
		['Y11_Q25d', '3--No-tension', 'Žádné napětí'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Velké napětí'],
		['Y11_Q25e', '2--Some-tension', 'Malé napětí'],
		['Y11_Q25e', '3--No-tension', 'Žádné napětí'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Velké napětí'],
		['Y11_Q25f', '2--Some-tension', 'Malé napětí'],
		['Y11_Q25f', '3--No-tension', 'Žádné napětí'],
		['Y11_Q25g', '1--A-lot-of--tension', 'Velké napětí'],
		['Y11_Q25g', '2--Some-tension', 'Malé napětí'],
		['Y11_Q25g', '3--No-tension', 'Žádné napětí'],
		['Y11_Q28a', 'Mean', 'Střední hodnota'],
		['Y11_Q28b', 'Mean', 'Střední hodnota'],
		['Y11_Q28c', 'Mean', 'Střední hodnota'],
		['Y11_Q28d', 'Mean', 'Střední hodnota'],
		['Y11_Q28e', 'Mean', 'Střední hodnota'],
		['Y11_Q28f', 'Mean', 'Střední hodnota'],
		['Y11_Q29a', '1--Strongly-agree', 'Rozhodně souhlasím'],
		['Y11_Q29a', '2--Agree', 'Souhlasím'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Ani souhlas, ani nesouhlas'],
		['Y11_Q29a', '4--Disagree', 'Nesouhlasím'],
		['Y11_Q29a', '5--Strongly-disagree', 'Rozhodně nesouhlasím'],
		['Y11_Q29b', '1--Strongly-agree', 'Rozhodně souhlasím'],
		['Y11_Q29b', '2--Agree', 'Souhlasím'],
		['Y11_Q29b', '3--Neither-agree-nor-disagree', 'Ani souhlas, ani nesouhlas'],
		['Y11_Q29b', '4--Disagree', 'Nesouhlasím'],
		['Y11_Q29b', '5--Strongly-disagree', 'Rozhodně nesouhlasím'],
		['Y11_Q29c', '1--Strongly-agree', 'Rozhodně souhlasím'],
		['Y11_Q29c', '2--Agree', 'Souhlasím'],
		['Y11_Q29c', '3--Neither-agree-nor-disagree', 'Ani souhlas, ani nesouhlas'],
		['Y11_Q29c', '4--Disagree', 'Nesouhlasím'],
		['Y11_Q29c', '5--Strongly-disagree', 'Rozhodně nesouhlasím'],
		['Y11_Q29d', '1--Strongly-agree', 'Rozhodně souhlasím'],
		['Y11_Q29d', '2--Agree', 'Souhlasím'],
		['Y11_Q29d', '3--Neither-agree-nor-disagree', 'Ani souhlas, ani nesouhlas'],
		['Y11_Q29d', '4--Disagree', 'Nesouhlasím'],
		['Y11_Q29d', '5--Strongly-disagree', 'Rozhodně nesouhlasím'],
		['Y11_Q29e', '1--Strongly-agree', 'Rozhodně souhlasím'],
		['Y11_Q29e', '2--Agree', 'Souhlasím'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Ani souhlas, ani nesouhlas'],
		['Y11_Q29e', '4--Disagree', 'Nesouhlasím'],
		['Y11_Q29e', '5--Strongly-disagree', 'Rozhodně nesouhlasím'],
		['Y11_Q29f', '1--Strongly-agree', 'Rozhodně souhlasím'],
		['Y11_Q29f', '2--Agree', 'Souhlasím'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Ani souhlas, ani nesouhlas'],
		['Y11_Q29f', '4--Disagree', 'Nesouhlasím'],
		['Y11_Q29f', '5--Strongly-disagree', 'Rozhodně nesouhlasím'],
		['Y11_Q29g', '1--Strongly-agree', 'Rozhodně souhlasím'],
		['Y11_Q29g', '2--Agree', 'Souhlasím'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Ani souhlas, ani nesouhlas'],
		['Y11_Q29g', '4--Disagree', 'Nesouhlasím'],
		['Y11_Q29g', '5--Strongly-disagree', 'Rozhodně nesouhlasím'],
		['Y11_Q29h', '1--Strongly-agree', 'Rozhodně souhlasím'],
		['Y11_Q29h', '2--Agree', 'Souhlasím'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Ani souhlas, ani nesouhlas'],
		['Y11_Q29h', '4--Disagree', 'Nesouhlasím'],
		['Y11_Q29h', '5--Strongly-disagree', 'Rozhodně nesouhlasím'],
		['Y11_Q29i', '1--Strongly-agree', 'Rozhodně souhlasím'],
		['Y11_Q29i', '2--Agree', 'Souhlasím'],
		['Y11_Q29i', '3--Neither-agree-nor-disagree', 'Ani souhlas, ani nesouhlas'],
		['Y11_Q29i', '4--Disagree', 'Nesouhlasím'],
		['Y11_Q29i', '5--Strongly-disagree', 'Rozhodně nesouhlasím'],
		['Y11_Q30', 'Mean', 'Střední hodnota'],
		['Y11_Q33a', '1--Every-day-or-almost-every-day', 'Denně nebo téměř denně'],
		['Y11_Q33a', '2--At-least-once-a-week', 'Alespoň jednou týdně'],
		['Y11_Q33a', '3--One-to-three-times-a-month', 'Jednou až třikrát měsíčně'],
		['Y11_Q33a', '4--Less-often', 'Méně často'],
		['Y11_Q33a', '5--Never', 'Nikdy'],
		['Y11_Q33b', '1--Every-day-or-almost-every-day', 'Denně nebo téměř denně'],
		['Y11_Q33b', '2--At-least-once-a-week', 'Alespoň jednou týdně'],
		['Y11_Q33b', '3--One-to-three-times-a-month', 'Jednou až třikrát měsíčně'],
		['Y11_Q33b', '4--Less-often', 'Méně často'],
		['Y11_Q33b', '5--Never', 'Nikdy'],
		['Y11_Q33c', '1--Every-day-or-almost-every-day', 'Denně nebo téměř denně'],
		['Y11_Q33c', '2--At-least-once-a-week', 'Alespoň jednou týdně'],
		['Y11_Q33c', '3--One-to-three-times-a-month', 'Jednou až třikrát měsíčně'],
		['Y11_Q33c', '4--Less-often', 'Méně často'],
		['Y11_Q33c', '5--Never', 'Nikdy'],
		['Y11_Q33d', '1--Every-day-or-almost-every-day', 'Denně nebo téměř denně'],
		['Y11_Q33d', '2--At-least-once-a-week', 'Alespoň jednou týdně'],
		['Y11_Q33d', '3--One-to-three-times-a-month', 'Jednou až třikrát měsíčně'],
		['Y11_Q33d', '4--Less-often', 'Méně často'],
		['Y11_Q33d', '5--Never', 'Nikdy'],
		['Y11_Q34a', '1--Every-day-or-almost-every-day', 'Denně nebo téměř denně'],
		['Y11_Q34a', '2--At-least-once-a-week', 'Alespoň jednou týdně'],
		['Y11_Q34a', '3--One-to-three-times-a-month', 'Jednou až třikrát měsíčně'],
		['Y11_Q34a', '4--Less-often', 'Méně často'],
		['Y11_Q34a', '5--Never', 'Nikdy'],
		['Y11_Q34b', '1--Every-day-or-almost-every-day', 'Denně nebo téměř denně'],
		['Y11_Q34b', '2--At-least-once-a-week', 'Alespoň jednou týdně'],
		['Y11_Q34b', '3--One-to-three-times-a-month', 'Jednou až třikrát měsíčně'],
		['Y11_Q34b', '4--Less-often', 'Méně často'],
		['Y11_Q34b', '5--Never', 'Nikdy'],
		['Y11_Q34c', '1--Every-day-or-almost-every-day', 'Denně nebo téměř denně'],
		['Y11_Q34c', '2--At-least-once-a-week', 'Alespoň jednou týdně'],
		['Y11_Q34c', '3--One-to-three-times-a-month', 'Jednou až třikrát měsíčně'],
		['Y11_Q34c', '4--Less-often', 'Méně často'],
		['Y11_Q34c', '5--Never', 'Nikdy'],
		['Y11_Q34d', '1--Every-day-or-almost-every-day', 'Denně nebo téměř denně'],
		['Y11_Q34d', '2--At-least-once-a-week', 'Alespoň jednou týdně'],
		['Y11_Q34d', '3--One-to-three-times-a-month', 'Jednou až třikrát měsíčně'],
		['Y11_Q34d', '4--Less-often', 'Méně často'],
		['Y11_Q34d', '5--Never', 'Nikdy'],
		['Y11_Q35a', '1--A-member-of-your-family', 'Člen Vaší rodiny'],
		['Y11_Q35a', '2--A-friend--neighbour--or-someone-else', 'Přítel(kyně), soused(ka) nebo někdo jiný'],
		['Y11_Q35a', '3--A-service-provider--institution-or-organisation', 'Poskytovatel služeb, instituce nebo organizace'],
		['Y11_Q35a', '4--Nobody', 'Nikdo'],
		['Y11_Q35b', '1--A-member-of-your-family', 'Člen Vaší rodiny'],
		['Y11_Q35b', '2--A-friend--neighbour--or-someone-else', 'Přítel(kyně), soused(ka) nebo někdo jiný'],
		['Y11_Q35b', '3--A-service-provider--institution-or-organisation', 'Poskytovatel služeb, instituce nebo organizace'],
		['Y11_Q35b', '4--Nobody', 'Nikdo'],
		['Y11_Q35c', '1--A-member-of-your-family', 'Člen Vaší rodiny'],
		['Y11_Q35c', '2--A-friend--neighbour--or-someone-else', 'Přítel(kyně), soused(ka) nebo někdo jiný'],
		['Y11_Q35c', '3--A-service-provider--institution-or-organisation', 'Poskytovatel služeb, instituce nebo organizace'],
		['Y11_Q35c', '4--Nobody', 'Nikdo'],
		['Y11_Q35d', '1--A-member-of-your-family', 'Člen Vaší rodiny'],
		['Y11_Q35d', '2--A-friend--neighbour--or-someone-else', 'Přítel(kyně), soused(ka) nebo někdo jiný'],
		['Y11_Q35d', '3--A-service-provider--institution-or-organisation', 'Poskytovatel služeb, instituce nebo organizace'],
		['Y11_Q35d', '4--Nobody', 'Nikdo'],
		['Y11_Q35e', '1--A-member-of-your-family', 'Člen Vaší rodiny'],
		['Y11_Q35e', '2--A-friend--neighbour--or-someone-else', 'Přítel(kyně), soused(ka) nebo někdo jiný'],
		['Y11_Q35e', '3--A-service-provider--institution-or-organisation', 'Poskytovatel služeb, instituce nebo organizace'],
		['Y11_Q35e', '4--Nobody', 'Nikdo'],
		['Y11_Q36a', '1--Every-day', 'Každý den'],
		['Y11_Q36a', '2--Several-days-a-week', 'Několikrát týdně'],
		['Y11_Q36a', '3--Once-or-twice-a-week', 'Jednou nebo dvakrát týdně'],
		['Y11_Q36a', '4--Less-often', 'Méně často'],
		['Y11_Q36a', '5--Never', 'Nikdy'],
		['Y11_Q36b', '1--Every-day', 'Každý den'],
		['Y11_Q36b', '2--Several-days-a-week', 'Několikrát týdně'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'Jednou nebo dvakrát týdně'],
		['Y11_Q36b', '4--Less-often', 'Méně často'],
		['Y11_Q36b', '5--Never', 'Nikdy'],
		['Y11_Q36c', '1--Every-day', 'Každý den'],
		['Y11_Q36c', '2--Several-days-a-week', 'Několikrát týdně'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'Jednou nebo dvakrát týdně'],
		['Y11_Q36c', '4--Less-often', 'Méně často'],
		['Y11_Q36c', '5--Never', 'Nikdy'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Více než je spravedlivé'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Tak akorát'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Méně než je spravedlivé'],
		['Y11_Q39a', '1--Spend-more-time', 'Věnovat více času'],
		['Y11_Q39a', '2--As-much-as-I-currently-do', 'Stejně jako dosud'],
		['Y11_Q39a', '3--Spend-less-time', 'Věnovat méně času'],
		['Y11_Q39b', '1--Spend-more-time', 'Věnovat více času'],
		['Y11_Q39b', '2--As-much-as-I-currently-do', 'Stejně jako dosud'],
		['Y11_Q39b', '3--Spend-less-time', 'Věnovat méně času'],
		['Y11_Q39c', '1--Spend-more-time', 'Věnovat více času'],
		['Y11_Q39c', '2--As-much-as-I-currently-do', 'Stejně jako dosud'],
		['Y11_Q39c', '3--Spend-less-time', 'Věnovat méně času'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'V práci a doma'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'V práci nebo doma'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Malý nebo žádný stres'],
		['Y11_Q40a', 'Mean', 'Střední hodnota'],
		['Y11_Q40b', 'Mean', 'Střední hodnota'],
		['Y11_Q40c', 'Mean', 'Střední hodnota'],
		['Y11_Q40d', 'Mean', 'Střední hodnota'],
		['Y11_Q40e', 'Mean', 'Střední hodnota'],
		['Y11_Q40f', 'Mean', 'Střední hodnota'],
		['Y11_Q40g', 'Mean', 'Střední hodnota'],
		['Y11_Q40h', 'Mean', 'Střední hodnota'],
		['Y11_Q41', 'Mean', 'Střední hodnota'],
		['Y11_Q42', '1--Very-good', 'Velmi dobré'],
		['Y11_Q42', '2--Good', 'Dobré'],
		['Y11_Q42', '3--Fair', 'Ucházející'],
		['Y11_Q42', '4--Bad', 'Špatné'],
		['Y11_Q42', '5--Very-bad', 'Velmi špatné'],
		['Y11_Q46a', '1--All-of-the-time', 'Pořád'],
		['Y11_Q46a', '2--Most-of-the-time', 'Většinu času'],
		['Y11_Q46a', '3--More-than-half-of-the-time', 'Více než polovinu času'],
		['Y11_Q46a', '4--Less-than-half-of-the-time', 'Méně než polovinu času'],
		['Y11_Q46a', '5--Some-of-the-time', 'Někdy'],
		['Y11_Q46a', '6--At-no-time', 'Nikdy'],
		['Y11_Q46b', '1--All-of-the-time', 'Pořád'],
		['Y11_Q46b', '2--Most-of-the-time', 'Většinu času'],
		['Y11_Q46b', '3--More-than-half-of-the-time', 'Více než polovinu času'],
		['Y11_Q46b', '4--Less-than-half-of-the-time', 'Méně než polovinu času'],
		['Y11_Q46b', '5--Some-of-the-time', 'Někdy'],
		['Y11_Q46b', '6--At-no-time', 'Nikdy'],
		['Y11_Q46c', '1--All-of-the-time', 'Pořád'],
		['Y11_Q46c', '2--Most-of-the-time', 'Většinu času'],
		['Y11_Q46c', '3--More-than-half-of-the-time', 'Více než polovinu času'],
		['Y11_Q46c', '4--Less-than-half-of-the-time', 'Méně než polovinu času'],
		['Y11_Q46c', '5--Some-of-the-time', 'Někdy'],
		['Y11_Q46c', '6--At-no-time', 'Nikdy'],
		['Y11_Q46d_WHO5', 'Mean', 'Střední hodnota'],
		['Y11_Q47a', '1--Very-difficult', 'Velmi obtížné'],
		['Y11_Q47a', '2--A-little-difficult', 'Trochu obtížné'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Vůbec to není obtížné'],
		['Y11_Q47b', '1--Very-difficult', 'Velmi obtížné'],
		['Y11_Q47b', '2--A-little-difficult', 'Trochu obtížné'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Vůbec to není obtížné'],
		['Y11_Q47c', '1--Very-difficult', 'Velmi obtížné'],
		['Y11_Q47c', '2--A-little-difficult', 'Trochu obtížné'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Vůbec to není obtížné'],
		['Y11_Q47d', '1--Very-difficult', 'Velmi obtížné'],
		['Y11_Q47d', '2--A-little-difficult', 'Trochu obtížné'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Vůbec to není obtížné'],
		['Y11_Q47e', '1--Very-difficult', 'Velmi obtížné'],
		['Y11_Q47e', '2--A-little-difficult', 'Trochu obtížné'],
		['Y11_Q47e', '3--Not-difficult-at-all', 'Vůbec to není obtížné'],
		['Y11_Q50a', '1--Major-problems', 'Zásadní problémy'],
		['Y11_Q50a', '2--Moderate-problems', 'Mírné problémy'],
		['Y11_Q50a', '3--No-problems', 'Žádné problémy'],
		['Y11_Q50b', '1--Major-problems', 'Zásadní problémy'],
		['Y11_Q50b', '2--Moderate-problems', 'Mírné problémy'],
		['Y11_Q50b', '3--No-problems', 'Žádné problémy'],
		['Y11_Q50c', '1--Major-problems', 'Zásadní problémy'],
		['Y11_Q50c', '2--Moderate-problems', 'Mírné problémy'],
		['Y11_Q50c', '3--No-problems', 'Žádné problémy'],
		['Y11_Q50d', '1--Major-problems', 'Zásadní problémy'],
		['Y11_Q50d', '2--Moderate-problems', 'Mírné problémy'],
		['Y11_Q50d', '3--No-problems', 'Žádné problémy'],
		['Y11_Q50e', '1--Major-problems', 'Zásadní problémy'],
		['Y11_Q50e', '2--Moderate-problems', 'Mírné problémy'],
		['Y11_Q50e', '3--No-problems', 'Žádné problémy'],
		['Y11_Q50f', '1--Major-problems', 'Zásadní problémy'],
		['Y11_Q50f', '2--Moderate-problems', 'Mírné problémy'],
		['Y11_Q50f', '3--No-problems', 'Žádné problémy'],
		['Y11_Q51a', '1--with-great-difficulty', 'S velkými obtížemi'],
		['Y11_Q51a', '2--with-some-difficulty', 'S určitými obtížemi'],
		['Y11_Q51a', '3--easily', 'Snadno'],
		['Y11_Q51a', '4--very-easily', 'Velmi snadno'],
		['Y11_Q51b', '1--with-great-difficulty', 'S velkými obtížemi'],
		['Y11_Q51b', '2--with-some-difficulty', 'S určitými obtížemi'],
		['Y11_Q51b', '3--easily', 'Snadno'],
		['Y11_Q51b', '4--very-easily', 'Velmi snadno'],
		['Y11_Q51c', '1--with-great-difficulty', 'S velkými obtížemi'],
		['Y11_Q51c', '2--with-some-difficulty', 'S určitými obtížemi'],
		['Y11_Q51c', '3--easily', 'Snadno'],
		['Y11_Q51c', '4--very-easily', 'Velmi snadno'],
		['Y11_Q51d', '1--with-great-difficulty', 'S velkými obtížemi'],
		['Y11_Q51d', '2--with-some-difficulty', 'S určitými obtížemi'],
		['Y11_Q51d', '3--easily', 'Snadno'],
		['Y11_Q51d', '4--very-easily', 'Velmi snadno'],
		['Y11_Q51e', '1--with-great-difficulty', 'S velkými obtížemi'],
		['Y11_Q51e', '2--with-some-difficulty', 'S určitými obtížemi'],
		['Y11_Q51e', '3--easily', 'Snadno'],
		['Y11_Q51e', '4--very-easily', 'Velmi snadno'],
		['Y11_Q52', 'Mean', 'Střední hodnota'],
		['Y11_Q53a', 'Mean', 'Střední hodnota'],
		['Y11_Q53b', 'Mean', 'Střední hodnota'],
		['Y11_Q53c', 'Mean', 'Střední hodnota'],
		['Y11_Q53d', 'Mean', 'Střední hodnota'],
		['Y11_Q53e', 'Mean', 'Střední hodnota'],
		['Y11_Q53f', 'Mean', 'Střední hodnota'],
		['Y11_Q53g', 'Mean', 'Střední hodnota'],
		['Y11_Q57', '1--Much-worse', 'Mnohem horší'],
		['Y11_Q57', '2--Somewhat-worse', 'Poněkud horší'],
		['Y11_Q57', '3--Neither-worse-nor-better', 'Ani horší, ani lepší'],
		['Y11_Q57', '4--Somewhat-better', 'Poněkud lepší'],
		['Y11_Q57', '5--Much-better', 'Mnohem lepší'],
		['Y11_Q58', '1--With-great-difficulty', 'S velkými obtížemi'],
		['Y11_Q58', '2--With-difficulty', 'S obtížemi'],
		['Y11_Q58', '3--With-some-difficulty', 'S určitými obtížemi'],
		['Y11_Q58', '4--Fairly-easily', 'Poměrně snadno'],
		['Y11_Q58', '5--Easily', 'Snadno'],
		['Y11_Q58', '6--Very-easily', 'Velmi snadno'],
		['Y11_Q59a', '1--No', 'Ne'],
		['Y11_Q59a', '2--Yes', 'Ano'],
		['Y11_Q59b', '1--No', 'Ne'],
		['Y11_Q59b', '2--Yes', 'Ano'],
		['Y11_Q59c', '1--No', 'Ne'],
		['Y11_Q59c', '2--Yes', 'Ano'],
		['Y11_Q59d', '1--No', 'Ne'],
		['Y11_Q59d', '2--Yes', 'Ano'],
		['Y11_Q59e', '1--No', 'Ne'],
		['Y11_Q59e', '2--Yes', 'Ano'],
		['Y11_Q59f', '1--No', 'Ne'],
		['Y11_Q59f', '2--Yes', 'Ano'],
		['Y11_Q60a', '1--Yes', 'Ano'],
		['Y11_Q60a', '2--No', 'Ne'],
		['Y11_Q60b', '1--Yes', 'Ano'],
		['Y11_Q60b', '2--No', 'Ne'],
		['Y11_Q60c', '1--Yes', 'Ano'],
		['Y11_Q60c', '2--No', 'Ne'],
		['Y11_Q60d', '1--Yes', 'Ano'],
		['Y11_Q60d', '2--No', 'Ne'],
		['Y11_Q65', '1--Better', 'Lepší'],
		['Y11_Q65', '2--The-same', 'Stejná'],
		['Y11_Q65', '3--Worse', 'Horší'],
		['Y11_Q66', '1--Better', 'Lepší'],
		['Y11_Q66', '2--The-same', 'Stejná'],
		['Y11_Q66', '3--Worse', 'Horší'],
		['Y11_Q8_PreferredWorkingHours', '1--Work-less', 'Pracuje méně'],
		['Y11_Q8_PreferredWorkingHours', '2--Work-the-same', 'Pracuje stejně'],
		['Y11_Q8_PreferredWorkingHours', '3--Work-more', 'Pracuje více'],
		['Y11_SocExIndex', 'Mean', 'Střední hodnota']
	];
var country_
	 = [
	
		['AT', 'Rakousko'],
		['BE', 'Belgie'],
		['BG', 'Bulharsko'],
		['CY', 'Kypr'],
		['CZ', 'Česká republika'],
		['DE', 'Německo'],
		['DK', 'Dánsko'],
		['EE', 'Estonsko'],
		['EL', 'Řecko'],
		['ES', 'Španělsko'],
		['FI', 'Finsko'],
		['FR', 'Francie'],
		['HR', 'Chorvatsko'],
		['HU', 'Maďarsko'],
		['IE', 'Irsko'],
		['IS', 'Island'],
		['IT', 'Itálie'],
		['LT', 'Litva'],
		['LU', 'Lucembursko'],
		['LV', 'Lotyšsko'],
		['ME', 'Černá hora'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Nizozemsko'],
		['PL', 'Polsko'],
		['PT', 'Portugalsko'],
		['RO', 'Rumunsko'],
		['RS', 'Srbsko'],
		['SE', 'Švédsko'],
		['SI', 'Slovinsko'],
		['SK', 'Slovensko'],
		['TR', 'Turecko'],
		['UK', 'Spojené království'],
		['XK', 'Kosovo'],
		['EuropeanUnion', 'Evropská unie']
	];
var question_meta
	 = [
	
		['Y11_Accommproblems', 'Řada problémů s ubytováním', ''],
		['Y11_Q18', 'Vlastnictví domu/bytu', ''],
		['Y11_Q19a', 'Problémy s ubytováním/bydlením: nedostatek místa', ''],
		['Y11_Q19b', 'Problémy s ubytováním/bydlením: hniloba v oknech, dveřích nebo podlaze', ''],
		['Y11_Q19c', 'Problémy s ubytováním/bydlením: vlhkost / zatékání ve zdech nebo ve střeše', ''],
		['Y11_Q19d', 'Problémy s ubytováním/bydlením: bez splachovacího záchodu v domě/bytě', ''],
		['Y11_Q19e', 'Problémy s ubytováním/bydlením: chybějící vana nebo sprcha', ''],
		['Y11_Q19f', 'Problémy s ubytováním/bydlením: chybějící místo, kam byste se mohl(a) posadit ven', ''],
		['Y11_Q20', 'Jak je podle vás pravděpodobné nebo nepravděpodobné, že budete muset své ubytování/bydlení během následujících šesti měsíců opustit, protože si je už nadále nebudete moci dovolit?', ''],
		['Y11_Q50a', 'Problémy s hlukem v okolí', ''],
		['Y11_Q50b', 'Problémy s kvalitou ovzduší v okolí', ''],
		['Y11_Q50c', 'Problémy s kvalitou pitné vody v okolí', ''],
		['Y11_Q50d', 'Problémy se zločinem, násilím nebo vandalismem v okolí', ''],
		['Y11_Q50e', 'Problémy s nepořádkem nebo odpadky na ulici v okolí', ''],
		['Y11_Q50f', 'Problémy s dopravními zácpami v okolí', ''],
		['Y11_Q51a', 'Přístup k poštovním službám', ''],
		['Y11_Q51b', 'Přístup k bankovním službám', ''],
		['Y11_Q51c', 'Přístup k veřejné dopravě', ''],
		['Y11_Q51d', 'Přístup do kina, divadla nebo kulturního centra', ''],
		['Y11_Q51e', 'Přístup k rekreačním nebo zeleným plochám', ''],
		['Y11_Q52', 'Čas strávený na cestě do práce nebo do školy a zpět domů', ''],
		['Y11_Q24', 'Řekl(a) byste, že většině lidí lze důvěřovat, nebo že člověk nemůže být při jednání s lidmi nikdy dost opatrný?', ''],
		['Y11_Q25a', 'Vnímané napětí mezi chudými a bohatými lidmi', ''],
		['Y11_Q25b', 'Vnímané napětí mezi vedoucími pracovníky (managementem) a pracujícími', ''],
		['Y11_Q25c', 'Vnímané napětí mezi muži a ženami', ''],
		['Y11_Q25d', 'Vnímané napětí mezi starými a mladými lidmi', ''],
		['Y11_Q25e', 'Vnímané napětí mezi různými rasovými a etnickými skupinami', ''],
		['Y11_Q25f', 'Vnímané napětí mezi různými náboženskými skupinami', ''],
		['Y11_Q25g', 'Vnímané napětí mezi lidmi s rozdílnou sexuální orientací', ''],
		['Y11_Q28a', 'Důvěra v parlament', ''],
		['Y11_Q28b', 'Důvěra v právní systém', ''],
		['Y11_Q28c', 'Důvěra v tisk', ''],
		['Y11_Q28d', 'Důvěra v policii', ''],
		['Y11_Q28e', 'Důvěra ve vládu', ''],
		['Y11_Q28f', 'Důvěra v místní nebo městské úřady', ''],
		['Y11_Q33a', 'Osobní kontakt s dětmi, které žijí mimo Vaši domácnost', ''],
		['Y11_Q33b', 'Osobní kontakt s matkou nebo otcem, kteří žijí mimo Vaši domácnost', ''],
		['Y11_Q33c', 'Osobní kontakt s bratrem, sestrou nebo jiným příbuzným, kteří žijí mimo Vaši domácnost', ''],
		['Y11_Q33d', 'Osobní kontakt s přáteli nebo sousedy, kteří žijí mimo Vaši domácnost', ''],
		['Y11_Q34a', 'Kontakt s dětmi, které žijí mimo Vaši domácnost, po telefonu, přes internet nebo poštou', ''],
		['Y11_Q34b', 'Kontakt s matkou nebo otcem, kteří žijí mimo Vaši domácnost, po telefonu, přes internet nebo poštou', ''],
		['Y11_Q34c', 'Kontakt s bratrem, sestrou nebo jiným příbuzným, kteří žijí mimo Vaši domácnost, po telefonu, přes internet nebo poštou', ''],
		['Y11_Q34d', 'Kontakt s přáteli nebo sousedy žijícími mimo Vaši domácnost po telefonu, přes internet nebo poštou', ''],
		['Y11_Q35a', 'Od koho byste mohl(a) očekávat podporu, jestliže byste v době své nemoci potřeboval(a) doma pomoc?', ''],
		['Y11_Q35b', 'Od koho byste mohl(a) očekávat podporu, jestliže byste potřeboval(a) poradit v souvislosti s vážnou osobní nebo rodinnou záležitostí?', ''],
		['Y11_Q35c', 'Od koho byste mohl(a) očekávat podporu, kdybyste potřeboval(a) pomoc při hledání práce?', ''],
		['Y11_Q35d', 'Od koho byste mohl(a) očekávat podporu v případě, že byste se cítil(a) trochu v depresi a chtěl(a) si s někým popovídat?', ''],
		['Y11_Q35e', 'Od koho byste mohl(a) očekávat podporu, pokud byste v případě nějaké akutní potřeby potřeboval(a) pro řešení naléhavého případu sehnat částku 1 000 EUR?', ''],
		['Y11_Q21a', 'Návštěva bohoslužeb kromě svateb, pohřbů nebo křtin', ''],
		['Y11_Q21b', 'Používání internetu za jiným účelem než pro práci', ''],
		['Y11_Q21c', 'Sportování nebo cvičení', ''],
		['Y11_Q21d', 'Účast na společenských aktivitách klubu, organizace nebo asociace', ''],
		['Y11_Q22_Volunteering', 'Jak často jste v posledních 12 měsících vykonával(a) neplacenou dobrovolnickou práci?', ''],
		['Y11_Q23a', 'Navštívil(a) v posledních 12 měsících nějaké jednání odborové organizace, politické strany nebo politicky činné skupiny', ''],
		['Y11_Q23b', 'Zúčastnil(a) se v posledních 12 měsících nějaké protestní akce nebo demonstrace', ''],
		['Y11_Q23c', 'Podepsal(a) v posledních 12 měsících nějakou petici (i formou e-mailu nebo on-line)', ''],
		['Y11_Q23d', 'Kontaktoval(a) nějakého politika nebo veřejného činitele (nemyslíme běžný kontakt související s používáním veřejných služeb)', ''],
		['Y11_Q29e', 'Cítím se vyřazený(á) ze společnosti', ''],
		['Y11_Q29f', 'Život je dnes tak složitý, že se v něm jen stěží mohu orientovat', ''],
		['Y11_Q29g', 'Mám pocit, že to, co dělám, není ostatními doceněno', ''],
		['Y11_Q29h', 'Někteří lidé se na mě dívají spatra kvůli mému pracovnímu zařazení nebo příjmu', ''],
		['Y11_Q29i', 'Cítím se blízko lidem v oblasti, kde žiji', ''],
		['Y11_SocExIndex', 'Index sociálního vyloučení', ''],
		['Y11_Q29a', 'Jsem optimista, pokud jde o budoucnost', ''],
		['Y11_Q29b', 'Mám obecně pocit, že to, co dělám v životě, stojí za to', ''],
		['Y11_Q29c', 'Mám svobodu v rozhodování o tom, jak žít svůj život', ''],
		['Y11_Q29d', 'Ve svém každodenním životě mám zřídka čas dělat věci, které mne opravdu baví', ''],
		['Y11_Q30', 'Do jaké míry jste spokojený(á) se svým životem v dnešní době?', ''],
		['Y11_Q40a', 'Spokojenost se vzděláním', ''],
		['Y11_Q40b', 'Spokojenost se současným zaměstnáním', ''],
		['Y11_Q40c', 'Spokojenost se současnou životní úrovní', ''],
		['Y11_Q40d', 'Spokojenost s ubytováním/bydlením', ''],
		['Y11_Q40e', 'Spokojenost s rodinným životem', ''],
		['Y11_Q40f', 'Spokojenost se zdravím', ''],
		['Y11_Q40g', 'Spokojenost se společenským životem', ''],
		['Y11_Q40h', 'Spokojenost s ekonomickou situací v zemi', ''],
		['Y11_Q41', 'Když se vezmou všechny okolnosti, můžete prosím uvést, jak jste šťastný(á)?', ''],
		['Y11_Q8_PreferredWorkingHours', 'Kolik hodin týdně byste chtěl(a) pracovat? ', ''],
		['Y11_Q10_Partnerprefhours', 'Kolik hodin týdně byste chtěl(a), aby pracoval(a) Váš partner / Vaše partnerka?', 'Tato otázka byla položena těm respondentům, kteří měli partnera žijícího ve stejné domácnosti.'],
		['Y11_Q12a', 'Přišel(a) jsem z práce domů příliš unavený(á) na to, abych mohl(a) dělat domácí práce', ''],
		['Y11_Q12b', 'Vzhledem k množství času, které věnuji práci, pro mě bylo těžké plnit povinnosti vůči rodině', ''],
		['Y11_Q12c', 'Vzhledem k mým povinnostem v rodině bylo pro mě těžké se soustředit na práci', ''],
		['Y11_Q13a', 'Mám volnou pracovní dobu', ''],
		['Y11_Q13b', 'Mohu si napracovat hodiny za účelem pracovního volna', ''],
		['Y11_Q13c', 'Mohu si vzít narychlo volno, pokud potřebuji', ''],
		['Y11_Q15', 'S jakou pravděpodobností by se mohlo stát, že byste v průběhu následujících 6 měsíců přišel(a) o svou práci?', ''],
		['Y11_Q16', 'Kdybyste ztratil(a) práci, jak je pravděpodobné, že byste si našel/našla zaměstnání s podobným platem?', 'Tato otázka byla položena těm respondentům, kteří měli placené zaměstnání.'],
		['Y11_Q36a', 'Jak často se zabýváte péčí o své děti nebo vnoučata?', ''],
		['Y11_Q36b', 'Jak často se zabýváte vařením nebo domácími pracemi?', ''],
		['Y11_Q36c', 'Jak často se zabýváte péčí o staré nebo invalidní příbuzné?', ''],
		['Y11_Q38', 'Co si myslíte o svém podílu na domácích pracích?', ''],
		['Y11_Q39a', 'Postoj k času strávenému v kontaktu s rodinnými příslušníky', ''],
		['Y11_Q39b', 'Postoj k času strávenému s jinými lidmi', ''],
		['Y11_Q39c', 'Postoj k času strávenému s vlastními koníčky a zájmy', ''],
		['Y11_Q39d_stress', 'Stres z důvodu problémů v oblasti rovnováhy mezi pracovním a osobním životem', ''],
		['Y11_Q42', 'Vnímaný zdravotní stav', ''],
		['Y11_Q46a', 'Cítil(a) jsem se obzvláště napjatý/á', ''],
		['Y11_Q46b', 'Cítil()a jsem se osaměle', ''],
		['Y11_Q46c', 'Cítil(a) jsem se skleslý(á) a v depresi', ''],
		['Y11_Q46d_WHO5', 'Pětistupňová klasifikace duševní pohody podle WHO', ''],
		['Y11_Q47a', 'Problém s návštěvou lékaře z důvodu vzdálenosti ordinace nebo nemocnice', ''],
		['Y11_Q47b', 'Problém s návštěvou lékaře z důvodu dlouhé lhůty objednání', ''],
		['Y11_Q47c', 'Problém s návštěvou lékaře z důvodu doby strávené v čekárně čekáním na lékaře v den objednání', ''],
		['Y11_Q47d', 'Problém s návštěvou lékaře z důvodu ceny zaplacené za návštěvu lékaře', ''],
		['Y11_Q47e', 'Problém s návštěvou lékaře z důvodu potíže najít čas kvůli práci nebo pečovatelským povinnostem', ''],
		['Y11_Q53a', 'Jak byste hodnotil(a) kvalitu zdravotní péče ve Vaší zemi? ', ''],
		['Y11_Q53b', 'Jak byste hodnotil(a) kvalitu vzdělávacího systému ve Vaší zemi? ', ''],
		['Y11_Q53c', 'Jak byste hodnotil(a) kvalitu veřejné dopravy ve Vaší zemi? ', ''],
		['Y11_Q53d', 'Jak byste hodnotil(a) kvalitu péče o děti ve Vaší zemi? ', ''],
		['Y11_Q53e', 'Jak byste hodnotil(a) kvalitu služeb dlouhodobé péče ve Vaší zemi? ', ''],
		['Y11_Q53f', 'Jak byste hodnotil(a) kvalitu sociálních bytů ve Vaší zemi? ', ''],
		['Y11_Q53g', 'Jak byste hodnotil(a) kvalitu státního důchodového systému ve Vaší zemi? ', ''],
		['Y11_Deprindex', 'Index deprivace: Počet položek, které si domácnost nemůže dovolit', ''],
		['Y11_Q57', 'Finanční situace domácnosti ve srovnání s většinou lidí v zemi ', ''],
		['Y11_Q58', 'Je Vaše domácnost schopna vyjít s penězi?', ''],
		['Y11_Q59a', 'Můžete si dovolit udržovat v domácnosti přiměřené teplo?', ''],
		['Y11_Q59b', 'Můžete si dovolit zaplatit ročně za týden dovolené mimo domov?', ''],
		['Y11_Q59c', 'Můžete si dovolit vyměnit jakýkoliv opotřebovaný nábytek?', ''],
		['Y11_Q59d', 'Může si Vaše domácnost dovolit mít každý druhý den jídlo s masem, kuřetem nebo rybou, pokud byste je chtěl(a)?', ''],
		['Y11_Q59e', 'Mohou si členové Vaší domácnosti dovolit kupovat si spíše nové oblečení než obnošené oblečení (ze second‐handu)?', ''],
		['Y11_Q59f', 'Může si Vaše domácnost dovolit alespoň jednou za měsíc pozvat domů přátele nebo rodinu na nějaké pití nebo jídlo?', ''],
		['Y11_Q60a', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu s placením nájmu nebo hypotéky za bydlení?', ''],
		['Y11_Q60b', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu s placením účtů za elektřinu, vodu, plyn?', ''],
		['Y11_Q60c', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu se splácením spotřebitelských úvěrů?', ''],
		['Y11_Q60d', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu se splácením neformálních půjček?', ''],
		['Y11_Q65', 'Finanční situace domácnosti ve srovnání s její finanční situací před 12 měsíci', ''],
		['Y11_Q66', 'Očekávaná finanční situace za dalších 12 měsíců', '']
	];
