//Auto Generated file
var subset_
	 = [
	
		['Y11_Incomequartiles_percapita', 'Sissetulek'],
		['Y11_HH2a', 'Sugu'],
		['Y11_Agecategory', 'Vanus']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Kõik vanused'],
		['Y11_Agecategory', '1--18-24y', '18 - 24 aastat'],
		['Y11_Agecategory', '2--25-34y', '25 - 34 aastat'],
		['Y11_Agecategory', '3--35-49y', '35 - 49 aastat'],
		['Y11_Agecategory', '4--50-64y', '50 - 64 aastat'],
		['Y11_Agecategory', '5---64y', 'üle 64 aasta'],
		['Y11_HH2a', 'All', 'Mõlemad sood'],
		['Y11_HH2a', '1--Female', 'Naine'],
		['Y11_HH2a', '2--Male', 'Mees'],
		['Y11_Incomequartiles_percapita', 'All', 'Kõik sissetulekutasemed'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Kõige madalam'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'Teine'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'Kolmas'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Kõige kõrgem']
	];
var topic_
	 = [
	
		['', 'Kõik (127)'],
		['Elatustase ja vaesus', 'Elatustase ja vaesus (15)'],
		['Kodu ja kohalik keskkond', 'Kodu ja kohalik keskkond (21)'],
		['Pere- ja seltskondlik elu', 'Pere- ja seltskondlik elu (13)'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses (15)'],
		['Subjektiivne heaolu', 'Subjektiivne heaolu (14)'],
		['Tervishoiu- jms riiklikud teenused', 'Tervishoiu- jms riiklikud teenused (17)'],
		['Töö- ja eraelu tasakaal', 'Töö- ja eraelu tasakaal (18)'],
		['Ühiskonna kvaliteet', 'Ühiskonna kvaliteet (14)']
	];
var topic_question
	 = [
	
		['Elatustase ja vaesus', 'Y11_Deprindex', 'Ainelise puuduse indeks: nende asjade arv, mida leibkonnad ei saa endale lubada'],
		['Elatustase ja vaesus', 'Y11_Q57', 'Leibkonna rahaline seis võrreldes Eesti enamikuga'],
		['Elatustase ja vaesus', 'Y11_Q58', 'Kas teie leibkond saab olemasolevate vahenditega hakkama?'],
		['Elatustase ja vaesus', 'Y11_Q59a', 'Kas teie kodu kütmine on teile jõukohane?'],
		['Elatustase ja vaesus', 'Y11_Q59b', 'Kas teile on jõukohane minna kord aastas nädalaks puhkusele kodunt kaugele?'],
		['Elatustase ja vaesus', 'Y11_Q59c', 'Kas teile on jõukohane osta oma aja ära elanud mööbli asemel uut?'],
		['Elatustase ja vaesus', 'Y11_Q59d', 'Kas teile on jõukohane süüa soovi korral ülepäeviti loomaliha, kanaliha või kala?'],
		['Elatustase ja vaesus', 'Y11_Q59e', 'Kas teile on jõukohane osta uusi (mitte kasutatud) riideid?'],
		['Elatustase ja vaesus', 'Y11_Q59f', 'Kas teile on jõukohane võõrustada vähemalt kord kuus söögi või joogiga sõpru või lähedasi?'],
		['Elatustase ja vaesus', 'Y11_Q60a', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud üüri- või laenumaksete võlgnevusi?'],
		['Elatustase ja vaesus', 'Y11_Q60b', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud kommunaalteenuste maksete võlgnevusi?'],
		['Elatustase ja vaesus', 'Y11_Q60c', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud tarbimislaenumaksete võlgnevusi?'],
		['Elatustase ja vaesus', 'Y11_Q60d', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud mitteametlike laenumaksete võlgnevusi?'],
		['Elatustase ja vaesus', 'Y11_Q65', 'Leibkonna rahaline seis võrreldes 12 kuu taguse olukorraga'],
		['Elatustase ja vaesus', 'Y11_Q66', 'Järgneval 12 kuul eeldatav rahaline seis'],
		['Kodu ja kohalik keskkond', 'Y11_Accommproblems', 'Eluaseme probleemide arv'],
		['Kodu ja kohalik keskkond', 'Y11_Q18', 'Kodu omamine'],
		['Kodu ja kohalik keskkond', 'Y11_Q19a', 'Eluasemeprobleemid: ruumipuudus'],
		['Kodu ja kohalik keskkond', 'Y11_Q19b', 'Eluasemeprobleemid: pehkinud aknad, uksed või põrandad'],
		['Kodu ja kohalik keskkond', 'Y11_Q19c', 'Eluasemeprobleemid: niiskus/lekked seintes või katuses'],
		['Kodu ja kohalik keskkond', 'Y11_Q19d', 'Eluasemeprobleemid: puudub vesiklosett'],
		['Kodu ja kohalik keskkond', 'Y11_Q19e', 'Eluasemeprobleemid: puudub vann või dušš'],
		['Kodu ja kohalik keskkond', 'Y11_Q19f', 'Eluasemeprobleemid: puudub koht väljas istumiseks'],
		['Kodu ja kohalik keskkond', 'Y11_Q20', 'Kui tõenäoliseks peate vajadust lahkuda oma elukohast järgneva kuue kuu jooksul, kuna ei suuda enam selle eest maksta?'],
		['Kodu ja kohalik keskkond', 'Y11_Q50a', 'Probleemid müraga vahetus koduümbruses'],
		['Kodu ja kohalik keskkond', 'Y11_Q50b', 'Probleemid õhu kvaliteediga vahetus koduümbruses'],
		['Kodu ja kohalik keskkond', 'Y11_Q50c', 'Probleemid kraanivee kvaliteediga vahetus koduümbruses'],
		['Kodu ja kohalik keskkond', 'Y11_Q50d', 'Probleemid kuritegevuse, vägivalla või vandalismiga vahetus koduümbruses'],
		['Kodu ja kohalik keskkond', 'Y11_Q50e', 'Probleemid tänavatel vedeleva prügi või prahiga'],
		['Kodu ja kohalik keskkond', 'Y11_Q50f', 'Probleemid liiklusummikutega vahetus koduümbruses'],
		['Kodu ja kohalik keskkond', 'Y11_Q51a', 'Postiteenuste kättesaadavus'],
		['Kodu ja kohalik keskkond', 'Y11_Q51b', 'Pangateenuste kättesaadavus'],
		['Kodu ja kohalik keskkond', 'Y11_Q51c', 'Ühistransporditeenuste kättesaadavus'],
		['Kodu ja kohalik keskkond', 'Y11_Q51d', 'Kino, teatri või kultuurikeskuse olemasolu'],
		['Kodu ja kohalik keskkond', 'Y11_Q51e', 'Puhke- või haljasalade olemasolu'],
		['Kodu ja kohalik keskkond', 'Y11_Q52', 'Tööle või õpingutele minekuks ja tagasitulekuks kuluv aeg'],
		['Pere- ja seltskondlik elu', 'Y11_Q33a', 'Vahetu suhtlemine väljaspool leibkonda elavate lastega'],
		['Pere- ja seltskondlik elu', 'Y11_Q33b', 'Vahetu suhtlemine väljaspool leibkonda elava vanemaga'],
		['Pere- ja seltskondlik elu', 'Y11_Q33c', 'Vahetu suhtlemine muude väljaspool leibkonda elavate sugulastega'],
		['Pere- ja seltskondlik elu', 'Y11_Q33d', 'Vahetu suhtlemine sõprade või naabritega'],
		['Pere- ja seltskondlik elu', 'Y11_Q34a', 'Telefoni, interneti või posti teel suhtlemine väljaspool leibkonda elavate lastega'],
		['Pere- ja seltskondlik elu', 'Y11_Q34b', 'Telefoni, interneti või posti teel suhtlemine väljaspool leibkonda elava vanemaga'],
		['Pere- ja seltskondlik elu', 'Y11_Q34c', 'Telefoni, interneti või posti teel suhtlemine muude väljaspool leibkonda elavate sugulastega'],
		['Pere- ja seltskondlik elu', 'Y11_Q34d', 'Telefoni, interneti või posti teel suhtlemine sõprade või naabritega'],
		['Pere- ja seltskondlik elu', 'Y11_Q35a', 'Kellelt saaksite vajaduse korral haigena abi majapidamises?'],
		['Pere- ja seltskondlik elu', 'Y11_Q35b', 'Kellelt saaksite vajaduse korral nõu seoses mõne tõsise isikliku või perekondliku probleemiga?'],
		['Pere- ja seltskondlik elu', 'Y11_Q35c', 'Kellelt saaksite vajaduse korral abi töökoha leidmisel?'],
		['Pere- ja seltskondlik elu', 'Y11_Q35d', 'Kellelt saaksite abi, kui olete kerges masenduses?'],
		['Pere- ja seltskondlik elu', 'Y11_Q35e', 'Kellelt saaksite abi, kui vajate kiiresti 1000 eurot?'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q21a', 'Osalemine usutalitustel, v.a pulmad, matused ja ristimised'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q21b', 'Interneti kasutamine muul otstarbel kui tööks'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q21c', 'Spordi harrastamine vms füüsiline tegevus'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q21d', 'Osalemine klubide, seltside või ühingute tegevuses'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q22_Volunteering', 'Kui tihti olete viimase 12 kuu jooksul töötanud tasuta vabatahtlikuna?'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q23a', 'Osalemine ametiühingu, erakonna või kodanikualgatusrühma koosolekul viimase 12 kuu jooksul'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q23b', 'Osalemine protesti- või meeleavaldusel viimase 12 kuu jooksul'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q23c', 'Allakirjutamine petitsioonile viimase 12 kuu jooksul'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q23d', 'Poliitiku või ametniku poole pöördumine (v.a seoses tavapäraste riiklike teenustega)'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q29e', 'Tunnen end sotsiaalselt tõrjutuna'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q29f', 'Tänapäeva elu on läinud nii keeruliseks, et mul on juba raske toime tulla'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q29g', 'Mul on tunne, et teised ei väärtusta mind'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q29h', 'Mõnikord halvustatakse mind mu tööalase olukorra või sissetuleku tõttu'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q29i', 'Tunnen lähedust oma kodukandi inimestega'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_SocExIndex', 'Sotsiaalse tõrjutuse indeks'],
		['Subjektiivne heaolu', 'Y11_Q29a', 'Olen tuleviku suhtes optimistlik'],
		['Subjektiivne heaolu', 'Y11_Q29b', 'Tunnen üldiselt, et sellel, mida ma teen, on väärtus'],
		['Subjektiivne heaolu', 'Y11_Q29c', 'Tunnen, et saan oma elu üle ise otsustada'],
		['Subjektiivne heaolu', 'Y11_Q29d', 'Oma igapäevaelus on mul harva aega teha asju, mida ma tõeliselt naudin'],
		['Subjektiivne heaolu', 'Y11_Q30', 'Kui rahul olete oma eluga praegu?'],
		['Subjektiivne heaolu', 'Y11_Q40a', 'Rahulolu haridusega'],
		['Subjektiivne heaolu', 'Y11_Q40b', 'Rahulolu praeguse tööga'],
		['Subjektiivne heaolu', 'Y11_Q40c', 'Rahulolu praeguse elatustasemega'],
		['Subjektiivne heaolu', 'Y11_Q40d', 'Rahulolu eluasemega'],
		['Subjektiivne heaolu', 'Y11_Q40e', 'Rahulolu pereeluga'],
		['Subjektiivne heaolu', 'Y11_Q40f', 'Rahulolu tervisega'],
		['Subjektiivne heaolu', 'Y11_Q40g', 'Rahulolu seltskondliku eluga'],
		['Subjektiivne heaolu', 'Y11_Q40h', 'Rahulolu Eesti majandusliku olukorraga'],
		['Subjektiivne heaolu', 'Y11_Q41', 'Kõike arvesse võttes, kui rahul te oma eluga olete?'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q42', 'Terviseseisund enda hinnangul'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q46a', 'Olen tundnud end eriti pinges'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q46b', 'Olen tundnud end üksikuna'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q46c', 'Olen tundnud masendust'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q46d_WHO5', 'WHO-5 vaimse heaolu skaala'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q47a', 'Raskused arsti juurde pääsemisel kauguse tõttu'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q47b', 'Raskused arsti juurde pääsemisel viivituse tõttu arsti vastuvõtule pääsemisel'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q47c', 'Raskused arsti juurde pääsemisel ooteaja tõttu arsti vastuvõtule visiidi päeval'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q47d', 'Raskused arsti juurde pääsemisel kulude tõttu'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q47e', 'Raskused arsti juurde pääsemisel ajapuuduse tõttu'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q53a', 'Milliseks hindaksite tervishoiuteenuste kvaliteedi Eestis?'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q53b', 'Milliseks hindaksite haridussüsteemi kvaliteedi Eestis?'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q53c', 'Milliseks hindaksite ühistranspordi kvaliteedi Eestis?'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q53d', 'Milliseks hindaksite lastehoiuteenuste kvaliteedi Eestis?'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q53e', 'Milliseks hindaksite pikaajaliste hooldusteenuste kvaliteedi Eestis?'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q53f', 'Milliseks hindaksite sotsiaaleluasemeteenuste kvaliteedi Eestis?'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q53g', 'Milliseks hindaksite riikliku pensionisüsteemi kvaliteedi Eestis?'],
		['Töö- ja eraelu tasakaal', 'Y11_Q8_PreferredWorkingHours', 'Mitu tundi nädalas eelistaksite tööd teha?'],
		['Töö- ja eraelu tasakaal', 'Y11_Q10_Partnerprefhours', 'Kui see oleks teie otsustada, siis mitu tundi peaks teie elukaaslane nädalas töötama?'],
		['Töö- ja eraelu tasakaal', 'Y11_Q12a', 'Olen töölt koju tulles olnud majapidamistööde tegemiseks liiga väsinud'],
		['Töö- ja eraelu tasakaal', 'Y11_Q12b', 'Mul on olnud raske täita oma perekondlikke kohustusi tööl oldud aja tõttu '],
		['Töö- ja eraelu tasakaal', 'Y11_Q12c', 'Mul on olnud perekondlike kohustuste tõttu raske tööle keskenduda'],
		['Töö- ja eraelu tasakaal', 'Y11_Q13a', 'Saan oma tööpäeva alguse ja lõpu üle ise otsustada'],
		['Töö- ja eraelu tasakaal', 'Y11_Q13b', 'Ületundide eest saan vaba aega'],
		['Töö- ja eraelu tasakaal', 'Y11_Q13c', 'Vajaduse korral saan võtta lühikese etteteatamisajaga vaba päeva '],
		['Töö- ja eraelu tasakaal', 'Y11_Q15', 'Kui tõenäoliseks peate oma töökoha kaotamist järgmise kuue kuu jooksul?'],
		['Töö- ja eraelu tasakaal', 'Y11_Q16', 'Kui kaotaksite praegu oma töö, siis kui tõenäoliseks peate sarnase palgatasemega töökoha leidmist?'],
		['Töö- ja eraelu tasakaal', 'Y11_Q36a', 'Kui sageli olete hõivatud oma laste või lapselaste eest hoolitsemisega?'],
		['Töö- ja eraelu tasakaal', 'Y11_Q36b', 'Kui sageli olete hõivatud toidu valmistamise või majapidamistöödega?'],
		['Töö- ja eraelu tasakaal', 'Y11_Q36c', 'Kui sageli olete hõivatud eakate või puudega sugulaste eest hoolitsemisega?'],
		['Töö- ja eraelu tasakaal', 'Y11_Q38', 'Suhtumine majapidamistööde jaotusse'],
		['Töö- ja eraelu tasakaal', 'Y11_Q39a', 'Suhtumine pereliikmetega veedetud aega'],
		['Töö- ja eraelu tasakaal', 'Y11_Q39b', 'Suhtumine teistega veedetud aega'],
		['Töö- ja eraelu tasakaal', 'Y11_Q39c', 'Suhtumine hobide ja huvialadega veedetud aega'],
		['Töö- ja eraelu tasakaal', 'Y11_Q39d_stress', 'Stress'],
		['Ühiskonna kvaliteet', 'Y11_Q24', 'Kas te peate ennast väga usaldavaks või väga umbusklikuks?'],
		['Ühiskonna kvaliteet', 'Y11_Q25a', 'Hinnang vaeste ja rikaste vahelisele lõhele'],
		['Ühiskonna kvaliteet', 'Y11_Q25b', 'Hinnang juhtkonna ja töötajate vahelisele lõhele'],
		['Ühiskonna kvaliteet', 'Y11_Q25c', 'Hinnang meeste ja naiste vahelisele lõhele'],
		['Ühiskonna kvaliteet', 'Y11_Q25d', 'Hinnang põlvkondadevahelisele lõhele'],
		['Ühiskonna kvaliteet', 'Y11_Q25e', 'Hinnang rahvustevahelisele lõhele'],
		['Ühiskonna kvaliteet', 'Y11_Q25f', 'Hinnang usugruppidevahelisele lõhele'],
		['Ühiskonna kvaliteet', 'Y11_Q25g', 'Hinnang eri seksuaalse sättumusegas inimeste vahelisele lõhele'],
		['Ühiskonna kvaliteet', 'Y11_Q28a', 'Riigikogu usaldamine'],
		['Ühiskonna kvaliteet', 'Y11_Q28b', 'Õigussüsteemi usaldamine'],
		['Ühiskonna kvaliteet', 'Y11_Q28c', 'Kirjutava ajakirjanduse usaldamine'],
		['Ühiskonna kvaliteet', 'Y11_Q28d', 'Politsei usaldamine'],
		['Ühiskonna kvaliteet', 'Y11_Q28e', 'Valitsuse usaldamine'],
		['Ühiskonna kvaliteet', 'Y11_Q28f', 'Kohaliku omavalitsuse usaldamine']
	];
var question_
	 = [
	
		['Y11_Deprindex', 'Ainelise puuduse indeks: nende asjade arv, mida leibkonnad ei saa endale lubada'],
		['Y11_Q57', 'Leibkonna rahaline seis võrreldes Eesti enamikuga'],
		['Y11_Q58', 'Kas teie leibkond saab olemasolevate vahenditega hakkama?'],
		['Y11_Q59a', 'Kas teie kodu kütmine on teile jõukohane?'],
		['Y11_Q59b', 'Kas teile on jõukohane minna kord aastas nädalaks puhkusele kodunt kaugele?'],
		['Y11_Q59c', 'Kas teile on jõukohane osta oma aja ära elanud mööbli asemel uut?'],
		['Y11_Q59d', 'Kas teile on jõukohane süüa soovi korral ülepäeviti loomaliha, kanaliha või kala?'],
		['Y11_Q59e', 'Kas teile on jõukohane osta uusi (mitte kasutatud) riideid?'],
		['Y11_Q59f', 'Kas teile on jõukohane võõrustada vähemalt kord kuus söögi või joogiga sõpru või lähedasi?'],
		['Y11_Q60a', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud üüri- või laenumaksete võlgnevusi?'],
		['Y11_Q60b', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud kommunaalteenuste maksete võlgnevusi?'],
		['Y11_Q60c', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud tarbimislaenumaksete võlgnevusi?'],
		['Y11_Q60d', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud mitteametlike laenumaksete võlgnevusi?'],
		['Y11_Q65', 'Leibkonna rahaline seis võrreldes 12 kuu taguse olukorraga'],
		['Y11_Q66', 'Järgneval 12 kuul eeldatav rahaline seis'],
		['Y11_Accommproblems', 'Eluaseme probleemide arv'],
		['Y11_Q18', 'Kodu omamine'],
		['Y11_Q19a', 'Eluasemeprobleemid: ruumipuudus'],
		['Y11_Q19b', 'Eluasemeprobleemid: pehkinud aknad, uksed või põrandad'],
		['Y11_Q19c', 'Eluasemeprobleemid: niiskus/lekked seintes või katuses'],
		['Y11_Q19d', 'Eluasemeprobleemid: puudub vesiklosett'],
		['Y11_Q19e', 'Eluasemeprobleemid: puudub vann või dušš'],
		['Y11_Q19f', 'Eluasemeprobleemid: puudub koht väljas istumiseks'],
		['Y11_Q20', 'Kui tõenäoliseks peate vajadust lahkuda oma elukohast järgneva kuue kuu jooksul, kuna ei suuda enam selle eest maksta?'],
		['Y11_Q50a', 'Probleemid müraga vahetus koduümbruses'],
		['Y11_Q50b', 'Probleemid õhu kvaliteediga vahetus koduümbruses'],
		['Y11_Q50c', 'Probleemid kraanivee kvaliteediga vahetus koduümbruses'],
		['Y11_Q50d', 'Probleemid kuritegevuse, vägivalla või vandalismiga vahetus koduümbruses'],
		['Y11_Q50e', 'Probleemid tänavatel vedeleva prügi või prahiga'],
		['Y11_Q50f', 'Probleemid liiklusummikutega vahetus koduümbruses'],
		['Y11_Q51a', 'Postiteenuste kättesaadavus'],
		['Y11_Q51b', 'Pangateenuste kättesaadavus'],
		['Y11_Q51c', 'Ühistransporditeenuste kättesaadavus'],
		['Y11_Q51d', 'Kino, teatri või kultuurikeskuse olemasolu'],
		['Y11_Q51e', 'Puhke- või haljasalade olemasolu'],
		['Y11_Q52', 'Tööle või õpingutele minekuks ja tagasitulekuks kuluv aeg'],
		['Y11_Q33a', 'Vahetu suhtlemine väljaspool leibkonda elavate lastega'],
		['Y11_Q33b', 'Vahetu suhtlemine väljaspool leibkonda elava vanemaga'],
		['Y11_Q33c', 'Vahetu suhtlemine muude väljaspool leibkonda elavate sugulastega'],
		['Y11_Q33d', 'Vahetu suhtlemine sõprade või naabritega'],
		['Y11_Q34a', 'Telefoni, interneti või posti teel suhtlemine väljaspool leibkonda elavate lastega'],
		['Y11_Q34b', 'Telefoni, interneti või posti teel suhtlemine väljaspool leibkonda elava vanemaga'],
		['Y11_Q34c', 'Telefoni, interneti või posti teel suhtlemine muude väljaspool leibkonda elavate sugulastega'],
		['Y11_Q34d', 'Telefoni, interneti või posti teel suhtlemine sõprade või naabritega'],
		['Y11_Q35a', 'Kellelt saaksite vajaduse korral haigena abi majapidamises?'],
		['Y11_Q35b', 'Kellelt saaksite vajaduse korral nõu seoses mõne tõsise isikliku või perekondliku probleemiga?'],
		['Y11_Q35c', 'Kellelt saaksite vajaduse korral abi töökoha leidmisel?'],
		['Y11_Q35d', 'Kellelt saaksite abi, kui olete kerges masenduses?'],
		['Y11_Q35e', 'Kellelt saaksite abi, kui vajate kiiresti 1000 eurot?'],
		['Y11_Q21a', 'Osalemine usutalitustel, v.a pulmad, matused ja ristimised'],
		['Y11_Q21b', 'Interneti kasutamine muul otstarbel kui tööks'],
		['Y11_Q21c', 'Spordi harrastamine vms füüsiline tegevus'],
		['Y11_Q21d', 'Osalemine klubide, seltside või ühingute tegevuses'],
		['Y11_Q22_Volunteering', 'Kui tihti olete viimase 12 kuu jooksul töötanud tasuta vabatahtlikuna?'],
		['Y11_Q23a', 'Osalemine ametiühingu, erakonna või kodanikualgatusrühma koosolekul viimase 12 kuu jooksul'],
		['Y11_Q23b', 'Osalemine protesti- või meeleavaldusel viimase 12 kuu jooksul'],
		['Y11_Q23c', 'Allakirjutamine petitsioonile viimase 12 kuu jooksul'],
		['Y11_Q23d', 'Poliitiku või ametniku poole pöördumine (v.a seoses tavapäraste riiklike teenustega)'],
		['Y11_Q29e', 'Tunnen end sotsiaalselt tõrjutuna'],
		['Y11_Q29f', 'Tänapäeva elu on läinud nii keeruliseks, et mul on juba raske toime tulla'],
		['Y11_Q29g', 'Mul on tunne, et teised ei väärtusta mind'],
		['Y11_Q29h', 'Mõnikord halvustatakse mind mu tööalase olukorra või sissetuleku tõttu'],
		['Y11_Q29i', 'Tunnen lähedust oma kodukandi inimestega'],
		['Y11_SocExIndex', 'Sotsiaalse tõrjutuse indeks'],
		['Y11_Q29a', 'Olen tuleviku suhtes optimistlik'],
		['Y11_Q29b', 'Tunnen üldiselt, et sellel, mida ma teen, on väärtus'],
		['Y11_Q29c', 'Tunnen, et saan oma elu üle ise otsustada'],
		['Y11_Q29d', 'Oma igapäevaelus on mul harva aega teha asju, mida ma tõeliselt naudin'],
		['Y11_Q30', 'Kui rahul olete oma eluga praegu?'],
		['Y11_Q40a', 'Rahulolu haridusega'],
		['Y11_Q40b', 'Rahulolu praeguse tööga'],
		['Y11_Q40c', 'Rahulolu praeguse elatustasemega'],
		['Y11_Q40d', 'Rahulolu eluasemega'],
		['Y11_Q40e', 'Rahulolu pereeluga'],
		['Y11_Q40f', 'Rahulolu tervisega'],
		['Y11_Q40g', 'Rahulolu seltskondliku eluga'],
		['Y11_Q40h', 'Rahulolu Eesti majandusliku olukorraga'],
		['Y11_Q41', 'Kõike arvesse võttes, kui rahul te oma eluga olete?'],
		['Y11_Q42', 'Terviseseisund enda hinnangul'],
		['Y11_Q46a', 'Olen tundnud end eriti pinges'],
		['Y11_Q46b', 'Olen tundnud end üksikuna'],
		['Y11_Q46c', 'Olen tundnud masendust'],
		['Y11_Q46d_WHO5', 'WHO-5 vaimse heaolu skaala'],
		['Y11_Q47a', 'Raskused arsti juurde pääsemisel kauguse tõttu'],
		['Y11_Q47b', 'Raskused arsti juurde pääsemisel viivituse tõttu arsti vastuvõtule pääsemisel'],
		['Y11_Q47c', 'Raskused arsti juurde pääsemisel ooteaja tõttu arsti vastuvõtule visiidi päeval'],
		['Y11_Q47d', 'Raskused arsti juurde pääsemisel kulude tõttu'],
		['Y11_Q47e', 'Raskused arsti juurde pääsemisel ajapuuduse tõttu'],
		['Y11_Q53a', 'Milliseks hindaksite tervishoiuteenuste kvaliteedi Eestis?'],
		['Y11_Q53b', 'Milliseks hindaksite haridussüsteemi kvaliteedi Eestis?'],
		['Y11_Q53c', 'Milliseks hindaksite ühistranspordi kvaliteedi Eestis?'],
		['Y11_Q53d', 'Milliseks hindaksite lastehoiuteenuste kvaliteedi Eestis?'],
		['Y11_Q53e', 'Milliseks hindaksite pikaajaliste hooldusteenuste kvaliteedi Eestis?'],
		['Y11_Q53f', 'Milliseks hindaksite sotsiaaleluasemeteenuste kvaliteedi Eestis?'],
		['Y11_Q53g', 'Milliseks hindaksite riikliku pensionisüsteemi kvaliteedi Eestis?'],
		['Y11_Q8_PreferredWorkingHours', 'Mitu tundi nädalas eelistaksite tööd teha?'],
		['Y11_Q10_Partnerprefhours', 'Kui see oleks teie otsustada, siis mitu tundi peaks teie elukaaslane nädalas töötama?'],
		['Y11_Q12a', 'Olen töölt koju tulles olnud majapidamistööde tegemiseks liiga väsinud'],
		['Y11_Q12b', 'Mul on olnud raske täita oma perekondlikke kohustusi tööl oldud aja tõttu '],
		['Y11_Q12c', 'Mul on olnud perekondlike kohustuste tõttu raske tööle keskenduda'],
		['Y11_Q13a', 'Saan oma tööpäeva alguse ja lõpu üle ise otsustada'],
		['Y11_Q13b', 'Ületundide eest saan vaba aega'],
		['Y11_Q13c', 'Vajaduse korral saan võtta lühikese etteteatamisajaga vaba päeva '],
		['Y11_Q15', 'Kui tõenäoliseks peate oma töökoha kaotamist järgmise kuue kuu jooksul?'],
		['Y11_Q16', 'Kui kaotaksite praegu oma töö, siis kui tõenäoliseks peate sarnase palgatasemega töökoha leidmist?'],
		['Y11_Q36a', 'Kui sageli olete hõivatud oma laste või lapselaste eest hoolitsemisega?'],
		['Y11_Q36b', 'Kui sageli olete hõivatud toidu valmistamise või majapidamistöödega?'],
		['Y11_Q36c', 'Kui sageli olete hõivatud eakate või puudega sugulaste eest hoolitsemisega?'],
		['Y11_Q38', 'Suhtumine majapidamistööde jaotusse'],
		['Y11_Q39a', 'Suhtumine pereliikmetega veedetud aega'],
		['Y11_Q39b', 'Suhtumine teistega veedetud aega'],
		['Y11_Q39c', 'Suhtumine hobide ja huvialadega veedetud aega'],
		['Y11_Q39d_stress', 'Stress'],
		['Y11_Q24', 'Kas te peate ennast väga usaldavaks või väga umbusklikuks?'],
		['Y11_Q25a', 'Hinnang vaeste ja rikaste vahelisele lõhele'],
		['Y11_Q25b', 'Hinnang juhtkonna ja töötajate vahelisele lõhele'],
		['Y11_Q25c', 'Hinnang meeste ja naiste vahelisele lõhele'],
		['Y11_Q25d', 'Hinnang põlvkondadevahelisele lõhele'],
		['Y11_Q25e', 'Hinnang rahvustevahelisele lõhele'],
		['Y11_Q25f', 'Hinnang usugruppidevahelisele lõhele'],
		['Y11_Q25g', 'Hinnang eri seksuaalse sättumusegas inimeste vahelisele lõhele'],
		['Y11_Q28a', 'Riigikogu usaldamine'],
		['Y11_Q28b', 'Õigussüsteemi usaldamine'],
		['Y11_Q28c', 'Kirjutava ajakirjanduse usaldamine'],
		['Y11_Q28d', 'Politsei usaldamine'],
		['Y11_Q28e', 'Valitsuse usaldamine'],
		['Y11_Q28f', 'Kohaliku omavalitsuse usaldamine']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Keskmine'],
		['Y11_Deprindex', 'Mean', 'Keskmine'],
		['Y11_Q10_Partnerprefhours', '1--Work-less', 'Vähem'],
		['Y11_Q10_Partnerprefhours', '2--Work-the-same', 'Sama palju'],
		['Y11_Q10_Partnerprefhours', '3--Work-more', 'Rohkem'],
		['Y11_Q12a', '1--Several-times-a-week', 'Mitu korda nädalas'],
		['Y11_Q12a', '2--Several-times-a-month', 'Mitu korda kuus'],
		['Y11_Q12a', '3--Several-times-a-year', 'Mitu korda aastas'],
		['Y11_Q12a', '4--Less-often-rarely', 'Harva'],
		['Y11_Q12a', '5--Never', 'Mitte kunagi'],
		['Y11_Q12b', '1--Several-times-a-week', 'Mitu korda nädalas'],
		['Y11_Q12b', '2--Several-times-a-month', 'Mitu korda kuus'],
		['Y11_Q12b', '3--Several-times-a-year', 'Mitu korda aastas'],
		['Y11_Q12b', '4--Less-often-rarely', 'Harva'],
		['Y11_Q12b', '5--Never', 'Mitte kunagi'],
		['Y11_Q12c', '1--Several-times-a-week', 'Mitu korda nädalas'],
		['Y11_Q12c', '2--Several-times-a-month', 'Mitu korda kuus'],
		['Y11_Q12c', '3--Several-times-a-year', 'Mitu korda aastas'],
		['Y11_Q12c', '4--Less-often-rarely', 'Harva'],
		['Y11_Q12c', '5--Never', 'Mitte kunagi'],
		['Y11_Q13a', '1--Yes', 'Jah'],
		['Y11_Q13a', '2--No', 'Ei'],
		['Y11_Q13b', '1--Yes', 'Jah'],
		['Y11_Q13b', '2--No', 'Ei'],
		['Y11_Q13c', '1--Yes', 'Jah'],
		['Y11_Q13c', '2--No', 'Ei'],
		['Y11_Q15', '1--Very-likely', 'Väga tõenäoliseks'],
		['Y11_Q15', '2--Quite-likely', 'Üsna tõenäoliseks'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Ei oska öelda'],
		['Y11_Q15', '4--Quite-unlikely', 'Üsna ebatõenäoliseks'],
		['Y11_Q15', '5--Very-unlikely', 'Väga ebatõenäoliseks'],
		['Y11_Q16', '1--Very-likely', 'Väga tõenäoliseks'],
		['Y11_Q16', '2--Quite-likely', 'Üsna töenäoliselt'],
		['Y11_Q16', '3--Neither-likely-nor-unlikely', 'Ei oska öelda'],
		['Y11_Q16', '4--Quite-unlikely', 'Üsna ebatõenäoliseks'],
		['Y11_Q16', '5--Very-unlikely', 'Väga ebatõenäoliseks'],
		['Y11_Q18', '1--Own-without-mortgage', 'Kuulub mulle ilma hüpoteegita'],
		['Y11_Q18', '2--Own-with-mortgage', 'Kuulub mulle koos hüpoteegiga'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Olen üürnik, maksan sotsiaal‐/munitsipaaleluruumi eest üüri'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Olen üürnik, maksan üüri eraisikule'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Kasutan eluaset ilma üürita '],
		['Y11_Q18', '6--Other', 'Muu'],
		['Y11_Q19a', '1--Yes', 'Jah'],
		['Y11_Q19a', '2--No', 'Ei'],
		['Y11_Q19b', '1--Yes', 'Jah'],
		['Y11_Q19b', '2--No', 'Ei'],
		['Y11_Q19c', '1--Yes', 'Jah'],
		['Y11_Q19c', '2--No', 'Ei'],
		['Y11_Q19d', '1--Yes', 'Jah'],
		['Y11_Q19d', '2--No', 'Ei'],
		['Y11_Q19e', '1--Yes', 'Jah'],
		['Y11_Q19e', '2--No', 'Ei'],
		['Y11_Q19f', '1--Yes', 'Jah'],
		['Y11_Q19f', '2--No', 'Ei'],
		['Y11_Q20', '1--Very-likely', 'Väga tõenäoliseks'],
		['Y11_Q20', '2--Quite-likely', 'Üsna tõenäoliseks'],
		['Y11_Q20', '3--Quite-unlikely', 'Üsna ebatõenäoliseks'],
		['Y11_Q20', '4--Very-unlikely', 'Väga ebatõenäoliseks'],
		['Y11_Q21a', '1--Every-day-or-almost-every-day', 'Iga päev või peaaegu iga päev'],
		['Y11_Q21a', '2--At-least-once-a-week', 'Vähemalt kord nädalas'],
		['Y11_Q21a', '3--One-to-three-times-a-month', 'Üks kuni kolm korda kuus'],
		['Y11_Q21a', '4--Less-often', 'Harvem'],
		['Y11_Q21a', '5--Never', 'Võimatuks'],
		['Y11_Q21b', '1--Every-day-or-almost-every-day', 'Iga päev või peaaegu iga päev'],
		['Y11_Q21b', '2--At-least-once-a-week', 'Vähemalt kord nädalas'],
		['Y11_Q21b', '3--One-to-three-times-a-month', 'Üks kuni kolm korda kuus'],
		['Y11_Q21b', '4--Less-often', 'Harvem'],
		['Y11_Q21b', '5--Never', 'Mitte kunagi'],
		['Y11_Q21c', '1--Every-day-or-almost-every-day', 'Iga päev või peaaegu iga päev'],
		['Y11_Q21c', '2--At-least-once-a-week', 'Vähemalt kord nädalas'],
		['Y11_Q21c', '3--One-to-three-times-a-month', 'Üks kuni kolm korda kuus'],
		['Y11_Q21c', '4--Less-often', 'Harvem'],
		['Y11_Q21c', '5--Never', 'Mitte kunagi'],
		['Y11_Q21d', '1--Every-day-or-almost-every-day', 'Iga päev või peaaegu iga päev'],
		['Y11_Q21d', '2--At-least-once-a-week', 'Vähemalt kord nädalas'],
		['Y11_Q21d', '3--One-to-three-times-a-month', 'Üks kuni kolm korda kuus'],
		['Y11_Q21d', '4--Less-often', 'Harvem'],
		['Y11_Q21d', '5--Never', 'Mitte kunagi'],
		['Y11_Q22_Volunteering', '1--Volunteers-regularly', 'Töötab vabatahtlikuna korrapäraselt'],
		['Y11_Q22_Volunteering', '2--Volunteers-occasionally', 'Töötab vabatahtlikuna aeg-ajalt'],
		['Y11_Q22_Volunteering', '3--Does-not-volunteer', 'Ei tööta vabatahtlikuna'],
		['Y11_Q23a', '1--Yes', 'Jah'],
		['Y11_Q23a', '2--No', 'Ei'],
		['Y11_Q23b', '1--Yes', 'Jah'],
		['Y11_Q23b', '2--No', 'Ei'],
		['Y11_Q23c', '1--Yes', 'Jah'],
		['Y11_Q23c', '2--No', 'Ei'],
		['Y11_Q23d', '1--Yes', 'Jah'],
		['Y11_Q23d', '2--No', 'Ei'],
		['Y11_Q24', 'Mean', 'Keskmine'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Suur lõhe'],
		['Y11_Q25a', '2--Some-tension', 'Väike lõhe'],
		['Y11_Q25a', '3--No-tension', 'Lõhet ei ole'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Suur lõhe'],
		['Y11_Q25b', '2--Some-tension', 'Väike lõhe'],
		['Y11_Q25b', '3--No-tension', 'Lõhet ei ole'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Suur lõhe'],
		['Y11_Q25c', '2--Some-tension', 'Väike lõhe'],
		['Y11_Q25c', '3--No-tension', 'Lõhet ei ole'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Suur lõhe'],
		['Y11_Q25d', '2--Some-tension', 'Väike lõhe'],
		['Y11_Q25d', '3--No-tension', 'Lõhet ei ole'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Suur lõhe'],
		['Y11_Q25e', '2--Some-tension', 'Väike lõhe'],
		['Y11_Q25e', '3--No-tension', 'Lõhet ei ole'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Suur lõhe'],
		['Y11_Q25f', '2--Some-tension', 'Väike lõhe'],
		['Y11_Q25f', '3--No-tension', 'Lõhet ei ole'],
		['Y11_Q25g', '1--A-lot-of--tension', 'Suur lõhe'],
		['Y11_Q25g', '2--Some-tension', 'Väike lõhe'],
		['Y11_Q25g', '3--No-tension', 'Lõhet ei ole'],
		['Y11_Q28a', 'Mean', 'Keskmine'],
		['Y11_Q28b', 'Mean', 'Keskmine'],
		['Y11_Q28c', 'Mean', 'Keskmine'],
		['Y11_Q28d', 'Mean', 'Keskmine'],
		['Y11_Q28e', 'Mean', 'Keskmine'],
		['Y11_Q28f', 'Mean', 'Keskmine'],
		['Y11_Q29a', '1--Strongly-agree', 'Nõustun täielikult'],
		['Y11_Q29a', '2--Agree', 'Nõustun'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Ei oska öelda'],
		['Y11_Q29a', '4--Disagree', 'Ei nõustu'],
		['Y11_Q29a', '5--Strongly-disagree', 'Ei nõustu üldse'],
		['Y11_Q29b', '1--Strongly-agree', 'Nõustun täielikult'],
		['Y11_Q29b', '2--Agree', 'Nõustun'],
		['Y11_Q29b', '3--Neither-agree-nor-disagree', 'Ei oska öelda'],
		['Y11_Q29b', '4--Disagree', 'Ei nõustu'],
		['Y11_Q29b', '5--Strongly-disagree', 'Ei nõustu üldse'],
		['Y11_Q29c', '1--Strongly-agree', 'Nõustun täielikult'],
		['Y11_Q29c', '2--Agree', 'Nõustun'],
		['Y11_Q29c', '3--Neither-agree-nor-disagree', 'Ei oska öelda'],
		['Y11_Q29c', '4--Disagree', 'Ei nõustu'],
		['Y11_Q29c', '5--Strongly-disagree', 'Ei nõustu üldse'],
		['Y11_Q29d', '1--Strongly-agree', 'Nõustun täielikult'],
		['Y11_Q29d', '2--Agree', 'Nõustun'],
		['Y11_Q29d', '3--Neither-agree-nor-disagree', 'Ei oska öelda'],
		['Y11_Q29d', '4--Disagree', 'Ei nõustu'],
		['Y11_Q29d', '5--Strongly-disagree', 'Ei nõustu üldse'],
		['Y11_Q29e', '1--Strongly-agree', 'Nõustun täielikult'],
		['Y11_Q29e', '2--Agree', 'Nõustun'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Ei oska öelda'],
		['Y11_Q29e', '4--Disagree', 'Ei nõustu'],
		['Y11_Q29e', '5--Strongly-disagree', 'Ei nõustu üldse'],
		['Y11_Q29f', '1--Strongly-agree', 'Nõustun täielikult'],
		['Y11_Q29f', '2--Agree', 'Nõustun'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Ei oska öelda'],
		['Y11_Q29f', '4--Disagree', 'Ei nõustu'],
		['Y11_Q29f', '5--Strongly-disagree', 'Ei nõustu üldse'],
		['Y11_Q29g', '1--Strongly-agree', 'Nõustun täielikult'],
		['Y11_Q29g', '2--Agree', 'Nõustun'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Ei oska öelda'],
		['Y11_Q29g', '4--Disagree', 'Ei nõustu'],
		['Y11_Q29g', '5--Strongly-disagree', 'Ei nõustu üldse'],
		['Y11_Q29h', '1--Strongly-agree', 'Nõustun täielikult'],
		['Y11_Q29h', '2--Agree', 'Nõustun'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Ei oska öelda'],
		['Y11_Q29h', '4--Disagree', 'Ei nõustu'],
		['Y11_Q29h', '5--Strongly-disagree', 'Ei nõustu üldse'],
		['Y11_Q29i', '1--Strongly-agree', 'Nõustun täielikult'],
		['Y11_Q29i', '2--Agree', 'Nõustun'],
		['Y11_Q29i', '3--Neither-agree-nor-disagree', 'Ei oska öelda'],
		['Y11_Q29i', '4--Disagree', 'Ei nõustu'],
		['Y11_Q29i', '5--Strongly-disagree', 'Ei nõustu üldse'],
		['Y11_Q30', 'Mean', 'Keskmine'],
		['Y11_Q33a', '1--Every-day-or-almost-every-day', 'Iga päev või peaaegu iga päev'],
		['Y11_Q33a', '2--At-least-once-a-week', 'Vähemalt kord nädalas'],
		['Y11_Q33a', '3--One-to-three-times-a-month', 'Üks kuni kolm korda kuus'],
		['Y11_Q33a', '4--Less-often', 'Harvem'],
		['Y11_Q33a', '5--Never', 'Mitte kunagi'],
		['Y11_Q33b', '1--Every-day-or-almost-every-day', 'Iga päev või peaaegu iga päev'],
		['Y11_Q33b', '2--At-least-once-a-week', 'Vähemalt kord nädalas'],
		['Y11_Q33b', '3--One-to-three-times-a-month', 'Üks kuni kolm korda kuus'],
		['Y11_Q33b', '4--Less-often', 'Harvem'],
		['Y11_Q33b', '5--Never', 'Mitte kunagi'],
		['Y11_Q33c', '1--Every-day-or-almost-every-day', 'Iga päev või peaaegu iga päev'],
		['Y11_Q33c', '2--At-least-once-a-week', 'Vähemalt kord nädalas'],
		['Y11_Q33c', '3--One-to-three-times-a-month', 'Üks kuni kolm korda kuus'],
		['Y11_Q33c', '4--Less-often', 'Harvem'],
		['Y11_Q33c', '5--Never', 'Mitte kunagi'],
		['Y11_Q33d', '1--Every-day-or-almost-every-day', 'Iga päev või peaaegu iga päev'],
		['Y11_Q33d', '2--At-least-once-a-week', 'Vähemalt kord nädalas'],
		['Y11_Q33d', '3--One-to-three-times-a-month', 'Üks kuni kolm korda kuus'],
		['Y11_Q33d', '4--Less-often', 'Harvem'],
		['Y11_Q33d', '5--Never', 'Mitte kunagi'],
		['Y11_Q34a', '1--Every-day-or-almost-every-day', 'Iga päev või peaaegu iga päev'],
		['Y11_Q34a', '2--At-least-once-a-week', 'Vähemalt kord nädalas'],
		['Y11_Q34a', '3--One-to-three-times-a-month', 'Üks kuni kolm korda kuus'],
		['Y11_Q34a', '4--Less-often', 'Harvem'],
		['Y11_Q34a', '5--Never', 'Mitte kunagi'],
		['Y11_Q34b', '1--Every-day-or-almost-every-day', 'Iga päev või peaaegu iga päev'],
		['Y11_Q34b', '2--At-least-once-a-week', 'Vähemalt kord nädalas'],
		['Y11_Q34b', '3--One-to-three-times-a-month', 'Üks kuni kolm korda kuus'],
		['Y11_Q34b', '4--Less-often', 'Harvem'],
		['Y11_Q34b', '5--Never', 'Mitte kunagi'],
		['Y11_Q34c', '1--Every-day-or-almost-every-day', 'Iga päev või peaaegu iga päev'],
		['Y11_Q34c', '2--At-least-once-a-week', 'Vähemalt kord nädalas'],
		['Y11_Q34c', '3--One-to-three-times-a-month', 'Üks kuni kolm korda kuus'],
		['Y11_Q34c', '4--Less-often', 'Harvem'],
		['Y11_Q34c', '5--Never', 'Mitte kunagi'],
		['Y11_Q34d', '1--Every-day-or-almost-every-day', 'Iga päev või peaaegu iga päev'],
		['Y11_Q34d', '2--At-least-once-a-week', 'Vähemalt kord nädalas'],
		['Y11_Q34d', '3--One-to-three-times-a-month', 'Üks kuni kolm korda kuus'],
		['Y11_Q34d', '4--Less-often', 'Harvem'],
		['Y11_Q34d', '5--Never', 'Mitte kunagi'],
		['Y11_Q35a', '1--A-member-of-your-family', 'Pereliikmelt või sugulaselt'],
		['Y11_Q35a', '2--A-friend--neighbour--or-someone-else', 'Sõbralt, naabrilt või kelleltki teiselt'],
		['Y11_Q35a', '3--A-service-provider--institution-or-organisation', 'Teenusepakkujalt, institutsioonilt või organisatsioonilt'],
		['Y11_Q35a', '4--Nobody', 'Mitte kelleltki'],
		['Y11_Q35b', '1--A-member-of-your-family', 'Pereliikmelt või sugulaselt'],
		['Y11_Q35b', '2--A-friend--neighbour--or-someone-else', 'Sõbralt, naabrilt või kelleltki teiselt'],
		['Y11_Q35b', '3--A-service-provider--institution-or-organisation', 'Teenusepakkujalt, institutsioonilt või organisatsioonilt'],
		['Y11_Q35b', '4--Nobody', 'Mitte kelleltki'],
		['Y11_Q35c', '1--A-member-of-your-family', 'Pereliikmelt või sugulaselt'],
		['Y11_Q35c', '2--A-friend--neighbour--or-someone-else', 'Sõbralt, naabrilt või kelleltki teiselt'],
		['Y11_Q35c', '3--A-service-provider--institution-or-organisation', 'Teenusepakkujalt, institutsioonilt või organisatsioonilt'],
		['Y11_Q35c', '4--Nobody', 'Mitte kelleltki'],
		['Y11_Q35d', '1--A-member-of-your-family', 'Pereliikmelt või sugulaselt'],
		['Y11_Q35d', '2--A-friend--neighbour--or-someone-else', 'Sõbralt, naabrilt või kelleltki teiselt'],
		['Y11_Q35d', '3--A-service-provider--institution-or-organisation', 'Teenusepakkujalt, institutsioonilt või organisatsioonilt'],
		['Y11_Q35d', '4--Nobody', 'Mitte kelleltki'],
		['Y11_Q35e', '1--A-member-of-your-family', 'Pereliikmelt või sugulaselt'],
		['Y11_Q35e', '2--A-friend--neighbour--or-someone-else', 'Sõbralt, naabrilt või kelleltki teiselt'],
		['Y11_Q35e', '3--A-service-provider--institution-or-organisation', 'Teenusepakkujalt, institutsioonilt või organisatsioonilt'],
		['Y11_Q35e', '4--Nobody', 'Mitte kelleltki'],
		['Y11_Q36a', '1--Every-day', 'Iga päev'],
		['Y11_Q36a', '2--Several-days-a-week', 'Mitu korda nädalas'],
		['Y11_Q36a', '3--Once-or-twice-a-week', 'Mõni kord nädalas'],
		['Y11_Q36a', '4--Less-often', 'Harvem'],
		['Y11_Q36a', '5--Never', 'Mitte kunagi'],
		['Y11_Q36b', '1--Every-day', 'Iga päev'],
		['Y11_Q36b', '2--Several-days-a-week', 'Mitu korda nädalas'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'Mõni kord nädalas'],
		['Y11_Q36b', '4--Less-often', 'Harvem'],
		['Y11_Q36b', '5--Never', 'Mitte kunagi'],
		['Y11_Q36c', '1--Every-day', 'Iga päev'],
		['Y11_Q36c', '2--Several-days-a-week', 'Mitu korda nädalas'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'Mõni kord nädalas'],
		['Y11_Q36c', '4--Less-often', 'Harvem'],
		['Y11_Q36c', '5--Never', 'Mitte kunagi'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Teen liiga palju'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Teen piisavalt'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Teen liiga vähe'],
		['Y11_Q39a', '1--Spend-more-time', 'Tahaksin rohkem aega veeta'],
		['Y11_Q39a', '2--As-much-as-I-currently-do', 'Veedan aega parajalt'],
		['Y11_Q39a', '3--Spend-less-time', 'Tahaksin vähem aega veeta'],
		['Y11_Q39b', '1--Spend-more-time', 'Tahaksin rohkem aega veeta'],
		['Y11_Q39b', '2--As-much-as-I-currently-do', 'Veedan aega parajalt'],
		['Y11_Q39b', '3--Spend-less-time', 'Tahaksin vähem aega veeta'],
		['Y11_Q39c', '1--Spend-more-time', 'Tahaksin rohkem aega veeta'],
		['Y11_Q39c', '2--As-much-as-I-currently-do', 'Veedan aega parajalt'],
		['Y11_Q39c', '3--Spend-less-time', 'Tahaksin vähem aega veeta'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'Tööl ja kodus'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Kas tööl või kodus'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Stress puudub või on väike'],
		['Y11_Q40a', 'Mean', 'Keskmine'],
		['Y11_Q40b', 'Mean', 'Keskmine'],
		['Y11_Q40c', 'Mean', 'Keskmine'],
		['Y11_Q40d', 'Mean', 'Keskmine'],
		['Y11_Q40e', 'Mean', 'Keskmine'],
		['Y11_Q40f', 'Mean', 'Keskmine'],
		['Y11_Q40g', 'Mean', 'Keskmine'],
		['Y11_Q40h', 'Mean', 'Keskmine'],
		['Y11_Q41', 'Mean', 'Keskmine'],
		['Y11_Q42', '1--Very-good', 'Väga hea'],
		['Y11_Q42', '2--Good', 'Hea'],
		['Y11_Q42', '3--Fair', 'Rahuldav'],
		['Y11_Q42', '4--Bad', 'Halb'],
		['Y11_Q42', '5--Very-bad', 'Väga halb'],
		['Y11_Q46a', '1--All-of-the-time', 'Pidevalt'],
		['Y11_Q46a', '2--Most-of-the-time', 'Enamus ajast'],
		['Y11_Q46a', '3--More-than-half-of-the-time', 'Üle poole ajast'],
		['Y11_Q46a', '4--Less-than-half-of-the-time', 'Alla poole ajast'],
		['Y11_Q46a', '5--Some-of-the-time', 'Aeg-ajalt'],
		['Y11_Q46a', '6--At-no-time', 'Mitte kunagi'],
		['Y11_Q46b', '1--All-of-the-time', 'Pidevalt'],
		['Y11_Q46b', '2--Most-of-the-time', 'Enamus ajast'],
		['Y11_Q46b', '3--More-than-half-of-the-time', 'Üle poole ajast'],
		['Y11_Q46b', '4--Less-than-half-of-the-time', 'Alla poole ajast'],
		['Y11_Q46b', '5--Some-of-the-time', 'Aeg-ajalt'],
		['Y11_Q46b', '6--At-no-time', 'Mitte kunagi'],
		['Y11_Q46c', '1--All-of-the-time', 'Pidevalt'],
		['Y11_Q46c', '2--Most-of-the-time', 'Enamus ajast'],
		['Y11_Q46c', '3--More-than-half-of-the-time', 'Üle poole ajast'],
		['Y11_Q46c', '4--Less-than-half-of-the-time', 'Alla poole ajast'],
		['Y11_Q46c', '5--Some-of-the-time', 'Aeg-ajalt'],
		['Y11_Q46c', '6--At-no-time', 'Mitte kunagi'],
		['Y11_Q46d_WHO5', 'Mean', 'Keskmine'],
		['Y11_Q47a', '1--Very-difficult', 'Suured raskused'],
		['Y11_Q47a', '2--A-little-difficult', 'Väikesed raskused'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Raskusi ei ole'],
		['Y11_Q47b', '1--Very-difficult', 'Suured raskused'],
		['Y11_Q47b', '2--A-little-difficult', 'Väikesed raskused'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Raskusi ei ole'],
		['Y11_Q47c', '1--Very-difficult', 'Suured raskused'],
		['Y11_Q47c', '2--A-little-difficult', 'Väikesed raskused'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Raskusi ei ole'],
		['Y11_Q47d', '1--Very-difficult', 'Suured raskused'],
		['Y11_Q47d', '2--A-little-difficult', 'Väikesed raskused'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Raskusi ei ole'],
		['Y11_Q47e', '1--Very-difficult', 'Suured raskused'],
		['Y11_Q47e', '2--A-little-difficult', 'Väikesed raskused'],
		['Y11_Q47e', '3--Not-difficult-at-all', 'Raskusi ei ole'],
		['Y11_Q50a', '1--Major-problems', 'Palju probleeme'],
		['Y11_Q50a', '2--Moderate-problems', 'Vähe probleeme'],
		['Y11_Q50a', '3--No-problems', 'Probleeme ei ole'],
		['Y11_Q50b', '1--Major-problems', 'Palju probleeme'],
		['Y11_Q50b', '2--Moderate-problems', 'Vähe probleeme'],
		['Y11_Q50b', '3--No-problems', 'Probleeme ei ole'],
		['Y11_Q50c', '1--Major-problems', 'Palju probleeme'],
		['Y11_Q50c', '2--Moderate-problems', 'Vähe probleeme'],
		['Y11_Q50c', '3--No-problems', 'Probleeme ei ole'],
		['Y11_Q50d', '1--Major-problems', 'Palju probleeme'],
		['Y11_Q50d', '2--Moderate-problems', 'Vähe probleeme'],
		['Y11_Q50d', '3--No-problems', 'Probleeme ei ole'],
		['Y11_Q50e', '1--Major-problems', 'Palju probleeme'],
		['Y11_Q50e', '2--Moderate-problems', 'Vähe probleeme'],
		['Y11_Q50e', '3--No-problems', 'Probleeme ei ole'],
		['Y11_Q50f', '1--Major-problems', 'Palju probleeme'],
		['Y11_Q50f', '2--Moderate-problems', 'Vähe probleeme'],
		['Y11_Q50f', '3--No-problems', 'Probleeme ei ole'],
		['Y11_Q51a', '1--with-great-difficulty', 'Väga raske'],
		['Y11_Q51a', '2--with-some-difficulty', 'Pisut raske'],
		['Y11_Q51a', '3--easily', 'Kerge'],
		['Y11_Q51a', '4--very-easily', 'Väga kerge'],
		['Y11_Q51b', '1--with-great-difficulty', 'Väga raske'],
		['Y11_Q51b', '2--with-some-difficulty', 'Pisut raske'],
		['Y11_Q51b', '3--easily', 'Kerge'],
		['Y11_Q51b', '4--very-easily', 'Väga kerge'],
		['Y11_Q51c', '1--with-great-difficulty', 'Väga raske'],
		['Y11_Q51c', '2--with-some-difficulty', 'Pisut raske'],
		['Y11_Q51c', '3--easily', 'Kerge'],
		['Y11_Q51c', '4--very-easily', 'Väga kerge'],
		['Y11_Q51d', '1--with-great-difficulty', 'Väga raske'],
		['Y11_Q51d', '2--with-some-difficulty', 'Pisut raske'],
		['Y11_Q51d', '3--easily', 'Kerge'],
		['Y11_Q51d', '4--very-easily', 'Väga kerge'],
		['Y11_Q51e', '1--with-great-difficulty', 'Väga raske'],
		['Y11_Q51e', '2--with-some-difficulty', 'Pisut raske'],
		['Y11_Q51e', '3--easily', 'Kerge'],
		['Y11_Q51e', '4--very-easily', 'Väga kerge'],
		['Y11_Q52', 'Mean', 'Keskmine'],
		['Y11_Q53a', 'Mean', 'Keskmine'],
		['Y11_Q53b', 'Mean', 'Keskmine'],
		['Y11_Q53c', 'Mean', 'Keskmine'],
		['Y11_Q53d', 'Mean', 'Keskmine'],
		['Y11_Q53e', 'Mean', 'Keskmine'],
		['Y11_Q53f', 'Mean', 'Keskmine'],
		['Y11_Q53g', 'Mean', 'Keskmine'],
		['Y11_Q57', '1--Much-worse', 'Palju halvem'],
		['Y11_Q57', '2--Somewhat-worse', 'Pisut halvem'],
		['Y11_Q57', '3--Neither-worse-nor-better', 'Sama kui praegu'],
		['Y11_Q57', '4--Somewhat-better', 'Pisut parem'],
		['Y11_Q57', '5--Much-better', 'Palju parem'],
		['Y11_Q58', '1--With-great-difficulty', 'Suurte raskustega'],
		['Y11_Q58', '2--With-difficulty', 'Raskustega'],
		['Y11_Q58', '3--With-some-difficulty', 'Mõningate raskustega'],
		['Y11_Q58', '4--Fairly-easily', 'Üsna lihtsalt'],
		['Y11_Q58', '5--Easily', 'Lihtsalt'],
		['Y11_Q58', '6--Very-easily', 'Väga lihtsalt'],
		['Y11_Q59a', '1--No', 'Ei'],
		['Y11_Q59a', '2--Yes', 'Jah'],
		['Y11_Q59b', '1--No', 'Ei'],
		['Y11_Q59b', '2--Yes', 'Jah'],
		['Y11_Q59c', '1--No', 'Ei'],
		['Y11_Q59c', '2--Yes', 'Jah'],
		['Y11_Q59d', '1--No', 'Ei'],
		['Y11_Q59d', '2--Yes', 'Jah'],
		['Y11_Q59e', '1--No', 'Ei'],
		['Y11_Q59e', '2--Yes', 'Jah'],
		['Y11_Q59f', '1--No', 'Ei'],
		['Y11_Q59f', '2--Yes', 'Jah'],
		['Y11_Q60a', '1--Yes', 'Jah'],
		['Y11_Q60a', '2--No', 'Ei'],
		['Y11_Q60b', '1--Yes', 'Jah'],
		['Y11_Q60b', '2--No', 'Ei'],
		['Y11_Q60c', '1--Yes', 'Jah'],
		['Y11_Q60c', '2--No', 'Ei'],
		['Y11_Q60d', '1--Yes', 'Jah'],
		['Y11_Q60d', '2--No', 'Ei'],
		['Y11_Q65', '1--Better', 'Parem'],
		['Y11_Q65', '2--The-same', 'Sama'],
		['Y11_Q65', '3--Worse', 'Halvem'],
		['Y11_Q66', '1--Better', 'Parem'],
		['Y11_Q66', '2--The-same', 'Sama'],
		['Y11_Q66', '3--Worse', 'Halvem'],
		['Y11_Q8_PreferredWorkingHours', '1--Work-less', 'Vähem'],
		['Y11_Q8_PreferredWorkingHours', '2--Work-the-same', 'Sama palju'],
		['Y11_Q8_PreferredWorkingHours', '3--Work-more', 'Rohkem'],
		['Y11_SocExIndex', 'Mean', 'Keskmine']
	];
var country_
	 = [
	
		['AT', 'Austria'],
		['BE', 'Belgia'],
		['BG', 'Bulgaaria'],
		['CY', 'Küpros'],
		['CZ', 'Tšehhi'],
		['DE', 'Saksamaa'],
		['DK', 'Taani'],
		['EE', 'Eesti'],
		['EL', 'Kreeka'],
		['ES', 'Hispaania'],
		['FI', 'Soome'],
		['FR', 'Prantsusmaa'],
		['HR', 'Horvaatia'],
		['HU', 'Ungari'],
		['IE', 'Iirimaa'],
		['IS', 'Island'],
		['IT', 'Itaalia'],
		['LT', 'Leedu'],
		['LU', 'Luksemburg'],
		['LV', 'Läti'],
		['ME', 'Montenegro'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Madalmaad'],
		['PL', 'Poola'],
		['PT', 'Portugal'],
		['RO', 'Rumeenia'],
		['RS', 'Serbia'],
		['SE', 'Rootsi'],
		['SI', 'Sloveenia'],
		['SK', 'Slovakkia'],
		['TR', 'Türgi'],
		['UK', 'Ühendkuningriik'],
		['XK', 'Kosovo'],
		['EuropeanUnion', 'Euroopa Liit']
	];
var question_meta
	 = [
	
		['Y11_Deprindex', 'Ainelise puuduse indeks: nende asjade arv, mida leibkonnad ei saa endale lubada', ''],
		['Y11_Q57', 'Leibkonna rahaline seis võrreldes Eesti enamikuga', ''],
		['Y11_Q58', 'Kas teie leibkond saab olemasolevate vahenditega hakkama?', ''],
		['Y11_Q59a', 'Kas teie kodu kütmine on teile jõukohane?', ''],
		['Y11_Q59b', 'Kas teile on jõukohane minna kord aastas nädalaks puhkusele kodunt kaugele?', ''],
		['Y11_Q59c', 'Kas teile on jõukohane osta oma aja ära elanud mööbli asemel uut?', ''],
		['Y11_Q59d', 'Kas teie leibkonnale on jõukohane süüa soovi korral ülepäeviti loomaliha, kanaliha või kala?', ''],
		['Y11_Q59e', 'Kas teie leibkonna liikmetele on jõukohane osta uusi (mitte kasutatud) riideid?', ''],
		['Y11_Q59f', 'Kas teie leibkonnale on jõukohane võõrustada vähemalt kord kuus söögi või joogiga sõpru või lähedasi?', ''],
		['Y11_Q60a', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud üüri- või laenumaksete võlgnevusi?', ''],
		['Y11_Q60b', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud kommunaalteenuste maksete võlgnevusi?', ''],
		['Y11_Q60c', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud tarbimislaenumaksete võlgnevusi?', ''],
		['Y11_Q60d', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud mitteametlike laenumaksete võlgnevusi?', ''],
		['Y11_Q65', 'Leibkonna rahaline seis võrreldes 12 kuu taguse olukorraga', ''],
		['Y11_Q66', 'Järgneval 12 kuul eeldatav rahaline seis', ''],
		['Y11_Accommproblems', 'Eluaseme probleemide arv', ''],
		['Y11_Q18', 'Kodu omamine', ''],
		['Y11_Q19a', 'Eluasemeprobleemid: ruumipuudus', ''],
		['Y11_Q19b', 'Eluasemeprobleemid: pehkinud aknad, uksed või põrandad', ''],
		['Y11_Q19c', 'Eluasemeprobleemid: niiskus/lekked seintes või katuses', ''],
		['Y11_Q19d', 'Eluasemeprobleemid: puudub vesiklosett', ''],
		['Y11_Q19e', 'Eluasemeprobleemid: puudub vann või dušš', ''],
		['Y11_Q19f', 'Eluasemeprobleemid: puudub koht väljas istumiseks', ''],
		['Y11_Q20', 'Kui tõenäoliseks peate vajadust lahkuda oma elukohast järgneva kuue kuu jooksul, kuna ei suuda enam selle eest maksta?', ''],
		['Y11_Q50a', 'Probleemid müraga vahetus koduümbruses', ''],
		['Y11_Q50b', 'Probleemid õhu kvaliteediga vahetus koduümbruses', ''],
		['Y11_Q50c', 'Probleemid kraanivee kvaliteediga vahetus koduümbruses', ''],
		['Y11_Q50d', 'Probleemid kuritegevuse, vägivalla või vandalismiga vahetus koduümbruses', ''],
		['Y11_Q50e', 'Probleemid tänavatel vedeleva prügi või prahiga vahetus koduümbruses', ''],
		['Y11_Q50f', 'Probleemid liiklusummikutega vahetus koduümbruses', ''],
		['Y11_Q51a', 'Postiteenuste kättesaadavus', ''],
		['Y11_Q51b', 'Pangateenuste kättesaadavus', ''],
		['Y11_Q51c', 'Ühistransporditeenuste kättesaadavus', ''],
		['Y11_Q51d', 'Kino, teatri või kultuurikeskuse olemasolu', ''],
		['Y11_Q51e', 'Puhke- või haljasalade olemasolu', ''],
		['Y11_Q52', 'Tööle või õpingutele minekuks ja tagasitulekuks kuluv aeg', ''],
		['Y11_Q33a', 'Vahetu suhtlemine väljaspool leibkonda elavate lastega', ''],
		['Y11_Q33b', 'Vahetu suhtlemine väljaspool leibkonda elava vanemaga', ''],
		['Y11_Q33c', 'Vahetu suhtlemine väljaspool leibkonda elava venna, õue või muu sugulasega', ''],
		['Y11_Q33d', 'Vahetu suhtlemine väljaspool leibkonda elavate sõprade või naabritega', ''],
		['Y11_Q34a', 'Telefoni, interneti või posti teel suhtlemine väljaspool leibkonda elavate lastega', ''],
		['Y11_Q34b', 'Telefoni, interneti või posti teel suhtlemine väljaspool leibkonda elava vanemaga', ''],
		['Y11_Q34c', 'Telefoni, interneti või posti teel suhtlemine väljaspool leibkonda elava õe, venna või muu sugulasega', ''],
		['Y11_Q34d', 'Telefoni, interneti või posti teel suhtlemine väljaspool leibkonda elavate sõprade või naabritega', ''],
		['Y11_Q35a', 'Kellelt saaksite vajaduse korral haigena abi majapidamises?', ''],
		['Y11_Q35b', 'Kellelt saaksite vajaduse korral nõu seoses mõne tõsise isikliku või perekondliku probleemiga?', ''],
		['Y11_Q35c', 'Kellelt saaksite vajaduse korral abi töökoha leidmisel?', ''],
		['Y11_Q35d', 'Kellelt saaksite abi, kui olete kerges masenduses ja tahate kellegagi rääkida?', ''],
		['Y11_Q35e', 'Kellelt saaksite abi, kui vajate kiiresti 1000 eurot hädaolukorra lahendamiseks?', ''],
		['Y11_Q21a', 'Osalemine usutalitustel, v.a pulmad, matused ja ristimised', ''],
		['Y11_Q21b', 'Interneti kasutamine muul otstarbel kui tööks', ''],
		['Y11_Q21c', 'Spordi harrastamine vms füüsiline tegevus', ''],
		['Y11_Q21d', 'Osalemine klubide, seltside või ühingute tegevuses', ''],
		['Y11_Q22_Volunteering', 'Kui tihti olete viimase 12 kuu jooksul töötanud tasuta vabatahtlikuna?', ''],
		['Y11_Q23a', 'Osalemine ametiühingu, erakonna või kodanikualgatusrühma koosolekul viimase 12 kuu jooksul', ''],
		['Y11_Q23b', 'Osalemine protesti- või meeleavaldusel viimase 12 kuu jooksul', ''],
		['Y11_Q23c', 'Allakirjutamine petitsioonile viimase 12 kuu jooksul (k.a e-posti või interneti teel).', ''],
		['Y11_Q23d', 'Poliitiku või ametniku poole pöördumine (v.a seoses tavapäraste riiklike teenustega)', ''],
		['Y11_Q29e', 'Tunnen end sotsiaalselt tõrjutuna', ''],
		['Y11_Q29f', 'Tänapäeva elu on läinud nii keeruliseks, et mul on juba raske toime tulla', ''],
		['Y11_Q29g', 'Mul on tunne, et teised ei väärtusta mind', ''],
		['Y11_Q29h', 'Mõnikord halvustatakse mind mu tööalase olukorra või sissetuleku tõttu', ''],
		['Y11_Q29i', 'Tunnen lähedust oma kodukandi inimestega', ''],
		['Y11_SocExIndex', 'Sotsiaalse tõrjutuse indeks', ''],
		['Y11_Q29a', 'Olen tuleviku suhtes optimistlik', ''],
		['Y11_Q29b', 'Tunnen üldiselt, et sellel, mida ma teen, on väärtus', ''],
		['Y11_Q29c', 'Tunnen, et saan oma elu üle ise otsustada', ''],
		['Y11_Q29d', 'Oma igapäevaelus on mul harva aega teha asju, mida ma tõeliselt naudin', ''],
		['Y11_Q30', 'Kui rahul olete oma eluga praegu?', ''],
		['Y11_Q40a', 'Rahulolu haridusega', ''],
		['Y11_Q40b', 'Rahulolu praeguse tööga', ''],
		['Y11_Q40c', 'Rahulolu praeguse elatustasemega', ''],
		['Y11_Q40d', 'Rahulolu eluasemega', ''],
		['Y11_Q40e', 'Rahulolu pereeluga', ''],
		['Y11_Q40f', 'Rahulolu tervisega', ''],
		['Y11_Q40g', 'Rahulolu seltskondliku eluga', ''],
		['Y11_Q40h', 'Rahulolu Eesti majandusliku olukorraga', ''],
		['Y11_Q41', 'Kõike arvesse võttes, kui rahul te oma eluga olete?', ''],
		['Y11_Q42', 'Terviseseisund enda hinnangul', ''],
		['Y11_Q46a', 'Olen tundnud end eriti pinges', ''],
		['Y11_Q46b', 'Olen tundnud end üksikuna', ''],
		['Y11_Q46c', 'Olen tundnud masendust', ''],
		['Y11_Q46d_WHO5', 'WHO-5 vaimse heaolu skaala', ''],
		['Y11_Q47a', 'Raskused arsti juurde pääsemisel kauguse tõttu arsti vastuvõturuumidest või haiglast', ''],
		['Y11_Q47b', 'Raskused arsti juurde pääsemisel viivituse tõttu arsti vastuvõtule pääsemisel', ''],
		['Y11_Q47c', 'Raskused arsti juurde pääsemisel ooteaja tõttu arsti vastuvõtule visiidi päeval', ''],
		['Y11_Q47d', 'Raskused arsti juurde pääsemisel visiiditasu tõttu', ''],
		['Y11_Q47e', 'Raskused arsti juurde pääsemisel ajapuuduse tõttu töö või kellegi eest hoolitsemise pärast', ''],
		['Y11_Q53a', 'Milliseks hindaksite tervishoiuteenuste kvaliteedi Eestis?', ''],
		['Y11_Q53b', 'Milliseks hindaksite haridussüsteemi kvaliteedi Eestis?', ''],
		['Y11_Q53c', 'Milliseks hindaksite ühistranspordi kvaliteedi Eestis?', ''],
		['Y11_Q53d', 'Milliseks hindaksite lastehoiuteenuste kvaliteedi Eestis?', ''],
		['Y11_Q53e', 'Milliseks hindaksite pikaajaliste hooldusteenuste kvaliteedi Eestis?', ''],
		['Y11_Q53f', 'Milliseks hindaksite sotsiaaleluasemeteenuste kvaliteedi Eestis?', ''],
		['Y11_Q53g', 'Milliseks hindaksite riikliku pensionisüsteemi kvaliteedi Eestis?', ''],
		['Y11_Q8_PreferredWorkingHours', 'Mitu tundi nädalas eelistaksite tööd teha?', ''],
		['Y11_Q10_Partnerprefhours', 'Kui see oleks teie otsustada, siis mitu tundi peaks teie elukaaslane nädalas töötama?', 'See küsimus esitati küsitletutele, kelle leibkonda kuulub elukaaslane.'],
		['Y11_Q12a', ' Olen töölt koju tulles olnud majapidamistööde tegemiseks liiga väsinud', ''],
		['Y11_Q12b', 'Mul on olnud raske täita oma perekondlikke kohustusi tööl oldud aja tõttu ', ''],
		['Y11_Q12c', 'Mul on olnud perekondlike kohustuste tõttu raske tööle keskenduda', ''],
		['Y11_Q13a', 'Saan oma tööpäeva alguse ja lõpu üle ise otsustada', ''],
		['Y11_Q13b', 'Ületundide eest saan vaba aega', ''],
		['Y11_Q13c', 'Vajaduse korral saan võtta lühikese etteteatamisajaga vaba päeva ', ''],
		['Y11_Q15', 'Kui tõenäoliseks peate oma töökoha kaotamist järgmise kuue kuu jooksul?', ''],
		['Y11_Q16', 'Kui kaotaksite praegu oma töö, siis kui tõenäoliseks peate sarnase palgatasemega töökoha leidmist?', 'See küsimus esitati küsitletutele, kes saavad oma töö eest palka.'],
		['Y11_Q36a', 'Kui sageli olete hõivatud oma laste või lapselaste eest hoolitsemisega?', ''],
		['Y11_Q36b', 'Kui sageli olete hõivatud toidu valmistamise või majapidamistöödega?', ''],
		['Y11_Q36c', 'Kui sageli olete hõivatud eakate või puudega sugulaste eest hoolitsemisega?', ''],
		['Y11_Q38', 'Mida arvate oma osast majapidamistöödes?', ''],
		['Y11_Q39a', 'Suhtumine pereliikmetega veedetud aega', ''],
		['Y11_Q39b', 'Suhtumine muude sotsiaalsete kontaktidega veedetud aega', ''],
		['Y11_Q39c', 'Suhtumine hobide ja huvialadega veedetud aega', ''],
		['Y11_Q39d_stress', 'Töö- ja eraelu tasakaalustamatusest põhjustatud stress', ''],
		['Y11_Q24', 'Kas te peate ennast väga usaldavaks või väga umbusklikuks?', ''],
		['Y11_Q25a', 'Hinnang vaeste ja rikaste vahelisele lõhele', ''],
		['Y11_Q25b', 'Hinnang juhtkonna ja töötajate vahelisele lõhele', ''],
		['Y11_Q25c', 'Hinnang meeste ja naiste vahelisele lõhele', ''],
		['Y11_Q25d', 'Hinnang põlvkondadevahelisele lõhele', ''],
		['Y11_Q25e', 'Hinnang rahvustevahelisele lõhele', ''],
		['Y11_Q25f', 'Hinnang usugruppidevahelisele lõhele', ''],
		['Y11_Q25g', 'Hinnang eri seksuaalse sättumusegas inimeste vahelisele lõhele', ''],
		['Y11_Q28a', 'Riigikogu usaldamine', ''],
		['Y11_Q28b', 'Õigussüsteemi usaldamine', ''],
		['Y11_Q28c', 'Kirjutava ajakirjanduse usaldamine', ''],
		['Y11_Q28d', 'Politsei usaldamine', ''],
		['Y11_Q28e', 'Valitsuse usaldamine', ''],
		['Y11_Q28f', 'Kohaliku omavalitsuse usaldamine', '']
	];
