//Auto Generated file
var subset_
	 = [
	
		['Y11_Agecategory', 'Ikä'],
		['Y11_HH2a', 'Sukupuoli'],
		['Y11_Incomequartiles_percapita', 'Tulot']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Kaikki ikäryhmät'],
		['Y11_Agecategory', '1--18-24y', '18–24 vuotta'],
		['Y11_Agecategory', '2--25-34y', '25–34 vuotta'],
		['Y11_Agecategory', '3--35-49y', '35–49 vuotta'],
		['Y11_Agecategory', '4--50-64y', '50–64 vuotta'],
		['Y11_Agecategory', '5---64y', '> 64 vuotta'],
		['Y11_HH2a', 'All', 'Molemmat sukupuolet'],
		['Y11_HH2a', '1--Female', 'Naiset'],
		['Y11_HH2a', '2--Male', 'Miehet'],
		['Y11_Incomequartiles_percapita', 'All', 'Kaikki tulotasot'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Alin'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'Toiseksi ylin'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'Kolmanneksi ylin'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Ylin']
	];
var topic_
	 = [
	
		['', 'Kaikki (127)'],
		['Elintaso ja puute', 'Elintaso ja puute (15)'],
		['Julkiset terveyspalvelut', 'Julkiset terveyspalvelut (17)'],
		['Koti ja lähiympäristö', 'Koti ja lähiympäristö (21)'],
		['Perhe ja sosiaalinen elämä', 'Perhe ja sosiaalinen elämä (13)'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan (15)'],
		['Subjektiivinen hyvinvointi', 'Subjektiivinen hyvinvointi (14)'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Työllisyys ja työ- ja yksityiselämän tasapaino (18)'],
		['Yhteiskunnan laatu', 'Yhteiskunnan laatu (14)']
	];
var topic_question
	 = [
	
		['Elintaso ja puute', 'Y11_Deprindex', 'Huono-osaisuuden indeksi: määrä asioista, joihin kotitalouksilla ei ole varaa'],
		['Elintaso ja puute', 'Y11_Q57', 'Kotitalouden taloudellinen tilanne verrattuna kotimaan yleiseen tilanteeseen'],
		['Elintaso ja puute', 'Y11_Q58', 'Ovatko kotitaloutenne tulot riittävät?'],
		['Elintaso ja puute', 'Y11_Q59a', 'Onko teillä varaa pitää koti riittävän lämpimänä?'],
		['Elintaso ja puute', 'Y11_Q59b', 'Onko teillä varaa vuosittaiseen lomaviikkoon poissa kotoa?'],
		['Elintaso ja puute', 'Y11_Q59c', 'Onko teillä varaa vaihtaa mikä tahansa kulunut huonekalu uuteen?'],
		['Elintaso ja puute', 'Y11_Q59d', 'Onko teillä varaa liha-, kana- tai kala-ateriaan joka toinen päivä (niin halutessanne)?'],
		['Elintaso ja puute', 'Y11_Q59e', 'Onko teillä varaa ostaa uusia vaatteita käytettyjen sijaan?'],
		['Elintaso ja puute', 'Y11_Q59f', 'Onko teillä varaa kutsua ystäviä tai sukulaisia lasilliselle tai aterialle vähintään kerran kuussa?'],
		['Elintaso ja puute', 'Y11_Q60a', 'Onko kotitaloudella ollut asunnon vuokran tai asuntolainan maksuerän maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?'],
		['Elintaso ja puute', 'Y11_Q60b', 'Onko kotitaloudella ollut yleisiin asumiseen liittyvien kulujen maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?'],
		['Elintaso ja puute', 'Y11_Q60c', 'Onko kotitaloudella ollut kulutusluoton lyhennysten maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?'],
		['Elintaso ja puute', 'Y11_Q60d', 'Onko kotitaloudella ollut epävirallisten lainojen maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?'],
		['Elintaso ja puute', 'Y11_Q65', 'Kotitalouden taloudellinen tilanne verrattuna 12 kuukauden takaiseen'],
		['Elintaso ja puute', 'Y11_Q66', 'Kotitalouden odotettu taloudellinen tilanne seuraavien 12 kuukauden aikana'],
		['Julkiset terveyspalvelut', 'Y11_Q42', 'Koettu terveydentila'],
		['Julkiset terveyspalvelut', 'Y11_Q46a', 'Olen tuntenut oloni hyvin jännittyneeksi'],
		['Julkiset terveyspalvelut', 'Y11_Q46b', 'Olen tuntenut oloni yksinäiseksi'],
		['Julkiset terveyspalvelut', 'Y11_Q46c', 'Olen tuntenut oloni alakuloiseksi ja masentuneeksi'],
		['Julkiset terveyspalvelut', 'Y11_Q46d_WHO5', 'Psyykkisen hyvinvoinnin WHO-5-indeksi'],
		['Julkiset terveyspalvelut', 'Y11_Q47a', 'Etäisyyden aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Julkiset terveyspalvelut', 'Y11_Q47b', 'Vastaanottoajan saamisen viivytyksen aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Julkiset terveyspalvelut', 'Y11_Q47c', 'Vastaanottopäivän odotusajan aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Julkiset terveyspalvelut', 'Y11_Q47d', 'Kustannusten aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Julkiset terveyspalvelut', 'Y11_Q47e', 'Ajanpuutteen aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Julkiset terveyspalvelut', 'Y11_Q53a', 'Miten laadukkaaksi arvioisitte kotimaanne terveydenhuoltopalvelut?'],
		['Julkiset terveyspalvelut', 'Y11_Q53b', 'Miten laadukkaaksi arvioisitte kotimaanne koulutusjärjestelmän?'],
		['Julkiset terveyspalvelut', 'Y11_Q53c', 'Miten laadukkaaksi arvioisitte kotimaanne julkisen liikenteen?'],
		['Julkiset terveyspalvelut', 'Y11_Q53d', 'Miten laadukkaaksi arvioisitte kotimaanne lastenhoitopalvelut?'],
		['Julkiset terveyspalvelut', 'Y11_Q53e', 'Miten laadukkaaksi arvioisitte kotimaanne pitkäaikaishoidon palvelut?'],
		['Julkiset terveyspalvelut', 'Y11_Q53f', 'Miten laadukkaaksi arvioisitte kotimaanne sosiaaliset asumispalvelut?'],
		['Julkiset terveyspalvelut', 'Y11_Q53g', 'Miten laadukkaaksi arvioisitte kotimaanne kansaneläkejärjestelmän?'],
		['Koti ja lähiympäristö', 'Y11_Accommproblems', 'Asumisongelmien määrä'],
		['Koti ja lähiympäristö', 'Y11_Q18', 'Omistusasuminen'],
		['Koti ja lähiympäristö', 'Y11_Q19a', 'Asumiseen liittyvät ongelmat: tilanpuute'],
		['Koti ja lähiympäristö', 'Y11_Q19b', 'Asumiseen liittyvät ongelmat: lahovaurioita ikkunoissa, ovissa tai lattioissa'],
		['Koti ja lähiympäristö', 'Y11_Q19c', 'Asumiseen liittyvät ongelmat: kosteutta tai vuotoja seinissä tai katossa'],
		['Koti ja lähiympäristö', 'Y11_Q19d', 'Asumiseen liittyvät ongelmat: sisävesivessan puuttuminen'],
		['Koti ja lähiympäristö', 'Y11_Q19e', 'Asumiseen liittyvät ongelmat: suihkun tai ammeen puuttuminen'],
		['Koti ja lähiympäristö', 'Y11_Q19f', 'Asumiseen liittyvät ongelmat: ulkona olevan oleskelutilan puuttuminen'],
		['Koti ja lähiympäristö', 'Y11_Q20', 'Miten todennäköisesti joudutte luopumaan asunnostanne seuraavan puolen vuoden kuluessa, koska teillä ei enää ole varaa siihen?'],
		['Koti ja lähiympäristö', 'Y11_Q50a', 'Asuinalueen melun aiheuttamat ongelmat'],
		['Koti ja lähiympäristö', 'Y11_Q50b', 'Asuinalueen ilmanlaadun aiheuttamat ongelmat'],
		['Koti ja lähiympäristö', 'Y11_Q50c', 'Asuinalueen vesijohtoveden laadun aiheuttamat ongelmat'],
		['Koti ja lähiympäristö', 'Y11_Q50d', 'Asuinalueen rikollisuuden, väkivallan tai ilkivallan aiheuttamat ongelmat'],
		['Koti ja lähiympäristö', 'Y11_Q50e', 'Katujen roskaisuuden aiheuttamat ongelmat'],
		['Koti ja lähiympäristö', 'Y11_Q50f', 'Asuinalueen liikenneruuhkien aiheuttamat ongelmat'],
		['Koti ja lähiympäristö', 'Y11_Q51a', 'Postipalvelujen saavutettavuus'],
		['Koti ja lähiympäristö', 'Y11_Q51b', 'Pankkipalvelujen saavutettavuus'],
		['Koti ja lähiympäristö', 'Y11_Q51c', 'Julkisen liikenteen palvelujen saavutettavuus'],
		['Koti ja lähiympäristö', 'Y11_Q51d', 'Elokuvateatterin, teatterin tai kulttuurikeskuksen saavutettavuus'],
		['Koti ja lähiympäristö', 'Y11_Q51e', 'Virkistys- tai viheralueiden saavutettavuus'],
		['Koti ja lähiympäristö', 'Y11_Q52', 'Työ- tai koulumatkoihin kuluva aika'],
		['Perhe ja sosiaalinen elämä', 'Y11_Q33a', 'Henkilökohtainen yhteydenpito kotitalouden ulkopuolella asuviin lapsiin'],
		['Perhe ja sosiaalinen elämä', 'Y11_Q33b', 'Henkilökohtainen yhteydenpito kotitalouden ulkopuolella asuvaan äitiin tai isään'],
		['Perhe ja sosiaalinen elämä', 'Y11_Q33c', 'Henkilökohtainen yhteydenpito muihin kotitalouden ulkopuolella asuviin sukulaisiin'],
		['Perhe ja sosiaalinen elämä', 'Y11_Q33d', 'Henkilökohtainen yhteydenpito ystäviin ja naapureihin'],
		['Perhe ja sosiaalinen elämä', 'Y11_Q34a', 'Yhteydenpito kotitalouden ulkopuolella asuviin lapsiin puhelimitse, postitse tai internetin avulla'],
		['Perhe ja sosiaalinen elämä', 'Y11_Q34b', 'Yhteydenpito kotitalouden ulkopuolella asuvaan äitiin tai isään puhelimitse, postitse tai internetin avulla'],
		['Perhe ja sosiaalinen elämä', 'Y11_Q34c', 'Yhteydenpito kotitalouden ulkopuolella asuviin muihin sukulaisiin puhelimitse, postitse tai internetin avulla'],
		['Perhe ja sosiaalinen elämä', 'Y11_Q34d', 'Yhteydenpito ystäviin ja naapureihin puhelimitse, postitse tai internetin avulla'],
		['Perhe ja sosiaalinen elämä', 'Y11_Q35a', 'Keneltä saatte tukea, jos olette sairaana ja tarvitsette apua kotona?'],
		['Perhe ja sosiaalinen elämä', 'Y11_Q35b', 'Keneltä saatte tukea, jos tarvitsette neuvoa vakavasta henkilökohtaisesta tai perheeseen liittyvästä asiasta?'],
		['Perhe ja sosiaalinen elämä', 'Y11_Q35c', 'Keneltä saatte tukea, jos tarvitsette apua työnhaussa?'],
		['Perhe ja sosiaalinen elämä', 'Y11_Q35d', 'Keneltä saatte tukea, jos olo on vähän masentunut?'],
		['Perhe ja sosiaalinen elämä', 'Y11_Q35e', 'Keneltä saatte tukea, jos tarvitsette pikaisesti 1 000 euroa?'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q21a', 'Osallistuminen kirkollisiin toimituksiin, pois lukien häät, hautajaiset ja kastetilaisuudet'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q21b', 'Internetin käyttö muuhun kuin työhön'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q21c', 'Urheilu ja kuntoilu'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q21d', 'Osallistuminen sosiaalisiin tapahtumiin kerhossa, yhteisössä tai järjestössä'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q22_Volunteering', 'Kuinka usein osallistuitte palkattomaan vapaaehtoistyöhön viimeksi kuluneiden 12 kuukauden aikana?'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q23a', 'Osallistunut ammattiliiton, poliittisen puolueen tai toimintaryhmän kokoukseen'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q23b', 'Osallistunut mielenosoitukseen tai mielenilmaisuun viimeisten 12 kuukauden aikana'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q23c', 'Allekirjoittanut vetoomuksen viimeisten 12 kuukauden aikana'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q23d', 'Ottanut yhteyttä poliitikkoon tai virkamieheen (muu kuin julkisten palveluiden käyttöön liittyvä tavanomainen yhteydenotto)'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q29e', 'Tunnen olevani yhteiskunnan ulkopuolella'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q29f', 'Elämä on nykyään niin monimutkaista, että olen vähällä eksyä'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q29g', 'Muut eivät tunnu antavan arvoa tekemisilleni'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q29h', 'Jotkut halveksivat minua työtilanteeni tai ansiotasoni vuoksi'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q29i', 'Tunnen läheisyyttä asuinalueeni ihmisiin'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_SocExIndex', 'Sosiaaliseen syrjäytymisen indeksi'],
		['Subjektiivinen hyvinvointi', 'Y11_Q29a', 'Olen optimistinen tulevaisuuden suhteen'],
		['Subjektiivinen hyvinvointi', 'Y11_Q29b', 'Koen yleisesti ottaen, että elämäni ja tekemiseni ovat arvokkaita'],
		['Subjektiivinen hyvinvointi', 'Y11_Q29c', 'Koen voivani vapaasti päättää, miten elän elämäni'],
		['Subjektiivinen hyvinvointi', 'Y11_Q29d', 'Minulla on jokapäiväisessä elämässäni harvoin aikaa asioille, joista todella nautin'],
		['Subjektiivinen hyvinvointi', 'Y11_Q30', 'Miten tyytyväinen olette elämäänne nykyään?'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40a', 'Tyytyväisyys koulutukseen'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40b', 'Tyytyväisyys nykyiseen työhön'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40c', 'Tyytyväisyys nykyiseen elintasoon'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40d', 'Tyytyväisyys asuntoon'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40e', 'Tyytyväisyys perhe-elämään'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40f', 'Tyytyväisyys terveydentilaan'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40g', 'Tyytyväisyys sosiaaliseen elämään'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40h', 'Tyytyväisyys maan taloudelliseen tilaan'],
		['Subjektiivinen hyvinvointi', 'Y11_Q41', 'Miten onnelliseksi arvioitte itsenne kaiken kaikkiaan?'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q8_PreferredWorkingHours', 'Montako tuntia viikossa haluaisitte itse työskennellä?'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q10_Partnerprefhours', 'Montako tuntia viikossa haluaisitte kumppaninne työskentelevän?'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q12a', 'Olen ollut liian väsynyt tekemään kotitöitä työpäivän jälkeen'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q12b', 'Perheeseen liittyvien velvollisuuksien täyttäminen on ollut hankalaa töissä vietetyn ajan vuoksi'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q12c', 'Perheeseen liittyvät velvollisuudet ovat vaikeuttaneet keskittymistä työpaikalla'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q13a', 'Voin vaihdella työni aloitus- ja lopetusaikoja'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q13b', 'Voin kerätä työtunteja käytettäväksi vapaana'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q13c', 'Voin tarvittaessa pitää vapaapäivän lyhyellä varoitusajalla'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q15', 'Miten todennäköisesti voitte menettää työpaikkanne seuraavan puolen vuoden kuluessa?'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q16', 'Jos menettäisitte työpaikkanne, kuinka todennäköisesti löytäisitte työn, josta maksetaan samaa palkkaa kuin nykyisestä?'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q36a', 'Kuinka usein osallistutte lastenne tai lastenlastenne hoitamiseen?'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q36b', 'Kuinka usein osallistutte ruoanlaittoon tai kotitöihin?'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q36c', 'Kuinka usein hoidatte vanhoja tai vammaisia sukulaisianne?'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q38', 'Mielipide kotitöiden jakamisesta'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q39a', 'Mielipide perheenjäsenten kanssa vietetystä ajasta'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q39b', 'Mielipide muiden parissa vietetystä ajasta'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q39c', 'Mielipide omien harrastusten ja mielenkiinnon kohteiden parissa vietetystä ajasta'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q39d_stress', 'Stressi'],
		['Yhteiskunnan laatu', 'Y11_Q24', 'Voiko mielestänne suurimpaan osaan ihmisistä luottaa vai oletteko sitä mieltä, ettei kanssakäynnissä ihmisten kanssa voi olla liian varovainen?'],
		['Yhteiskunnan laatu', 'Y11_Q25a', 'Havaittu jännite köyhien ja rikkaiden välillä'],
		['Yhteiskunnan laatu', 'Y11_Q25b', 'Havaittu jännite johtoportaan ja työntekijöiden välillä'],
		['Yhteiskunnan laatu', 'Y11_Q25c', 'Havaittu jännite miesten ja naisten välillä'],
		['Yhteiskunnan laatu', 'Y11_Q25d', 'Havaittu jännite vanhojen ja nuorten ihmisten välillä'],
		['Yhteiskunnan laatu', 'Y11_Q25e', 'Havaittu jännite eri rodullisten ja etnisten ryhmien väillä'],
		['Yhteiskunnan laatu', 'Y11_Q25f', 'Havaittu jännite eri uskonnollisten ryhmien välillä'],
		['Yhteiskunnan laatu', 'Y11_Q25g', 'Havaittu jännite seksuaalisesti eri tavoin suuntautuneiden ihmisten välillä'],
		['Yhteiskunnan laatu', 'Y11_Q28a', 'Luottamus eduskuntaan'],
		['Yhteiskunnan laatu', 'Y11_Q28b', 'Luottamus oikeusjärjestelmään'],
		['Yhteiskunnan laatu', 'Y11_Q28c', 'Luottamus lehdistöön'],
		['Yhteiskunnan laatu', 'Y11_Q28d', 'Luottamus poliisiin'],
		['Yhteiskunnan laatu', 'Y11_Q28e', 'Luottamus hallitukseen'],
		['Yhteiskunnan laatu', 'Y11_Q28f', 'Luottamus paikallisiin tai kunnallisiin päättäjiin']
	];
var question_
	 = [
	
		['Y11_Deprindex', 'Huono-osaisuuden indeksi: määrä asioista, joihin kotitalouksilla ei ole varaa'],
		['Y11_Q57', 'Kotitalouden taloudellinen tilanne verrattuna kotimaan yleiseen tilanteeseen'],
		['Y11_Q58', 'Ovatko kotitaloutenne tulot riittävät?'],
		['Y11_Q59a', 'Onko teillä varaa pitää koti riittävän lämpimänä?'],
		['Y11_Q59b', 'Onko teillä varaa vuosittaiseen lomaviikkoon poissa kotoa?'],
		['Y11_Q59c', 'Onko teillä varaa vaihtaa mikä tahansa kulunut huonekalu uuteen?'],
		['Y11_Q59d', 'Onko teillä varaa liha-, kana- tai kala-ateriaan joka toinen päivä (niin halutessanne)?'],
		['Y11_Q59e', 'Onko teillä varaa ostaa uusia vaatteita käytettyjen sijaan?'],
		['Y11_Q59f', 'Onko teillä varaa kutsua ystäviä tai sukulaisia lasilliselle tai aterialle vähintään kerran kuussa?'],
		['Y11_Q60a', 'Onko kotitaloudella ollut asunnon vuokran tai asuntolainan maksuerän maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?'],
		['Y11_Q60b', 'Onko kotitaloudella ollut yleisiin asumiseen liittyvien kulujen maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?'],
		['Y11_Q60c', 'Onko kotitaloudella ollut kulutusluoton lyhennysten maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?'],
		['Y11_Q60d', 'Onko kotitaloudella ollut epävirallisten lainojen maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?'],
		['Y11_Q65', 'Kotitalouden taloudellinen tilanne verrattuna 12 kuukauden takaiseen'],
		['Y11_Q66', 'Kotitalouden odotettu taloudellinen tilanne seuraavien 12 kuukauden aikana'],
		['Y11_Q42', 'Koettu terveydentila'],
		['Y11_Q46a', 'Olen tuntenut oloni hyvin jännittyneeksi'],
		['Y11_Q46b', 'Olen tuntenut oloni yksinäiseksi'],
		['Y11_Q46c', 'Olen tuntenut oloni alakuloiseksi ja masentuneeksi'],
		['Y11_Q46d_WHO5', 'Psyykkisen hyvinvoinnin WHO-5-indeksi'],
		['Y11_Q47a', 'Etäisyyden aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Y11_Q47b', 'Vastaanottoajan saamisen viivytyksen aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Y11_Q47c', 'Vastaanottopäivän odotusajan aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Y11_Q47d', 'Kustannusten aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Y11_Q47e', 'Ajanpuutteen aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Y11_Q53a', 'Miten laadukkaaksi arvioisitte kotimaanne terveydenhuoltopalvelut?'],
		['Y11_Q53b', 'Miten laadukkaaksi arvioisitte kotimaanne koulutusjärjestelmän?'],
		['Y11_Q53c', 'Miten laadukkaaksi arvioisitte kotimaanne julkisen liikenteen?'],
		['Y11_Q53d', 'Miten laadukkaaksi arvioisitte kotimaanne lastenhoitopalvelut?'],
		['Y11_Q53e', 'Miten laadukkaaksi arvioisitte kotimaanne pitkäaikaishoidon palvelut?'],
		['Y11_Q53f', 'Miten laadukkaaksi arvioisitte kotimaanne sosiaaliset asumispalvelut?'],
		['Y11_Q53g', 'Miten laadukkaaksi arvioisitte kotimaanne kansaneläkejärjestelmän?'],
		['Y11_Accommproblems', 'Asumisongelmien määrä'],
		['Y11_Q18', 'Omistusasuminen'],
		['Y11_Q19a', 'Asumiseen liittyvät ongelmat: tilanpuute'],
		['Y11_Q19b', 'Asumiseen liittyvät ongelmat: lahovaurioita ikkunoissa, ovissa tai lattioissa'],
		['Y11_Q19c', 'Asumiseen liittyvät ongelmat: kosteutta tai vuotoja seinissä tai katossa'],
		['Y11_Q19d', 'Asumiseen liittyvät ongelmat: sisävesivessan puuttuminen'],
		['Y11_Q19e', 'Asumiseen liittyvät ongelmat: suihkun tai ammeen puuttuminen'],
		['Y11_Q19f', 'Asumiseen liittyvät ongelmat: ulkona olevan oleskelutilan puuttuminen'],
		['Y11_Q20', 'Miten todennäköisesti joudutte luopumaan asunnostanne seuraavan puolen vuoden kuluessa, koska teillä ei enää ole varaa siihen?'],
		['Y11_Q50a', 'Asuinalueen melun aiheuttamat ongelmat'],
		['Y11_Q50b', 'Asuinalueen ilmanlaadun aiheuttamat ongelmat'],
		['Y11_Q50c', 'Asuinalueen vesijohtoveden laadun aiheuttamat ongelmat'],
		['Y11_Q50d', 'Asuinalueen rikollisuuden, väkivallan tai ilkivallan aiheuttamat ongelmat'],
		['Y11_Q50e', 'Katujen roskaisuuden aiheuttamat ongelmat'],
		['Y11_Q50f', 'Asuinalueen liikenneruuhkien aiheuttamat ongelmat'],
		['Y11_Q51a', 'Postipalvelujen saavutettavuus'],
		['Y11_Q51b', 'Pankkipalvelujen saavutettavuus'],
		['Y11_Q51c', 'Julkisen liikenteen palvelujen saavutettavuus'],
		['Y11_Q51d', 'Elokuvateatterin, teatterin tai kulttuurikeskuksen saavutettavuus'],
		['Y11_Q51e', 'Virkistys- tai viheralueiden saavutettavuus'],
		['Y11_Q52', 'Työ- tai koulumatkoihin kuluva aika'],
		['Y11_Q33a', 'Henkilökohtainen yhteydenpito kotitalouden ulkopuolella asuviin lapsiin'],
		['Y11_Q33b', 'Henkilökohtainen yhteydenpito kotitalouden ulkopuolella asuvaan äitiin tai isään'],
		['Y11_Q33c', 'Henkilökohtainen yhteydenpito muihin kotitalouden ulkopuolella asuviin sukulaisiin'],
		['Y11_Q33d', 'Henkilökohtainen yhteydenpito ystäviin ja naapureihin'],
		['Y11_Q34a', 'Yhteydenpito kotitalouden ulkopuolella asuviin lapsiin puhelimitse, postitse tai internetin avulla'],
		['Y11_Q34b', 'Yhteydenpito kotitalouden ulkopuolella asuvaan äitiin tai isään puhelimitse, postitse tai internetin avulla'],
		['Y11_Q34c', 'Yhteydenpito kotitalouden ulkopuolella asuviin muihin sukulaisiin puhelimitse, postitse tai internetin avulla'],
		['Y11_Q34d', 'Yhteydenpito ystäviin ja naapureihin puhelimitse, postitse tai internetin avulla'],
		['Y11_Q35a', 'Keneltä saatte tukea, jos olette sairaana ja tarvitsette apua kotona?'],
		['Y11_Q35b', 'Keneltä saatte tukea, jos tarvitsette neuvoa vakavasta henkilökohtaisesta tai perheeseen liittyvästä asiasta?'],
		['Y11_Q35c', 'Keneltä saatte tukea, jos tarvitsette apua työnhaussa?'],
		['Y11_Q35d', 'Keneltä saatte tukea, jos olo on vähän masentunut?'],
		['Y11_Q35e', 'Keneltä saatte tukea, jos tarvitsette pikaisesti 1 000 euroa?'],
		['Y11_Q21a', 'Osallistuminen kirkollisiin toimituksiin, pois lukien häät, hautajaiset ja kastetilaisuudet'],
		['Y11_Q21b', 'Internetin käyttö muuhun kuin työhön'],
		['Y11_Q21c', 'Urheilu ja kuntoilu'],
		['Y11_Q21d', 'Osallistuminen sosiaalisiin tapahtumiin kerhossa, yhteisössä tai järjestössä'],
		['Y11_Q22_Volunteering', 'Kuinka usein osallistuitte palkattomaan vapaaehtoistyöhön viimeksi kuluneiden 12 kuukauden aikana?'],
		['Y11_Q23a', 'Osallistunut ammattiliiton, poliittisen puolueen tai toimintaryhmän kokoukseen'],
		['Y11_Q23b', 'Osallistunut mielenosoitukseen tai mielenilmaisuun viimeisten 12 kuukauden aikana'],
		['Y11_Q23c', 'Allekirjoittanut vetoomuksen viimeisten 12 kuukauden aikana'],
		['Y11_Q23d', 'Ottanut yhteyttä poliitikkoon tai virkamieheen (muu kuin julkisten palveluiden käyttöön liittyvä tavanomainen yhteydenotto)'],
		['Y11_Q29e', 'Tunnen olevani yhteiskunnan ulkopuolella'],
		['Y11_Q29f', 'Elämä on nykyään niin monimutkaista, että olen vähällä eksyä'],
		['Y11_Q29g', 'Muut eivät tunnu antavan arvoa tekemisilleni'],
		['Y11_Q29h', 'Jotkut halveksivat minua työtilanteeni tai ansiotasoni vuoksi'],
		['Y11_Q29i', 'Tunnen läheisyyttä asuinalueeni ihmisiin'],
		['Y11_SocExIndex', 'Sosiaaliseen syrjäytymisen indeksi'],
		['Y11_Q29a', 'Olen optimistinen tulevaisuuden suhteen'],
		['Y11_Q29b', 'Koen yleisesti ottaen, että elämäni ja tekemiseni ovat arvokkaita'],
		['Y11_Q29c', 'Koen voivani vapaasti päättää, miten elän elämäni'],
		['Y11_Q29d', 'Minulla on jokapäiväisessä elämässäni harvoin aikaa asioille, joista todella nautin'],
		['Y11_Q30', 'Miten tyytyväinen olette elämäänne nykyään?'],
		['Y11_Q40a', 'Tyytyväisyys koulutukseen'],
		['Y11_Q40b', 'Tyytyväisyys nykyiseen työhön'],
		['Y11_Q40c', 'Tyytyväisyys nykyiseen elintasoon'],
		['Y11_Q40d', 'Tyytyväisyys asuntoon'],
		['Y11_Q40e', 'Tyytyväisyys perhe-elämään'],
		['Y11_Q40f', 'Tyytyväisyys terveydentilaan'],
		['Y11_Q40g', 'Tyytyväisyys sosiaaliseen elämään'],
		['Y11_Q40h', 'Tyytyväisyys maan taloudelliseen tilaan'],
		['Y11_Q41', 'Miten onnelliseksi arvioitte itsenne kaiken kaikkiaan?'],
		['Y11_Q8_PreferredWorkingHours', 'Montako tuntia viikossa haluaisitte itse työskennellä?'],
		['Y11_Q10_Partnerprefhours', 'Montako tuntia viikossa haluaisitte kumppaninne työskentelevän?'],
		['Y11_Q12a', 'Olen ollut liian väsynyt tekemään kotitöitä työpäivän jälkeen'],
		['Y11_Q12b', 'Perheeseen liittyvien velvollisuuksien täyttäminen on ollut hankalaa töissä vietetyn ajan vuoksi'],
		['Y11_Q12c', 'Perheeseen liittyvät velvollisuudet ovat vaikeuttaneet keskittymistä työpaikalla'],
		['Y11_Q13a', 'Voin vaihdella työni aloitus- ja lopetusaikoja'],
		['Y11_Q13b', 'Voin kerätä työtunteja käytettäväksi vapaana'],
		['Y11_Q13c', 'Voin tarvittaessa pitää vapaapäivän lyhyellä varoitusajalla'],
		['Y11_Q15', 'Miten todennäköisesti voitte menettää työpaikkanne seuraavan puolen vuoden kuluessa?'],
		['Y11_Q16', 'Jos menettäisitte työpaikkanne, kuinka todennäköisesti löytäisitte työn, josta maksetaan samaa palkkaa kuin nykyisestä?'],
		['Y11_Q36a', 'Kuinka usein osallistutte lastenne tai lastenlastenne hoitamiseen?'],
		['Y11_Q36b', 'Kuinka usein osallistutte ruoanlaittoon tai kotitöihin?'],
		['Y11_Q36c', 'Kuinka usein hoidatte vanhoja tai vammaisia sukulaisianne?'],
		['Y11_Q38', 'Mielipide kotitöiden jakamisesta'],
		['Y11_Q39a', 'Mielipide perheenjäsenten kanssa vietetystä ajasta'],
		['Y11_Q39b', 'Mielipide muiden parissa vietetystä ajasta'],
		['Y11_Q39c', 'Mielipide omien harrastusten ja mielenkiinnon kohteiden parissa vietetystä ajasta'],
		['Y11_Q39d_stress', 'Stressi'],
		['Y11_Q24', 'Voiko mielestänne suurimpaan osaan ihmisistä luottaa vai oletteko sitä mieltä, ettei kanssakäynnissä ihmisten kanssa voi olla liian varovainen?'],
		['Y11_Q25a', 'Havaittu jännite köyhien ja rikkaiden välillä'],
		['Y11_Q25b', 'Havaittu jännite johtoportaan ja työntekijöiden välillä'],
		['Y11_Q25c', 'Havaittu jännite miesten ja naisten välillä'],
		['Y11_Q25d', 'Havaittu jännite vanhojen ja nuorten ihmisten välillä'],
		['Y11_Q25e', 'Havaittu jännite eri rodullisten ja etnisten ryhmien väillä'],
		['Y11_Q25f', 'Havaittu jännite eri uskonnollisten ryhmien välillä'],
		['Y11_Q25g', 'Havaittu jännite seksuaalisesti eri tavoin suuntautuneiden ihmisten välillä'],
		['Y11_Q28a', 'Luottamus eduskuntaan'],
		['Y11_Q28b', 'Luottamus oikeusjärjestelmään'],
		['Y11_Q28c', 'Luottamus lehdistöön'],
		['Y11_Q28d', 'Luottamus poliisiin'],
		['Y11_Q28e', 'Luottamus hallitukseen'],
		['Y11_Q28f', 'Luottamus paikallisiin tai kunnallisiin päättäjiin']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Keskiarvo'],
		['Y11_Deprindex', 'Mean', 'Keskiarvo'],
		['Y11_Q10_Partnerprefhours', '1--Work-less', 'Työskennellä vähemmän'],
		['Y11_Q10_Partnerprefhours', '2--Work-the-same', 'Työskennellä saman verran'],
		['Y11_Q10_Partnerprefhours', '3--Work-more', 'Työskennellä enemmän'],
		['Y11_Q12a', '1--Several-times-a-week', 'Useita kertoja viikossa'],
		['Y11_Q12a', '2--Several-times-a-month', 'Useita kertoja kuukaudessa'],
		['Y11_Q12a', '3--Several-times-a-year', 'Useita kertoja vuodessa'],
		['Y11_Q12a', '4--Less-often-rarely', 'Harvemmin'],
		['Y11_Q12a', '5--Never', 'Ei koskaan'],
		['Y11_Q12b', '1--Several-times-a-week', 'Useita kertoja viikossa'],
		['Y11_Q12b', '2--Several-times-a-month', 'Useita kertoja kuukaudessa'],
		['Y11_Q12b', '3--Several-times-a-year', 'Useita kertoja vuodessa'],
		['Y11_Q12b', '4--Less-often-rarely', 'Harvemmin'],
		['Y11_Q12b', '5--Never', 'Ei koskaan'],
		['Y11_Q12c', '1--Several-times-a-week', 'Useita kertoja viikossa'],
		['Y11_Q12c', '2--Several-times-a-month', 'Useita kertoja kuukaudessa'],
		['Y11_Q12c', '3--Several-times-a-year', 'Useita kertoja vuodessa'],
		['Y11_Q12c', '4--Less-often-rarely', 'Harvemmin'],
		['Y11_Q12c', '5--Never', 'Ei koskaan'],
		['Y11_Q13a', '1--Yes', 'Kyllä'],
		['Y11_Q13a', '2--No', 'Ei'],
		['Y11_Q13b', '1--Yes', 'Kyllä'],
		['Y11_Q13b', '2--No', 'Ei'],
		['Y11_Q13c', '1--Yes', 'Kyllä'],
		['Y11_Q13c', '2--No', 'Ei'],
		['Y11_Q15', '1--Very-likely', 'Hyvin todennäköisesti'],
		['Y11_Q15', '2--Quite-likely', 'Melko todennäköisesti'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'En todennäköisesti enkä epätodennäköisesti'],
		['Y11_Q15', '4--Quite-unlikely', 'Melko epätodennäköisesti'],
		['Y11_Q15', '5--Very-unlikely', 'Hyvin epätodennäköisesti'],
		['Y11_Q16', '1--Very-likely', 'Hyvin todennäköisesti'],
		['Y11_Q16', '2--Quite-likely', 'Melko todennäköisesti'],
		['Y11_Q16', '3--Neither-likely-nor-unlikely', 'En todennäköisesti enkä epätodennäköisesti'],
		['Y11_Q16', '4--Quite-unlikely', 'Melko epätodennäköisesti'],
		['Y11_Q16', '5--Very-unlikely', 'Hyvin epätodennäköisesti'],
		['Y11_Q18', '1--Own-without-mortgage', 'Omistusasunto, ei ole asuntolainaa'],
		['Y11_Q18', '2--Own-with-mortgage', 'Omistusasunto, on asuntolainaa'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Vuokralla, kunta tai yhteisö vuokranantajana'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Vuokralla, yksityinen vuokranantaja'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Asuminen järjestetty ilman vuokraa'],
		['Y11_Q18', '6--Other', 'Muu'],
		['Y11_Q19a', '1--Yes', 'Kyllä'],
		['Y11_Q19a', '2--No', 'Ei'],
		['Y11_Q19b', '1--Yes', 'Kyllä'],
		['Y11_Q19b', '2--No', 'Ei'],
		['Y11_Q19c', '1--Yes', 'Kyllä'],
		['Y11_Q19c', '2--No', 'Ei'],
		['Y11_Q19d', '1--Yes', 'Kyllä'],
		['Y11_Q19d', '2--No', 'Ei'],
		['Y11_Q19e', '1--Yes', 'Kyllä'],
		['Y11_Q19e', '2--No', 'Ei'],
		['Y11_Q19f', '1--Yes', 'Kyllä'],
		['Y11_Q19f', '2--No', 'Ei'],
		['Y11_Q20', '1--Very-likely', 'Hyvin todennäköisesti'],
		['Y11_Q20', '2--Quite-likely', 'Melko todennäköisesti'],
		['Y11_Q20', '3--Quite-unlikely', 'Melko epätodennäköisesti'],
		['Y11_Q20', '4--Very-unlikely', 'Hyvin epätodennäköisesti'],
		['Y11_Q21a', '1--Every-day-or-almost-every-day', 'Päivittäin tai lähes päivittäin'],
		['Y11_Q21a', '2--At-least-once-a-week', 'Vähintään kerran viikossa'],
		['Y11_Q21a', '3--One-to-three-times-a-month', 'Yhdestä kolmeen kertaan kuukaudessa'],
		['Y11_Q21a', '4--Less-often', 'Harvemmin'],
		['Y11_Q21a', '5--Never', 'Ei koskaan'],
		['Y11_Q21b', '1--Every-day-or-almost-every-day', 'Päivittäin tai lähes päivittäin'],
		['Y11_Q21b', '2--At-least-once-a-week', 'Vähintään kerran viikossa'],
		['Y11_Q21b', '3--One-to-three-times-a-month', 'Yhdestä kolmeen kertaan kuukaudessa'],
		['Y11_Q21b', '4--Less-often', 'Harvemmin'],
		['Y11_Q21b', '5--Never', 'Ei koskaan'],
		['Y11_Q21c', '1--Every-day-or-almost-every-day', 'Päivittäin tai lähes päivittäin'],
		['Y11_Q21c', '2--At-least-once-a-week', 'Vähintään kerran viikossa'],
		['Y11_Q21c', '3--One-to-three-times-a-month', 'Yhdestä kolmeen kertaan kuukaudessa'],
		['Y11_Q21c', '4--Less-often', 'Harvemmin'],
		['Y11_Q21c', '5--Never', 'Ei koskaan'],
		['Y11_Q21d', '1--Every-day-or-almost-every-day', 'Päivittäin tai lähes päivittäin'],
		['Y11_Q21d', '2--At-least-once-a-week', 'Vähintään kerran viikossa'],
		['Y11_Q21d', '3--One-to-three-times-a-month', 'Yhdestä kolmeen kertaan kuukaudessa'],
		['Y11_Q21d', '4--Less-often', 'Harvemmin'],
		['Y11_Q21d', '5--Never', 'Ei koskaan'],
		['Y11_Q22_Volunteering', '1--Volunteers-regularly', 'Tekee vapaaehtoistyötä säännöllisesti'],
		['Y11_Q22_Volunteering', '2--Volunteers-occasionally', 'Tekee vapaaehtoistyötä satunnaisesti'],
		['Y11_Q22_Volunteering', '3--Does-not-volunteer', 'Ei tee vapaaehtoistyötä'],
		['Y11_Q23a', '1--Yes', 'Kyllä'],
		['Y11_Q23a', '2--No', 'Ei'],
		['Y11_Q23b', '1--Yes', 'Kyllä'],
		['Y11_Q23b', '2--No', 'Ei'],
		['Y11_Q23c', '1--Yes', 'Kyllä'],
		['Y11_Q23c', '2--No', 'Ei'],
		['Y11_Q23d', '1--Yes', 'Kyllä'],
		['Y11_Q23d', '2--No', 'Ei'],
		['Y11_Q24', 'Mean', 'Keskiarvo'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Paljon jännitteitä'],
		['Y11_Q25a', '2--Some-tension', 'Jonkin verran jännitteitä'],
		['Y11_Q25a', '3--No-tension', 'Ei jännitteitä'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Paljon jännitteitä'],
		['Y11_Q25b', '2--Some-tension', 'Jonkin verran jännitteitä'],
		['Y11_Q25b', '3--No-tension', 'Ei jännitteitä'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Paljon jännitteitä'],
		['Y11_Q25c', '2--Some-tension', 'Jonkin verran jännitteitä'],
		['Y11_Q25c', '3--No-tension', 'Ei jännitteitä'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Paljon jännitteitä'],
		['Y11_Q25d', '2--Some-tension', 'Jonkin verran jännitteitä'],
		['Y11_Q25d', '3--No-tension', 'Ei jännitteitä'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Paljon jännitteitä'],
		['Y11_Q25e', '2--Some-tension', 'Jonkin verran jännitteitä'],
		['Y11_Q25e', '3--No-tension', 'Ei jännitteitä'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Paljon jännitteitä'],
		['Y11_Q25f', '2--Some-tension', 'Jonkin verran jännitteitä'],
		['Y11_Q25f', '3--No-tension', 'Ei jännitteitä'],
		['Y11_Q25g', '1--A-lot-of--tension', 'Paljon jännitteitä'],
		['Y11_Q25g', '2--Some-tension', 'Jonkin verran jännitteitä'],
		['Y11_Q25g', '3--No-tension', 'Ei jännitteitä'],
		['Y11_Q28a', 'Mean', 'Keskiarvo'],
		['Y11_Q28b', 'Mean', 'Keskiarvo'],
		['Y11_Q28c', 'Mean', 'Keskiarvo'],
		['Y11_Q28d', 'Mean', 'Keskiarvo'],
		['Y11_Q28e', 'Mean', 'Keskiarvo'],
		['Y11_Q28f', 'Mean', 'Keskiarvo'],
		['Y11_Q29a', '1--Strongly-agree', 'Täysin samaa mieltä'],
		['Y11_Q29a', '2--Agree', 'Samaa mieltä'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Ei samaa eikä eri mieltä'],
		['Y11_Q29a', '4--Disagree', 'Eri mieltä'],
		['Y11_Q29a', '5--Strongly-disagree', 'Täysin eri mieltä'],
		['Y11_Q29b', '1--Strongly-agree', 'Täysin samaa mieltä'],
		['Y11_Q29b', '2--Agree', 'Samaa mieltä'],
		['Y11_Q29b', '3--Neither-agree-nor-disagree', 'Ei samaa eikä eri mieltä'],
		['Y11_Q29b', '4--Disagree', 'Eri mieltä'],
		['Y11_Q29b', '5--Strongly-disagree', 'Täysin eri mieltä'],
		['Y11_Q29c', '1--Strongly-agree', 'Täysin samaa mieltä'],
		['Y11_Q29c', '2--Agree', 'Samaa mieltä'],
		['Y11_Q29c', '3--Neither-agree-nor-disagree', 'Ei samaa eikä eri mieltä'],
		['Y11_Q29c', '4--Disagree', 'Eri mieltä'],
		['Y11_Q29c', '5--Strongly-disagree', 'Täysin eri mieltä'],
		['Y11_Q29d', '1--Strongly-agree', 'Täysin samaa mieltä'],
		['Y11_Q29d', '2--Agree', 'Samaa mieltä'],
		['Y11_Q29d', '3--Neither-agree-nor-disagree', 'Ei samaa eikä eri mieltä'],
		['Y11_Q29d', '4--Disagree', 'Eri mieltä'],
		['Y11_Q29d', '5--Strongly-disagree', 'Täysin eri mieltä'],
		['Y11_Q29e', '1--Strongly-agree', 'Täysin samaa mieltä'],
		['Y11_Q29e', '2--Agree', 'Samaa mieltä'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Ei samaa eikä eri mieltä'],
		['Y11_Q29e', '4--Disagree', 'Eri mieltä'],
		['Y11_Q29e', '5--Strongly-disagree', 'Täysin eri mieltä'],
		['Y11_Q29f', '1--Strongly-agree', 'Täysin samaa mieltä'],
		['Y11_Q29f', '2--Agree', 'Samaa mieltä'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Ei samaa eikä eri mieltä'],
		['Y11_Q29f', '4--Disagree', 'Eri mieltä'],
		['Y11_Q29f', '5--Strongly-disagree', 'Täysin eri mieltä'],
		['Y11_Q29g', '1--Strongly-agree', 'Täysin samaa mieltä'],
		['Y11_Q29g', '2--Agree', 'Samaa mieltä'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Ei samaa eikä eri mieltä'],
		['Y11_Q29g', '4--Disagree', 'Eri mieltä'],
		['Y11_Q29g', '5--Strongly-disagree', 'Täysin eri mieltä'],
		['Y11_Q29h', '1--Strongly-agree', 'Täysin samaa mieltä'],
		['Y11_Q29h', '2--Agree', 'Samaa mieltä'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Ei samaa eikä eri mieltä'],
		['Y11_Q29h', '4--Disagree', 'Eri mieltä'],
		['Y11_Q29h', '5--Strongly-disagree', 'Täysin eri mieltä'],
		['Y11_Q29i', '1--Strongly-agree', 'Täysin samaa mieltä'],
		['Y11_Q29i', '2--Agree', 'Samaa mieltä'],
		['Y11_Q29i', '3--Neither-agree-nor-disagree', 'Ei samaa eikä eri mieltä'],
		['Y11_Q29i', '4--Disagree', 'Eri mieltä'],
		['Y11_Q29i', '5--Strongly-disagree', 'Täysin eri mieltä'],
		['Y11_Q30', 'Mean', 'Keskiarvo'],
		['Y11_Q33a', '1--Every-day-or-almost-every-day', 'Päivittäin tai lähes päivittäin'],
		['Y11_Q33a', '2--At-least-once-a-week', 'Vähintään kerran viikossa'],
		['Y11_Q33a', '3--One-to-three-times-a-month', 'Yhdestä kolmeen kertaa kuukaudessa'],
		['Y11_Q33a', '4--Less-often', 'Harvemmin'],
		['Y11_Q33a', '5--Never', 'Ei koskaan'],
		['Y11_Q33b', '1--Every-day-or-almost-every-day', 'Päivittäin tai lähes päivittäin'],
		['Y11_Q33b', '2--At-least-once-a-week', 'Vähintään kerran viikossa'],
		['Y11_Q33b', '3--One-to-three-times-a-month', 'Yhdestä kolmeen kertaa kuukaudessa'],
		['Y11_Q33b', '4--Less-often', 'Harvemmin'],
		['Y11_Q33b', '5--Never', 'Ei koskaan'],
		['Y11_Q33c', '1--Every-day-or-almost-every-day', 'Päivittäin tai lähes päivittäin'],
		['Y11_Q33c', '2--At-least-once-a-week', 'Vähintään kerran viikossa'],
		['Y11_Q33c', '3--One-to-three-times-a-month', 'Yhdestä kolmeen kertaa kuukaudessa'],
		['Y11_Q33c', '4--Less-often', 'Harvemmin'],
		['Y11_Q33c', '5--Never', 'Ei koskaan'],
		['Y11_Q33d', '1--Every-day-or-almost-every-day', 'Päivittäin tai lähes päivittäin'],
		['Y11_Q33d', '2--At-least-once-a-week', 'Vähintään kerran viikossa'],
		['Y11_Q33d', '3--One-to-three-times-a-month', 'Yhdestä kolmeen kertaa kuukaudessa'],
		['Y11_Q33d', '4--Less-often', 'Harvemmin'],
		['Y11_Q33d', '5--Never', 'Ei koskaan'],
		['Y11_Q34a', '1--Every-day-or-almost-every-day', 'Päivittäin tai lähes päivittäin'],
		['Y11_Q34a', '2--At-least-once-a-week', 'Vähintään kerran viikossa'],
		['Y11_Q34a', '3--One-to-three-times-a-month', 'Yhdestä kolmeen kertaa kuukaudessa'],
		['Y11_Q34a', '4--Less-often', 'Harvemmin'],
		['Y11_Q34a', '5--Never', 'Ei koskaan'],
		['Y11_Q34b', '1--Every-day-or-almost-every-day', 'Päivittäin tai lähes päivittäin'],
		['Y11_Q34b', '2--At-least-once-a-week', 'Vähintään kerran viikossa'],
		['Y11_Q34b', '3--One-to-three-times-a-month', 'Yhdestä kolmeen kertaa kuukaudessa'],
		['Y11_Q34b', '4--Less-often', 'Harvemmin'],
		['Y11_Q34b', '5--Never', 'Ei koskaan'],
		['Y11_Q34c', '1--Every-day-or-almost-every-day', 'Päivittäin tai lähes päivittäin'],
		['Y11_Q34c', '2--At-least-once-a-week', 'Vähintään kerran viikossa'],
		['Y11_Q34c', '3--One-to-three-times-a-month', 'Yhdestä kolmeen kertaa kuukaudessa'],
		['Y11_Q34c', '4--Less-often', 'Harvemmin'],
		['Y11_Q34c', '5--Never', 'Ei koskaan'],
		['Y11_Q34d', '1--Every-day-or-almost-every-day', 'Päivittäin tai lähes päivittäin'],
		['Y11_Q34d', '2--At-least-once-a-week', 'Vähintään kerran viikossa'],
		['Y11_Q34d', '3--One-to-three-times-a-month', 'Yhdestä kolmeen kertaa kuukaudessa'],
		['Y11_Q34d', '4--Less-often', 'Harvemmin'],
		['Y11_Q34d', '5--Never', 'Ei koskaan'],
		['Y11_Q35a', '1--A-member-of-your-family', 'Perheenjäseneltä tai sukulaiselta'],
		['Y11_Q35a', '2--A-friend--neighbour--or-someone-else', 'Ystävältä, naapurilta tai joltakulta muulta'],
		['Y11_Q35a', '3--A-service-provider--institution-or-organisation', 'Palveluntarjoajalta, instituutiolta tai organisaatiolta'],
		['Y11_Q35a', '4--Nobody', 'En keneltäkään'],
		['Y11_Q35b', '1--A-member-of-your-family', 'Perheenjäseneltä tai sukulaiselta'],
		['Y11_Q35b', '2--A-friend--neighbour--or-someone-else', 'Ystävältä, naapurilta tai joltakulta muulta'],
		['Y11_Q35b', '3--A-service-provider--institution-or-organisation', 'Palveluntarjoajalta, instituutiolta tai organisaatiolta'],
		['Y11_Q35b', '4--Nobody', 'En keneltäkään'],
		['Y11_Q35c', '1--A-member-of-your-family', 'Perheenjäseneltä tai sukulaiselta'],
		['Y11_Q35c', '2--A-friend--neighbour--or-someone-else', 'Ystävältä, naapurilta tai joltakulta muulta'],
		['Y11_Q35c', '3--A-service-provider--institution-or-organisation', 'Palveluntarjoajalta, instituutiolta tai organisaatiolta'],
		['Y11_Q35c', '4--Nobody', 'En keneltäkään'],
		['Y11_Q35d', '1--A-member-of-your-family', 'Perheenjäseneltä tai sukulaiselta'],
		['Y11_Q35d', '2--A-friend--neighbour--or-someone-else', 'Ystävältä, naapurilta tai joltakulta muulta'],
		['Y11_Q35d', '3--A-service-provider--institution-or-organisation', 'Palveluntarjoajalta, instituutiolta tai organisaatiolta'],
		['Y11_Q35d', '4--Nobody', 'En keneltäkään'],
		['Y11_Q35e', '1--A-member-of-your-family', 'Perheenjäseneltä tai sukulaiselta'],
		['Y11_Q35e', '2--A-friend--neighbour--or-someone-else', 'Ystävältä, naapurilta tai joltakulta muulta'],
		['Y11_Q35e', '3--A-service-provider--institution-or-organisation', 'Palveluntarjoajalta, instituutiolta tai organisaatiolta'],
		['Y11_Q35e', '4--Nobody', 'En keneltäkään'],
		['Y11_Q36a', '1--Every-day', 'Päivittäin'],
		['Y11_Q36a', '2--Several-days-a-week', 'Useita kertoja viikossa'],
		['Y11_Q36a', '3--Once-or-twice-a-week', 'Kerran tai kaksi viikossa'],
		['Y11_Q36a', '4--Less-often', 'Harvemmin'],
		['Y11_Q36a', '5--Never', 'En koskaan'],
		['Y11_Q36b', '1--Every-day', 'Päivittäin'],
		['Y11_Q36b', '2--Several-days-a-week', 'Useita kertoja viikossa'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'Kerran tai kaksi viikossa'],
		['Y11_Q36b', '4--Less-often', 'Harvemmin'],
		['Y11_Q36b', '5--Never', 'En koskaan'],
		['Y11_Q36c', '1--Every-day', 'Päivittäin'],
		['Y11_Q36c', '2--Several-days-a-week', 'Useita kertoja viikossa'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'Kerran tai kaksi viikossa'],
		['Y11_Q36c', '4--Less-often', 'Harvemmin'],
		['Y11_Q36c', '5--Never', 'En koskaan'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Teen enemmän kuin kohtuullisen osuuteni'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Teen kohtuullisen osuuteni'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Teen vähemmän kuin kohtuullisen osuuteni'],
		['Y11_Q39a', '1--Spend-more-time', 'Haluaisin käyttää enemmän aikaa'],
		['Y11_Q39a', '2--As-much-as-I-currently-do', 'Nykyisin käyttämäni ajan määrä on sopiva'],
		['Y11_Q39a', '3--Spend-less-time', 'Haluaisin käyttää vähemmän aikaa'],
		['Y11_Q39b', '1--Spend-more-time', 'Haluaisin käyttää enemmän aikaa'],
		['Y11_Q39b', '2--As-much-as-I-currently-do', 'Nykyisin käyttämäni ajan määrä on sopiva'],
		['Y11_Q39b', '3--Spend-less-time', 'Haluaisin käyttää vähemmän aikaa'],
		['Y11_Q39c', '1--Spend-more-time', 'Haluaisin käyttää enemmän aikaa'],
		['Y11_Q39c', '2--As-much-as-I-currently-do', 'Nykyisin käyttämäni ajan määrä on sopiva'],
		['Y11_Q39c', '3--Spend-less-time', 'Haluaisin käyttää vähemmän aikaa'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'Työpaikalla ja kotona'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Joko työpaikalla tai kotona'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Vähän tai ei lainkaan stressiä'],
		['Y11_Q40a', 'Mean', 'Keskiarvo'],
		['Y11_Q40b', 'Mean', 'Keskiarvo'],
		['Y11_Q40c', 'Mean', 'Keskiarvo'],
		['Y11_Q40d', 'Mean', 'Keskiarvo'],
		['Y11_Q40e', 'Mean', 'Keskiarvo'],
		['Y11_Q40f', 'Mean', 'Keskiarvo'],
		['Y11_Q40g', 'Mean', 'Keskiarvo'],
		['Y11_Q40h', 'Mean', 'Keskiarvo'],
		['Y11_Q41', 'Mean', 'Keskiarvo'],
		['Y11_Q42', '1--Very-good', 'Erittäin hyvä'],
		['Y11_Q42', '2--Good', 'Hyvä'],
		['Y11_Q42', '3--Fair', 'Kohtalainen'],
		['Y11_Q42', '4--Bad', 'Huono'],
		['Y11_Q42', '5--Very-bad', 'Erittäin huono'],
		['Y11_Q46a', '1--All-of-the-time', 'Koko ajan'],
		['Y11_Q46a', '2--Most-of-the-time', 'Suurimman osan aikaa'],
		['Y11_Q46a', '3--More-than-half-of-the-time', 'Yli puolet ajasta'],
		['Y11_Q46a', '4--Less-than-half-of-the-time', 'Alle puolet ajasta'],
		['Y11_Q46a', '5--Some-of-the-time', 'Joskus'],
		['Y11_Q46a', '6--At-no-time', 'Ei koskaan'],
		['Y11_Q46b', '1--All-of-the-time', 'Koko ajan'],
		['Y11_Q46b', '2--Most-of-the-time', 'Suurimman osan aikaa'],
		['Y11_Q46b', '3--More-than-half-of-the-time', 'Yli puolet ajasta'],
		['Y11_Q46b', '4--Less-than-half-of-the-time', 'Alle puolet ajasta'],
		['Y11_Q46b', '5--Some-of-the-time', 'Joskus'],
		['Y11_Q46b', '6--At-no-time', 'Ei koskaan'],
		['Y11_Q46c', '1--All-of-the-time', 'Koko ajan'],
		['Y11_Q46c', '2--Most-of-the-time', 'Suurimman osan aikaa'],
		['Y11_Q46c', '3--More-than-half-of-the-time', 'Yli puolet ajasta'],
		['Y11_Q46c', '4--Less-than-half-of-the-time', 'Alle puolet ajasta'],
		['Y11_Q46c', '5--Some-of-the-time', 'Joskus'],
		['Y11_Q46c', '6--At-no-time', 'Ei koskaan'],
		['Y11_Q46d_WHO5', 'Mean', 'Keskiarvo'],
		['Y11_Q47a', '1--Very-difficult', 'Vaikeutti hyvin paljon'],
		['Y11_Q47a', '2--A-little-difficult', 'Vaikeutti jonkin verran'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Ei vaikeuttanut lainkaan'],
		['Y11_Q47b', '1--Very-difficult', 'Vaikeutti hyvin paljon'],
		['Y11_Q47b', '2--A-little-difficult', 'Vaikeutti jonkin verran'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Ei vaikeuttanut lainkaan'],
		['Y11_Q47c', '1--Very-difficult', 'Vaikeutti hyvin paljon'],
		['Y11_Q47c', '2--A-little-difficult', 'Vaikeutti jonkin verran'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Ei vaikeuttanut lainkaan'],
		['Y11_Q47d', '1--Very-difficult', 'Vaikeutti hyvin paljon'],
		['Y11_Q47d', '2--A-little-difficult', 'Vaikeutti jonkin verran'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Ei vaikeuttanut lainkaan'],
		['Y11_Q47e', '1--Very-difficult', 'Vaikeutti hyvin paljon'],
		['Y11_Q47e', '2--A-little-difficult', 'Vaikeutti jonkin verran'],
		['Y11_Q47e', '3--Not-difficult-at-all', 'Ei vaikeuttanut lainkaan'],
		['Y11_Q50a', '1--Major-problems', 'Suuria ongelmia'],
		['Y11_Q50a', '2--Moderate-problems', 'Kohtalaisia ongelmia'],
		['Y11_Q50a', '3--No-problems', 'Ei ongelmia'],
		['Y11_Q50b', '1--Major-problems', 'Suuria ongelmia'],
		['Y11_Q50b', '2--Moderate-problems', 'Kohtalaisia ongelmia'],
		['Y11_Q50b', '3--No-problems', 'Ei ongelmia'],
		['Y11_Q50c', '1--Major-problems', 'Suuria ongelmia'],
		['Y11_Q50c', '2--Moderate-problems', 'Kohtalaisia ongelmia'],
		['Y11_Q50c', '3--No-problems', 'Ei ongelmia'],
		['Y11_Q50d', '1--Major-problems', 'Suuria ongelmia'],
		['Y11_Q50d', '2--Moderate-problems', 'Kohtalaisia ongelmia'],
		['Y11_Q50d', '3--No-problems', 'Ei ongelmia'],
		['Y11_Q50e', '1--Major-problems', 'Suuria ongelmia'],
		['Y11_Q50e', '2--Moderate-problems', 'Kohtalaisia ongelmia'],
		['Y11_Q50e', '3--No-problems', 'Ei ongelmia'],
		['Y11_Q50f', '1--Major-problems', 'Suuria ongelmia'],
		['Y11_Q50f', '2--Moderate-problems', 'Kohtalaisia ongelmia'],
		['Y11_Q50f', '3--No-problems', 'Ei ongelmia'],
		['Y11_Q51a', '1--with-great-difficulty', 'Hyvin vaikeasti saavutettavissa'],
		['Y11_Q51a', '2--with-some-difficulty', 'Melko vaikeasti saavutettavissa'],
		['Y11_Q51a', '3--easily', 'Helposti saavutettavissa'],
		['Y11_Q51a', '4--very-easily', 'Hyvin helposti saavutettavissa'],
		['Y11_Q51b', '1--with-great-difficulty', 'Hyvin vaikeasti saavutettavissa'],
		['Y11_Q51b', '2--with-some-difficulty', 'Melko vaikeasti saavutettavissa'],
		['Y11_Q51b', '3--easily', 'Helposti saavutettavissa'],
		['Y11_Q51b', '4--very-easily', 'Hyvin helposti saavutettavissa'],
		['Y11_Q51c', '1--with-great-difficulty', 'Hyvin vaikeasti saavutettavissa'],
		['Y11_Q51c', '2--with-some-difficulty', 'Melko vaikeasti saavutettavissa'],
		['Y11_Q51c', '3--easily', 'Helposti saavutettavissa'],
		['Y11_Q51c', '4--very-easily', 'Hyvin helposti saavutettavissa'],
		['Y11_Q51d', '1--with-great-difficulty', 'Hyvin vaikeasti saavutettavissa'],
		['Y11_Q51d', '2--with-some-difficulty', 'Melko vaikeasti saavutettavissa'],
		['Y11_Q51d', '3--easily', 'Helposti saavutettavissa'],
		['Y11_Q51d', '4--very-easily', 'Hyvin helposti saavutettavissa'],
		['Y11_Q51e', '1--with-great-difficulty', 'Hyvin vaikeasti saavutettavissa'],
		['Y11_Q51e', '2--with-some-difficulty', 'Melko vaikeasti saavutettavissa'],
		['Y11_Q51e', '3--easily', 'Helposti saavutettavissa'],
		['Y11_Q51e', '4--very-easily', 'Hyvin helposti saavutettavissa'],
		['Y11_Q52', 'Mean', 'Keskiarvo'],
		['Y11_Q53a', 'Mean', 'Keskiarvo'],
		['Y11_Q53b', 'Mean', 'Keskiarvo'],
		['Y11_Q53c', 'Mean', 'Keskiarvo'],
		['Y11_Q53d', 'Mean', 'Keskiarvo'],
		['Y11_Q53e', 'Mean', 'Keskiarvo'],
		['Y11_Q53f', 'Mean', 'Keskiarvo'],
		['Y11_Q53g', 'Mean', 'Keskiarvo'],
		['Y11_Q57', '1--Much-worse', 'Paljon huonompi'],
		['Y11_Q57', '2--Somewhat-worse', 'Jonkin verran huonompi'],
		['Y11_Q57', '3--Neither-worse-nor-better', 'Ei huonompi eikä parempi'],
		['Y11_Q57', '4--Somewhat-better', 'Jonkin verran parempi'],
		['Y11_Q57', '5--Much-better', 'Paljon parempi'],
		['Y11_Q58', '1--With-great-difficulty', 'Hyvin vaikeasti'],
		['Y11_Q58', '2--With-difficulty', 'Vaikeasti'],
		['Y11_Q58', '3--With-some-difficulty', 'Jonkin verran vaikeasti'],
		['Y11_Q58', '4--Fairly-easily', 'Melko helposti'],
		['Y11_Q58', '5--Easily', 'Helposti'],
		['Y11_Q58', '6--Very-easily', 'Hyvin helposti'],
		['Y11_Q59a', '1--No', 'Ei'],
		['Y11_Q59a', '2--Yes', 'Kyllä'],
		['Y11_Q59b', '1--No', 'Ei'],
		['Y11_Q59b', '2--Yes', 'Kyllä'],
		['Y11_Q59c', '1--No', 'Ei'],
		['Y11_Q59c', '2--Yes', 'Kyllä'],
		['Y11_Q59d', '1--No', 'Ei'],
		['Y11_Q59d', '2--Yes', 'Kyllä'],
		['Y11_Q59e', '1--No', 'Ei'],
		['Y11_Q59e', '2--Yes', 'Kyllä'],
		['Y11_Q59f', '1--No', 'Ei'],
		['Y11_Q59f', '2--Yes', 'Kyllä'],
		['Y11_Q60a', '1--Yes', 'Kyllä'],
		['Y11_Q60a', '2--No', 'Ei'],
		['Y11_Q60b', '1--Yes', 'Kyllä'],
		['Y11_Q60b', '2--No', 'Ei'],
		['Y11_Q60c', '1--Yes', 'Kyllä'],
		['Y11_Q60c', '2--No', 'Ei'],
		['Y11_Q60d', '1--Yes', 'Kyllä'],
		['Y11_Q60d', '2--No', 'Ei'],
		['Y11_Q65', '1--Better', 'Parantunut'],
		['Y11_Q65', '2--The-same', 'Pysynyt samana'],
		['Y11_Q65', '3--Worse', 'Heikontunut'],
		['Y11_Q66', '1--Better', 'Parantunut'],
		['Y11_Q66', '2--The-same', 'Pysynyt samana'],
		['Y11_Q66', '3--Worse', 'Heikontunut'],
		['Y11_Q8_PreferredWorkingHours', '1--Work-less', 'Työskennellä vähemmän'],
		['Y11_Q8_PreferredWorkingHours', '2--Work-the-same', 'Työskennellä saman verran'],
		['Y11_Q8_PreferredWorkingHours', '3--Work-more', 'Työskennellä enemmän'],
		['Y11_SocExIndex', 'Mean', 'Keskiarvo']
	];
var country_
	 = [
	
		['AT', 'Itävalta'],
		['BE', 'Belgia'],
		['BG', 'Bulgaria'],
		['CY', 'Kypros'],
		['CZ', 'Tšekki'],
		['DE', 'Saksa'],
		['DK', 'Tanska'],
		['EE', 'Viro'],
		['EL', 'Kreikka'],
		['ES', 'Espanja'],
		['FI', 'Suomi'],
		['FR', 'Ranska'],
		['HR', 'Kroatia'],
		['HU', 'Unkari'],
		['IE', 'Irlanti'],
		['IS', 'Islanti'],
		['IT', 'Italia'],
		['LT', 'Liettua'],
		['LU', 'Luxemburg'],
		['LV', 'Latvia'],
		['ME', 'Montenegro'],
		['MK', 'EJTM'],
		['MT', 'Malta'],
		['NL', 'Alankomaat'],
		['PL', 'Puola'],
		['PT', 'Portugali'],
		['RO', 'Romania'],
		['RS', 'Serbia'],
		['SE', 'Ruotsi'],
		['SI', 'Slovenia'],
		['SK', 'Slovakia'],
		['TR', 'Turkki'],
		['UK', 'Yhdistynyt kuningaskunta'],
		['XK', 'Kosovo'],
		['EuropeanUnion', 'Euroopan unioni']
	];
var question_meta
	 = [
	
		['Y11_Deprindex', 'Huono-osaisuuden indeksi: määrä asioista, joihin kotitalouksilla ei ole varaa', ''],
		['Y11_Q57', 'Kotitalouden taloudellinen tilanne verrattuna kotimaan yleiseen tilanteeseen', ''],
		['Y11_Q58', 'Ovatko kotitaloutenne tulot riittävät?', ''],
		['Y11_Q59a', 'Onko teillä varaa pitää koti riittävän lämpimänä?', ''],
		['Y11_Q59b', 'Onko teillä varaa vuosittaiseen lomaviikkoon poissa kotoa?', ''],
		['Y11_Q59c', 'Onko teillä varaa vaihtaa mikä tahansa kulunut huonekalu uuteen?', ''],
		['Y11_Q59d', 'Onko kotitaloudella varaa liha-, kana- tai kala-ateriaan joka toinen päivä (niin halutessanne)?', ''],
		['Y11_Q59e', 'Onko kotitalouden jäsenillä varaa ostaa uusia vaatteita käytettyjen sijaan?', ''],
		['Y11_Q59f', 'Onko kotitaloudella varaa kutsua ystäviä tai sukulaisia lasilliselle tai aterialle vähintään kerran kuussa?', ''],
		['Y11_Q60a', 'Onko kotitaloudella ollut asunnon vuokran tai asuntolainan maksuerän maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?', ''],
		['Y11_Q60b', 'Onko kotitaloudella ollut yleisiin asumiseen liittyvien kulujen maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?', ''],
		['Y11_Q60c', 'Onko kotitaloudella ollut kulutusluoton lyhennysten maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?', ''],
		['Y11_Q60d', 'Onko kotitaloudella ollut epävirallisten lainojen maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?', ''],
		['Y11_Q65', 'Kotitalouden taloudellinen tilanne verrattuna 12 kuukauden takaiseen', ''],
		['Y11_Q66', 'Kotitalouden odotettu taloudellinen tilanne seuraavien 12 kuukauden aikana', ''],
		['Y11_Q42', 'Koettu terveydentila', ''],
		['Y11_Q46a', 'Olen tuntenut oloni hyvin jännittyneeksi', ''],
		['Y11_Q46b', 'Olen tuntenut oloni yksinäiseksi', ''],
		['Y11_Q46c', 'Olen tuntenut oloni alakuloiseksi ja masentuneeksi', ''],
		['Y11_Q46d_WHO5', 'Psyykkisen hyvinvoinnin WHO-5-indeksi', ''],
		['Y11_Q47a', 'Lääkäriin pääsyn vaikeus, koska lääkärin vastaanotto tai sairaala on kaukana', ''],
		['Y11_Q47b', 'Vastaanottoajan saamisen viivytyksen aiheuttamat ongelmat lääkäriin pääsyssä', ''],
		['Y11_Q47c', 'Lääkäriin pääsyn vaikeus, koska vastaanottopäivänä joutui odottamaan', ''],
		['Y11_Q47d', 'Lääkäriin pääsyn vaikeus lääkärikäynnin hinnan vuoksi', ''],
		['Y11_Q47e', 'Lääkäriin pääsyn vaikeus työstä tai hoitovelvoitteista johtuvan ajanpuutteen vuoksi', ''],
		['Y11_Q53a', 'Miten laadukkaaksi arvioisitte kotimaanne terveydenhuoltopalvelut?', ''],
		['Y11_Q53b', 'Miten laadukkaaksi arvioisitte kotimaanne koulutusjärjestelmän?', ''],
		['Y11_Q53c', 'Miten laadukkaaksi arvioisitte kotimaanne julkisen liikenteen?', ''],
		['Y11_Q53d', 'Miten laadukkaaksi arvioisitte kotimaanne lastenhoitopalvelut?', ''],
		['Y11_Q53e', 'Miten laadukkaaksi arvioisitte kotimaanne pitkäaikaishoidon palvelut?', ''],
		['Y11_Q53f', 'Miten laadukkaaksi arvioisitte kotimaanne sosiaaliset asumispalvelut?', ''],
		['Y11_Q53g', 'Miten laadukkaaksi arvioisitte kotimaanne kansaneläkejärjestelmän?', ''],
		['Y11_Accommproblems', 'Asumisongelmien määrä', ''],
		['Y11_Q18', 'Omistusasuminen', ''],
		['Y11_Q19a', 'Asumiseen liittyvät ongelmat: tilanpuute', ''],
		['Y11_Q19b', 'Asumiseen liittyvät ongelmat: lahovaurioita ikkunoissa, ovissa tai lattioissa', ''],
		['Y11_Q19c', 'Asumiseen liittyvät ongelmat: kosteutta tai vuotoja seinissä tai katossa', ''],
		['Y11_Q19d', 'Asumiseen liittyvät ongelmat: sisävesivessan puuttuminen', ''],
		['Y11_Q19e', 'Asumiseen liittyvät ongelmat: suihkun tai ammeen puuttuminen', ''],
		['Y11_Q19f', 'Asumiseen liittyvät ongelmat: ulkona olevan oleskelutilan puuttuminen', ''],
		['Y11_Q20', 'Miten todennäköisesti joudutte luopumaan asunnostanne seuraavan puolen vuoden kuluessa, koska teillä ei enää ole varaa siihen?', ''],
		['Y11_Q50a', 'Asuinalueen melun aiheuttamat ongelmat', ''],
		['Y11_Q50b', 'Asuinalueen ilmanlaadun aiheuttamat ongelmat', ''],
		['Y11_Q50c', 'Asuinalueen vesijohtoveden laadun aiheuttamat ongelmat', ''],
		['Y11_Q50d', 'Asuinalueen rikollisuuden, väkivallan tai ilkivallan aiheuttamat ongelmat', ''],
		['Y11_Q50e', 'Asuinalueen katujen roskaisuuden aiheuttamat ongelmat', ''],
		['Y11_Q50f', 'Asuinalueen liikenneruuhkien aiheuttamat ongelmat', ''],
		['Y11_Q51a', 'Postipalvelujen saavutettavuus', ''],
		['Y11_Q51b', 'Pankkipalvelujen saavutettavuus', ''],
		['Y11_Q51c', 'Julkisen liikenteen palvelujen saavutettavuus', ''],
		['Y11_Q51d', 'Elokuvateatterin, teatterin tai kulttuurikeskuksen saavutettavuus', ''],
		['Y11_Q51e', 'Virkistys- tai viheralueiden saavutettavuus', ''],
		['Y11_Q52', 'Työ- tai koulumatkoihin kuluva aika', ''],
		['Y11_Q33a', 'Henkilökohtainen yhteydenpito kotitalouden ulkopuolella asuviin lapsiin', ''],
		['Y11_Q33b', 'Henkilökohtainen yhteydenpito kotitalouden ulkopuolella asuvaan äitiin tai isään', ''],
		['Y11_Q33c', 'Henkilökohtainen yhteydenpito veljeen, sisareen ja muihin kotitalouden ulkopuolella asuviin sukulaisiin', ''],
		['Y11_Q33d', 'Henkilökohtainen yhteydenpito naapureihin ja kotitalouden ulkopuolella asuviin ystäviin', ''],
		['Y11_Q34a', 'Yhteydenpito kotitalouden ulkopuolella asuviin lapsiin puhelimitse, postitse tai internetin avulla', ''],
		['Y11_Q34b', 'Yhteydenpito kotitalouden ulkopuolella asuvaan äitiin tai isään puhelimitse, postitse tai internetin avulla', ''],
		['Y11_Q34c', 'Yhteydenpito veljeen, sisareen tai kotitalouden ulkopuolella asuviin muihin sukulaisiin puhelimitse, postitse tai internetin avulla', ''],
		['Y11_Q34d', 'Yhteydenpito naapureihin ja kotitalouden ulkopuolella asuviin ystäviin puhelimitse, postitse tai internetin avulla', ''],
		['Y11_Q35a', 'Keneltä saatte tukea, jos olette sairaana ja tarvitsette apua kotona?', ''],
		['Y11_Q35b', 'Keneltä saatte tukea, jos tarvitsette neuvoa vakavasta henkilökohtaisesta tai perheeseen liittyvästä asiasta?', ''],
		['Y11_Q35c', 'Keneltä saatte tukea, jos tarvitsette apua työnhaussa?', ''],
		['Y11_Q35d', 'Keneltä saatte tukea, jos olo on vähän masentunut ja kaipaatte juttuseuraa?', ''],
		['Y11_Q35e', 'Keneltä saatte tukea, jos tarvitsette pikaisesti 1 000 euroa hätätilanteesta selviytymiseen?', ''],
		['Y11_Q21a', 'Osallistuminen kirkollisiin toimituksiin, pois lukien häät, hautajaiset ja kastetilaisuudet', ''],
		['Y11_Q21b', 'Internetin käyttö muuhun kuin työhön', ''],
		['Y11_Q21c', 'Urheilu ja kuntoilu', ''],
		['Y11_Q21d', 'Osallistuminen sosiaalisiin tapahtumiin kerhossa, yhteisössä tai järjestössä', ''],
		['Y11_Q22_Volunteering', 'Kuinka usein osallistuitte palkattomaan vapaaehtoistyöhön viimeksi kuluneiden 12 kuukauden aikana?', ''],
		['Y11_Q23a', 'Osallistunut ammattiliiton, poliittisen puolueen tai toimintaryhmän kokoukseen', ''],
		['Y11_Q23b', 'Osallistunut mielenosoitukseen tai mielenilmaisuun viimeisten 12 kuukauden aikana', ''],
		['Y11_Q23c', 'Allekirjoittanut vetoomuksen, mukaan lukien vetoomukset sähköpostitse tai internetissä, viimeisten 12 kuukauden aikana', ''],
		['Y11_Q23d', 'Ottanut yhteyttä poliitikkoon tai virkamieheen (muu kuin julkisten palveluiden käyttöön liittyvä tavanomainen yhteydenotto)', ''],
		['Y11_Q29e', 'Tunnen olevani yhteiskunnan ulkopuolella', ''],
		['Y11_Q29f', 'Elämä on nykyään niin monimutkaista, että olen vähällä eksyä', ''],
		['Y11_Q29g', 'Muut eivät tunnu antavan arvoa tekemisilleni', ''],
		['Y11_Q29h', 'Jotkut halveksivat minua työtilanteeni tai ansiotasoni vuoksi', ''],
		['Y11_Q29i', 'Tunnen läheisyyttä asuinalueeni ihmisiin', ''],
		['Y11_SocExIndex', 'Sosiaaliseen syrjäytymisen indeksi', ''],
		['Y11_Q29a', 'Olen optimistinen tulevaisuuden suhteen', ''],
		['Y11_Q29b', 'Koen yleisesti ottaen, että elämäni ja tekemiseni ovat arvokkaita', ''],
		['Y11_Q29c', 'Koen voivani vapaasti päättää, miten elän elämäni', ''],
		['Y11_Q29d', 'Minulla on jokapäiväisessä elämässäni harvoin aikaa asioille, joista todella nautin', ''],
		['Y11_Q30', 'Miten tyytyväinen olette elämäänne nykyään?', ''],
		['Y11_Q40a', 'Tyytyväisyys koulutukseen', ''],
		['Y11_Q40b', 'Tyytyväisyys nykyiseen työhön', ''],
		['Y11_Q40c', 'Tyytyväisyys nykyiseen elintasoon', ''],
		['Y11_Q40d', 'Tyytyväisyys asuntoon', ''],
		['Y11_Q40e', 'Tyytyväisyys perhe-elämään', ''],
		['Y11_Q40f', 'Tyytyväisyys terveydentilaan', ''],
		['Y11_Q40g', 'Tyytyväisyys sosiaaliseen elämään', ''],
		['Y11_Q40h', 'Tyytyväisyys maan taloudelliseen tilaan', ''],
		['Y11_Q41', 'Miten onnelliseksi arvioit itsesi kaiken kaikkiaan?', ''],
		['Y11_Q8_PreferredWorkingHours', 'Montako tuntia viikossa haluaisitte itse työskennellä?', ''],
		['Y11_Q10_Partnerprefhours', 'Montako tuntia viikossa haluaisitte kumppaninne työskentelevän?', 'Tämä kysymys esitettiin vastaajille, joilla oli samassa taloudessa elävä kumppani.'],
		['Y11_Q12a', 'Olen ollut liian väsynyt tekemään kotitöitä työpäivän jälkeen', ''],
		['Y11_Q12b', 'Perheeseen liittyvien velvollisuuksien täyttäminen on ollut hankalaa töissä vietetyn ajan vuoksi', ''],
		['Y11_Q12c', 'Perheeseen liittyvät velvollisuudet ovat vaikeuttaneet keskittymistä työpaikalla', ''],
		['Y11_Q13a', 'Voin vaihdella työni aloitus- ja lopetusaikoja', ''],
		['Y11_Q13b', 'Voin kerätä työtunteja käytettäväksi vapaana', ''],
		['Y11_Q13c', 'Voin tarvittaessa pitää vapaapäivän lyhyellä varoitusajalla', ''],
		['Y11_Q15', 'Miten todennäköisesti voitte menettää työpaikkanne seuraavan puolen vuoden kuluessa?', ''],
		['Y11_Q16', 'Jos menettäisitte työpaikkanne, kuinka todennäköisesti löytäisitte työn, josta maksetaan samaa palkkaa kuin nykyisestä?', 'Tämä kysymys esitettiin vastaajille, jotka olivat palkkatyössä.'],
		['Y11_Q36a', 'Kuinka usein osallistutte lastenne tai lastenlastenne hoitamiseen?', ''],
		['Y11_Q36b', 'Kuinka usein osallistutte ruoanlaittoon tai kotitöihin?', ''],
		['Y11_Q36c', 'Kuinka usein hoidatte vanhoja tai vammaisia sukulaisianne?', ''],
		['Y11_Q38', 'Mitä mieltä olette tekemienne kotitöiden osuudesta?', ''],
		['Y11_Q39a', 'Mielipide perheenjäsenten kanssa vietetystä ajasta', ''],
		['Y11_Q39b', 'Mielipide muiden sosiaalisten kontaktien parissa vietetystä ajasta', ''],
		['Y11_Q39c', 'Mielipide omien harrastusten ja mielenkiinnon kohteiden parissa vietetystä ajasta', ''],
		['Y11_Q39d_stress', 'Työ- ja yksityiselämän tasapainottelusta johtuva stressi', ''],
		['Y11_Q24', 'Voiko mielestänne suurimpaan osaan ihmisistä luottaa vai oletteko sitä mieltä, ettei kanssakäynnissä ihmisten kanssa voi olla liian varovainen?', ''],
		['Y11_Q25a', 'Havaittu jännite köyhien ja rikkaiden välillä', ''],
		['Y11_Q25b', 'Havaittu jännite johtoportaan ja työntekijöiden välillä', ''],
		['Y11_Q25c', 'Havaittu jännite miesten ja naisten välillä', ''],
		['Y11_Q25d', 'Havaittu jännite vanhojen ja nuorten ihmisten välillä', ''],
		['Y11_Q25e', 'Havaittu jännite eri rodullisten ja etnisten ryhmien väillä', ''],
		['Y11_Q25f', 'Havaittu jännite eri uskonnollisten ryhmien välillä', ''],
		['Y11_Q25g', 'Havaittu jännite seksuaalisesti eri tavoin suuntautuneiden ihmisten välillä', ''],
		['Y11_Q28a', 'Luottamus eduskuntaan', ''],
		['Y11_Q28b', 'Luottamus oikeusjärjestelmään', ''],
		['Y11_Q28c', 'Luottamus lehdistöön', ''],
		['Y11_Q28d', 'Luottamus poliisiin', ''],
		['Y11_Q28e', 'Luottamus hallitukseen', ''],
		['Y11_Q28f', 'Trust in the local or municipal authorities', '']
	];
