//Auto Generated file
var subset_
	 = [
	
		['Y11_HH2a', 'Dzimums'],
		['Y11_Incomequartiles_percapita', 'Ieņēmumi'],
		['Y11_Agecategory', 'Vecums']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Visi vecumi'],
		['Y11_Agecategory', '1--18-24y', '18–24 gadi'],
		['Y11_Agecategory', '2--25-34y', '25–34  gadi'],
		['Y11_Agecategory', '3--35-49y', '35–49 gadi'],
		['Y11_Agecategory', '4--50-64y', '50–64 gadi'],
		['Y11_Agecategory', '5---64y', '> 64 gadi'],
		['Y11_HH2a', 'All', 'Abi dzimumi'],
		['Y11_HH2a', '1--Female', 'Sieviete'],
		['Y11_HH2a', '2--Male', 'Vīrietis'],
		['Y11_Incomequartiles_percapita', 'All', 'Visi ienākumu līmeņi'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Zemākie'],
		['Y11_Incomequartiles_percapita', '2--2nd', '2.'],
		['Y11_Incomequartiles_percapita', '3--3rd', '3.'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Augstākie']
	];
var topic_
	 = [
	
		['', 'Visas (127)'],
		['Dzīves līmenis un trūkumi', 'Dzīves līmenis un trūkumi (15)'],
		['Mājas un apkārtējā vide', 'Mājas un apkārtējā vide (21)'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Nodarbinātība un darba un privātās dzīves līdzsvars (18)'],
		['Sabiedrības kvalitāte', 'Sabiedrības kvalitāte (14)'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Sociālā atstumtība un sabiedrības iesaistīšanās (15)'],
		['Subjektīvā labklājība', 'Subjektīvā labklājība (14)'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Veselības aprūpe un sociālie pakalpojumi (17)'],
		['Ģimene un sociālā dzīve', 'Ģimene un sociālā dzīve (13)']
	];
var topic_question
	 = [
	
		['Dzīves līmenis un trūkumi', 'Y11_Deprindex', 'Maznodrošinātības indekss: mājsaimniecībā trūkstošo lietu skaits'],
		['Dzīves līmenis un trūkumi', 'Y11_Q57', 'Mājsaimniecības finanšu situācija, salīdzinot ar lielāko daļu cilvēku valstī'],
		['Dzīves līmenis un trūkumi', 'Y11_Q58', 'Vai Jūsu mājsaimniecība var savilkt galus kopā?'],
		['Dzīves līmenis un trūkumi', 'Y11_Q59a', 'Vai varat atļauties savu māju uzturēt pietiekami siltu?'],
		['Dzīves līmenis un trūkumi', 'Y11_Q59b', 'Vai varat atļauties katru gadu samaksāt par nedēļu ilgām brīvdienām ārpus mājas?'],
		['Dzīves līmenis un trūkumi', 'Y11_Q59c', 'Vai varat atļauties aizstāt nolietotas mēbeles?'],
		['Dzīves līmenis un trūkumi', 'Y11_Q59d', 'Vai varat atļauties maltīti ar gaļu, vistu vai zivi katru otro dienu (ja Jūs to vēlētos)?'],
		['Dzīves līmenis un trūkumi', 'Y11_Q59e', 'Vai varat atļauties iegādāties jaunu, nevis lietotu apģērbu?'],
		['Dzīves līmenis un trūkumi', 'Y11_Q59f', 'Vai varat atļauties uzaicināt pie sevis draugus vai ģimeni uz kādu dzērienu vai maltīti vismaz reizi mēnesī'],
		['Dzīves līmenis un trūkumi', 'Y11_Q60a', 'Vai Jūsu mājsaimniecībai pēdējo 12 mēnešu laikā ir bijuši parādi par īri vai hipotekārajiem maksājumiem?'],
		['Dzīves līmenis un trūkumi', 'Y11_Q60b', 'Vai Jūsu mājsaimniecībai pēdējo 12 mēnešu laikā ir bijuši parādi par komunālo pakalpojumu rēķiniem?'],
		['Dzīves līmenis un trūkumi', 'Y11_Q60c', 'Vai Jūsu mājsaimniecībai pēdējo 12 mēnešu laikā ir bijuši parādi par patēriņa kredītiem?'],
		['Dzīves līmenis un trūkumi', 'Y11_Q60d', 'Vai Jūsu mājsaimniecībai pēdējo 12 mēnešu laikā ir bijuši parādi par neoficiāliem aizņēmumiem?'],
		['Dzīves līmenis un trūkumi', 'Y11_Q65', 'Mājsaimniecības finanšu situācija, salīdzinot ar to, kā bija pirms 12 mēnešiem'],
		['Dzīves līmenis un trūkumi', 'Y11_Q66', 'Gaidāmā finanšu situācija nākamajiem 12 mēnešiem'],
		['Mājas un apkārtējā vide', 'Y11_Accommproblems', 'Daudz problēmu sakarā ar dzīves apstākļiem'],
		['Mājas un apkārtējā vide', 'Y11_Q18', 'Mājas īpašumtiesības'],
		['Mājas un apkārtējā vide', 'Y11_Q19a', 'Problēmas ar mājvietu: Šaurība'],
		['Mājas un apkārtējā vide', 'Y11_Q19b', 'Problēmas ar mājvietu: Puve logu rāmjos, durvīs vai grīdās'],
		['Mājas un apkārtējā vide', 'Y11_Q19c', 'Problēmas ar mājvietu: Mitrums vai sūces sienās vai griestos'],
		['Mājas un apkārtējā vide', 'Y11_Q19d', 'Problēmas ar mājvietu: Iekštelpās nav ar ūdeni skalojamās tualetes'],
		['Mājas un apkārtējā vide', 'Y11_Q19e', 'Problēmas ar mājvietu: Nav vannas vai dušas'],
		['Mājas un apkārtējā vide', 'Y11_Q19f', 'Problēmas ar mājvietu: Trūkst vietas, kur pasēdēt ārā'],
		['Mājas un apkārtējā vide', 'Y11_Q20', 'Cik ļoti ticams ir tas, ka Jums nākamo sešu mēnešu laikā var nākties pamest savu mājokli tāpēc, ka Jūs to nevarat atļauties?'],
		['Mājas un apkārtējā vide', 'Y11_Q50a', 'Problēmas ar troksni apkaimē'],
		['Mājas un apkārtējā vide', 'Y11_Q50b', 'Problēmas ar gaisa kvalitāti apkaimē'],
		['Mājas un apkārtējā vide', 'Y11_Q50c', 'Problēmas ar dzeramā ūdens kvalitāti apkaimē'],
		['Mājas un apkārtējā vide', 'Y11_Q50d', 'Problēmas ar noziedzību, vardarbību un vandalismu apkaimē'],
		['Mājas un apkārtējā vide', 'Y11_Q50e', 'Problēmas ar nekārtību vai atkritumiem uz ielas'],
		['Mājas un apkārtējā vide', 'Y11_Q50f', 'Problēmas ar satiksmes sastrēgumiem apkaimē'],
		['Mājas un apkārtējā vide', 'Y11_Q51a', 'Pasta pakalpojumu pieejamība'],
		['Mājas un apkārtējā vide', 'Y11_Q51b', 'Bankas pakalpojumu pieejamība'],
		['Mājas un apkārtējā vide', 'Y11_Q51c', 'Sabiedriskā transporta pieejamība'],
		['Mājas un apkārtējā vide', 'Y11_Q51d', 'Kino, teātra vai kultūras centra pieejamība'],
		['Mājas un apkārtējā vide', 'Y11_Q51e', 'Atpūtas vai zaļo zonu pieejamība'],
		['Mājas un apkārtējā vide', 'Y11_Q52', 'Laiks, kas tiek pavadīts, lai nokļūtu līdz darbam vai mācību vietai'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q8_PreferredWorkingHours', 'Cik stundas nedēļā Jūs gribētu strādāt?'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q10_Partnerprefhours', 'Cik stundas nedēļā Jūs gribētu, lai Jūsu partneris strādā?'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q12a', 'Pārnācu mājās no darba pārāk noguris(‐usi), lai veiktu mājsaimniecības darbus'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q12b', 'Man ir bijis grūti izpildīt mājās veicamos pienākumus, jo daudz laika pavadu darbā '],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q12c', 'Man ir bijis grūti koncentrēties darbam mājās veicamo pienākumu dēļ'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q13a', 'Es varu regulēt savu darba laiku'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q13b', 'Es varu uzkrāt stundas brīvdienām'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q13c', 'Es varu paņemt brīvu dienu bez iepriekšējas organizēšanas, kad man tas ir vajadzīgs '],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q15', 'Cik lielā mērā ir iespējams, ka Jūs varētu zaudēt darbu nākamo sešu mēnešu laikā?'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q16', 'Ja Jūs zaudētu darbu, cik lielā mērā ir iespējams, ka Jūs atrastu darbu ar līdzīgu atalgojumu?'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q36a', 'Cik bieži Jūs esat iesaistīts(-a) rūpēs par Jūsu bērniem vai mazbērniem?'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q36b', 'Cik bieži Jūs gatavojat vai veicat mājsaimniecības darbus?'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q36c', 'Cik bieži Jūs esat iesaistīts(-a) rūpēs par saviem vecajiem vai nespējīgajiem radiniekiem?'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q38', 'Attieksme pret mājsaimniecības darbu dalīšanu'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q39a', 'Attieksme pret laiku, kas pavadīts kopā ar ģimenes locekļiem'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q39b', 'Attieksme pret laiku, kas pavadīts kopā ar citiem'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q39c', 'Attieksme pret laiku, kas veltīts saviem hobijiem un interesēm'],
		['Nodarbinātība un darba un privātās dzīves līdzsvars', 'Y11_Q39d_stress', 'Stress'],
		['Sabiedrības kvalitāte', 'Y11_Q24', 'Vai varat teikt, ka varat uzticēties lielākajai daļai cilvēku vai ka attiecībās ar cilvēkiem ir jābūt piesardzīgam?'],
		['Sabiedrības kvalitāte', 'Y11_Q25a', 'Apzinātas saspīlētas attiecības starp nabadzīgiem un bagātiem cilvēkiem'],
		['Sabiedrības kvalitāte', 'Y11_Q25b', 'Apzinātas saspīlētas attiecības starp vadītājiem un darbiniekiem'],
		['Sabiedrības kvalitāte', 'Y11_Q25c', 'Apzinātas saspīlētas attiecības starp vīriešiem un sievietēm'],
		['Sabiedrības kvalitāte', 'Y11_Q25d', 'Apzinātas saspīlētas attiecības starp veciem cilvēkiem un jauniem cilvēkiem'],
		['Sabiedrības kvalitāte', 'Y11_Q25e', 'Apzinātas saspīlētas attiecības starp dažādām rasēm un etniskām grupām'],
		['Sabiedrības kvalitāte', 'Y11_Q25f', 'Apzinātas saspīlētas attiecības starp dažādām reliģiskajām grupām'],
		['Sabiedrības kvalitāte', 'Y11_Q25g', 'Apzinātas saspīlētas attiecības starp cilvēkiem ar atšķirīgu seksuālo orientāciju'],
		['Sabiedrības kvalitāte', 'Y11_Q28a', 'Ticība parlamentam'],
		['Sabiedrības kvalitāte', 'Y11_Q28b', 'Ticība tiesu sistēmai'],
		['Sabiedrības kvalitāte', 'Y11_Q28c', 'Ticība presei'],
		['Sabiedrības kvalitāte', 'Y11_Q28d', 'Ticība policijai'],
		['Sabiedrības kvalitāte', 'Y11_Q28e', 'Ticība valdībai'],
		['Sabiedrības kvalitāte', 'Y11_Q28f', 'Ticība vietējai pašvaldībai'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_Q21a', 'Piedalīšanās dievkalpojumos, izņemot kāzu, bēru, kristību ceremonijas'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_Q21b', 'Interneta lietošana ar darbu nesaistītām vajadzībām'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_Q21c', 'Piedalīšanās sporta vai fiziskajās nodarbībās'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_Q21d', 'Piedalīšanās kāda kluba, biedrības vai asociācijas sabiedriskajās aktivitātēs'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_Q22_Volunteering', 'Cik bieži esat veicis(-kusi) neapmaksātu brīvprātīgo darbu pēdējo 12 mēnešu laikā?'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_Q23a', 'Esat piedalījies(-usies) arodbiedrības, politiskās partijas vai rīcības grupas sanāksmē pēdējo 12 mēnešu laikā'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_Q23b', 'Esat apmeklējis(-usi) protesta akciju vai demonstrāciju pēdējo 12 mēnešu laikā'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_Q23c', 'Esat parakstījis(-usi) petīciju pēdējo 12 mēnešu laikā'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_Q23d', 'Esat sazinājies(-usies) ar politiķi vai valsts ierēdni (cita iemesla dēļ, nevis ikdienas situācijās izmantojot sabiedrisko iestāžu pakalpojumus)'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_Q29e', 'Es jūtos sabiedrības atstumts(-a)'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_Q29f', 'Dzīve mūsdienās ir kļuvusi tik sarežģīta, ka es gandrīz nevaru atrast savu ceļu'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_Q29g', 'Es jūtu, ka citi nesaskata vērtību tajā, ko es daru'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_Q29h', 'Daži cilvēki uz mani skatās no augšas mana darba vai ienākumu dēļ'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_Q29i', 'Jūtos tuvs(‐a) savas dzīvesvietas cilvēkiem'],
		['Sociālā atstumtība un sabiedrības iesaistīšanās', 'Y11_SocExIndex', 'Sociālās atstumtības indekss'],
		['Subjektīvā labklājība', 'Y11_Q29a', 'Esmu optimistiski noskaņots(-a) par nākotni'],
		['Subjektīvā labklājība', 'Y11_Q29b', 'Vispār, es jūtu, ka tas, ko dzīvē daru, ir vērtīgs'],
		['Subjektīvā labklājība', 'Y11_Q29c', 'Es jūtu, ka varu izlemt, kā dzīvot savu dzīvi'],
		['Subjektīvā labklājība', 'Y11_Q29d', 'Ikdienas dzīvē man reti ir laiks darīt to, kas man patīk'],
		['Subjektīvā labklājība', 'Y11_Q30', 'Cik apmierināts(-a) Jūs šobrīd esat ar savu dzīvi?'],
		['Subjektīvā labklājība', 'Y11_Q40a', 'Apmierinātība ar izglītību'],
		['Subjektīvā labklājība', 'Y11_Q40b', 'Apmierinātība ar pašreizējo darbu'],
		['Subjektīvā labklājība', 'Y11_Q40c', 'Apmierinātība ar pašreizējo dzīves līmeni'],
		['Subjektīvā labklājība', 'Y11_Q40d', 'Apmierinātība ar mājokli'],
		['Subjektīvā labklājība', 'Y11_Q40e', 'Apmierinātība ar ģimenes dzīvi'],
		['Subjektīvā labklājība', 'Y11_Q40f', 'Apmierinātība ar veselību'],
		['Subjektīvā labklājība', 'Y11_Q40g', 'Apmierinātība ar sabiedrisko dzīvi'],
		['Subjektīvā labklājība', 'Y11_Q40h', 'Apmierinātība ar ekonomisko situāciju valstī'],
		['Subjektīvā labklājība', 'Y11_Q41', 'Ņemot vērā visu kopā, cik laimīgs(-a) Jūs esat?'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q42', 'Apzinātais veselības stāvoklis'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q46a', 'Esmu izjutis(-usi) īpašu spriedzi'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q46b', 'Esmu juties(-usies) vientuļi'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q46c', 'Esmu juties(-usies) drūms(-a) un nomākts(-a)'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q46d_WHO5', 'PVO-5 garīgās labsajūtas skala'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q47a', 'Grūtības apmeklēt ārstu attāluma dēļ'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q47b', 'Grūtības apmeklēt ārstu, jo ilgi jāgaida pieraksts'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q47c', 'Grūtības apmeklēt ārstu, jo pieraksta dienā ir ilgi jāgaida'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q47d', 'Grūtības apmeklēt ārstu izmaksu dēļ'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q47e', 'Grūtības apmeklēt ārstu laika trūkuma dēļ'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q53a', 'Kā Jūs novērtētu veselības aprūpes pakalpojumu kvalitāti savā valstī?'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q53b', 'Kā Jūs novērtētu izglītības sistēmas kvalitāti savā valstī?'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q53c', 'Kā Jūs novērtētu sabiedriskā transporta pakalpojumu kvalitāti savā valstī?'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q53d', 'Kā Jūs novērtētu bērnu aprūpes pakalpojumu kvalitāti savā valstī?'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q53e', 'Kā Jūs novērtētu ilgstošas aprūpes pakalpojumu kvalitāti savā valstī?'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q53f', 'Kā Jūs novērtētu sociālo mājokļu pakalpojumu kvalitāti savā valstī?'],
		['Veselības aprūpe un sociālie pakalpojumi', 'Y11_Q53g', 'Kā Jūs novērtētu valsts pensiju sistēmas kvalitāti savā valstī?'],
		['Ģimene un sociālā dzīve', 'Y11_Q33a', 'Klātienes tikšanās ar bērniem, kuri nedzīvo mājsaimniecībā'],
		['Ģimene un sociālā dzīve', 'Y11_Q33b', 'Klātienes tikšanās ar māti vai tēvu, kuri nedzīvo mājsaimniecībā'],
		['Ģimene un sociālā dzīve', 'Y11_Q33c', 'Klātienes tikšanās ar radiniekiem, kuri nedzīvo mājsaimniecībā'],
		['Ģimene un sociālā dzīve', 'Y11_Q33d', 'Klātienes tikšanās ar draugiem vai kaimiņiem'],
		['Ģimene un sociālā dzīve', 'Y11_Q34a', 'Saziņa ar bērniem, kuri nedzīvo mājsaimniecībā, pa tālruni, internetā vai pa pastu'],
		['Ģimene un sociālā dzīve', 'Y11_Q34b', 'Saziņa ar māti vai tēvu, kuri nedzīvo mājsaimniecībā, pa tālruni, internetā vai pa pastu'],
		['Ģimene un sociālā dzīve', 'Y11_Q34c', 'Saziņa ar citiem radiniekiem, kuri nedzīvo mājsaimniecībā, pa tālruni, internetā vai pa pastu'],
		['Ģimene un sociālā dzīve', 'Y11_Q34d', 'Saziņa ar draugiem vai kaimiņiem pa tālruni, internetā vai pa pastu'],
		['Ģimene un sociālā dzīve', 'Y11_Q35a', 'No kā Jūs varētu saņemt atbalstu, ja Jums būtu vajadzīga palīdzība mājās slimības laikā?'],
		['Ģimene un sociālā dzīve', 'Y11_Q35b', 'No kā Jūs varētu saņemt atbalstu, ja Jums būtu vajadzīgs padoms nopietnā personīgā vai ģimenes jautājumā?'],
		['Ģimene un sociālā dzīve', 'Y11_Q35c', 'No kā Jūs varētu saņemt atbalstu, ja Jums būtu vajadzīga palīdzība, meklējot darbu?'],
		['Ģimene un sociālā dzīve', 'Y11_Q35d', 'No kā Jūs varētu saņemt atbalstu, ja justos nedaudz nomākts(-a)?'],
		['Ģimene un sociālā dzīve', 'Y11_Q35e', 'No kā Jūs varētu saņemt atbalstu, ja Jums steidzami būtu vajadzīgi 1000 euro?']
	];
var question_
	 = [
	
		['Y11_Deprindex', 'Maznodrošinātības indekss: mājsaimniecībā trūkstošo lietu skaits'],
		['Y11_Q57', 'Mājsaimniecības finanšu situācija, salīdzinot ar lielāko daļu cilvēku valstī'],
		['Y11_Q58', 'Vai Jūsu mājsaimniecība var savilkt galus kopā?'],
		['Y11_Q59a', 'Vai varat atļauties savu māju uzturēt pietiekami siltu?'],
		['Y11_Q59b', 'Vai varat atļauties katru gadu samaksāt par nedēļu ilgām brīvdienām ārpus mājas?'],
		['Y11_Q59c', 'Vai varat atļauties aizstāt nolietotas mēbeles?'],
		['Y11_Q59d', 'Vai varat atļauties maltīti ar gaļu, vistu vai zivi katru otro dienu (ja Jūs to vēlētos)?'],
		['Y11_Q59e', 'Vai varat atļauties iegādāties jaunu, nevis lietotu apģērbu?'],
		['Y11_Q59f', 'Vai varat atļauties uzaicināt pie sevis draugus vai ģimeni uz kādu dzērienu vai maltīti vismaz reizi mēnesī'],
		['Y11_Q60a', 'Vai Jūsu mājsaimniecībai pēdējo 12 mēnešu laikā ir bijuši parādi par īri vai hipotekārajiem maksājumiem?'],
		['Y11_Q60b', 'Vai Jūsu mājsaimniecībai pēdējo 12 mēnešu laikā ir bijuši parādi par komunālo pakalpojumu rēķiniem?'],
		['Y11_Q60c', 'Vai Jūsu mājsaimniecībai pēdējo 12 mēnešu laikā ir bijuši parādi par patēriņa kredītiem?'],
		['Y11_Q60d', 'Vai Jūsu mājsaimniecībai pēdējo 12 mēnešu laikā ir bijuši parādi par neoficiāliem aizņēmumiem?'],
		['Y11_Q65', 'Mājsaimniecības finanšu situācija, salīdzinot ar to, kā bija pirms 12 mēnešiem'],
		['Y11_Q66', 'Gaidāmā finanšu situācija nākamajiem 12 mēnešiem'],
		['Y11_Accommproblems', 'Daudz problēmu sakarā ar dzīves apstākļiem'],
		['Y11_Q18', 'Mājas īpašumtiesības'],
		['Y11_Q19a', 'Problēmas ar mājvietu: Šaurība'],
		['Y11_Q19b', 'Problēmas ar mājvietu: Puve logu rāmjos, durvīs vai grīdās'],
		['Y11_Q19c', 'Problēmas ar mājvietu: Mitrums vai sūces sienās vai griestos'],
		['Y11_Q19d', 'Problēmas ar mājvietu: Iekštelpās nav ar ūdeni skalojamās tualetes'],
		['Y11_Q19e', 'Problēmas ar mājvietu: Nav vannas vai dušas'],
		['Y11_Q19f', 'Problēmas ar mājvietu: Trūkst vietas, kur pasēdēt ārā'],
		['Y11_Q20', 'Cik ļoti ticams ir tas, ka Jums nākamo sešu mēnešu laikā var nākties pamest savu mājokli tāpēc, ka Jūs to nevarat atļauties?'],
		['Y11_Q50a', 'Problēmas ar troksni apkaimē'],
		['Y11_Q50b', 'Problēmas ar gaisa kvalitāti apkaimē'],
		['Y11_Q50c', 'Problēmas ar dzeramā ūdens kvalitāti apkaimē'],
		['Y11_Q50d', 'Problēmas ar noziedzību, vardarbību un vandalismu apkaimē'],
		['Y11_Q50e', 'Problēmas ar nekārtību vai atkritumiem uz ielas'],
		['Y11_Q50f', 'Problēmas ar satiksmes sastrēgumiem apkaimē'],
		['Y11_Q51a', 'Pasta pakalpojumu pieejamība'],
		['Y11_Q51b', 'Bankas pakalpojumu pieejamība'],
		['Y11_Q51c', 'Sabiedriskā transporta pieejamība'],
		['Y11_Q51d', 'Kino, teātra vai kultūras centra pieejamība'],
		['Y11_Q51e', 'Atpūtas vai zaļo zonu pieejamība'],
		['Y11_Q52', 'Laiks, kas tiek pavadīts, lai nokļūtu līdz darbam vai mācību vietai'],
		['Y11_Q8_PreferredWorkingHours', 'Cik stundas nedēļā Jūs gribētu strādāt?'],
		['Y11_Q10_Partnerprefhours', 'Cik stundas nedēļā Jūs gribētu, lai Jūsu partneris strādā?'],
		['Y11_Q12a', 'Pārnācu mājās no darba pārāk noguris(‐usi), lai veiktu mājsaimniecības darbus'],
		['Y11_Q12b', 'Man ir bijis grūti izpildīt mājās veicamos pienākumus, jo daudz laika pavadu darbā '],
		['Y11_Q12c', 'Man ir bijis grūti koncentrēties darbam mājās veicamo pienākumu dēļ'],
		['Y11_Q13a', 'Es varu regulēt savu darba laiku'],
		['Y11_Q13b', 'Es varu uzkrāt stundas brīvdienām'],
		['Y11_Q13c', 'Es varu paņemt brīvu dienu bez iepriekšējas organizēšanas, kad man tas ir vajadzīgs '],
		['Y11_Q15', 'Cik lielā mērā ir iespējams, ka Jūs varētu zaudēt darbu nākamo sešu mēnešu laikā?'],
		['Y11_Q16', 'Ja Jūs zaudētu darbu, cik lielā mērā ir iespējams, ka Jūs atrastu darbu ar līdzīgu atalgojumu?'],
		['Y11_Q36a', 'Cik bieži Jūs esat iesaistīts(-a) rūpēs par Jūsu bērniem vai mazbērniem?'],
		['Y11_Q36b', 'Cik bieži Jūs gatavojat vai veicat mājsaimniecības darbus?'],
		['Y11_Q36c', 'Cik bieži Jūs esat iesaistīts(-a) rūpēs par saviem vecajiem vai nespējīgajiem radiniekiem?'],
		['Y11_Q38', 'Attieksme pret mājsaimniecības darbu dalīšanu'],
		['Y11_Q39a', 'Attieksme pret laiku, kas pavadīts kopā ar ģimenes locekļiem'],
		['Y11_Q39b', 'Attieksme pret laiku, kas pavadīts kopā ar citiem'],
		['Y11_Q39c', 'Attieksme pret laiku, kas veltīts saviem hobijiem un interesēm'],
		['Y11_Q39d_stress', 'Stress'],
		['Y11_Q24', 'Vai varat teikt, ka varat uzticēties lielākajai daļai cilvēku vai ka attiecībās ar cilvēkiem ir jābūt piesardzīgam?'],
		['Y11_Q25a', 'Apzinātas saspīlētas attiecības starp nabadzīgiem un bagātiem cilvēkiem'],
		['Y11_Q25b', 'Apzinātas saspīlētas attiecības starp vadītājiem un darbiniekiem'],
		['Y11_Q25c', 'Apzinātas saspīlētas attiecības starp vīriešiem un sievietēm'],
		['Y11_Q25d', 'Apzinātas saspīlētas attiecības starp veciem cilvēkiem un jauniem cilvēkiem'],
		['Y11_Q25e', 'Apzinātas saspīlētas attiecības starp dažādām rasēm un etniskām grupām'],
		['Y11_Q25f', 'Apzinātas saspīlētas attiecības starp dažādām reliģiskajām grupām'],
		['Y11_Q25g', 'Apzinātas saspīlētas attiecības starp cilvēkiem ar atšķirīgu seksuālo orientāciju'],
		['Y11_Q28a', 'Ticība parlamentam'],
		['Y11_Q28b', 'Ticība tiesu sistēmai'],
		['Y11_Q28c', 'Ticība presei'],
		['Y11_Q28d', 'Ticība policijai'],
		['Y11_Q28e', 'Ticība valdībai'],
		['Y11_Q28f', 'Ticība vietējai pašvaldībai'],
		['Y11_Q21a', 'Piedalīšanās dievkalpojumos, izņemot kāzu, bēru, kristību ceremonijas'],
		['Y11_Q21b', 'Interneta lietošana ar darbu nesaistītām vajadzībām'],
		['Y11_Q21c', 'Piedalīšanās sporta vai fiziskajās nodarbībās'],
		['Y11_Q21d', 'Piedalīšanās kāda kluba, biedrības vai asociācijas sabiedriskajās aktivitātēs'],
		['Y11_Q22_Volunteering', 'Cik bieži esat veicis(-kusi) neapmaksātu brīvprātīgo darbu pēdējo 12 mēnešu laikā?'],
		['Y11_Q23a', 'Esat piedalījies(-usies) arodbiedrības, politiskās partijas vai rīcības grupas sanāksmē pēdējo 12 mēnešu laikā'],
		['Y11_Q23b', 'Esat apmeklējis(-usi) protesta akciju vai demonstrāciju pēdējo 12 mēnešu laikā'],
		['Y11_Q23c', 'Esat parakstījis(-usi) petīciju pēdējo 12 mēnešu laikā'],
		['Y11_Q23d', 'Esat sazinājies(-usies) ar politiķi vai valsts ierēdni (cita iemesla dēļ, nevis ikdienas situācijās izmantojot sabiedrisko iestāžu pakalpojumus)'],
		['Y11_Q29e', 'Es jūtos sabiedrības atstumts(-a)'],
		['Y11_Q29f', 'Dzīve mūsdienās ir kļuvusi tik sarežģīta, ka es gandrīz nevaru atrast savu ceļu'],
		['Y11_Q29g', 'Es jūtu, ka citi nesaskata vērtību tajā, ko es daru'],
		['Y11_Q29h', 'Daži cilvēki uz mani skatās no augšas mana darba vai ienākumu dēļ'],
		['Y11_Q29i', 'Jūtos tuvs(‐a) savas dzīvesvietas cilvēkiem'],
		['Y11_SocExIndex', 'Sociālās atstumtības indekss'],
		['Y11_Q29a', 'Esmu optimistiski noskaņots(-a) par nākotni'],
		['Y11_Q29b', 'Vispār, es jūtu, ka tas, ko dzīvē daru, ir vērtīgs'],
		['Y11_Q29c', 'Es jūtu, ka varu izlemt, kā dzīvot savu dzīvi'],
		['Y11_Q29d', 'Ikdienas dzīvē man reti ir laiks darīt to, kas man patīk'],
		['Y11_Q30', 'Cik apmierināts(-a) Jūs šobrīd esat ar savu dzīvi?'],
		['Y11_Q40a', 'Apmierinātība ar izglītību'],
		['Y11_Q40b', 'Apmierinātība ar pašreizējo darbu'],
		['Y11_Q40c', 'Apmierinātība ar pašreizējo dzīves līmeni'],
		['Y11_Q40d', 'Apmierinātība ar mājokli'],
		['Y11_Q40e', 'Apmierinātība ar ģimenes dzīvi'],
		['Y11_Q40f', 'Apmierinātība ar veselību'],
		['Y11_Q40g', 'Apmierinātība ar sabiedrisko dzīvi'],
		['Y11_Q40h', 'Apmierinātība ar ekonomisko situāciju valstī'],
		['Y11_Q41', 'Ņemot vērā visu kopā, cik laimīgs(-a) Jūs esat?'],
		['Y11_Q42', 'Apzinātais veselības stāvoklis'],
		['Y11_Q46a', 'Esmu izjutis(-usi) īpašu spriedzi'],
		['Y11_Q46b', 'Esmu juties(-usies) vientuļi'],
		['Y11_Q46c', 'Esmu juties(-usies) drūms(-a) un nomākts(-a)'],
		['Y11_Q46d_WHO5', 'PVO-5 garīgās labsajūtas skala'],
		['Y11_Q47a', 'Grūtības apmeklēt ārstu attāluma dēļ'],
		['Y11_Q47b', 'Grūtības apmeklēt ārstu, jo ilgi jāgaida pieraksts'],
		['Y11_Q47c', 'Grūtības apmeklēt ārstu, jo pieraksta dienā ir ilgi jāgaida'],
		['Y11_Q47d', 'Grūtības apmeklēt ārstu izmaksu dēļ'],
		['Y11_Q47e', 'Grūtības apmeklēt ārstu laika trūkuma dēļ'],
		['Y11_Q53a', 'Kā Jūs novērtētu veselības aprūpes pakalpojumu kvalitāti savā valstī?'],
		['Y11_Q53b', 'Kā Jūs novērtētu izglītības sistēmas kvalitāti savā valstī?'],
		['Y11_Q53c', 'Kā Jūs novērtētu sabiedriskā transporta pakalpojumu kvalitāti savā valstī?'],
		['Y11_Q53d', 'Kā Jūs novērtētu bērnu aprūpes pakalpojumu kvalitāti savā valstī?'],
		['Y11_Q53e', 'Kā Jūs novērtētu ilgstošas aprūpes pakalpojumu kvalitāti savā valstī?'],
		['Y11_Q53f', 'Kā Jūs novērtētu sociālo mājokļu pakalpojumu kvalitāti savā valstī?'],
		['Y11_Q53g', 'Kā Jūs novērtētu valsts pensiju sistēmas kvalitāti savā valstī?'],
		['Y11_Q33a', 'Klātienes tikšanās ar bērniem, kuri nedzīvo mājsaimniecībā'],
		['Y11_Q33b', 'Klātienes tikšanās ar māti vai tēvu, kuri nedzīvo mājsaimniecībā'],
		['Y11_Q33c', 'Klātienes tikšanās ar radiniekiem, kuri nedzīvo mājsaimniecībā'],
		['Y11_Q33d', 'Klātienes tikšanās ar draugiem vai kaimiņiem'],
		['Y11_Q34a', 'Saziņa ar bērniem, kuri nedzīvo mājsaimniecībā, pa tālruni, internetā vai pa pastu'],
		['Y11_Q34b', 'Saziņa ar māti vai tēvu, kuri nedzīvo mājsaimniecībā, pa tālruni, internetā vai pa pastu'],
		['Y11_Q34c', 'Saziņa ar citiem radiniekiem, kuri nedzīvo mājsaimniecībā, pa tālruni, internetā vai pa pastu'],
		['Y11_Q34d', 'Saziņa ar draugiem vai kaimiņiem pa tālruni, internetā vai pa pastu'],
		['Y11_Q35a', 'No kā Jūs varētu saņemt atbalstu, ja Jums būtu vajadzīga palīdzība mājās slimības laikā?'],
		['Y11_Q35b', 'No kā Jūs varētu saņemt atbalstu, ja Jums būtu vajadzīgs padoms nopietnā personīgā vai ģimenes jautājumā?'],
		['Y11_Q35c', 'No kā Jūs varētu saņemt atbalstu, ja Jums būtu vajadzīga palīdzība, meklējot darbu?'],
		['Y11_Q35d', 'No kā Jūs varētu saņemt atbalstu, ja justos nedaudz nomākts(-a)?'],
		['Y11_Q35e', 'No kā Jūs varētu saņemt atbalstu, ja Jums steidzami būtu vajadzīgi 1000 euro?']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Vidējā vērtība'],
		['Y11_Deprindex', 'Mean', 'Vidējā vērtība'],
		['Y11_Q10_Partnerprefhours', '1--Work-less', 'Strādā mazāk'],
		['Y11_Q10_Partnerprefhours', '2--Work-the-same', 'Strādā tikpat'],
		['Y11_Q10_Partnerprefhours', '3--Work-more', 'Strādā vairāk'],
		['Y11_Q12a', '1--Several-times-a-week', 'Dažas reizes nedēļā'],
		['Y11_Q12a', '2--Several-times-a-month', 'Dažas reizes mēnesī'],
		['Y11_Q12a', '3--Several-times-a-year', 'Dažas reizes gadā'],
		['Y11_Q12a', '4--Less-often-rarely', 'Retāk vai ļoti reti'],
		['Y11_Q12a', '5--Never', 'Nekad'],
		['Y11_Q12b', '1--Several-times-a-week', 'Dažas reizes nedēļā'],
		['Y11_Q12b', '2--Several-times-a-month', 'Dažas reizes mēnesī'],
		['Y11_Q12b', '3--Several-times-a-year', 'Dažas reizes gadā'],
		['Y11_Q12b', '4--Less-often-rarely', 'Retāk vai ļoti reti'],
		['Y11_Q12b', '5--Never', 'Nekad'],
		['Y11_Q12c', '1--Several-times-a-week', 'Dažas reizes nedēļā'],
		['Y11_Q12c', '2--Several-times-a-month', 'Dažas reizes mēnesī'],
		['Y11_Q12c', '3--Several-times-a-year', 'Dažas reizes gadā'],
		['Y11_Q12c', '4--Less-often-rarely', 'Retāk vai ļoti reti'],
		['Y11_Q12c', '5--Never', 'Nekad'],
		['Y11_Q13a', '1--Yes', 'Jā'],
		['Y11_Q13a', '2--No', 'Nē'],
		['Y11_Q13b', '1--Yes', 'Jā'],
		['Y11_Q13b', '2--No', 'Nē'],
		['Y11_Q13c', '1--Yes', 'Jā'],
		['Y11_Q13c', '2--No', 'Nē'],
		['Y11_Q15', '1--Very-likely', 'Ļoti ticami'],
		['Y11_Q15', '2--Quite-likely', 'Drīzāk ticami'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Ne ticami, ne neticami'],
		['Y11_Q15', '4--Quite-unlikely', 'Drīzāk neticami'],
		['Y11_Q15', '5--Very-unlikely', 'Ļoti neticami'],
		['Y11_Q16', '1--Very-likely', 'Ļoti ticami'],
		['Y11_Q16', '2--Quite-likely', 'Drīzāk ticami'],
		['Y11_Q16', '3--Neither-likely-nor-unlikely', 'Ne ticami, ne neticami'],
		['Y11_Q16', '4--Quite-unlikely', 'Drīzāk neticami'],
		['Y11_Q16', '5--Very-unlikely', 'Ļoti neticami'],
		['Y11_Q18', '1--Own-without-mortgage', 'Īpašums bez hipotēkas/ķīlas'],
		['Y11_Q18', '2--Own-with-mortgage', 'Īpašums ar hipotēku/ķīlu'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Īrējamā platība, par kuru jāmaksā īre sociālo mājokļu apsaimniekotājiem/sabiedriskām organizācijām/pašvaldībai'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Īrējamā platība, par kuru jāmaksā īre privātam saimniekam'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Mājoklis, par kuru nav jāmaksā īre'],
		['Y11_Q18', '6--Other', 'Cits'],
		['Y11_Q19a', '1--Yes', 'Jā'],
		['Y11_Q19a', '2--No', 'Nē'],
		['Y11_Q19b', '1--Yes', 'Jā'],
		['Y11_Q19b', '2--No', 'Nē'],
		['Y11_Q19c', '1--Yes', 'Jā'],
		['Y11_Q19c', '2--No', 'Nē'],
		['Y11_Q19d', '1--Yes', 'Jā'],
		['Y11_Q19d', '2--No', 'Nē'],
		['Y11_Q19e', '1--Yes', 'Jā'],
		['Y11_Q19e', '2--No', 'Nē'],
		['Y11_Q19f', '1--Yes', 'Jā'],
		['Y11_Q19f', '2--No', 'Nē'],
		['Y11_Q20', '1--Very-likely', 'Ļoti ticami'],
		['Y11_Q20', '2--Quite-likely', 'Drīzāk ticami'],
		['Y11_Q20', '3--Quite-unlikely', 'Drīzāk neticami'],
		['Y11_Q20', '4--Very-unlikely', 'Ļoti neticami'],
		['Y11_Q21a', '1--Every-day-or-almost-every-day', 'Katru dienu vai gandrīz katru dienu'],
		['Y11_Q21a', '2--At-least-once-a-week', 'Vismaz vienu reizi nedēļā'],
		['Y11_Q21a', '3--One-to-three-times-a-month', 'Vienu līdz trīs reizes mēnesī'],
		['Y11_Q21a', '4--Less-often', 'Retāk'],
		['Y11_Q21a', '5--Never', 'Nekad'],
		['Y11_Q21b', '1--Every-day-or-almost-every-day', 'Katru dienu vai gandrīz katru dienu'],
		['Y11_Q21b', '2--At-least-once-a-week', 'Vismaz vienu reizi nedēļā'],
		['Y11_Q21b', '3--One-to-three-times-a-month', 'Vienu līdz trīs reizes mēnesī'],
		['Y11_Q21b', '4--Less-often', 'Retāk'],
		['Y11_Q21b', '5--Never', 'Nekad'],
		['Y11_Q21c', '1--Every-day-or-almost-every-day', 'Katru dienu vai gandrīz katru dienu'],
		['Y11_Q21c', '2--At-least-once-a-week', 'Vismaz vienu reizi nedēļā'],
		['Y11_Q21c', '3--One-to-three-times-a-month', 'Vienu līdz trīs reizes mēnesī'],
		['Y11_Q21c', '4--Less-often', 'Retāk'],
		['Y11_Q21c', '5--Never', 'Nekad'],
		['Y11_Q21d', '1--Every-day-or-almost-every-day', 'Katru dienu vai gandrīz katru dienu'],
		['Y11_Q21d', '2--At-least-once-a-week', 'Vismaz vienu reizi nedēļā'],
		['Y11_Q21d', '3--One-to-three-times-a-month', 'Vienu līdz trīs reizes mēnesī'],
		['Y11_Q21d', '4--Less-often', 'Retāk'],
		['Y11_Q21d', '5--Never', 'Nekad'],
		['Y11_Q22_Volunteering', '1--Volunteers-regularly', 'Regulāri veic brīvprātīgo darbu'],
		['Y11_Q22_Volunteering', '2--Volunteers-occasionally', 'Reizēm veic brīvprātīgo darbu'],
		['Y11_Q22_Volunteering', '3--Does-not-volunteer', 'Neveic brīvprātīgo darbu'],
		['Y11_Q23a', '1--Yes', 'Jā'],
		['Y11_Q23a', '2--No', 'Nē'],
		['Y11_Q23b', '1--Yes', 'Jā'],
		['Y11_Q23b', '2--No', 'Nē'],
		['Y11_Q23c', '1--Yes', 'Jā'],
		['Y11_Q23c', '2--No', 'Nē'],
		['Y11_Q23d', '1--Yes', 'Jā'],
		['Y11_Q23d', '2--No', 'Nē'],
		['Y11_Q24', 'Mean', 'Vidējā vērtība'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Ļoti saspīlētas attiecības'],
		['Y11_Q25a', '2--Some-tension', 'Nedaudz saspīlētas attiecības'],
		['Y11_Q25a', '3--No-tension', 'Nemaz nav saspīlētas attiecības'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Ļoti saspīlētas attiecības'],
		['Y11_Q25b', '2--Some-tension', 'Nedaudz saspīlētas attiecības'],
		['Y11_Q25b', '3--No-tension', 'Nemaz nav saspīlētas attiecības'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Ļoti saspīlētas attiecības'],
		['Y11_Q25c', '2--Some-tension', 'Nedaudz saspīlētas attiecības'],
		['Y11_Q25c', '3--No-tension', 'Nemaz nav saspīlētas attiecības'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Ļoti saspīlētas attiecības'],
		['Y11_Q25d', '2--Some-tension', 'Nedaudz saspīlētas attiecības'],
		['Y11_Q25d', '3--No-tension', 'Nemaz nav saspīlētas attiecības'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Ļoti saspīlētas attiecības'],
		['Y11_Q25e', '2--Some-tension', 'Nedaudz saspīlētas attiecības'],
		['Y11_Q25e', '3--No-tension', 'Nemaz nav saspīlētas attiecības'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Ļoti saspīlētas attiecības'],
		['Y11_Q25f', '2--Some-tension', 'Nedaudz saspīlētas attiecības'],
		['Y11_Q25f', '3--No-tension', 'Nemaz nav saspīlētas attiecības'],
		['Y11_Q25g', '1--A-lot-of--tension', 'Ļoti saspīlētas attiecības'],
		['Y11_Q25g', '2--Some-tension', 'Nedaudz saspīlētas attiecības'],
		['Y11_Q25g', '3--No-tension', 'Nemaz nav saspīlētas attiecības'],
		['Y11_Q28a', 'Mean', 'Vidējā vērtība'],
		['Y11_Q28b', 'Mean', 'Vidējā vērtība'],
		['Y11_Q28c', 'Mean', 'Vidējā vērtība'],
		['Y11_Q28d', 'Mean', 'Vidējā vērtība'],
		['Y11_Q28e', 'Mean', 'Vidējā vērtība'],
		['Y11_Q28f', 'Mean', 'Vidējā vērtība'],
		['Y11_Q29a', '1--Strongly-agree', 'Pilnībā piekrītat'],
		['Y11_Q29a', '2--Agree', 'Piekrītat'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Ne piekrītat, ne nepiekrītat'],
		['Y11_Q29a', '4--Disagree', 'Nepiekrītat'],
		['Y11_Q29a', '5--Strongly-disagree', 'Pilnībā nepiekrītat'],
		['Y11_Q29b', '1--Strongly-agree', 'Pilnībā piekrītat'],
		['Y11_Q29b', '2--Agree', 'Piekrītat'],
		['Y11_Q29b', '3--Neither-agree-nor-disagree', 'Ne piekrītat, ne nepiekrītat'],
		['Y11_Q29b', '4--Disagree', 'Nepiekrītat'],
		['Y11_Q29b', '5--Strongly-disagree', 'Pilnībā nepiekrītat'],
		['Y11_Q29c', '1--Strongly-agree', 'Pilnībā piekrītat'],
		['Y11_Q29c', '2--Agree', 'Piekrītat'],
		['Y11_Q29c', '3--Neither-agree-nor-disagree', 'Ne piekrītat, ne nepiekrītat'],
		['Y11_Q29c', '4--Disagree', 'Nepiekrītat'],
		['Y11_Q29c', '5--Strongly-disagree', 'Pilnībā nepiekrītat'],
		['Y11_Q29d', '1--Strongly-agree', 'Pilnībā piekrītat'],
		['Y11_Q29d', '2--Agree', 'Piekrītat'],
		['Y11_Q29d', '3--Neither-agree-nor-disagree', 'Ne piekrītat, ne nepiekrītat'],
		['Y11_Q29d', '4--Disagree', 'Nepiekrītat'],
		['Y11_Q29d', '5--Strongly-disagree', 'Pilnībā nepiekrītat'],
		['Y11_Q29e', '1--Strongly-agree', 'Pilnībā piekrītat'],
		['Y11_Q29e', '2--Agree', 'Piekrītat'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Ne piekrītat, ne nepiekrītat'],
		['Y11_Q29e', '4--Disagree', 'Nepiekrītat'],
		['Y11_Q29e', '5--Strongly-disagree', 'Pilnībā nepiekrītat'],
		['Y11_Q29f', '1--Strongly-agree', 'Pilnībā piekrītat'],
		['Y11_Q29f', '2--Agree', 'Piekrītat'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Ne piekrītat, ne nepiekrītat'],
		['Y11_Q29f', '4--Disagree', 'Nepiekrītat'],
		['Y11_Q29f', '5--Strongly-disagree', 'Pilnībā nepiekrītat'],
		['Y11_Q29g', '1--Strongly-agree', 'Pilnībā piekrītat'],
		['Y11_Q29g', '2--Agree', 'Piekrītat'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Ne piekrītat, ne nepiekrītat'],
		['Y11_Q29g', '4--Disagree', 'Nepiekrītat'],
		['Y11_Q29g', '5--Strongly-disagree', 'Pilnībā nepiekrītat'],
		['Y11_Q29h', '1--Strongly-agree', 'Pilnībā piekrītat'],
		['Y11_Q29h', '2--Agree', 'Piekrītat'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Ne piekrītat, ne nepiekrītat'],
		['Y11_Q29h', '4--Disagree', 'Nepiekrītat'],
		['Y11_Q29h', '5--Strongly-disagree', 'Pilnībā nepiekrītat'],
		['Y11_Q29i', '1--Strongly-agree', 'Pilnībā piekrītat'],
		['Y11_Q29i', '2--Agree', 'Piekrītat'],
		['Y11_Q29i', '3--Neither-agree-nor-disagree', 'Ne piekrītat, ne nepiekrītat'],
		['Y11_Q29i', '4--Disagree', 'Nepiekrītat'],
		['Y11_Q29i', '5--Strongly-disagree', 'Pilnībā nepiekrītat'],
		['Y11_Q30', 'Mean', 'Vidējā vērtība'],
		['Y11_Q33a', '1--Every-day-or-almost-every-day', 'Katru dienu vai gandrīz katru dienu'],
		['Y11_Q33a', '2--At-least-once-a-week', 'Vismaz vienu reizi nedēļā'],
		['Y11_Q33a', '3--One-to-three-times-a-month', 'Vienu līdz trīs reizes mēnesī'],
		['Y11_Q33a', '4--Less-often', 'Retāk'],
		['Y11_Q33a', '5--Never', 'Nekad'],
		['Y11_Q33b', '1--Every-day-or-almost-every-day', 'Katru dienu vai gandrīz katru dienu'],
		['Y11_Q33b', '2--At-least-once-a-week', 'Vismaz vienu reizi nedēļā'],
		['Y11_Q33b', '3--One-to-three-times-a-month', 'Vienu līdz trīs reizes mēnesī'],
		['Y11_Q33b', '4--Less-often', 'Retāk'],
		['Y11_Q33b', '5--Never', 'Nekad'],
		['Y11_Q33c', '1--Every-day-or-almost-every-day', 'Katru dienu vai gandrīz katru dienu'],
		['Y11_Q33c', '2--At-least-once-a-week', 'Vismaz vienu reizi nedēļā'],
		['Y11_Q33c', '3--One-to-three-times-a-month', 'Vienu līdz trīs reizes mēnesī'],
		['Y11_Q33c', '4--Less-often', 'Retāk'],
		['Y11_Q33c', '5--Never', 'Nekad'],
		['Y11_Q33d', '1--Every-day-or-almost-every-day', 'Katru dienu vai gandrīz katru dienu'],
		['Y11_Q33d', '2--At-least-once-a-week', 'Vismaz vienu reizi nedēļā'],
		['Y11_Q33d', '3--One-to-three-times-a-month', 'Vienu līdz trīs reizes mēnesī'],
		['Y11_Q33d', '4--Less-often', 'Retāk'],
		['Y11_Q33d', '5--Never', 'Nekad'],
		['Y11_Q34a', '1--Every-day-or-almost-every-day', 'Katru dienu vai gandrīz katru dienu'],
		['Y11_Q34a', '2--At-least-once-a-week', 'Vismaz vienu reizi nedēļā'],
		['Y11_Q34a', '3--One-to-three-times-a-month', 'Vienu līdz trīs reizes mēnesī'],
		['Y11_Q34a', '4--Less-often', 'Retāk'],
		['Y11_Q34a', '5--Never', 'Nekad'],
		['Y11_Q34b', '1--Every-day-or-almost-every-day', 'Katru dienu vai gandrīz katru dienu'],
		['Y11_Q34b', '2--At-least-once-a-week', 'Vismaz vienu reizi nedēļā'],
		['Y11_Q34b', '3--One-to-three-times-a-month', 'Vienu līdz trīs reizes mēnesī'],
		['Y11_Q34b', '4--Less-often', 'Retāk'],
		['Y11_Q34b', '5--Never', 'Nekad'],
		['Y11_Q34c', '1--Every-day-or-almost-every-day', 'Katru dienu vai gandrīz katru dienu'],
		['Y11_Q34c', '2--At-least-once-a-week', 'Vismaz vienu reizi nedēļā'],
		['Y11_Q34c', '3--One-to-three-times-a-month', 'Vienu līdz trīs reizes mēnesī'],
		['Y11_Q34c', '4--Less-often', 'Retāk'],
		['Y11_Q34c', '5--Never', 'Nekad'],
		['Y11_Q34d', '1--Every-day-or-almost-every-day', 'Katru dienu vai gandrīz katru dienu'],
		['Y11_Q34d', '2--At-least-once-a-week', 'Vismaz vienu reizi nedēļā'],
		['Y11_Q34d', '3--One-to-three-times-a-month', 'Vienu līdz trīs reizes mēnesī'],
		['Y11_Q34d', '4--Less-often', 'Retāk'],
		['Y11_Q34d', '5--Never', 'Nekad'],
		['Y11_Q35a', '1--A-member-of-your-family', 'Jūsu ģimenes loceklis'],
		['Y11_Q35a', '2--A-friend--neighbour--or-someone-else', 'Draugs, kaimiņš vai kāds cits'],
		['Y11_Q35a', '3--A-service-provider--institution-or-organisation', 'Pakalpojumu sniedzējs, institūcija vai organizācija'],
		['Y11_Q35a', '4--Nobody', 'Neviens'],
		['Y11_Q35b', '1--A-member-of-your-family', 'Jūsu ģimenes loceklis'],
		['Y11_Q35b', '2--A-friend--neighbour--or-someone-else', 'Draugs, kaimiņš vai kāds cits'],
		['Y11_Q35b', '3--A-service-provider--institution-or-organisation', 'Pakalpojumu sniedzējs, institūcija vai organizācija'],
		['Y11_Q35b', '4--Nobody', 'Neviens'],
		['Y11_Q35c', '1--A-member-of-your-family', 'Jūsu ģimenes loceklis'],
		['Y11_Q35c', '2--A-friend--neighbour--or-someone-else', 'Draugs, kaimiņš vai kāds cits'],
		['Y11_Q35c', '3--A-service-provider--institution-or-organisation', 'Pakalpojumu sniedzējs, institūcija vai organizācija'],
		['Y11_Q35c', '4--Nobody', 'Neviens'],
		['Y11_Q35d', '1--A-member-of-your-family', 'Jūsu ģimenes loceklis'],
		['Y11_Q35d', '2--A-friend--neighbour--or-someone-else', 'Draugs, kaimiņš vai kāds cits'],
		['Y11_Q35d', '3--A-service-provider--institution-or-organisation', 'Pakalpojumu sniedzējs, institūcija vai organizācija'],
		['Y11_Q35d', '4--Nobody', 'Neviens'],
		['Y11_Q35e', '1--A-member-of-your-family', 'Jūsu ģimenes loceklis'],
		['Y11_Q35e', '2--A-friend--neighbour--or-someone-else', 'Draugs, kaimiņš vai kāds cits'],
		['Y11_Q35e', '3--A-service-provider--institution-or-organisation', 'Pakalpojumu sniedzējs, institūcija vai organizācija'],
		['Y11_Q35e', '4--Nobody', 'Neviens'],
		['Y11_Q36a', '1--Every-day', 'Katru dienu'],
		['Y11_Q36a', '2--Several-days-a-week', 'Dažas dienas nedēļā'],
		['Y11_Q36a', '3--Once-or-twice-a-week', 'Vienu vai divas reizes nedēļā'],
		['Y11_Q36a', '4--Less-often', 'Retāk'],
		['Y11_Q36a', '5--Never', 'Nekad'],
		['Y11_Q36b', '1--Every-day', 'Katru dienu'],
		['Y11_Q36b', '2--Several-days-a-week', 'Dažas dienas nedēļā'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'Vienu vai divas reizes nedēļā'],
		['Y11_Q36b', '4--Less-often', 'Retāk'],
		['Y11_Q36b', '5--Never', 'Nekad'],
		['Y11_Q36c', '1--Every-day', 'Katru dienu'],
		['Y11_Q36c', '2--Several-days-a-week', 'Dažas dienas nedēļā'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'Vienu vai divas reizes nedēļā'],
		['Y11_Q36c', '4--Less-often', 'Retāk'],
		['Y11_Q36c', '5--Never', 'Nekad'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Lielāka nekā Jums pienāktos'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Apmēram tāda, kāda Jums pienāktos'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Mazāka nekā Jums pienāktos'],
		['Y11_Q39a', '1--Spend-more-time', 'Veltīt vairāk laika'],
		['Y11_Q39a', '2--As-much-as-I-currently-do', 'Tik daudz, cik šobrīd'],
		['Y11_Q39a', '3--Spend-less-time', 'Veltīt mazāk laika'],
		['Y11_Q39b', '1--Spend-more-time', 'Veltīt vairāk laika'],
		['Y11_Q39b', '2--As-much-as-I-currently-do', 'Tik daudz, cik šobrīd'],
		['Y11_Q39b', '3--Spend-less-time', 'Veltīt mazāk laika'],
		['Y11_Q39c', '1--Spend-more-time', 'Veltīt vairāk laika'],
		['Y11_Q39c', '2--As-much-as-I-currently-do', 'Tik daudz, cik šobrīd'],
		['Y11_Q39c', '3--Spend-less-time', 'Veltīt mazāk laika'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'Darbā un mājās'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Vai nu darbā, vai mājās'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Neliels stress vai nav stresa'],
		['Y11_Q40a', 'Mean', 'Vidējā vērtība'],
		['Y11_Q40b', 'Mean', 'Vidējā vērtība'],
		['Y11_Q40c', 'Mean', 'Vidējā vērtība'],
		['Y11_Q40d', 'Mean', 'Vidējā vērtība'],
		['Y11_Q40e', 'Mean', 'Vidējā vērtība'],
		['Y11_Q40f', 'Mean', 'Vidējā vērtība'],
		['Y11_Q40g', 'Mean', 'Vidējā vērtība'],
		['Y11_Q40h', 'Mean', 'Vidējā vērtība'],
		['Y11_Q41', 'Mean', 'Vidējā vērtība'],
		['Y11_Q42', '1--Very-good', 'Ļoti labi'],
		['Y11_Q42', '2--Good', 'Laba'],
		['Y11_Q42', '3--Fair', 'Vidēja'],
		['Y11_Q42', '4--Bad', 'Slikta'],
		['Y11_Q42', '5--Very-bad', 'Ļoti slikta'],
		['Y11_Q46a', '1--All-of-the-time', 'Visu laiku'],
		['Y11_Q46a', '2--Most-of-the-time', 'Lielāko laika daļu'],
		['Y11_Q46a', '3--More-than-half-of-the-time', 'Vairāk nekā pusi no laika'],
		['Y11_Q46a', '4--Less-than-half-of-the-time', 'Mazāk nekā pusi no laika'],
		['Y11_Q46a', '5--Some-of-the-time', 'Daļu no laika'],
		['Y11_Q46a', '6--At-no-time', 'Nevienu brīdi'],
		['Y11_Q46b', '1--All-of-the-time', 'Visu laiku'],
		['Y11_Q46b', '2--Most-of-the-time', 'Lielāko laika daļu'],
		['Y11_Q46b', '3--More-than-half-of-the-time', 'Vairāk nekā pusi no laika'],
		['Y11_Q46b', '4--Less-than-half-of-the-time', 'Mazāk nekā pusi no laika'],
		['Y11_Q46b', '5--Some-of-the-time', 'Daļu no laika'],
		['Y11_Q46b', '6--At-no-time', 'Nevienu brīdi'],
		['Y11_Q46c', '1--All-of-the-time', 'Visu laiku'],
		['Y11_Q46c', '2--Most-of-the-time', 'Lielāko daļu laika'],
		['Y11_Q46c', '3--More-than-half-of-the-time', 'Vairāk nekā pusi laika'],
		['Y11_Q46c', '4--Less-than-half-of-the-time', 'Mazāk nekā pusi laika'],
		['Y11_Q46c', '5--Some-of-the-time', 'Daļu laika'],
		['Y11_Q46c', '6--At-no-time', 'Nevienu brīdi'],
		['Y11_Q46d_WHO5', 'Mean', 'Vidējā vērtība'],
		['Y11_Q47a', '1--Very-difficult', 'Radīja lielas grūtības'],
		['Y11_Q47a', '2--A-little-difficult', 'Radīja nelielas grūtības'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Nemaz neradīja grūtības'],
		['Y11_Q47b', '1--Very-difficult', 'Radīja lielas grūtības'],
		['Y11_Q47b', '2--A-little-difficult', 'Radīja nelielas grūtības'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Nemaz neradīja grūtības'],
		['Y11_Q47c', '1--Very-difficult', 'Radīja lielas grūtības'],
		['Y11_Q47c', '2--A-little-difficult', 'Radīja nelielas grūtības'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Nemaz neradīja grūtības'],
		['Y11_Q47d', '1--Very-difficult', 'Radīja lielas grūtības'],
		['Y11_Q47d', '2--A-little-difficult', 'Radīja nelielas grūtības'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Nemaz neradīja grūtības'],
		['Y11_Q47e', '1--Very-difficult', 'Radīja lielas grūtības'],
		['Y11_Q47e', '2--A-little-difficult', 'Radīja nelielas grūtības'],
		['Y11_Q47e', '3--Not-difficult-at-all', 'Nemaz neradīja grūtības'],
		['Y11_Q50a', '1--Major-problems', 'Ļoti daudz problēmu'],
		['Y11_Q50a', '2--Moderate-problems', 'Vidēji daudz problēmu'],
		['Y11_Q50a', '3--No-problems', 'Nav problēmu'],
		['Y11_Q50b', '1--Major-problems', 'Ļoti daudz problēmu'],
		['Y11_Q50b', '2--Moderate-problems', 'Vidēji daudz problēmu'],
		['Y11_Q50b', '3--No-problems', 'Nav problēmu'],
		['Y11_Q50c', '1--Major-problems', 'Ļoti daudz problēmu'],
		['Y11_Q50c', '2--Moderate-problems', 'Vidēji daudz problēmu'],
		['Y11_Q50c', '3--No-problems', 'Nav problēmu'],
		['Y11_Q50d', '1--Major-problems', 'Ļoti daudz problēmu'],
		['Y11_Q50d', '2--Moderate-problems', 'Vidēji daudz problēmu'],
		['Y11_Q50d', '3--No-problems', 'Nav problēmu'],
		['Y11_Q50e', '1--Major-problems', 'Ļoti daudz problēmu'],
		['Y11_Q50e', '2--Moderate-problems', 'Vidēji daudz problēmu'],
		['Y11_Q50e', '3--No-problems', 'Nav problēmu'],
		['Y11_Q50f', '1--Major-problems', 'Ļoti daudz problēmu'],
		['Y11_Q50f', '2--Moderate-problems', 'Vidēji daudz problēmu'],
		['Y11_Q50f', '3--No-problems', 'Nav problēmu'],
		['Y11_Q51a', '1--with-great-difficulty', 'Ar ļoti lielām grūtībām'],
		['Y11_Q51a', '2--with-some-difficulty', 'Ar zināmām grūtībām'],
		['Y11_Q51a', '3--easily', 'Viegli'],
		['Y11_Q51a', '4--very-easily', 'Ļoti viegli'],
		['Y11_Q51b', '1--with-great-difficulty', 'Ar ļoti lielām grūtībām'],
		['Y11_Q51b', '2--with-some-difficulty', 'Ar zināmām grūtībām'],
		['Y11_Q51b', '3--easily', 'Viegli'],
		['Y11_Q51b', '4--very-easily', 'Ļoti viegli'],
		['Y11_Q51c', '1--with-great-difficulty', 'Ar ļoti lielām grūtībām'],
		['Y11_Q51c', '2--with-some-difficulty', 'Ar zināmām grūtībām'],
		['Y11_Q51c', '3--easily', 'Viegli'],
		['Y11_Q51c', '4--very-easily', 'Ļoti viegli'],
		['Y11_Q51d', '1--with-great-difficulty', 'Ar ļoti lielām grūtībām'],
		['Y11_Q51d', '2--with-some-difficulty', 'Ar zināmām grūtībām'],
		['Y11_Q51d', '3--easily', 'Viegli'],
		['Y11_Q51d', '4--very-easily', 'Ļoti viegli'],
		['Y11_Q51e', '1--with-great-difficulty', 'Ar ļoti lielām grūtībām'],
		['Y11_Q51e', '2--with-some-difficulty', 'Ar zināmām grūtībām'],
		['Y11_Q51e', '3--easily', 'Viegli'],
		['Y11_Q51e', '4--very-easily', 'Ļoti viegli'],
		['Y11_Q52', 'Mean', 'Vidējā vērtība'],
		['Y11_Q53a', 'Mean', 'Vidējā vērtība'],
		['Y11_Q53b', 'Mean', 'Vidējā vērtība'],
		['Y11_Q53c', 'Mean', 'Vidējā vērtība'],
		['Y11_Q53d', 'Mean', 'Vidējā vērtība'],
		['Y11_Q53e', 'Mean', 'Vidējā vērtība'],
		['Y11_Q53f', 'Mean', 'Vidējā vērtība'],
		['Y11_Q53g', 'Mean', 'Vidējā vērtība'],
		['Y11_Q57', '1--Much-worse', 'Daudz sliktāka'],
		['Y11_Q57', '2--Somewhat-worse', 'Nedaudz sliktāka'],
		['Y11_Q57', '3--Neither-worse-nor-better', 'Ne labāka, ne sliktāka'],
		['Y11_Q57', '4--Somewhat-better', 'Nedaudz labāka'],
		['Y11_Q57', '5--Much-better', 'Daudz labāka'],
		['Y11_Q58', '1--With-great-difficulty', 'Ar ļoti lielām grūtībām'],
		['Y11_Q58', '2--With-difficulty', 'Ar grūtībām'],
		['Y11_Q58', '3--With-some-difficulty', 'Ar zināmām grūtībām'],
		['Y11_Q58', '4--Fairly-easily', 'Samērā viegli'],
		['Y11_Q58', '5--Easily', 'Viegli'],
		['Y11_Q58', '6--Very-easily', 'Ļoti viegli'],
		['Y11_Q59a', '1--No', 'Nē'],
		['Y11_Q59a', '2--Yes', 'Jā'],
		['Y11_Q59b', '1--No', 'Nē'],
		['Y11_Q59b', '2--Yes', 'Jā'],
		['Y11_Q59c', '1--No', 'Nē'],
		['Y11_Q59c', '2--Yes', 'Jā'],
		['Y11_Q59d', '1--No', 'Nē'],
		['Y11_Q59d', '2--Yes', 'Jā'],
		['Y11_Q59e', '1--No', 'Nē'],
		['Y11_Q59e', '2--Yes', 'Jā'],
		['Y11_Q59f', '1--No', 'Nē'],
		['Y11_Q59f', '2--Yes', 'Jā'],
		['Y11_Q60a', '1--Yes', 'Jā'],
		['Y11_Q60a', '2--No', 'Nē'],
		['Y11_Q60b', '1--Yes', 'Jā'],
		['Y11_Q60b', '2--No', 'Nē'],
		['Y11_Q60c', '1--Yes', 'Jā'],
		['Y11_Q60c', '2--No', 'Nē'],
		['Y11_Q60d', '1--Yes', 'Jā'],
		['Y11_Q60d', '2--No', 'Nē'],
		['Y11_Q65', '1--Better', 'Uzlabojusies'],
		['Y11_Q65', '2--The-same', 'Tāda pati'],
		['Y11_Q65', '3--Worse', 'Pasliktinājusies'],
		['Y11_Q66', '1--Better', 'Uzlabojusies'],
		['Y11_Q66', '2--The-same', 'Tāda pati'],
		['Y11_Q66', '3--Worse', 'Pasliktinājusies'],
		['Y11_Q8_PreferredWorkingHours', '1--Work-less', 'Strādā mazāk'],
		['Y11_Q8_PreferredWorkingHours', '2--Work-the-same', 'Strādā tikpat'],
		['Y11_Q8_PreferredWorkingHours', '3--Work-more', 'Strādā vairāk'],
		['Y11_SocExIndex', 'Mean', 'Vidējā vērtība']
	];
var country_
	 = [
	
		['AT', 'Austrija'],
		['BE', 'Beļģija'],
		['BG', 'Bulgārija'],
		['CY', 'Kipra'],
		['CZ', 'Čehijas Republika'],
		['DE', 'Vācija'],
		['DK', 'Dānija'],
		['EE', 'Igaunija'],
		['EL', 'Grieķija'],
		['ES', 'Spānija'],
		['FI', 'Somija'],
		['FR', 'Francija'],
		['HR', 'Horvātija'],
		['HU', 'Ungārija'],
		['IE', 'Īrija'],
		['IS', 'Islande'],
		['IT', 'Itālija'],
		['LT', 'Lietuva'],
		['LU', 'Luksemburga'],
		['LV', 'Latvija'],
		['ME', 'Melnkalne'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Nīderlande'],
		['PL', 'Polija'],
		['PT', 'Portugāle'],
		['RO', 'Rumānija'],
		['RS', 'Serbija'],
		['SE', 'Zviedrija'],
		['SI', 'Slovēnija'],
		['SK', 'Slovākija'],
		['TR', 'Turcija'],
		['UK', 'Apvienotā Karaliste'],
		['XK', 'Kosova'],
		['EuropeanUnion', 'Eiropas Savienība']
	];
var question_meta
	 = [
	
		['Y11_Deprindex', 'Maznodrošinātības indekss: mājsaimniecībā trūkstošo lietu skaits', ''],
		['Y11_Q57', 'Mājsaimniecības finanšu situācija, salīdzinot ar lielāko daļu cilvēku valstī', ''],
		['Y11_Q58', 'Vai Jūsu mājsaimniecība var savilkt galus kopā?', ''],
		['Y11_Q59a', 'Vai varat atļauties savu māju uzturēt pietiekami siltu?', ''],
		['Y11_Q59b', 'Vai varat atļauties katru gadu samaksāt par nedēļu ilgām brīvdienām ārpus mājas?', ''],
		['Y11_Q59c', 'Vai varat atļauties aizstāt nolietotas mēbeles?', ''],
		['Y11_Q59d', 'Vai Jūsu mājsaimniecība var atļauties maltīti ar gaļu, vistu vai zivi katru otro dienu (ja Jūs to vēlētos)?', ''],
		['Y11_Q59e', 'Vai Jūsu mājsaimniecības locekļi var atļauties iegādāties jaunu, nevis lietotu apģērbu?', ''],
		['Y11_Q59f', 'Vai Jūsu mājsaimniecība var atļauties uzaicināt pie sevis draugus vai ģimeni uz kādu dzērienu vai maltīti vismaz reizi mēnesī', ''],
		['Y11_Q60a', 'Vai Jūsu mājsaimniecībai pēdējo 12 mēnešu laikā ir bijuši parādi par īri vai hipotekārajiem maksājumiem?', ''],
		['Y11_Q60b', 'Vai Jūsu mājsaimniecībai pēdējo 12 mēnešu laikā ir bijuši parādi par komunālo pakalpojumu rēķiniem?', ''],
		['Y11_Q60c', 'Vai Jūsu mājsaimniecībai pēdējo 12 mēnešu laikā ir bijuši parādi par maksājumiem saistībā ar patēriņa kredītiem?', ''],
		['Y11_Q60d', 'Vai Jūsu mājsaimniecībai pēdējo 12 mēnešu laikā ir bijuši parādi par maksājumiem saistībā ar neoficiāliem aizņēmumiem?', ''],
		['Y11_Q65', 'Mājsaimniecības finanšu situācija, salīdzinot ar to, kā bija pirms 12 mēnešiem', ''],
		['Y11_Q66', 'Gaidāmā finanšu situācija nākamajiem 12 mēnešiem', ''],
		['Y11_Accommproblems', 'Daudz problēmu sakarā ar dzīves apstākļiem', ''],
		['Y11_Q18', 'Mājas īpašumtiesības', ''],
		['Y11_Q19a', 'Problēmas ar mājvietu: Šaurība', ''],
		['Y11_Q19b', 'Problēmas ar mājvietu: Puve logu rāmjos, durvīs vai grīdās', ''],
		['Y11_Q19c', 'Problēmas ar mājvietu: Mitrums vai sūces sienās vai griestos', ''],
		['Y11_Q19d', 'Problēmas ar mājvietu: Iekštelpās nav ar ūdeni skalojamās tualetes', ''],
		['Y11_Q19e', 'Problēmas ar mājvietu: Nav vannas vai dušas', ''],
		['Y11_Q19f', 'Problēmas ar mājvietu: Trūkst vietas, kur pasēdēt ārā', ''],
		['Y11_Q20', 'Cik ļoti ticams ir tas, ka Jums nākamo sešu mēnešu laikā var nākties pamest savu mājokli tāpēc, ka Jūs to vairs nevarat atļauties?', ''],
		['Y11_Q50a', 'Problēmas ar troksni apkaimē', ''],
		['Y11_Q50b', 'Problēmas ar gaisa kvalitāti apkaimē', ''],
		['Y11_Q50c', 'Problēmas ar dzeramā ūdens kvalitāti apkaimē', ''],
		['Y11_Q50d', 'Problēmas ar noziedzību, vardarbību un vandalismu apkaimē', ''],
		['Y11_Q50e', 'Problēmas ar nekārtību vai atkritumiem uz ielas apkaimē', ''],
		['Y11_Q50f', 'Problēmas ar satiksmes sastrēgumiem apkaimē', ''],
		['Y11_Q51a', 'Pasta pakalpojumu pieejamība', ''],
		['Y11_Q51b', 'Bankas pakalpojumu pieejamība', ''],
		['Y11_Q51c', 'Sabiedriskā transporta pieejamība', ''],
		['Y11_Q51d', 'Kino, teātra vai kultūras centra pieejamība', ''],
		['Y11_Q51e', 'Atpūtas vai zaļo zonu pieejamība', ''],
		['Y11_Q52', 'Laiks, kas tiek pavadīts, lai nokļūtu līdz darbam vai mācību vietai', ''],
		['Y11_Q8_PreferredWorkingHours', 'Cik stundas nedēļā Jūs gribētu strādāt?', ''],
		['Y11_Q10_Partnerprefhours', 'Cik stundas nedēļā Jūs gribētu, lai Jūsu partneris strādā?', 'Šo jautājumu uzdeva tiem respondentiem, kuru mājsaimniecībā dzīvo partneris.'],
		['Y11_Q12a', ' Pārnācu mājās no darba pārāk noguris(‐usi), lai veiktu mājsaimniecības darbus', ''],
		['Y11_Q12b', 'Man ir bijis grūti izpildīt mājās veicamos pienākumus, jo daudz laika pavadu darbā ', ''],
		['Y11_Q12c', 'Man ir bijis grūti koncentrēties darbam mājās veicamo pienākumu dēļ', ''],
		['Y11_Q13a', 'Es varu regulēt savu darba laiku', ''],
		['Y11_Q13b', 'Es varu uzkrāt stundas brīvdienām', ''],
		['Y11_Q13c', 'Es varu paņemt brīvu dienu bez iepriekšējas organizēšanas, kad man tas ir vajadzīgs ', ''],
		['Y11_Q15', 'Cik lielā mērā ir iespējams, ka Jūs varētu zaudēt darbu nākamo sešu mēnešu laikā?', ''],
		['Y11_Q16', 'Ja Jūs zaudētu darbu, cik lielā mērā ir iespējams, ka Jūs atrastu darbu ar līdzīgu atalgojumu?', 'Šo jautājumu uzdeva tiem respondentiem, kuri ir algoti darbinieki.'],
		['Y11_Q36a', 'Cik bieži Jūs esat iesaistīts(-a) rūpēs par Jūsu bērniem vai mazbērniem?', ''],
		['Y11_Q36b', 'Cik bieži Jūs gatavojat vai veicat mājsaimniecības darbus?', ''],
		['Y11_Q36c', 'Cik bieži Jūs esat iesaistīts(-a) rūpēs par saviem vecajiem vai nespējīgajiem radiniekiem?', ''],
		['Y11_Q38', 'Ko Jūs domājat par Jūsu mājsaimniecības darbu daļu?', ''],
		['Y11_Q39a', 'Attieksme pret laiku, kas pavadīts kontaktējoties ar ģimenes locekļiem', ''],
		['Y11_Q39b', 'Attieksme pret laiku, kas veltīts citiem sociālajiem kontaktiem', ''],
		['Y11_Q39c', 'Attieksme pret laiku, kas veltīts saviem hobijiem un interesēm', ''],
		['Y11_Q39d_stress', 'Stress, kas rodas darba un privātās dzīves līdzsvara trūkuma dēļ', ''],
		['Y11_Q24', 'Vai varat teikt, ka varat uzticēties lielākajai daļai cilvēku vai ka attiecībās ar cilvēkiem ir jābūt piesardzīgam?', ''],
		['Y11_Q25a', 'Apzinātas saspīlētas attiecības starp nabadzīgiem un bagātiem cilvēkiem', ''],
		['Y11_Q25b', 'Apzinātas saspīlētas attiecības starp vadītājiem un darbiniekiem', ''],
		['Y11_Q25c', 'Apzinātas saspīlētas attiecības starp vīriešiem un sievietēm', ''],
		['Y11_Q25d', 'Apzinātas saspīlētas attiecības starp veciem cilvēkiem un jauniem cilvēkiem', ''],
		['Y11_Q25e', 'Apzinātas saspīlētas attiecības starp dažādām rasēm un etniskām grupām', ''],
		['Y11_Q25f', 'Apzinātas saspīlētas attiecības starp dažādām reliģiskajām grupām', ''],
		['Y11_Q25g', 'Apzinātas saspīlētas attiecības starp cilvēkiem ar atšķirīgu seksuālo orientāciju', ''],
		['Y11_Q28a', 'Ticība parlamentam', ''],
		['Y11_Q28b', 'Ticība tiesu sistēmai', ''],
		['Y11_Q28c', 'Ticība presei', ''],
		['Y11_Q28d', 'Ticība policijai', ''],
		['Y11_Q28e', 'Ticība valdībai', ''],
		['Y11_Q28f', 'Ticība vietējai pašvaldībai', ''],
		['Y11_Q21a', 'Piedalīšanās dievkalpojumos, izņemot kāzu, bēru, kristību ceremonijas', ''],
		['Y11_Q21b', 'Interneta lietošana ar darbu nesaistītām vajadzībām', ''],
		['Y11_Q21c', 'Piedalīšanās sporta vai fiziskajās nodarbībās', ''],
		['Y11_Q21d', 'Piedalīšanās kāda kluba, biedrības vai asociācijas sabiedriskajās aktivitātēs', ''],
		['Y11_Q22_Volunteering', 'Cik bieži esat veicis(-kusi) neapmaksātu brīvprātīgo darbu pēdējo 12 mēnešu laikā?', ''],
		['Y11_Q23a', 'Esat piedalījies(-usies) arodbiedrības, politiskās partijas vai rīcības grupas sanāksmē pēdējo 12 mēnešu laikā', ''],
		['Y11_Q23b', 'Esat apmeklējis(-usi) protesta akciju vai demonstrāciju pēdējo 12 mēnešu laikā', ''],
		['Y11_Q23c', 'Esat parakstījis(-usi) petīciju (tostarp, izmantojot e-pastu vai tiešsaistē) pēdējo 12 mēnešu laikā', ''],
		['Y11_Q23d', 'Esat sazinājies(-usies) ar politiķi vai valsts ierēdni (cita iemesla dēļ, nevis ikdienas situācijās izmantojot sabiedrisko iestāžu pakalpojumus)', ''],
		['Y11_Q29e', 'Es jūtos sabiedrības atstumts(-a)', ''],
		['Y11_Q29f', 'Dzīve mūsdienās ir kļuvusi tik sarežģīta, ka es gandrīz nevaru atrast savu ceļu', ''],
		['Y11_Q29g', 'Es jūtu, ka citi nesaskata vērtību tajā, ko es daru', ''],
		['Y11_Q29h', 'Daži cilvēki uz mani skatās no augšas mana darba vai ienākumu dēļ', ''],
		['Y11_Q29i', 'Jūtos tuvs(‐a) savas dzīvesvietas cilvēkiem', ''],
		['Y11_SocExIndex', 'Sociālās atstumtības indekss', ''],
		['Y11_Q29a', 'Esmu optimistiski noskaņots(-a) par nākotni', ''],
		['Y11_Q29b', 'Vispār, es jūtu, ka tas, ko dzīvē daru, ir vērtīgs', ''],
		['Y11_Q29c', 'Es jūtu, ka varu izlemt, kā dzīvot savu dzīvi', ''],
		['Y11_Q29d', 'Ikdienas dzīvē man reti ir laiks darīt to, kas man patīk', ''],
		['Y11_Q30', 'Cik apmierināts(-a) Jūs šobrīd esat ar savu dzīvi?', ''],
		['Y11_Q40a', 'Apmierinātība ar izglītību', ''],
		['Y11_Q40b', 'Apmierinātība ar pašreizējo darbu', ''],
		['Y11_Q40c', 'Apmierinātība ar pašreizējo dzīves līmeni', ''],
		['Y11_Q40d', 'Apmierinātība ar mājokli', ''],
		['Y11_Q40e', 'Apmierinātība ar ģimenes dzīvi', ''],
		['Y11_Q40f', 'Apmierinātība ar veselību', ''],
		['Y11_Q40g', 'Apmierinātība ar sabiedrisko dzīvi', ''],
		['Y11_Q40h', 'Apmierinātība ar ekonomisko situāciju valstī', ''],
		['Y11_Q41', 'Ņemot vērā visu kopā, cik laimīgs(-a) Jūs esat?', ''],
		['Y11_Q42', 'Apzinātais veselības stāvoklis', ''],
		['Y11_Q46a', 'Esmu izjutis(-usi) īpašu spriedzi', ''],
		['Y11_Q46b', 'Esmu juties(-usies) vientuļi', ''],
		['Y11_Q46c', 'Esmu juties(-usies) drūms(-a) un nomākts(-a)', ''],
		['Y11_Q46d_WHO5', 'PVO-5 garīgās labsajūtas skala', ''],
		['Y11_Q47a', 'Grūtības apmeklēt ārstu, jo ārsta prakse vai slimnīca atrodas tālu', ''],
		['Y11_Q47b', 'Grūtības apmeklēt ārstu, jo ilgi jāgaida pieraksts', ''],
		['Y11_Q47c', 'Grūtības apmeklēt ārstu, jo pieraksta dienā ir ilgi jāgaida, lai varētu satikt ārstu', ''],
		['Y11_Q47d', 'Grūtības apmeklēt ārstu apmeklējuma izmaksu dēļ', ''],
		['Y11_Q47e', 'Grūtības apmeklēt ārstu, jo tam pietrūkst laika darba vai aprūpes pienākumu dēļ', ''],
		['Y11_Q53a', 'Kā Jūs novērtētu veselības aprūpes pakalpojumu kvalitāti savā valstī?', ''],
		['Y11_Q53b', 'Kā Jūs novērtētu izglītības sistēmas kvalitāti savā valstī?', ''],
		['Y11_Q53c', 'Kā Jūs novērtētu sabiedriskā transporta pakalpojumu kvalitāti savā valstī?', ''],
		['Y11_Q53d', 'Kā Jūs novērtētu bērnu aprūpes pakalpojumu kvalitāti savā valstī?', ''],
		['Y11_Q53e', 'Kā Jūs novērtētu ilgstošas aprūpes pakalpojumu kvalitāti savā valstī?', ''],
		['Y11_Q53f', 'Kā Jūs novērtētu sociālo mājokļu pakalpojumu kvalitāti savā valstī?', ''],
		['Y11_Q53g', 'Kā Jūs novērtētu valsts pensiju sistēmas kvalitāti savā valstī?', ''],
		['Y11_Q33a', 'Klātienes tikšanās ar bērniem, kuri nedzīvo mājsaimniecībā', ''],
		['Y11_Q33b', 'Klātienes tikšanās ar māti vai tēvu, kuri nedzīvo mājsaimniecībā', ''],
		['Y11_Q33c', 'Klātienes tikšanās ar brāli, māsu vai citu radinieku, kurš nedzīvo mājsaimniecībā', ''],
		['Y11_Q33d', 'Klātienes tikšanās ar draugiem vai kaimiņiem, kuri nedzīvo mājsaimniecībā', ''],
		['Y11_Q34a', 'Saziņa ar bērniem, kuri nedzīvo mājsaimniecībā, pa tālruni, internetā vai pa pastu', ''],
		['Y11_Q34b', 'Saziņa ar māti vai tēvu, kuri nedzīvo mājsaimniecībā, pa tālruni, internetā vai pa pastu', ''],
		['Y11_Q34c', 'Saziņa ar brāli, māsu, citu radinieku, kurš nedzīvo mājsaimniecībā, pa tālruni, internetā vai pa pastu', ''],
		['Y11_Q34d', 'Saziņa ar draugiem vai kaimiņiem, kuri nedzīvo mājsaimniecībā, pa tālruni, internetā vai pa pastu', ''],
		['Y11_Q35a', 'No kā Jūs varētu saņemt atbalstu, ja Jums būtu vajadzīga palīdzība mājās slimības laikā?', ''],
		['Y11_Q35b', 'No kā Jūs varētu saņemt atbalstu, ja Jums būtu vajadzīgs padoms nopietnā personīgā vai ģimenes jautājumā?', ''],
		['Y11_Q35c', 'No kā Jūs varētu saņemt atbalstu, ja Jums būtu vajadzīga palīdzība, meklējot darbu?', ''],
		['Y11_Q35d', 'No kā Jūs varētu saņemt atbalstu, ja justos nedaudz nomākts(-a) un gribētu ar kādu aprunāties?', ''],
		['Y11_Q35e', 'No kā Jūs varētu saņemt atbalstu, ja Jums steidzami būtu vajadzīgi 1000 euro neparedzētiem izdevumiem?', '']
	];
