//Auto Generated file
var subset_
	 = [
	
		['Y11_Agecategory', 'Età'],
		['Y11_Incomequartiles_percapita', 'Introjtu'],
		['Y11_HH2a', 'Sess']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'L-etajiet kollha'],
		['Y11_Agecategory', '1--18-24y', 'minn 18 sa 24 sena'],
		['Y11_Agecategory', '2--25-34y', 'minn 25 sa 34 sena'],
		['Y11_Agecategory', '3--35-49y', 'minn 35 sa 49 sena'],
		['Y11_Agecategory', '4--50-64y', 'minn 50 sa 64 sena'],
		['Y11_Agecategory', '5---64y', '> 64 sena'],
		['Y11_HH2a', 'All', 'Iż-żewġ sessi'],
		['Y11_HH2a', '1--Female', 'Nisa'],
		['Y11_HH2a', '2--Male', 'Irġiel'],
		['Y11_Incomequartiles_percapita', 'All', 'Il-livelli kollha ta’ introjtu'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'L-inqas'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'It-tieni'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'It-tielet'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'L-ogħla']
	];
var topic_
	 = [
	
		['', 'Kollha (127)'],
		['Il-benesseri suġġettiv', 'Il-benesseri suġġettiv (14)'],
		['Il-familja u l-ħajja soċjali', 'Il-familja u l-ħajja soċjali (13)'],
		['Il-kwalità tas-soċjetà', 'Il-kwalità tas-soċjetà (14)'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Il-livell tal-għajxien u l-privazzjoni (15)'],
		['Is-saħħa u s-servizzi pubbliċi', 'Is-saħħa u s-servizzi pubbliċi (17)'],
		['L-ambjent tad-dar u tal-lokalità', 'L-ambjent tad-dar u tal-lokalità (21)'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'L-esklużjoni soċjali u l-involviment fil-komunità (15)'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja (18)']
	];
var topic_question
	 = [
	
		['Il-benesseri suġġettiv', 'Y11_Q29a', 'Jien ottimist/a dwar il-futur'],
		['Il-benesseri suġġettiv', 'Y11_Q29b', 'B’mod ġenerali nħoss li dak li nagħmel fil-ħajja għandu valur'],
		['Il-benesseri suġġettiv', 'Y11_Q29c', 'Inħossni ħieles/ħielsa li niddeċiedi kif ngħix ħajti'],
		['Il-benesseri suġġettiv', 'Y11_Q29d', 'Fil-ħajja tiegħi ta’ kuljum rari nsib ħin nagħmel dak li tassew jagħtini gost'],
		['Il-benesseri suġġettiv', 'Y11_Q30', 'Kemm inti sodisfatt/a b’ħajtek bħalissa?'],
		['Il-benesseri suġġettiv', 'Y11_Q40a', 'Sodisfazzjon bl-edukazzjoni'],
		['Il-benesseri suġġettiv', 'Y11_Q40b', 'Sodisfazzjon bl-impjieg preżenti'],
		['Il-benesseri suġġettiv', 'Y11_Q40c', 'Sodisfazzjon bil-livell preżenti tal-għajxien'],
		['Il-benesseri suġġettiv', 'Y11_Q40d', 'Sodisfazzjon bl-akkomodazzjoni'],
		['Il-benesseri suġġettiv', 'Y11_Q40e', 'Sodisfazzjon bil-ħajja tal-familja'],
		['Il-benesseri suġġettiv', 'Y11_Q40f', 'Sodisfazzjon bis-saħħa'],
		['Il-benesseri suġġettiv', 'Y11_Q40g', 'Sodisfazzjon bil-ħajja soċjali'],
		['Il-benesseri suġġettiv', 'Y11_Q40h', 'Sodisfazzjon bis-sitwazzjoni ekonomika fil-pajjiż'],
		['Il-benesseri suġġettiv', 'Y11_Q41', 'Meta tqis kollox, kemm tgħid li inti kuntent/a?'],
		['Il-familja u l-ħajja soċjali', 'Y11_Q33a', 'Kuntatt wiċċ imb wiċċ ma’ wlied li ma jgħixux fid-dar'],
		['Il-familja u l-ħajja soċjali', 'Y11_Q33b', 'Kuntatt wiċċ imb wiċċ ma’ omm jew missier li ma jgħixux fid-dar'],
		['Il-familja u l-ħajja soċjali', 'Y11_Q33c', 'Kuntatt wiċċ imb wiċċ ma’ qraba oħra li ma jgħixux fid-dar'],
		['Il-familja u l-ħajja soċjali', 'Y11_Q33d', 'Kuntatt wiċċ imb wiċċ ma’ ħbieb jew ġirien'],
		['Il-familja u l-ħajja soċjali', 'Y11_Q34a', 'Kuntatt bit-telefown, bl-internet jew bil-posta ma’ wlied li ma jgħixux fid-dar'],
		['Il-familja u l-ħajja soċjali', 'Y11_Q34b', 'Kuntatt bit-telefown, bl-internet jew bil-posta ma’ omm jew missier li ma jgħixux fid-dar'],
		['Il-familja u l-ħajja soċjali', 'Y11_Q34c', 'Kuntatt bit-telefown, bl-internet jew bil-posta ma’ qraba oħra li ma jgħixux fid-dar'],
		['Il-familja u l-ħajja soċjali', 'Y11_Q34d', 'Kuntatt bit-telefown, bl-internet jew bil-posta ma’ ħbieb jew ġirien'],
		['Il-familja u l-ħajja soċjali', 'Y11_Q35a', 'Jekk tkun ma tiflaħx, mingħand min issib għajnuna fix-xogħol tad-dar?'],
		['Il-familja u l-ħajja soċjali', 'Y11_Q35b', 'Jekk tkun teħtieġ parir dwar xi affari personali jew familjari serja, mingħand min issib għajnuna?'],
		['Il-familja u l-ħajja soċjali', 'Y11_Q35c', 'Jekk tkun qed tfittex xogħol, mingħand min issib għajnuna?'],
		['Il-familja u l-ħajja soċjali', 'Y11_Q35d', 'Jekk tħossok xi ftit depress/a, mingħand min issib għajnuna?'],
		['Il-familja u l-ħajja soċjali', 'Y11_Q35e', 'F’każ li tkun trid 1000 ewro f’idejk b’mod urġenti, mingħand min issib għajnuna?'],
		['Il-kwalità tas-soċjetà', 'Y11_Q24', 'Taħseb li ħafna nies huma ta’ min jafdahom jew li qatt ma tista’ tkun kawt/a biżżejjed meta jkollok x’taqsam man-nies?'],
		['Il-kwalità tas-soċjetà', 'Y11_Q25a', 'Kemm tara li hawn tensjoni bejn il-foqra u s-sinjuri'],
		['Il-kwalità tas-soċjetà', 'Y11_Q25b', 'Kemm tara li hawn tensjoni bejn il-maniġment u l-ħaddiema'],
		['Il-kwalità tas-soċjetà', 'Y11_Q25c', 'Kemm tara li hawn tensjoni bejn l-irġiel u n-nisa'],
		['Il-kwalità tas-soċjetà', 'Y11_Q25d', 'Kemm tara li hawn tensjoni bejn l-anzjani u ż-żgħażagħ'],
		['Il-kwalità tas-soċjetà', 'Y11_Q25e', 'Kemm tara li hawn tensjoni bejn razez differenti u gruppi etniċi'],
		['Il-kwalità tas-soċjetà', 'Y11_Q25f', 'Kemm tara li hawn tensjoni bejn gruppi reliġjużi differenti'],
		['Il-kwalità tas-soċjetà', 'Y11_Q25g', 'Kemm tara li hawn tensjoni bejn nies b’orjentazzjoni sesswali differenti'],
		['Il-kwalità tas-soċjetà', 'Y11_Q28a', 'Il-fiduċja fil-parlament'],
		['Il-kwalità tas-soċjetà', 'Y11_Q28b', 'Il-fiduċja fis-sistema legali'],
		['Il-kwalità tas-soċjetà', 'Y11_Q28c', 'Il-fiduċja fl-istampa'],
		['Il-kwalità tas-soċjetà', 'Y11_Q28d', 'Il-fiduċja fil-pulizija'],
		['Il-kwalità tas-soċjetà', 'Y11_Q28e', 'Il-fiduċja fil-gvern'],
		['Il-kwalità tas-soċjetà', 'Y11_Q28f', 'Il-fiduċja fl-awtoritajiet lokali jew muniċipali'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Deprindex', 'Indiċi ta privazzjoni: Numru ta oġġetti li l-familja ma tistax tħallas'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Q57', 'Is-sitwazzjoni finanzjarja tal-familja tiegħek imqabbla ma’ dik tal-biċċa l-kbira tan-nies f’pajjiżek'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Q58', 'Il-familja tiegħek jirnexxilha tlaħħaq mal-ispejjeż?'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Q59a', 'Tiflaħ iżżomm darek sħuna biżżejjed?'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Q59b', 'Tiflaħ tħallas biex tmur ġimgħa btala ’l bogħod mid-dar kull sena?'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Q59c', 'Tiflaħ tbiddel xi għamara li spiċċat?'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Q59d', 'Għandek biex (jekk trid) tiekol il-laħam, it-tiġieġ jew il-ħut kull jumejn?'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Q59e', 'Tiflaħ tixtri ħwejjeġ ġodda aktar milli użati?'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Q59f', 'Tiflaħ tistieden xi ħbieb jew qraba għal drink jew ikla għallinqas darba fix-xahar?'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Q60a', 'Fl-aħħar 12-il xahar, il-familja tiegħek qatt waqgħet lura fil-ħlas tal-kera jew ta’ pagamenti ta’ self għall-akkomodazzjoni?'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Q60b', 'Fl-aħħar 12-il xahar, il-familja tiegħek qatt waqgħet lura fil-ħlas ta’ kontijiet utilitarji?'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Q60c', 'Fl-aħħar 12-il xahar, il-familja tiegħek qatt waqgħet lura fil-ħlas ta’ kontijiet relatati ma’ self għall-konsum?'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Q60d', 'Fl-aħħar 12-il xahar, bħala familja qatt waqajtu lura  fil-ħlas ta’ self informali?'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Q65', 'Il-qagħda finanzjarja tal-familja mqabbla ma’ 12-il xahar ilu'],
		['Il-livell tal-għajxien u l-privazzjoni', 'Y11_Q66', 'Kif mistennija tkun il-qagħda finanzjarja fit-12-il xahar li ġejjin'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q42', 'Kif tara l-istat ta’ saħħtek'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q46a', 'Ħassejtni partikolarment nervuż'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q46b', 'Ħassejtni waħdi'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q46c', 'Ħassejtni mdejjaq/mdejqa u bla ħeġġa'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q46d_WHO5', 'L-iskala WHO-5 dwar il-benesseri mentali'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q47a', 'Diffikultà li tara tabib minħabba d-distanza'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q47b', 'Diffikultà li tara tabib għax iddum biex tingħata appuntament'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q47c', 'Diffikultà li tara tabib minħabba li l-ħin li tagħmel tistenna dakinhar tal-appuntament'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q47d', 'Diffikultà li tara tabib minħabba l-ispiża'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q47e', 'Diffikultà li tara tabib għax ma ssibx il-ħin'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q53a', 'Kif tikklassifika l-kwalità tas-servizzi tas-saħħa f’pajjiżek?'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q53b', 'Kif tikklassifika l-kwalità tas-sistema edukattiva f’pajjiżek?'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q53c', 'Kif tikklassifika l-kwalità tat-trasport pubbliku f’pajjiżek?'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q53d', 'Kif tikklassifika l-kwalità tas-servizzi tal-ħarsien tat-tfal f’pajjiżek?'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q53e', 'Kif tikklassifika l-kwalità tas-servizzi tal-ħarsien fit-tul f’pajjiżek?'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q53f', 'Kif tikklassifika l-kwalità tas-servizzi tal-akkomodazzjoni soċjali f’pajjiżek?'],
		['Is-saħħa u s-servizzi pubbliċi', 'Y11_Q53g', 'Kif tikklassifika l-kwalità tas-sistema tal-pensjonijiet tal-Istat f’pajjiżek?'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Accommproblems', 'Numru ta problemi bl-akkomodazzjoni'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q18', 'Il-pussess tad-dar'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q19a', 'Problemi ta’ akkomodazzjoni: Nuqqas ta’ spazju'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q19b', 'Problemi ta’ akkomodazzjoni: Twieqi, bibien jew art mherrija'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q19c', 'Problemi ta’ akkomodazzjoni: Ħitan jew soqfa umdi jew joqtru'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q19d', 'Problemi ta’ akkomodazzjoni: M’hemmx tojlit fuq ġewwa li jifflaxxja'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q19e', 'Problemi ta’ akkomodazzjoni: M’hemmx banju jew doċċa'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q19f', 'Problemi ta’ akkomodazzjoni: M’hemmx post fejn toħroġ għall-arja'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q20', 'Kemm hu probabbli li jkollok titlaq mill-post fejn toqgħod fis-6 xhur li ġejjin għax ma tiflaħx tħallas għalih?'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q50a', 'Problemi ta’ storbju fl-inħawi'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q50b', 'Problemi bil-kwalità tal-arja fl-inħawi'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q50c', 'Problemi bil-kwalità tal-ilma tax-xorb fl-inħawi'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q50d', 'Problemi ta’ kriminalità, vjolenza jew vandaliżmu fl-inħawi'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q50e', 'Problemi ta’ skart jew żibel fit-triq'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q50f', 'Problemi ta’ konġestjoni tat-traffiku fl-inħawi'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q51a', 'Aċċess għas-servizzi postali'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q51b', 'Aċċess għas-servizzi bankarji'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q51c', 'Aċċess għall-faċilitajiet tat-trasport pubbliku'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q51d', 'Aċċess għaċ-ċinema, għat-teatru jew għal xi ċentru kulturali'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q51e', 'Aċċess għal postijiet ta’ rikreazzjoni u ġonna'],
		['L-ambjent tad-dar u tal-lokalità', 'Y11_Q52', 'Ħin li tagħmel tivvjaġġa biex tmur għax-xogħol jew fejn tistudja'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_Q21a', 'Attendenza f’servizzi reliġjużi minbarra tiġijiet, funerali u magħmudijiet'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_Q21b', 'Użu tal-internet mhux għax-xogħol'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_Q21c', 'Prattika ta’ xi sport jew eżerċizzju fiżiku'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_Q21d', 'Parteċipazzjoni f’attivitajiet soċjali ta’ każin, soċjetà jew assoċjazzjoni'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_Q22_Volunteering', 'Kemm għamilt ta’ spiss xogħol volontarju bla ħlas fl-aħħar 12-il xahar?'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_Q23a', 'Attendejt laqgħa ta’ xi trejdjunjin, partit politiku jew grupp ta’ azzjoni fl-aħħar 12-il xahar'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_Q23b', 'Attendejt protesta jew dimostrazzjoni fl-aħħar 12-il xahar'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_Q23c', 'Iffirmajt petizzjoni fl-aħħar 12-il xahar'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_Q23d', 'Ikkuntattjajt politiku jew uffiċjal pubbliku (minbarra kuntatti ta’ rutina bl-użu ta’ servizzi pubbliċi)'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_Q29e', 'Inħossni eskluż mis-soċjetà'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_Q29f', 'Il-ħajja tant saret ikkumplikata li kważi nħossni mitluf/a'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_Q29g', 'Inħoss li l-valur ta’ dak li nagħmel mhuwiex rikonoxxut minn ħaddieħor'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_Q29h', 'Xi nies iqisuni anqas minnhom minħabba s-sitwazzjoni tax-xogħol tiegħi jew minħabba kemm indaħħal'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_Q29i', 'Inħossni qrib tan-nies tal-inħawi fejn ngħix'],
		['L-esklużjoni soċjali u l-involviment fil-komunità', 'Y11_SocExIndex', 'Indiċi tal-Esklużjoni Soċjali'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q8_PreferredWorkingHours', 'Kemm tippreferi li taħdem sigħat fil-ġimgħa?'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q10_Partnerprefhours', 'Kemm tippreferi li j/taħdem sigħat fil-ġimgħa is-sieħeb/sieħba tiegħek?'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q12a', 'Ġejt mix-xogħol għajjien/a wisq biex nagħmel il-faċendi tad-dar'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q12b', 'Sibtha diffiċli nlaħħaq mar-responsabbiltajiet tal-familja minħabba l-ħin li nqatta’ fuq ix-xogħol'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q12c', 'Sibtha diffiċli nikkonċentra fuq ix-xogħol minħabba r-responsabbiltajiet tal-familja'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q13a', 'Nista’ nvarja xħin nibda x-xogħol u xħin nispiċċa'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q13b', 'Nista’ niġma’ s-sigħat biex ikolli l-frank'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q13c', 'Meta jkolli bżonn, nista’ nieħu ġurnata frank billi navża fi żmien qasir'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q15', 'Kemm hu probabbli li titlef l-impjieg fis-6 xhur li ġejjin?'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q16', 'Jekk titlef l-impjieg, kemm hu probabbli li ssib impjieg ieħor b’salarju simili?'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q36a', 'Kemm spiss tqatta’ ħin tieħu ħsieb uliedek jew ulied uliedek?'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q36b', 'Kemm spiss tqatta’ ħin fit-tisjir jew fil-faċendi?'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q36c', 'Kemm spiss tqatta’ ħin tieħu ħsieb qraba anzjani jew b’diżabilità?'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q38', 'L-attitudni lejn is-sehem fil-faċendi tad-dar'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q39a', 'L-attitudni lejn il-ħin li tqatta’ mal-membri tal-familja'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q39b', 'L-attitudni lejn il-ħin li tqatta’ mal-oħrajn'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q39c', 'L-attitudni lejn il-ħin li tqatta f’passatempi u interessi oħra'],
		['L-impjieg u l-bilanċ bejn ix-xogħol u l-ħajja', 'Y11_Q39d_stress', 'L-istress']
	];
var question_
	 = [
	
		['Y11_Q29a', 'Jien ottimist/a dwar il-futur'],
		['Y11_Q29b', 'B’mod ġenerali nħoss li dak li nagħmel fil-ħajja għandu valur'],
		['Y11_Q29c', 'Inħossni ħieles/ħielsa li niddeċiedi kif ngħix ħajti'],
		['Y11_Q29d', 'Fil-ħajja tiegħi ta’ kuljum rari nsib ħin nagħmel dak li tassew jagħtini gost'],
		['Y11_Q30', 'Kemm inti sodisfatt/a b’ħajtek bħalissa?'],
		['Y11_Q40a', 'Sodisfazzjon bl-edukazzjoni'],
		['Y11_Q40b', 'Sodisfazzjon bl-impjieg preżenti'],
		['Y11_Q40c', 'Sodisfazzjon bil-livell preżenti tal-għajxien'],
		['Y11_Q40d', 'Sodisfazzjon bl-akkomodazzjoni'],
		['Y11_Q40e', 'Sodisfazzjon bil-ħajja tal-familja'],
		['Y11_Q40f', 'Sodisfazzjon bis-saħħa'],
		['Y11_Q40g', 'Sodisfazzjon bil-ħajja soċjali'],
		['Y11_Q40h', 'Sodisfazzjon bis-sitwazzjoni ekonomika fil-pajjiż'],
		['Y11_Q41', 'Meta tqis kollox, kemm tgħid li inti kuntent/a?'],
		['Y11_Q33a', 'Kuntatt wiċċ imb wiċċ ma’ wlied li ma jgħixux fid-dar'],
		['Y11_Q33b', 'Kuntatt wiċċ imb wiċċ ma’ omm jew missier li ma jgħixux fid-dar'],
		['Y11_Q33c', 'Kuntatt wiċċ imb wiċċ ma’ qraba oħra li ma jgħixux fid-dar'],
		['Y11_Q33d', 'Kuntatt wiċċ imb wiċċ ma’ ħbieb jew ġirien'],
		['Y11_Q34a', 'Kuntatt bit-telefown, bl-internet jew bil-posta ma’ wlied li ma jgħixux fid-dar'],
		['Y11_Q34b', 'Kuntatt bit-telefown, bl-internet jew bil-posta ma’ omm jew missier li ma jgħixux fid-dar'],
		['Y11_Q34c', 'Kuntatt bit-telefown, bl-internet jew bil-posta ma’ qraba oħra li ma jgħixux fid-dar'],
		['Y11_Q34d', 'Kuntatt bit-telefown, bl-internet jew bil-posta ma’ ħbieb jew ġirien'],
		['Y11_Q35a', 'Jekk tkun ma tiflaħx, mingħand min issib għajnuna fix-xogħol tad-dar?'],
		['Y11_Q35b', 'Jekk tkun teħtieġ parir dwar xi affari personali jew familjari serja, mingħand min issib għajnuna?'],
		['Y11_Q35c', 'Jekk tkun qed tfittex xogħol, mingħand min issib għajnuna?'],
		['Y11_Q35d', 'Jekk tħossok xi ftit depress/a, mingħand min issib għajnuna?'],
		['Y11_Q35e', 'F’każ li tkun trid 1000 ewro f’idejk b’mod urġenti, mingħand min issib għajnuna?'],
		['Y11_Q24', 'Taħseb li ħafna nies huma ta’ min jafdahom jew li qatt ma tista’ tkun kawt/a biżżejjed meta jkollok x’taqsam man-nies?'],
		['Y11_Q25a', 'Kemm tara li hawn tensjoni bejn il-foqra u s-sinjuri'],
		['Y11_Q25b', 'Kemm tara li hawn tensjoni bejn il-maniġment u l-ħaddiema'],
		['Y11_Q25c', 'Kemm tara li hawn tensjoni bejn l-irġiel u n-nisa'],
		['Y11_Q25d', 'Kemm tara li hawn tensjoni bejn l-anzjani u ż-żgħażagħ'],
		['Y11_Q25e', 'Kemm tara li hawn tensjoni bejn razez differenti u gruppi etniċi'],
		['Y11_Q25f', 'Kemm tara li hawn tensjoni bejn gruppi reliġjużi differenti'],
		['Y11_Q25g', 'Kemm tara li hawn tensjoni bejn nies b’orjentazzjoni sesswali differenti'],
		['Y11_Q28a', 'Il-fiduċja fil-parlament'],
		['Y11_Q28b', 'Il-fiduċja fis-sistema legali'],
		['Y11_Q28c', 'Il-fiduċja fl-istampa'],
		['Y11_Q28d', 'Il-fiduċja fil-pulizija'],
		['Y11_Q28e', 'Il-fiduċja fil-gvern'],
		['Y11_Q28f', 'Il-fiduċja fl-awtoritajiet lokali jew muniċipali'],
		['Y11_Deprindex', 'Indiċi ta privazzjoni: Numru ta oġġetti li l-familja ma tistax tħallas'],
		['Y11_Q57', 'Is-sitwazzjoni finanzjarja tal-familja tiegħek imqabbla ma’ dik tal-biċċa l-kbira tan-nies f’pajjiżek'],
		['Y11_Q58', 'Il-familja tiegħek jirnexxilha tlaħħaq mal-ispejjeż?'],
		['Y11_Q59a', 'Tiflaħ iżżomm darek sħuna biżżejjed?'],
		['Y11_Q59b', 'Tiflaħ tħallas biex tmur ġimgħa btala ’l bogħod mid-dar kull sena?'],
		['Y11_Q59c', 'Tiflaħ tbiddel xi għamara li spiċċat?'],
		['Y11_Q59d', 'Għandek biex (jekk trid) tiekol il-laħam, it-tiġieġ jew il-ħut kull jumejn?'],
		['Y11_Q59e', 'Tiflaħ tixtri ħwejjeġ ġodda aktar milli użati?'],
		['Y11_Q59f', 'Tiflaħ tistieden xi ħbieb jew qraba għal drink jew ikla għallinqas darba fix-xahar?'],
		['Y11_Q60a', 'Fl-aħħar 12-il xahar, il-familja tiegħek qatt waqgħet lura fil-ħlas tal-kera jew ta’ pagamenti ta’ self għall-akkomodazzjoni?'],
		['Y11_Q60b', 'Fl-aħħar 12-il xahar, il-familja tiegħek qatt waqgħet lura fil-ħlas ta’ kontijiet utilitarji?'],
		['Y11_Q60c', 'Fl-aħħar 12-il xahar, il-familja tiegħek qatt waqgħet lura fil-ħlas ta’ kontijiet relatati ma’ self għall-konsum?'],
		['Y11_Q60d', 'Fl-aħħar 12-il xahar, bħala familja qatt waqajtu lura  fil-ħlas ta’ self informali?'],
		['Y11_Q65', 'Il-qagħda finanzjarja tal-familja mqabbla ma’ 12-il xahar ilu'],
		['Y11_Q66', 'Kif mistennija tkun il-qagħda finanzjarja fit-12-il xahar li ġejjin'],
		['Y11_Q42', 'Kif tara l-istat ta’ saħħtek'],
		['Y11_Q46a', 'Ħassejtni partikolarment nervuż'],
		['Y11_Q46b', 'Ħassejtni waħdi'],
		['Y11_Q46c', 'Ħassejtni mdejjaq/mdejqa u bla ħeġġa'],
		['Y11_Q46d_WHO5', 'L-iskala WHO-5 dwar il-benesseri mentali'],
		['Y11_Q47a', 'Diffikultà li tara tabib minħabba d-distanza'],
		['Y11_Q47b', 'Diffikultà li tara tabib għax iddum biex tingħata appuntament'],
		['Y11_Q47c', 'Diffikultà li tara tabib minħabba li l-ħin li tagħmel tistenna dakinhar tal-appuntament'],
		['Y11_Q47d', 'Diffikultà li tara tabib minħabba l-ispiża'],
		['Y11_Q47e', 'Diffikultà li tara tabib għax ma ssibx il-ħin'],
		['Y11_Q53a', 'Kif tikklassifika l-kwalità tas-servizzi tas-saħħa f’pajjiżek?'],
		['Y11_Q53b', 'Kif tikklassifika l-kwalità tas-sistema edukattiva f’pajjiżek?'],
		['Y11_Q53c', 'Kif tikklassifika l-kwalità tat-trasport pubbliku f’pajjiżek?'],
		['Y11_Q53d', 'Kif tikklassifika l-kwalità tas-servizzi tal-ħarsien tat-tfal f’pajjiżek?'],
		['Y11_Q53e', 'Kif tikklassifika l-kwalità tas-servizzi tal-ħarsien fit-tul f’pajjiżek?'],
		['Y11_Q53f', 'Kif tikklassifika l-kwalità tas-servizzi tal-akkomodazzjoni soċjali f’pajjiżek?'],
		['Y11_Q53g', 'Kif tikklassifika l-kwalità tas-sistema tal-pensjonijiet tal-Istat f’pajjiżek?'],
		['Y11_Accommproblems', 'Numru ta problemi bl-akkomodazzjoni'],
		['Y11_Q18', 'Il-pussess tad-dar'],
		['Y11_Q19a', 'Problemi ta’ akkomodazzjoni: Nuqqas ta’ spazju'],
		['Y11_Q19b', 'Problemi ta’ akkomodazzjoni: Twieqi, bibien jew art mherrija'],
		['Y11_Q19c', 'Problemi ta’ akkomodazzjoni: Ħitan jew soqfa umdi jew joqtru'],
		['Y11_Q19d', 'Problemi ta’ akkomodazzjoni: M’hemmx tojlit fuq ġewwa li jifflaxxja'],
		['Y11_Q19e', 'Problemi ta’ akkomodazzjoni: M’hemmx banju jew doċċa'],
		['Y11_Q19f', 'Problemi ta’ akkomodazzjoni: M’hemmx post fejn toħroġ għall-arja'],
		['Y11_Q20', 'Kemm hu probabbli li jkollok titlaq mill-post fejn toqgħod fis-6 xhur li ġejjin għax ma tiflaħx tħallas għalih?'],
		['Y11_Q50a', 'Problemi ta’ storbju fl-inħawi'],
		['Y11_Q50b', 'Problemi bil-kwalità tal-arja fl-inħawi'],
		['Y11_Q50c', 'Problemi bil-kwalità tal-ilma tax-xorb fl-inħawi'],
		['Y11_Q50d', 'Problemi ta’ kriminalità, vjolenza jew vandaliżmu fl-inħawi'],
		['Y11_Q50e', 'Problemi ta’ skart jew żibel fit-triq'],
		['Y11_Q50f', 'Problemi ta’ konġestjoni tat-traffiku fl-inħawi'],
		['Y11_Q51a', 'Aċċess għas-servizzi postali'],
		['Y11_Q51b', 'Aċċess għas-servizzi bankarji'],
		['Y11_Q51c', 'Aċċess għall-faċilitajiet tat-trasport pubbliku'],
		['Y11_Q51d', 'Aċċess għaċ-ċinema, għat-teatru jew għal xi ċentru kulturali'],
		['Y11_Q51e', 'Aċċess għal postijiet ta’ rikreazzjoni u ġonna'],
		['Y11_Q52', 'Ħin li tagħmel tivvjaġġa biex tmur għax-xogħol jew fejn tistudja'],
		['Y11_Q21a', 'Attendenza f’servizzi reliġjużi minbarra tiġijiet, funerali u magħmudijiet'],
		['Y11_Q21b', 'Użu tal-internet mhux għax-xogħol'],
		['Y11_Q21c', 'Prattika ta’ xi sport jew eżerċizzju fiżiku'],
		['Y11_Q21d', 'Parteċipazzjoni f’attivitajiet soċjali ta’ każin, soċjetà jew assoċjazzjoni'],
		['Y11_Q22_Volunteering', 'Kemm għamilt ta’ spiss xogħol volontarju bla ħlas fl-aħħar 12-il xahar?'],
		['Y11_Q23a', 'Attendejt laqgħa ta’ xi trejdjunjin, partit politiku jew grupp ta’ azzjoni fl-aħħar 12-il xahar'],
		['Y11_Q23b', 'Attendejt protesta jew dimostrazzjoni fl-aħħar 12-il xahar'],
		['Y11_Q23c', 'Iffirmajt petizzjoni fl-aħħar 12-il xahar'],
		['Y11_Q23d', 'Ikkuntattjajt politiku jew uffiċjal pubbliku (minbarra kuntatti ta’ rutina bl-użu ta’ servizzi pubbliċi)'],
		['Y11_Q29e', 'Inħossni eskluż mis-soċjetà'],
		['Y11_Q29f', 'Il-ħajja tant saret ikkumplikata li kważi nħossni mitluf/a'],
		['Y11_Q29g', 'Inħoss li l-valur ta’ dak li nagħmel mhuwiex rikonoxxut minn ħaddieħor'],
		['Y11_Q29h', 'Xi nies iqisuni anqas minnhom minħabba s-sitwazzjoni tax-xogħol tiegħi jew minħabba kemm indaħħal'],
		['Y11_Q29i', 'Inħossni qrib tan-nies tal-inħawi fejn ngħix'],
		['Y11_SocExIndex', 'Indiċi tal-Esklużjoni Soċjali'],
		['Y11_Q8_PreferredWorkingHours', 'Kemm tippreferi li taħdem sigħat fil-ġimgħa?'],
		['Y11_Q10_Partnerprefhours', 'Kemm tippreferi li j/taħdem sigħat fil-ġimgħa is-sieħeb/sieħba tiegħek?'],
		['Y11_Q12a', 'Ġejt mix-xogħol għajjien/a wisq biex nagħmel il-faċendi tad-dar'],
		['Y11_Q12b', 'Sibtha diffiċli nlaħħaq mar-responsabbiltajiet tal-familja minħabba l-ħin li nqatta’ fuq ix-xogħol'],
		['Y11_Q12c', 'Sibtha diffiċli nikkonċentra fuq ix-xogħol minħabba r-responsabbiltajiet tal-familja'],
		['Y11_Q13a', 'Nista’ nvarja xħin nibda x-xogħol u xħin nispiċċa'],
		['Y11_Q13b', 'Nista’ niġma’ s-sigħat biex ikolli l-frank'],
		['Y11_Q13c', 'Meta jkolli bżonn, nista’ nieħu ġurnata frank billi navża fi żmien qasir'],
		['Y11_Q15', 'Kemm hu probabbli li titlef l-impjieg fis-6 xhur li ġejjin?'],
		['Y11_Q16', 'Jekk titlef l-impjieg, kemm hu probabbli li ssib impjieg ieħor b’salarju simili?'],
		['Y11_Q36a', 'Kemm spiss tqatta’ ħin tieħu ħsieb uliedek jew ulied uliedek?'],
		['Y11_Q36b', 'Kemm spiss tqatta’ ħin fit-tisjir jew fil-faċendi?'],
		['Y11_Q36c', 'Kemm spiss tqatta’ ħin tieħu ħsieb qraba anzjani jew b’diżabilità?'],
		['Y11_Q38', 'L-attitudni lejn is-sehem fil-faċendi tad-dar'],
		['Y11_Q39a', 'L-attitudni lejn il-ħin li tqatta’ mal-membri tal-familja'],
		['Y11_Q39b', 'L-attitudni lejn il-ħin li tqatta’ mal-oħrajn'],
		['Y11_Q39c', 'L-attitudni lejn il-ħin li tqatta f’passatempi u interessi oħra'],
		['Y11_Q39d_stress', 'L-istress']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Medja'],
		['Y11_Deprindex', 'Mean', 'Medja'],
		['Y11_Q10_Partnerprefhours', '1--Work-less', 'J/taħdem inqas'],
		['Y11_Q10_Partnerprefhours', '2--Work-the-same', 'J/taħdem l-istess'],
		['Y11_Q10_Partnerprefhours', '3--Work-more', 'J/taħdem iktar'],
		['Y11_Q12a', '1--Several-times-a-week', 'Ħafna drabi matul il-ġimgħa'],
		['Y11_Q12a', '2--Several-times-a-month', 'Ħafna drabi matul ix-xahar'],
		['Y11_Q12a', '3--Several-times-a-year', 'Ħafna drabi matul is-sena'],
		['Y11_Q12a', '4--Less-often-rarely', 'Inqas spiss jew rari'],
		['Y11_Q12a', '5--Never', 'Qatt'],
		['Y11_Q12b', '1--Several-times-a-week', 'Ħafna drabi matul il-ġimgħa'],
		['Y11_Q12b', '2--Several-times-a-month', 'Ħafna drabi matul ix-xahar'],
		['Y11_Q12b', '3--Several-times-a-year', 'Ħafna drabi matul is-sena'],
		['Y11_Q12b', '4--Less-often-rarely', 'Inqas spiss jew rari'],
		['Y11_Q12b', '5--Never', 'Qatt'],
		['Y11_Q12c', '1--Several-times-a-week', 'Ħafna drabi matul il-ġimgħa'],
		['Y11_Q12c', '2--Several-times-a-month', 'Ħafna drabi matul ix-xahar'],
		['Y11_Q12c', '3--Several-times-a-year', 'Ħafna drabi matul is-sena'],
		['Y11_Q12c', '4--Less-often-rarely', 'Inqas spiss jew rari'],
		['Y11_Q12c', '5--Never', 'Qatt'],
		['Y11_Q13a', '1--Yes', 'Iva'],
		['Y11_Q13a', '2--No', 'Le'],
		['Y11_Q13b', '1--Yes', 'Iva'],
		['Y11_Q13b', '2--No', 'Le'],
		['Y11_Q13c', '1--Yes', 'Iva'],
		['Y11_Q13c', '2--No', 'Le'],
		['Y11_Q15', '1--Very-likely', 'X’aktarx li iva'],
		['Y11_Q15', '2--Quite-likely', 'Pjuttost probabbli'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'La probabbli u lanqas le'],
		['Y11_Q15', '4--Quite-unlikely', 'Pjuttost mhux probabbli'],
		['Y11_Q15', '5--Very-unlikely', 'Improbabbli ħafna'],
		['Y11_Q16', '1--Very-likely', 'X’aktarx li iva'],
		['Y11_Q16', '2--Quite-likely', 'Probabbli ħafna'],
		['Y11_Q16', '3--Neither-likely-nor-unlikely', 'La probabbli u lanqas le'],
		['Y11_Q16', '4--Quite-unlikely', 'Pjuttost mhux probabbli'],
		['Y11_Q16', '5--Very-unlikely', 'Improbabbli ħafna'],
		['Y11_Q18', '1--Own-without-mortgage', 'Tiegħi u mingħajr dejn fuqha'],
		['Y11_Q18', '2--Own-with-mortgage', 'Tiegħi bid-dejn fuqha'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Kerrej, inħallas il-kera lill-Housing jew lill-Kurja'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Kerrej, inħallas il-kera lil sid il-kera privat'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Akkomodazzjoni pprovduta mingħajr kera'],
		['Y11_Q18', '6--Other', 'Oħrajn'],
		['Y11_Q19a', '1--Yes', 'Iva'],
		['Y11_Q19a', '2--No', 'Le'],
		['Y11_Q19b', '1--Yes', 'Iva'],
		['Y11_Q19b', '2--No', 'Le'],
		['Y11_Q19c', '1--Yes', 'Iva'],
		['Y11_Q19c', '2--No', 'Le'],
		['Y11_Q19d', '1--Yes', 'Iva'],
		['Y11_Q19d', '2--No', 'Le'],
		['Y11_Q19e', '1--Yes', 'Iva'],
		['Y11_Q19e', '2--No', 'Le'],
		['Y11_Q19f', '1--Yes', 'Iva'],
		['Y11_Q19f', '2--No', 'Le'],
		['Y11_Q20', '1--Very-likely', 'X’aktarx li iva'],
		['Y11_Q20', '2--Quite-likely', 'Pjuttost probabbli'],
		['Y11_Q20', '3--Quite-unlikely', 'Pjuttost mhux probabbli'],
		['Y11_Q20', '4--Very-unlikely', 'Improbabbli ħafna'],
		['Y11_Q21a', '1--Every-day-or-almost-every-day', 'Kuljum jew kważi kuljum'],
		['Y11_Q21a', '2--At-least-once-a-week', 'Tal-inqas darba fil-ġimgħa'],
		['Y11_Q21a', '3--One-to-three-times-a-month', 'Minn darba sa tliet darbiet fix-xahar'],
		['Y11_Q21a', '4--Less-often', 'Inqas spiss'],
		['Y11_Q21a', '5--Never', 'Qatt'],
		['Y11_Q21b', '1--Every-day-or-almost-every-day', 'Kuljum jew kważi kuljum'],
		['Y11_Q21b', '2--At-least-once-a-week', 'Tal-inqas darba fil-ġimgħa'],
		['Y11_Q21b', '3--One-to-three-times-a-month', 'Minn darba sa tliet darbiet fix-xahar'],
		['Y11_Q21b', '4--Less-often', 'Inqas spiss'],
		['Y11_Q21b', '5--Never', 'Qatt'],
		['Y11_Q21c', '1--Every-day-or-almost-every-day', 'Kuljum jew kważi kuljum'],
		['Y11_Q21c', '2--At-least-once-a-week', 'Tal-inqas darba fil-ġimgħa'],
		['Y11_Q21c', '3--One-to-three-times-a-month', 'Minn darba sa tliet darbiet fix-xahar'],
		['Y11_Q21c', '4--Less-often', 'Inqas spiss'],
		['Y11_Q21c', '5--Never', 'Qatt'],
		['Y11_Q21d', '1--Every-day-or-almost-every-day', 'Kuljum jew kważi kuljum'],
		['Y11_Q21d', '2--At-least-once-a-week', 'Tal-inqas darba fil-ġimgħa'],
		['Y11_Q21d', '3--One-to-three-times-a-month', 'Minn darba sa tliet darbiet fix-xahar'],
		['Y11_Q21d', '4--Less-often', 'Inqas spiss'],
		['Y11_Q21d', '5--Never', 'Qatt'],
		['Y11_Q22_Volunteering', '1--Volunteers-regularly', 'Nivvolontarja regolarment'],
		['Y11_Q22_Volunteering', '2--Volunteers-occasionally', 'Nivvolontarja kultant'],
		['Y11_Q22_Volunteering', '3--Does-not-volunteer', 'Ma nivvolontarjax'],
		['Y11_Q23a', '1--Yes', 'Iva'],
		['Y11_Q23a', '2--No', 'Le'],
		['Y11_Q23b', '1--Yes', 'Iva'],
		['Y11_Q23b', '2--No', 'Le'],
		['Y11_Q23c', '1--Yes', 'Iva'],
		['Y11_Q23c', '2--No', 'Le'],
		['Y11_Q23d', '1--Yes', 'Iva'],
		['Y11_Q23d', '2--No', 'Le'],
		['Y11_Q24', 'Mean', 'Medja'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Tensjoni kbira'],
		['Y11_Q25a', '2--Some-tension', 'Ftit tensjoni'],
		['Y11_Q25a', '3--No-tension', 'M’hemmx tensjoni'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Tensjoni kbira'],
		['Y11_Q25b', '2--Some-tension', 'Ftit tensjoni'],
		['Y11_Q25b', '3--No-tension', 'M’hemmx tensjoni'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Tensjoni kbira'],
		['Y11_Q25c', '2--Some-tension', 'Ftit tensjoni'],
		['Y11_Q25c', '3--No-tension', 'M’hemmx tensjoni'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Tensjoni kbira'],
		['Y11_Q25d', '2--Some-tension', 'Ftit tensjoni'],
		['Y11_Q25d', '3--No-tension', 'M’hemmx tensjoni'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Tensjoni kbira'],
		['Y11_Q25e', '2--Some-tension', 'Ftit tensjoni'],
		['Y11_Q25e', '3--No-tension', 'M’hemmx tensjoni'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Tensjoni kbira'],
		['Y11_Q25f', '2--Some-tension', 'Ftit tensjoni'],
		['Y11_Q25f', '3--No-tension', 'M’hemmx tensjoni'],
		['Y11_Q25g', '1--A-lot-of--tension', 'Tensjoni kbira'],
		['Y11_Q25g', '2--Some-tension', 'Ftit tensjoni'],
		['Y11_Q25g', '3--No-tension', 'M’hemmx tensjoni'],
		['Y11_Q28a', 'Mean', 'Medja'],
		['Y11_Q28b', 'Mean', 'Medja'],
		['Y11_Q28c', 'Mean', 'Medja'],
		['Y11_Q28d', 'Mean', 'Medja'],
		['Y11_Q28e', 'Mean', 'Medja'],
		['Y11_Q28f', 'Mean', 'Medja'],
		['Y11_Q29a', '1--Strongly-agree', 'Naqbel ħafna'],
		['Y11_Q29a', '2--Agree', 'Naqbel'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'La naqbel u lanqas ma naqbilx'],
		['Y11_Q29a', '4--Disagree', 'Ma naqbilx'],
		['Y11_Q29a', '5--Strongly-disagree', 'Ma naqbilx ħafna'],
		['Y11_Q29b', '1--Strongly-agree', 'Naqbel ħafna'],
		['Y11_Q29b', '2--Agree', 'Naqbel'],
		['Y11_Q29b', '3--Neither-agree-nor-disagree', 'La naqbel u lanqas ma naqbilx'],
		['Y11_Q29b', '4--Disagree', 'Ma naqbilx'],
		['Y11_Q29b', '5--Strongly-disagree', 'Ma naqbilx ħafna'],
		['Y11_Q29c', '1--Strongly-agree', 'Naqbel ħafna'],
		['Y11_Q29c', '2--Agree', 'Naqbel'],
		['Y11_Q29c', '3--Neither-agree-nor-disagree', 'La naqbel u lanqas ma naqbilx'],
		['Y11_Q29c', '4--Disagree', 'Ma naqbilx'],
		['Y11_Q29c', '5--Strongly-disagree', 'Ma naqbilx ħafna'],
		['Y11_Q29d', '1--Strongly-agree', 'Naqbel ħafna'],
		['Y11_Q29d', '2--Agree', 'Naqbel'],
		['Y11_Q29d', '3--Neither-agree-nor-disagree', 'La naqbel u lanqas ma naqbilx'],
		['Y11_Q29d', '4--Disagree', 'Ma naqbilx'],
		['Y11_Q29d', '5--Strongly-disagree', 'Ma naqbilx ħafna'],
		['Y11_Q29e', '1--Strongly-agree', 'Naqbel ħafna'],
		['Y11_Q29e', '2--Agree', 'Naqbel'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'La naqbel u lanqas ma naqbilx'],
		['Y11_Q29e', '4--Disagree', 'Ma naqbilx'],
		['Y11_Q29e', '5--Strongly-disagree', 'Ma naqbilx ħafna'],
		['Y11_Q29f', '1--Strongly-agree', 'Naqbel ħafna'],
		['Y11_Q29f', '2--Agree', 'Naqbel'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'La naqbel u lanqas ma naqbilx'],
		['Y11_Q29f', '4--Disagree', 'Ma naqbilx'],
		['Y11_Q29f', '5--Strongly-disagree', 'Ma naqbilx ħafna'],
		['Y11_Q29g', '1--Strongly-agree', 'Naqbel ħafna'],
		['Y11_Q29g', '2--Agree', 'Naqbel'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'La naqbel u lanqas ma naqbilx'],
		['Y11_Q29g', '4--Disagree', 'Ma naqbilx'],
		['Y11_Q29g', '5--Strongly-disagree', 'Ma naqbilx ħafna'],
		['Y11_Q29h', '1--Strongly-agree', 'Naqbel ħafna'],
		['Y11_Q29h', '2--Agree', 'Naqbel'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'La naqbel u lanqas ma naqbilx'],
		['Y11_Q29h', '4--Disagree', 'Ma naqbilx'],
		['Y11_Q29h', '5--Strongly-disagree', 'Ma naqbilx ħafna'],
		['Y11_Q29i', '1--Strongly-agree', 'Naqbel ħafna'],
		['Y11_Q29i', '2--Agree', 'Naqbel'],
		['Y11_Q29i', '3--Neither-agree-nor-disagree', 'La naqbel u lanqas ma naqbilx'],
		['Y11_Q29i', '4--Disagree', 'Ma naqbilx'],
		['Y11_Q29i', '5--Strongly-disagree', 'Ma naqbilx ħafna'],
		['Y11_Q30', 'Mean', 'Medja'],
		['Y11_Q33a', '1--Every-day-or-almost-every-day', 'Kuljum jew kważi kuljum'],
		['Y11_Q33a', '2--At-least-once-a-week', 'Tal-inqas darba fil-ġimgħa'],
		['Y11_Q33a', '3--One-to-three-times-a-month', 'Minn darba sa tliet darbiet fix-xahar'],
		['Y11_Q33a', '4--Less-often', 'Inqas spiss'],
		['Y11_Q33a', '5--Never', 'Qatt'],
		['Y11_Q33b', '1--Every-day-or-almost-every-day', 'Kuljum jew kważi kuljum'],
		['Y11_Q33b', '2--At-least-once-a-week', 'Tal-inqas darba fil-ġimgħa'],
		['Y11_Q33b', '3--One-to-three-times-a-month', 'Minn darba sa tliet darbiet fix-xahar'],
		['Y11_Q33b', '4--Less-often', 'Inqas spiss'],
		['Y11_Q33b', '5--Never', 'Qatt'],
		['Y11_Q33c', '1--Every-day-or-almost-every-day', 'Kuljum jew kważi kuljum'],
		['Y11_Q33c', '2--At-least-once-a-week', 'Tal-inqas darba fil-ġimgħa'],
		['Y11_Q33c', '3--One-to-three-times-a-month', 'Minn darba sa tliet darbiet fix-xahar'],
		['Y11_Q33c', '4--Less-often', 'Inqas spiss'],
		['Y11_Q33c', '5--Never', 'Qatt'],
		['Y11_Q33d', '1--Every-day-or-almost-every-day', 'Kuljum jew kważi kuljum'],
		['Y11_Q33d', '2--At-least-once-a-week', 'Tal-inqas darba fil-ġimgħa'],
		['Y11_Q33d', '3--One-to-three-times-a-month', 'Minn darba sa tliet darbiet fix-xahar'],
		['Y11_Q33d', '4--Less-often', 'Inqas spiss'],
		['Y11_Q33d', '5--Never', 'Qatt'],
		['Y11_Q34a', '1--Every-day-or-almost-every-day', 'Kuljum jew kważi kuljum'],
		['Y11_Q34a', '2--At-least-once-a-week', 'Tal-inqas darba fil-ġimgħa'],
		['Y11_Q34a', '3--One-to-three-times-a-month', 'Minn darba sa tliet darbiet fix-xahar'],
		['Y11_Q34a', '4--Less-often', 'Inqas spiss'],
		['Y11_Q34a', '5--Never', 'Qatt'],
		['Y11_Q34b', '1--Every-day-or-almost-every-day', 'Kuljum jew kważi kuljum'],
		['Y11_Q34b', '2--At-least-once-a-week', 'Tal-inqas darba fil-ġimgħa'],
		['Y11_Q34b', '3--One-to-three-times-a-month', 'Minn darba sa tliet darbiet fix-xahar'],
		['Y11_Q34b', '4--Less-often', 'Inqas spiss'],
		['Y11_Q34b', '5--Never', 'Qatt'],
		['Y11_Q34c', '1--Every-day-or-almost-every-day', 'Kuljum jew kważi kuljum'],
		['Y11_Q34c', '2--At-least-once-a-week', 'Tal-inqas darba fil-ġimgħa'],
		['Y11_Q34c', '3--One-to-three-times-a-month', 'Minn darba sa tliet darbiet fix-xahar'],
		['Y11_Q34c', '4--Less-often', 'Inqas spiss'],
		['Y11_Q34c', '5--Never', 'Qatt'],
		['Y11_Q34d', '1--Every-day-or-almost-every-day', 'Kuljum jew kważi kuljum'],
		['Y11_Q34d', '2--At-least-once-a-week', 'Tal-inqas darba fil-ġimgħa'],
		['Y11_Q34d', '3--One-to-three-times-a-month', 'Minn darba sa tliet darbiet fix-xahar'],
		['Y11_Q34d', '4--Less-often', 'Inqas spiss'],
		['Y11_Q34d', '5--Never', 'Qatt'],
		['Y11_Q35a', '1--A-member-of-your-family', 'Membru tal-familja / qarib'],
		['Y11_Q35a', '2--A-friend--neighbour--or-someone-else', 'Ħabib, ġar jew xi ħadd ieħor'],
		['Y11_Q35a', '3--A-service-provider--institution-or-organisation', 'Xi servizz, istituzzjoni jew organizzazzjoni'],
		['Y11_Q35a', '4--Nobody', 'Ħadd'],
		['Y11_Q35b', '1--A-member-of-your-family', 'Membru tal-familja / qarib'],
		['Y11_Q35b', '2--A-friend--neighbour--or-someone-else', 'Ħabib, ġar jew xi ħadd ieħor'],
		['Y11_Q35b', '3--A-service-provider--institution-or-organisation', 'Xi servizz, istituzzjoni jew organizzazzjoni'],
		['Y11_Q35b', '4--Nobody', 'Ħadd'],
		['Y11_Q35c', '1--A-member-of-your-family', 'Membru tal-familja / qarib'],
		['Y11_Q35c', '2--A-friend--neighbour--or-someone-else', 'Ħabib, ġar jew xi ħadd ieħor'],
		['Y11_Q35c', '3--A-service-provider--institution-or-organisation', 'Xi servizz, istituzzjoni jew organizzazzjoni'],
		['Y11_Q35c', '4--Nobody', 'Ħadd'],
		['Y11_Q35d', '1--A-member-of-your-family', 'Membru tal-familja / qarib'],
		['Y11_Q35d', '2--A-friend--neighbour--or-someone-else', 'Ħabib, ġar jew xi ħadd ieħor'],
		['Y11_Q35d', '3--A-service-provider--institution-or-organisation', 'Xi servizz, istituzzjoni jew organizzazzjoni'],
		['Y11_Q35d', '4--Nobody', 'Ħadd'],
		['Y11_Q35e', '1--A-member-of-your-family', 'Membru tal-familja / qarib'],
		['Y11_Q35e', '2--A-friend--neighbour--or-someone-else', 'Ħabib, ġar jew xi ħadd ieħor'],
		['Y11_Q35e', '3--A-service-provider--institution-or-organisation', 'Xi servizz, istituzzjoni jew organizzazzjoni'],
		['Y11_Q35e', '4--Nobody', 'Ħadd'],
		['Y11_Q36a', '1--Every-day', 'Kuljum'],
		['Y11_Q36a', '2--Several-days-a-week', 'Ħafna drabi matul il-ġimgħa'],
		['Y11_Q36a', '3--Once-or-twice-a-week', 'Darba jew darbtejn fil-ġimgħa'],
		['Y11_Q36a', '4--Less-often', 'Inqas spiss'],
		['Y11_Q36a', '5--Never', 'Qatt'],
		['Y11_Q36b', '1--Every-day', 'Kuljum'],
		['Y11_Q36b', '2--Several-days-a-week', 'Ħafna drabi matul il-ġimgħa'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'Darba jew darbtejn fil-ġimgħa'],
		['Y11_Q36b', '4--Less-often', 'Inqas spiss'],
		['Y11_Q36b', '5--Never', 'Qatt'],
		['Y11_Q36c', '1--Every-day', 'Kuljum'],
		['Y11_Q36c', '2--Several-days-a-week', 'Ħafna drabi matul il-ġimgħa'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'Darba jew darbtejn fil-ġimgħa'],
		['Y11_Q36c', '4--Less-often', 'Inqas spiss'],
		['Y11_Q36c', '5--Never', 'Qatt'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Aktar milli hu s-sehem ġust tiegħek'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Eżatt dak li għandu jkun is-sehem ġust tiegħek'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Inqas minn kemm għandu jkun is-sehem ġust tiegħek'],
		['Y11_Q39a', '1--Spend-more-time', 'Inqatta’ iżjed ħin'],
		['Y11_Q39a', '2--As-much-as-I-currently-do', 'Daqskemm qed inqatta’ ħin bħalissa'],
		['Y11_Q39a', '3--Spend-less-time', 'Inqatta’ inqas ħin'],
		['Y11_Q39b', '1--Spend-more-time', 'Inqatta’ iżjed ħin'],
		['Y11_Q39b', '2--As-much-as-I-currently-do', 'Daqskemm qed inqatta’ ħin bħalissa'],
		['Y11_Q39b', '3--Spend-less-time', 'Inqatta’ inqas ħin'],
		['Y11_Q39c', '1--Spend-more-time', 'Inqatta’ iżjed ħin'],
		['Y11_Q39c', '2--As-much-as-I-currently-do', 'Daqskemm qed inqatta’ ħin bħalissa'],
		['Y11_Q39c', '3--Spend-less-time', 'Inqatta’ inqas ħin'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'Ix-xogħol u d-dar'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Jew ix-xogħol jew id-dar'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Ftit jew xejn stress'],
		['Y11_Q40a', 'Mean', 'Medja'],
		['Y11_Q40b', 'Mean', 'Medja'],
		['Y11_Q40c', 'Mean', 'Medja'],
		['Y11_Q40d', 'Mean', 'Medja'],
		['Y11_Q40e', 'Mean', 'Medja'],
		['Y11_Q40f', 'Mean', 'Medja'],
		['Y11_Q40g', 'Mean', 'Medja'],
		['Y11_Q40h', 'Mean', 'Medja'],
		['Y11_Q41', 'Mean', 'Medja'],
		['Y11_Q42', '1--Very-good', 'Tajjeb ħafna'],
		['Y11_Q42', '2--Good', 'Tajjeb'],
		['Y11_Q42', '3--Fair', 'Mhux ħażin'],
		['Y11_Q42', '4--Bad', 'Ħażin'],
		['Y11_Q42', '5--Very-bad', 'Ħażin ħafna'],
		['Y11_Q46a', '1--All-of-the-time', 'Il-ħin kollu'],
		['Y11_Q46a', '2--Most-of-the-time', 'Ħafna mill-ħin'],
		['Y11_Q46a', '3--More-than-half-of-the-time', 'Aktar minn nofs il-ħin'],
		['Y11_Q46a', '4--Less-than-half-of-the-time', 'Anqas minn nofs il-ħin'],
		['Y11_Q46a', '5--Some-of-the-time', 'Xi ftit mill-ħin'],
		['Y11_Q46a', '6--At-no-time', 'Fl-ebda ħin'],
		['Y11_Q46b', '1--All-of-the-time', 'Il-ħin kollu'],
		['Y11_Q46b', '2--Most-of-the-time', 'Ħafna mill-ħin'],
		['Y11_Q46b', '3--More-than-half-of-the-time', 'Aktar minn nofs il-ħin'],
		['Y11_Q46b', '4--Less-than-half-of-the-time', 'Anqas minn nofs il-ħin'],
		['Y11_Q46b', '5--Some-of-the-time', 'Xi ftit mill-ħin'],
		['Y11_Q46b', '6--At-no-time', 'Fl-ebda ħin'],
		['Y11_Q46c', '1--All-of-the-time', 'Il-ħin kollu'],
		['Y11_Q46c', '2--Most-of-the-time', 'Ħafna mill-ħin'],
		['Y11_Q46c', '3--More-than-half-of-the-time', 'Aktar minn nofs il-ħin'],
		['Y11_Q46c', '4--Less-than-half-of-the-time', 'Anqas minn nofs il-ħin'],
		['Y11_Q46c', '5--Some-of-the-time', 'Xi ftit mill-ħin'],
		['Y11_Q46c', '6--At-no-time', 'Fl-ebda ħin'],
		['Y11_Q46d_WHO5', 'Mean', 'Medja'],
		['Y11_Q47a', '1--Very-difficult', 'Diffiċli ħafna'],
		['Y11_Q47a', '2--A-little-difficult', 'Ftit diffiċli'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Diffikultà ta’ xejn'],
		['Y11_Q47b', '1--Very-difficult', 'Diffiċli ħafna'],
		['Y11_Q47b', '2--A-little-difficult', 'Ftit diffiċli'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Diffikultà ta’ xejn'],
		['Y11_Q47c', '1--Very-difficult', 'Diffiċli ħafna'],
		['Y11_Q47c', '2--A-little-difficult', 'Ftit diffiċli'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Diffikultà ta’ xejn'],
		['Y11_Q47d', '1--Very-difficult', 'Diffiċli ħafna'],
		['Y11_Q47d', '2--A-little-difficult', 'Ftit diffiċli'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Diffikultà ta’ xejn'],
		['Y11_Q47e', '1--Very-difficult', 'Diffiċli ħafna'],
		['Y11_Q47e', '2--A-little-difficult', 'Ftit diffiċli'],
		['Y11_Q47e', '3--Not-difficult-at-all', 'Diffikultà ta’ xejn'],
		['Y11_Q50a', '1--Major-problems', 'Problemi kbar'],
		['Y11_Q50a', '2--Moderate-problems', 'Problemi moderati'],
		['Y11_Q50a', '3--No-problems', 'Problemi ta’ xejn'],
		['Y11_Q50b', '1--Major-problems', 'Problemi kbar'],
		['Y11_Q50b', '2--Moderate-problems', 'Problemi moderati'],
		['Y11_Q50b', '3--No-problems', 'Problemi ta’ xejn'],
		['Y11_Q50c', '1--Major-problems', 'Problemi kbar'],
		['Y11_Q50c', '2--Moderate-problems', 'Problemi moderati'],
		['Y11_Q50c', '3--No-problems', 'Problemi ta’ xejn'],
		['Y11_Q50d', '1--Major-problems', 'Problemi kbar'],
		['Y11_Q50d', '2--Moderate-problems', 'Problemi moderati'],
		['Y11_Q50d', '3--No-problems', 'Problemi ta’ xejn'],
		['Y11_Q50e', '1--Major-problems', 'Problemi kbar'],
		['Y11_Q50e', '2--Moderate-problems', 'Problemi moderati'],
		['Y11_Q50e', '3--No-problems', 'Problemi ta’ xejn'],
		['Y11_Q50f', '1--Major-problems', 'Problemi kbar'],
		['Y11_Q50f', '2--Moderate-problems', 'Problemi moderati'],
		['Y11_Q50f', '3--No-problems', 'Problemi ta’ xejn'],
		['Y11_Q51a', '1--with-great-difficulty', 'B’diffikultà kbira'],
		['Y11_Q51a', '2--with-some-difficulty', 'B’xi diffikultà'],
		['Y11_Q51a', '3--easily', 'Faċli'],
		['Y11_Q51a', '4--very-easily', 'Faċli ħafna'],
		['Y11_Q51b', '1--with-great-difficulty', 'B’diffikultà kbira'],
		['Y11_Q51b', '2--with-some-difficulty', 'B’xi diffikultà'],
		['Y11_Q51b', '3--easily', 'Faċli'],
		['Y11_Q51b', '4--very-easily', 'Faċli ħafna'],
		['Y11_Q51c', '1--with-great-difficulty', 'B’diffikultà kbira'],
		['Y11_Q51c', '2--with-some-difficulty', 'B’xi diffikultà'],
		['Y11_Q51c', '3--easily', 'Faċli'],
		['Y11_Q51c', '4--very-easily', 'Faċli ħafna'],
		['Y11_Q51d', '1--with-great-difficulty', 'B’diffikultà kbira'],
		['Y11_Q51d', '2--with-some-difficulty', 'B’xi diffikultà'],
		['Y11_Q51d', '3--easily', 'Faċli'],
		['Y11_Q51d', '4--very-easily', 'Faċli ħafna'],
		['Y11_Q51e', '1--with-great-difficulty', 'B’diffikultà kbira'],
		['Y11_Q51e', '2--with-some-difficulty', 'B’xi diffikultà'],
		['Y11_Q51e', '3--easily', 'Faċli'],
		['Y11_Q51e', '4--very-easily', 'Faċli ħafna'],
		['Y11_Q52', 'Mean', 'Medja'],
		['Y11_Q53a', 'Mean', 'Medja'],
		['Y11_Q53b', 'Mean', 'Medja'],
		['Y11_Q53c', 'Mean', 'Medja'],
		['Y11_Q53d', 'Mean', 'Medja'],
		['Y11_Q53e', 'Mean', 'Medja'],
		['Y11_Q53f', 'Mean', 'Medja'],
		['Y11_Q53g', 'Mean', 'Medja'],
		['Y11_Q57', '1--Much-worse', 'Ħafna agħar'],
		['Y11_Q57', '2--Somewhat-worse', 'Daqsxejn agħar'],
		['Y11_Q57', '3--Neither-worse-nor-better', 'La agħar u lanqas aħjar'],
		['Y11_Q57', '4--Somewhat-better', 'Daqsxejn aħjar'],
		['Y11_Q57', '5--Much-better', 'Ħafna aħjar'],
		['Y11_Q58', '1--With-great-difficulty', 'B’diffikultà kbira'],
		['Y11_Q58', '2--With-difficulty', 'B’diffikultà'],
		['Y11_Q58', '3--With-some-difficulty', 'B’xi diffikultà'],
		['Y11_Q58', '4--Fairly-easily', 'Xi ftit jew wisq faċli'],
		['Y11_Q58', '5--Easily', 'Faċli'],
		['Y11_Q58', '6--Very-easily', 'Faċli ħafna'],
		['Y11_Q59a', '1--No', 'Le'],
		['Y11_Q59a', '2--Yes', 'Iva'],
		['Y11_Q59b', '1--No', 'Le'],
		['Y11_Q59b', '2--Yes', 'Iva'],
		['Y11_Q59c', '1--No', 'Le'],
		['Y11_Q59c', '2--Yes', 'Iva'],
		['Y11_Q59d', '1--No', 'Le'],
		['Y11_Q59d', '2--Yes', 'Iva'],
		['Y11_Q59e', '1--No', 'Le'],
		['Y11_Q59e', '2--Yes', 'Iva'],
		['Y11_Q59f', '1--No', 'Le'],
		['Y11_Q59f', '2--Yes', 'Iva'],
		['Y11_Q60a', '1--Yes', 'Iva'],
		['Y11_Q60a', '2--No', 'Le'],
		['Y11_Q60b', '1--Yes', 'Iva'],
		['Y11_Q60b', '2--No', 'Le'],
		['Y11_Q60c', '1--Yes', 'Iva'],
		['Y11_Q60c', '2--No', 'Le'],
		['Y11_Q60d', '1--Yes', 'Iva'],
		['Y11_Q60d', '2--No', 'Le'],
		['Y11_Q65', '1--Better', 'Aħjar'],
		['Y11_Q65', '2--The-same', 'L-istess'],
		['Y11_Q65', '3--Worse', 'Agħar'],
		['Y11_Q66', '1--Better', 'Aħjar'],
		['Y11_Q66', '2--The-same', 'L-istess'],
		['Y11_Q66', '3--Worse', 'Agħar'],
		['Y11_Q8_PreferredWorkingHours', '1--Work-less', 'Naħdem inqas'],
		['Y11_Q8_PreferredWorkingHours', '2--Work-the-same', 'Naħdem l-istess'],
		['Y11_Q8_PreferredWorkingHours', '3--Work-more', 'Naħdem iktar'],
		['Y11_SocExIndex', 'Mean', 'Medja']
	];
var country_
	 = [
	
		['AT', 'L-Awstrija'],
		['BE', 'Il-Belġju'],
		['BG', 'Il-Bulgarija'],
		['CY', 'Ċipru'],
		['CZ', 'Ir-Repubblika Ċeka'],
		['DE', 'Il-Ġermanja'],
		['DK', 'Id-Danimarka'],
		['EE', 'L-Estonja'],
		['EL', 'Il-Greċja'],
		['ES', 'Spanja'],
		['FI', 'Il-Finlandja'],
		['FR', 'Franza'],
		['HR', 'Il-Kroazja'],
		['HU', 'L-Ungerija'],
		['IE', 'L-Irlanda'],
		['IS', 'l-Islanda'],
		['IT', 'L-Italja'],
		['LT', 'Il-Litwanja'],
		['LU', 'Il-Lussemburgu'],
		['LV', 'Il-Latvja'],
		['ME', 'Il-Montenegro'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Il-Pajjiżi l-Baxxi'],
		['PL', 'Il-Polonja'],
		['PT', 'Il-Portugall'],
		['RO', 'Ir-Rumanija'],
		['RS', 'Is-Serbja'],
		['SE', 'L-Isvezja'],
		['SI', 'Is-Slovenja'],
		['SK', 'Is-Slovakkja'],
		['TR', 'It-Turkija'],
		['UK', 'Ir-Renju Unit'],
		['XK', 'Il-Kosovo'],
		['EuropeanUnion', 'L-Unjoni Ewropea']
	];
var question_meta
	 = [
	
		['Y11_Q29a', 'Jien ottimist/a dwar il-futur', ''],
		['Y11_Q29b', 'B’mod ġenerali nħoss li dak li nagħmel fil-ħajja għandu valur', ''],
		['Y11_Q29c', 'Inħossni ħieles/ħielsa li niddeċiedi kif ngħix ħajti', ''],
		['Y11_Q29d', 'Fil-ħajja tiegħi ta’ kuljum rari nsib ħin nagħmel dak li tassew jagħtini gost', ''],
		['Y11_Q30', 'Kemm inti sodisfatt/a b’ħajtek bħalissa?', ''],
		['Y11_Q40a', 'Sodisfazzjon bl-edukazzjoni', ''],
		['Y11_Q40b', 'Sodisfazzjon bl-impjieg preżenti', ''],
		['Y11_Q40c', 'Sodisfazzjon bil-livell preżenti tal-għajxien', ''],
		['Y11_Q40d', 'Sodisfazzjon bl-akkomodazzjoni', ''],
		['Y11_Q40e', 'Sodisfazzjon bil-ħajja tal-familja', ''],
		['Y11_Q40f', 'Sodisfazzjon bis-saħħa', ''],
		['Y11_Q40g', 'Sodisfazzjon bil-ħajja soċjali', ''],
		['Y11_Q40h', 'Sodisfazzjon bis-sitwazzjoni ekonomika fil-pajjiż', ''],
		['Y11_Q41', 'Meta tqis kollox, kemm tgħid li inti kuntent/a?', ''],
		['Y11_Q33a', 'Kuntatt wiċċ imb wiċċ ma’ wlied li ma jgħixux fid-dar', ''],
		['Y11_Q33b', 'Kuntatt wiċċ imb wiċċ ma’ omm jew missier li ma jgħixux fid-dar', ''],
		['Y11_Q33c', 'Kuntatt wiċċ imb wiċċ ma’ xi ħadd minn ħutek jew qrabatek li ma jgħixx fid-dar', ''],
		['Y11_Q33d', 'Kuntatt ma’ ħbieb jew ġirien li ma jgħixux fid-dar', ''],
		['Y11_Q34a', 'Kuntatt bit-telefown, bl-internet jew bil-posta ma’ wlied li ma jgħixux fid-dar', ''],
		['Y11_Q34b', 'Kuntatt bit-telefown, bl-internet jew bil-posta ma’ omm jew missier li ma jgħixux fid-dar', ''],
		['Y11_Q34c', 'Kuntatt bit-telefown, bl-internet jew bil-posta ma’ xi ħadd minn ħutek jew qrabatek li ma jgħixx fid-dar', ''],
		['Y11_Q34d', 'Kuntatt bit-telefown, bl-internet jew bil-posta ma’ ħbieb jew ġirien li ma jgħixux fid-dar', ''],
		['Y11_Q35a', 'Meta tkun ma tiflaħx, mingħand min issib għajnuna fix-xogħol tad-dar?', ''],
		['Y11_Q35b', 'Jekk tkun teħtieġ parir dwar xi affari personali jew familjari serja, mingħand min issib għajnuna?', ''],
		['Y11_Q35c', 'Jekk tkun qed tfittex xogħol, mingħand min issib għajnuna?', ''],
		['Y11_Q35d', 'Jekk tħossok xi ftit depress/a u tkun tixtieq xi ħadd ma’ min tiftaħ qalbek, mingħand min issib għajnuna?', ''],
		['Y11_Q35e', 'F’każ li tkun trid 1000 ewro malajr f’idejk biex tiffaċċja xi emerġenza, mingħand min issib għajnuna?', ''],
		['Y11_Q24', 'Taħseb li ħafna nies huma ta’ min jafdahom jew li qatt ma tista’ tkun kawt/a biżżejjed meta jkollok x’taqsam man-nies?', ''],
		['Y11_Q25a', 'Kemm tara li hawn tensjoni bejn il-foqra u s-sinjuri', ''],
		['Y11_Q25b', 'Kemm tara li hawn tensjoni bejn il-maniġment u l-ħaddiema', ''],
		['Y11_Q25c', 'Kemm tara li hawn tensjoni bejn l-irġiel u n-nisa', ''],
		['Y11_Q25d', 'Kemm tara li hawn tensjoni bejn l-anzjani u ż-żgħażagħ', ''],
		['Y11_Q25e', 'Kemm tara li hawn tensjoni bejn razez differenti u gruppi etniċi', ''],
		['Y11_Q25f', 'Kemm tara li hawn tensjoni bejn gruppi reliġjużi differenti', ''],
		['Y11_Q25g', 'Kemm tara li hawn tensjoni bejn nies b’orjentazzjoni sesswali differenti', ''],
		['Y11_Q28a', 'Il-fiduċja fil-parlament', ''],
		['Y11_Q28b', 'Il-fiduċja fis-sistema legali', ''],
		['Y11_Q28c', 'Il-fiduċja fl-istampa', ''],
		['Y11_Q28d', 'Il-fiduċja fil-pulizija', ''],
		['Y11_Q28e', 'Il-fiduċja fil-gvern', ''],
		['Y11_Q28f', 'Il-fiduċja fl-awtoritajiet lokali jew muniċipali', ''],
		['Y11_Deprindex', 'Indiċi ta privazzjoni: Numru ta oġġetti li l-familja ma tistax tħallas', ''],
		['Y11_Q57', 'Is-sitwazzjoni finanzjarja tal-familja tiegħek imqabbla ma’ dik tal-biċċa l-kbira tan-nies f’pajjiżek', ''],
		['Y11_Q58', 'Il-familja tiegħek jirnexxilha tlaħħaq mal-ispejjeż?', ''],
		['Y11_Q59a', 'Tiflaħ iżżomm darek sħuna biżżejjed?', ''],
		['Y11_Q59b', 'Tiflaħ tħallas biex tmur ġimgħa btala ’l bogħod mid-dar kull sena?', ''],
		['Y11_Q59c', 'Tiflaħ tbiddel xi għamara li spiċċat?', ''],
		['Y11_Q59d', 'Il-familja tiegħek tiflaħ tiekol il-laħam, it-tiġieġ jew il-ħut kull jumejn (jekk tkun trid)?', ''],
		['Y11_Q59e', 'Il-membri tal-familja tiegħek jifilħu jixtru ħwejjeġ ġodda aktar milli użati?', ''],
		['Y11_Q59f', 'Il-familja tiegħek tiflaħ tistieden xi ħbieb jew qraba għal drink jew ikla għallinqas darba fix-xahar?', ''],
		['Y11_Q60a', 'Fl-aħħar 12-il xahar, il-familja tiegħek qatt waqgħet lura fil-ħlas tal-kera jew ta’ pagamenti ta’ self għall-akkomodazzjoni?', ''],
		['Y11_Q60b', 'Fl-aħħar 12-il xahar, il-familja tiegħek qatt waqgħet lura fil-ħlas ta’ kontijiet utilitarji?', ''],
		['Y11_Q60c', 'Fl-aħħar 12-il xahar, il-familja tiegħek qatt waqgħet lura fil-ħlas ta’ kontijiet relatati ma’ self għall-konsum?', ''],
		['Y11_Q60d', 'Fl-aħħar 12-il xahar, bħala familja qatt waqajtu lura  fil-ħlas ta’ self informali?', ''],
		['Y11_Q65', 'Il-qagħda finanzjarja tal-familja mqabbla ma’ 12-il xahar ilu', ''],
		['Y11_Q66', 'Kif mistennija tkun il-qagħda finanzjarja fit-12-il xahar li ġejjin', ''],
		['Y11_Q42', 'Kif tara l-istat ta’ saħħtek', ''],
		['Y11_Q46a', 'Ħassejtni partikolarment nervuż', ''],
		['Y11_Q46b', 'Ħassejtni waħdi', ''],
		['Y11_Q46c', 'Ħassejtni mdejjaq/mdejqa u bla ħeġġa', ''],
		['Y11_Q46d_WHO5', 'L-iskala WHO-5 dwar il-benesseri mentali', ''],
		['Y11_Q47a', 'Diffikultà li tara tabib minħabba d-distanza sal-uffiċċju tiegħu jew sal-isptar', ''],
		['Y11_Q47b', 'Diffikultà li tara tabib għax iddum biex tingħata appuntament', ''],
		['Y11_Q47c', 'Diffikultà li tara tabib minħabba li l-ħin li tagħmel tistenna biex tara t-tabib dakinhar tal-appuntament', ''],
		['Y11_Q47d', 'Diffikultà li tara tabib minħabba l-ispiża biex tarah', ''],
		['Y11_Q47e', 'Diffikultà li tara tabib għax ma ssibx il-ħin minħabba x-xogħol jew minħabba li trid tieħu ħsieb ħaddieħor', ''],
		['Y11_Q53a', 'Kif tikklassifika l-kwalità tas-servizzi tas-saħħa f’pajjiżek?', ''],
		['Y11_Q53b', 'Kif tikklassifika l-kwalità tas-sistema edukattiva f’pajjiżek?', ''],
		['Y11_Q53c', 'Kif tikklassifika l-kwalità tat-trasport pubbliku f’pajjiżek?', ''],
		['Y11_Q53d', 'Kif tikklassifika l-kwalità tas-servizzi tal-ħarsien tat-tfal f’pajjiżek?', ''],
		['Y11_Q53e', 'Kif tikklassifika l-kwalità tas-servizzi tal-ħarsien fit-tul f’pajjiżek?', ''],
		['Y11_Q53f', 'Kif tikklassifika l-kwalità tas-servizzi tal-akkomodazzjoni soċjali f’pajjiżek?', ''],
		['Y11_Q53g', 'Kif tikklassifika l-kwalità tas-sistema tal-pensjonijiet tal-Istat f’pajjiżek?', ''],
		['Y11_Accommproblems', 'Numru ta problemi bl-akkomodazzjoni', ''],
		['Y11_Q18', 'Il-pussess tad-dar', ''],
		['Y11_Q19a', 'Problemi ta’ akkomodazzjoni: Nuqqas ta’ spazju', ''],
		['Y11_Q19b', 'Problemi ta’ akkomodazzjoni: Twieqi, bibien jew art mherrija', ''],
		['Y11_Q19c', 'Problemi ta’ akkomodazzjoni: Ħitan jew soqfa umdi jew joqtru', ''],
		['Y11_Q19d', 'Problemi ta’ akkomodazzjoni: M’hemmx tojlit fuq ġewwa li jifflaxxja', ''],
		['Y11_Q19e', 'Problemi ta’ akkomodazzjoni: M’hemmx banju jew doċċa', ''],
		['Y11_Q19f', 'Problemi ta’ akkomodazzjoni: M’hemmx post fejn toħroġ għall-arja', ''],
		['Y11_Q20', 'Kemm hu probabbli li jkollok titlaq mill-post fejn toqgħod fis-6 xhur li ġejjin għax m’għadekx tiflaħ tħallas għalih aktar?', ''],
		['Y11_Q50a', 'Problemi ta’ storbju fl-inħawi', ''],
		['Y11_Q50b', 'Problemi bil-kwalità tal-arja fl-inħawi', ''],
		['Y11_Q50c', 'Problemi bil-kwalità tal-ilma tax-xorb fl-inħawi', ''],
		['Y11_Q50d', 'Problemi ta’ kriminalità, vjolenza jew vandaliżmu fl-inħawi', ''],
		['Y11_Q50e', 'Problemi ta’ skart jew żibel fit-triq fl-inħawi', ''],
		['Y11_Q50f', 'Problemi ta’ konġestjoni tat-traffiku fl-inħawi', ''],
		['Y11_Q51a', 'Aċċess għas-servizzi postali', ''],
		['Y11_Q51b', 'Aċċess għas-servizzi bankarji', ''],
		['Y11_Q51c', 'Aċċess għall-faċilitajiet tat-trasport pubbliku', ''],
		['Y11_Q51d', 'Aċċess għaċ-ċinema, għat-teatru jew għal xi ċentru kulturali', ''],
		['Y11_Q51e', 'Aċċess għal postijiet ta’ rikreazzjoni u ġonna', ''],
		['Y11_Q52', 'Ħin li tagħmel tivvjaġġa biex tmur għax-xogħol jew fejn tistudja', ''],
		['Y11_Q21a', 'Attendenza f’servizzi reliġjużi minbarra tiġijiet, funerali u magħmudijiet', ''],
		['Y11_Q21b', 'Użu tal-internet mhux għax-xogħol', ''],
		['Y11_Q21c', 'Prattika ta’ xi sport jew eżerċizzju fiżiku', ''],
		['Y11_Q21d', 'Parteċipazzjoni f’attivitajiet soċjali ta’ każin, soċjetà jew assoċjazzjoni', ''],
		['Y11_Q22_Volunteering', 'Kemm għamilt ta’ spiss xogħol volontarju bla ħlas fl-aħħar 12-il xahar?', ''],
		['Y11_Q23a', 'Attendejt laqgħa ta’ xi trejdjunjin, partit politiku jew grupp ta’ azzjoni fl-aħħar 12-il xahar', ''],
		['Y11_Q23b', 'Attendejt protesta jew dimostrazzjoni fl-aħħar 12-il xahar', ''],
		['Y11_Q23c', 'Iffirmajt petizzjoni (inkluż b’email jew online) fl-aħħar 12-il xahar', ''],
		['Y11_Q23d', 'Ikkuntattjajt politiku jew uffiċjal pubbliku (minbarra kuntatti ta’ rutina bl-użu ta’ servizzi pubbliċi)', ''],
		['Y11_Q29e', 'Inħossni eskluż mis-soċjetà', ''],
		['Y11_Q29f', 'Il-ħajja tant saret ikkumplikata li kważi nħossni mitluf/a', ''],
		['Y11_Q29g', 'Inħoss li l-valur ta’ dak li nagħmel mhuwiex rikonoxxut minn ħaddieħor', ''],
		['Y11_Q29h', 'Xi nies iqisuni anqas minnhom minħabba s-sitwazzjoni tax-xogħol tiegħi jew minħabba kemm indaħħal', ''],
		['Y11_Q29i', 'Inħossni qrib tan-nies tal-inħawi fejn ngħix', ''],
		['Y11_SocExIndex', 'Indiċi tal-Esklużjoni Soċjali', ''],
		['Y11_Q8_PreferredWorkingHours', 'Kemm tippreferi li taħdem sigħat fil-ġimgħa?', ''],
		['Y11_Q10_Partnerprefhours', 'Kemm tippreferi li j/taħdem sigħat fil-ġimgħa is-sieħeb/sieħba tiegħek?', 'Din il-mistoqsija saret lil dawk ir-rispondenti  li kellhom sieħeb/sieħba j/tgħix fl-istess dar.'],
		['Y11_Q12a', 'Ġejt mix-xogħol għajjien/a wisq biex nagħmel il-faċendi tad-dar', ''],
		['Y11_Q12b', 'Sibtha diffiċli nlaħħaq mar-responsabbiltajiet tal-familja minħabba l-ħin li nqatta’ fuq ix-xogħol', ''],
		['Y11_Q12c', 'Sibtha diffiċli nikkonċentra fuq ix-xogħol minħabba r-responsabbiltajiet tal-familja', ''],
		['Y11_Q13a', 'Nista’ nvarja xħin nibda x-xogħol u xħin nispiċċa', ''],
		['Y11_Q13b', 'Nista’ niġma’ s-sigħat biex ikolli l-frank', ''],
		['Y11_Q13c', 'Meta jkolli bżonn, nista’ nieħu ġurnata frank billi navża fi żmien qasir', ''],
		['Y11_Q15', 'Kemm hu probabbli li titlef l-impjieg fis-6 xhur li ġejjin?', ''],
		['Y11_Q16', 'Jekk titlef l-impjieg, kemm hu probabbli li ssib impjieg ieħor b’salarju simili?', 'Din il-mistoqsija saret lil dawk ir-rispondenti li kienu qed jaħdmu bi ħlas.'],
		['Y11_Q36a', 'Kemm spiss trid tieħu ħsieb uliedek jew ulied uliedek?', ''],
		['Y11_Q36b', 'Kemm spiss tqatta’ ħin fit-tisjir jew fil-faċendi?', ''],
		['Y11_Q36c', 'Kemm spiss tqatta’ ħin tieħu ħsieb qraba anzjani jew b’diżabilità?', ''],
		['Y11_Q38', 'X’taħseb dwar is-sehem li tagħti int fix-xogħol tad-dar?', ''],
		['Y11_Q39a', 'L-attitudni lejn il-ħin li tqatta’ f’kuntatt mal-membri tal-familja', ''],
		['Y11_Q39b', 'L-attitudni lejn il-ħin li tqatta’ f’kuntatt soċjali ieħor', ''],
		['Y11_Q39c', 'L-attitudni lejn il-ħin li tqatta f’passatempi u interessi oħra', ''],
		['Y11_Q39d_stress', 'Stress minħabba kwistjonijiet ta’ bilanċ bejn ix-xogħol u l-ħajja', '']
	];
