//Auto Generated file
var subset_
	 = [
	
		['Y11_HH2a', 'Geslacht'],
		['Y11_Incomequartiles_percapita', 'Inkomen'],
		['Y11_Agecategory', 'Leeftijd']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Alle leeftijden'],
		['Y11_Agecategory', '1--18-24y', '18 tot en met 24 jaar'],
		['Y11_Agecategory', '2--25-34y', '25 tot en met 34 jaar'],
		['Y11_Agecategory', '3--35-49y', '35 tot en met 49 jaar'],
		['Y11_Agecategory', '4--50-64y', '50 tot en met 64 jaar'],
		['Y11_Agecategory', '5---64y', '> 64 jaar'],
		['Y11_HH2a', 'All', 'Beide geslachten'],
		['Y11_HH2a', '1--Female', 'Vrouw'],
		['Y11_HH2a', '2--Male', 'Man'],
		['Y11_Incomequartiles_percapita', 'All', 'Alle inkomensniveaus'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Laagste'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'Tweede'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'Derde'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Hoogste']
	];
var topic_
	 = [
	
		['', 'Alle (127)'],
		['Gezins- en sociaal leven', 'Gezins- en sociaal leven (13)'],
		['Gezondheid en openbare voorzieningen', 'Gezondheid en openbare voorzieningen (16)'],
		['Gezondheidszorg en openbare voorzieningen', 'Gezondheidszorg en openbare voorzieningen (1)'],
		['Kwaliteit van de samenleving', 'Kwaliteit van de samenleving (14)'],
		['Levensstandaard en deprivatie', 'Levensstandaard en deprivatie (15)'],
		['Persoonlijk welzijn', 'Persoonlijk welzijn (14)'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Sociale uitsluiting en maatschappelijke betrokkenheid (15)'],
		['Werkgelegenheid en balans werk-privé', 'Werkgelegenheid en balans werk-privé (18)'],
		['Woning en woonomgeving', 'Woning en woonomgeving (21)']
	];
var topic_question
	 = [
	
		['Gezins- en sociaal leven', 'Y11_Q33a', 'Direct contact (face to face) met uw kinderen die buiten het huishouden wonen'],
		['Gezins- en sociaal leven', 'Y11_Q33b', 'Direct contact (face to face) met uw vader en/of moeder die buiten het huishouden wonen'],
		['Gezins- en sociaal leven', 'Y11_Q33c', 'Direct contact (face to face) met andere familieleden die buiten het huishouden wonen'],
		['Gezins- en sociaal leven', 'Y11_Q33d', 'Direct contact (face to face) met uw vrienden of buren'],
		['Gezins- en sociaal leven', 'Y11_Q34a', 'Contact via telefoon, internet of post met uw kinderen die buiten het huishouden wonen'],
		['Gezins- en sociaal leven', 'Y11_Q34b', 'Contact via telefoon, internet of post met uw vader en/of moeder die buiten het huishouden wonen'],
		['Gezins- en sociaal leven', 'Y11_Q34c', 'Contact via telefoon, internet of post met andere familieleden die buiten het huishouden wonen'],
		['Gezins- en sociaal leven', 'Y11_Q34d', 'Contact via telefoon, internet of post met uw vrienden of buren'],
		['Gezins- en sociaal leven', 'Y11_Q35a', 'Van wie krijgt u steun u als u thuis hulp nodig heeft als u ziek bent?'],
		['Gezins- en sociaal leven', 'Y11_Q35b', 'Van wie krijgt u steun u als u advies nodig heeft over belangrijke persoonlijke of familiezaken?'],
		['Gezins- en sociaal leven', 'Y11_Q35c', 'Van wie krijgt u steun u als u hulp nodig heeft bij het vinden van een baan?'],
		['Gezins- en sociaal leven', 'Y11_Q35d', 'Wie steunt u als u zich ongelukkig of depressief voelt?'],
		['Gezins- en sociaal leven', 'Y11_Q35e', 'Wie steunt u als u dringend 1000 euro nodig heeft? '],
		['Gezondheid en openbare voorzieningen', 'Y11_Q46a', 'Ik ben bijzonder gespannen geweest'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q46b', 'Ik heb me eenzaam gevoeld'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q46c', 'Ik heb me neerslachtig en depressief gevoeld'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q46d_WHO5', 'WHO-5 geestelijk welzijnsindex'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q47a', 'Een bezoek aan de dokter wordt bemoeilijkt door de afstand'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q47b', 'Een bezoek de een dokter wordt bemoeilijkt door de wachttijd voor het krijgen van een afspraak'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q47c', 'Een bezoek aan de dokter wordt bemoeilijkt door de wachttijd op de dag van de afspraak'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q47d', 'Een bezoek aan de dokter wordt bemoeilijkt door de kosten'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q47e', 'Een bezoek aan de dokter wordt bemoeilijkt door tijdgebrek'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q53a', 'Hoe waardeert u de kwaliteit van de gezondheidszorg in uw land?'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q53b', 'Hoe waardeert u de kwaliteit van het onderwijs in uw land?'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q53c', 'Hoe waardeert u de kwaliteit van het openbaar vervoer in uw land?'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q53d', 'Hoe waardeert u de kwaliteit van de kinderopvang in uw land?'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q53e', 'Hoe waardeert u de kwaliteit van de voorzieningen voor langdurige zorg in uw land?'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q53f', 'Hoe waardeert u de kwaliteit van de sociale woningbouw in uw land?'],
		['Gezondheid en openbare voorzieningen', 'Y11_Q53g', 'Hoe waardeert u de kwaliteit van de algemene ouderdomswet (AOW) in uw land?'],
		['Gezondheidszorg en openbare voorzieningen', 'Y11_Q42', 'Waarneming van de eigen gezondheidstoestand'],
		['Kwaliteit van de samenleving', 'Y11_Q24', 'Denkt u dat mensen te vertrouwen zijn of dat je niet voorzichtig genoeg kunt zijn in de omgang met mensen?'],
		['Kwaliteit van de samenleving', 'Y11_Q25a', 'Is er volgens u sprake van wrijving tussen arme en rijke mensen?'],
		['Kwaliteit van de samenleving', 'Y11_Q25b', 'Is er volgens u sprake van wrijving tussen management en werknemers?'],
		['Kwaliteit van de samenleving', 'Y11_Q25c', 'Is er volgens u sprake van wrijving tussen mannen en vrouwen?'],
		['Kwaliteit van de samenleving', 'Y11_Q25d', 'Is er volgens u sprake van wrijving tussen ouderen en jongeren?'],
		['Kwaliteit van de samenleving', 'Y11_Q25e', 'Is er volgens u sprake van wrijving tussen verschillende etnische groeperingen?'],
		['Kwaliteit van de samenleving', 'Y11_Q25f', 'Is er volgens u sprake van wrijving tussen verschillende religieuze groeperingen?'],
		['Kwaliteit van de samenleving', 'Y11_Q25g', 'Is er volgens u sprake van wrijving tussen personen met een verschillende seksuele geaardheid?'],
		['Kwaliteit van de samenleving', 'Y11_Q28a', 'Vertrouwen in de Tweede Kamer'],
		['Kwaliteit van de samenleving', 'Y11_Q28b', 'Vertrouwen in het rechtssysteem'],
		['Kwaliteit van de samenleving', 'Y11_Q28c', 'Vertrouwen in de pers'],
		['Kwaliteit van de samenleving', 'Y11_Q28d', 'Vertrouwen in de politie'],
		['Kwaliteit van de samenleving', 'Y11_Q28e', 'Vertrouwen in de regering'],
		['Kwaliteit van de samenleving', 'Y11_Q28f', 'Vertrouwen in de lokale (gemeentelijke) overheid'],
		['Levensstandaard en deprivatie', 'Y11_Deprindex', 'Deprivatie-index: aantal items dat een huishouden zich niet kan permitteren'],
		['Levensstandaard en deprivatie', 'Y11_Q57', 'Financiële situatie van het huishouden vergeleken met de meeste mensen in Nederland'],
		['Levensstandaard en deprivatie', 'Y11_Q58', 'Is uw huishouden in staat rond te komen?'],
		['Levensstandaard en deprivatie', 'Y11_Q59a', 'Kunt u het zich permitteren uw woning goed te verwarmen?'],
		['Levensstandaard en deprivatie', 'Y11_Q59b', 'Kunt u het zich permitteren om elk jaar een week met vakantie te gaan?'],
		['Levensstandaard en deprivatie', 'Y11_Q59c', 'Kunt u het zich permitteren versleten meubilair te vervangen?'],
		['Levensstandaard en deprivatie', 'Y11_Q59d', 'Kunt u zich (als u dat zou willen) om de dag een warme maaltijd met vlees, kip of vis permitteren?'],
		['Levensstandaard en deprivatie', 'Y11_Q59e', 'Kunt u het zich permitteren om nieuwe kleding te kopen in plaats van tweedehands?'],
		['Levensstandaard en deprivatie', 'Y11_Q59f', 'Kunt u het zich permitteren om ten minste één keer maand vrienden of familie thuis uit te nodigen voor een drankje of een maaltijd?'],
		['Levensstandaard en deprivatie', 'Y11_Q60a', 'Heeft uw huishouden in de afgelopen 12 maanden een achterstand opgelopen bij het betalen van huur of hypotheeklasten?'],
		['Levensstandaard en deprivatie', 'Y11_Q60b', 'Heeft uw huishouden in de afgelopen 12 maanden een achterstand opgelopen bij het betalen van de rekeningen voor elektriciteit, water of gas?'],
		['Levensstandaard en deprivatie', 'Y11_Q60c', 'Heeft uw huishouden in de afgelopen 12 maanden een achterstand opgelopen met betrekking tot consumentenleningen?'],
		['Levensstandaard en deprivatie', 'Y11_Q60d', 'Heeft uw huishouden in de afgelopen 12 maanden een achterstand opgelopen met betrekking tot niet-officiële leningen?'],
		['Levensstandaard en deprivatie', 'Y11_Q65', 'Hoe is de financiële situatie van uw huishouden vergeleken met 12 maanden geleden?'],
		['Levensstandaard en deprivatie', 'Y11_Q66', 'Hoe ziet naar verwachting uw financiële situatie er de komende 12 maanden uit?'],
		['Persoonlijk welzijn', 'Y11_Q29a', 'Ik ben positief over de toekomst'],
		['Persoonlijk welzijn', 'Y11_Q29b', 'Over het algemeen vind ik dat wat ik doe in het leven de moeite waard is'],
		['Persoonlijk welzijn', 'Y11_Q29c', 'Naar mijn mening ben ik vrij om te beslissen hoe ik mijn leven leid'],
		['Persoonlijk welzijn', 'Y11_Q29d', 'In mijn dagelijkse leven heb ik maar zelden de tijd om de dingen te doen waar ik echt van geniet'],
		['Persoonlijk welzijn', 'Y11_Q30', 'Hoe tevreden bent u op dit moment met uw leven?'],
		['Persoonlijk welzijn', 'Y11_Q40a', 'Tevredenheid over uw opleiding'],
		['Persoonlijk welzijn', 'Y11_Q40b', 'Tevredenheid over uw huidige baan'],
		['Persoonlijk welzijn', 'Y11_Q40c', 'Tevredenheid over uw huidige levensstandaard'],
		['Persoonlijk welzijn', 'Y11_Q40d', 'Tevredenheid over uw woonsituatie'],
		['Persoonlijk welzijn', 'Y11_Q40e', 'Tevredenheid over uw gezinsleven'],
		['Persoonlijk welzijn', 'Y11_Q40f', 'Tevredenheid over uw gezondheid'],
		['Persoonlijk welzijn', 'Y11_Q40g', 'Tevredenheid over uw sociale leven'],
		['Persoonlijk welzijn', 'Y11_Q40h', 'Tevredenheid over de economische situatie in Nederland'],
		['Persoonlijk welzijn', 'Y11_Q41', 'Alles bij elkaar genomen, hoe gelukkig zou u zeggen dat u bent?'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_Q21a', 'Kerkdiensten bijwonen, uitgezonderd bruiloften, begrafenissen en doopplechtigheden'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_Q21b', 'Internet gebruiken voor andere doeleinden dan werk'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_Q21c', 'Een sport beoefenen of op een andere manier lichamelijk inspannend bezig zijn'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_Q21d', 'Deelnemen aan sociale activiteiten van een club, vereniging of stichting'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_Q22_Volunteering', 'Hoe vaak heeft u in de afgelopen 12 maanden onbetaald vrijwilligerswerk gedaan?'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_Q23a', 'Heeft u in de afgelopen 12 maanden een vergadering bijgewoond van een vakbond, politieke partij of politieke actiegroep?'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_Q23b', 'Heeft u in de afgelopen 12 maanden meegedaan aan een protestactie of demonstratie?'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_Q23c', 'Heeft u in de afgelopen 12 maanden een petitie ondertekend?'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_Q23d', 'Heeft u contact opgenomen met een politicus of overheidsvertegenwoordiger (anders dan een routinecontact met publieke instanties)?'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_Q29e', 'Ik voel me buitengesloten van de maatschappij'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_Q29f', 'Het leven is tegenwoordig zo gecompliceerd dat ik moeite heb om mijn weg te vinden'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_Q29g', 'Ik heb het gevoel dat anderen de waarde van wat ik doe niet erkennen'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_Q29h', 'Sommige mensen kijken op mij neer vanwege mijn werksituatie of inkomen'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_Q29i', 'Ik voel me betrokken bij de mensen in mijn woonomgeving'],
		['Sociale uitsluiting en maatschappelijke betrokkenheid', 'Y11_SocExIndex', 'Index sociale uitsluiting'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q8_PreferredWorkingHours', 'Hoeveel uur per week zou u willen werken?'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q10_Partnerprefhours', 'Hoeveel uur per week zou u willen dat uw partner werkt?'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q12a', 'Ik ben te moe thuisgekomen van het werk om huishoudelijke taken te doen'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q12b', 'Ik vond het moeilijk om aan mijn verantwoordelijkheden thuis te voldoen door de tijd die ik aan mijn werk besteed '],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q12c', 'Ik heb moeite gehad me op mijn werk te concentreren vanwege gezinsverantwoordelijkheden'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q13a', 'Ik kan de tijdstippen waarop ik begin en ophoud met werken aanpassen'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q13b', 'Ik kan (over)uren sparen voor verlof/vrije tijd'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q13c', 'Ik kan op korte termijn een vrije dag/verlofdag opnemen wanneer nodig '],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q15', 'Hoe waarschijnlijk is het dat u in de komende zes maanden wordt ontslagen?'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q16', 'Als u uw huidige baan verliest, hoe waarschijnlijk is het dan dat u een nieuwe baan vindt met een vergelijkbaar salaris?'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q36a', 'Hoe vaak bent u bezig met de zorg voor uw kinderen of kleinkinderen?'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q36b', 'Hoe vaak kookt u en/of bent u bezig met huishoudelijk werk?'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q36c', 'Hoe vaak bent u zich bezig met de zorg voor invalide of oudere familieleden?'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q38', 'Houding ten opzichte van het eigen aandeel in het huishoudelijk werk'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q39a', 'Houding ten opzichte van de tijd besteed aan familieleden'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q39b', 'Houding ten opzichte van de tijd besteed aan anderen'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q39c', 'Houding ten opzichte van de tijd besteed aan persoonlijke hobbys of interesses'],
		['Werkgelegenheid en balans werk-privé', 'Y11_Q39d_stress', 'Stress'],
		['Woning en woonomgeving', 'Y11_Accommproblems', 'Aantal problemen met de woonsituatie'],
		['Woning en woonomgeving', 'Y11_Q18', 'Huiseigenaar'],
		['Woning en woonomgeving', 'Y11_Q19a', 'Problemen met de woonsituatie: gebrek aan ruimte'],
		['Woning en woonomgeving', 'Y11_Q19b', 'Problemen met de woonsituatie: houtrot in raamkozijnen, deuren of vloeren'],
		['Woning en woonomgeving', 'Y11_Q19c', 'Problemen met de woonsituatie: vochtproblemen of lekkages van muren of dak'],
		['Woning en woonomgeving', 'Y11_Q19d', 'Problemen met de woonsituatie: ontbreken van een toilet in huis'],
		['Woning en woonomgeving', 'Y11_Q19e', 'Problemen met de woonsituatie: ontbreken van een bad of douche'],
		['Woning en woonomgeving', 'Y11_Q19f', 'Problemen met de woonsituatie: ontbreken van een plaats om buiten te zitten'],
		['Woning en woonomgeving', 'Y11_Q20', 'Hoe waarschijnlijk is het dat u in de komende zes maanden uw woning moet verlaten omdat u deze niet meer kunt betalen?'],
		['Woning en woonomgeving', 'Y11_Q50a', 'Problemen in de buurt met geluidsoverlast'],
		['Woning en woonomgeving', 'Y11_Q50b', 'Problemen in de buurt met de luchtkwaliteit'],
		['Woning en woonomgeving', 'Y11_Q50c', 'Problemen in de buurt met de kwaliteit van het drinkwater'],
		['Woning en woonomgeving', 'Y11_Q50d', 'Problemen in de buurt met criminaliteit, geweld of vandalisme'],
		['Woning en woonomgeving', 'Y11_Q50e', 'Problemen met vuilnis of afval op straat'],
		['Woning en woonomgeving', 'Y11_Q50f', 'Problemen in de buurt met verkeersopstoppingen'],
		['Woning en woonomgeving', 'Y11_Q51a', 'Toegang tot postdiensten'],
		['Woning en woonomgeving', 'Y11_Q51b', 'Toegang tot bankdiensten'],
		['Woning en woonomgeving', 'Y11_Q51c', 'Toegang tot openbaar vervoer'],
		['Woning en woonomgeving', 'Y11_Q51d', 'Toegang tot bioscoop, theater of cultureel centrum'],
		['Woning en woonomgeving', 'Y11_Q51e', 'Toegang tot recreatiegebieden of groenvoorzieningen'],
		['Woning en woonomgeving', 'Y11_Q52', 'Tijd kwijt aan de heen- en terugreis van huis naar werk of school']
	];
var question_
	 = [
	
		['Y11_Q33a', 'Direct contact (face to face) met uw kinderen die buiten het huishouden wonen'],
		['Y11_Q33b', 'Direct contact (face to face) met uw vader en/of moeder die buiten het huishouden wonen'],
		['Y11_Q33c', 'Direct contact (face to face) met andere familieleden die buiten het huishouden wonen'],
		['Y11_Q33d', 'Direct contact (face to face) met uw vrienden of buren'],
		['Y11_Q34a', 'Contact via telefoon, internet of post met uw kinderen die buiten het huishouden wonen'],
		['Y11_Q34b', 'Contact via telefoon, internet of post met uw vader en/of moeder die buiten het huishouden wonen'],
		['Y11_Q34c', 'Contact via telefoon, internet of post met andere familieleden die buiten het huishouden wonen'],
		['Y11_Q34d', 'Contact via telefoon, internet of post met uw vrienden of buren'],
		['Y11_Q35a', 'Van wie krijgt u steun u als u thuis hulp nodig heeft als u ziek bent?'],
		['Y11_Q35b', 'Van wie krijgt u steun u als u advies nodig heeft over belangrijke persoonlijke of familiezaken?'],
		['Y11_Q35c', 'Van wie krijgt u steun u als u hulp nodig heeft bij het vinden van een baan?'],
		['Y11_Q35d', 'Wie steunt u als u zich ongelukkig of depressief voelt?'],
		['Y11_Q35e', 'Wie steunt u als u dringend 1000 euro nodig heeft? '],
		['Y11_Q46a', 'Ik ben bijzonder gespannen geweest'],
		['Y11_Q46b', 'Ik heb me eenzaam gevoeld'],
		['Y11_Q46c', 'Ik heb me neerslachtig en depressief gevoeld'],
		['Y11_Q46d_WHO5', 'WHO-5 geestelijk welzijnsindex'],
		['Y11_Q47a', 'Een bezoek aan de dokter wordt bemoeilijkt door de afstand'],
		['Y11_Q47b', 'Een bezoek de een dokter wordt bemoeilijkt door de wachttijd voor het krijgen van een afspraak'],
		['Y11_Q47c', 'Een bezoek aan de dokter wordt bemoeilijkt door de wachttijd op de dag van de afspraak'],
		['Y11_Q47d', 'Een bezoek aan de dokter wordt bemoeilijkt door de kosten'],
		['Y11_Q47e', 'Een bezoek aan de dokter wordt bemoeilijkt door tijdgebrek'],
		['Y11_Q53a', 'Hoe waardeert u de kwaliteit van de gezondheidszorg in uw land?'],
		['Y11_Q53b', 'Hoe waardeert u de kwaliteit van het onderwijs in uw land?'],
		['Y11_Q53c', 'Hoe waardeert u de kwaliteit van het openbaar vervoer in uw land?'],
		['Y11_Q53d', 'Hoe waardeert u de kwaliteit van de kinderopvang in uw land?'],
		['Y11_Q53e', 'Hoe waardeert u de kwaliteit van de voorzieningen voor langdurige zorg in uw land?'],
		['Y11_Q53f', 'Hoe waardeert u de kwaliteit van de sociale woningbouw in uw land?'],
		['Y11_Q53g', 'Hoe waardeert u de kwaliteit van de algemene ouderdomswet (AOW) in uw land?'],
		['Y11_Q42', 'Waarneming van de eigen gezondheidstoestand'],
		['Y11_Q24', 'Denkt u dat mensen te vertrouwen zijn of dat je niet voorzichtig genoeg kunt zijn in de omgang met mensen?'],
		['Y11_Q25a', 'Is er volgens u sprake van wrijving tussen arme en rijke mensen?'],
		['Y11_Q25b', 'Is er volgens u sprake van wrijving tussen management en werknemers?'],
		['Y11_Q25c', 'Is er volgens u sprake van wrijving tussen mannen en vrouwen?'],
		['Y11_Q25d', 'Is er volgens u sprake van wrijving tussen ouderen en jongeren?'],
		['Y11_Q25e', 'Is er volgens u sprake van wrijving tussen verschillende etnische groeperingen?'],
		['Y11_Q25f', 'Is er volgens u sprake van wrijving tussen verschillende religieuze groeperingen?'],
		['Y11_Q25g', 'Is er volgens u sprake van wrijving tussen personen met een verschillende seksuele geaardheid?'],
		['Y11_Q28a', 'Vertrouwen in de Tweede Kamer'],
		['Y11_Q28b', 'Vertrouwen in het rechtssysteem'],
		['Y11_Q28c', 'Vertrouwen in de pers'],
		['Y11_Q28d', 'Vertrouwen in de politie'],
		['Y11_Q28e', 'Vertrouwen in de regering'],
		['Y11_Q28f', 'Vertrouwen in de lokale (gemeentelijke) overheid'],
		['Y11_Deprindex', 'Deprivatie-index: aantal items dat een huishouden zich niet kan permitteren'],
		['Y11_Q57', 'Financiële situatie van het huishouden vergeleken met de meeste mensen in Nederland'],
		['Y11_Q58', 'Is uw huishouden in staat rond te komen?'],
		['Y11_Q59a', 'Kunt u het zich permitteren uw woning goed te verwarmen?'],
		['Y11_Q59b', 'Kunt u het zich permitteren om elk jaar een week met vakantie te gaan?'],
		['Y11_Q59c', 'Kunt u het zich permitteren versleten meubilair te vervangen?'],
		['Y11_Q59d', 'Kunt u zich (als u dat zou willen) om de dag een warme maaltijd met vlees, kip of vis permitteren?'],
		['Y11_Q59e', 'Kunt u het zich permitteren om nieuwe kleding te kopen in plaats van tweedehands?'],
		['Y11_Q59f', 'Kunt u het zich permitteren om ten minste één keer maand vrienden of familie thuis uit te nodigen voor een drankje of een maaltijd?'],
		['Y11_Q60a', 'Heeft uw huishouden in de afgelopen 12 maanden een achterstand opgelopen bij het betalen van huur of hypotheeklasten?'],
		['Y11_Q60b', 'Heeft uw huishouden in de afgelopen 12 maanden een achterstand opgelopen bij het betalen van de rekeningen voor elektriciteit, water of gas?'],
		['Y11_Q60c', 'Heeft uw huishouden in de afgelopen 12 maanden een achterstand opgelopen met betrekking tot consumentenleningen?'],
		['Y11_Q60d', 'Heeft uw huishouden in de afgelopen 12 maanden een achterstand opgelopen met betrekking tot niet-officiële leningen?'],
		['Y11_Q65', 'Hoe is de financiële situatie van uw huishouden vergeleken met 12 maanden geleden?'],
		['Y11_Q66', 'Hoe ziet naar verwachting uw financiële situatie er de komende 12 maanden uit?'],
		['Y11_Q29a', 'Ik ben positief over de toekomst'],
		['Y11_Q29b', 'Over het algemeen vind ik dat wat ik doe in het leven de moeite waard is'],
		['Y11_Q29c', 'Naar mijn mening ben ik vrij om te beslissen hoe ik mijn leven leid'],
		['Y11_Q29d', 'In mijn dagelijkse leven heb ik maar zelden de tijd om de dingen te doen waar ik echt van geniet'],
		['Y11_Q30', 'Hoe tevreden bent u op dit moment met uw leven?'],
		['Y11_Q40a', 'Tevredenheid over uw opleiding'],
		['Y11_Q40b', 'Tevredenheid over uw huidige baan'],
		['Y11_Q40c', 'Tevredenheid over uw huidige levensstandaard'],
		['Y11_Q40d', 'Tevredenheid over uw woonsituatie'],
		['Y11_Q40e', 'Tevredenheid over uw gezinsleven'],
		['Y11_Q40f', 'Tevredenheid over uw gezondheid'],
		['Y11_Q40g', 'Tevredenheid over uw sociale leven'],
		['Y11_Q40h', 'Tevredenheid over de economische situatie in Nederland'],
		['Y11_Q41', 'Alles bij elkaar genomen, hoe gelukkig zou u zeggen dat u bent?'],
		['Y11_Q21a', 'Kerkdiensten bijwonen, uitgezonderd bruiloften, begrafenissen en doopplechtigheden'],
		['Y11_Q21b', 'Internet gebruiken voor andere doeleinden dan werk'],
		['Y11_Q21c', 'Een sport beoefenen of op een andere manier lichamelijk inspannend bezig zijn'],
		['Y11_Q21d', 'Deelnemen aan sociale activiteiten van een club, vereniging of stichting'],
		['Y11_Q22_Volunteering', 'Hoe vaak heeft u in de afgelopen 12 maanden onbetaald vrijwilligerswerk gedaan?'],
		['Y11_Q23a', 'Heeft u in de afgelopen 12 maanden een vergadering bijgewoond van een vakbond, politieke partij of politieke actiegroep?'],
		['Y11_Q23b', 'Heeft u in de afgelopen 12 maanden meegedaan aan een protestactie of demonstratie?'],
		['Y11_Q23c', 'Heeft u in de afgelopen 12 maanden een petitie ondertekend?'],
		['Y11_Q23d', 'Heeft u contact opgenomen met een politicus of overheidsvertegenwoordiger (anders dan een routinecontact met publieke instanties)?'],
		['Y11_Q29e', 'Ik voel me buitengesloten van de maatschappij'],
		['Y11_Q29f', 'Het leven is tegenwoordig zo gecompliceerd dat ik moeite heb om mijn weg te vinden'],
		['Y11_Q29g', 'Ik heb het gevoel dat anderen de waarde van wat ik doe niet erkennen'],
		['Y11_Q29h', 'Sommige mensen kijken op mij neer vanwege mijn werksituatie of inkomen'],
		['Y11_Q29i', 'Ik voel me betrokken bij de mensen in mijn woonomgeving'],
		['Y11_SocExIndex', 'Index sociale uitsluiting'],
		['Y11_Q8_PreferredWorkingHours', 'Hoeveel uur per week zou u willen werken?'],
		['Y11_Q10_Partnerprefhours', 'Hoeveel uur per week zou u willen dat uw partner werkt?'],
		['Y11_Q12a', 'Ik ben te moe thuisgekomen van het werk om huishoudelijke taken te doen'],
		['Y11_Q12b', 'Ik vond het moeilijk om aan mijn verantwoordelijkheden thuis te voldoen door de tijd die ik aan mijn werk besteed '],
		['Y11_Q12c', 'Ik heb moeite gehad me op mijn werk te concentreren vanwege gezinsverantwoordelijkheden'],
		['Y11_Q13a', 'Ik kan de tijdstippen waarop ik begin en ophoud met werken aanpassen'],
		['Y11_Q13b', 'Ik kan (over)uren sparen voor verlof/vrije tijd'],
		['Y11_Q13c', 'Ik kan op korte termijn een vrije dag/verlofdag opnemen wanneer nodig '],
		['Y11_Q15', 'Hoe waarschijnlijk is het dat u in de komende zes maanden wordt ontslagen?'],
		['Y11_Q16', 'Als u uw huidige baan verliest, hoe waarschijnlijk is het dan dat u een nieuwe baan vindt met een vergelijkbaar salaris?'],
		['Y11_Q36a', 'Hoe vaak bent u bezig met de zorg voor uw kinderen of kleinkinderen?'],
		['Y11_Q36b', 'Hoe vaak kookt u en/of bent u bezig met huishoudelijk werk?'],
		['Y11_Q36c', 'Hoe vaak bent u zich bezig met de zorg voor invalide of oudere familieleden?'],
		['Y11_Q38', 'Houding ten opzichte van het eigen aandeel in het huishoudelijk werk'],
		['Y11_Q39a', 'Houding ten opzichte van de tijd besteed aan familieleden'],
		['Y11_Q39b', 'Houding ten opzichte van de tijd besteed aan anderen'],
		['Y11_Q39c', 'Houding ten opzichte van de tijd besteed aan persoonlijke hobbys of interesses'],
		['Y11_Q39d_stress', 'Stress'],
		['Y11_Accommproblems', 'Aantal problemen met de woonsituatie'],
		['Y11_Q18', 'Huiseigenaar'],
		['Y11_Q19a', 'Problemen met de woonsituatie: gebrek aan ruimte'],
		['Y11_Q19b', 'Problemen met de woonsituatie: houtrot in raamkozijnen, deuren of vloeren'],
		['Y11_Q19c', 'Problemen met de woonsituatie: vochtproblemen of lekkages van muren of dak'],
		['Y11_Q19d', 'Problemen met de woonsituatie: ontbreken van een toilet in huis'],
		['Y11_Q19e', 'Problemen met de woonsituatie: ontbreken van een bad of douche'],
		['Y11_Q19f', 'Problemen met de woonsituatie: ontbreken van een plaats om buiten te zitten'],
		['Y11_Q20', 'Hoe waarschijnlijk is het dat u in de komende zes maanden uw woning moet verlaten omdat u deze niet meer kunt betalen?'],
		['Y11_Q50a', 'Problemen in de buurt met geluidsoverlast'],
		['Y11_Q50b', 'Problemen in de buurt met de luchtkwaliteit'],
		['Y11_Q50c', 'Problemen in de buurt met de kwaliteit van het drinkwater'],
		['Y11_Q50d', 'Problemen in de buurt met criminaliteit, geweld of vandalisme'],
		['Y11_Q50e', 'Problemen met vuilnis of afval op straat'],
		['Y11_Q50f', 'Problemen in de buurt met verkeersopstoppingen'],
		['Y11_Q51a', 'Toegang tot postdiensten'],
		['Y11_Q51b', 'Toegang tot bankdiensten'],
		['Y11_Q51c', 'Toegang tot openbaar vervoer'],
		['Y11_Q51d', 'Toegang tot bioscoop, theater of cultureel centrum'],
		['Y11_Q51e', 'Toegang tot recreatiegebieden of groenvoorzieningen'],
		['Y11_Q52', 'Tijd kwijt aan de heen- en terugreis van huis naar werk of school']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Gemiddeld'],
		['Y11_Deprindex', 'Mean', 'Gemiddeld'],
		['Y11_Q10_Partnerprefhours', '1--Work-less', 'Minder uur werken'],
		['Y11_Q10_Partnerprefhours', '2--Work-the-same', 'Hetzelfde aantal uur werken'],
		['Y11_Q10_Partnerprefhours', '3--Work-more', 'Meer uur werken'],
		['Y11_Q12a', '1--Several-times-a-week', 'Meerdere malen per week'],
		['Y11_Q12a', '2--Several-times-a-month', 'Meerdere malen per maand'],
		['Y11_Q12a', '3--Several-times-a-year', 'Meerdere malen per jaar'],
		['Y11_Q12a', '4--Less-often-rarely', 'Minder vaak / bijna nooit'],
		['Y11_Q12a', '5--Never', 'Nooit'],
		['Y11_Q12b', '1--Several-times-a-week', 'Meerdere malen per week'],
		['Y11_Q12b', '2--Several-times-a-month', 'Meerdere malen per maand'],
		['Y11_Q12b', '3--Several-times-a-year', 'Meerdere malen per jaar'],
		['Y11_Q12b', '4--Less-often-rarely', 'Minder vaak / bijna nooit'],
		['Y11_Q12b', '5--Never', 'Nooit'],
		['Y11_Q12c', '1--Several-times-a-week', 'Meerdere malen per week'],
		['Y11_Q12c', '2--Several-times-a-month', 'Meerdere malen per maand'],
		['Y11_Q12c', '3--Several-times-a-year', 'Meerdere malen per jaar'],
		['Y11_Q12c', '4--Less-often-rarely', 'Minder vaak / bijna nooit'],
		['Y11_Q12c', '5--Never', 'Nooit'],
		['Y11_Q13a', '1--Yes', 'Ja'],
		['Y11_Q13a', '2--No', 'Nee'],
		['Y11_Q13b', '1--Yes', 'Ja'],
		['Y11_Q13b', '2--No', 'Nee'],
		['Y11_Q13c', '1--Yes', 'Ja'],
		['Y11_Q13c', '2--No', 'Nee'],
		['Y11_Q15', '1--Very-likely', 'Zeer waarschijnlijk'],
		['Y11_Q15', '2--Quite-likely', 'Waarschijnlijk'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Niet waarschijnlijk maar ook niet onwaarschijnlijk'],
		['Y11_Q15', '4--Quite-unlikely', 'Onwaarschijnlijk'],
		['Y11_Q15', '5--Very-unlikely', 'Zeer onwaarschijnlijk'],
		['Y11_Q16', '1--Very-likely', 'Zeer waarschijnlijk'],
		['Y11_Q16', '2--Quite-likely', 'Waarschijnlijk'],
		['Y11_Q16', '3--Neither-likely-nor-unlikely', 'Niet waarschijnlijk maar ook niet onwaarschijnlijk'],
		['Y11_Q16', '4--Quite-unlikely', 'Onwaarschijnlijk'],
		['Y11_Q16', '5--Very-unlikely', 'Zeer onwaarschijnlijk'],
		['Y11_Q18', '1--Own-without-mortgage', 'Eigenaar zonder hypotheek'],
		['Y11_Q18', '2--Own-with-mortgage', 'Eigenaar met hypotheek'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Huurder, u betaalt huur aan een woningbouwcorporatie of een andere sociale instelling'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Huurder, u betaalt huur aan een woningbouwcorporatie of een andere sociale instantie'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Woning wordt bewoond zonder huur'],
		['Y11_Q18', '6--Other', 'Anders'],
		['Y11_Q19a', '1--Yes', 'Ja'],
		['Y11_Q19a', '2--No', 'Nee'],
		['Y11_Q19b', '1--Yes', 'Ja'],
		['Y11_Q19b', '2--No', 'Nee'],
		['Y11_Q19c', '1--Yes', 'Ja'],
		['Y11_Q19c', '2--No', 'Nee'],
		['Y11_Q19d', '1--Yes', 'Ja'],
		['Y11_Q19d', '2--No', 'Nee'],
		['Y11_Q19e', '1--Yes', 'Ja'],
		['Y11_Q19e', '2--No', 'Nee'],
		['Y11_Q19f', '1--Yes', 'Ja'],
		['Y11_Q19f', '2--No', 'Nee'],
		['Y11_Q20', '1--Very-likely', 'Zeer waarschijnlijk'],
		['Y11_Q20', '2--Quite-likely', 'Waarschijnlijk'],
		['Y11_Q20', '3--Quite-unlikely', 'Onwaarschijnlijk'],
		['Y11_Q20', '4--Very-unlikely', 'Zeer onwaarschijnlijk'],
		['Y11_Q21a', '1--Every-day-or-almost-every-day', 'Elke dag of bijna elke dag'],
		['Y11_Q21a', '2--At-least-once-a-week', 'Tenminste één keer per week'],
		['Y11_Q21a', '3--One-to-three-times-a-month', 'Eén tot drie keer per maand'],
		['Y11_Q21a', '4--Less-often', 'Minder vaak'],
		['Y11_Q21a', '5--Never', 'Nooit'],
		['Y11_Q21b', '1--Every-day-or-almost-every-day', 'Elke dag of bijna elke dag'],
		['Y11_Q21b', '2--At-least-once-a-week', 'Tenminste één keer per week'],
		['Y11_Q21b', '3--One-to-three-times-a-month', 'Eén tot drie keer per maand'],
		['Y11_Q21b', '4--Less-often', 'Minder vaak'],
		['Y11_Q21b', '5--Never', 'Nooit'],
		['Y11_Q21c', '1--Every-day-or-almost-every-day', 'Elke dag of bijna elke dag'],
		['Y11_Q21c', '2--At-least-once-a-week', 'Tenminste één keer per week'],
		['Y11_Q21c', '3--One-to-three-times-a-month', 'Eén tot drie keer per maand'],
		['Y11_Q21c', '4--Less-often', 'Minder vaak'],
		['Y11_Q21c', '5--Never', 'Nooit'],
		['Y11_Q21d', '1--Every-day-or-almost-every-day', 'Elke dag of bijna elke dag'],
		['Y11_Q21d', '2--At-least-once-a-week', 'Tenminste één keer per week'],
		['Y11_Q21d', '3--One-to-three-times-a-month', 'Eén tot drie keer per maand'],
		['Y11_Q21d', '4--Less-often', 'Minder vaak'],
		['Y11_Q21d', '5--Never', 'Nooit'],
		['Y11_Q22_Volunteering', '1--Volunteers-regularly', 'Doet regelmatig vrijwilligerswerk'],
		['Y11_Q22_Volunteering', '2--Volunteers-occasionally', 'Doet af en toe vrijwilligerswerk'],
		['Y11_Q22_Volunteering', '3--Does-not-volunteer', 'Doet geen vrijwilligerswerk'],
		['Y11_Q23a', '1--Yes', 'Ja'],
		['Y11_Q23a', '2--No', 'Nee'],
		['Y11_Q23b', '1--Yes', 'Ja'],
		['Y11_Q23b', '2--No', 'Nee'],
		['Y11_Q23c', '1--Yes', 'Ja'],
		['Y11_Q23c', '2--No', 'Nee'],
		['Y11_Q23d', '1--Yes', 'Ja'],
		['Y11_Q23d', '2--No', 'Nee'],
		['Y11_Q24', 'Mean', 'Gemiddeld'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Veel wrijving'],
		['Y11_Q25a', '2--Some-tension', 'Enige wrijving'],
		['Y11_Q25a', '3--No-tension', 'Geen wrijving'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Veel wrijving'],
		['Y11_Q25b', '2--Some-tension', 'Enige wrijving'],
		['Y11_Q25b', '3--No-tension', 'Geen wrijving'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Veel wrijving'],
		['Y11_Q25c', '2--Some-tension', 'Enige wrijving'],
		['Y11_Q25c', '3--No-tension', 'Geen wrijving'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Veel wrijving'],
		['Y11_Q25d', '2--Some-tension', 'Enige wrijving'],
		['Y11_Q25d', '3--No-tension', 'Geen wrijving'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Veel wrijving'],
		['Y11_Q25e', '2--Some-tension', 'Enige wrijving'],
		['Y11_Q25e', '3--No-tension', 'Geen wrijving'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Veel wrijving'],
		['Y11_Q25f', '2--Some-tension', 'Enige wrijving'],
		['Y11_Q25f', '3--No-tension', 'Geen wrijving'],
		['Y11_Q25g', '1--A-lot-of--tension', 'Veel wrijving'],
		['Y11_Q25g', '2--Some-tension', 'Enige wrijving'],
		['Y11_Q25g', '3--No-tension', 'Geen wrijving'],
		['Y11_Q28a', 'Mean', 'Gemiddeld'],
		['Y11_Q28b', 'Mean', 'Gemiddeld'],
		['Y11_Q28c', 'Mean', 'Gemiddeld'],
		['Y11_Q28d', 'Mean', 'Gemiddeld'],
		['Y11_Q28e', 'Mean', 'Gemiddeld'],
		['Y11_Q28f', 'Mean', 'Gemiddeld'],
		['Y11_Q29a', '1--Strongly-agree', 'Helemaal mee eens'],
		['Y11_Q29a', '2--Agree', 'Mee eens'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Niet mee eens, niet mee oneens'],
		['Y11_Q29a', '4--Disagree', 'Mee oneens'],
		['Y11_Q29a', '5--Strongly-disagree', 'Helemaal mee oneens'],
		['Y11_Q29b', '1--Strongly-agree', 'Helemaal mee eens'],
		['Y11_Q29b', '2--Agree', 'Mee eens'],
		['Y11_Q29b', '3--Neither-agree-nor-disagree', 'Niet mee eens, niet mee oneens'],
		['Y11_Q29b', '4--Disagree', 'Mee oneens'],
		['Y11_Q29b', '5--Strongly-disagree', 'Helemaal mee oneens'],
		['Y11_Q29c', '1--Strongly-agree', 'Helemaal mee eens'],
		['Y11_Q29c', '2--Agree', 'Mee eens'],
		['Y11_Q29c', '3--Neither-agree-nor-disagree', 'Niet mee eens, niet mee oneens'],
		['Y11_Q29c', '4--Disagree', 'Mee oneens'],
		['Y11_Q29c', '5--Strongly-disagree', 'Helemaal mee oneens'],
		['Y11_Q29d', '1--Strongly-agree', 'Helemaal mee eens'],
		['Y11_Q29d', '2--Agree', 'Mee eens'],
		['Y11_Q29d', '3--Neither-agree-nor-disagree', 'Niet mee eens, niet mee oneens'],
		['Y11_Q29d', '4--Disagree', 'Mee oneens'],
		['Y11_Q29d', '5--Strongly-disagree', 'Helemaal mee oneens'],
		['Y11_Q29e', '1--Strongly-agree', 'Helemaal mee eens'],
		['Y11_Q29e', '2--Agree', 'Mee eens'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Niet mee eens, niet mee oneens'],
		['Y11_Q29e', '4--Disagree', 'Mee oneens'],
		['Y11_Q29e', '5--Strongly-disagree', 'Helemaal mee oneens'],
		['Y11_Q29f', '1--Strongly-agree', 'Helemaal mee eens'],
		['Y11_Q29f', '2--Agree', 'Mee eens'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Niet mee eens, niet mee oneens'],
		['Y11_Q29f', '4--Disagree', 'Mee oneens'],
		['Y11_Q29f', '5--Strongly-disagree', 'Helemaal mee oneens'],
		['Y11_Q29g', '1--Strongly-agree', 'Helemaal mee eens'],
		['Y11_Q29g', '2--Agree', 'Mee eens'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Niet mee eens, niet mee oneens'],
		['Y11_Q29g', '4--Disagree', 'Mee oneens'],
		['Y11_Q29g', '5--Strongly-disagree', 'Helemaal mee oneens'],
		['Y11_Q29h', '1--Strongly-agree', 'Helemaal mee eens'],
		['Y11_Q29h', '2--Agree', 'Mee eens'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Niet mee eens, niet mee oneens'],
		['Y11_Q29h', '4--Disagree', 'Mee oneens'],
		['Y11_Q29h', '5--Strongly-disagree', 'Helemaal mee oneens'],
		['Y11_Q29i', '1--Strongly-agree', 'Helemaal mee eens'],
		['Y11_Q29i', '2--Agree', 'Mee eens'],
		['Y11_Q29i', '3--Neither-agree-nor-disagree', 'Niet mee eens, niet mee oneens'],
		['Y11_Q29i', '4--Disagree', 'Mee oneens'],
		['Y11_Q29i', '5--Strongly-disagree', 'Helemaal mee oneens'],
		['Y11_Q30', 'Mean', 'Gemiddeld'],
		['Y11_Q33a', '1--Every-day-or-almost-every-day', 'Elke dag of bijna elke dag'],
		['Y11_Q33a', '2--At-least-once-a-week', 'Tenminste één keer per week'],
		['Y11_Q33a', '3--One-to-three-times-a-month', 'Eén tot drie keer per maand'],
		['Y11_Q33a', '4--Less-often', 'Minder vaak'],
		['Y11_Q33a', '5--Never', 'Nooit'],
		['Y11_Q33b', '1--Every-day-or-almost-every-day', 'Elke dag of bijna elke dag'],
		['Y11_Q33b', '2--At-least-once-a-week', 'Tenminste één keer per week'],
		['Y11_Q33b', '3--One-to-three-times-a-month', 'Eén tot drie keer per maand'],
		['Y11_Q33b', '4--Less-often', 'Minder vaak'],
		['Y11_Q33b', '5--Never', 'Nooit'],
		['Y11_Q33c', '1--Every-day-or-almost-every-day', 'Elke dag of bijna elke dag'],
		['Y11_Q33c', '2--At-least-once-a-week', 'Tenminste één keer per week'],
		['Y11_Q33c', '3--One-to-three-times-a-month', 'Eén tot drie keer per maand'],
		['Y11_Q33c', '4--Less-often', 'Minder vaak'],
		['Y11_Q33c', '5--Never', 'Nooit'],
		['Y11_Q33d', '1--Every-day-or-almost-every-day', 'Elke dag of bijna elke dag'],
		['Y11_Q33d', '2--At-least-once-a-week', 'Tenminste één keer per week'],
		['Y11_Q33d', '3--One-to-three-times-a-month', 'Eén tot drie keer per maand'],
		['Y11_Q33d', '4--Less-often', 'Minder vaak'],
		['Y11_Q33d', '5--Never', 'Nooit'],
		['Y11_Q34a', '1--Every-day-or-almost-every-day', 'Elke dag of bijna elke dag'],
		['Y11_Q34a', '2--At-least-once-a-week', 'Tenminste één keer per week'],
		['Y11_Q34a', '3--One-to-three-times-a-month', 'Eén tot drie keer per maand'],
		['Y11_Q34a', '4--Less-often', 'Minder vaak'],
		['Y11_Q34a', '5--Never', 'Nooit'],
		['Y11_Q34b', '1--Every-day-or-almost-every-day', 'Elke dag of bijna elke dag'],
		['Y11_Q34b', '2--At-least-once-a-week', 'Tenminste één keer per week'],
		['Y11_Q34b', '3--One-to-three-times-a-month', 'Eén tot drie keer per maand'],
		['Y11_Q34b', '4--Less-often', 'Minder vaak'],
		['Y11_Q34b', '5--Never', 'Nooit'],
		['Y11_Q34c', '1--Every-day-or-almost-every-day', 'Elke dag of bijna elke dag'],
		['Y11_Q34c', '2--At-least-once-a-week', 'Tenminste één keer per week'],
		['Y11_Q34c', '3--One-to-three-times-a-month', 'Eén tot drie keer per maand'],
		['Y11_Q34c', '4--Less-often', 'Minder vaak'],
		['Y11_Q34c', '5--Never', 'Nooit'],
		['Y11_Q34d', '1--Every-day-or-almost-every-day', 'Elke dag of bijna elke dag'],
		['Y11_Q34d', '2--At-least-once-a-week', 'Tenminste één keer per week'],
		['Y11_Q34d', '3--One-to-three-times-a-month', 'Eén tot drie keer per maand'],
		['Y11_Q34d', '4--Less-often', 'Minder vaak'],
		['Y11_Q34d', '5--Never', 'Nooit'],
		['Y11_Q35a', '1--A-member-of-your-family', 'Een lid van uw gezin / familielid'],
		['Y11_Q35a', '2--A-friend--neighbour--or-someone-else', 'Een vriend, buurman/vrouw of iemand anders'],
		['Y11_Q35a', '3--A-service-provider--institution-or-organisation', 'Een dienstverlener, instelling of organisatie'],
		['Y11_Q35a', '4--Nobody', 'Niemand'],
		['Y11_Q35b', '1--A-member-of-your-family', 'Een lid van uw gezin / familielid'],
		['Y11_Q35b', '2--A-friend--neighbour--or-someone-else', 'Een vriend, buurman/vrouw of iemand anders'],
		['Y11_Q35b', '3--A-service-provider--institution-or-organisation', 'Een dienstverlener, instelling of organisatie'],
		['Y11_Q35b', '4--Nobody', 'Niemand'],
		['Y11_Q35c', '1--A-member-of-your-family', 'Een lid van uw gezin / familielid'],
		['Y11_Q35c', '2--A-friend--neighbour--or-someone-else', 'Een vriend, buurman/vrouw of iemand anders'],
		['Y11_Q35c', '3--A-service-provider--institution-or-organisation', 'Een dienstverlener, instelling of organisatie'],
		['Y11_Q35c', '4--Nobody', 'Niemand'],
		['Y11_Q35d', '1--A-member-of-your-family', 'Een lid van uw gezin / familielid'],
		['Y11_Q35d', '2--A-friend--neighbour--or-someone-else', 'Een vriend, buurman/vrouw of iemand anders'],
		['Y11_Q35d', '3--A-service-provider--institution-or-organisation', 'Een dienstverlener, instelling of organisatie'],
		['Y11_Q35d', '4--Nobody', 'Niemand'],
		['Y11_Q35e', '1--A-member-of-your-family', 'Een lid van uw gezin / familielid'],
		['Y11_Q35e', '2--A-friend--neighbour--or-someone-else', 'Een vriend, buurman/vrouw of iemand anders'],
		['Y11_Q35e', '3--A-service-provider--institution-or-organisation', 'Een dienstverlener, instelling of organisatie'],
		['Y11_Q35e', '4--Nobody', 'Niemand'],
		['Y11_Q36a', '1--Every-day', 'Elke dag'],
		['Y11_Q36a', '2--Several-days-a-week', 'Meerdere malen per week'],
		['Y11_Q36a', '3--Once-or-twice-a-week', 'Een of twee keer per week'],
		['Y11_Q36a', '4--Less-often', 'Minder vaak'],
		['Y11_Q36a', '5--Never', 'Nooit'],
		['Y11_Q36b', '1--Every-day', 'Elke dag'],
		['Y11_Q36b', '2--Several-days-a-week', 'Meerdere malen per week'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'Een of twee keer per week'],
		['Y11_Q36b', '4--Less-often', 'Minder vaak'],
		['Y11_Q36b', '5--Never', 'Nooit'],
		['Y11_Q36c', '1--Every-day', 'Elke dag'],
		['Y11_Q36c', '2--Several-days-a-week', 'Meerdere malen per week'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'Een of twee keer per week'],
		['Y11_Q36c', '4--Less-often', 'Minder vaak'],
		['Y11_Q36c', '5--Never', 'Nooit'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Groter dan bij een eerlijke verdeling uw deel zou horen te zijn'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Precies het deel dat bij een eerlijke verdeling uw deel zou horen te zijn'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Kleiner dan bij een eerlijke verdeling uw deel zou horen te zijn'],
		['Y11_Q39a', '1--Spend-more-time', 'Meer tijd besteden'],
		['Y11_Q39a', '2--As-much-as-I-currently-do', 'Zoveel als ik op dit moment doe'],
		['Y11_Q39a', '3--Spend-less-time', 'Minder tijd besteden'],
		['Y11_Q39b', '1--Spend-more-time', 'Meer tijd besteden'],
		['Y11_Q39b', '2--As-much-as-I-currently-do', 'Zoveel als ik op dit moment doe'],
		['Y11_Q39b', '3--Spend-less-time', 'Minder tijd besteden'],
		['Y11_Q39c', '1--Spend-more-time', 'Meer tijd besteden'],
		['Y11_Q39c', '2--As-much-as-I-currently-do', 'Zoveel als ik op dit moment doe'],
		['Y11_Q39c', '3--Spend-less-time', 'Minder tijd besteden'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'Zowel op het werk als thuis'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Op het werk of thuis'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Weinig of geen stress'],
		['Y11_Q40a', 'Mean', 'Gemiddeld'],
		['Y11_Q40b', 'Mean', 'Gemiddeld'],
		['Y11_Q40c', 'Mean', 'Gemiddeld'],
		['Y11_Q40d', 'Mean', 'Gemiddeld'],
		['Y11_Q40e', 'Mean', 'Gemiddeld'],
		['Y11_Q40f', 'Mean', 'Gemiddeld'],
		['Y11_Q40g', 'Mean', 'Gemiddeld'],
		['Y11_Q40h', 'Mean', 'Gemiddeld'],
		['Y11_Q41', 'Mean', 'Gemiddeld'],
		['Y11_Q42', '1--Very-good', 'Zeer goed'],
		['Y11_Q42', '2--Good', 'Goed'],
		['Y11_Q42', '3--Fair', 'Gemiddeld'],
		['Y11_Q42', '4--Bad', 'Slecht'],
		['Y11_Q42', '5--Very-bad', 'Zeer slecht'],
		['Y11_Q46a', '1--All-of-the-time', 'De hele tijd'],
		['Y11_Q46a', '2--Most-of-the-time', 'Het merendeel van de tijd'],
		['Y11_Q46a', '3--More-than-half-of-the-time', 'Meer dan de helft van de tijd'],
		['Y11_Q46a', '4--Less-than-half-of-the-time', 'Minder dan de helft van de tijd'],
		['Y11_Q46a', '5--Some-of-the-time', 'Enige tijd'],
		['Y11_Q46a', '6--At-no-time', 'Helemaal niet'],
		['Y11_Q46b', '1--All-of-the-time', 'De hele tijd'],
		['Y11_Q46b', '2--Most-of-the-time', 'Het merendeel van de tijd'],
		['Y11_Q46b', '3--More-than-half-of-the-time', 'Meer dan de helft van de tijd'],
		['Y11_Q46b', '4--Less-than-half-of-the-time', 'Minder dan de helft van de tijd'],
		['Y11_Q46b', '5--Some-of-the-time', 'Enige tijd'],
		['Y11_Q46b', '6--At-no-time', 'Helemaal niet'],
		['Y11_Q46c', '1--All-of-the-time', 'De hele tijd'],
		['Y11_Q46c', '2--Most-of-the-time', 'Het merendeel van de tijd'],
		['Y11_Q46c', '3--More-than-half-of-the-time', 'Meer dan de helft van de tijd'],
		['Y11_Q46c', '4--Less-than-half-of-the-time', 'Minder dan de helft van de tijd'],
		['Y11_Q46c', '5--Some-of-the-time', 'Enige tijd'],
		['Y11_Q46c', '6--At-no-time', 'Helemaal niet'],
		['Y11_Q46d_WHO5', 'Mean', 'Gemiddeld'],
		['Y11_Q47a', '1--Very-difficult', 'Zeer bemoeilijkt'],
		['Y11_Q47a', '2--A-little-difficult', 'Een beetje bemoeilijkt'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Helemaal niet bemoeilijkt'],
		['Y11_Q47b', '1--Very-difficult', 'Zeer bemoeilijkt'],
		['Y11_Q47b', '2--A-little-difficult', 'Een beetje bemoeilijkt'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Helemaal niet bemoeilijkt'],
		['Y11_Q47c', '1--Very-difficult', 'Zeer bemoeilijkt'],
		['Y11_Q47c', '2--A-little-difficult', 'Een beetje bemoeilijkt'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Helemaal niet bemoeilijkt'],
		['Y11_Q47d', '1--Very-difficult', 'Zeer bemoeilijkt'],
		['Y11_Q47d', '2--A-little-difficult', 'Een beetje bemoeilijkt'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Helemaal niet bemoeilijkt'],
		['Y11_Q47e', '1--Very-difficult', 'Zeer bemoeilijkt'],
		['Y11_Q47e', '2--A-little-difficult', 'Een beetje bemoeilijkt'],
		['Y11_Q47e', '3--Not-difficult-at-all', 'Helemaal niet bemoeilijkt'],
		['Y11_Q50a', '1--Major-problems', 'Ernstige problemen'],
		['Y11_Q50a', '2--Moderate-problems', 'Enige problemen'],
		['Y11_Q50a', '3--No-problems', 'Geen problemen'],
		['Y11_Q50b', '1--Major-problems', 'Ernstige problemen'],
		['Y11_Q50b', '2--Moderate-problems', 'Enige problemen'],
		['Y11_Q50b', '3--No-problems', 'Geen problemen'],
		['Y11_Q50c', '1--Major-problems', 'Ernstige problemen'],
		['Y11_Q50c', '2--Moderate-problems', 'Enige problemen'],
		['Y11_Q50c', '3--No-problems', 'Geen problemen'],
		['Y11_Q50d', '1--Major-problems', 'Ernstige problemen'],
		['Y11_Q50d', '2--Moderate-problems', 'Enige problemen'],
		['Y11_Q50d', '3--No-problems', 'Geen problemen'],
		['Y11_Q50e', '1--Major-problems', 'Ernstige problemen'],
		['Y11_Q50e', '2--Moderate-problems', 'Enige problemen'],
		['Y11_Q50e', '3--No-problems', 'Geen problemen'],
		['Y11_Q50f', '1--Major-problems', 'Ernstige problemen'],
		['Y11_Q50f', '2--Moderate-problems', 'Enige problemen'],
		['Y11_Q50f', '3--No-problems', 'Geen problemen'],
		['Y11_Q51a', '1--with-great-difficulty', 'Met veel moeite'],
		['Y11_Q51a', '2--with-some-difficulty', 'Met enige moeite'],
		['Y11_Q51a', '3--easily', 'Makkelijk'],
		['Y11_Q51a', '4--very-easily', 'Heel makkelijk'],
		['Y11_Q51b', '1--with-great-difficulty', 'Met veel moeite'],
		['Y11_Q51b', '2--with-some-difficulty', 'Met enige moeite'],
		['Y11_Q51b', '3--easily', 'Makkelijk'],
		['Y11_Q51b', '4--very-easily', 'Heel makkelijk'],
		['Y11_Q51c', '1--with-great-difficulty', 'Met veel moeite'],
		['Y11_Q51c', '2--with-some-difficulty', 'Met enige moeite'],
		['Y11_Q51c', '3--easily', 'Makkelijk'],
		['Y11_Q51c', '4--very-easily', 'Heel makkelijk'],
		['Y11_Q51d', '1--with-great-difficulty', 'Met veel moeite'],
		['Y11_Q51d', '2--with-some-difficulty', 'Met enige moeite'],
		['Y11_Q51d', '3--easily', 'Makkelijk'],
		['Y11_Q51d', '4--very-easily', 'Heel makkelijk'],
		['Y11_Q51e', '1--with-great-difficulty', 'Met veel moeite'],
		['Y11_Q51e', '2--with-some-difficulty', 'Met enige moeite'],
		['Y11_Q51e', '3--easily', 'Makkelijk'],
		['Y11_Q51e', '4--very-easily', 'Heel makkelijk'],
		['Y11_Q52', 'Mean', 'Gemiddeld'],
		['Y11_Q53a', 'Mean', 'Gemiddeld'],
		['Y11_Q53b', 'Mean', 'Gemiddeld'],
		['Y11_Q53c', 'Mean', 'Gemiddeld'],
		['Y11_Q53d', 'Mean', 'Gemiddeld'],
		['Y11_Q53e', 'Mean', 'Gemiddeld'],
		['Y11_Q53f', 'Mean', 'Gemiddeld'],
		['Y11_Q53g', 'Mean', 'Gemiddeld'],
		['Y11_Q57', '1--Much-worse', 'Veel slechter'],
		['Y11_Q57', '2--Somewhat-worse', 'Iets slechter'],
		['Y11_Q57', '3--Neither-worse-nor-better', 'Niet beter of slechter'],
		['Y11_Q57', '4--Somewhat-better', 'Iets beter'],
		['Y11_Q57', '5--Much-better', 'Veel beter'],
		['Y11_Q58', '1--With-great-difficulty', 'Met heel veel moeite'],
		['Y11_Q58', '2--With-difficulty', 'Met moeite'],
		['Y11_Q58', '3--With-some-difficulty', 'Met een klein beetje moeite'],
		['Y11_Q58', '4--Fairly-easily', 'Erg makkelijk'],
		['Y11_Q58', '5--Easily', 'Makkelijk'],
		['Y11_Q58', '6--Very-easily', 'Vrij makkelijk'],
		['Y11_Q59a', '1--No', 'Nee'],
		['Y11_Q59a', '2--Yes', 'Ja'],
		['Y11_Q59b', '1--No', 'Nee'],
		['Y11_Q59b', '2--Yes', 'Ja'],
		['Y11_Q59c', '1--No', 'Nee'],
		['Y11_Q59c', '2--Yes', 'Ja'],
		['Y11_Q59d', '1--No', 'Nee'],
		['Y11_Q59d', '2--Yes', 'Ja'],
		['Y11_Q59e', '1--No', 'Nee'],
		['Y11_Q59e', '2--Yes', 'Ja'],
		['Y11_Q59f', '1--No', 'Nee'],
		['Y11_Q59f', '2--Yes', 'Ja'],
		['Y11_Q60a', '1--Yes', 'Ja'],
		['Y11_Q60a', '2--No', 'Nee'],
		['Y11_Q60b', '1--Yes', 'Ja'],
		['Y11_Q60b', '2--No', 'Nee'],
		['Y11_Q60c', '1--Yes', 'Ja'],
		['Y11_Q60c', '2--No', 'Nee'],
		['Y11_Q60d', '1--Yes', 'Ja'],
		['Y11_Q60d', '2--No', 'Nee'],
		['Y11_Q65', '1--Better', 'Beter'],
		['Y11_Q65', '2--The-same', 'Hetzelfde'],
		['Y11_Q65', '3--Worse', 'Slechter'],
		['Y11_Q66', '1--Better', 'Beter'],
		['Y11_Q66', '2--The-same', 'Hetzelfde'],
		['Y11_Q66', '3--Worse', 'Slechter'],
		['Y11_Q8_PreferredWorkingHours', '1--Work-less', 'Minder uur werken'],
		['Y11_Q8_PreferredWorkingHours', '2--Work-the-same', 'Hetzelfde aantal uur werken'],
		['Y11_Q8_PreferredWorkingHours', '3--Work-more', 'Meer uur werken'],
		['Y11_SocExIndex', 'Mean', 'Gemiddeld']
	];
var country_
	 = [
	
		['AT', 'Oostenrijk'],
		['BE', 'België'],
		['BG', 'Bulgarije'],
		['CY', 'Cyprus'],
		['CZ', 'Tsjechië'],
		['DE', 'Duitsland'],
		['DK', 'Denemarken'],
		['EE', 'Estland'],
		['EL', 'Griekenland'],
		['ES', 'Spanje'],
		['FI', 'Finland'],
		['FR', 'Frankrijk'],
		['HR', 'Kroatië'],
		['HU', 'Hongarije'],
		['IE', 'Ierland'],
		['IS', 'IJsland'],
		['IT', 'Italië'],
		['LT', 'Litouwen'],
		['LU', 'Luxemburg'],
		['LV', 'Letland'],
		['ME', 'Montenegro'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Nederland'],
		['PL', 'Polen'],
		['PT', 'Portugal'],
		['RO', 'Roemenië'],
		['RS', 'Servië'],
		['SE', 'Zweden'],
		['SI', 'Slovenië'],
		['SK', 'Slowakije'],
		['TR', 'Turkije'],
		['UK', 'Verenigd Koninkrijk'],
		['XK', 'Kosovo'],
		['EuropeanUnion', 'Europese Unie']
	];
var question_meta
	 = [
	
		['Y11_Q33a', 'Direct contact (face to face) met uw kinderen die buiten het huishouden wonen', ''],
		['Y11_Q33b', 'Direct contact (face to face) met uw vader en/of moeder die buiten het huishouden wonen', ''],
		['Y11_Q33c', 'Direct contact (face to face) met een broer, zus of een ander familielid die buiten het huishouden woont', ''],
		['Y11_Q33d', 'Direct contact (face to face) met uw vrienden of buren die buiten het huishouden wonen', ''],
		['Y11_Q34a', 'Contact via telefoon, internet of post met uw kinderen die buiten het huishouden wonen', ''],
		['Y11_Q34b', 'Contact via telefoon, internet of post met uw vader en/of moeder die buiten het huishouden wonen', ''],
		['Y11_Q34c', 'Contact via telefoon, internet of post met een broer, zus of een andere familielid dat buiten het huishouden woont', ''],
		['Y11_Q34d', 'Contact via telefoon, internet of post met uw vrienden of buren die buiten het huishouden wonen', ''],
		['Y11_Q35a', 'Van wie krijgt u steun u als u thuis hulp nodig heeft als u ziek bent?', ''],
		['Y11_Q35b', 'Van wie krijgt u steun u als u advies nodig heeft over belangrijke persoonlijke of familiezaken?', ''],
		['Y11_Q35c', 'Van wie krijgt u steun u als u hulp nodig heeft bij het vinden van een baan?', ''],
		['Y11_Q35d', 'Wie steunt u als u zich ongelukkig of depressief voelt en iemand nodig heeft om mee te praten?', ''],
		['Y11_Q35e', 'Wie steunt u als u dringend 1000 euro nodig heeft voor een noodgeval? ', ''],
		['Y11_Q46a', 'Ik ben bijzonder gespannen geweest', ''],
		['Y11_Q46b', 'Ik heb me eenzaam gevoeld', ''],
		['Y11_Q46c', 'Ik heb me neerslachtig en depressief gevoeld', ''],
		['Y11_Q46d_WHO5', 'WHO-5 geestelijk welzijnsindex', ''],
		['Y11_Q47a', 'Een bezoek aan de dokter wordt bemoeilijkt door de afstand tot de dokterspraktijk of het ziekenhuis', ''],
		['Y11_Q47b', 'Een bezoek de een dokter wordt bemoeilijkt door de wachttijd voor het krijgen van een afspraak', ''],
		['Y11_Q47c', 'Het bezoek aan een dokter wordt bemoeilijkt door de wachttijd om de dokter te zien te krijgen op de dag van de afspraak', ''],
		['Y11_Q47d', 'Een bezoek aan de dokter wordt bemoeilijkt door de kosten van het medisch consult', ''],
		['Y11_Q47e', 'Een bezoek aan de dokter wordt bemoeilijkt door tijdgebrek vanwege werk of zorg voor kinderen', ''],
		['Y11_Q53a', 'Hoe waardeert u de kwaliteit van de gezondheidszorg in uw land?', ''],
		['Y11_Q53b', 'Hoe waardeert u de kwaliteit van het onderwijs in uw land?', ''],
		['Y11_Q53c', 'Hoe waardeert u de kwaliteit van het openbaar vervoer in uw land?', ''],
		['Y11_Q53d', 'Hoe waardeert u de kwaliteit van de kinderopvang in uw land?', ''],
		['Y11_Q53e', 'Hoe waardeert u de kwaliteit van de voorzieningen voor langdurige zorg in uw land?', ''],
		['Y11_Q53f', 'Hoe waardeert u de kwaliteit van de sociale woningbouw in uw land?', ''],
		['Y11_Q53g', 'Hoe waardeert u de kwaliteit van de algemene ouderdomswet (AOW) in uw land?', ''],
		['Y11_Q42', 'Waarneming van de eigen gezondheidstoestand', ''],
		['Y11_Q24', 'Denkt u dat mensen te vertrouwen zijn of dat je niet voorzichtig genoeg kunt zijn in de omgang met mensen?', ''],
		['Y11_Q25a', 'Is er volgens u sprake van wrijving tussen arme en rijke mensen?', ''],
		['Y11_Q25b', 'Is er volgens u sprake van wrijving tussen management en werknemers?', ''],
		['Y11_Q25c', 'Is er volgens u sprake van wrijving tussen mannen en vrouwen?', ''],
		['Y11_Q25d', 'Is er volgens u sprake van wrijving tussen ouderen en jongeren?', ''],
		['Y11_Q25e', 'Is er volgens u sprake van wrijving tussen verschillende etnische groeperingen?', ''],
		['Y11_Q25f', 'Is er volgens u sprake van wrijving tussen verschillende religieuze groeperingen?', ''],
		['Y11_Q25g', 'Is er volgens u sprake van wrijving tussen personen met een verschillende seksuele geaardheid?', ''],
		['Y11_Q28a', 'Vertrouwen in de Tweede Kamer', ''],
		['Y11_Q28b', 'Vertrouwen in het rechtssysteem', ''],
		['Y11_Q28c', 'Vertrouwen in de pers', ''],
		['Y11_Q28d', 'Vertrouwen in de politie', ''],
		['Y11_Q28e', 'Vertrouwen in de regering', ''],
		['Y11_Q28f', 'Vertrouwen in de lokale (gemeentelijke) overheid', ''],
		['Y11_Deprindex', 'Deprivatie-index: aantal items dat een huishouden zich niet kan permitteren', ''],
		['Y11_Q57', 'Financiële situatie van het huishouden vergeleken met de meeste mensen in Nederland', ''],
		['Y11_Q58', 'Is uw huishouden in staat rond te komen?', ''],
		['Y11_Q59a', 'Kunt u het zich permitteren uw woning goed te verwarmen?', ''],
		['Y11_Q59b', 'Kunt u het zich permitteren om elk jaar een week met vakantie te gaan?', ''],
		['Y11_Q59c', 'Kunt u het zich permitteren versleten meubilair te vervangen?', ''],
		['Y11_Q59d', 'Kan uw huishouden zich (als u dat zou willen) om de dag een warme maaltijd met vlees, kip of vis permitteren?', ''],
		['Y11_Q59e', 'Kunnen de leden van uw huishouden het zich permitteren om nieuwe kleding te kopen in plaats van tweedehands?', ''],
		['Y11_Q59f', 'Kan uw huishouden het zich permitteren om ten minste één keer maand vrienden of familie thuis uit te nodigen voor een drankje of een maaltijd?', ''],
		['Y11_Q60a', 'Heeft uw huishouden in de afgelopen 12 maanden een achterstand opgelopen bij het betalen van huur of hypotheeklasten?', ''],
		['Y11_Q60b', 'Heeft uw huishouden in de afgelopen 12 maanden een achterstand opgelopen bij het betalen van de rekeningen voor elektriciteit, water of gas?', ''],
		['Y11_Q60c', 'Heeft uw huishouden in de afgelopen 12 maanden een achterstand opgelopen bij betalingen die te maken hebben met consumentenleningen?', ''],
		['Y11_Q60d', 'Heeft uw huishouden in de afgelopen 12 maanden een achterstand opgelopen met betalingen in het kader van niet-officiële leningen?', ''],
		['Y11_Q65', 'Hoe is de financiële situatie van uw huishouden vergeleken met 12 maanden geleden?', ''],
		['Y11_Q66', 'Hoe ziet naar verwachting uw financiële situatie er de komende 12 maanden uit?', ''],
		['Y11_Q29a', 'Ik ben positief over de toekomst', ''],
		['Y11_Q29b', 'Over het algemeen vind ik dat wat ik doe in het leven de moeite waard is', ''],
		['Y11_Q29c', 'Naar mijn mening ben ik vrij om te beslissen hoe ik mijn leven leid', ''],
		['Y11_Q29d', 'In mijn dagelijkse leven heb ik maar zelden de tijd om de dingen te doen waar ik echt van geniet', ''],
		['Y11_Q30', 'Hoe tevreden bent u op dit moment met uw leven?', ''],
		['Y11_Q40a', 'Tevredenheid over uw opleiding', ''],
		['Y11_Q40b', 'Tevredenheid over uw huidige baan', ''],
		['Y11_Q40c', 'Tevredenheid over uw huidige levensstandaard', ''],
		['Y11_Q40d', 'Tevredenheid over uw woonsituatie', ''],
		['Y11_Q40e', 'Tevredenheid over uw gezinsleven', ''],
		['Y11_Q40f', 'Tevredenheid over uw gezondheid', ''],
		['Y11_Q40g', 'Tevredenheid over uw sociale leven', ''],
		['Y11_Q40h', 'Tevredenheid over de economische situatie in Nederland', ''],
		['Y11_Q41', 'Alles bij elkaar genomen, hoe gelukkig zou u zeggen dat u bent?', ''],
		['Y11_Q21a', 'Kerkdiensten bijwonen, uitgezonderd bruiloften, begrafenissen en doopplechtigheden', ''],
		['Y11_Q21b', 'Internet gebruiken voor andere doeleinden dan werk', ''],
		['Y11_Q21c', 'Een sport beoefenen of op een andere manier lichamelijk inspannend bezig zijn', ''],
		['Y11_Q21d', 'Deelnemen aan sociale activiteiten van een club, vereniging of stichting', ''],
		['Y11_Q22_Volunteering', 'Hoe vaak heeft u in de afgelopen 12 maanden onbetaald vrijwilligerswerk gedaan?', ''],
		['Y11_Q23a', 'Heeft u in de afgelopen 12 maanden een vergadering bijgewoond van een vakbond, politieke partij of politieke actiegroep?', ''],
		['Y11_Q23b', 'Heeft u in de afgelopen 12 maanden meegedaan aan een protestactie of demonstratie?', ''],
		['Y11_Q23c', 'Heeft u in de afgelopen 12 maanden een petitie ondertekend (op papier of via e-mail of internet)?', ''],
		['Y11_Q23d', 'Heeft u contact opgenomen met een politicus of overheidsvertegenwoordiger (anders dan een routinecontact met publieke instanties)?', ''],
		['Y11_Q29e', 'Ik voel me buitengesloten van de maatschappij', ''],
		['Y11_Q29f', 'Het leven is tegenwoordig zo gecompliceerd dat ik moeite heb om mijn weg te vinden', ''],
		['Y11_Q29g', 'Ik heb het gevoel dat anderen de waarde van wat ik doe niet erkennen', ''],
		['Y11_Q29h', 'Sommige mensen kijken op mij neer vanwege mijn werksituatie of inkomen', ''],
		['Y11_Q29i', 'Ik voel me betrokken bij de mensen in mijn woonomgeving', ''],
		['Y11_SocExIndex', 'Index sociale uitsluiting', ''],
		['Y11_Q8_PreferredWorkingHours', 'Hoeveel uur per week zou u willen werken?', ''],
		['Y11_Q10_Partnerprefhours', 'Hoeveel uur per week zou u willen dat uw partner werkt?', 'Deze vraag is gesteld aan respondenten die met een partner samenwonen.'],
		['Y11_Q12a', ' Ik ben te moe thuisgekomen van het werk om huishoudelijke taken te doen', ''],
		['Y11_Q12b', 'Ik vond het moeilijk om aan mijn verantwoordelijkheden thuis te voldoen door de tijd die ik aan mijn werk besteed ', ''],
		['Y11_Q12c', 'Ik heb moeite gehad me op mijn werk te concentreren vanwege gezinsverantwoordelijkheden', ''],
		['Y11_Q13a', 'Ik kan de tijdstippen waarop ik begin en ophoud met werken aanpassen', ''],
		['Y11_Q13b', 'Ik kan (over)uren sparen voor verlof/vrije tijd', ''],
		['Y11_Q13c', 'Ik kan op korte termijn een vrije dag/verlofdag opnemen wanneer nodig ', ''],
		['Y11_Q15', 'Hoe waarschijnlijk is het dat u in de komende zes maanden wordt ontslagen?', ''],
		['Y11_Q16', 'Als u uw huidige baan verliest, hoe waarschijnlijk is het dan dat u een nieuwe baan vindt met een vergelijkbaar salaris?', 'Deze vraag is gesteld aan respondenten die een betaalde baan hadden.'],
		['Y11_Q36a', 'Hoe vaak bent u bezig met de zorg voor uw kinderen of kleinkinderen?', ''],
		['Y11_Q36b', 'Hoe vaak kookt u en/of bent u bezig met huishoudelijk werk?', ''],
		['Y11_Q36c', 'Hoe vaak bent u zich bezig met de zorg voor invalide of oudere familieleden?', ''],
		['Y11_Q38', 'Wat vindt u van uw aandeel in het huishoudelijk werk?', ''],
		['Y11_Q39a', 'Houding ten opzichte van de tijd besteed aan contacten met familieleden', ''],
		['Y11_Q39b', 'Houding ten opzichte van de tijd besteed aan andere sociale contacten', ''],
		['Y11_Q39c', 'Houding ten opzichte van de tijd besteed aan persoonlijke hobbys of interesses', ''],
		['Y11_Q39d_stress', 'Heeft u last van stress vanwege problemen met de balans werk-privé?', ''],
		['Y11_Accommproblems', 'Aantal problemen met de woonsituatie', ''],
		['Y11_Q18', 'Huiseigenaar', ''],
		['Y11_Q19a', 'Problemen met de woonsituatie: gebrek aan ruimte', ''],
		['Y11_Q19b', 'Problemen met de woonsituatie: houtrot in raamkozijnen, deuren of vloeren', ''],
		['Y11_Q19c', 'Problemen met de woonsituatie: vochtproblemen of lekkages van muren of dak', ''],
		['Y11_Q19d', 'Problemen met de woonsituatie: ontbreken van een toilet in huis', ''],
		['Y11_Q19e', 'Problemen met de woonsituatie: ontbreken van een bad of douche', ''],
		['Y11_Q19f', 'Problemen met de woonsituatie: ontbreken van een plaats om buiten te zitten', ''],
		['Y11_Q20', 'Hoe waarschijnlijk is het dat u in de komende zes maanden uw woning moet verlaten omdat u deze niet meer kunt betalen?', ''],
		['Y11_Q50a', 'Problemen in de buurt met geluidsoverlast', ''],
		['Y11_Q50b', 'Problemen in de buurt met de luchtkwaliteit', ''],
		['Y11_Q50c', 'Problemen in de buurt met de kwaliteit van het drinkwater', ''],
		['Y11_Q50d', 'Problemen in de buurt met criminaliteit, geweld of vandalisme', ''],
		['Y11_Q50e', 'Problemen in de buurt met vuilnis of afval op straat', ''],
		['Y11_Q50f', 'Problemen in de buurt met verkeersopstoppingen', ''],
		['Y11_Q51a', 'Toegang tot postdiensten', ''],
		['Y11_Q51b', 'Toegang tot bankdiensten', ''],
		['Y11_Q51c', 'Toegang tot openbaar vervoer', ''],
		['Y11_Q51d', 'Toegang tot bioscoop, theater of cultureel centrum', ''],
		['Y11_Q51e', 'Toegang tot recreatiegebieden of groenvoorzieningen', ''],
		['Y11_Q52', 'Tijd kwijt aan de heen- en terugreis van huis naar werk of school', '']
	];
