//Auto Generated file
var subset_
	 = [
	
		['Y11_Incomequartiles_percapita', 'Inkomst'],
		['Y11_HH2a', 'Kön'],
		['Y11_Agecategory', 'Ålder']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Alla åldrar'],
		['Y11_Agecategory', '1--18-24y', '18 till 24 år'],
		['Y11_Agecategory', '2--25-34y', '25 till 34 år'],
		['Y11_Agecategory', '3--35-49y', '35 till 49 år'],
		['Y11_Agecategory', '4--50-64y', '50 till 64 år'],
		['Y11_Agecategory', '5---64y', '> 64 år'],
		['Y11_HH2a', 'All', 'Båda könen'],
		['Y11_HH2a', '1--Female', 'Kvinna'],
		['Y11_HH2a', '2--Male', 'Man'],
		['Y11_Incomequartiles_percapita', 'All', 'Alla inkomstnivåer'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Lägsta'],
		['Y11_Incomequartiles_percapita', '2--2nd', '2:a'],
		['Y11_Incomequartiles_percapita', '3--3rd', '3:e'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Högsta']
	];
var topic_
	 = [
	
		['', 'Alla (127)'],
		['Anställning och balans arbete–fritid', 'Anställning och balans arbete–fritid (18)'],
		['Familj och umgänge', 'Familj och umgänge (13)'],
		['Hem och närmiljö', 'Hem och närmiljö (21)'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Hälso- och sjukvård samt offentliga tjänster (17)'],
		['Levnadsstandard och fattigdom', 'Levnadsstandard och fattigdom (15)'],
		['Samhällets kvalitet', 'Samhällets kvalitet (14)'],
		['Social utstötning och samhällsengagemang', 'Social utstötning och samhällsengagemang (15)'],
		['Subjektivt välstånd', 'Subjektivt välstånd (14)']
	];
var topic_question
	 = [
	
		['Anställning och balans arbete–fritid', 'Y11_Q8_PreferredWorkingHours', 'Hur många timmar i veckan vill du själv arbeta?'],
		['Anställning och balans arbete–fritid', 'Y11_Q10_Partnerprefhours', 'Hur många timmar i veckan vill du att din partner ska arbeta?'],
		['Anställning och balans arbete–fritid', 'Y11_Q12a', 'Jag har kommit hem från arbetet för trött för att utföra hushållssysslor.'],
		['Anställning och balans arbete–fritid', 'Y11_Q12b', 'Jag har haft svårt att uppfylla mitt ansvar mot familjen på grund av mina arbetstider. '],
		['Anställning och balans arbete–fritid', 'Y11_Q12c', 'Jag har haft svårt att koncentrera mig på arbetet på grund av ansvaret gentemot familjen.'],
		['Anställning och balans arbete–fritid', 'Y11_Q13a', 'Jag kan arbeta flextid.'],
		['Anställning och balans arbete–fritid', 'Y11_Q13b', 'Jag kan ackumulera timmar för kompledighet.'],
		['Anställning och balans arbete–fritid', 'Y11_Q13c', 'Jag kan ta ledigt en dag med kort varsel om det behövs. '],
		['Anställning och balans arbete–fritid', 'Y11_Q15', 'Hur sannolikt är det att du ska förlora jobbet under de kommande sex månaderna?'],
		['Anställning och balans arbete–fritid', 'Y11_Q16', 'Om du blev arbetslös, hur sannolikt är det att du hittar ett jobb med samma lön?'],
		['Anställning och balans arbete–fritid', 'Y11_Q36a', 'Hur ofta passar du dina barn eller barnbarn?'],
		['Anställning och balans arbete–fritid', 'Y11_Q36b', 'Hur ofta lagar du mat eller utför andra hushållsgöromål?'],
		['Anställning och balans arbete–fritid', 'Y11_Q36c', 'Hur ofta vårdar du gamla eller funktionshindrade släktingar?'],
		['Anställning och balans arbete–fritid', 'Y11_Q38', 'Attityd när det gäller att dela på hushållsarbetet.'],
		['Anställning och balans arbete–fritid', 'Y11_Q39a', 'Attityd när det gäller att tillbringa tid med familjen.'],
		['Anställning och balans arbete–fritid', 'Y11_Q39b', 'Attityd när det gäller social samvaro.'],
		['Anställning och balans arbete–fritid', 'Y11_Q39c', 'Attityd när det gäller tid för hobbyer och intressen.'],
		['Anställning och balans arbete–fritid', 'Y11_Q39d_stress', 'Stress.'],
		['Familj och umgänge', 'Y11_Q33a', 'Direktkontakt med barn som flyttat hemifrån.'],
		['Familj och umgänge', 'Y11_Q33b', 'Direktkontakt med mor eller far som inte ingår i hushållet.'],
		['Familj och umgänge', 'Y11_Q33c', 'Direktkontakt med andra släktingar som inte ingår i hushållet.'],
		['Familj och umgänge', 'Y11_Q33d', 'Direktkontakt med vänner eller grannar.'],
		['Familj och umgänge', 'Y11_Q34a', 'Kontakt med barn som flyttat hemifrån via telefon, internet eller brev.'],
		['Familj och umgänge', 'Y11_Q34b', 'Kontakt med mor eller far som inte ingår i hushållet via telefon, internet eller brev.'],
		['Familj och umgänge', 'Y11_Q34c', 'Kontakt med andra släktingar som inte ingår i hushållet via telefon, internet eller brev.'],
		['Familj och umgänge', 'Y11_Q34d', 'Kontakt med vänner eller grannar via telefon, internet eller brev.'],
		['Familj och umgänge', 'Y11_Q35a', 'Vem skulle hjälpa dig om du är sjuk och behöver hjälp i hemmet?'],
		['Familj och umgänge', 'Y11_Q35b', 'Vem skulle ge dig stöd om du behövde råd i en viktig fråga som gäller dig själv eller familjen?'],
		['Familj och umgänge', 'Y11_Q35c', 'Vem skulle ge dig stöd om du behöver hjälp med att söka arbete?'],
		['Familj och umgänge', 'Y11_Q35d', 'Vem skulle ge dig stöd om du kände dig lite deprimerad?'],
		['Familj och umgänge', 'Y11_Q35e', 'Vem skulle du få hjälp av om du snabbt behövde 1 000 euro?'],
		['Hem och närmiljö', 'Y11_Accommproblems', 'Antal problem med bostad'],
		['Hem och närmiljö', 'Y11_Q18', 'Bostaden'],
		['Hem och närmiljö', 'Y11_Q19a', 'Problem med bostaden: brist på utrymme.'],
		['Hem och närmiljö', 'Y11_Q19b', 'Problem med bostaden: röta i fönster, dörrar eller golv.'],
		['Hem och närmiljö', 'Y11_Q19c', 'Problem med bostaden: fukt eller läckage i väggar eller tak.'],
		['Hem och närmiljö', 'Y11_Q19d', 'Problem med bostaden: inget wc inomhus.'],
		['Hem och närmiljö', 'Y11_Q19e', 'Problem med bostaden: inget badkar eller dusch.'],
		['Hem och närmiljö', 'Y11_Q19f', 'Problem med bostaden: ingen plats att sitta utomhus.'],
		['Hem och närmiljö', 'Y11_Q20', 'Hur troligt är det att du kommer att behöva lämna din bostad inom de närmaste sex månaderna eftersom du inte har råd att bo kvar?'],
		['Hem och närmiljö', 'Y11_Q50a', 'Problem med buller i grannskapet.'],
		['Hem och närmiljö', 'Y11_Q50b', 'Problem med luftkvalitet i grannskapet.'],
		['Hem och närmiljö', 'Y11_Q50c', 'Problem med dricksvattnets kvalitet i grannskapet.'],
		['Hem och närmiljö', 'Y11_Q50d', 'Problem med brottslighet, våld eller vandalism i grannskapet.'],
		['Hem och närmiljö', 'Y11_Q50e', 'Problem med avfall eller skräp på gatan.'],
		['Hem och närmiljö', 'Y11_Q50f', 'Problem med trafikstockningar i grannskapet.'],
		['Hem och närmiljö', 'Y11_Q51a', 'Tillgång till posttjänster.'],
		['Hem och närmiljö', 'Y11_Q51b', 'Tillgång till banktjänster.'],
		['Hem och närmiljö', 'Y11_Q51c', 'Tillgång till offentliga transporter.'],
		['Hem och närmiljö', 'Y11_Q51d', 'Tillgång till biograf, teater eller kulturcentrum.'],
		['Hem och närmiljö', 'Y11_Q51e', 'Tillgång till rekreations- eller grönområden.'],
		['Hem och närmiljö', 'Y11_Q52', 'Tid för att ta sig till eller från arbete eller studier.'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q42', 'Upplevd hälsostatus'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q46a', 'Jag har varit mycket orolig.'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q46b', 'Jag har känt mig ensam.'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q46c', 'Jag har känt mig nedslagen och deprimerad.'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q46d_WHO5', 'WHO-5, skalan över psykisk hälsa'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q47a', 'Svårt att besöka läkare på grund av avståndet.'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q47b', 'Svårt att besöka läkare på grund av svårigheter med att boka tid.'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q47c', 'Svårt att besöka läkare på grund av långa väntetider på mottagningen den bokade tiden.'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q47d', 'Svårt att besöka läkare på grund av kostnaden.'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q47e', 'Svårt att besöka läkare på grund av tidsbrist.'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q53a', 'Hur skulle du bedöma kvaliteten på hälso- och sjukvården i ditt land?'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q53b', 'Hur skulle du bedöma kvaliteten på utbildningssystemet i ditt land?'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q53c', 'Hur skulle du bedöma kvaliteten på de offentliga transporterna i ditt land?'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q53d', 'Hur skulle du bedöma kvaliteten på barnomsorgen i ditt land?'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q53e', 'Hur skulle du bedöma kvaliteten på långtidsvården i ditt land?'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q53f', 'Hur skulle du bedöma kvaliteten på de allmännyttiga bostäderna i ditt land?'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q53g', 'Hur skulle du bedöma kvaliteten på det statliga pensionssystemet i ditt land?'],
		['Levnadsstandard och fattigdom', 'Y11_Deprindex', 'Eftersatthetsindex: Antal saker hushållen inte har råd med'],
		['Levnadsstandard och fattigdom', 'Y11_Q57', 'Hushållets finansiella situation jämfört med de flesta i landet.'],
		['Levnadsstandard och fattigdom', 'Y11_Q58', 'Kan ditt hushåll klara av att betala sina utgifter?'],
		['Levnadsstandard och fattigdom', 'Y11_Q59a', 'Har du råd att hålla bostaden tillräckligt varm?'],
		['Levnadsstandard och fattigdom', 'Y11_Q59b', 'Har du råd att resa på en veckas semester?'],
		['Levnadsstandard och fattigdom', 'Y11_Q59c', 'Har du råd att ersätta utslitna möbler?'],
		['Levnadsstandard och fattigdom', 'Y11_Q59d', 'Skulle du ha råd att äta kött, kyckling eller fisk varannan dag (om du vill)?'],
		['Levnadsstandard och fattigdom', 'Y11_Q59e', 'Har du råd att köpa nya i stället för begagnade kläder?'],
		['Levnadsstandard och fattigdom', 'Y11_Q59f', 'Har du råd att bjuda in vänner eller familj på en drink eller måltid minst en gång i månaden?'],
		['Levnadsstandard och fattigdom', 'Y11_Q60a', 'Har ditt hushåll legat efter med hyran eller avbetalningar på bostadslån under de senaste tolv månaderna?'],
		['Levnadsstandard och fattigdom', 'Y11_Q60b', 'Har ditt hushåll legat efter med att betala räkningar för vatten, el etc. under de senaste tolv månaderna?'],
		['Levnadsstandard och fattigdom', 'Y11_Q60c', 'Har ditt hushåll legat efter med avbetalningar på konsumtionslån under de senaste tolv månaderna?'],
		['Levnadsstandard och fattigdom', 'Y11_Q60d', 'Har ditt hushåll legat efter med betalningar på personliga lån under de senaste tolv månaderna?'],
		['Levnadsstandard och fattigdom', 'Y11_Q65', 'Hushållets finansiella situation jämfört med för tolv månader sedan'],
		['Levnadsstandard och fattigdom', 'Y11_Q66', 'Förväntad finansiell situation under den kommande tolvmånadersperioden'],
		['Samhällets kvalitet', 'Y11_Q24', 'Anser du att man kan lita på de flesta människor eller att man aldrig kan vara nog försiktig i kontakten med andra?'],
		['Samhällets kvalitet', 'Y11_Q25a', 'Upplevd spänning mellan fattiga och rika.'],
		['Samhällets kvalitet', 'Y11_Q25b', 'Upplevd spänning mellan chefer och anställda.'],
		['Samhällets kvalitet', 'Y11_Q25c', 'Upplevd spänning mellan män och kvinnor.'],
		['Samhällets kvalitet', 'Y11_Q25d', 'Upplevd spänning mellan gamla och unga.'],
		['Samhällets kvalitet', 'Y11_Q25e', 'Upplevd spänning mellan olika raser och etniska grupper.'],
		['Samhällets kvalitet', 'Y11_Q25f', 'Upplevd spänning mellan olika religiösa grupper.'],
		['Samhällets kvalitet', 'Y11_Q25g', 'Upplevd spänning mellan personer med olika sexuell läggning.'],
		['Samhällets kvalitet', 'Y11_Q28a', 'Förtroende för parlamentet.'],
		['Samhällets kvalitet', 'Y11_Q28b', 'Förtroende för rättssystemet.'],
		['Samhällets kvalitet', 'Y11_Q28c', 'Förtroende för pressen.'],
		['Samhällets kvalitet', 'Y11_Q28d', 'Förtroende för polisen.'],
		['Samhällets kvalitet', 'Y11_Q28e', 'Förtroende för regeringen.'],
		['Samhällets kvalitet', 'Y11_Q28f', 'Förtroende för lokala eller kommunala myndigheter.'],
		['Social utstötning och samhällsengagemang', 'Y11_Q21a', 'Deltagande i religiösa ceremonier, förutom bröllop, begravningar och dop.'],
		['Social utstötning och samhällsengagemang', 'Y11_Q21b', 'Användning av internet utanför arbetet.'],
		['Social utstötning och samhällsengagemang', 'Y11_Q21c', 'Deltagande i idrott eller fysisk träning.'],
		['Social utstötning och samhällsengagemang', 'Y11_Q21d', 'Deltagande i social verksamhet i en klubb, förening eller liknande.'],
		['Social utstötning och samhällsengagemang', 'Y11_Q22_Volunteering', 'Hur ofta utförde du ideellt arbete under de senaste tolv månaderna?'],
		['Social utstötning och samhällsengagemang', 'Y11_Q23a', 'Deltog i ett möte med fackförening, politiskt parti eller opinionsgrupp under de senaste tolv månaderna.'],
		['Social utstötning och samhällsengagemang', 'Y11_Q23b', 'Deltog i protest eller demonstration under de senaste tolv månaderna.'],
		['Social utstötning och samhällsengagemang', 'Y11_Q23c', 'Skrev på ett upprop under de senaste tolv månaderna.'],
		['Social utstötning och samhällsengagemang', 'Y11_Q23d', 'Kontaktade politiker eller offentlig tjänsteman (förutom rutinkontakt genom offentlig förvaltning).'],
		['Social utstötning och samhällsengagemang', 'Y11_Q29e', 'Jag känner mig utestängd från samhället.'],
		['Social utstötning och samhällsengagemang', 'Y11_Q29f', 'Livet har blivit så komplicerat i dag att jag inte vet hur jag ska göra.'],
		['Social utstötning och samhällsengagemang', 'Y11_Q29g', 'Jag upplever att andra inte uppskattar det jag gör.'],
		['Social utstötning och samhällsengagemang', 'Y11_Q29h', 'Vissa människor ser ner på mig på grund av mitt arbete eller inkomst.'],
		['Social utstötning och samhällsengagemang', 'Y11_Q29i', 'Jag känner samhörighet med människorna där jag bor.'],
		['Social utstötning och samhällsengagemang', 'Y11_SocExIndex', 'Index för socialt utanförskap'],
		['Subjektivt välstånd', 'Y11_Q29a', 'Jag är optimistisk inför framtiden.'],
		['Subjektivt välstånd', 'Y11_Q29b', 'Jag upplever i regel att det jag gör är meningsfullt.'],
		['Subjektivt välstånd', 'Y11_Q29c', 'Jag upplever att jag är fri att besluta om hur jag ska leva.'],
		['Subjektivt välstånd', 'Y11_Q29d', 'I mitt dagliga liv har jag sällan tid att göra sådant jag verkligen tycker om.'],
		['Subjektivt välstånd', 'Y11_Q30', 'Hur tillfredsställd är du med ditt liv nuförtiden?'],
		['Subjektivt välstånd', 'Y11_Q40a', 'Tillfredsställelse med utbildning'],
		['Subjektivt välstånd', 'Y11_Q40b', 'Tillfredsställelse med nuvarande arbete'],
		['Subjektivt välstånd', 'Y11_Q40c', 'Tillfredsställelse med nuvarande levnadsstandard'],
		['Subjektivt välstånd', 'Y11_Q40d', 'Tillfredsställelse med bostad'],
		['Subjektivt välstånd', 'Y11_Q40e', 'Tillfredsställelse med familjeliv'],
		['Subjektivt välstånd', 'Y11_Q40f', 'Tillfredsställelse med hälsa'],
		['Subjektivt välstånd', 'Y11_Q40g', 'Tillfredsställelse med umgänge'],
		['Subjektivt välstånd', 'Y11_Q40h', 'Tillfredsställelse med landets ekonomiska situation'],
		['Subjektivt välstånd', 'Y11_Q41', 'Om du sammanfattar allt detta, hur lycklig anser du att du är?']
	];
var question_
	 = [
	
		['Y11_Q8_PreferredWorkingHours', 'Hur många timmar i veckan vill du själv arbeta?'],
		['Y11_Q10_Partnerprefhours', 'Hur många timmar i veckan vill du att din partner ska arbeta?'],
		['Y11_Q12a', 'Jag har kommit hem från arbetet för trött för att utföra hushållssysslor.'],
		['Y11_Q12b', 'Jag har haft svårt att uppfylla mitt ansvar mot familjen på grund av mina arbetstider. '],
		['Y11_Q12c', 'Jag har haft svårt att koncentrera mig på arbetet på grund av ansvaret gentemot familjen.'],
		['Y11_Q13a', 'Jag kan arbeta flextid.'],
		['Y11_Q13b', 'Jag kan ackumulera timmar för kompledighet.'],
		['Y11_Q13c', 'Jag kan ta ledigt en dag med kort varsel om det behövs. '],
		['Y11_Q15', 'Hur sannolikt är det att du ska förlora jobbet under de kommande sex månaderna?'],
		['Y11_Q16', 'Om du blev arbetslös, hur sannolikt är det att du hittar ett jobb med samma lön?'],
		['Y11_Q36a', 'Hur ofta passar du dina barn eller barnbarn?'],
		['Y11_Q36b', 'Hur ofta lagar du mat eller utför andra hushållsgöromål?'],
		['Y11_Q36c', 'Hur ofta vårdar du gamla eller funktionshindrade släktingar?'],
		['Y11_Q38', 'Attityd när det gäller att dela på hushållsarbetet.'],
		['Y11_Q39a', 'Attityd när det gäller att tillbringa tid med familjen.'],
		['Y11_Q39b', 'Attityd när det gäller social samvaro.'],
		['Y11_Q39c', 'Attityd när det gäller tid för hobbyer och intressen.'],
		['Y11_Q39d_stress', 'Stress.'],
		['Y11_Q33a', 'Direktkontakt med barn som flyttat hemifrån.'],
		['Y11_Q33b', 'Direktkontakt med mor eller far som inte ingår i hushållet.'],
		['Y11_Q33c', 'Direktkontakt med andra släktingar som inte ingår i hushållet.'],
		['Y11_Q33d', 'Direktkontakt med vänner eller grannar.'],
		['Y11_Q34a', 'Kontakt med barn som flyttat hemifrån via telefon, internet eller brev.'],
		['Y11_Q34b', 'Kontakt med mor eller far som inte ingår i hushållet via telefon, internet eller brev.'],
		['Y11_Q34c', 'Kontakt med andra släktingar som inte ingår i hushållet via telefon, internet eller brev.'],
		['Y11_Q34d', 'Kontakt med vänner eller grannar via telefon, internet eller brev.'],
		['Y11_Q35a', 'Vem skulle hjälpa dig om du är sjuk och behöver hjälp i hemmet?'],
		['Y11_Q35b', 'Vem skulle ge dig stöd om du behövde råd i en viktig fråga som gäller dig själv eller familjen?'],
		['Y11_Q35c', 'Vem skulle ge dig stöd om du behöver hjälp med att söka arbete?'],
		['Y11_Q35d', 'Vem skulle ge dig stöd om du kände dig lite deprimerad?'],
		['Y11_Q35e', 'Vem skulle du få hjälp av om du snabbt behövde 1 000 euro?'],
		['Y11_Accommproblems', 'Antal problem med bostad'],
		['Y11_Q18', 'Bostaden'],
		['Y11_Q19a', 'Problem med bostaden: brist på utrymme.'],
		['Y11_Q19b', 'Problem med bostaden: röta i fönster, dörrar eller golv.'],
		['Y11_Q19c', 'Problem med bostaden: fukt eller läckage i väggar eller tak.'],
		['Y11_Q19d', 'Problem med bostaden: inget wc inomhus.'],
		['Y11_Q19e', 'Problem med bostaden: inget badkar eller dusch.'],
		['Y11_Q19f', 'Problem med bostaden: ingen plats att sitta utomhus.'],
		['Y11_Q20', 'Hur troligt är det att du kommer att behöva lämna din bostad inom de närmaste sex månaderna eftersom du inte har råd att bo kvar?'],
		['Y11_Q50a', 'Problem med buller i grannskapet.'],
		['Y11_Q50b', 'Problem med luftkvalitet i grannskapet.'],
		['Y11_Q50c', 'Problem med dricksvattnets kvalitet i grannskapet.'],
		['Y11_Q50d', 'Problem med brottslighet, våld eller vandalism i grannskapet.'],
		['Y11_Q50e', 'Problem med avfall eller skräp på gatan.'],
		['Y11_Q50f', 'Problem med trafikstockningar i grannskapet.'],
		['Y11_Q51a', 'Tillgång till posttjänster.'],
		['Y11_Q51b', 'Tillgång till banktjänster.'],
		['Y11_Q51c', 'Tillgång till offentliga transporter.'],
		['Y11_Q51d', 'Tillgång till biograf, teater eller kulturcentrum.'],
		['Y11_Q51e', 'Tillgång till rekreations- eller grönområden.'],
		['Y11_Q52', 'Tid för att ta sig till eller från arbete eller studier.'],
		['Y11_Q42', 'Upplevd hälsostatus'],
		['Y11_Q46a', 'Jag har varit mycket orolig.'],
		['Y11_Q46b', 'Jag har känt mig ensam.'],
		['Y11_Q46c', 'Jag har känt mig nedslagen och deprimerad.'],
		['Y11_Q46d_WHO5', 'WHO-5, skalan över psykisk hälsa'],
		['Y11_Q47a', 'Svårt att besöka läkare på grund av avståndet.'],
		['Y11_Q47b', 'Svårt att besöka läkare på grund av svårigheter med att boka tid.'],
		['Y11_Q47c', 'Svårt att besöka läkare på grund av långa väntetider på mottagningen den bokade tiden.'],
		['Y11_Q47d', 'Svårt att besöka läkare på grund av kostnaden.'],
		['Y11_Q47e', 'Svårt att besöka läkare på grund av tidsbrist.'],
		['Y11_Q53a', 'Hur skulle du bedöma kvaliteten på hälso- och sjukvården i ditt land?'],
		['Y11_Q53b', 'Hur skulle du bedöma kvaliteten på utbildningssystemet i ditt land?'],
		['Y11_Q53c', 'Hur skulle du bedöma kvaliteten på de offentliga transporterna i ditt land?'],
		['Y11_Q53d', 'Hur skulle du bedöma kvaliteten på barnomsorgen i ditt land?'],
		['Y11_Q53e', 'Hur skulle du bedöma kvaliteten på långtidsvården i ditt land?'],
		['Y11_Q53f', 'Hur skulle du bedöma kvaliteten på de allmännyttiga bostäderna i ditt land?'],
		['Y11_Q53g', 'Hur skulle du bedöma kvaliteten på det statliga pensionssystemet i ditt land?'],
		['Y11_Deprindex', 'Eftersatthetsindex: Antal saker hushållen inte har råd med'],
		['Y11_Q57', 'Hushållets finansiella situation jämfört med de flesta i landet.'],
		['Y11_Q58', 'Kan ditt hushåll klara av att betala sina utgifter?'],
		['Y11_Q59a', 'Har du råd att hålla bostaden tillräckligt varm?'],
		['Y11_Q59b', 'Har du råd att resa på en veckas semester?'],
		['Y11_Q59c', 'Har du råd att ersätta utslitna möbler?'],
		['Y11_Q59d', 'Skulle du ha råd att äta kött, kyckling eller fisk varannan dag (om du vill)?'],
		['Y11_Q59e', 'Har du råd att köpa nya i stället för begagnade kläder?'],
		['Y11_Q59f', 'Har du råd att bjuda in vänner eller familj på en drink eller måltid minst en gång i månaden?'],
		['Y11_Q60a', 'Har ditt hushåll legat efter med hyran eller avbetalningar på bostadslån under de senaste tolv månaderna?'],
		['Y11_Q60b', 'Har ditt hushåll legat efter med att betala räkningar för vatten, el etc. under de senaste tolv månaderna?'],
		['Y11_Q60c', 'Har ditt hushåll legat efter med avbetalningar på konsumtionslån under de senaste tolv månaderna?'],
		['Y11_Q60d', 'Har ditt hushåll legat efter med betalningar på personliga lån under de senaste tolv månaderna?'],
		['Y11_Q65', 'Hushållets finansiella situation jämfört med för tolv månader sedan'],
		['Y11_Q66', 'Förväntad finansiell situation under den kommande tolvmånadersperioden'],
		['Y11_Q24', 'Anser du att man kan lita på de flesta människor eller att man aldrig kan vara nog försiktig i kontakten med andra?'],
		['Y11_Q25a', 'Upplevd spänning mellan fattiga och rika.'],
		['Y11_Q25b', 'Upplevd spänning mellan chefer och anställda.'],
		['Y11_Q25c', 'Upplevd spänning mellan män och kvinnor.'],
		['Y11_Q25d', 'Upplevd spänning mellan gamla och unga.'],
		['Y11_Q25e', 'Upplevd spänning mellan olika raser och etniska grupper.'],
		['Y11_Q25f', 'Upplevd spänning mellan olika religiösa grupper.'],
		['Y11_Q25g', 'Upplevd spänning mellan personer med olika sexuell läggning.'],
		['Y11_Q28a', 'Förtroende för parlamentet.'],
		['Y11_Q28b', 'Förtroende för rättssystemet.'],
		['Y11_Q28c', 'Förtroende för pressen.'],
		['Y11_Q28d', 'Förtroende för polisen.'],
		['Y11_Q28e', 'Förtroende för regeringen.'],
		['Y11_Q28f', 'Förtroende för lokala eller kommunala myndigheter.'],
		['Y11_Q21a', 'Deltagande i religiösa ceremonier, förutom bröllop, begravningar och dop.'],
		['Y11_Q21b', 'Användning av internet utanför arbetet.'],
		['Y11_Q21c', 'Deltagande i idrott eller fysisk träning.'],
		['Y11_Q21d', 'Deltagande i social verksamhet i en klubb, förening eller liknande.'],
		['Y11_Q22_Volunteering', 'Hur ofta utförde du ideellt arbete under de senaste tolv månaderna?'],
		['Y11_Q23a', 'Deltog i ett möte med fackförening, politiskt parti eller opinionsgrupp under de senaste tolv månaderna.'],
		['Y11_Q23b', 'Deltog i protest eller demonstration under de senaste tolv månaderna.'],
		['Y11_Q23c', 'Skrev på ett upprop under de senaste tolv månaderna.'],
		['Y11_Q23d', 'Kontaktade politiker eller offentlig tjänsteman (förutom rutinkontakt genom offentlig förvaltning).'],
		['Y11_Q29e', 'Jag känner mig utestängd från samhället.'],
		['Y11_Q29f', 'Livet har blivit så komplicerat i dag att jag inte vet hur jag ska göra.'],
		['Y11_Q29g', 'Jag upplever att andra inte uppskattar det jag gör.'],
		['Y11_Q29h', 'Vissa människor ser ner på mig på grund av mitt arbete eller inkomst.'],
		['Y11_Q29i', 'Jag känner samhörighet med människorna där jag bor.'],
		['Y11_SocExIndex', 'Index för socialt utanförskap'],
		['Y11_Q29a', 'Jag är optimistisk inför framtiden.'],
		['Y11_Q29b', 'Jag upplever i regel att det jag gör är meningsfullt.'],
		['Y11_Q29c', 'Jag upplever att jag är fri att besluta om hur jag ska leva.'],
		['Y11_Q29d', 'I mitt dagliga liv har jag sällan tid att göra sådant jag verkligen tycker om.'],
		['Y11_Q30', 'Hur tillfredsställd är du med ditt liv nuförtiden?'],
		['Y11_Q40a', 'Tillfredsställelse med utbildning'],
		['Y11_Q40b', 'Tillfredsställelse med nuvarande arbete'],
		['Y11_Q40c', 'Tillfredsställelse med nuvarande levnadsstandard'],
		['Y11_Q40d', 'Tillfredsställelse med bostad'],
		['Y11_Q40e', 'Tillfredsställelse med familjeliv'],
		['Y11_Q40f', 'Tillfredsställelse med hälsa'],
		['Y11_Q40g', 'Tillfredsställelse med umgänge'],
		['Y11_Q40h', 'Tillfredsställelse med landets ekonomiska situation'],
		['Y11_Q41', 'Om du sammanfattar allt detta, hur lycklig anser du att du är?']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Medelvärde'],
		['Y11_Deprindex', 'Mean', 'Medelvärde'],
		['Y11_Q10_Partnerprefhours', '1--Work-less', 'Arbeta mindre'],
		['Y11_Q10_Partnerprefhours', '2--Work-the-same', 'Arbeta lika mycket'],
		['Y11_Q10_Partnerprefhours', '3--Work-more', 'Arbeta mer'],
		['Y11_Q12a', '1--Several-times-a-week', 'Flera gånger i veckan'],
		['Y11_Q12a', '2--Several-times-a-month', 'Flera gånger i månaden'],
		['Y11_Q12a', '3--Several-times-a-year', 'Flera gånger om året'],
		['Y11_Q12a', '4--Less-often-rarely', 'Mindre ofta eller sällan'],
		['Y11_Q12a', '5--Never', 'Aldrig'],
		['Y11_Q12b', '1--Several-times-a-week', 'Flera gånger i veckan'],
		['Y11_Q12b', '2--Several-times-a-month', 'Flera gånger i månaden'],
		['Y11_Q12b', '3--Several-times-a-year', 'Flera gånger om året'],
		['Y11_Q12b', '4--Less-often-rarely', 'Mindre ofta eller sällan'],
		['Y11_Q12b', '5--Never', 'Aldrig'],
		['Y11_Q12c', '1--Several-times-a-week', 'Flera gånger i veckan'],
		['Y11_Q12c', '2--Several-times-a-month', 'Flera gånger i månaden'],
		['Y11_Q12c', '3--Several-times-a-year', 'Flera gånger om året'],
		['Y11_Q12c', '4--Less-often-rarely', 'Mindre ofta eller sällan'],
		['Y11_Q12c', '5--Never', 'Aldrig'],
		['Y11_Q13a', '1--Yes', 'Ja'],
		['Y11_Q13a', '2--No', 'Nej'],
		['Y11_Q13b', '1--Yes', 'Ja'],
		['Y11_Q13b', '2--No', 'Nej'],
		['Y11_Q13c', '1--Yes', 'Ja'],
		['Y11_Q13c', '2--No', 'Nej'],
		['Y11_Q15', '1--Very-likely', 'Mycket sannolikt'],
		['Y11_Q15', '2--Quite-likely', 'Ganska sannolikt'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Varken sannolikt eller osannolikt'],
		['Y11_Q15', '4--Quite-unlikely', 'Ganska osannolikt'],
		['Y11_Q15', '5--Very-unlikely', 'Mycket osannolikt'],
		['Y11_Q16', '1--Very-likely', 'Mycket sannolikt'],
		['Y11_Q16', '2--Quite-likely', 'Ganska sannolikt'],
		['Y11_Q16', '3--Neither-likely-nor-unlikely', 'Varken sannolikt eller osannolikt'],
		['Y11_Q16', '4--Quite-unlikely', 'Ganska osannolikt'],
		['Y11_Q16', '5--Very-unlikely', 'Mycket osannolikt'],
		['Y11_Q18', '1--Own-without-mortgage', 'Äger utan lån'],
		['Y11_Q18', '2--Own-with-mortgage', 'Äger med lån'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Hyresgäst, betalar hyra till subventionerad, frivillig eller kommunal bostad'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Hyresgäst, betalar hyra till privat hyresvärd'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Bostaden hyresfri'],
		['Y11_Q18', '6--Other', 'Övrigt'],
		['Y11_Q19a', '1--Yes', 'Ja'],
		['Y11_Q19a', '2--No', 'Nej'],
		['Y11_Q19b', '1--Yes', 'Ja'],
		['Y11_Q19b', '2--No', 'Nej'],
		['Y11_Q19c', '1--Yes', 'Ja'],
		['Y11_Q19c', '2--No', 'Nej'],
		['Y11_Q19d', '1--Yes', 'Ja'],
		['Y11_Q19d', '2--No', 'Nej'],
		['Y11_Q19e', '1--Yes', 'Ja'],
		['Y11_Q19e', '2--No', 'Nej'],
		['Y11_Q19f', '1--Yes', 'Ja'],
		['Y11_Q19f', '2--No', 'Nej'],
		['Y11_Q20', '1--Very-likely', 'Mycket sannolikt'],
		['Y11_Q20', '2--Quite-likely', 'Ganska sannolikt'],
		['Y11_Q20', '3--Quite-unlikely', 'Ganska osannolikt'],
		['Y11_Q20', '4--Very-unlikely', 'Mycket osannolikt'],
		['Y11_Q21a', '1--Every-day-or-almost-every-day', 'Varje dag eller nästan varje dag'],
		['Y11_Q21a', '2--At-least-once-a-week', 'Minst en gång i veckan'],
		['Y11_Q21a', '3--One-to-three-times-a-month', 'En till tre gånger i månaden'],
		['Y11_Q21a', '4--Less-often', 'Mindre ofta'],
		['Y11_Q21a', '5--Never', 'Aldrig'],
		['Y11_Q21b', '1--Every-day-or-almost-every-day', 'Varje dag eller nästan varje dag'],
		['Y11_Q21b', '2--At-least-once-a-week', 'Minst en gång i veckan'],
		['Y11_Q21b', '3--One-to-three-times-a-month', 'En till tre gånger i månaden'],
		['Y11_Q21b', '4--Less-often', 'Mindre ofta'],
		['Y11_Q21b', '5--Never', 'Aldrig'],
		['Y11_Q21c', '1--Every-day-or-almost-every-day', 'Varje dag eller nästan varje dag'],
		['Y11_Q21c', '2--At-least-once-a-week', 'Minst en gång i veckan'],
		['Y11_Q21c', '3--One-to-three-times-a-month', 'En till tre gånger i månaden'],
		['Y11_Q21c', '4--Less-often', 'Mindre ofta'],
		['Y11_Q21c', '5--Never', 'Aldrig'],
		['Y11_Q21d', '1--Every-day-or-almost-every-day', 'Varje dag eller nästan varje dag'],
		['Y11_Q21d', '2--At-least-once-a-week', 'Minst en gång i veckan'],
		['Y11_Q21d', '3--One-to-three-times-a-month', 'En till tre gånger i månaden'],
		['Y11_Q21d', '4--Less-often', 'Mindre ofta'],
		['Y11_Q21d', '5--Never', 'Aldrig'],
		['Y11_Q22_Volunteering', '1--Volunteers-regularly', 'Arbetar frivilligt regelbundet'],
		['Y11_Q22_Volunteering', '2--Volunteers-occasionally', 'Arbetar frivilligt ibland'],
		['Y11_Q22_Volunteering', '3--Does-not-volunteer', 'Arbetar aldrig frivilligt'],
		['Y11_Q23a', '1--Yes', 'Ja'],
		['Y11_Q23a', '2--No', 'Nej'],
		['Y11_Q23b', '1--Yes', 'Ja'],
		['Y11_Q23b', '2--No', 'Nej'],
		['Y11_Q23c', '1--Yes', 'Ja'],
		['Y11_Q23c', '2--No', 'Nej'],
		['Y11_Q23d', '1--Yes', 'Ja'],
		['Y11_Q23d', '2--No', 'Nej'],
		['Y11_Q24', 'Mean', 'Genomsnittligt'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Mycket spänning'],
		['Y11_Q25a', '2--Some-tension', 'Viss spänning'],
		['Y11_Q25a', '3--No-tension', 'Ingen spänning'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Mycket spänning'],
		['Y11_Q25b', '2--Some-tension', 'Viss spänning'],
		['Y11_Q25b', '3--No-tension', 'Ingen spänning'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Mycket spänning'],
		['Y11_Q25c', '2--Some-tension', 'Viss spänning'],
		['Y11_Q25c', '3--No-tension', 'Ingen spänning'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Mycket spänning'],
		['Y11_Q25d', '2--Some-tension', 'Viss spänning'],
		['Y11_Q25d', '3--No-tension', 'Ingen spänning'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Mycket spänning'],
		['Y11_Q25e', '2--Some-tension', 'Viss spänning'],
		['Y11_Q25e', '3--No-tension', 'Ingen spänning'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Mycket spänning'],
		['Y11_Q25f', '2--Some-tension', 'Viss spänning'],
		['Y11_Q25f', '3--No-tension', 'Ingen spänning'],
		['Y11_Q25g', '1--A-lot-of--tension', 'Mycket spänning'],
		['Y11_Q25g', '2--Some-tension', 'Viss spänning'],
		['Y11_Q25g', '3--No-tension', 'Ingen spänning'],
		['Y11_Q28a', 'Mean', 'Genomsnittligt'],
		['Y11_Q28b', 'Mean', 'Genomsnittligt'],
		['Y11_Q28c', 'Mean', 'Genomsnittligt'],
		['Y11_Q28d', 'Mean', 'Genomsnittligt'],
		['Y11_Q28e', 'Mean', 'Genomsnittligt'],
		['Y11_Q28f', 'Mean', 'Genomsnittligt'],
		['Y11_Q29a', '1--Strongly-agree', 'Instämmer helt'],
		['Y11_Q29a', '2--Agree', 'Instämmer'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Varken instämmer eller instämmer inte'],
		['Y11_Q29a', '4--Disagree', 'Instämmer inte'],
		['Y11_Q29a', '5--Strongly-disagree', 'Instämmer inte alls'],
		['Y11_Q29b', '1--Strongly-agree', 'Instämmer helt'],
		['Y11_Q29b', '2--Agree', 'Instämmer'],
		['Y11_Q29b', '3--Neither-agree-nor-disagree', 'Varken instämmer eller instämmer inte'],
		['Y11_Q29b', '4--Disagree', 'Instämmer inte'],
		['Y11_Q29b', '5--Strongly-disagree', 'Instämmer inte alls'],
		['Y11_Q29c', '1--Strongly-agree', 'Instämmer helt'],
		['Y11_Q29c', '2--Agree', 'Instämmer'],
		['Y11_Q29c', '3--Neither-agree-nor-disagree', 'Varken instämmer eller instämmer inte'],
		['Y11_Q29c', '4--Disagree', 'Instämmer inte'],
		['Y11_Q29c', '5--Strongly-disagree', 'Instämmer inte alls'],
		['Y11_Q29d', '1--Strongly-agree', 'Instämmer helt'],
		['Y11_Q29d', '2--Agree', 'Instämmer'],
		['Y11_Q29d', '3--Neither-agree-nor-disagree', 'Varken instämmer eller instämmer inte'],
		['Y11_Q29d', '4--Disagree', 'Instämmer inte'],
		['Y11_Q29d', '5--Strongly-disagree', 'Instämmer inte alls'],
		['Y11_Q29e', '1--Strongly-agree', 'Instämmer helt'],
		['Y11_Q29e', '2--Agree', 'Instämmer'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Varken instämmer eller instämmer inte'],
		['Y11_Q29e', '4--Disagree', 'Instämmer inte'],
		['Y11_Q29e', '5--Strongly-disagree', 'Instämmer inte alls'],
		['Y11_Q29f', '1--Strongly-agree', 'Instämmer helt'],
		['Y11_Q29f', '2--Agree', 'Instämmer'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Varken instämmer eller instämmer inte'],
		['Y11_Q29f', '4--Disagree', 'Instämmer inte'],
		['Y11_Q29f', '5--Strongly-disagree', 'Instämmer inte alls'],
		['Y11_Q29g', '1--Strongly-agree', 'Instämmer helt'],
		['Y11_Q29g', '2--Agree', 'Instämmer'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Varken instämmer eller instämmer inte'],
		['Y11_Q29g', '4--Disagree', 'Instämmer inte'],
		['Y11_Q29g', '5--Strongly-disagree', 'Instämmer inte alls'],
		['Y11_Q29h', '1--Strongly-agree', 'Instämmer helt'],
		['Y11_Q29h', '2--Agree', 'Instämmer'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Varken instämmer eller instämmer inte'],
		['Y11_Q29h', '4--Disagree', 'Instämmer inte'],
		['Y11_Q29h', '5--Strongly-disagree', 'Instämmer inte alls'],
		['Y11_Q29i', '1--Strongly-agree', 'Instämmer helt'],
		['Y11_Q29i', '2--Agree', 'Instämmer'],
		['Y11_Q29i', '3--Neither-agree-nor-disagree', 'Varken instämmer eller instämmer inte'],
		['Y11_Q29i', '4--Disagree', 'Instämmer inte'],
		['Y11_Q29i', '5--Strongly-disagree', 'Instämmer inte alls'],
		['Y11_Q30', 'Mean', 'Genomsnittligt'],
		['Y11_Q33a', '1--Every-day-or-almost-every-day', 'Varje dag eller nästan varje dag'],
		['Y11_Q33a', '2--At-least-once-a-week', 'Minst en gång i veckan'],
		['Y11_Q33a', '3--One-to-three-times-a-month', 'En till tre gånger i månaden'],
		['Y11_Q33a', '4--Less-often', 'Mindre ofta'],
		['Y11_Q33a', '5--Never', 'Aldrig'],
		['Y11_Q33b', '1--Every-day-or-almost-every-day', 'Varje dag eller nästan varje dag'],
		['Y11_Q33b', '2--At-least-once-a-week', 'Minst en gång i veckan'],
		['Y11_Q33b', '3--One-to-three-times-a-month', 'En till tre gånger i månaden'],
		['Y11_Q33b', '4--Less-often', 'Mindre ofta'],
		['Y11_Q33b', '5--Never', 'Aldrig'],
		['Y11_Q33c', '1--Every-day-or-almost-every-day', 'Varje dag eller nästan varje dag'],
		['Y11_Q33c', '2--At-least-once-a-week', 'Minst en gång i veckan'],
		['Y11_Q33c', '3--One-to-three-times-a-month', 'En till tre gånger i månaden'],
		['Y11_Q33c', '4--Less-often', 'Mindre ofta'],
		['Y11_Q33c', '5--Never', 'Aldrig'],
		['Y11_Q33d', '1--Every-day-or-almost-every-day', 'Varje dag eller nästan varje dag'],
		['Y11_Q33d', '2--At-least-once-a-week', 'Minst en gång i veckan'],
		['Y11_Q33d', '3--One-to-three-times-a-month', 'En till tre gånger i månaden'],
		['Y11_Q33d', '4--Less-often', 'Mindre ofta'],
		['Y11_Q33d', '5--Never', 'Aldrig'],
		['Y11_Q34a', '1--Every-day-or-almost-every-day', 'Varje dag eller nästan varje dag'],
		['Y11_Q34a', '2--At-least-once-a-week', 'Minst en gång i veckan'],
		['Y11_Q34a', '3--One-to-three-times-a-month', 'En till tre gånger i månaden'],
		['Y11_Q34a', '4--Less-often', 'Mindre ofta'],
		['Y11_Q34a', '5--Never', 'Aldrig'],
		['Y11_Q34b', '1--Every-day-or-almost-every-day', 'Varje dag eller nästan varje dag'],
		['Y11_Q34b', '2--At-least-once-a-week', 'Minst en gång i veckan'],
		['Y11_Q34b', '3--One-to-three-times-a-month', 'En till tre gånger i månaden'],
		['Y11_Q34b', '4--Less-often', 'Mindre ofta'],
		['Y11_Q34b', '5--Never', 'Aldrig'],
		['Y11_Q34c', '1--Every-day-or-almost-every-day', 'Varje dag eller nästan varje dag'],
		['Y11_Q34c', '2--At-least-once-a-week', 'Minst en gång i veckan'],
		['Y11_Q34c', '3--One-to-three-times-a-month', 'En till tre gånger i månaden'],
		['Y11_Q34c', '4--Less-often', 'Mindre ofta'],
		['Y11_Q34c', '5--Never', 'Aldrig'],
		['Y11_Q34d', '1--Every-day-or-almost-every-day', 'Varje dag eller nästan varje dag'],
		['Y11_Q34d', '2--At-least-once-a-week', 'Minst en gång i veckan'],
		['Y11_Q34d', '3--One-to-three-times-a-month', 'En till tre gånger i månaden'],
		['Y11_Q34d', '4--Less-often', 'Mindre ofta'],
		['Y11_Q34d', '5--Never', 'Aldrig'],
		['Y11_Q35a', '1--A-member-of-your-family', 'En familjemedlem'],
		['Y11_Q35a', '2--A-friend--neighbour--or-someone-else', 'En vän, granne eller någon annan'],
		['Y11_Q35a', '3--A-service-provider--institution-or-organisation', 'En tjänsteleverantör, institution eller organisation'],
		['Y11_Q35a', '4--Nobody', 'Ingen'],
		['Y11_Q35b', '1--A-member-of-your-family', 'En familjemedlem'],
		['Y11_Q35b', '2--A-friend--neighbour--or-someone-else', 'En vän, granne eller någon annan'],
		['Y11_Q35b', '3--A-service-provider--institution-or-organisation', 'En tjänsteleverantör, institution eller organisation'],
		['Y11_Q35b', '4--Nobody', 'Ingen'],
		['Y11_Q35c', '1--A-member-of-your-family', 'En familjemedlem'],
		['Y11_Q35c', '2--A-friend--neighbour--or-someone-else', 'En vän, granne eller någon annan'],
		['Y11_Q35c', '3--A-service-provider--institution-or-organisation', 'En tjänsteleverantör, institution eller organisation'],
		['Y11_Q35c', '4--Nobody', 'Ingen'],
		['Y11_Q35d', '1--A-member-of-your-family', 'En familjemedlem'],
		['Y11_Q35d', '2--A-friend--neighbour--or-someone-else', 'En vän, granne eller någon annan'],
		['Y11_Q35d', '3--A-service-provider--institution-or-organisation', 'En tjänsteleverantör, institution eller organisation'],
		['Y11_Q35d', '4--Nobody', 'Ingen'],
		['Y11_Q35e', '1--A-member-of-your-family', 'En familjemedlem'],
		['Y11_Q35e', '2--A-friend--neighbour--or-someone-else', 'En vän, granne eller någon annan'],
		['Y11_Q35e', '3--A-service-provider--institution-or-organisation', 'En tjänsteleverantör, institution eller organisation'],
		['Y11_Q35e', '4--Nobody', 'Ingen'],
		['Y11_Q36a', '1--Every-day', 'Varje dag'],
		['Y11_Q36a', '2--Several-days-a-week', 'Flera dagar i veckan'],
		['Y11_Q36a', '3--Once-or-twice-a-week', 'En eller två gånger i veckan'],
		['Y11_Q36a', '4--Less-often', 'Mindre ofta'],
		['Y11_Q36a', '5--Never', 'Aldrig'],
		['Y11_Q36b', '1--Every-day', 'Varje dag'],
		['Y11_Q36b', '2--Several-days-a-week', 'Flera dagar i veckan'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'En eller två gånger i veckan'],
		['Y11_Q36b', '4--Less-often', 'Mindre ofta'],
		['Y11_Q36b', '5--Never', 'Aldrig'],
		['Y11_Q36c', '1--Every-day', 'Varje dag'],
		['Y11_Q36c', '2--Several-days-a-week', 'Flera dagar i veckan'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'En eller två gånger i veckan'],
		['Y11_Q36c', '4--Less-often', 'Mindre ofta'],
		['Y11_Q36c', '5--Never', 'Aldrig'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Mer än din skäliga andel'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Ungefär din skäliga andel'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Mindre än din skäliga andel'],
		['Y11_Q39a', '1--Spend-more-time', 'Tillbringa mer tid'],
		['Y11_Q39a', '2--As-much-as-I-currently-do', 'Lika mycket som nu'],
		['Y11_Q39a', '3--Spend-less-time', 'Tillbringa mindre tid'],
		['Y11_Q39b', '1--Spend-more-time', 'Tillbringa mer tid'],
		['Y11_Q39b', '2--As-much-as-I-currently-do', 'Lika mycket som nu'],
		['Y11_Q39b', '3--Spend-less-time', 'Tillbringa mindre tid'],
		['Y11_Q39c', '1--Spend-more-time', 'Tillbringa mer tid'],
		['Y11_Q39c', '2--As-much-as-I-currently-do', 'Lika mycket som nu'],
		['Y11_Q39c', '3--Spend-less-time', 'Tillbringa mindre tid'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'På arbetet och hemma'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Varken på arbetet eller hemma'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Lite eller ingen stress'],
		['Y11_Q40a', 'Mean', 'Genomsnittligt'],
		['Y11_Q40b', 'Mean', 'Genomsnittligt'],
		['Y11_Q40c', 'Mean', 'Genomsnittligt'],
		['Y11_Q40d', 'Mean', 'Genomsnittligt'],
		['Y11_Q40e', 'Mean', 'Genomsnittligt'],
		['Y11_Q40f', 'Mean', 'Genomsnittligt'],
		['Y11_Q40g', 'Mean', 'Genomsnittligt'],
		['Y11_Q40h', 'Mean', 'Genomsnittligt'],
		['Y11_Q41', 'Mean', 'Genomsnittligt'],
		['Y11_Q42', '1--Very-good', 'Mycket bra'],
		['Y11_Q42', '2--Good', 'Bra'],
		['Y11_Q42', '3--Fair', 'Ganska bra'],
		['Y11_Q42', '4--Bad', 'Dålig'],
		['Y11_Q42', '5--Very-bad', 'Mycket dålig'],
		['Y11_Q46a', '1--All-of-the-time', 'Hela tiden'],
		['Y11_Q46a', '2--Most-of-the-time', 'Det mesta av tiden'],
		['Y11_Q46a', '3--More-than-half-of-the-time', 'Mer än halva tiden'],
		['Y11_Q46a', '4--Less-than-half-of-the-time', 'Mindre än halva tiden'],
		['Y11_Q46a', '5--Some-of-the-time', 'Viss tid'],
		['Y11_Q46a', '6--At-no-time', 'Aldrig'],
		['Y11_Q46b', '1--All-of-the-time', 'Hela tiden'],
		['Y11_Q46b', '2--Most-of-the-time', 'Det mesta av tiden'],
		['Y11_Q46b', '3--More-than-half-of-the-time', 'Mer än halva tiden'],
		['Y11_Q46b', '4--Less-than-half-of-the-time', 'Mindre än halva tiden'],
		['Y11_Q46b', '5--Some-of-the-time', 'Viss tid'],
		['Y11_Q46b', '6--At-no-time', 'Aldrig'],
		['Y11_Q46c', '1--All-of-the-time', 'Hela tiden'],
		['Y11_Q46c', '2--Most-of-the-time', 'Det mesta av tiden'],
		['Y11_Q46c', '3--More-than-half-of-the-time', 'Mer än halva tiden'],
		['Y11_Q46c', '4--Less-than-half-of-the-time', 'Mindre än halva tiden'],
		['Y11_Q46c', '5--Some-of-the-time', 'Viss tid'],
		['Y11_Q46c', '6--At-no-time', 'Aldrig'],
		['Y11_Q46d_WHO5', 'Mean', 'Genomsnittligt'],
		['Y11_Q47a', '1--Very-difficult', 'Mycket svårt'],
		['Y11_Q47a', '2--A-little-difficult', 'Ganska svårt'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Inte alls svårt'],
		['Y11_Q47b', '1--Very-difficult', 'Mycket svårt'],
		['Y11_Q47b', '2--A-little-difficult', 'Ganska svårt'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Inte alls svårt'],
		['Y11_Q47c', '1--Very-difficult', 'Mycket svårt'],
		['Y11_Q47c', '2--A-little-difficult', 'Ganska svårt'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Inte alls svårt'],
		['Y11_Q47d', '1--Very-difficult', 'Mycket svårt'],
		['Y11_Q47d', '2--A-little-difficult', 'Ganska svårt'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Inte alls svårt'],
		['Y11_Q47e', '1--Very-difficult', 'Mycket svårt'],
		['Y11_Q47e', '2--A-little-difficult', 'Ganska svårt'],
		['Y11_Q47e', '3--Not-difficult-at-all', 'Inte alls svårt'],
		['Y11_Q50a', '1--Major-problems', 'Stora problem'],
		['Y11_Q50a', '2--Moderate-problems', 'Vissa problem'],
		['Y11_Q50a', '3--No-problems', 'Inga problem'],
		['Y11_Q50b', '1--Major-problems', 'Stora problem'],
		['Y11_Q50b', '2--Moderate-problems', 'Vissa problem'],
		['Y11_Q50b', '3--No-problems', 'Inga problem'],
		['Y11_Q50c', '1--Major-problems', 'Stora problem'],
		['Y11_Q50c', '2--Moderate-problems', 'Vissa problem'],
		['Y11_Q50c', '3--No-problems', 'Inga problem'],
		['Y11_Q50d', '1--Major-problems', 'Stora problem'],
		['Y11_Q50d', '2--Moderate-problems', 'Vissa problem'],
		['Y11_Q50d', '3--No-problems', 'Inga problem'],
		['Y11_Q50e', '1--Major-problems', 'Stora problem'],
		['Y11_Q50e', '2--Moderate-problems', 'Vissa problem'],
		['Y11_Q50e', '3--No-problems', 'Inga problem'],
		['Y11_Q50f', '1--Major-problems', 'Stora problem'],
		['Y11_Q50f', '2--Moderate-problems', 'Vissa problem'],
		['Y11_Q50f', '3--No-problems', 'Inga problem'],
		['Y11_Q51a', '1--with-great-difficulty', 'Med stor svårighet'],
		['Y11_Q51a', '2--with-some-difficulty', 'Med viss svårighet'],
		['Y11_Q51a', '3--easily', 'Lätt'],
		['Y11_Q51a', '4--very-easily', 'Mycket lätt'],
		['Y11_Q51b', '1--with-great-difficulty', 'Med stor svårighet'],
		['Y11_Q51b', '2--with-some-difficulty', 'Med viss svårighet'],
		['Y11_Q51b', '3--easily', 'Lätt'],
		['Y11_Q51b', '4--very-easily', 'Mycket lätt'],
		['Y11_Q51c', '1--with-great-difficulty', 'Med stor svårighet'],
		['Y11_Q51c', '2--with-some-difficulty', 'Med viss svårighet'],
		['Y11_Q51c', '3--easily', 'Lätt'],
		['Y11_Q51c', '4--very-easily', 'Mycket lätt'],
		['Y11_Q51d', '1--with-great-difficulty', 'Med stor svårighet'],
		['Y11_Q51d', '2--with-some-difficulty', 'Med viss svårighet'],
		['Y11_Q51d', '3--easily', 'Lätt'],
		['Y11_Q51d', '4--very-easily', 'Mycket lätt'],
		['Y11_Q51e', '1--with-great-difficulty', 'Med stor svårighet'],
		['Y11_Q51e', '2--with-some-difficulty', 'Med viss svårighet'],
		['Y11_Q51e', '3--easily', 'Lätt'],
		['Y11_Q51e', '4--very-easily', 'Mycket lätt'],
		['Y11_Q52', 'Mean', 'Genomsnittligt'],
		['Y11_Q53a', 'Mean', 'Genomsnittligt'],
		['Y11_Q53b', 'Mean', 'Genomsnittligt'],
		['Y11_Q53c', 'Mean', 'Genomsnittligt'],
		['Y11_Q53d', 'Mean', 'Genomsnittligt'],
		['Y11_Q53e', 'Mean', 'Genomsnittligt'],
		['Y11_Q53f', 'Mean', 'Genomsnittligt'],
		['Y11_Q53g', 'Mean', 'Genomsnittligt'],
		['Y11_Q57', '1--Much-worse', 'Mycket värre'],
		['Y11_Q57', '2--Somewhat-worse', 'Något värre'],
		['Y11_Q57', '3--Neither-worse-nor-better', 'Varken värre eller bättre'],
		['Y11_Q57', '4--Somewhat-better', 'Lite bättre'],
		['Y11_Q57', '5--Much-better', 'Mycket bättre'],
		['Y11_Q58', '1--With-great-difficulty', 'Med stor svårighet'],
		['Y11_Q58', '2--With-difficulty', 'Med svårighet'],
		['Y11_Q58', '3--With-some-difficulty', 'Med viss svårighet'],
		['Y11_Q58', '4--Fairly-easily', 'Ganska lätt'],
		['Y11_Q58', '5--Easily', 'Lätt'],
		['Y11_Q58', '6--Very-easily', 'Mycket lätt'],
		['Y11_Q59a', '1--No', 'Nej'],
		['Y11_Q59a', '2--Yes', 'Ja'],
		['Y11_Q59b', '1--No', 'Nej'],
		['Y11_Q59b', '2--Yes', 'Ja'],
		['Y11_Q59c', '1--No', 'Nej'],
		['Y11_Q59c', '2--Yes', 'Ja'],
		['Y11_Q59d', '1--No', 'Nej'],
		['Y11_Q59d', '2--Yes', 'Ja'],
		['Y11_Q59e', '1--No', 'Nej'],
		['Y11_Q59e', '2--Yes', 'Ja'],
		['Y11_Q59f', '1--No', 'Nej'],
		['Y11_Q59f', '2--Yes', 'Ja'],
		['Y11_Q60a', '1--Yes', 'Ja'],
		['Y11_Q60a', '2--No', 'Nej'],
		['Y11_Q60b', '1--Yes', 'Ja'],
		['Y11_Q60b', '2--No', 'Nej'],
		['Y11_Q60c', '1--Yes', 'Ja'],
		['Y11_Q60c', '2--No', 'Nej'],
		['Y11_Q60d', '1--Yes', 'Ja'],
		['Y11_Q60d', '2--No', 'Nej'],
		['Y11_Q65', '1--Better', 'Bättre'],
		['Y11_Q65', '2--The-same', 'Samma'],
		['Y11_Q65', '3--Worse', 'Sämre'],
		['Y11_Q66', '1--Better', 'Bättre'],
		['Y11_Q66', '2--The-same', 'Samma'],
		['Y11_Q66', '3--Worse', 'Sämre'],
		['Y11_Q8_PreferredWorkingHours', '1--Work-less', 'Arbeta mindre'],
		['Y11_Q8_PreferredWorkingHours', '2--Work-the-same', 'Arbeta lika mycket'],
		['Y11_Q8_PreferredWorkingHours', '3--Work-more', 'Arbeta mer'],
		['Y11_SocExIndex', 'Mean', 'Medelvärde']
	];
var country_
	 = [
	
		['AT', 'Österrike'],
		['BE', 'Belgien'],
		['BG', 'Bulgarien'],
		['CY', 'Cypern'],
		['CZ', 'Tjeckien'],
		['DE', 'Tyskland'],
		['DK', 'Danmark'],
		['EE', 'Estland'],
		['EL', 'Grekland'],
		['ES', 'Spanien'],
		['FI', 'Finland'],
		['FR', 'Frankrike'],
		['HR', 'Kroatien'],
		['HU', 'Ungern'],
		['IE', 'Irland'],
		['IS', 'Island'],
		['IT', 'Italien'],
		['LT', 'Litauen'],
		['LU', 'Luxemburg'],
		['LV', 'Lettland'],
		['ME', 'Montenegro'],
		['MK', 'Fyrom'],
		['MT', 'Malta'],
		['NL', 'Nederländerna'],
		['PL', 'Polen'],
		['PT', 'Portugal'],
		['RO', 'Rumänien'],
		['RS', 'Serbien'],
		['SE', 'Sverige'],
		['SI', 'Slovenien'],
		['SK', 'Slovakien'],
		['TR', 'Turkiet'],
		['UK', 'Storbritannien'],
		['XK', 'Kosovo'],
		['EuropeanUnion', 'Europeiska unionen']
	];
var question_meta
	 = [
	
		['Y11_Q8_PreferredWorkingHours', 'Hur många timmar i veckan vill du själv arbeta?', ''],
		['Y11_Q10_Partnerprefhours', 'Hur många timmar i veckan vill du att din partner ska arbeta?', 'Frågan ställdes till de svarande som hade en partner bosatt i hushållet.'],
		['Y11_Q12a', 'Jag har kommit hem från arbetet för trött för att utföra hushållssysslor.', ''],
		['Y11_Q12b', 'Jag har haft svårt att uppfylla mitt ansvar mot familjen på grund av mina arbetstider. ', ''],
		['Y11_Q12c', 'Jag har haft svårt att koncentrera mig på arbetet på grund av ansvaret gentemot familjen.', ''],
		['Y11_Q13a', 'Jag kan arbeta flextid.', ''],
		['Y11_Q13b', 'Jag kan ackumulera timmar för kompledighet.', ''],
		['Y11_Q13c', 'Jag kan ta ledigt en dag med kort varsel om det behövs. ', ''],
		['Y11_Q15', 'Hur sannolikt är det att du ska förlora jobbet under de kommande sex månaderna?', ''],
		['Y11_Q16', 'Om du blev arbetslös, hur sannolikt är det att du hittar ett jobb med samma lön?', 'Frågan ställdes till de svarande som hade en betald anställning.'],
		['Y11_Q36a', 'Hur ofta passar du dina barn eller barnbarn?', ''],
		['Y11_Q36b', 'Hur ofta lagar du mat eller utför andra hushållsgöromål?', ''],
		['Y11_Q36c', 'Hur ofta vårdar du gamla eller funktionshindrade släktingar?', ''],
		['Y11_Q38', 'Vad anser du om den del av hushållsarbetet som du utför?', ''],
		['Y11_Q39a', 'Attityd när det gäller tiden i kontakt med familjemedlemmar.', ''],
		['Y11_Q39b', 'Attityd när det gäller tiden som tillbringas med annan social samvaro.', ''],
		['Y11_Q39c', 'Attityd när det gäller tid för hobbyer och intressen.', ''],
		['Y11_Q39d_stress', 'Stress på grund av bristande balans arbete-fritid.', ''],
		['Y11_Q33a', 'Direktkontakt med barn som flyttat hemifrån.', ''],
		['Y11_Q33b', 'Direktkontakt med mor eller far som inte ingår i hushållet.', ''],
		['Y11_Q33c', 'Direktkontakt med broder, syster eller andra släktingar som inte ingår i hushållet.', ''],
		['Y11_Q33d', 'Direktkontakt med vänner eller grannar som inte ingår i hushållet.', ''],
		['Y11_Q34a', 'Kontakt med barn som flyttat hemifrån via telefon, internet eller brev.', ''],
		['Y11_Q34b', 'Kontakt med mor eller far som inte ingår i hushållet via telefon, internet eller brev.', ''],
		['Y11_Q34c', 'Kontakt med andra broder, syster eller andra släktingar som inte ingår i hushållet via telefon, internet eller brev.', ''],
		['Y11_Q34d', 'Kontakt med vänner eller grannar som inte ingår i hushållet via telefon, internet eller brev.', ''],
		['Y11_Q35a', 'Vem skulle hjälpa dig om du är sjuk och behöver hjälp i hemmet?', ''],
		['Y11_Q35b', 'Vem skulle ge dig stöd om du behövde råd i en viktig fråga som gäller dig själv eller familjen?', ''],
		['Y11_Q35c', 'Vem skulle ge dig stöd om du behöver hjälp med att söka arbete?', ''],
		['Y11_Q35d', 'Vem skulle ge dig stöd om du kände dig lite deprimerad och behövde någon att tala med?', ''],
		['Y11_Q35e', 'Vem skulle du få hjälp av om du snabbt behövde 1 000 euro i en nödsituation?', ''],
		['Y11_Accommproblems', 'Antal problem med bostad', ''],
		['Y11_Q18', 'Bostaden', ''],
		['Y11_Q19a', 'Problem med bostaden: brist på utrymme.', ''],
		['Y11_Q19b', 'Problem med bostaden: röta i fönster, dörrar eller golv.', ''],
		['Y11_Q19c', 'Problem med bostaden: fukt eller läckage i väggar eller tak.', ''],
		['Y11_Q19d', 'Problem med bostaden: inget wc inomhus.', ''],
		['Y11_Q19e', 'Problem med bostaden: inget badkar eller dusch.', ''],
		['Y11_Q19f', 'Problem med bostaden: ingen plats att sitta utomhus.', ''],
		['Y11_Q20', 'Hur troligt är det att du kommer att behöva lämna din bostad inom de närmaste sex månaderna eftersom du inte har råd att bo kvar?', ''],
		['Y11_Q50a', 'Problem med buller i grannskapet.', ''],
		['Y11_Q50b', 'Problem med luftkvalitet i grannskapet.', ''],
		['Y11_Q50c', 'Problem med dricksvattnets kvalitet i grannskapet.', ''],
		['Y11_Q50d', 'Problem med brottslighet, våld eller vandalism i grannskapet.', ''],
		['Y11_Q50e', 'Problem med avfall eller skräp på gatan i grannskapet.', ''],
		['Y11_Q50f', 'Problem med trafikstockningar i grannskapet.', ''],
		['Y11_Q51a', 'Tillgång till posttjänster.', ''],
		['Y11_Q51b', 'Tillgång till banktjänster.', ''],
		['Y11_Q51c', 'Tillgång till offentliga transporter.', ''],
		['Y11_Q51d', 'Tillgång till biograf, teater eller kulturcentrum.', ''],
		['Y11_Q51e', 'Tillgång till rekreations- eller grönområden.', ''],
		['Y11_Q52', 'Tid för att ta sig till eller från arbete eller studier.', ''],
		['Y11_Q42', 'Upplevd hälsostatus', ''],
		['Y11_Q46a', 'Jag har varit mycket orolig.', ''],
		['Y11_Q46b', 'Jag har känt mig ensam.', ''],
		['Y11_Q46c', 'Jag har känt mig nedslagen och deprimerad.', ''],
		['Y11_Q46d_WHO5', 'WHO-5, skalan över psykisk hälsa', ''],
		['Y11_Q47a', 'Svårt att besöka läkare på grund av avståndet till läkarens mottagning eller sjukhuset.', ''],
		['Y11_Q47b', 'Svårt att besöka läkare på grund av svårigheter med att boka tid.', ''],
		['Y11_Q47c', 'Svårt att besöka läkare på grund av långa väntetider innan man får träffa läkaren den bokade tiden.', ''],
		['Y11_Q47d', 'Svårt att besöka läkare på grund av kostnaden för att träffa en läkare.', ''],
		['Y11_Q47e', 'Svårt att besöka läkare på grund av tidsbrist på grund av arbete eller vårdskyldigheter.', ''],
		['Y11_Q53a', 'Hur skulle du bedöma kvaliteten på hälso- och sjukvården i ditt land?', ''],
		['Y11_Q53b', 'Hur skulle du bedöma kvaliteten på utbildningssystemet i ditt land?', ''],
		['Y11_Q53c', 'Hur skulle du bedöma kvaliteten på de offentliga transporterna i ditt land?', ''],
		['Y11_Q53d', 'Hur skulle du bedöma kvaliteten på barnomsorgen i ditt land?', ''],
		['Y11_Q53e', 'Hur skulle du bedöma kvaliteten på långtidsvården i ditt land?', ''],
		['Y11_Q53f', 'Hur skulle du bedöma kvaliteten på de allmännyttiga bostäderna i ditt land?', ''],
		['Y11_Q53g', 'Hur skulle du bedöma kvaliteten på det statliga pensionssystemet i ditt land?', ''],
		['Y11_Deprindex', 'Eftersatthetsindex: Antal saker hushållen inte har råd med', ''],
		['Y11_Q57', 'Hushållets finansiella situation jämfört med de flesta i landet.', ''],
		['Y11_Q58', 'Kan ditt hushåll klara av att betala sina utgifter?', ''],
		['Y11_Q59a', 'Har du råd att hålla bostaden tillräckligt varm?', ''],
		['Y11_Q59b', 'Har du råd att resa på en veckas semester?', ''],
		['Y11_Q59c', 'Har du råd att ersätta utslitna möbler?', ''],
		['Y11_Q59d', 'Har ditt hushåll råd att äta kött, kyckling eller fisk varannan dag (om ni skulle vilja)?', ''],
		['Y11_Q59e', 'Har medlemmarna i hushållet råd att köpa nya i stället för begagnade kläder?', ''],
		['Y11_Q59f', 'Har ditt hushåll råd att bjuda in vänner eller familj på en drink eller måltid minst en gång i månaden?', ''],
		['Y11_Q60a', 'Har ditt hushåll legat efter med hyran eller avbetalningar på bostadslån under de senaste tolv månaderna?', ''],
		['Y11_Q60b', 'Har ditt hushåll legat efter med att betala räkningar för vatten, el etc. under de senaste tolv månaderna?', ''],
		['Y11_Q60c', 'Har ditt hushåll legat efter med avbetalningar på konsumtionslån under de senaste tolv månaderna?', ''],
		['Y11_Q60d', 'Har ditt hushåll legat efter med betalningar på personliga lån under de senaste tolv månaderna?', ''],
		['Y11_Q65', 'Hushållets finansiella situation jämfört med för tolv månader sedan', ''],
		['Y11_Q66', 'Förväntad finansiell situation under den kommande tolvmånadersperioden', ''],
		['Y11_Q24', 'Anser du att man kan lita på de flesta människor eller att man aldrig kan vara nog försiktig i kontakten med andra?', ''],
		['Y11_Q25a', 'Upplevd spänning mellan fattiga och rika.', ''],
		['Y11_Q25b', 'Upplevd spänning mellan chefer och anställda.', ''],
		['Y11_Q25c', 'Upplevd spänning mellan män och kvinnor.', ''],
		['Y11_Q25d', 'Upplevd spänning mellan gamla och unga.', ''],
		['Y11_Q25e', 'Upplevd spänning mellan olika raser och etniska grupper.', ''],
		['Y11_Q25f', 'Upplevd spänning mellan olika religiösa grupper.', ''],
		['Y11_Q25g', 'Upplevd spänning mellan personer med olika sexuell läggning.', ''],
		['Y11_Q28a', 'Förtroende för parlamentet.', ''],
		['Y11_Q28b', 'Förtroende för rättssystemet.', ''],
		['Y11_Q28c', 'Förtroende för pressen.', ''],
		['Y11_Q28d', 'Förtroende för polisen.', ''],
		['Y11_Q28e', 'Förtroende för regeringen.', ''],
		['Y11_Q28f', 'Förtroende för lokala eller kommunala myndigheter.', ''],
		['Y11_Q21a', 'Deltagande i religiösa ceremonier, förutom bröllop, begravningar och dop.', ''],
		['Y11_Q21b', 'Användning av internet utanför arbetet.', ''],
		['Y11_Q21c', 'Deltagande i idrott eller fysisk träning.', ''],
		['Y11_Q21d', 'Deltagande i social verksamhet i en klubb, förening eller liknande.', ''],
		['Y11_Q22_Volunteering', 'Hur ofta utförde du ideellt arbete under de senaste tolv månaderna?', ''],
		['Y11_Q23a', 'Deltog i ett möte med fackförening, politiskt parti eller opinionsgrupp under de senaste tolv månaderna.', ''],
		['Y11_Q23b', 'Deltog i protest eller demonstration under de senaste tolv månaderna.', ''],
		['Y11_Q23c', 'Skrev på ett upprop (bl.a. via e-post eller online) under de senaste 12 månaderna.', ''],
		['Y11_Q23d', 'Kontaktade politiker eller offentlig tjänsteman (förutom rutinkontakt genom offentlig förvaltning).', ''],
		['Y11_Q29e', 'Jag känner mig utestängd från samhället.', ''],
		['Y11_Q29f', 'Livet har blivit så komplicerat i dag att jag inte vet hur jag ska göra.', ''],
		['Y11_Q29g', 'Jag upplever att andra inte uppskattar det jag gör.', ''],
		['Y11_Q29h', 'Vissa människor ser ner på mig på grund av mitt arbete eller inkomst.', ''],
		['Y11_Q29i', 'Jag känner samhörighet med människorna där jag bor.', ''],
		['Y11_SocExIndex', 'Index för socialt utanförskap', ''],
		['Y11_Q29a', 'Jag är optimistisk inför framtiden.', ''],
		['Y11_Q29b', 'Jag upplever i regel att det jag gör är meningsfullt.', ''],
		['Y11_Q29c', 'Jag upplever att jag är fri att besluta om hur jag ska leva.', ''],
		['Y11_Q29d', 'I mitt dagliga liv har jag sällan tid att göra sådant jag verkligen tycker om.', ''],
		['Y11_Q30', 'Hur tillfredsställd är du med ditt liv nuförtiden?', ''],
		['Y11_Q40a', 'Tillfredsställelse med utbildning', ''],
		['Y11_Q40b', 'Tillfredsställelse med nuvarande arbete', ''],
		['Y11_Q40c', 'Tillfredsställelse med nuvarande levnadsstandard', ''],
		['Y11_Q40d', 'Tillfredsställelse med bostad', ''],
		['Y11_Q40e', 'Tillfredsställelse med familjeliv', ''],
		['Y11_Q40f', 'Tillfredsställelse med hälsa', ''],
		['Y11_Q40g', 'Tillfredsställelse med umgänge', ''],
		['Y11_Q40h', 'Tillfredsställelse med landets ekonomiska situation', ''],
		['Y11_Q41', 'Om du sammanfattar allt detta, hur lycklig anser du att du är?', '']
	];
