//Auto Generated file
var subset_
	 = [
	
		['sector_sub', 'Secteur'],
		['est_size3', 'Taille de l’établissement']
	];
var subset_subsetValue
	 = [
	
		['est_size3', 'All', 'Tous'],
		['est_size3', '2--50-249', '50-249'],
		['est_size3', '3--250', '250'],
		['est_size3', '10-49', '10-49'],
		['sector_sub', 'All', 'Tous'],
		['sector_sub', '2--Industry', 'Industrie'],
		['sector_sub', '3--Services', 'Services']
	];
var topic_
	 = [
	
		['', 'Tous (30)'],
		['Aménagement du temps de travail', 'Aménagement du temps de travail (2)'],
		['Compétences et formation', 'Compétences et formation (2)'],
		['Dialogue social', 'Dialogue social (2)'],
		['Innovation', 'Innovation (4)'],
		['Organisation du travail', 'Organisation du travail (5)'],
		['Participation directe des employés', 'Participation directe des employés (7)'],
		['Représentation du personnel', 'Représentation du personnel (3)'],
		['Rémunération variable', 'Rémunération variable (5)']
	];
var topic_question
	 = [
	
		['Participation directe des employés', 'JADHOC', 'L’établissement recourt à la pratique des réunions de groupe temporaire, comité ou groupe de travail ad hoc pour impliquer les employés dans l’organisation du travail'],
		['Participation directe des employés', 'JDISSINF', 'L’établissement recourt à la pratique de la diffusion d’informations au moyen de bulletins d’information, site web, panneaux d’affichage, e-mails, etc pour impliquer les employés dans l’organisation du travail'],
		['Participation directe des employés', 'JREGMEE', 'L’établissement recourt à la pratique des réunions régulières entre les employés et le responsable direct pour impliquer les employés dans l’organisation du travail'],
		['Participation directe des employés', 'JSOMEDI', 'L’établissement recourt à la pratique des discussions avec les employés par le biais des réseaux sociaux ou sur des forums de discussion en ligne pour impliquer les employés dans l’organisation du travail'],
		['Participation directe des employés', 'JSTAFFME', 'L’établissement recourt à la pratique des réunions régulières du personnel ouvertes à tous les employés pour impliquer ceux-ci dans l’organisation du travail'],
		['Participation directe des employés', 'JSUGGS', 'L’établissement recourt à la pratique des boîtes à idées pour impliquer les employés dans l’organisation du travail'],
		['Participation directe des employés', 'JSURVEY', 'L’établissement recourt à la pratique des sondages auprès des employés pour impliquer ceux-ci dans l’organisation du travail'],
		['Représentation du personnel', 'designatime', 'Les représentants du personnel disposent d’un nombre défini et suffisant d’heures par semaine qu’ils peuvent consacrer à l’exécution de leurs missions dans ce rôle'],
		['Représentation du personnel', 'q14', 'Les représentants du personnel ont bénéficié d’une formation liée à leur rôle au cours des douze derniers mois'],
		['Représentation du personnel', 'q15', 'Les représentants du personnel ont accès à des financements pour bénéficier de conseils externes'],
		['Innovation', 'BINNOPROC', 'Des procédés nouveaux ou sensiblement modifiés ont été mis en place dans l’établissement depuis le début de l’année 2010'],
		['Innovation', 'BINNPRSE', 'Des produits ou services nouveaux ou sensiblement modifiés ont été introduits dans l’établissement depuis le début de l’année 2010'],
		['Innovation', 'binnmaco', 'Des méthodes nouvelles ou sensiblement améliorées de marketing ou pour communiquer sur les activités auprès du public ont été mises en place dans l’établissement depuis le début de l’année 2010'],
		['Innovation', 'binnoorg', 'Un changement organisationnel a été mis en place dans l’établissement depuis le début de l’année 2010'],
		['Compétences et formation', 'CONJOB_CONJOB_N_CONJOBPC', 'Pourcentage d’employés travaillant à des postes requérant au moins un an d’apprentissage pour que la personne soit compétente dans la réalisation de ses tâches'],
		['Compétences et formation', 'HTRAIN_HTRAIN_N_HTRAIPC', 'Pourcentage d’employés ayant suivi une formation sur leur temps de travail avec maintien de la rémunération'],
		['Dialogue social', 'AEMPORG', 'L’entreprise est membre d’une organisation patronale'],
		['Dialogue social', 'er_present', 'Structure officielle de la représentation du personnel présente dans l’établissement'],
		['Rémunération variable', 'HVBPRES', 'Rémunération au résultat disponible dans l’établissement pour au moins certains employés'],
		['Rémunération variable', 'HVPGRPE', 'Rémunération supplémentaire variable, liée aux performances d’une équipe, d’un groupe de travail ou d’un service, disponible dans l’établissement pour au moins certains employés'],
		['Rémunération variable', 'HVPINPER', 'Rémunération supplémentaire variable, liée aux performances individuelles à la suite d’une évaluation réalisée par la direction, disponible dans l’établissement pour au moins certains employés'],
		['Rémunération variable', 'HVPPRSH', 'Rémunération supplémentaire variable, liée aux résultats de l’entreprise ou de l’établissement (régime de participation aux bénéfices), disponible dans l’établissement pour au moins certains employés'],
		['Rémunération variable', 'HVPSHOW', 'Rémunération supplémentaire variable sous la forme d’un plan d’actionnariat proposé par l’entreprise, disponible dans l’établissement pour au moins certains employés'],
		['Organisation du travail', 'EEXTEMON', 'L’établissement réalise une veille sur les idées externes ou les développements technologiques externes pour des produits, des processus ou des services nouveaux ou améliorés'],
		['Organisation du travail', 'EINFSYS', 'L’établissement utilise des systèmes d’information pour minimiser les stocks ou les en-cours'],
		['Organisation du travail', 'ELELEDOC', 'Les employés de l’établissement documentent et gardent une trace de leurs bonnes pratiques de travail ou des enseignements tirés'],
		['Organisation du travail', 'FROTATE', 'Des employés de l’établissement effectuent des tâches en alternance avec d’autres employés'],
		['Organisation du travail', 'aut_team', 'Travail d’équipe au sein de l’établissement'],
		['Aménagement du temps de travail', 'HACCUOV', 'Les employés ont la possibilité de récupérer leurs heures supplémentaires en prenant des jours de congé'],
		['Aménagement du temps de travail', 'HFLEXI_HFLEXI_N_HFLEXIPC', 'Pourcentage d’employés dans l’établissement ayant la possibilité d’adapter les heures de début et de fin de leur journée de travail']
	];
var question_
	 = [
	
		['JADHOC', 'L’établissement recourt à la pratique des réunions de groupe temporaire, comité ou groupe de travail ad hoc pour impliquer les employés dans l’organisation du travail'],
		['JDISSINF', 'L’établissement recourt à la pratique de la diffusion d’informations au moyen de bulletins d’information, site web, panneaux d’affichage, e-mails, etc pour impliquer les employés dans l’organisation du travail'],
		['JREGMEE', 'L’établissement recourt à la pratique des réunions régulières entre les employés et le responsable direct pour impliquer les employés dans l’organisation du travail'],
		['JSOMEDI', 'L’établissement recourt à la pratique des discussions avec les employés par le biais des réseaux sociaux ou sur des forums de discussion en ligne pour impliquer les employés dans l’organisation du travail'],
		['JSTAFFME', 'L’établissement recourt à la pratique des réunions régulières du personnel ouvertes à tous les employés pour impliquer ceux-ci dans l’organisation du travail'],
		['JSUGGS', 'L’établissement recourt à la pratique des boîtes à idées pour impliquer les employés dans l’organisation du travail'],
		['JSURVEY', 'L’établissement recourt à la pratique des sondages auprès des employés pour impliquer ceux-ci dans l’organisation du travail'],
		['designatime', 'Les représentants du personnel disposent d’un nombre défini et suffisant d’heures par semaine qu’ils peuvent consacrer à l’exécution de leurs missions dans ce rôle'],
		['q14', 'Les représentants du personnel ont bénéficié d’une formation liée à leur rôle au cours des douze derniers mois'],
		['q15', 'Les représentants du personnel ont accès à des financements pour bénéficier de conseils externes'],
		['BINNOPROC', 'Des procédés nouveaux ou sensiblement modifiés ont été mis en place dans l’établissement depuis le début de l’année 2010'],
		['BINNPRSE', 'Des produits ou services nouveaux ou sensiblement modifiés ont été introduits dans l’établissement depuis le début de l’année 2010'],
		['binnmaco', 'Des méthodes nouvelles ou sensiblement améliorées de marketing ou pour communiquer sur les activités auprès du public ont été mises en place dans l’établissement depuis le début de l’année 2010'],
		['binnoorg', 'Un changement organisationnel a été mis en place dans l’établissement depuis le début de l’année 2010'],
		['CONJOB_CONJOB_N_CONJOBPC', 'Pourcentage d’employés travaillant à des postes requérant au moins un an d’apprentissage pour que la personne soit compétente dans la réalisation de ses tâches'],
		['HTRAIN_HTRAIN_N_HTRAIPC', 'Pourcentage d’employés ayant suivi une formation sur leur temps de travail avec maintien de la rémunération'],
		['AEMPORG', 'L’entreprise est membre d’une organisation patronale'],
		['er_present', 'Structure officielle de la représentation du personnel présente dans l’établissement'],
		['HVBPRES', 'Rémunération au résultat disponible dans l’établissement pour au moins certains employés'],
		['HVPGRPE', 'Rémunération supplémentaire variable, liée aux performances d’une équipe, d’un groupe de travail ou d’un service, disponible dans l’établissement pour au moins certains employés'],
		['HVPINPER', 'Rémunération supplémentaire variable, liée aux performances individuelles à la suite d’une évaluation réalisée par la direction, disponible dans l’établissement pour au moins certains employés'],
		['HVPPRSH', 'Rémunération supplémentaire variable, liée aux résultats de l’entreprise ou de l’établissement (régime de participation aux bénéfices), disponible dans l’établissement pour au moins certains employés'],
		['HVPSHOW', 'Rémunération supplémentaire variable sous la forme d’un plan d’actionnariat proposé par l’entreprise, disponible dans l’établissement pour au moins certains employés'],
		['EEXTEMON', 'L’établissement réalise une veille sur les idées externes ou les développements technologiques externes pour des produits, des processus ou des services nouveaux ou améliorés'],
		['EINFSYS', 'L’établissement utilise des systèmes d’information pour minimiser les stocks ou les en-cours'],
		['ELELEDOC', 'Les employés de l’établissement documentent et gardent une trace de leurs bonnes pratiques de travail ou des enseignements tirés'],
		['FROTATE', 'Des employés de l’établissement effectuent des tâches en alternance avec d’autres employés'],
		['aut_team', 'Travail d’équipe au sein de l’établissement'],
		['HACCUOV', 'Les employés ont la possibilité de récupérer leurs heures supplémentaires en prenant des jours de congé'],
		['HFLEXI_HFLEXI_N_HFLEXIPC', 'Pourcentage d’employés dans l’établissement ayant la possibilité d’adapter les heures de début et de fin de leur journée de travail']
	];
var question_answer
	 = [
	
		['AEMPORG', '1--Yes', 'Oui'],
		['AEMPORG', '2--No', 'Non'],
		['BINNOPROC', '1--Yes', 'Oui'],
		['BINNOPROC', '2--No', 'Non'],
		['BINNPRSE', '1--Yes', 'Oui'],
		['BINNPRSE', '2--No', 'Non'],
		['CONJOB_CONJOB_N_CONJOBPC', '1--80--or-more', '80 % ou plus'],
		['CONJOB_CONJOB_N_CONJOBPC', '2--60--to-79-', '60 % à 79 %'],
		['CONJOB_CONJOB_N_CONJOBPC', '3--40--to-59-', '40 % à 59 %'],
		['CONJOB_CONJOB_N_CONJOBPC', '4--20--to-39-', '20 % à 39 %'],
		['CONJOB_CONJOB_N_CONJOBPC', '5--Less-than-20-', 'Moins de 20 %'],
		['EEXTEMON', '1--Yes--using-staff-assigned-specifically-to-this-task', 'Oui, à l’aide de membres du personnel affectés spécifiquement à cette tâche'],
		['EEXTEMON', '2--Yes--as-part-of-the-responsibilities-of-general-staff', 'Oui, c’est l’une des responsabilités de l’équipe générale'],
		['EEXTEMON', '3--No', 'Non'],
		['EINFSYS', '1--Yes', 'Oui'],
		['EINFSYS', '2--No', 'Non'],
		['ELELEDOC', '1--Yes', 'Oui'],
		['ELELEDOC', '2--No', 'Non'],
		['FROTATE', '1--No', 'Non'],
		['FROTATE', '2--Yes--some-do', 'Oui, pour certains'],
		['FROTATE', '3--Yes--most-do', 'Oui, pour la plupart'],
		['HACCUOV', '1--Possible-for-all', 'Possible pour tous'],
		['HACCUOV', '2--Possible-for-some', 'Possible pour certains'],
		['HACCUOV', '3--Not-possible', 'Impossible'],
		['HFLEXI_HFLEXI_N_HFLEXIPC', '1--80--or-more', '80 % ou plus'],
		['HFLEXI_HFLEXI_N_HFLEXIPC', '2--60--to-79-', '60 % à 79 %'],
		['HFLEXI_HFLEXI_N_HFLEXIPC', '3--40--to-59-', '40 % à 59 %'],
		['HFLEXI_HFLEXI_N_HFLEXIPC', '4--20--to-39-', '20 % à 39 %'],
		['HFLEXI_HFLEXI_N_HFLEXIPC', '5--Less-than-20-', 'Moins de 20 %'],
		['HTRAIN_HTRAIN_N_HTRAIPC', '1--80--or-more', '80 % ou plus'],
		['HTRAIN_HTRAIN_N_HTRAIPC', '2--60--to-79-', '60 % à 79 %'],
		['HTRAIN_HTRAIN_N_HTRAIPC', '3--40--to-59-', '40 % à 59 %'],
		['HTRAIN_HTRAIN_N_HTRAIPC', '4--20--to-39-', '20 % à 39 %'],
		['HTRAIN_HTRAIN_N_HTRAIPC', '5--Less-than-20-', 'Moins de 20 %'],
		['HVBPRES', '1--Yes', 'Oui'],
		['HVBPRES', '2--No', 'Non'],
		['HVPGRPE', '1--Yes', 'Oui'],
		['HVPGRPE', '2--No', 'Non'],
		['HVPINPER', '1--Yes', 'Oui'],
		['HVPINPER', '2--No', 'Non'],
		['HVPPRSH', '1--Yes', 'Oui'],
		['HVPPRSH', '2--No', 'Non'],
		['HVPSHOW', '1--Yes', 'Oui'],
		['HVPSHOW', '2--No', 'Non'],
		['JADHOC', '1--Yes', 'Oui'],
		['JADHOC', '2--No', 'Non'],
		['JDISSINF', '1--Yes', 'Oui'],
		['JDISSINF', '2--No', 'Non'],
		['JREGMEE', '1--Yes', 'Oui'],
		['JREGMEE', '2--No', 'Non'],
		['JSOMEDI', '1--Yes', 'Oui'],
		['JSOMEDI', '2--No', 'Non'],
		['JSTAFFME', '1--Yes', 'Oui'],
		['JSTAFFME', '2--No', 'Non'],
		['JSUGGS', '1--Yes', 'Oui'],
		['JSUGGS', '2--No', 'Non'],
		['JSURVEY', '1--Yes', 'Oui'],
		['JSURVEY', '2--No', 'Non'],
		['aut_team', '1--Autonomous-teamwork', 'Travail en équipe autonome'],
		['aut_team', '2--Management-directed-teamwork', 'Travail en équipe supervisé par la direction'],
		['aut_team', '3--No-teamwork', 'Pas de travail en équipe'],
		['binnmaco', '1--Yes', 'Oui'],
		['binnmaco', '2--No', 'Non'],
		['binnoorg', '1--Yes', 'Oui'],
		['binnoorg', '2--No', 'Non'],
		['designatime', '1--Designated-and-sufficient', 'Alloué et suffisant'],
		['designatime', '2--Designated-but-not-sufficient', 'Alloué mais insuffisant'],
		['designatime', '3--Not-entitled-to-use-working-time', 'Non autorisé à utiliser le temps de travail'],
		['designatime', '4--Can-use-as-much-working-time-as-is-necessary', 'Possibilité d’utiliser autant d’heures du temps de travail que nécessaire'],
		['designatime', '5--Full-time', 'Temps plein'],
		['er_present', '1--Yes', 'Oui'],
		['er_present', '2--No', 'Non'],
		['q14', '1--Yes', 'Oui'],
		['q14', '2--No', 'Non'],
		['q15', '1--Yes', 'Oui'],
		['q15', '2--No', 'Non']
	];
var country_
	 = [
	
		['AT', 'Autriche'],
		['BE', 'Belgique'],
		['BG', 'Bulgarie'],
		['CY', 'Chypre'],
		['CZ', 'République tchèque'],
		['DE', 'Allemagne'],
		['DK', 'Danemark'],
		['EE', 'Estonie'],
		['EL', 'Grèce'],
		['ES', 'Espagne'],
		['FI', 'Finlande'],
		['FR', 'France'],
		['HR', 'Croatie'],
		['HU', 'Hongrie'],
		['IE', 'Irlande'],
		['IS', 'Islande'],
		['IT', 'Italie'],
		['LT', 'Lituanie'],
		['LU', 'Luxembourg'],
		['LV', 'Lettonie'],
		['ME', 'Monténégro'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malte'],
		['NL', 'Pays-Bas'],
		['PL', 'Pologne'],
		['PT', 'Portugal'],
		['RO', 'Roumanie'],
		['SE', 'Suède'],
		['SI', 'Slovénie'],
		['SK', 'Slovaquie'],
		['TR', 'Turquie'],
		['UK', 'Royaume-Uni'],
		['EuropeanUnion', 'Union européenne']
	];
var question_meta
	 = [
	
		['JADHOC', 'L’établissement recourt à la pratique des réunions de groupe temporaire, comité ou groupe de travail ad hoc pour impliquer les employés dans l’organisation du travail', ''],
		['JDISSINF', 'L’établissement recourt à la pratique de la diffusion d’informations au moyen de bulletins d’information, site web, panneaux d’affichage, e-mails, etc pour impliquer les employés dans l’organisation du travail', ''],
		['JREGMEE', 'L’établissement recourt à la pratique des réunions régulières entre les employés et le responsable direct pour impliquer les employés dans l’organisation du travail', ''],
		['JSOMEDI', 'L’établissement recourt à la pratique des discussions avec les employés par le biais des réseaux sociaux ou sur des forums de discussion en ligne pour impliquer les employés dans l’organisation du travail', ''],
		['JSTAFFME', 'L’établissement recourt à la pratique des réunions régulières du personnel ouvertes à tous les employés pour impliquer ceux-ci dans l’organisation du travail', ''],
		['JSUGGS', 'L’établissement recourt à la pratique des boîtes à idées pour impliquer les employés dans l’organisation du travail', ''],
		['JSURVEY', 'L’établissement recourt à la pratique des sondages auprès des employés pour impliquer ceux-ci dans l’organisation du travail', ''],
		['designatime', 'Les représentants du personnel disposent d’un nombre défini et suffisant d’heures par semaine qu’ils peuvent consacrer à l’exécution de leurs missions dans ce rôle', ''],
		['q14', 'Les représentants du personnel ont bénéficié d’une formation liée à leur rôle au cours des douze derniers mois', ''],
		['q15', 'Les représentants du personnel ont accès à des financements pour bénéficier de conseils externes', ''],
		['BINNOPROC', 'Des procédés nouveaux ou sensiblement modifiés ont été mis en place dans l’établissement depuis le début de l’année 2010', ''],
		['BINNPRSE', 'Des produits ou services nouveaux ou sensiblement modifiés ont été introduits dans l’établissement depuis le début de l’année 2010', ''],
		['binnmaco', 'Des méthodes nouvelles ou sensiblement améliorées de marketing ou pour communiquer sur les activités auprès du public ont été mises en place dans l’établissement depuis le début de l’année 2010', ''],
		['binnoorg', 'Un changement organisationnel a été mis en place dans l’établissement depuis le début de l’année 2010', ''],
		['CONJOB_CONJOB_N_CONJOBPC', 'Pourcentage d’employés travaillant à des postes requérant au moins un an d’apprentissage pour que la personne soit compétente dans la réalisation de ses tâches', ''],
		['HTRAIN_HTRAIN_N_HTRAIPC', 'Pourcentage d’employés ayant suivi une formation sur leur temps de travail avec maintien de la rémunération', ''],
		['AEMPORG', 'L’entreprise est membre d’une organisation patronale', ''],
		['er_present', 'Structure officielle de la représentation du personnel présente dans l’établissement', ''],
		['HVBPRES', 'Rémunération au résultat disponible dans l’établissement pour au moins certains employés', ''],
		['HVPGRPE', 'Rémunération supplémentaire variable, liée aux performances d’une équipe, d’un groupe de travail ou d’un service, disponible dans l’établissement pour au moins certains employés', ''],
		['HVPINPER', 'Rémunération supplémentaire variable, liée aux performances individuelles à la suite d’une évaluation réalisée par la direction, disponible dans l’établissement pour au moins certains employés', ''],
		['HVPPRSH', 'Rémunération supplémentaire variable, liée aux résultats de l’entreprise ou de l’établissement (régime de participation aux bénéfices), disponible dans l’établissement pour au moins certains employés', ''],
		['HVPSHOW', 'Rémunération supplémentaire variable sous la forme d’un plan d’actionnariat proposé par l’entreprise, disponible dans l’établissement pour au moins certains employés', ''],
		['EEXTEMON', 'L’établissement réalise une veille sur les idées externes ou les développements technologiques externes pour des produits, des processus ou des services nouveaux ou améliorés', ''],
		['EINFSYS', 'L’établissement utilise des systèmes d’information pour minimiser les stocks ou les en-cours', '* Par exemple, des systèmes de production au plus juste ou juste à temps, ou le principe des cinq zéros'],
		['ELELEDOC', 'Les employés de l’établissement documentent et gardent une trace de leurs bonnes pratiques de travail ou des enseignements tirés', ''],
		['FROTATE', 'Des employés de l’établissement effectuent des tâches en alternance avec d’autres employés', ''],
		['aut_team', 'Travail d’équipe au sein de l’établissement', ''],
		['HACCUOV', 'Les employés ont la possibilité de récupérer leurs heures supplémentaires en prenant des jours de congé', ''],
		['HFLEXI_HFLEXI_N_HFLEXIPC', 'Pourcentage d’employés dans l’établissement ayant la possibilité d’adapter les heures de début et de fin de leur journée de travail', '']
	];
