//Auto Generated file
var subset_
	 = [
	
		['sector_sub', 'Sektorius'],
		['est_size3', 'Įmonės dydis']
	];
var subset_subsetValue
	 = [
	
		['est_size3', 'All', 'Visi (-os)'],
		['est_size3', '2--50-249', '50-249'],
		['est_size3', '3--250', '250'],
		['est_size3', '10-49', '10-49'],
		['sector_sub', 'All', 'Visi (-os)'],
		['sector_sub', '2--Industry', 'Pramonės šaka'],
		['sector_sub', '3--Services', 'Paslaugos']
	];
var topic_
	 = [
	
		['', 'Visi (-os) (30)'],
		['Darbo laiko organizavimas', 'Darbo laiko organizavimas (2)'],
		['Darbo organizavimo procesas', 'Darbo organizavimo procesas (5)'],
		['Darbuotojų atstovavimas', 'Darbuotojų atstovavimas (3)'],
		['Inovacijos', 'Inovacijos (4)'],
		['Kintamoji darbo užmokesčio dalis', 'Kintamoji darbo užmokesčio dalis (5)'],
		['Socialinis dialogas', 'Socialinis dialogas (2)'],
		['Tiesioginis darbuotojų dalyvavimas', 'Tiesioginis darbuotojų dalyvavimas (7)'],
		['Įgūdžiai ir mokymai', 'Įgūdžiai ir mokymai (2)']
	];
var topic_question
	 = [
	
		['Tiesioginis darbuotojų dalyvavimas', 'JADHOC', 'Įmonė rengia laikinos grupės ar komiteto ar specialios (ad hoc) grupės susirinkimus, kad darbuotojai galėtų dalyvauti darbo organizavimo procese'],
		['Tiesioginis darbuotojų dalyvavimas', 'JDISSINF', 'Įmonė informacijos sklaidai naudoja naujienlaiškius, interneto tinklalapį, skelbimų lentas, elektroninius laiškus ir pan, kad darbuotojai galėtų dalyvauti darbo organizavimo procese'],
		['Tiesioginis darbuotojų dalyvavimas', 'JREGMEE', 'Įmonė rengia reguliarius darbuotojų ir jų tiesioginių vadovų susirinkimus, kad darbuotojai galėtų dalyvauti darbo organizavimo procese '],
		['Tiesioginis darbuotojų dalyvavimas', 'JSOMEDI', 'Įmonė, naudodamasi socialiniais tinklais arba forumais internete, rengia diskusijas, kad darbuotojai galėtų dalyvauti darbo organizavimo procese'],
		['Tiesioginis darbuotojų dalyvavimas', 'JSTAFFME', 'Įmonė rengia reguliarius visuotinius įmonės personalo susirinkimus, kad darbuotojai galėtų dalyvauti darbo organizavimo procese'],
		['Tiesioginis darbuotojų dalyvavimas', 'JSUGGS', 'Įmonė naudojasi pasiūlymų sistemomis, kad darbuotojai galėtų dalyvauti darbo organizavimo procese'],
		['Tiesioginis darbuotojų dalyvavimas', 'JSURVEY', 'Įmonė rengia darbuotojų apklausas, kad darbuotojai galėtų dalyvauti darbo organizavimo procese'],
		['Darbuotojų atstovavimas', 'designatime', 'Darbuotojų atstovui nustatomas pakankamas darbo valandų skaičius per savaitę, kad jis galėtų tinkamai atlikti darbuotojų atstovo pareigas'],
		['Darbuotojų atstovavimas', 'q14', 'Darbuotojų atstovas per pastaruosius 12 mėnesių dalyvavo mokymuose, susijusiuose su darbuotojų atstovo pareigomis'],
		['Darbuotojų atstovavimas', 'q15', 'Sprendžiant darbuotojų atstovavimo klausimus gali būti skiriamas finansavimas sumokėti išorės konsultantams '],
		['Inovacijos', 'BINNOPROC', 'Įmonėje nuo 2010 m pradžios buvo įdiegti nauji arba iš esmės pakeisti procesai'],
		['Inovacijos', 'BINNPRSE', 'Įmonėje nuo 2010 m pradžios buvo įdiegti nauji arba iš esmės pakeisti produktai ar paslaugos'],
		['Inovacijos', 'binnmaco', 'Įmonėje nuo 2010 m pradžios buvo įdiegti nauji arba iš esmės patobulinti rinkodaros arba visuomenės informavimo apie savo veiklą būdai'],
		['Inovacijos', 'binnoorg', 'Įmonėje nuo 2010 m pradžios atlikti organizaciniai pokyčiai'],
		['Įgūdžiai ir mokymai', 'CONJOB_CONJOB_N_CONJOBPC', 'Įmonėje dirbančių darbuotojų dalis procentais, kurie dirba darbą, kuriam reikia bent vienų metų mokymosi darbo vietoje, kad būtų įgyti reikiami įgūdžiai tam darbui atlikti'],
		['Įgūdžiai ir mokymai', 'HTRAIN_HTRAIN_N_HTRAIPC', 'Įmonėje dirbančių darbuotojų dalis procentais, kuriems buvo suteiktos apmokamos atostogos, kad jie galėtų dalyvauti mokymuose'],
		['Socialinis dialogas', 'AEMPORG', 'Kompanija yra darbdavių asociacijos narė'],
		['Socialinis dialogas', 'er_present', 'Įmonėje nustatyta oficiali darbuotojų atstovavimo struktūra'],
		['Kintamoji darbo užmokesčio dalis', 'HVBPRES', 'Kai kurie įmonės darbuotojai gali gauti darbo užmokestį pagal darbo rezultatus'],
		['Kintamoji darbo užmokesčio dalis', 'HVPGRPE', 'Kai kurie įmonės darbuotojai gali gauti kintamąją darbo užmokesčio dalį, kuri priklauso nuo komandos, darbo grupės ar padalinio veiklos rezultatų'],
		['Kintamoji darbo užmokesčio dalis', 'HVPINPER', 'Kai kurie įmonės darbuotojai gali gauti kintamąją darbo užmokesčio dalį, kuri priklauso nuo individualios veiklos rezultatų ir vadovybės įvertinimo'],
		['Kintamoji darbo užmokesčio dalis', 'HVPPRSH', 'Kai kurie įmonės darbuotojai gali gauti kintamąją darbo užmokesčio dalį, kuri priklauso nuo kompanijos ar įmonės veiklos rezultatų (pelno pasidalijimo schema)'],
		['Kintamoji darbo užmokesčio dalis', 'HVPSHOW', 'Kai kurie įmonės darbuotojai gali gauti kintamąją darbo užmokesčio dalį pagal akcijų nuosavybės schemos formą, pasiūlytą kompanijos'],
		['Darbo organizavimo procesas', 'EEXTEMON', 'Įmonė vykdo išorės idėjų arba technologinių naujovių, susijusių su naujais ar pakeistais produktais, procesais ar paslaugomis, stebėseną'],
		['Darbo organizavimo procesas', 'EINFSYS', 'Įmonė naudojasi informacinėmis sistemomis, kad kuo labiau sumažintų atsargų kiekį ar atvejus, kai darbai nepabaigiami'],
		['Darbo organizavimo procesas', 'ELELEDOC', 'Įmonės darbuotojai užrašo ir saugo geros savo darbo praktikos pavyzdžius ar kaupia įgytas žinias'],
		['Darbo organizavimo procesas', 'FROTATE', 'Įmonėje darbuotojai keičiasi užduotimis su kitais darbuotojais'],
		['Darbo organizavimo procesas', 'aut_team', 'Įmonėje vyksta komandinis darbas'],
		['Darbo laiko organizavimas', 'HACCUOV', 'Darbuotojai turi galimybę laisvadieniams panaudoti sukauptus viršvalandžius'],
		['Darbo laiko organizavimas', 'HFLEXI_HFLEXI_N_HFLEXIPC', 'Įmonės darbuotojų dalis procentais, kurie turi galimybę keisti įprastą darbo pradžios ir pabaigos laiką']
	];
var question_
	 = [
	
		['JADHOC', 'Įmonė rengia laikinos grupės ar komiteto ar specialios (ad hoc) grupės susirinkimus, kad darbuotojai galėtų dalyvauti darbo organizavimo procese'],
		['JDISSINF', 'Įmonė informacijos sklaidai naudoja naujienlaiškius, interneto tinklalapį, skelbimų lentas, elektroninius laiškus ir pan, kad darbuotojai galėtų dalyvauti darbo organizavimo procese'],
		['JREGMEE', 'Įmonė rengia reguliarius darbuotojų ir jų tiesioginių vadovų susirinkimus, kad darbuotojai galėtų dalyvauti darbo organizavimo procese '],
		['JSOMEDI', 'Įmonė, naudodamasi socialiniais tinklais arba forumais internete, rengia diskusijas, kad darbuotojai galėtų dalyvauti darbo organizavimo procese'],
		['JSTAFFME', 'Įmonė rengia reguliarius visuotinius įmonės personalo susirinkimus, kad darbuotojai galėtų dalyvauti darbo organizavimo procese'],
		['JSUGGS', 'Įmonė naudojasi pasiūlymų sistemomis, kad darbuotojai galėtų dalyvauti darbo organizavimo procese'],
		['JSURVEY', 'Įmonė rengia darbuotojų apklausas, kad darbuotojai galėtų dalyvauti darbo organizavimo procese'],
		['designatime', 'Darbuotojų atstovui nustatomas pakankamas darbo valandų skaičius per savaitę, kad jis galėtų tinkamai atlikti darbuotojų atstovo pareigas'],
		['q14', 'Darbuotojų atstovas per pastaruosius 12 mėnesių dalyvavo mokymuose, susijusiuose su darbuotojų atstovo pareigomis'],
		['q15', 'Sprendžiant darbuotojų atstovavimo klausimus gali būti skiriamas finansavimas sumokėti išorės konsultantams '],
		['BINNOPROC', 'Įmonėje nuo 2010 m pradžios buvo įdiegti nauji arba iš esmės pakeisti procesai'],
		['BINNPRSE', 'Įmonėje nuo 2010 m pradžios buvo įdiegti nauji arba iš esmės pakeisti produktai ar paslaugos'],
		['binnmaco', 'Įmonėje nuo 2010 m pradžios buvo įdiegti nauji arba iš esmės patobulinti rinkodaros arba visuomenės informavimo apie savo veiklą būdai'],
		['binnoorg', 'Įmonėje nuo 2010 m pradžios atlikti organizaciniai pokyčiai'],
		['CONJOB_CONJOB_N_CONJOBPC', 'Įmonėje dirbančių darbuotojų dalis procentais, kurie dirba darbą, kuriam reikia bent vienų metų mokymosi darbo vietoje, kad būtų įgyti reikiami įgūdžiai tam darbui atlikti'],
		['HTRAIN_HTRAIN_N_HTRAIPC', 'Įmonėje dirbančių darbuotojų dalis procentais, kuriems buvo suteiktos apmokamos atostogos, kad jie galėtų dalyvauti mokymuose'],
		['AEMPORG', 'Kompanija yra darbdavių asociacijos narė'],
		['er_present', 'Įmonėje nustatyta oficiali darbuotojų atstovavimo struktūra'],
		['HVBPRES', 'Kai kurie įmonės darbuotojai gali gauti darbo užmokestį pagal darbo rezultatus'],
		['HVPGRPE', 'Kai kurie įmonės darbuotojai gali gauti kintamąją darbo užmokesčio dalį, kuri priklauso nuo komandos, darbo grupės ar padalinio veiklos rezultatų'],
		['HVPINPER', 'Kai kurie įmonės darbuotojai gali gauti kintamąją darbo užmokesčio dalį, kuri priklauso nuo individualios veiklos rezultatų ir vadovybės įvertinimo'],
		['HVPPRSH', 'Kai kurie įmonės darbuotojai gali gauti kintamąją darbo užmokesčio dalį, kuri priklauso nuo kompanijos ar įmonės veiklos rezultatų (pelno pasidalijimo schema)'],
		['HVPSHOW', 'Kai kurie įmonės darbuotojai gali gauti kintamąją darbo užmokesčio dalį pagal akcijų nuosavybės schemos formą, pasiūlytą kompanijos'],
		['EEXTEMON', 'Įmonė vykdo išorės idėjų arba technologinių naujovių, susijusių su naujais ar pakeistais produktais, procesais ar paslaugomis, stebėseną'],
		['EINFSYS', 'Įmonė naudojasi informacinėmis sistemomis, kad kuo labiau sumažintų atsargų kiekį ar atvejus, kai darbai nepabaigiami'],
		['ELELEDOC', 'Įmonės darbuotojai užrašo ir saugo geros savo darbo praktikos pavyzdžius ar kaupia įgytas žinias'],
		['FROTATE', 'Įmonėje darbuotojai keičiasi užduotimis su kitais darbuotojais'],
		['aut_team', 'Įmonėje vyksta komandinis darbas'],
		['HACCUOV', 'Darbuotojai turi galimybę laisvadieniams panaudoti sukauptus viršvalandžius'],
		['HFLEXI_HFLEXI_N_HFLEXIPC', 'Įmonės darbuotojų dalis procentais, kurie turi galimybę keisti įprastą darbo pradžios ir pabaigos laiką']
	];
var question_answer
	 = [
	
		['AEMPORG', '1--Yes', 'Taip'],
		['AEMPORG', '2--No', 'Ne'],
		['BINNOPROC', '1--Yes', 'Taip'],
		['BINNOPROC', '2--No', 'Ne'],
		['BINNPRSE', '1--Yes', 'Taip'],
		['BINNPRSE', '2--No', 'Ne'],
		['CONJOB_CONJOB_N_CONJOBPC', '1--80--or-more', '80 % arba daugiau'],
		['CONJOB_CONJOB_N_CONJOBPC', '2--60--to-79-', '60 % – 79 %'],
		['CONJOB_CONJOB_N_CONJOBPC', '3--40--to-59-', '40 % – 59 %'],
		['CONJOB_CONJOB_N_CONJOBPC', '4--20--to-39-', '20 % – 39 %'],
		['CONJOB_CONJOB_N_CONJOBPC', '5--Less-than-20-', 'Mažiau negu 20%'],
		['EEXTEMON', '1--Yes--using-staff-assigned-specifically-to-this-task', 'Taip, skiriamas konkrečiai už tai atsakingas personalas '],
		['EEXTEMON', '2--Yes--as-part-of-the-responsibilities-of-general-staff', 'Taip, už tai atsakingas visas personalas '],
		['EEXTEMON', '3--No', 'Ne'],
		['EINFSYS', '1--Yes', 'Taip'],
		['EINFSYS', '2--No', 'Ne'],
		['ELELEDOC', '1--Yes', 'Taip'],
		['ELELEDOC', '2--No', 'Ne'],
		['FROTATE', '1--No', 'Ne'],
		['FROTATE', '2--Yes--some-do', 'Taip, kai kurie'],
		['FROTATE', '3--Yes--most-do', 'Taip, dauguma'],
		['HACCUOV', '1--Possible-for-all', 'Gali visi'],
		['HACCUOV', '2--Possible-for-some', 'Gali kai kurie'],
		['HACCUOV', '3--Not-possible', 'Negalima'],
		['HFLEXI_HFLEXI_N_HFLEXIPC', '1--80--or-more', '80 % arba daugiau'],
		['HFLEXI_HFLEXI_N_HFLEXIPC', '2--60--to-79-', '60 % – 79 %'],
		['HFLEXI_HFLEXI_N_HFLEXIPC', '3--40--to-59-', '40 % – 59 %'],
		['HFLEXI_HFLEXI_N_HFLEXIPC', '4--20--to-39-', '20 % – 39 %'],
		['HFLEXI_HFLEXI_N_HFLEXIPC', '5--Less-than-20-', 'Mažiau negu 20%'],
		['HTRAIN_HTRAIN_N_HTRAIPC', '1--80--or-more', '80 % arba daugiau'],
		['HTRAIN_HTRAIN_N_HTRAIPC', '2--60--to-79-', '60 % – 79 %'],
		['HTRAIN_HTRAIN_N_HTRAIPC', '3--40--to-59-', '40 % – 59 %'],
		['HTRAIN_HTRAIN_N_HTRAIPC', '4--20--to-39-', '20 % – 39 %'],
		['HTRAIN_HTRAIN_N_HTRAIPC', '5--Less-than-20-', 'Mažiau negu 20%'],
		['HVBPRES', '1--Yes', 'Taip'],
		['HVBPRES', '2--No', 'Ne'],
		['HVPGRPE', '1--Yes', 'Taip'],
		['HVPGRPE', '2--No', 'Ne'],
		['HVPINPER', '1--Yes', 'Taip'],
		['HVPINPER', '2--No', 'Ne'],
		['HVPPRSH', '1--Yes', 'Taip'],
		['HVPPRSH', '2--No', 'Ne'],
		['HVPSHOW', '1--Yes', 'Taip'],
		['HVPSHOW', '2--No', 'Ne'],
		['JADHOC', '1--Yes', 'Taip'],
		['JADHOC', '2--No', 'Ne'],
		['JDISSINF', '1--Yes', 'Taip'],
		['JDISSINF', '2--No', 'Ne'],
		['JREGMEE', '1--Yes', 'Taip'],
		['JREGMEE', '2--No', 'Ne'],
		['JSOMEDI', '1--Yes', 'Taip'],
		['JSOMEDI', '2--No', 'Ne'],
		['JSTAFFME', '1--Yes', 'Taip'],
		['JSTAFFME', '2--No', 'Ne'],
		['JSUGGS', '1--Yes', 'Taip'],
		['JSUGGS', '2--No', 'Ne'],
		['JSURVEY', '1--Yes', 'Taip'],
		['JSURVEY', '2--No', 'Ne'],
		['aut_team', '1--Autonomous-teamwork', 'Savarankiškas komandinis darbas'],
		['aut_team', '2--Management-directed-teamwork', 'Vadovybės prižiūrimas komandinis darbas'],
		['aut_team', '3--No-teamwork', 'Komandinio darbo nėra'],
		['binnmaco', '1--Yes', 'Taip'],
		['binnmaco', '2--No', 'Ne'],
		['binnoorg', '1--Yes', 'Taip'],
		['binnoorg', '2--No', 'Ne'],
		['designatime', '1--Designated-and-sufficient', 'Nustatytas ir pakankamas '],
		['designatime', '2--Designated-but-not-sufficient', 'Nustatytas, bet nepakankamas '],
		['designatime', '3--Not-entitled-to-use-working-time', 'Negali naudoti darbo laiko'],
		['designatime', '4--Can-use-as-much-working-time-as-is-necessary', 'Gali skirti tiek darbo laiko, kiek reikia'],
		['designatime', '5--Full-time', 'Visa darbo diena'],
		['er_present', '1--Yes', 'Taip'],
		['er_present', '2--No', 'Ne'],
		['q14', '1--Yes', 'Taip'],
		['q14', '2--No', 'Ne'],
		['q15', '1--Yes', 'Taip'],
		['q15', '2--No', 'Ne']
	];
var country_
	 = [
	
		['AT', 'Austrija'],
		['BE', 'Belgija'],
		['BG', 'Bulgarija'],
		['CY', 'Kipras'],
		['CZ', 'Čekija'],
		['DE', 'Vokietija'],
		['DK', 'Danija'],
		['EE', 'Estija'],
		['EL', 'Graikija'],
		['ES', 'Ispanija'],
		['FI', 'Suomija'],
		['FR', 'Prancūzija'],
		['HR', 'Kroatija'],
		['HU', 'Vengrija'],
		['IE', 'Airija'],
		['IS', 'Islandija'],
		['IT', 'Italija'],
		['LT', 'Lietuva'],
		['LU', 'Liuksemburgas'],
		['LV', 'Latvija'],
		['ME', 'Juodkalnija'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Nyderlandai'],
		['PL', 'Lenkija'],
		['PT', 'Portugalija'],
		['RO', 'Rumunija'],
		['SE', 'Švedija'],
		['SI', 'Slovėnija'],
		['SK', 'Slovakija'],
		['TR', 'Turkija'],
		['UK', 'Jungtinė Karalystė'],
		['EuropeanUnion', 'Europos Sąjunga']
	];
var question_meta
	 = [
	
		['JADHOC', 'Įmonė rengia laikinos grupės ar komiteto ar specialios (ad hoc) grupės susirinkimus, kad darbuotojai galėtų dalyvauti darbo organizavimo procese', ''],
		['JDISSINF', 'Įmonė informacijos sklaidai naudoja naujienlaiškius, interneto tinklalapį, skelbimų lentas, elektroninius laiškus ir pan, kad darbuotojai galėtų dalyvauti darbo organizavimo procese', ''],
		['JREGMEE', 'Įmonė rengia reguliarius darbuotojų ir jų tiesioginių vadovų susirinkimus, kad darbuotojai galėtų dalyvauti darbo organizavimo procese ', ''],
		['JSOMEDI', 'Įmonė, naudodamasi socialiniais tinklais arba forumais internete, rengia diskusijas, kad darbuotojai galėtų dalyvauti darbo organizavimo procese', ''],
		['JSTAFFME', 'Įmonė rengia reguliarius visuotinius įmonės personalo susirinkimus, kad darbuotojai galėtų dalyvauti darbo organizavimo procese', ''],
		['JSUGGS', 'Įmonė naudojasi pasiūlymų sistemomis, kad darbuotojai galėtų dalyvauti darbo organizavimo procese', ''],
		['JSURVEY', 'Įmonė rengia darbuotojų apklausas, kad darbuotojai galėtų dalyvauti darbo organizavimo procese', ''],
		['designatime', 'Darbuotojų atstovui nustatomas pakankamas darbo valandų skaičius per savaitę, kad jis galėtų tinkamai atlikti darbuotojų atstovo pareigas', ''],
		['q14', 'Darbuotojų atstovas per pastaruosius 12 mėnesių dalyvavo mokymuose, susijusiuose su darbuotojų atstovo pareigomis', ''],
		['q15', 'Sprendžiant darbuotojų atstovavimo klausimus gali būti skiriamas finansavimas sumokėti išorės konsultantams ', ''],
		['BINNOPROC', 'Įmonėje nuo 2010 m pradžios buvo įdiegti nauji arba iš esmės pakeisti procesai', ''],
		['BINNPRSE', 'Įmonėje nuo 2010 m pradžios buvo įdiegti nauji arba iš esmės pakeisti produktai ar paslaugos', ''],
		['binnmaco', 'Įmonėje nuo 2010 m pradžios buvo įdiegti nauji arba iš esmės patobulinti rinkodaros arba visuomenės informavimo apie savo veiklą būdai', ''],
		['binnoorg', 'Įmonėje nuo 2010 m pradžios atlikti organizaciniai pokyčiai', ''],
		['CONJOB_CONJOB_N_CONJOBPC', 'Įmonėje dirbančių darbuotojų dalis procentais, kurie dirba darbą, kuriam reikia bent vienų metų mokymosi darbo vietoje, kad būtų įgyti reikiami įgūdžiai tam darbui atlikti', ''],
		['HTRAIN_HTRAIN_N_HTRAIPC', 'Įmonėje dirbančių darbuotojų dalis procentais, kuriems buvo suteiktos apmokamos atostogos, kad jie galėtų dalyvauti mokymuose', ''],
		['AEMPORG', 'Kompanija yra darbdavių asociacijos narė', ''],
		['er_present', 'Įmonėje nustatyta oficiali darbuotojų atstovavimo struktūra', ''],
		['HVBPRES', 'Kai kurie įmonės darbuotojai gali gauti darbo užmokestį pagal darbo rezultatus', ''],
		['HVPGRPE', 'Kai kurie įmonės darbuotojai gali gauti kintamąją darbo užmokesčio dalį, kuri priklauso nuo komandos, darbo grupės ar padalinio veiklos rezultatų', ''],
		['HVPINPER', 'Kai kurie įmonės darbuotojai gali gauti kintamąją darbo užmokesčio dalį, kuri priklauso nuo individualios veiklos rezultatų ir vadovybės įvertinimo', ''],
		['HVPPRSH', 'Kai kurie įmonės darbuotojai gali gauti kintamąją darbo užmokesčio dalį, kuri priklauso nuo kompanijos ar įmonės veiklos rezultatų (pelno pasidalijimo schema)', ''],
		['HVPSHOW', 'Kai kurie įmonės darbuotojai gali gauti kintamąją darbo užmokesčio dalį pagal akcijų nuosavybės schemos formą, pasiūlytą kompanijos', ''],
		['EEXTEMON', 'Įmonė vykdo išorės idėjų arba technologinių naujovių, susijusių su naujais ar pakeistais produktais, procesais ar paslaugomis, stebėseną', ''],
		['EINFSYS', 'Įmonė naudojasi informacinėmis sistemomis, kad kuo labiau sumažintų atsargų kiekį ar atvejus, kai darbai nepabaigiami', '* Pavyzdžiui, griežto darbo grafiko laikymasis arba taupiosios gamybos sistema, arba darbas, vadovaujantis nulinių sąnaudų principu'],
		['ELELEDOC', 'Įmonės darbuotojai užrašo ir saugo geros savo darbo praktikos pavyzdžius ar kaupia įgytas žinias', ''],
		['FROTATE', 'Įmonėje darbuotojai keičiasi užduotimis su kitais darbuotojais', ''],
		['aut_team', 'Įmonėje vyksta komandinis darbas', ''],
		['HACCUOV', 'Darbuotojai turi galimybę laisvadieniams panaudoti sukauptus viršvalandžius', ''],
		['HFLEXI_HFLEXI_N_HFLEXIPC', 'Įmonės darbuotojų dalis procentais, kurie turi galimybę keisti įprastą darbo pradžios ir pabaigos laiką', '']
	];
