//Auto Generated file
var subset_
	 = [
	
		['sec3', 'Sector de actividad'],
		['size_4', 'Tamaño de la empresa']
	];
var subset_subsetValue
	 = [
	
		['sec3', 'All', 'Todos'],
		['sec3', '1--Producing-Industries', 'Sector de producción'],
		['sec3', '2--Private-Services', 'Servicios privados'],
		['sec3', '3--Public-Services', 'Servicios públicos'],
		['size_4', 'All', 'Todos'],
		['size_4', '1--10-to-19-employees', 'de 10 a 19 empleados'],
		['size_4', '2--20-to-49-employees', 'de 20 a 49 empleados'],
		['size_4', '3--50-to-249-employees', 'de 50 a 249 empleados'],
		['size_4', '4--250-employees-or-more', ' 250 o más empleados']
	];
var topic_
	 = [
	
		['', 'Todos (70)'],
		['Factores impulsores y obstáculos', 'Factores impulsores y obstáculos (15)'],
		['Gestión de la SST', 'Gestión de la SST (29)'],
		['Participación de los trabajadores', 'Participación de los trabajadores (4)'],
		['Riesgos psicosociales y su gestión', 'Riesgos psicosociales y su gestión (22)']
	];
var topic_question
	 = [
	
		['Gestión de la SST', 'MM150_1', 'Utilización de servicios de salud y seguridad: Un médico del trabajo'],
		['Gestión de la SST', 'MM150_2', 'Utilización de servicios de salud y seguridad: Un experto en seguridad'],
		['Gestión de la SST', 'MM150_3', 'Utilización de servicios de salud y seguridad: Un psicólogo'],
		['Gestión de la SST', 'MM150_4', 'Utilización de servicios de salud y seguridad: Un ergonomista, encargado de la disposición del puesto de trabajo'],
		['Gestión de la SST', 'MM150_5', 'Utilización de servicios de salud y seguridad: Una consultoría de seguridad y salud'],
		['Gestión de la SST', 'MM152', '¿Su establecimiento analiza de forma sistemática las causas de las bajas por enfermedad?'],
		['Gestión de la SST', 'MM153', '¿Toma usted medidas para facilitar la reincorporación de los empleados al trabajo después de una baja por enfermedad de larga duración?'],
		['Gestión de la SST', 'MM154', '¿Se realizan chequeos médicos con regularidad para controlar la salud de los empleados?'],
		['Gestión de la SST', 'MM155', '¿Hay una política documentada, un sistema de gestión establecido o un plan de acción sobre seguridad y salud en su establecimiento?'],
		['Gestión de la SST', 'MM158', '¿La seguridad y la salud son temas que se abordan en las reuniones de la dirección a alto nivel con frecuencia, ocasionalmente o prácticamente nunca?'],
		['Gestión de la SST', 'MM159', 'En general, ¿cómo valoraría el grado de implicación de los jefes intermedios y supervisores en la gestión de la seguridad y la salud? ¿Es muy elevado, bastante elevado, bastante bajo o muy bajo?'],
		['Gestión de la SST', 'MM161', '¿En su centro de trabajo, se comprueban regularmente los riesgos de seguridad y salud como parte de un plan de evaluación de riesgos u otro similar?'],
		['Gestión de la SST', 'MM170', '¿La inspección de trabajo ha visitado este establecimiento en los últimos 3 años para comprobar las condiciones de seguridad y salud?'],
		['Gestión de la SST', 'MM173_1', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: Institutos oficiales de seguridad y salud en el trabajo'],
		['Gestión de la SST', 'MM173_2', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: La Agencia Europea para la Seguridad y la Salud en el Trabajo'],
		['Gestión de la SST', 'MM173_3', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: Los servicios internos de seguridad y salud'],
		['Gestión de la SST', 'MM173_4', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: La inspección de trabajo'],
		['Gestión de la SST', 'MM173_5', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: Las organizaciones empresariales'],
		['Gestión de la SST', 'MM173_6', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: Sindicatos'],
		['Gestión de la SST', 'MM173_7', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: Expertos en seguridad y salud contratados'],
		['Gestión de la SST', 'MM173_8', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: Las compañías de seguros'],
		['Gestión de la SST', 'MM175', '¿Conoce la Semana Europea para la Seguridad y la Salud en el Trabajo?'],
		['Gestión de la SST', 'MM200_1', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Sustancias peligrosas (Por ejemplo, polvo, sustancias químicas, biológicas o radioactivas)'],
		['Gestión de la SST', 'MM200_2', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Accidentes'],
		['Gestión de la SST', 'MM200_3', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Ruido y vibraciones'],
		['Gestión de la SST', 'MM200_4', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Trastornos músculo-esqueléticos, como dolor de espalda, cuello, brazos, piernas'],
		['Gestión de la SST', 'MM200_5', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Estrés laboral'],
		['Gestión de la SST', 'MM200_6', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Violencia o amenazas'],
		['Gestión de la SST', 'MM200_7', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Acoso o intimidación, es decir insultos, humillación o agresiones por parte de compañeros o superiores'],
		['Riesgos psicosociales y su gestión', 'MM202_1', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.: Presión de tiempo'],
		['Riesgos psicosociales y su gestión', 'MM202_2', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.: Pobre comunicación entre la dirección y los trabajadores'],
		['Riesgos psicosociales y su gestión', 'MM202_3', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Pobre colaboración entre compañeros'],
		['Riesgos psicosociales y su gestión', 'MM202_4', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Falta de control del empleado sobre la organización de su trabajo'],
		['Riesgos psicosociales y su gestión', 'MM202_5', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Inseguridad laboral'],
		['Riesgos psicosociales y su gestión', 'MM202_6', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Tener que tratar con clientes, pacientes, alumnos difíciles'],
		['Riesgos psicosociales y su gestión', 'MM202_7', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Problemas de relación entre supervisor - trabajador'],
		['Riesgos psicosociales y su gestión', 'MM202_8', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Horario prolongado o irregular'],
		['Riesgos psicosociales y su gestión', 'MM202_9', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Inadecuada política de recursos humanos'],
		['Riesgos psicosociales y su gestión', 'MM202_10', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Discriminación (por ejemplo, de género, edad, raza)'],
		['Riesgos psicosociales y su gestión', 'MM250', '¿En su establecimiento hay algún procedimiento para tratar el estrés laboral?'],
		['Riesgos psicosociales y su gestión', 'MM251', '¿Hay algún procedimiento para abordar la intimidación o el acoso?'],
		['Riesgos psicosociales y su gestión', 'MM252', '¿Hay algún procedimiento para abordar al violencia laboral?'],
		['Riesgos psicosociales y su gestión', 'MM253_1', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?: Cambios en la manera de organizar el trabajo'],
		['Riesgos psicosociales y su gestión', 'MM253_2', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?: Rediseñar el espacio de trabajo'],
		['Riesgos psicosociales y su gestión', 'MM253_3', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?: Asesoría confidencial para los empleados'],
		['Riesgos psicosociales y su gestión', 'MM253_4', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?: Creación de un procedimiento de resolución de conflictos'],
		['Riesgos psicosociales y su gestión', 'MM253_5', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?: Cambios en los horarios de trabajo'],
		['Riesgos psicosociales y su gestión', 'MM253_6', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?: Formación'],
		['Riesgos psicosociales y su gestión', 'MM256', '¿Su establecimiento emprende acciones si algún empleado trabaja demasiadas horas o tiene horarios irregulares?'],
		['Riesgos psicosociales y su gestión', 'MM259', '¿Informa a sus trabajadores sobre los riesgos psicosociales y sus consecuencias en la seguridad y salud?'],
		['Riesgos psicosociales y su gestión', 'MM260', '¿Se ha informado a los trabajadores de a quién deben dirigirse en caso de problemas psicosociales relacionados con el trabajo?¿Los empleados están informados de a quién deben dirigirse en caso de problemas psicosociales relacionados con el trabajo?'],
		['Factores impulsores y obstáculos', 'MM171_1', 'Motivos para abordar la salud y la seguridad en la empresa: Cumplir con las obligaciones legales'],
		['Factores impulsores y obstáculos', 'MM171_2', 'Motivos para abordar la salud y la seguridad en la empresa: Solicitudes por parte de los trabajadores o de sus representantes'],
		['Factores impulsores y obstáculos', 'MM171_3', 'Motivos para abordar la salud y la seguridad en la empresa: Retención del personal y gestión del absentismo'],
		['Factores impulsores y obstáculos', 'MM171_4', 'Motivos para abordar la salud y la seguridad en la empresa: Razones económicas o ligadas al rendimiento'],
		['Factores impulsores y obstáculos', 'MM171_5', 'Motivos para abordar la salud y la seguridad en la empresa: Exigencias de los clientes o preocupación con respecto a la reputación de la organización'],
		['Factores impulsores y obstáculos', 'MM171_6', 'Motivos para abordar la salud y la seguridad en la empresa: Presión por parte de la Inspección de Trabajo'],
		['Factores impulsores y obstáculos', 'MM172_1', 'Principales dificultades para abordar la salud y la seguridad: La falta de recursos, como tiempo, personal o dinero'],
		['Factores impulsores y obstáculos', 'MM172_2', 'Principales dificultades para abordar la salud y la seguridad: La falta de sensibilización'],
		['Factores impulsores y obstáculos', 'MM172_3', 'Principales dificultades para abordar la salud y la seguridad: La falta de experiencia'],
		['Factores impulsores y obstáculos', 'MM172_4', 'Principales dificultades para abordar la salud y la seguridad: La falta de apoyo técnico u orientación'],
		['Factores impulsores y obstáculos', 'MM172_5', 'Principales dificultades para abordar la salud y la seguridad: La cultura dentro del establecimiento'],
		['Factores impulsores y obstáculos', 'MM172_6', 'Principales dificultades para abordar la salud y la seguridad: La sensibilidad del tema'],
		['Factores impulsores y obstáculos', 'MM300', 'Comparado con otros temas de seguridad y salud: ¿es más difícil tratar los riesgos psicosociales, menos difícil o no hay diferencia?'],
		['Factores impulsores y obstáculos', 'MM302', '¿Utiliza información o apoyo de fuentes externas para abordar los riesgos psicosociales en el trabajo?'],
		['Factores impulsores y obstáculos', 'MM303a', '¿Necesita información adicional o apoyo sobre este tema?'],
		['Participación de los trabajadores', 'MM350', '¿Hay un delegado de personal, Comité de Empresa o Junta de personal en este establecimiento?'],
		['Participación de los trabajadores', 'MM351', '¿Hay una delegación sindical en su establecimiento?'],
		['Participación de los trabajadores', 'MM355all', '¿Hay en su establecimiento un delegado de prevención?'],
		['Participación de los trabajadores', 'MM358', '¿Hay un Comité de Seguridad y Salud en este establecimiento?']
	];
var question_
	 = [
	
		['MM150_1', 'Utilización de servicios de salud y seguridad: Un médico del trabajo'],
		['MM150_2', 'Utilización de servicios de salud y seguridad: Un experto en seguridad'],
		['MM150_3', 'Utilización de servicios de salud y seguridad: Un psicólogo'],
		['MM150_4', 'Utilización de servicios de salud y seguridad: Un ergonomista, encargado de la disposición del puesto de trabajo'],
		['MM150_5', 'Utilización de servicios de salud y seguridad: Una consultoría de seguridad y salud'],
		['MM152', '¿Su establecimiento analiza de forma sistemática las causas de las bajas por enfermedad?'],
		['MM153', '¿Toma usted medidas para facilitar la reincorporación de los empleados al trabajo después de una baja por enfermedad de larga duración?'],
		['MM154', '¿Se realizan chequeos médicos con regularidad para controlar la salud de los empleados?'],
		['MM155', '¿Hay una política documentada, un sistema de gestión establecido o un plan de acción sobre seguridad y salud en su establecimiento?'],
		['MM158', '¿La seguridad y la salud son temas que se abordan en las reuniones de la dirección a alto nivel con frecuencia, ocasionalmente o prácticamente nunca?'],
		['MM159', 'En general, ¿cómo valoraría el grado de implicación de los jefes intermedios y supervisores en la gestión de la seguridad y la salud? ¿Es muy elevado, bastante elevado, bastante bajo o muy bajo?'],
		['MM161', '¿En su centro de trabajo, se comprueban regularmente los riesgos de seguridad y salud como parte de un plan de evaluación de riesgos u otro similar?'],
		['MM170', '¿La inspección de trabajo ha visitado este establecimiento en los últimos 3 años para comprobar las condiciones de seguridad y salud?'],
		['MM173_1', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: Institutos oficiales de seguridad y salud en el trabajo'],
		['MM173_2', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: La Agencia Europea para la Seguridad y la Salud en el Trabajo'],
		['MM173_3', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: Los servicios internos de seguridad y salud'],
		['MM173_4', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: La inspección de trabajo'],
		['MM173_5', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: Las organizaciones empresariales'],
		['MM173_6', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: Sindicatos'],
		['MM173_7', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: Expertos en seguridad y salud contratados'],
		['MM173_8', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?: Las compañías de seguros'],
		['MM175', '¿Conoce la Semana Europea para la Seguridad y la Salud en el Trabajo?'],
		['MM200_1', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Sustancias peligrosas (Por ejemplo, polvo, sustancias químicas, biológicas o radioactivas)'],
		['MM200_2', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Accidentes'],
		['MM200_3', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Ruido y vibraciones'],
		['MM200_4', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Trastornos músculo-esqueléticos, como dolor de espalda, cuello, brazos, piernas'],
		['MM200_5', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Estrés laboral'],
		['MM200_6', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Violencia o amenazas'],
		['MM200_7', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Acoso o intimidación, es decir insultos, humillación o agresiones por parte de compañeros o superiores'],
		['MM202_1', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.: Presión de tiempo'],
		['MM202_2', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.: Pobre comunicación entre la dirección y los trabajadores'],
		['MM202_3', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Pobre colaboración entre compañeros'],
		['MM202_4', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Falta de control del empleado sobre la organización de su trabajo'],
		['MM202_5', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Inseguridad laboral'],
		['MM202_6', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Tener que tratar con clientes, pacientes, alumnos difíciles'],
		['MM202_7', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Problemas de relación entre supervisor - trabajador'],
		['MM202_8', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Horario prolongado o irregular'],
		['MM202_9', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Inadecuada política de recursos humanos'],
		['MM202_10', 'Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:Discriminación (por ejemplo, de género, edad, raza)'],
		['MM250', '¿En su establecimiento hay algún procedimiento para tratar el estrés laboral?'],
		['MM251', '¿Hay algún procedimiento para abordar la intimidación o el acoso?'],
		['MM252', '¿Hay algún procedimiento para abordar al violencia laboral?'],
		['MM253_1', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?: Cambios en la manera de organizar el trabajo'],
		['MM253_2', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?: Rediseñar el espacio de trabajo'],
		['MM253_3', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?: Asesoría confidencial para los empleados'],
		['MM253_4', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?: Creación de un procedimiento de resolución de conflictos'],
		['MM253_5', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?: Cambios en los horarios de trabajo'],
		['MM253_6', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?: Formación'],
		['MM256', '¿Su establecimiento emprende acciones si algún empleado trabaja demasiadas horas o tiene horarios irregulares?'],
		['MM259', '¿Informa a sus trabajadores sobre los riesgos psicosociales y sus consecuencias en la seguridad y salud?'],
		['MM260', '¿Se ha informado a los trabajadores de a quién deben dirigirse en caso de problemas psicosociales relacionados con el trabajo?¿Los empleados están informados de a quién deben dirigirse en caso de problemas psicosociales relacionados con el trabajo?'],
		['MM171_1', 'Motivos para abordar la salud y la seguridad en la empresa: Cumplir con las obligaciones legales'],
		['MM171_2', 'Motivos para abordar la salud y la seguridad en la empresa: Solicitudes por parte de los trabajadores o de sus representantes'],
		['MM171_3', 'Motivos para abordar la salud y la seguridad en la empresa: Retención del personal y gestión del absentismo'],
		['MM171_4', 'Motivos para abordar la salud y la seguridad en la empresa: Razones económicas o ligadas al rendimiento'],
		['MM171_5', 'Motivos para abordar la salud y la seguridad en la empresa: Exigencias de los clientes o preocupación con respecto a la reputación de la organización'],
		['MM171_6', 'Motivos para abordar la salud y la seguridad en la empresa: Presión por parte de la Inspección de Trabajo'],
		['MM172_1', 'Principales dificultades para abordar la salud y la seguridad: La falta de recursos, como tiempo, personal o dinero'],
		['MM172_2', 'Principales dificultades para abordar la salud y la seguridad: La falta de sensibilización'],
		['MM172_3', 'Principales dificultades para abordar la salud y la seguridad: La falta de experiencia'],
		['MM172_4', 'Principales dificultades para abordar la salud y la seguridad: La falta de apoyo técnico u orientación'],
		['MM172_5', 'Principales dificultades para abordar la salud y la seguridad: La cultura dentro del establecimiento'],
		['MM172_6', 'Principales dificultades para abordar la salud y la seguridad: La sensibilidad del tema'],
		['MM300', 'Comparado con otros temas de seguridad y salud: ¿es más difícil tratar los riesgos psicosociales, menos difícil o no hay diferencia?'],
		['MM302', '¿Utiliza información o apoyo de fuentes externas para abordar los riesgos psicosociales en el trabajo?'],
		['MM303a', '¿Necesita información adicional o apoyo sobre este tema?'],
		['MM350', '¿Hay un delegado de personal, Comité de Empresa o Junta de personal en este establecimiento?'],
		['MM351', '¿Hay una delegación sindical en su establecimiento?'],
		['MM355all', '¿Hay en su establecimiento un delegado de prevención?'],
		['MM358', '¿Hay un Comité de Seguridad y Salud en este establecimiento?']
	];
var question_answer
	 = [
	
		['MM150_1', '1--Yes', 'Sí'],
		['MM150_1', '2--No', 'No'],
		['MM150_1', '3--DK--NA', 'No contesta'],
		['MM150_2', '1--Yes', 'Sí'],
		['MM150_2', '2--No', 'No'],
		['MM150_2', '3--DK--NA', 'No contesta'],
		['MM150_3', '1--Yes', 'Sí'],
		['MM150_3', '2--No', 'No'],
		['MM150_3', '3--DK--NA', 'No contesta'],
		['MM150_4', '1--Yes', 'Sí'],
		['MM150_4', '2--No', 'No'],
		['MM150_4', '3--DK--NA', 'No contesta'],
		['MM150_5', '1--Yes', 'Sí'],
		['MM150_5', '2--No', 'No'],
		['MM150_5', '3--DK--NA', 'No contesta'],
		['MM152', '1--Yes', 'Sí'],
		['MM152', '2--No', 'No'],
		['MM152', '3--DK--NA', 'No contesta'],
		['MM153', '1--Yes', 'Sí'],
		['MM153', '2--No', 'No'],
		['MM153', '3--DK--NA', 'No contesta'],
		['MM154', '1--Yes', 'Sí'],
		['MM154', '2--No', 'No'],
		['MM154', '3--DK--NA', 'No contesta'],
		['MM155', '1--Yes', 'Sí'],
		['MM155', '2--No', 'No'],
		['MM155', '3--DK--NA', 'No contesta'],
		['MM158', '1--Regularly', 'Habitualmente'],
		['MM158', '2--Occasionally', 'Ocasionalmente'],
		['MM158', '3--Practically-never', 'Prácticamente nunca'],
		['MM158', '4--DK--NA', 'No contesta'],
		['MM159', '1--Very-high', 'Muy elevado'],
		['MM159', '2--Quite-high', 'Bastante elevado'],
		['MM159', '3--Quite-low', 'Bastante bajo'],
		['MM159', '4--Very-low', 'Muy bajo'],
		['MM159', '5--DK--NA', 'No contesta'],
		['MM161', '1--Yes', 'Sí'],
		['MM161', '2--No', 'No'],
		['MM161', '3--DK--NA', 'No contesta'],
		['MM170', '1--Yes', 'Sí'],
		['MM170', '2--No', 'No'],
		['MM170', '3--DK--NA', 'No contesta'],
		['MM171_1', '1--Major', 'De gran importancia'],
		['MM171_1', '2--Minor', 'De menor importancia'],
		['MM171_1', '3--No', 'De ninguna importancia'],
		['MM171_1', '4--DK--NA', 'No contesta'],
		['MM171_2', '1--Major', 'De gran importancia'],
		['MM171_2', '2--Minor', 'De menor importancia'],
		['MM171_2', '3--No', 'De ninguna importancia'],
		['MM171_2', '4--DK--NA', 'No contesta'],
		['MM171_3', '1--Major', 'De gran importancia'],
		['MM171_3', '2--Minor', 'De menor importancia'],
		['MM171_3', '3--No', 'De ninguna importancia'],
		['MM171_3', '4--DK--NA', 'No contesta'],
		['MM171_4', '1--Major', 'De gran importancia'],
		['MM171_4', '2--Minor', 'De menor importancia'],
		['MM171_4', '3--No', 'De ninguna importancia'],
		['MM171_4', '4--DK--NA', 'No contesta'],
		['MM171_5', '1--Major', 'De gran importancia'],
		['MM171_5', '2--Minor', 'De menor importancia'],
		['MM171_5', '3--No', 'De ninguna importancia'],
		['MM171_5', '4--DK--NA', 'No contesta'],
		['MM171_6', '1--Major', 'De gran importancia'],
		['MM171_6', '2--Minor', 'De menor importancia'],
		['MM171_6', '3--No', 'De ninguna importancia'],
		['MM171_6', '4--DK--NA', 'No contesta'],
		['MM172_1', '1--Major', 'Dificultad mayor'],
		['MM172_1', '2--Minor', 'Dificultad menor'],
		['MM172_1', '3--No', 'Ninguna dificultad'],
		['MM172_1', '4--DK--NA', 'No contesta'],
		['MM172_2', '1--Major', 'Dificultad mayor'],
		['MM172_2', '2--Minor', 'Dificultad menor'],
		['MM172_2', '3--No', 'Ninguna dificultad'],
		['MM172_2', '4--DK--NA', 'No contesta'],
		['MM172_3', '1--Major', 'Dificultad mayor'],
		['MM172_3', '2--Minor', 'Dificultad menor'],
		['MM172_3', '3--No', 'Ninguna dificultad'],
		['MM172_3', '4--DK--NA', 'No contesta'],
		['MM172_4', '1--Major', 'Dificultad mayor'],
		['MM172_4', '2--Minor', 'Dificultad menor'],
		['MM172_4', '3--No', 'Ninguna dificultad'],
		['MM172_4', '4--DK--NA', 'No contesta'],
		['MM172_5', '1--Major', 'Dificultad mayor'],
		['MM172_5', '2--Minor', 'Dificultad menor'],
		['MM172_5', '3--No', 'Ninguna dificultad'],
		['MM172_5', '4--DK--NA', 'No contesta'],
		['MM172_6', '1--Major', 'Dificultad mayor'],
		['MM172_6', '2--Minor', 'Dificultad menor'],
		['MM172_6', '3--No', 'Ninguna dificultad'],
		['MM172_6', '4--DK--NA', 'No contesta'],
		['MM173_1', '1--Yes', 'Sí'],
		['MM173_1', '2--No', 'No'],
		['MM173_1', '3--DK--NA', 'No contesta'],
		['MM173_2', '1--Yes', 'Sí'],
		['MM173_2', '2--No', 'No'],
		['MM173_2', '3--DK--NA', 'No contesta'],
		['MM173_3', '1--Yes', 'Sí'],
		['MM173_3', '2--No', 'No'],
		['MM173_3', '3--DK--NA', 'No contesta'],
		['MM173_4', '1--Yes', 'Sí'],
		['MM173_4', '2--No', 'No'],
		['MM173_4', '3--DK--NA', 'No contesta'],
		['MM173_5', '1--Yes', 'Sí'],
		['MM173_5', '2--No', 'No'],
		['MM173_5', '3--DK--NA', 'No contesta'],
		['MM173_6', '1--Yes', 'Sí'],
		['MM173_6', '2--No', 'No'],
		['MM173_6', '3--DK--NA', 'No contesta'],
		['MM173_7', '1--Yes', 'Sí'],
		['MM173_7', '2--No', 'No'],
		['MM173_7', '3--DK--NA', 'No contesta'],
		['MM173_8', '1--Yes', 'Sí'],
		['MM173_8', '2--No', 'No'],
		['MM173_8', '3--DK--NA', 'No contesta'],
		['MM175', '1--Yes', 'Sí'],
		['MM175', '2--No', 'No'],
		['MM175', '3--DK--NA', 'No contesta'],
		['MM200_1', '1--Major-concern', 'Gran preocupación'],
		['MM200_1', '2--Some-concern', 'Cierta preocupación'],
		['MM200_1', '3--No-concern', 'Ninguna preocupación'],
		['MM200_1', '4--DK--NA', 'No contesta'],
		['MM200_2', '1--Major-concern', 'Gran preocupación'],
		['MM200_2', '2--Some-concern', 'Cierta preocupación'],
		['MM200_2', '3--No-concern', 'Ninguna preocupación'],
		['MM200_2', '4--DK--NA', 'No contesta'],
		['MM200_3', '1--Major-concern', 'Gran preocupación'],
		['MM200_3', '2--Some-concern', 'Cierta preocupación'],
		['MM200_3', '3--No-concern', 'Ninguna preocupación'],
		['MM200_3', '4--DK--NA', 'No contesta'],
		['MM200_4', '1--Major-concern', 'Gran preocupación'],
		['MM200_4', '2--Some-concern', 'Cierta preocupación'],
		['MM200_4', '3--No-concern', 'Ninguna preocupación'],
		['MM200_4', '4--DK--NA', 'No contesta'],
		['MM200_5', '1--Major-concern', 'Gran preocupación'],
		['MM200_5', '2--Some-concern', 'Cierta preocupación'],
		['MM200_5', '3--No-concern', 'Ninguna preocupación'],
		['MM200_5', '4--DK--NA', 'No contesta'],
		['MM200_6', '1--Major-concern', 'Gran preocupación'],
		['MM200_6', '2--Some-concern', 'Cierta preocupación'],
		['MM200_6', '3--No-concern', 'Ninguna preocupación'],
		['MM200_6', '4--DK--NA', 'No contesta'],
		['MM200_7', '1--Major-concern', 'Gran preocupación'],
		['MM200_7', '2--Some-concern', 'Cierta preocupación'],
		['MM200_7', '3--No-concern', 'Ninguna preocupación'],
		['MM200_7', '4--DK--NA', 'No contesta'],
		['MM202_1', '1--Yes', 'Sí'],
		['MM202_1', '2--No', 'No'],
		['MM202_1', '3--DK--NA', 'No contesta'],
		['MM202_10', '1--Yes', 'Sí'],
		['MM202_10', '2--No', 'No'],
		['MM202_10', '3--DK--NA', 'No contesta'],
		['MM202_2', '1--Yes', 'Sí'],
		['MM202_2', '2--No', 'No'],
		['MM202_2', '3--DK--NA', 'No contesta'],
		['MM202_3', '1--Yes', 'Sí'],
		['MM202_3', '2--No', 'No'],
		['MM202_3', '3--DK--NA', 'No contesta'],
		['MM202_4', '1--Yes', 'Sí'],
		['MM202_4', '2--No', 'No'],
		['MM202_4', '3--DK--NA', 'No contesta'],
		['MM202_5', '1--Yes', 'Sí'],
		['MM202_5', '2--No', 'No'],
		['MM202_5', '3--DK--NA', 'No contesta'],
		['MM202_6', '1--Yes', 'Sí'],
		['MM202_6', '2--No', 'No'],
		['MM202_6', '3--DK--NA', 'No contesta'],
		['MM202_7', '1--Yes', 'Sí'],
		['MM202_7', '2--No', 'No'],
		['MM202_7', '3--DK--NA', 'No contesta'],
		['MM202_8', '1--Yes', 'Sí'],
		['MM202_8', '2--No', 'No'],
		['MM202_8', '3--DK--NA', 'No contesta'],
		['MM202_9', '1--Yes', 'Sí'],
		['MM202_9', '2--No', 'No'],
		['MM202_9', '3--DK--NA', 'No contesta'],
		['MM250', '1--Yes', 'Sí'],
		['MM250', '2--No', 'No'],
		['MM250', '3--Work-related-stress-is-not-an-issue-in-our-establishment', 'El estrés laboral no es un problema en nuestro establecimiento'],
		['MM250', '4--No-answer', 'No contesta'],
		['MM251', '1--Yes', 'Sí'],
		['MM251', '2--No', 'No'],
		['MM251', '3--These-problems-are-not-an-issue-in-our-establishment', 'Estas situaciones no son un problema en nuestro establecimiento'],
		['MM251', '4--No-answer', 'No contesta'],
		['MM252', '1--Yes', 'Sí'],
		['MM252', '2--No', 'No'],
		['MM252', '3--Work-related-violence-is-not-an-issue-in-our-establishment', 'La violencia laboral no es un problema en nuestro establecimiento'],
		['MM252', '4--No-answer', 'No contesta'],
		['MM253_1', '1--Yes', 'Sí'],
		['MM253_1', '2--No', 'No'],
		['MM253_1', '3--DK--NA', 'No contesta'],
		['MM253_2', '1--Yes', 'Sí'],
		['MM253_2', '2--No', 'No'],
		['MM253_2', '3--DK--NA', 'No contesta'],
		['MM253_3', '1--Yes', 'Sí'],
		['MM253_3', '2--No', 'No'],
		['MM253_3', '3--DK--NA', 'No contesta'],
		['MM253_4', '1--Yes', 'Sí'],
		['MM253_4', '2--No', 'No'],
		['MM253_4', '3--DK--NA', 'No contesta'],
		['MM253_5', '1--Yes', 'Sí'],
		['MM253_5', '2--No', 'No'],
		['MM253_5', '3--DK--NA', 'No contesta'],
		['MM253_6', '1--Yes', 'Sí'],
		['MM253_6', '2--No', 'No'],
		['MM253_6', '3--DK--NA', 'No contesta'],
		['MM256', '1--Yes', 'Sí'],
		['MM256', '2--No', 'No'],
		['MM256', '3--Long-or-irregular-working-hours-are-not-an-issue-in-our-esta', 'Los horarios prolongados o irregulares no son un problema en nuestro establecimiento'],
		['MM256', '4--No-answer', 'No contesta'],
		['MM259', '1--Yes', 'Sí'],
		['MM259', '2--No', 'No'],
		['MM259', '3--No-answer', 'No contesta'],
		['MM260', '1--Yes', 'Sí'],
		['MM260', '2--No', 'No'],
		['MM260', '3--No-answer', 'No contesta'],
		['MM300', '1--More-difficult', 'Más difícil'],
		['MM300', '2--Less-difficult', 'Menos difícil'],
		['MM300', '3--No-difference', 'No hay diferencia'],
		['MM300', '4--No-answer', 'No contesta'],
		['MM302', '1--Yes', 'Sí'],
		['MM302', '2--No', 'No'],
		['MM302', '3--No-answer', 'No contesta'],
		['MM303a', '1--Yes', 'Sí'],
		['MM303a', '2--No', 'No'],
		['MM303a', '3--No-answer', 'No contesta'],
		['MM350', '1--Yes', 'Sí'],
		['MM350', '2--No', 'No'],
		['MM350', '3--No-answer', 'No contesta'],
		['MM351', '1--Yes', 'Sí'],
		['MM351', '2--No', 'No'],
		['MM351', '3--No-answer', 'No contesta'],
		['MM355all', '1--Yes', 'Sí'],
		['MM355all', '2--No', 'No'],
		['MM355all', '3--No-answer', 'No contesta'],
		['MM358', '1--Yes', 'Sí'],
		['MM358', '2--No', 'No'],
		['MM358', '3--No-answer', 'No contesta']
	];
var country_
	 = [
	
		['AT', 'Austria'],
		['BE', 'Bélgica'],
		['BG', 'Bulgaria'],
		['CH', 'Suiza'],
		['CY', 'Chipre'],
		['CZ', 'República Checa'],
		['DE', 'Alemania'],
		['DK', 'Dinamarca'],
		['EE', 'Estonia'],
		['EL', 'Grecia'],
		['ES', 'España'],
		['FI', 'Finlandia'],
		['FR', 'Francia'],
		['HR', 'Croacia *'],
		['HU', 'Hungría'],
		['IE', 'Irlanda'],
		['IT', 'Italia'],
		['LT', 'Lituania'],
		['LU', 'Luxemburgo'],
		['LV', 'Letonia'],
		['MT', 'Malta'],
		['NL', 'Países Bajos'],
		['NO', 'Noruega'],
		['PL', 'Polonia'],
		['PT', 'Portugal'],
		['RO', 'Rumanía'],
		['SE', 'Suecia'],
		['SI', 'Eslovenia'],
		['SK', 'Eslovaquia'],
		['TR', 'Turquía'],
		['UK', 'Reino Unido'],
		['EuropeanUnion', 'Unión Europea *']
	];
var question_meta
	 = [
	
		['MM150_1', 'Un médico del trabajo', '¿Qué servicios de seguridad y salud utiliza ya sean internos o externos?Un médico del trabajo'],
		['MM150_2', 'Un experto en seguridad', '¿Qué servicios de seguridad y salud utiliza ya sean internos o externos?Un experto en seguridad'],
		['MM150_3', 'Un psicólogo', '¿Qué servicios de seguridad y salud utiliza ya sean internos o externos?Un psicólogo'],
		['MM150_4', 'Un ergonomista, encargado de la disposición del puesto de trabajo', '¿Qué servicios de seguridad y salud utiliza ya sean internos o externos?Un ergonomista, encargado de la disposición del puesto de trabajo'],
		['MM150_5', 'Una consultoría de seguridad y salud', '¿Qué servicios de seguridad y salud utiliza ya sean internos o externos?Una consultoría de seguridad y salud'],
		['MM152', '¿Su establecimiento analiza de forma sistemática las causas de las bajas por enfermedad?', '¿Su establecimiento analiza de forma sistemática las causas de las bajas por enfermedad?'],
		['MM153', '¿Toma usted medidas para facilitar la reincorporación de los empleados al trabajo después de una baja por enfermedad de larga duración?', '¿Toma usted medidas para facilitar la reincorporación de los empleados al trabajo después de una baja por enfermedad de larga duración?'],
		['MM154', '¿Se realizan chequeos médicos con regularidad para controlar la salud de los empleados?', '¿Se realizan chequeos médicos con regularidad para controlar la salud de los empleados?'],
		['MM155', '¿Hay una política documentada, un sistema de gestión establecido o un plan de acción sobre seguridad y salud en su establecimiento?', '¿Hay una política documentada, un sistema de gestión establecido o un plan de acción sobre seguridad y salud en su establecimiento?'],
		['MM158', '¿La seguridad y la salud son temas que se abordan en las reuniones de la dirección a alto nivel con frecuencia, ocasionalmente o prácticamente nunca?', '¿La seguridad y la salud son temas que se abordan en las reuniones de la dirección a alto nivel con frecuencia, ocasionalmente o prácticamente nunca?'],
		['MM159', 'En general, ¿cómo valoraría el grado de implicación de los jefes intermedios y supervisores en la gestión de la seguridad y la salud? ¿Es muy elevado, bastante elevado, bastante bajo o muy bajo?', 'En general, ¿cómo valoraría el grado de implicación de los jefes intermedios y supervisores en la gestión de la seguridad y la salud? ¿Es muy elevado, bastante elevado, bastante bajo o muy bajo?'],
		['MM161', '¿En su centro de trabajo, se comprueban regularmente los riesgos de seguridad y salud como parte de un plan de evaluación de riesgos u otro similar?', '¿En su centro de trabajo, se comprueban regularmente los riesgos de seguridad y salud como parte de un plan de evaluación de riesgos u otro similar?'],
		['MM170', '¿La inspección de trabajo ha visitado este establecimiento en los últimos 3 años para comprobar las condiciones de seguridad y salud?', '¿La inspección de trabajo ha visitado este establecimiento en los últimos 3 años para comprobar las condiciones de seguridad y salud?'],
		['MM173_1', 'Institutos oficiales de seguridad y salud en el trabajo', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?Institutos oficiales de seguridad y salud en el trabajo'],
		['MM173_2', 'La Agencia Europea para la Seguridad y la Salud en el Trabajo', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?La Agencia Europea para la Seguridad y la Salud en el Trabajo'],
		['MM173_3', 'Los servicios internos de seguridad y salud', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?Los servicios internos de seguridad y salud'],
		['MM173_4', 'La inspección de trabajo', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?La inspección de trabajo'],
		['MM173_5', 'Las organizaciones empresariales', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?Las organizaciones empresariales'],
		['MM173_6', 'Sindicatos', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?Sindicatos'],
		['MM173_7', 'Expertos en seguridad y salud contratados', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?Expertos en seguridad y salud contratados'],
		['MM173_8', 'Las compañías de seguros', '¿Ha utilizado su establecimiento la información sobre seguridad y salud de alguno de los organismos o instituciones siguientes?Las compañías de seguros'],
		['MM175', '¿Conoce la Semana Europea para la Seguridad y la Salud en el Trabajo?', '¿Conoce la Semana Europea para la Seguridad y la Salud en el Trabajo?'],
		['MM200_1', 'Sustancias peligrosas ( Por ejemplo, polvo, sustancias químicas, biológicas o radioactivas)', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.: Sustancias peligrosas (Por ejemplo, polvo, sustancias químicas, biológicas o radioactivas)'],
		['MM200_2', 'Accidentes', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.Accidentes'],
		['MM200_3', 'Ruido y vibraciones', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.Ruido y vibraciones'],
		['MM200_4', 'Trastornos músculo-esqueléticos, como dolor de espalda, cuello, brazos, piernas', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.Trastornos músculo-esqueléticos, como dolor de espalda, cuello, brazos, piernas'],
		['MM200_5', 'Estrés laboral', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.Estrés laboral'],
		['MM200_6', 'Violencia o amenazas', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.Violencia o amenazas'],
		['MM200_7', 'Acoso o intimidación, es decir insultos, humillación o agresiones por parte de compañeros o superiores', 'Para cada uno de los siguientes temas, por favor, dígame si es una gran preocupación, cierta preocupación o ninguna preocupación en su establecimiento.Acoso o intimidación, es decir insultos, humillación o agresiones por parte de compañeros o superiores'],
		['MM202_1', 'Presión de tiempo', 'Algunos factores pueden contribuir al estrés, la violencia y el acoso en el trabajo. Tienen que ver con la manera en la que el trabajo está organizado y a menudo se consideran como "riesgos psicosociales". Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.: Presión de tiempo'],
		['MM202_2', 'Pobre comunicación entre la dirección y los trabajadores', 'Algunos factores pueden contribuir al estrés, la violencia y el acoso en el trabajo. Tienen que ver con la manera en la que el trabajo está organizado y a menudo se consideran como "riesgos psicosociales". Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.: Pobre comunicación entre la dirección y los trabajadores'],
		['MM202_3', 'Pobre colaboración entre compañeros', 'Algunos factores pueden contribuir al estrés, la violencia y el acoso en el trabajo. Tienen que ver con la manera en la que el trabajo está organizado y a menudo se consideran como "riesgos psicosociales". Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.: Pobre colaboración entre compañeros'],
		['MM202_4', 'Falta de control del empleado sobre la organización de su trabajo', 'Algunos factores pueden contribuir al estrés, la violencia y el acoso en el trabajo. Tienen que ver con la manera en la que el trabajo está organizado y a menudo se consideran como "riesgos psicosociales". Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:  Falta de control del empleado sobre la organización de su trabajo'],
		['MM202_5', 'Inseguridad laboral', 'Algunos factores pueden contribuir al estrés, la violencia y el acoso en el trabajo. Tienen que ver con la manera en la que el trabajo está organizado y a menudo se consideran como "riesgos psicosociales". Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.: Inseguridad laboral'],
		['MM202_6', 'Tener que tratar con clientes, pacientes, alumnos difíciles', 'Algunos factores pueden contribuir al estrés, la violencia y el acoso en el trabajo. Tienen que ver con la manera en la que el trabajo está organizado y a menudo se consideran como "riesgos psicosociales". Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:  Tener que tratar con clientes, pacientes, alumnos difíciles'],
		['MM202_7', 'Problemas de relación entre supervisor - trabajador', 'Algunos factores pueden contribuir al estrés, la violencia y el acoso en el trabajo. Tienen que ver con la manera en la que el trabajo está organizado y a menudo se consideran como "riesgos psicosociales". Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:  Problemas de relación entre supervisor - trabajador'],
		['MM202_8', 'Horario prolongado o irregular', 'Algunos factores pueden contribuir al estrés, la violencia y el acoso en el trabajo. Tienen que ver con la manera en la que el trabajo está organizado y a menudo se consideran como "riesgos psicosociales". Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.: Horario prolongado o irregular'],
		['MM202_9', 'Inadecuada política de recursos humanos', 'Algunos factores pueden contribuir al estrés, la violencia y el acoso en el trabajo. Tienen que ver con la manera en la que el trabajo está organizado y a menudo se consideran como "riesgos psicosociales". Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:  Inadecuada política de recursos humanos'],
		['MM202_10', 'Discriminación (por ejemplo, de género, edad, raza)', 'Algunos factores pueden contribuir al estrés, la violencia y el acoso en el trabajo. Tienen que ver con la manera en la que el trabajo está organizado y a menudo se consideran como "riesgos psicosociales". Por favor, dígame si cualquiera de estos riesgos psicosociales están presentes en su establecimiento.:  Discriminación (por ejemplo, de género, edad, raza)'],
		['MM250', '¿En su establecimiento hay algún procedimiento para tratar el estrés laboral?', '¿En su establecimiento hay algún procedimiento para tratar el estrés laboral?'],
		['MM251', '¿Hay algún procedimiento para abordar la intimidación o el acoso?', '¿Hay algún procedimiento para abordar la intimidación o el acoso?'],
		['MM252', '¿Hay algún procedimiento para abordar al violencia laboral?', '¿Hay algún procedimiento para abordar al violencia laboral?'],
		['MM253_1', 'Cambios en la manera de organizar el trabajo', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?Cambios en la manera de organizar el trabajo'],
		['MM253_2', 'Rediseñar el espacio de trabajo', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?Rediseñar el espacio de trabajo'],
		['MM253_3', 'Asesoría confidencial para los empleados', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?Asesoría confidencial para los empleados'],
		['MM253_4', 'Creación de un procedimiento de resolución de conflictos', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?Creación de un procedimiento de resolución de conflictos'],
		['MM253_5', 'Cambios en los horarios de trabajo', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?Cambios en los horarios de trabajo'],
		['MM253_6', 'Formación', 'En los tres últimos años su establecimiento ha tenido que recurrir a una de las medidas siguientes para abordar los riesgos psicosociales?Formación'],
		['MM256', '¿Su establecimiento emprende acciones si algún empleado trabaja demasiadas horas o tiene horarios irregulares?', '¿Su establecimiento emprende acciones si algún empleado trabaja demasiadas horas o tiene horarios irregulares?'],
		['MM259', '¿Informa a sus trabajadores sobre los riesgos psicosociales y sus consecuencias en la seguridad y salud?', '¿Informa a sus trabajadores sobre los riesgos psicosociales y sus consecuencias en la seguridad y salud?'],
		['MM260', '¿Se ha informado a los trabajadores de a quién deben dirigirse en caso de problemas psicosociales relacionados con el trabajo?¿Los empleados están informados de a quién deben dirigirse en caso de problemas psicosociales relacionados con el trabajo?', '¿Se ha informado a los trabajadores de a quién deben dirigirse en caso de problemas psicosociales relacionados con el trabajo?¿Los empleados están informados de a quién deben dirigirse en caso de problemas psicosociales relacionados con el trabajo?'],
		['MM171_1', 'Cumplir con las obligaciones legales', 'En su establecimiento, ¿qué importancia tienen cada una de las siguientes razones a la hora de abordar la seguridad y la salud? Para cada una de ellas, dígame si es de gran importancia, de menor importancia o de ninguna importancia.Cumplir con las obligaciones legales'],
		['MM171_2', 'Solicitudes por parte de los trabajadores o de sus representantes', 'En su establecimiento, ¿qué importancia tienen cada una de las siguientes razones a la hora de abordar la seguridad y la salud? Para cada una de ellas, dígame si es de gran importancia, de menor importancia o de ninguna importancia.Solicitudes por parte de los trabajadores o de sus representantes'],
		['MM171_3', 'Retención del personal y gestión del absentismo', 'En su establecimiento, ¿qué importancia tienen cada una de las siguientes razones a la hora de abordar la seguridad y la salud? Para cada una de ellas, dígame si es de gran importancia, de menor importancia o de ninguna importancia.Retención del personal y gestión del absentismo'],
		['MM171_4', 'Razones económicas o ligadas al rendimiento', 'En su establecimiento, ¿qué importancia tienen cada una de las siguientes razones a la hora de abordar la seguridad y la salud? Para cada una de ellas, dígame si es de gran importancia, de menor importancia o de ninguna importancia.Razones económicas o ligadas al rendimiento'],
		['MM171_5', 'Exigencias de los clientes o preocupación con respecto a la reputación de la organización', 'En su establecimiento, ¿qué importancia tienen cada una de las siguientes razones a la hora de abordar la seguridad y la salud? Para cada una de ellas, dígame si es de gran importancia, de menor importancia o de ninguna importancia.Exigencias de los clientes o preocupación con respecto a la reputación de la organización'],
		['MM171_6', 'Presión por parte de la Inspección de Trabajo', 'En su establecimiento, ¿qué importancia tienen cada una de las siguientes razones a la hora de abordar la seguridad y la salud? Para cada una de ellas, dígame si es de gran importancia, de menor importancia o de ninguna importancia.Presión por parte de la Inspección de Trabajo'],
		['MM172_1', 'La falta de recursos, como tiempo, personal o dinero', 'En su establecimiento, ¿cuáles son las principales dificultades para abordar la seguridad y la salud. Por favor, para cada una de ellas, dígame si es una dificultad mayor, dificultad menor o ninguna dificultad en absoluto?La falta de recursos, como tiempo, personal o dinero'],
		['MM172_2', 'La falta de sensibilización', 'En su establecimiento, ¿cuáles son las principales dificultades para abordar la seguridad y la salud. Por favor, para cada una de ellas, dígame si es una dificultad mayor, dificultad menor o ninguna dificultad en absoluto?La falta de sensibilización'],
		['MM172_3', 'La falta de experiencia', 'En su establecimiento, ¿cuáles son las principales dificultades para abordar la seguridad y la salud. Por favor, para cada una de ellas, dígame si es una dificultad mayor, dificultad menor o ninguna dificultad en absoluto?La falta de experiencia'],
		['MM172_4', 'La falta de apoyo técnico u orientación', 'En su establecimiento, ¿cuáles son las principales dificultades para abordar la seguridad y la salud. Por favor, para cada una de ellas, dígame si es una dificultad mayor, dificultad menor o ninguna dificultad en absoluto?La falta de apoyo técnico u orientación'],
		['MM172_5', 'La cultura dentro del establecimiento', 'En su establecimiento, ¿cuáles son las principales dificultades para abordar la seguridad y la salud. Por favor, para cada una de ellas, dígame si es una dificultad mayor, dificultad menor o ninguna dificultad en absoluto?La cultura dentro del establecimiento'],
		['MM172_6', 'La sensibilidad del tema', 'En su establecimiento, ¿cuáles son las principales dificultades para abordar la seguridad y la salud. Por favor, para cada una de ellas, dígame si es una dificultad mayor, dificultad menor o ninguna dificultad en absoluto?La sensibilidad del tema'],
		['MM300', 'Comparado con otros temas de seguridad y salud: ¿es más difícil tratar los riesgos psicosociales, menos difícil o no hay diferencia?', 'Comparado con otros temas de seguridad y salud: ¿es más difícil tratar los riesgos psicosociales, menos difícil o no hay diferencia?'],
		['MM302', '¿Utiliza información o apoyo de fuentes externas para abordar los riesgos psicosociales en el trabajo?', '¿Utiliza información o apoyo de fuentes externas para abordar los riesgos psicosociales en el trabajo?'],
		['MM303a', '¿Necesita información adicional o apoyo sobre este tema?', '¿Necesita información adicional o apoyo sobre este tema?<br><br>Pregunta formulada a los centros de trabajo que afirman que utilizan información o asistencia de fuentes externas sobre la manera de tratar los riesgos psicosociales en el trabajo.'],
		['MM350', '¿Hay un delegado de personal, Comité de Empresa o Junta de personal en este establecimiento?', '¿Hay un delegado de personal, Comité de Empresa o Junta de personal en este establecimiento?'],
		['MM351', '¿Hay una delegación sindical en su establecimiento?', '¿Hay una delegación sindical en su establecimiento?'],
		['MM355all', '¿Hay en su establecimiento un delegado de prevención?', '¿Hay en su establecimiento un delegado de prevención?<br><br>NL: ¿Hay un representante de seguridad y salud en esta empresa?'],
		['MM358', '¿Hay un Comité de Seguridad y Salud en este establecimiento?', '¿Hay un Comité de Seguridad y Salud en este establecimiento?']
	];
