//Auto Generated file
var subset_
	 = [
	
		['size_4', 'Ettevõtte/asutuse suurus'],
		['sec3', 'Tegevusvaldkond']
	];
var subset_subsetValue
	 = [
	
		['sec3', 'All', 'Kõik'],
		['sec3', '1--Producing-Industries', 'Tootmissektor'],
		['sec3', '2--Private-Services', 'Erasektori teenused'],
		['sec3', '3--Public-Services', 'Avalikud teenused'],
		['size_4', 'All', 'Kõik'],
		['size_4', '1--10-to-19-employees', '10–19 töötajat'],
		['size_4', '2--20-to-49-employees', '20–49 töötajat'],
		['size_4', '3--50-to-249-employees', '50–249 töötajat'],
		['size_4', '4--250-employees-or-more', 'vähemalt 250 töötajat']
	];
var topic_
	 = [
	
		['', 'Kõik (70)'],
		['Ajendid ja tõkked', 'Ajendid ja tõkked (15)'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'Psühhosotsiaalsed riskid ja nende ohjamine (22)'],
		['Töötaja osalus', 'Töötaja osalus (4)'],
		['Töötervishoiu ja tööohutuse juhtimine', 'Töötervishoiu ja tööohutuse juhtimine (29)']
	];
var topic_question
	 = [
	
		['Töötervishoiu ja tööohutuse juhtimine', 'MM150_1', 'Töötervishoiu- ja tööohutusteenuste kasutamine: Töötervishoiuarst'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM150_2', 'Töötervishoiu- ja tööohutusteenuste kasutamine: Turvaekspert'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM150_3', 'Töötervishoiu- ja tööohutusteenuste kasutamine: Psühholoog'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM150_4', 'Töötervishoiu- ja tööohutusteenuste kasutamine: Ergonoomika ekspert, kes tegeleb töökoha korraldusega'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM150_5', 'Töötervishoiu- ja tööohutusteenuste kasutamine: Üldine tervise- ja ohutusalane konsultatsioon'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM152', 'Kas teie ettevõte tavaliselt uurib haigestumisest tingitud töölt puudumise põhjuseid?'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM153', 'Kas rakendate meetmeid, et toetada töötajate tagasipöördumist tööle pärast haigusest tingitud pikemat puudumist?'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM154', 'Kas te viite läbi regulaarselt töötajate meditsiinikontrolli?'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM155', 'Kas teie ettevõttes on olemas tervishoiu- ja ohutusalane strateegiadokument, välja töötatud juhtimissüsteem või tegevusplaan?'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM158', 'Kas tervishoiu- ja ohutusalaseid küsimusi käsitletakse kõrgema juhtkonna koosolekutel regulaarselt, mõnikord või praktiliselt mitte kunagi?'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM159', 'Kuidas te üldiselt hindate vahetute juhtide ja ülemuste panust tervishoiu- ja ohutusalasesse juhtimisse? Kas see on väga kõrge, üsna kõrge, üsna madal või väga madal?'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM161', 'Kas teie ettevõttes kontrollitakse regulaarselt töökohtade ohutust ja tervislikkust riskianalüüsi vms meetmete raames?'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM170', 'Kas tööinspektsioon on seda töökohta viimase 3 aasta jooksul külastanud, et kontrollida tervishoiu- ja ohutusalaseid tingimusi?'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM173_1', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Ametlikud töötervishoiu ja -ohutusega tegelevad asutused'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM173_2', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Euroopa Tööohutuse ja Töötervishoiu Agentuur'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM173_3', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Ettevõttesisesed tervishoiu- ja ohutusalased teenistused'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM173_4', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Tööinspektsioon'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM173_5', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Tööandjate organisatsioonid'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM173_6', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Ametiühingud'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM173_7', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Lepingulised tervishoiu- ja ohutuseksperdid'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM173_8', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Kindlustusfirmad'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM175', 'Kas olete teadlik Euroopa tööohutuse ja -tervishoiu nädalast?'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM200_1', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.: Ohtlikud ained (nt tolm, keemiline, bioloogiline või radioaktiivne)'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM200_2', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.: Õnnetusjuhtumid'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM200_3', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.: Müra ja vibratsioon'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM200_4', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.: Sellised luu-lihaskonna vaevused nagu seljavalu, valu kuklas, käsivartes või jalgades'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM200_5', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.: Tööga seotud stress'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM200_6', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.: Vägivald või vägivallaga ähvardamine'],
		['Töötervishoiu ja tööohutuse juhtimine', 'MM200_7', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.: Mõnitamine või kiusamine, nt solvamine, alandamine või vägivald kolleegide või ülemuste poolt'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM202_1', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Ajasurve'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM202_2', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Puudulik kommunikatsioon juhtkonna ja töötajate vahel'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM202_3', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Halb koostöö kolleegide vahel'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM202_4', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Töötajate vähene kontroll oma töökorralduse üle'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM202_5', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Töösuhte ebakindlus'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM202_6', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Vajadus tegeleda raskete klientide, patsientide, õpilastega jne.'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM202_7', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Probleemid ülemuse - töötaja suhetes'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM202_8', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Pikk või ebaregulaarne tööaeg'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM202_9', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Ebaselge inimressursside poliitika'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM202_10', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Diskrimineerimine (nt soost, vanusest või etnilisest päritolust tingitud)'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM250', 'Kas teie ettevõttel on kindlad tavad tööst tingitud stressiga tegelemiseks?'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM251', 'Kas on kindlad tavad mõnitamise või kiusamisega tegelemiseks?'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM252', 'Kas teil on kindlad tavad tööga seotud vägivallaga tegelemiseks?'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM253_1', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?: Muutused töökorraldused'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM253_2', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?: Tööala ümberkujundamine'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM253_3', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?: Töötajate konfidentsiaalne nõustamine'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM253_4', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?: Konfliktide lahendamise protseduuri kindlaksmääramine'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM253_5', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?: Muutused tööaja korralduses'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM253_6', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?: Väljaõppe pakkumine'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM256', 'Kas teie ettevõttes võetakse midagi ette, kui üksikud töötajad teevad liiga pikki tööpäevi või töötavad ebaregulaarse tööajaga?'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM259', 'Kas teavitate töötajaid psühhosotsiaalsetest riskidest ning nende mõjust tervisele ja ohutusele?'],
		['Psühhosotsiaalsed riskid ja nende ohjamine', 'MM260', 'Kas neile öeldi, kelle poole pöörduda, kui esineb psühhosotsiaalseid probleeme?'],
		['Ajendid ja tõkked', 'MM171_1', 'Asutuse töötervishoiu ja tööohutusega tegelemise põhjused: Seadusesätte täitmine'],
		['Ajendid ja tõkked', 'MM171_2', 'Asutuse töötervishoiu ja tööohutusega tegelemise põhjused: Töötajate või nende esindajate soovid'],
		['Ajendid ja tõkked', 'MM171_3', 'Asutuse töötervishoiu ja tööohutusega tegelemise põhjused: Personali säilitamine ja puudumistega tegelemine'],
		['Ajendid ja tõkked', 'MM171_4', 'Asutuse töötervishoiu ja tööohutusega tegelemise põhjused: Majanduslikud või tulemuslikkusega seotud põhjused'],
		['Ajendid ja tõkked', 'MM171_5', 'Asutuse töötervishoiu ja tööohutusega tegelemise põhjused: Klientide nõudel või mure organisatsiooni maine pärast'],
		['Ajendid ja tõkked', 'MM171_6', 'Asutuse töötervishoiu ja tööohutusega tegelemise põhjused: Tööinspektsiooni surve'],
		['Ajendid ja tõkked', 'MM172_1', 'Peamised takistused töötervishoiu ja tööohutusega tegelemisel: Ressursside puudumine, nt aeg, personal või raha'],
		['Ajendid ja tõkked', 'MM172_2', 'Peamised takistused töötervishoiu ja tööohutusega tegelemisel: Vähene teadlikkus'],
		['Ajendid ja tõkked', 'MM172_3', 'Peamised takistused töötervishoiu ja tööohutusega tegelemisel: Oskuste puudumine'],
		['Ajendid ja tõkked', 'MM172_4', 'Peamised takistused töötervishoiu ja tööohutusega tegelemisel: Tehnilise toe ja juhendamise puudumine'],
		['Ajendid ja tõkked', 'MM172_5', 'Peamised takistused töötervishoiu ja tööohutusega tegelemisel: Ettevõtte kultuur'],
		['Ajendid ja tõkked', 'MM172_6', 'Peamised takistused töötervishoiu ja tööohutusega tegelemisel: Küsimuse delikaatsus'],
		['Ajendid ja tõkked', 'MM300', 'Kas võrreldes muude ohutus- ja tervishoiualaste küsimustega on psühhosotsiaalsete riskidega tegelemine raskem, vähem raske või ei ole vahet?'],
		['Ajendid ja tõkked', 'MM302', 'Kas te olete kasutanud välisallikate infot või tuge, et tegelda tööl esinevate psühhosotsiaalsete riskidega?'],
		['Ajendid ja tõkked', 'MM303a', 'Kas vajaksite selles küsimuses lisainfot või tuge?'],
		['Töötaja osalus', 'MM350', 'Kas teie ettevõttes on olemas töönõukogu?'],
		['Töötaja osalus', 'MM351', 'Ning kas teie ettevõttes on ametiühing?'],
		['Töötaja osalus', 'MM355all', 'Kas teie ettevõttel on töökeskkonna volinik?'],
		['Töötaja osalus', 'MM358', 'Kas teie ettevõttes on olemas töökeskkonna nõukogu?']
	];
var question_
	 = [
	
		['MM150_1', 'Töötervishoiu- ja tööohutusteenuste kasutamine: Töötervishoiuarst'],
		['MM150_2', 'Töötervishoiu- ja tööohutusteenuste kasutamine: Turvaekspert'],
		['MM150_3', 'Töötervishoiu- ja tööohutusteenuste kasutamine: Psühholoog'],
		['MM150_4', 'Töötervishoiu- ja tööohutusteenuste kasutamine: Ergonoomika ekspert, kes tegeleb töökoha korraldusega'],
		['MM150_5', 'Töötervishoiu- ja tööohutusteenuste kasutamine: Üldine tervise- ja ohutusalane konsultatsioon'],
		['MM152', 'Kas teie ettevõte tavaliselt uurib haigestumisest tingitud töölt puudumise põhjuseid?'],
		['MM153', 'Kas rakendate meetmeid, et toetada töötajate tagasipöördumist tööle pärast haigusest tingitud pikemat puudumist?'],
		['MM154', 'Kas te viite läbi regulaarselt töötajate meditsiinikontrolli?'],
		['MM155', 'Kas teie ettevõttes on olemas tervishoiu- ja ohutusalane strateegiadokument, välja töötatud juhtimissüsteem või tegevusplaan?'],
		['MM158', 'Kas tervishoiu- ja ohutusalaseid küsimusi käsitletakse kõrgema juhtkonna koosolekutel regulaarselt, mõnikord või praktiliselt mitte kunagi?'],
		['MM159', 'Kuidas te üldiselt hindate vahetute juhtide ja ülemuste panust tervishoiu- ja ohutusalasesse juhtimisse? Kas see on väga kõrge, üsna kõrge, üsna madal või väga madal?'],
		['MM161', 'Kas teie ettevõttes kontrollitakse regulaarselt töökohtade ohutust ja tervislikkust riskianalüüsi vms meetmete raames?'],
		['MM170', 'Kas tööinspektsioon on seda töökohta viimase 3 aasta jooksul külastanud, et kontrollida tervishoiu- ja ohutusalaseid tingimusi?'],
		['MM173_1', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Ametlikud töötervishoiu ja -ohutusega tegelevad asutused'],
		['MM173_2', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Euroopa Tööohutuse ja Töötervishoiu Agentuur'],
		['MM173_3', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Ettevõttesisesed tervishoiu- ja ohutusalased teenistused'],
		['MM173_4', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Tööinspektsioon'],
		['MM173_5', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Tööandjate organisatsioonid'],
		['MM173_6', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Ametiühingud'],
		['MM173_7', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Lepingulised tervishoiu- ja ohutuseksperdid'],
		['MM173_8', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?: Kindlustusfirmad'],
		['MM175', 'Kas olete teadlik Euroopa tööohutuse ja -tervishoiu nädalast?'],
		['MM200_1', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.: Ohtlikud ained (nt tolm, keemiline, bioloogiline või radioaktiivne)'],
		['MM200_2', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.: Õnnetusjuhtumid'],
		['MM200_3', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.: Müra ja vibratsioon'],
		['MM200_4', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.: Sellised luu-lihaskonna vaevused nagu seljavalu, valu kuklas, käsivartes või jalgades'],
		['MM200_5', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.: Tööga seotud stress'],
		['MM200_6', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.: Vägivald või vägivallaga ähvardamine'],
		['MM200_7', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.: Mõnitamine või kiusamine, nt solvamine, alandamine või vägivald kolleegide või ülemuste poolt'],
		['MM202_1', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Ajasurve'],
		['MM202_2', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Puudulik kommunikatsioon juhtkonna ja töötajate vahel'],
		['MM202_3', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Halb koostöö kolleegide vahel'],
		['MM202_4', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Töötajate vähene kontroll oma töökorralduse üle'],
		['MM202_5', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Töösuhte ebakindlus'],
		['MM202_6', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Vajadus tegeleda raskete klientide, patsientide, õpilastega jne.'],
		['MM202_7', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Probleemid ülemuse - töötaja suhetes'],
		['MM202_8', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Pikk või ebaregulaarne tööaeg'],
		['MM202_9', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Ebaselge inimressursside poliitika'],
		['MM202_10', 'Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.: Diskrimineerimine (nt soost, vanusest või etnilisest päritolust tingitud)'],
		['MM250', 'Kas teie ettevõttel on kindlad tavad tööst tingitud stressiga tegelemiseks?'],
		['MM251', 'Kas on kindlad tavad mõnitamise või kiusamisega tegelemiseks?'],
		['MM252', 'Kas teil on kindlad tavad tööga seotud vägivallaga tegelemiseks?'],
		['MM253_1', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?: Muutused töökorraldused'],
		['MM253_2', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?: Tööala ümberkujundamine'],
		['MM253_3', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?: Töötajate konfidentsiaalne nõustamine'],
		['MM253_4', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?: Konfliktide lahendamise protseduuri kindlaksmääramine'],
		['MM253_5', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?: Muutused tööaja korralduses'],
		['MM253_6', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?: Väljaõppe pakkumine'],
		['MM256', 'Kas teie ettevõttes võetakse midagi ette, kui üksikud töötajad teevad liiga pikki tööpäevi või töötavad ebaregulaarse tööajaga?'],
		['MM259', 'Kas teavitate töötajaid psühhosotsiaalsetest riskidest ning nende mõjust tervisele ja ohutusele?'],
		['MM260', 'Kas neile öeldi, kelle poole pöörduda, kui esineb psühhosotsiaalseid probleeme?'],
		['MM171_1', 'Asutuse töötervishoiu ja tööohutusega tegelemise põhjused: Seadusesätte täitmine'],
		['MM171_2', 'Asutuse töötervishoiu ja tööohutusega tegelemise põhjused: Töötajate või nende esindajate soovid'],
		['MM171_3', 'Asutuse töötervishoiu ja tööohutusega tegelemise põhjused: Personali säilitamine ja puudumistega tegelemine'],
		['MM171_4', 'Asutuse töötervishoiu ja tööohutusega tegelemise põhjused: Majanduslikud või tulemuslikkusega seotud põhjused'],
		['MM171_5', 'Asutuse töötervishoiu ja tööohutusega tegelemise põhjused: Klientide nõudel või mure organisatsiooni maine pärast'],
		['MM171_6', 'Asutuse töötervishoiu ja tööohutusega tegelemise põhjused: Tööinspektsiooni surve'],
		['MM172_1', 'Peamised takistused töötervishoiu ja tööohutusega tegelemisel: Ressursside puudumine, nt aeg, personal või raha'],
		['MM172_2', 'Peamised takistused töötervishoiu ja tööohutusega tegelemisel: Vähene teadlikkus'],
		['MM172_3', 'Peamised takistused töötervishoiu ja tööohutusega tegelemisel: Oskuste puudumine'],
		['MM172_4', 'Peamised takistused töötervishoiu ja tööohutusega tegelemisel: Tehnilise toe ja juhendamise puudumine'],
		['MM172_5', 'Peamised takistused töötervishoiu ja tööohutusega tegelemisel: Ettevõtte kultuur'],
		['MM172_6', 'Peamised takistused töötervishoiu ja tööohutusega tegelemisel: Küsimuse delikaatsus'],
		['MM300', 'Kas võrreldes muude ohutus- ja tervishoiualaste küsimustega on psühhosotsiaalsete riskidega tegelemine raskem, vähem raske või ei ole vahet?'],
		['MM302', 'Kas te olete kasutanud välisallikate infot või tuge, et tegelda tööl esinevate psühhosotsiaalsete riskidega?'],
		['MM303a', 'Kas vajaksite selles küsimuses lisainfot või tuge?'],
		['MM350', 'Kas teie ettevõttes on olemas töönõukogu?'],
		['MM351', 'Ning kas teie ettevõttes on ametiühing?'],
		['MM355all', 'Kas teie ettevõttel on töökeskkonna volinik?'],
		['MM358', 'Kas teie ettevõttes on olemas töökeskkonna nõukogu?']
	];
var question_answer
	 = [
	
		['MM150_1', '1--Yes', 'Jah'],
		['MM150_1', '2--No', 'Ei'],
		['MM150_1', '3--DK--NA', 'Vastamata'],
		['MM150_2', '1--Yes', 'Jah'],
		['MM150_2', '2--No', 'Ei'],
		['MM150_2', '3--DK--NA', 'Vastamata'],
		['MM150_3', '1--Yes', 'Jah'],
		['MM150_3', '2--No', 'Ei'],
		['MM150_3', '3--DK--NA', 'Vastamata'],
		['MM150_4', '1--Yes', 'Jah'],
		['MM150_4', '2--No', 'Ei'],
		['MM150_4', '3--DK--NA', 'Vastamata'],
		['MM150_5', '1--Yes', 'Jah'],
		['MM150_5', '2--No', 'Ei'],
		['MM150_5', '3--DK--NA', 'Vastamata'],
		['MM152', '1--Yes', 'Jah'],
		['MM152', '2--No', 'Ei'],
		['MM152', '3--DK--NA', 'Vastamata'],
		['MM153', '1--Yes', 'Jah'],
		['MM153', '2--No', 'Ei'],
		['MM153', '3--DK--NA', 'Vastamata'],
		['MM154', '1--Yes', 'Jah'],
		['MM154', '2--No', 'Ei'],
		['MM154', '3--DK--NA', 'Vastamata'],
		['MM155', '1--Yes', 'Jah'],
		['MM155', '2--No', 'Ei'],
		['MM155', '3--DK--NA', 'Vastamata'],
		['MM158', '1--Regularly', 'Regulaarselt'],
		['MM158', '2--Occasionally', 'Mõnikord'],
		['MM158', '3--Practically-never', 'Peaaegu mitte kunagi'],
		['MM158', '4--DK--NA', 'Vastamata'],
		['MM159', '1--Very-high', 'Väga kõrge'],
		['MM159', '2--Quite-high', 'Üsna kõrge'],
		['MM159', '3--Quite-low', 'Üsna madal'],
		['MM159', '4--Very-low', 'Väga madal'],
		['MM159', '5--DK--NA', 'Vastamata'],
		['MM161', '1--Yes', 'Jah'],
		['MM161', '2--No', 'Ei'],
		['MM161', '3--DK--NA', 'Vastamata'],
		['MM170', '1--Yes', 'Jah'],
		['MM170', '2--No', 'Ei'],
		['MM170', '3--DK--NA', 'Vastamata'],
		['MM171_1', '1--Major', 'Zelo'],
		['MM171_1', '2--Minor', 'Manj'],
		['MM171_1', '3--No', 'Ni'],
		['MM171_1', '4--DK--NA', 'Vastamata'],
		['MM171_2', '1--Major', 'Zelo'],
		['MM171_2', '2--Minor', 'Manj'],
		['MM171_2', '3--No', 'Ni'],
		['MM171_2', '4--DK--NA', 'Vastamata'],
		['MM171_3', '1--Major', 'Zelo'],
		['MM171_3', '2--Minor', 'Manj'],
		['MM171_3', '3--No', 'Ni'],
		['MM171_3', '4--DK--NA', 'Vastamata'],
		['MM171_4', '1--Major', 'Zelo'],
		['MM171_4', '2--Minor', 'Manj'],
		['MM171_4', '3--No', 'Ni'],
		['MM171_4', '4--DK--NA', 'Vastamata'],
		['MM171_5', '1--Major', 'Zelo'],
		['MM171_5', '2--Minor', 'Manj'],
		['MM171_5', '3--No', 'Ni'],
		['MM171_5', '4--DK--NA', 'Vastamata'],
		['MM171_6', '1--Major', 'Zelo'],
		['MM171_6', '2--Minor', 'Manj'],
		['MM171_6', '3--No', 'Ni'],
		['MM171_6', '4--DK--NA', 'Vastamata'],
		['MM172_1', '1--Major', 'Velika'],
		['MM172_1', '2--Minor', 'Manjša '],
		['MM172_1', '3--No', 'Ni'],
		['MM172_1', '4--DK--NA', 'Vastamata'],
		['MM172_2', '1--Major', 'Velika'],
		['MM172_2', '2--Minor', 'Manjša '],
		['MM172_2', '3--No', 'Ni'],
		['MM172_2', '4--DK--NA', 'Vastamata'],
		['MM172_3', '1--Major', 'Velika'],
		['MM172_3', '2--Minor', 'Manjša '],
		['MM172_3', '3--No', 'Ni'],
		['MM172_3', '4--DK--NA', 'Vastamata'],
		['MM172_4', '1--Major', 'Velika'],
		['MM172_4', '2--Minor', 'Manjša '],
		['MM172_4', '3--No', 'Ni'],
		['MM172_4', '4--DK--NA', 'Vastamata'],
		['MM172_5', '1--Major', 'Velika'],
		['MM172_5', '2--Minor', 'Manjša '],
		['MM172_5', '3--No', 'Ni'],
		['MM172_5', '4--DK--NA', 'Vastamata'],
		['MM172_6', '1--Major', 'Velika'],
		['MM172_6', '2--Minor', 'Manjša '],
		['MM172_6', '3--No', 'Ni'],
		['MM172_6', '4--DK--NA', 'Vastamata'],
		['MM173_1', '1--Yes', 'Jah'],
		['MM173_1', '2--No', 'Ei'],
		['MM173_1', '3--DK--NA', 'Vastamata'],
		['MM173_2', '1--Yes', 'Jah'],
		['MM173_2', '2--No', 'Ei'],
		['MM173_2', '3--DK--NA', 'Vastamata'],
		['MM173_3', '1--Yes', 'Jah'],
		['MM173_3', '2--No', 'Ei'],
		['MM173_3', '3--DK--NA', 'Vastamata'],
		['MM173_4', '1--Yes', 'Jah'],
		['MM173_4', '2--No', 'Ei'],
		['MM173_4', '3--DK--NA', 'Vastamata'],
		['MM173_5', '1--Yes', 'Jah'],
		['MM173_5', '2--No', 'Ei'],
		['MM173_5', '3--DK--NA', 'Vastamata'],
		['MM173_6', '1--Yes', 'Jah'],
		['MM173_6', '2--No', 'Ei'],
		['MM173_6', '3--DK--NA', 'Vastamata'],
		['MM173_7', '1--Yes', 'Jah'],
		['MM173_7', '2--No', 'Ei'],
		['MM173_7', '3--DK--NA', 'Vastamata'],
		['MM173_8', '1--Yes', 'Jah'],
		['MM173_8', '2--No', 'Ei'],
		['MM173_8', '3--DK--NA', 'Vastamata'],
		['MM175', '1--Yes', 'Jah'],
		['MM175', '2--No', 'Ei'],
		['MM175', '3--DK--NA', 'Vastamata'],
		['MM200_1', '1--Major-concern', 'Suur probleem'],
		['MM200_1', '2--Some-concern', 'Mõningane probleem'],
		['MM200_1', '3--No-concern', 'Ei ole probleemiks'],
		['MM200_1', '4--DK--NA', 'Vastamata'],
		['MM200_2', '1--Major-concern', 'Suur probleem'],
		['MM200_2', '2--Some-concern', 'Mõningane probleem'],
		['MM200_2', '3--No-concern', 'Ei ole probleemiks'],
		['MM200_2', '4--DK--NA', 'Vastamata'],
		['MM200_3', '1--Major-concern', 'Suur probleem'],
		['MM200_3', '2--Some-concern', 'Mõningane probleem'],
		['MM200_3', '3--No-concern', 'Ei ole probleemiks'],
		['MM200_3', '4--DK--NA', 'Vastamata'],
		['MM200_4', '1--Major-concern', 'Suur probleem'],
		['MM200_4', '2--Some-concern', 'Mõningane probleem'],
		['MM200_4', '3--No-concern', 'Ei ole probleemiks'],
		['MM200_4', '4--DK--NA', 'Vastamata'],
		['MM200_5', '1--Major-concern', 'Suur probleem'],
		['MM200_5', '2--Some-concern', 'Mõningane probleem'],
		['MM200_5', '3--No-concern', 'Ei ole probleemiks'],
		['MM200_5', '4--DK--NA', 'Vastamata'],
		['MM200_6', '1--Major-concern', 'Suur probleem'],
		['MM200_6', '2--Some-concern', 'Mõningane probleem'],
		['MM200_6', '3--No-concern', 'Ei ole probleemiks'],
		['MM200_6', '4--DK--NA', 'Vastamata'],
		['MM200_7', '1--Major-concern', 'Suur probleem'],
		['MM200_7', '2--Some-concern', 'Mõningane probleem'],
		['MM200_7', '3--No-concern', 'Ei ole probleemiks'],
		['MM200_7', '4--DK--NA', 'Vastamata'],
		['MM202_1', '1--Yes', 'Jah'],
		['MM202_1', '2--No', 'Ei'],
		['MM202_1', '3--DK--NA', 'Vastamata'],
		['MM202_10', '1--Yes', 'Jah'],
		['MM202_10', '2--No', 'Ei'],
		['MM202_10', '3--DK--NA', 'Vastamata'],
		['MM202_2', '1--Yes', 'Jah'],
		['MM202_2', '2--No', 'Ei'],
		['MM202_2', '3--DK--NA', 'Vastamata'],
		['MM202_3', '1--Yes', 'Jah'],
		['MM202_3', '2--No', 'Ei'],
		['MM202_3', '3--DK--NA', 'Vastamata'],
		['MM202_4', '1--Yes', 'Jah'],
		['MM202_4', '2--No', 'Ei'],
		['MM202_4', '3--DK--NA', 'Vastamata'],
		['MM202_5', '1--Yes', 'Jah'],
		['MM202_5', '2--No', 'Ei'],
		['MM202_5', '3--DK--NA', 'Vastamata'],
		['MM202_6', '1--Yes', 'Jah'],
		['MM202_6', '2--No', 'Ei'],
		['MM202_6', '3--DK--NA', 'Vastamata'],
		['MM202_7', '1--Yes', 'Jah'],
		['MM202_7', '2--No', 'Ei'],
		['MM202_7', '3--DK--NA', 'Vastamata'],
		['MM202_8', '1--Yes', 'Jah'],
		['MM202_8', '2--No', 'Ei'],
		['MM202_8', '3--DK--NA', 'Vastamata'],
		['MM202_9', '1--Yes', 'Jah'],
		['MM202_9', '2--No', 'Ei'],
		['MM202_9', '3--DK--NA', 'Vastamata'],
		['MM250', '1--Yes', 'Jah'],
		['MM250', '2--No', 'Ei'],
		['MM250', '3--Work-related-stress-is-not-an-issue-in-our-establishment', 'Tööst tingitud stress ei ole meie ettevõttes probleemiks'],
		['MM250', '4--No-answer', 'Vastamata'],
		['MM251', '1--Yes', 'Jah'],
		['MM251', '2--No', 'Ei'],
		['MM251', '3--These-problems-are-not-an-issue-in-our-establishment', 'Need küsimused ei ole meie ettevõtte jaoks probleemid'],
		['MM251', '4--No-answer', 'Vastamata'],
		['MM252', '1--Yes', 'Jah'],
		['MM252', '2--No', 'Ei'],
		['MM252', '3--Work-related-violence-is-not-an-issue-in-our-establishment', 'Tööga seotud vägivald ei ole meie ettevõttes probleemiks'],
		['MM252', '4--No-answer', 'Vastamata'],
		['MM253_1', '1--Yes', 'Jah'],
		['MM253_1', '2--No', 'Ei'],
		['MM253_1', '3--DK--NA', 'Vastamata'],
		['MM253_2', '1--Yes', 'Jah'],
		['MM253_2', '2--No', 'Ei'],
		['MM253_2', '3--DK--NA', 'Vastamata'],
		['MM253_3', '1--Yes', 'Jah'],
		['MM253_3', '2--No', 'Ei'],
		['MM253_3', '3--DK--NA', 'Vastamata'],
		['MM253_4', '1--Yes', 'Jah'],
		['MM253_4', '2--No', 'Ei'],
		['MM253_4', '3--DK--NA', 'Vastamata'],
		['MM253_5', '1--Yes', 'Jah'],
		['MM253_5', '2--No', 'Ei'],
		['MM253_5', '3--DK--NA', 'Vastamata'],
		['MM253_6', '1--Yes', 'Jah'],
		['MM253_6', '2--No', 'Ei'],
		['MM253_6', '3--DK--NA', 'Vastamata'],
		['MM256', '1--Yes', 'Jah'],
		['MM256', '2--No', 'Ei'],
		['MM256', '3--Long-or-irregular-working-hours-are-not-an-issue-in-our-esta', 'Pikk või ebaregulaarne tööaeg ei ole meie ettevõttes probleemiks'],
		['MM256', '4--No-answer', 'Vastamata'],
		['MM259', '1--Yes', 'Jah'],
		['MM259', '2--No', 'Ei'],
		['MM259', '3--No-answer', 'Vastamata'],
		['MM260', '1--Yes', 'Jah'],
		['MM260', '2--No', 'Ei'],
		['MM260', '3--No-answer', 'Vastamata'],
		['MM300', '1--More-difficult', 'Raskem'],
		['MM300', '2--Less-difficult', 'Vähem raske'],
		['MM300', '3--No-difference', 'Vahet ei ole'],
		['MM300', '4--No-answer', 'Vastamata'],
		['MM302', '1--Yes', 'Jah'],
		['MM302', '2--No', 'Ei'],
		['MM302', '3--No-answer', 'Vastamata'],
		['MM303a', '1--Yes', 'Jah'],
		['MM303a', '2--No', 'Ei'],
		['MM303a', '3--No-answer', 'Vastamata'],
		['MM350', '1--Yes', 'Jah'],
		['MM350', '2--No', 'Ei'],
		['MM350', '3--No-answer', 'Vastamata'],
		['MM351', '1--Yes', 'Jah'],
		['MM351', '2--No', 'Ei'],
		['MM351', '3--No-answer', 'Vastamata'],
		['MM355all', '1--Yes', 'Jah'],
		['MM355all', '2--No', 'Ei'],
		['MM355all', '3--No-answer', 'Vastamata'],
		['MM358', '1--Yes', 'Jah'],
		['MM358', '2--No', 'Ei'],
		['MM358', '3--No-answer', 'Vastamata']
	];
var country_
	 = [
	
		['AT', 'Austria'],
		['BE', 'Belgia'],
		['BG', 'Bulgaaria'],
		['CH', 'Šveits'],
		['CY', 'Küpros'],
		['CZ', 'Tšehhi'],
		['DE', 'Saksamaa'],
		['DK', 'Taani'],
		['EE', 'Eesti'],
		['EL', 'Kreeka'],
		['ES', 'Hispaania'],
		['FI', 'Soome'],
		['FR', 'Prantsusmaa'],
		['HR', 'Horvaatia *'],
		['HU', 'Ungari'],
		['IE', 'Iirimaa'],
		['IT', 'Itaalia'],
		['LT', 'Leedu'],
		['LU', 'Luksemburg'],
		['LV', 'Läti'],
		['MT', 'Malta'],
		['NL', 'Madalmaad'],
		['NO', 'Norra'],
		['PL', 'Poola'],
		['PT', 'Portugal'],
		['RO', 'Rumeenia'],
		['SE', 'Rootsi'],
		['SI', 'Sloveenia'],
		['SK', 'Slovakkia'],
		['TR', 'Türgi'],
		['UK', 'Ühendkuningriik'],
		['EuropeanUnion', 'Euroopa Liit *']
	];
var question_meta
	 = [
	
		['MM150_1', 'Töötervishoiuarst', 'Milliseid tervishoiu- ja ohutusteenuseid te kasutate, kas ettevõtte sees või väljaspool?Töötervishoiuarst'],
		['MM150_2', 'Turvaekspert', 'Milliseid tervishoiu- ja ohutusteenuseid te kasutate, kas ettevõtte sees või väljaspool?Turvaekspert'],
		['MM150_3', 'Psühholoog', 'Milliseid tervishoiu- ja ohutusteenuseid te kasutate, kas ettevõtte sees või väljaspool?Psühholoog'],
		['MM150_4', 'Ergonoomika ekspert, kes tegeleb töökoha korraldusega', 'Milliseid tervishoiu- ja ohutusteenuseid te kasutate, kas ettevõtte sees või väljaspool?Ergonoomika ekspert, kes tegeleb töökoha korraldusega'],
		['MM150_5', 'Üldine tervise- ja ohutusalane konsultatsioon', 'Milliseid tervishoiu- ja ohutusteenuseid te kasutate, kas ettevõtte sees või väljaspool?Üldine tervise- ja ohutusalane konsultatsioon'],
		['MM152', 'Kas teie ettevõte tavaliselt uurib haigestumisest tingitud töölt puudumise põhjuseid?', 'Kas teie ettevõte tavaliselt uurib haigestumisest tingitud töölt puudumise põhjuseid?'],
		['MM153', 'Kas rakendate meetmeid, et toetada töötajate tagasipöördumist tööle pärast haigusest tingitud pikemat puudumist?', 'Kas rakendate meetmeid, et toetada töötajate tagasipöördumist tööle pärast haigusest tingitud pikemat puudumist?'],
		['MM154', 'Kas te viite läbi regulaarselt töötajate meditsiinikontrolli?', 'Kas te viite läbi regulaarselt töötajate meditsiinikontrolli?'],
		['MM155', 'Kas teie ettevõttes on olemas tervishoiu- ja ohutusalane strateegiadokument, välja töötatud juhtimissüsteem või tegevusplaan?', 'Kas teie ettevõttes on olemas tervishoiu- ja ohutusalane strateegiadokument, välja töötatud juhtimissüsteem või tegevusplaan?'],
		['MM158', 'Kas tervishoiu- ja ohutusalaseid küsimusi käsitletakse kõrgema juhtkonna koosolekutel regulaarselt, mõnikord või praktiliselt mitte kunagi?', 'Kas tervishoiu- ja ohutusalaseid küsimusi käsitletakse kõrgema juhtkonna koosolekutel regulaarselt, mõnikord või praktiliselt mitte kunagi?'],
		['MM159', 'Kuidas te üldiselt hindate vahetute juhtide ja ülemuste panust tervishoiu- ja ohutusalasesse juhtimisse? Kas see on väga kõrge, üsna kõrge, üsna madal või väga madal?', 'Kuidas te üldiselt hindate vahetute juhtide ja ülemuste panust tervishoiu- ja ohutusalasesse juhtimisse? Kas see on väga kõrge, üsna kõrge, üsna madal või väga madal?'],
		['MM161', 'Kas teie ettevõttes kontrollitakse regulaarselt töökohtade ohutust ja tervislikkust riskianalüüsi vms meetmete raames?', 'Kas teie ettevõttes kontrollitakse regulaarselt töökohtade ohutust ja tervislikkust riskianalüüsi vms meetmete raames?'],
		['MM170', 'Kas tööinspektsioon on seda töökohta viimase 3 aasta jooksul külastanud, et kontrollida tervishoiu- ja ohutusalaseid tingimusi?', 'Kas tööinspektsioon on seda töökohta viimase 3 aasta jooksul külastanud, et kontrollida tervishoiu- ja ohutusalaseid tingimusi?'],
		['MM173_1', 'Ametlikud töötervishoiu ja -ohutusega tegelevad asutused', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?Ametlikud töötervishoiu ja -ohutusega tegelevad asutused'],
		['MM173_2', 'Euroopa Tööohutuse ja Töötervishoiu Agentuur', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?Euroopa Tööohutuse ja Töötervishoiu Agentuur'],
		['MM173_3', 'Ettevõttesisesed tervishoiu- ja ohutusalased teenistused', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?Ettevõttesisesed tervishoiu- ja ohutusalased teenistused'],
		['MM173_4', 'Tööinspektsioon', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?Tööinspektsioon'],
		['MM173_5', 'Tööandjate organisatsioonid', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?Tööandjate organisatsioonid'],
		['MM173_6', 'Ametiühingud', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?Ametiühingud'],
		['MM173_7', 'Lepingulised tervishoiu- ja ohutuseksperdid', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?Lepingulised tervishoiu- ja ohutuseksperdid'],
		['MM173_8', 'Kindlustusfirmad', 'Kas teie ettevõte on kasutanud tervishoiu- ja ohutusalast infot mõnelt järgmiselt organisatsioonilt või institutsioonilt?Kindlustusfirmad'],
		['MM175', 'Kas olete teadlik Euroopa tööohutuse ja -tervishoiu nädalast?', 'Kas olete teadlik Euroopa tööohutuse ja -tervishoiu nädalast?'],
		['MM200_1', 'Ohtlikud ained (nt tolm, keemiline, bioloogiline või radioaktiivne)', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.Ohtlikud ained (nt tolm, keemiline, bioloogiline või radioaktiivne)'],
		['MM200_2', 'Õnnetusjuhtumid', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.Õnnetusjuhtumid'],
		['MM200_3', 'Müra ja vibratsioon', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.Müra ja vibratsioon'],
		['MM200_4', 'Sellised luu-lihaskonna vaevused nagu seljavalu, valu kuklas, käsivartes või jalgades', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.Sellised luu-lihaskonna vaevused nagu seljavalu, valu kuklas, käsivartes või jalgades'],
		['MM200_5', 'Tööga seotud stress', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.Tööga seotud stress'],
		['MM200_6', 'Vägivald või vägivallaga ähvardamine', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.Vägivald või vägivallaga ähvardamine'],
		['MM200_7', 'Mõnitamine või kiusamine, nt solvamine, alandamine või vägivald kolleegide või ülemuste poolt', 'Palun öelge iga järgmise valdkonna kohta, kas see valmistab teie ettevõttele suurt muret, mõningal määral muret või ei valmista üldse muret.Mõnitamine või kiusamine, nt solvamine, alandamine või vägivald kolleegide või ülemuste poolt'],
		['MM202_1', 'Ajasurve', 'Stressi, vägivalda ja kiusamist töökohal mõjutavad mitmed tegurid; need puudutavad töökorraldust ja neist räägitakse sageli kui "psühhosotsiaalsetest riskidest". Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.Ajasurve'],
		['MM202_2', 'Puudulik kommunikatsioon juhtkonna ja töötajate vahel', 'Stressi, vägivalda ja kiusamist töökohal mõjutavad mitmed tegurid; need puudutavad töökorraldust ja neist räägitakse sageli kui "psühhosotsiaalsetest riskidest". Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.Puudulik kommunikatsioon juhtkonna ja töötajate vahel'],
		['MM202_3', 'Halb koostöö kolleegide vahel', 'Stressi, vägivalda ja kiusamist töökohal mõjutavad mitmed tegurid; need puudutavad töökorraldust ja neist räägitakse sageli kui "psühhosotsiaalsetest riskidest". Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.Halb koostöö kolleegide vahel'],
		['MM202_4', 'Töötajate vähene kontroll oma töökorralduse üle', 'Stressi, vägivalda ja kiusamist töökohal mõjutavad mitmed tegurid; need puudutavad töökorraldust ja neist räägitakse sageli kui "psühhosotsiaalsetest riskidest". Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.Töötajate vähene kontroll oma töökorralduse üle'],
		['MM202_5', 'Töösuhte ebakindlus', 'Stressi, vägivalda ja kiusamist töökohal mõjutavad mitmed tegurid; need puudutavad töökorraldust ja neist räägitakse sageli kui "psühhosotsiaalsetest riskidest". Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.Töösuhte ebakindlus'],
		['MM202_6', 'Vajadus tegeleda raskete klientide, patsientide, õpilastega jne.', 'Stressi, vägivalda ja kiusamist töökohal mõjutavad mitmed tegurid; need puudutavad töökorraldust ja neist räägitakse sageli kui "psühhosotsiaalsetest riskidest". Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.Vajadus tegeleda raskete klientide, patsientide, õpilastega jne.'],
		['MM202_7', 'Probleemid ülemuse - töötaja suhetes', 'Stressi, vägivalda ja kiusamist töökohal mõjutavad mitmed tegurid; need puudutavad töökorraldust ja neist räägitakse sageli kui "psühhosotsiaalsetest riskidest". Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.Probleemid ülemuse - töötaja suhetes'],
		['MM202_8', 'Pikk või ebaregulaarne tööaeg', 'Stressi, vägivalda ja kiusamist töökohal mõjutavad mitmed tegurid; need puudutavad töökorraldust ja neist räägitakse sageli kui "psühhosotsiaalsetest riskidest". Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.Pikk või ebaregulaarne tööaeg'],
		['MM202_9', 'Ebaselge inimressursside poliitika', 'Stressi, vägivalda ja kiusamist töökohal mõjutavad mitmed tegurid; need puudutavad töökorraldust ja neist räägitakse sageli kui "psühhosotsiaalsetest riskidest". Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.Ebaselge inimressursside poliitika'],
		['MM202_10', 'Diskrimineerimine (nt soost, vanusest või etnilisest päritolust tingitud)', 'Stressi, vägivalda ja kiusamist töökohal mõjutavad mitmed tegurid; need puudutavad töökorraldust ja neist räägitakse sageli kui "psühhosotsiaalsetest riskidest". Palun öelge, kas mõni järgmistest psühhosotsiaalsetest riskidest on teie ettevõttes valupunktiks.Diskrimineerimine (nt soost, vanusest või etnilisest päritolust tingitud)'],
		['MM250', 'Kas teie ettevõttel on kindlad tavad tööst tingitud stressiga tegelemiseks?', 'Kas teie ettevõttel on kindlad tavad tööst tingitud stressiga tegelemiseks?'],
		['MM251', 'Kas on kindlad tavad mõnitamise või kiusamisega tegelemiseks?', 'Kas on kindlad tavad mõnitamise või kiusamisega tegelemiseks?'],
		['MM252', 'Kas teil on kindlad tavad tööga seotud vägivallaga tegelemiseks?', 'Kas teil on kindlad tavad tööga seotud vägivallaga tegelemiseks?'],
		['MM253_1', 'Muutused töökorraldused', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?Muutused töökorraldused'],
		['MM253_2', 'Tööala ümberkujundamine', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?Tööala ümberkujundamine'],
		['MM253_3', 'Töötajate konfidentsiaalne nõustamine', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?Töötajate konfidentsiaalne nõustamine'],
		['MM253_4', 'Konfliktide lahendamise protseduuri kindlaksmääramine', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?Konfliktide lahendamise protseduuri kindlaksmääramine'],
		['MM253_5', 'Muutused tööaja korralduses', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?Muutused tööaja korralduses'],
		['MM253_6', 'Väljaõppe pakkumine', 'Kas teie ettevõte on viimase 3 aasta jooksul kasutanud psühhosotsiaalsete riskidega tegelemiseks mõnda järgmistest meetmetest?Väljaõppe pakkumine'],
		['MM256', 'Kas teie ettevõttes võetakse midagi ette, kui üksikud töötajad teevad liiga pikki tööpäevi või töötavad ebaregulaarse tööajaga?', 'Kas teie ettevõttes võetakse midagi ette, kui üksikud töötajad teevad liiga pikki tööpäevi või töötavad ebaregulaarse tööajaga?'],
		['MM259', 'Kas teavitate töötajaid psühhosotsiaalsetest riskidest ning nende mõjust tervisele ja ohutusele?', 'Kas teavitate töötajaid psühhosotsiaalsetest riskidest ning nende mõjust tervisele ja ohutusele?'],
		['MM260', 'Kas neile öeldi, kelle poole pöörduda, kui esineb psühhosotsiaalseid probleeme?', 'Kas neile öeldi, kelle poole pöörduda, kui esineb psühhosotsiaalseid probleeme?'],
		['MM171_1', 'Seadusesätte täitmine', 'Kuivõrd olulised on teie ettevõttele järgmised põhjused tervishoiu- ja ohutusalaste küsimustega tegelemiseks? Palun öelge iga põhjuse puhul, kas see on oluline põhjus, väheoluline põhjus või ei ole üldse põhjuseks.Seadusesätte täitmine'],
		['MM171_2', 'Töötajate või nende esindajate soovid', 'Kuivõrd olulised on teie ettevõttele järgmised põhjused tervishoiu- ja ohutusalaste küsimustega tegelemiseks? Palun öelge iga põhjuse puhul, kas see on oluline põhjus, väheoluline põhjus või ei ole üldse põhjuseks.Töötajate või nende esindajate soovid'],
		['MM171_3', 'Personali säilitamine ja puudumistega tegelemine', 'Kuivõrd olulised on teie ettevõttele järgmised põhjused tervishoiu- ja ohutusalaste küsimustega tegelemiseks? Palun öelge iga põhjuse puhul, kas see on oluline põhjus, väheoluline põhjus või ei ole üldse põhjuseks.Personali säilitamine ja puudumistega tegelemine'],
		['MM171_4', 'Majanduslikud või tulemuslikkusega seotud põhjused', 'Kuivõrd olulised on teie ettevõttele järgmised põhjused tervishoiu- ja ohutusalaste küsimustega tegelemiseks? Palun öelge iga põhjuse puhul, kas see on oluline põhjus, väheoluline põhjus või ei ole üldse põhjuseks.Majanduslikud või tulemuslikkusega seotud põhjused'],
		['MM171_5', 'Klientide nõudel või mure organisatsiooni maine pärast', 'Kuivõrd olulised on teie ettevõttele järgmised põhjused tervishoiu- ja ohutusalaste küsimustega tegelemiseks? Palun öelge iga põhjuse puhul, kas see on oluline põhjus, väheoluline põhjus või ei ole üldse põhjuseks.Klientide nõudel või mure organisatsiooni maine pärast'],
		['MM171_6', 'Tööinspektsiooni surve', 'Kuivõrd olulised on teie ettevõttele järgmised põhjused tervishoiu- ja ohutusalaste küsimustega tegelemiseks? Palun öelge iga põhjuse puhul, kas see on oluline põhjus, väheoluline põhjus või ei ole üldse põhjuseks.Tööinspektsiooni surve'],
		['MM172_1', 'Ressursside puudumine, nt aeg, personal või raha', 'Millised on teie ettevõttele põhilised raskused tervishoiu ja ohutusega tegelemisel? Palun öelge iga järgmise põhjuse kohta, kas see on oluline, väheoluline või ei ole üldse oluline.Ressursside puudumine, nt aeg, personal või raha'],
		['MM172_2', 'Vähene teadlikkus', 'Millised on teie ettevõttele põhilised raskused tervishoiu ja ohutusega tegelemisel? Palun öelge iga järgmise põhjuse kohta, kas see on oluline, väheoluline või ei ole üldse oluline.Vähene teadlikkus'],
		['MM172_3', 'Oskuste puudumine', 'Millised on teie ettevõttele põhilised raskused tervishoiu ja ohutusega tegelemisel? Palun öelge iga järgmise põhjuse kohta, kas see on oluline, väheoluline või ei ole üldse oluline.Oskuste puudumine'],
		['MM172_4', 'Tehnilise toe ja juhendamise puudumine', 'Millised on teie ettevõttele põhilised raskused tervishoiu ja ohutusega tegelemisel? Palun öelge iga järgmise põhjuse kohta, kas see on oluline, väheoluline või ei ole üldse oluline.Tehnilise toe ja juhendamise puudumine'],
		['MM172_5', 'Ettevõtte kultuur', 'Millised on teie ettevõttele põhilised raskused tervishoiu ja ohutusega tegelemisel? Palun öelge iga järgmise põhjuse kohta, kas see on oluline, väheoluline või ei ole üldse oluline.Ettevõtte kultuur'],
		['MM172_6', 'Küsimuse delikaatsus', 'Millised on teie ettevõttele põhilised raskused tervishoiu ja ohutusega tegelemisel? Palun öelge iga järgmise põhjuse kohta, kas see on oluline, väheoluline või ei ole üldse oluline.Küsimuse delikaatsus'],
		['MM300', 'Kas võrreldes muude ohutus- ja tervishoiualaste küsimustega on psühhosotsiaalsete riskidega tegelemine raskem, vähem raske või ei ole vahet?', 'Kas võrreldes muude ohutus- ja tervishoiualaste küsimustega on psühhosotsiaalsete riskidega tegelemine raskem, vähem raske või ei ole vahet?'],
		['MM302', 'Kas te olete kasutanud välisallikate infot või tuge, et tegelda tööl esinevate psühhosotsiaalsete riskidega?', 'Kas te olete kasutanud välisallikate infot või tuge, et tegelda tööl esinevate psühhosotsiaalsete riskidega?'],
		['MM303a', 'Kas vajaksite selles küsimuses lisainfot või tuge?', 'Kas vajaksite selles küsimuses lisainfot või tuge?<br><br>Küsimus ettevõtetele, kes teatavad, et on kasutanud välisallikate teavet või tuge, et tegelda tööl esinevate psühhosotsiaalsete riskidega.'],
		['MM350', 'Kas teie ettevõttes on olemas töönõukogu?', 'Kas teie ettevõttes on olemas töönõukogu?'],
		['MM351', 'Ning kas teie ettevõttes on ametiühing?', 'Ning kas teie ettevõttes on ametiühing?'],
		['MM355all', 'Kas teie ettevõttel on töökeskkonna volinik?', 'Kas teie ettevõttel on töökeskkonna volinik?<br><br>NL: Kas teie ettevõttes on olemas töökeskkonna volinik?'],
		['MM358', 'Kas teie ettevõttes on olemas töökeskkonna nõukogu?', 'Kas teie ettevõttes on olemas töökeskkonna nõukogu?']
	];
