//Auto Generated file
var subset_
	 = [
	
		['sec3', 'Toiminta-ala'],
		['size_4', 'Toimipaikan koko']
	];
var subset_subsetValue
	 = [
	
		['sec3', 'All', 'Kaikki'],
		['sec3', '1--Producing-Industries', 'Tuotantosektori'],
		['sec3', '2--Private-Services', 'Yksityiset palvelut'],
		['sec3', '3--Public-Services', 'Julkiset palvelut'],
		['size_4', 'All', 'Kaikki'],
		['size_4', '1--10-to-19-employees', '10 – 19 työntekijää'],
		['size_4', '2--20-to-49-employees', '20 – 49 työntekijää'],
		['size_4', '3--50-to-249-employees', '50 – 249 työntekijää'],
		['size_4', '4--250-employees-or-more', '250 työntekijää tai enemmän']
	];
var topic_
	 = [
	
		['', 'Kaikki (70)'],
		['Edistäjät ja esteet', 'Edistäjät ja esteet (15)'],
		['Psykososiaaliset riskit ja niiden hallinta', 'Psykososiaaliset riskit ja niiden hallinta (22)'],
		['Työntekijöiden osallistuminen', 'Työntekijöiden osallistuminen (4)'],
		['Työsuojelun hallinta', 'Työsuojelun hallinta (29)']
	];
var topic_question
	 = [
	
		['Työsuojelun hallinta', 'MM150_1', 'Työsuojelupalvelujen käyttö: Työterveyslääkäriä'],
		['Työsuojelun hallinta', 'MM150_2', 'Työsuojelupalvelujen käyttö: Turvallisuusasiantuntijaa'],
		['Työsuojelun hallinta', 'MM150_3', 'Työsuojelupalvelujen käyttö: Psykologia'],
		['Työsuojelun hallinta', 'MM150_4', 'Työsuojelupalvelujen käyttö: Ergonomian tai vastaavaa asiantuntijaa, joka käsittelee fyysistä työympäristöä'],
		['Työsuojelun hallinta', 'MM150_5', 'Työsuojelupalvelujen käyttö: Yleistä terveys- ja turvallisuusasiantuntijaa'],
		['Työsuojelun hallinta', 'MM152', 'Analysoidaanko toimipaikassanne järjestelmällisesti sairauspoissaolojen syitä?'],
		['Työsuojelun hallinta', 'MM153', 'Tuetteko pitkältä sairauslomalta palaavien työntekijöiden työhönpaluuta?'],
		['Työsuojelun hallinta', 'MM154', 'Seurataanko työntekijöiden terveyttä säännöllisin terveystarkastuksin?'],
		['Työsuojelun hallinta', 'MM155', 'Onko toimipaikallanne terveys- ja turvallisuusasioita koskien käytössä dokumentoitu (kirjallinen) menettelytapa, vakiintunut johtamisjärjestelmä tai toimintasuunnitelma?'],
		['Työsuojelun hallinta', 'MM158', 'Käsitelläänkö terveys- ja turvallisuusasioita korkean tason johdon kokouksissa toimipaikassanne säännöllisesti, satunnaisesti vai käytännössä ei koskaan?'],
		['Työsuojelun hallinta', 'MM159', 'Missä määrin arvioisitte kaiken kaikkiaan linjajohdon ja esimiesten osallistuvan toimipaikassanne terveys- ja turvallisuusasioiden hallintaan? Osallistuvatko he siihen erittäin paljon, melko paljon, melko vähän vai erittäin vähän?'],
		['Työsuojelun hallinta', 'MM161', 'Tarkistetaanko toimipaikan työpisteiden terveys- ja turvallisuusasiat säännöllisesti osana riskinarviointia tai vastaavaa toimenpidettä?'],
		['Työsuojelun hallinta', 'MM170', 'Onko Työsuojelupiiri tehnyt terveys- ja turvallisuusolojen tarkastuksia tässä toimipaikassa viimeisten 3 vuoden aikana?'],
		['Työsuojelun hallinta', 'MM173_1', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Viralliset työterveys- ja työturvallisuuslaitokset'],
		['Työsuojelun hallinta', 'MM173_2', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Euroopan työterveys- ja työturvallisuusvirasto'],
		['Työsuojelun hallinta', 'MM173_3', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Yrityksen sisäiset terveys- ja turvallisuuspalvelut'],
		['Työsuojelun hallinta', 'MM173_4', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Työsuojelupiiri'],
		['Työsuojelun hallinta', 'MM173_5', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Työntekijäjärjestöt'],
		['Työsuojelun hallinta', 'MM173_6', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Ammattiliitot'],
		['Työsuojelun hallinta', 'MM173_7', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Terveys- ja turvallisuuspalveluiden asiantuntijat, joiden kanssa on tehty sopimus'],
		['Työsuojelun hallinta', 'MM173_8', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Vakuutusyhtiöt'],
		['Työsuojelun hallinta', 'MM175', 'Oletteko tietoinen Euroopan työterveys- ja työturvallisuusviikosta?'],
		['Työsuojelun hallinta', 'MM200_1', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?: Vaaralliset aineet (esim. pöly, kemialliset, biologiset tai radioaktiiviset aineet)'],
		['Työsuojelun hallinta', 'MM200_2', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?: Tapaturmat'],
		['Työsuojelun hallinta', 'MM200_3', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?: Melu ja tärinä'],
		['Työsuojelun hallinta', 'MM200_4', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?: Tuki- ja liikuntaelinvammat, kuten särky selässä, niskassa, käsivarsissa tai jaloissa'],
		['Työsuojelun hallinta', 'MM200_5', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?: Työperäinen stressi'],
		['Työsuojelun hallinta', 'MM200_6', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?: Väkivalta tai väkivallan uhka'],
		['Työsuojelun hallinta', 'MM200_7', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?: Kiusaaminen tai häirintä, esimerkiksi solvaaminen, nöyryyttäminen tai päällekäyminen työtovereiden tai esimiesten taholta'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM202_1', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Aikapaine'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM202_2', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Heikko viestintä johdon ja työntekijöiden välillä'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM202_3', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Huono yhteistyö työtovereiden kesken'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM202_4', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Työntekijöiltä puuttuu mahdollisuus vaikuttaa työnsä organisointiin'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM202_5', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Työn epävarmuus'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM202_6', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Vaikeiden asiakkaiden, potilaiden, oppilaiden yms. käsittely'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM202_7', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Ongelmat esimies-alaissuhteissa'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM202_8', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Pitkät tai epäsäännölliset työajat'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM202_9', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Epäselvä henkilöstöpolitiikka'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM202_10', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Syrjintä (sukupuolen, iän tai etnisen alkuperän vuoksi)'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM250', 'Onko toimipaikassanne jokin toimintatapa, jonka avulla käsitellään työperäistä stressiä?'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM251', 'Onko käytössänne toimintatapa, jonka avulla puututaan kiusaamiseen tai häirintään?'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM252', 'Ja onko teillä toimintatapa työhön liittyvän väkivallan käsittelyyn?'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM253_1', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?: Työn organisointitavan muutokset'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM253_2', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?: Työtilan uudelleenjärjestely'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM253_3', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?: Työntekijöiden luottamuksellinen neuvonta'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM253_4', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?: Ristiriidan sovittelumenettelyn käynnistäminen'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM253_5', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?: Työaikajärjestelyiden muutokset'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM253_6', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?: Koulutuksen tarjoaminen'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM256', 'Ryhtyykö toimipaikkanne toimenpiteisiin, jos yksittäiset työntekijät työskentelevät liian pitkiä työpäiviä tai epäsäännöllisiä työaikoja?'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM259', 'Kerrotteko työntekijöille mahdollisista psykososiaalisista riskeistä ja niiden vaikutuksesta terveyteen ja turvallisuuteen?'],
		['Psykososiaaliset riskit ja niiden hallinta', 'MM260', 'Onko heille kerrottu, keneen he voivat ottaa yhteyden työperäisten psykososiaalisten ongelmien ilmetessä?'],
		['Edistäjät ja esteet', 'MM171_1', 'Työsuojelun edistämisen syyt toimipaikassa: Lakisääteisen velvoitteen täyttäminen'],
		['Edistäjät ja esteet', 'MM171_2', 'Työsuojelun edistämisen syyt toimipaikassa: Työntekijöiltä tai näiden edustajilta tulevat pyynnöt'],
		['Edistäjät ja esteet', 'MM171_3', 'Työsuojelun edistämisen syyt toimipaikassa: Henkilöstöstä kiinni pitäminen ja poissaolojen hallinta'],
		['Edistäjät ja esteet', 'MM171_4', 'Työsuojelun edistämisen syyt toimipaikassa: Talouteen tai tuottoon liittyvät syyt'],
		['Edistäjät ja esteet', 'MM171_5', 'Työsuojelun edistämisen syyt toimipaikassa: Asiakkailta tulevat vaatimukset tai huoli organisaation maineesta'],
		['Edistäjät ja esteet', 'MM171_6', 'Työsuojelun edistämisen syyt toimipaikassa: Työsuojelupiiriltä tuleva paine'],
		['Edistäjät ja esteet', 'MM172_1', 'Suurimmat vaikeudet työsuojelun edistämisessä: Resurssien, kuten ajan, henkilöstön tai rahan, puute'],
		['Edistäjät ja esteet', 'MM172_2', 'Suurimmat vaikeudet työsuojelun edistämisessä: Tietoisuuden puute'],
		['Edistäjät ja esteet', 'MM172_3', 'Suurimmat vaikeudet työsuojelun edistämisessä: Asiantuntemuksen puute'],
		['Edistäjät ja esteet', 'MM172_4', 'Suurimmat vaikeudet työsuojelun edistämisessä: Teknisen tuen tai opastuksen puute'],
		['Edistäjät ja esteet', 'MM172_5', 'Suurimmat vaikeudet työsuojelun edistämisessä: Toimipaikan kulttuuri'],
		['Edistäjät ja esteet', 'MM172_6', 'Suurimmat vaikeudet työsuojelun edistämisessä: Asian arkaluonteisuus'],
		['Edistäjät ja esteet', 'MM300', 'Verrattuna muihin työterveys- ja turvallisuuskysymyksiin: Onko psykososiaalisiin riskeihin vaikeampaa vai helpompaa puuttua vai eikö siinä ole eroa?'],
		['Edistäjät ja esteet', 'MM302', 'Oletteko käyttäneet ulkoisista lähteistä saatavaa tietoa tai tukea psykososiaalisten riskien käsittelyyn työpaikalla?'],
		['Edistäjät ja esteet', 'MM303a', 'Tarvitsisitteko lisätietoja tai -tukea tässä aiheessa?'],
		['Työntekijöiden osallistuminen', 'MM350', 'Onko tässä toimipaikassanne YT-toimikunta?'],
		['Työntekijöiden osallistuminen', 'MM351', 'Ja onko toimipaikassanne työntekijäpuolen ammattiosasto/luottamusmies?'],
		['Työntekijöiden osallistuminen', 'MM355all', 'Onko toimipaikassanne sisäinen työsuojeluvaltuutettu.'],
		['Työntekijöiden osallistuminen', 'MM358', 'Onko toimipaikassanne työsuojelutoimikunta?']
	];
var question_
	 = [
	
		['MM150_1', 'Työsuojelupalvelujen käyttö: Työterveyslääkäriä'],
		['MM150_2', 'Työsuojelupalvelujen käyttö: Turvallisuusasiantuntijaa'],
		['MM150_3', 'Työsuojelupalvelujen käyttö: Psykologia'],
		['MM150_4', 'Työsuojelupalvelujen käyttö: Ergonomian tai vastaavaa asiantuntijaa, joka käsittelee fyysistä työympäristöä'],
		['MM150_5', 'Työsuojelupalvelujen käyttö: Yleistä terveys- ja turvallisuusasiantuntijaa'],
		['MM152', 'Analysoidaanko toimipaikassanne järjestelmällisesti sairauspoissaolojen syitä?'],
		['MM153', 'Tuetteko pitkältä sairauslomalta palaavien työntekijöiden työhönpaluuta?'],
		['MM154', 'Seurataanko työntekijöiden terveyttä säännöllisin terveystarkastuksin?'],
		['MM155', 'Onko toimipaikallanne terveys- ja turvallisuusasioita koskien käytössä dokumentoitu (kirjallinen) menettelytapa, vakiintunut johtamisjärjestelmä tai toimintasuunnitelma?'],
		['MM158', 'Käsitelläänkö terveys- ja turvallisuusasioita korkean tason johdon kokouksissa toimipaikassanne säännöllisesti, satunnaisesti vai käytännössä ei koskaan?'],
		['MM159', 'Missä määrin arvioisitte kaiken kaikkiaan linjajohdon ja esimiesten osallistuvan toimipaikassanne terveys- ja turvallisuusasioiden hallintaan? Osallistuvatko he siihen erittäin paljon, melko paljon, melko vähän vai erittäin vähän?'],
		['MM161', 'Tarkistetaanko toimipaikan työpisteiden terveys- ja turvallisuusasiat säännöllisesti osana riskinarviointia tai vastaavaa toimenpidettä?'],
		['MM170', 'Onko Työsuojelupiiri tehnyt terveys- ja turvallisuusolojen tarkastuksia tässä toimipaikassa viimeisten 3 vuoden aikana?'],
		['MM173_1', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Viralliset työterveys- ja työturvallisuuslaitokset'],
		['MM173_2', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Euroopan työterveys- ja työturvallisuusvirasto'],
		['MM173_3', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Yrityksen sisäiset terveys- ja turvallisuuspalvelut'],
		['MM173_4', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Työsuojelupiiri'],
		['MM173_5', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Työntekijäjärjestöt'],
		['MM173_6', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Ammattiliitot'],
		['MM173_7', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Terveys- ja turvallisuuspalveluiden asiantuntijat, joiden kanssa on tehty sopimus'],
		['MM173_8', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?: Vakuutusyhtiöt'],
		['MM175', 'Oletteko tietoinen Euroopan työterveys- ja työturvallisuusviikosta?'],
		['MM200_1', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?: Vaaralliset aineet (esim. pöly, kemialliset, biologiset tai radioaktiiviset aineet)'],
		['MM200_2', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?: Tapaturmat'],
		['MM200_3', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?: Melu ja tärinä'],
		['MM200_4', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?: Tuki- ja liikuntaelinvammat, kuten särky selässä, niskassa, käsivarsissa tai jaloissa'],
		['MM200_5', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?: Työperäinen stressi'],
		['MM200_6', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?: Väkivalta tai väkivallan uhka'],
		['MM200_7', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?: Kiusaaminen tai häirintä, esimerkiksi solvaaminen, nöyryyttäminen tai päällekäyminen työtovereiden tai esimiesten taholta'],
		['MM202_1', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Aikapaine'],
		['MM202_2', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Heikko viestintä johdon ja työntekijöiden välillä'],
		['MM202_3', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Huono yhteistyö työtovereiden kesken'],
		['MM202_4', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Työntekijöiltä puuttuu mahdollisuus vaikuttaa työnsä organisointiin'],
		['MM202_5', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Työn epävarmuus'],
		['MM202_6', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Vaikeiden asiakkaiden, potilaiden, oppilaiden yms. käsittely'],
		['MM202_7', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Ongelmat esimies-alaissuhteissa'],
		['MM202_8', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Pitkät tai epäsäännölliset työajat'],
		['MM202_9', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Epäselvä henkilöstöpolitiikka'],
		['MM202_10', 'Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.: Syrjintä (sukupuolen, iän tai etnisen alkuperän vuoksi)'],
		['MM250', 'Onko toimipaikassanne jokin toimintatapa, jonka avulla käsitellään työperäistä stressiä?'],
		['MM251', 'Onko käytössänne toimintatapa, jonka avulla puututaan kiusaamiseen tai häirintään?'],
		['MM252', 'Ja onko teillä toimintatapa työhön liittyvän väkivallan käsittelyyn?'],
		['MM253_1', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?: Työn organisointitavan muutokset'],
		['MM253_2', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?: Työtilan uudelleenjärjestely'],
		['MM253_3', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?: Työntekijöiden luottamuksellinen neuvonta'],
		['MM253_4', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?: Ristiriidan sovittelumenettelyn käynnistäminen'],
		['MM253_5', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?: Työaikajärjestelyiden muutokset'],
		['MM253_6', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?: Koulutuksen tarjoaminen'],
		['MM256', 'Ryhtyykö toimipaikkanne toimenpiteisiin, jos yksittäiset työntekijät työskentelevät liian pitkiä työpäiviä tai epäsäännöllisiä työaikoja?'],
		['MM259', 'Kerrotteko työntekijöille mahdollisista psykososiaalisista riskeistä ja niiden vaikutuksesta terveyteen ja turvallisuuteen?'],
		['MM260', 'Onko heille kerrottu, keneen he voivat ottaa yhteyden työperäisten psykososiaalisten ongelmien ilmetessä?'],
		['MM171_1', 'Työsuojelun edistämisen syyt toimipaikassa: Lakisääteisen velvoitteen täyttäminen'],
		['MM171_2', 'Työsuojelun edistämisen syyt toimipaikassa: Työntekijöiltä tai näiden edustajilta tulevat pyynnöt'],
		['MM171_3', 'Työsuojelun edistämisen syyt toimipaikassa: Henkilöstöstä kiinni pitäminen ja poissaolojen hallinta'],
		['MM171_4', 'Työsuojelun edistämisen syyt toimipaikassa: Talouteen tai tuottoon liittyvät syyt'],
		['MM171_5', 'Työsuojelun edistämisen syyt toimipaikassa: Asiakkailta tulevat vaatimukset tai huoli organisaation maineesta'],
		['MM171_6', 'Työsuojelun edistämisen syyt toimipaikassa: Työsuojelupiiriltä tuleva paine'],
		['MM172_1', 'Suurimmat vaikeudet työsuojelun edistämisessä: Resurssien, kuten ajan, henkilöstön tai rahan, puute'],
		['MM172_2', 'Suurimmat vaikeudet työsuojelun edistämisessä: Tietoisuuden puute'],
		['MM172_3', 'Suurimmat vaikeudet työsuojelun edistämisessä: Asiantuntemuksen puute'],
		['MM172_4', 'Suurimmat vaikeudet työsuojelun edistämisessä: Teknisen tuen tai opastuksen puute'],
		['MM172_5', 'Suurimmat vaikeudet työsuojelun edistämisessä: Toimipaikan kulttuuri'],
		['MM172_6', 'Suurimmat vaikeudet työsuojelun edistämisessä: Asian arkaluonteisuus'],
		['MM300', 'Verrattuna muihin työterveys- ja turvallisuuskysymyksiin: Onko psykososiaalisiin riskeihin vaikeampaa vai helpompaa puuttua vai eikö siinä ole eroa?'],
		['MM302', 'Oletteko käyttäneet ulkoisista lähteistä saatavaa tietoa tai tukea psykososiaalisten riskien käsittelyyn työpaikalla?'],
		['MM303a', 'Tarvitsisitteko lisätietoja tai -tukea tässä aiheessa?'],
		['MM350', 'Onko tässä toimipaikassanne YT-toimikunta?'],
		['MM351', 'Ja onko toimipaikassanne työntekijäpuolen ammattiosasto/luottamusmies?'],
		['MM355all', 'Onko toimipaikassanne sisäinen työsuojeluvaltuutettu.'],
		['MM358', 'Onko toimipaikassanne työsuojelutoimikunta?']
	];
var question_answer
	 = [
	
		['MM150_1', '1--Yes', 'Kyllä'],
		['MM150_1', '2--No', 'Ei'],
		['MM150_1', '3--DK--NA', 'Ei vastausta'],
		['MM150_2', '1--Yes', 'Kyllä'],
		['MM150_2', '2--No', 'Ei'],
		['MM150_2', '3--DK--NA', 'Ei vastausta'],
		['MM150_3', '1--Yes', 'Kyllä'],
		['MM150_3', '2--No', 'Ei'],
		['MM150_3', '3--DK--NA', 'Ei vastausta'],
		['MM150_4', '1--Yes', 'Kyllä'],
		['MM150_4', '2--No', 'Ei'],
		['MM150_4', '3--DK--NA', 'Ei vastausta'],
		['MM150_5', '1--Yes', 'Kyllä'],
		['MM150_5', '2--No', 'Ei'],
		['MM150_5', '3--DK--NA', 'Ei vastausta'],
		['MM152', '1--Yes', 'Kyllä'],
		['MM152', '2--No', 'Ei'],
		['MM152', '3--DK--NA', 'Ei vastausta'],
		['MM153', '1--Yes', 'Kyllä'],
		['MM153', '2--No', 'Ei'],
		['MM153', '3--DK--NA', 'Ei vastausta'],
		['MM154', '1--Yes', 'Kyllä'],
		['MM154', '2--No', 'Ei'],
		['MM154', '3--DK--NA', 'Ei vastausta'],
		['MM155', '1--Yes', 'Kyllä'],
		['MM155', '2--No', 'Ei'],
		['MM155', '3--DK--NA', 'Ei vastausta'],
		['MM158', '1--Regularly', 'Säännöllisesti'],
		['MM158', '2--Occasionally', 'Satunnaisesti'],
		['MM158', '3--Practically-never', 'Tuskin koskaan'],
		['MM158', '4--DK--NA', 'Ei vastausta'],
		['MM159', '1--Very-high', 'Erittäin paljon'],
		['MM159', '2--Quite-high', 'Melko paljon'],
		['MM159', '3--Quite-low', 'Melko vähän'],
		['MM159', '4--Very-low', 'Erittäin vähän'],
		['MM159', '5--DK--NA', 'Ei vastausta'],
		['MM161', '1--Yes', 'Kyllä'],
		['MM161', '2--No', 'Ei'],
		['MM161', '3--DK--NA', 'Ei vastausta'],
		['MM170', '1--Yes', 'Kyllä'],
		['MM170', '2--No', 'Ei'],
		['MM170', '3--DK--NA', 'Ei vastausta'],
		['MM171_1', '1--Major', 'Tärkeä'],
		['MM171_1', '2--Minor', 'Ei kovinkaan tärkeä'],
		['MM171_1', '3--No', 'Ei ollenkaan tärkeä'],
		['MM171_1', '4--DK--NA', 'Ei vastausta'],
		['MM171_2', '1--Major', 'Tärkeä'],
		['MM171_2', '2--Minor', 'Ei kovinkaan tärkeä'],
		['MM171_2', '3--No', 'Ei ollenkaan tärkeä'],
		['MM171_2', '4--DK--NA', 'Ei vastausta'],
		['MM171_3', '1--Major', 'Tärkeä'],
		['MM171_3', '2--Minor', 'Ei kovinkaan tärkeä'],
		['MM171_3', '3--No', 'Ei ollenkaan tärkeä'],
		['MM171_3', '4--DK--NA', 'Ei vastausta'],
		['MM171_4', '1--Major', 'Tärkeä'],
		['MM171_4', '2--Minor', 'Ei kovinkaan tärkeä'],
		['MM171_4', '3--No', 'Ei ollenkaan tärkeä'],
		['MM171_4', '4--DK--NA', 'Ei vastausta'],
		['MM171_5', '1--Major', 'Tärkeä'],
		['MM171_5', '2--Minor', 'Ei kovinkaan tärkeä'],
		['MM171_5', '3--No', 'Ei ollenkaan tärkeä'],
		['MM171_5', '4--DK--NA', 'Ei vastausta'],
		['MM171_6', '1--Major', 'Tärkeä'],
		['MM171_6', '2--Minor', 'Ei kovinkaan tärkeä'],
		['MM171_6', '3--No', 'Ei ollenkaan tärkeä'],
		['MM171_6', '4--DK--NA', 'Ei vastausta'],
		['MM172_1', '1--Major', 'Suuri'],
		['MM172_1', '2--Minor', 'Pieni'],
		['MM172_1', '3--No', 'Ei'],
		['MM172_1', '4--DK--NA', 'Ei vastausta'],
		['MM172_2', '1--Major', 'Suuri'],
		['MM172_2', '2--Minor', 'Pieni'],
		['MM172_2', '3--No', 'Ei'],
		['MM172_2', '4--DK--NA', 'Ei vastausta'],
		['MM172_3', '1--Major', 'Suuri'],
		['MM172_3', '2--Minor', 'Pieni'],
		['MM172_3', '3--No', 'Ei'],
		['MM172_3', '4--DK--NA', 'Ei vastausta'],
		['MM172_4', '1--Major', 'Suuri'],
		['MM172_4', '2--Minor', 'Pieni'],
		['MM172_4', '3--No', 'Ei'],
		['MM172_4', '4--DK--NA', 'Ei vastausta'],
		['MM172_5', '1--Major', 'Suuri'],
		['MM172_5', '2--Minor', 'Pieni'],
		['MM172_5', '3--No', 'Ei'],
		['MM172_5', '4--DK--NA', 'Ei vastausta'],
		['MM172_6', '1--Major', 'Suuri'],
		['MM172_6', '2--Minor', 'Pieni'],
		['MM172_6', '3--No', 'Ei'],
		['MM172_6', '4--DK--NA', 'Ei vastausta'],
		['MM173_1', '1--Yes', 'Kyllä'],
		['MM173_1', '2--No', 'Ei'],
		['MM173_1', '3--DK--NA', 'Ei vastausta'],
		['MM173_2', '1--Yes', 'Kyllä'],
		['MM173_2', '2--No', 'Ei'],
		['MM173_2', '3--DK--NA', 'Ei vastausta'],
		['MM173_3', '1--Yes', 'Kyllä'],
		['MM173_3', '2--No', 'Ei'],
		['MM173_3', '3--DK--NA', 'Ei vastausta'],
		['MM173_4', '1--Yes', 'Kyllä'],
		['MM173_4', '2--No', 'Ei'],
		['MM173_4', '3--DK--NA', 'Ei vastausta'],
		['MM173_5', '1--Yes', 'Kyllä'],
		['MM173_5', '2--No', 'Ei'],
		['MM173_5', '3--DK--NA', 'Ei vastausta'],
		['MM173_6', '1--Yes', 'Kyllä'],
		['MM173_6', '2--No', 'Ei'],
		['MM173_6', '3--DK--NA', 'Ei vastausta'],
		['MM173_7', '1--Yes', 'Kyllä'],
		['MM173_7', '2--No', 'Ei'],
		['MM173_7', '3--DK--NA', 'Ei vastausta'],
		['MM173_8', '1--Yes', 'Kyllä'],
		['MM173_8', '2--No', 'Ei'],
		['MM173_8', '3--DK--NA', 'Ei vastausta'],
		['MM175', '1--Yes', 'Kyllä'],
		['MM175', '2--No', 'Ei'],
		['MM175', '3--DK--NA', 'Ei vastausta'],
		['MM200_1', '1--Major-concern', 'Suuri huolenaihe'],
		['MM200_1', '2--Some-concern', 'Jonkinasteinen huolenaihe'],
		['MM200_1', '3--No-concern', 'Ei lainkaan huolenaihe'],
		['MM200_1', '4--DK--NA', 'Ei vastausta'],
		['MM200_2', '1--Major-concern', 'Suuri huolenaihe'],
		['MM200_2', '2--Some-concern', 'Jonkinasteinen huolenaihe'],
		['MM200_2', '3--No-concern', 'Ei lainkaan huolenaihe'],
		['MM200_2', '4--DK--NA', 'Ei vastausta'],
		['MM200_3', '1--Major-concern', 'Suuri huolenaihe'],
		['MM200_3', '2--Some-concern', 'Jonkinasteinen huolenaihe'],
		['MM200_3', '3--No-concern', 'Ei lainkaan huolenaihe'],
		['MM200_3', '4--DK--NA', 'Ei vastausta'],
		['MM200_4', '1--Major-concern', 'Suuri huolenaihe'],
		['MM200_4', '2--Some-concern', 'Jonkinasteinen huolenaihe'],
		['MM200_4', '3--No-concern', 'Ei lainkaan huolenaihe'],
		['MM200_4', '4--DK--NA', 'Ei vastausta'],
		['MM200_5', '1--Major-concern', 'Suuri huolenaihe'],
		['MM200_5', '2--Some-concern', 'Jonkinasteinen huolenaihe'],
		['MM200_5', '3--No-concern', 'Ei lainkaan huolenaihe'],
		['MM200_5', '4--DK--NA', 'Ei vastausta'],
		['MM200_6', '1--Major-concern', 'Suuri huolenaihe'],
		['MM200_6', '2--Some-concern', 'Jonkinasteinen huolenaihe'],
		['MM200_6', '3--No-concern', 'Ei lainkaan huolenaihe'],
		['MM200_6', '4--DK--NA', 'Ei vastausta'],
		['MM200_7', '1--Major-concern', 'Suuri huolenaihe'],
		['MM200_7', '2--Some-concern', 'Jonkinasteinen huolenaihe'],
		['MM200_7', '3--No-concern', 'Ei lainkaan huolenaihe'],
		['MM200_7', '4--DK--NA', 'Ei vastausta'],
		['MM202_1', '1--Yes', 'Kyllä'],
		['MM202_1', '2--No', 'Ei'],
		['MM202_1', '3--DK--NA', 'Ei vastausta'],
		['MM202_10', '1--Yes', 'Kyllä'],
		['MM202_10', '2--No', 'Ei'],
		['MM202_10', '3--DK--NA', 'Ei vastausta'],
		['MM202_2', '1--Yes', 'Kyllä'],
		['MM202_2', '2--No', 'Ei'],
		['MM202_2', '3--DK--NA', 'Ei vastausta'],
		['MM202_3', '1--Yes', 'Kyllä'],
		['MM202_3', '2--No', 'Ei'],
		['MM202_3', '3--DK--NA', 'Ei vastausta'],
		['MM202_4', '1--Yes', 'Kyllä'],
		['MM202_4', '2--No', 'Ei'],
		['MM202_4', '3--DK--NA', 'Ei vastausta'],
		['MM202_5', '1--Yes', 'Kyllä'],
		['MM202_5', '2--No', 'Ei'],
		['MM202_5', '3--DK--NA', 'Ei vastausta'],
		['MM202_6', '1--Yes', 'Kyllä'],
		['MM202_6', '2--No', 'Ei'],
		['MM202_6', '3--DK--NA', 'Ei vastausta'],
		['MM202_7', '1--Yes', 'Kyllä'],
		['MM202_7', '2--No', 'Ei'],
		['MM202_7', '3--DK--NA', 'Ei vastausta'],
		['MM202_8', '1--Yes', 'Kyllä'],
		['MM202_8', '2--No', 'Ei'],
		['MM202_8', '3--DK--NA', 'Ei vastausta'],
		['MM202_9', '1--Yes', 'Kyllä'],
		['MM202_9', '2--No', 'Ei'],
		['MM202_9', '3--DK--NA', 'Ei vastausta'],
		['MM250', '1--Yes', 'Kyllä'],
		['MM250', '2--No', 'Ei'],
		['MM250', '3--Work-related-stress-is-not-an-issue-in-our-establishment', 'Työperäinen stressi ei ole ongelma toimipaikassamme'],
		['MM250', '4--No-answer', 'Ei vastausta'],
		['MM251', '1--Yes', 'Kyllä'],
		['MM251', '2--No', 'Ei'],
		['MM251', '3--These-problems-are-not-an-issue-in-our-establishment', 'Nämä asiat eivät ole ongelma toimipaikassamme'],
		['MM251', '4--No-answer', 'Ei vastausta'],
		['MM252', '1--Yes', 'Kyllä'],
		['MM252', '2--No', 'Ei'],
		['MM252', '3--Work-related-violence-is-not-an-issue-in-our-establishment', 'Työhön liittyvä väkivalta ei ole ongelma toimipaikassamme'],
		['MM252', '4--No-answer', 'Ei vastausta'],
		['MM253_1', '1--Yes', 'Kyllä'],
		['MM253_1', '2--No', 'Ei'],
		['MM253_1', '3--DK--NA', 'Ei vastausta'],
		['MM253_2', '1--Yes', 'Kyllä'],
		['MM253_2', '2--No', 'Ei'],
		['MM253_2', '3--DK--NA', 'Ei vastausta'],
		['MM253_3', '1--Yes', 'Kyllä'],
		['MM253_3', '2--No', 'Ei'],
		['MM253_3', '3--DK--NA', 'Ei vastausta'],
		['MM253_4', '1--Yes', 'Kyllä'],
		['MM253_4', '2--No', 'Ei'],
		['MM253_4', '3--DK--NA', 'Ei vastausta'],
		['MM253_5', '1--Yes', 'Kyllä'],
		['MM253_5', '2--No', 'Ei'],
		['MM253_5', '3--DK--NA', 'Ei vastausta'],
		['MM253_6', '1--Yes', 'Kyllä'],
		['MM253_6', '2--No', 'Ei'],
		['MM253_6', '3--DK--NA', 'Ei vastausta'],
		['MM256', '1--Yes', 'Kyllä'],
		['MM256', '2--No', 'Ei'],
		['MM256', '3--Long-or-irregular-working-hours-are-not-an-issue-in-our-esta', 'Pitkä tai epäsäännöllinen työaika ei ole ongelma toimipaikassamme'],
		['MM256', '4--No-answer', 'Ei vastausta'],
		['MM259', '1--Yes', 'Kyllä'],
		['MM259', '2--No', 'Ei'],
		['MM259', '3--No-answer', 'Ei vastausta'],
		['MM260', '1--Yes', 'Kyllä'],
		['MM260', '2--No', 'Ei'],
		['MM260', '3--No-answer', 'Ei vastausta'],
		['MM300', '1--More-difficult', 'Vaikeampaa'],
		['MM300', '2--Less-difficult', 'Helpompaa'],
		['MM300', '3--No-difference', 'Ei eroa'],
		['MM300', '4--No-answer', 'Ei vastausta'],
		['MM302', '1--Yes', 'Kyllä'],
		['MM302', '2--No', 'Ei'],
		['MM302', '3--No-answer', 'Ei vastausta'],
		['MM303a', '1--Yes', 'Kyllä'],
		['MM303a', '2--No', 'Ei'],
		['MM303a', '3--No-answer', 'Ei vastausta'],
		['MM350', '1--Yes', 'Kyllä'],
		['MM350', '2--No', 'Ei'],
		['MM350', '3--No-answer', 'Ei vastausta'],
		['MM351', '1--Yes', 'Kyllä'],
		['MM351', '2--No', 'Ei'],
		['MM351', '3--No-answer', 'Ei vastausta'],
		['MM355all', '1--Yes', 'Kyllä'],
		['MM355all', '2--No', 'Ei'],
		['MM355all', '3--No-answer', 'Ei vastausta'],
		['MM358', '1--Yes', 'Kyllä'],
		['MM358', '2--No', 'Ei'],
		['MM358', '3--No-answer', 'Ei vastausta']
	];
var country_
	 = [
	
		['AT', 'Itävalta'],
		['BE', 'Belgia'],
		['BG', 'Bulgaria'],
		['CH', 'Sveitsi'],
		['CY', 'Kypros'],
		['CZ', 'Tšekki'],
		['DE', 'Saksa'],
		['DK', 'Tanska'],
		['EE', 'Viro'],
		['EL', 'Kreikka'],
		['ES', 'Espanja'],
		['FI', 'Suomi'],
		['FR', 'Ranska'],
		['HR', 'Kroatia *'],
		['HU', 'Unkari'],
		['IE', 'Irlanti'],
		['IT', 'Italia'],
		['LT', 'Liettua'],
		['LU', 'Luxemburg'],
		['LV', 'Latvia'],
		['MT', 'Malta'],
		['NL', 'Alankomaat'],
		['NO', 'Norja'],
		['PL', 'Puola'],
		['PT', 'Portugali'],
		['RO', 'Romania'],
		['SE', 'Ruotsi'],
		['SI', 'Slovenia'],
		['SK', 'Slovakia'],
		['TR', 'Turkki'],
		['UK', 'Yhdistynyt kuningaskunta'],
		['EuropeanUnion', 'Euroopan unioni *']
	];
var question_meta
	 = [
	
		['MM150_1', 'Työterveyslääkäriä', 'Minkälaisia työterveys- ja työturvallisuuspalveluita käytätte toimipaikassanne - joko yksikön sisäisiä tai ulkopuolisilta ostettuja?Työterveyslääkäriä'],
		['MM150_2', 'Turvallisuusasiantuntijaa', 'Minkälaisia työterveys- ja työturvallisuuspalveluita käytätte toimipaikassanne - joko yksikön sisäisiä tai ulkopuolisilta ostettuja?Turvallisuusasiantuntijaa'],
		['MM150_3', 'Psykologia', 'Minkälaisia työterveys- ja työturvallisuuspalveluita käytätte toimipaikassanne - joko yksikön sisäisiä tai ulkopuolisilta ostettuja?Psykologia'],
		['MM150_4', 'Ergonomian tai vastaavaa asiantuntijaa, joka käsittelee fyysistä työympäristöä', 'Minkälaisia työterveys- ja työturvallisuuspalveluita käytätte toimipaikassanne - joko yksikön sisäisiä tai ulkopuolisilta ostettuja?Ergonomian tai vastaavaa asiantuntijaa, joka käsittelee fyysistä työympäristöä'],
		['MM150_5', 'Yleistä terveys- ja turvallisuusasiantuntijaa', 'Minkälaisia työterveys- ja työturvallisuuspalveluita käytätte toimipaikassanne - joko yksikön sisäisiä tai ulkopuolisilta ostettuja?Yleistä terveys- ja turvallisuusasiantuntijaa'],
		['MM152', 'Analysoidaanko toimipaikassanne järjestelmällisesti sairauspoissaolojen syitä?', 'Analysoidaanko toimipaikassanne järjestelmällisesti sairauspoissaolojen syitä?'],
		['MM153', 'Tuetteko pitkältä sairauslomalta palaavien työntekijöiden työhönpaluuta?', 'Tuetteko pitkältä sairauslomalta palaavien työntekijöiden työhönpaluuta?'],
		['MM154', 'Seurataanko työntekijöiden terveyttä säännöllisin terveystarkastuksin?', 'Seurataanko työntekijöiden terveyttä säännöllisin terveystarkastuksin?'],
		['MM155', 'Onko toimipaikallanne terveys- ja turvallisuusasioita koskien käytössä dokumentoitu (kirjallinen) menettelytapa, vakiintunut johtamisjärjestelmä tai toimintasuunnitelma?', 'Onko toimipaikallanne terveys- ja turvallisuusasioita koskien käytössä dokumentoitu (kirjallinen) menettelytapa, vakiintunut johtamisjärjestelmä tai toimintasuunnitelma?'],
		['MM158', 'Käsitelläänkö terveys- ja turvallisuusasioita korkean tason johdon kokouksissa toimipaikassanne säännöllisesti, satunnaisesti vai käytännössä ei koskaan?', 'Käsitelläänkö terveys- ja turvallisuusasioita korkean tason johdon kokouksissa toimipaikassanne säännöllisesti, satunnaisesti vai käytännössä ei koskaan?'],
		['MM159', 'Missä määrin arvioisitte kaiken kaikkiaan linjajohdon ja esimiesten osallistuvan toimipaikassanne terveys- ja turvallisuusasioiden hallintaan? Osallistuvatko he siihen erittäin paljon, melko paljon, melko vähän vai erittäin vähän?', 'Missä määrin arvioisitte kaiken kaikkiaan linjajohdon ja esimiesten osallistuvan toimipaikassanne terveys- ja turvallisuusasioiden hallintaan? Osallistuvatko he siihen erittäin paljon, melko paljon, melko vähän vai erittäin vähän?'],
		['MM161', 'Tarkistetaanko toimipaikan työpisteiden terveys- ja turvallisuusasiat säännöllisesti osana riskinarviointia tai vastaavaa toimenpidettä?', 'Tarkistetaanko toimipaikan työpisteiden terveys- ja turvallisuusasiat säännöllisesti osana riskinarviointia tai vastaavaa toimenpidettä?'],
		['MM170', 'Onko Työsuojelupiiri tehnyt terveys- ja turvallisuusolojen tarkastuksia tässä toimipaikassa viimeisten 3 vuoden aikana?', 'Onko Työsuojelupiiri tehnyt terveys- ja turvallisuusolojen tarkastuksia tässä toimipaikassa viimeisten 3 vuoden aikana?'],
		['MM173_1', 'Viralliset työterveys- ja työturvallisuuslaitokset', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?Viralliset työterveys- ja työturvallisuuslaitokset'],
		['MM173_2', 'Euroopan työterveys- ja työturvallisuusvirasto', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?Euroopan työterveys- ja työturvallisuusvirasto'],
		['MM173_3', 'Yrityksen sisäiset terveys- ja turvallisuuspalvelut', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?Yrityksen sisäiset terveys- ja turvallisuuspalvelut'],
		['MM173_4', 'Työsuojelupiiri', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?Työsuojelupiiri'],
		['MM173_5', 'Työntekijäjärjestöt', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?Työntekijäjärjestöt'],
		['MM173_6', 'Ammattiliitot', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?Ammattiliitot'],
		['MM173_7', 'Terveys- ja turvallisuuspalveluiden asiantuntijat, joiden kanssa on tehty sopimus', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?Terveys- ja turvallisuuspalveluiden asiantuntijat, joiden kanssa on tehty sopimus'],
		['MM173_8', 'Vakuutusyhtiöt', 'Onko toimipaikkanne käyttänyt terveys- tai turvallisuusasioita koskevaa tietoa, jonka olette saaneet joltakin seuraavista elimistä tai instituutioista?Vakuutusyhtiöt'],
		['MM175', 'Oletteko tietoinen Euroopan työterveys- ja työturvallisuusviikosta?', 'Oletteko tietoinen Euroopan työterveys- ja työturvallisuusviikosta?'],
		['MM200_1', 'Vaaralliset aineet (esim. pöly, kemialliset, biologiset tai radioaktiiviset aineet)', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?Vaaralliset aineet (Haast. selitä: esim. pöly, kemialliset, biologiset tai radioaktiiviset aineet)'],
		['MM200_2', 'Tapaturmat', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?Tapaturmat'],
		['MM200_3', 'Melu ja tärinä', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?Melu ja tärinä'],
		['MM200_4', 'Tuki- ja liikuntaelinvammat, kuten särky selässä, niskassa, käsivarsissa tai jaloissa', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?Tuki- ja liikuntaelinvammat, kuten särky selässä, niskassa, käsivarsissa tai jaloissa'],
		['MM200_5', 'Työperäinen stressi', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?Työperäinen stressi'],
		['MM200_6', 'Väkivalta tai väkivallan uhka', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?Väkivalta tai väkivallan uhka'],
		['MM200_7', 'Kiusaaminen tai häirintä, esimerkiksi solvaaminen, nöyryyttäminen tai päällekäyminen työtovereiden tai esimiesten taholta', 'Kertoisitteko minulle kunkin väittämän kohdalla, onko se suuri huolenaihe, jonkinasteinen huolenaihe vai ei lainkaan huolenaihe toimipaikassanne?Kiusaaminen tai häirintä, esimerkiksi solvaaminen, nöyryyttäminen tai päällekäyminen työtovereiden tai esimiesten taholta'],
		['MM202_1', 'Aikapaine', 'Useat tekijät voivat aiheuttaa stressiä, väkivaltaa tai häirintää työpaikalla. Ne liittyvät työn organisointitapaan ja niitä kutsutaan usein "psykososiaalisiksi riskeiksi". Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.Aikapaine'],
		['MM202_2', 'Heikko viestintä johdon ja työntekijöiden välillä', 'Useat tekijät voivat aiheuttaa stressiä, väkivaltaa tai häirintää työpaikalla. Ne liittyvät työn organisointitapaan ja niitä kutsutaan usein "psykososiaalisiksi riskeiksi". Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.Heikko viestintä johdon ja työntekijöiden välillä'],
		['MM202_3', 'Huono yhteistyö työtovereiden kesken', 'Useat tekijät voivat aiheuttaa stressiä, väkivaltaa tai häirintää työpaikalla. Ne liittyvät työn organisointitapaan ja niitä kutsutaan usein "psykososiaalisiksi riskeiksi". Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.Huono yhteistyö työtovereiden kesken'],
		['MM202_4', 'Työntekijöiltä puuttuu mahdollisuus vaikuttaa työnsä organisointiin', 'Useat tekijät voivat aiheuttaa stressiä, väkivaltaa tai häirintää työpaikalla. Ne liittyvät työn organisointitapaan ja niitä kutsutaan usein "psykososiaalisiksi riskeiksi". Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.Työntekijöiltä puuttuu mahdollisuus vaikuttaa työnsä organisointiin'],
		['MM202_5', 'Työn epävarmuus', 'Useat tekijät voivat aiheuttaa stressiä, väkivaltaa tai häirintää työpaikalla. Ne liittyvät työn organisointitapaan ja niitä kutsutaan usein "psykososiaalisiksi riskeiksi". Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.Työn epävarmuus'],
		['MM202_6', 'Vaikeiden asiakkaiden, potilaiden, oppilaiden yms. käsittely', 'Useat tekijät voivat aiheuttaa stressiä, väkivaltaa tai häirintää työpaikalla. Ne liittyvät työn organisointitapaan ja niitä kutsutaan usein "psykososiaalisiksi riskeiksi". Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.Vaikeiden asiakkaiden, potilaiden, oppilaiden yms. käsittely'],
		['MM202_7', 'Ongelmat esimies-alaissuhteissa', 'Useat tekijät voivat aiheuttaa stressiä, väkivaltaa tai häirintää työpaikalla. Ne liittyvät työn organisointitapaan ja niitä kutsutaan usein "psykososiaalisiksi riskeiksi". Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.Ongelmat esimies-alaissuhteissa'],
		['MM202_8', 'Pitkät tai epäsäännölliset työajat', 'Useat tekijät voivat aiheuttaa stressiä, väkivaltaa tai häirintää työpaikalla. Ne liittyvät työn organisointitapaan ja niitä kutsutaan usein "psykososiaalisiksi riskeiksi". Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.Pitkät tai epäsäännölliset työajat'],
		['MM202_9', 'Epäselvä henkilöstöpolitiikka', 'Useat tekijät voivat aiheuttaa stressiä, väkivaltaa tai häirintää työpaikalla. Ne liittyvät työn organisointitapaan ja niitä kutsutaan usein "psykososiaalisiksi riskeiksi". Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.Epäselvä henkilöstöpolitiikka'],
		['MM202_10', 'Syrjintä (sukupuolen, iän tai etnisen alkuperän vuoksi)', 'Useat tekijät voivat aiheuttaa stressiä, väkivaltaa tai häirintää työpaikalla. Ne liittyvät työn organisointitapaan ja niitä kutsutaan usein "psykososiaalisiksi riskeiksi". Kertokaa minulle, onko jokin seuraavista psykososiaalisista riskeistä huolenaihe toimipaikallanne.Syrjintä (sukupuolen, iän tai etnisen alkuperän vuoksi)'],
		['MM250', 'Onko toimipaikassanne jokin toimintatapa, jonka avulla käsitellään työperäistä stressiä?', 'Onko toimipaikassanne jokin toimintatapa, jonka avulla käsitellään työperäistä stressiä?'],
		['MM251', 'Onko käytössänne toimintatapa, jonka avulla puututaan kiusaamiseen tai häirintään?', 'Onko käytössänne toimintatapa, jonka avulla puututaan kiusaamiseen tai häirintään?'],
		['MM252', 'Ja onko teillä toimintatapa työhön liittyvän väkivallan käsittelyyn?', 'Ja onko teillä toimintatapa työhön liittyvän väkivallan käsittelyyn?'],
		['MM253_1', 'Työn organisointitavan muutokset', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?Työn organisointitavan muutokset'],
		['MM253_2', 'Työtilan uudelleenjärjestely', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?Työtilan uudelleenjärjestely'],
		['MM253_3', 'Työntekijöiden luottamuksellinen neuvonta', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?Työntekijöiden luottamuksellinen neuvonta'],
		['MM253_4', 'Ristiriidan sovittelumenettelyn käynnistäminen', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?Ristiriidan sovittelumenettelyn käynnistäminen'],
		['MM253_5', 'Työaikajärjestelyiden muutokset', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?Työaikajärjestelyiden muutokset'],
		['MM253_6', 'Koulutuksen tarjoaminen', 'Onko toimipaikkanne käyttänyt viimeisten kolmen vuoden aikana mitään seuraavista toimenpiteistä psykososiaalisten riskien käsittelyyn?Koulutuksen tarjoaminen'],
		['MM256', 'Ryhtyykö toimipaikkanne toimenpiteisiin, jos yksittäiset työntekijät työskentelevät liian pitkiä työpäiviä tai epäsäännöllisiä työaikoja?', 'Ryhtyykö toimipaikkanne toimenpiteisiin, jos yksittäiset työntekijät työskentelevät liian pitkiä työpäiviä tai epäsäännöllisiä työaikoja?'],
		['MM259', 'Kerrotteko työntekijöille mahdollisista psykososiaalisista riskeistä ja niiden vaikutuksesta terveyteen ja turvallisuuteen?', 'Kerrotteko työntekijöille mahdollisista psykososiaalisista riskeistä ja niiden vaikutuksesta terveyteen ja turvallisuuteen?'],
		['MM260', 'Onko heille kerrottu, keneen he voivat ottaa yhteyden työperäisten psykososiaalisten ongelmien ilmetessä?', 'Onko heille kerrottu, keneen he voivat ottaa yhteyden työperäisten psykososiaalisten ongelmien ilmetessä?'],
		['MM171_1', 'Lakisääteisen velvoitteen täyttäminen', 'Miten tärkeitä ovat seuraavat syyt työterveys- ja työturvallisuusasioiden käsittelyn edistämiselle? Kertoisitteko jokaisen kohdalla, onko se tärkeä, ei kovinkaan tärkeä vai ei ollenkaan tärkeä.Lakisääteisen velvoitteen täyttäminen'],
		['MM171_2', 'Työntekijöiltä tai näiden edustajilta tulevat pyynnöt', 'Miten tärkeitä ovat seuraavat syyt työterveys- ja työturvallisuusasioiden käsittelyn edistämiselle? Kertoisitteko jokaisen kohdalla, onko se tärkeä, ei kovinkaan tärkeä vai ei ollenkaan tärkeä.Työntekijöiltä tai näiden edustajilta tulevat pyynnöt'],
		['MM171_3', 'Henkilöstöstä kiinni pitäminen ja poissaolojen hallinta', 'Miten tärkeitä ovat seuraavat syyt työterveys- ja työturvallisuusasioiden käsittelyn edistämiselle? Kertoisitteko jokaisen kohdalla, onko se tärkeä, ei kovinkaan tärkeä vai ei ollenkaan tärkeä.Henkilöstöstä kiinni pitäminen ja poissaolojen hallinta'],
		['MM171_4', 'Talouteen tai tuottoon liittyvät syyt', 'Miten tärkeitä ovat seuraavat syyt työterveys- ja työturvallisuusasioiden käsittelyn edistämiselle? Kertoisitteko jokaisen kohdalla, onko se tärkeä, ei kovinkaan tärkeä vai ei ollenkaan tärkeä.Talouteen tai tuottoon liittyvät syyt'],
		['MM171_5', 'Asiakkailta tulevat vaatimukset tai huoli organisaation maineesta', 'Miten tärkeitä ovat seuraavat syyt työterveys- ja työturvallisuusasioiden käsittelyn edistämiselle? Kertoisitteko jokaisen kohdalla, onko se tärkeä, ei kovinkaan tärkeä vai ei ollenkaan tärkeä.Asiakkailta tulevat vaatimukset tai huoli organisaation maineesta'],
		['MM171_6', 'Työsuojelupiiriltä tuleva paine', 'Miten tärkeitä ovat seuraavat syyt työterveys- ja työturvallisuusasioiden käsittelyn edistämiselle? Kertoisitteko jokaisen kohdalla, onko se tärkeä, ei kovinkaan tärkeä vai ei ollenkaan tärkeä.Työsuojelupiiriltä tuleva paine'],
		['MM172_1', 'Resurssien, kuten ajan, henkilöstön tai rahan, puute', 'Mitkä ovat toimipaikkanne suurimmat ongelmat terveys- ja turvallisuusasioiden käsittelyssä? Kertoisitteko jokaisen väittämän kohdalla, onko se suuri, pieni vai ei ollenkaan ongelma?Resurssien, kuten ajan, henkilöstön tai rahan, puute'],
		['MM172_2', 'Tietoisuuden puute', 'Mitkä ovat toimipaikkanne suurimmat ongelmat terveys- ja turvallisuusasioiden käsittelyssä? Kertoisitteko jokaisen väittämän kohdalla, onko se suuri, pieni vai ei ollenkaan ongelma?Tietoisuuden puute'],
		['MM172_3', 'Asiantuntemuksen puute', 'Mitkä ovat toimipaikkanne suurimmat ongelmat terveys- ja turvallisuusasioiden käsittelyssä? Kertoisitteko jokaisen väittämän kohdalla, onko se suuri, pieni vai ei ollenkaan ongelma?Asiantuntemuksen puute'],
		['MM172_4', 'Teknisen tuen tai opastuksen puute', 'Mitkä ovat toimipaikkanne suurimmat ongelmat terveys- ja turvallisuusasioiden käsittelyssä? Kertoisitteko jokaisen väittämän kohdalla, onko se suuri, pieni vai ei ollenkaan ongelma?Teknisen tuen tai opastuksen puute'],
		['MM172_5', 'Toimipaikan kulttuuri', 'Mitkä ovat toimipaikkanne suurimmat ongelmat terveys- ja turvallisuusasioiden käsittelyssä? Kertoisitteko jokaisen väittämän kohdalla, onko se suuri, pieni vai ei ollenkaan ongelma?Toimipaikan kulttuuri'],
		['MM172_6', 'Asian arkaluonteisuus', 'Mitkä ovat toimipaikkanne suurimmat ongelmat terveys- ja turvallisuusasioiden käsittelyssä? Kertoisitteko jokaisen väittämän kohdalla, onko se suuri, pieni vai ei ollenkaan ongelma?Asian arkaluonteisuus'],
		['MM300', 'Verrattuna muihin työterveys- ja turvallisuuskysymyksiin: Onko psykososiaalisiin riskeihin vaikeampaa vai helpompaa puuttua vai eikö siinä ole eroa?', 'Verrattuna muihin työterveys- ja turvallisuuskysymyksiin: Onko psykososiaalisiin riskeihin vaikeampaa vai helpompaa puuttua vai eikö siinä ole eroa?'],
		['MM302', 'Oletteko käyttäneet ulkoisista lähteistä saatavaa tietoa tai tukea psykososiaalisten riskien käsittelyyn työpaikalla?', 'Oletteko käyttäneet ulkoisista lähteistä saatavaa tietoa tai tukea psykososiaalisten riskien käsittelyyn työpaikalla?'],
		['MM303a', 'Tarvitsisitteko lisätietoja tai -tukea tässä aiheessa?', 'Tarvitsisitteko lisätietoja tai -tukea tässä aiheessa?<br><br>Kysymys esitettiin laitoksille, jotka kertovat käyttävänsä ulkopuolisista lähteistä saatavaa tietoa tai tukea työpaikan psykososiaalisten riskien käsittelyssä.'],
		['MM350', 'Onko tässä toimipaikassanne YT-toimikunta?', 'Onko tässä toimipaikassanne YT-toimikunta?'],
		['MM351', 'Ja onko toimipaikassanne työntekijäpuolen ammattiosasto/luottamusmies?', 'Ja onko toimipaikassanne työntekijäpuolen ammattiosasto/luottamusmies?'],
		['MM355all', 'Onko toimipaikassanne sisäinen työsuojeluvaltuutettu.', 'Onko toimipaikassanne sisäinen työsuojeluvaltuutettu.<br><br>NL: Onko toimipaikassanne työsuojeluvaltuutettu?'],
		['MM358', 'Onko toimipaikassanne työsuojelutoimikunta?', 'Onko toimipaikassanne työsuojelutoimikunta?']
	];
