//Auto Generated file
var subset_
	 = [
	
		['size_4', 'Létesítmény mérete'],
		['sec3', 'Tevékenységi ágazat']
	];
var subset_subsetValue
	 = [
	
		['sec3', 'All', 'Összes'],
		['sec3', '1--Producing-Industries', 'Termelési ágazat'],
		['sec3', '2--Private-Services', 'Magánszolgáltatások'],
		['sec3', '3--Public-Services', 'Közszolgáltatások'],
		['size_4', 'All', 'Összes'],
		['size_4', '1--10-to-19-employees', '10-19 alkalmazott'],
		['size_4', '2--20-to-49-employees', '20-49 alkalmazott'],
		['size_4', '3--50-to-249-employees', '50-249 alkalmazott'],
		['size_4', '4--250-employees-or-more', '250 vagy több alkalmazott']
	];
var topic_
	 = [
	
		['', 'Összes (70)'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'A munkahelyi biztonság és egészségvédelem kezelése (29)'],
		['Indítékok és korlátok', 'Indítékok és korlátok (15)'],
		['Munkavállalói részvétel', 'Munkavállalói részvétel (4)'],
		['Pszichoszociális kockázatok és kezelésük', 'Pszichoszociális kockázatok és kezelésük (22)']
	];
var topic_question
	 = [
	
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM150_1', 'Az egészségvédelmi és biztonsági szolgáltatások igénybevétele: Üzemorvos'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM150_2', 'Az egészségvédelmi és biztonsági szolgáltatások igénybevétele: Biztonságvédelmi szakértő'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM150_3', 'Az egészségvédelmi és biztonsági szolgáltatások igénybevétele: Pszichológus'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM150_4', 'Az egészségvédelmi és biztonsági szolgáltatások igénybevétele: Ergonómiai szakértő, aki a munkaállomások felállításával foglalkozik'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM150_5', 'Az egészségvédelmi és biztonsági szolgáltatások igénybevétele: Általános munkavédelmi tanácsadó'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM152', 'Az intézménynél/telephelynél általában elemzik a betegség miatti hiányzások okát?'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM153', 'Tesznek intézkedéseket annak érdekében, hogy a munkavállalókat támogassák a munkába való visszatérésben hosszú, betegség miatti hiányzást követően?'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM154', 'Figyelik a munkavállalók egészségi állapotát rendszeres orvosi vizsgálatokkal?'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM155', 'Van az intézménynél dokumentált politika, vezetési rendszer vagy intézkedés a munkavédelemre vonatkozóan?'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM158', 'A felsővezetői értekezleteken munkavédelmi ügyeket rendszeresen, néha vagy gyakorlatilag soha nem hoznak fel?'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM159', 'Összességében hogyan értékelné a műszaki vezetők és felügyelők bevonásának mértékét a munkavédelem irányításába? Nagyon nagy mértékben bevonják őket, elég nagy mértékben, elég kis mértékben vagy nagyon kis mértékben?'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM161', 'Az intézménynél/telephelynél ellenőrzik rendszeresen a munkahelyeket munkavédelmi szempontból a kockázatértékelés részeként vagy hasonló intézkedés során?'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM170', 'Járt az intézménynél/telephelyen az elmúlt 3 évben a Munkavédelmi Felügyelőség, hogy ellenőrizze a munkavédelmi feltételeket?'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM173_1', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Hivatalos munkavédelmi intézmények'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM173_2', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Európai Munkavédelmi Ügynökség'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM173_3', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Belső munkavédelmi szolgálatok'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM173_4', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Munkavédelmi Felügyelőség'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM173_5', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Munkaadók szervezetei'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM173_6', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Szakszervezetek'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM173_7', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Szerződéssel rendelkező munkavédelmi szakértők'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM173_8', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Biztosítók'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM175', 'Ismeri Ön az Európai Munkavédelmi Hét intézményét?'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM200_1', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.: Veszélyes anyagok (pl. porok,vegyi, biológiai vagy rádioaktív anyagok)'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM200_2', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.: Balesetek'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM200_3', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.: Zaj és rezgés'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM200_4', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.: Izom- és csontrendellenességek, mint például fájdalom a hátban, nyakban, karokban és lábakban'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM200_5', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.: Munkahelyi stressz'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM200_6', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.: Erőszak vagy annak fenyegetése'],
		['A munkahelyi biztonság és egészségvédelem kezelése', 'MM200_7', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.: Erőszakoskodás vagy zaklatás, azaz durva bánásmód, megalázás vagy támadás a kollégák vagy az elöljárók részéről'],
		['Pszichoszociális kockázatok és kezelésük', 'MM202_1', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Az idő által gyakorolt nyomás'],
		['Pszichoszociális kockázatok és kezelésük', 'MM202_2', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Gyenge kommunikáció a vezetés és a munkavállalók között'],
		['Pszichoszociális kockázatok és kezelésük', 'MM202_3', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Gyenge együttműködés a kollégák között'],
		['Pszichoszociális kockázatok és kezelésük', 'MM202_4', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: A munkavállalói irányítás hiánya a munkájuk megszervezésében'],
		['Pszichoszociális kockázatok és kezelésük', 'MM202_5', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Az állások bizonytalansága'],
		['Pszichoszociális kockázatok és kezelésük', 'MM202_6', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Fárasztó ügyfelekkel, páciensekkel, tanulókkal, stb. kell foglalkozni'],
		['Pszichoszociális kockázatok és kezelésük', 'MM202_7', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénéll: Problémák a felügyelő - munkavállaló viszonyban'],
		['Pszichoszociális kockázatok és kezelésük', 'MM202_8', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Hosszú vagy szabálytalan munkaidő'],
		['Pszichoszociális kockázatok és kezelésük', 'MM202_9', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Homályos humán erőforrás politika'],
		['Pszichoszociális kockázatok és kezelésük', 'MM202_10', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Diszkrimináció (például nemi, életkori vagy etnikai hovatartozás miatt)'],
		['Pszichoszociális kockázatok és kezelésük', 'MM250', 'Létezik az intézménynek/telephelynek munkahelyi stressz kezelésére vonatkozó eljárási rendje?'],
		['Pszichoszociális kockázatok és kezelésük', 'MM251', 'Létezik az erőszakoskodás vagy zaklatás kezelésére vonatkozó eljárási rend?'],
		['Pszichoszociális kockázatok és kezelésük', 'MM252', 'Létezik munkahelyi erőszak kezelése vonatkozó eljárási rend?'],
		['Pszichoszociális kockázatok és kezelésük', 'MM253_1', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?: A munka megszervezés módjának változtatása'],
		['Pszichoszociális kockázatok és kezelésük', 'MM253_2', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?: A munkaterület átépítése'],
		['Pszichoszociális kockázatok és kezelésük', 'MM253_3', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?: Bizalmas tanácsadás munkavállalóknak'],
		['Pszichoszociális kockázatok és kezelésük', 'MM253_4', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?: Konfliktus-megoldó eljárás bevezetése'],
		['Pszichoszociális kockázatok és kezelésük', 'MM253_5', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?: A munkaidő beosztás változtatása'],
		['Pszichoszociális kockázatok és kezelésük', 'MM253_6', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?: Képzés nyújtása'],
		['Pszichoszociális kockázatok és kezelésük', 'MM256', 'Tesz az intézmény/telephely lépéseket, ha az egyes munkavállalók különösen hosszú vagy szabálytalan munkaidőben dolgoznak?'],
		['Pszichoszociális kockázatok és kezelésük', 'MM259', 'Az intézmény tájékoztatja a munkavállalókat a pszichológiai kockázatokról és azoknak az egészségre és biztonságra gyakorolt hatásairól?'],
		['Pszichoszociális kockázatok és kezelésük', 'MM260', 'Tájékoztatták őket arról, hogy kihez fordulhatnak munkahelyi pszichológiai problémák esetén?'],
		['Indítékok és korlátok', 'MM171_1', 'Indokok arra, hogy a létesítményben foglalkozzanak a munkavédelemmel: A törvényi előírások betartása'],
		['Indítékok és korlátok', 'MM171_2', 'Indokok arra, hogy a létesítményben foglalkozzanak a munkavédelemmel: A munkavállalók vagy képviselőik kérése'],
		['Indítékok és korlátok', 'MM171_3', 'Indokok arra, hogy a létesítményben foglalkozzanak a munkavédelemmel: A személyzet megtartása és a hiányzás kezelése'],
		['Indítékok és korlátok', 'MM171_4', 'Indokok arra, hogy a létesítményben foglalkozzanak a munkavédelemmel: Gazdasági vagy teljesítménnyel kapcsolatos okok'],
		['Indítékok és korlátok', 'MM171_5', 'Indokok arra, hogy a létesítményben foglalkozzanak a munkavédelemmel: Ügyfelek követelményei vagy a vállalat jó hírneve miatti aggodalom'],
		['Indítékok és korlátok', 'MM171_6', 'Indokok arra, hogy a létesítményben foglalkozzanak a munkavédelemmel: A Munkavédelmi Felügyelőség által gyakorolt nyomás'],
		['Indítékok és korlátok', 'MM172_1', 'A munkavédelem kezelésének fő nehézségei: Erőforrások, mint idő, személyzet vagy pénz hiánya'],
		['Indítékok és korlátok', 'MM172_2', 'A munkavédelem kezelésének fő nehézségei: A tudatosság hiánya'],
		['Indítékok és korlátok', 'MM172_3', 'A munkavédelem kezelésének fő nehézségei: Szaktudás hiánya'],
		['Indítékok és korlátok', 'MM172_4', 'A munkavédelem kezelésének fő nehézségei: A műszaki támogatás vagy irányítás hiánya'],
		['Indítékok és korlátok', 'MM172_5', 'A munkavédelem kezelésének fő nehézségei: Az intézmény kultúrája'],
		['Indítékok és korlátok', 'MM172_6', 'A munkavédelem kezelésének fő nehézségei: A kérdés érzékenysége'],
		['Indítékok és korlátok', 'MM300', 'Más munkavédelmi kérdésekkel összehasonlítva: Nehezebb vagy könnyebb a pszichológiai kockázatok kezelése, vagy nincs különbség?'],
		['Indítékok és korlátok', 'MM302', 'Igénybe vettek külső forrásból származó információt arra vonatkozóan, hogy miként kell kezelni a munkahelyi pszichológiai kockázatokat?'],
		['Indítékok és korlátok', 'MM303a', 'Szüksége lenne további információra vagy támogatásra ebben a kérdésben?'],
		['Munkavállalói részvétel', 'MM350', 'Van üzemi megbízott vagy üzemi tanács az intézménynél/telephelynél?'],
		['Munkavállalói részvétel', 'MM351', 'Van szakszervezet az intézménynél/telephelyen?'],
		['Munkavállalói részvétel', 'MM355all', 'Van az intézménynél belső munkavédelmi képviselő?'],
		['Munkavállalói részvétel', 'MM358', 'Van munkavédelmi bizottság az intézménynél?']
	];
var question_
	 = [
	
		['MM150_1', 'Az egészségvédelmi és biztonsági szolgáltatások igénybevétele: Üzemorvos'],
		['MM150_2', 'Az egészségvédelmi és biztonsági szolgáltatások igénybevétele: Biztonságvédelmi szakértő'],
		['MM150_3', 'Az egészségvédelmi és biztonsági szolgáltatások igénybevétele: Pszichológus'],
		['MM150_4', 'Az egészségvédelmi és biztonsági szolgáltatások igénybevétele: Ergonómiai szakértő, aki a munkaállomások felállításával foglalkozik'],
		['MM150_5', 'Az egészségvédelmi és biztonsági szolgáltatások igénybevétele: Általános munkavédelmi tanácsadó'],
		['MM152', 'Az intézménynél/telephelynél általában elemzik a betegség miatti hiányzások okát?'],
		['MM153', 'Tesznek intézkedéseket annak érdekében, hogy a munkavállalókat támogassák a munkába való visszatérésben hosszú, betegség miatti hiányzást követően?'],
		['MM154', 'Figyelik a munkavállalók egészségi állapotát rendszeres orvosi vizsgálatokkal?'],
		['MM155', 'Van az intézménynél dokumentált politika, vezetési rendszer vagy intézkedés a munkavédelemre vonatkozóan?'],
		['MM158', 'A felsővezetői értekezleteken munkavédelmi ügyeket rendszeresen, néha vagy gyakorlatilag soha nem hoznak fel?'],
		['MM159', 'Összességében hogyan értékelné a műszaki vezetők és felügyelők bevonásának mértékét a munkavédelem irányításába? Nagyon nagy mértékben bevonják őket, elég nagy mértékben, elég kis mértékben vagy nagyon kis mértékben?'],
		['MM161', 'Az intézménynél/telephelynél ellenőrzik rendszeresen a munkahelyeket munkavédelmi szempontból a kockázatértékelés részeként vagy hasonló intézkedés során?'],
		['MM170', 'Járt az intézménynél/telephelyen az elmúlt 3 évben a Munkavédelmi Felügyelőség, hogy ellenőrizze a munkavédelmi feltételeket?'],
		['MM173_1', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Hivatalos munkavédelmi intézmények'],
		['MM173_2', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Európai Munkavédelmi Ügynökség'],
		['MM173_3', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Belső munkavédelmi szolgálatok'],
		['MM173_4', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Munkavédelmi Felügyelőség'],
		['MM173_5', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Munkaadók szervezetei'],
		['MM173_6', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Szakszervezetek'],
		['MM173_7', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Szerződéssel rendelkező munkavédelmi szakértők'],
		['MM173_8', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?: Biztosítók'],
		['MM175', 'Ismeri Ön az Európai Munkavédelmi Hét intézményét?'],
		['MM200_1', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.: Veszélyes anyagok (pl. porok,vegyi, biológiai vagy rádioaktív anyagok)'],
		['MM200_2', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.: Balesetek'],
		['MM200_3', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.: Zaj és rezgés'],
		['MM200_4', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.: Izom- és csontrendellenességek, mint például fájdalom a hátban, nyakban, karokban és lábakban'],
		['MM200_5', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.: Munkahelyi stressz'],
		['MM200_6', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.: Erőszak vagy annak fenyegetése'],
		['MM200_7', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.: Erőszakoskodás vagy zaklatás, azaz durva bánásmód, megalázás vagy támadás a kollégák vagy az elöljárók részéről'],
		['MM202_1', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Az idő által gyakorolt nyomás'],
		['MM202_2', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Gyenge kommunikáció a vezetés és a munkavállalók között'],
		['MM202_3', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Gyenge együttműködés a kollégák között'],
		['MM202_4', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: A munkavállalói irányítás hiánya a munkájuk megszervezésében'],
		['MM202_5', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Az állások bizonytalansága'],
		['MM202_6', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Fárasztó ügyfelekkel, páciensekkel, tanulókkal, stb. kell foglalkozni'],
		['MM202_7', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénéll: Problémák a felügyelő - munkavállaló viszonyban'],
		['MM202_8', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Hosszú vagy szabálytalan munkaidő'],
		['MM202_9', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Homályos humán erőforrás politika'],
		['MM202_10', 'Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Diszkrimináció (például nemi, életkori vagy etnikai hovatartozás miatt)'],
		['MM250', 'Létezik az intézménynek/telephelynek munkahelyi stressz kezelésére vonatkozó eljárási rendje?'],
		['MM251', 'Létezik az erőszakoskodás vagy zaklatás kezelésére vonatkozó eljárási rend?'],
		['MM252', 'Létezik munkahelyi erőszak kezelése vonatkozó eljárási rend?'],
		['MM253_1', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?: A munka megszervezés módjának változtatása'],
		['MM253_2', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?: A munkaterület átépítése'],
		['MM253_3', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?: Bizalmas tanácsadás munkavállalóknak'],
		['MM253_4', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?: Konfliktus-megoldó eljárás bevezetése'],
		['MM253_5', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?: A munkaidő beosztás változtatása'],
		['MM253_6', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?: Képzés nyújtása'],
		['MM256', 'Tesz az intézmény/telephely lépéseket, ha az egyes munkavállalók különösen hosszú vagy szabálytalan munkaidőben dolgoznak?'],
		['MM259', 'Az intézmény tájékoztatja a munkavállalókat a pszichológiai kockázatokról és azoknak az egészségre és biztonságra gyakorolt hatásairól?'],
		['MM260', 'Tájékoztatták őket arról, hogy kihez fordulhatnak munkahelyi pszichológiai problémák esetén?'],
		['MM171_1', 'Indokok arra, hogy a létesítményben foglalkozzanak a munkavédelemmel: A törvényi előírások betartása'],
		['MM171_2', 'Indokok arra, hogy a létesítményben foglalkozzanak a munkavédelemmel: A munkavállalók vagy képviselőik kérése'],
		['MM171_3', 'Indokok arra, hogy a létesítményben foglalkozzanak a munkavédelemmel: A személyzet megtartása és a hiányzás kezelése'],
		['MM171_4', 'Indokok arra, hogy a létesítményben foglalkozzanak a munkavédelemmel: Gazdasági vagy teljesítménnyel kapcsolatos okok'],
		['MM171_5', 'Indokok arra, hogy a létesítményben foglalkozzanak a munkavédelemmel: Ügyfelek követelményei vagy a vállalat jó hírneve miatti aggodalom'],
		['MM171_6', 'Indokok arra, hogy a létesítményben foglalkozzanak a munkavédelemmel: A Munkavédelmi Felügyelőség által gyakorolt nyomás'],
		['MM172_1', 'A munkavédelem kezelésének fő nehézségei: Erőforrások, mint idő, személyzet vagy pénz hiánya'],
		['MM172_2', 'A munkavédelem kezelésének fő nehézségei: A tudatosság hiánya'],
		['MM172_3', 'A munkavédelem kezelésének fő nehézségei: Szaktudás hiánya'],
		['MM172_4', 'A munkavédelem kezelésének fő nehézségei: A műszaki támogatás vagy irányítás hiánya'],
		['MM172_5', 'A munkavédelem kezelésének fő nehézségei: Az intézmény kultúrája'],
		['MM172_6', 'A munkavédelem kezelésének fő nehézségei: A kérdés érzékenysége'],
		['MM300', 'Más munkavédelmi kérdésekkel összehasonlítva: Nehezebb vagy könnyebb a pszichológiai kockázatok kezelése, vagy nincs különbség?'],
		['MM302', 'Igénybe vettek külső forrásból származó információt arra vonatkozóan, hogy miként kell kezelni a munkahelyi pszichológiai kockázatokat?'],
		['MM303a', 'Szüksége lenne további információra vagy támogatásra ebben a kérdésben?'],
		['MM350', 'Van üzemi megbízott vagy üzemi tanács az intézménynél/telephelynél?'],
		['MM351', 'Van szakszervezet az intézménynél/telephelyen?'],
		['MM355all', 'Van az intézménynél belső munkavédelmi képviselő?'],
		['MM358', 'Van munkavédelmi bizottság az intézménynél?']
	];
var question_answer
	 = [
	
		['MM150_1', '1--Yes', 'Igen'],
		['MM150_1', '2--No', 'Nem'],
		['MM150_1', '3--DK--NA', 'Nincs válasz'],
		['MM150_2', '1--Yes', 'Igen'],
		['MM150_2', '2--No', 'Nem'],
		['MM150_2', '3--DK--NA', 'Nincs válasz'],
		['MM150_3', '1--Yes', 'Igen'],
		['MM150_3', '2--No', 'Nem'],
		['MM150_3', '3--DK--NA', 'Nincs válasz'],
		['MM150_4', '1--Yes', 'Igen'],
		['MM150_4', '2--No', 'Nem'],
		['MM150_4', '3--DK--NA', 'Nincs válasz'],
		['MM150_5', '1--Yes', 'Igen'],
		['MM150_5', '2--No', 'Nem'],
		['MM150_5', '3--DK--NA', 'Nincs válasz'],
		['MM152', '1--Yes', 'Igen'],
		['MM152', '2--No', 'Nem'],
		['MM152', '3--DK--NA', 'Nincs válasz'],
		['MM153', '1--Yes', 'Igen'],
		['MM153', '2--No', 'Nem'],
		['MM153', '3--DK--NA', 'Nincs válasz'],
		['MM154', '1--Yes', 'Igen'],
		['MM154', '2--No', 'Nem'],
		['MM154', '3--DK--NA', 'Nincs válasz'],
		['MM155', '1--Yes', 'Igen'],
		['MM155', '2--No', 'Nem'],
		['MM155', '3--DK--NA', 'Nincs válasz'],
		['MM158', '1--Regularly', 'Rendszeresen'],
		['MM158', '2--Occasionally', 'Néha'],
		['MM158', '3--Practically-never', 'Gyakorlatilag soha'],
		['MM158', '4--DK--NA', 'Nincs válasz'],
		['MM159', '1--Very-high', 'Nagyon nagy mértékben'],
		['MM159', '2--Quite-high', 'Elég nagy mértékben'],
		['MM159', '3--Quite-low', 'Elég kis mértékben'],
		['MM159', '4--Very-low', 'Nagyon kis mértékben'],
		['MM159', '5--DK--NA', 'Nincs válasz'],
		['MM161', '1--Yes', 'Igen'],
		['MM161', '2--No', 'Nem'],
		['MM161', '3--DK--NA', 'Nincs válasz'],
		['MM170', '1--Yes', 'Igen'],
		['MM170', '2--No', 'Nem'],
		['MM170', '3--DK--NA', 'Nincs válasz'],
		['MM171_1', '1--Major', 'Nagyon fontos'],
		['MM171_1', '2--Minor', 'Kevésbé fontos'],
		['MM171_1', '3--No', 'Egyáltalán nem fontos'],
		['MM171_1', '4--DK--NA', 'Nincs válasz'],
		['MM171_2', '1--Major', 'Nagyon fontos'],
		['MM171_2', '2--Minor', 'Kevésbé fontos'],
		['MM171_2', '3--No', 'Egyáltalán nem fontos'],
		['MM171_2', '4--DK--NA', 'Nincs válasz'],
		['MM171_3', '1--Major', 'Nagyon fontos'],
		['MM171_3', '2--Minor', 'Kevésbé fontos'],
		['MM171_3', '3--No', 'Egyáltalán nem fontos'],
		['MM171_3', '4--DK--NA', 'Nincs válasz'],
		['MM171_4', '1--Major', 'Nagyon fontos'],
		['MM171_4', '2--Minor', 'Kevésbé fontos'],
		['MM171_4', '3--No', 'Egyáltalán nem fontos'],
		['MM171_4', '4--DK--NA', 'Nincs válasz'],
		['MM171_5', '1--Major', 'Nagyon fontos'],
		['MM171_5', '2--Minor', 'Kevésbé fontos'],
		['MM171_5', '3--No', 'Egyáltalán nem fontos'],
		['MM171_5', '4--DK--NA', 'Nincs válasz'],
		['MM171_6', '1--Major', 'Nagyon fontos'],
		['MM171_6', '2--Minor', 'Kevésbé fontos'],
		['MM171_6', '3--No', 'Egyáltalán nem fontos'],
		['MM171_6', '4--DK--NA', 'Nincs válasz'],
		['MM172_1', '1--Major', 'Nagy nehézség'],
		['MM172_1', '2--Minor', 'Kisebb nehézség'],
		['MM172_1', '3--No', 'Egyáltalán nem nehézség'],
		['MM172_1', '4--DK--NA', 'Nincs válasz'],
		['MM172_2', '1--Major', 'Nagy nehézség'],
		['MM172_2', '2--Minor', 'Kisebb nehézség'],
		['MM172_2', '3--No', 'Egyáltalán nem nehézség'],
		['MM172_2', '4--DK--NA', 'Nincs válasz'],
		['MM172_3', '1--Major', 'Nagy nehézség'],
		['MM172_3', '2--Minor', 'Kisebb nehézség'],
		['MM172_3', '3--No', 'Egyáltalán nem nehézség'],
		['MM172_3', '4--DK--NA', 'Nincs válasz'],
		['MM172_4', '1--Major', 'Nagy nehézség'],
		['MM172_4', '2--Minor', 'Kisebb nehézség'],
		['MM172_4', '3--No', 'Egyáltalán nem nehézség'],
		['MM172_4', '4--DK--NA', 'Nincs válasz'],
		['MM172_5', '1--Major', 'Nagy nehézség'],
		['MM172_5', '2--Minor', 'Kisebb nehézség'],
		['MM172_5', '3--No', 'Egyáltalán nem nehézség'],
		['MM172_5', '4--DK--NA', 'Nincs válasz'],
		['MM172_6', '1--Major', 'Nagy nehézség'],
		['MM172_6', '2--Minor', 'Kisebb nehézség'],
		['MM172_6', '3--No', 'Egyáltalán nem nehézség'],
		['MM172_6', '4--DK--NA', 'Nincs válasz'],
		['MM173_1', '1--Yes', 'Igen'],
		['MM173_1', '2--No', 'Nem'],
		['MM173_1', '3--DK--NA', 'Nincs válasz'],
		['MM173_2', '1--Yes', 'Igen'],
		['MM173_2', '2--No', 'Nem'],
		['MM173_2', '3--DK--NA', 'Nincs válasz'],
		['MM173_3', '1--Yes', 'Igen'],
		['MM173_3', '2--No', 'Nem'],
		['MM173_3', '3--DK--NA', 'Nincs válasz'],
		['MM173_4', '1--Yes', 'Igen'],
		['MM173_4', '2--No', 'Nem'],
		['MM173_4', '3--DK--NA', 'Nincs válasz'],
		['MM173_5', '1--Yes', 'Igen'],
		['MM173_5', '2--No', 'Nem'],
		['MM173_5', '3--DK--NA', 'Nincs válasz'],
		['MM173_6', '1--Yes', 'Igen'],
		['MM173_6', '2--No', 'Nem'],
		['MM173_6', '3--DK--NA', 'Nincs válasz'],
		['MM173_7', '1--Yes', 'Igen'],
		['MM173_7', '2--No', 'Nem'],
		['MM173_7', '3--DK--NA', 'Nincs válasz'],
		['MM173_8', '1--Yes', 'Igen'],
		['MM173_8', '2--No', 'Nem'],
		['MM173_8', '3--DK--NA', 'Nincs válasz'],
		['MM175', '1--Yes', 'Igen'],
		['MM175', '2--No', 'Nem'],
		['MM175', '3--DK--NA', 'Nincs válasz'],
		['MM200_1', '1--Major-concern', 'Nagy gondot'],
		['MM200_1', '2--Some-concern', 'Valamennyi gondot'],
		['MM200_1', '3--No-concern', 'Nem okoz gondot'],
		['MM200_1', '4--DK--NA', 'Nincs válasz'],
		['MM200_2', '1--Major-concern', 'Nagy gondot'],
		['MM200_2', '2--Some-concern', 'Valamennyi gondot'],
		['MM200_2', '3--No-concern', 'Nem okoz gondot'],
		['MM200_2', '4--DK--NA', 'Nincs válasz'],
		['MM200_3', '1--Major-concern', 'Nagy gondot'],
		['MM200_3', '2--Some-concern', 'Valamennyi gondot'],
		['MM200_3', '3--No-concern', 'Nem okoz gondot'],
		['MM200_3', '4--DK--NA', 'Nincs válasz'],
		['MM200_4', '1--Major-concern', 'Nagy gondot'],
		['MM200_4', '2--Some-concern', 'Valamennyi gondot'],
		['MM200_4', '3--No-concern', 'Nem okoz gondot'],
		['MM200_4', '4--DK--NA', 'Nincs válasz'],
		['MM200_5', '1--Major-concern', 'Nagy gondot'],
		['MM200_5', '2--Some-concern', 'Valamennyi gondot'],
		['MM200_5', '3--No-concern', 'Nem okoz gondot'],
		['MM200_5', '4--DK--NA', 'Nincs válasz'],
		['MM200_6', '1--Major-concern', 'Nagy gondot'],
		['MM200_6', '2--Some-concern', 'Valamennyi gondot'],
		['MM200_6', '3--No-concern', 'Nem okoz gondot'],
		['MM200_6', '4--DK--NA', 'Nincs válasz'],
		['MM200_7', '1--Major-concern', 'Nagy gondot'],
		['MM200_7', '2--Some-concern', 'Valamennyi gondot'],
		['MM200_7', '3--No-concern', 'Nem okoz gondot'],
		['MM200_7', '4--DK--NA', 'Nincs válasz'],
		['MM202_1', '1--Yes', 'Igen'],
		['MM202_1', '2--No', 'Nem'],
		['MM202_1', '3--DK--NA', 'Nincs válasz'],
		['MM202_10', '1--Yes', 'Igen'],
		['MM202_10', '2--No', 'Nem'],
		['MM202_10', '3--DK--NA', 'Nincs válasz'],
		['MM202_2', '1--Yes', 'Igen'],
		['MM202_2', '2--No', 'Nem'],
		['MM202_2', '3--DK--NA', 'Nincs válasz'],
		['MM202_3', '1--Yes', 'Igen'],
		['MM202_3', '2--No', 'Nem'],
		['MM202_3', '3--DK--NA', 'Nincs válasz'],
		['MM202_4', '1--Yes', 'Igen'],
		['MM202_4', '2--No', 'Nem'],
		['MM202_4', '3--DK--NA', 'Nincs válasz'],
		['MM202_5', '1--Yes', 'Igen'],
		['MM202_5', '2--No', 'Nem'],
		['MM202_5', '3--DK--NA', 'Nincs válasz'],
		['MM202_6', '1--Yes', 'Igen'],
		['MM202_6', '2--No', 'Nem'],
		['MM202_6', '3--DK--NA', 'Nincs válasz'],
		['MM202_7', '1--Yes', 'Igen'],
		['MM202_7', '2--No', 'Nem'],
		['MM202_7', '3--DK--NA', 'Nincs válasz'],
		['MM202_8', '1--Yes', 'Igen'],
		['MM202_8', '2--No', 'Nem'],
		['MM202_8', '3--DK--NA', 'Nincs válasz'],
		['MM202_9', '1--Yes', 'Igen'],
		['MM202_9', '2--No', 'Nem'],
		['MM202_9', '3--DK--NA', 'Nincs válasz'],
		['MM250', '1--Yes', 'Igen'],
		['MM250', '2--No', 'Nem'],
		['MM250', '3--Work-related-stress-is-not-an-issue-in-our-establishment', 'A munkahelyi stressz nem jelent gondot az intézménynél/telephelyen'],
		['MM250', '4--No-answer', 'Nincs válasz'],
		['MM251', '1--Yes', 'Igen'],
		['MM251', '2--No', 'Nem'],
		['MM251', '3--These-problems-are-not-an-issue-in-our-establishment', 'Ezek nem jelentenek gondot az intézménynél'],
		['MM251', '4--No-answer', 'Nincs válasz'],
		['MM252', '1--Yes', 'Igen'],
		['MM252', '2--No', 'Nem'],
		['MM252', '3--Work-related-violence-is-not-an-issue-in-our-establishment', 'A munkahelyi erőszak nem jelent gondot az intézménynél/telephelynél'],
		['MM252', '4--No-answer', 'Nincs válasz'],
		['MM253_1', '1--Yes', 'Igen'],
		['MM253_1', '2--No', 'Nem'],
		['MM253_1', '3--DK--NA', 'Nincs válasz'],
		['MM253_2', '1--Yes', 'Igen'],
		['MM253_2', '2--No', 'Nem'],
		['MM253_2', '3--DK--NA', 'Nincs válasz'],
		['MM253_3', '1--Yes', 'Igen'],
		['MM253_3', '2--No', 'Nem'],
		['MM253_3', '3--DK--NA', 'Nincs válasz'],
		['MM253_4', '1--Yes', 'Igen'],
		['MM253_4', '2--No', 'Nem'],
		['MM253_4', '3--DK--NA', 'Nincs válasz'],
		['MM253_5', '1--Yes', 'Igen'],
		['MM253_5', '2--No', 'Nem'],
		['MM253_5', '3--DK--NA', 'Nincs válasz'],
		['MM253_6', '1--Yes', 'Igen'],
		['MM253_6', '2--No', 'Nem'],
		['MM253_6', '3--DK--NA', 'Nincs válasz'],
		['MM256', '1--Yes', 'Igen'],
		['MM256', '2--No', 'Nem'],
		['MM256', '3--Long-or-irregular-working-hours-are-not-an-issue-in-our-esta', 'A hosszú vagy szabálytalan munkaidő nem jelent gondot az intézménynél/telephelyen'],
		['MM256', '4--No-answer', 'Nincs válasz'],
		['MM259', '1--Yes', 'Igen'],
		['MM259', '2--No', 'Nem'],
		['MM259', '3--No-answer', 'Nincs válasz'],
		['MM260', '1--Yes', 'Igen'],
		['MM260', '2--No', 'Nem'],
		['MM260', '3--No-answer', 'Nincs válasz'],
		['MM300', '1--More-difficult', 'Nehezebb'],
		['MM300', '2--Less-difficult', 'Könnyebb'],
		['MM300', '3--No-difference', 'Nincs különbség'],
		['MM300', '4--No-answer', 'Nincs válasz'],
		['MM302', '1--Yes', 'Igen'],
		['MM302', '2--No', 'Nem'],
		['MM302', '3--No-answer', 'Nincs válasz'],
		['MM303a', '1--Yes', 'Igen'],
		['MM303a', '2--No', 'Nem'],
		['MM303a', '3--No-answer', 'Nincs válasz'],
		['MM350', '1--Yes', 'Igen'],
		['MM350', '2--No', 'Nem'],
		['MM350', '3--No-answer', 'Nincs válasz'],
		['MM351', '1--Yes', 'Igen'],
		['MM351', '2--No', 'Nem'],
		['MM351', '3--No-answer', 'Nincs válasz'],
		['MM355all', '1--Yes', 'Igen'],
		['MM355all', '2--No', 'Nem'],
		['MM355all', '3--No-answer', 'Nincs válasz'],
		['MM358', '1--Yes', 'Igen'],
		['MM358', '2--No', 'Nem'],
		['MM358', '3--No-answer', 'Nincs válasz']
	];
var country_
	 = [
	
		['AT', 'Ausztria'],
		['BE', 'Belgium'],
		['BG', 'Bulgária'],
		['CH', 'Svájc'],
		['CY', 'Ciprus'],
		['CZ', 'Csehország'],
		['DE', 'Németország'],
		['DK', 'Dánia'],
		['EE', 'Észtország'],
		['EL', 'Görögország'],
		['ES', 'Spanyolország'],
		['FI', 'Finnország'],
		['FR', 'Franciaország'],
		['HR', 'Horvátország *'],
		['HU', 'Magyarország'],
		['IE', 'Írország'],
		['IT', 'Olaszország'],
		['LT', 'Litvánia'],
		['LU', 'Luxemburg'],
		['LV', 'Lettország'],
		['MT', 'Málta'],
		['NL', 'Hollandia'],
		['NO', 'Norvégia'],
		['PL', 'Lengyelország'],
		['PT', 'Portugália'],
		['RO', 'Románia'],
		['SE', 'Svédország'],
		['SI', 'Szlovénia'],
		['SK', 'Szlovákia'],
		['TR', 'Törökország'],
		['UK', 'Egyesült Királyság'],
		['EuropeanUnion', 'Európai Unió *']
	];
var question_meta
	 = [
	
		['MM150_1', 'Üzemorvos', 'Milyen munkavédelmi szolgáltatásokat alkalmaznak, legyen az belső vagy kiszervezett?Üzemorvos'],
		['MM150_2', 'Biztonságvédelmi szakértő', 'Milyen munkavédelmi szolgáltatásokat alkalmaznak, legyen az belső vagy kiszervezett?Biztonságvédelmi szakértő'],
		['MM150_3', 'Pszichológus', 'Milyen munkavédelmi szolgáltatásokat alkalmaznak, legyen az belső vagy kiszervezett?Pszichológus'],
		['MM150_4', 'Ergonómiai szakértő, aki a munkaállomások felállításával foglalkozik', 'Milyen munkavédelmi szolgáltatásokat alkalmaznak, legyen az belső vagy kiszervezett?Ergonómiai szakértő, aki a munkaállomások felállításával foglalkozik'],
		['MM150_5', 'Általános munkavédelmi tanácsadó', 'Milyen munkavédelmi szolgáltatásokat alkalmaznak, legyen az belső vagy kiszervezett?Általános munkavédelmi tanácsadó'],
		['MM152', 'Az intézménynél/telephelynél általában elemzik a betegség miatti hiányzások okát?', 'Az intézménynél/telephelynél általában elemzik a betegség miatti hiányzások okát?'],
		['MM153', 'Tesznek intézkedéseket annak érdekében, hogy a munkavállalókat támogassák a munkába való visszatérésben hosszú, betegség miatti hiányzást követően?', 'Tesznek intézkedéseket annak érdekében, hogy a munkavállalókat támogassák a munkába való visszatérésben hosszú, betegség miatti hiányzást követően?'],
		['MM154', 'Figyelik a munkavállalók egészségi állapotát rendszeres orvosi vizsgálatokkal?', 'Figyelik a munkavállalók egészségi állapotát rendszeres orvosi vizsgálatokkal?'],
		['MM155', 'Van az intézménynél dokumentált politika, vezetési rendszer vagy intézkedés a munkavédelemre vonatkozóan?', 'Van az intézménynél dokumentált politika, vezetési rendszer vagy intézkedés a munkavédelemre vonatkozóan?'],
		['MM158', 'A felsővezetői értekezleteken munkavédelmi ügyeket rendszeresen, néha vagy gyakorlatilag soha nem hoznak fel?', 'A felsővezetői értekezleteken munkavédelmi ügyeket rendszeresen, néha vagy gyakorlatilag soha nem hoznak fel?'],
		['MM159', 'Összességében hogyan értékelné a műszaki vezetők és felügyelők bevonásának mértékét a munkavédelem irányításába? Nagyon nagy mértékben bevonják őket, elég nagy mértékben, elég kis mértékben vagy nagyon kis mértékben?', 'Összességében hogyan értékelné a műszaki vezetők és felügyelők bevonásának mértékét a munkavédelem irányításába? Nagyon nagy mértékben bevonják őket, elég nagy mértékben, elég kis mértékben vagy nagyon kis mértékben?'],
		['MM161', 'Az intézménynél/telephelynél ellenőrzik rendszeresen a munkahelyeket munkavédelmi szempontból a kockázatértékelés részeként vagy hasonló intézkedés során?', 'Az intézménynél/telephelynél ellenőrzik rendszeresen a munkahelyeket munkavédelmi szempontból a kockázatértékelés részeként vagy hasonló intézkedés során?'],
		['MM170', 'Járt az intézménynél/telephelyen az elmúlt 3 évben a Munkavédelmi Felügyelőség, hogy ellenőrizze a munkavédelmi feltételeket?', 'Járt az intézménynél/telephelyen az elmúlt 3 évben a Munkavédelmi Felügyelőség, hogy ellenőrizze a munkavédelmi feltételeket?'],
		['MM173_1', 'Hivatalos munkavédelmi intézmények', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?Hivatalos munkavédelmi intézmények'],
		['MM173_2', 'Európai Munkavédelmi Ügynökség', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?Európai Munkavédelmi Ügynökség'],
		['MM173_3', 'Belső munkavédelmi szolgálatok', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?Belső munkavédelmi szolgálatok'],
		['MM173_4', 'Munkavédelmi Felügyelőség', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?Munkavédelmi Felügyelőség'],
		['MM173_5', 'Munkaadók szervezetei', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?Munkaadók szervezetei'],
		['MM173_6', 'Szakszervezetek', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?Szakszervezetek'],
		['MM173_7', 'Szerződéssel rendelkező munkavédelmi szakértők', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?Szerződéssel rendelkező munkavédelmi szakértők'],
		['MM173_8', 'Biztosítók', 'Az Ön intézménye/telephelye használta már az alábbi testületek vagy intézmények munkavédelmi információit?Biztosítók'],
		['MM175', 'Ismeri Ön az Európai Munkavédelmi Hét intézményét?', 'Ismeri Ön az Európai Munkavédelmi Hét intézményét?'],
		['MM200_1', 'Veszélyes anyagok (pl. porok,vegyi, biológiai vagy rádioaktív anyagok)', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.Veszélyes anyagok (pl. porok, vegyi, biológiai vagy rádioaktív anyagok)'],
		['MM200_2', 'Balesetek', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.Balesetek'],
		['MM200_3', 'Zaj és rezgés', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.Zaj és rezgés'],
		['MM200_4', 'Izom- és csontrendellenességek, mint például fájdalom a hátban, nyakban, karokban és lábakban', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.Izom- és csontrendellenességek, mint például fájdalom a hátban, nyakban, karokban és lábakban'],
		['MM200_5', 'Munkahelyi stressz', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.Munkahelyi stressz'],
		['MM200_6', 'Erőszak vagy annak fenyegetése', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.Erőszak vagy annak fenyegetése'],
		['MM200_7', 'Erőszakoskodás vagy zaklatás, azaz durva bánásmód, megalázás vagy támadás a kollégák vagy az elöljárók részéről', 'Kérem mondja meg a következő állítások mindegyikéről, hogy az intézménynél/telephelynél nagy gondot, némi gondot jelentenek vagy egyáltalán nem jelentenek gondot.Erőszakoskodás vagy zaklatás, azaz durva bánásmód, megalázás vagy támadás a kollégák vagy az elöljárók részéről'],
		['MM202_1', 'Az idő által gyakorolt nyomás', 'A munkahelyi stresszhez, erőszakhoz és zaklatáshoz számos tényező hozzájárulhat; ezek érintik a munka szervezését és gyakran ’pszichológiai kockázatokként’ említik őket. Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Az idő által gyakorolt nyomás'],
		['MM202_2', 'Gyenge kommunikáció a vezetés és a munkavállalók között', 'A munkahelyi stresszhez, erőszakhoz és zaklatáshoz számos tényező hozzájárulhat; ezek érintik a munka szervezését és gyakran ’pszichológiai kockázatokként’ említik őket. Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Gyenge kommunikáció a vezetés és a munkavállalók között'],
		['MM202_3', 'Gyenge együttműködés a kollégák között', 'A munkahelyi stresszhez, erőszakhoz és zaklatáshoz számos tényező hozzájárulhat; ezek érintik a munka szervezését és gyakran ’pszichológiai kockázatokként’ említik őket. Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Gyenge együttműködés a kollégák között'],
		['MM202_4', 'A munkavállalói irányítás hiánya a munkájuk megszervezésében', 'A munkahelyi stresszhez, erőszakhoz és zaklatáshoz számos tényező hozzájárulhat; ezek érintik a munka szervezését és gyakran ’pszichológiai kockázatokként’ említik őket. Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: A munkavállalói irányítás hiánya a munkájuk megszervezésében'],
		['MM202_5', 'Az állások bizonytalansága', 'A munkahelyi stresszhez, erőszakhoz és zaklatáshoz számos tényező hozzájárulhat; ezek érintik a munka szervezését és gyakran ’pszichológiai kockázatokként’ említik őket. Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Az állások bizonytalansága'],
		['MM202_6', 'Fárasztó ügyfelekkel, páciensekkel, tanulókkal, stb. kell foglalkozni', 'A munkahelyi stresszhez, erőszakhoz és zaklatáshoz számos tényező hozzájárulhat; ezek érintik a munka szervezését és gyakran ’pszichológiai kockázatokként’ említik őket. Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Fárasztó ügyfelekkel, páciensekkel, tanulókkal, stb. kell foglalkozni'],
		['MM202_7', 'Problémák a felügyelő - munkavállaló viszonyban', 'A munkahelyi stresszhez, erőszakhoz és zaklatáshoz számos tényező hozzájárulhat; ezek érintik a munka szervezését és gyakran ’pszichológiai kockázatokként’ említik őket. Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Problémák a felügyelő - munkavállaló viszonyban'],
		['MM202_8', 'Hosszú vagy szabálytalan munkaidő', 'A munkahelyi stresszhez, erőszakhoz és zaklatáshoz számos tényező hozzájárulhat; ezek érintik a munka szervezését és gyakran ’pszichológiai kockázatokként’ említik őket. Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Hosszú vagy szabálytalan munkaidő'],
		['MM202_9', 'Homályos humán erőforrás politika', 'A munkahelyi stresszhez, erőszakhoz és zaklatáshoz számos tényező hozzájárulhat; ezek érintik a munka szervezését és gyakran ’pszichológiai kockázatokként’ említik őket. Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Homályos humán erőforrás politika'],
		['MM202_10', 'Diszkrimináció (például nemi, életkori vagy etnikai hovatartozás miatt)', 'A munkahelyi stresszhez, erőszakhoz és zaklatáshoz számos tényező hozzájárulhat; ezek érintik a munka szervezését és gyakran ’pszichológiai kockázatokként’ említik őket. Kérem, mondja meg, hogy az alábbi pszichológiai kockázatok közül jelent-e gondot valamelyik az intézménynél/telephelyénél: Diszkrimináció (például nemi, életkori vagy etnikai hovatartozás miatt)'],
		['MM250', 'Létezik az intézménynek/telephelynek munkahelyi stressz kezelésére vonatkozó eljárási rendje?', 'Létezik az intézménynek/telephelynek munkahelyi stressz kezelésére vonatkozó eljárási rendje?'],
		['MM251', 'Létezik az erőszakoskodás vagy zaklatás kezelésére vonatkozó eljárási rend?', 'Létezik az erőszakoskodás vagy zaklatás kezelésére vonatkozó eljárási rend?'],
		['MM252', 'Létezik munkahelyi erőszak kezelése vonatkozó eljárási rend?', 'Létezik munkahelyi erőszak kezelése vonatkozó eljárási rend?'],
		['MM253_1', 'A munka megszervezés módjának változtatása', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?A munka megszervezés módjának változtatása'],
		['MM253_2', 'A munkaterület átépítése', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?A munkaterület átépítése'],
		['MM253_3', 'Bizalmas tanácsadás munkavállalóknak', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?Bizalmas tanácsadás munkavállalóknak'],
		['MM253_4', 'Konfliktus-megoldó eljárás bevezetése', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?Konfliktus-megoldó eljárás bevezetése'],
		['MM253_5', 'A munkaidő beosztás változtatása', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?A munkaidő beosztás változtatása'],
		['MM253_6', 'Képzés nyújtása', 'Az elmúlt 3 évben az Önök intézménye/telephelye alkalmazta-e az alábbi intézkedések bármelyikét a pszichológiai kockázatok kezelése érdekében?Képzés nyújtása'],
		['MM256', 'Tesz az intézmény/telephely lépéseket, ha az egyes munkavállalók különösen hosszú vagy szabálytalan munkaidőben dolgoznak?', 'Tesz az intézmény/telephely lépéseket, ha az egyes munkavállalók különösen hosszú vagy szabálytalan munkaidőben dolgoznak?'],
		['MM259', 'Az intézmény tájékoztatja a munkavállalókat a pszichológiai kockázatokról és azoknak az egészségre és biztonságra gyakorolt hatásairól?', 'Az intézmény tájékoztatja a munkavállalókat a pszichológiai kockázatokról és azoknak az egészségre és biztonságra gyakorolt hatásairól?'],
		['MM260', 'Tájékoztatták őket arról, hogy kihez fordulhatnak munkahelyi pszichológiai problémák esetén?', 'Tájékoztatták őket arról, hogy kihez fordulhatnak munkahelyi pszichológiai problémák esetén?'],
		['MM171_1', 'A törvényi előírások betartása', 'Az Önök intézményénél/telephelyén mennyire fontosak a következő indítékok a munkavédelmi ügyek rendezésekor? Kérem mindegyikről mondja meg, hogy az nagyon fontos indíték, kevésbé fontos indíték vagy egyáltalán nem fontos indíték.A törvényi előírások betartása'],
		['MM171_2', 'A munkavállalók vagy képviselőik kérése', 'Az Önök intézményénél/telephelyén mennyire fontosak a következő indítékok a munkavédelmi ügyek rendezésekor? Kérem mindegyikről mondja meg, hogy az nagyon fontos indíték, kevésbé fontos indíték vagy egyáltalán nem fontos indíték.A munkavállalók vagy képviselőik kérése'],
		['MM171_3', 'A személyzet megtartása és a hiányzás kezelése', 'Az Önök intézményénél/telephelyén mennyire fontosak a következő indítékok a munkavédelmi ügyek rendezésekor? Kérem mindegyikről mondja meg, hogy az nagyon fontos indíték, kevésbé fontos indíték vagy egyáltalán nem fontos indíték.A személyzet megtartása és a hiányzás kezelése'],
		['MM171_4', 'Gazdasági vagy teljesítménnyel kapcsolatos okok', 'Az Önök intézményénél/telephelyén mennyire fontosak a következő indítékok a munkavédelmi ügyek rendezésekor? Kérem mindegyikről mondja meg, hogy az nagyon fontos indíték, kevésbé fontos indíték vagy egyáltalán nem fontos indíték.Gazdasági vagy teljesítménnyel kapcsolatos okok'],
		['MM171_5', 'Ügyfelek követelményei vagy a vállalat jó hírneve miatti aggodalom', 'Az Önök intézményénél/telephelyén mennyire fontosak a következő indítékok a munkavédelmi ügyek rendezésekor? Kérem mindegyikről mondja meg, hogy az nagyon fontos indíték, kevésbé fontos indíték vagy egyáltalán nem fontos indíték.Ügyfelek követelményei vagy a vállalat jó hírneve miatti aggodalom'],
		['MM171_6', 'A Munkavédelmi Felügyelőség által gyakorolt nyomás', 'Az Önök intézményénél/telephelyén mennyire fontosak a következő indítékok a munkavédelmi ügyek rendezésekor? Kérem mindegyikről mondja meg, hogy az nagyon fontos indíték, kevésbé fontos indíték vagy egyáltalán nem fontos indíték.A Munkavédelmi Felügyelőség által gyakorolt nyomás'],
		['MM172_1', 'Erőforrások, mint idő, személyzet vagy pénz hiánya', 'Az Önök intézményénél/telephelyén melyek a főbb nehézségek a munkavédelem kezelésében? Kérem mindegyikről mondja meg, hogy az nagyon nagy nehézség, kisebb nehézség vagy egyáltalán nem nehézség.Erőforrások, mint idő, személyzet vagy pénz hiánya'],
		['MM172_2', 'A tudatosság hiánya', 'Az Önök intézményénél/telephelyén melyek a főbb nehézségek a munkavédelem kezelésében? Kérem mindegyikről mondja meg, hogy az nagyon nagy nehézség, kisebb nehézség vagy egyáltalán nem nehézség.A tudatosság hiánya'],
		['MM172_3', 'Szaktudás hiánya', 'Az Önök intézményénél/telephelyén melyek a főbb nehézségek a munkavédelem kezelésében? Kérem mindegyikről mondja meg, hogy az nagyon nagy nehézség, kisebb nehézség vagy egyáltalán nem nehézség.Szaktudás hiánya'],
		['MM172_4', 'A műszaki támogatás vagy irányítás hiánya', 'Az Önök intézményénél/telephelyén melyek a főbb nehézségek a munkavédelem kezelésében? Kérem mindegyikről mondja meg, hogy az nagyon nagy nehézség, kisebb nehézség vagy egyáltalán nem nehézség.A műszaki támogatás vagy irányítás hiánya'],
		['MM172_5', 'Az intézmény kultúrája', 'Az Önök intézményénél/telephelyén melyek a főbb nehézségek a munkavédelem kezelésében? Kérem mindegyikről mondja meg, hogy az nagyon nagy nehézség, kisebb nehézség vagy egyáltalán nem nehézség.Az intézmény kultúrája'],
		['MM172_6', 'A kérdés érzékenysége', 'Az Önök intézményénél/telephelyén melyek a főbb nehézségek a munkavédelem kezelésében? Kérem mindegyikről mondja meg, hogy az nagyon nagy nehézség, kisebb nehézség vagy egyáltalán nem nehézség.A kérdés érzékenysége'],
		['MM300', 'Más munkavédelmi kérdésekkel összehasonlítva: Nehezebb vagy könnyebb a pszichológiai kockázatok kezelése, vagy nincs különbség?', 'Más munkavédelmi kérdésekkel összehasonlítva: Nehezebb vagy könnyebb a pszichológiai kockázatok kezelése, vagy nincs különbség?'],
		['MM302', 'Igénybe vettek külső forrásból származó információt arra vonatkozóan, hogy miként kell kezelni a munkahelyi pszichológiai kockázatokat?', 'Igénybe vettek külső forrásból származó információt arra vonatkozóan, hogy miként kell kezelni a munkahelyi pszichológiai kockázatokat?'],
		['MM303a', 'Szüksége lenne további információra vagy támogatásra ebben a kérdésben?', 'Szüksége lenne további információra vagy támogatásra ebben a kérdésben?<br><br>Kérdést intéztek azokhoz az intézményekhez, amelyek állításuk szerint külső forrásból származó információt vagy támogatást vettek igénybe a munkahelyi pszichoszociális kockázatok kezeléséhez.'],
		['MM350', 'Van üzemi megbízott vagy üzemi tanács az intézménynél/telephelynél?', 'Van üzemi megbízott vagy üzemi tanács az intézménynél/telephelynél?'],
		['MM351', 'Van szakszervezet az intézménynél/telephelyen?', 'Van szakszervezet az intézménynél/telephelyen?'],
		['MM355all', 'Van az intézménynél belső munkavédelmi képviselő?', 'Van az intézménynél belső munkavédelmi képviselő?<br><br>NL: Van-e a szervezetben egészségvédelmi és biztonsági képviseleti tag?'],
		['MM358', 'Van munkavédelmi bizottság az intézménynél?', 'Van munkavédelmi bizottság az intézménynél?']
	];
