//Auto Generated file
var subset_
	 = [
	
		['size_4', 'Dimensioni dell’impresa'],
		['sec3', 'Settore d’attività']
	];
var subset_subsetValue
	 = [
	
		['sec3', 'All', 'Tutti'],
		['sec3', '1--Producing-Industries', 'Settore produttivo'],
		['sec3', '2--Private-Services', 'Servizi forniti da privati'],
		['sec3', '3--Public-Services', 'Servizi pubblici'],
		['size_4', 'All', 'Tutti'],
		['size_4', '1--10-to-19-employees', 'da 10 a 19 dipendenti'],
		['size_4', '2--20-to-49-employees', 'da 20 a 49 dipendenti'],
		['size_4', '3--50-to-249-employees', 'da 50 a 249 dipendenti'],
		['size_4', '4--250-employees-or-more', '250 o più dipendenti']
	];
var topic_
	 = [
	
		['', 'Tutti (70)'],
		['Gestione della SSL', 'Gestione della SSL (29)'],
		['Incentivi e ostacoli', 'Incentivi e ostacoli (15)'],
		['Partecipazione dei dipendenti', 'Partecipazione dei dipendenti (4)'],
		['Rischi psicosociali e loro gestione', 'Rischi psicosociali e loro gestione (22)']
	];
var topic_question
	 = [
	
		['Gestione della SSL', 'MM150_1', 'Utilizzo dei servizi per la salute e la sicurezza: Un Medico Competente'],
		['Gestione della SSL', 'MM150_2', 'Utilizzo dei servizi per la salute e la sicurezza: Un esperto di sicurezza'],
		['Gestione della SSL', 'MM150_3', 'Utilizzo dei servizi per la salute e la sicurezza: Uno psicologo'],
		['Gestione della SSL', 'MM150_4', 'Utilizzo dei servizi per la salute e la sicurezza: Un esperto in ergonomia che si occupa della sistemazione delle postazioni di lavoro'],
		['Gestione della SSL', 'MM150_5', 'Utilizzo dei servizi per la salute e la sicurezza: Un consulente esperto di sicurezza e salute in generale'],
		['Gestione della SSL', 'MM152', 'La Sua sede si occupa sistematicamente di analizzare le cause di assenza dal lavoro per malattia?'],
		['Gestione della SSL', 'MM153', 'La sua azienda adotta misure per favorire il reinserimento lavorativo di dipendenti che rientrano dopo una lunga assenza dovuta a malattia?'],
		['Gestione della SSL', 'MM154', 'La salute dei dipendenti viene monitorata attraverso esami medici regolari?'],
		['Gestione della SSL', 'MM155', 'Esiste nella vostra sede una politica documentata, un sistema di gestione definito o un programma specifico per la salute e la sicurezza?'],
		['Gestione della SSL', 'MM158', 'Nelle riunioni a livello dirigenziale della vostra azienda si sollevano regolarmente, qualche volta o quasi mai questioni relative alla sicurezza e alla salute?'],
		['Gestione della SSL', 'MM159', 'Nel complesso come definirebbe il coinvolgimento della direzione e dei dirigenti nella gestione della sicurezza e della salute? Molto alto, abbastanza alto, abbastanza basso o molto basso?'],
		['Gestione della SSL', 'MM161', 'I luoghi di lavoro nella vostra azienda sono regolarmente controllati per ciò che riguarda aspetti della sicurezza e della tutela della salute come parte della valutazione del rischio o misure simili?'],
		['Gestione della SSL', 'MM170', 'Gli organi di vigilanza hanno mai svolto controlli o ispezioni in questa azienda negli ultimi 3 anni allo scopo di verificare le condizioni di salute e sicurezza?'],
		['Gestione della SSL', 'MM173_1', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: istituti ufficiali per la salute e la sicurezza sul lavoro'],
		['Gestione della SSL', 'MM173_2', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: Agenzia Europea per la Sicurezza e la Salute sul Lavoro'],
		['Gestione della SSL', 'MM173_3', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: Servizi di sicurezza e tutela della salute interni'],
		['Gestione della SSL', 'MM173_4', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: organi di vigilanza'],
		['Gestione della SSL', 'MM173_5', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: Organizzazioni di lavoratori'],
		['Gestione della SSL', 'MM173_6', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: I sindacati'],
		['Gestione della SSL', 'MM173_7', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: Esperti o fornitori privati di servizi di salute sul lavoro'],
		['Gestione della SSL', 'MM173_8', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: Agenzie di assicurazioni'],
		['Gestione della SSL', 'MM175', 'E a conoscenza della Settimana Europea per la sicurezza e la salute sul lavoro?'],
		['Gestione della SSL', 'MM200_1', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?: Sostanze pericolose (ad es. polveri, agenti chimici, biologici o radiazioni)'],
		['Gestione della SSL', 'MM200_2', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?: Infortuni'],
		['Gestione della SSL', 'MM200_3', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?: Rumori e vibrazioni'],
		['Gestione della SSL', 'MM200_4', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?: Disturbi muscolo-scheletrici quali dolore alla schiena, collo, braccia o gambe'],
		['Gestione della SSL', 'MM200_5', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?: Stress lavoro-correlato'],
		['Gestione della SSL', 'MM200_6', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?: Violenza o minacce'],
		['Gestione della SSL', 'MM200_7', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?: Episodi di bullismo o mobbing (es abusi, umiliazioni o attacchi da parte di colleghi/superiori)'],
		['Rischi psicosociali e loro gestione', 'MM202_1', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Pressioni per scadenze'],
		['Rischi psicosociali e loro gestione', 'MM202_2', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Poca comunicazione tra dipendenti e direzione'],
		['Rischi psicosociali e loro gestione', 'MM202_3', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Poca collaborazione tra colleghi'],
		['Rischi psicosociali e loro gestione', 'MM202_4', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Mancanza di controllo da parte dei dipendenti sullorganizzazione del loro lavoro'],
		['Rischi psicosociali e loro gestione', 'MM202_5', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Insicurezza dellimpiego'],
		['Rischi psicosociali e loro gestione', 'MM202_6', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Il dover affrontare difficili clienti, pazienti, allievi ecc'],
		['Rischi psicosociali e loro gestione', 'MM202_7', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Problemi nel rapporto tra dipendenti e superiori'],
		['Rischi psicosociali e loro gestione', 'MM202_8', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Orari troppo lunghi o irregolari'],
		['Rischi psicosociali e loro gestione', 'MM202_9', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Mancanza di trasparenza nella politica delle risorse umane'],
		['Rischi psicosociali e loro gestione', 'MM202_10', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Discriminazione (per es. dovuta a età, sesso, gruppo etnico ecc.)'],
		['Rischi psicosociali e loro gestione', 'MM250', 'Nella vostra azienda esiste una procedura o un regolamento da seguire nel caso di stress lavoro-correlato?'],
		['Rischi psicosociali e loro gestione', 'MM251', 'Nella vostra azienda esiste una procedura o un regolamento da seguire nel caso di bullismo o mobbing?'],
		['Rischi psicosociali e loro gestione', 'MM252', 'E una procedura o un regolamento da seguire nel caso di violenza sul lavoro?'],
		['Rischi psicosociali e loro gestione', 'MM253_1', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?: Cambiamenti nellorganizzazione del lavoro'],
		['Rischi psicosociali e loro gestione', 'MM253_2', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?: Cambiamenti nella sistemazione delle aree lavorative'],
		['Rischi psicosociali e loro gestione', 'MM253_3', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?: Assistenza e consulenza confidenziale per i dipendenti'],
		['Rischi psicosociali e loro gestione', 'MM253_4', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?: Istituzione di una procedura di risoluzione dei conflitti'],
		['Rischi psicosociali e loro gestione', 'MM253_5', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?: Cambiamenti nella programmazione dellorario di lavoro'],
		['Rischi psicosociali e loro gestione', 'MM253_6', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?: Organizzazione di corsi di formazione'],
		['Rischi psicosociali e loro gestione', 'MM256', 'La sua azienda intraprende azioni nel caso in cui alcuni dipendenti abbiano il problema di orari di lavoro troppo lunghi o irregolari?'],
		['Rischi psicosociali e loro gestione', 'MM259', 'La sua azienda informa il personale sui rischi psicosociali potenziali e sul loro impatto su salute e sicurezza?'],
		['Rischi psicosociali e loro gestione', 'MM260', 'Sono stati informati sulle persone a cui rivolgersi in caso di problematiche psicosociali?'],
		['Incentivi e ostacoli', 'MM171_1', 'Motivi per affrontare questioni di salute e sicurezza nell’impresa: Adempimento obblighi di legge'],
		['Incentivi e ostacoli', 'MM171_2', 'Motivi per affrontare questioni di salute e sicurezza nell’impresa: Richieste da parte dei dipendenti o dei loro rappresentanti'],
		['Incentivi e ostacoli', 'MM171_3', 'Motivi per affrontare questioni di salute e sicurezza nell’impresa: Gestione delle assenze e strategia di mantenimento personale'],
		['Incentivi e ostacoli', 'MM171_4', 'Motivi per affrontare questioni di salute e sicurezza nell’impresa: Motivi economici o legati alle prestazioni'],
		['Incentivi e ostacoli', 'MM171_5', 'Motivi per affrontare questioni di salute e sicurezza nell’impresa: Richieste da parte di clienti o preoccupazione per la reputazione dellazienda'],
		['Incentivi e ostacoli', 'MM171_6', 'Motivi per affrontare questioni di salute e sicurezza nell’impresa: Pressioni da parte degli organi di vigilanza.'],
		['Incentivi e ostacoli', 'MM172_1', 'Principali difficoltà nell’affrontare temi di salute e sicurezza: Mancanza di risorse quali tempo, soldi e personale'],
		['Incentivi e ostacoli', 'MM172_2', 'Principali difficoltà nell’affrontare temi di salute e sicurezza: Mancanza di consapevolezza/cultura'],
		['Incentivi e ostacoli', 'MM172_3', 'Principali difficoltà nell’affrontare temi di salute e sicurezza: Mancanza di conoscenza e preparazione'],
		['Incentivi e ostacoli', 'MM172_4', 'Principali difficoltà nell’affrontare temi di salute e sicurezza: Mancanza di sostegno tecnico e guida'],
		['Incentivi e ostacoli', 'MM172_5', 'Principali difficoltà nell’affrontare temi di salute e sicurezza: La cultura nellazienda'],
		['Incentivi e ostacoli', 'MM172_6', 'Principali difficoltà nell’affrontare temi di salute e sicurezza: La delicatezza della questione'],
		['Incentivi e ostacoli', 'MM300', 'In confronto ad altre questioni relative a sicurezza e salute, è più difficile, meno difficile o non cè differenza nel gestire il rischio psicosociale?'],
		['Incentivi e ostacoli', 'MM302', 'Avete mai utilizzato informazioni o supporto da qualche fonte esterna su come gestire il rischio psicosociale?'],
		['Incentivi e ostacoli', 'MM303a', 'Pensa che dovreste avere più informazioni o supporto su questo argomento?'],
		['Partecipazione dei dipendenti', 'MM350', 'Avete una Rappresentanza Sindacale Unitaria o Aziendale (RSU or RSA) nella vostra azienda?'],
		['Partecipazione dei dipendenti', 'MM351', 'Avete una organizzazione sindacale in azienda?'],
		['Partecipazione dei dipendenti', 'MM355all', 'La vostra sede ha un rappresentante dei lavoratori per la sicurezza (RLS) interno?'],
		['Partecipazione dei dipendenti', 'MM358', 'Esiste un Comitato per la Salute e la Sicurezza in azienda?']
	];
var question_
	 = [
	
		['MM150_1', 'Utilizzo dei servizi per la salute e la sicurezza: Un Medico Competente'],
		['MM150_2', 'Utilizzo dei servizi per la salute e la sicurezza: Un esperto di sicurezza'],
		['MM150_3', 'Utilizzo dei servizi per la salute e la sicurezza: Uno psicologo'],
		['MM150_4', 'Utilizzo dei servizi per la salute e la sicurezza: Un esperto in ergonomia che si occupa della sistemazione delle postazioni di lavoro'],
		['MM150_5', 'Utilizzo dei servizi per la salute e la sicurezza: Un consulente esperto di sicurezza e salute in generale'],
		['MM152', 'La Sua sede si occupa sistematicamente di analizzare le cause di assenza dal lavoro per malattia?'],
		['MM153', 'La sua azienda adotta misure per favorire il reinserimento lavorativo di dipendenti che rientrano dopo una lunga assenza dovuta a malattia?'],
		['MM154', 'La salute dei dipendenti viene monitorata attraverso esami medici regolari?'],
		['MM155', 'Esiste nella vostra sede una politica documentata, un sistema di gestione definito o un programma specifico per la salute e la sicurezza?'],
		['MM158', 'Nelle riunioni a livello dirigenziale della vostra azienda si sollevano regolarmente, qualche volta o quasi mai questioni relative alla sicurezza e alla salute?'],
		['MM159', 'Nel complesso come definirebbe il coinvolgimento della direzione e dei dirigenti nella gestione della sicurezza e della salute? Molto alto, abbastanza alto, abbastanza basso o molto basso?'],
		['MM161', 'I luoghi di lavoro nella vostra azienda sono regolarmente controllati per ciò che riguarda aspetti della sicurezza e della tutela della salute come parte della valutazione del rischio o misure simili?'],
		['MM170', 'Gli organi di vigilanza hanno mai svolto controlli o ispezioni in questa azienda negli ultimi 3 anni allo scopo di verificare le condizioni di salute e sicurezza?'],
		['MM173_1', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: istituti ufficiali per la salute e la sicurezza sul lavoro'],
		['MM173_2', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: Agenzia Europea per la Sicurezza e la Salute sul Lavoro'],
		['MM173_3', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: Servizi di sicurezza e tutela della salute interni'],
		['MM173_4', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: organi di vigilanza'],
		['MM173_5', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: Organizzazioni di lavoratori'],
		['MM173_6', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: I sindacati'],
		['MM173_7', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: Esperti o fornitori privati di servizi di salute sul lavoro'],
		['MM173_8', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?: Agenzie di assicurazioni'],
		['MM175', 'E a conoscenza della Settimana Europea per la sicurezza e la salute sul lavoro?'],
		['MM200_1', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?: Sostanze pericolose (ad es. polveri, agenti chimici, biologici o radiazioni)'],
		['MM200_2', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?: Infortuni'],
		['MM200_3', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?: Rumori e vibrazioni'],
		['MM200_4', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?: Disturbi muscolo-scheletrici quali dolore alla schiena, collo, braccia o gambe'],
		['MM200_5', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?: Stress lavoro-correlato'],
		['MM200_6', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?: Violenza o minacce'],
		['MM200_7', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?: Episodi di bullismo o mobbing (es abusi, umiliazioni o attacchi da parte di colleghi/superiori)'],
		['MM202_1', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Pressioni per scadenze'],
		['MM202_2', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Poca comunicazione tra dipendenti e direzione'],
		['MM202_3', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Poca collaborazione tra colleghi'],
		['MM202_4', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Mancanza di controllo da parte dei dipendenti sullorganizzazione del loro lavoro'],
		['MM202_5', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Insicurezza dellimpiego'],
		['MM202_6', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Il dover affrontare difficili clienti, pazienti, allievi ecc'],
		['MM202_7', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Problemi nel rapporto tra dipendenti e superiori'],
		['MM202_8', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Orari troppo lunghi o irregolari'],
		['MM202_9', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Mancanza di trasparenza nella politica delle risorse umane'],
		['MM202_10', 'La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.: Discriminazione (per es. dovuta a età, sesso, gruppo etnico ecc.)'],
		['MM250', 'Nella vostra azienda esiste una procedura o un regolamento da seguire nel caso di stress lavoro-correlato?'],
		['MM251', 'Nella vostra azienda esiste una procedura o un regolamento da seguire nel caso di bullismo o mobbing?'],
		['MM252', 'E una procedura o un regolamento da seguire nel caso di violenza sul lavoro?'],
		['MM253_1', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?: Cambiamenti nellorganizzazione del lavoro'],
		['MM253_2', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?: Cambiamenti nella sistemazione delle aree lavorative'],
		['MM253_3', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?: Assistenza e consulenza confidenziale per i dipendenti'],
		['MM253_4', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?: Istituzione di una procedura di risoluzione dei conflitti'],
		['MM253_5', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?: Cambiamenti nella programmazione dellorario di lavoro'],
		['MM253_6', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?: Organizzazione di corsi di formazione'],
		['MM256', 'La sua azienda intraprende azioni nel caso in cui alcuni dipendenti abbiano il problema di orari di lavoro troppo lunghi o irregolari?'],
		['MM259', 'La sua azienda informa il personale sui rischi psicosociali potenziali e sul loro impatto su salute e sicurezza?'],
		['MM260', 'Sono stati informati sulle persone a cui rivolgersi in caso di problematiche psicosociali?'],
		['MM171_1', 'Motivi per affrontare questioni di salute e sicurezza nell’impresa: Adempimento obblighi di legge'],
		['MM171_2', 'Motivi per affrontare questioni di salute e sicurezza nell’impresa: Richieste da parte dei dipendenti o dei loro rappresentanti'],
		['MM171_3', 'Motivi per affrontare questioni di salute e sicurezza nell’impresa: Gestione delle assenze e strategia di mantenimento personale'],
		['MM171_4', 'Motivi per affrontare questioni di salute e sicurezza nell’impresa: Motivi economici o legati alle prestazioni'],
		['MM171_5', 'Motivi per affrontare questioni di salute e sicurezza nell’impresa: Richieste da parte di clienti o preoccupazione per la reputazione dellazienda'],
		['MM171_6', 'Motivi per affrontare questioni di salute e sicurezza nell’impresa: Pressioni da parte degli organi di vigilanza.'],
		['MM172_1', 'Principali difficoltà nell’affrontare temi di salute e sicurezza: Mancanza di risorse quali tempo, soldi e personale'],
		['MM172_2', 'Principali difficoltà nell’affrontare temi di salute e sicurezza: Mancanza di consapevolezza/cultura'],
		['MM172_3', 'Principali difficoltà nell’affrontare temi di salute e sicurezza: Mancanza di conoscenza e preparazione'],
		['MM172_4', 'Principali difficoltà nell’affrontare temi di salute e sicurezza: Mancanza di sostegno tecnico e guida'],
		['MM172_5', 'Principali difficoltà nell’affrontare temi di salute e sicurezza: La cultura nellazienda'],
		['MM172_6', 'Principali difficoltà nell’affrontare temi di salute e sicurezza: La delicatezza della questione'],
		['MM300', 'In confronto ad altre questioni relative a sicurezza e salute, è più difficile, meno difficile o non cè differenza nel gestire il rischio psicosociale?'],
		['MM302', 'Avete mai utilizzato informazioni o supporto da qualche fonte esterna su come gestire il rischio psicosociale?'],
		['MM303a', 'Pensa che dovreste avere più informazioni o supporto su questo argomento?'],
		['MM350', 'Avete una Rappresentanza Sindacale Unitaria o Aziendale (RSU or RSA) nella vostra azienda?'],
		['MM351', 'Avete una organizzazione sindacale in azienda?'],
		['MM355all', 'La vostra sede ha un rappresentante dei lavoratori per la sicurezza (RLS) interno?'],
		['MM358', 'Esiste un Comitato per la Salute e la Sicurezza in azienda?']
	];
var question_answer
	 = [
	
		['MM150_1', '1--Yes', 'Sì'],
		['MM150_1', '2--No', 'No'],
		['MM150_1', '3--DK--NA', 'Nessuna risposta'],
		['MM150_2', '1--Yes', 'Sì'],
		['MM150_2', '2--No', 'No'],
		['MM150_2', '3--DK--NA', 'Nessuna risposta'],
		['MM150_3', '1--Yes', 'Sì'],
		['MM150_3', '2--No', 'No'],
		['MM150_3', '3--DK--NA', 'Nessuna risposta'],
		['MM150_4', '1--Yes', 'Sì'],
		['MM150_4', '2--No', 'No'],
		['MM150_4', '3--DK--NA', 'Nessuna risposta'],
		['MM150_5', '1--Yes', 'Sì'],
		['MM150_5', '2--No', 'No'],
		['MM150_5', '3--DK--NA', 'Nessuna risposta'],
		['MM152', '1--Yes', 'Sì'],
		['MM152', '2--No', 'No'],
		['MM152', '3--DK--NA', 'Nessuna risposta'],
		['MM153', '1--Yes', 'Sì'],
		['MM153', '2--No', 'No'],
		['MM153', '3--DK--NA', 'Nessuna risposta'],
		['MM154', '1--Yes', 'Sì'],
		['MM154', '2--No', 'No'],
		['MM154', '3--DK--NA', 'Nessuna risposta'],
		['MM155', '1--Yes', 'Sì'],
		['MM155', '2--No', 'No'],
		['MM155', '3--DK--NA', 'Nessuna risposta'],
		['MM158', '1--Regularly', 'Regolarmente'],
		['MM158', '2--Occasionally', 'Qualche volta'],
		['MM158', '3--Practically-never', 'Praticamente mai'],
		['MM158', '4--DK--NA', 'Nessuna risposta'],
		['MM159', '1--Very-high', 'Molto alto'],
		['MM159', '2--Quite-high', 'Abbastanza alto'],
		['MM159', '3--Quite-low', 'Abbastanza basso'],
		['MM159', '4--Very-low', 'Molto basso'],
		['MM159', '5--DK--NA', 'Nessuna risposta'],
		['MM161', '1--Yes', 'Sì'],
		['MM161', '2--No', 'No'],
		['MM161', '3--DK--NA', 'Nessuna risposta'],
		['MM170', '1--Yes', 'Sì'],
		['MM170', '2--No', 'No'],
		['MM170', '3--DK--NA', 'Nessuna risposta'],
		['MM171_1', '1--Major', 'Motivo importante'],
		['MM171_1', '2--Minor', 'Motivo poco importante'],
		['MM171_1', '3--No', 'Non è un motivo'],
		['MM171_1', '4--DK--NA', 'Nessuna risposta'],
		['MM171_2', '1--Major', 'Motivo importante'],
		['MM171_2', '2--Minor', 'Motivo poco importante'],
		['MM171_2', '3--No', 'Non è un motivo'],
		['MM171_2', '4--DK--NA', 'Nessuna risposta'],
		['MM171_3', '1--Major', 'Motivo importante'],
		['MM171_3', '2--Minor', 'Motivo poco importante'],
		['MM171_3', '3--No', 'Non è un motivo'],
		['MM171_3', '4--DK--NA', 'Nessuna risposta'],
		['MM171_4', '1--Major', 'Motivo importante'],
		['MM171_4', '2--Minor', 'Motivo poco importante'],
		['MM171_4', '3--No', 'Non è un motivo'],
		['MM171_4', '4--DK--NA', 'Nessuna risposta'],
		['MM171_5', '1--Major', 'Motivo importante'],
		['MM171_5', '2--Minor', 'Motivo poco importante'],
		['MM171_5', '3--No', 'Non è un motivo'],
		['MM171_5', '4--DK--NA', 'Nessuna risposta'],
		['MM171_6', '1--Major', 'Motivo importante'],
		['MM171_6', '2--Minor', 'Motivo poco importante'],
		['MM171_6', '3--No', 'Non è un motivo'],
		['MM171_6', '4--DK--NA', 'Nessuna risposta'],
		['MM172_1', '1--Major', 'Grande difficoltà'],
		['MM172_1', '2--Minor', 'Difficoltà minore'],
		['MM172_1', '3--No', 'Non è una difficoltà'],
		['MM172_1', '4--DK--NA', 'Nessuna risposta'],
		['MM172_2', '1--Major', 'Grande difficoltà'],
		['MM172_2', '2--Minor', 'Difficoltà minore'],
		['MM172_2', '3--No', 'Non è una difficoltà'],
		['MM172_2', '4--DK--NA', 'Nessuna risposta'],
		['MM172_3', '1--Major', 'Grande difficoltà'],
		['MM172_3', '2--Minor', 'Difficoltà minore'],
		['MM172_3', '3--No', 'Non è una difficoltà'],
		['MM172_3', '4--DK--NA', 'Nessuna risposta'],
		['MM172_4', '1--Major', 'Grande difficoltà'],
		['MM172_4', '2--Minor', 'Difficoltà minore'],
		['MM172_4', '3--No', 'Non è una difficoltà'],
		['MM172_4', '4--DK--NA', 'Nessuna risposta'],
		['MM172_5', '1--Major', 'Grande difficoltà'],
		['MM172_5', '2--Minor', 'Difficoltà minore'],
		['MM172_5', '3--No', 'Non è una difficoltà'],
		['MM172_5', '4--DK--NA', 'Nessuna risposta'],
		['MM172_6', '1--Major', 'Grande difficoltà'],
		['MM172_6', '2--Minor', 'Difficoltà minore'],
		['MM172_6', '3--No', 'Non è una difficoltà'],
		['MM172_6', '4--DK--NA', 'Nessuna risposta'],
		['MM173_1', '1--Yes', 'Sì'],
		['MM173_1', '2--No', 'No'],
		['MM173_1', '3--DK--NA', 'Nessuna risposta'],
		['MM173_2', '1--Yes', 'Sì'],
		['MM173_2', '2--No', 'No'],
		['MM173_2', '3--DK--NA', 'Nessuna risposta'],
		['MM173_3', '1--Yes', 'Sì'],
		['MM173_3', '2--No', 'No'],
		['MM173_3', '3--DK--NA', 'Nessuna risposta'],
		['MM173_4', '1--Yes', 'Sì'],
		['MM173_4', '2--No', 'No'],
		['MM173_4', '3--DK--NA', 'Nessuna risposta'],
		['MM173_5', '1--Yes', 'Sì'],
		['MM173_5', '2--No', 'No'],
		['MM173_5', '3--DK--NA', 'Nessuna risposta'],
		['MM173_6', '1--Yes', 'Sì'],
		['MM173_6', '2--No', 'No'],
		['MM173_6', '3--DK--NA', 'Nessuna risposta'],
		['MM173_7', '1--Yes', 'Sì'],
		['MM173_7', '2--No', 'No'],
		['MM173_7', '3--DK--NA', 'Nessuna risposta'],
		['MM173_8', '1--Yes', 'Sì'],
		['MM173_8', '2--No', 'No'],
		['MM173_8', '3--DK--NA', 'Nessuna risposta'],
		['MM175', '1--Yes', 'Sì'],
		['MM175', '2--No', 'No'],
		['MM175', '3--DK--NA', 'Nessuna risposta'],
		['MM200_1', '1--Major-concern', 'Grande preoccupazione'],
		['MM200_1', '2--Some-concern', 'Un po di preoccupazione'],
		['MM200_1', '3--No-concern', 'Nessuna preoccupazione'],
		['MM200_1', '4--DK--NA', 'Nessuna risposta'],
		['MM200_2', '1--Major-concern', 'Grande preoccupazione'],
		['MM200_2', '2--Some-concern', 'Un po di preoccupazione'],
		['MM200_2', '3--No-concern', 'Nessuna preoccupazione'],
		['MM200_2', '4--DK--NA', 'Nessuna risposta'],
		['MM200_3', '1--Major-concern', 'Grande preoccupazione'],
		['MM200_3', '2--Some-concern', 'Un po di preoccupazione'],
		['MM200_3', '3--No-concern', 'Nessuna preoccupazione'],
		['MM200_3', '4--DK--NA', 'Nessuna risposta'],
		['MM200_4', '1--Major-concern', 'Grande preoccupazione'],
		['MM200_4', '2--Some-concern', 'Un po di preoccupazione'],
		['MM200_4', '3--No-concern', 'Nessuna preoccupazione'],
		['MM200_4', '4--DK--NA', 'Nessuna risposta'],
		['MM200_5', '1--Major-concern', 'Grande preoccupazione'],
		['MM200_5', '2--Some-concern', 'Un po di preoccupazione'],
		['MM200_5', '3--No-concern', 'Nessuna preoccupazione'],
		['MM200_5', '4--DK--NA', 'Nessuna risposta'],
		['MM200_6', '1--Major-concern', 'Grande preoccupazione'],
		['MM200_6', '2--Some-concern', 'Un po di preoccupazione'],
		['MM200_6', '3--No-concern', 'Nessuna preoccupazione'],
		['MM200_6', '4--DK--NA', 'Nessuna risposta'],
		['MM200_7', '1--Major-concern', 'Grande preoccupazione'],
		['MM200_7', '2--Some-concern', 'Un po di preoccupazione'],
		['MM200_7', '3--No-concern', 'Nessuna preoccupazione'],
		['MM200_7', '4--DK--NA', 'Nessuna risposta'],
		['MM202_1', '1--Yes', 'Sì'],
		['MM202_1', '2--No', 'No'],
		['MM202_1', '3--DK--NA', 'Nessuna risposta'],
		['MM202_10', '1--Yes', 'Sì'],
		['MM202_10', '2--No', 'No'],
		['MM202_10', '3--DK--NA', 'Nessuna risposta'],
		['MM202_2', '1--Yes', 'Sì'],
		['MM202_2', '2--No', 'No'],
		['MM202_2', '3--DK--NA', 'Nessuna risposta'],
		['MM202_3', '1--Yes', 'Sì'],
		['MM202_3', '2--No', 'No'],
		['MM202_3', '3--DK--NA', 'Nessuna risposta'],
		['MM202_4', '1--Yes', 'Sì'],
		['MM202_4', '2--No', 'No'],
		['MM202_4', '3--DK--NA', 'Nessuna risposta'],
		['MM202_5', '1--Yes', 'Sì'],
		['MM202_5', '2--No', 'No'],
		['MM202_5', '3--DK--NA', 'Nessuna risposta'],
		['MM202_6', '1--Yes', 'Sì'],
		['MM202_6', '2--No', 'No'],
		['MM202_6', '3--DK--NA', 'Nessuna risposta'],
		['MM202_7', '1--Yes', 'Sì'],
		['MM202_7', '2--No', 'No'],
		['MM202_7', '3--DK--NA', 'Nessuna risposta'],
		['MM202_8', '1--Yes', 'Sì'],
		['MM202_8', '2--No', 'No'],
		['MM202_8', '3--DK--NA', 'Nessuna risposta'],
		['MM202_9', '1--Yes', 'Sì'],
		['MM202_9', '2--No', 'No'],
		['MM202_9', '3--DK--NA', 'Nessuna risposta'],
		['MM250', '1--Yes', 'Sì'],
		['MM250', '2--No', 'No'],
		['MM250', '3--Work-related-stress-is-not-an-issue-in-our-establishment', 'Non è una questione presente nella nostra azienda'],
		['MM250', '4--No-answer', 'Nessuna risposta'],
		['MM251', '1--Yes', 'Sì'],
		['MM251', '2--No', 'No'],
		['MM251', '3--These-problems-are-not-an-issue-in-our-establishment', 'Non è una questione presente nella nostra azienda'],
		['MM251', '4--No-answer', 'Nessuna risposta'],
		['MM252', '1--Yes', 'Sì'],
		['MM252', '2--No', 'No'],
		['MM252', '3--Work-related-violence-is-not-an-issue-in-our-establishment', 'Non è una questione presente nella nostra azienda'],
		['MM252', '4--No-answer', 'Nessuna risposta'],
		['MM253_1', '1--Yes', 'Sì'],
		['MM253_1', '2--No', 'No'],
		['MM253_1', '3--DK--NA', 'Nessuna risposta'],
		['MM253_2', '1--Yes', 'Sì'],
		['MM253_2', '2--No', 'No'],
		['MM253_2', '3--DK--NA', 'Nessuna risposta'],
		['MM253_3', '1--Yes', 'Sì'],
		['MM253_3', '2--No', 'No'],
		['MM253_3', '3--DK--NA', 'Nessuna risposta'],
		['MM253_4', '1--Yes', 'Sì'],
		['MM253_4', '2--No', 'No'],
		['MM253_4', '3--DK--NA', 'Nessuna risposta'],
		['MM253_5', '1--Yes', 'Sì'],
		['MM253_5', '2--No', 'No'],
		['MM253_5', '3--DK--NA', 'Nessuna risposta'],
		['MM253_6', '1--Yes', 'Sì'],
		['MM253_6', '2--No', 'No'],
		['MM253_6', '3--DK--NA', 'Nessuna risposta'],
		['MM256', '1--Yes', 'Sì'],
		['MM256', '2--No', 'No'],
		['MM256', '3--Long-or-irregular-working-hours-are-not-an-issue-in-our-esta', 'Non è una questione presente nella nostra azienda'],
		['MM256', '4--No-answer', 'Nessuna risposta'],
		['MM259', '1--Yes', 'Sì'],
		['MM259', '2--No', 'No'],
		['MM259', '3--No-answer', 'Nessuna risposta'],
		['MM260', '1--Yes', 'Sì'],
		['MM260', '2--No', 'No'],
		['MM260', '3--No-answer', 'Nessuna risposta'],
		['MM300', '1--More-difficult', 'Più difficile'],
		['MM300', '2--Less-difficult', 'Meno difficile'],
		['MM300', '3--No-difference', 'Nessuna differenza'],
		['MM300', '4--No-answer', 'Nessuna risposta'],
		['MM302', '1--Yes', 'Sì'],
		['MM302', '2--No', 'No'],
		['MM302', '3--No-answer', 'Nessuna risposta'],
		['MM303a', '1--Yes', 'Sì'],
		['MM303a', '2--No', 'No'],
		['MM303a', '3--No-answer', 'Nessuna risposta'],
		['MM350', '1--Yes', 'Sì'],
		['MM350', '2--No', 'No'],
		['MM350', '3--No-answer', 'Nessuna risposta'],
		['MM351', '1--Yes', 'Sì'],
		['MM351', '2--No', 'No'],
		['MM351', '3--No-answer', 'Nessuna risposta'],
		['MM355all', '1--Yes', 'Sì'],
		['MM355all', '2--No', 'No'],
		['MM355all', '3--No-answer', 'Nessuna risposta'],
		['MM358', '1--Yes', 'Sì'],
		['MM358', '2--No', 'No'],
		['MM358', '3--No-answer', 'Nessuna risposta']
	];
var country_
	 = [
	
		['AT', 'Austria'],
		['BE', 'Belgio'],
		['BG', 'Bulgaria'],
		['CH', 'Svizzera'],
		['CY', 'Cipro'],
		['CZ', 'Repubblica ceca'],
		['DE', 'Germania'],
		['DK', 'Danimarca'],
		['EE', 'Estonia'],
		['EL', 'Grecia'],
		['ES', 'Spagna'],
		['FI', 'Finlandia'],
		['FR', 'Francia'],
		['HR', 'Croazia*'],
		['HU', 'Ungheria'],
		['IE', 'Irlanda'],
		['IT', 'Italia'],
		['LT', 'Lituania'],
		['LU', 'Lussemburgo'],
		['LV', 'Lettonia'],
		['MT', 'Malta'],
		['NL', 'Paesi Bassi'],
		['NO', 'Norvegia'],
		['PL', 'Polonia'],
		['PT', 'Portogallo'],
		['RO', 'Romania'],
		['SE', 'Svezia'],
		['SI', 'Slovenia'],
		['SK', 'Slovacchia'],
		['TR', 'Turchia'],
		['UK', 'Regno Unito'],
		['EuropeanUnion', 'Unione europea*']
	];
var question_meta
	 = [
	
		['MM150_1', 'Un Medico Competente', 'Che tipo di servizi riguardanti la salute e la sicurezza utilizzate, sia interni sia in appalto ad agenzie esterne?Un Medico Competente'],
		['MM150_2', 'Un esperto di sicurezza', 'Che tipo di servizi riguardanti la salute e la sicurezza utilizzate, sia interni sia in appalto ad agenzie esterne?Un esperto di sicurezza'],
		['MM150_3', 'Uno psicologo', 'Che tipo di servizi riguardanti la salute e la sicurezza utilizzate, sia interni sia in appalto ad agenzie esterne?Uno psicologo'],
		['MM150_4', 'Un esperto in ergonomia che si occupa della sistemazione delle postazioni di lavoro', 'Che tipo di servizi riguardanti la salute e la sicurezza utilizzate, sia interni sia in appalto ad agenzie esterne?Un esperto in ergonomia che si occupa della sistemazione delle postazioni di lavoro'],
		['MM150_5', 'Un consulente esperto di sicurezza e salute in generale', 'Che tipo di servizi riguardanti la salute e la sicurezza utilizzate, sia interni sia in appalto ad agenzie esterne?Un consulente esperto di sicurezza e salute in generale'],
		['MM152', 'La Sua sede si occupa sistematicamente di analizzare le cause di assenza dal lavoro per malattia?', 'La Sua sede si occupa sistematicamente di analizzare le cause di assenza dal lavoro per malattia?'],
		['MM153', 'La sua azienda adotta misure per favorire il reinserimento lavorativo di dipendenti che rientrano dopo una lunga assenza dovuta a malattia?', 'La sua azienda adotta misure per favorire il reinserimento lavorativo di dipendenti che rientrano dopo una lunga assenza dovuta a malattia?'],
		['MM154', 'La salute dei dipendenti viene monitorata attraverso esami medici regolari?', 'La salute dei dipendenti viene monitorata attraverso esami medici regolari?'],
		['MM155', 'Esiste nella vostra sede una politica documentata, un sistema di gestione definito o un programma specifico per la salute e la sicurezza?', 'Esiste nella vostra sede una politica documentata, un sistema di gestione definito o un programma specifico per la salute e la sicurezza?'],
		['MM158', 'Nelle riunioni a livello dirigenziale della vostra azienda si sollevano regolarmente, qualche volta o quasi mai questioni relative alla sicurezza e alla salute?', 'Nelle riunioni a livello dirigenziale della vostra azienda si sollevano regolarmente, qualche volta o quasi mai questioni relative alla sicurezza e alla salute?'],
		['MM159', 'Nel complesso come definirebbe il coinvolgimento della direzione e dei dirigenti nella gestione della sicurezza e della salute? Molto alto, abbastanza alto, abbastanza basso o molto basso?', 'Nel complesso come definirebbe il coinvolgimento della direzione e dei dirigenti nella gestione della sicurezza e della salute? Molto alto, abbastanza alto, abbastanza basso o molto basso?'],
		['MM161', 'I luoghi di lavoro nella vostra azienda sono regolarmente controllati per ciò che riguarda aspetti della sicurezza e della tutela della salute come parte della valutazione del rischio o misure simili?', 'I luoghi di lavoro nella vostra azienda sono regolarmente controllati per ciò che riguarda aspetti della sicurezza e della tutela della salute come parte della valutazione del rischio o misure simili?'],
		['MM170', 'Gli organi di vigilanza hanno mai svolto controlli o ispezioni in questa azienda negli ultimi 3 anni allo scopo di verificare le condizioni di salute e sicurezza?', 'Gli organi di vigilanza hanno mai svolto controlli o ispezioni in questa azienda negli ultimi 3 anni allo scopo di verificare le condizioni di salute e sicurezza?'],
		['MM173_1', 'istituti ufficiali per la salute e la sicurezza sul lavoro', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?istituti ufficiali per la salute e la sicurezza sul lavoro'],
		['MM173_2', 'Agenzia Europea per la Sicurezza e la Salute sul Lavoro', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?Agenzia Europea per la Sicurezza e la Salute sul Lavoro'],
		['MM173_3', 'Servizi di sicurezza e tutela della salute interni', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?Servizi di sicurezza e tutela della salute interni'],
		['MM173_4', 'organi di vigilanza', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?organi di vigilanza'],
		['MM173_5', 'Organizzazioni di lavoratori', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?Organizzazioni di lavoratori'],
		['MM173_6', 'I sindacati', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?I sindacati'],
		['MM173_7', 'Esperti o fornitori privati di servizi di salute sul lavoro', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?Esperti o fornitori privati di servizi di salute sul lavoro'],
		['MM173_8', 'Agenzie di assicurazioni', 'La vostra sede ha mai usufruito di informazioni da uno dei seguenti organismi o istituzioni su questioni relative a sicurezza e salute?Agenzie di assicurazioni'],
		['MM175', 'E a conoscenza della Settimana Europea per la sicurezza e la salute sul lavoro?', 'E a conoscenza della Settimana Europea per la sicurezza e la salute sul lavoro?'],
		['MM200_1', 'Sostanze pericolose (ad es. polveri, agenti chimici, biologici o radiazioni)', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?Sostanze pericolose ( ad es. polveri, agenti chimici, biologici o radiazioni)'],
		['MM200_2', 'Infortuni', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?Infortuni'],
		['MM200_3', 'Rumori e vibrazioni', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?Rumori e vibrazioni'],
		['MM200_4', 'Disturbi muscolo-scheletrici quali dolore alla schiena, collo, braccia o gambe', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?Disturbi muscolo-scheletrici quali dolore alla schiena, collo, braccia o gambe'],
		['MM200_5', 'Stress lavoro-correlato', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?Stress lavoro-correlato'],
		['MM200_6', 'Violenza o minacce', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?Violenza o minacce'],
		['MM200_7', 'Episodi di bullismo o mobbing (es abusi, umiliazioni o attacchi da parte di colleghi/superiori)', 'Per ognuno dei seguenti aspetti, mi dica se cè grande preoccupazione, un po, o nessuna preoccupazione nella vostra sede?Episodi di bullismo o mobbing (es abusi, umiliazioni o attacchi da parte di colleghi/superiori)'],
		['MM202_1', 'Pressioni per scadenze', 'I fattori che possono contribuire allo stress, alla violenza o alle minacce sul lavoro sono molteplici; riguardano il modo in cui il lavoro è organizzato e rientrano in quelli che vengono chiamati ‘rischi psicosociali’. La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.Pressioni per scadenze'],
		['MM202_2', 'Poca comunicazione tra dipendenti e direzione', 'I fattori che possono contribuire allo stress, alla violenza o alle minacce sul lavoro sono molteplici; riguardano il modo in cui il lavoro è organizzato e rientrano in quelli che vengono chiamati ‘rischi psicosociali’. La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.Poca comunicazione tra dipendenti e direzione'],
		['MM202_3', 'Poca collaborazione tra colleghi', 'I fattori che possono contribuire allo stress, alla violenza o alle minacce sul lavoro sono molteplici; riguardano il modo in cui il lavoro è organizzato e rientrano in quelli che vengono chiamati ‘rischi psicosociali’. La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.Poca collaborazione tra colleghi'],
		['MM202_4', 'Mancanza di controllo da parte dei dipendenti sullorganizzazione del loro lavoro', 'I fattori che possono contribuire allo stress, alla violenza o alle minacce sul lavoro sono molteplici; riguardano il modo in cui il lavoro è organizzato e rientrano in quelli che vengono chiamati ‘rischi psicosociali’. La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.Mancanza di controllo da parte dei dipendenti sullorganizzazione del loro lavoro'],
		['MM202_5', 'Insicurezza dellimpiego', 'I fattori che possono contribuire allo stress, alla violenza o alle minacce sul lavoro sono molteplici; riguardano il modo in cui il lavoro è organizzato e rientrano in quelli che vengono chiamati ‘rischi psicosociali’. La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.Insicurezza dellimpiego'],
		['MM202_6', 'Il dover affrontare difficili clienti, pazienti, allievi ecc', 'I fattori che possono contribuire allo stress, alla violenza o alle minacce sul lavoro sono molteplici; riguardano il modo in cui il lavoro è organizzato e rientrano in quelli che vengono chiamati ‘rischi psicosociali’. La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.Il dover affrontare difficili clienti, pazienti, allievi ecc'],
		['MM202_7', 'Problemi nel rapporto tra dipendenti e superiori', 'I fattori che possono contribuire allo stress, alla violenza o alle minacce sul lavoro sono molteplici; riguardano il modo in cui il lavoro è organizzato e rientrano in quelli che vengono chiamati ‘rischi psicosociali’. La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.Problemi nel rapporto tra dipendenti e superiori'],
		['MM202_8', 'Orari troppo lunghi o irregolari', 'I fattori che possono contribuire allo stress, alla violenza o alle minacce sul lavoro sono molteplici; riguardano il modo in cui il lavoro è organizzato e rientrano in quelli che vengono chiamati ‘rischi psicosociali’. La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.Orari troppo lunghi o irregolari'],
		['MM202_9', 'Mancanza di trasparenza nella politica delle risorse umane', 'I fattori che possono contribuire allo stress, alla violenza o alle minacce sul lavoro sono molteplici; riguardano il modo in cui il lavoro è organizzato e rientrano in quelli che vengono chiamati ‘rischi psicosociali’. La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.Mancanza di trasparenza nella politica delle risorse umane'],
		['MM202_10', 'Discriminazione (per es. dovuta a età, sesso, gruppo etnico ecc.)', 'I fattori che possono contribuire allo stress, alla violenza o alle minacce sul lavoro sono molteplici; riguardano il modo in cui il lavoro è organizzato e rientrano in quelli che vengono chiamati ‘rischi psicosociali’. La prego di dirmi se qualcuno tra i seguenti rischi psicosociali sono motivo di preoccupazione nella vostra azienda.Discriminazione (per es. dovuta a età, sesso, gruppo etnico ecc.)'],
		['MM250', 'Nella vostra azienda esiste una procedura o un regolamento da seguire nel caso di stress lavoro-correlato?', 'Nella vostra azienda esiste una procedura o un regolamento da seguire nel caso di stress lavoro-correlato?'],
		['MM251', 'Nella vostra azienda esiste una procedura o un regolamento da seguire nel caso di bullismo o mobbing?', 'Nella vostra azienda esiste una procedura o un regolamento da seguire nel caso di bullismo o mobbing?'],
		['MM252', 'E una procedura o un regolamento da seguire nel caso di violenza sul lavoro?', 'E una procedura o un regolamento da seguire nel caso di violenza sul lavoro?'],
		['MM253_1', 'Cambiamenti nellorganizzazione del lavoro', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?Cambiamenti nellorganizzazione del lavoro'],
		['MM253_2', 'Cambiamenti nella sistemazione delle aree lavorative', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?Cambiamenti nella sistemazione delle aree lavorative'],
		['MM253_3', 'Assistenza e consulenza confidenziale per i dipendenti', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?Assistenza e consulenza confidenziale per i dipendenti'],
		['MM253_4', 'Istituzione di una procedura di risoluzione dei conflitti', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?Istituzione di una procedura di risoluzione dei conflitti'],
		['MM253_5', 'Cambiamenti nella programmazione dellorario di lavoro', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?Cambiamenti nella programmazione dellorario di lavoro'],
		['MM253_6', 'Organizzazione di corsi di formazione', 'La sua sede ha utlizzato una delle seguenti misure per affrontare rischi psicosociali negli ultimi 3 anni?Organizzazione di corsi di formazione'],
		['MM256', 'La sua azienda intraprende azioni nel caso in cui alcuni dipendenti abbiano il problema di orari di lavoro troppo lunghi o irregolari?', 'La sua azienda intraprende azioni nel caso in cui alcuni dipendenti abbiano il problema di orari di lavoro troppo lunghi o irregolari?'],
		['MM259', 'La sua azienda informa il personale sui rischi psicosociali potenziali e sul loro impatto su salute e sicurezza?', 'La sua azienda informa il personale sui rischi psicosociali potenziali e sul loro impatto su salute e sicurezza?'],
		['MM260', 'Sono stati informati sulle persone a cui rivolgersi in caso di problematiche psicosociali?', 'Sono stati informati sulle persone a cui rivolgersi in caso di problematiche psicosociali?'],
		['MM171_1', 'Adempimento obblighi di legge', 'Nella vostra azienda, quanto sono importanti i seguenti motivi per spingervi ad affrontare questioni relative a sicurezza e salute? Per ognuno dei seguenti aspetti mi dica se è un motivo prioritario, secondario o se non lo è affattoAdempimento obblighi di legge'],
		['MM171_2', 'Richieste da parte dei dipendenti o dei loro rappresentanti', 'Nella vostra azienda, quanto sono importanti i seguenti motivi per spingervi ad affrontare questioni relative a sicurezza e salute? Per ognuno dei seguenti aspetti mi dica se è un motivo prioritario, secondario o se non lo è affattoRichieste da parte dei dipendenti o dei loro rappresentanti'],
		['MM171_3', 'Gestione delle assenze e strategia di mantenimento personale', 'Nella vostra azienda, quanto sono importanti i seguenti motivi per spingervi ad affrontare questioni relative a sicurezza e salute? Per ognuno dei seguenti aspetti mi dica se è un motivo prioritario, secondario o se non lo è affattoGestione delle assenze e strategia di mantenimento personale'],
		['MM171_4', 'Motivi economici o legati alle prestazioni', 'Nella vostra azienda, quanto sono importanti i seguenti motivi per spingervi ad affrontare questioni relative a sicurezza e salute? Per ognuno dei seguenti aspetti mi dica se è un motivo prioritario, secondario o se non lo è affattoMotivi economici o legati alle prestazioni'],
		['MM171_5', 'Richieste da parte di clienti o preoccupazione per la reputazione dellazienda', 'Nella vostra azienda, quanto sono importanti i seguenti motivi per spingervi ad affrontare questioni relative a sicurezza e salute? Per ognuno dei seguenti aspetti mi dica se è un motivo prioritario, secondario o se non lo è affattoRichieste da parte di clienti o preoccupazione per la reputazione dellazienda'],
		['MM171_6', 'Pressioni da parte degli organi di vigilanza.', 'Nella vostra azienda, quanto sono importanti i seguenti motivi per spingervi ad affrontare questioni relative a sicurezza e salute? Per ognuno dei seguenti aspetti mi dica se è un motivo prioritario, secondario o se non lo è affattoPressioni da parte degli organi di vigilanza.'],
		['MM172_1', 'Mancanza di risorse quali tempo, soldi e personale', 'Quali sono le maggiori difficoltà nellaffrontare questioni relative a sicurezza e salute nella vostra sede? Per ognuno dei seguenti aspetti mi dica se è una difficoltà importante, secondaria o se non è affatto una difficoltà.Mancanza di risorse quali tempo, soldi e personale'],
		['MM172_2', 'Mancanza di consapevolezza/cultura', 'Quali sono le maggiori difficoltà nellaffrontare questioni relative a sicurezza e salute nella vostra sede? Per ognuno dei seguenti aspetti mi dica se è una difficoltà importante, secondaria o se non è affatto una difficoltà.Mancanza di consapevolezza/cultura'],
		['MM172_3', 'Mancanza di conoscenza e preparazione', 'Quali sono le maggiori difficoltà nellaffrontare questioni relative a sicurezza e salute nella vostra sede? Per ognuno dei seguenti aspetti mi dica se è una difficoltà importante, secondaria o se non è affatto una difficoltà.Mancanza di conoscenza e preparazione'],
		['MM172_4', 'Mancanza di sostegno tecnico e guida', 'Quali sono le maggiori difficoltà nellaffrontare questioni relative a sicurezza e salute nella vostra sede? Per ognuno dei seguenti aspetti mi dica se è una difficoltà importante, secondaria o se non è affatto una difficoltà.Mancanza di sostegno tecnico e guida'],
		['MM172_5', 'La cultura nellazienda', 'Quali sono le maggiori difficoltà nellaffrontare questioni relative a sicurezza e salute nella vostra sede? Per ognuno dei seguenti aspetti mi dica se è una difficoltà importante, secondaria o se non è affatto una difficoltà.La cultura nellazienda'],
		['MM172_6', 'La delicatezza della questione', 'Quali sono le maggiori difficoltà nellaffrontare questioni relative a sicurezza e salute nella vostra sede? Per ognuno dei seguenti aspetti mi dica se è una difficoltà importante, secondaria o se non è affatto una difficoltà.La delicatezza della questione'],
		['MM300', 'In confronto ad altre questioni relative a sicurezza e salute, è più difficile, meno difficile o non cè differenza nel gestire il rischio psicosociale?', 'In confronto ad altre questioni relative a sicurezza e salute, è più difficile, meno difficile o non cè differenza nel gestire il rischio psicosociale?'],
		['MM302', 'Avete mai utilizzato informazioni o supporto da qualche fonte esterna su come gestire il rischio psicosociale?', 'Avete mai utilizzato informazioni o supporto da qualche fonte esterna su come gestire il rischio psicosociale?'],
		['MM303a', 'Pensa che dovreste avere più informazioni o supporto su questo argomento?', 'Pensa che dovreste avere più informazioni o supporto su questo argomento?<br><br>Domanda rivolta alle organizzazioni che riferiscono di utilizzare informazioni o di appoggiarsi a fonti esterne per avere supporto su come affrontare i rischi psicosociali nel luogo di lavoro.'],
		['MM350', 'Avete una Rappresentanza Sindacale Unitaria o Aziendale (RSU or RSA) nella vostra azienda?', 'Avete una Rappresentanza Sindacale Unitaria o Aziendale (RSU or RSA) nella vostra azienda?'],
		['MM351', 'Avete una organizzazione sindacale in azienda?', 'Avete una organizzazione sindacale in azienda?'],
		['MM355all', 'La vostra sede ha un rappresentante dei lavoratori per la sicurezza (RLS) interno?', 'La vostra sede ha un rappresentante dei lavoratori per la sicurezza (RLS) interno?<br><br>NL: Esiste un rappresentante dei lavoratori per la sicurezza (RLS) nella vostra azienda?'],
		['MM358', 'Esiste un Comitato per la Salute e la Sicurezza in azienda?', 'Esiste un Comitato per la Salute e la Sicurezza in azienda?']
	];
