//Auto Generated file
var subset_
	 = [
	
		['sec3', 'Veiklos sektorius'],
		['size_4', 'Įmonės dydis']
	];
var subset_subsetValue
	 = [
	
		['sec3', 'All', 'Visi sektoriai'],
		['sec3', '1--Producing-Industries', 'Gamybos sektorius'],
		['sec3', '2--Private-Services', 'Privačiosios paslaugos'],
		['sec3', '3--Public-Services', 'Viešosios paslaugos'],
		['size_4', 'All', 'Visi sektoriai'],
		['size_4', '1--10-to-19-employees', 'Nuo 10 iki 19 darbuotojų'],
		['size_4', '2--20-to-49-employees', 'Nuo 20 iki 49 darbuotojų'],
		['size_4', '3--50-to-249-employees', 'Nuo 50 iki 249 darbuotojų'],
		['size_4', '4--250-employees-or-more', '250 ir daugiau darbuotojų']
	];
var topic_
	 = [
	
		['', 'Visi sektoriai (70)'],
		['DSS valdymas', 'DSS valdymas (29)'],
		['Darbuotojų dalyvavimas', 'Darbuotojų dalyvavimas (4)'],
		['Paskatos ir kliūtys', 'Paskatos ir kliūtys (15)'],
		['Psichosocialinė rizika ir jos valdymas', 'Psichosocialinė rizika ir jos valdymas (22)']
	];
var topic_question
	 = [
	
		['DSS valdymas', 'MM150_1', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Pagal darbo pobūdį specializuotas gydytojas'],
		['DSS valdymas', 'MM150_2', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Darbų saugos specialistas'],
		['DSS valdymas', 'MM150_3', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Psichologas'],
		['DSS valdymas', 'MM150_4', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Ergonomikos ekspertas, sprendžiantis darbo vietos įrengimo klausimus'],
		['DSS valdymas', 'MM150_5', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Bendrosios darbų saugos ir sveikatos konsultacijos'],
		['DSS valdymas', 'MM152', 'Ar Jūsų įmonėje nebuvimo darbe dėl ligos priežastys yra nagrinėjamos?'],
		['DSS valdymas', 'MM153', 'Ar imatės priemonių, kurios padėtų darbuotojams grįžti į darbą po ilgalaikio nebuvimo darbe dėl ligos?'],
		['DSS valdymas', 'MM154', 'Ar darbuotojų sveikata stebima atliekant reguliarias medicinines patikras?'],
		['DSS valdymas', 'MM155', 'Ar Jūsų įmonė turi dokumentais patvirtintą politiką, įdiegtą valdymo sistemą arba veiksmų planą sveikatos ir darbų saugos klausimais?'],
		['DSS valdymas', 'MM158', 'Ar aukšto lygio vadovybės posėdžiuose sveikatos ir darbų saugos klausimai yra keliami nuolat, kartais, o gal nekeliami niekada?'],
		['DSS valdymas', 'MM159', 'O kaip Jūs bendrai įvertintumėte kitų vadovaujančių asmenų Jūsų įmonėje dalyvavimą sveikatos ir darbų saugos priežiūroje? Ar jis yra labai aktyvus, gana aktyvus, gana pasyvus arba labai pasyvus?'],
		['DSS valdymas', 'MM161', 'Ar įmonėje yra reguliariai atliekama darbo vietų patikra sveikatos ir darbų saugos požiūriu, kuomet yra įvertinami rizikos veiksniai?'],
		['DSS valdymas', 'MM170', 'Ar per paskutinius 3 metus Darbo inspekcija nors kartą tikrino darbo saugos ir sveikatos laikymąsi Jūsų įmonėje?'],
		['DSS valdymas', 'MM173_1', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Oficialios darbo saugos ir sveikatos priežiūros institucijos'],
		['DSS valdymas', 'MM173_2', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Europos saugos ir sveikatos darbe agentūra'],
		['DSS valdymas', 'MM173_3', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Įmonės sveikatos ir darbų saugos skyrius/ darbuotojai'],
		['DSS valdymas', 'MM173_4', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Darbo inspekcija'],
		['DSS valdymas', 'MM173_5', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Darbdavių organizacijos'],
		['DSS valdymas', 'MM173_6', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Profesinės sąjungos'],
		['DSS valdymas', 'MM173_7', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Samdomi sveikatos ir darbų saugos ekspertai'],
		['DSS valdymas', 'MM173_8', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Draudimo paslaugų teikėjai'],
		['DSS valdymas', 'MM175', 'Ar žinote apie Europos saugos ir sveikatos darbe savaitę?'],
		['DSS valdymas', 'MM200_1', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?: Pavojingos medžiagos (pvz., dulkės, cheminės, biologinės arba radioaktyvios medžiagos)'],
		['DSS valdymas', 'MM200_2', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?: Nelaimingi atsitikimai'],
		['DSS valdymas', 'MM200_3', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?: Triukšmas ir vibracija'],
		['DSS valdymas', 'MM200_4', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?: Kaulų ir raumenų sistemos pažeidimai, pvz., nugaros, kaklo, rankų arba kojų skausmai'],
		['DSS valdymas', 'MM200_5', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?: Su darbu susijęs stresas'],
		['DSS valdymas', 'MM200_6', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?: Prievarta arba prievartos grėsmė'],
		['DSS valdymas', 'MM200_7', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?: Persekiojimas arba priekabiavimas, t.y. bendradarbių arba viršininkų vykdomas smurtavimas, žeminimas arba užpuolimas'],
		['Psichosocialinė rizika ir jos valdymas', 'MM202_1', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Laiko trūkumo keliamas stresas'],
		['Psichosocialinė rizika ir jos valdymas', 'MM202_2', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Nepakankama komunikacija tarp vadovybės ir darbuotojų'],
		['Psichosocialinė rizika ir jos valdymas', 'MM202_3', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Nepakankamas bendradarbiavimas tarp bendradarbių'],
		['Psichosocialinė rizika ir jos valdymas', 'MM202_4', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Nepakankama darbuotojų kontrolė organizuojant jų darbą'],
		['Psichosocialinė rizika ir jos valdymas', 'MM202_5', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Darbo saugumas'],
		['Psichosocialinė rizika ir jos valdymas', 'MM202_6', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Būtinybė turėti reikalų su problemiškais klientais, pacientais, mokiniais ir pan.'],
		['Psichosocialinė rizika ir jos valdymas', 'MM202_7', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Vadovybės ir darbuotojų santykių problemos'],
		['Psichosocialinė rizika ir jos valdymas', 'MM202_8', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Ilgai trunkančios arba nereguliarios darbo valandos'],
		['Psichosocialinė rizika ir jos valdymas', 'MM202_9', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Neaiški žmogiškųjų išteklių politika'],
		['Psichosocialinė rizika ir jos valdymas', 'MM202_10', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Diskriminacija (pvz., dėl lyties, amžiaus arba tautinės kilmės)'],
		['Psichosocialinė rizika ir jos valdymas', 'MM250', 'Ar Jūsų įmonė turi nustatytą tvarką, kaip spręsti su darbu susijusio streso klausimus?'],
		['Psichosocialinė rizika ir jos valdymas', 'MM251', 'Ar yra nustatyta tvarka, kaip spręsti klausimus, susijusius su darbuotojų persekiojimu arba priekabiavimu?'],
		['Psichosocialinė rizika ir jos valdymas', 'MM252', 'Ar Jūsų įmonė turi procedūras, nurodančias kaip spręsti su darbu susijusios prievartos klausimus?'],
		['Psichosocialinė rizika ir jos valdymas', 'MM253_1', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?: Darbo organizavimo būdo pokyčiai'],
		['Psichosocialinė rizika ir jos valdymas', 'MM253_2', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?: Darbo vietos pertvarkymas'],
		['Psichosocialinė rizika ir jos valdymas', 'MM253_3', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?: Konfidencialus darbuotojų konsultavimas'],
		['Psichosocialinė rizika ir jos valdymas', 'MM253_4', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?: Konfliktų sprendimo tvarkos nustatymas'],
		['Psichosocialinė rizika ir jos valdymas', 'MM253_5', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?: Darbo laiko tvarkos pokyčiai'],
		['Psichosocialinė rizika ir jos valdymas', 'MM253_6', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?: Apmokymų užtikrinimas'],
		['Psichosocialinė rizika ir jos valdymas', 'MM256', 'Ar Jūsų įmonė imasi kokių nors veiksmų, jei pavieniai darbuotojai dirba pernelyg ilgai arba nereguliariai?'],
		['Psichosocialinė rizika ir jos valdymas', 'MM259', 'Ar informuojate darbuotojus apie psichologinius ir socialinius rizikos veiksnius ir jų poveikį sveikatai ir darbų saugai?'],
		['Psichosocialinė rizika ir jos valdymas', 'MM260', 'Ar jie yra informuoti, į ką turėtų kreiptis, jei iškiltų su darbu susijusios psichologinės ir socialinės problemos?'],
		['Paskatos ir kliūtys', 'MM171_1', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Teisinių prievolių įvykdymas'],
		['Paskatos ir kliūtys', 'MM171_2', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbuotojų arba jų atstovų prašymai'],
		['Paskatos ir kliūtys', 'MM171_3', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbuotojų išlaikymas ir nebuvimo darbe valdymas'],
		['Paskatos ir kliūtys', 'MM171_4', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Ekonominės arba su darbo atlikimu susijusios priežastys'],
		['Paskatos ir kliūtys', 'MM171_5', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Klientų reikalavimai arba susirūpinimas organizacijos reputacija'],
		['Paskatos ir kliūtys', 'MM171_6', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Spaudimas iš Darbo inspekcijos'],
		['Paskatos ir kliūtys', 'MM172_1', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Trūksta išteklių - pvz., laiko, darbuotojų arba pinigų'],
		['Paskatos ir kliūtys', 'MM172_2', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Trūksta supratingumo'],
		['Paskatos ir kliūtys', 'MM172_3', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Trūksta patirties ir žinių'],
		['Paskatos ir kliūtys', 'MM172_4', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Trūksta techninės paramos arba konsultacijų'],
		['Paskatos ir kliūtys', 'MM172_5', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Nepalanki įmonės vidaus kultūra'],
		['Paskatos ir kliūtys', 'MM172_6', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Pats klausimo jautrumas'],
		['Paskatos ir kliūtys', 'MM300', 'Palyginus su kitais darbų saugos ir sveikatos klausimais, ar psichologinius ir socialinius rizikos veiksnius suvaldyti yra sunkiau, lengviau, o gal nėra jokio skirtumo?'],
		['Paskatos ir kliūtys', 'MM302', 'Ar naudojotės informacija arba parama iš išorės šaltinių, apie tai kaip spręsti klausimus, susijusius su psichologiniais ir socialiniais rizikos veiksniais darbe?'],
		['Paskatos ir kliūtys', 'MM303a', 'Ar Jums norėtumėte papildomos informacijos arba paramos šiais klausimais?'],
		['Darbuotojų dalyvavimas', 'MM350', 'Ar įmonėje turite Darbo tarybą?'],
		['Darbuotojų dalyvavimas', 'MM351', 'Ar Jūsų įmonėje yra darbuotojų profesinės sąjungos atstovas?'],
		['Darbuotojų dalyvavimas', 'MM355all', 'Ar Jūsų įmonė turi darbuotojų atstovą darbų saugos ir sveikatos klausimams?'],
		['Darbuotojų dalyvavimas', 'MM358', 'Ar Jūsų įmonėje yra Darbuotojų saugos ir sveikatos komitetas?']
	];
var question_
	 = [
	
		['MM150_1', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Pagal darbo pobūdį specializuotas gydytojas'],
		['MM150_2', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Darbų saugos specialistas'],
		['MM150_3', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Psichologas'],
		['MM150_4', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Ergonomikos ekspertas, sprendžiantis darbo vietos įrengimo klausimus'],
		['MM150_5', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Bendrosios darbų saugos ir sveikatos konsultacijos'],
		['MM152', 'Ar Jūsų įmonėje nebuvimo darbe dėl ligos priežastys yra nagrinėjamos?'],
		['MM153', 'Ar imatės priemonių, kurios padėtų darbuotojams grįžti į darbą po ilgalaikio nebuvimo darbe dėl ligos?'],
		['MM154', 'Ar darbuotojų sveikata stebima atliekant reguliarias medicinines patikras?'],
		['MM155', 'Ar Jūsų įmonė turi dokumentais patvirtintą politiką, įdiegtą valdymo sistemą arba veiksmų planą sveikatos ir darbų saugos klausimais?'],
		['MM158', 'Ar aukšto lygio vadovybės posėdžiuose sveikatos ir darbų saugos klausimai yra keliami nuolat, kartais, o gal nekeliami niekada?'],
		['MM159', 'O kaip Jūs bendrai įvertintumėte kitų vadovaujančių asmenų Jūsų įmonėje dalyvavimą sveikatos ir darbų saugos priežiūroje? Ar jis yra labai aktyvus, gana aktyvus, gana pasyvus arba labai pasyvus?'],
		['MM161', 'Ar įmonėje yra reguliariai atliekama darbo vietų patikra sveikatos ir darbų saugos požiūriu, kuomet yra įvertinami rizikos veiksniai?'],
		['MM170', 'Ar per paskutinius 3 metus Darbo inspekcija nors kartą tikrino darbo saugos ir sveikatos laikymąsi Jūsų įmonėje?'],
		['MM173_1', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Oficialios darbo saugos ir sveikatos priežiūros institucijos'],
		['MM173_2', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Europos saugos ir sveikatos darbe agentūra'],
		['MM173_3', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Įmonės sveikatos ir darbų saugos skyrius/ darbuotojai'],
		['MM173_4', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Darbo inspekcija'],
		['MM173_5', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Darbdavių organizacijos'],
		['MM173_6', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Profesinės sąjungos'],
		['MM173_7', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Samdomi sveikatos ir darbų saugos ekspertai'],
		['MM173_8', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?: Draudimo paslaugų teikėjai'],
		['MM175', 'Ar žinote apie Europos saugos ir sveikatos darbe savaitę?'],
		['MM200_1', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?: Pavojingos medžiagos (pvz., dulkės, cheminės, biologinės arba radioaktyvios medžiagos)'],
		['MM200_2', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?: Nelaimingi atsitikimai'],
		['MM200_3', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?: Triukšmas ir vibracija'],
		['MM200_4', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?: Kaulų ir raumenų sistemos pažeidimai, pvz., nugaros, kaklo, rankų arba kojų skausmai'],
		['MM200_5', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?: Su darbu susijęs stresas'],
		['MM200_6', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?: Prievarta arba prievartos grėsmė'],
		['MM200_7', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?: Persekiojimas arba priekabiavimas, t.y. bendradarbių arba viršininkų vykdomas smurtavimas, žeminimas arba užpuolimas'],
		['MM202_1', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Laiko trūkumo keliamas stresas'],
		['MM202_2', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Nepakankama komunikacija tarp vadovybės ir darbuotojų'],
		['MM202_3', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Nepakankamas bendradarbiavimas tarp bendradarbių'],
		['MM202_4', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Nepakankama darbuotojų kontrolė organizuojant jų darbą'],
		['MM202_5', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Darbo saugumas'],
		['MM202_6', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Būtinybė turėti reikalų su problemiškais klientais, pacientais, mokiniais ir pan.'],
		['MM202_7', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Vadovybės ir darbuotojų santykių problemos'],
		['MM202_8', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Ilgai trunkančios arba nereguliarios darbo valandos'],
		['MM202_9', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Neaiški žmogiškųjų išteklių politika'],
		['MM202_10', 'Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.: Diskriminacija (pvz., dėl lyties, amžiaus arba tautinės kilmės)'],
		['MM250', 'Ar Jūsų įmonė turi nustatytą tvarką, kaip spręsti su darbu susijusio streso klausimus?'],
		['MM251', 'Ar yra nustatyta tvarka, kaip spręsti klausimus, susijusius su darbuotojų persekiojimu arba priekabiavimu?'],
		['MM252', 'Ar Jūsų įmonė turi procedūras, nurodančias kaip spręsti su darbu susijusios prievartos klausimus?'],
		['MM253_1', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?: Darbo organizavimo būdo pokyčiai'],
		['MM253_2', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?: Darbo vietos pertvarkymas'],
		['MM253_3', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?: Konfidencialus darbuotojų konsultavimas'],
		['MM253_4', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?: Konfliktų sprendimo tvarkos nustatymas'],
		['MM253_5', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?: Darbo laiko tvarkos pokyčiai'],
		['MM253_6', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?: Apmokymų užtikrinimas'],
		['MM256', 'Ar Jūsų įmonė imasi kokių nors veiksmų, jei pavieniai darbuotojai dirba pernelyg ilgai arba nereguliariai?'],
		['MM259', 'Ar informuojate darbuotojus apie psichologinius ir socialinius rizikos veiksnius ir jų poveikį sveikatai ir darbų saugai?'],
		['MM260', 'Ar jie yra informuoti, į ką turėtų kreiptis, jei iškiltų su darbu susijusios psichologinės ir socialinės problemos?'],
		['MM171_1', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Teisinių prievolių įvykdymas'],
		['MM171_2', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbuotojų arba jų atstovų prašymai'],
		['MM171_3', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbuotojų išlaikymas ir nebuvimo darbe valdymas'],
		['MM171_4', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Ekonominės arba su darbo atlikimu susijusios priežastys'],
		['MM171_5', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Klientų reikalavimai arba susirūpinimas organizacijos reputacija'],
		['MM171_6', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Spaudimas iš Darbo inspekcijos'],
		['MM172_1', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Trūksta išteklių - pvz., laiko, darbuotojų arba pinigų'],
		['MM172_2', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Trūksta supratingumo'],
		['MM172_3', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Trūksta patirties ir žinių'],
		['MM172_4', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Trūksta techninės paramos arba konsultacijų'],
		['MM172_5', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Nepalanki įmonės vidaus kultūra'],
		['MM172_6', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Pats klausimo jautrumas'],
		['MM300', 'Palyginus su kitais darbų saugos ir sveikatos klausimais, ar psichologinius ir socialinius rizikos veiksnius suvaldyti yra sunkiau, lengviau, o gal nėra jokio skirtumo?'],
		['MM302', 'Ar naudojotės informacija arba parama iš išorės šaltinių, apie tai kaip spręsti klausimus, susijusius su psichologiniais ir socialiniais rizikos veiksniais darbe?'],
		['MM303a', 'Ar Jums norėtumėte papildomos informacijos arba paramos šiais klausimais?'],
		['MM350', 'Ar įmonėje turite Darbo tarybą?'],
		['MM351', 'Ar Jūsų įmonėje yra darbuotojų profesinės sąjungos atstovas?'],
		['MM355all', 'Ar Jūsų įmonė turi darbuotojų atstovą darbų saugos ir sveikatos klausimams?'],
		['MM358', 'Ar Jūsų įmonėje yra Darbuotojų saugos ir sveikatos komitetas?']
	];
var question_answer
	 = [
	
		['MM150_1', '1--Yes', 'Taip'],
		['MM150_1', '2--No', 'Ne'],
		['MM150_1', '3--DK--NA', 'Neatsakė'],
		['MM150_2', '1--Yes', 'Taip'],
		['MM150_2', '2--No', 'Ne'],
		['MM150_2', '3--DK--NA', 'Neatsakė'],
		['MM150_3', '1--Yes', 'Taip'],
		['MM150_3', '2--No', 'Ne'],
		['MM150_3', '3--DK--NA', 'Neatsakė'],
		['MM150_4', '1--Yes', 'Taip'],
		['MM150_4', '2--No', 'Ne'],
		['MM150_4', '3--DK--NA', 'Neatsakė'],
		['MM150_5', '1--Yes', 'Taip'],
		['MM150_5', '2--No', 'Ne'],
		['MM150_5', '3--DK--NA', 'Neatsakė'],
		['MM152', '1--Yes', 'Taip'],
		['MM152', '2--No', 'Ne'],
		['MM152', '3--DK--NA', 'Neatsakė'],
		['MM153', '1--Yes', 'Taip'],
		['MM153', '2--No', 'Ne'],
		['MM153', '3--DK--NA', 'Neatsakė'],
		['MM154', '1--Yes', 'Taip'],
		['MM154', '2--No', 'Ne'],
		['MM154', '3--DK--NA', 'Neatsakė'],
		['MM155', '1--Yes', 'Taip'],
		['MM155', '2--No', 'Ne'],
		['MM155', '3--DK--NA', 'Neatsakė'],
		['MM158', '1--Regularly', 'Nuolat'],
		['MM158', '2--Occasionally', 'Kartais'],
		['MM158', '3--Practically-never', 'Niekada'],
		['MM158', '4--DK--NA', 'Neatsakė'],
		['MM159', '1--Very-high', 'Labai aktyvus'],
		['MM159', '2--Quite-high', 'Gana aktyvus'],
		['MM159', '3--Quite-low', 'Gana pasyvus'],
		['MM159', '4--Very-low', 'Labai pasyvus'],
		['MM159', '5--DK--NA', 'Neatsakė'],
		['MM161', '1--Yes', 'Taip'],
		['MM161', '2--No', 'Ne'],
		['MM161', '3--DK--NA', 'Neatsakė'],
		['MM170', '1--Yes', 'Taip'],
		['MM170', '2--No', 'Ne'],
		['MM170', '3--DK--NA', 'Neatsakė'],
		['MM171_1', '1--Major', 'Svarbi priežastis'],
		['MM171_1', '2--Minor', 'Nesvarbi priežastis'],
		['MM171_1', '3--No', 'Nėra priežastis'],
		['MM171_1', '4--DK--NA', 'Neatsakė'],
		['MM171_2', '1--Major', 'Svarbi priežastis'],
		['MM171_2', '2--Minor', 'Nesvarbi priežastis'],
		['MM171_2', '3--No', 'Nėra priežastis'],
		['MM171_2', '4--DK--NA', 'Neatsakė'],
		['MM171_3', '1--Major', 'Svarbi priežastis'],
		['MM171_3', '2--Minor', 'Nesvarbi priežastis'],
		['MM171_3', '3--No', 'Nėra priežastis'],
		['MM171_3', '4--DK--NA', 'Neatsakė'],
		['MM171_4', '1--Major', 'Svarbi priežastis'],
		['MM171_4', '2--Minor', 'Nesvarbi priežastis'],
		['MM171_4', '3--No', 'Nėra priežastis'],
		['MM171_4', '4--DK--NA', 'Neatsakė'],
		['MM171_5', '1--Major', 'Svarbi priežastis'],
		['MM171_5', '2--Minor', 'Nesvarbi priežastis'],
		['MM171_5', '3--No', 'Nėra priežastis'],
		['MM171_5', '4--DK--NA', 'Neatsakė'],
		['MM171_6', '1--Major', 'Svarbi priežastis'],
		['MM171_6', '2--Minor', 'Nesvarbi priežastis'],
		['MM171_6', '3--No', 'Nėra priežastis'],
		['MM171_6', '4--DK--NA', 'Neatsakė'],
		['MM172_1', '1--Major', 'Didelė problema'],
		['MM172_1', '2--Minor', 'Nedidelė problema'],
		['MM172_1', '3--No', 'Nėra jokia problema'],
		['MM172_1', '4--DK--NA', 'Neatsakė'],
		['MM172_2', '1--Major', 'Didelė problema'],
		['MM172_2', '2--Minor', 'Nedidelė problema'],
		['MM172_2', '3--No', 'Nėra jokia problema'],
		['MM172_2', '4--DK--NA', 'Neatsakė'],
		['MM172_3', '1--Major', 'Didelė problema'],
		['MM172_3', '2--Minor', 'Nedidelė problema'],
		['MM172_3', '3--No', 'Nėra jokia problema'],
		['MM172_3', '4--DK--NA', 'Neatsakė'],
		['MM172_4', '1--Major', 'Didelė problema'],
		['MM172_4', '2--Minor', 'Nedidelė problema'],
		['MM172_4', '3--No', 'Nėra jokia problema'],
		['MM172_4', '4--DK--NA', 'Neatsakė'],
		['MM172_5', '1--Major', 'Didelė problema'],
		['MM172_5', '2--Minor', 'Nedidelė problema'],
		['MM172_5', '3--No', 'Nėra jokia problema'],
		['MM172_5', '4--DK--NA', 'Neatsakė'],
		['MM172_6', '1--Major', 'Didelė problema'],
		['MM172_6', '2--Minor', 'Nedidelė problema'],
		['MM172_6', '3--No', 'Nėra jokia problema'],
		['MM172_6', '4--DK--NA', 'Neatsakė'],
		['MM173_1', '1--Yes', 'Taip'],
		['MM173_1', '2--No', 'Ne'],
		['MM173_1', '3--DK--NA', 'Neatsakė'],
		['MM173_2', '1--Yes', 'Taip'],
		['MM173_2', '2--No', 'Ne'],
		['MM173_2', '3--DK--NA', 'Neatsakė'],
		['MM173_3', '1--Yes', 'Taip'],
		['MM173_3', '2--No', 'Ne'],
		['MM173_3', '3--DK--NA', 'Neatsakė'],
		['MM173_4', '1--Yes', 'Taip'],
		['MM173_4', '2--No', 'Ne'],
		['MM173_4', '3--DK--NA', 'Neatsakė'],
		['MM173_5', '1--Yes', 'Taip'],
		['MM173_5', '2--No', 'Ne'],
		['MM173_5', '3--DK--NA', 'Neatsakė'],
		['MM173_6', '1--Yes', 'Taip'],
		['MM173_6', '2--No', 'Ne'],
		['MM173_6', '3--DK--NA', 'Neatsakė'],
		['MM173_7', '1--Yes', 'Taip'],
		['MM173_7', '2--No', 'Ne'],
		['MM173_7', '3--DK--NA', 'Neatsakė'],
		['MM173_8', '1--Yes', 'Taip'],
		['MM173_8', '2--No', 'Ne'],
		['MM173_8', '3--DK--NA', 'Neatsakė'],
		['MM175', '1--Yes', 'Taip'],
		['MM175', '2--No', 'Ne'],
		['MM175', '3--DK--NA', 'Neatsakė'],
		['MM200_1', '1--Major-concern', 'Didelį susirūpinimą'],
		['MM200_1', '2--Some-concern', 'Tam tikrą susirūpinimą'],
		['MM200_1', '3--No-concern', 'Jokio susirūpinimo'],
		['MM200_1', '4--DK--NA', 'Neatsakė'],
		['MM200_2', '1--Major-concern', 'Didelį susirūpinimą'],
		['MM200_2', '2--Some-concern', 'Tam tikrą susirūpinimą'],
		['MM200_2', '3--No-concern', 'Jokio susirūpinimo'],
		['MM200_2', '4--DK--NA', 'Neatsakė'],
		['MM200_3', '1--Major-concern', 'Didelį susirūpinimą'],
		['MM200_3', '2--Some-concern', 'Tam tikrą susirūpinimą'],
		['MM200_3', '3--No-concern', 'Jokio susirūpinimo'],
		['MM200_3', '4--DK--NA', 'Neatsakė'],
		['MM200_4', '1--Major-concern', 'Didelį susirūpinimą'],
		['MM200_4', '2--Some-concern', 'Tam tikrą susirūpinimą'],
		['MM200_4', '3--No-concern', 'Jokio susirūpinimo'],
		['MM200_4', '4--DK--NA', 'Neatsakė'],
		['MM200_5', '1--Major-concern', 'Didelį susirūpinimą'],
		['MM200_5', '2--Some-concern', 'Tam tikrą susirūpinimą'],
		['MM200_5', '3--No-concern', 'Jokio susirūpinimo'],
		['MM200_5', '4--DK--NA', 'Neatsakė'],
		['MM200_6', '1--Major-concern', 'Didelį susirūpinimą'],
		['MM200_6', '2--Some-concern', 'Tam tikrą susirūpinimą'],
		['MM200_6', '3--No-concern', 'Jokio susirūpinimo'],
		['MM200_6', '4--DK--NA', 'Neatsakė'],
		['MM200_7', '1--Major-concern', 'Didelį susirūpinimą'],
		['MM200_7', '2--Some-concern', 'Tam tikrą susirūpinimą'],
		['MM200_7', '3--No-concern', 'Jokio susirūpinimo'],
		['MM200_7', '4--DK--NA', 'Neatsakė'],
		['MM202_1', '1--Yes', 'Taip'],
		['MM202_1', '2--No', 'Ne'],
		['MM202_1', '3--DK--NA', 'Neatsakė'],
		['MM202_10', '1--Yes', 'Taip'],
		['MM202_10', '2--No', 'Ne'],
		['MM202_10', '3--DK--NA', 'Neatsakė'],
		['MM202_2', '1--Yes', 'Taip'],
		['MM202_2', '2--No', 'Ne'],
		['MM202_2', '3--DK--NA', 'Neatsakė'],
		['MM202_3', '1--Yes', 'Taip'],
		['MM202_3', '2--No', 'Ne'],
		['MM202_3', '3--DK--NA', 'Neatsakė'],
		['MM202_4', '1--Yes', 'Taip'],
		['MM202_4', '2--No', 'Ne'],
		['MM202_4', '3--DK--NA', 'Neatsakė'],
		['MM202_5', '1--Yes', 'Taip'],
		['MM202_5', '2--No', 'Ne'],
		['MM202_5', '3--DK--NA', 'Neatsakė'],
		['MM202_6', '1--Yes', 'Taip'],
		['MM202_6', '2--No', 'Ne'],
		['MM202_6', '3--DK--NA', 'Neatsakė'],
		['MM202_7', '1--Yes', 'Taip'],
		['MM202_7', '2--No', 'Ne'],
		['MM202_7', '3--DK--NA', 'Neatsakė'],
		['MM202_8', '1--Yes', 'Taip'],
		['MM202_8', '2--No', 'Ne'],
		['MM202_8', '3--DK--NA', 'Neatsakė'],
		['MM202_9', '1--Yes', 'Taip'],
		['MM202_9', '2--No', 'Ne'],
		['MM202_9', '3--DK--NA', 'Neatsakė'],
		['MM250', '1--Yes', 'Taip'],
		['MM250', '2--No', 'Ne'],
		['MM250', '3--Work-related-stress-is-not-an-issue-in-our-establishment', 'Su darbu susijęs stresas nekelia jokių problemų mūsų įmonėje'],
		['MM250', '4--No-answer', 'Neatsakė'],
		['MM251', '1--Yes', 'Taip'],
		['MM251', '2--No', 'Ne'],
		['MM251', '3--These-problems-are-not-an-issue-in-our-establishment', 'Šios problemos nekyla mūsų įmonėje'],
		['MM251', '4--No-answer', 'Neatsakė'],
		['MM252', '1--Yes', 'Taip'],
		['MM252', '2--No', 'Ne'],
		['MM252', '3--Work-related-violence-is-not-an-issue-in-our-establishment', 'Su darbu susijusi prievarta nekelia jokių problemų mūsų įmonėje'],
		['MM252', '4--No-answer', 'Neatsakė'],
		['MM253_1', '1--Yes', 'Taip'],
		['MM253_1', '2--No', 'Ne'],
		['MM253_1', '3--DK--NA', 'Neatsakė'],
		['MM253_2', '1--Yes', 'Taip'],
		['MM253_2', '2--No', 'Ne'],
		['MM253_2', '3--DK--NA', 'Neatsakė'],
		['MM253_3', '1--Yes', 'Taip'],
		['MM253_3', '2--No', 'Ne'],
		['MM253_3', '3--DK--NA', 'Neatsakė'],
		['MM253_4', '1--Yes', 'Taip'],
		['MM253_4', '2--No', 'Ne'],
		['MM253_4', '3--DK--NA', 'Neatsakė'],
		['MM253_5', '1--Yes', 'Taip'],
		['MM253_5', '2--No', 'Ne'],
		['MM253_5', '3--DK--NA', 'Neatsakė'],
		['MM253_6', '1--Yes', 'Taip'],
		['MM253_6', '2--No', 'Ne'],
		['MM253_6', '3--DK--NA', 'Neatsakė'],
		['MM256', '1--Yes', 'Taip'],
		['MM256', '2--No', 'Ne'],
		['MM256', '3--Long-or-irregular-working-hours-are-not-an-issue-in-our-esta', 'Ilgos arba nereguliarios darbo valandos nekelia jokių problemų mūsų įmonėje'],
		['MM256', '4--No-answer', 'Neatsakė'],
		['MM259', '1--Yes', 'Taip'],
		['MM259', '2--No', 'Ne'],
		['MM259', '3--No-answer', 'Neatsakė'],
		['MM260', '1--Yes', 'Taip'],
		['MM260', '2--No', 'Ne'],
		['MM260', '3--No-answer', 'Neatsakė'],
		['MM300', '1--More-difficult', 'Sunkiau'],
		['MM300', '2--Less-difficult', 'Lengviau'],
		['MM300', '3--No-difference', 'Jokio skirtumo'],
		['MM300', '4--No-answer', 'Neatsakė'],
		['MM302', '1--Yes', 'Taip'],
		['MM302', '2--No', 'Ne'],
		['MM302', '3--No-answer', 'Neatsakė'],
		['MM303a', '1--Yes', 'Taip'],
		['MM303a', '2--No', 'Ne'],
		['MM303a', '3--No-answer', 'Neatsakė'],
		['MM350', '1--Yes', 'Taip'],
		['MM350', '2--No', 'Ne'],
		['MM350', '3--No-answer', 'Neatsakė'],
		['MM351', '1--Yes', 'Taip'],
		['MM351', '2--No', 'Ne'],
		['MM351', '3--No-answer', 'Neatsakė'],
		['MM355all', '1--Yes', 'Taip'],
		['MM355all', '2--No', 'Ne'],
		['MM355all', '3--No-answer', 'Neatsakė'],
		['MM358', '1--Yes', 'Taip'],
		['MM358', '2--No', 'Ne'],
		['MM358', '3--No-answer', 'Neatsakė']
	];
var country_
	 = [
	
		['AT', 'Austrija'],
		['BE', 'Belgija'],
		['BG', 'Bulgarija'],
		['CH', 'Šveicarija'],
		['CY', 'Kipras'],
		['CZ', 'Čekija'],
		['DE', 'Vokietija'],
		['DK', 'Danija'],
		['EE', 'Estija'],
		['EL', 'Graikija'],
		['ES', 'Ispanija'],
		['FI', 'Suomija'],
		['FR', 'Prancūzija'],
		['HR', 'Kroatija *'],
		['HU', 'Vengrija'],
		['IE', 'Airija'],
		['IT', 'Italija'],
		['LT', 'Lietuva'],
		['LU', 'Liuksemburgas'],
		['LV', 'Latvija'],
		['MT', 'Malta'],
		['NL', 'Nyderlandai'],
		['NO', 'Norvegija'],
		['PL', 'Lenkija'],
		['PT', 'Portugalija'],
		['RO', 'Rumunija'],
		['SE', 'Švedija'],
		['SI', 'Slovėnija'],
		['SK', 'Slovakija'],
		['TR', 'Turkija'],
		['UK', 'Jungtinė Karalystė'],
		['EuropeanUnion', 'Europos Sąjunga *']
	];
var question_meta
	 = [
	
		['MM150_1', 'Pagal darbo pobūdį specializuotas gydytojas', 'Kokiomis sveikatos ir darbų saugos paslaugomis naudojatės? Nepriklausomai nuo to, ar specialistus turite įmonėje ar samdotePagal darbo pobūdį specializuotas gydytojas'],
		['MM150_2', 'Darbų saugos specialistas', 'Kokiomis sveikatos ir darbų saugos paslaugomis naudojatės? Nepriklausomai nuo to, ar specialistus turite įmonėje ar samdoteDarbų saugos specialistas'],
		['MM150_3', 'Psichologas', 'Kokiomis sveikatos ir darbų saugos paslaugomis naudojatės? Nepriklausomai nuo to, ar specialistus turite įmonėje ar samdotePsichologas'],
		['MM150_4', 'Ergonomikos ekspertas, sprendžiantis darbo vietos įrengimo klausimus', 'Kokiomis sveikatos ir darbų saugos paslaugomis naudojatės? Nepriklausomai nuo to, ar specialistus turite įmonėje ar samdoteErgonomikos ekspertas, sprendžiantis darbo vietos įrengimo klausimus'],
		['MM150_5', 'Bendrosios darbų saugos ir sveikatos konsultacijos', 'Kokiomis sveikatos ir darbų saugos paslaugomis naudojatės? Nepriklausomai nuo to, ar specialistus turite įmonėje ar samdoteBendrosios darbų saugos ir sveikatos konsultacijos'],
		['MM152', 'Ar Jūsų įmonėje nebuvimo darbe dėl ligos priežastys yra nagrinėjamos?', 'Ar Jūsų įmonėje nebuvimo darbe dėl ligos priežastys yra nagrinėjamos?'],
		['MM153', 'Ar imatės priemonių, kurios padėtų darbuotojams grįžti į darbą po ilgalaikio nebuvimo darbe dėl ligos?', 'Ar imatės priemonių, kurios padėtų darbuotojams grįžti į darbą po ilgalaikio nebuvimo darbe dėl ligos?'],
		['MM154', 'Ar darbuotojų sveikata stebima atliekant reguliarias medicinines patikras?', 'Ar darbuotojų sveikata stebima atliekant reguliarias medicinines patikras?'],
		['MM155', 'Ar Jūsų įmonė turi dokumentais patvirtintą politiką, įdiegtą valdymo sistemą arba veiksmų planą sveikatos ir darbų saugos klausimais?', 'Ar Jūsų įmonė turi dokumentais patvirtintą politiką, įdiegtą valdymo sistemą arba veiksmų planą sveikatos ir darbų saugos klausimais?'],
		['MM158', 'Ar aukšto lygio vadovybės posėdžiuose sveikatos ir darbų saugos klausimai yra keliami nuolat, kartais, o gal nekeliami niekada?', 'Ar aukšto lygio vadovybės posėdžiuose sveikatos ir darbų saugos klausimai yra keliami nuolat, kartais, o gal nekeliami niekada?'],
		['MM159', 'O kaip Jūs bendrai įvertintumėte kitų vadovaujančių asmenų Jūsų įmonėje dalyvavimą sveikatos ir darbų saugos priežiūroje? Ar jis yra labai aktyvus, gana aktyvus, gana pasyvus arba labai pasyvus?', 'O kaip Jūs bendrai įvertintumėte kitų vadovaujančių asmenų Jūsų įmonėje dalyvavimą sveikatos ir darbų saugos priežiūroje? Ar jis yra labai aktyvus, gana aktyvus, gana pasyvus arba labai pasyvus?'],
		['MM161', 'Ar įmonėje yra reguliariai atliekama darbo vietų patikra sveikatos ir darbų saugos požiūriu, kuomet yra įvertinami rizikos veiksniai?', 'Ar įmonėje yra reguliariai atliekama darbo vietų patikra sveikatos ir darbų saugos požiūriu, kuomet yra įvertinami rizikos veiksniai?'],
		['MM170', 'Ar per paskutinius 3 metus Darbo inspekcija nors kartą tikrino darbo saugos ir sveikatos laikymąsi Jūsų įmonėje?', 'Ar per paskutinius 3 metus Darbo inspekcija nors kartą tikrino darbo saugos ir sveikatos laikymąsi Jūsų įmonėje?'],
		['MM173_1', 'Oficialios darbo saugos ir sveikatos priežiūros institucijos', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?Oficialios darbo saugos ir sveikatos priežiūros institucijos'],
		['MM173_2', 'Europos saugos ir sveikatos darbe agentūra', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?Europos saugos ir sveikatos darbe agentūra'],
		['MM173_3', 'Įmonės sveikatos ir darbų saugos skyrius/ darbuotojai', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?Įmonės sveikatos ir darbų saugos skyrius/ darbuotojai'],
		['MM173_4', 'Darbo inspekcija', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?Darbo inspekcija'],
		['MM173_5', 'Darbdavių organizacijos', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?Darbdavių organizacijos'],
		['MM173_6', 'Profesinės sąjungos', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?Profesinės sąjungos'],
		['MM173_7', 'Samdomi sveikatos ir darbų saugos ekspertai', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?Samdomi sveikatos ir darbų saugos ekspertai'],
		['MM173_8', 'Draudimo paslaugų teikėjai', 'Ar Jūsų įmonė naudojosi informacija apie sveikatą ir darbų saugą iš bet kurios iš šių organizacijų arba institucijų?Draudimo paslaugų teikėjai'],
		['MM175', 'Ar žinote apie Europos saugos ir sveikatos darbe savaitę?', 'Ar žinote apie Europos saugos ir sveikatos darbe savaitę?'],
		['MM200_1', 'Pavojingos medžiagos (pvz., dulkės, cheminės, biologinės arba radioaktyvios medžiagos)', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?Pavojingos medžiagos (int.: paaiškinkite, jei reikia: pvz., dulkės, cheminės, biologinės arba radioaktyvios medžiagos)'],
		['MM200_2', 'Nelaimingi atsitikimai', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?Nelaimingi atsitikimai'],
		['MM200_3', 'Triukšmas ir vibracija', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?Triukšmas ir vibracija'],
		['MM200_4', 'Kaulų ir raumenų sistemos pažeidimai, pvz., nugaros, kaklo, rankų arba kojų skausmai', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?Kaulų ir raumenų sistemos pažeidimai, pvz., nugaros, kaklo, rankų arba kojų skausmai'],
		['MM200_5', 'Su darbu susijęs stresas', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?Su darbu susijęs stresas'],
		['MM200_6', 'Prievarta arba prievartos grėsmė', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?Prievarta arba prievartos grėsmė'],
		['MM200_7', 'Persekiojimas arba priekabiavimas, t.y. bendradarbių arba viršininkų vykdomas smurtavimas, žeminimas arba užpuolimas', 'Prašome apie kiekvieną iš šių klausimų pasakyti, ar Jūsų įmonėje tai kelia didelį susirūpinimą, tam tikrą susirūpinimą, o gal nekelia jokio susirūpinimo?Persekiojimas arba priekabiavimas, t.y. bendradarbių arba viršininkų vykdomas smurtavimas, žeminimas arba užpuolimas'],
		['MM202_1', 'Laiko trūkumo keliamas stresas', 'Prie streso, prievartos arba priekabiavimo darbe gali prisidėti keletas veiksnių; jie yra susiję su darbo organizavimo pobūdžiu ir dažnai vadinami „psichologiniais ir socialiniais rizikos veiksniais“. Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.Laiko trūkumo keliamas stresas'],
		['MM202_2', 'Nepakankama komunikacija tarp vadovybės ir darbuotojų', 'Prie streso, prievartos arba priekabiavimo darbe gali prisidėti keletas veiksnių; jie yra susiję su darbo organizavimo pobūdžiu ir dažnai vadinami „psichologiniais ir socialiniais rizikos veiksniais“. Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.Nepakankama komunikacija tarp vadovybės ir darbuotojų'],
		['MM202_3', 'Nepakankamas bendradarbiavimas tarp bendradarbių', 'Prie streso, prievartos arba priekabiavimo darbe gali prisidėti keletas veiksnių; jie yra susiję su darbo organizavimo pobūdžiu ir dažnai vadinami „psichologiniais ir socialiniais rizikos veiksniais“. Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.Nepakankamas bendradarbiavimas tarp bendradarbių'],
		['MM202_4', 'Nepakankama darbuotojų kontrolė organizuojant jų darbą', 'Prie streso, prievartos arba priekabiavimo darbe gali prisidėti keletas veiksnių; jie yra susiję su darbo organizavimo pobūdžiu ir dažnai vadinami „psichologiniais ir socialiniais rizikos veiksniais“. Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.Nepakankama darbuotojų kontrolė organizuojant jų darbą'],
		['MM202_5', 'Darbo saugumas', 'Prie streso, prievartos arba priekabiavimo darbe gali prisidėti keletas veiksnių; jie yra susiję su darbo organizavimo pobūdžiu ir dažnai vadinami „psichologiniais ir socialiniais rizikos veiksniais“. Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.Darbo saugumas'],
		['MM202_6', 'Būtinybė turėti reikalų su problemiškais klientais, pacientais, mokiniais ir pan.', 'Prie streso, prievartos arba priekabiavimo darbe gali prisidėti keletas veiksnių; jie yra susiję su darbo organizavimo pobūdžiu ir dažnai vadinami „psichologiniais ir socialiniais rizikos veiksniais“. Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.Būtinybė turėti reikalų su problemiškais klientais, pacientais, mokiniais ir pan.'],
		['MM202_7', 'Vadovybės ir darbuotojų santykių problemos', 'Prie streso, prievartos arba priekabiavimo darbe gali prisidėti keletas veiksnių; jie yra susiję su darbo organizavimo pobūdžiu ir dažnai vadinami „psichologiniais ir socialiniais rizikos veiksniais“. Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.Vadovybės ir darbuotojų santykių problemos'],
		['MM202_8', 'Ilgai trunkančios arba nereguliarios darbo valandos', 'Prie streso, prievartos arba priekabiavimo darbe gali prisidėti keletas veiksnių; jie yra susiję su darbo organizavimo pobūdžiu ir dažnai vadinami „psichologiniais ir socialiniais rizikos veiksniais“. Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.Ilgai trunkančios arba nereguliarios darbo valandos'],
		['MM202_9', 'Neaiški žmogiškųjų išteklių politika', 'Prie streso, prievartos arba priekabiavimo darbe gali prisidėti keletas veiksnių; jie yra susiję su darbo organizavimo pobūdžiu ir dažnai vadinami „psichologiniais ir socialiniais rizikos veiksniais“. Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.Neaiški žmogiškųjų išteklių politika'],
		['MM202_10', 'Diskriminacija (pvz., dėl lyties, amžiaus arba tautinės kilmės)', 'Prie streso, prievartos arba priekabiavimo darbe gali prisidėti keletas veiksnių; jie yra susiję su darbo organizavimo pobūdžiu ir dažnai vadinami „psichologiniais ir socialiniais rizikos veiksniais“. Prašome pasakyti, ar kurie nors iš šių psichosocialinių rizikos veiksnių kelia susirūpinimą Jūsų įmonėje.Diskriminacija (pvz., dėl lyties, amžiaus arba tautinės kilmės)'],
		['MM250', 'Ar Jūsų įmonė turi nustatytą tvarką, kaip spręsti su darbu susijusio streso klausimus?', 'Ar Jūsų įmonė turi nustatytą tvarką, kaip spręsti su darbu susijusio streso klausimus?'],
		['MM251', 'Ar yra nustatyta tvarka, kaip spręsti klausimus, susijusius su darbuotojų persekiojimu arba priekabiavimu?', 'Ar yra nustatyta tvarka, kaip spręsti klausimus, susijusius su darbuotojų persekiojimu arba priekabiavimu?'],
		['MM252', 'Ar Jūsų įmonė turi procedūras, nurodančias kaip spręsti su darbu susijusios prievartos klausimus?', 'Ar Jūsų įmonė turi procedūras, nurodančias kaip spręsti su darbu susijusios prievartos klausimus?'],
		['MM253_1', 'Darbo organizavimo būdo pokyčiai', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?Darbo organizavimo būdo pokyčiai'],
		['MM253_2', 'Darbo vietos pertvarkymas', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?Darbo vietos pertvarkymas'],
		['MM253_3', 'Konfidencialus darbuotojų konsultavimas', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?Konfidencialus darbuotojų konsultavimas'],
		['MM253_4', 'Konfliktų sprendimo tvarkos nustatymas', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?Konfliktų sprendimo tvarkos nustatymas'],
		['MM253_5', 'Darbo laiko tvarkos pokyčiai', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?Darbo laiko tvarkos pokyčiai'],
		['MM253_6', 'Apmokymų užtikrinimas', 'Ar per paskutinius 3 metus Jūsų įmonėje buvo imtasi kurių nors iš šių priemonių mažinant psichologinius ir socialinius rizikos veiksnius?Apmokymų užtikrinimas'],
		['MM256', 'Ar Jūsų įmonė imasi kokių nors veiksmų, jei pavieniai darbuotojai dirba pernelyg ilgai arba nereguliariai?', 'Ar Jūsų įmonė imasi kokių nors veiksmų, jei pavieniai darbuotojai dirba pernelyg ilgai arba nereguliariai?'],
		['MM259', 'Ar informuojate darbuotojus apie psichologinius ir socialinius rizikos veiksnius ir jų poveikį sveikatai ir darbų saugai?', 'Ar informuojate darbuotojus apie psichologinius ir socialinius rizikos veiksnius ir jų poveikį sveikatai ir darbų saugai?'],
		['MM260', 'Ar jie yra informuoti, į ką turėtų kreiptis, jei iškiltų su darbu susijusios psichologinės ir socialinės problemos?', 'Ar jie yra informuoti, į ką turėtų kreiptis, jei iškiltų su darbu susijusios psichologinės ir socialinės problemos?'],
		['MM171_1', 'Teisinių prievolių įvykdymas', 'Kiek Jūsų įmonėje sveikatos ir darbų saugos užtikrinimą įtakoja tokios priežastys? Apie kiekvieną iš jų pasakykite prašau, ar tai yra svarbi priežastis, nesvarbi priežastis, o gal tai iš viso nėra jokia priežastis?Teisinių prievolių įvykdymas'],
		['MM171_2', 'Darbuotojų arba jų atstovų prašymai', 'Kiek Jūsų įmonėje sveikatos ir darbų saugos užtikrinimą įtakoja tokios priežastys? Apie kiekvieną iš jų pasakykite prašau, ar tai yra svarbi priežastis, nesvarbi priežastis, o gal tai iš viso nėra jokia priežastis?Darbuotojų arba jų atstovų prašymai'],
		['MM171_3', 'Darbuotojų išlaikymas ir nebuvimo darbe valdymas', 'Kiek Jūsų įmonėje sveikatos ir darbų saugos užtikrinimą įtakoja tokios priežastys? Apie kiekvieną iš jų pasakykite prašau, ar tai yra svarbi priežastis, nesvarbi priežastis, o gal tai iš viso nėra jokia priežastis?Darbuotojų išlaikymas ir nebuvimo darbe valdymas'],
		['MM171_4', 'Ekonominės arba su darbo atlikimu susijusios priežastys', 'Kiek Jūsų įmonėje sveikatos ir darbų saugos užtikrinimą įtakoja tokios priežastys? Apie kiekvieną iš jų pasakykite prašau, ar tai yra svarbi priežastis, nesvarbi priežastis, o gal tai iš viso nėra jokia priežastis?Ekonominės arba su darbo atlikimu susijusios priežastys'],
		['MM171_5', 'Klientų reikalavimai arba susirūpinimas organizacijos reputacija', 'Kiek Jūsų įmonėje sveikatos ir darbų saugos užtikrinimą įtakoja tokios priežastys? Apie kiekvieną iš jų pasakykite prašau, ar tai yra svarbi priežastis, nesvarbi priežastis, o gal tai iš viso nėra jokia priežastis?Klientų reikalavimai arba susirūpinimas organizacijos reputacija'],
		['MM171_6', 'Spaudimas iš Darbo inspekcijos', 'Kiek Jūsų įmonėje sveikatos ir darbų saugos užtikrinimą įtakoja tokios priežastys? Apie kiekvieną iš jų pasakykite prašau, ar tai yra svarbi priežastis, nesvarbi priežastis, o gal tai iš viso nėra jokia priežastis?Spaudimas iš Darbo inspekcijos'],
		['MM172_1', 'Trūksta išteklių - pvz., laiko, darbuotojų arba pinigų', 'Su kokiomis problemomis susiduriate įmonėje, kai sprendžiate sveikatos ir darbų saugos klausimus? Apie kiekvieną iš jų pasakykite prašau, ar tai yra didelė problema, nedidelė problema, o gal tai iš viso nėra jokia problema?Trūksta išteklių - pvz., laiko, darbuotojų arba pinigų'],
		['MM172_2', 'Trūksta supratingumo', 'Su kokiomis problemomis susiduriate įmonėje, kai sprendžiate sveikatos ir darbų saugos klausimus? Apie kiekvieną iš jų pasakykite prašau, ar tai yra didelė problema, nedidelė problema, o gal tai iš viso nėra jokia problema?Trūksta supratingumo'],
		['MM172_3', 'Trūksta patirties ir žinių', 'Su kokiomis problemomis susiduriate įmonėje, kai sprendžiate sveikatos ir darbų saugos klausimus? Apie kiekvieną iš jų pasakykite prašau, ar tai yra didelė problema, nedidelė problema, o gal tai iš viso nėra jokia problema?Trūksta patirties ir žinių'],
		['MM172_4', 'Trūksta techninės paramos arba konsultacijų', 'Su kokiomis problemomis susiduriate įmonėje, kai sprendžiate sveikatos ir darbų saugos klausimus? Apie kiekvieną iš jų pasakykite prašau, ar tai yra didelė problema, nedidelė problema, o gal tai iš viso nėra jokia problema?Trūksta techninės paramos arba konsultacijų'],
		['MM172_5', 'Nepalanki įmonės vidaus kultūra', 'Su kokiomis problemomis susiduriate įmonėje, kai sprendžiate sveikatos ir darbų saugos klausimus? Apie kiekvieną iš jų pasakykite prašau, ar tai yra didelė problema, nedidelė problema, o gal tai iš viso nėra jokia problema?Nepalanki įmonės vidaus kultūra'],
		['MM172_6', 'Pats klausimo jautrumas', 'Su kokiomis problemomis susiduriate įmonėje, kai sprendžiate sveikatos ir darbų saugos klausimus? Apie kiekvieną iš jų pasakykite prašau, ar tai yra didelė problema, nedidelė problema, o gal tai iš viso nėra jokia problema?Pats klausimo jautrumas'],
		['MM300', 'Palyginus su kitais darbų saugos ir sveikatos klausimais, ar psichologinius ir socialinius rizikos veiksnius suvaldyti yra sunkiau, lengviau, o gal nėra jokio skirtumo?', 'Palyginus su kitais darbų saugos ir sveikatos klausimais, ar psichologinius ir socialinius rizikos veiksnius suvaldyti yra sunkiau, lengviau, o gal nėra jokio skirtumo?'],
		['MM302', 'Ar naudojotės informacija arba parama iš išorės šaltinių, apie tai kaip spręsti klausimus, susijusius su psichologiniais ir socialiniais rizikos veiksniais darbe?', 'Ar naudojotės informacija arba parama iš išorės šaltinių, apie tai kaip spręsti klausimus, susijusius su psichologiniais ir socialiniais rizikos veiksniais darbe?'],
		['MM303a', 'Ar Jums norėtumėte papildomos informacijos arba paramos šiais klausimais?', 'Ar Jums norėtumėte papildomos informacijos arba paramos šiais klausimais?<br><br>Siekiant išsiaiškinti, kaip sprendžiamos su psichosocialine rizika darbe susijusios problemos, buvo apklaustos įmonės, kurios pranešė pasitelkiančios išorės šaltinių teikiamą informaciją arba pagalbą.'],
		['MM350', 'Ar įmonėje turite Darbo tarybą?', 'Ar įmonėje turite Darbo tarybą?'],
		['MM351', 'Ar Jūsų įmonėje yra darbuotojų profesinės sąjungos atstovas?', 'Ar Jūsų įmonėje yra darbuotojų profesinės sąjungos atstovas?'],
		['MM355all', 'Ar Jūsų įmonė turi darbuotojų atstovą darbų saugos ir sveikatos klausimams?', 'Ar Jūsų įmonė turi darbuotojų atstovą darbų saugos ir sveikatos klausimams?<br><br>NL: Ar šioje įmonėje yra atstovas, atsakingas už darbuotojų saugą ir sveikatą?'],
		['MM358', 'Ar Jūsų įmonėje yra Darbuotojų saugos ir sveikatos komitetas?', 'Ar Jūsų įmonėje yra Darbuotojų saugos ir sveikatos komitetas?']
	];
