//Auto Generated file
var subset_
	 = [
	
		['sec3', 'Darbības nozare'],
		['size_4', 'Uzņēmumu lielums']
	];
var subset_subsetValue
	 = [
	
		['sec3', 'All', 'Visi'],
		['sec3', '1--Producing-Industries', 'Ražošanas nozare'],
		['sec3', '2--Private-Services', 'Privāti pakalpojumi'],
		['sec3', '3--Public-Services', 'Sabiedriski pakalpojumi'],
		['size_4', 'All', 'Visi'],
		['size_4', '1--10-to-19-employees', '10–19 darbinieki'],
		['size_4', '2--20-to-49-employees', '20–49 darbinieki'],
		['size_4', '3--50-to-249-employees', '50–249 darbinieki'],
		['size_4', '4--250-employees-or-more', '250 darbinieki vai vairāk ']
	];
var topic_
	 = [
	
		['', 'Visi (70)'],
		['DDVA pārvaldība', 'DDVA pārvaldība (29)'],
		['Darbinieku līdzdalība', 'Darbinieku līdzdalība (4)'],
		['Psihosociālie riski un to pārvaldība', 'Psihosociālie riski un to pārvaldība (22)'],
		['Virzītājfaktori un šķēršļi', 'Virzītājfaktori un šķēršļi (15)']
	];
var topic_question
	 = [
	
		['DDVA pārvaldība', 'MM150_1', 'Vai tiek izmantoti veselības un darba drošības nodrošināšanas pakalpojumi?: Ārsts, kas ir specializējies arodveselības jomā (arodārsts)'],
		['DDVA pārvaldība', 'MM150_2', 'Vai tiek izmantoti veselības un darba drošības nodrošināšanas pakalpojumi?: Darba drošības speciālists'],
		['DDVA pārvaldība', 'MM150_3', 'Vai tiek izmantoti veselības un darba drošības nodrošināšanas pakalpojumi?: Psihologs'],
		['DDVA pārvaldība', 'MM150_4', 'Vai tiek izmantoti veselības un darba drošības nodrošināšanas pakalpojumi?: Ergonomikas eksperts, kurš nodarbojas ar darbavietu iekārtošanu'],
		['DDVA pārvaldība', 'MM150_5', 'Vai tiek izmantoti veselības un darba drošības nodrošināšanas pakalpojumi?: Vispārējas konsultācijas darba drošības un veselības aizsardzības jomā'],
		['DDVA pārvaldība', 'MM152', 'Vai jūsu uzņēmuma vienībā regulāri tiek analizēti darba kavējuma iemesli slimības dēļ?'],
		['DDVA pārvaldība', 'MM153', 'Vai jūs veicat pasākumus, lai veicinātu darbinieku atgriešanos darbā pēc ilgstoša darba kavējuma slimības dēļ?'],
		['DDVA pārvaldība', 'MM154', 'Vai tiek veiktas regulāras medicīniskās pārbaudes, lai apzinātu darbinieku veselības stāvokli?'],
		['DDVA pārvaldība', 'MM155', 'Vai jūsu uzņēmuma vienībā ir dokumentēta politika, pārvaldības sistēma vai rīcības plāns attiecībā uz darba drošību un veselības aizsardzību?'],
		['DDVA pārvaldība', 'MM158', 'Vai darba drošības un veselības aizsardzības jautājumi Jūsu uzņēmuma vienības augstākās vadības sanāksmēs tiek apskatīti regulāri, laiku pa laikam vai praktiski nekad?'],
		['DDVA pārvaldība', 'MM159', 'Kopumā, kā jūs vērtējat vidējā līmeņa vadītāju un vadības pārstāvju iesaistības pakāpi ar darba drošību un veselības aizsardzību saistītu jautājumu risināšanā? Vai tā ir ļoti augsta, diezgan augsta, diezgan zema vai ļoti zema?'],
		['DDVA pārvaldība', 'MM161', 'Vai jūsu uzņēmuma vienībā regulāri risku novērtējuma vai līdzīgu pasākumu ietvaros tiek pārbaudīta darbavietu atbilstība drošībai un veselībai?'],
		['DDVA pārvaldība', 'MM170', 'Vai Valsts darba inspekcija pēdējo 3 gadu laikā ir veikusi Jūsu uzņēmuma vienībā darba drošības un veselības aizsardzības pārbaudi?'],
		['DDVA pārvaldība', 'MM173_1', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Oficiālās darba drošības un veselības aizsardzības iestādes'],
		['DDVA pārvaldība', 'MM173_2', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Eiropas Darba drošības un veselības aizsardzības aģentūra'],
		['DDVA pārvaldība', 'MM173_3', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Uzņēmuma iekšējie darba drošības un veselības aizsardzības dienesti'],
		['DDVA pārvaldība', 'MM173_4', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Valsts darba inspekcija'],
		['DDVA pārvaldība', 'MM173_5', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Darba devēju organizācijas'],
		['DDVA pārvaldība', 'MM173_6', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Arodbiedrības'],
		['DDVA pārvaldība', 'MM173_7', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Nolīgti darba drošības un veselības aizsardzības speciālisti'],
		['DDVA pārvaldība', 'MM173_8', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Apdrošināšanas pakalpojumu sniedzēji'],
		['DDVA pārvaldība', 'MM175', 'Vai jūs zināt kaut ko par Eiropas darba drošības un veselības aizsardzības nedēļu?'],
		['DDVA pārvaldība', 'MM200_1', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?: Bīstamas vielas (piemēram, putekĜi, ėīmiskas, bioloăiskas vai radioaktīvas vielas)'],
		['DDVA pārvaldība', 'MM200_2', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?: Nelaimes gadījumi'],
		['DDVA pārvaldība', 'MM200_3', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?: Troksnis un vibrācijas'],
		['DDVA pārvaldība', 'MM200_4', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?: Balsta un kustību aparāta traucējumi, piemēram, muguras sāpes, sāpes sprandā, rokās vai kājās'],
		['DDVA pārvaldība', 'MM200_5', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?: Stress, kas saistīts ar darba pienākumu izpildi'],
		['DDVA pārvaldība', 'MM200_6', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?: Vardarbība vai vardarbības draudi'],
		['DDVA pārvaldība', 'MM200_7', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?: Iebiedēšana vai psiholoģiskais terors, piemēram, apvainošana, pazemošana vai uzbrukums no kolēģu vai vadības puses'],
		['Psihosociālie riski un to pārvaldība', 'MM202_1', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Laika trūkums'],
		['Psihosociālie riski un to pārvaldība', 'MM202_2', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Slikta komunikācija starp vadību un darbiniekiem'],
		['Psihosociālie riski un to pārvaldība', 'MM202_3', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Vāja sadarbība kolēģu starpā'],
		['Psihosociālie riski un to pārvaldība', 'MM202_4', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Darbinieku nespēja ietekmēt sava darba organizāciju'],
		['Psihosociālie riski un to pārvaldība', 'MM202_5', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Darbavietas nedrošība/nepastāvība'],
		['Psihosociālie riski un to pārvaldība', 'MM202_6', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Darbs ar sarežģītiem klientiem, pacientiem, skolniekiem utt.'],
		['Psihosociālie riski un to pārvaldība', 'MM202_7', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Problemas vadības un darbinieku attiecības'],
		['Psihosociālie riski un to pārvaldība', 'MM202_8', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Garas vai neregulāras darba stundas'],
		['Psihosociālie riski un to pārvaldība', 'MM202_9', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Neskaidra cilvēkresursu politika'],
		['Psihosociālie riski un to pārvaldība', 'MM202_10', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Diskriminācija (piemēram, dzimuma, vecuma vai etniskā diskriminācija)'],
		['Psihosociālie riski un to pārvaldība', 'MM250', 'Vai jūsu pārstāvētajā uzņēmuma vienībā ir noteikta kārtība, kā mazināt stresu, kas saistīts ar darba pienākumu izpildi?'],
		['Psihosociālie riski un to pārvaldība', 'MM251', 'Vai jūsu pārstāvētajā uzņēmuma vienībā ir noteikta kārtība, kā risināt iebiedēšanas vai psiholoģiskā terora problēmas?'],
		['Psihosociālie riski un to pārvaldība', 'MM252', 'Vai jūsu pārstāvētajā uzņēmuma vienībā ir noteikta kārtība, kā risināt problēmas, kas saistītas ar vardarbību darba vietā?'],
		['Psihosociālie riski un to pārvaldība', 'MM253_1', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?: Izmaiņas darba organizācijā'],
		['Psihosociālie riski un to pārvaldība', 'MM253_2', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?: Darba vietas pārplānošana'],
		['Psihosociālie riski un to pārvaldība', 'MM253_3', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?: Konfidenciālas darbinieku konsultācijas'],
		['Psihosociālie riski un to pārvaldība', 'MM253_4', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?: Konfliktu risināšanas kārtības plānošana'],
		['Psihosociālie riski un to pārvaldība', 'MM253_5', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?: Izmaiņas darba laika sistēmā'],
		['Psihosociālie riski un to pārvaldība', 'MM253_6', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?: Apmācību nodrošināšana'],
		['Psihosociālie riski un to pārvaldība', 'MM256', 'Vai jūsu uzņēmuma vienībā tiek veikti kaut kādi pasākumi, ja atsevišķi darbinieki strādā pārāk garas vai neregulāras darba stundas?'],
		['Psihosociālie riski un to pārvaldība', 'MM259', 'Vai jūs informējat darbiniekus par psihosociālajiem riskiem un to ietekmi uz drošību un veselību?'],
		['Psihosociālie riski un to pārvaldība', 'MM260', 'Vai darbinieki ir informēti, kur vērsties ar darbu saistīto psihosociālo problēmu gadījumā ?'],
		['Virzītājfaktori un šķēršļi', 'MM171_1', 'Kādi ir iemesli risināt darba aizsardzības jautājumus uzņēmumā?: Likumisko prasību izpilde'],
		['Virzītājfaktori un šķēršļi', 'MM171_2', 'Kādi ir iemesli risināt darba aizsardzības jautājumus uzņēmumā?: Darbinieku vai viņu pārstāvju lūgums'],
		['Virzītājfaktori un šķēršļi', 'MM171_3', 'Kādi ir iemesli risināt darba aizsardzības jautājumus uzņēmumā?: Darbinieku saglabāšanas un darba kavējumu pārvaldība'],
		['Virzītājfaktori un šķēršļi', 'MM171_4', 'Kādi ir iemesli risināt darba aizsardzības jautājumus uzņēmumā?: Ekonomiski vai ar darba izpildi saistīti iemesli'],
		['Virzītājfaktori un šķēršļi', 'MM171_5', 'Kādi ir iemesli risināt darba aizsardzības jautājumus uzņēmumā?: Klientu prasības vai bažas par uzņēmuma reputāciju'],
		['Virzītājfaktori un šķēršļi', 'MM171_6', 'Kādi ir iemesli risināt darba aizsardzības jautājumus uzņēmumā?: Spiediens no Valsts darba inspekcijas puses'],
		['Virzītājfaktori un šķēršļi', 'MM172_1', 'Kādas ir galvenās grūtības, risinot darba aizsardzības jautājumus?: Līdzekļu tādu kā, piemēram, laiks, darbaspēks vai nauda, trūkums'],
		['Virzītājfaktori un šķēršļi', 'MM172_2', 'Kādas ir galvenās grūtības, risinot darba aizsardzības jautājumus?: Informētības trūkums'],
		['Virzītājfaktori un šķēršļi', 'MM172_3', 'Kādas ir galvenās grūtības, risinot darba aizsardzības jautājumus?: Speciālu zināšanu/kompetences trūkums'],
		['Virzītājfaktori un šķēršļi', 'MM172_4', 'Kādas ir galvenās grūtības, risinot darba aizsardzības jautājumus?: Tehniskā nodrošinājuma vai instrukciju trūkums'],
		['Virzītājfaktori un šķēršļi', 'MM172_5', 'Kādas ir galvenās grūtības, risinot darba aizsardzības jautājumus?: Uzņēmuma vienības/uzņēmuma kultūra'],
		['Virzītājfaktori un šķēršļi', 'MM172_6', 'Kādas ir galvenās grūtības, risinot darba aizsardzības jautājumus?: Tas ir jūtīgs jautājums'],
		['Virzītājfaktori un šķēršļi', 'MM300', 'Salīdzinot ar citiem ar darba drošību un veselības aizsardzību saistītiem jautājumiem: Vai novērst psihosociālos riskus ir grūtāk, vieglāk vai nav atšķirības'],
		['Virzītājfaktori un šķēršļi', 'MM302', 'Vai jūsu esat izmantojuši ārēju avotu informāciju vai atbalstu psihosociālo risku novēršanai?'],
		['Virzītājfaktori un šķēršļi', 'MM303a', 'Vai jums būtu nepieciešama papildus informācija vai atbalsts šajā jautājumā?'],
		['Darbinieku līdzdalība', 'MM350', 'Vai jūsu uzņēmuma vienībā ir darbinieku pilnvarotais pārstāvis vai Darba padome?'],
		['Darbinieku līdzdalība', 'MM351', 'Un vai jūsu uzņēmuma vienībā ir arodbiedrība?'],
		['Darbinieku līdzdalība', 'MM355all', 'Vai jūsu uzņēmuma vienībā ir nodarbināto uzticības persona?'],
		['Darbinieku līdzdalība', 'MM358', 'Vai jūsu uzņēmuma vienībā ir nodarbināto uzticības personu komiteja?']
	];
var question_
	 = [
	
		['MM150_1', 'Vai tiek izmantoti veselības un darba drošības nodrošināšanas pakalpojumi?: Ārsts, kas ir specializējies arodveselības jomā (arodārsts)'],
		['MM150_2', 'Vai tiek izmantoti veselības un darba drošības nodrošināšanas pakalpojumi?: Darba drošības speciālists'],
		['MM150_3', 'Vai tiek izmantoti veselības un darba drošības nodrošināšanas pakalpojumi?: Psihologs'],
		['MM150_4', 'Vai tiek izmantoti veselības un darba drošības nodrošināšanas pakalpojumi?: Ergonomikas eksperts, kurš nodarbojas ar darbavietu iekārtošanu'],
		['MM150_5', 'Vai tiek izmantoti veselības un darba drošības nodrošināšanas pakalpojumi?: Vispārējas konsultācijas darba drošības un veselības aizsardzības jomā'],
		['MM152', 'Vai jūsu uzņēmuma vienībā regulāri tiek analizēti darba kavējuma iemesli slimības dēļ?'],
		['MM153', 'Vai jūs veicat pasākumus, lai veicinātu darbinieku atgriešanos darbā pēc ilgstoša darba kavējuma slimības dēļ?'],
		['MM154', 'Vai tiek veiktas regulāras medicīniskās pārbaudes, lai apzinātu darbinieku veselības stāvokli?'],
		['MM155', 'Vai jūsu uzņēmuma vienībā ir dokumentēta politika, pārvaldības sistēma vai rīcības plāns attiecībā uz darba drošību un veselības aizsardzību?'],
		['MM158', 'Vai darba drošības un veselības aizsardzības jautājumi Jūsu uzņēmuma vienības augstākās vadības sanāksmēs tiek apskatīti regulāri, laiku pa laikam vai praktiski nekad?'],
		['MM159', 'Kopumā, kā jūs vērtējat vidējā līmeņa vadītāju un vadības pārstāvju iesaistības pakāpi ar darba drošību un veselības aizsardzību saistītu jautājumu risināšanā? Vai tā ir ļoti augsta, diezgan augsta, diezgan zema vai ļoti zema?'],
		['MM161', 'Vai jūsu uzņēmuma vienībā regulāri risku novērtējuma vai līdzīgu pasākumu ietvaros tiek pārbaudīta darbavietu atbilstība drošībai un veselībai?'],
		['MM170', 'Vai Valsts darba inspekcija pēdējo 3 gadu laikā ir veikusi Jūsu uzņēmuma vienībā darba drošības un veselības aizsardzības pārbaudi?'],
		['MM173_1', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Oficiālās darba drošības un veselības aizsardzības iestādes'],
		['MM173_2', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Eiropas Darba drošības un veselības aizsardzības aģentūra'],
		['MM173_3', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Uzņēmuma iekšējie darba drošības un veselības aizsardzības dienesti'],
		['MM173_4', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Valsts darba inspekcija'],
		['MM173_5', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Darba devēju organizācijas'],
		['MM173_6', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Arodbiedrības'],
		['MM173_7', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Nolīgti darba drošības un veselības aizsardzības speciālisti'],
		['MM173_8', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?: Apdrošināšanas pakalpojumu sniedzēji'],
		['MM175', 'Vai jūs zināt kaut ko par Eiropas darba drošības un veselības aizsardzības nedēļu?'],
		['MM200_1', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?: Bīstamas vielas (piemēram, putekĜi, ėīmiskas, bioloăiskas vai radioaktīvas vielas)'],
		['MM200_2', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?: Nelaimes gadījumi'],
		['MM200_3', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?: Troksnis un vibrācijas'],
		['MM200_4', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?: Balsta un kustību aparāta traucējumi, piemēram, muguras sāpes, sāpes sprandā, rokās vai kājās'],
		['MM200_5', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?: Stress, kas saistīts ar darba pienākumu izpildi'],
		['MM200_6', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?: Vardarbība vai vardarbības draudi'],
		['MM200_7', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?: Iebiedēšana vai psiholoģiskais terors, piemēram, apvainošana, pazemošana vai uzbrukums no kolēģu vai vadības puses'],
		['MM202_1', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Laika trūkums'],
		['MM202_2', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Slikta komunikācija starp vadību un darbiniekiem'],
		['MM202_3', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Vāja sadarbība kolēģu starpā'],
		['MM202_4', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Darbinieku nespēja ietekmēt sava darba organizāciju'],
		['MM202_5', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Darbavietas nedrošība/nepastāvība'],
		['MM202_6', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Darbs ar sarežģītiem klientiem, pacientiem, skolniekiem utt.'],
		['MM202_7', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Problemas vadības un darbinieku attiecības'],
		['MM202_8', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Garas vai neregulāras darba stundas'],
		['MM202_9', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Neskaidra cilvēkresursu politika'],
		['MM202_10', 'Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?: Diskriminācija (piemēram, dzimuma, vecuma vai etniskā diskriminācija)'],
		['MM250', 'Vai jūsu pārstāvētajā uzņēmuma vienībā ir noteikta kārtība, kā mazināt stresu, kas saistīts ar darba pienākumu izpildi?'],
		['MM251', 'Vai jūsu pārstāvētajā uzņēmuma vienībā ir noteikta kārtība, kā risināt iebiedēšanas vai psiholoģiskā terora problēmas?'],
		['MM252', 'Vai jūsu pārstāvētajā uzņēmuma vienībā ir noteikta kārtība, kā risināt problēmas, kas saistītas ar vardarbību darba vietā?'],
		['MM253_1', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?: Izmaiņas darba organizācijā'],
		['MM253_2', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?: Darba vietas pārplānošana'],
		['MM253_3', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?: Konfidenciālas darbinieku konsultācijas'],
		['MM253_4', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?: Konfliktu risināšanas kārtības plānošana'],
		['MM253_5', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?: Izmaiņas darba laika sistēmā'],
		['MM253_6', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?: Apmācību nodrošināšana'],
		['MM256', 'Vai jūsu uzņēmuma vienībā tiek veikti kaut kādi pasākumi, ja atsevišķi darbinieki strādā pārāk garas vai neregulāras darba stundas?'],
		['MM259', 'Vai jūs informējat darbiniekus par psihosociālajiem riskiem un to ietekmi uz drošību un veselību?'],
		['MM260', 'Vai darbinieki ir informēti, kur vērsties ar darbu saistīto psihosociālo problēmu gadījumā ?'],
		['MM171_1', 'Kādi ir iemesli risināt darba aizsardzības jautājumus uzņēmumā?: Likumisko prasību izpilde'],
		['MM171_2', 'Kādi ir iemesli risināt darba aizsardzības jautājumus uzņēmumā?: Darbinieku vai viņu pārstāvju lūgums'],
		['MM171_3', 'Kādi ir iemesli risināt darba aizsardzības jautājumus uzņēmumā?: Darbinieku saglabāšanas un darba kavējumu pārvaldība'],
		['MM171_4', 'Kādi ir iemesli risināt darba aizsardzības jautājumus uzņēmumā?: Ekonomiski vai ar darba izpildi saistīti iemesli'],
		['MM171_5', 'Kādi ir iemesli risināt darba aizsardzības jautājumus uzņēmumā?: Klientu prasības vai bažas par uzņēmuma reputāciju'],
		['MM171_6', 'Kādi ir iemesli risināt darba aizsardzības jautājumus uzņēmumā?: Spiediens no Valsts darba inspekcijas puses'],
		['MM172_1', 'Kādas ir galvenās grūtības, risinot darba aizsardzības jautājumus?: Līdzekļu tādu kā, piemēram, laiks, darbaspēks vai nauda, trūkums'],
		['MM172_2', 'Kādas ir galvenās grūtības, risinot darba aizsardzības jautājumus?: Informētības trūkums'],
		['MM172_3', 'Kādas ir galvenās grūtības, risinot darba aizsardzības jautājumus?: Speciālu zināšanu/kompetences trūkums'],
		['MM172_4', 'Kādas ir galvenās grūtības, risinot darba aizsardzības jautājumus?: Tehniskā nodrošinājuma vai instrukciju trūkums'],
		['MM172_5', 'Kādas ir galvenās grūtības, risinot darba aizsardzības jautājumus?: Uzņēmuma vienības/uzņēmuma kultūra'],
		['MM172_6', 'Kādas ir galvenās grūtības, risinot darba aizsardzības jautājumus?: Tas ir jūtīgs jautājums'],
		['MM300', 'Salīdzinot ar citiem ar darba drošību un veselības aizsardzību saistītiem jautājumiem: Vai novērst psihosociālos riskus ir grūtāk, vieglāk vai nav atšķirības'],
		['MM302', 'Vai jūsu esat izmantojuši ārēju avotu informāciju vai atbalstu psihosociālo risku novēršanai?'],
		['MM303a', 'Vai jums būtu nepieciešama papildus informācija vai atbalsts šajā jautājumā?'],
		['MM350', 'Vai jūsu uzņēmuma vienībā ir darbinieku pilnvarotais pārstāvis vai Darba padome?'],
		['MM351', 'Un vai jūsu uzņēmuma vienībā ir arodbiedrība?'],
		['MM355all', 'Vai jūsu uzņēmuma vienībā ir nodarbināto uzticības persona?'],
		['MM358', 'Vai jūsu uzņēmuma vienībā ir nodarbināto uzticības personu komiteja?']
	];
var question_answer
	 = [
	
		['MM150_1', '1--Yes', 'Jā'],
		['MM150_1', '2--No', 'Nē'],
		['MM150_1', '3--DK--NA', '3.Nav atbildes'],
		['MM150_2', '1--Yes', 'Jā'],
		['MM150_2', '2--No', 'Nē'],
		['MM150_2', '3--DK--NA', '3.Nav atbildes'],
		['MM150_3', '1--Yes', 'Jā'],
		['MM150_3', '2--No', 'Nē'],
		['MM150_3', '3--DK--NA', '3.Nav atbildes'],
		['MM150_4', '1--Yes', 'Jā'],
		['MM150_4', '2--No', 'Nē'],
		['MM150_4', '3--DK--NA', '3.Nav atbildes'],
		['MM150_5', '1--Yes', 'Jā'],
		['MM150_5', '2--No', 'Nē'],
		['MM150_5', '3--DK--NA', '3.Nav atbildes'],
		['MM152', '1--Yes', 'Jā'],
		['MM152', '2--No', 'Nē'],
		['MM152', '3--DK--NA', '3.Nav atbildes'],
		['MM153', '1--Yes', 'Jā'],
		['MM153', '2--No', 'Nē'],
		['MM153', '3--DK--NA', '3.Nav atbildes'],
		['MM154', '1--Yes', 'Jā'],
		['MM154', '2--No', 'Nē'],
		['MM154', '3--DK--NA', '3.Nav atbildes'],
		['MM155', '1--Yes', 'Jā'],
		['MM155', '2--No', 'Nē'],
		['MM155', '3--DK--NA', '3.Nav atbildes'],
		['MM158', '1--Regularly', 'Regulāri'],
		['MM158', '2--Occasionally', 'Laiku pa laikam'],
		['MM158', '3--Practically-never', 'Praktiski nekad'],
		['MM158', '4--DK--NA', 'Nav atbildes'],
		['MM159', '1--Very-high', 'Ļoti augsta'],
		['MM159', '2--Quite-high', 'Diezgan augsta'],
		['MM159', '3--Quite-low', 'Diezgan zema'],
		['MM159', '4--Very-low', 'Ļoti zema'],
		['MM159', '5--DK--NA', 'Nav atbildes'],
		['MM161', '1--Yes', 'Jā'],
		['MM161', '2--No', 'Nē'],
		['MM161', '3--DK--NA', '3.Nav atbildes'],
		['MM170', '1--Yes', 'Jā'],
		['MM170', '2--No', 'Nē'],
		['MM170', '3--DK--NA', '3.Nav atbildes'],
		['MM171_1', '1--Major', 'Ļoti nozīmīgs'],
		['MM171_1', '2--Minor', 'Maznozīmīgs'],
		['MM171_1', '3--No', 'Pavisam nesvarīgs'],
		['MM171_1', '4--DK--NA', 'Nav atbildes'],
		['MM171_2', '1--Major', 'Ļoti nozīmīgs'],
		['MM171_2', '2--Minor', 'Maznozīmīgs'],
		['MM171_2', '3--No', 'Pavisam nesvarīgs'],
		['MM171_2', '4--DK--NA', 'Nav atbildes'],
		['MM171_3', '1--Major', 'Ļoti nozīmīgs'],
		['MM171_3', '2--Minor', 'Maznozīmīgs'],
		['MM171_3', '3--No', 'Pavisam nesvarīgs'],
		['MM171_3', '4--DK--NA', 'Nav atbildes'],
		['MM171_4', '1--Major', 'Ļoti nozīmīgs'],
		['MM171_4', '2--Minor', 'Maznozīmīgs'],
		['MM171_4', '3--No', 'Pavisam nesvarīgs'],
		['MM171_4', '4--DK--NA', 'Nav atbildes'],
		['MM171_5', '1--Major', 'Ļoti nozīmīgs'],
		['MM171_5', '2--Minor', 'Maznozīmīgs'],
		['MM171_5', '3--No', 'Pavisam nesvarīgs'],
		['MM171_5', '4--DK--NA', 'Nav atbildes'],
		['MM171_6', '1--Major', 'Ļoti nozīmīgs'],
		['MM171_6', '2--Minor', 'Maznozīmīgs'],
		['MM171_6', '3--No', 'Pavisam nesvarīgs'],
		['MM171_6', '4--DK--NA', 'Nav atbildes'],
		['MM172_1', '1--Major', 'Ļoti nozīmīgs'],
		['MM172_1', '2--Minor', 'Maznozīmīgs'],
		['MM172_1', '3--No', 'Pavisam nav šķērslis'],
		['MM172_1', '4--DK--NA', 'Nav atbildes'],
		['MM172_2', '1--Major', 'Ļoti nozīmīgs'],
		['MM172_2', '2--Minor', 'Maznozīmīgs'],
		['MM172_2', '3--No', 'Pavisam nav šķērslis'],
		['MM172_2', '4--DK--NA', 'Nav atbildes'],
		['MM172_3', '1--Major', 'Ļoti nozīmīgs'],
		['MM172_3', '2--Minor', 'Maznozīmīgs'],
		['MM172_3', '3--No', 'Pavisam nav šķērslis'],
		['MM172_3', '4--DK--NA', 'Nav atbildes'],
		['MM172_4', '1--Major', 'Ļoti nozīmīgs'],
		['MM172_4', '2--Minor', 'Maznozīmīgs'],
		['MM172_4', '3--No', 'Pavisam nav šķērslis'],
		['MM172_4', '4--DK--NA', 'Nav atbildes'],
		['MM172_5', '1--Major', 'Ļoti nozīmīgs'],
		['MM172_5', '2--Minor', 'Maznozīmīgs'],
		['MM172_5', '3--No', 'Pavisam nav šķērslis'],
		['MM172_5', '4--DK--NA', 'Nav atbildes'],
		['MM172_6', '1--Major', 'Ļoti nozīmīgs'],
		['MM172_6', '2--Minor', 'Maznozīmīgs'],
		['MM172_6', '3--No', 'Pavisam nav šķērslis'],
		['MM172_6', '4--DK--NA', 'Nav atbildes'],
		['MM173_1', '1--Yes', 'Jā'],
		['MM173_1', '2--No', 'Nē'],
		['MM173_1', '3--DK--NA', '3.Nav atbildes'],
		['MM173_2', '1--Yes', 'Jā'],
		['MM173_2', '2--No', 'Nē'],
		['MM173_2', '3--DK--NA', '3.Nav atbildes'],
		['MM173_3', '1--Yes', 'Jā'],
		['MM173_3', '2--No', 'Nē'],
		['MM173_3', '3--DK--NA', '3.Nav atbildes'],
		['MM173_4', '1--Yes', 'Jā'],
		['MM173_4', '2--No', 'Nē'],
		['MM173_4', '3--DK--NA', '3.Nav atbildes'],
		['MM173_5', '1--Yes', 'Jā'],
		['MM173_5', '2--No', 'Nē'],
		['MM173_5', '3--DK--NA', '3.Nav atbildes'],
		['MM173_6', '1--Yes', 'Jā'],
		['MM173_6', '2--No', 'Nē'],
		['MM173_6', '3--DK--NA', '3.Nav atbildes'],
		['MM173_7', '1--Yes', 'Jā'],
		['MM173_7', '2--No', 'Nē'],
		['MM173_7', '3--DK--NA', '3.Nav atbildes'],
		['MM173_8', '1--Yes', 'Jā'],
		['MM173_8', '2--No', 'Nē'],
		['MM173_8', '3--DK--NA', '3.Nav atbildes'],
		['MM175', '1--Yes', 'Jā'],
		['MM175', '2--No', 'Nē'],
		['MM175', '3--DK--NA', '3.Nav atbildes'],
		['MM200_1', '1--Major-concern', 'Liela uzmanība'],
		['MM200_1', '2--Some-concern', 'Zināma uzmanība'],
		['MM200_1', '3--No-concern', 'Netiek pievērsta uzmanība nemaz'],
		['MM200_1', '4--DK--NA', 'Nav atbildes'],
		['MM200_2', '1--Major-concern', 'Liela uzmanība'],
		['MM200_2', '2--Some-concern', 'Zināma uzmanība'],
		['MM200_2', '3--No-concern', 'Netiek pievērsta uzmanība nemaz'],
		['MM200_2', '4--DK--NA', 'Nav atbildes'],
		['MM200_3', '1--Major-concern', 'Liela uzmanība'],
		['MM200_3', '2--Some-concern', 'Zināma uzmanība'],
		['MM200_3', '3--No-concern', 'Netiek pievērsta uzmanība nemaz'],
		['MM200_3', '4--DK--NA', 'Nav atbildes'],
		['MM200_4', '1--Major-concern', 'Liela uzmanība'],
		['MM200_4', '2--Some-concern', 'Zināma uzmanība'],
		['MM200_4', '3--No-concern', 'Netiek pievērsta uzmanība nemaz'],
		['MM200_4', '4--DK--NA', 'Nav atbildes'],
		['MM200_5', '1--Major-concern', 'Liela uzmanība'],
		['MM200_5', '2--Some-concern', 'Zināma uzmanība'],
		['MM200_5', '3--No-concern', 'Netiek pievērsta uzmanība nemaz'],
		['MM200_5', '4--DK--NA', 'Nav atbildes'],
		['MM200_6', '1--Major-concern', 'Liela uzmanība'],
		['MM200_6', '2--Some-concern', 'Zināma uzmanība'],
		['MM200_6', '3--No-concern', 'Netiek pievērsta uzmanība nemaz'],
		['MM200_6', '4--DK--NA', 'Nav atbildes'],
		['MM200_7', '1--Major-concern', 'Liela uzmanība'],
		['MM200_7', '2--Some-concern', 'Zināma uzmanība'],
		['MM200_7', '3--No-concern', 'Netiek pievērsta uzmanība nemaz'],
		['MM200_7', '4--DK--NA', 'Nav atbildes'],
		['MM202_1', '1--Yes', 'Jā'],
		['MM202_1', '2--No', 'Nē'],
		['MM202_1', '3--DK--NA', '3.Nav atbildes'],
		['MM202_10', '1--Yes', 'Jā'],
		['MM202_10', '2--No', 'Nē'],
		['MM202_10', '3--DK--NA', '3.Nav atbildes'],
		['MM202_2', '1--Yes', 'Jā'],
		['MM202_2', '2--No', 'Nē'],
		['MM202_2', '3--DK--NA', '3.Nav atbildes'],
		['MM202_3', '1--Yes', 'Jā'],
		['MM202_3', '2--No', 'Nē'],
		['MM202_3', '3--DK--NA', '3.Nav atbildes'],
		['MM202_4', '1--Yes', 'Jā'],
		['MM202_4', '2--No', 'Nē'],
		['MM202_4', '3--DK--NA', '3.Nav atbildes'],
		['MM202_5', '1--Yes', 'Jā'],
		['MM202_5', '2--No', 'Nē'],
		['MM202_5', '3--DK--NA', '3.Nav atbildes'],
		['MM202_6', '1--Yes', 'Jā'],
		['MM202_6', '2--No', 'Nē'],
		['MM202_6', '3--DK--NA', '3.Nav atbildes'],
		['MM202_7', '1--Yes', 'Jā'],
		['MM202_7', '2--No', 'Nē'],
		['MM202_7', '3--DK--NA', '3.Nav atbildes'],
		['MM202_8', '1--Yes', 'Jā'],
		['MM202_8', '2--No', 'Nē'],
		['MM202_8', '3--DK--NA', '3.Nav atbildes'],
		['MM202_9', '1--Yes', 'Jā'],
		['MM202_9', '2--No', 'Nē'],
		['MM202_9', '3--DK--NA', '3.Nav atbildes'],
		['MM250', '1--Yes', 'Jā'],
		['MM250', '2--No', 'Nē'],
		['MM250', '3--Work-related-stress-is-not-an-issue-in-our-establishment', 'Ar darba pienākumu izpildi saistīts stress šajā uzņēmuma vienībā nav problēma'],
		['MM250', '4--No-answer', 'Nav atbildes'],
		['MM251', '1--Yes', 'Jā'],
		['MM251', '2--No', 'Nē'],
		['MM251', '3--These-problems-are-not-an-issue-in-our-establishment', 'Šīs problēmas šajā uzņēmuma vienībā nav aktuālas'],
		['MM251', '4--No-answer', 'Nav atbildes'],
		['MM252', '1--Yes', 'Jā'],
		['MM252', '2--No', 'Nē'],
		['MM252', '3--Work-related-violence-is-not-an-issue-in-our-establishment', 'Problēmas, kas saistītas ar vardarbību darba vietā, šajā uzņēmuma vienībā nav aktuālas'],
		['MM252', '4--No-answer', 'Nav atbildes'],
		['MM253_1', '1--Yes', 'Jā'],
		['MM253_1', '2--No', 'Nē'],
		['MM253_1', '3--DK--NA', '3.Nav atbildes'],
		['MM253_2', '1--Yes', 'Jā'],
		['MM253_2', '2--No', 'Nē'],
		['MM253_2', '3--DK--NA', '3.Nav atbildes'],
		['MM253_3', '1--Yes', 'Jā'],
		['MM253_3', '2--No', 'Nē'],
		['MM253_3', '3--DK--NA', '3.Nav atbildes'],
		['MM253_4', '1--Yes', 'Jā'],
		['MM253_4', '2--No', 'Nē'],
		['MM253_4', '3--DK--NA', '3.Nav atbildes'],
		['MM253_5', '1--Yes', 'Jā'],
		['MM253_5', '2--No', 'Nē'],
		['MM253_5', '3--DK--NA', '3.Nav atbildes'],
		['MM253_6', '1--Yes', 'Jā'],
		['MM253_6', '2--No', 'Nē'],
		['MM253_6', '3--DK--NA', '3.Nav atbildes'],
		['MM256', '1--Yes', 'Jā'],
		['MM256', '2--No', 'Nē'],
		['MM256', '3--Long-or-irregular-working-hours-are-not-an-issue-in-our-esta', 'Pārāk garas vai neregulāras darba stundas šajā uzņēmuma vienībā nav aktuālas'],
		['MM256', '4--No-answer', 'Nav atbildes'],
		['MM259', '1--Yes', 'Jā'],
		['MM259', '2--No', 'Nē'],
		['MM259', '3--No-answer', 'Nav atbildes'],
		['MM260', '1--Yes', 'Jā'],
		['MM260', '2--No', 'Nē'],
		['MM260', '3--No-answer', 'Nav atbildes'],
		['MM300', '1--More-difficult', 'Grūtāk'],
		['MM300', '2--Less-difficult', 'Vieglāk'],
		['MM300', '3--No-difference', 'Nav atšķirības'],
		['MM300', '4--No-answer', 'Nav atbildes'],
		['MM302', '1--Yes', 'Jā'],
		['MM302', '2--No', 'Nē'],
		['MM302', '3--No-answer', 'Nav atbildes'],
		['MM303a', '1--Yes', 'Jā'],
		['MM303a', '2--No', 'Nē'],
		['MM303a', '3--No-answer', 'Nav atbildes'],
		['MM350', '1--Yes', 'Jā'],
		['MM350', '2--No', 'Nē'],
		['MM350', '3--No-answer', 'Nav atbildes'],
		['MM351', '1--Yes', 'Jā'],
		['MM351', '2--No', 'Nē'],
		['MM351', '3--No-answer', 'Nav atbildes'],
		['MM355all', '1--Yes', 'Jā'],
		['MM355all', '2--No', 'Nē'],
		['MM355all', '3--No-answer', 'Nav atbildes'],
		['MM358', '1--Yes', 'Jā'],
		['MM358', '2--No', 'Nē'],
		['MM358', '3--No-answer', 'Nav atbildes']
	];
var country_
	 = [
	
		['AT', 'Austrija'],
		['BE', 'Beļģija'],
		['BG', 'Bulgārija'],
		['CH', 'Šveice'],
		['CY', 'Kipra'],
		['CZ', 'Čehijas Republika'],
		['DE', 'Vācija'],
		['DK', 'Dānija'],
		['EE', 'Igaunija'],
		['EL', 'Grieķija'],
		['ES', 'Spānija'],
		['FI', 'Somija'],
		['FR', 'Francija'],
		['HR', 'Horvātija *'],
		['HU', 'Ungārija'],
		['IE', 'Īrija'],
		['IT', 'Itālija'],
		['LT', 'Lietuva'],
		['LU', 'Luksemburga'],
		['LV', 'Latvija'],
		['MT', 'Malta'],
		['NL', 'Nīderlande'],
		['NO', 'Norvēģija'],
		['PL', 'Polija'],
		['PT', 'Portugāle'],
		['RO', 'Rumānija'],
		['SE', 'Zviedrija'],
		['SI', 'Slovēnija'],
		['SK', 'Slovākija'],
		['TR', 'Turcija'],
		['UK', 'Apvienotā Karaliste'],
		['EuropeanUnion', 'Eiropas Savienība *']
	];
var question_meta
	 = [
	
		['MM150_1', 'Ārsts, kas ir specializējies arodveselības jomā (arodārsts)', 'Kādus darba drošības un veselības aizsardzības pakalpojumus jūs izmantojat: vienalga vai iekšējos vai uz līguma pamata no ārpuses?Ārsts, kas ir specializējies arodveselības jomā (arodārsts)'],
		['MM150_2', 'Darba drošības speciālists', 'Kādus darba drošības un veselības aizsardzības pakalpojumus jūs izmantojat: vienalga vai iekšējos vai uz līguma pamata no ārpuses?Darba drošības speciālists'],
		['MM150_3', 'Psihologs', 'Kādus darba drošības un veselības aizsardzības pakalpojumus jūs izmantojat: vienalga vai iekšējos vai uz līguma pamata no ārpuses?Psihologs'],
		['MM150_4', 'Ergonomikas eksperts, kurš nodarbojas ar darbavietu iekārtošanu', 'Kādus darba drošības un veselības aizsardzības pakalpojumus jūs izmantojat: vienalga vai iekšējos vai uz līguma pamata no ārpuses?Ergonomikas eksperts, kurš nodarbojas ar darbavietu iekārtošanu'],
		['MM150_5', 'Vispārējas konsultācijas darba drošības un veselības aizsardzības jomā', 'Kādus darba drošības un veselības aizsardzības pakalpojumus jūs izmantojat: vienalga vai iekšējos vai uz līguma pamata no ārpuses?Vispārējas konsultācijas darba drošības un veselības aizsardzības jomā'],
		['MM152', 'Vai jūsu uzņēmuma vienībā regulāri tiek analizēti darba kavējuma iemesli slimības dēļ?', 'Vai jūsu uzņēmuma vienībā regulāri tiek analizēti darba kavējuma iemesli slimības dēļ?'],
		['MM153', 'Vai jūs veicat pasākumus, lai veicinātu darbinieku atgriešanos darbā pēc ilgstoša darba kavējuma slimības dēļ?', 'Vai jūs veicat pasākumus, lai veicinātu darbinieku atgriešanos darbā pēc ilgstoša darba kavējuma slimības dēļ?'],
		['MM154', 'Vai tiek veiktas regulāras medicīniskās pārbaudes, lai apzinātu darbinieku veselības stāvokli?', 'Vai tiek veiktas regulāras medicīniskās pārbaudes, lai apzinātu darbinieku veselības stāvokli?'],
		['MM155', 'Vai jūsu uzņēmuma vienībā ir dokumentēta politika, pārvaldības sistēma vai rīcības plāns attiecībā uz darba drošību un veselības aizsardzību?', 'Vai jūsu uzņēmuma vienībā ir dokumentēta politika, pārvaldības sistēma vai rīcības plāns attiecībā uz darba drošību un veselības aizsardzību?'],
		['MM158', 'Vai darba drošības un veselības aizsardzības jautājumi Jūsu uzņēmuma vienības augstākās vadības sanāksmēs tiek apskatīti regulāri, laiku pa laikam vai praktiski nekad?', 'Vai darba drošības un veselības aizsardzības jautājumi Jūsu uzņēmuma vienības augstākās vadības sanāksmēs tiek apskatīti regulāri, laiku pa laikam vai praktiski nekad?'],
		['MM159', 'Kopumā, kā jūs vērtējat vidējā līmeņa vadītāju un vadības pārstāvju iesaistības pakāpi ar darba drošību un veselības aizsardzību saistītu jautājumu risināšanā? Vai tā ir ļoti augsta, diezgan augsta, diezgan zema vai ļoti zema?', 'Kopumā, kā jūs vērtējat vidējā līmeņa vadītāju un vadības pārstāvju iesaistības pakāpi ar darba drošību un veselības aizsardzību saistītu jautājumu risināšanā? Vai tā ir ļoti augsta, diezgan augsta, diezgan zema vai ļoti zema?'],
		['MM161', 'Vai jūsu uzņēmuma vienībā regulāri risku novērtējuma vai līdzīgu pasākumu ietvaros tiek pārbaudīta darbavietu atbilstība drošībai un veselībai?', 'Vai jūsu uzņēmuma vienībā regulāri risku novērtējuma vai līdzīgu pasākumu ietvaros tiek pārbaudīta darbavietu atbilstība drošībai un veselībai?'],
		['MM170', 'Vai Valsts darba inspekcija pēdējo 3 gadu laikā ir veikusi Jūsu uzņēmuma vienībā darba drošības un veselības aizsardzības pārbaudi?', 'Vai Valsts darba inspekcija pēdējo 3 gadu laikā ir veikusi Jūsu uzņēmuma vienībā darba drošības un veselības aizsardzības pārbaudi?'],
		['MM173_1', 'Oficiālās darba drošības un veselības aizsardzības iestādes', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?Oficiālās darba drošības un veselības aizsardzības iestādes'],
		['MM173_2', 'Eiropas Darba drošības un veselības aizsardzības aģentūra', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?Eiropas Darba drošības un veselības aizsardzības aģentūra'],
		['MM173_3', 'Uzņēmuma iekšējie darba drošības un veselības aizsardzības dienesti', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?Uzņēmuma iekšējie darba drošības un veselības aizsardzības dienesti'],
		['MM173_4', 'Valsts darba inspekcija', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?Valsts darba inspekcija'],
		['MM173_5', 'Darba devēju organizācijas', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?Darba devēju organizācijas'],
		['MM173_6', 'Arodbiedrības', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?Arodbiedrības'],
		['MM173_7', 'Nolīgti darba drošības un veselības aizsardzības speciālisti', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?Nolīgti darba drošības un veselības aizsardzības speciālisti'],
		['MM173_8', 'Apdrošināšanas pakalpojumu sniedzēji', 'Vai jūsu uzņēmuma vienība ir izmantojusi šādu organizāciju vai iestāžu sniegtu informāciju par darba drošību un veselības aizsardzību?Apdrošināšanas pakalpojumu sniedzēji'],
		['MM175', 'Vai jūs zināt kaut ko par Eiropas darba drošības un veselības aizsardzības nedēļu?', 'Vai jūs zināt kaut ko par Eiropas darba drošības un veselības aizsardzības nedēļu?'],
		['MM200_1', 'Bīstamas vielas (piemēram, putekĜi, ėīmiskas, bioloăiskas vai radioaktīvas vielas)', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?Bīstamas vielas (Intervētājam: nepieciešamības gadījumā paskaidrojiet: piemēram, putekļi, ķīmiskas, bioloģiskas vai radioaktīvas vielas)'],
		['MM200_2', 'Nelaimes gadījumi', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?Nelaimes gadījumi'],
		['MM200_3', 'Troksnis un vibrācijas', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?Troksnis un vibrācijas'],
		['MM200_4', 'Balsta un kustību aparāta traucējumi, piemēram, muguras sāpes, sāpes sprandā, rokās vai kājās', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?Balsta un kustību aparāta traucējumi, piemēram, muguras sāpes, sāpes sprandā, rokās vai kājās'],
		['MM200_5', 'Stress, kas saistīts ar darba pienākumu izpildi', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?Stress, kas saistīts ar darba pienākumu izpildi'],
		['MM200_6', 'Vardarbība vai vardarbības draudi', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?Vardarbība vai vardarbības draudi'],
		['MM200_7', 'Iebiedēšana vai psiholoģiskais terors, piemēram, apvainošana, pazemošana vai uzbrukums no kolēģu vai vadības puses', 'Par katru no šiem faktoriem, sakiet, lūdzu, vai Jūsu uzņēmuma vienībā tiem tiek pievērsta liela uzmanība, zināma uzmanība vai netiek pievērsta uzmanība nemaz?Iebiedēšana vai psiholoģiskais terors, piemēram, apvainošana, pazemošana vai uzbrukums no kolēģu vai vadības puses'],
		['MM202_1', 'Laika trūkums', 'Stresu, vardarbību un psiholoģisko teroru darbā var sekmēt dažādi faktori; tie saistīti ar darba organizāciju un tos bieži dēvē par "psihosociāliem riskiem". Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?Laika trūkums'],
		['MM202_2', 'Slikta komunikācija starp vadību un darbiniekiem', 'Stresu, vardarbību un psiholoģisko teroru darbā var sekmēt dažādi faktori; tie saistīti ar darba organizāciju un tos bieži dēvē par "psihosociāliem riskiem". Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?Slikta komunikācija starp vadību un darbiniekiem'],
		['MM202_3', 'Vāja sadarbība kolēģu starpā', 'Stresu, vardarbību un psiholoģisko teroru darbā var sekmēt dažādi faktori; tie saistīti ar darba organizāciju un tos bieži dēvē par "psihosociāliem riskiem". Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?Vāja sadarbība kolēģu starpā'],
		['MM202_4', 'Darbinieku nespēja ietekmēt sava darba organizāciju', 'Stresu, vardarbību un psiholoģisko teroru darbā var sekmēt dažādi faktori; tie saistīti ar darba organizāciju un tos bieži dēvē par "psihosociāliem riskiem". Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?Darbinieku nespēja ietekmēt sava darba organizāciju'],
		['MM202_5', 'Darbavietas nedrošība/nepastāvība', 'Stresu, vardarbību un psiholoģisko teroru darbā var sekmēt dažādi faktori; tie saistīti ar darba organizāciju un tos bieži dēvē par "psihosociāliem riskiem". Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?Darbavietas nedrošība/nepastāvība'],
		['MM202_6', 'Darbs ar sarežģītiem klientiem, pacientiem, skolniekiem utt.', 'Stresu, vardarbību un psiholoģisko teroru darbā var sekmēt dažādi faktori; tie saistīti ar darba organizāciju un tos bieži dēvē par "psihosociāliem riskiem". Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?Darbs ar sarežģītiem klientiem, pacientiem, skolniekiem utt.'],
		['MM202_7', 'Problemas vadības un darbinieku attiecības', 'Stresu, vardarbību un psiholoģisko teroru darbā var sekmēt dažādi faktori; tie saistīti ar darba organizāciju un tos bieži dēvē par "psihosociāliem riskiem". Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?Problemas vadības un darbinieku attiecības'],
		['MM202_8', 'Garas vai neregulāras darba stundas', 'Stresu, vardarbību un psiholoģisko teroru darbā var sekmēt dažādi faktori; tie saistīti ar darba organizāciju un tos bieži dēvē par "psihosociāliem riskiem". Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?Garas vai neregulāras darba stundas'],
		['MM202_9', 'Neskaidra cilvēkresursu politika', 'Stresu, vardarbību un psiholoģisko teroru darbā var sekmēt dažādi faktori; tie saistīti ar darba organizāciju un tos bieži dēvē par "psihosociāliem riskiem". Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?Neskaidra cilvēkresursu politika'],
		['MM202_10', 'Diskriminācija (piemēram, dzimuma, vecuma vai etniskā diskriminācija)', 'Stresu, vardarbību un psiholoģisko teroru darbā var sekmēt dažādi faktori; tie saistīti ar darba organizāciju un tos bieži dēvē par "psihosociāliem riskiem". Lūdzu, sakiet, kurš no šiem psihosociālajiem riskiem attiecas uz Jūsu uzņēmuma vienību?Diskriminācija (piemēram, dzimuma, vecuma vai etniskā diskriminācija)'],
		['MM250', 'Vai jūsu pārstāvētajā uzņēmuma vienībā ir noteikta kārtība, kā mazināt stresu, kas saistīts ar darba pienākumu izpildi?', 'Vai jūsu pārstāvētajā uzņēmuma vienībā ir noteikta kārtība, kā mazināt stresu, kas saistīts ar darba pienākumu izpildi?'],
		['MM251', 'Vai jūsu pārstāvētajā uzņēmuma vienībā ir noteikta kārtība, kā risināt iebiedēšanas vai psiholoģiskā terora problēmas?', 'Vai jūsu pārstāvētajā uzņēmuma vienībā ir noteikta kārtība, kā risināt iebiedēšanas vai psiholoģiskā terora problēmas?'],
		['MM252', 'Vai jūsu pārstāvētajā uzņēmuma vienībā ir noteikta kārtība, kā risināt problēmas, kas saistītas ar vardarbību darba vietā?', 'Vai jūsu pārstāvētajā uzņēmuma vienībā ir noteikta kārtība, kā risināt problēmas, kas saistītas ar vardarbību darba vietā?'],
		['MM253_1', 'Izmaiņas darba organizācijā', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?Izmaiņas darba organizācijā'],
		['MM253_2', 'Darba vietas pārplānošana', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?Darba vietas pārplānošana'],
		['MM253_3', 'Konfidenciālas darbinieku konsultācijas', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?Konfidenciālas darbinieku konsultācijas'],
		['MM253_4', 'Konfliktu risināšanas kārtības plānošana', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?Konfliktu risināšanas kārtības plānošana'],
		['MM253_5', 'Izmaiņas darba laika sistēmā', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?Izmaiņas darba laika sistēmā'],
		['MM253_6', 'Apmācību nodrošināšana', 'Vai pēdējo 3 gadu laikā jūsu uzņēmuma vienībā ir izmantots kāds no šiem veidiem psihosociālo risku novēršanai?Apmācību nodrošināšana'],
		['MM256', 'Vai jūsu uzņēmuma vienībā tiek veikti kaut kādi pasākumi, ja atsevišķi darbinieki strādā pārāk garas vai neregulāras darba stundas?', 'Vai jūsu uzņēmuma vienībā tiek veikti kaut kādi pasākumi, ja atsevišķi darbinieki strādā pārāk garas vai neregulāras darba stundas?'],
		['MM259', 'Vai jūs informējat darbiniekus par psihosociālajiem riskiem un to ietekmi uz drošību un veselību?', 'Vai jūs informējat darbiniekus par psihosociālajiem riskiem un to ietekmi uz drošību un veselību?'],
		['MM260', 'Vai darbinieki ir informēti, kur vērsties ar darbu saistīto psihosociālo problēmu gadījumā ?', 'Vai darbinieki ir informēti, kur vērsties ar darbu saistīto psihosociālo problēmu gadījumā ?'],
		['MM171_1', 'Likumisko prasību izpilde', 'Cik svarīgi jūsu uzņēmuma vienībā ir šādi iemesli, lai pievērstos darba drošības un veselības aizsardzības jautājumu risināšanai? Par katru no šiem, lūdzu, norādiet, vai tas ir ļoti nozīmīgs, maznozīmīgs vai pavisam nesvarīgs iemesls.Likumisko prasību izpilde'],
		['MM171_2', 'Darbinieku vai viņu pārstāvju lūgums', 'Cik svarīgi jūsu uzņēmuma vienībā ir šādi iemesli, lai pievērstos darba drošības un veselības aizsardzības jautājumu risināšanai? Par katru no šiem, lūdzu, norādiet, vai tas ir ļoti nozīmīgs, maznozīmīgs vai pavisam nesvarīgs iemesls.Darbinieku vai viņu pārstāvju lūgums'],
		['MM171_3', 'Darbinieku saglabāšanas un darba kavējumu pārvaldība', 'Cik svarīgi jūsu uzņēmuma vienībā ir šādi iemesli, lai pievērstos darba drošības un veselības aizsardzības jautājumu risināšanai? Par katru no šiem, lūdzu, norādiet, vai tas ir ļoti nozīmīgs, maznozīmīgs vai pavisam nesvarīgs iemesls.Darbinieku saglabāšanas un darba kavējumu pārvaldība'],
		['MM171_4', 'Ekonomiski vai ar darba izpildi saistīti iemesli', 'Cik svarīgi jūsu uzņēmuma vienībā ir šādi iemesli, lai pievērstos darba drošības un veselības aizsardzības jautājumu risināšanai? Par katru no šiem, lūdzu, norādiet, vai tas ir ļoti nozīmīgs, maznozīmīgs vai pavisam nesvarīgs iemesls.Ekonomiski vai ar darba izpildi saistīti iemesli'],
		['MM171_5', 'Klientu prasības vai bažas par uzņēmuma reputāciju', 'Cik svarīgi jūsu uzņēmuma vienībā ir šādi iemesli, lai pievērstos darba drošības un veselības aizsardzības jautājumu risināšanai? Par katru no šiem, lūdzu, norādiet, vai tas ir ļoti nozīmīgs, maznozīmīgs vai pavisam nesvarīgs iemesls.Klientu prasības vai bažas par uzņēmuma reputāciju'],
		['MM171_6', 'Spiediens no Valsts darba inspekcijas puses', 'Cik svarīgi jūsu uzņēmuma vienībā ir šādi iemesli, lai pievērstos darba drošības un veselības aizsardzības jautājumu risināšanai? Par katru no šiem, lūdzu, norādiet, vai tas ir ļoti nozīmīgs, maznozīmīgs vai pavisam nesvarīgs iemesls.Spiediens no Valsts darba inspekcijas puses'],
		['MM172_1', 'Līdzekļu tādu kā, piemēram, laiks, darbaspēks vai nauda, trūkums', 'Kādi ir galvenie šķēršļi, kas traucē veikt nepieciešamos darba drošības un veselības aizsardzības pasākumus Jūsu uzņēmuma vienībā. Par katru no šiem, lūdzu, norādiet, vai tas ir ļoti nozīmīgs, maznozīmīgs vai tas pavisam nav šķērslis.Līdzekļu tādu kā, piemēram, laiks, darbaspēks vai nauda, trūkums'],
		['MM172_2', 'Informētības trūkums', 'Kādi ir galvenie šķēršļi, kas traucē veikt nepieciešamos darba drošības un veselības aizsardzības pasākumus Jūsu uzņēmuma vienībā. Par katru no šiem, lūdzu, norādiet, vai tas ir ļoti nozīmīgs, maznozīmīgs vai tas pavisam nav šķērslis.Informētības trūkums'],
		['MM172_3', 'Speciālu zināšanu/kompetences trūkums', 'Kādi ir galvenie šķēršļi, kas traucē veikt nepieciešamos darba drošības un veselības aizsardzības pasākumus Jūsu uzņēmuma vienībā. Par katru no šiem, lūdzu, norādiet, vai tas ir ļoti nozīmīgs, maznozīmīgs vai tas pavisam nav šķērslis.Speciālu zināšanu/kompetences trūkums'],
		['MM172_4', 'Tehniskā nodrošinājuma vai instrukciju trūkums', 'Kādi ir galvenie šķēršļi, kas traucē veikt nepieciešamos darba drošības un veselības aizsardzības pasākumus Jūsu uzņēmuma vienībā. Par katru no šiem, lūdzu, norādiet, vai tas ir ļoti nozīmīgs, maznozīmīgs vai tas pavisam nav šķērslis.Tehniskā nodrošinājuma vai instrukciju trūkums'],
		['MM172_5', 'Uzņēmuma vienības/uzņēmuma kultūra', 'Kādi ir galvenie šķēršļi, kas traucē veikt nepieciešamos darba drošības un veselības aizsardzības pasākumus Jūsu uzņēmuma vienībā. Par katru no šiem, lūdzu, norādiet, vai tas ir ļoti nozīmīgs, maznozīmīgs vai tas pavisam nav šķērslis.Uzņēmuma vienības/uzņēmuma kultūra'],
		['MM172_6', 'Tas ir jūtīgs jautājums', 'Kādi ir galvenie šķēršļi, kas traucē veikt nepieciešamos darba drošības un veselības aizsardzības pasākumus Jūsu uzņēmuma vienībā. Par katru no šiem, lūdzu, norādiet, vai tas ir ļoti nozīmīgs, maznozīmīgs vai tas pavisam nav šķērslis.Tas ir jūtīgs jautājums'],
		['MM300', 'Salīdzinot ar citiem ar darba drošību un veselības aizsardzību saistītiem jautājumiem: Vai novērst psihosociālos riskus ir grūtāk, vieglāk vai nav atšķirības', 'Salīdzinot ar citiem ar darba drošību un veselības aizsardzību saistītiem jautājumiem: Vai novērst psihosociālos riskus ir grūtāk, vieglāk vai nav atšķirības'],
		['MM302', 'Vai jūsu esat izmantojuši ārēju avotu informāciju vai atbalstu psihosociālo risku novēršanai?', 'Vai jūsu esat izmantojuši ārēju avotu informāciju vai atbalstu psihosociālo risku novēršanai?'],
		['MM303a', 'Vai jums būtu nepieciešama papildus informācija vai atbalsts šajā jautājumā?', 'Vai jums būtu nepieciešama papildus informācija vai atbalsts šajā jautājumā?<br><br>Jautājums uzdots iestādēm, kuras ziņo, ka izmanto ārējo resursu informāciju vai atbalstu par to, kā novērst psihosociālos riskus darba vietā.'],
		['MM350', 'Vai jūsu uzņēmuma vienībā ir darbinieku pilnvarotais pārstāvis vai Darba padome?', 'Vai jūsu uzņēmuma vienībā ir darbinieku pilnvarotais pārstāvis vai Darba padome?'],
		['MM351', 'Un vai jūsu uzņēmuma vienībā ir arodbiedrība?', 'Un vai jūsu uzņēmuma vienībā ir arodbiedrība?'],
		['MM355all', 'Vai jūsu uzņēmuma vienībā ir nodarbināto uzticības persona?', 'Vai jūsu uzņēmuma vienībā ir nodarbināto uzticības persona?<br><br>NL: Vai šajā uzņēmumā ir pārstāvja darba drošības un veselības aizsardzības jautājumos biedrs?'],
		['MM358', 'Vai jūsu uzņēmuma vienībā ir nodarbināto uzticības personu komiteja?', 'Vai jūsu uzņēmuma vienībā ir nodarbināto uzticības personu komiteja?']
	];
