//Auto Generated file
var subset_
	 = [
	
		['size_4', 'Daqs tal-istabbiliment'],
		['sec3', 'Settur ta’ attività']
	];
var subset_subsetValue
	 = [
	
		['sec3', 'All', 'Kollha'],
		['sec3', '1--Producing-Industries', 'Settur ta’ produzzjoni'],
		['sec3', '2--Private-Services', 'Servizzi Privati'],
		['sec3', '3--Public-Services', 'Servizzi Pubbliċi'],
		['size_4', 'All', 'Kollha'],
		['size_4', '1--10-to-19-employees', '10 sa 19 impjegat'],
		['size_4', '2--20-to-49-employees', '20 sa 49 impjegat'],
		['size_4', '3--50-to-249-employees', '50 sa 249 impjegat'],
		['size_4', '4--250-employees-or-more', '250 impjegat jew iżjed']
	];
var topic_
	 = [
	
		['', 'Kollha (70)'],
		['Il-parteċipazzjoni tal-impjegati', 'Il-parteċipazzjoni tal-impjegati (4)'],
		['Motivaturi u ostakli', 'Motivaturi u ostakli (15)'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'Riskji psikosoċjali u l-kontroll tagħhom (22)'],
		['Ġestjoni tal-OSH', 'Ġestjoni tal-OSH (29)']
	];
var topic_question
	 = [
	
		['Ġestjoni tal-OSH', 'MM150_1', 'L-użu tas-servizzi ta’ saħħa u sigurtà: Tabib fuq il-post tax-xogħol'],
		['Ġestjoni tal-OSH', 'MM150_2', 'L-użu tas-servizzi ta’ saħħa u sigurtà: Espert tas-sigurtà'],
		['Ġestjoni tal-OSH', 'MM150_3', 'L-użu tas-servizzi ta’ saħħa u sigurtà: Psikoloġista'],
		['Ġestjoni tal-OSH', 'MM150_4', 'L-użu tas-servizzi ta’ saħħa u sigurtà: Espert tal-ergonomija, li jieħu ħsieb it-twaqqif tal-workstation'],
		['Ġestjoni tal-OSH', 'MM150_5', 'L-użu tas-servizzi ta’ saħħa u sigurtà: Konsulenza ġenerali tas-saħħa u s-sigurtà'],
		['Ġestjoni tal-OSH', 'MM152', 'Il-post tax-xogħol tiegħek janalizza b’mod regolari l-kawżi tal-assenza minħabba mard?'],
		['Ġestjoni tal-OSH', 'MM153', 'Tieħu miżuri sabiex tappoġġja r-ritorn fuq il-post tax-xogħol wara assenza ta’ żmien twil minħabba mard?'],
		['Ġestjoni tal-OSH', 'MM154', 'Is-saħħa tal-impjegati hija ssorveljata permezz ta’ eżaminazzjonijiet mediċi regolari?'],
		['Ġestjoni tal-OSH', 'MM155', 'Hemm xi policy dokumentata, management system stabbilita jew pjan ta’ azzjoni dwar is-saħħa u s-sigurtà fuq il-post tax-xogħol tiegħek?'],
		['Ġestjoni tal-OSH', 'MM158', 'Suġġetti ta’ saħħa u sigurtà jitqajjmu f’laqgħat tal-management fuq livell għoli b’mod regolari, xi kultant jew prattikament qatt?'],
		['Ġestjoni tal-OSH', 'MM159', 'B’mod ġenerali, kif tikklassifika l-grad ta’ involviment tal-’line’ maniġers u supervisors fl-immaniġjar tas-saħħa u s-sigurtà? Huwa għoli ħafna, pjuttost għoli, pjuttost baxx jew baxx ħafna?'],
		['Ġestjoni tal-OSH', 'MM161', 'Il-postijiet ta’ ħidma fil-post tax-xogħol tiegħek huma iċċekjati regolarment għas-saħħa u s-sigurtà bħala parti minn risk assesment jew miżura simili?'],
		['Ġestjoni tal-OSH', 'MM170', 'L-ispettorat tax-xogħol żar il-post tax-xogħol f’dawn l-aħħar 3 snin biex jiċċekkja l-kondizzjonijiet tas-saħħa u s-sigurtà?'],
		['Ġestjoni tal-OSH', 'MM173_1', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: Istituti uffiċjali għas-saħħa u s-sigurtà fuq ix-xogħol'],
		['Ġestjoni tal-OSH', 'MM173_2', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: L-Aġenzija Ewropea għas-saħħa u sigurtà fuq ix-xogħol'],
		['Ġestjoni tal-OSH', 'MM173_3', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: Servizzi interni (in-house) tas-saħħa u s-sigurtà'],
		['Ġestjoni tal-OSH', 'MM173_4', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: L-ispettorat tax-xogħol'],
		['Ġestjoni tal-OSH', 'MM173_5', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: Organizzazzjonijiet ta’ min iħaddem'],
		['Ġestjoni tal-OSH', 'MM173_6', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: Trejdunjins'],
		['Ġestjoni tal-OSH', 'MM173_7', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: Esperti kuntrattati tas-saħħa u s-sigurtà'],
		['Ġestjoni tal-OSH', 'MM173_8', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: Kumpaniji tal-assigurazzjoni'],
		['Ġestjoni tal-OSH', 'MM175', 'Inti konxju mill-Ġimgħa Ewropea dwar is-saħħa u s-sigurtà fuq ix-xogħol?'],
		['Ġestjoni tal-OSH', 'MM200_1', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek: Sustanzi perikolużi (e.ż. trabijiet, kimiċi, bioloġiċi jew radjuattivi)'],
		['Ġestjoni tal-OSH', 'MM200_2', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek: Inċidenti'],
		['Ġestjoni tal-OSH', 'MM200_3', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek: Storbju u vibrazzjoni'],
		['Ġestjoni tal-OSH', 'MM200_4', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek: Mard muskoluskeletali bħal uġiegħ fid-dahar, l-għonq, id-dirgħajn jew ir-riġlejn'],
		['Ġestjoni tal-OSH', 'MM200_5', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek: Stress relatat max-xogħol'],
		['Ġestjoni tal-OSH', 'MM200_6', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek: Vjolenza jew theddida ta’ vjolenza'],
		['Ġestjoni tal-OSH', 'MM200_7', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek: Bullying jew iffastidjar i.e. Abbuż, umiljazzjoni jew attakki minn kollegi jew superjuri'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM202_1', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Pressjoni ta’ ħin'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM202_2', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Komunikazzjoni batuta bejn il-management u l-impjegati'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM202_3', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Kooperazzjoni fqira fost il-kollegi'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM202_4', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Nuqqas ta’ kontroll ta’ impjegati meta jorganizzaw ix-xogħol tagħhom'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM202_5', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. .: Nuqqas ta’ sigurtà tax-xogħol'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM202_6', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Li jkollhom jittrattaw ma’ klijenti, pazjenti, studenti eċċ diffiċli'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM202_7', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Problemi fir-relazzjoni bejn is-supervisor u l-impjegat'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM202_8', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. .: Siegħat tax-xogħol twal jew irregolari'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM202_9', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Policy tar-riżorsi umani mhux ċara'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM202_10', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Diskriminazzjoni (per eżempju minħabba sess, età jew etniċità)'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM250', 'Il-post tax-xogħol tiegħek għandu proċedura sabiex jittratta ma’ stress relatat max-xogħol?'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM251', 'Hemm proċedura fis-seħħ sabiex titratta l-bullying jew il-fastidu?'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM252', 'U għandkom proċedura li titratta l-vjolenza relatata max-xogħol?'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM253_1', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?: Tibdil fil-mod kif ix-xogħol huwa organizzat'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM253_2', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?: Disinn mill-ġdid (redesign) tal-post tax-xogħol'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM253_3', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?: Għoti ta’ parir kunfidenzjali għall-impjegati'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM253_4', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?: Twaqqif ta’ proċedura għar-riżoluzzjoni ta’ kunflitt'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM253_5', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?: Tibdiliet fl-arranġamenti tal-ħin tax-xogħol'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM253_6', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?: Għoti ta’ taħriġ'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM256', 'Il-post tax-xogħol tiegħek jieħu azzjoni jekk ikun hemm impjegati individwali li jaħdmu siegħat eċċessivi li huma twal jew irregolari?'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM259', 'Inti tinforma lill-impjegati dwar riskji psikolsoċjali u l-effett tagħhom fuq is-saħħa u sigurtà?'],
		['Riskji psikosoċjali u l-kontroll tagħhom', 'MM260', 'Ġew infurmati dwar lil min għandhom jindirizzaw f’każ ta’ problemi psikosoċjali relatati max-xogħol?'],
		['Motivaturi u ostakli', 'MM171_1', 'Raġunijiet biex tkun indirizzata s-saħħa u s-sigurtà fl-istabbiliment: Twettieq ta’ obbligu legali'],
		['Motivaturi u ostakli', 'MM171_2', 'Raġunijiet biex tkun indirizzata s-saħħa u s-sigurtà fl-istabbiliment: Talbiet minn impjegati jew ir-rappreżentanti tagħhom'],
		['Motivaturi u ostakli', 'MM171_3', 'Raġunijiet biex tkun indirizzata s-saħħa u s-sigurtà fl-istabbiliment: Staff retention’ jew immaniġġjar ta’ assenza'],
		['Motivaturi u ostakli', 'MM171_4', 'Raġunijiet biex tkun indirizzata s-saħħa u s-sigurtà fl-istabbiliment: Raġunijiet ekonomiċi jew relatati mal-kapaċità (performance-related)'],
		['Motivaturi u ostakli', 'MM171_5', 'Raġunijiet biex tkun indirizzata s-saħħa u s-sigurtà fl-istabbiliment: Ħtiġijiet mill-klijenti jew tħassib dwar ir-reputazzjoni tal-organizzazzjoni'],
		['Motivaturi u ostakli', 'MM171_6', 'Raġunijiet biex tkun indirizzata s-saħħa u s-sigurtà fl-istabbiliment: Pressjoni mill-ispettorat tax-xogħol'],
		['Motivaturi u ostakli', 'MM172_1', 'Diffikultajiet ewlenin biex ikunu indirizzati s-saħħa u s-sigurtà: Nuqqas ta’ riżorsi bħal ħin, staff jew flus'],
		['Motivaturi u ostakli', 'MM172_2', 'Diffikultajiet ewlenin biex ikunu indirizzati s-saħħa u s-sigurtà: Nuqqas ta’ għarfien'],
		['Motivaturi u ostakli', 'MM172_3', 'Diffikultajiet ewlenin biex ikunu indirizzati s-saħħa u s-sigurtà: Nuqqas ta’ kompetenza'],
		['Motivaturi u ostakli', 'MM172_4', 'Diffikultajiet ewlenin biex ikunu indirizzati s-saħħa u s-sigurtà: Nuqqas ta’ appoġġ tekniku jew gwida'],
		['Motivaturi u ostakli', 'MM172_5', 'Diffikultajiet ewlenin biex ikunu indirizzati s-saħħa u s-sigurtà: Il-kultura fil-post tax-xogħol'],
		['Motivaturi u ostakli', 'MM172_6', 'Diffikultajiet ewlenin biex ikunu indirizzati s-saħħa u s-sigurtà: Is-sensittività tas-suġġett'],
		['Motivaturi u ostakli', 'MM300', 'Meta mqabbel ma’ suġġetti oħra ta’ saħħa u sigurtà: Huwa aktar diffiċli li tittratta riskji psikosoċjali, huwa inqas diffiċli, jew ma hemmx differenza?'],
		['Motivaturi u ostakli', 'MM302', 'Inti użajt informazzjoni jew appoġġ minn sorsi esterni dwar kif titratta ma’ riskji psikosoċjali fuq ix-xogħol?'],
		['Motivaturi u ostakli', 'MM303a', 'Għandek bżonn xi informazzjoni oħra dwar dan is-suġġett?'],
		['Il-parteċipazzjoni tal-impjegati', 'MM350', 'F’dan l-istabbiliment għandkom kunsill tax-xogħlijiet?'],
		['Il-parteċipazzjoni tal-impjegati', 'MM351', 'U hemm rappreżentant rikonoxxut tal-unjin fil-post tax-xogħol tiegħek?'],
		['Il-parteċipazzjoni tal-impjegati', 'MM355all', 'Il-post tax-xogħol tiegħek għandu rappreżentant intern tas-saħħa u s-sigurtà?'],
		['Il-parteċipazzjoni tal-impjegati', 'MM358', 'Hemm kumitat tas-saħħa u s-sigurtà fl-istabbiliment tiegħek?']
	];
var question_
	 = [
	
		['MM150_1', 'L-użu tas-servizzi ta’ saħħa u sigurtà: Tabib fuq il-post tax-xogħol'],
		['MM150_2', 'L-użu tas-servizzi ta’ saħħa u sigurtà: Espert tas-sigurtà'],
		['MM150_3', 'L-użu tas-servizzi ta’ saħħa u sigurtà: Psikoloġista'],
		['MM150_4', 'L-użu tas-servizzi ta’ saħħa u sigurtà: Espert tal-ergonomija, li jieħu ħsieb it-twaqqif tal-workstation'],
		['MM150_5', 'L-użu tas-servizzi ta’ saħħa u sigurtà: Konsulenza ġenerali tas-saħħa u s-sigurtà'],
		['MM152', 'Il-post tax-xogħol tiegħek janalizza b’mod regolari l-kawżi tal-assenza minħabba mard?'],
		['MM153', 'Tieħu miżuri sabiex tappoġġja r-ritorn fuq il-post tax-xogħol wara assenza ta’ żmien twil minħabba mard?'],
		['MM154', 'Is-saħħa tal-impjegati hija ssorveljata permezz ta’ eżaminazzjonijiet mediċi regolari?'],
		['MM155', 'Hemm xi policy dokumentata, management system stabbilita jew pjan ta’ azzjoni dwar is-saħħa u s-sigurtà fuq il-post tax-xogħol tiegħek?'],
		['MM158', 'Suġġetti ta’ saħħa u sigurtà jitqajjmu f’laqgħat tal-management fuq livell għoli b’mod regolari, xi kultant jew prattikament qatt?'],
		['MM159', 'B’mod ġenerali, kif tikklassifika l-grad ta’ involviment tal-’line’ maniġers u supervisors fl-immaniġjar tas-saħħa u s-sigurtà? Huwa għoli ħafna, pjuttost għoli, pjuttost baxx jew baxx ħafna?'],
		['MM161', 'Il-postijiet ta’ ħidma fil-post tax-xogħol tiegħek huma iċċekjati regolarment għas-saħħa u s-sigurtà bħala parti minn risk assesment jew miżura simili?'],
		['MM170', 'L-ispettorat tax-xogħol żar il-post tax-xogħol f’dawn l-aħħar 3 snin biex jiċċekkja l-kondizzjonijiet tas-saħħa u s-sigurtà?'],
		['MM173_1', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: Istituti uffiċjali għas-saħħa u s-sigurtà fuq ix-xogħol'],
		['MM173_2', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: L-Aġenzija Ewropea għas-saħħa u sigurtà fuq ix-xogħol'],
		['MM173_3', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: Servizzi interni (in-house) tas-saħħa u s-sigurtà'],
		['MM173_4', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: L-ispettorat tax-xogħol'],
		['MM173_5', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: Organizzazzjonijiet ta’ min iħaddem'],
		['MM173_6', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: Trejdunjins'],
		['MM173_7', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: Esperti kuntrattati tas-saħħa u s-sigurtà'],
		['MM173_8', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?: Kumpaniji tal-assigurazzjoni'],
		['MM175', 'Inti konxju mill-Ġimgħa Ewropea dwar is-saħħa u s-sigurtà fuq ix-xogħol?'],
		['MM200_1', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek: Sustanzi perikolużi (e.ż. trabijiet, kimiċi, bioloġiċi jew radjuattivi)'],
		['MM200_2', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek: Inċidenti'],
		['MM200_3', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek: Storbju u vibrazzjoni'],
		['MM200_4', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek: Mard muskoluskeletali bħal uġiegħ fid-dahar, l-għonq, id-dirgħajn jew ir-riġlejn'],
		['MM200_5', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek: Stress relatat max-xogħol'],
		['MM200_6', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek: Vjolenza jew theddida ta’ vjolenza'],
		['MM200_7', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek: Bullying jew iffastidjar i.e. Abbuż, umiljazzjoni jew attakki minn kollegi jew superjuri'],
		['MM202_1', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Pressjoni ta’ ħin'],
		['MM202_2', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Komunikazzjoni batuta bejn il-management u l-impjegati'],
		['MM202_3', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Kooperazzjoni fqira fost il-kollegi'],
		['MM202_4', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Nuqqas ta’ kontroll ta’ impjegati meta jorganizzaw ix-xogħol tagħhom'],
		['MM202_5', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. .: Nuqqas ta’ sigurtà tax-xogħol'],
		['MM202_6', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Li jkollhom jittrattaw ma’ klijenti, pazjenti, studenti eċċ diffiċli'],
		['MM202_7', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Problemi fir-relazzjoni bejn is-supervisor u l-impjegat'],
		['MM202_8', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. .: Siegħat tax-xogħol twal jew irregolari'],
		['MM202_9', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Policy tar-riżorsi umani mhux ċara'],
		['MM202_10', 'Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek. : Diskriminazzjoni (per eżempju minħabba sess, età jew etniċità)'],
		['MM250', 'Il-post tax-xogħol tiegħek għandu proċedura sabiex jittratta ma’ stress relatat max-xogħol?'],
		['MM251', 'Hemm proċedura fis-seħħ sabiex titratta l-bullying jew il-fastidu?'],
		['MM252', 'U għandkom proċedura li titratta l-vjolenza relatata max-xogħol?'],
		['MM253_1', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?: Tibdil fil-mod kif ix-xogħol huwa organizzat'],
		['MM253_2', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?: Disinn mill-ġdid (redesign) tal-post tax-xogħol'],
		['MM253_3', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?: Għoti ta’ parir kunfidenzjali għall-impjegati'],
		['MM253_4', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?: Twaqqif ta’ proċedura għar-riżoluzzjoni ta’ kunflitt'],
		['MM253_5', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?: Tibdiliet fl-arranġamenti tal-ħin tax-xogħol'],
		['MM253_6', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?: Għoti ta’ taħriġ'],
		['MM256', 'Il-post tax-xogħol tiegħek jieħu azzjoni jekk ikun hemm impjegati individwali li jaħdmu siegħat eċċessivi li huma twal jew irregolari?'],
		['MM259', 'Inti tinforma lill-impjegati dwar riskji psikolsoċjali u l-effett tagħhom fuq is-saħħa u sigurtà?'],
		['MM260', 'Ġew infurmati dwar lil min għandhom jindirizzaw f’każ ta’ problemi psikosoċjali relatati max-xogħol?'],
		['MM171_1', 'Raġunijiet biex tkun indirizzata s-saħħa u s-sigurtà fl-istabbiliment: Twettieq ta’ obbligu legali'],
		['MM171_2', 'Raġunijiet biex tkun indirizzata s-saħħa u s-sigurtà fl-istabbiliment: Talbiet minn impjegati jew ir-rappreżentanti tagħhom'],
		['MM171_3', 'Raġunijiet biex tkun indirizzata s-saħħa u s-sigurtà fl-istabbiliment: Staff retention’ jew immaniġġjar ta’ assenza'],
		['MM171_4', 'Raġunijiet biex tkun indirizzata s-saħħa u s-sigurtà fl-istabbiliment: Raġunijiet ekonomiċi jew relatati mal-kapaċità (performance-related)'],
		['MM171_5', 'Raġunijiet biex tkun indirizzata s-saħħa u s-sigurtà fl-istabbiliment: Ħtiġijiet mill-klijenti jew tħassib dwar ir-reputazzjoni tal-organizzazzjoni'],
		['MM171_6', 'Raġunijiet biex tkun indirizzata s-saħħa u s-sigurtà fl-istabbiliment: Pressjoni mill-ispettorat tax-xogħol'],
		['MM172_1', 'Diffikultajiet ewlenin biex ikunu indirizzati s-saħħa u s-sigurtà: Nuqqas ta’ riżorsi bħal ħin, staff jew flus'],
		['MM172_2', 'Diffikultajiet ewlenin biex ikunu indirizzati s-saħħa u s-sigurtà: Nuqqas ta’ għarfien'],
		['MM172_3', 'Diffikultajiet ewlenin biex ikunu indirizzati s-saħħa u s-sigurtà: Nuqqas ta’ kompetenza'],
		['MM172_4', 'Diffikultajiet ewlenin biex ikunu indirizzati s-saħħa u s-sigurtà: Nuqqas ta’ appoġġ tekniku jew gwida'],
		['MM172_5', 'Diffikultajiet ewlenin biex ikunu indirizzati s-saħħa u s-sigurtà: Il-kultura fil-post tax-xogħol'],
		['MM172_6', 'Diffikultajiet ewlenin biex ikunu indirizzati s-saħħa u s-sigurtà: Is-sensittività tas-suġġett'],
		['MM300', 'Meta mqabbel ma’ suġġetti oħra ta’ saħħa u sigurtà: Huwa aktar diffiċli li tittratta riskji psikosoċjali, huwa inqas diffiċli, jew ma hemmx differenza?'],
		['MM302', 'Inti użajt informazzjoni jew appoġġ minn sorsi esterni dwar kif titratta ma’ riskji psikosoċjali fuq ix-xogħol?'],
		['MM303a', 'Għandek bżonn xi informazzjoni oħra dwar dan is-suġġett?'],
		['MM350', 'F’dan l-istabbiliment għandkom kunsill tax-xogħlijiet?'],
		['MM351', 'U hemm rappreżentant rikonoxxut tal-unjin fil-post tax-xogħol tiegħek?'],
		['MM355all', 'Il-post tax-xogħol tiegħek għandu rappreżentant intern tas-saħħa u s-sigurtà?'],
		['MM358', 'Hemm kumitat tas-saħħa u s-sigurtà fl-istabbiliment tiegħek?']
	];
var question_answer
	 = [
	
		['MM150_1', '1--Yes', 'Iva'],
		['MM150_1', '2--No', 'Le'],
		['MM150_1', '3--DK--NA', 'L-ebda tweġiba'],
		['MM150_2', '1--Yes', 'Iva'],
		['MM150_2', '2--No', 'Le'],
		['MM150_2', '3--DK--NA', 'L-ebda tweġiba'],
		['MM150_3', '1--Yes', 'Iva'],
		['MM150_3', '2--No', 'Le'],
		['MM150_3', '3--DK--NA', 'L-ebda tweġiba'],
		['MM150_4', '1--Yes', 'Iva'],
		['MM150_4', '2--No', 'Le'],
		['MM150_4', '3--DK--NA', 'L-ebda tweġiba'],
		['MM150_5', '1--Yes', 'Iva'],
		['MM150_5', '2--No', 'Le'],
		['MM150_5', '3--DK--NA', 'L-ebda tweġiba'],
		['MM152', '1--Yes', 'Iva'],
		['MM152', '2--No', 'Le'],
		['MM152', '3--DK--NA', 'L-ebda tweġiba'],
		['MM153', '1--Yes', 'Iva'],
		['MM153', '2--No', 'Le'],
		['MM153', '3--DK--NA', 'L-ebda tweġiba'],
		['MM154', '1--Yes', 'Iva'],
		['MM154', '2--No', 'Le'],
		['MM154', '3--DK--NA', 'L-ebda tweġiba'],
		['MM155', '1--Yes', 'Iva'],
		['MM155', '2--No', 'Le'],
		['MM155', '3--DK--NA', 'L-ebda tweġiba'],
		['MM158', '1--Regularly', 'Regolarment'],
		['MM158', '2--Occasionally', 'Kultant'],
		['MM158', '3--Practically-never', 'Prattikament qatt'],
		['MM158', '4--DK--NA', 'L-ebda tweġiba'],
		['MM159', '1--Very-high', 'Għoli ħafna'],
		['MM159', '2--Quite-high', 'Pjuttost għoli'],
		['MM159', '3--Quite-low', 'Pjuttost baxx'],
		['MM159', '4--Very-low', 'Baxx ħafna'],
		['MM159', '5--DK--NA', 'L-ebda tweġiba'],
		['MM161', '1--Yes', 'Iva'],
		['MM161', '2--No', 'Le'],
		['MM161', '3--DK--NA', 'L-ebda tweġiba'],
		['MM170', '1--Yes', 'Iva'],
		['MM170', '2--No', 'Le'],
		['MM170', '3--DK--NA', 'L-ebda tweġiba'],
		['MM171_1', '1--Major', 'Raġuni importanti'],
		['MM171_1', '2--Minor', 'Raġuni mhux importanti'],
		['MM171_1', '3--No', 'M’humiex raġuni'],
		['MM171_1', '4--DK--NA', 'L-ebda tweġiba'],
		['MM171_2', '1--Major', 'Raġuni importanti'],
		['MM171_2', '2--Minor', 'Raġuni mhux importanti'],
		['MM171_2', '3--No', 'M’humiex raġuni'],
		['MM171_2', '4--DK--NA', 'L-ebda tweġiba'],
		['MM171_3', '1--Major', 'Raġuni importanti'],
		['MM171_3', '2--Minor', 'Raġuni mhux importanti'],
		['MM171_3', '3--No', 'M’humiex raġuni'],
		['MM171_3', '4--DK--NA', 'L-ebda tweġiba'],
		['MM171_4', '1--Major', 'Raġuni importanti'],
		['MM171_4', '2--Minor', 'Raġuni mhux importanti'],
		['MM171_4', '3--No', 'M’humiex raġuni'],
		['MM171_4', '4--DK--NA', 'L-ebda tweġiba'],
		['MM171_5', '1--Major', 'Raġuni importanti'],
		['MM171_5', '2--Minor', 'Raġuni mhux importanti'],
		['MM171_5', '3--No', 'M’humiex raġuni'],
		['MM171_5', '4--DK--NA', 'L-ebda tweġiba'],
		['MM171_6', '1--Major', 'Raġuni importanti'],
		['MM171_6', '2--Minor', 'Raġuni mhux importanti'],
		['MM171_6', '3--No', 'M’humiex raġuni'],
		['MM171_6', '4--DK--NA', 'L-ebda tweġiba'],
		['MM172_1', '1--Major', 'Diffikultà kbira'],
		['MM172_1', '2--Minor', 'Diffikultà żgħira'],
		['MM172_1', '3--No', 'Mhux ta’ ebda diffikultà'],
		['MM172_1', '4--DK--NA', 'L-ebda tweġiba'],
		['MM172_2', '1--Major', 'Diffikultà kbira'],
		['MM172_2', '2--Minor', 'Diffikultà żgħira'],
		['MM172_2', '3--No', 'Mhux ta’ ebda diffikultà'],
		['MM172_2', '4--DK--NA', 'L-ebda tweġiba'],
		['MM172_3', '1--Major', 'Diffikultà kbira'],
		['MM172_3', '2--Minor', 'Diffikultà żgħira'],
		['MM172_3', '3--No', 'Mhux ta’ ebda diffikultà'],
		['MM172_3', '4--DK--NA', 'L-ebda tweġiba'],
		['MM172_4', '1--Major', 'Diffikultà kbira'],
		['MM172_4', '2--Minor', 'Diffikultà żgħira'],
		['MM172_4', '3--No', 'Mhux ta’ ebda diffikultà'],
		['MM172_4', '4--DK--NA', 'L-ebda tweġiba'],
		['MM172_5', '1--Major', 'Diffikultà kbira'],
		['MM172_5', '2--Minor', 'Diffikultà żgħira'],
		['MM172_5', '3--No', 'Mhux ta’ ebda diffikultà'],
		['MM172_5', '4--DK--NA', 'L-ebda tweġiba'],
		['MM172_6', '1--Major', 'Diffikultà kbira'],
		['MM172_6', '2--Minor', 'Diffikultà żgħira'],
		['MM172_6', '3--No', 'Mhux ta’ ebda diffikultà'],
		['MM172_6', '4--DK--NA', 'L-ebda tweġiba'],
		['MM173_1', '1--Yes', 'Iva'],
		['MM173_1', '2--No', 'Le'],
		['MM173_1', '3--DK--NA', 'L-ebda tweġiba'],
		['MM173_2', '1--Yes', 'Iva'],
		['MM173_2', '2--No', 'Le'],
		['MM173_2', '3--DK--NA', 'L-ebda tweġiba'],
		['MM173_3', '1--Yes', 'Iva'],
		['MM173_3', '2--No', 'Le'],
		['MM173_3', '3--DK--NA', 'L-ebda tweġiba'],
		['MM173_4', '1--Yes', 'Iva'],
		['MM173_4', '2--No', 'Le'],
		['MM173_4', '3--DK--NA', 'L-ebda tweġiba'],
		['MM173_5', '1--Yes', 'Iva'],
		['MM173_5', '2--No', 'Le'],
		['MM173_5', '3--DK--NA', 'L-ebda tweġiba'],
		['MM173_6', '1--Yes', 'Iva'],
		['MM173_6', '2--No', 'Le'],
		['MM173_6', '3--DK--NA', 'L-ebda tweġiba'],
		['MM173_7', '1--Yes', 'Iva'],
		['MM173_7', '2--No', 'Le'],
		['MM173_7', '3--DK--NA', 'L-ebda tweġiba'],
		['MM173_8', '1--Yes', 'Iva'],
		['MM173_8', '2--No', 'Le'],
		['MM173_8', '3--DK--NA', 'L-ebda tweġiba'],
		['MM175', '1--Yes', 'Iva'],
		['MM175', '2--No', 'Le'],
		['MM175', '3--DK--NA', 'L-ebda tweġiba'],
		['MM200_1', '1--Major-concern', 'Tħassib kbir'],
		['MM200_1', '2--Some-concern', 'Xi tħassib'],
		['MM200_1', '3--No-concern', 'L-ebda tħassib'],
		['MM200_1', '4--DK--NA', 'L-ebda tweġiba'],
		['MM200_2', '1--Major-concern', 'Tħassib kbir'],
		['MM200_2', '2--Some-concern', 'Xi tħassib'],
		['MM200_2', '3--No-concern', 'L-ebda tħassib'],
		['MM200_2', '4--DK--NA', 'L-ebda tweġiba'],
		['MM200_3', '1--Major-concern', 'Tħassib kbir'],
		['MM200_3', '2--Some-concern', 'Xi tħassib'],
		['MM200_3', '3--No-concern', 'L-ebda tħassib'],
		['MM200_3', '4--DK--NA', 'L-ebda tweġiba'],
		['MM200_4', '1--Major-concern', 'Tħassib kbir'],
		['MM200_4', '2--Some-concern', 'Xi tħassib'],
		['MM200_4', '3--No-concern', 'L-ebda tħassib'],
		['MM200_4', '4--DK--NA', 'L-ebda tweġiba'],
		['MM200_5', '1--Major-concern', 'Tħassib kbir'],
		['MM200_5', '2--Some-concern', 'Xi tħassib'],
		['MM200_5', '3--No-concern', 'L-ebda tħassib'],
		['MM200_5', '4--DK--NA', 'L-ebda tweġiba'],
		['MM200_6', '1--Major-concern', 'Tħassib kbir'],
		['MM200_6', '2--Some-concern', 'Xi tħassib'],
		['MM200_6', '3--No-concern', 'L-ebda tħassib'],
		['MM200_6', '4--DK--NA', 'L-ebda tweġiba'],
		['MM200_7', '1--Major-concern', 'Tħassib kbir'],
		['MM200_7', '2--Some-concern', 'Xi tħassib'],
		['MM200_7', '3--No-concern', 'L-ebda tħassib'],
		['MM200_7', '4--DK--NA', 'L-ebda tweġiba'],
		['MM202_1', '1--Yes', 'Iva'],
		['MM202_1', '2--No', 'Le'],
		['MM202_1', '3--DK--NA', 'L-ebda tweġiba'],
		['MM202_10', '1--Yes', 'Iva'],
		['MM202_10', '2--No', 'Le'],
		['MM202_10', '3--DK--NA', 'L-ebda tweġiba'],
		['MM202_2', '1--Yes', 'Iva'],
		['MM202_2', '2--No', 'Le'],
		['MM202_2', '3--DK--NA', 'L-ebda tweġiba'],
		['MM202_3', '1--Yes', 'Iva'],
		['MM202_3', '2--No', 'Le'],
		['MM202_3', '3--DK--NA', 'L-ebda tweġiba'],
		['MM202_4', '1--Yes', 'Iva'],
		['MM202_4', '2--No', 'Le'],
		['MM202_4', '3--DK--NA', 'L-ebda tweġiba'],
		['MM202_5', '1--Yes', 'Iva'],
		['MM202_5', '2--No', 'Le'],
		['MM202_5', '3--DK--NA', 'L-ebda tweġiba'],
		['MM202_6', '1--Yes', 'Iva'],
		['MM202_6', '2--No', 'Le'],
		['MM202_6', '3--DK--NA', 'L-ebda tweġiba'],
		['MM202_7', '1--Yes', 'Iva'],
		['MM202_7', '2--No', 'Le'],
		['MM202_7', '3--DK--NA', 'L-ebda tweġiba'],
		['MM202_8', '1--Yes', 'Iva'],
		['MM202_8', '2--No', 'Le'],
		['MM202_8', '3--DK--NA', 'L-ebda tweġiba'],
		['MM202_9', '1--Yes', 'Iva'],
		['MM202_9', '2--No', 'Le'],
		['MM202_9', '3--DK--NA', 'L-ebda tweġiba'],
		['MM250', '1--Yes', 'Iva'],
		['MM250', '2--No', 'Le'],
		['MM250', '3--Work-related-stress-is-not-an-issue-in-our-establishment', 'Stress relatat max-xogħol mhux kwistjoni fil-post tax-xogħol tagħna'],
		['MM250', '4--No-answer', 'L-ebda tweġiba'],
		['MM251', '1--Yes', 'Iva'],
		['MM251', '2--No', 'Le'],
		['MM251', '3--These-problems-are-not-an-issue-in-our-establishment', 'Dawn il-problemi mhumiex kwistjoni fil-post tax-xogħol tagħna'],
		['MM251', '4--No-answer', 'L-ebda tweġiba'],
		['MM252', '1--Yes', 'Iva'],
		['MM252', '2--No', 'Le'],
		['MM252', '3--Work-related-violence-is-not-an-issue-in-our-establishment', 'Il-vjolenza relatata max-xogħol ma teżistix fuq il-post tax-xogħol tagħna'],
		['MM252', '4--No-answer', 'L-ebda tweġiba'],
		['MM253_1', '1--Yes', 'Iva'],
		['MM253_1', '2--No', 'Le'],
		['MM253_1', '3--DK--NA', 'L-ebda tweġiba'],
		['MM253_2', '1--Yes', 'Iva'],
		['MM253_2', '2--No', 'Le'],
		['MM253_2', '3--DK--NA', 'L-ebda tweġiba'],
		['MM253_3', '1--Yes', 'Iva'],
		['MM253_3', '2--No', 'Le'],
		['MM253_3', '3--DK--NA', 'L-ebda tweġiba'],
		['MM253_4', '1--Yes', 'Iva'],
		['MM253_4', '2--No', 'Le'],
		['MM253_4', '3--DK--NA', 'L-ebda tweġiba'],
		['MM253_5', '1--Yes', 'Iva'],
		['MM253_5', '2--No', 'Le'],
		['MM253_5', '3--DK--NA', 'L-ebda tweġiba'],
		['MM253_6', '1--Yes', 'Iva'],
		['MM253_6', '2--No', 'Le'],
		['MM253_6', '3--DK--NA', 'L-ebda tweġiba'],
		['MM256', '1--Yes', 'Iva'],
		['MM256', '2--No', 'Le'],
		['MM256', '3--Long-or-irregular-working-hours-are-not-an-issue-in-our-esta', 'Siegħat tax-xogħol twal jew irregolari ma jeżistux fil-post tax-xogħol tagħna'],
		['MM256', '4--No-answer', 'L-ebda tweġiba'],
		['MM259', '1--Yes', 'Iva'],
		['MM259', '2--No', 'Le'],
		['MM259', '3--No-answer', 'L-ebda tweġiba'],
		['MM260', '1--Yes', 'Iva'],
		['MM260', '2--No', 'Le'],
		['MM260', '3--No-answer', 'L-ebda tweġiba'],
		['MM300', '1--More-difficult', 'Aktar diffiċli'],
		['MM300', '2--Less-difficult', 'Anqas diffiċli'],
		['MM300', '3--No-difference', 'L-ebda differenza'],
		['MM300', '4--No-answer', 'L-ebda tweġiba'],
		['MM302', '1--Yes', 'Iva'],
		['MM302', '2--No', 'Le'],
		['MM302', '3--No-answer', 'L-ebda tweġiba'],
		['MM303a', '1--Yes', 'Iva'],
		['MM303a', '2--No', 'Le'],
		['MM303a', '3--No-answer', 'L-ebda tweġiba'],
		['MM350', '1--Yes', 'Iva'],
		['MM350', '2--No', 'Le'],
		['MM350', '3--No-answer', 'L-ebda tweġiba'],
		['MM351', '1--Yes', 'Iva'],
		['MM351', '2--No', 'Le'],
		['MM351', '3--No-answer', 'L-ebda tweġiba'],
		['MM355all', '1--Yes', 'Iva'],
		['MM355all', '2--No', 'Le'],
		['MM355all', '3--No-answer', 'L-ebda tweġiba'],
		['MM358', '1--Yes', 'Iva'],
		['MM358', '2--No', 'Le'],
		['MM358', '3--No-answer', 'L-ebda tweġiba']
	];
var country_
	 = [
	
		['AT', 'L-Awstrija'],
		['BE', 'Il-Belġju'],
		['BG', 'Il-Bulgarija'],
		['CH', 'L-Isvizzera'],
		['CY', 'Ċipru'],
		['CZ', 'Ir-Repubblika Ċeka'],
		['DE', 'Il-Ġermanja'],
		['DK', 'Id-Danimarka'],
		['EE', 'L-Estonja'],
		['EL', 'Il-Greċja'],
		['ES', 'Spanja'],
		['FI', 'Il-Finlandja'],
		['FR', 'Franza'],
		['HR', 'Il-Kroazja *'],
		['HU', 'L-Ungerija'],
		['IE', 'L-Irlanda'],
		['IT', 'L-Italja'],
		['LT', 'Il-Litwanja'],
		['LU', 'Il-Lussemburgu'],
		['LV', 'Il-Latvja'],
		['MT', 'Malta'],
		['NL', 'Il-Pajjiżi l-Baxxi'],
		['NO', 'In-Norveġja'],
		['PL', 'Il-Polonja'],
		['PT', 'Il-Portugall'],
		['RO', 'Ir-Rumanija'],
		['SE', 'L-Isvezja'],
		['SI', 'Is-Slovenja'],
		['SK', 'Is-Slovakkja'],
		['TR', 'It-Turkija'],
		['UK', 'Ir-Renju Unit'],
		['EuropeanUnion', 'L-Unjoni Ewropea *']
	];
var question_meta
	 = [
	
		['MM150_1', 'Tabib fuq il-post tax-xogħol', 'X’servizzi tas-saħħa u s-sigurtà tużaw, kemm li tipprovdu intom stess (in-house) jew minn kuntrattati esterni?Tabib fuq il-post tax-xogħol'],
		['MM150_2', 'Espert tas-sigurtà', 'X’servizzi tas-saħħa u s-sigurtà tużaw, kemm li tipprovdu intom stess (in-house) jew minn kuntrattati esterni?Espert tas-sigurtà'],
		['MM150_3', 'Psikoloġista', 'X’servizzi tas-saħħa u s-sigurtà tużaw, kemm li tipprovdu intom stess (in-house) jew minn kuntrattati esterni?Psikoloġista'],
		['MM150_4', 'Espert tal-ergonomija, li jieħu ħsieb it-twaqqif tal-workstation', 'X’servizzi tas-saħħa u s-sigurtà tużaw, kemm li tipprovdu intom stess (in-house) jew minn kuntrattati esterni?Espert tal-ergonomija, li jieħu ħsieb it-twaqqif tal-workstation'],
		['MM150_5', 'Konsulenza ġenerali tas-saħħa u s-sigurtà', 'X’servizzi tas-saħħa u s-sigurtà tużaw, kemm li tipprovdu intom stess (in-house) jew minn kuntrattati esterni?Konsulenza ġenerali tas-saħħa u s-sigurtà'],
		['MM152', 'Il-post tax-xogħol tiegħek janalizza b’mod regolari l-kawżi tal-assenza minħabba mard?', 'Il-post tax-xogħol tiegħek janalizza b’mod regolari l-kawżi tal-assenza minħabba mard?'],
		['MM153', 'Tieħu miżuri sabiex tappoġġja r-ritorn fuq il-post tax-xogħol wara assenza ta’ żmien twil minħabba mard?', 'Tieħu miżuri sabiex tappoġġja r-ritorn fuq il-post tax-xogħol wara assenza ta’ żmien twil minħabba mard?'],
		['MM154', 'Is-saħħa tal-impjegati hija ssorveljata permezz ta’ eżaminazzjonijiet mediċi regolari?', 'Is-saħħa tal-impjegati hija ssorveljata permezz ta’ eżaminazzjonijiet mediċi regolari?'],
		['MM155', 'Hemm xi policy dokumentata, management system stabbilita jew pjan ta’ azzjoni dwar is-saħħa u s-sigurtà fuq il-post tax-xogħol tiegħek?', 'Hemm xi policy dokumentata, management system stabbilita jew pjan ta’ azzjoni dwar is-saħħa u s-sigurtà fuq il-post tax-xogħol tiegħek?'],
		['MM158', 'Suġġetti ta’ saħħa u sigurtà jitqajjmu f’laqgħat tal-management fuq livell għoli b’mod regolari, xi kultant jew prattikament qatt?', 'Suġġetti ta’ saħħa u sigurtà jitqajjmu f’laqgħat tal-management fuq livell għoli b’mod regolari, xi kultant jew prattikament qatt?'],
		['MM159', 'B’mod ġenerali, kif tikklassifika l-grad ta’ involviment tal-’line’ maniġers u supervisors fl-immaniġjar tas-saħħa u s-sigurtà? Huwa għoli ħafna, pjuttost għoli, pjuttost baxx jew baxx ħafna?', 'B’mod ġenerali, kif tikklassifika l-grad ta’ involviment tal-’line’ maniġers u supervisors fl-immaniġjar tas-saħħa u s-sigurtà? Huwa għoli ħafna, pjuttost għoli, pjuttost baxx jew baxx ħafna?'],
		['MM161', 'Il-postijiet ta’ ħidma fil-post tax-xogħol tiegħek huma iċċekjati regolarment għas-saħħa u s-sigurtà bħala parti minn risk assesment jew miżura simili?', 'Il-postijiet ta’ ħidma fil-post tax-xogħol tiegħek huma iċċekjati regolarment għas-saħħa u s-sigurtà bħala parti minn risk assesment jew miżura simili?'],
		['MM170', 'L-ispettorat tax-xogħol żar il-post tax-xogħol f’dawn l-aħħar 3 snin biex jiċċekkja l-kondizzjonijiet tas-saħħa u s-sigurtà?', 'L-ispettorat tax-xogħol żar il-post tax-xogħol f’dawn l-aħħar 3 snin biex jiċċekkja l-kondizzjonijiet tas-saħħa u s-sigurtà?'],
		['MM173_1', 'Istituti uffiċjali għas-saħħa u s-sigurtà fuq ix-xogħol', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?Istituti uffiċjali għas-saħħa u s-sigurtà fuq ix-xogħol'],
		['MM173_2', 'L-Aġenzija Ewropea għas-saħħa u sigurtà fuq ix-xogħol', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?L-Aġenzija Ewropea għas-saħħa u sigurtà fuq ix-xogħol'],
		['MM173_3', 'Servizzi interni (in-house) tas-saħħa u s-sigurtà', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?Servizzi interni (in-house) tas-saħħa u s-sigurtà'],
		['MM173_4', 'L-ispettorat tax-xogħol', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?L-ispettorat tax-xogħol'],
		['MM173_5', 'Organizzazzjonijiet ta’ min iħaddem', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?Organizzazzjonijiet ta’ min iħaddem'],
		['MM173_6', 'Trejdunjins', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?Trejdunjins'],
		['MM173_7', 'Esperti kuntrattati tas-saħħa u s-sigurtà', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?Esperti kuntrattati tas-saħħa u s-sigurtà'],
		['MM173_8', 'Kumpaniji tal-assigurazzjoni', 'Il-post tax-xogħol tagħkom uża informazzjoni dwar is-saħħa u sigurtà minn xi waħda minn dawn l-għaqdiet jew istituzzjonijiet li ġejjin?Kumpaniji tal-assigurazzjoni'],
		['MM175', 'Inti konxju mill-Ġimgħa Ewropea dwar is-saħħa u s-sigurtà fuq ix-xogħol?', 'Inti konxju mill-Ġimgħa Ewropea dwar is-saħħa u s-sigurtà fuq ix-xogħol?'],
		['MM200_1', 'Sustanzi perikolużi (e.ż. trabijiet, kimiċi, bioloġiċi jew radjuattivi)', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek.: Sustanzi perikolużi (e.ż. trabijiet, kimiċi, bioloġiċi jew radjuattivi)'],
		['MM200_2', 'Inċidenti', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek.: Inċidenti'],
		['MM200_3', 'Storbju u vibrazzjoni', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek.: Storbju u vibrazzjoni'],
		['MM200_4', 'Mard muskoluskeletali bħal uġiegħ fid-dahar, l-għonq, id-dirgħajn jew ir-riġlejn', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek.: Mard muskoluskeletali bħal uġiegħ fid-dahar, l-għonq, id-dirgħajn jew ir-riġlejn'],
		['MM200_5', 'Stress relatat max-xogħol', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek.: Stress relatat max-xogħol'],
		['MM200_6', 'Vjolenza jew theddida ta’ vjolenza', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek.: Vjolenza jew theddida ta’ vjolenza'],
		['MM200_7', 'Bullying jew iffastidjar i.e. Abbuż, umiljazzjoni jew attakki minn kollegi jew superjuri', 'Għal kull waħda mill-kwistjonijiet li ġejjin, jekk jogħġbok għidli jekk hijiex ta’ tħassib kbir, ta’ xi tħassib jew ta’ l-ebda tħassib fl-istabbiliment tiegħek.: Bullying jew iffastidjar i.e. Abbuż, umiljazzjoni jew attakki minn kollegi jew superjuri'],
		['MM202_1', 'Pressjoni ta’ ħin', 'Diversi fatturi jistgħu jikkontribwixxu għall-stress, vjolenza u fastidju fuq ix-xogħol; dawn jikkonċernaw il-mod kif ix-xogħol huwa organizzat u huma ta’ spiss imsejjħa ’riskji psikosoċjali’. Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek.: Pressjoni ta’ ħin'],
		['MM202_2', 'Komunikazzjoni batuta bejn il-management u l-impjegati', 'Diversi fatturi jistgħu jikkontribwixxu għall-stress, vjolenza u fastidju fuq ix-xogħol; dawn jikkonċernaw il-mod kif ix-xogħol huwa organizzat u huma ta’ spiss imsejjħa ’riskji psikosoċjali’. Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek.: Komunikazzjoni batuta bejn il-management u l-impjegati'],
		['MM202_3', 'Kooperazzjoni fqira fost il-kollegi', 'Diversi fatturi jistgħu jikkontribwixxu għall-stress, vjolenza u fastidju fuq ix-xogħol; dawn jikkonċernaw il-mod kif ix-xogħol huwa organizzat u huma ta’ spiss imsejjħa ’riskji psikosoċjali’. Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek.: Kooperazzjoni fqira fost il-kollegi'],
		['MM202_4', 'Nuqqas ta’ kontroll ta’ impjegati meta jorganizzaw ix-xogħol tagħhom', 'Diversi fatturi jistgħu jikkontribwixxu għall-stress, vjolenza u fastidju fuq ix-xogħol; dawn jikkonċernaw il-mod kif ix-xogħol huwa organizzat u huma ta’ spiss imsejjħa ’riskji psikosoċjali’. Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek.: Nuqqas ta’ kontroll ta’ impjegati meta jorganizzaw ix-xogħol tagħhom'],
		['MM202_5', 'Nuqqas ta’ sigurtà tax-xogħol', 'Diversi fatturi jistgħu jikkontribwixxu għall-stress, vjolenza u fastidju fuq ix-xogħol; dawn jikkonċernaw il-mod kif ix-xogħol huwa organizzat u huma ta’ spiss imsejjħa ’riskji psikosoċjali’. Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek.: Nuqqas ta’ sigurtà tax-xogħol'],
		['MM202_6', 'Li jkollhom jittrattaw ma’ klijenti, pazjenti, studenti eċċ diffiċli', 'Diversi fatturi jistgħu jikkontribwixxu għall-stress, vjolenza u fastidju fuq ix-xogħol; dawn jikkonċernaw il-mod kif ix-xogħol huwa organizzat u huma ta’ spiss imsejjħa ’riskji psikosoċjali’. Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek.: Li jkollhom jittrattaw ma’ klijenti, pazjenti, studenti eċċ diffiċli'],
		['MM202_7', 'Problemi fir-relazzjoni bejn is-supervisor u l-impjegat', 'Diversi fatturi jistgħu jikkontribwixxu għall-stress, vjolenza u fastidju fuq ix-xogħol; dawn jikkonċernaw il-mod kif ix-xogħol huwa organizzat u huma ta’ spiss imsejjħa ’riskji psikosoċjali’. Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek.: Problemi fir-relazzjoni bejn is-supervisor u l-impjegat'],
		['MM202_8', 'Siegħat tax-xogħol twal jew irregolari', 'Diversi fatturi jistgħu jikkontribwixxu għall-stress, vjolenza u fastidju fuq ix-xogħol; dawn jikkonċernaw il-mod kif ix-xogħol huwa organizzat u huma ta’ spiss imsejjħa ’riskji psikosoċjali’. Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek.: Siegħat tax-xogħol twal jew irregolari'],
		['MM202_9', 'Policy tar-riżorsi umani mhux ċara', 'Diversi fatturi jistgħu jikkontribwixxu għall-stress, vjolenza u fastidju fuq ix-xogħol; dawn jikkonċernaw il-mod kif ix-xogħol huwa organizzat u huma ta’ spiss imsejjħa ’riskji psikosoċjali’. Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek.: Policy tar-riżorsi umani mhux ċara'],
		['MM202_10', 'Diskriminazzjoni (per eżempju minħabba sess, età jew etniċità)', 'Diversi fatturi jistgħu jikkontribwixxu għall-stress, vjolenza u fastidju fuq ix-xogħol; dawn jikkonċernaw il-mod kif ix-xogħol huwa organizzat u huma ta’ spiss imsejjħa ’riskji psikosoċjali’. Jekk jogħġbok għidli jekk xi wieħed minn dawn ir-riskji psikosoċjali li ġejjin huma ta’ tħassib fil-post tax-xogħol tiegħek.: Diskriminazzjoni (per eżempju minħabba sess, età jew etniċità)'],
		['MM250', 'Il-post tax-xogħol tiegħek għandu proċedura sabiex jittratta ma’ stress relatat max-xogħol?', 'Il-post tax-xogħol tiegħek għandu proċedura sabiex jittratta ma’ stress relatat max-xogħol?'],
		['MM251', 'Hemm proċedura fis-seħħ sabiex titratta l-bullying jew il-fastidu?', 'Hemm proċedura fis-seħħ sabiex titratta l-bullying jew il-fastidu?'],
		['MM252', 'U għandkom proċedura li titratta l-vjolenza relatata max-xogħol?', 'U għandkom proċedura li titratta l-vjolenza relatata max-xogħol?'],
		['MM253_1', 'Tibdil fil-mod kif ix-xogħol huwa organizzat', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?Tibdil fil-mod kif ix-xogħol huwa organizzat'],
		['MM253_2', 'Disinn mill-ġdid (redesign) tal-post tax-xogħol', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?Disinn mill-ġdid (redesign) tal-post tax-xogħol'],
		['MM253_3', 'Għoti ta’ parir kunfidenzjali għall-impjegati', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?Għoti ta’ parir kunfidenzjali għall-impjegati'],
		['MM253_4', 'Twaqqif ta’ proċedura għar-riżoluzzjoni ta’ kunflitt', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?Twaqqif ta’ proċedura għar-riżoluzzjoni ta’ kunflitt'],
		['MM253_5', 'Tibdiliet fl-arranġamenti tal-ħin tax-xogħol', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?Tibdiliet fl-arranġamenti tal-ħin tax-xogħol'],
		['MM253_6', 'Għoti ta’ taħriġ', 'Fl-aħħar 3 snin, il-post tax-xogħol tiegħek għamel użu minn xi waħda minn dawn il-miżuri li ġejjin sabiex tittratta r-riskji psikosoċjali?Għoti ta’ taħriġ'],
		['MM256', 'Il-post tax-xogħol tiegħek jieħu azzjoni jekk ikun hemm impjegati individwali li jaħdmu siegħat eċċessivi li huma twal jew irregolari?', 'Il-post tax-xogħol tiegħek jieħu azzjoni jekk ikun hemm impjegati individwali li jaħdmu siegħat eċċessivi li huma twal jew irregolari?'],
		['MM259', 'Inti tinforma lill-impjegati dwar riskji psikolsoċjali u l-effett tagħhom fuq is-saħħa u sigurtà?', 'Inti tinforma lill-impjegati dwar riskji psikolsoċjali u l-effett tagħhom fuq is-saħħa u sigurtà?'],
		['MM260', 'Ġew infurmati dwar lil min għandhom jindirizzaw f’każ ta’ problemi psikosoċjali relatati max-xogħol?', 'Ġew infurmati dwar lil min għandhom jindirizzaw f’każ ta’ problemi psikosoċjali relatati max-xogħol?'],
		['MM171_1', 'Twettieq ta’ obbligu legali', 'Fil-post tax-xogħol tiegħek, kemm huma importanti r-raġunijiet li ġejjin sabiex jiġu indirizzati s-saħħa u s-sigurtà? Għal kull wieħed, jekk jogħġbok għidli jekk hijiex raġuni importanti, raġuni mhux importanti jew jekk m’humiex raġuni affattu.Twettieq ta’ obbligu legali'],
		['MM171_2', 'Talbiet minn impjegati jew ir-rappreżentanti tagħhom', 'Fil-post tax-xogħol tiegħek, kemm huma importanti r-raġunijiet li ġejjin sabiex jiġu indirizzati s-saħħa u s-sigurtà? Għal kull wieħed, jekk jogħġbok għidli jekk hijiex raġuni importanti, raġuni mhux importanti jew jekk m’humiex raġuni affattu.Talbiet minn impjegati jew ir-rappreżentanti tagħhom'],
		['MM171_3', 'Staff retention’ jew immaniġġjar ta’ assenza', 'Fil-post tax-xogħol tiegħek, kemm huma importanti r-raġunijiet li ġejjin sabiex jiġu indirizzati s-saħħa u s-sigurtà? Għal kull wieħed, jekk jogħġbok għidli jekk hijiex raġuni importanti, raġuni mhux importanti jew jekk m’humiex raġuni affattu.Staff retention’ jew immaniġġjar ta’ assenza'],
		['MM171_4', 'Raġunijiet ekonomiċi jew relatati mal-kapaċità (performance-related)', 'Fil-post tax-xogħol tiegħek, kemm huma importanti r-raġunijiet li ġejjin sabiex jiġu indirizzati s-saħħa u s-sigurtà? Għal kull wieħed, jekk jogħġbok għidli jekk hijiex raġuni importanti, raġuni mhux importanti jew jekk m’humiex raġuni affattu.Raġunijiet ekonomiċi jew relatati mal-kapaċità (performance-related)'],
		['MM171_5', 'Ħtiġijiet mill-klijenti jew tħassib dwar ir-reputazzjoni tal-organizzazzjoni', 'Fil-post tax-xogħol tiegħek, kemm huma importanti r-raġunijiet li ġejjin sabiex jiġu indirizzati s-saħħa u s-sigurtà? Għal kull wieħed, jekk jogħġbok għidli jekk hijiex raġuni importanti, raġuni mhux importanti jew jekk m’humiex raġuni affattu.Ħtiġijiet mill-klijenti jew tħassib dwar ir-reputazzjoni tal-organizzazzjoni'],
		['MM171_6', 'Pressjoni mill-ispettorat tax-xogħol', 'Fil-post tax-xogħol tiegħek, kemm huma importanti r-raġunijiet li ġejjin sabiex jiġu indirizzati s-saħħa u s-sigurtà? Għal kull wieħed, jekk jogħġbok għidli jekk hijiex raġuni importanti, raġuni mhux importanti jew jekk m’humiex raġuni affattu.Pressjoni mill-ispettorat tax-xogħol'],
		['MM172_1', 'Nuqqas ta’ riżorsi bħal ħin, staff jew flus', 'Fil-post tax-xogħol tiegħek, liema huma d-diffikultajiet prinċipali meta tittrattaw mas-saħħa u s-sigurtà? Jekk jogħġbok għidli għal kull wieħed minn dawn li ġejjin jekk hijiex diffikultà kbira, diffikultà żgħira, jew ta ebda diffikultà.Nuqqas ta’ riżorsi bħal ħin, staff jew flus'],
		['MM172_2', 'Nuqqas ta’ għarfien', 'Fil-post tax-xogħol tiegħek, liema huma d-diffikultajiet prinċipali meta tittrattaw mas-saħħa u s-sigurtà? Jekk jogħġbok għidli għal kull wieħed minn dawn li ġejjin jekk hijiex diffikultà kbira, diffikultà żgħira, jew ta’ ebda diffikultà.Nuqqas ta’ għarfien'],
		['MM172_3', 'Nuqqas ta’ kompetenza', 'Fil-post tax-xogħol tiegħek, liema huma d-diffikultajiet prinċipali meta tittrattaw mas-saħħa u s-sigurtà? Jekk jogħġbok għidli għal kull wieħed minn dawn li ġejjin jekk hijiex diffikultà kbira, diffikultà żgħira, jew ta’ ebda diffikultà.Nuqqas ta’ kompetenza'],
		['MM172_4', 'Nuqqas ta’ appoġġ tekniku jew gwida', 'Fil-post tax-xogħol tiegħek, liema huma d-diffikultajiet prinċipali meta tittrattaw mas-saħħa u s-sigurtà? Jekk jogħġbok għidli għal kull wieħed minn dawn li ġejjin jekk hijiex diffikultà kbira, diffikultà żgħira, jew ta’ ebda diffikultà.Nuqqas ta’ appoġġ tekniku jew gwida'],
		['MM172_5', 'Il-kultura fil-post tax-xogħol', 'Fil-post tax-xogħol tiegħek, liema huma d-diffikultajiet prinċipali meta tittrattaw mas-saħħa u s-sigurtà? Jekk jogħġbok għidli għal kull wieħed minn dawn li ġejjin jekk hijiex diffikultà kbira, diffikultà żgħira, jew ta’ ebda diffikultà.Il-kultura fil-post tax-xogħol'],
		['MM172_6', 'Is-sensittività tas-suġġett', 'Fil-post tax-xogħol tiegħek, liema huma d-diffikultajiet prinċipali meta tittrattaw mas-saħħa u s-sigurtà? Jekk jogħġbok għidli għal kull wieħed minn dawn li ġejjin jekk hijiex diffikultà kbira, diffikultà żgħira, jew ta’ ebda diffikultà.Is-sensittività tas-suġġett'],
		['MM300', 'Meta mqabbel ma’ suġġetti oħra ta’ saħħa u sigurtà: Huwa aktar diffiċli li tittratta riskji psikosoċjali, huwa inqas diffiċli, jew ma hemmx differenza?', 'Meta mqabbel ma’ suġġetti oħra ta’ saħħa u sigurtà: Huwa aktar diffiċli li tittratta riskji psikosoċjali, huwa inqas diffiċli, jew ma hemmx differenza?'],
		['MM302', 'Inti użajt informazzjoni jew appoġġ minn sorsi esterni dwar kif titratta ma’ riskji psikosoċjali fuq ix-xogħol?', 'Inti użajt informazzjoni jew appoġġ minn sorsi esterni dwar kif titratta ma’ riskji psikosoċjali fuq ix-xogħol?'],
		['MM303a', 'Għandek bżonn xi informazzjoni oħra dwar dan is-suġġett?', 'Għandek bżonn xi informazzjoni oħra dwar dan is-suġġett?<br><br>Mistoqsijiet li saru lil dawk l-istabbilimenti li jirrapportaw li jużaw informazzjoni jew appoġġ minn sorsi esterni dwar kif jiġu indirizzati riskji psikosoċjali fuq il-post tax-xogħol.'],
		['MM350', 'F’dan l-istabbiliment għandkom kunsill tax-xogħlijiet?', 'F’dan l-istabbiliment għandkom kunsill tax-xogħlijiet?'],
		['MM351', 'U hemm rappreżentant rikonoxxut tal-unjin fil-post tax-xogħol tiegħek?', 'U hemm rappreżentant rikonoxxut tal-unjin fil-post tax-xogħol tiegħek?'],
		['MM355all', 'Il-post tax-xogħol tiegħek għandu rappreżentant intern tas-saħħa u s-sigurtà?', 'Il-post tax-xogħol tiegħek għandu rappreżentant intern tas-saħħa u s-sigurtà?<br><br>NL: F’dan l-istabbiliment, hemm membru tar-rappreżentant tas-saħħa u s-sigurtà?'],
		['MM358', 'Hemm kumitat tas-saħħa u s-sigurtà fl-istabbiliment tiegħek?', 'Hemm kumitat tas-saħħa u s-sigurtà fl-istabbiliment tiegħek?']
	];
