//Auto Generated file
var subset_
	 = [
	
		['sec3', 'Sektor działalności'],
		['size_4', 'Wielkość zakładu pracy']
	];
var subset_subsetValue
	 = [
	
		['sec3', 'All', 'Wszystkie'],
		['sec3', '1--Producing-Industries', 'Sektor produkcyjny'],
		['sec3', '2--Private-Services', 'Usługi prywante'],
		['sec3', '3--Public-Services', 'Usługi publiczne'],
		['size_4', 'All', 'Wszystkie'],
		['size_4', '1--10-to-19-employees', '10-19 pracowników'],
		['size_4', '2--20-to-49-employees', '20-49 pracowników'],
		['size_4', '3--50-to-249-employees', '50-249 pracowników'],
		['size_4', '4--250-employees-or-more', '250 lub więcej pracowników']
	];
var topic_
	 = [
	
		['', 'Wszystkie (70)'],
		['Czynniki motywujące i bariery', 'Czynniki motywujące i bariery (15)'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Ryzyko psychospołeczne i zarządzanie nim (22)'],
		['Udział pracowników', 'Udział pracowników (4)'],
		['Zarządzanie BHP', 'Zarządzanie BHP (29)']
	];
var topic_question
	 = [
	
		['Zarządzanie BHP', 'MM150_1', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: lekarz medycyny pracy'],
		['Zarządzanie BHP', 'MM150_2', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: specjalista ds. bezpieczeństwa'],
		['Zarządzanie BHP', 'MM150_3', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: psycholog'],
		['Zarządzanie BHP', 'MM150_4', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: specjalista ds. ergonomii zajmujący się organizacją stanowiska pracy'],
		['Zarządzanie BHP', 'MM150_5', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: ogólne konsultacje w zakresie zdrowia i bezpieczeństwa'],
		['Zarządzanie BHP', 'MM152', 'Czy Pana(i) oddział rutynowo analizuje przyczyny absencji chorobowej?'],
		['Zarządzanie BHP', 'MM153', 'Czy oddział podejmuje kroki wspierające powrót pracowników do pracy po długiej chorobie?'],
		['Zarządzanie BHP', 'MM154', 'Czy zdrowie pracowników jest monitorowane przez regularne badania zdrowotne?'],
		['Zarządzanie BHP', 'MM155', 'Czy w Pana(i) oddziale istnieje udokumentowana polityka, przyjęty system zarządzania lub plan działania w zakresie zdrowia i bezpieczeństwa w pracy?'],
		['Zarządzanie BHP', 'MM158', 'Czy kwestie zdrowia i bezpieczeństwa są omawiane na spotkaniach kadry kierowniczej wysokiego szczebla regularnie, czasami czy praktycznie w ogóle nie są omawiane?'],
		['Zarządzanie BHP', 'MM159', 'Ogólnie rzecz biorąc, jak ocenił(a)by Pan(i) stopień zaangażowania kierowników liniowych i przełożonych w zarządzanie sprawami bezpieczeństwa i zdrowia w pracy? Czy jest ono bardzo wysokie, dość wysokie, dość niskie czy bardzo niskie?'],
		['Zarządzanie BHP', 'MM161', 'Czy stanowiska pracy w Pana(i) oddziale są regularnie kontrolowane pod kątem bezpieczeństwa i zdrowia w pracy jako element oceny ryzyka lub w ramach podobnych działań?'],
		['Zarządzanie BHP', 'MM170', 'Czy w ciągu ostatnich 3 lat Państwowa Inspekcja Pracy odwiedziła ten oddział w celu skontrolowania warunków bezpieczeństwa i zdrowia?'],
		['Zarządzanie BHP', 'MM173_1', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: Instytuty ds. bezpieczeństwa i higieny w pracy'],
		['Zarządzanie BHP', 'MM173_2', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: Europejska Agencja Bezpieczeństwa i Zdrowia w Pracy'],
		['Zarządzanie BHP', 'MM173_3', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: wewnętrzne służby ds. bezpieczeństwa i zdrowia w pracy'],
		['Zarządzanie BHP', 'MM173_4', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: Państwowa Inspekcja Pracy'],
		['Zarządzanie BHP', 'MM173_5', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: organizacje pracodawców'],
		['Zarządzanie BHP', 'MM173_6', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: Związki zawodowe'],
		['Zarządzanie BHP', 'MM173_7', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: Zewnętrzni specjaliści ds. bezpieczeństwa i zdrowia pracy'],
		['Zarządzanie BHP', 'MM173_8', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: Ubezpieczyciele'],
		['Zarządzanie BHP', 'MM175', 'Czy słyszał Pan(i) o Europejskim Tygodniu bezpieczeństwa i zdrowia w pracy?'],
		['Zarządzanie BHP', 'MM200_1', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.: Niebezpieczne substancje (np. pyły, substancje chemiczne, biologiczne lub radioaktywne)'],
		['Zarządzanie BHP', 'MM200_2', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.: Wypadki'],
		['Zarządzanie BHP', 'MM200_3', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.: Hałas i wibracje'],
		['Zarządzanie BHP', 'MM200_4', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.: Uszkodzenia układu mięśniowo-szkieletowego, np. ból kręgosłupa, szyi, ramion lub nóg'],
		['Zarządzanie BHP', 'MM200_5', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.: Stres związany z pracą'],
		['Zarządzanie BHP', 'MM200_6', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.: Przemoc lub zagrożenie przemocą'],
		['Zarządzanie BHP', 'MM200_7', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.: Mobbing lub prześladowanie, tj. znęcanie się, poniżanie lub agresja ze strony współpracowników lub przełożonych'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM202_1', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Presja czasu'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM202_2', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Słaba komunikacja pomiędzy kadrą kierowniczą a pracownikami'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM202_3', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Słaba współpraca między współpracownikami'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM202_4', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Brak kontroli pracowników nad organizacją swojej pracy'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM202_5', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Niepewność pracy'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM202_6', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Konieczność kontaktów z trudnymi klientami, pacjentami, uczniami itp.'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM202_7', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Problemy w relacjach przełożony - podwładny'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM202_8', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Długie lub nieregularne godziny pracy'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM202_9', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Niejasna polityka kadrowa'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM202_10', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Dyskryminacja (na przykład ze względu na płeć, wiek lub pochodzenie etniczne)'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM250', 'Czy w Pana(i) oddziale istnieją procedury postępowania ze stresem związanym z pracą?'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM251', 'Czy istnieje procedura postępowania z mobbingiem lub prześladowaniem?'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM252', 'Czy istnieje procedura postępowania z przemocą w miejscu pracy?'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM253_1', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?: Zmiany sposobu organizacji pracy'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM253_2', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?: Zmiana aranżacji miejsca pracy'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM253_3', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?: Poufne konsultacje dla pracowników'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM253_4', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?: Wprowadzenie procedury rozwiązywania konfliktów'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM253_5', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?: Zmiany w organizacji czasu pracy'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM253_6', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?: Zapewnienie szkoleń'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM256', 'Czy Pana(i) oddział podejmuje działania, jeżeli poszczególni pracownicy pracują zbyt długo lub mają nieregularne godziny pracy?'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM259', 'Czy informuje Pan(i) pracowników o czynnikach ryzyka psychospołecznego i ich wpływie na zdrowie i bezpieczeństwo?'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'MM260', 'Czy pracownicy zostali poinformowani, do kogo mogą się zwrócić z problemami psychospołecznymi związanymi z pracą?'],
		['Czynniki motywujące i bariery', 'MM171_1', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Spełnienie wymogów prawnych'],
		['Czynniki motywujące i bariery', 'MM171_2', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Żądania ze strony pracowników lub ich przedstawicieli'],
		['Czynniki motywujące i bariery', 'MM171_3', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: zapobieganie odchodzeniu pracowników i zarządzanie absencjami'],
		['Czynniki motywujące i bariery', 'MM171_4', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: przyczyny ekonomiczne lub związane z jakością wykonania pracy'],
		['Czynniki motywujące i bariery', 'MM171_5', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Wymagania klientów lub troska o reputację przedsiębiorstwa'],
		['Czynniki motywujące i bariery', 'MM171_6', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Naciski ze strony Państwowej Inspekcji Pracy'],
		['Czynniki motywujące i bariery', 'MM172_1', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: brak takich zasobów, jak czas, personel czy środki pieniężne'],
		['Czynniki motywujące i bariery', 'MM172_2', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: nieświadomość'],
		['Czynniki motywujące i bariery', 'MM172_3', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: brak wiedzy'],
		['Czynniki motywujące i bariery', 'MM172_4', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: brak wsparcia technicznego lub wskazówek'],
		['Czynniki motywujące i bariery', 'MM172_5', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: kultura organizacji'],
		['Czynniki motywujące i bariery', 'MM172_6', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: ta kwestia jest delikatna'],
		['Czynniki motywujące i bariery', 'MM300', 'W porównaniu z innymi zagadnieniami z zakresu bezpieczeństwa i higieny pracy - czy zajmowanie się ryzykiem psychospołecznym jest trudniejsze, łatwiejsze czy nie ma różnicy?'],
		['Czynniki motywujące i bariery', 'MM302', 'Czy korzystał(a) Pana(i) z informacji lub wsparcia z zewnętrznych źródeł na temat postępowania z ryzykiem psychospołecznym w pracy?'],
		['Czynniki motywujące i bariery', 'MM303a', 'Czy potrzebne byłyby Panu(i) dodatkowe informacje lub wsparcie w tym zakresie?'],
		['Udział pracowników', 'MM350', 'Czy w Pana(i) oddziale istnieje rada pracowników?'],
		['Udział pracowników', 'MM351', 'Czy w Pana(i) oddziale istnieje zakładowa organizacja związkowa?'],
		['Udział pracowników', 'MM355all', 'Czy Pana(i) oddział ma wewnętrznego społecznego inspektora pracy?'],
		['Udział pracowników', 'MM358', 'Czy w Pana(i) oddziale jest komisja BHP?']
	];
var question_
	 = [
	
		['MM150_1', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: lekarz medycyny pracy'],
		['MM150_2', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: specjalista ds. bezpieczeństwa'],
		['MM150_3', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: psycholog'],
		['MM150_4', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: specjalista ds. ergonomii zajmujący się organizacją stanowiska pracy'],
		['MM150_5', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: ogólne konsultacje w zakresie zdrowia i bezpieczeństwa'],
		['MM152', 'Czy Pana(i) oddział rutynowo analizuje przyczyny absencji chorobowej?'],
		['MM153', 'Czy oddział podejmuje kroki wspierające powrót pracowników do pracy po długiej chorobie?'],
		['MM154', 'Czy zdrowie pracowników jest monitorowane przez regularne badania zdrowotne?'],
		['MM155', 'Czy w Pana(i) oddziale istnieje udokumentowana polityka, przyjęty system zarządzania lub plan działania w zakresie zdrowia i bezpieczeństwa w pracy?'],
		['MM158', 'Czy kwestie zdrowia i bezpieczeństwa są omawiane na spotkaniach kadry kierowniczej wysokiego szczebla regularnie, czasami czy praktycznie w ogóle nie są omawiane?'],
		['MM159', 'Ogólnie rzecz biorąc, jak ocenił(a)by Pan(i) stopień zaangażowania kierowników liniowych i przełożonych w zarządzanie sprawami bezpieczeństwa i zdrowia w pracy? Czy jest ono bardzo wysokie, dość wysokie, dość niskie czy bardzo niskie?'],
		['MM161', 'Czy stanowiska pracy w Pana(i) oddziale są regularnie kontrolowane pod kątem bezpieczeństwa i zdrowia w pracy jako element oceny ryzyka lub w ramach podobnych działań?'],
		['MM170', 'Czy w ciągu ostatnich 3 lat Państwowa Inspekcja Pracy odwiedziła ten oddział w celu skontrolowania warunków bezpieczeństwa i zdrowia?'],
		['MM173_1', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: Instytuty ds. bezpieczeństwa i higieny w pracy'],
		['MM173_2', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: Europejska Agencja Bezpieczeństwa i Zdrowia w Pracy'],
		['MM173_3', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: wewnętrzne służby ds. bezpieczeństwa i zdrowia w pracy'],
		['MM173_4', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: Państwowa Inspekcja Pracy'],
		['MM173_5', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: organizacje pracodawców'],
		['MM173_6', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: Związki zawodowe'],
		['MM173_7', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: Zewnętrzni specjaliści ds. bezpieczeństwa i zdrowia pracy'],
		['MM173_8', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?: Ubezpieczyciele'],
		['MM175', 'Czy słyszał Pan(i) o Europejskim Tygodniu bezpieczeństwa i zdrowia w pracy?'],
		['MM200_1', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.: Niebezpieczne substancje (np. pyły, substancje chemiczne, biologiczne lub radioaktywne)'],
		['MM200_2', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.: Wypadki'],
		['MM200_3', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.: Hałas i wibracje'],
		['MM200_4', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.: Uszkodzenia układu mięśniowo-szkieletowego, np. ból kręgosłupa, szyi, ramion lub nóg'],
		['MM200_5', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.: Stres związany z pracą'],
		['MM200_6', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.: Przemoc lub zagrożenie przemocą'],
		['MM200_7', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.: Mobbing lub prześladowanie, tj. znęcanie się, poniżanie lub agresja ze strony współpracowników lub przełożonych'],
		['MM202_1', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Presja czasu'],
		['MM202_2', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Słaba komunikacja pomiędzy kadrą kierowniczą a pracownikami'],
		['MM202_3', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Słaba współpraca między współpracownikami'],
		['MM202_4', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Brak kontroli pracowników nad organizacją swojej pracy'],
		['MM202_5', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Niepewność pracy'],
		['MM202_6', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Konieczność kontaktów z trudnymi klientami, pacjentami, uczniami itp.'],
		['MM202_7', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Problemy w relacjach przełożony - podwładny'],
		['MM202_8', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Długie lub nieregularne godziny pracy'],
		['MM202_9', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Niejasna polityka kadrowa'],
		['MM202_10', 'Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.: Dyskryminacja (na przykład ze względu na płeć, wiek lub pochodzenie etniczne)'],
		['MM250', 'Czy w Pana(i) oddziale istnieją procedury postępowania ze stresem związanym z pracą?'],
		['MM251', 'Czy istnieje procedura postępowania z mobbingiem lub prześladowaniem?'],
		['MM252', 'Czy istnieje procedura postępowania z przemocą w miejscu pracy?'],
		['MM253_1', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?: Zmiany sposobu organizacji pracy'],
		['MM253_2', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?: Zmiana aranżacji miejsca pracy'],
		['MM253_3', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?: Poufne konsultacje dla pracowników'],
		['MM253_4', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?: Wprowadzenie procedury rozwiązywania konfliktów'],
		['MM253_5', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?: Zmiany w organizacji czasu pracy'],
		['MM253_6', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?: Zapewnienie szkoleń'],
		['MM256', 'Czy Pana(i) oddział podejmuje działania, jeżeli poszczególni pracownicy pracują zbyt długo lub mają nieregularne godziny pracy?'],
		['MM259', 'Czy informuje Pan(i) pracowników o czynnikach ryzyka psychospołecznego i ich wpływie na zdrowie i bezpieczeństwo?'],
		['MM260', 'Czy pracownicy zostali poinformowani, do kogo mogą się zwrócić z problemami psychospołecznymi związanymi z pracą?'],
		['MM171_1', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Spełnienie wymogów prawnych'],
		['MM171_2', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Żądania ze strony pracowników lub ich przedstawicieli'],
		['MM171_3', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: zapobieganie odchodzeniu pracowników i zarządzanie absencjami'],
		['MM171_4', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: przyczyny ekonomiczne lub związane z jakością wykonania pracy'],
		['MM171_5', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Wymagania klientów lub troska o reputację przedsiębiorstwa'],
		['MM171_6', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Naciski ze strony Państwowej Inspekcji Pracy'],
		['MM172_1', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: brak takich zasobów, jak czas, personel czy środki pieniężne'],
		['MM172_2', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: nieświadomość'],
		['MM172_3', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: brak wiedzy'],
		['MM172_4', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: brak wsparcia technicznego lub wskazówek'],
		['MM172_5', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: kultura organizacji'],
		['MM172_6', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: ta kwestia jest delikatna'],
		['MM300', 'W porównaniu z innymi zagadnieniami z zakresu bezpieczeństwa i higieny pracy - czy zajmowanie się ryzykiem psychospołecznym jest trudniejsze, łatwiejsze czy nie ma różnicy?'],
		['MM302', 'Czy korzystał(a) Pana(i) z informacji lub wsparcia z zewnętrznych źródeł na temat postępowania z ryzykiem psychospołecznym w pracy?'],
		['MM303a', 'Czy potrzebne byłyby Panu(i) dodatkowe informacje lub wsparcie w tym zakresie?'],
		['MM350', 'Czy w Pana(i) oddziale istnieje rada pracowników?'],
		['MM351', 'Czy w Pana(i) oddziale istnieje zakładowa organizacja związkowa?'],
		['MM355all', 'Czy Pana(i) oddział ma wewnętrznego społecznego inspektora pracy?'],
		['MM358', 'Czy w Pana(i) oddziale jest komisja BHP?']
	];
var question_answer
	 = [
	
		['MM150_1', '1--Yes', 'Tak'],
		['MM150_1', '2--No', 'Nie'],
		['MM150_1', '3--DK--NA', 'Brak odpowiedzi'],
		['MM150_2', '1--Yes', 'Tak'],
		['MM150_2', '2--No', 'Nie'],
		['MM150_2', '3--DK--NA', 'Brak odpowiedzi'],
		['MM150_3', '1--Yes', 'Tak'],
		['MM150_3', '2--No', 'Nie'],
		['MM150_3', '3--DK--NA', 'Brak odpowiedzi'],
		['MM150_4', '1--Yes', 'Tak'],
		['MM150_4', '2--No', 'Nie'],
		['MM150_4', '3--DK--NA', 'Brak odpowiedzi'],
		['MM150_5', '1--Yes', 'Tak'],
		['MM150_5', '2--No', 'Nie'],
		['MM150_5', '3--DK--NA', 'Brak odpowiedzi'],
		['MM152', '1--Yes', 'Tak'],
		['MM152', '2--No', 'Nie'],
		['MM152', '3--DK--NA', 'Brak odpowiedzi'],
		['MM153', '1--Yes', 'Tak'],
		['MM153', '2--No', 'Nie'],
		['MM153', '3--DK--NA', 'Brak odpowiedzi'],
		['MM154', '1--Yes', 'Tak'],
		['MM154', '2--No', 'Nie'],
		['MM154', '3--DK--NA', 'Brak odpowiedzi'],
		['MM155', '1--Yes', 'Tak'],
		['MM155', '2--No', 'Nie'],
		['MM155', '3--DK--NA', 'Brak odpowiedzi'],
		['MM158', '1--Regularly', 'Regularnie'],
		['MM158', '2--Occasionally', 'czasami'],
		['MM158', '3--Practically-never', 'Praktycznie nigdy'],
		['MM158', '4--DK--NA', 'Brak odpowiedzi'],
		['MM159', '1--Very-high', 'Bardzo wysokie'],
		['MM159', '2--Quite-high', 'Dość wysokie'],
		['MM159', '3--Quite-low', 'Dość niskie'],
		['MM159', '4--Very-low', 'Bardzo niskie'],
		['MM159', '5--DK--NA', 'Brak odpowiedzi'],
		['MM161', '1--Yes', 'Tak'],
		['MM161', '2--No', 'Nie'],
		['MM161', '3--DK--NA', 'Brak odpowiedzi'],
		['MM170', '1--Yes', 'Tak'],
		['MM170', '2--No', 'Nie'],
		['MM170', '3--DK--NA', 'Brak odpowiedzi'],
		['MM171_1', '1--Major', 'Duża'],
		['MM171_1', '2--Minor', 'Mała '],
		['MM171_1', '3--No', 'Żadna'],
		['MM171_1', '4--DK--NA', 'Brak odpowiedzi'],
		['MM171_2', '1--Major', 'Duża'],
		['MM171_2', '2--Minor', 'Mała '],
		['MM171_2', '3--No', 'Żadna'],
		['MM171_2', '4--DK--NA', 'Brak odpowiedzi'],
		['MM171_3', '1--Major', 'Duża'],
		['MM171_3', '2--Minor', 'Mała '],
		['MM171_3', '3--No', 'Żadna'],
		['MM171_3', '4--DK--NA', 'Brak odpowiedzi'],
		['MM171_4', '1--Major', 'Duża'],
		['MM171_4', '2--Minor', 'Mała '],
		['MM171_4', '3--No', 'Żadna'],
		['MM171_4', '4--DK--NA', 'Brak odpowiedzi'],
		['MM171_5', '1--Major', 'Duża'],
		['MM171_5', '2--Minor', 'Mała '],
		['MM171_5', '3--No', 'Żadna'],
		['MM171_5', '4--DK--NA', 'Brak odpowiedzi'],
		['MM171_6', '1--Major', 'Duża'],
		['MM171_6', '2--Minor', 'Mała '],
		['MM171_6', '3--No', 'Żadna'],
		['MM171_6', '4--DK--NA', 'Brak odpowiedzi'],
		['MM172_1', '1--Major', 'Istotna '],
		['MM172_1', '2--Minor', 'Mało istotna'],
		['MM172_1', '3--No', 'Żadna'],
		['MM172_1', '4--DK--NA', 'Brak odpowiedzi'],
		['MM172_2', '1--Major', 'Istotna '],
		['MM172_2', '2--Minor', 'Mało istotna'],
		['MM172_2', '3--No', 'Żadna'],
		['MM172_2', '4--DK--NA', 'Brak odpowiedzi'],
		['MM172_3', '1--Major', 'Istotna '],
		['MM172_3', '2--Minor', 'Mało istotna'],
		['MM172_3', '3--No', 'Żadna'],
		['MM172_3', '4--DK--NA', 'Brak odpowiedzi'],
		['MM172_4', '1--Major', 'Istotna '],
		['MM172_4', '2--Minor', 'Mało istotna'],
		['MM172_4', '3--No', 'Żadna'],
		['MM172_4', '4--DK--NA', 'Brak odpowiedzi'],
		['MM172_5', '1--Major', 'Istotna '],
		['MM172_5', '2--Minor', 'Mało istotna'],
		['MM172_5', '3--No', 'Żadna'],
		['MM172_5', '4--DK--NA', 'Brak odpowiedzi'],
		['MM172_6', '1--Major', 'Istotna '],
		['MM172_6', '2--Minor', 'Mało istotna'],
		['MM172_6', '3--No', 'Żadna'],
		['MM172_6', '4--DK--NA', 'Brak odpowiedzi'],
		['MM173_1', '1--Yes', 'Tak'],
		['MM173_1', '2--No', 'Nie'],
		['MM173_1', '3--DK--NA', 'Brak odpowiedzi'],
		['MM173_2', '1--Yes', 'Tak'],
		['MM173_2', '2--No', 'Nie'],
		['MM173_2', '3--DK--NA', 'Brak odpowiedzi'],
		['MM173_3', '1--Yes', 'Tak'],
		['MM173_3', '2--No', 'Nie'],
		['MM173_3', '3--DK--NA', 'Brak odpowiedzi'],
		['MM173_4', '1--Yes', 'Tak'],
		['MM173_4', '2--No', 'Nie'],
		['MM173_4', '3--DK--NA', 'Brak odpowiedzi'],
		['MM173_5', '1--Yes', 'Tak'],
		['MM173_5', '2--No', 'Nie'],
		['MM173_5', '3--DK--NA', 'Brak odpowiedzi'],
		['MM173_6', '1--Yes', 'Tak'],
		['MM173_6', '2--No', 'Nie'],
		['MM173_6', '3--DK--NA', 'Brak odpowiedzi'],
		['MM173_7', '1--Yes', 'Tak'],
		['MM173_7', '2--No', 'Nie'],
		['MM173_7', '3--DK--NA', 'Brak odpowiedzi'],
		['MM173_8', '1--Yes', 'Tak'],
		['MM173_8', '2--No', 'Nie'],
		['MM173_8', '3--DK--NA', 'Brak odpowiedzi'],
		['MM175', '1--Yes', 'Tak'],
		['MM175', '2--No', 'Nie'],
		['MM175', '3--DK--NA', 'Brak odpowiedzi'],
		['MM200_1', '1--Major-concern', 'Ważna kwestia'],
		['MM200_1', '2--Some-concern', 'Mało ważna kwestia'],
		['MM200_1', '3--No-concern', 'Żadna kwestia'],
		['MM200_1', '4--DK--NA', 'Brak odpowiedzi'],
		['MM200_2', '1--Major-concern', 'Ważna kwestia'],
		['MM200_2', '2--Some-concern', 'Mało ważna kwestia'],
		['MM200_2', '3--No-concern', 'Żadna kwestia'],
		['MM200_2', '4--DK--NA', 'Brak odpowiedzi'],
		['MM200_3', '1--Major-concern', 'Ważna kwestia'],
		['MM200_3', '2--Some-concern', 'Mało ważna kwestia'],
		['MM200_3', '3--No-concern', 'Żadna kwestia'],
		['MM200_3', '4--DK--NA', 'Brak odpowiedzi'],
		['MM200_4', '1--Major-concern', 'Ważna kwestia'],
		['MM200_4', '2--Some-concern', 'Mało ważna kwestia'],
		['MM200_4', '3--No-concern', 'Żadna kwestia'],
		['MM200_4', '4--DK--NA', 'Brak odpowiedzi'],
		['MM200_5', '1--Major-concern', 'Ważna kwestia'],
		['MM200_5', '2--Some-concern', 'Mało ważna kwestia'],
		['MM200_5', '3--No-concern', 'Żadna kwestia'],
		['MM200_5', '4--DK--NA', 'Brak odpowiedzi'],
		['MM200_6', '1--Major-concern', 'Ważna kwestia'],
		['MM200_6', '2--Some-concern', 'Mało ważna kwestia'],
		['MM200_6', '3--No-concern', 'Żadna kwestia'],
		['MM200_6', '4--DK--NA', 'Brak odpowiedzi'],
		['MM200_7', '1--Major-concern', 'Ważna kwestia'],
		['MM200_7', '2--Some-concern', 'Mało ważna kwestia'],
		['MM200_7', '3--No-concern', 'Żadna kwestia'],
		['MM200_7', '4--DK--NA', 'Brak odpowiedzi'],
		['MM202_1', '1--Yes', 'Tak'],
		['MM202_1', '2--No', 'Nie'],
		['MM202_1', '3--DK--NA', 'Brak odpowiedzi'],
		['MM202_10', '1--Yes', 'Tak'],
		['MM202_10', '2--No', 'Nie'],
		['MM202_10', '3--DK--NA', 'Brak odpowiedzi'],
		['MM202_2', '1--Yes', 'Tak'],
		['MM202_2', '2--No', 'Nie'],
		['MM202_2', '3--DK--NA', 'Brak odpowiedzi'],
		['MM202_3', '1--Yes', 'Tak'],
		['MM202_3', '2--No', 'Nie'],
		['MM202_3', '3--DK--NA', 'Brak odpowiedzi'],
		['MM202_4', '1--Yes', 'Tak'],
		['MM202_4', '2--No', 'Nie'],
		['MM202_4', '3--DK--NA', 'Brak odpowiedzi'],
		['MM202_5', '1--Yes', 'Tak'],
		['MM202_5', '2--No', 'Nie'],
		['MM202_5', '3--DK--NA', 'Brak odpowiedzi'],
		['MM202_6', '1--Yes', 'Tak'],
		['MM202_6', '2--No', 'Nie'],
		['MM202_6', '3--DK--NA', 'Brak odpowiedzi'],
		['MM202_7', '1--Yes', 'Tak'],
		['MM202_7', '2--No', 'Nie'],
		['MM202_7', '3--DK--NA', 'Brak odpowiedzi'],
		['MM202_8', '1--Yes', 'Tak'],
		['MM202_8', '2--No', 'Nie'],
		['MM202_8', '3--DK--NA', 'Brak odpowiedzi'],
		['MM202_9', '1--Yes', 'Tak'],
		['MM202_9', '2--No', 'Nie'],
		['MM202_9', '3--DK--NA', 'Brak odpowiedzi'],
		['MM250', '1--Yes', 'Tak'],
		['MM250', '2--No', 'Nie'],
		['MM250', '3--Work-related-stress-is-not-an-issue-in-our-establishment', 'W naszym oddziale stres związany z pracą nie stanowi problemu'],
		['MM250', '4--No-answer', 'Brak odpowiedzi'],
		['MM251', '1--Yes', 'Tak'],
		['MM251', '2--No', 'Nie'],
		['MM251', '3--These-problems-are-not-an-issue-in-our-establishment', 'W naszym oddziale nie stanowi to problemu'],
		['MM251', '4--No-answer', 'Brak odpowiedzi'],
		['MM252', '1--Yes', 'Tak'],
		['MM252', '2--No', 'Nie'],
		['MM252', '3--Work-related-violence-is-not-an-issue-in-our-establishment', 'W naszym oddziale przemoc w miejscu pracy nie stanowi problemu'],
		['MM252', '4--No-answer', 'Brak odpowiedzi'],
		['MM253_1', '1--Yes', 'Tak'],
		['MM253_1', '2--No', 'Nie'],
		['MM253_1', '3--DK--NA', 'Brak odpowiedzi'],
		['MM253_2', '1--Yes', 'Tak'],
		['MM253_2', '2--No', 'Nie'],
		['MM253_2', '3--DK--NA', 'Brak odpowiedzi'],
		['MM253_3', '1--Yes', 'Tak'],
		['MM253_3', '2--No', 'Nie'],
		['MM253_3', '3--DK--NA', 'Brak odpowiedzi'],
		['MM253_4', '1--Yes', 'Tak'],
		['MM253_4', '2--No', 'Nie'],
		['MM253_4', '3--DK--NA', 'Brak odpowiedzi'],
		['MM253_5', '1--Yes', 'Tak'],
		['MM253_5', '2--No', 'Nie'],
		['MM253_5', '3--DK--NA', 'Brak odpowiedzi'],
		['MM253_6', '1--Yes', 'Tak'],
		['MM253_6', '2--No', 'Nie'],
		['MM253_6', '3--DK--NA', 'Brak odpowiedzi'],
		['MM256', '1--Yes', 'Tak'],
		['MM256', '2--No', 'Nie'],
		['MM256', '3--Long-or-irregular-working-hours-are-not-an-issue-in-our-esta', 'Długie lub nieregularne godziny pracy nie stanowią problemu w naszym oddziale'],
		['MM256', '4--No-answer', 'Brak odpowiedzi'],
		['MM259', '1--Yes', 'Tak'],
		['MM259', '2--No', 'Nie'],
		['MM259', '3--No-answer', 'Brak odpowiedzi'],
		['MM260', '1--Yes', 'Tak'],
		['MM260', '2--No', 'Nie'],
		['MM260', '3--No-answer', 'Brak odpowiedzi'],
		['MM300', '1--More-difficult', 'trudniejsze'],
		['MM300', '2--Less-difficult', 'łatwiejsze'],
		['MM300', '3--No-difference', 'nie ma różnicy'],
		['MM300', '4--No-answer', 'Brak odpowiedzi'],
		['MM302', '1--Yes', 'Tak'],
		['MM302', '2--No', 'Nie'],
		['MM302', '3--No-answer', 'Brak odpowiedzi'],
		['MM303a', '1--Yes', 'Tak'],
		['MM303a', '2--No', 'Nie'],
		['MM303a', '3--No-answer', 'Brak odpowiedzi'],
		['MM350', '1--Yes', 'Tak'],
		['MM350', '2--No', 'Nie'],
		['MM350', '3--No-answer', 'Brak odpowiedzi'],
		['MM351', '1--Yes', 'Tak'],
		['MM351', '2--No', 'Nie'],
		['MM351', '3--No-answer', 'Brak odpowiedzi'],
		['MM355all', '1--Yes', 'Tak'],
		['MM355all', '2--No', 'Nie'],
		['MM355all', '3--No-answer', 'Brak odpowiedzi'],
		['MM358', '1--Yes', 'Tak'],
		['MM358', '2--No', 'Nie'],
		['MM358', '3--No-answer', 'Brak odpowiedzi']
	];
var country_
	 = [
	
		['AT', 'Austria'],
		['BE', 'Belgia'],
		['BG', 'Bułgaria'],
		['CH', 'Szwajcaria'],
		['CY', 'Cypr'],
		['CZ', 'Republika Czeska'],
		['DE', 'Niemcy'],
		['DK', 'Dania'],
		['EE', 'Estonia'],
		['EL', 'Grecja'],
		['ES', 'Hiszpania'],
		['FI', 'Finlandia'],
		['FR', 'Francja'],
		['HR', 'Chorwacja *'],
		['HU', 'Węgry'],
		['IE', 'Irlandia'],
		['IT', 'Włochy'],
		['LT', 'Litwa'],
		['LU', 'Luksemburg'],
		['LV', 'Łotwa'],
		['MT', 'Malta'],
		['NL', 'Holandia'],
		['NO', 'Norwegia'],
		['PL', 'Polska'],
		['PT', 'Portugalia'],
		['RO', 'Rumunia'],
		['SE', 'Szwecja'],
		['SI', 'Słowenia'],
		['SK', 'Słowacja'],
		['TR', 'Turcja'],
		['UK', 'Zjednoczone Królestwo'],
		['EuropeanUnion', 'Unia Europejska *']
	];
var question_meta
	 = [
	
		['MM150_1', 'lekarz medycyny pracy', 'Jakie wewnątrzzakładowe lub zewnętrzne służby w zakresie zdrowia i bezpieczeństwa pracy Pan(i) wykorzystuje?lekarz medycyny pracy'],
		['MM150_2', 'specjalista ds. bezpieczeństwa', 'Jakie wewnątrzzakładowe lub zewnętrzne służby w zakresie zdrowia i bezpieczeństwa pracy Pan(i) wykorzystuje?specjalista ds. bezpieczeństwa'],
		['MM150_3', 'psycholog', 'Jakie wewnątrzzakładowe lub zewnętrzne służby w zakresie zdrowia i bezpieczeństwa pracy Pan(i) wykorzystuje?psycholog'],
		['MM150_4', 'specjalista ds. ergonomii zajmujący się organizacją stanowiska pracy', 'Jakie wewnątrzzakładowe lub zewnętrzne służby w zakresie zdrowia i bezpieczeństwa pracy Pan(i) wykorzystuje?specjalista ds. ergonomii zajmujący się organizacją stanowiska pracy'],
		['MM150_5', 'ogólne konsultacje w zakresie zdrowia i bezpieczeństwa', 'Jakie wewnątrzzakładowe lub zewnętrzne służby w zakresie zdrowia i bezpieczeństwa pracy Pan(i) wykorzystuje?ogólne konsultacje w zakresie zdrowia i bezpieczeństwa'],
		['MM152', 'Czy Pana(i) oddział rutynowo analizuje przyczyny absencji chorobowej?', 'Czy Pana(i) oddział rutynowo analizuje przyczyny absencji chorobowej?'],
		['MM153', 'Czy oddział podejmuje kroki wspierające powrót pracowników do pracy po długiej chorobie?', 'Czy oddział podejmuje kroki wspierające powrót pracowników do pracy po długiej chorobie?'],
		['MM154', 'Czy zdrowie pracowników jest monitorowane przez regularne badania zdrowotne?', 'Czy zdrowie pracowników jest monitorowane przez regularne badania zdrowotne?'],
		['MM155', 'Czy w Pana(i) oddziale istnieje udokumentowana polityka, przyjęty system zarządzania lub plan działania w zakresie zdrowia i bezpieczeństwa w pracy?', 'Czy w Pana(i) oddziale istnieje udokumentowana polityka, przyjęty system zarządzania lub plan działania w zakresie zdrowia i bezpieczeństwa w pracy?'],
		['MM158', 'Czy kwestie zdrowia i bezpieczeństwa są omawiane na spotkaniach kadry kierowniczej wysokiego szczebla regularnie, czasami czy praktycznie w ogóle nie są omawiane?', 'Czy kwestie zdrowia i bezpieczeństwa są omawiane na spotkaniach kadry kierowniczej wysokiego szczebla regularnie, czasami czy praktycznie w ogóle nie są omawiane?'],
		['MM159', 'Ogólnie rzecz biorąc, jak ocenił(a)by Pan(i) stopień zaangażowania kierowników liniowych i przełożonych w zarządzanie sprawami bezpieczeństwa i zdrowia w pracy? Czy jest ono bardzo wysokie, dość wysokie, dość niskie czy bardzo niskie?', 'Ogólnie rzecz biorąc, jak ocenił(a)by Pan(i) stopień zaangażowania kierowników liniowych i przełożonych w zarządzanie sprawami bezpieczeństwa i zdrowia w pracy? Czy jest ono bardzo wysokie, dość wysokie, dość niskie czy bardzo niskie?'],
		['MM161', 'Czy stanowiska pracy w Pana(i) oddziale są regularnie kontrolowane pod kątem bezpieczeństwa i zdrowia w pracy jako element oceny ryzyka lub w ramach podobnych działań?', 'Czy stanowiska pracy w Pana(i) oddziale są regularnie kontrolowane pod kątem bezpieczeństwa i zdrowia w pracy jako element oceny ryzyka lub w ramach podobnych działań?'],
		['MM170', 'Czy w ciągu ostatnich 3 lat Państwowa Inspekcja Pracy odwiedziła ten oddział w celu skontrolowania warunków bezpieczeństwa i zdrowia?', 'Czy w ciągu ostatnich 3 lat Państwowa Inspekcja Pracy odwiedziła ten oddział w celu skontrolowania warunków bezpieczeństwa i zdrowia?'],
		['MM173_1', 'Instytuty ds. bezpieczeństwa i higieny w pracy', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?Instytuty ds. bezpieczeństwa i higieny w pracy'],
		['MM173_2', 'Europejska Agencja Bezpieczeństwa i Zdrowia w Pracy', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?Europejska Agencja Bezpieczeństwa i Zdrowia w Pracy'],
		['MM173_3', 'wewnętrzne służby ds. bezpieczeństwa i zdrowia w pracy', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?wewnętrzne służby ds. bezpieczeństwa i zdrowia w pracy'],
		['MM173_4', 'Państwowa Inspekcja Pracy', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?Państwowa Inspekcja Pracy'],
		['MM173_5', 'organizacje pracodawców', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?organizacje pracodawców'],
		['MM173_6', 'Związki zawodowe', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?Związki zawodowe'],
		['MM173_7', 'Zewnętrzni specjaliści ds. bezpieczeństwa i zdrowia pracy', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?Zewnętrzni specjaliści ds. bezpieczeństwa i zdrowia pracy'],
		['MM173_8', 'Ubezpieczyciele', 'Czy Pana(i) oddział korzystał z informacji na temat bezpieczeństwa i zdrowia w pracy uzyskanych od niżej wymienionych organów lub instytucji?Ubezpieczyciele'],
		['MM175', 'Czy słyszał Pan(i) o Europejskim Tygodniu bezpieczeństwa i zdrowia w pracy?', 'Czy słyszał Pan(i) o Europejskim Tygodniu bezpieczeństwa i zdrowia w pracy?'],
		['MM200_1', 'Niebezpieczne substancje (np. pyły, substancje chemiczne, biologiczne lub radioaktywne)', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.Niebezpieczne substancje (np. pyły, substancje chemiczne, biologiczne czy radioaktywne)'],
		['MM200_2', 'Wypadki', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.Wypadki'],
		['MM200_3', 'Hałas i wibracje', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.Hałas i wibracje'],
		['MM200_4', 'Uszkodzenia układu mięśniowo-szkieletowego, np. ból kręgosłupa, szyi, ramion lub nóg', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.Uszkodzenia układu mięśniowo-szkieletowego, np. ból kręgosłupa, szyi, ramion lub nóg'],
		['MM200_5', 'Stres związany z pracą', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.Stres związany z pracą'],
		['MM200_6', 'Przemoc lub zagrożenie przemocą', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.Przemoc lub zagrożenie przemocą'],
		['MM200_7', 'Mobbing lub prześladowanie, tj. znęcanie się, poniżanie lub agresja ze strony współpracowników lub przełożonych', 'Proszę powiedzieć, czy każda z następujących spraw jest w Pana(i) oddziale ważną kwestią, mało ważną kwestią czy nie jest to żadna kwestia.Mobbing lub prześladowanie, tj. znęcanie się, poniżanie lub agresja ze strony współpracowników lub przełożonych'],
		['MM202_1', 'Presja czasu', 'Na stres, przemoc czy prześladowanie w pracy może mieć wpływ kilka czynników; dotyczą one sposobu organizacji pracy i określa się je często mianem "ryzyka psychospołecznego". Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.Presja czasu'],
		['MM202_2', 'Słaba komunikacja pomiędzy kadrą kierowniczą a pracownikami', 'Na stres, przemoc czy prześladowanie w pracy może mieć wpływ kilka czynników; dotyczą one sposobu organizacji pracy i określa się je często mianem "ryzyka psychospołecznego". Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.Słaba komunikacja pomiędzy kadrą kierowniczą a pracownikami'],
		['MM202_3', 'Słaba współpraca między współpracownikami', 'Na stres, przemoc czy prześladowanie w pracy może mieć wpływ kilka czynników; dotyczą one sposobu organizacji pracy i określa się je często mianem "ryzyka psychospołecznego". Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.Słaba współpraca między współpracownikami'],
		['MM202_4', 'Brak kontroli pracowników nad organizacją swojej pracy', 'Na stres, przemoc czy prześladowanie w pracy może mieć wpływ kilka czynników; dotyczą one sposobu organizacji pracy i określa się je często mianem "ryzyka psychospołecznego". Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.Brak kontroli pracowników nad organizacją swojej pracy'],
		['MM202_5', 'Niepewność pracy', 'Na stres, przemoc czy prześladowanie w pracy może mieć wpływ kilka czynników; dotyczą one sposobu organizacji pracy i określa się je często mianem "ryzyka psychospołecznego". Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.Niepewność pracy'],
		['MM202_6', 'Konieczność kontaktów z trudnymi klientami, pacjentami, uczniami itp.', 'Na stres, przemoc czy prześladowanie w pracy może mieć wpływ kilka czynników; dotyczą one sposobu organizacji pracy i określa się je często mianem "ryzyka psychospołecznego". Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.Konieczność kontaktów z trudnymi klientami, pacjentami, uczniami itp.'],
		['MM202_7', 'Problemy w relacjach przełożony - podwładny', 'Na stres, przemoc czy prześladowanie w pracy może mieć wpływ kilka czynników; dotyczą one sposobu organizacji pracy i określa się je często mianem "ryzyka psychospołecznego". Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.Problemy w relacjach przełożony - podwładny'],
		['MM202_8', 'Długie lub nieregularne godziny pracy', 'Na stres, przemoc czy prześladowanie w pracy może mieć wpływ kilka czynników; dotyczą one sposobu organizacji pracy i określa się je często mianem "ryzyka psychospołecznego". Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.Długie lub nieregularne godziny pracy'],
		['MM202_9', 'Niejasna polityka kadrowa', 'Na stres, przemoc czy prześladowanie w pracy może mieć wpływ kilka czynników; dotyczą one sposobu organizacji pracy i określa się je często mianem "ryzyka psychospołecznego". Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.Niejasna polityka kadrowa'],
		['MM202_10', 'Dyskryminacja (na przykład ze względu na płeć, wiek lub pochodzenie etniczne)', 'Na stres, przemoc czy prześladowanie w pracy może mieć wpływ kilka czynników; dotyczą one sposobu organizacji pracy i określa się je często mianem "ryzyka psychospołecznego". Proszę powiedzieć, czy niżej wymienione zagrożenia psychospołeczne stanowią kwestię w Pana(i) oddziale.Dyskryminacja (na przykład ze względu na płeć, wiek lub pochodzenie etniczne)'],
		['MM250', 'Czy w Pana(i) oddziale istnieją procedury postępowania ze stresem związanym z pracą?', 'Czy w Pana(i) oddziale istnieją procedury postępowania ze stresem związanym z pracą?'],
		['MM251', 'Czy istnieje procedura postępowania z mobbingiem lub prześladowaniem?', 'Czy istnieje procedura postępowania z mobbingiem lub prześladowaniem?'],
		['MM252', 'Czy istnieje procedura postępowania z przemocą w miejscu pracy?', 'Czy istnieje procedura postępowania z przemocą w miejscu pracy?'],
		['MM253_1', 'Zmiany sposobu organizacji pracy', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?Zmiany sposobu organizacji pracy'],
		['MM253_2', 'Zmiana aranżacji miejsca pracy', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?Zmiana aranżacji miejsca pracy'],
		['MM253_3', 'Poufne konsultacje dla pracowników', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?Poufne konsultacje dla pracowników'],
		['MM253_4', 'Wprowadzenie procedury rozwiązywania konfliktów', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?Wprowadzenie procedury rozwiązywania konfliktów'],
		['MM253_5', 'Zmiany w organizacji czasu pracy', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?Zmiany w organizacji czasu pracy'],
		['MM253_6', 'Zapewnienie szkoleń', 'Czy w ciągu ostatnich 3 lat Pana(i) oddział stosował któreś z poniższych środków w celu eliminowania ryzyka psychospołecznego?Zapewnienie szkoleń'],
		['MM256', 'Czy Pana(i) oddział podejmuje działania, jeżeli poszczególni pracownicy pracują zbyt długo lub mają nieregularne godziny pracy?', 'Czy Pana(i) oddział podejmuje działania, jeżeli poszczególni pracownicy pracują zbyt długo lub mają nieregularne godziny pracy?'],
		['MM259', 'Czy informuje Pan(i) pracowników o czynnikach ryzyka psychospołecznego i ich wpływie na zdrowie i bezpieczeństwo?', 'Czy informuje Pan(i) pracowników o czynnikach ryzyka psychospołecznego i ich wpływie na zdrowie i bezpieczeństwo?'],
		['MM260', 'Czy pracownicy zostali poinformowani, do kogo mogą się zwrócić z problemami psychospołecznymi związanymi z pracą?', 'Czy pracownicy zostali poinformowani, do kogo mogą się zwrócić z problemami psychospołecznymi związanymi z pracą?'],
		['MM171_1', 'Spełnienie wymogów prawnych', 'Na ile ważne są w Pana(i) oddziale następujące powody zajmowania się sprawami bezpieczeństwa i zdrowia w pracy? Proszę powiedzieć o każdej z niżej wymienionych przyczyn, czy odgrywa ona dużą rolę, małą rolę czy nie odgrywa żadnej roli?Spełnienie wymogów prawnych'],
		['MM171_2', 'Żądania ze strony pracowników lub ich przedstawicieli', 'Na ile ważne są w Pana(i) oddziale następujące powody zajmowania się sprawami bezpieczeństwa i zdrowia w pracy? Proszę powiedzieć o każdej z niżej wymienionych przyczyn, czy odgrywa ona dużą rolę, małą rolę czy nie odgrywa żadnej roli?Żądania ze strony pracowników lub ich przedstawicieli'],
		['MM171_3', 'zapobieganie odchodzeniu pracowników i zarządzanie absencjami', 'Na ile ważne są w Pana(i) oddziale następujące powody zajmowania się sprawami bezpieczeństwa i zdrowia w pracy? Proszę powiedzieć o każdej z niżej wymienionych przyczyn, czy odgrywa ona dużą rolę, małą rolę czy nie odgrywa żadnej roli?zapobieganie odchodzeniu pracowników i zarządzanie absencjami'],
		['MM171_4', 'przyczyny ekonomiczne lub związane z jakością wykonania pracy', 'Na ile ważne są w Pana(i) oddziale następujące powody zajmowania się sprawami bezpieczeństwa i zdrowia w pracy? Proszę powiedzieć o każdej z niżej wymienionych przyczyn, czy odgrywa ona dużą rolę, małą rolę czy nie odgrywa żadnej roli?przyczyny ekonomiczne lub związane z jakością wykonania pracy'],
		['MM171_5', 'Wymagania klientów lub troska o reputację przedsiębiorstwa', 'Na ile ważne są w Pana(i) oddziale następujące powody zajmowania się sprawami bezpieczeństwa i zdrowia w pracy? Proszę powiedzieć o każdej z niżej wymienionych przyczyn, czy odgrywa ona dużą rolę, małą rolę czy nie odgrywa żadnej roli?Wymagania klientów lub troska o reputację przedsiębiorstwa'],
		['MM171_6', 'Naciski ze strony Państwowej Inspekcji Pracy', 'Na ile ważne są w Pana(i) oddziale następujące powody zajmowania się sprawami bezpieczeństwa i zdrowia w pracy? Proszę powiedzieć o każdej z niżej wymienionych przyczyn, czy odgrywa ona dużą rolę, małą rolę czy nie odgrywa żadnej roli?Naciski ze strony Państwowej Inspekcji Pracy'],
		['MM172_1', 'brak takich zasobów, jak czas, personel czy środki pieniężne', 'Jakie są główne trudności występujące przy zajmowaniu się bezpieczeństwem i zdrowiem w pracy w Pana(i) oddziale? Proszę powiedzieć o każdej z następujących trudności, czy jest ona istotną przeszkodą, mało istotną przeszkodą czy nie jest żadną przeszkodą.brak takich zasobów, jak czas, personel czy środki pieniężne'],
		['MM172_2', 'nieświadomość', 'Jakie są główne trudności występujące przy zajmowaniu się bezpieczeństwem i zdrowiem w pracy w Pana(i) oddziale? Proszę powiedzieć o każdej z następujących trudności, czy jest ona istotną przeszkodą, mało istotną przeszkodą czy nie jest żadną przeszkodą.nieświadomość'],
		['MM172_3', 'brak wiedzy', 'Jakie są główne trudności występujące przy zajmowaniu się bezpieczeństwem i zdrowiem w pracy w Pana(i) oddziale? Proszę powiedzieć o każdej z następujących trudności, czy jest ona istotną przeszkodą, mało istotną przeszkodą czy nie jest żadną przeszkodą.brak wiedzy'],
		['MM172_4', 'brak wsparcia technicznego lub wskazówek', 'Jakie są główne trudności występujące przy zajmowaniu się bezpieczeństwem i zdrowiem w pracy w Pana(i) oddziale? Proszę powiedzieć o każdej z następujących trudności, czy jest ona istotną przeszkodą, mało istotną przeszkodą czy nie jest żadną przeszkodą.brak wsparcia technicznego lub wskazówek'],
		['MM172_5', 'kultura organizacji', 'Jakie są główne trudności występujące przy zajmowaniu się bezpieczeństwem i zdrowiem w pracy w Pana(i) oddziale? Proszę powiedzieć o każdej z następujących trudności, czy jest ona istotną przeszkodą, mało istotną przeszkodą czy nie jest żadną przeszkodą.kultura organizacji'],
		['MM172_6', 'ta kwestia jest delikatna', 'Jakie są główne trudności występujące przy zajmowaniu się bezpieczeństwem i zdrowiem w pracy w Pana(i) oddziale? Proszę powiedzieć o każdej z następujących trudności, czy jest ona istotną przeszkodą, mało istotną przeszkodą czy nie jest żadną przeszkodą.ta kwestia jest delikatna'],
		['MM300', 'W porównaniu z innymi zagadnieniami z zakresu bezpieczeństwa i higieny pracy - czy zajmowanie się ryzykiem psychospołecznym jest trudniejsze, łatwiejsze czy nie ma różnicy?', 'W porównaniu z innymi zagadnieniami z zakresu bezpieczeństwa i higieny pracy - czy zajmowanie się ryzykiem psychospołecznym jest trudniejsze, łatwiejsze czy nie ma różnicy?'],
		['MM302', 'Czy korzystał(a) Pana(i) z informacji lub wsparcia z zewnętrznych źródeł na temat postępowania z ryzykiem psychospołecznym w pracy?', 'Czy korzystał(a) Pana(i) z informacji lub wsparcia z zewnętrznych źródeł na temat postępowania z ryzykiem psychospołecznym w pracy?'],
		['MM303a', 'Czy potrzebne byłyby Panu(i) dodatkowe informacje lub wsparcie w tym zakresie?', 'Czy potrzebne byłyby Panu(i) dodatkowe informacje lub wsparcie w tym zakresie?<br><br>Pytania zadawane zakładom zgłaszającym korzystanie z informacji lub wsparcia z zewnętrznych źródeł, dotyczącego sposobów radzenia sobie z zagrożeniami psychospołecznymi w pracy.'],
		['MM350', 'Czy w Pana(i) oddziale istnieje rada pracowników?', 'Czy w Pana(i) oddziale istnieje rada pracowników?'],
		['MM351', 'Czy w Pana(i) oddziale istnieje zakładowa organizacja związkowa?', 'Czy w Pana(i) oddziale istnieje zakładowa organizacja związkowa?'],
		['MM355all', 'Czy Pana(i) oddział ma wewnętrznego społecznego inspektora pracy?', 'Czy Pana(i) oddział ma wewnętrznego społecznego inspektora pracy?<br><br>NL: Czy w tym zakładzie jest członek przedstawicielstwa zdrowia i bezpieczeństwa?'],
		['MM358', 'Czy w Pana(i) oddziale jest komisja BHP?', 'Czy w Pana(i) oddziale jest komisja BHP?']
	];
