//Auto Generated file
var subset_
	 = [
	
		['size_4', 'Dimensão do estabelecimento'],
		['sec3', 'Setor de atividade']
	];
var subset_subsetValue
	 = [
	
		['sec3', 'All', 'Todos'],
		['sec3', '1--Producing-Industries', 'Sector de produção'],
		['sec3', '2--Private-Services', 'Serviços privados'],
		['sec3', '3--Public-Services', 'Serviços públicos'],
		['size_4', 'All', 'Todos'],
		['size_4', '1--10-to-19-employees', '10 a 19 trabalhadores'],
		['size_4', '2--20-to-49-employees', '20 a 49 trabalhadores'],
		['size_4', '3--50-to-249-employees', '50 a 249 trabalhadores'],
		['size_4', '4--250-employees-or-more', '250 ou mais trabalhadores']
	];
var topic_
	 = [
	
		['', 'Todos (70)'],
		['Gestão da SST', 'Gestão da SST (29)'],
		['Gestão dos fatores de risco psicossocial', 'Gestão dos fatores de risco psicossocial (22)'],
		['Impulsionadores e obstáculos', 'Impulsionadores e obstáculos (15)'],
		['Participação dos trabalhadores', 'Participação dos trabalhadores (4)']
	];
var topic_question
	 = [
	
		['Gestão da SST', 'MM150_1', 'Utilização dos serviços de segurança e saúde: Um médico de medicina do trabalho'],
		['Gestão da SST', 'MM150_2', 'Utilização dos serviços de segurança e saúde: Um especialista em segurança'],
		['Gestão da SST', 'MM150_3', 'Utilização dos serviços de segurança e saúde: Um psicólogo'],
		['Gestão da SST', 'MM150_4', 'Utilização dos serviços de segurança e saúde: Um especialista em ergonomia, para lidar com a configuração do local de trabalho'],
		['Gestão da SST', 'MM150_5', 'Utilização dos serviços de segurança e saúde: Um técnico de segurança e saúde'],
		['Gestão da SST', 'MM152', 'O seu estabelecimento analisa de forma rotineira as causas das faltas por doença?'],
		['Gestão da SST', 'MM153', 'Toma medidas para apoiar o regresso dos trabalhadores ao trabalho depois de um longo período de baixa médica?'],
		['Gestão da SST', 'MM154', 'A saúde dos trabalhadores é monitorizada através de exames médicos regulares?'],
		['Gestão da SST', 'MM155', 'Existe alguma política documentada, sistema de gestão estabelecido ou plano de acção para a segurança e saúde no seu estabelecimento?'],
		['Gestão da SST', 'MM158', 'As questões da saúde e da segurança e saúde são abordadas em reuniões da direcção de alto nível regularmente, de vez em quando ou praticamente nunca?'],
		['Gestão da SST', 'MM159', 'De uma forma geral, como classificaria o envolvimento dos directores e supervisores imediatos na gestão da segurança e saúde ? É muito elevado, elevado, baixo ou muito baixo?'],
		['Gestão da SST', 'MM161', 'Os locais de trabalho neste estabelecimento são regularmente verificados no que respeita à segurança e saúde como parte da avaliação dos riscos ou medidas similares?'],
		['Gestão da SST', 'MM170', 'A Inspecção do Trabalho visitou este local de trabalho nos últimos 3 anos a fim de verificar as condições de segurança e saúde?'],
		['Gestão da SST', 'MM173_1', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Institutos oficiais para a segurança e saúde no trabalho'],
		['Gestão da SST', 'MM173_2', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Agência Europeia para a Segurança e Saúde no Trabalho'],
		['Gestão da SST', 'MM173_3', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Serviços internos de segurança e saúde'],
		['Gestão da SST', 'MM173_4', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Inspecção do Trabalho'],
		['Gestão da SST', 'MM173_5', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Organizações de trabalhadores'],
		['Gestão da SST', 'MM173_6', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Sindicatos'],
		['Gestão da SST', 'MM173_7', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Especialistas contratados em segurança e saúde'],
		['Gestão da SST', 'MM173_8', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Fornecedores de seguros'],
		['Gestão da SST', 'MM175', 'Tem conhecimento da Semana Europeia para a Segurança e Saúde no Trabalho?'],
		['Gestão da SST', 'MM200_1', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimento: Substâncias perigosas (por ex., poeiras produtos químicos, biológicos ou radioactivos)'],
		['Gestão da SST', 'MM200_2', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimento: Acidentes'],
		['Gestão da SST', 'MM200_3', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimento: Ruídos e vibrações'],
		['Gestão da SST', 'MM200_4', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimento: Doenças musculo-esqueléticas, como dor de costas, pescoço, braços ou pernas'],
		['Gestão da SST', 'MM200_5', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimento: Stresse relacionado com o trabalho'],
		['Gestão da SST', 'MM200_6', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimento: Violência ou ameaça de violência'],
		['Gestão da SST', 'MM200_7', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimento: Intimidação ou assédio, ou seja, ofensa, humilhação ou agressão por colegas ou superiores'],
		['Gestão dos fatores de risco psicossocial', 'MM202_1', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Pressão de tempo'],
		['Gestão dos fatores de risco psicossocial', 'MM202_2', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Má comunicação entre a direcção e os trabalhadores'],
		['Gestão dos fatores de risco psicossocial', 'MM202_3', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Fraca cooperação entre os colegas'],
		['Gestão dos fatores de risco psicossocial', 'MM202_4', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Falta de controlo dos trabalhadores na organização do seu trabalho'],
		['Gestão dos fatores de risco psicossocial', 'MM202_5', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento..: Insegurança no trabalho'],
		['Gestão dos fatores de risco psicossocial', 'MM202_6', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Ter de lidar com clientes difíceis, doentes, crianças, etc.'],
		['Gestão dos fatores de risco psicossocial', 'MM202_7', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Problemas nas relações entre o supervisor e o empregado'],
		['Gestão dos fatores de risco psicossocial', 'MM202_8', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Horários de trabalho longos ou irregulares'],
		['Gestão dos fatores de risco psicossocial', 'MM202_9', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Uma política de recursos humanos pouco clara'],
		['Gestão dos fatores de risco psicossocial', 'MM202_10', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Discriminação (por exemplo, devido ao sexo, idade ou etnia)'],
		['Gestão dos fatores de risco psicossocial', 'MM250', 'O seu estabelecimento possui um procedimento para lidar com o stresse relacionado com o trabalho?'],
		['Gestão dos fatores de risco psicossocial', 'MM251', 'Existe algum procedimento implementado para lidar com as intimidações ou o assédio?'],
		['Gestão dos fatores de risco psicossocial', 'MM252', 'E possui um procedimento para lidar com a violência relacionada com o trabalho?'],
		['Gestão dos fatores de risco psicossocial', 'MM253_1', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?: Alterações na forma como o trabalho é organizado'],
		['Gestão dos fatores de risco psicossocial', 'MM253_2', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?: Remodelação da área de trabalho'],
		['Gestão dos fatores de risco psicossocial', 'MM253_3', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?: Aconselhamento confidencial para os trabalhadores'],
		['Gestão dos fatores de risco psicossocial', 'MM253_4', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?: Implementação de um procedimento de resolução de conflitos'],
		['Gestão dos fatores de risco psicossocial', 'MM253_5', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?: Alterações às disposições do horário de trabalho'],
		['Gestão dos fatores de risco psicossocial', 'MM253_6', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?: Fornecimento de formação'],
		['Gestão dos fatores de risco psicossocial', 'MM256', 'O seu estabelecimento toma acções se os trabalhadores individuais trabalharem durante muito tempo ou durante horas irregulares?'],
		['Gestão dos fatores de risco psicossocial', 'MM259', 'Informa os trabalhadores sobre os riscos psicossociais e o seu efeito na saúde e na segurança?'],
		['Gestão dos fatores de risco psicossocial', 'MM260', 'Foram informados sobre quem devem contactar em caso de problemas psicossociais relacionados com o trabalho?'],
		['Impulsionadores e obstáculos', 'MM171_1', 'Razões para abordar a segurança e saúde no estabelecimento: Cumprimento das obrigações legais'],
		['Impulsionadores e obstáculos', 'MM171_2', 'Razões para abordar a segurança e saúde no estabelecimento: Pedidos dos trabalhadores ou dos seus representantes'],
		['Impulsionadores e obstáculos', 'MM171_3', 'Razões para abordar a segurança e saúde no estabelecimento: Retenção de trabalhadores e gestão do absentismo'],
		['Impulsionadores e obstáculos', 'MM171_4', 'Razões para abordar a segurança e saúde no estabelecimento: Razões económicas ou relacionadas com o desempenho'],
		['Impulsionadores e obstáculos', 'MM171_5', 'Razões para abordar a segurança e saúde no estabelecimento: Requisitos de clientes ou preocupações sobre a reputação da organizaçao'],
		['Impulsionadores e obstáculos', 'MM171_6', 'Razões para abordar a segurança e saúde no estabelecimento: Pressão da Inspecção do Trabalho'],
		['Impulsionadores e obstáculos', 'MM172_1', 'Principais dificuldades ao abordar a segurança e a saúde: Falta de recursos, como tempo, pessoal ou verbas'],
		['Impulsionadores e obstáculos', 'MM172_2', 'Principais dificuldades ao abordar a segurança e a saúde: Falta de sensibilização'],
		['Impulsionadores e obstáculos', 'MM172_3', 'Principais dificuldades ao abordar a segurança e a saúde: Falta de competências'],
		['Impulsionadores e obstáculos', 'MM172_4', 'Principais dificuldades ao abordar a segurança e a saúde: Falta de apoio técnico ou orientação'],
		['Impulsionadores e obstáculos', 'MM172_5', 'Principais dificuldades ao abordar a segurança e a saúde: A cultura no estabelecimento'],
		['Impulsionadores e obstáculos', 'MM172_6', 'Principais dificuldades ao abordar a segurança e a saúde: A sensibilidade do assunto'],
		['Impulsionadores e obstáculos', 'MM300', 'Comparando com outras questões de segurança e saúde, é mais difícil lidar com os riscos psicossociais, menos difícil, ou não existem diferenças?'],
		['Impulsionadores e obstáculos', 'MM302', 'Usou informações ou apoio de fontes externas sobre como lidar com os riscos psicossociais no trabalho?'],
		['Impulsionadores e obstáculos', 'MM303a', 'Necessita de informações ou apoio adicionais sobre este assunto?'],
		['Participação dos trabalhadores', 'MM350', 'Existe uma comissão de trabalhadores neste estabelecimento?'],
		['Participação dos trabalhadores', 'MM351', 'E existe uma comissão sindical ou intersindical no seu estabelecimento?'],
		['Participação dos trabalhadores', 'MM355all', 'O seu estabelecimento possui um representante dos trabalhadores para a segurança, higiene e saúde no trabalho?'],
		['Participação dos trabalhadores', 'MM358', 'Existe uma Comissão de Segurança, Higiene e Saúde no Trabalho no seu estabelecimento?']
	];
var question_
	 = [
	
		['MM150_1', 'Utilização dos serviços de segurança e saúde: Um médico de medicina do trabalho'],
		['MM150_2', 'Utilização dos serviços de segurança e saúde: Um especialista em segurança'],
		['MM150_3', 'Utilização dos serviços de segurança e saúde: Um psicólogo'],
		['MM150_4', 'Utilização dos serviços de segurança e saúde: Um especialista em ergonomia, para lidar com a configuração do local de trabalho'],
		['MM150_5', 'Utilização dos serviços de segurança e saúde: Um técnico de segurança e saúde'],
		['MM152', 'O seu estabelecimento analisa de forma rotineira as causas das faltas por doença?'],
		['MM153', 'Toma medidas para apoiar o regresso dos trabalhadores ao trabalho depois de um longo período de baixa médica?'],
		['MM154', 'A saúde dos trabalhadores é monitorizada através de exames médicos regulares?'],
		['MM155', 'Existe alguma política documentada, sistema de gestão estabelecido ou plano de acção para a segurança e saúde no seu estabelecimento?'],
		['MM158', 'As questões da saúde e da segurança e saúde são abordadas em reuniões da direcção de alto nível regularmente, de vez em quando ou praticamente nunca?'],
		['MM159', 'De uma forma geral, como classificaria o envolvimento dos directores e supervisores imediatos na gestão da segurança e saúde ? É muito elevado, elevado, baixo ou muito baixo?'],
		['MM161', 'Os locais de trabalho neste estabelecimento são regularmente verificados no que respeita à segurança e saúde como parte da avaliação dos riscos ou medidas similares?'],
		['MM170', 'A Inspecção do Trabalho visitou este local de trabalho nos últimos 3 anos a fim de verificar as condições de segurança e saúde?'],
		['MM173_1', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Institutos oficiais para a segurança e saúde no trabalho'],
		['MM173_2', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Agência Europeia para a Segurança e Saúde no Trabalho'],
		['MM173_3', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Serviços internos de segurança e saúde'],
		['MM173_4', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Inspecção do Trabalho'],
		['MM173_5', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Organizações de trabalhadores'],
		['MM173_6', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Sindicatos'],
		['MM173_7', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Especialistas contratados em segurança e saúde'],
		['MM173_8', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?: Fornecedores de seguros'],
		['MM175', 'Tem conhecimento da Semana Europeia para a Segurança e Saúde no Trabalho?'],
		['MM200_1', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimento: Substâncias perigosas (por ex., poeiras produtos químicos, biológicos ou radioactivos)'],
		['MM200_2', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimento: Acidentes'],
		['MM200_3', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimento: Ruídos e vibrações'],
		['MM200_4', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimento: Doenças musculo-esqueléticas, como dor de costas, pescoço, braços ou pernas'],
		['MM200_5', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimento: Stresse relacionado com o trabalho'],
		['MM200_6', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimento: Violência ou ameaça de violência'],
		['MM200_7', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimento: Intimidação ou assédio, ou seja, ofensa, humilhação ou agressão por colegas ou superiores'],
		['MM202_1', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Pressão de tempo'],
		['MM202_2', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Má comunicação entre a direcção e os trabalhadores'],
		['MM202_3', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Fraca cooperação entre os colegas'],
		['MM202_4', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Falta de controlo dos trabalhadores na organização do seu trabalho'],
		['MM202_5', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento..: Insegurança no trabalho'],
		['MM202_6', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Ter de lidar com clientes difíceis, doentes, crianças, etc.'],
		['MM202_7', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Problemas nas relações entre o supervisor e o empregado'],
		['MM202_8', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Horários de trabalho longos ou irregulares'],
		['MM202_9', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Uma política de recursos humanos pouco clara'],
		['MM202_10', 'Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.: Discriminação (por exemplo, devido ao sexo, idade ou etnia)'],
		['MM250', 'O seu estabelecimento possui um procedimento para lidar com o stresse relacionado com o trabalho?'],
		['MM251', 'Existe algum procedimento implementado para lidar com as intimidações ou o assédio?'],
		['MM252', 'E possui um procedimento para lidar com a violência relacionada com o trabalho?'],
		['MM253_1', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?: Alterações na forma como o trabalho é organizado'],
		['MM253_2', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?: Remodelação da área de trabalho'],
		['MM253_3', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?: Aconselhamento confidencial para os trabalhadores'],
		['MM253_4', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?: Implementação de um procedimento de resolução de conflitos'],
		['MM253_5', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?: Alterações às disposições do horário de trabalho'],
		['MM253_6', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?: Fornecimento de formação'],
		['MM256', 'O seu estabelecimento toma acções se os trabalhadores individuais trabalharem durante muito tempo ou durante horas irregulares?'],
		['MM259', 'Informa os trabalhadores sobre os riscos psicossociais e o seu efeito na saúde e na segurança?'],
		['MM260', 'Foram informados sobre quem devem contactar em caso de problemas psicossociais relacionados com o trabalho?'],
		['MM171_1', 'Razões para abordar a segurança e saúde no estabelecimento: Cumprimento das obrigações legais'],
		['MM171_2', 'Razões para abordar a segurança e saúde no estabelecimento: Pedidos dos trabalhadores ou dos seus representantes'],
		['MM171_3', 'Razões para abordar a segurança e saúde no estabelecimento: Retenção de trabalhadores e gestão do absentismo'],
		['MM171_4', 'Razões para abordar a segurança e saúde no estabelecimento: Razões económicas ou relacionadas com o desempenho'],
		['MM171_5', 'Razões para abordar a segurança e saúde no estabelecimento: Requisitos de clientes ou preocupações sobre a reputação da organizaçao'],
		['MM171_6', 'Razões para abordar a segurança e saúde no estabelecimento: Pressão da Inspecção do Trabalho'],
		['MM172_1', 'Principais dificuldades ao abordar a segurança e a saúde: Falta de recursos, como tempo, pessoal ou verbas'],
		['MM172_2', 'Principais dificuldades ao abordar a segurança e a saúde: Falta de sensibilização'],
		['MM172_3', 'Principais dificuldades ao abordar a segurança e a saúde: Falta de competências'],
		['MM172_4', 'Principais dificuldades ao abordar a segurança e a saúde: Falta de apoio técnico ou orientação'],
		['MM172_5', 'Principais dificuldades ao abordar a segurança e a saúde: A cultura no estabelecimento'],
		['MM172_6', 'Principais dificuldades ao abordar a segurança e a saúde: A sensibilidade do assunto'],
		['MM300', 'Comparando com outras questões de segurança e saúde, é mais difícil lidar com os riscos psicossociais, menos difícil, ou não existem diferenças?'],
		['MM302', 'Usou informações ou apoio de fontes externas sobre como lidar com os riscos psicossociais no trabalho?'],
		['MM303a', 'Necessita de informações ou apoio adicionais sobre este assunto?'],
		['MM350', 'Existe uma comissão de trabalhadores neste estabelecimento?'],
		['MM351', 'E existe uma comissão sindical ou intersindical no seu estabelecimento?'],
		['MM355all', 'O seu estabelecimento possui um representante dos trabalhadores para a segurança, higiene e saúde no trabalho?'],
		['MM358', 'Existe uma Comissão de Segurança, Higiene e Saúde no Trabalho no seu estabelecimento?']
	];
var question_answer
	 = [
	
		['MM150_1', '1--Yes', 'Sim'],
		['MM150_1', '2--No', 'Não'],
		['MM150_1', '3--DK--NA', 'Não responde'],
		['MM150_2', '1--Yes', 'Sim'],
		['MM150_2', '2--No', 'Não'],
		['MM150_2', '3--DK--NA', 'Não responde'],
		['MM150_3', '1--Yes', 'Sim'],
		['MM150_3', '2--No', 'Não'],
		['MM150_3', '3--DK--NA', 'Não responde'],
		['MM150_4', '1--Yes', 'Sim'],
		['MM150_4', '2--No', 'Não'],
		['MM150_4', '3--DK--NA', 'Não responde'],
		['MM150_5', '1--Yes', 'Sim'],
		['MM150_5', '2--No', 'Não'],
		['MM150_5', '3--DK--NA', 'Não responde'],
		['MM152', '1--Yes', 'Sim'],
		['MM152', '2--No', 'Não'],
		['MM152', '3--DK--NA', 'Não responde'],
		['MM153', '1--Yes', 'Sim'],
		['MM153', '2--No', 'Não'],
		['MM153', '3--DK--NA', 'Não responde'],
		['MM154', '1--Yes', 'Sim'],
		['MM154', '2--No', 'Não'],
		['MM154', '3--DK--NA', 'Não responde'],
		['MM155', '1--Yes', 'Sim'],
		['MM155', '2--No', 'Não'],
		['MM155', '3--DK--NA', 'Não responde'],
		['MM158', '1--Regularly', 'Regularmente'],
		['MM158', '2--Occasionally', 'Ocasionalmente'],
		['MM158', '3--Practically-never', 'Quase nunca'],
		['MM158', '4--DK--NA', 'Não responde'],
		['MM159', '1--Very-high', 'Muito elevado'],
		['MM159', '2--Quite-high', 'Elevado'],
		['MM159', '3--Quite-low', 'Baixo'],
		['MM159', '4--Very-low', 'Muito baixo'],
		['MM159', '5--DK--NA', 'Não responde'],
		['MM161', '1--Yes', 'Sim'],
		['MM161', '2--No', 'Não'],
		['MM161', '3--DK--NA', 'Não responde'],
		['MM170', '1--Yes', 'Sim'],
		['MM170', '2--No', 'Não'],
		['MM170', '3--DK--NA', 'Não responde'],
		['MM171_1', '1--Major', 'Importante'],
		['MM171_1', '2--Minor', 'Secundária'],
		['MM171_1', '3--No', 'Não é de todo uma razão'],
		['MM171_1', '4--DK--NA', 'Não responde'],
		['MM171_2', '1--Major', 'Importante'],
		['MM171_2', '2--Minor', 'Secundária'],
		['MM171_2', '3--No', 'Não é de todo uma razão'],
		['MM171_2', '4--DK--NA', 'Não responde'],
		['MM171_3', '1--Major', 'Importante'],
		['MM171_3', '2--Minor', 'Secundária'],
		['MM171_3', '3--No', 'Não é de todo uma razão'],
		['MM171_3', '4--DK--NA', 'Não responde'],
		['MM171_4', '1--Major', 'Importante'],
		['MM171_4', '2--Minor', 'Secundária'],
		['MM171_4', '3--No', 'Não é de todo uma razão'],
		['MM171_4', '4--DK--NA', 'Não responde'],
		['MM171_5', '1--Major', 'Importante'],
		['MM171_5', '2--Minor', 'Secundária'],
		['MM171_5', '3--No', 'Não é de todo uma razão'],
		['MM171_5', '4--DK--NA', 'Não responde'],
		['MM171_6', '1--Major', 'Importante'],
		['MM171_6', '2--Minor', 'Secundária'],
		['MM171_6', '3--No', 'Não é de todo uma razão'],
		['MM171_6', '4--DK--NA', 'Não responde'],
		['MM172_1', '1--Major', 'Importante'],
		['MM172_1', '2--Minor', 'Pouco importante'],
		['MM172_1', '3--No', 'Não é uma dificuldade'],
		['MM172_1', '4--DK--NA', 'Não responde'],
		['MM172_2', '1--Major', 'Importante'],
		['MM172_2', '2--Minor', 'Pouco importante'],
		['MM172_2', '3--No', 'Não é uma dificuldade'],
		['MM172_2', '4--DK--NA', 'Não responde'],
		['MM172_3', '1--Major', 'Importante'],
		['MM172_3', '2--Minor', 'Pouco importante'],
		['MM172_3', '3--No', 'Não é uma dificuldade'],
		['MM172_3', '4--DK--NA', 'Não responde'],
		['MM172_4', '1--Major', 'Importante'],
		['MM172_4', '2--Minor', 'Pouco importante'],
		['MM172_4', '3--No', 'Não é uma dificuldade'],
		['MM172_4', '4--DK--NA', 'Não responde'],
		['MM172_5', '1--Major', 'Importante'],
		['MM172_5', '2--Minor', 'Pouco importante'],
		['MM172_5', '3--No', 'Não é uma dificuldade'],
		['MM172_5', '4--DK--NA', 'Não responde'],
		['MM172_6', '1--Major', 'Importante'],
		['MM172_6', '2--Minor', 'Pouco importante'],
		['MM172_6', '3--No', 'Não é uma dificuldade'],
		['MM172_6', '4--DK--NA', 'Não responde'],
		['MM173_1', '1--Yes', 'Sim'],
		['MM173_1', '2--No', 'Não'],
		['MM173_1', '3--DK--NA', 'Não responde'],
		['MM173_2', '1--Yes', 'Sim'],
		['MM173_2', '2--No', 'Não'],
		['MM173_2', '3--DK--NA', 'Não responde'],
		['MM173_3', '1--Yes', 'Sim'],
		['MM173_3', '2--No', 'Não'],
		['MM173_3', '3--DK--NA', 'Não responde'],
		['MM173_4', '1--Yes', 'Sim'],
		['MM173_4', '2--No', 'Não'],
		['MM173_4', '3--DK--NA', 'Não responde'],
		['MM173_5', '1--Yes', 'Sim'],
		['MM173_5', '2--No', 'Não'],
		['MM173_5', '3--DK--NA', 'Não responde'],
		['MM173_6', '1--Yes', 'Sim'],
		['MM173_6', '2--No', 'Não'],
		['MM173_6', '3--DK--NA', 'Não responde'],
		['MM173_7', '1--Yes', 'Sim'],
		['MM173_7', '2--No', 'Não'],
		['MM173_7', '3--DK--NA', 'Não responde'],
		['MM173_8', '1--Yes', 'Sim'],
		['MM173_8', '2--No', 'Não'],
		['MM173_8', '3--DK--NA', 'Não responde'],
		['MM175', '1--Yes', 'Sim'],
		['MM175', '2--No', 'Não'],
		['MM175', '3--DK--NA', 'Não responde'],
		['MM200_1', '1--Major-concern', 'Preocupação importante'],
		['MM200_1', '2--Some-concern', 'Preocupação pouco importante'],
		['MM200_1', '3--No-concern', 'Não é uma preocupação'],
		['MM200_1', '4--DK--NA', 'Não responde'],
		['MM200_2', '1--Major-concern', 'Preocupação importante'],
		['MM200_2', '2--Some-concern', 'Preocupação pouco importante'],
		['MM200_2', '3--No-concern', 'Não é uma preocupação'],
		['MM200_2', '4--DK--NA', 'Não responde'],
		['MM200_3', '1--Major-concern', 'Preocupação importante'],
		['MM200_3', '2--Some-concern', 'Preocupação pouco importante'],
		['MM200_3', '3--No-concern', 'Não é uma preocupação'],
		['MM200_3', '4--DK--NA', 'Não responde'],
		['MM200_4', '1--Major-concern', 'Preocupação importante'],
		['MM200_4', '2--Some-concern', 'Preocupação pouco importante'],
		['MM200_4', '3--No-concern', 'Não é uma preocupação'],
		['MM200_4', '4--DK--NA', 'Não responde'],
		['MM200_5', '1--Major-concern', 'Preocupação importante'],
		['MM200_5', '2--Some-concern', 'Preocupação pouco importante'],
		['MM200_5', '3--No-concern', 'Não é uma preocupação'],
		['MM200_5', '4--DK--NA', 'Não responde'],
		['MM200_6', '1--Major-concern', 'Preocupação importante'],
		['MM200_6', '2--Some-concern', 'Preocupação pouco importante'],
		['MM200_6', '3--No-concern', 'Não é uma preocupação'],
		['MM200_6', '4--DK--NA', 'Não responde'],
		['MM200_7', '1--Major-concern', 'Preocupação importante'],
		['MM200_7', '2--Some-concern', 'Preocupação pouco importante'],
		['MM200_7', '3--No-concern', 'Não é uma preocupação'],
		['MM200_7', '4--DK--NA', 'Não responde'],
		['MM202_1', '1--Yes', 'Sim'],
		['MM202_1', '2--No', 'Não'],
		['MM202_1', '3--DK--NA', 'Não responde'],
		['MM202_10', '1--Yes', 'Sim'],
		['MM202_10', '2--No', 'Não'],
		['MM202_10', '3--DK--NA', 'Não responde'],
		['MM202_2', '1--Yes', 'Sim'],
		['MM202_2', '2--No', 'Não'],
		['MM202_2', '3--DK--NA', 'Não responde'],
		['MM202_3', '1--Yes', 'Sim'],
		['MM202_3', '2--No', 'Não'],
		['MM202_3', '3--DK--NA', 'Não responde'],
		['MM202_4', '1--Yes', 'Sim'],
		['MM202_4', '2--No', 'Não'],
		['MM202_4', '3--DK--NA', 'Não responde'],
		['MM202_5', '1--Yes', 'Sim'],
		['MM202_5', '2--No', 'Não'],
		['MM202_5', '3--DK--NA', 'Não responde'],
		['MM202_6', '1--Yes', 'Sim'],
		['MM202_6', '2--No', 'Não'],
		['MM202_6', '3--DK--NA', 'Não responde'],
		['MM202_7', '1--Yes', 'Sim'],
		['MM202_7', '2--No', 'Não'],
		['MM202_7', '3--DK--NA', 'Não responde'],
		['MM202_8', '1--Yes', 'Sim'],
		['MM202_8', '2--No', 'Não'],
		['MM202_8', '3--DK--NA', 'Não responde'],
		['MM202_9', '1--Yes', 'Sim'],
		['MM202_9', '2--No', 'Não'],
		['MM202_9', '3--DK--NA', 'Não responde'],
		['MM250', '1--Yes', 'Sim'],
		['MM250', '2--No', 'Não'],
		['MM250', '3--Work-related-stress-is-not-an-issue-in-our-establishment', 'O stress relacionado com o trabalho não é um problema no nosso estabelecimento'],
		['MM250', '4--No-answer', 'Não responde'],
		['MM251', '1--Yes', 'Sim'],
		['MM251', '2--No', 'Não'],
		['MM251', '3--These-problems-are-not-an-issue-in-our-establishment', 'Estas questões não são um problema no nosso estabelecimento'],
		['MM251', '4--No-answer', 'Não responde'],
		['MM252', '1--Yes', 'Sim'],
		['MM252', '2--No', 'Não'],
		['MM252', '3--Work-related-violence-is-not-an-issue-in-our-establishment', 'A violência relacionada com o trabalho não é um problema no nosso estabelecimento'],
		['MM252', '4--No-answer', 'Não responde'],
		['MM253_1', '1--Yes', 'Sim'],
		['MM253_1', '2--No', 'Não'],
		['MM253_1', '3--DK--NA', 'Não responde'],
		['MM253_2', '1--Yes', 'Sim'],
		['MM253_2', '2--No', 'Não'],
		['MM253_2', '3--DK--NA', 'Não responde'],
		['MM253_3', '1--Yes', 'Sim'],
		['MM253_3', '2--No', 'Não'],
		['MM253_3', '3--DK--NA', 'Não responde'],
		['MM253_4', '1--Yes', 'Sim'],
		['MM253_4', '2--No', 'Não'],
		['MM253_4', '3--DK--NA', 'Não responde'],
		['MM253_5', '1--Yes', 'Sim'],
		['MM253_5', '2--No', 'Não'],
		['MM253_5', '3--DK--NA', 'Não responde'],
		['MM253_6', '1--Yes', 'Sim'],
		['MM253_6', '2--No', 'Não'],
		['MM253_6', '3--DK--NA', 'Não responde'],
		['MM256', '1--Yes', 'Sim'],
		['MM256', '2--No', 'Não'],
		['MM256', '3--Long-or-irregular-working-hours-are-not-an-issue-in-our-esta', 'Os horários de trabalho longos ou irregulares não são um problema no nosso estabelecimento'],
		['MM256', '4--No-answer', 'Não responde'],
		['MM259', '1--Yes', 'Sim'],
		['MM259', '2--No', 'Não'],
		['MM259', '3--No-answer', 'Não responde'],
		['MM260', '1--Yes', 'Sim'],
		['MM260', '2--No', 'Não'],
		['MM260', '3--No-answer', 'Não responde'],
		['MM300', '1--More-difficult', 'Mais difícil'],
		['MM300', '2--Less-difficult', 'Menos difícil'],
		['MM300', '3--No-difference', 'Não há diferença'],
		['MM300', '4--No-answer', 'Não responde'],
		['MM302', '1--Yes', 'Sim'],
		['MM302', '2--No', 'Não'],
		['MM302', '3--No-answer', 'Não responde'],
		['MM303a', '1--Yes', 'Sim'],
		['MM303a', '2--No', 'Não'],
		['MM303a', '3--No-answer', 'Não responde'],
		['MM350', '1--Yes', 'Sim'],
		['MM350', '2--No', 'Não'],
		['MM350', '3--No-answer', 'Não responde'],
		['MM351', '1--Yes', 'Sim'],
		['MM351', '2--No', 'Não'],
		['MM351', '3--No-answer', 'Não responde'],
		['MM355all', '1--Yes', 'Sim'],
		['MM355all', '2--No', 'Não'],
		['MM355all', '3--No-answer', 'Não responde'],
		['MM358', '1--Yes', 'Sim'],
		['MM358', '2--No', 'Não'],
		['MM358', '3--No-answer', 'Não responde']
	];
var country_
	 = [
	
		['AT', 'Áustria'],
		['BE', 'Bélgica'],
		['BG', 'Bulgária'],
		['CH', 'Suíça'],
		['CY', 'Chipre'],
		['CZ', 'República Checa'],
		['DE', 'Alemanha'],
		['DK', 'Dinamarca'],
		['EE', 'Estónia'],
		['EL', 'Grécia'],
		['ES', 'Espanha'],
		['FI', 'Finlândia'],
		['FR', 'França'],
		['HR', 'Croácia *'],
		['HU', 'Hungria'],
		['IE', 'Irlanda'],
		['IT', 'Itália'],
		['LT', 'Lituânia'],
		['LU', 'Luxemburgo'],
		['LV', 'Letónia'],
		['MT', 'Malta'],
		['NL', 'Países Baixos'],
		['NO', 'Noruega'],
		['PL', 'Polónia'],
		['PT', 'Portugal'],
		['RO', 'Roménia'],
		['SE', 'Suécia'],
		['SI', 'Eslovénia'],
		['SK', 'Eslováquia'],
		['TR', 'Turquia'],
		['UK', 'Reino Unido'],
		['EuropeanUnion', 'União Europeia *']
	];
var question_meta
	 = [
	
		['MM150_1', 'Um médico de medicina do trabalho', 'Que serviços de segurança e saúde usa, quer seja a nível interno ou contratados?Um médico de medicina do trabalho'],
		['MM150_2', 'Um especialista em segurança', 'Que serviços de segurança e saúde usa, quer seja a nível interno ou contratados?Um especialista em segurança'],
		['MM150_3', 'Um psicólogo', 'Que serviços de segurança e saúde usa, quer seja a nível interno ou contratados?Um psicólogo'],
		['MM150_4', 'Um especialista em ergonomia, para lidar com a configuração do local de trabalho', 'Que serviços de segurança e saúde usa, quer seja a nível interno ou contratados?Um especialista em ergonomia, para lidar com a configuração do local de trabalho'],
		['MM150_5', 'Um técnico de segurança e saúde', 'Que serviços de segurança e saúde usa, quer seja a nível interno ou contratados?Um técnico de segurança e saúde'],
		['MM152', 'O seu estabelecimento analisa de forma rotineira as causas das faltas por doença?', 'O seu estabelecimento analisa de forma rotineira as causas das faltas por doença?'],
		['MM153', 'Toma medidas para apoiar o regresso dos trabalhadores ao trabalho depois de um longo período de baixa médica?', 'Toma medidas para apoiar o regresso dos trabalhadores ao trabalho depois de um longo período de baixa médica?'],
		['MM154', 'A saúde dos trabalhadores é monitorizada através de exames médicos regulares?', 'A saúde dos trabalhadores é monitorizada através de exames médicos regulares?'],
		['MM155', 'Existe alguma política documentada, sistema de gestão estabelecido ou plano de acção para a segurança e saúde no seu estabelecimento?', 'Existe alguma política documentada, sistema de gestão estabelecido ou plano de acção para a segurança e saúde no seu estabelecimento?'],
		['MM158', 'As questões da saúde e da segurança e saúde são abordadas em reuniões da direcção de alto nível regularmente, de vez em quando ou praticamente nunca?', 'As questões da saúde e da segurança e saúde são abordadas em reuniões da direcção de alto nível regularmente, de vez em quando ou praticamente nunca?'],
		['MM159', 'De uma forma geral, como classificaria o envolvimento dos directores e supervisores imediatos na gestão da segurança e saúde ? É muito elevado, elevado, baixo ou muito baixo?', 'De uma forma geral, como classificaria o envolvimento dos directores e supervisores imediatos na gestão da segurança e saúde ? É muito elevado, elevado, baixo ou muito baixo?'],
		['MM161', 'Os locais de trabalho neste estabelecimento são regularmente verificados no que respeita à segurança e saúde como parte da avaliação dos riscos ou medidas similares?', 'Os locais de trabalho neste estabelecimento são regularmente verificados no que respeita à segurança e saúde como parte da avaliação dos riscos ou medidas similares?'],
		['MM170', 'A Inspecção do Trabalho visitou este local de trabalho nos últimos 3 anos a fim de verificar as condições de segurança e saúde?', 'A Inspecção do Trabalho visitou este local de trabalho nos últimos 3 anos a fim de verificar as condições de segurança e saúde?'],
		['MM173_1', 'Institutos oficiais para a segurança e saúde no trabalho', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?Institutos oficiais para a segurança e saúde no trabalho'],
		['MM173_2', 'Agência Europeia para a Segurança e Saúde no Trabalho', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?Agência Europeia para a Segurança e Saúde no Trabalho'],
		['MM173_3', 'Serviços internos de segurança e saúde', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?Serviços internos de segurança e saúde'],
		['MM173_4', 'Inspecção do Trabalho', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?Inspecção do Trabalho'],
		['MM173_5', 'Organizações de trabalhadores', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?Organizações de trabalhadores'],
		['MM173_6', 'Sindicatos', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?Sindicatos'],
		['MM173_7', 'Especialistas contratados em segurança e saúde', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?Especialistas contratados em segurança e saúde'],
		['MM173_8', 'Fornecedores de seguros', 'O seu estabelecimento usou as informações sobre segurança e saúde de alguns dos organismos ou instituições que se seguem?Fornecedores de seguros'],
		['MM175', 'Tem conhecimento da Semana Europeia para a Segurança e Saúde no Trabalho?', 'Tem conhecimento da Semana Europeia para a Segurança e Saúde no Trabalho?'],
		['MM200_1', 'Substâncias perigosas (por ex., poeiras produtos químicos, biológicos ou radioactivos)', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimentoSubstâncias perigosas (por ex., poeiras produtos químicos, biológicos ou radioactivos)'],
		['MM200_2', 'Acidentes', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimentoAcidentes'],
		['MM200_3', 'Ruídos e vibrações', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimentoRuídos e vibrações'],
		['MM200_4', 'Doenças musculo-esqueléticas, como dor de costas, pescoço, braços ou pernas', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimentoDoenças musculo-esqueléticas, como dor de costas, pescoço, braços ou pernas'],
		['MM200_5', 'Stresse relacionado com o trabalho', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimentoStresse relacionado com o trabalho'],
		['MM200_6', 'Violência ou ameaça de violência', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimentoViolência ou ameaça de violência'],
		['MM200_7', 'Intimidação ou assédio, ou seja, ofensa, humilhação ou agressão por colegas ou superiores', 'Para cada um dos seguintes problemas, diga-me se é uma preocupação importante, pouco importante ou não é uma preocupação no seu estabelecimentoIntimidação ou assédio, ou seja, ofensa, humilhação ou agressão por colegas ou superiores'],
		['MM202_1', 'Pressão de tempo', 'Vários factores podem contribuir para o stresse, violência ou assédio no local de trabalho; dizem respeito à forma como o trabalho é organizado e são geralmente referidos como riscos psicossociais. Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.Pressão de tempo'],
		['MM202_2', 'Má comunicação entre a direcção e os trabalhadores', 'Vários factores podem contribuir para o stresse, violência ou assédio no local de trabalho; dizem respeito à forma como o trabalho é organizado e são geralmente referidos como riscos psicossociais. Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.Má comunicação entre a direcção e os trabalhadores'],
		['MM202_3', 'Fraca cooperação entre os colegas', 'Vários factores podem contribuir para o stresse, violência ou assédio no local de trabalho; dizem respeito à forma como o trabalho é organizado e são geralmente referidos como riscos psicossociais. Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.Fraca cooperação entre os colegas'],
		['MM202_4', 'Falta de controlo dos trabalhadores na organização do seu trabalho', 'Vários factores podem contribuir para o stresse, violência ou assédio no local de trabalho; dizem respeito à forma como o trabalho é organizado e são geralmente referidos como riscos psicossociais. Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.Falta de controlo dos trabalhadores na organização do seu trabalho'],
		['MM202_5', 'Insegurança no trabalho', 'Vários factores podem contribuir para o stresse, violência ou assédio no local de trabalho; dizem respeito à forma como o trabalho é organizado e são geralmente referidos como riscos psicossociais. Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.Insegurança no trabalho'],
		['MM202_6', 'Ter de lidar com clientes difíceis, doentes, crianças, etc.', 'Vários factores podem contribuir para o stresse, violência ou assédio no local de trabalho; dizem respeito à forma como o trabalho é organizado e são geralmente referidos como riscos psicossociais. Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.Ter de lidar com clientes difíceis, doentes, crianças, etc.'],
		['MM202_7', 'Problemas nas relações entre o supervisor e o empregado', 'Vários factores podem contribuir para o stresse, violência ou assédio no local de trabalho; dizem respeito à forma como o trabalho é organizado e são geralmente referidos como riscos psicossociais. Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.Problemas nas relações entre o supervisor e o empregado'],
		['MM202_8', 'Horários de trabalho longos ou irregulares', 'Vários factores podem contribuir para o stresse, violência ou assédio no local de trabalho; dizem respeito à forma como o trabalho é organizado e são geralmente referidos como riscos psicossociais. Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.Horários de trabalho longos ou irregulares'],
		['MM202_9', 'Uma política de recursos humanos pouco clara', 'Vários factores podem contribuir para o stresse, violência ou assédio no local de trabalho; dizem respeito à forma como o trabalho é organizado e são geralmente referidos como riscos psicossociais. Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.Uma política de recursos humanos pouco clara'],
		['MM202_10', 'Discriminação (por exemplo, devido ao sexo, idade ou etnia)', 'Vários factores podem contribuir para o stresse, violência ou assédio no local de trabalho; dizem respeito à forma como o trabalho é organizado e são geralmente referidos como riscos psicossociais. Diga-me se algum dos seguintes riscos psicossociais são uma preocupação no seu estabelecimento.Discriminação (por exemplo, devido ao sexo, idade ou etnia)'],
		['MM250', 'O seu estabelecimento possui um procedimento para lidar com o stresse relacionado com o trabalho?', 'O seu estabelecimento possui um procedimento para lidar com o stresse relacionado com o trabalho?'],
		['MM251', 'Existe algum procedimento implementado para lidar com as intimidações ou o assédio?', 'Existe algum procedimento implementado para lidar com as intimidações ou o assédio?'],
		['MM252', 'E possui um procedimento para lidar com a violência relacionada com o trabalho?', 'E possui um procedimento para lidar com a violência relacionada com o trabalho?'],
		['MM253_1', 'Alterações na forma como o trabalho é organizado', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?Alterações na forma como o trabalho é organizado'],
		['MM253_2', 'Remodelação da área de trabalho', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?Remodelação da área de trabalho'],
		['MM253_3', 'Aconselhamento confidencial para os trabalhadores', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?Aconselhamento confidencial para os trabalhadores'],
		['MM253_4', 'Implementação de um procedimento de resolução de conflitos', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?Implementação de um procedimento de resolução de conflitos'],
		['MM253_5', 'Alterações às disposições do horário de trabalho', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?Alterações às disposições do horário de trabalho'],
		['MM253_6', 'Fornecimento de formação', 'Nos últimos 3 anos, o seu estabelecimento usou algumas das seguintes medidas para lidar com os riscos psicossociais?Fornecimento de formação'],
		['MM256', 'O seu estabelecimento toma acções se os trabalhadores individuais trabalharem durante muito tempo ou durante horas irregulares?', 'O seu estabelecimento toma acções se os trabalhadores individuais trabalharem durante muito tempo ou durante horas irregulares?'],
		['MM259', 'Informa os trabalhadores sobre os riscos psicossociais e o seu efeito na saúde e na segurança?', 'Informa os trabalhadores sobre os riscos psicossociais e o seu efeito na saúde e na segurança?'],
		['MM260', 'Foram informados sobre quem devem contactar em caso de problemas psicossociais relacionados com o trabalho?', 'Foram informados sobre quem devem contactar em caso de problemas psicossociais relacionados com o trabalho?'],
		['MM171_1', 'Cumprimento das obrigações legais', 'No seu estabelecimento, em que medida as seguintes razões são importantes para lidar com a segurança e saúde? Para cada uma, diga-me se é uma razão importante, secundária ou não é de todo uma razão?Cumprimento das obrigações legais'],
		['MM171_2', 'Pedidos dos trabalhadores ou dos seus representantes', 'No seu estabelecimento, em que medida as seguintes razões são importantes para lidar com a segurança e saúde? Para cada uma, diga-me se é uma razão importante, secundária ou não é de todo uma razão?Pedidos dos trabalhadores ou dos seus representantes'],
		['MM171_3', 'Retenção de trabalhadores e gestão do absentismo', 'No seu estabelecimento, em que medida as seguintes razões são importantes para lidar com a segurança e saúde? Para cada uma, diga-me se é uma razão importante, secundária ou não é de todo uma razão?Retenção de trabalhadores e gestão do absentismo'],
		['MM171_4', 'Razões económicas ou relacionadas com o desempenho', 'No seu estabelecimento, em que medida as seguintes razões são importantes para lidar com a segurança e saúde? Para cada uma, diga-me se é uma razão importante, secundária ou não é de todo uma razão?Razões económicas ou relacionadas com o desempenho'],
		['MM171_5', 'Requisitos de clientes ou preocupações sobre a reputação da organizaçao', 'No seu estabelecimento, em que medida as seguintes razões são importantes para lidar com a segurança e saúde? Para cada uma, diga-me se é uma razão importante, secundária ou não é de todo uma razão?Requisitos de clientes ou preocupações sobre a reputação da organizaçao'],
		['MM171_6', 'Pressão da Inspecção do Trabalho', 'No seu estabelecimento, em que medida as seguintes razões são importantes para lidar com a segurança e saúde? Para cada uma, diga-me se é uma razão importante, secundária ou não é de todo uma razão?Pressão da Inspecção do Trabalho'],
		['MM172_1', 'Falta de recursos, como tempo, pessoal ou verbas', 'No seu estabelecimento, quais são as principais dificuldades em lidar com a segurança e saúde ? Para cada um dos seguintes aspectos, diga-me se é uma dificuldade importante, pouco importante ou não é uma dificuldade.Falta de recursos, como tempo, pessoal ou verbas'],
		['MM172_2', 'Falta de sensibilização', 'No seu estabelecimento, quais são as principais dificuldades em lidar com a segurança e saúde ? Para cada um dos seguintes aspectos, diga-me se é uma dificuldade importante, pouco importante ou não é uma dificuldade.Falta de sensibilização'],
		['MM172_3', 'Falta de competências', 'No seu estabelecimento, quais são as principais dificuldades em lidar com a segurança e saúde ? Para cada um dos seguintes aspectos, diga-me se é uma dificuldade importante, pouco importante ou não é uma dificuldade.Falta de competências'],
		['MM172_4', 'Falta de apoio técnico ou orientação', 'No seu estabelecimento, quais são as principais dificuldades em lidar com a segurança e saúde ? Para cada um dos seguintes aspectos, diga-me se é uma dificuldade importante, pouco importante ou não é uma dificuldade.Falta de apoio técnico ou orientação'],
		['MM172_5', 'A cultura no estabelecimento', 'No seu estabelecimento, quais são as principais dificuldades em lidar com a segurança e saúde ? Para cada um dos seguintes aspectos, diga-me se é uma dificuldade importante, pouco importante ou não é uma dificuldade.A cultura no estabelecimento'],
		['MM172_6', 'A sensibilidade do assunto', 'No seu estabelecimento, quais são as principais dificuldades em lidar com a segurança e saúde ? Para cada um dos seguintes aspectos, diga-me se é uma dificuldade importante, pouco importante ou não é uma dificuldade.A sensibilidade do assunto'],
		['MM300', 'Comparando com outras questões de segurança e saúde, é mais difícil lidar com os riscos psicossociais, menos difícil, ou não existem diferenças?', 'Comparando com outras questões de segurança e saúde, é mais difícil lidar com os riscos psicossociais, menos difícil, ou não existem diferenças?'],
		['MM302', 'Usou informações ou apoio de fontes externas sobre como lidar com os riscos psicossociais no trabalho?', 'Usou informações ou apoio de fontes externas sobre como lidar com os riscos psicossociais no trabalho?'],
		['MM303a', 'Necessita de informações ou apoio adicionais sobre este assunto?', 'Necessita de informações ou apoio adicionais sobre este assunto?<br><br>Pergunta colocada aos estabelecimentos que indicam recorrer a informações ou ao apoio de fontes externas para saberem como lidar com os riscos psicossociais no local de trabalho.'],
		['MM350', 'Existe uma comissão de trabalhadores neste estabelecimento?', 'Existe uma comissão de trabalhadores neste estabelecimento?'],
		['MM351', 'E existe uma comissão sindical ou intersindical no seu estabelecimento?', 'E existe uma comissão sindical ou intersindical no seu estabelecimento?'],
		['MM355all', 'O seu estabelecimento possui um representante dos trabalhadores para a segurança, higiene e saúde no trabalho?', 'O seu estabelecimento possui um representante dos trabalhadores para a segurança, higiene e saúde no trabalho?<br><br>NL: Há algum membro da representante em matéria de saúde e segurança neste estabelecimento?'],
		['MM358', 'Existe uma Comissão de Segurança, Higiene e Saúde no Trabalho no seu estabelecimento?', 'Existe uma Comissão de Segurança, Higiene e Saúde no Trabalho no seu estabelecimento?']
	];
