//Auto Generated file
var subset_
	 = [
	
		['size_4', 'Dimensiunea instituției'],
		['sec3', 'Sectorul de activitate']
	];
var subset_subsetValue
	 = [
	
		['sec3', 'All', 'Toate'],
		['sec3', '1--Producing-Industries', 'Sectorul de producție'],
		['sec3', '2--Private-Services', 'Servicii private'],
		['sec3', '3--Public-Services', 'Servicii publice'],
		['size_4', 'All', 'Toate'],
		['size_4', '1--10-to-19-employees', '10-19 angajați'],
		['size_4', '2--20-to-49-employees', '20-49 angajați'],
		['size_4', '3--50-to-249-employees', '50-249  angajați'],
		['size_4', '4--250-employees-or-more', '250 sau mai mulți angajați']
	];
var topic_
	 = [
	
		['', 'Toate (70)'],
		['Factori de stimulare și impedimente', 'Factori de stimulare și impedimente (15)'],
		['Gestionarea SSM', 'Gestionarea SSM (29)'],
		['Participarea angajaților', 'Participarea angajaților (4)'],
		['Riscurile psihosociale și gestionarea acestora', 'Riscurile psihosociale și gestionarea acestora (22)']
	];
var topic_question
	 = [
	
		['Gestionarea SSM', 'MM150_1', 'Utilizarea serviciilor de securitate și sănătate în muncă: Un medic de medicina muncii'],
		['Gestionarea SSM', 'MM150_2', 'Utilizarea serviciilor de securitate și sănătate în muncă: Un expert în securitate'],
		['Gestionarea SSM', 'MM150_3', 'Utilizarea serviciilor de securitate și sănătate în muncă: Un psiholog'],
		['Gestionarea SSM', 'MM150_4', 'Utilizarea serviciilor de securitate și sănătate în muncă: Un expert în ergonomie, care se ocupă de amenajarea locului de muncă'],
		['Gestionarea SSM', 'MM150_5', 'Utilizarea serviciilor de securitate și sănătate în muncă: Consultanţă generală în materie de securitate şi sănătate'],
		['Gestionarea SSM', 'MM152', 'Întreprinderea dvs. analizează de obicei cauzele concediilor de boală?'],
		['Gestionarea SSM', 'MM153', 'Întreprindeţi măsuri pentru a susţine întoarcerea la serviciu a angajaţilor după un concediu de boală de lungă durată?'],
		['Gestionarea SSM', 'MM154', 'Starea sănătăţii angajaţilor este monitorizată regulat prin investigaţii medicale?'],
		['Gestionarea SSM', 'MM155', 'Există o politică documentată, un sistem stabilit de management, sau vreun plan de acţiuni în domeniul securităţiii şi sănătăţii în muncă în întreprinderea dvs.?'],
		['Gestionarea SSM', 'MM158', 'Problemele referitoare la sănătate şi securitate sunt discutate în şedinţele management-ului la nivel înalt în mod regulat, ocazional sau practic niciodată?'],
		['Gestionarea SSM', 'MM159', 'În general, cum aţi evalua gradul de implicare al managerilor şi supervizorilor în gestiunea problemelor de sănătate şi securitate? Foarte ridicat, destul de ridicat, destul de scăzut, foarte scăzut?'],
		['Gestionarea SSM', 'MM161', 'Locurile de muncă din întreprinderea dvs.sunt verificate periodic cu privire la sănătate şi securitate ca parte a procesului de evaluare a riscurilor sau a altei măsuri similare?'],
		['Gestionarea SSM', 'MM170', 'Inspectoratul de Muncă a vizitat această întreprindere în ultimii 3 ani pentru a verifica condiţiile de sănătate şi securitate?'],
		['Gestionarea SSM', 'MM173_1', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Institute oficiale pentru sănătatea şi securitatea la locul de muncă'],
		['Gestionarea SSM', 'MM173_2', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Agenţia Europeană pentru Securitate şi Sănătate în Muncă'],
		['Gestionarea SSM', 'MM173_3', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Servicii de securitate şi sănătate din cadrul întreprinderii dvs.'],
		['Gestionarea SSM', 'MM173_4', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Inspectoratul de Muncă'],
		['Gestionarea SSM', 'MM173_5', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Organizaţii ale angajatorilor'],
		['Gestionarea SSM', 'MM173_6', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Sindicate'],
		['Gestionarea SSM', 'MM173_7', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Experţi contractaţi în probleme de sănătate şi securitate'],
		['Gestionarea SSM', 'MM173_8', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Prestatori de asigurări'],
		['Gestionarea SSM', 'MM175', 'Aţi auzit de Săptămâna Europeană pentru Securitate şi Sănătate în Muncă?'],
		['Gestionarea SSM', 'MM200_1', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.: Substanțe periculoase (de ex. praf, substanțe chimice, biologice sau radioactive)'],
		['Gestionarea SSM', 'MM200_2', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.: Accidente'],
		['Gestionarea SSM', 'MM200_3', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.: Zgomotul şi vibraţia'],
		['Gestionarea SSM', 'MM200_4', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.: Afecţiuni musculo-scheletice precum dureri de spate, ceafă, braţe sau picioare'],
		['Gestionarea SSM', 'MM200_5', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.: Stresul legat de muncă'],
		['Gestionarea SSM', 'MM200_6', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.: Violenţa sau ameninţarea cu violenţă'],
		['Gestionarea SSM', 'MM200_7', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.: Intimidarea sau hărţuirea, de ex. abuz, umilire sau atacuri din partea colegilor sau superiorilor.'],
		['Riscurile psihosociale și gestionarea acestora', 'MM202_1', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Munca sub presiunea timpului'],
		['Riscurile psihosociale și gestionarea acestora', 'MM202_2', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Comunicarea proastă dintre management şi angajaţi'],
		['Riscurile psihosociale și gestionarea acestora', 'MM202_3', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Cooperarea proastă între colegi'],
		['Riscurile psihosociale și gestionarea acestora', 'MM202_4', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Lipsa controlului angajaţilor în organizarea muncii lor'],
		['Riscurile psihosociale și gestionarea acestora', 'MM202_5', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Insecuritatea muncii'],
		['Riscurile psihosociale și gestionarea acestora', 'MM202_6', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Contactul cu unii clienţi dificili, pacienţi, elevi, etc.'],
		['Riscurile psihosociale și gestionarea acestora', 'MM202_7', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Probleme în relaţiile şef-angajat'],
		['Riscurile psihosociale și gestionarea acestora', 'MM202_8', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Programe de lucru prelungite sau neregulate'],
		['Riscurile psihosociale și gestionarea acestora', 'MM202_9', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:O politică neclară cu privire la resursele umane'],
		['Riscurile psihosociale și gestionarea acestora', 'MM202_10', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Discriminare (de ex. pe bază de gen, vârstă sau etnie)'],
		['Riscurile psihosociale și gestionarea acestora', 'MM250', 'În întreprinderea dvs. exista o procedură pentru abordarea stresului legat de muncă ?'],
		['Riscurile psihosociale și gestionarea acestora', 'MM251', 'Există vreo procedură în vigoare care să soluţioneze situaţiile de intimidare sau hărţuire?'],
		['Riscurile psihosociale și gestionarea acestora', 'MM252', 'Şi aveţi vreo procedură în vigoare care să soluţioneze situaţiile de violenţă la locul de muncă?'],
		['Riscurile psihosociale și gestionarea acestora', 'MM253_1', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?: Schimbări în felul în care este organizată munca'],
		['Riscurile psihosociale și gestionarea acestora', 'MM253_2', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?: Reamenajarea locului de muncă'],
		['Riscurile psihosociale și gestionarea acestora', 'MM253_3', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?: Consiliere confidenţială a angajaţilor'],
		['Riscurile psihosociale și gestionarea acestora', 'MM253_4', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?: Adoptarea unei proceduri de soluţionare a conflictelor'],
		['Riscurile psihosociale și gestionarea acestora', 'MM253_5', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?: Schimbări în aranjamentele cu privire la timpul de muncă'],
		['Riscurile psihosociale și gestionarea acestora', 'MM253_6', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?: Oferirea instruirilor'],
		['Riscurile psihosociale și gestionarea acestora', 'MM256', 'Întreprinderea dvs. ia măsuri dacă unii angajaţi lucrează excesiv ore suplimentare sau neregulate?'],
		['Riscurile psihosociale și gestionarea acestora', 'MM259', 'Îi informaţi pe angajaţi cu privire la riscurile psihosociale şi efectul lor asupra sănătăţii şi securităţii?'],
		['Riscurile psihosociale și gestionarea acestora', 'MM260', 'Aţi fost informat la cine să vă adresaţi în caz de probleme psihosociale legate de serviciu?'],
		['Factori de stimulare și impedimente', 'MM171_1', 'Motive pentru abordarea problemelor legate de securitatea și sănătatea în muncă: Îndeplinirea obligaţiunilor legale'],
		['Factori de stimulare și impedimente', 'MM171_2', 'Motive pentru abordarea problemelor legate de securitatea și sănătatea în muncă: Solicitări de la angajaţi sau reprezentanţii lor'],
		['Factori de stimulare și impedimente', 'MM171_3', 'Motive pentru abordarea problemelor legate de securitatea și sănătatea în muncă: Reţinerea angajaţilor şi management-ul absenţelor'],
		['Factori de stimulare și impedimente', 'MM171_4', 'Motive pentru abordarea problemelor legate de securitatea și sănătatea în muncă: Motive economice sau legate de performanţă'],
		['Factori de stimulare și impedimente', 'MM171_5', 'Motive pentru abordarea problemelor legate de securitatea și sănătatea în muncă: Solicitări de la clienţi sau preocupare cu privire la reputaţia organizaţiei'],
		['Factori de stimulare și impedimente', 'MM171_6', 'Motive pentru abordarea problemelor legate de securitatea și sănătatea în muncă: Presiune din partea Inspectoratului de Muncă'],
		['Factori de stimulare și impedimente', 'MM172_1', 'Principalele dificultăți la abordarea securității și sănătății în muncă: Insuficienţa resurselor precum timp, forţă de muncă sau bani'],
		['Factori de stimulare și impedimente', 'MM172_2', 'Principalele dificultăți la abordarea securității și sănătății în muncă: Insuficienţa informării'],
		['Factori de stimulare și impedimente', 'MM172_3', 'Principalele dificultăți la abordarea securității și sănătății în muncă: insuficenţă de expertiză'],
		['Factori de stimulare și impedimente', 'MM172_4', 'Principalele dificultăți la abordarea securității și sănătății în muncă: Insuficienţă de suport tehnic sau asistenţă'],
		['Factori de stimulare și impedimente', 'MM172_5', 'Principalele dificultăți la abordarea securității și sănătății în muncă: Cultura din cadrul întreprinderii'],
		['Factori de stimulare și impedimente', 'MM172_6', 'Principalele dificultăți la abordarea securității și sănătății în muncă: Sensibilitatea problemei'],
		['Factori de stimulare și impedimente', 'MM300', 'În comparaţie cu alte probleme de sănătate şi securitate: Este mai dificil să gestionezi riscurile psihosociale, mai puţin dificil, sau nu există nicio diferenţă?'],
		['Factori de stimulare și impedimente', 'MM302', 'Aţi folosit informaţii sau suport din surse externe pentru gestionarea riscurilor psihosociale la locul de muncă?'],
		['Factori de stimulare și impedimente', 'MM303a', 'Aţi avea nevoie de informaţii sau asistenţă adiţională cu privire la aceste probleme?'],
		['Participarea angajaților', 'MM350', 'Există reprezentanţi ai salariaţIlor în întreprinderea dvs.?'],
		['Participarea angajaților', 'MM351', 'Există în întreprinderea dvs. vreun sindicat?'],
		['Participarea angajaților', 'MM355all', 'Există în întreprinderea dvs. reprezentanţi pentru sănătate şi securitate în muncă?'],
		['Participarea angajaților', 'MM358', 'Există vreun comitet pentru securitate şi sănătate în muncă în întreprinderea dvs.?']
	];
var question_
	 = [
	
		['MM150_1', 'Utilizarea serviciilor de securitate și sănătate în muncă: Un medic de medicina muncii'],
		['MM150_2', 'Utilizarea serviciilor de securitate și sănătate în muncă: Un expert în securitate'],
		['MM150_3', 'Utilizarea serviciilor de securitate și sănătate în muncă: Un psiholog'],
		['MM150_4', 'Utilizarea serviciilor de securitate și sănătate în muncă: Un expert în ergonomie, care se ocupă de amenajarea locului de muncă'],
		['MM150_5', 'Utilizarea serviciilor de securitate și sănătate în muncă: Consultanţă generală în materie de securitate şi sănătate'],
		['MM152', 'Întreprinderea dvs. analizează de obicei cauzele concediilor de boală?'],
		['MM153', 'Întreprindeţi măsuri pentru a susţine întoarcerea la serviciu a angajaţilor după un concediu de boală de lungă durată?'],
		['MM154', 'Starea sănătăţii angajaţilor este monitorizată regulat prin investigaţii medicale?'],
		['MM155', 'Există o politică documentată, un sistem stabilit de management, sau vreun plan de acţiuni în domeniul securităţiii şi sănătăţii în muncă în întreprinderea dvs.?'],
		['MM158', 'Problemele referitoare la sănătate şi securitate sunt discutate în şedinţele management-ului la nivel înalt în mod regulat, ocazional sau practic niciodată?'],
		['MM159', 'În general, cum aţi evalua gradul de implicare al managerilor şi supervizorilor în gestiunea problemelor de sănătate şi securitate? Foarte ridicat, destul de ridicat, destul de scăzut, foarte scăzut?'],
		['MM161', 'Locurile de muncă din întreprinderea dvs.sunt verificate periodic cu privire la sănătate şi securitate ca parte a procesului de evaluare a riscurilor sau a altei măsuri similare?'],
		['MM170', 'Inspectoratul de Muncă a vizitat această întreprindere în ultimii 3 ani pentru a verifica condiţiile de sănătate şi securitate?'],
		['MM173_1', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Institute oficiale pentru sănătatea şi securitatea la locul de muncă'],
		['MM173_2', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Agenţia Europeană pentru Securitate şi Sănătate în Muncă'],
		['MM173_3', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Servicii de securitate şi sănătate din cadrul întreprinderii dvs.'],
		['MM173_4', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Inspectoratul de Muncă'],
		['MM173_5', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Organizaţii ale angajatorilor'],
		['MM173_6', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Sindicate'],
		['MM173_7', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Experţi contractaţi în probleme de sănătate şi securitate'],
		['MM173_8', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?: Prestatori de asigurări'],
		['MM175', 'Aţi auzit de Săptămâna Europeană pentru Securitate şi Sănătate în Muncă?'],
		['MM200_1', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.: Substanțe periculoase (de ex. praf, substanțe chimice, biologice sau radioactive)'],
		['MM200_2', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.: Accidente'],
		['MM200_3', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.: Zgomotul şi vibraţia'],
		['MM200_4', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.: Afecţiuni musculo-scheletice precum dureri de spate, ceafă, braţe sau picioare'],
		['MM200_5', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.: Stresul legat de muncă'],
		['MM200_6', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.: Violenţa sau ameninţarea cu violenţă'],
		['MM200_7', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.: Intimidarea sau hărţuirea, de ex. abuz, umilire sau atacuri din partea colegilor sau superiorilor.'],
		['MM202_1', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Munca sub presiunea timpului'],
		['MM202_2', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Comunicarea proastă dintre management şi angajaţi'],
		['MM202_3', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Cooperarea proastă între colegi'],
		['MM202_4', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Lipsa controlului angajaţilor în organizarea muncii lor'],
		['MM202_5', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Insecuritatea muncii'],
		['MM202_6', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Contactul cu unii clienţi dificili, pacienţi, elevi, etc.'],
		['MM202_7', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Probleme în relaţiile şef-angajat'],
		['MM202_8', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Programe de lucru prelungite sau neregulate'],
		['MM202_9', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:O politică neclară cu privire la resursele umane'],
		['MM202_10', 'Vă rog să indicați dacă vreunul din următoarele riscuri psihosociale reprezintă o îngrijorare în întreprinderea dvs.?:Discriminare (de ex. pe bază de gen, vârstă sau etnie)'],
		['MM250', 'În întreprinderea dvs. exista o procedură pentru abordarea stresului legat de muncă ?'],
		['MM251', 'Există vreo procedură în vigoare care să soluţioneze situaţiile de intimidare sau hărţuire?'],
		['MM252', 'Şi aveţi vreo procedură în vigoare care să soluţioneze situaţiile de violenţă la locul de muncă?'],
		['MM253_1', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?: Schimbări în felul în care este organizată munca'],
		['MM253_2', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?: Reamenajarea locului de muncă'],
		['MM253_3', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?: Consiliere confidenţială a angajaţilor'],
		['MM253_4', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?: Adoptarea unei proceduri de soluţionare a conflictelor'],
		['MM253_5', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?: Schimbări în aranjamentele cu privire la timpul de muncă'],
		['MM253_6', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?: Oferirea instruirilor'],
		['MM256', 'Întreprinderea dvs. ia măsuri dacă unii angajaţi lucrează excesiv ore suplimentare sau neregulate?'],
		['MM259', 'Îi informaţi pe angajaţi cu privire la riscurile psihosociale şi efectul lor asupra sănătăţii şi securităţii?'],
		['MM260', 'Aţi fost informat la cine să vă adresaţi în caz de probleme psihosociale legate de serviciu?'],
		['MM171_1', 'Motive pentru abordarea problemelor legate de securitatea și sănătatea în muncă: Îndeplinirea obligaţiunilor legale'],
		['MM171_2', 'Motive pentru abordarea problemelor legate de securitatea și sănătatea în muncă: Solicitări de la angajaţi sau reprezentanţii lor'],
		['MM171_3', 'Motive pentru abordarea problemelor legate de securitatea și sănătatea în muncă: Reţinerea angajaţilor şi management-ul absenţelor'],
		['MM171_4', 'Motive pentru abordarea problemelor legate de securitatea și sănătatea în muncă: Motive economice sau legate de performanţă'],
		['MM171_5', 'Motive pentru abordarea problemelor legate de securitatea și sănătatea în muncă: Solicitări de la clienţi sau preocupare cu privire la reputaţia organizaţiei'],
		['MM171_6', 'Motive pentru abordarea problemelor legate de securitatea și sănătatea în muncă: Presiune din partea Inspectoratului de Muncă'],
		['MM172_1', 'Principalele dificultăți la abordarea securității și sănătății în muncă: Insuficienţa resurselor precum timp, forţă de muncă sau bani'],
		['MM172_2', 'Principalele dificultăți la abordarea securității și sănătății în muncă: Insuficienţa informării'],
		['MM172_3', 'Principalele dificultăți la abordarea securității și sănătății în muncă: insuficenţă de expertiză'],
		['MM172_4', 'Principalele dificultăți la abordarea securității și sănătății în muncă: Insuficienţă de suport tehnic sau asistenţă'],
		['MM172_5', 'Principalele dificultăți la abordarea securității și sănătății în muncă: Cultura din cadrul întreprinderii'],
		['MM172_6', 'Principalele dificultăți la abordarea securității și sănătății în muncă: Sensibilitatea problemei'],
		['MM300', 'În comparaţie cu alte probleme de sănătate şi securitate: Este mai dificil să gestionezi riscurile psihosociale, mai puţin dificil, sau nu există nicio diferenţă?'],
		['MM302', 'Aţi folosit informaţii sau suport din surse externe pentru gestionarea riscurilor psihosociale la locul de muncă?'],
		['MM303a', 'Aţi avea nevoie de informaţii sau asistenţă adiţională cu privire la aceste probleme?'],
		['MM350', 'Există reprezentanţi ai salariaţIlor în întreprinderea dvs.?'],
		['MM351', 'Există în întreprinderea dvs. vreun sindicat?'],
		['MM355all', 'Există în întreprinderea dvs. reprezentanţi pentru sănătate şi securitate în muncă?'],
		['MM358', 'Există vreun comitet pentru securitate şi sănătate în muncă în întreprinderea dvs.?']
	];
var question_answer
	 = [
	
		['MM150_1', '1--Yes', 'Da'],
		['MM150_1', '2--No', 'Nu'],
		['MM150_1', '3--DK--NA', 'Nu s-a răspuns'],
		['MM150_2', '1--Yes', 'Da'],
		['MM150_2', '2--No', 'Nu'],
		['MM150_2', '3--DK--NA', 'Nu s-a răspuns'],
		['MM150_3', '1--Yes', 'Da'],
		['MM150_3', '2--No', 'Nu'],
		['MM150_3', '3--DK--NA', 'Nu s-a răspuns'],
		['MM150_4', '1--Yes', 'Da'],
		['MM150_4', '2--No', 'Nu'],
		['MM150_4', '3--DK--NA', 'Nu s-a răspuns'],
		['MM150_5', '1--Yes', 'Da'],
		['MM150_5', '2--No', 'Nu'],
		['MM150_5', '3--DK--NA', 'Nu s-a răspuns'],
		['MM152', '1--Yes', 'Da'],
		['MM152', '2--No', 'Nu'],
		['MM152', '3--DK--NA', 'Nu s-a răspuns'],
		['MM153', '1--Yes', 'Da'],
		['MM153', '2--No', 'Nu'],
		['MM153', '3--DK--NA', 'Nu s-a răspuns'],
		['MM154', '1--Yes', 'Da'],
		['MM154', '2--No', 'Nu'],
		['MM154', '3--DK--NA', 'Nu s-a răspuns'],
		['MM155', '1--Yes', 'Da'],
		['MM155', '2--No', 'Nu'],
		['MM155', '3--DK--NA', 'Nu s-a răspuns'],
		['MM158', '1--Regularly', 'În mod regulat'],
		['MM158', '2--Occasionally', 'Ocazional'],
		['MM158', '3--Practically-never', 'Practic niciodată'],
		['MM158', '4--DK--NA', 'Nu s-a răspuns'],
		['MM159', '1--Very-high', 'Foarte ridicat'],
		['MM159', '2--Quite-high', 'Destul de ridicat'],
		['MM159', '3--Quite-low', 'Destul de scăzut'],
		['MM159', '4--Very-low', 'Foarte scăzut'],
		['MM159', '5--DK--NA', 'Nu s-a răspuns'],
		['MM161', '1--Yes', 'Da'],
		['MM161', '2--No', 'Nu'],
		['MM161', '3--DK--NA', 'Nu s-a răspuns'],
		['MM170', '1--Yes', 'Da'],
		['MM170', '2--No', 'Nu'],
		['MM170', '3--DK--NA', 'Nu s-a răspuns'],
		['MM171_1', '1--Major', 'Motivațe importantă'],
		['MM171_1', '2--Minor', 'Motivațe puțin importantă'],
		['MM171_1', '3--No', 'Nu constituie deloc o motivațe'],
		['MM171_1', '4--DK--NA', 'Nu s-a răspuns'],
		['MM171_2', '1--Major', 'Motivațe importantă'],
		['MM171_2', '2--Minor', 'Motivațe puțin importantă'],
		['MM171_2', '3--No', 'Nu constituie deloc o motivațe'],
		['MM171_2', '4--DK--NA', 'Nu s-a răspuns'],
		['MM171_3', '1--Major', 'Motivațe importantă'],
		['MM171_3', '2--Minor', 'Motivațe puțin importantă'],
		['MM171_3', '3--No', 'Nu constituie deloc o motivațe'],
		['MM171_3', '4--DK--NA', 'Nu s-a răspuns'],
		['MM171_4', '1--Major', 'Motivațe importantă'],
		['MM171_4', '2--Minor', 'Motivațe puțin importantă'],
		['MM171_4', '3--No', 'Nu constituie deloc o motivațe'],
		['MM171_4', '4--DK--NA', 'Nu s-a răspuns'],
		['MM171_5', '1--Major', 'Motivațe importantă'],
		['MM171_5', '2--Minor', 'Motivațe puțin importantă'],
		['MM171_5', '3--No', 'Nu constituie deloc o motivațe'],
		['MM171_5', '4--DK--NA', 'Nu s-a răspuns'],
		['MM171_6', '1--Major', 'Motivațe importantă'],
		['MM171_6', '2--Minor', 'Motivațe puțin importantă'],
		['MM171_6', '3--No', 'Nu constituie deloc o motivațe'],
		['MM171_6', '4--DK--NA', 'Nu s-a răspuns'],
		['MM172_1', '1--Major', 'Dificultate importantă'],
		['MM172_1', '2--Minor', 'Dificultate puțin importantă'],
		['MM172_1', '3--No', 'Nu este o dificultate'],
		['MM172_1', '4--DK--NA', 'Nu s-a răspuns'],
		['MM172_2', '1--Major', 'Dificultate importantă'],
		['MM172_2', '2--Minor', 'Dificultate puțin importantă'],
		['MM172_2', '3--No', 'Nu este o dificultate'],
		['MM172_2', '4--DK--NA', 'Nu s-a răspuns'],
		['MM172_3', '1--Major', 'Dificultate importantă'],
		['MM172_3', '2--Minor', 'Dificultate puțin importantă'],
		['MM172_3', '3--No', 'Nu este o dificultate'],
		['MM172_3', '4--DK--NA', 'Nu s-a răspuns'],
		['MM172_4', '1--Major', 'Dificultate importantă'],
		['MM172_4', '2--Minor', 'Dificultate puțin importantă'],
		['MM172_4', '3--No', 'Nu este o dificultate'],
		['MM172_4', '4--DK--NA', 'Nu s-a răspuns'],
		['MM172_5', '1--Major', 'Dificultate importantă'],
		['MM172_5', '2--Minor', 'Dificultate puțin importantă'],
		['MM172_5', '3--No', 'Nu este o dificultate'],
		['MM172_5', '4--DK--NA', 'Nu s-a răspuns'],
		['MM172_6', '1--Major', 'Dificultate importantă'],
		['MM172_6', '2--Minor', 'Dificultate puțin importantă'],
		['MM172_6', '3--No', 'Nu este o dificultate'],
		['MM172_6', '4--DK--NA', 'Nu s-a răspuns'],
		['MM173_1', '1--Yes', 'Da'],
		['MM173_1', '2--No', 'Nu'],
		['MM173_1', '3--DK--NA', 'Nu s-a răspuns'],
		['MM173_2', '1--Yes', 'Da'],
		['MM173_2', '2--No', 'Nu'],
		['MM173_2', '3--DK--NA', 'Nu s-a răspuns'],
		['MM173_3', '1--Yes', 'Da'],
		['MM173_3', '2--No', 'Nu'],
		['MM173_3', '3--DK--NA', 'Nu s-a răspuns'],
		['MM173_4', '1--Yes', 'Da'],
		['MM173_4', '2--No', 'Nu'],
		['MM173_4', '3--DK--NA', 'Nu s-a răspuns'],
		['MM173_5', '1--Yes', 'Da'],
		['MM173_5', '2--No', 'Nu'],
		['MM173_5', '3--DK--NA', 'Nu s-a răspuns'],
		['MM173_6', '1--Yes', 'Da'],
		['MM173_6', '2--No', 'Nu'],
		['MM173_6', '3--DK--NA', 'Nu s-a răspuns'],
		['MM173_7', '1--Yes', 'Da'],
		['MM173_7', '2--No', 'Nu'],
		['MM173_7', '3--DK--NA', 'Nu s-a răspuns'],
		['MM173_8', '1--Yes', 'Da'],
		['MM173_8', '2--No', 'Nu'],
		['MM173_8', '3--DK--NA', 'Nu s-a răspuns'],
		['MM175', '1--Yes', 'Da'],
		['MM175', '2--No', 'Nu'],
		['MM175', '3--DK--NA', 'Nu s-a răspuns'],
		['MM200_1', '1--Major-concern', 'Preocupare majoră'],
		['MM200_1', '2--Some-concern', 'Oarecum o preocupare'],
		['MM200_1', '3--No-concern', 'Nu este o preocupare'],
		['MM200_1', '4--DK--NA', 'Nu s-a răspuns'],
		['MM200_2', '1--Major-concern', 'Preocupare majoră'],
		['MM200_2', '2--Some-concern', 'Oarecum o preocupare'],
		['MM200_2', '3--No-concern', 'Nu este o preocupare'],
		['MM200_2', '4--DK--NA', 'Nu s-a răspuns'],
		['MM200_3', '1--Major-concern', 'Preocupare majoră'],
		['MM200_3', '2--Some-concern', 'Oarecum o preocupare'],
		['MM200_3', '3--No-concern', 'Nu este o preocupare'],
		['MM200_3', '4--DK--NA', 'Nu s-a răspuns'],
		['MM200_4', '1--Major-concern', 'Preocupare majoră'],
		['MM200_4', '2--Some-concern', 'Oarecum o preocupare'],
		['MM200_4', '3--No-concern', 'Nu este o preocupare'],
		['MM200_4', '4--DK--NA', 'Nu s-a răspuns'],
		['MM200_5', '1--Major-concern', 'Preocupare majoră'],
		['MM200_5', '2--Some-concern', 'Oarecum o preocupare'],
		['MM200_5', '3--No-concern', 'Nu este o preocupare'],
		['MM200_5', '4--DK--NA', 'Nu s-a răspuns'],
		['MM200_6', '1--Major-concern', 'Preocupare majoră'],
		['MM200_6', '2--Some-concern', 'Oarecum o preocupare'],
		['MM200_6', '3--No-concern', 'Nu este o preocupare'],
		['MM200_6', '4--DK--NA', 'Nu s-a răspuns'],
		['MM200_7', '1--Major-concern', 'Preocupare majoră'],
		['MM200_7', '2--Some-concern', 'Oarecum o preocupare'],
		['MM200_7', '3--No-concern', 'Nu este o preocupare'],
		['MM200_7', '4--DK--NA', 'Nu s-a răspuns'],
		['MM202_1', '1--Yes', 'Da'],
		['MM202_1', '2--No', 'Nu'],
		['MM202_1', '3--DK--NA', 'Nu s-a răspuns'],
		['MM202_10', '1--Yes', 'Da'],
		['MM202_10', '2--No', 'Nu'],
		['MM202_10', '3--DK--NA', 'Nu s-a răspuns'],
		['MM202_2', '1--Yes', 'Da'],
		['MM202_2', '2--No', 'Nu'],
		['MM202_2', '3--DK--NA', 'Nu s-a răspuns'],
		['MM202_3', '1--Yes', 'Da'],
		['MM202_3', '2--No', 'Nu'],
		['MM202_3', '3--DK--NA', 'Nu s-a răspuns'],
		['MM202_4', '1--Yes', 'Da'],
		['MM202_4', '2--No', 'Nu'],
		['MM202_4', '3--DK--NA', 'Nu s-a răspuns'],
		['MM202_5', '1--Yes', 'Da'],
		['MM202_5', '2--No', 'Nu'],
		['MM202_5', '3--DK--NA', 'Nu s-a răspuns'],
		['MM202_6', '1--Yes', 'Da'],
		['MM202_6', '2--No', 'Nu'],
		['MM202_6', '3--DK--NA', 'Nu s-a răspuns'],
		['MM202_7', '1--Yes', 'Da'],
		['MM202_7', '2--No', 'Nu'],
		['MM202_7', '3--DK--NA', 'Nu s-a răspuns'],
		['MM202_8', '1--Yes', 'Da'],
		['MM202_8', '2--No', 'Nu'],
		['MM202_8', '3--DK--NA', 'Nu s-a răspuns'],
		['MM202_9', '1--Yes', 'Da'],
		['MM202_9', '2--No', 'Nu'],
		['MM202_9', '3--DK--NA', 'Nu s-a răspuns'],
		['MM250', '1--Yes', 'Da'],
		['MM250', '2--No', 'Nu'],
		['MM250', '3--Work-related-stress-is-not-an-issue-in-our-establishment', 'Stresul legat de muncănu este o problemă în întreprinderea noastră'],
		['MM250', '4--No-answer', 'Nu s-a răspuns'],
		['MM251', '1--Yes', 'Da'],
		['MM251', '2--No', 'Nu'],
		['MM251', '3--These-problems-are-not-an-issue-in-our-establishment', 'Aceste aspecte nu sunt o problemă în întreprinderea noastră'],
		['MM251', '4--No-answer', 'Nu s-a răspuns'],
		['MM252', '1--Yes', 'Da'],
		['MM252', '2--No', 'Nu'],
		['MM252', '3--Work-related-violence-is-not-an-issue-in-our-establishment', 'Violența la locul de muncă nu este o problemă în întreprinderea noastră'],
		['MM252', '4--No-answer', 'Nu s-a răspuns'],
		['MM253_1', '1--Yes', 'Da'],
		['MM253_1', '2--No', 'Nu'],
		['MM253_1', '3--DK--NA', 'Nu s-a răspuns'],
		['MM253_2', '1--Yes', 'Da'],
		['MM253_2', '2--No', 'Nu'],
		['MM253_2', '3--DK--NA', 'Nu s-a răspuns'],
		['MM253_3', '1--Yes', 'Da'],
		['MM253_3', '2--No', 'Nu'],
		['MM253_3', '3--DK--NA', 'Nu s-a răspuns'],
		['MM253_4', '1--Yes', 'Da'],
		['MM253_4', '2--No', 'Nu'],
		['MM253_4', '3--DK--NA', 'Nu s-a răspuns'],
		['MM253_5', '1--Yes', 'Da'],
		['MM253_5', '2--No', 'Nu'],
		['MM253_5', '3--DK--NA', 'Nu s-a răspuns'],
		['MM253_6', '1--Yes', 'Da'],
		['MM253_6', '2--No', 'Nu'],
		['MM253_6', '3--DK--NA', 'Nu s-a răspuns'],
		['MM256', '1--Yes', 'Da'],
		['MM256', '2--No', 'Nu'],
		['MM256', '3--Long-or-irregular-working-hours-are-not-an-issue-in-our-esta', 'Orele de lucru suplimentare lungi şi neregulate nu sunt o problemă în întreprinderea noastră'],
		['MM256', '4--No-answer', 'Nu s-a răspuns'],
		['MM259', '1--Yes', 'Da'],
		['MM259', '2--No', 'Nu'],
		['MM259', '3--No-answer', 'Nu s-a răspuns'],
		['MM260', '1--Yes', 'Da'],
		['MM260', '2--No', 'Nu'],
		['MM260', '3--No-answer', 'Nu s-a răspuns'],
		['MM300', '1--More-difficult', 'Mai dificil'],
		['MM300', '2--Less-difficult', 'Mai puțin dificil'],
		['MM300', '3--No-difference', 'Nu există diferență'],
		['MM300', '4--No-answer', 'Nu s-a răspuns'],
		['MM302', '1--Yes', 'Da'],
		['MM302', '2--No', 'Nu'],
		['MM302', '3--No-answer', 'Nu s-a răspuns'],
		['MM303a', '1--Yes', 'Da'],
		['MM303a', '2--No', 'Nu'],
		['MM303a', '3--No-answer', 'Nu s-a răspuns'],
		['MM350', '1--Yes', 'Da'],
		['MM350', '2--No', 'Nu'],
		['MM350', '3--No-answer', 'Nu s-a răspuns'],
		['MM351', '1--Yes', 'Da'],
		['MM351', '2--No', 'Nu'],
		['MM351', '3--No-answer', 'Nu s-a răspuns'],
		['MM355all', '1--Yes', 'Da'],
		['MM355all', '2--No', 'Nu'],
		['MM355all', '3--No-answer', 'Nu s-a răspuns'],
		['MM358', '1--Yes', 'Da'],
		['MM358', '2--No', 'Nu'],
		['MM358', '3--No-answer', 'Nu s-a răspuns']
	];
var country_
	 = [
	
		['AT', 'Austria'],
		['BE', 'Belgia'],
		['BG', 'Bulgaria'],
		['CH', 'Elveția'],
		['CY', 'Cipru'],
		['CZ', 'Republica Cehă'],
		['DE', 'Germania'],
		['DK', 'Danemarca'],
		['EE', 'Estonia'],
		['EL', 'Grecia'],
		['ES', 'Spania'],
		['FI', 'Finlanda'],
		['FR', 'Franța'],
		['HR', 'Croația*'],
		['HU', 'Ungaria'],
		['IE', 'Irlanda'],
		['IT', 'Italia'],
		['LT', 'Lituania'],
		['LU', 'Luxemburg'],
		['LV', 'Letonia'],
		['MT', 'Malta'],
		['NL', 'Țările de Jos'],
		['NO', 'Norvegia'],
		['PL', 'Polonia'],
		['PT', 'Portugalia'],
		['RO', 'România'],
		['SE', 'Suedia'],
		['SI', 'Slovenia'],
		['SK', 'Slovacia'],
		['TR', 'Turcia'],
		['UK', 'Regatul Unit'],
		['EuropeanUnion', 'Uniunea Europeană*']
	];
var question_meta
	 = [
	
		['MM150_1', 'Un medic de medicina muncii', 'Ce servicii de securitate si sănătate utilizaţi, servicii interne sau externe?Un medic de medicina muncii'],
		['MM150_2', 'Un expert în securitate', 'Ce servicii de securitate si sănătate utilizaţi, servicii interne sau externe?Un expert în securitate'],
		['MM150_3', 'Un psiholog', 'Ce servicii de securitate si sănătate utilizaţi, servicii interne sau externe?Un psiholog'],
		['MM150_4', 'Un expert în ergonomie, care se ocupă de amenajarea locului de muncă', 'Ce servicii de securitate si sănătate utilizaţi, servicii interne sau externe?Un expert în ergonomie, care se ocupă de amenajarea locului de muncă'],
		['MM150_5', 'Consultanţă generală în materie de securitate şi sănătate', 'Ce servicii de securitate si sănătate utilizaţi, servicii interne sau externe?Consultanţă generală în materie de securitate şi sănătate'],
		['MM152', 'Întreprinderea dvs. analizează de obicei cauzele concediilor de boală?', 'Întreprinderea dvs. analizează de obicei cauzele concediilor de boală?'],
		['MM153', 'Întreprindeţi măsuri pentru a susţine întoarcerea la serviciu a angajaţilor după un concediu de boală de lungă durată?', 'Întreprindeţi măsuri pentru a susţine întoarcerea la serviciu a angajaţilor după un concediu de boală de lungă durată?'],
		['MM154', 'Starea sănătăţii angajaţilor este monitorizată regulat prin investigaţii medicale?', 'Starea sănătăţii angajaţilor este monitorizată regulat prin investigaţii medicale?'],
		['MM155', 'Există o politică documentată, un sistem stabilit de management, sau vreun plan de acţiuni în domeniul securităţiii şi sănătăţii în muncă în întreprinderea dvs.?', 'Există o politică documentată, un sistem stabilit de management, sau vreun plan de acţiuni în domeniul securităţiii şi sănătăţii în muncă în întreprinderea dvs.?'],
		['MM158', 'Problemele referitoare la sănătate şi securitate sunt discutate în şedinţele management-ului la nivel înalt în mod regulat, ocazional sau practic niciodată?', 'Problemele referitoare la sănătate şi securitate sunt discutate în şedinţele management-ului la nivel înalt în mod regulat, ocazional sau practic niciodată?'],
		['MM159', 'În general, cum aţi evalua gradul de implicare al managerilor şi supervizorilor în gestiunea problemelor de sănătate şi securitate? Foarte ridicat, destul de ridicat, destul de scăzut, foarte scăzut?', 'În general, cum aţi evalua gradul de implicare al managerilor şi supervizorilor în gestiunea problemelor de sănătate şi securitate? Foarte ridicat, destul de ridicat, destul de scăzut, foarte scăzut?'],
		['MM161', 'Locurile de muncă din întreprinderea dvs.sunt verificate periodic cu privire la sănătate şi securitate ca parte a procesului de evaluare a riscurilor sau a altei măsuri similare?', 'Locurile de muncă din întreprinderea dvs.sunt verificate periodic cu privire la sănătate şi securitate ca parte a procesului de evaluare a riscurilor sau a altei măsuri similare?'],
		['MM170', 'Inspectoratul de Muncă a vizitat această întreprindere în ultimii 3 ani pentru a verifica condiţiile de sănătate şi securitate?', 'Inspectoratul de Muncă a vizitat această întreprindere în ultimii 3 ani pentru a verifica condiţiile de sănătate şi securitate?'],
		['MM173_1', 'Institute oficiale pentru sănătatea şi securitatea la locul de muncă', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?Institute oficiale pentru sănătatea şi securitatea la locul de muncă'],
		['MM173_2', 'Agenţia Europeană pentru Securitate şi Sănătate în Muncă', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?Agenţia Europeană pentru Securitate şi Sănătate în Muncă'],
		['MM173_3', 'Servicii de securitate şi sănătate din cadrul întreprinderii dvs.', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?Servicii de securitate şi sănătate din cadrul întreprinderii dvs.'],
		['MM173_4', 'Inspectoratul de Muncă', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?Inspectoratul de Muncă'],
		['MM173_5', 'Organizaţii ale angajatorilor', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?Organizaţii ale angajatorilor'],
		['MM173_6', 'Sindicate', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?Sindicate'],
		['MM173_7', 'Experţi contractaţi în probleme de sănătate şi securitate', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?Experţi contractaţi în probleme de sănătate şi securitate'],
		['MM173_8', 'Prestatori de asigurări', 'Întreprinderea dvs. a utilizat informaţii referitoare la sănătate şi securitate din vreuna din organizaţiile sau instituţiile următoare?Prestatori de asigurări'],
		['MM175', 'Aţi auzit de Săptămâna Europeană pentru Securitate şi Sănătate în Muncă?', 'Aţi auzit de Săptămâna Europeană pentru Securitate şi Sănătate în Muncă?'],
		['MM200_1', 'Substanțe periculoase (de ex. praf, substanțe chimice, biologice sau radioactive)', 'Pentru fiecare din urmÄƒtoarele subiecte, vÄƒ rog sÄƒ indicaÅ£i dacÄƒ este de o preocupare majorÄƒ, oarecum o preocupare sau nu este o preocupare deloc Ã®n Ã®ntreprinderea dvs.: SubstanÅ£e periculoase (Operator: explicaÅ£i dacÄƒ e necesar: de ex. praf, substanÅ£e chimice, biologice sau radioactive)'],
		['MM200_2', 'Accidente', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.Accidente'],
		['MM200_3', 'Zgomotul şi vibraţia', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.Zgomotul şi vibraţia'],
		['MM200_4', 'Afecţiuni musculo-scheletice precum dureri de spate, ceafă, braţe sau picioare', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.Afecţiuni musculo-scheletice precum dureri de spate, ceafă, braţe sau picioare'],
		['MM200_5', 'Stresul legat de muncă', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.Stresul legat de muncă'],
		['MM200_6', 'Violenţa sau ameninţarea cu violenţă', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.Violenţa sau ameninţarea cu violenţă'],
		['MM200_7', 'Intimidarea sau hărţuirea, de ex. abuz, umilire sau atacuri din partea colegilor sau superiorilor.', 'Pentru fiecare din următoarele subiecte, vă rog să indicaţi dacă este de o preocupare majoră, oarecum o preocupare sau nu este o preocupare deloc în întreprinderea dvs.Intimidarea sau hărţuirea, de ex. abuz, umilire sau atacuri din partea colegilor sau superiorilor.'],
		['MM202_1', 'Munca sub presiunea timpului', 'O serie de factori pot contribui la stres, violenÅ£Äƒ ÅŸi hÄƒrÅ£uire Ã®n muncÄƒ; aceÅŸtia se referÄƒ la felul Ã®n care este organizatÄƒ munca ÅŸi deseori sunt cunoscuÅ£i sub denumirea de " riscuri psihosociale". VÄƒ rog sÄƒ indicaÅ£i dacÄƒ vreunul din urmÄƒtoarele riscuri psihosociale reprezintÄƒ o Ã®ngrijorare Ã®n Ã®ntreprinderea dvs.?: Munca sub presiunea timpului'],
		['MM202_2', 'Comunicarea proastă dintre management şi angajaţi', 'O serie de factori pot contribui la stres, violenÅ£Äƒ ÅŸi hÄƒrÅ£uire Ã®n muncÄƒ; aceÅŸtia se referÄƒ la felul Ã®n care este organizatÄƒ munca ÅŸi deseori sunt cunoscuÅ£i sub denumirea de " riscuri psihosociale". VÄƒ rog sÄƒ indicaÅ£i dacÄƒ vreunul din urmÄƒtoarele riscuri psihosociale reprezintÄƒ o Ã®ngrijorare Ã®n Ã®ntreprinderea dvs.?: Comunicarea proastÄƒ dintre management ÅŸi angajaÅ£i'],
		['MM202_3', 'Cooperarea proastă între colegi', 'O serie de factori pot contribui la stres, violenÅ£Äƒ ÅŸi hÄƒrÅ£uire Ã®n muncÄƒ; aceÅŸtia se referÄƒ la felul Ã®n care este organizatÄƒ munca ÅŸi deseori sunt cunoscuÅ£i sub denumirea de " riscuri psihosociale". VÄƒ rog sÄƒ indicaÅ£i dacÄƒ vreunul din urmÄƒtoarele riscuri psihosociale reprezintÄƒ o Ã®ngrijorare Ã®n Ã®ntreprinderea dvs.?: Cooperarea proastÄƒ Ã®ntre colegi'],
		['MM202_4', 'Lipsa controlului angajaţilor în organizarea muncii lor', 'O serie de factori pot contribui la stres, violenÅ£Äƒ ÅŸi hÄƒrÅ£uire Ã®n muncÄƒ; aceÅŸtia se referÄƒ la felul Ã®n care este organizatÄƒ munca ÅŸi deseori sunt cunoscuÅ£i sub denumirea de " riscuri psihosociale". VÄƒ rog sÄƒ indicaÅ£i dacÄƒ vreunul din urmÄƒtoarele riscuri psihosociale reprezintÄƒ o Ã®ngrijorare Ã®n Ã®ntreprinderea dvs.?: Lipsa controlului angajaÅ£ilor Ã®n organizarea muncii lor'],
		['MM202_5', 'Insecuritatea muncii', 'O serie de factori pot contribui la stres, violenÅ£Äƒ ÅŸi hÄƒrÅ£uire Ã®n muncÄƒ; aceÅŸtia se referÄƒ la felul Ã®n care este organizatÄƒ munca ÅŸi deseori sunt cunoscuÅ£i sub denumirea de " riscuri psihosociale". VÄƒ rog sÄƒ indicaÅ£i dacÄƒ vreunul din urmÄƒtoarele riscuri psihosociale reprezintÄƒ o Ã®ngrijorare Ã®n Ã®ntreprinderea dvs.?: Insecuritatea muncii'],
		['MM202_6', 'Contactul cu unii clienţi dificili, pacienţi, elevi, etc.', 'O serie de factori pot contribui la stres, violenÅ£Äƒ ÅŸi hÄƒrÅ£uire Ã®n muncÄƒ; aceÅŸtia se referÄƒ la felul Ã®n care este organizatÄƒ munca ÅŸi deseori sunt cunoscuÅ£i sub denumirea de " riscuri psihosociale". VÄƒ rog sÄƒ indicaÅ£i dacÄƒ vreunul din urmÄƒtoarele riscuri psihosociale reprezintÄƒ o Ã®ngrijorare Ã®n Ã®ntreprinderea dvs.?: Contactul cu unii clienÅ£i dificili, pacienÅ£i, elevi, etc.'],
		['MM202_7', 'Probleme în relaţiile şef-angajat', 'O serie de factori pot contribui la stres, violenÅ£Äƒ ÅŸi hÄƒrÅ£uire Ã®n muncÄƒ; aceÅŸtia se referÄƒ la felul Ã®n care este organizatÄƒ munca ÅŸi deseori sunt cunoscuÅ£i sub denumirea de " riscuri psihosociale". VÄƒ rog sÄƒ indicaÅ£i dacÄƒ vreunul din urmÄƒtoarele riscuri psihosociale reprezintÄƒ o Ã®ngrijorare Ã®n Ã®ntreprinderea dvs.?: Probleme Ã®n relaÅ£iile ÅŸef-angajat'],
		['MM202_8', 'Programe de lucru prelungite sau neregulate', 'O serie de factori pot contribui la stres, violenÅ£Äƒ ÅŸi hÄƒrÅ£uire Ã®n muncÄƒ; aceÅŸtia se referÄƒ la felul Ã®n care este organizatÄƒ munca ÅŸi deseori sunt cunoscuÅ£i sub denumirea de " riscuri psihosociale". VÄƒ rog sÄƒ indicaÅ£i dacÄƒ vreunul din urmÄƒtoarele riscuri psihosociale reprezintÄƒ o Ã®ngrijorare Ã®n Ã®ntreprinderea dvs.?: Programe de lucru prelungite sau neregulate'],
		['MM202_9', 'O politică neclară cu privire la resursele umane', 'O serie de factori pot contribui la stres, violenÅ£Äƒ ÅŸi hÄƒrÅ£uire Ã®n muncÄƒ; aceÅŸtia se referÄƒ la felul Ã®n care este organizatÄƒ munca ÅŸi deseori sunt cunoscuÅ£i sub denumirea de " riscuri psihosociale". VÄƒ rog sÄƒ indicaÅ£i dacÄƒ vreunul din urmÄƒtoarele riscuri psihosociale reprezintÄƒ o Ã®ngrijorare Ã®n Ã®ntreprinderea dvs.?: O politicÄƒ neclarÄƒ cu privire la resursele umane'],
		['MM202_10', 'Discriminare (de ex. pe bază de gen, vârstă sau etnie)', 'O serie de factori pot contribui la stres, violenÅ£Äƒ ÅŸi hÄƒrÅ£uire Ã®n muncÄƒ; aceÅŸtia se referÄƒ la felul Ã®n care este organizatÄƒ munca ÅŸi deseori sunt cunoscuÅ£i sub denumirea de " riscuri psihosociale". VÄƒ rog sÄƒ indicaÅ£i dacÄƒ vreunul din urmÄƒtoarele riscuri psihosociale reprezintÄƒ o Ã®ngrijorare Ã®n Ã®ntreprinderea dvs.?: Discriminare (de ex. pe bazÄƒ de gen, vÃ¢rstÄƒ sau etnie)'],
		['MM250', 'În întreprinderea dvs. exista o procedură pentru abordarea stresului legat de muncă ?', 'În întreprinderea dvs. exista o procedură pentru abordarea stresului legat de muncă ?'],
		['MM251', 'Există vreo procedură în vigoare care să soluţioneze situaţiile de intimidare sau hărţuire?', 'Există vreo procedură în vigoare care să soluţioneze situaţiile de intimidare sau hărţuire?'],
		['MM252', 'Şi aveţi vreo procedură în vigoare care să soluţioneze situaţiile de violenţă la locul de muncă?', 'Şi aveţi vreo procedură în vigoare care să soluţioneze situaţiile de violenţă la locul de muncă?'],
		['MM253_1', 'Schimbări în felul în care este organizată munca', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?Schimbări în felul în care este organizată munca'],
		['MM253_2', 'Reamenajarea locului de muncă', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?Reamenajarea locului de muncă'],
		['MM253_3', 'Consiliere confidenţială a angajaţilor', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?Consiliere confidenţială a angajaţilor'],
		['MM253_4', 'Adoptarea unei proceduri de soluţionare a conflictelor', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?Adoptarea unei proceduri de soluţionare a conflictelor'],
		['MM253_5', 'Schimbări în aranjamentele cu privire la timpul de muncă', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?Schimbări în aranjamentele cu privire la timpul de muncă'],
		['MM253_6', 'Oferirea instruirilor', 'Pe parcursul ultimilor 3 ani, întreprinderea dvs. a recurs la vreuna din următoarele măsuri pentru a diminua riscurile psihosociale?Oferirea instruirilor'],
		['MM256', 'Întreprinderea dvs. ia măsuri dacă unii angajaţi lucrează excesiv ore suplimentare sau neregulate?', 'Întreprinderea dvs. ia măsuri dacă unii angajaţi lucrează excesiv ore suplimentare sau neregulate?'],
		['MM259', 'Îi informaţi pe angajaţi cu privire la riscurile psihosociale şi efectul lor asupra sănătăţii şi securităţii?', 'Îi informaţi pe angajaţi cu privire la riscurile psihosociale şi efectul lor asupra sănătăţii şi securităţii?'],
		['MM260', 'Aţi fost informat la cine să vă adresaţi în caz de probleme psihosociale legate de serviciu?', 'Aţi fost informat la cine să vă adresaţi în caz de probleme psihosociale legate de serviciu?'],
		['MM171_1', 'Îndeplinirea obligaţiunilor legale', 'În întreprinderea dvs. cât de importante sunt următoarele motivaţii de rezolvare a problemelor de sănătate şi securitate? Pentru fiecare din următoarele, vă rog să indicaţi dacă este o motivaţie importantă, puţin importantă, sau nu constituie deloc o motivaţie .Îndeplinirea obligaţiunilor legale'],
		['MM171_2', 'Solicitări de la angajaţi sau reprezentanţii lor', 'În întreprinderea dvs. cât de importante sunt următoarele motivaţii de rezolvare a problemelor de sănătate şi securitate? Pentru fiecare din următoarele, vă rog să indicaţi dacă este o motivaţie importantă, puţin importantă, sau nu constituie deloc o motivaţie .Solicitări de la angajaţi sau reprezentanţii lor'],
		['MM171_3', 'Reţinerea angajaţilor şi management-ul absenţelor', 'În întreprinderea dvs. cât de importante sunt următoarele motivaţii de rezolvare a problemelor de sănătate şi securitate? Pentru fiecare din următoarele, vă rog să indicaţi dacă este o motivaţie importantă, puţin importantă, sau nu constituie deloc o motivaţie .Reţinerea angajaţilor şi management-ul absenţelor'],
		['MM171_4', 'Motive economice sau legate de performanţă', 'În întreprinderea dvs. cât de importante sunt următoarele motivaţii de rezolvare a problemelor de sănătate şi securitate? Pentru fiecare din următoarele, vă rog să indicaţi dacă este o motivaţie importantă, puţin importantă, sau nu constituie deloc o motivaţie .Motive economice sau legate de performanţă'],
		['MM171_5', 'Solicitări de la clienţi sau preocupare cu privire la reputaţia organizaţiei', 'În întreprinderea dvs. cât de importante sunt următoarele motivaţii de rezolvare a problemelor de sănătate şi securitate? Pentru fiecare din următoarele, vă rog să indicaţi dacă este o motivaţie importantă, puţin importantă, sau nu constituie deloc o motivaţie .Solicitări de la clienţi sau preocupare cu privire la reputaţia organizaţiei'],
		['MM171_6', 'Presiune din partea Inspectoratului de Muncă', 'În întreprinderea dvs. cât de importante sunt următoarele motivaţii de rezolvare a problemelor de sănătate şi securitate? Pentru fiecare din următoarele, vă rog să indicaţi dacă este o motivaţie importantă, puţin importantă, sau nu constituie deloc o motivaţie .Presiune din partea Inspectoratului de Muncă'],
		['MM172_1', 'Insuficienţa resurselor precum timp, forţă de muncă sau bani', 'În întreprinderea dvs. care sunt dificultăţile majore în soluţionarea problemelor de sănătate şi securitate? Pentru fiecare din următoarele, vă rog să indicaţi dacă este o dificultate importantă, puţin importantă, sau nu este o dificultate deloc.Insuficienţa resurselor precum timp, forţă de muncă sau bani'],
		['MM172_2', 'Insuficienţa informării', 'În întreprinderea dvs. care sunt dificultăţile majore în soluţionarea problemelor de sănătate şi securitate? Pentru fiecare din următoarele, vă rog să indicaţi dacă este o dificultate importantă, puţin importantă, sau nu este o dificultate deloc.Insuficienţa informării'],
		['MM172_3', 'insuficenţă de expertiză', 'În întreprinderea dvs. care sunt dificultăţile majore în soluţionarea problemelor de sănătate şi securitate? Pentru fiecare din următoarele, vă rog să indicaţi dacă este o dificultate importantă, puţin importantă, sau nu este o dificultate deloc.insuficenţă de expertiză'],
		['MM172_4', 'Insuficienţă de suport tehnic sau asistenţă', 'În întreprinderea dvs. care sunt dificultăţile majore în soluţionarea problemelor de sănătate şi securitate? Pentru fiecare din următoarele, vă rog să indicaţi dacă este o dificultate importantă, puţin importantă, sau nu este o dificultate deloc.Insuficienţă de suport tehnic sau asistenţă'],
		['MM172_5', 'Cultura din cadrul întreprinderii', 'În întreprinderea dvs. care sunt dificultăţile majore în soluţionarea problemelor de sănătate şi securitate? Pentru fiecare din următoarele, vă rog să indicaţi dacă este o dificultate importantă, puţin importantă, sau nu este o dificultate deloc.Cultura din cadrul întreprinderii'],
		['MM172_6', 'Sensibilitatea problemei', 'În întreprinderea dvs. care sunt dificultăţile majore în soluţionarea problemelor de sănătate şi securitate? Pentru fiecare din următoarele, vă rog să indicaţi dacă este o dificultate importantă, puţin importantă, sau nu este o dificultate deloc.Sensibilitatea problemei'],
		['MM300', 'În comparaţie cu alte probleme de sănătate şi securitate: Este mai dificil să gestionezi riscurile psihosociale, mai puţin dificil, sau nu există nicio diferenţă?', 'În comparaţie cu alte probleme de sănătate şi securitate: Este mai dificil să gestionezi riscurile psihosociale, mai puţin dificil, sau nu există nicio diferenţă?'],
		['MM302', 'Aţi folosit informaţii sau suport din surse externe pentru gestionarea riscurilor psihosociale la locul de muncă?', 'Aţi folosit informaţii sau suport din surse externe pentru gestionarea riscurilor psihosociale la locul de muncă?'],
		['MM303a', 'Aţi avea nevoie de informaţii sau asistenţă adiţională cu privire la aceste probleme?', 'Aţi avea nevoie de informaţii sau asistenţă adiţională cu privire la aceste probleme?<br><br>Întrebare adresată întreprinderilor care declară că apelează la informații sau asistență din surse externe pentru a ști cum să abordeze riscurile psihosociale la locul de muncă.'],
		['MM350', 'Există reprezentanţi ai salariaţIlor în întreprinderea dvs.?', 'Există reprezentanţi ai salariaţIlor în întreprinderea dvs.?'],
		['MM351', 'Există în întreprinderea dvs. vreun sindicat?', 'Există în întreprinderea dvs. vreun sindicat?'],
		['MM355all', 'Există în întreprinderea dvs. reprezentanţi pentru sănătate şi securitate în muncă?', 'Există în întreprinderea dvs. reprezentanţi pentru sănătate şi securitate în muncă?<br><br>NL: Există în această întreprindere un membru al reprezentant pe probleme de sănătate şi securitate?'],
		['MM358', 'Există vreun comitet pentru securitate şi sănătate în muncă în întreprinderea dvs.?', 'Există vreun comitet pentru securitate şi sănătate în muncă în întreprinderea dvs.?']
	];
