//Auto Generated file
var subset_
	 = [
	
		['Y11_Agecategory', 'Age'],
		['Y11_HH2a', 'Gender'],
		['Y11_Incomequartiles_percapita', 'Income']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'All ages'],
		['Y11_Agecategory', '1--18-24y', '18 to 24 years'],
		['Y11_Agecategory', '2--25-34y', '25 to 34 years'],
		['Y11_Agecategory', '3--35-49y', '35 to 49 years'],
		['Y11_Agecategory', '4--50-64y', '50 to 64 years'],
		['Y11_Agecategory', '5---64y', '> 64 years'],
		['Y11_HH2a', 'All', 'Both genders'],
		['Y11_HH2a', '1--Female', 'Female'],
		['Y11_HH2a', '2--Male', 'Male'],
		['Y11_Incomequartiles_percapita', 'All', 'All income levels'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Lowest'],
		['Y11_Incomequartiles_percapita', '2--2nd', '2nd'],
		['Y11_Incomequartiles_percapita', '3--3rd', '3rd'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Highest']
	];
var topic_
	 = [
	
		['', 'All (67)'],
		['Employment and work-life balance', 'Employment and work-life balance (8)'],
		['Health and public services', 'Health and public services (11)'],
		['Home and local environment', 'Home and local environment (9)'],
		['Quality of society', 'Quality of society (12)'],
		['Social exclusion and community involvement', 'Social exclusion and community involvement (7)'],
		['Standard of living and deprivation', 'Standard of living and deprivation (10)'],
		['Subjective well-being', 'Subjective well-being (10)']
	];
var topic_question
	 = [
	
		['Employment and work-life balance', 'Y11_Q12a', 'I have come home from work too tired to do household jobs'],
		['Employment and work-life balance', 'Y11_Q12b', 'It has been difficult to fufil family responsibilities because of time spent on job'],
		['Employment and work-life balance', 'Y11_Q12c', 'I have found it difficult to concentrate at work because of family responsibilities'],
		['Employment and work-life balance', 'Y11_Q15', 'How likely is it that you might lose your job in the next 6 months?'],
		['Employment and work-life balance', 'Y11_Q36b', 'How often are you involved in cooking or housework?'],
		['Employment and work-life balance', 'Y11_Q36c', 'How often are you involved in caring for your elderly or disabled relatives?'],
		['Employment and work-life balance', 'Y11_Q38', 'Attitude to share of housework'],
		['Employment and work-life balance', 'Y11_Q39d_stress', 'Stress'],
		['Health and public services', 'Y11_Q42', 'Perceived health status'],
		['Health and public services', 'Y11_Q46d_WHO5', 'WHO-5 mental well-being scale'],
		['Health and public services', 'Y11_Q47a', 'Difficulty in seeing a doctor because of distance'],
		['Health and public services', 'Y11_Q47b', 'Difficulty in seeing a doctor because of delay in getting an appointment'],
		['Health and public services', 'Y11_Q47c', 'Difficulty in seeing a doctor because of waiting time on the day of appointment'],
		['Health and public services', 'Y11_Q47d', 'Difficulty in seeing a doctor because of cost'],
		['Health and public services', 'Y11_Q53a', 'How would you rate the quality of health services in your country?'],
		['Health and public services', 'Y11_Q53b', 'How would you rate the quality of the education system in your country?'],
		['Health and public services', 'Y11_Q53c', 'How would you rate the quality of public transport in your country?'],
		['Health and public services', 'Y11_Q53d', 'How would you rate the quality of child care services in your country?'],
		['Health and public services', 'Y11_Q53g', 'How would you rate the quality of the state pension system in your country?'],
		['Home and local environment', 'Y11_Accommproblems', 'Number of problems with accommodation'],
		['Home and local environment', 'Y11_Q18', 'Home ownership'],
		['Home and local environment', 'Y11_Q19a', 'Problems with accommodation: Shortage of space'],
		['Home and local environment', 'Y11_Q19b', 'Problems with accommodation: Rot in windows, doors or floors'],
		['Home and local environment', 'Y11_Q19c', 'Problems with accommodation: Damp or leaks in walls or roof'],
		['Home and local environment', 'Y11_Q19d', 'Problems with accommodation: Lack of indoor flushing toilet'],
		['Home and local environment', 'Y11_Q19e', 'Problems with accommodation: Lack of bath or shower'],
		['Home and local environment', 'Y11_Q19f', 'Problems with accommodation: Lack of place to sit outside'],
		['Home and local environment', 'Y11_Q20', 'How likely is it that you will need to leave your accommodation in the next 6 months because you cannot afford it?'],
		['Quality of society', 'Y11_Q24', 'Would you say that most people can be trusted or that you can`t be too careful in dealing with people?'],
		['Quality of society', 'Y11_Q25a', 'Perceived tension between poor and rich people'],
		['Quality of society', 'Y11_Q25b', 'Perceived tension between management and workers'],
		['Quality of society', 'Y11_Q25c', 'Perceived tension between men and women'],
		['Quality of society', 'Y11_Q25d', 'Perceived tension between old people and young people'],
		['Quality of society', 'Y11_Q25e', 'Perceived tension between different racial and ethnic groups'],
		['Quality of society', 'Y11_Q25f', 'Perceived tension between different religious groups'],
		['Quality of society', 'Y11_Q28a', 'Trust in the parliament'],
		['Quality of society', 'Y11_Q28b', 'Trust in the legal system'],
		['Quality of society', 'Y11_Q28c', 'Trust in the press'],
		['Quality of society', 'Y11_Q28d', 'Trust in the police'],
		['Quality of society', 'Y11_Q28e', 'Trust in the government'],
		['Social exclusion and community involvement', 'Y11_Q23a', 'Attended a meeting of a trade union, political party or action group in last 12 months'],
		['Social exclusion and community involvement', 'Y11_Q23d', 'Contacted a politician or public official (other than routine contact through public services)'],
		['Social exclusion and community involvement', 'Y11_Q29e', 'I feel left out of society'],
		['Social exclusion and community involvement', 'Y11_Q29f', 'Life has become so complicated today that I almost can`t find my way'],
		['Social exclusion and community involvement', 'Y11_Q29g', 'I feel that the value of what I do is not recognised by others'],
		['Social exclusion and community involvement', 'Y11_Q29h', 'Some people look down on me because of my job situation or income'],
		['Social exclusion and community involvement', 'Y11_SocExIndex', 'Social Exclusion Index'],
		['Standard of living and deprivation', 'Y11_Deprindex', 'Deprivation index: Number of items household cannot afford'],
		['Standard of living and deprivation', 'Y11_Q58', 'Is your household able to make ends meet?'],
		['Standard of living and deprivation', 'Y11_Q59a', 'Can you afford to keep your home adequately warm?'],
		['Standard of living and deprivation', 'Y11_Q59b', 'Can you afford to pay for a week`s annual holiday away from home?'],
		['Standard of living and deprivation', 'Y11_Q59c', 'Can you afford to replace any worn-out furniture?'],
		['Standard of living and deprivation', 'Y11_Q59d', 'Can you afford a meal with meat, chicken or fish every second day (if you wanted it)?'],
		['Standard of living and deprivation', 'Y11_Q59e', 'Can you afford to buy new, rather than second-hand clothes?'],
		['Standard of living and deprivation', 'Y11_Q59f', 'Can you afford to have friends or family for a drink or meal at least once a month?'],
		['Standard of living and deprivation', 'Y11_Q60a', 'Has your household been in arrears for rent or mortgage payments in the last 12 months?'],
		['Standard of living and deprivation', 'Y11_Q60b', 'Has your household been in arrears for utility bills in the last 12 months?'],
		['Subjective well-being', 'Y11_Q29a', 'I am optimistic about the future'],
		['Subjective well-being', 'Y11_Q30', 'How satisfied are you with your life these days?'],
		['Subjective well-being', 'Y11_Q40a', 'Satisfaction with education'],
		['Subjective well-being', 'Y11_Q40b', 'Satisfaction with present job'],
		['Subjective well-being', 'Y11_Q40c', 'Satisfaction with present standard of living'],
		['Subjective well-being', 'Y11_Q40d', 'Satisfaction with accommodation'],
		['Subjective well-being', 'Y11_Q40e', 'Satisfaction with family life'],
		['Subjective well-being', 'Y11_Q40f', 'Satisfaction with health'],
		['Subjective well-being', 'Y11_Q40g', 'Satisfaction with social life'],
		['Subjective well-being', 'Y11_Q41', 'Taking all things together, how happy would you say you are?']
	];
var question_
	 = [
	
		['Y11_Q12a', 'I have come home from work too tired to do household jobs'],
		['Y11_Q12b', 'It has been difficult to fufil family responsibilities because of time spent on job'],
		['Y11_Q12c', 'I have found it difficult to concentrate at work because of family responsibilities'],
		['Y11_Q15', 'How likely is it that you might lose your job in the next 6 months?'],
		['Y11_Q36b', 'How often are you involved in cooking or housework?'],
		['Y11_Q36c', 'How often are you involved in caring for your elderly or disabled relatives?'],
		['Y11_Q38', 'Attitude to share of housework'],
		['Y11_Q39d_stress', 'Stress'],
		['Y11_Q42', 'Perceived health status'],
		['Y11_Q46d_WHO5', 'WHO-5 mental well-being scale'],
		['Y11_Q47a', 'Difficulty in seeing a doctor because of distance'],
		['Y11_Q47b', 'Difficulty in seeing a doctor because of delay in getting an appointment'],
		['Y11_Q47c', 'Difficulty in seeing a doctor because of waiting time on the day of appointment'],
		['Y11_Q47d', 'Difficulty in seeing a doctor because of cost'],
		['Y11_Q53a', 'How would you rate the quality of health services in your country?'],
		['Y11_Q53b', 'How would you rate the quality of the education system in your country?'],
		['Y11_Q53c', 'How would you rate the quality of public transport in your country?'],
		['Y11_Q53d', 'How would you rate the quality of child care services in your country?'],
		['Y11_Q53g', 'How would you rate the quality of the state pension system in your country?'],
		['Y11_Accommproblems', 'Number of problems with accommodation'],
		['Y11_Q18', 'Home ownership'],
		['Y11_Q19a', 'Problems with accommodation: Shortage of space'],
		['Y11_Q19b', 'Problems with accommodation: Rot in windows, doors or floors'],
		['Y11_Q19c', 'Problems with accommodation: Damp or leaks in walls or roof'],
		['Y11_Q19d', 'Problems with accommodation: Lack of indoor flushing toilet'],
		['Y11_Q19e', 'Problems with accommodation: Lack of bath or shower'],
		['Y11_Q19f', 'Problems with accommodation: Lack of place to sit outside'],
		['Y11_Q20', 'How likely is it that you will need to leave your accommodation in the next 6 months because you cannot afford it?'],
		['Y11_Q24', 'Would you say that most people can be trusted or that you can`t be too careful in dealing with people?'],
		['Y11_Q25a', 'Perceived tension between poor and rich people'],
		['Y11_Q25b', 'Perceived tension between management and workers'],
		['Y11_Q25c', 'Perceived tension between men and women'],
		['Y11_Q25d', 'Perceived tension between old people and young people'],
		['Y11_Q25e', 'Perceived tension between different racial and ethnic groups'],
		['Y11_Q25f', 'Perceived tension between different religious groups'],
		['Y11_Q28a', 'Trust in the parliament'],
		['Y11_Q28b', 'Trust in the legal system'],
		['Y11_Q28c', 'Trust in the press'],
		['Y11_Q28d', 'Trust in the police'],
		['Y11_Q28e', 'Trust in the government'],
		['Y11_Q23a', 'Attended a meeting of a trade union, political party or action group in last 12 months'],
		['Y11_Q23d', 'Contacted a politician or public official (other than routine contact through public services)'],
		['Y11_Q29e', 'I feel left out of society'],
		['Y11_Q29f', 'Life has become so complicated today that I almost can`t find my way'],
		['Y11_Q29g', 'I feel that the value of what I do is not recognised by others'],
		['Y11_Q29h', 'Some people look down on me because of my job situation or income'],
		['Y11_SocExIndex', 'Social Exclusion Index'],
		['Y11_Deprindex', 'Deprivation index: Number of items household cannot afford'],
		['Y11_Q58', 'Is your household able to make ends meet?'],
		['Y11_Q59a', 'Can you afford to keep your home adequately warm?'],
		['Y11_Q59b', 'Can you afford to pay for a week`s annual holiday away from home?'],
		['Y11_Q59c', 'Can you afford to replace any worn-out furniture?'],
		['Y11_Q59d', 'Can you afford a meal with meat, chicken or fish every second day (if you wanted it)?'],
		['Y11_Q59e', 'Can you afford to buy new, rather than second-hand clothes?'],
		['Y11_Q59f', 'Can you afford to have friends or family for a drink or meal at least once a month?'],
		['Y11_Q60a', 'Has your household been in arrears for rent or mortgage payments in the last 12 months?'],
		['Y11_Q60b', 'Has your household been in arrears for utility bills in the last 12 months?'],
		['Y11_Q29a', 'I am optimistic about the future'],
		['Y11_Q30', 'How satisfied are you with your life these days?'],
		['Y11_Q40a', 'Satisfaction with education'],
		['Y11_Q40b', 'Satisfaction with present job'],
		['Y11_Q40c', 'Satisfaction with present standard of living'],
		['Y11_Q40d', 'Satisfaction with accommodation'],
		['Y11_Q40e', 'Satisfaction with family life'],
		['Y11_Q40f', 'Satisfaction with health'],
		['Y11_Q40g', 'Satisfaction with social life'],
		['Y11_Q41', 'Taking all things together, how happy would you say you are?']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Mean'],
		['Y11_Deprindex', 'Mean', 'Mean'],
		['Y11_Q12a', '1--Several-times-a-week', 'Several times a week'],
		['Y11_Q12a', '2--Several-times-a-month', 'Several times a month'],
		['Y11_Q12a', '3--Several-times-a-year', 'Several times a year'],
		['Y11_Q12a', '4--Less-often-rarely', 'Less often or rarely'],
		['Y11_Q12a', '5--Never', 'Never'],
		['Y11_Q12b', '1--Several-times-a-week', 'Several times a week'],
		['Y11_Q12b', '2--Several-times-a-month', 'Several times a month'],
		['Y11_Q12b', '3--Several-times-a-year', 'Several times a year'],
		['Y11_Q12b', '4--Less-often-rarely', 'Less often or rarely'],
		['Y11_Q12b', '5--Never', 'Never'],
		['Y11_Q12c', '1--Several-times-a-week', 'Several times a week'],
		['Y11_Q12c', '2--Several-times-a-month', 'Several times a month'],
		['Y11_Q12c', '3--Several-times-a-year', 'Several times a year'],
		['Y11_Q12c', '4--Less-often-rarely', 'Less often or rarely'],
		['Y11_Q12c', '5--Never', 'Never'],
		['Y11_Q15', '1--Very-likely', 'Very likely'],
		['Y11_Q15', '2--Quite-likely', 'Quite likely'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Neither likely nor unlikely'],
		['Y11_Q15', '4--Quite-unlikely', 'Quite unlikely'],
		['Y11_Q15', '5--Very-unlikely', 'Very unlikely'],
		['Y11_Q18', '1--Own-without-mortgage', 'Own without mortgage'],
		['Y11_Q18', '2--Own-with-mortgage', 'Own with mortgage'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Tenant, paying rent in social or voluntary or municipal housing'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Tenant, paying rent to private landlord'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Accommodation is provided rent free'],
		['Y11_Q18', '6--Other', 'Other'],
		['Y11_Q19a', '1--Yes', 'Yes'],
		['Y11_Q19a', '2--No', 'No'],
		['Y11_Q19b', '1--Yes', 'Yes'],
		['Y11_Q19b', '2--No', 'No'],
		['Y11_Q19c', '1--Yes', 'Yes'],
		['Y11_Q19c', '2--No', 'No'],
		['Y11_Q19d', '1--Yes', 'Yes'],
		['Y11_Q19d', '2--No', 'No'],
		['Y11_Q19e', '1--Yes', 'Yes'],
		['Y11_Q19e', '2--No', 'No'],
		['Y11_Q19f', '1--Yes', 'Yes'],
		['Y11_Q19f', '2--No', 'No'],
		['Y11_Q20', '1--Very-likely', 'Very likely'],
		['Y11_Q20', '2--Quite-likely', 'Quite likely'],
		['Y11_Q20', '3--Quite-unlikely', 'Quite unlikely'],
		['Y11_Q20', '4--Very-unlikely', 'Very unlikely'],
		['Y11_Q23a', '1--Yes', 'Yes'],
		['Y11_Q23a', '2--No', 'No'],
		['Y11_Q23d', '1--Yes', 'Yes'],
		['Y11_Q23d', '2--No', 'No'],
		['Y11_Q24', 'Mean', 'Mean'],
		['Y11_Q25a', '1--A-lot-of--tension', 'A lot of  tension'],
		['Y11_Q25a', '2--Some-tension', 'Some tension'],
		['Y11_Q25a', '3--No-tension', 'No tension'],
		['Y11_Q25b', '1--A-lot-of--tension', 'A lot of  tension'],
		['Y11_Q25b', '2--Some-tension', 'Some tension'],
		['Y11_Q25b', '3--No-tension', 'No tension'],
		['Y11_Q25c', '1--A-lot-of--tension', 'A lot of  tension'],
		['Y11_Q25c', '2--Some-tension', 'Some tension'],
		['Y11_Q25c', '3--No-tension', 'No tension'],
		['Y11_Q25d', '1--A-lot-of--tension', 'A lot of  tension'],
		['Y11_Q25d', '2--Some-tension', 'Some tension'],
		['Y11_Q25d', '3--No-tension', 'No tension'],
		['Y11_Q25e', '1--A-lot-of--tension', 'A lot of  tension'],
		['Y11_Q25e', '2--Some-tension', 'Some tension'],
		['Y11_Q25e', '3--No-tension', 'No tension'],
		['Y11_Q25f', '1--A-lot-of--tension', 'A lot of  tension'],
		['Y11_Q25f', '2--Some-tension', 'Some tension'],
		['Y11_Q25f', '3--No-tension', 'No tension'],
		['Y11_Q28a', 'Mean', 'Mean'],
		['Y11_Q28b', 'Mean', 'Mean'],
		['Y11_Q28c', 'Mean', 'Mean'],
		['Y11_Q28d', 'Mean', 'Mean'],
		['Y11_Q28e', 'Mean', 'Mean'],
		['Y11_Q29a', '1--Strongly-agree', 'Strongly agree'],
		['Y11_Q29a', '2--Agree', 'Agree'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Neither agree nor disagree'],
		['Y11_Q29a', '4--Disagree', 'Disagree'],
		['Y11_Q29a', '5--Strongly-disagree', 'Strongly disagree'],
		['Y11_Q29e', '1--Strongly-agree', 'Strongly agree'],
		['Y11_Q29e', '2--Agree', 'Agree'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Neither agree nor disagree'],
		['Y11_Q29e', '4--Disagree', 'Disagree'],
		['Y11_Q29e', '5--Strongly-disagree', 'Strongly disagree'],
		['Y11_Q29f', '1--Strongly-agree', 'Strongly agree'],
		['Y11_Q29f', '2--Agree', 'Agree'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Neither agree nor disagree'],
		['Y11_Q29f', '4--Disagree', 'Disagree'],
		['Y11_Q29f', '5--Strongly-disagree', 'Strongly disagree'],
		['Y11_Q29g', '1--Strongly-agree', 'Strongly agree'],
		['Y11_Q29g', '2--Agree', 'Agree'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Neither agree nor disagree'],
		['Y11_Q29g', '4--Disagree', 'Disagree'],
		['Y11_Q29g', '5--Strongly-disagree', 'Strongly disagree'],
		['Y11_Q29h', '1--Strongly-agree', 'Strongly agree'],
		['Y11_Q29h', '2--Agree', 'Agree'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Neither agree nor disagree'],
		['Y11_Q29h', '4--Disagree', 'Disagree'],
		['Y11_Q29h', '5--Strongly-disagree', 'Strongly disagree'],
		['Y11_Q30', 'Mean', 'Mean'],
		['Y11_Q36b', '1--Every-day', 'Every day'],
		['Y11_Q36b', '2--Several-days-a-week', 'Several days a week'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'Once or twice a week'],
		['Y11_Q36b', '4--Less-often', 'Less often'],
		['Y11_Q36b', '5--Never', 'Never'],
		['Y11_Q36c', '1--Every-day', 'Every day'],
		['Y11_Q36c', '2--Several-days-a-week', 'Several days a week'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'Once or twice a week'],
		['Y11_Q36c', '4--Less-often', 'Less often'],
		['Y11_Q36c', '5--Never', 'Never'],
		['Y11_Q38', '1--More-than-your-fair-share', 'More than your fair share'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Just about your fair share'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Less than your fair share'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'At work and at home'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Either at work or at home'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Little or no stress'],
		['Y11_Q40a', 'Mean', 'Mean'],
		['Y11_Q40b', 'Mean', 'Mean'],
		['Y11_Q40c', 'Mean', 'Mean'],
		['Y11_Q40d', 'Mean', 'Mean'],
		['Y11_Q40e', 'Mean', 'Mean'],
		['Y11_Q40f', 'Mean', 'Mean'],
		['Y11_Q40g', 'Mean', 'Mean'],
		['Y11_Q41', 'Mean', 'Mean'],
		['Y11_Q42', '1--Very-good', 'Very good'],
		['Y11_Q42', '2--Good', 'Good'],
		['Y11_Q42', '3--Fair', 'Fair'],
		['Y11_Q42', '4--Bad', 'Bad'],
		['Y11_Q42', '5--Very-bad', 'Very bad'],
		['Y11_Q46d_WHO5', 'Mean', 'Mean'],
		['Y11_Q47a', '1--Very-difficult', 'Very difficult'],
		['Y11_Q47a', '2--A-little-difficult', 'A little difficult'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Not difficult at all'],
		['Y11_Q47b', '1--Very-difficult', 'Very difficult'],
		['Y11_Q47b', '2--A-little-difficult', 'A little difficult'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Not difficult at all'],
		['Y11_Q47c', '1--Very-difficult', 'Very difficult'],
		['Y11_Q47c', '2--A-little-difficult', 'A little difficult'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Not difficult at all'],
		['Y11_Q47d', '1--Very-difficult', 'Very difficult'],
		['Y11_Q47d', '2--A-little-difficult', 'A little difficult'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Not difficult at all'],
		['Y11_Q53a', 'Mean', 'Mean'],
		['Y11_Q53b', 'Mean', 'Mean'],
		['Y11_Q53c', 'Mean', 'Mean'],
		['Y11_Q53d', 'Mean', 'Mean'],
		['Y11_Q53g', 'Mean', 'Mean'],
		['Y11_Q58', '1--With-great-difficulty', 'With great difficulty'],
		['Y11_Q58', '2--With-difficulty', 'With difficulty'],
		['Y11_Q58', '3--With-some-difficulty', 'With some difficulty'],
		['Y11_Q58', '4--Fairly-easily', 'Fairly easily'],
		['Y11_Q58', '5--Easily', 'Easily'],
		['Y11_Q58', '6--Very-easily', 'Very easily'],
		['Y11_Q59a', '1--No', 'No'],
		['Y11_Q59a', '2--Yes', 'Yes'],
		['Y11_Q59b', '1--No', 'No'],
		['Y11_Q59b', '2--Yes', 'Yes'],
		['Y11_Q59c', '1--No', 'No'],
		['Y11_Q59c', '2--Yes', 'Yes'],
		['Y11_Q59d', '1--No', 'No'],
		['Y11_Q59d', '2--Yes', 'Yes'],
		['Y11_Q59e', '1--No', 'No'],
		['Y11_Q59e', '2--Yes', 'Yes'],
		['Y11_Q59f', '1--No', 'No'],
		['Y11_Q59f', '2--Yes', 'Yes'],
		['Y11_Q60a', '1--Yes', 'Yes'],
		['Y11_Q60a', '2--No', 'No'],
		['Y11_Q60b', '1--Yes', 'Yes'],
		['Y11_Q60b', '2--No', 'No'],
		['Y11_SocExIndex', 'Mean', 'Mean']
	];
var country_
	 = [
	
		['AT', 'Austria'],
		['BE', 'Belgium'],
		['BG', 'Bulgaria'],
		['CY', 'Cyprus'],
		['CZ', 'Czech Republic'],
		['DE', 'Germany'],
		['DK', 'Denmark'],
		['EE', 'Estonia'],
		['EL', 'Greece'],
		['ES', 'Spain'],
		['FI', 'Finland'],
		['FR', 'France'],
		['HR', 'Croatia'],
		['HU', 'Hungary'],
		['IE', 'Ireland'],
		['IT', 'Italy'],
		['LT', 'Lithuania'],
		['LU', 'Luxembourg'],
		['LV', 'Latvia'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Netherlands'],
		['NO', 'Norway'],
		['PL', 'Poland'],
		['PT', 'Portugal'],
		['RO', 'Romania'],
		['SE', 'Sweden'],
		['SI', 'Slovenia'],
		['SK', 'Slovakia'],
		['TR', 'Turkey'],
		['UK', 'United Kingdom'],
		['EuropeanUnion', 'European Union']
	];
var question_meta
	 = [
	
		['Y11_Q12a', 'I have come home from work too tired to do household jobs', ''],
		['Y11_Q12b', 'It has been difficult to fufil family responsibilities because of time spent on job', ''],
		['Y11_Q12c', 'I have found it difficult to concentrate at work because of family responsibilities', ''],
		['Y11_Q15', 'How likely is it that you might lose your job in the next 6 months?', ''],
		['Y11_Q36b', 'How often are you involved in cooking or housework?', ''],
		['Y11_Q36c', 'How often are you involved in caring for your elderly or disabled relatives?', ''],
		['Y11_Q38', 'What do you think about the share of housework you do?', ''],
		['Y11_Q39d_stress', 'Stress due to work-life balance issues', ''],
		['Y11_Q42', 'Perceived health status', ''],
		['Y11_Q46d_WHO5', 'WHO-5 mental well-being scale', ''],
		['Y11_Q47a', 'Difficulty in seeing a doctor because of distance to doctor`s office or hospital', ''],
		['Y11_Q47b', 'Difficulty in seeing a doctor because of delay in getting an appointment', ''],
		['Y11_Q47c', 'Difficulty in seeing a doctor because of waiting time to see doctor on the day of appointment', ''],
		['Y11_Q47d', 'Difficulty in seeing a doctor because of cost of seeing the doctor', ''],
		['Y11_Q53a', 'How would you rate the quality of health services in your country?', ''],
		['Y11_Q53b', 'How would you rate the quality of the education system in your country?', ''],
		['Y11_Q53c', 'How would you rate the quality of public transport in your country?', ''],
		['Y11_Q53d', 'How would you rate the quality of child care services in your country?', ''],
		['Y11_Q53g', 'How would you rate the quality of the state pension system in your country?', ''],
		['Y11_Accommproblems', 'Number of problems with accommodation', ''],
		['Y11_Q18', 'Home ownership', ''],
		['Y11_Q19a', 'Problems with accommodation: Shortage of space', ''],
		['Y11_Q19b', 'Problems with accommodation: Rot in windows, doors or floors', ''],
		['Y11_Q19c', 'Problems with accommodation: Damp or leaks in walls or roof', ''],
		['Y11_Q19d', 'Problems with accommodation: Lack of indoor flushing toilet', ''],
		['Y11_Q19e', 'Problems with accommodation: Lack of bath or shower', ''],
		['Y11_Q19f', 'Problems with accommodation: Lack of place to sit outside', ''],
		['Y11_Q20', 'How likely is it that you will need to leave your accommodation in the next 6 months because you can no longer afford it?', ''],
		['Y11_Q24', 'Would you say that most people can be trusted or that you can`t be too careful in dealing with people?', ''],
		['Y11_Q25a', 'Perceived tension between poor and rich people', ''],
		['Y11_Q25b', 'Perceived tension between management and workers', ''],
		['Y11_Q25c', 'Perceived tension between men and women', ''],
		['Y11_Q25d', 'Perceived tension between old people and young people', ''],
		['Y11_Q25e', 'Perceived tension between different racial and ethnic groups', ''],
		['Y11_Q25f', 'Perceived tension between different religious groups', ''],
		['Y11_Q28a', 'Trust in the parliament', ''],
		['Y11_Q28b', 'Trust in the legal system', ''],
		['Y11_Q28c', 'Trust in the press', ''],
		['Y11_Q28d', 'Trust in the police', ''],
		['Y11_Q28e', 'Trust in the government', ''],
		['Y11_Q23a', 'Attended a meeting of a trade union, political party or action group in last 12 months', ''],
		['Y11_Q23d', 'Contacted a politician or public official (other than routine contact through public services)', ''],
		['Y11_Q29e', 'I feel left out of society', ''],
		['Y11_Q29f', 'Life has become so complicated today that I almost can`t find my way', ''],
		['Y11_Q29g', 'I feel that the value of what I do is not recognised by others', ''],
		['Y11_Q29h', 'Some people look down on me because of my job situation or income', ''],
		['Y11_SocExIndex', 'Social Exclusion Index', ''],
		['Y11_Deprindex', 'Deprivation index: Number of items household cannot afford', ''],
		['Y11_Q58', 'Is your household able to make ends meet?', ''],
		['Y11_Q59a', 'Can you afford to keep your home adequately warm?', ''],
		['Y11_Q59b', 'Can you afford to pay for a week`s annual holiday away from home?', ''],
		['Y11_Q59c', 'Can you afford to replace any worn-out furniture?', ''],
		['Y11_Q59d', 'Can your household afford a meal with meat, chicken or fish every second day (if you wanted it)?', ''],
		['Y11_Q59e', 'Can members of your household afford to buy new, rather than second-hand clothes?', ''],
		['Y11_Q59f', 'Can your household afford to have friends or family for a drink or meal at least once a month?', ''],
		['Y11_Q60a', 'Has your household been in arrears for rent or mortgage payments in the last 12 months?', ''],
		['Y11_Q60b', 'Has your household been in arrears for utility bills in the last 12 months?', ''],
		['Y11_Q29a', 'I am optimistic about the future', ''],
		['Y11_Q30', 'How satisfied are you with your life these days?', ''],
		['Y11_Q40a', 'Satisfaction with education', ''],
		['Y11_Q40b', 'Satisfaction with present job', ''],
		['Y11_Q40c', 'Satisfaction with present standard of living', ''],
		['Y11_Q40d', 'Satisfaction with accommodation', ''],
		['Y11_Q40e', 'Satisfaction with family life', ''],
		['Y11_Q40f', 'Satisfaction with health', ''],
		['Y11_Q40g', 'Satisfaction with social life', ''],
		['Y11_Q41', 'Taking all things together, how happy would you say you are?', '']
	];
