//Auto Generated file
var subset_
	 = [
	
		['Y11_Incomequartiles_percapita', 'Sissetulek'],
		['Y11_HH2a', 'Sugu'],
		['Y11_Agecategory', 'Vanus']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Kõik vanused'],
		['Y11_Agecategory', '1--18-24y', '18 - 24 aastat'],
		['Y11_Agecategory', '2--25-34y', '25 - 34 aastat'],
		['Y11_Agecategory', '3--35-49y', '35 - 49 aastat'],
		['Y11_Agecategory', '4--50-64y', '50 - 64 aastat'],
		['Y11_Agecategory', '5---64y', 'üle 64 aasta'],
		['Y11_HH2a', 'All', 'Mõlemad sood'],
		['Y11_HH2a', '1--Female', 'Naine'],
		['Y11_HH2a', '2--Male', 'Mees'],
		['Y11_Incomequartiles_percapita', 'All', 'Kõik sissetulekutasemed'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Kõige madalam'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'Teine'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'Kolmas'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Kõige kõrgem']
	];
var topic_
	 = [
	
		['', 'Kõik (67)'],
		['Elatustase ja vaesus', 'Elatustase ja vaesus (10)'],
		['Kodu ja kohalik keskkond', 'Kodu ja kohalik keskkond (9)'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses (7)'],
		['Subjektiivne heaolu', 'Subjektiivne heaolu (10)'],
		['Tervishoiu- jms riiklikud teenused', 'Tervishoiu- jms riiklikud teenused (11)'],
		['Töö- ja eraelu tasakaal', 'Töö- ja eraelu tasakaal (8)'],
		['Ühiskonna kvaliteet', 'Ühiskonna kvaliteet (12)']
	];
var topic_question
	 = [
	
		['Elatustase ja vaesus', 'Y11_Deprindex', 'Ainelise puuduse indeks: nende asjade arv, mida leibkonnad ei saa endale lubada'],
		['Elatustase ja vaesus', 'Y11_Q58', 'Kas teie leibkond saab olemasolevate vahenditega hakkama?'],
		['Elatustase ja vaesus', 'Y11_Q59a', 'Kas teie kodu kütmine on teile jõukohane?'],
		['Elatustase ja vaesus', 'Y11_Q59b', 'Kas teile on jõukohane minna kord aastas nädalaks puhkusele kodunt kaugele?'],
		['Elatustase ja vaesus', 'Y11_Q59c', 'Kas teile on jõukohane osta oma aja ära elanud mööbli asemel uut?'],
		['Elatustase ja vaesus', 'Y11_Q59d', 'Kas teile on jõukohane süüa soovi korral ülepäeviti loomaliha, kanaliha või kala?'],
		['Elatustase ja vaesus', 'Y11_Q59e', 'Kas teile on jõukohane osta uusi (mitte kasutatud) riideid?'],
		['Elatustase ja vaesus', 'Y11_Q59f', 'Kas teile on jõukohane võõrustada vähemalt kord kuus söögi või joogiga sõpru või lähedasi?'],
		['Elatustase ja vaesus', 'Y11_Q60a', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud üüri- või laenumaksete võlgnevusi?'],
		['Elatustase ja vaesus', 'Y11_Q60b', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud kommunaalteenuste maksete võlgnevusi?'],
		['Kodu ja kohalik keskkond', 'Y11_Accommproblems', 'Eluaseme probleemide arv'],
		['Kodu ja kohalik keskkond', 'Y11_Q18', 'Kodu omamine'],
		['Kodu ja kohalik keskkond', 'Y11_Q19a', 'Eluasemeprobleemid: ruumipuudus'],
		['Kodu ja kohalik keskkond', 'Y11_Q19b', 'Eluasemeprobleemid: pehkinud aknad, uksed või põrandad'],
		['Kodu ja kohalik keskkond', 'Y11_Q19c', 'Eluasemeprobleemid: niiskus/lekked seintes või katuses'],
		['Kodu ja kohalik keskkond', 'Y11_Q19d', 'Eluasemeprobleemid: puudub vesiklosett'],
		['Kodu ja kohalik keskkond', 'Y11_Q19e', 'Eluasemeprobleemid: puudub vann või dušš'],
		['Kodu ja kohalik keskkond', 'Y11_Q19f', 'Eluasemeprobleemid: puudub koht väljas istumiseks'],
		['Kodu ja kohalik keskkond', 'Y11_Q20', 'Kui tõenäoliseks peate vajadust lahkuda oma elukohast järgneva kuue kuu jooksul, kuna ei suuda enam selle eest maksta?'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q23a', 'Osalemine ametiühingu, erakonna või kodanikualgatusrühma koosolekul viimase 12 kuu jooksul'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q23d', 'Poliitiku või ametniku poole pöördumine (v.a seoses tavapäraste riiklike teenustega)'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q29e', 'Tunnen end sotsiaalselt tõrjutuna'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q29f', 'Tänapäeva elu on läinud nii keeruliseks, et mul on juba raske toime tulla'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q29g', 'Mul on tunne, et teised ei väärtusta mind'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_Q29h', 'Mõnikord halvustatakse mind mu tööalase olukorra või sissetuleku tõttu'],
		['Sotsiaalne tõrjutus ja osalemine kogukonna tegevuses', 'Y11_SocExIndex', 'Sotsiaalse tõrjutuse indeks'],
		['Subjektiivne heaolu', 'Y11_Q29a', 'Olen tuleviku suhtes optimistlik'],
		['Subjektiivne heaolu', 'Y11_Q30', 'Kui rahul olete oma eluga praegu?'],
		['Subjektiivne heaolu', 'Y11_Q40a', 'Rahulolu haridusega'],
		['Subjektiivne heaolu', 'Y11_Q40b', 'Rahulolu praeguse tööga'],
		['Subjektiivne heaolu', 'Y11_Q40c', 'Rahulolu praeguse elatustasemega'],
		['Subjektiivne heaolu', 'Y11_Q40d', 'Rahulolu eluasemega'],
		['Subjektiivne heaolu', 'Y11_Q40e', 'Rahulolu pereeluga'],
		['Subjektiivne heaolu', 'Y11_Q40f', 'Rahulolu tervisega'],
		['Subjektiivne heaolu', 'Y11_Q40g', 'Rahulolu seltskondliku eluga'],
		['Subjektiivne heaolu', 'Y11_Q41', 'Kõike arvesse võttes, kui rahul te oma eluga olete?'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q42', 'Terviseseisund enda hinnangul'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q46d_WHO5', 'WHO-5 vaimse heaolu skaala'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q47a', 'Raskused arsti juurde pääsemisel kauguse tõttu'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q47b', 'Raskused arsti juurde pääsemisel viivituse tõttu arsti vastuvõtule pääsemisel'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q47c', 'Raskused arsti juurde pääsemisel ooteaja tõttu arsti vastuvõtule visiidi päeval'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q47d', 'Raskused arsti juurde pääsemisel kulude tõttu'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q53a', 'Milliseks hindaksite tervishoiuteenuste kvaliteedi Eestis?'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q53b', 'Milliseks hindaksite haridussüsteemi kvaliteedi Eestis?'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q53c', 'Milliseks hindaksite ühistranspordi kvaliteedi Eestis?'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q53d', 'Milliseks hindaksite lastehoiuteenuste kvaliteedi Eestis?'],
		['Tervishoiu- jms riiklikud teenused', 'Y11_Q53g', 'Milliseks hindaksite riikliku pensionisüsteemi kvaliteedi Eestis?'],
		['Töö- ja eraelu tasakaal', 'Y11_Q12a', 'Olen töölt koju tulles olnud majapidamistööde tegemiseks liiga väsinud'],
		['Töö- ja eraelu tasakaal', 'Y11_Q12b', 'Mul on olnud raske täita oma perekondlikke kohustusi tööl oldud aja tõttu '],
		['Töö- ja eraelu tasakaal', 'Y11_Q12c', 'Mul on olnud perekondlike kohustuste tõttu raske tööle keskenduda'],
		['Töö- ja eraelu tasakaal', 'Y11_Q15', 'Kui tõenäoliseks peate oma töökoha kaotamist järgmise kuue kuu jooksul?'],
		['Töö- ja eraelu tasakaal', 'Y11_Q36b', 'Kui sageli olete hõivatud toidu valmistamise või majapidamistöödega?'],
		['Töö- ja eraelu tasakaal', 'Y11_Q36c', 'Kui sageli olete hõivatud eakate või puudega sugulaste eest hoolitsemisega?'],
		['Töö- ja eraelu tasakaal', 'Y11_Q38', 'Suhtumine majapidamistööde jaotusse'],
		['Töö- ja eraelu tasakaal', 'Y11_Q39d_stress', 'Stress'],
		['Ühiskonna kvaliteet', 'Y11_Q24', 'Kas te peate ennast väga usaldavaks või väga umbusklikuks?'],
		['Ühiskonna kvaliteet', 'Y11_Q25a', 'Hinnang vaeste ja rikaste vahelisele lõhele'],
		['Ühiskonna kvaliteet', 'Y11_Q25b', 'Hinnang juhtkonna ja töötajate vahelisele lõhele'],
		['Ühiskonna kvaliteet', 'Y11_Q25c', 'Hinnang meeste ja naiste vahelisele lõhele'],
		['Ühiskonna kvaliteet', 'Y11_Q25d', 'Hinnang põlvkondadevahelisele lõhele'],
		['Ühiskonna kvaliteet', 'Y11_Q25e', 'Hinnang rahvustevahelisele lõhele'],
		['Ühiskonna kvaliteet', 'Y11_Q25f', 'Hinnang usugruppidevahelisele lõhele'],
		['Ühiskonna kvaliteet', 'Y11_Q28a', 'Riigikogu usaldamine'],
		['Ühiskonna kvaliteet', 'Y11_Q28b', 'Õigussüsteemi usaldamine'],
		['Ühiskonna kvaliteet', 'Y11_Q28c', 'Kirjutava ajakirjanduse usaldamine'],
		['Ühiskonna kvaliteet', 'Y11_Q28d', 'Politsei usaldamine'],
		['Ühiskonna kvaliteet', 'Y11_Q28e', 'Valitsuse usaldamine']
	];
var question_
	 = [
	
		['Y11_Deprindex', 'Ainelise puuduse indeks: nende asjade arv, mida leibkonnad ei saa endale lubada'],
		['Y11_Q58', 'Kas teie leibkond saab olemasolevate vahenditega hakkama?'],
		['Y11_Q59a', 'Kas teie kodu kütmine on teile jõukohane?'],
		['Y11_Q59b', 'Kas teile on jõukohane minna kord aastas nädalaks puhkusele kodunt kaugele?'],
		['Y11_Q59c', 'Kas teile on jõukohane osta oma aja ära elanud mööbli asemel uut?'],
		['Y11_Q59d', 'Kas teile on jõukohane süüa soovi korral ülepäeviti loomaliha, kanaliha või kala?'],
		['Y11_Q59e', 'Kas teile on jõukohane osta uusi (mitte kasutatud) riideid?'],
		['Y11_Q59f', 'Kas teile on jõukohane võõrustada vähemalt kord kuus söögi või joogiga sõpru või lähedasi?'],
		['Y11_Q60a', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud üüri- või laenumaksete võlgnevusi?'],
		['Y11_Q60b', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud kommunaalteenuste maksete võlgnevusi?'],
		['Y11_Accommproblems', 'Eluaseme probleemide arv'],
		['Y11_Q18', 'Kodu omamine'],
		['Y11_Q19a', 'Eluasemeprobleemid: ruumipuudus'],
		['Y11_Q19b', 'Eluasemeprobleemid: pehkinud aknad, uksed või põrandad'],
		['Y11_Q19c', 'Eluasemeprobleemid: niiskus/lekked seintes või katuses'],
		['Y11_Q19d', 'Eluasemeprobleemid: puudub vesiklosett'],
		['Y11_Q19e', 'Eluasemeprobleemid: puudub vann või dušš'],
		['Y11_Q19f', 'Eluasemeprobleemid: puudub koht väljas istumiseks'],
		['Y11_Q20', 'Kui tõenäoliseks peate vajadust lahkuda oma elukohast järgneva kuue kuu jooksul, kuna ei suuda enam selle eest maksta?'],
		['Y11_Q23a', 'Osalemine ametiühingu, erakonna või kodanikualgatusrühma koosolekul viimase 12 kuu jooksul'],
		['Y11_Q23d', 'Poliitiku või ametniku poole pöördumine (v.a seoses tavapäraste riiklike teenustega)'],
		['Y11_Q29e', 'Tunnen end sotsiaalselt tõrjutuna'],
		['Y11_Q29f', 'Tänapäeva elu on läinud nii keeruliseks, et mul on juba raske toime tulla'],
		['Y11_Q29g', 'Mul on tunne, et teised ei väärtusta mind'],
		['Y11_Q29h', 'Mõnikord halvustatakse mind mu tööalase olukorra või sissetuleku tõttu'],
		['Y11_SocExIndex', 'Sotsiaalse tõrjutuse indeks'],
		['Y11_Q29a', 'Olen tuleviku suhtes optimistlik'],
		['Y11_Q30', 'Kui rahul olete oma eluga praegu?'],
		['Y11_Q40a', 'Rahulolu haridusega'],
		['Y11_Q40b', 'Rahulolu praeguse tööga'],
		['Y11_Q40c', 'Rahulolu praeguse elatustasemega'],
		['Y11_Q40d', 'Rahulolu eluasemega'],
		['Y11_Q40e', 'Rahulolu pereeluga'],
		['Y11_Q40f', 'Rahulolu tervisega'],
		['Y11_Q40g', 'Rahulolu seltskondliku eluga'],
		['Y11_Q41', 'Kõike arvesse võttes, kui rahul te oma eluga olete?'],
		['Y11_Q42', 'Terviseseisund enda hinnangul'],
		['Y11_Q46d_WHO5', 'WHO-5 vaimse heaolu skaala'],
		['Y11_Q47a', 'Raskused arsti juurde pääsemisel kauguse tõttu'],
		['Y11_Q47b', 'Raskused arsti juurde pääsemisel viivituse tõttu arsti vastuvõtule pääsemisel'],
		['Y11_Q47c', 'Raskused arsti juurde pääsemisel ooteaja tõttu arsti vastuvõtule visiidi päeval'],
		['Y11_Q47d', 'Raskused arsti juurde pääsemisel kulude tõttu'],
		['Y11_Q53a', 'Milliseks hindaksite tervishoiuteenuste kvaliteedi Eestis?'],
		['Y11_Q53b', 'Milliseks hindaksite haridussüsteemi kvaliteedi Eestis?'],
		['Y11_Q53c', 'Milliseks hindaksite ühistranspordi kvaliteedi Eestis?'],
		['Y11_Q53d', 'Milliseks hindaksite lastehoiuteenuste kvaliteedi Eestis?'],
		['Y11_Q53g', 'Milliseks hindaksite riikliku pensionisüsteemi kvaliteedi Eestis?'],
		['Y11_Q12a', 'Olen töölt koju tulles olnud majapidamistööde tegemiseks liiga väsinud'],
		['Y11_Q12b', 'Mul on olnud raske täita oma perekondlikke kohustusi tööl oldud aja tõttu '],
		['Y11_Q12c', 'Mul on olnud perekondlike kohustuste tõttu raske tööle keskenduda'],
		['Y11_Q15', 'Kui tõenäoliseks peate oma töökoha kaotamist järgmise kuue kuu jooksul?'],
		['Y11_Q36b', 'Kui sageli olete hõivatud toidu valmistamise või majapidamistöödega?'],
		['Y11_Q36c', 'Kui sageli olete hõivatud eakate või puudega sugulaste eest hoolitsemisega?'],
		['Y11_Q38', 'Suhtumine majapidamistööde jaotusse'],
		['Y11_Q39d_stress', 'Stress'],
		['Y11_Q24', 'Kas te peate ennast väga usaldavaks või väga umbusklikuks?'],
		['Y11_Q25a', 'Hinnang vaeste ja rikaste vahelisele lõhele'],
		['Y11_Q25b', 'Hinnang juhtkonna ja töötajate vahelisele lõhele'],
		['Y11_Q25c', 'Hinnang meeste ja naiste vahelisele lõhele'],
		['Y11_Q25d', 'Hinnang põlvkondadevahelisele lõhele'],
		['Y11_Q25e', 'Hinnang rahvustevahelisele lõhele'],
		['Y11_Q25f', 'Hinnang usugruppidevahelisele lõhele'],
		['Y11_Q28a', 'Riigikogu usaldamine'],
		['Y11_Q28b', 'Õigussüsteemi usaldamine'],
		['Y11_Q28c', 'Kirjutava ajakirjanduse usaldamine'],
		['Y11_Q28d', 'Politsei usaldamine'],
		['Y11_Q28e', 'Valitsuse usaldamine']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Keskmine'],
		['Y11_Deprindex', 'Mean', 'Keskmine'],
		['Y11_Q12a', '1--Several-times-a-week', 'Mitu korda nädalas'],
		['Y11_Q12a', '2--Several-times-a-month', 'Mitu korda kuus'],
		['Y11_Q12a', '3--Several-times-a-year', 'Mitu korda aastas'],
		['Y11_Q12a', '4--Less-often-rarely', 'Harva'],
		['Y11_Q12a', '5--Never', 'Mitte kunagi'],
		['Y11_Q12b', '1--Several-times-a-week', 'Mitu korda nädalas'],
		['Y11_Q12b', '2--Several-times-a-month', 'Mitu korda kuus'],
		['Y11_Q12b', '3--Several-times-a-year', 'Mitu korda aastas'],
		['Y11_Q12b', '4--Less-often-rarely', 'Harva'],
		['Y11_Q12b', '5--Never', 'Mitte kunagi'],
		['Y11_Q12c', '1--Several-times-a-week', 'Mitu korda nädalas'],
		['Y11_Q12c', '2--Several-times-a-month', 'Mitu korda kuus'],
		['Y11_Q12c', '3--Several-times-a-year', 'Mitu korda aastas'],
		['Y11_Q12c', '4--Less-often-rarely', 'Harva'],
		['Y11_Q12c', '5--Never', 'Mitte kunagi'],
		['Y11_Q15', '1--Very-likely', 'Väga tõenäoliseks'],
		['Y11_Q15', '2--Quite-likely', 'Üsna tõenäoliseks'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Ei oska öelda'],
		['Y11_Q15', '4--Quite-unlikely', 'Üsna ebatõenäoliseks'],
		['Y11_Q15', '5--Very-unlikely', 'Väga ebatõenäoliseks'],
		['Y11_Q18', '1--Own-without-mortgage', 'Kuulub mulle ilma hüpoteegita'],
		['Y11_Q18', '2--Own-with-mortgage', 'Kuulub mulle koos hüpoteegiga'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Olen üürnik, maksan sotsiaal‐/munitsipaaleluruumi eest üüri'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Olen üürnik, maksan üüri eraisikule'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Kasutan eluaset ilma üürita '],
		['Y11_Q18', '6--Other', 'Muu'],
		['Y11_Q19a', '1--Yes', 'Jah'],
		['Y11_Q19a', '2--No', 'Ei'],
		['Y11_Q19b', '1--Yes', 'Jah'],
		['Y11_Q19b', '2--No', 'Ei'],
		['Y11_Q19c', '1--Yes', 'Jah'],
		['Y11_Q19c', '2--No', 'Ei'],
		['Y11_Q19d', '1--Yes', 'Jah'],
		['Y11_Q19d', '2--No', 'Ei'],
		['Y11_Q19e', '1--Yes', 'Jah'],
		['Y11_Q19e', '2--No', 'Ei'],
		['Y11_Q19f', '1--Yes', 'Jah'],
		['Y11_Q19f', '2--No', 'Ei'],
		['Y11_Q20', '1--Very-likely', 'Väga tõenäoliseks'],
		['Y11_Q20', '2--Quite-likely', 'Üsna tõenäoliseks'],
		['Y11_Q20', '3--Quite-unlikely', 'Üsna ebatõenäoliseks'],
		['Y11_Q20', '4--Very-unlikely', 'Väga ebatõenäoliseks'],
		['Y11_Q23a', '1--Yes', 'Jah'],
		['Y11_Q23a', '2--No', 'Ei'],
		['Y11_Q23d', '1--Yes', 'Jah'],
		['Y11_Q23d', '2--No', 'Ei'],
		['Y11_Q24', 'Mean', 'Keskmine'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Suur lõhe'],
		['Y11_Q25a', '2--Some-tension', 'Väike lõhe'],
		['Y11_Q25a', '3--No-tension', 'Lõhet ei ole'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Suur lõhe'],
		['Y11_Q25b', '2--Some-tension', 'Väike lõhe'],
		['Y11_Q25b', '3--No-tension', 'Lõhet ei ole'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Suur lõhe'],
		['Y11_Q25c', '2--Some-tension', 'Väike lõhe'],
		['Y11_Q25c', '3--No-tension', 'Lõhet ei ole'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Suur lõhe'],
		['Y11_Q25d', '2--Some-tension', 'Väike lõhe'],
		['Y11_Q25d', '3--No-tension', 'Lõhet ei ole'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Suur lõhe'],
		['Y11_Q25e', '2--Some-tension', 'Väike lõhe'],
		['Y11_Q25e', '3--No-tension', 'Lõhet ei ole'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Suur lõhe'],
		['Y11_Q25f', '2--Some-tension', 'Väike lõhe'],
		['Y11_Q25f', '3--No-tension', 'Lõhet ei ole'],
		['Y11_Q28a', 'Mean', 'Keskmine'],
		['Y11_Q28b', 'Mean', 'Keskmine'],
		['Y11_Q28c', 'Mean', 'Keskmine'],
		['Y11_Q28d', 'Mean', 'Keskmine'],
		['Y11_Q28e', 'Mean', 'Keskmine'],
		['Y11_Q29a', '1--Strongly-agree', 'Nõustun täielikult'],
		['Y11_Q29a', '2--Agree', 'Nõustun'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Ei oska öelda'],
		['Y11_Q29a', '4--Disagree', 'Ei nõustu'],
		['Y11_Q29a', '5--Strongly-disagree', 'Ei nõustu üldse'],
		['Y11_Q29e', '1--Strongly-agree', 'Nõustun täielikult'],
		['Y11_Q29e', '2--Agree', 'Nõustun'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Ei oska öelda'],
		['Y11_Q29e', '4--Disagree', 'Ei nõustu'],
		['Y11_Q29e', '5--Strongly-disagree', 'Ei nõustu üldse'],
		['Y11_Q29f', '1--Strongly-agree', 'Nõustun täielikult'],
		['Y11_Q29f', '2--Agree', 'Nõustun'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Ei oska öelda'],
		['Y11_Q29f', '4--Disagree', 'Ei nõustu'],
		['Y11_Q29f', '5--Strongly-disagree', 'Ei nõustu üldse'],
		['Y11_Q29g', '1--Strongly-agree', 'Nõustun täielikult'],
		['Y11_Q29g', '2--Agree', 'Nõustun'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Ei oska öelda'],
		['Y11_Q29g', '4--Disagree', 'Ei nõustu'],
		['Y11_Q29g', '5--Strongly-disagree', 'Ei nõustu üldse'],
		['Y11_Q29h', '1--Strongly-agree', 'Nõustun täielikult'],
		['Y11_Q29h', '2--Agree', 'Nõustun'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Ei oska öelda'],
		['Y11_Q29h', '4--Disagree', 'Ei nõustu'],
		['Y11_Q29h', '5--Strongly-disagree', 'Ei nõustu üldse'],
		['Y11_Q30', 'Mean', 'Keskmine'],
		['Y11_Q36b', '1--Every-day', 'Iga päev'],
		['Y11_Q36b', '2--Several-days-a-week', 'Mitu korda nädalas'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'Mõni kord nädalas'],
		['Y11_Q36b', '4--Less-often', 'Harvem'],
		['Y11_Q36b', '5--Never', 'Mitte kunagi'],
		['Y11_Q36c', '1--Every-day', 'Iga päev'],
		['Y11_Q36c', '2--Several-days-a-week', 'Mitu korda nädalas'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'Mõni kord nädalas'],
		['Y11_Q36c', '4--Less-often', 'Harvem'],
		['Y11_Q36c', '5--Never', 'Mitte kunagi'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Teen liiga palju'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Teen piisavalt'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Teen liiga vähe'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'Tööl ja kodus'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Kas tööl või kodus'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Stress puudub või on väike'],
		['Y11_Q40a', 'Mean', 'Keskmine'],
		['Y11_Q40b', 'Mean', 'Keskmine'],
		['Y11_Q40c', 'Mean', 'Keskmine'],
		['Y11_Q40d', 'Mean', 'Keskmine'],
		['Y11_Q40e', 'Mean', 'Keskmine'],
		['Y11_Q40f', 'Mean', 'Keskmine'],
		['Y11_Q40g', 'Mean', 'Keskmine'],
		['Y11_Q41', 'Mean', 'Keskmine'],
		['Y11_Q42', '1--Very-good', 'Väga hea'],
		['Y11_Q42', '2--Good', 'Hea'],
		['Y11_Q42', '3--Fair', 'Rahuldav'],
		['Y11_Q42', '4--Bad', 'Halb'],
		['Y11_Q42', '5--Very-bad', 'Väga halb'],
		['Y11_Q46d_WHO5', 'Mean', 'Keskmine'],
		['Y11_Q47a', '1--Very-difficult', 'Suured raskused'],
		['Y11_Q47a', '2--A-little-difficult', 'Väikesed raskused'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Raskusi ei ole'],
		['Y11_Q47b', '1--Very-difficult', 'Suured raskused'],
		['Y11_Q47b', '2--A-little-difficult', 'Väikesed raskused'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Raskusi ei ole'],
		['Y11_Q47c', '1--Very-difficult', 'Suured raskused'],
		['Y11_Q47c', '2--A-little-difficult', 'Väikesed raskused'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Raskusi ei ole'],
		['Y11_Q47d', '1--Very-difficult', 'Suured raskused'],
		['Y11_Q47d', '2--A-little-difficult', 'Väikesed raskused'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Raskusi ei ole'],
		['Y11_Q53a', 'Mean', 'Keskmine'],
		['Y11_Q53b', 'Mean', 'Keskmine'],
		['Y11_Q53c', 'Mean', 'Keskmine'],
		['Y11_Q53d', 'Mean', 'Keskmine'],
		['Y11_Q53g', 'Mean', 'Keskmine'],
		['Y11_Q58', '1--With-great-difficulty', 'Suurte raskustega'],
		['Y11_Q58', '2--With-difficulty', 'Raskustega'],
		['Y11_Q58', '3--With-some-difficulty', 'Mõningate raskustega'],
		['Y11_Q58', '4--Fairly-easily', 'Üsna lihtsalt'],
		['Y11_Q58', '5--Easily', 'Lihtsalt'],
		['Y11_Q58', '6--Very-easily', 'Väga lihtsalt'],
		['Y11_Q59a', '1--No', 'Ei'],
		['Y11_Q59a', '2--Yes', 'Jah'],
		['Y11_Q59b', '1--No', 'Ei'],
		['Y11_Q59b', '2--Yes', 'Jah'],
		['Y11_Q59c', '1--No', 'Ei'],
		['Y11_Q59c', '2--Yes', 'Jah'],
		['Y11_Q59d', '1--No', 'Ei'],
		['Y11_Q59d', '2--Yes', 'Jah'],
		['Y11_Q59e', '1--No', 'Ei'],
		['Y11_Q59e', '2--Yes', 'Jah'],
		['Y11_Q59f', '1--No', 'Ei'],
		['Y11_Q59f', '2--Yes', 'Jah'],
		['Y11_Q60a', '1--Yes', 'Jah'],
		['Y11_Q60a', '2--No', 'Ei'],
		['Y11_Q60b', '1--Yes', 'Jah'],
		['Y11_Q60b', '2--No', 'Ei'],
		['Y11_SocExIndex', 'Mean', 'Keskmine']
	];
var country_
	 = [
	
		['AT', 'Austria'],
		['BE', 'Belgia'],
		['BG', 'Bulgaaria'],
		['CY', 'Küpros'],
		['CZ', 'Tšehhi'],
		['DE', 'Saksamaa'],
		['DK', 'Taani'],
		['EE', 'Eesti'],
		['EL', 'Kreeka'],
		['ES', 'Hispaania'],
		['FI', 'Soome'],
		['FR', 'Prantsusmaa'],
		['HR', 'Horvaatia'],
		['HU', 'Ungari'],
		['IE', 'Iirimaa'],
		['IT', 'Itaalia'],
		['LT', 'Leedu'],
		['LU', 'Luksemburg'],
		['LV', 'Läti'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Madalmaad'],
		['NO', 'Norra'],
		['PL', 'Poola'],
		['PT', 'Portugal'],
		['RO', 'Rumeenia'],
		['SE', 'Rootsi'],
		['SI', 'Sloveenia'],
		['SK', 'Slovakkia'],
		['TR', 'Türgi'],
		['UK', 'Ühendkuningriik'],
		['EuropeanUnion', 'Euroopa Liit']
	];
var question_meta
	 = [
	
		['Y11_Deprindex', 'Ainelise puuduse indeks: nende asjade arv, mida leibkonnad ei saa endale lubada', ''],
		['Y11_Q58', 'Kas teie leibkond saab olemasolevate vahenditega hakkama?', ''],
		['Y11_Q59a', 'Kas teie kodu kütmine on teile jõukohane?', ''],
		['Y11_Q59b', 'Kas teile on jõukohane minna kord aastas nädalaks puhkusele kodunt kaugele?', ''],
		['Y11_Q59c', 'Kas teile on jõukohane osta oma aja ära elanud mööbli asemel uut?', ''],
		['Y11_Q59d', 'Kas teie leibkonnale on jõukohane süüa soovi korral ülepäeviti loomaliha, kanaliha või kala?', ''],
		['Y11_Q59e', 'Kas teie leibkonna liikmetele on jõukohane osta uusi (mitte kasutatud) riideid?', ''],
		['Y11_Q59f', 'Kas teie leibkonnale on jõukohane võõrustada vähemalt kord kuus söögi või joogiga sõpru või lähedasi?', ''],
		['Y11_Q60a', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud üüri- või laenumaksete võlgnevusi?', ''],
		['Y11_Q60b', 'Kas teie leibkonnal on viimase 12 kuu jooksul olnud kommunaalteenuste maksete võlgnevusi?', ''],
		['Y11_Accommproblems', 'Eluaseme probleemide arv', ''],
		['Y11_Q18', 'Kodu omamine', ''],
		['Y11_Q19a', 'Eluasemeprobleemid: ruumipuudus', ''],
		['Y11_Q19b', 'Eluasemeprobleemid: pehkinud aknad, uksed või põrandad', ''],
		['Y11_Q19c', 'Eluasemeprobleemid: niiskus/lekked seintes või katuses', ''],
		['Y11_Q19d', 'Eluasemeprobleemid: puudub vesiklosett', ''],
		['Y11_Q19e', 'Eluasemeprobleemid: puudub vann või dušš', ''],
		['Y11_Q19f', 'Eluasemeprobleemid: puudub koht väljas istumiseks', ''],
		['Y11_Q20', 'Kui tõenäoliseks peate vajadust lahkuda oma elukohast järgneva kuue kuu jooksul, kuna ei suuda enam selle eest maksta?', ''],
		['Y11_Q23a', 'Osalemine ametiühingu, erakonna või kodanikualgatusrühma koosolekul viimase 12 kuu jooksul', ''],
		['Y11_Q23d', 'Poliitiku või ametniku poole pöördumine (v.a seoses tavapäraste riiklike teenustega)', ''],
		['Y11_Q29e', 'Tunnen end sotsiaalselt tõrjutuna', ''],
		['Y11_Q29f', 'Tänapäeva elu on läinud nii keeruliseks, et mul on juba raske toime tulla', ''],
		['Y11_Q29g', 'Mul on tunne, et teised ei väärtusta mind', ''],
		['Y11_Q29h', 'Mõnikord halvustatakse mind mu tööalase olukorra või sissetuleku tõttu', ''],
		['Y11_SocExIndex', 'Sotsiaalse tõrjutuse indeks', ''],
		['Y11_Q29a', 'Olen tuleviku suhtes optimistlik', ''],
		['Y11_Q30', 'Kui rahul olete oma eluga praegu?', ''],
		['Y11_Q40a', 'Rahulolu haridusega', ''],
		['Y11_Q40b', 'Rahulolu praeguse tööga', ''],
		['Y11_Q40c', 'Rahulolu praeguse elatustasemega', ''],
		['Y11_Q40d', 'Rahulolu eluasemega', ''],
		['Y11_Q40e', 'Rahulolu pereeluga', ''],
		['Y11_Q40f', 'Rahulolu tervisega', ''],
		['Y11_Q40g', 'Rahulolu seltskondliku eluga', ''],
		['Y11_Q41', 'Kõike arvesse võttes, kui rahul te oma eluga olete?', ''],
		['Y11_Q42', 'Terviseseisund enda hinnangul', ''],
		['Y11_Q46d_WHO5', 'WHO-5 vaimse heaolu skaala', ''],
		['Y11_Q47a', 'Raskused arsti juurde pääsemisel kauguse tõttu arsti vastuvõturuumidest või haiglast', ''],
		['Y11_Q47b', 'Raskused arsti juurde pääsemisel viivituse tõttu arsti vastuvõtule pääsemisel', ''],
		['Y11_Q47c', 'Raskused arsti juurde pääsemisel ooteaja tõttu arsti vastuvõtule visiidi päeval', ''],
		['Y11_Q47d', 'Raskused arsti juurde pääsemisel visiiditasu tõttu', ''],
		['Y11_Q53a', 'Milliseks hindaksite tervishoiuteenuste kvaliteedi Eestis?', ''],
		['Y11_Q53b', 'Milliseks hindaksite haridussüsteemi kvaliteedi Eestis?', ''],
		['Y11_Q53c', 'Milliseks hindaksite ühistranspordi kvaliteedi Eestis?', ''],
		['Y11_Q53d', 'Milliseks hindaksite lastehoiuteenuste kvaliteedi Eestis?', ''],
		['Y11_Q53g', 'Milliseks hindaksite riikliku pensionisüsteemi kvaliteedi Eestis?', ''],
		['Y11_Q12a', ' Olen töölt koju tulles olnud majapidamistööde tegemiseks liiga väsinud', ''],
		['Y11_Q12b', 'Mul on olnud raske täita oma perekondlikke kohustusi tööl oldud aja tõttu ', ''],
		['Y11_Q12c', 'Mul on olnud perekondlike kohustuste tõttu raske tööle keskenduda', ''],
		['Y11_Q15', 'Kui tõenäoliseks peate oma töökoha kaotamist järgmise kuue kuu jooksul?', ''],
		['Y11_Q36b', 'Kui sageli olete hõivatud toidu valmistamise või majapidamistöödega?', ''],
		['Y11_Q36c', 'Kui sageli olete hõivatud eakate või puudega sugulaste eest hoolitsemisega?', ''],
		['Y11_Q38', 'Mida arvate oma osast majapidamistöödes?', ''],
		['Y11_Q39d_stress', 'Töö- ja eraelu tasakaalustamatusest põhjustatud stress', ''],
		['Y11_Q24', 'Kas te peate ennast väga usaldavaks või väga umbusklikuks?', ''],
		['Y11_Q25a', 'Hinnang vaeste ja rikaste vahelisele lõhele', ''],
		['Y11_Q25b', 'Hinnang juhtkonna ja töötajate vahelisele lõhele', ''],
		['Y11_Q25c', 'Hinnang meeste ja naiste vahelisele lõhele', ''],
		['Y11_Q25d', 'Hinnang põlvkondadevahelisele lõhele', ''],
		['Y11_Q25e', 'Hinnang rahvustevahelisele lõhele', ''],
		['Y11_Q25f', 'Hinnang usugruppidevahelisele lõhele', ''],
		['Y11_Q28a', 'Riigikogu usaldamine', ''],
		['Y11_Q28b', 'Õigussüsteemi usaldamine', ''],
		['Y11_Q28c', 'Kirjutava ajakirjanduse usaldamine', ''],
		['Y11_Q28d', 'Politsei usaldamine', ''],
		['Y11_Q28e', 'Valitsuse usaldamine', '']
	];
