//Auto Generated file
var subset_
	 = [
	
		['Y11_Agecategory', 'Ikä'],
		['Y11_HH2a', 'Sukupuoli'],
		['Y11_Incomequartiles_percapita', 'Tulot']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Kaikki ikäryhmät'],
		['Y11_Agecategory', '1--18-24y', '18–24 vuotta'],
		['Y11_Agecategory', '2--25-34y', '25–34 vuotta'],
		['Y11_Agecategory', '3--35-49y', '35–49 vuotta'],
		['Y11_Agecategory', '4--50-64y', '50–64 vuotta'],
		['Y11_Agecategory', '5---64y', '> 64 vuotta'],
		['Y11_HH2a', 'All', 'Molemmat sukupuolet'],
		['Y11_HH2a', '1--Female', 'Naiset'],
		['Y11_HH2a', '2--Male', 'Miehet'],
		['Y11_Incomequartiles_percapita', 'All', 'Kaikki tulotasot'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Alin'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'Toiseksi ylin'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'Kolmanneksi ylin'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Ylin']
	];
var topic_
	 = [
	
		['', 'Kaikki (67)'],
		['Elintaso ja puute', 'Elintaso ja puute (10)'],
		['Julkiset terveyspalvelut', 'Julkiset terveyspalvelut (11)'],
		['Koti ja lähiympäristö', 'Koti ja lähiympäristö (9)'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan (7)'],
		['Subjektiivinen hyvinvointi', 'Subjektiivinen hyvinvointi (10)'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Työllisyys ja työ- ja yksityiselämän tasapaino (8)'],
		['Yhteiskunnan laatu', 'Yhteiskunnan laatu (12)']
	];
var topic_question
	 = [
	
		['Elintaso ja puute', 'Y11_Deprindex', 'Huono-osaisuuden indeksi: määrä asioista, joihin kotitalouksilla ei ole varaa'],
		['Elintaso ja puute', 'Y11_Q58', 'Ovatko kotitaloutenne tulot riittävät?'],
		['Elintaso ja puute', 'Y11_Q59a', 'Onko teillä varaa pitää koti riittävän lämpimänä?'],
		['Elintaso ja puute', 'Y11_Q59b', 'Onko teillä varaa vuosittaiseen lomaviikkoon poissa kotoa?'],
		['Elintaso ja puute', 'Y11_Q59c', 'Onko teillä varaa vaihtaa mikä tahansa kulunut huonekalu uuteen?'],
		['Elintaso ja puute', 'Y11_Q59d', 'Onko teillä varaa liha-, kana- tai kala-ateriaan joka toinen päivä (niin halutessanne)?'],
		['Elintaso ja puute', 'Y11_Q59e', 'Onko teillä varaa ostaa uusia vaatteita käytettyjen sijaan?'],
		['Elintaso ja puute', 'Y11_Q59f', 'Onko teillä varaa kutsua ystäviä tai sukulaisia lasilliselle tai aterialle vähintään kerran kuussa?'],
		['Elintaso ja puute', 'Y11_Q60a', 'Onko kotitaloudella ollut asunnon vuokran tai asuntolainan maksuerän maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?'],
		['Elintaso ja puute', 'Y11_Q60b', 'Onko kotitaloudella ollut yleisiin asumiseen liittyvien kulujen maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?'],
		['Julkiset terveyspalvelut', 'Y11_Q42', 'Koettu terveydentila'],
		['Julkiset terveyspalvelut', 'Y11_Q46d_WHO5', 'Psyykkisen hyvinvoinnin WHO-5-indeksi'],
		['Julkiset terveyspalvelut', 'Y11_Q47a', 'Etäisyyden aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Julkiset terveyspalvelut', 'Y11_Q47b', 'Vastaanottoajan saamisen viivytyksen aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Julkiset terveyspalvelut', 'Y11_Q47c', 'Vastaanottopäivän odotusajan aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Julkiset terveyspalvelut', 'Y11_Q47d', 'Kustannusten aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Julkiset terveyspalvelut', 'Y11_Q53a', 'Miten laadukkaaksi arvioisitte kotimaanne terveydenhuoltopalvelut?'],
		['Julkiset terveyspalvelut', 'Y11_Q53b', 'Miten laadukkaaksi arvioisitte kotimaanne koulutusjärjestelmän?'],
		['Julkiset terveyspalvelut', 'Y11_Q53c', 'Miten laadukkaaksi arvioisitte kotimaanne julkisen liikenteen?'],
		['Julkiset terveyspalvelut', 'Y11_Q53d', 'Miten laadukkaaksi arvioisitte kotimaanne lastenhoitopalvelut?'],
		['Julkiset terveyspalvelut', 'Y11_Q53g', 'Miten laadukkaaksi arvioisitte kotimaanne kansaneläkejärjestelmän?'],
		['Koti ja lähiympäristö', 'Y11_Accommproblems', 'Asumisongelmien määrä'],
		['Koti ja lähiympäristö', 'Y11_Q18', 'Omistusasuminen'],
		['Koti ja lähiympäristö', 'Y11_Q19a', 'Asumiseen liittyvät ongelmat: tilanpuute'],
		['Koti ja lähiympäristö', 'Y11_Q19b', 'Asumiseen liittyvät ongelmat: lahovaurioita ikkunoissa, ovissa tai lattioissa'],
		['Koti ja lähiympäristö', 'Y11_Q19c', 'Asumiseen liittyvät ongelmat: kosteutta tai vuotoja seinissä tai katossa'],
		['Koti ja lähiympäristö', 'Y11_Q19d', 'Asumiseen liittyvät ongelmat: sisävesivessan puuttuminen'],
		['Koti ja lähiympäristö', 'Y11_Q19e', 'Asumiseen liittyvät ongelmat: suihkun tai ammeen puuttuminen'],
		['Koti ja lähiympäristö', 'Y11_Q19f', 'Asumiseen liittyvät ongelmat: ulkona olevan oleskelutilan puuttuminen'],
		['Koti ja lähiympäristö', 'Y11_Q20', 'Miten todennäköisesti joudutte luopumaan asunnostanne seuraavan puolen vuoden kuluessa, koska teillä ei enää ole varaa siihen?'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q23a', 'Osallistunut ammattiliiton, poliittisen puolueen tai toimintaryhmän kokoukseen'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q23d', 'Ottanut yhteyttä poliitikkoon tai virkamieheen (muu kuin julkisten palveluiden käyttöön liittyvä tavanomainen yhteydenotto)'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q29e', 'Tunnen olevani yhteiskunnan ulkopuolella'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q29f', 'Elämä on nykyään niin monimutkaista, että olen vähällä eksyä'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q29g', 'Muut eivät tunnu antavan arvoa tekemisilleni'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_Q29h', 'Jotkut halveksivat minua työtilanteeni tai ansiotasoni vuoksi'],
		['Sosiaalinen syrjäytyminen ja osallistuminen yhteisölliseen toimintaan', 'Y11_SocExIndex', 'Sosiaaliseen syrjäytymisen indeksi'],
		['Subjektiivinen hyvinvointi', 'Y11_Q29a', 'Olen optimistinen tulevaisuuden suhteen'],
		['Subjektiivinen hyvinvointi', 'Y11_Q30', 'Miten tyytyväinen olette elämäänne nykyään?'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40a', 'Tyytyväisyys koulutukseen'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40b', 'Tyytyväisyys nykyiseen työhön'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40c', 'Tyytyväisyys nykyiseen elintasoon'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40d', 'Tyytyväisyys asuntoon'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40e', 'Tyytyväisyys perhe-elämään'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40f', 'Tyytyväisyys terveydentilaan'],
		['Subjektiivinen hyvinvointi', 'Y11_Q40g', 'Tyytyväisyys sosiaaliseen elämään'],
		['Subjektiivinen hyvinvointi', 'Y11_Q41', 'Miten onnelliseksi arvioitte itsenne kaiken kaikkiaan?'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q12a', 'Olen ollut liian väsynyt tekemään kotitöitä työpäivän jälkeen'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q12b', 'Perheeseen liittyvien velvollisuuksien täyttäminen on ollut hankalaa töissä vietetyn ajan vuoksi'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q12c', 'Perheeseen liittyvät velvollisuudet ovat vaikeuttaneet keskittymistä työpaikalla'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q15', 'Miten todennäköisesti voitte menettää työpaikkanne seuraavan puolen vuoden kuluessa?'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q36b', 'Kuinka usein osallistutte ruoanlaittoon tai kotitöihin?'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q36c', 'Kuinka usein hoidatte vanhoja tai vammaisia sukulaisianne?'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q38', 'Mielipide kotitöiden jakamisesta'],
		['Työllisyys ja työ- ja yksityiselämän tasapaino', 'Y11_Q39d_stress', 'Stressi'],
		['Yhteiskunnan laatu', 'Y11_Q24', 'Voiko mielestänne suurimpaan osaan ihmisistä luottaa vai oletteko sitä mieltä, ettei kanssakäynnissä ihmisten kanssa voi olla liian varovainen?'],
		['Yhteiskunnan laatu', 'Y11_Q25a', 'Havaittu jännite köyhien ja rikkaiden välillä'],
		['Yhteiskunnan laatu', 'Y11_Q25b', 'Havaittu jännite johtoportaan ja työntekijöiden välillä'],
		['Yhteiskunnan laatu', 'Y11_Q25c', 'Havaittu jännite miesten ja naisten välillä'],
		['Yhteiskunnan laatu', 'Y11_Q25d', 'Havaittu jännite vanhojen ja nuorten ihmisten välillä'],
		['Yhteiskunnan laatu', 'Y11_Q25e', 'Havaittu jännite eri rodullisten ja etnisten ryhmien väillä'],
		['Yhteiskunnan laatu', 'Y11_Q25f', 'Havaittu jännite eri uskonnollisten ryhmien välillä'],
		['Yhteiskunnan laatu', 'Y11_Q28a', 'Luottamus eduskuntaan'],
		['Yhteiskunnan laatu', 'Y11_Q28b', 'Luottamus oikeusjärjestelmään'],
		['Yhteiskunnan laatu', 'Y11_Q28c', 'Luottamus lehdistöön'],
		['Yhteiskunnan laatu', 'Y11_Q28d', 'Luottamus poliisiin'],
		['Yhteiskunnan laatu', 'Y11_Q28e', 'Luottamus hallitukseen']
	];
var question_
	 = [
	
		['Y11_Deprindex', 'Huono-osaisuuden indeksi: määrä asioista, joihin kotitalouksilla ei ole varaa'],
		['Y11_Q58', 'Ovatko kotitaloutenne tulot riittävät?'],
		['Y11_Q59a', 'Onko teillä varaa pitää koti riittävän lämpimänä?'],
		['Y11_Q59b', 'Onko teillä varaa vuosittaiseen lomaviikkoon poissa kotoa?'],
		['Y11_Q59c', 'Onko teillä varaa vaihtaa mikä tahansa kulunut huonekalu uuteen?'],
		['Y11_Q59d', 'Onko teillä varaa liha-, kana- tai kala-ateriaan joka toinen päivä (niin halutessanne)?'],
		['Y11_Q59e', 'Onko teillä varaa ostaa uusia vaatteita käytettyjen sijaan?'],
		['Y11_Q59f', 'Onko teillä varaa kutsua ystäviä tai sukulaisia lasilliselle tai aterialle vähintään kerran kuussa?'],
		['Y11_Q60a', 'Onko kotitaloudella ollut asunnon vuokran tai asuntolainan maksuerän maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?'],
		['Y11_Q60b', 'Onko kotitaloudella ollut yleisiin asumiseen liittyvien kulujen maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?'],
		['Y11_Q42', 'Koettu terveydentila'],
		['Y11_Q46d_WHO5', 'Psyykkisen hyvinvoinnin WHO-5-indeksi'],
		['Y11_Q47a', 'Etäisyyden aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Y11_Q47b', 'Vastaanottoajan saamisen viivytyksen aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Y11_Q47c', 'Vastaanottopäivän odotusajan aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Y11_Q47d', 'Kustannusten aiheuttamat ongelmat lääkäriin pääsyssä'],
		['Y11_Q53a', 'Miten laadukkaaksi arvioisitte kotimaanne terveydenhuoltopalvelut?'],
		['Y11_Q53b', 'Miten laadukkaaksi arvioisitte kotimaanne koulutusjärjestelmän?'],
		['Y11_Q53c', 'Miten laadukkaaksi arvioisitte kotimaanne julkisen liikenteen?'],
		['Y11_Q53d', 'Miten laadukkaaksi arvioisitte kotimaanne lastenhoitopalvelut?'],
		['Y11_Q53g', 'Miten laadukkaaksi arvioisitte kotimaanne kansaneläkejärjestelmän?'],
		['Y11_Accommproblems', 'Asumisongelmien määrä'],
		['Y11_Q18', 'Omistusasuminen'],
		['Y11_Q19a', 'Asumiseen liittyvät ongelmat: tilanpuute'],
		['Y11_Q19b', 'Asumiseen liittyvät ongelmat: lahovaurioita ikkunoissa, ovissa tai lattioissa'],
		['Y11_Q19c', 'Asumiseen liittyvät ongelmat: kosteutta tai vuotoja seinissä tai katossa'],
		['Y11_Q19d', 'Asumiseen liittyvät ongelmat: sisävesivessan puuttuminen'],
		['Y11_Q19e', 'Asumiseen liittyvät ongelmat: suihkun tai ammeen puuttuminen'],
		['Y11_Q19f', 'Asumiseen liittyvät ongelmat: ulkona olevan oleskelutilan puuttuminen'],
		['Y11_Q20', 'Miten todennäköisesti joudutte luopumaan asunnostanne seuraavan puolen vuoden kuluessa, koska teillä ei enää ole varaa siihen?'],
		['Y11_Q23a', 'Osallistunut ammattiliiton, poliittisen puolueen tai toimintaryhmän kokoukseen'],
		['Y11_Q23d', 'Ottanut yhteyttä poliitikkoon tai virkamieheen (muu kuin julkisten palveluiden käyttöön liittyvä tavanomainen yhteydenotto)'],
		['Y11_Q29e', 'Tunnen olevani yhteiskunnan ulkopuolella'],
		['Y11_Q29f', 'Elämä on nykyään niin monimutkaista, että olen vähällä eksyä'],
		['Y11_Q29g', 'Muut eivät tunnu antavan arvoa tekemisilleni'],
		['Y11_Q29h', 'Jotkut halveksivat minua työtilanteeni tai ansiotasoni vuoksi'],
		['Y11_SocExIndex', 'Sosiaaliseen syrjäytymisen indeksi'],
		['Y11_Q29a', 'Olen optimistinen tulevaisuuden suhteen'],
		['Y11_Q30', 'Miten tyytyväinen olette elämäänne nykyään?'],
		['Y11_Q40a', 'Tyytyväisyys koulutukseen'],
		['Y11_Q40b', 'Tyytyväisyys nykyiseen työhön'],
		['Y11_Q40c', 'Tyytyväisyys nykyiseen elintasoon'],
		['Y11_Q40d', 'Tyytyväisyys asuntoon'],
		['Y11_Q40e', 'Tyytyväisyys perhe-elämään'],
		['Y11_Q40f', 'Tyytyväisyys terveydentilaan'],
		['Y11_Q40g', 'Tyytyväisyys sosiaaliseen elämään'],
		['Y11_Q41', 'Miten onnelliseksi arvioitte itsenne kaiken kaikkiaan?'],
		['Y11_Q12a', 'Olen ollut liian väsynyt tekemään kotitöitä työpäivän jälkeen'],
		['Y11_Q12b', 'Perheeseen liittyvien velvollisuuksien täyttäminen on ollut hankalaa töissä vietetyn ajan vuoksi'],
		['Y11_Q12c', 'Perheeseen liittyvät velvollisuudet ovat vaikeuttaneet keskittymistä työpaikalla'],
		['Y11_Q15', 'Miten todennäköisesti voitte menettää työpaikkanne seuraavan puolen vuoden kuluessa?'],
		['Y11_Q36b', 'Kuinka usein osallistutte ruoanlaittoon tai kotitöihin?'],
		['Y11_Q36c', 'Kuinka usein hoidatte vanhoja tai vammaisia sukulaisianne?'],
		['Y11_Q38', 'Mielipide kotitöiden jakamisesta'],
		['Y11_Q39d_stress', 'Stressi'],
		['Y11_Q24', 'Voiko mielestänne suurimpaan osaan ihmisistä luottaa vai oletteko sitä mieltä, ettei kanssakäynnissä ihmisten kanssa voi olla liian varovainen?'],
		['Y11_Q25a', 'Havaittu jännite köyhien ja rikkaiden välillä'],
		['Y11_Q25b', 'Havaittu jännite johtoportaan ja työntekijöiden välillä'],
		['Y11_Q25c', 'Havaittu jännite miesten ja naisten välillä'],
		['Y11_Q25d', 'Havaittu jännite vanhojen ja nuorten ihmisten välillä'],
		['Y11_Q25e', 'Havaittu jännite eri rodullisten ja etnisten ryhmien väillä'],
		['Y11_Q25f', 'Havaittu jännite eri uskonnollisten ryhmien välillä'],
		['Y11_Q28a', 'Luottamus eduskuntaan'],
		['Y11_Q28b', 'Luottamus oikeusjärjestelmään'],
		['Y11_Q28c', 'Luottamus lehdistöön'],
		['Y11_Q28d', 'Luottamus poliisiin'],
		['Y11_Q28e', 'Luottamus hallitukseen']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Keskiarvo'],
		['Y11_Deprindex', 'Mean', 'Keskiarvo'],
		['Y11_Q12a', '1--Several-times-a-week', 'Useita kertoja viikossa'],
		['Y11_Q12a', '2--Several-times-a-month', 'Useita kertoja kuukaudessa'],
		['Y11_Q12a', '3--Several-times-a-year', 'Useita kertoja vuodessa'],
		['Y11_Q12a', '4--Less-often-rarely', 'Harvemmin'],
		['Y11_Q12a', '5--Never', 'Ei koskaan'],
		['Y11_Q12b', '1--Several-times-a-week', 'Useita kertoja viikossa'],
		['Y11_Q12b', '2--Several-times-a-month', 'Useita kertoja kuukaudessa'],
		['Y11_Q12b', '3--Several-times-a-year', 'Useita kertoja vuodessa'],
		['Y11_Q12b', '4--Less-often-rarely', 'Harvemmin'],
		['Y11_Q12b', '5--Never', 'Ei koskaan'],
		['Y11_Q12c', '1--Several-times-a-week', 'Useita kertoja viikossa'],
		['Y11_Q12c', '2--Several-times-a-month', 'Useita kertoja kuukaudessa'],
		['Y11_Q12c', '3--Several-times-a-year', 'Useita kertoja vuodessa'],
		['Y11_Q12c', '4--Less-often-rarely', 'Harvemmin'],
		['Y11_Q12c', '5--Never', 'Ei koskaan'],
		['Y11_Q15', '1--Very-likely', 'Hyvin todennäköisesti'],
		['Y11_Q15', '2--Quite-likely', 'Melko todennäköisesti'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'En todennäköisesti enkä epätodennäköisesti'],
		['Y11_Q15', '4--Quite-unlikely', 'Melko epätodennäköisesti'],
		['Y11_Q15', '5--Very-unlikely', 'Hyvin epätodennäköisesti'],
		['Y11_Q18', '1--Own-without-mortgage', 'Omistusasunto, ei ole asuntolainaa'],
		['Y11_Q18', '2--Own-with-mortgage', 'Omistusasunto, on asuntolainaa'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Vuokralla, kunta tai yhteisö vuokranantajana'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Vuokralla, yksityinen vuokranantaja'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Asuminen järjestetty ilman vuokraa'],
		['Y11_Q18', '6--Other', 'Muu'],
		['Y11_Q19a', '1--Yes', 'Kyllä'],
		['Y11_Q19a', '2--No', 'Ei'],
		['Y11_Q19b', '1--Yes', 'Kyllä'],
		['Y11_Q19b', '2--No', 'Ei'],
		['Y11_Q19c', '1--Yes', 'Kyllä'],
		['Y11_Q19c', '2--No', 'Ei'],
		['Y11_Q19d', '1--Yes', 'Kyllä'],
		['Y11_Q19d', '2--No', 'Ei'],
		['Y11_Q19e', '1--Yes', 'Kyllä'],
		['Y11_Q19e', '2--No', 'Ei'],
		['Y11_Q19f', '1--Yes', 'Kyllä'],
		['Y11_Q19f', '2--No', 'Ei'],
		['Y11_Q20', '1--Very-likely', 'Hyvin todennäköisesti'],
		['Y11_Q20', '2--Quite-likely', 'Melko todennäköisesti'],
		['Y11_Q20', '3--Quite-unlikely', 'Melko epätodennäköisesti'],
		['Y11_Q20', '4--Very-unlikely', 'Hyvin epätodennäköisesti'],
		['Y11_Q23a', '1--Yes', 'Kyllä'],
		['Y11_Q23a', '2--No', 'Ei'],
		['Y11_Q23d', '1--Yes', 'Kyllä'],
		['Y11_Q23d', '2--No', 'Ei'],
		['Y11_Q24', 'Mean', 'Keskiarvo'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Paljon jännitteitä'],
		['Y11_Q25a', '2--Some-tension', 'Jonkin verran jännitteitä'],
		['Y11_Q25a', '3--No-tension', 'Ei jännitteitä'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Paljon jännitteitä'],
		['Y11_Q25b', '2--Some-tension', 'Jonkin verran jännitteitä'],
		['Y11_Q25b', '3--No-tension', 'Ei jännitteitä'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Paljon jännitteitä'],
		['Y11_Q25c', '2--Some-tension', 'Jonkin verran jännitteitä'],
		['Y11_Q25c', '3--No-tension', 'Ei jännitteitä'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Paljon jännitteitä'],
		['Y11_Q25d', '2--Some-tension', 'Jonkin verran jännitteitä'],
		['Y11_Q25d', '3--No-tension', 'Ei jännitteitä'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Paljon jännitteitä'],
		['Y11_Q25e', '2--Some-tension', 'Jonkin verran jännitteitä'],
		['Y11_Q25e', '3--No-tension', 'Ei jännitteitä'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Paljon jännitteitä'],
		['Y11_Q25f', '2--Some-tension', 'Jonkin verran jännitteitä'],
		['Y11_Q25f', '3--No-tension', 'Ei jännitteitä'],
		['Y11_Q28a', 'Mean', 'Keskiarvo'],
		['Y11_Q28b', 'Mean', 'Keskiarvo'],
		['Y11_Q28c', 'Mean', 'Keskiarvo'],
		['Y11_Q28d', 'Mean', 'Keskiarvo'],
		['Y11_Q28e', 'Mean', 'Keskiarvo'],
		['Y11_Q29a', '1--Strongly-agree', 'Täysin samaa mieltä'],
		['Y11_Q29a', '2--Agree', 'Samaa mieltä'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Ei samaa eikä eri mieltä'],
		['Y11_Q29a', '4--Disagree', 'Eri mieltä'],
		['Y11_Q29a', '5--Strongly-disagree', 'Täysin eri mieltä'],
		['Y11_Q29e', '1--Strongly-agree', 'Täysin samaa mieltä'],
		['Y11_Q29e', '2--Agree', 'Samaa mieltä'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Ei samaa eikä eri mieltä'],
		['Y11_Q29e', '4--Disagree', 'Eri mieltä'],
		['Y11_Q29e', '5--Strongly-disagree', 'Täysin eri mieltä'],
		['Y11_Q29f', '1--Strongly-agree', 'Täysin samaa mieltä'],
		['Y11_Q29f', '2--Agree', 'Samaa mieltä'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Ei samaa eikä eri mieltä'],
		['Y11_Q29f', '4--Disagree', 'Eri mieltä'],
		['Y11_Q29f', '5--Strongly-disagree', 'Täysin eri mieltä'],
		['Y11_Q29g', '1--Strongly-agree', 'Täysin samaa mieltä'],
		['Y11_Q29g', '2--Agree', 'Samaa mieltä'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Ei samaa eikä eri mieltä'],
		['Y11_Q29g', '4--Disagree', 'Eri mieltä'],
		['Y11_Q29g', '5--Strongly-disagree', 'Täysin eri mieltä'],
		['Y11_Q29h', '1--Strongly-agree', 'Täysin samaa mieltä'],
		['Y11_Q29h', '2--Agree', 'Samaa mieltä'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Ei samaa eikä eri mieltä'],
		['Y11_Q29h', '4--Disagree', 'Eri mieltä'],
		['Y11_Q29h', '5--Strongly-disagree', 'Täysin eri mieltä'],
		['Y11_Q30', 'Mean', 'Keskiarvo'],
		['Y11_Q36b', '1--Every-day', 'Päivittäin'],
		['Y11_Q36b', '2--Several-days-a-week', 'Useita kertoja viikossa'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'Kerran tai kaksi viikossa'],
		['Y11_Q36b', '4--Less-often', 'Harvemmin'],
		['Y11_Q36b', '5--Never', 'En koskaan'],
		['Y11_Q36c', '1--Every-day', 'Päivittäin'],
		['Y11_Q36c', '2--Several-days-a-week', 'Useita kertoja viikossa'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'Kerran tai kaksi viikossa'],
		['Y11_Q36c', '4--Less-often', 'Harvemmin'],
		['Y11_Q36c', '5--Never', 'En koskaan'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Teen enemmän kuin kohtuullisen osuuteni'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Teen kohtuullisen osuuteni'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Teen vähemmän kuin kohtuullisen osuuteni'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'Työpaikalla ja kotona'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Joko työpaikalla tai kotona'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Vähän tai ei lainkaan stressiä'],
		['Y11_Q40a', 'Mean', 'Keskiarvo'],
		['Y11_Q40b', 'Mean', 'Keskiarvo'],
		['Y11_Q40c', 'Mean', 'Keskiarvo'],
		['Y11_Q40d', 'Mean', 'Keskiarvo'],
		['Y11_Q40e', 'Mean', 'Keskiarvo'],
		['Y11_Q40f', 'Mean', 'Keskiarvo'],
		['Y11_Q40g', 'Mean', 'Keskiarvo'],
		['Y11_Q41', 'Mean', 'Keskiarvo'],
		['Y11_Q42', '1--Very-good', 'Erittäin hyvä'],
		['Y11_Q42', '2--Good', 'Hyvä'],
		['Y11_Q42', '3--Fair', 'Kohtalainen'],
		['Y11_Q42', '4--Bad', 'Huono'],
		['Y11_Q42', '5--Very-bad', 'Erittäin huono'],
		['Y11_Q46d_WHO5', 'Mean', 'Keskiarvo'],
		['Y11_Q47a', '1--Very-difficult', 'Vaikeutti hyvin paljon'],
		['Y11_Q47a', '2--A-little-difficult', 'Vaikeutti jonkin verran'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Ei vaikeuttanut lainkaan'],
		['Y11_Q47b', '1--Very-difficult', 'Vaikeutti hyvin paljon'],
		['Y11_Q47b', '2--A-little-difficult', 'Vaikeutti jonkin verran'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Ei vaikeuttanut lainkaan'],
		['Y11_Q47c', '1--Very-difficult', 'Vaikeutti hyvin paljon'],
		['Y11_Q47c', '2--A-little-difficult', 'Vaikeutti jonkin verran'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Ei vaikeuttanut lainkaan'],
		['Y11_Q47d', '1--Very-difficult', 'Vaikeutti hyvin paljon'],
		['Y11_Q47d', '2--A-little-difficult', 'Vaikeutti jonkin verran'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Ei vaikeuttanut lainkaan'],
		['Y11_Q53a', 'Mean', 'Keskiarvo'],
		['Y11_Q53b', 'Mean', 'Keskiarvo'],
		['Y11_Q53c', 'Mean', 'Keskiarvo'],
		['Y11_Q53d', 'Mean', 'Keskiarvo'],
		['Y11_Q53g', 'Mean', 'Keskiarvo'],
		['Y11_Q58', '1--With-great-difficulty', 'Hyvin vaikeasti'],
		['Y11_Q58', '2--With-difficulty', 'Vaikeasti'],
		['Y11_Q58', '3--With-some-difficulty', 'Jonkin verran vaikeasti'],
		['Y11_Q58', '4--Fairly-easily', 'Melko helposti'],
		['Y11_Q58', '5--Easily', 'Helposti'],
		['Y11_Q58', '6--Very-easily', 'Hyvin helposti'],
		['Y11_Q59a', '1--No', 'Ei'],
		['Y11_Q59a', '2--Yes', 'Kyllä'],
		['Y11_Q59b', '1--No', 'Ei'],
		['Y11_Q59b', '2--Yes', 'Kyllä'],
		['Y11_Q59c', '1--No', 'Ei'],
		['Y11_Q59c', '2--Yes', 'Kyllä'],
		['Y11_Q59d', '1--No', 'Ei'],
		['Y11_Q59d', '2--Yes', 'Kyllä'],
		['Y11_Q59e', '1--No', 'Ei'],
		['Y11_Q59e', '2--Yes', 'Kyllä'],
		['Y11_Q59f', '1--No', 'Ei'],
		['Y11_Q59f', '2--Yes', 'Kyllä'],
		['Y11_Q60a', '1--Yes', 'Kyllä'],
		['Y11_Q60a', '2--No', 'Ei'],
		['Y11_Q60b', '1--Yes', 'Kyllä'],
		['Y11_Q60b', '2--No', 'Ei'],
		['Y11_SocExIndex', 'Mean', 'Keskiarvo']
	];
var country_
	 = [
	
		['AT', 'Itävalta'],
		['BE', 'Belgia'],
		['BG', 'Bulgaria'],
		['CY', 'Kypros'],
		['CZ', 'Tšekki'],
		['DE', 'Saksa'],
		['DK', 'Tanska'],
		['EE', 'Viro'],
		['EL', 'Kreikka'],
		['ES', 'Espanja'],
		['FI', 'Suomi'],
		['FR', 'Ranska'],
		['HR', 'Kroatia'],
		['HU', 'Unkari'],
		['IE', 'Irlanti'],
		['IT', 'Italia'],
		['LT', 'Liettua'],
		['LU', 'Luxemburg'],
		['LV', 'Latvia'],
		['MK', 'EJTM'],
		['MT', 'Malta'],
		['NL', 'Alankomaat'],
		['NO', 'Norja'],
		['PL', 'Puola'],
		['PT', 'Portugali'],
		['RO', 'Romania'],
		['SE', 'Ruotsi'],
		['SI', 'Slovenia'],
		['SK', 'Slovakia'],
		['TR', 'Turkki'],
		['UK', 'Yhdistynyt kuningaskunta'],
		['EuropeanUnion', 'Euroopan unioni']
	];
var question_meta
	 = [
	
		['Y11_Deprindex', 'Huono-osaisuuden indeksi: määrä asioista, joihin kotitalouksilla ei ole varaa', ''],
		['Y11_Q58', 'Ovatko kotitaloutenne tulot riittävät?', ''],
		['Y11_Q59a', 'Onko teillä varaa pitää koti riittävän lämpimänä?', ''],
		['Y11_Q59b', 'Onko teillä varaa vuosittaiseen lomaviikkoon poissa kotoa?', ''],
		['Y11_Q59c', 'Onko teillä varaa vaihtaa mikä tahansa kulunut huonekalu uuteen?', ''],
		['Y11_Q59d', 'Onko kotitaloudella varaa liha-, kana- tai kala-ateriaan joka toinen päivä (niin halutessanne)?', ''],
		['Y11_Q59e', 'Onko kotitalouden jäsenillä varaa ostaa uusia vaatteita käytettyjen sijaan?', ''],
		['Y11_Q59f', 'Onko kotitaloudella varaa kutsua ystäviä tai sukulaisia lasilliselle tai aterialle vähintään kerran kuussa?', ''],
		['Y11_Q60a', 'Onko kotitaloudella ollut asunnon vuokran tai asuntolainan maksuerän maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?', ''],
		['Y11_Q60b', 'Onko kotitaloudella ollut yleisiin asumiseen liittyvien kulujen maksuvaikeuksia viimeksi kuluneiden 12 kuukauden aikana?', ''],
		['Y11_Q42', 'Koettu terveydentila', ''],
		['Y11_Q46d_WHO5', 'Psyykkisen hyvinvoinnin WHO-5-indeksi', ''],
		['Y11_Q47a', 'Lääkäriin pääsyn vaikeus, koska lääkärin vastaanotto tai sairaala on kaukana', ''],
		['Y11_Q47b', 'Vastaanottoajan saamisen viivytyksen aiheuttamat ongelmat lääkäriin pääsyssä', ''],
		['Y11_Q47c', 'Lääkäriin pääsyn vaikeus, koska vastaanottopäivänä joutui odottamaan', ''],
		['Y11_Q47d', 'Lääkäriin pääsyn vaikeus lääkärikäynnin hinnan vuoksi', ''],
		['Y11_Q53a', 'Miten laadukkaaksi arvioisitte kotimaanne terveydenhuoltopalvelut?', ''],
		['Y11_Q53b', 'Miten laadukkaaksi arvioisitte kotimaanne koulutusjärjestelmän?', ''],
		['Y11_Q53c', 'Miten laadukkaaksi arvioisitte kotimaanne julkisen liikenteen?', ''],
		['Y11_Q53d', 'Miten laadukkaaksi arvioisitte kotimaanne lastenhoitopalvelut?', ''],
		['Y11_Q53g', 'Miten laadukkaaksi arvioisitte kotimaanne kansaneläkejärjestelmän?', ''],
		['Y11_Accommproblems', 'Asumisongelmien määrä', ''],
		['Y11_Q18', 'Omistusasuminen', ''],
		['Y11_Q19a', 'Asumiseen liittyvät ongelmat: tilanpuute', ''],
		['Y11_Q19b', 'Asumiseen liittyvät ongelmat: lahovaurioita ikkunoissa, ovissa tai lattioissa', ''],
		['Y11_Q19c', 'Asumiseen liittyvät ongelmat: kosteutta tai vuotoja seinissä tai katossa', ''],
		['Y11_Q19d', 'Asumiseen liittyvät ongelmat: sisävesivessan puuttuminen', ''],
		['Y11_Q19e', 'Asumiseen liittyvät ongelmat: suihkun tai ammeen puuttuminen', ''],
		['Y11_Q19f', 'Asumiseen liittyvät ongelmat: ulkona olevan oleskelutilan puuttuminen', ''],
		['Y11_Q20', 'Miten todennäköisesti joudutte luopumaan asunnostanne seuraavan puolen vuoden kuluessa, koska teillä ei enää ole varaa siihen?', ''],
		['Y11_Q23a', 'Osallistunut ammattiliiton, poliittisen puolueen tai toimintaryhmän kokoukseen', ''],
		['Y11_Q23d', 'Ottanut yhteyttä poliitikkoon tai virkamieheen (muu kuin julkisten palveluiden käyttöön liittyvä tavanomainen yhteydenotto)', ''],
		['Y11_Q29e', 'Tunnen olevani yhteiskunnan ulkopuolella', ''],
		['Y11_Q29f', 'Elämä on nykyään niin monimutkaista, että olen vähällä eksyä', ''],
		['Y11_Q29g', 'Muut eivät tunnu antavan arvoa tekemisilleni', ''],
		['Y11_Q29h', 'Jotkut halveksivat minua työtilanteeni tai ansiotasoni vuoksi', ''],
		['Y11_SocExIndex', 'Sosiaaliseen syrjäytymisen indeksi', ''],
		['Y11_Q29a', 'Olen optimistinen tulevaisuuden suhteen', ''],
		['Y11_Q30', 'Miten tyytyväinen olette elämäänne nykyään?', ''],
		['Y11_Q40a', 'Tyytyväisyys koulutukseen', ''],
		['Y11_Q40b', 'Tyytyväisyys nykyiseen työhön', ''],
		['Y11_Q40c', 'Tyytyväisyys nykyiseen elintasoon', ''],
		['Y11_Q40d', 'Tyytyväisyys asuntoon', ''],
		['Y11_Q40e', 'Tyytyväisyys perhe-elämään', ''],
		['Y11_Q40f', 'Tyytyväisyys terveydentilaan', ''],
		['Y11_Q40g', 'Tyytyväisyys sosiaaliseen elämään', ''],
		['Y11_Q41', 'Miten onnelliseksi arvioit itsesi kaiken kaikkiaan?', ''],
		['Y11_Q12a', 'Olen ollut liian väsynyt tekemään kotitöitä työpäivän jälkeen', ''],
		['Y11_Q12b', 'Perheeseen liittyvien velvollisuuksien täyttäminen on ollut hankalaa töissä vietetyn ajan vuoksi', ''],
		['Y11_Q12c', 'Perheeseen liittyvät velvollisuudet ovat vaikeuttaneet keskittymistä työpaikalla', ''],
		['Y11_Q15', 'Miten todennäköisesti voitte menettää työpaikkanne seuraavan puolen vuoden kuluessa?', ''],
		['Y11_Q36b', 'Kuinka usein osallistutte ruoanlaittoon tai kotitöihin?', ''],
		['Y11_Q36c', 'Kuinka usein hoidatte vanhoja tai vammaisia sukulaisianne?', ''],
		['Y11_Q38', 'Mitä mieltä olette tekemienne kotitöiden osuudesta?', ''],
		['Y11_Q39d_stress', 'Työ- ja yksityiselämän tasapainottelusta johtuva stressi', ''],
		['Y11_Q24', 'Voiko mielestänne suurimpaan osaan ihmisistä luottaa vai oletteko sitä mieltä, ettei kanssakäynnissä ihmisten kanssa voi olla liian varovainen?', ''],
		['Y11_Q25a', 'Havaittu jännite köyhien ja rikkaiden välillä', ''],
		['Y11_Q25b', 'Havaittu jännite johtoportaan ja työntekijöiden välillä', ''],
		['Y11_Q25c', 'Havaittu jännite miesten ja naisten välillä', ''],
		['Y11_Q25d', 'Havaittu jännite vanhojen ja nuorten ihmisten välillä', ''],
		['Y11_Q25e', 'Havaittu jännite eri rodullisten ja etnisten ryhmien väillä', ''],
		['Y11_Q25f', 'Havaittu jännite eri uskonnollisten ryhmien välillä', ''],
		['Y11_Q28a', 'Luottamus eduskuntaan', ''],
		['Y11_Q28b', 'Luottamus oikeusjärjestelmään', ''],
		['Y11_Q28c', 'Luottamus lehdistöön', ''],
		['Y11_Q28d', 'Luottamus poliisiin', ''],
		['Y11_Q28e', 'Luottamus hallitukseen', '']
	];
