//Auto Generated file
var subset_
	 = [
	
		['Y11_Incomequartiles_percapita', 'Revenus'],
		['Y11_HH2a', 'Sexe'],
		['Y11_Agecategory', 'Âge']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Tous les âges'],
		['Y11_Agecategory', '1--18-24y', '18-24 ans'],
		['Y11_Agecategory', '2--25-34y', '25-34 ans'],
		['Y11_Agecategory', '3--35-49y', '35-49 ans'],
		['Y11_Agecategory', '4--50-64y', '50-64 ans'],
		['Y11_Agecategory', '5---64y', 'Plus de 64 ans'],
		['Y11_HH2a', 'All', 'Tous les sexes'],
		['Y11_HH2a', '1--Female', 'Femme'],
		['Y11_HH2a', '2--Male', 'Homme'],
		['Y11_Incomequartiles_percapita', 'All', 'Tous les niveaux de revenus'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Le plus faible'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'Deuxième'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'Troisième'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Le plus élevé']
	];
var topic_
	 = [
	
		['', 'Tous (67)'],
		['Bien-être subjectif', 'Bien-être subjectif (10)'],
		['Domicile et environnement local', 'Domicile et environnement local (9)'],
		['Emploi et équilibre vie professionnelle/vie personnelle', 'Emploi et équilibre vie professionnelle/vie personnelle (8)'],
		['Exclusion sociale et participation à la communauté', 'Exclusion sociale et participation à la communauté (7)'],
		['Niveau de vie et privations', 'Niveau de vie et privations (10)'],
		['Qualité de la société', 'Qualité de la société (12)'],
		['Santé et services publics', 'Santé et services publics (11)']
	];
var topic_question
	 = [
	
		['Bien-être subjectif', 'Y11_Q29a', 'Je suis optimiste pour l’avenir'],
		['Bien-être subjectif', 'Y11_Q30', 'Quel est votre niveau de satisfaction à légard de votre vie à lheure actuelle ?'],
		['Bien-être subjectif', 'Y11_Q40a', 'Satisfaction par rapport au niveau d’éducation'],
		['Bien-être subjectif', 'Y11_Q40b', 'Satisfaction par rapport au poste occupé actuellement'],
		['Bien-être subjectif', 'Y11_Q40c', 'Satisfaction par rapport au niveau de vie actuel'],
		['Bien-être subjectif', 'Y11_Q40d', 'Satisfaction par rapport au logement'],
		['Bien-être subjectif', 'Y11_Q40e', 'Satisfaction par rapport à la vie familiale'],
		['Bien-être subjectif', 'Y11_Q40f', 'Satisfaction par rapport à l’état de santé'],
		['Bien-être subjectif', 'Y11_Q40g', 'Satisfaction par rapport à la vie sociale'],
		['Bien-être subjectif', 'Y11_Q41', 'Compte tenu de tous ces éléments, à quel point vous estimez-vous heureux ?'],
		['Domicile et environnement local', 'Y11_Accommproblems', 'Nombre de problèmes liés au logement'],
		['Domicile et environnement local', 'Y11_Q18', 'Accession à la propriété'],
		['Domicile et environnement local', 'Y11_Q19a', 'Problèmes de logement : manque d’espace'],
		['Domicile et environnement local', 'Y11_Q19b', 'Problèmes de logement : moisissure au niveau des fenêtres, des portes ou des sols'],
		['Domicile et environnement local', 'Y11_Q19c', 'Problèmes de logement : humidité ou fuites au niveau des murs ou du toit'],
		['Domicile et environnement local', 'Y11_Q19d', 'Problèmes de logement : absence de toilettes intérieures'],
		['Domicile et environnement local', 'Y11_Q19e', 'Problèmes de logement : absence de baignoire ou de douche'],
		['Domicile et environnement local', 'Y11_Q19f', 'Problèmes de logement : absence d’endroit à l’extérieur pour s’asseoir'],
		['Domicile et environnement local', 'Y11_Q20', 'Quelle est la probabilité que vous deviez quitter votre logement au cours des 6 prochains mois en raison de sa cherté ?'],
		['Emploi et équilibre vie professionnelle/vie personnelle', 'Y11_Q12a', 'J’étais trop las(se) pour effectuer des tâches domestiques à mon retour du travail'],
		['Emploi et équilibre vie professionnelle/vie personnelle', 'Y11_Q12b', 'J’ai rencontré des difficultés pour remplir mes obligations familiales en raison du temps que je consacre à ma vie professionnelle '],
		['Emploi et équilibre vie professionnelle/vie personnelle', 'Y11_Q12c', 'J’ai rencontré des difficultés pour me concentrer au travail en raison de mes obligations familiales'],
		['Emploi et équilibre vie professionnelle/vie personnelle', 'Y11_Q15', 'Quelle est la probabilité que vous perdiez votre emploi au cours des 6 prochains mois ?'],
		['Emploi et équilibre vie professionnelle/vie personnelle', 'Y11_Q36b', 'À quelle fréquence vous occupez-vous des tâches ménagères ou de la préparation des repas ?'],
		['Emploi et équilibre vie professionnelle/vie personnelle', 'Y11_Q36c', 'À quelle fréquence vous occupez-vous de vos parents âgés ou handicapés ?'],
		['Emploi et équilibre vie professionnelle/vie personnelle', 'Y11_Q38', 'Attitude vis-à-vis des tâches ménagères'],
		['Emploi et équilibre vie professionnelle/vie personnelle', 'Y11_Q39d_stress', 'Stress'],
		['Exclusion sociale et participation à la communauté', 'Y11_Q23a', 'Participation à une réunion d’un syndicat, d’un parti politique ou d’un groupe d’action au cours des 12 derniers mois'],
		['Exclusion sociale et participation à la communauté', 'Y11_Q23d', 'Contact d’un représentant politique ou public (autre que les contacts habituels via les services publics)'],
		['Exclusion sociale et participation à la communauté', 'Y11_Q29e', 'Je me sens exclu(e) de la société'],
		['Exclusion sociale et participation à la communauté', 'Y11_Q29f', 'La vie est si compliquée aujourd’hui que je me sens perdu(e)'],
		['Exclusion sociale et participation à la communauté', 'Y11_Q29g', 'J’ai le sentiment que la valeur de mon travail n’est pas reconnue par les autres'],
		['Exclusion sociale et participation à la communauté', 'Y11_Q29h', 'Certaines personnes expriment du dédain à mon encontre en raison de ma situation professionnelle ou de mes revenus'],
		['Exclusion sociale et participation à la communauté', 'Y11_SocExIndex', 'Indice dexclusion sociale'],
		['Niveau de vie et privations', 'Y11_Deprindex', 'Indice de privations:  nombre dobjets quun foyer ne peut pas se permettre dacheter'],
		['Niveau de vie et privations', 'Y11_Q58', 'Votre foyer parvient-il à joindre les deux bouts ?'],
		['Niveau de vie et privations', 'Y11_Q59a', 'Pouvez-vous vous permettre de maintenir un chauffage approprié de votre maison ?'],
		['Niveau de vie et privations', 'Y11_Q59b', 'Pouvez-vous vous permettre de payer une semaine de vacances annuelles ailleurs que chez vous ?'],
		['Niveau de vie et privations', 'Y11_Q59c', 'Pouvez-vous vous permettre de remplacer le mobilier vétuste ?'],
		['Niveau de vie et privations', 'Y11_Q59d', 'Pouvez-vous vous permettre de prendre un repas avec de la viande, de la volaille ou du poisson tous les deux jours (si vous le souhaitez) ?'],
		['Niveau de vie et privations', 'Y11_Q59e', 'Pouvez-vous vous permettre d’acheter des vêtements neufs, plutôt que des vêtements d’occasion ?'],
		['Niveau de vie et privations', 'Y11_Q59f', 'Pouvez-vous vous permettre de recevoir des amis ou de la famille autour d’un verre ou d’un repas au moins une fois par mois ?'],
		['Niveau de vie et privations', 'Y11_Q60a', 'Votre foyer a-t-il accusé des retards dans le paiement du loyer ou le remboursement d’un prêt immobilier au cours des 12 derniers mois ?'],
		['Niveau de vie et privations', 'Y11_Q60b', 'Votre foyer a-t-il accusé des retards dans le paiement des factures d’eau ou d’énergie au cours des 12 derniers mois ?'],
		['Qualité de la société', 'Y11_Q24', 'Diriez-vous que la plupart des personnes sont dignes de confiance ou qu’il faut toujours rester sur ses gardes dans les interactions avec les personnes ?'],
		['Qualité de la société', 'Y11_Q25a', 'Tension perçue entre les personnes pauvres et les personnes riches'],
		['Qualité de la société', 'Y11_Q25b', 'Tension perçue entre les cadres et les employés'],
		['Qualité de la société', 'Y11_Q25c', 'Tension perçue entre les hommes et les femmes'],
		['Qualité de la société', 'Y11_Q25d', 'Tension perçue entre les personnes âgées et les jeunes'],
		['Qualité de la société', 'Y11_Q25e', 'Tension perçue entre les différents groupes ethniques'],
		['Qualité de la société', 'Y11_Q25f', 'Tension perçue entre les différents groupes religieux'],
		['Qualité de la société', 'Y11_Q28a', 'Confiance dans les élus parlementaires'],
		['Qualité de la société', 'Y11_Q28b', 'Confiance dans le système judiciaire'],
		['Qualité de la société', 'Y11_Q28c', 'Confiance dans la presse'],
		['Qualité de la société', 'Y11_Q28d', 'Confiance dans les services de police'],
		['Qualité de la société', 'Y11_Q28e', 'Confiance dans le gouvernement'],
		['Santé et services publics', 'Y11_Q42', 'Perception de l’état de santé'],
		['Santé et services publics', 'Y11_Q46d_WHO5', 'Échelle de bien-être mental WHO-5'],
		['Santé et services publics', 'Y11_Q47a', 'Difficulté pour consulter un médecin en raison de l’éloignement géographique'],
		['Santé et services publics', 'Y11_Q47b', 'Difficulté pour consulter un médecin en raison des délais d’obtention d’un rendez-vous'],
		['Santé et services publics', 'Y11_Q47c', 'Difficulté pour consulter un médecin en raison du délai d’attente le jour du rendez-vous'],
		['Santé et services publics', 'Y11_Q47d', 'Difficulté pour consulter un médecin en raison du coût'],
		['Santé et services publics', 'Y11_Q53a', 'Comment évalueriez-vous la qualité des services de santé dans votre pays ?'],
		['Santé et services publics', 'Y11_Q53b', 'Comment évalueriez-vous la qualité du système éducatif dans votre pays ?'],
		['Santé et services publics', 'Y11_Q53c', 'Comment évalueriez-vous la qualité des transports publics dans votre pays ?'],
		['Santé et services publics', 'Y11_Q53d', 'Comment évalueriez-vous la qualité des services de garde d’enfants dans votre pays ?'],
		['Santé et services publics', 'Y11_Q53g', 'Comment évalueriez-vous la qualité du système de retraite dans votre pays ?']
	];
var question_
	 = [
	
		['Y11_Q29a', 'Je suis optimiste pour l’avenir'],
		['Y11_Q30', 'Quel est votre niveau de satisfaction à légard de votre vie à lheure actuelle ?'],
		['Y11_Q40a', 'Satisfaction par rapport au niveau d’éducation'],
		['Y11_Q40b', 'Satisfaction par rapport au poste occupé actuellement'],
		['Y11_Q40c', 'Satisfaction par rapport au niveau de vie actuel'],
		['Y11_Q40d', 'Satisfaction par rapport au logement'],
		['Y11_Q40e', 'Satisfaction par rapport à la vie familiale'],
		['Y11_Q40f', 'Satisfaction par rapport à l’état de santé'],
		['Y11_Q40g', 'Satisfaction par rapport à la vie sociale'],
		['Y11_Q41', 'Compte tenu de tous ces éléments, à quel point vous estimez-vous heureux ?'],
		['Y11_Accommproblems', 'Nombre de problèmes liés au logement'],
		['Y11_Q18', 'Accession à la propriété'],
		['Y11_Q19a', 'Problèmes de logement : manque d’espace'],
		['Y11_Q19b', 'Problèmes de logement : moisissure au niveau des fenêtres, des portes ou des sols'],
		['Y11_Q19c', 'Problèmes de logement : humidité ou fuites au niveau des murs ou du toit'],
		['Y11_Q19d', 'Problèmes de logement : absence de toilettes intérieures'],
		['Y11_Q19e', 'Problèmes de logement : absence de baignoire ou de douche'],
		['Y11_Q19f', 'Problèmes de logement : absence d’endroit à l’extérieur pour s’asseoir'],
		['Y11_Q20', 'Quelle est la probabilité que vous deviez quitter votre logement au cours des 6 prochains mois en raison de sa cherté ?'],
		['Y11_Q12a', 'J’étais trop las(se) pour effectuer des tâches domestiques à mon retour du travail'],
		['Y11_Q12b', 'J’ai rencontré des difficultés pour remplir mes obligations familiales en raison du temps que je consacre à ma vie professionnelle '],
		['Y11_Q12c', 'J’ai rencontré des difficultés pour me concentrer au travail en raison de mes obligations familiales'],
		['Y11_Q15', 'Quelle est la probabilité que vous perdiez votre emploi au cours des 6 prochains mois ?'],
		['Y11_Q36b', 'À quelle fréquence vous occupez-vous des tâches ménagères ou de la préparation des repas ?'],
		['Y11_Q36c', 'À quelle fréquence vous occupez-vous de vos parents âgés ou handicapés ?'],
		['Y11_Q38', 'Attitude vis-à-vis des tâches ménagères'],
		['Y11_Q39d_stress', 'Stress'],
		['Y11_Q23a', 'Participation à une réunion d’un syndicat, d’un parti politique ou d’un groupe d’action au cours des 12 derniers mois'],
		['Y11_Q23d', 'Contact d’un représentant politique ou public (autre que les contacts habituels via les services publics)'],
		['Y11_Q29e', 'Je me sens exclu(e) de la société'],
		['Y11_Q29f', 'La vie est si compliquée aujourd’hui que je me sens perdu(e)'],
		['Y11_Q29g', 'J’ai le sentiment que la valeur de mon travail n’est pas reconnue par les autres'],
		['Y11_Q29h', 'Certaines personnes expriment du dédain à mon encontre en raison de ma situation professionnelle ou de mes revenus'],
		['Y11_SocExIndex', 'Indice dexclusion sociale'],
		['Y11_Deprindex', 'Indice de privations:  nombre dobjets quun foyer ne peut pas se permettre dacheter'],
		['Y11_Q58', 'Votre foyer parvient-il à joindre les deux bouts ?'],
		['Y11_Q59a', 'Pouvez-vous vous permettre de maintenir un chauffage approprié de votre maison ?'],
		['Y11_Q59b', 'Pouvez-vous vous permettre de payer une semaine de vacances annuelles ailleurs que chez vous ?'],
		['Y11_Q59c', 'Pouvez-vous vous permettre de remplacer le mobilier vétuste ?'],
		['Y11_Q59d', 'Pouvez-vous vous permettre de prendre un repas avec de la viande, de la volaille ou du poisson tous les deux jours (si vous le souhaitez) ?'],
		['Y11_Q59e', 'Pouvez-vous vous permettre d’acheter des vêtements neufs, plutôt que des vêtements d’occasion ?'],
		['Y11_Q59f', 'Pouvez-vous vous permettre de recevoir des amis ou de la famille autour d’un verre ou d’un repas au moins une fois par mois ?'],
		['Y11_Q60a', 'Votre foyer a-t-il accusé des retards dans le paiement du loyer ou le remboursement d’un prêt immobilier au cours des 12 derniers mois ?'],
		['Y11_Q60b', 'Votre foyer a-t-il accusé des retards dans le paiement des factures d’eau ou d’énergie au cours des 12 derniers mois ?'],
		['Y11_Q24', 'Diriez-vous que la plupart des personnes sont dignes de confiance ou qu’il faut toujours rester sur ses gardes dans les interactions avec les personnes ?'],
		['Y11_Q25a', 'Tension perçue entre les personnes pauvres et les personnes riches'],
		['Y11_Q25b', 'Tension perçue entre les cadres et les employés'],
		['Y11_Q25c', 'Tension perçue entre les hommes et les femmes'],
		['Y11_Q25d', 'Tension perçue entre les personnes âgées et les jeunes'],
		['Y11_Q25e', 'Tension perçue entre les différents groupes ethniques'],
		['Y11_Q25f', 'Tension perçue entre les différents groupes religieux'],
		['Y11_Q28a', 'Confiance dans les élus parlementaires'],
		['Y11_Q28b', 'Confiance dans le système judiciaire'],
		['Y11_Q28c', 'Confiance dans la presse'],
		['Y11_Q28d', 'Confiance dans les services de police'],
		['Y11_Q28e', 'Confiance dans le gouvernement'],
		['Y11_Q42', 'Perception de l’état de santé'],
		['Y11_Q46d_WHO5', 'Échelle de bien-être mental WHO-5'],
		['Y11_Q47a', 'Difficulté pour consulter un médecin en raison de l’éloignement géographique'],
		['Y11_Q47b', 'Difficulté pour consulter un médecin en raison des délais d’obtention d’un rendez-vous'],
		['Y11_Q47c', 'Difficulté pour consulter un médecin en raison du délai d’attente le jour du rendez-vous'],
		['Y11_Q47d', 'Difficulté pour consulter un médecin en raison du coût'],
		['Y11_Q53a', 'Comment évalueriez-vous la qualité des services de santé dans votre pays ?'],
		['Y11_Q53b', 'Comment évalueriez-vous la qualité du système éducatif dans votre pays ?'],
		['Y11_Q53c', 'Comment évalueriez-vous la qualité des transports publics dans votre pays ?'],
		['Y11_Q53d', 'Comment évalueriez-vous la qualité des services de garde d’enfants dans votre pays ?'],
		['Y11_Q53g', 'Comment évalueriez-vous la qualité du système de retraite dans votre pays ?']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Moyen'],
		['Y11_Deprindex', 'Mean', 'Moyen'],
		['Y11_Q12a', '1--Several-times-a-week', 'Plusieurs fois par semaine'],
		['Y11_Q12a', '2--Several-times-a-month', 'Plusieurs fois par mois'],
		['Y11_Q12a', '3--Several-times-a-year', 'Plusieurs fois par an'],
		['Y11_Q12a', '4--Less-often-rarely', 'À loccasion ou rarement'],
		['Y11_Q12a', '5--Never', 'Jamais'],
		['Y11_Q12b', '1--Several-times-a-week', 'Plusieurs fois par semaine'],
		['Y11_Q12b', '2--Several-times-a-month', 'Plusieurs fois par mois'],
		['Y11_Q12b', '3--Several-times-a-year', 'Plusieurs fois par an'],
		['Y11_Q12b', '4--Less-often-rarely', 'À loccasion ou rarement'],
		['Y11_Q12b', '5--Never', 'Jamais'],
		['Y11_Q12c', '1--Several-times-a-week', 'Plusieurs fois par semaine'],
		['Y11_Q12c', '2--Several-times-a-month', 'Plusieurs fois par mois'],
		['Y11_Q12c', '3--Several-times-a-year', 'Plusieurs fois par an'],
		['Y11_Q12c', '4--Less-often-rarely', 'À loccasion ou rarement'],
		['Y11_Q12c', '5--Never', 'Jamais'],
		['Y11_Q15', '1--Very-likely', 'Très probable'],
		['Y11_Q15', '2--Quite-likely', 'Plutôt probable'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Ni probable ni improbable'],
		['Y11_Q15', '4--Quite-unlikely', 'Plutôt improbable'],
		['Y11_Q15', '5--Very-unlikely', 'Très improbable'],
		['Y11_Q18', '1--Own-without-mortgage', 'Propriétaire sans prêt en cours'],
		['Y11_Q18', '2--Own-with-mortgage', 'Propriétaire avec prêt en cours'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Locataire dun logement social ou municipal'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Locataire dun logement appartenant à un propriétaire privé'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Logement gratuit'],
		['Y11_Q18', '6--Other', 'Autres'],
		['Y11_Q19a', '1--Yes', 'Oui'],
		['Y11_Q19a', '2--No', 'Non'],
		['Y11_Q19b', '1--Yes', 'Oui'],
		['Y11_Q19b', '2--No', 'Non'],
		['Y11_Q19c', '1--Yes', 'Oui'],
		['Y11_Q19c', '2--No', 'Non'],
		['Y11_Q19d', '1--Yes', 'Oui'],
		['Y11_Q19d', '2--No', 'Non'],
		['Y11_Q19e', '1--Yes', 'Oui'],
		['Y11_Q19e', '2--No', 'Non'],
		['Y11_Q19f', '1--Yes', 'Oui'],
		['Y11_Q19f', '2--No', 'Non'],
		['Y11_Q20', '1--Very-likely', 'Très probable'],
		['Y11_Q20', '2--Quite-likely', 'Plutôt probable'],
		['Y11_Q20', '3--Quite-unlikely', 'Plutôt improbable'],
		['Y11_Q20', '4--Very-unlikely', 'Très improbable'],
		['Y11_Q23a', '1--Yes', 'Oui'],
		['Y11_Q23a', '2--No', 'Non'],
		['Y11_Q23d', '1--Yes', 'Oui'],
		['Y11_Q23d', '2--No', 'Non'],
		['Y11_Q24', 'Mean', 'Moyenne'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Tension importante'],
		['Y11_Q25a', '2--Some-tension', 'Tension peu importante'],
		['Y11_Q25a', '3--No-tension', 'Aucune tension'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Tension importante'],
		['Y11_Q25b', '2--Some-tension', 'Tension peu importante'],
		['Y11_Q25b', '3--No-tension', 'Aucune tension'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Tension importante'],
		['Y11_Q25c', '2--Some-tension', 'Tension peu importante'],
		['Y11_Q25c', '3--No-tension', 'Aucune tension'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Tension importante'],
		['Y11_Q25d', '2--Some-tension', 'Tension peu importante'],
		['Y11_Q25d', '3--No-tension', 'Aucune tension'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Tension importante'],
		['Y11_Q25e', '2--Some-tension', 'Tension peu importante'],
		['Y11_Q25e', '3--No-tension', 'Aucune tension'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Tension importante'],
		['Y11_Q25f', '2--Some-tension', 'Tension peu importante'],
		['Y11_Q25f', '3--No-tension', 'Aucune tension'],
		['Y11_Q28a', 'Mean', 'Moyenne'],
		['Y11_Q28b', 'Mean', 'Moyenne'],
		['Y11_Q28c', 'Mean', 'Moyenne'],
		['Y11_Q28d', 'Mean', 'Moyenne'],
		['Y11_Q28e', 'Mean', 'Moyenne'],
		['Y11_Q29a', '1--Strongly-agree', 'Tout à fait daccord'],
		['Y11_Q29a', '2--Agree', 'Daccord'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Ni daccord ni en désaccord'],
		['Y11_Q29a', '4--Disagree', 'Pas daccord'],
		['Y11_Q29a', '5--Strongly-disagree', 'Pas du tout d‘accord'],
		['Y11_Q29e', '1--Strongly-agree', 'Tout à fait daccord'],
		['Y11_Q29e', '2--Agree', 'Daccord'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Ni daccord ni en désaccord'],
		['Y11_Q29e', '4--Disagree', 'Pas daccord'],
		['Y11_Q29e', '5--Strongly-disagree', 'Pas du tout d‘accord'],
		['Y11_Q29f', '1--Strongly-agree', 'Tout à fait daccord'],
		['Y11_Q29f', '2--Agree', 'Daccord'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Ni daccord ni en désaccord'],
		['Y11_Q29f', '4--Disagree', 'Pas daccord'],
		['Y11_Q29f', '5--Strongly-disagree', 'Pas du tout d‘accord'],
		['Y11_Q29g', '1--Strongly-agree', 'Tout à fait daccord'],
		['Y11_Q29g', '2--Agree', 'Daccord'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Ni daccord ni en désaccord'],
		['Y11_Q29g', '4--Disagree', 'Pas daccord'],
		['Y11_Q29g', '5--Strongly-disagree', 'Pas du tout d‘accord'],
		['Y11_Q29h', '1--Strongly-agree', 'Tout à fait daccord'],
		['Y11_Q29h', '2--Agree', 'Daccord'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Ni daccord ni en désaccord'],
		['Y11_Q29h', '4--Disagree', 'Pas daccord'],
		['Y11_Q29h', '5--Strongly-disagree', 'Pas du tout d‘accord'],
		['Y11_Q30', 'Mean', 'Moyenne'],
		['Y11_Q36b', '1--Every-day', 'Tous les jours'],
		['Y11_Q36b', '2--Several-days-a-week', 'Plusieurs jours dans la semaine'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'Une à deux fois par semaine'],
		['Y11_Q36b', '4--Less-often', 'À loccasion'],
		['Y11_Q36b', '5--Never', 'Jamais'],
		['Y11_Q36c', '1--Every-day', 'Tous les jours'],
		['Y11_Q36c', '2--Several-days-a-week', 'Plusieurs jours dans la semaine'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'Une à deux fois par semaine'],
		['Y11_Q36c', '4--Less-often', 'À loccasion'],
		['Y11_Q36c', '5--Never', 'Jamais'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Plus que votre part équitable'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Juste votre part équitable'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Moins que votre part équitable'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'Au travail et à la maison'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Au travail ou à la maison'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Peu ou pas de stress'],
		['Y11_Q40a', 'Mean', 'Moyenne'],
		['Y11_Q40b', 'Mean', 'Moyenne'],
		['Y11_Q40c', 'Mean', 'Moyenne'],
		['Y11_Q40d', 'Mean', 'Moyenne'],
		['Y11_Q40e', 'Mean', 'Moyenne'],
		['Y11_Q40f', 'Mean', 'Moyenne'],
		['Y11_Q40g', 'Mean', 'Moyenne'],
		['Y11_Q41', 'Mean', 'Moyenne'],
		['Y11_Q42', '1--Very-good', 'Très bon'],
		['Y11_Q42', '2--Good', 'Bon'],
		['Y11_Q42', '3--Fair', 'Passable'],
		['Y11_Q42', '4--Bad', 'Mauvais'],
		['Y11_Q42', '5--Very-bad', 'Très mauvais'],
		['Y11_Q46d_WHO5', 'Mean', 'Moyenne'],
		['Y11_Q47a', '1--Very-difficult', 'Très difficile'],
		['Y11_Q47a', '2--A-little-difficult', 'Un peu difficile'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Pas difficile'],
		['Y11_Q47b', '1--Very-difficult', 'Très difficile'],
		['Y11_Q47b', '2--A-little-difficult', 'Un peu difficile'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Pas difficile'],
		['Y11_Q47c', '1--Very-difficult', 'Très difficile'],
		['Y11_Q47c', '2--A-little-difficult', 'Un peu difficile'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Pas difficile'],
		['Y11_Q47d', '1--Very-difficult', 'Très difficile'],
		['Y11_Q47d', '2--A-little-difficult', 'Un peu difficile'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Pas difficile'],
		['Y11_Q53a', 'Mean', 'Moyenne'],
		['Y11_Q53b', 'Mean', 'Moyenne'],
		['Y11_Q53c', 'Mean', 'Moyenne'],
		['Y11_Q53d', 'Mean', 'Moyenne'],
		['Y11_Q53g', 'Mean', 'Moyenne'],
		['Y11_Q58', '1--With-great-difficulty', 'Très difficile'],
		['Y11_Q58', '2--With-difficulty', 'Difficilement'],
		['Y11_Q58', '3--With-some-difficulty', 'Un peu difficile'],
		['Y11_Q58', '4--Fairly-easily', 'Assez facilement'],
		['Y11_Q58', '5--Easily', 'Facile'],
		['Y11_Q58', '6--Very-easily', 'Très facile'],
		['Y11_Q59a', '1--No', 'Non'],
		['Y11_Q59a', '2--Yes', 'Oui'],
		['Y11_Q59b', '1--No', 'Non'],
		['Y11_Q59b', '2--Yes', 'Oui'],
		['Y11_Q59c', '1--No', 'Non'],
		['Y11_Q59c', '2--Yes', 'Oui'],
		['Y11_Q59d', '1--No', 'Non'],
		['Y11_Q59d', '2--Yes', 'Oui'],
		['Y11_Q59e', '1--No', 'Non'],
		['Y11_Q59e', '2--Yes', 'Oui'],
		['Y11_Q59f', '1--No', 'Non'],
		['Y11_Q59f', '2--Yes', 'Oui'],
		['Y11_Q60a', '1--Yes', 'Oui'],
		['Y11_Q60a', '2--No', 'Non'],
		['Y11_Q60b', '1--Yes', 'Oui'],
		['Y11_Q60b', '2--No', 'Non'],
		['Y11_SocExIndex', 'Mean', 'Moyen']
	];
var country_
	 = [
	
		['AT', 'Autriche'],
		['BE', 'Belgique'],
		['BG', 'Bulgarie'],
		['CY', 'Chypre'],
		['CZ', 'République tchèque'],
		['DE', 'Allemagne'],
		['DK', 'Danemark'],
		['EE', 'Estonie'],
		['EL', 'Grèce'],
		['ES', 'Espagne'],
		['FI', 'Finlande'],
		['FR', 'France'],
		['HR', 'Croatie'],
		['HU', 'Hongrie'],
		['IE', 'Irlande'],
		['IT', 'Italie'],
		['LT', 'Lituanie'],
		['LU', 'Luxembourg'],
		['LV', 'Lettonie'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malte'],
		['NL', 'Pays-Bas'],
		['NO', 'Norvège'],
		['PL', 'Pologne'],
		['PT', 'Portugal'],
		['RO', 'Roumanie'],
		['SE', 'Suède'],
		['SI', 'Slovénie'],
		['SK', 'Slovaquie'],
		['TR', 'Turquie'],
		['UK', 'Royaume-Uni'],
		['EuropeanUnion', 'Union européenne']
	];
var question_meta
	 = [
	
		['Y11_Q29a', 'Je suis optimiste pour l’avenir', ''],
		['Y11_Q30', 'Quel est votre niveau de satisfaction à légard de votre vie à lheure actuelle ?', ''],
		['Y11_Q40a', 'Satisfaction par rapport au niveau d’éducation', ''],
		['Y11_Q40b', 'Satisfaction par rapport au poste occupé actuellement', ''],
		['Y11_Q40c', 'Satisfaction par rapport au niveau de vie actuel', ''],
		['Y11_Q40d', 'Satisfaction par rapport au logement', ''],
		['Y11_Q40e', 'Satisfaction par rapport à la vie familiale', ''],
		['Y11_Q40f', 'Satisfaction par rapport à l’état de santé', ''],
		['Y11_Q40g', 'Satisfaction par rapport à la vie sociale', ''],
		['Y11_Q41', 'Compte tenu de tous ces éléments, à quel point vous estimez-vous heureux ?', ''],
		['Y11_Accommproblems', 'Nombre de problèmes liés au logement', ''],
		['Y11_Q18', 'Accession à la propriété', ''],
		['Y11_Q19a', 'Problèmes de logement : manque d’espace', ''],
		['Y11_Q19b', 'Problèmes de logement : moisissure au niveau des fenêtres, des portes ou des sols', ''],
		['Y11_Q19c', 'Problèmes de logement : humidité ou fuites au niveau des murs ou du toit', ''],
		['Y11_Q19d', 'Problèmes de logement : absence de toilettes intérieures', ''],
		['Y11_Q19e', 'Problèmes de logement : absence de baignoire ou de douche', ''],
		['Y11_Q19f', 'Problèmes de logement : absence d’endroit à l’extérieur pour s’asseoir', ''],
		['Y11_Q20', 'Quelle est la probabilité que vous deviez quitter votre logement au cours des 6 prochains mois en raison de sa cherté croissante ?', ''],
		['Y11_Q12a', 'J’étais trop las(se) pour effectuer des tâches domestiques à mon retour du travail', ''],
		['Y11_Q12b', 'J’ai rencontré des difficultés pour remplir mes obligations familiales en raison du temps que je consacre à ma vie professionnelle ', ''],
		['Y11_Q12c', 'J’ai rencontré des difficultés pour me concentrer au travail en raison des mes obligations familiales', ''],
		['Y11_Q15', 'Quelle est la probabilité que vous perdiez votre emploi au cours des 6 prochains mois ?', ''],
		['Y11_Q36b', 'À quelle fréquence vous occupez-vous des tâches ménagères ou de la préparation des repas ?', ''],
		['Y11_Q36c', 'À quelle fréquence vous occupez-vous de vos parents âgés ou handicapés ?', ''],
		['Y11_Q38', 'Que pensez-vous de la part des tâches ménagères que vous effectuez ?', ''],
		['Y11_Q39d_stress', 'Stress provoqué par des problèmes liés à l’équilibre vie professionnelle/vie privée', ''],
		['Y11_Q23a', 'Participation à une réunion d’un syndicat, d’un parti politique ou d’un groupe d’action au cours des 12 derniers mois', ''],
		['Y11_Q23d', 'Contact d’un représentant politique ou public (autre que les contacts habituels via les services publics)', ''],
		['Y11_Q29e', 'Je me sens exclu(e) de la société', ''],
		['Y11_Q29f', 'La vie est si compliquée aujourd’hui que je me sens perdu(e)', ''],
		['Y11_Q29g', 'J’ai le sentiment que la valeur de mon travail n’est pas reconnue par les autres', ''],
		['Y11_Q29h', 'Certaines personnes expriment du dédain à mon encontre en raison de ma situation professionnelle ou de mes revenus', ''],
		['Y11_SocExIndex', 'Indice dexclusion sociale', ''],
		['Y11_Deprindex', 'Indice de privations:  nombre dobjets quun foyer ne peut pas se permettre dacheter', ''],
		['Y11_Q58', 'Votre foyer parvient-il à joindre les deux bouts ?', ''],
		['Y11_Q59a', 'Pouvez-vous vous permettre de maintenir un chauffage approprié de votre maison ?', ''],
		['Y11_Q59b', 'Pouvez-vous vous permettre de payer une semaine de vacances annuelles ailleurs que chez vous ?', ''],
		['Y11_Q59c', 'Pouvez-vous vous permettre de remplacer le mobilier vétuste ?', ''],
		['Y11_Q59d', 'Au sein de votre foyer, pouvez-vous vous permettre de prendre un repas avec de la viande, de la volaille ou du poisson tous les deux jours (si vous le souhaitez) ?', ''],
		['Y11_Q59e', 'Les membres de votre foyer peuvent-ils se permettre d’acheter des vêtements neufs, plutôt que des vêtements d’occasion ?', ''],
		['Y11_Q59f', 'Votre foyer peut-il se permettre de recevoir des amis ou de la famille autour d’un verre ou d’un repas au moins une fois par mois ?', ''],
		['Y11_Q60a', 'Votre foyer a-t-il accusé des retards dans le paiement du loyer ou le remboursement d’un prêt immobilier au cours des 12 derniers mois ?', ''],
		['Y11_Q60b', 'Votre foyer a-t-il accusé des retards dans le paiement des factures d’eau ou d’énergie au cours des 12 derniers mois ?', ''],
		['Y11_Q24', 'Diriez-vous que la plupart des personnes sont dignes de confiance ou qu’il faut toujours rester sur ses gardes dans les interactions avec les personnes ?', ''],
		['Y11_Q25a', 'Tension perçue entre les personnes pauvres et les personnes riches', ''],
		['Y11_Q25b', 'Tension perçue entre les cadres et les employés', ''],
		['Y11_Q25c', 'Tension perçue entre les hommes et les femmes', ''],
		['Y11_Q25d', 'Tension perçue entre les personnes âgées et les jeunes', ''],
		['Y11_Q25e', 'Tension perçue entre les différents groupes ethniques', ''],
		['Y11_Q25f', 'Tension perçue entre les différents groupes religieux', ''],
		['Y11_Q28a', 'Confiance dans les élus parlementaires', ''],
		['Y11_Q28b', 'Confiance dans le système judiciaire', ''],
		['Y11_Q28c', 'Confiance dans la presse', ''],
		['Y11_Q28d', 'Confiance dans les services de police', ''],
		['Y11_Q28e', 'Confiance dans le gouvernement', ''],
		['Y11_Q42', 'Perception de l’état de santé', ''],
		['Y11_Q46d_WHO5', 'Échelle de bien-être mental WHO-5', ''],
		['Y11_Q47a', 'Difficulté pour consulter un médecin en raison de l’éloignement géographique du cabinet médical ou de l’hôpital', ''],
		['Y11_Q47b', 'Difficulté pour consulter un médecin en raison des délais d’obtention d’un rendez-vous', ''],
		['Y11_Q47c', 'Difficulté pour consulter un médecin en raison du délai d’attente de la consultation le jour du rendez-vous', ''],
		['Y11_Q47d', 'Difficulté pour consulter un médecin en raison du coût de la consultation', ''],
		['Y11_Q53a', 'Comment évalueriez-vous la qualité des services de santé dans votre pays ?', ''],
		['Y11_Q53b', 'Comment évalueriez-vous la qualité du système éducatif dans votre pays ?', ''],
		['Y11_Q53c', 'Comment évalueriez-vous la qualité des transports publics dans votre pays ?', ''],
		['Y11_Q53d', 'Comment évalueriez-vous la qualité des services de garde d’enfants dans votre pays ?', ''],
		['Y11_Q53g', 'Comment évalueriez-vous la qualité du système de retraite dans votre pays ?', '']
	];
