//Auto Generated file
var subset_
	 = [
	
		['Y11_Agecategory', 'Dob'],
		['Y11_Incomequartiles_percapita', 'Prihod'],
		['Y11_HH2a', 'Spol']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Sve dobne skupine'],
		['Y11_Agecategory', '1--18-24y', 'od 18 do 24 godine'],
		['Y11_Agecategory', '2--25-34y', 'od 25 do 34 godine'],
		['Y11_Agecategory', '3--35-49y', 'od 35 do 49 godina'],
		['Y11_Agecategory', '4--50-64y', 'od 50 do 64 godine'],
		['Y11_Agecategory', '5---64y', '> 64 godine'],
		['Y11_HH2a', 'All', 'Oba spola'],
		['Y11_HH2a', '1--Female', 'Žensko'],
		['Y11_HH2a', '2--Male', 'Muško'],
		['Y11_Incomequartiles_percapita', 'All', 'Sve razine prihoda'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Najniži'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'Drugi'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'Treći'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Najviši']
	];
var topic_
	 = [
	
		['', 'Svi (67)'],
		['Dom i mjesno okruženje', 'Dom i mjesno okruženje (9)'],
		['Društvena isključenost i uključenost u zajednicu', 'Društvena isključenost i uključenost u zajednicu (7)'],
		['Kvaliteta društva', 'Kvaliteta društva (12)'],
		['Osobni osjećaj dobrobiti', 'Osobni osjećaj dobrobiti (10)'],
		['Zaposlenost i ravnoteža između poslovnog i privatnog života', 'Zaposlenost i ravnoteža između poslovnog i privatnog života (8)'],
		['Zdravstvene i javne službe', 'Zdravstvene i javne službe (11)'],
		['Životni standard i uskraćivanje', 'Životni standard i uskraćivanje (10)']
	];
var topic_question
	 = [
	
		['Dom i mjesno okruženje', 'Y11_Accommproblems', 'Broj problema s uvjetima stanovanja'],
		['Dom i mjesno okruženje', 'Y11_Q18', 'Vlasništvo doma'],
		['Dom i mjesno okruženje', 'Y11_Q19a', 'Problemi sa smještajem: Manjak prostora'],
		['Dom i mjesno okruženje', 'Y11_Q19b', 'Problemi sa smještajem: Propadanje prozora, vrata ili podova'],
		['Dom i mjesno okruženje', 'Y11_Q19c', 'Problemi sa smještajem: Vlaga ili propuštanje zidova ili krovišta'],
		['Dom i mjesno okruženje', 'Y11_Q19d', 'Problemi sa smještajem: Nepostojanje zahoda s vodom za ispiranje u zatvorenom prostoru'],
		['Dom i mjesno okruženje', 'Y11_Q19e', 'Problemi sa smještajem: Nepostojanje kade ili tuša'],
		['Dom i mjesno okruženje', 'Y11_Q19f', 'Problemi sa smještajem: Nedostatak prostora za sjedenje na otvorenome'],
		['Dom i mjesno okruženje', 'Y11_Q20', 'Kolika je vjerojatnost da ćete trenutačni smještaj napustiti u sljedećih šest mjeseci jer si ga ne možete priuštiti?'],
		['Društvena isključenost i uključenost u zajednicu', 'Y11_Q23a', 'Nazočnost sastanku sindikata, političke stranke ili djelatne skupine u posljednjih 12 mjeseci'],
		['Društvena isključenost i uključenost u zajednicu', 'Y11_Q23d', 'Kontaktirao/la političara ili javnog dužnosnika (osim rutinskog kontakta preko javnih službi)'],
		['Društvena isključenost i uključenost u zajednicu', 'Y11_Q29e', 'Osjećam se isključeno iz društva'],
		['Društvena isključenost i uključenost u zajednicu', 'Y11_Q29f', 'Život mi je postao toliko složen da jedva pronalazim izlaz'],
		['Društvena isključenost i uključenost u zajednicu', 'Y11_Q29g', 'Osjećam da vrijednost mojega rada nije prepoznata'],
		['Društvena isključenost i uključenost u zajednicu', 'Y11_Q29h', 'Neke me osobe omalovažavaju zbog mojega poslovnog položaja ili prihoda'],
		['Društvena isključenost i uključenost u zajednicu', 'Y11_SocExIndex', 'Indeks socijalne isključenosti'],
		['Kvaliteta društva', 'Y11_Q24', 'Biste li rekli da se većini ljudi može vjerovati ili da u odnosu s ljudima dodatan oprez nikad nije naodmet?'],
		['Kvaliteta društva', 'Y11_Q25a', 'Percepcija napetosti između bogatih i siromašnih'],
		['Kvaliteta društva', 'Y11_Q25b', 'Percepcija napetosti između uprave i radnika'],
		['Kvaliteta društva', 'Y11_Q25c', 'Percepcija napetosti između žena i muškaraca'],
		['Kvaliteta društva', 'Y11_Q25d', 'Percepcija napetosti između starih i mladih'],
		['Kvaliteta društva', 'Y11_Q25e', 'Percepcija napetosti među različitim rasnim i etničkim skupinama'],
		['Kvaliteta društva', 'Y11_Q25f', 'Percepcija napetosti među različitim religijskim skupinama'],
		['Kvaliteta društva', 'Y11_Q28a', 'Povjerenje u parlament'],
		['Kvaliteta društva', 'Y11_Q28b', 'Povjerenje u pravni sustav'],
		['Kvaliteta društva', 'Y11_Q28c', 'Povjerenje u novinstvo'],
		['Kvaliteta društva', 'Y11_Q28d', 'Povjerenje u policiju'],
		['Kvaliteta društva', 'Y11_Q28e', 'Povjerenje u vladu'],
		['Osobni osjećaj dobrobiti', 'Y11_Q29a', 'Optimističan/optimistična sam kada je riječ o budućnosti'],
		['Osobni osjećaj dobrobiti', 'Y11_Q30', 'Koliko ste trenutačno zadovoljni svojim životom?'],
		['Osobni osjećaj dobrobiti', 'Y11_Q40a', 'Zadovoljstvo obrazovanjem'],
		['Osobni osjećaj dobrobiti', 'Y11_Q40b', 'Zadovoljstvo sadašnjim zaposlenjem'],
		['Osobni osjećaj dobrobiti', 'Y11_Q40c', 'Zadovoljstvo trenutačnim životnim standardom'],
		['Osobni osjećaj dobrobiti', 'Y11_Q40d', 'Zadovoljstvo smještajem'],
		['Osobni osjećaj dobrobiti', 'Y11_Q40e', 'Zadovoljstvo obiteljskim životom'],
		['Osobni osjećaj dobrobiti', 'Y11_Q40f', 'Zadovoljstvo zdravljem'],
		['Osobni osjećaj dobrobiti', 'Y11_Q40g', 'Zadovoljstvo društvenim životom'],
		['Osobni osjećaj dobrobiti', 'Y11_Q41', 'Uzevši sve u obzir, što biste rekli, koliko ste sretni?'],
		['Zaposlenost i ravnoteža između poslovnog i privatnog života', 'Y11_Q12a', 'Nakon posla stigao/la sam kući preumoran/preumorna za obavljanje kućanskih poslova'],
		['Zaposlenost i ravnoteža između poslovnog i privatnog života', 'Y11_Q12b', 'Ispunjavanje obiteljskih obveza postaje sve zahtjevnije zbog vremena provedenoga na poslu '],
		['Zaposlenost i ravnoteža između poslovnog i privatnog života', 'Y11_Q12c', 'Zbog obiteljskih se obveza teže usredotočujem na poslu'],
		['Zaposlenost i ravnoteža između poslovnog i privatnog života', 'Y11_Q15', 'Kolika je vjerojatnost da u sljedećih šest mjeseci možete izgubiti posao?'],
		['Zaposlenost i ravnoteža između poslovnog i privatnog života', 'Y11_Q36b', 'Koliko često kuhate ili obavljate kućanske poslove?'],
		['Zaposlenost i ravnoteža između poslovnog i privatnog života', 'Y11_Q36c', 'Koliko često sudjelujete u skrbi za starije članove obitelji i radno nesposobne rođake ili rođake s invaliditetom?'],
		['Zaposlenost i ravnoteža između poslovnog i privatnog života', 'Y11_Q38', 'Stajalište prema podjeli kućanskih poslova'],
		['Zaposlenost i ravnoteža između poslovnog i privatnog života', 'Y11_Q39d_stress', 'Stres'],
		['Zdravstvene i javne službe', 'Y11_Q42', 'Percepcija zdravstvenog statusa'],
		['Zdravstvene i javne službe', 'Y11_Q46d_WHO5', 'WHO-5 ljestvica psihičke dobrobiti'],
		['Zdravstvene i javne službe', 'Y11_Q47a', 'Otežan posjet liječniku zbog udaljenosti'],
		['Zdravstvene i javne službe', 'Y11_Q47b', 'Otežan posjet liječniku zbog odgode dodjele termina'],
		['Zdravstvene i javne službe', 'Y11_Q47c', 'Otežan posjet liječniku zbog dugog čekanja dana dodijeljenog termina'],
		['Zdravstvene i javne službe', 'Y11_Q47d', 'Otežan posjet liječniku zbog troškova'],
		['Zdravstvene i javne službe', 'Y11_Q53a', 'Kako biste ocijenili kvalitetu zdravstvenih usluga u svojoj zemlji?'],
		['Zdravstvene i javne službe', 'Y11_Q53b', 'Kako biste ocijenili kvalitetu obrazovnog sustava u svojoj zemlji?'],
		['Zdravstvene i javne službe', 'Y11_Q53c', 'Kako biste ocijenili kvalitetu javnog prijevoza u svojoj zemlji?'],
		['Zdravstvene i javne službe', 'Y11_Q53d', 'Kako biste ocijenili kvalitetu usluga skrbi za djecu u svojoj zemlji?'],
		['Zdravstvene i javne službe', 'Y11_Q53g', 'Kako biste ocijenili kvalitetu državnoga mirovinskog sustava u svojoj zemlji?'],
		['Životni standard i uskraćivanje', 'Y11_Deprindex', 'Indeks prikraćenosti: broj artikala koje si domaćinstva ne mogu priuštiti'],
		['Životni standard i uskraćivanje', 'Y11_Q58', 'Spaja li Vaše kućanstvo kraj s krajem?'],
		['Životni standard i uskraćivanje', 'Y11_Q59a', 'Možete li si priuštiti odgovarajuću razinu zagrijanosti doma?'],
		['Životni standard i uskraćivanje', 'Y11_Q59b', 'Možete li si jedanput na godinu priuštiti jednotjedni odmor izvan doma?'],
		['Životni standard i uskraćivanje', 'Y11_Q59c', 'Možete li si priuštiti zamjenu istrošenog namještaja?'],
		['Životni standard i uskraćivanje', 'Y11_Q59d', 'Možete li si priuštiti mesni ili riblji obrok ili obrok s piletinom svakoga drugog dana (ako ga poželite)?'],
		['Životni standard i uskraćivanje', 'Y11_Q59e', 'Možete li si priuštiti novu odjeću, a ne rabljenu?'],
		['Životni standard i uskraćivanje', 'Y11_Q59f', 'Možete li si najmanje jedanput na mjesec priuštiti da pozovete prijatelje ili obitelj na piće ili jelo?'],
		['Životni standard i uskraćivanje', 'Y11_Q60a', 'Je li Vaše kućanstvo u posljednjih 12 mjeseci bilo u zaostalim dugovima za stanarinu ili hipoteku?'],
		['Životni standard i uskraćivanje', 'Y11_Q60b', 'Je li Vaše kućanstvo u posljednjih 12 mjeseci bilo u zaostalim dugovima za komunalije?']
	];
var question_
	 = [
	
		['Y11_Accommproblems', 'Broj problema s uvjetima stanovanja'],
		['Y11_Q18', 'Vlasništvo doma'],
		['Y11_Q19a', 'Problemi sa smještajem: Manjak prostora'],
		['Y11_Q19b', 'Problemi sa smještajem: Propadanje prozora, vrata ili podova'],
		['Y11_Q19c', 'Problemi sa smještajem: Vlaga ili propuštanje zidova ili krovišta'],
		['Y11_Q19d', 'Problemi sa smještajem: Nepostojanje zahoda s vodom za ispiranje u zatvorenom prostoru'],
		['Y11_Q19e', 'Problemi sa smještajem: Nepostojanje kade ili tuša'],
		['Y11_Q19f', 'Problemi sa smještajem: Nedostatak prostora za sjedenje na otvorenome'],
		['Y11_Q20', 'Kolika je vjerojatnost da ćete trenutačni smještaj napustiti u sljedećih šest mjeseci jer si ga ne možete priuštiti?'],
		['Y11_Q23a', 'Nazočnost sastanku sindikata, političke stranke ili djelatne skupine u posljednjih 12 mjeseci'],
		['Y11_Q23d', 'Kontaktirao/la političara ili javnog dužnosnika (osim rutinskog kontakta preko javnih službi)'],
		['Y11_Q29e', 'Osjećam se isključeno iz društva'],
		['Y11_Q29f', 'Život mi je postao toliko složen da jedva pronalazim izlaz'],
		['Y11_Q29g', 'Osjećam da vrijednost mojega rada nije prepoznata'],
		['Y11_Q29h', 'Neke me osobe omalovažavaju zbog mojega poslovnog položaja ili prihoda'],
		['Y11_SocExIndex', 'Indeks socijalne isključenosti'],
		['Y11_Q24', 'Biste li rekli da se većini ljudi može vjerovati ili da u odnosu s ljudima dodatan oprez nikad nije naodmet?'],
		['Y11_Q25a', 'Percepcija napetosti između bogatih i siromašnih'],
		['Y11_Q25b', 'Percepcija napetosti između uprave i radnika'],
		['Y11_Q25c', 'Percepcija napetosti između žena i muškaraca'],
		['Y11_Q25d', 'Percepcija napetosti između starih i mladih'],
		['Y11_Q25e', 'Percepcija napetosti među različitim rasnim i etničkim skupinama'],
		['Y11_Q25f', 'Percepcija napetosti među različitim religijskim skupinama'],
		['Y11_Q28a', 'Povjerenje u parlament'],
		['Y11_Q28b', 'Povjerenje u pravni sustav'],
		['Y11_Q28c', 'Povjerenje u novinstvo'],
		['Y11_Q28d', 'Povjerenje u policiju'],
		['Y11_Q28e', 'Povjerenje u vladu'],
		['Y11_Q29a', 'Optimističan/optimistična sam kada je riječ o budućnosti'],
		['Y11_Q30', 'Koliko ste trenutačno zadovoljni svojim životom?'],
		['Y11_Q40a', 'Zadovoljstvo obrazovanjem'],
		['Y11_Q40b', 'Zadovoljstvo sadašnjim zaposlenjem'],
		['Y11_Q40c', 'Zadovoljstvo trenutačnim životnim standardom'],
		['Y11_Q40d', 'Zadovoljstvo smještajem'],
		['Y11_Q40e', 'Zadovoljstvo obiteljskim životom'],
		['Y11_Q40f', 'Zadovoljstvo zdravljem'],
		['Y11_Q40g', 'Zadovoljstvo društvenim životom'],
		['Y11_Q41', 'Uzevši sve u obzir, što biste rekli, koliko ste sretni?'],
		['Y11_Q12a', 'Nakon posla stigao/la sam kući preumoran/preumorna za obavljanje kućanskih poslova'],
		['Y11_Q12b', 'Ispunjavanje obiteljskih obveza postaje sve zahtjevnije zbog vremena provedenoga na poslu '],
		['Y11_Q12c', 'Zbog obiteljskih se obveza teže usredotočujem na poslu'],
		['Y11_Q15', 'Kolika je vjerojatnost da u sljedećih šest mjeseci možete izgubiti posao?'],
		['Y11_Q36b', 'Koliko često kuhate ili obavljate kućanske poslove?'],
		['Y11_Q36c', 'Koliko često sudjelujete u skrbi za starije članove obitelji i radno nesposobne rođake ili rođake s invaliditetom?'],
		['Y11_Q38', 'Stajalište prema podjeli kućanskih poslova'],
		['Y11_Q39d_stress', 'Stres'],
		['Y11_Q42', 'Percepcija zdravstvenog statusa'],
		['Y11_Q46d_WHO5', 'WHO-5 ljestvica psihičke dobrobiti'],
		['Y11_Q47a', 'Otežan posjet liječniku zbog udaljenosti'],
		['Y11_Q47b', 'Otežan posjet liječniku zbog odgode dodjele termina'],
		['Y11_Q47c', 'Otežan posjet liječniku zbog dugog čekanja dana dodijeljenog termina'],
		['Y11_Q47d', 'Otežan posjet liječniku zbog troškova'],
		['Y11_Q53a', 'Kako biste ocijenili kvalitetu zdravstvenih usluga u svojoj zemlji?'],
		['Y11_Q53b', 'Kako biste ocijenili kvalitetu obrazovnog sustava u svojoj zemlji?'],
		['Y11_Q53c', 'Kako biste ocijenili kvalitetu javnog prijevoza u svojoj zemlji?'],
		['Y11_Q53d', 'Kako biste ocijenili kvalitetu usluga skrbi za djecu u svojoj zemlji?'],
		['Y11_Q53g', 'Kako biste ocijenili kvalitetu državnoga mirovinskog sustava u svojoj zemlji?'],
		['Y11_Deprindex', 'Indeks prikraćenosti: broj artikala koje si domaćinstva ne mogu priuštiti'],
		['Y11_Q58', 'Spaja li Vaše kućanstvo kraj s krajem?'],
		['Y11_Q59a', 'Možete li si priuštiti odgovarajuću razinu zagrijanosti doma?'],
		['Y11_Q59b', 'Možete li si jedanput na godinu priuštiti jednotjedni odmor izvan doma?'],
		['Y11_Q59c', 'Možete li si priuštiti zamjenu istrošenog namještaja?'],
		['Y11_Q59d', 'Možete li si priuštiti mesni ili riblji obrok ili obrok s piletinom svakoga drugog dana (ako ga poželite)?'],
		['Y11_Q59e', 'Možete li si priuštiti novu odjeću, a ne rabljenu?'],
		['Y11_Q59f', 'Možete li si najmanje jedanput na mjesec priuštiti da pozovete prijatelje ili obitelj na piće ili jelo?'],
		['Y11_Q60a', 'Je li Vaše kućanstvo u posljednjih 12 mjeseci bilo u zaostalim dugovima za stanarinu ili hipoteku?'],
		['Y11_Q60b', 'Je li Vaše kućanstvo u posljednjih 12 mjeseci bilo u zaostalim dugovima za komunalije?']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Srednja vrijednost'],
		['Y11_Deprindex', 'Mean', 'Srednja vrijednost'],
		['Y11_Q12a', '1--Several-times-a-week', 'Nekoliko puta tjedno'],
		['Y11_Q12a', '2--Several-times-a-month', 'Nekoliko puta mjesečno'],
		['Y11_Q12a', '3--Several-times-a-year', 'Nekoliko puta godišnje'],
		['Y11_Q12a', '4--Less-often-rarely', 'Manje često ili rjeđe'],
		['Y11_Q12a', '5--Never', 'Nikad'],
		['Y11_Q12b', '1--Several-times-a-week', 'Nekoliko puta tjedno'],
		['Y11_Q12b', '2--Several-times-a-month', 'Nekoliko puta mjesečno'],
		['Y11_Q12b', '3--Several-times-a-year', 'Nekoliko puta godišnje'],
		['Y11_Q12b', '4--Less-often-rarely', 'Manje često ili rjeđe'],
		['Y11_Q12b', '5--Never', 'Nikad'],
		['Y11_Q12c', '1--Several-times-a-week', 'Nekoliko puta tjedno'],
		['Y11_Q12c', '2--Several-times-a-month', 'Nekoliko puta mjesečno'],
		['Y11_Q12c', '3--Several-times-a-year', 'Nekoliko puta godišnje'],
		['Y11_Q12c', '4--Less-often-rarely', 'Manje često ili rjeđe'],
		['Y11_Q12c', '5--Never', 'Nikad'],
		['Y11_Q15', '1--Very-likely', 'Vrlo vjerojatno'],
		['Y11_Q15', '2--Quite-likely', 'Prilično vjerojatno'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Ni vjerojatno ni nevjerojatno'],
		['Y11_Q15', '4--Quite-unlikely', 'Prilično nevjerojatno'],
		['Y11_Q15', '5--Very-unlikely', 'Vrlo nevjerojatno'],
		['Y11_Q18', '1--Own-without-mortgage', 'Vlasništvo bez hipoteke'],
		['Y11_Q18', '2--Own-with-mortgage', 'Vlasništvo s hipotekom'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Stanar koji plaća najamninu u društvenom, dobrovoljnom ili općinskom smještaju'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Stanar koji plaća najamninu privatnom vlasniku'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Omogućen je smještaj bez plaćanja najamnine'],
		['Y11_Q18', '6--Other', 'Drugo'],
		['Y11_Q19a', '1--Yes', 'Da'],
		['Y11_Q19a', '2--No', 'Ne'],
		['Y11_Q19b', '1--Yes', 'Da'],
		['Y11_Q19b', '2--No', 'Ne'],
		['Y11_Q19c', '1--Yes', 'Da'],
		['Y11_Q19c', '2--No', 'Ne'],
		['Y11_Q19d', '1--Yes', 'Da'],
		['Y11_Q19d', '2--No', 'Ne'],
		['Y11_Q19e', '1--Yes', 'Da'],
		['Y11_Q19e', '2--No', 'Ne'],
		['Y11_Q19f', '1--Yes', 'Da'],
		['Y11_Q19f', '2--No', 'Ne'],
		['Y11_Q20', '1--Very-likely', 'Vrlo vjerojatno'],
		['Y11_Q20', '2--Quite-likely', 'Prilično vjerojatno'],
		['Y11_Q20', '3--Quite-unlikely', 'Prilično nevjerojatno'],
		['Y11_Q20', '4--Very-unlikely', 'Vrlo nevjerojatno'],
		['Y11_Q23a', '1--Yes', 'Da'],
		['Y11_Q23a', '2--No', 'Ne'],
		['Y11_Q23d', '1--Yes', 'Da'],
		['Y11_Q23d', '2--No', 'Ne'],
		['Y11_Q24', 'Mean', 'Prosjek'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Mnogo napetosti'],
		['Y11_Q25a', '2--Some-tension', 'Nešto napetosti'],
		['Y11_Q25a', '3--No-tension', 'Nema napetosti'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Mnogo napetosti'],
		['Y11_Q25b', '2--Some-tension', 'Nešto napetosti'],
		['Y11_Q25b', '3--No-tension', 'Nema napetosti'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Mnogo napetosti'],
		['Y11_Q25c', '2--Some-tension', 'Nešto napetosti'],
		['Y11_Q25c', '3--No-tension', 'Nema napetosti'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Mnogo napetosti'],
		['Y11_Q25d', '2--Some-tension', 'Nešto napetosti'],
		['Y11_Q25d', '3--No-tension', 'Nema napetosti'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Mnogo napetosti'],
		['Y11_Q25e', '2--Some-tension', 'Nešto napetosti'],
		['Y11_Q25e', '3--No-tension', 'Nema napetosti'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Mnogo napetosti'],
		['Y11_Q25f', '2--Some-tension', 'Nešto napetosti'],
		['Y11_Q25f', '3--No-tension', 'Nema napetosti'],
		['Y11_Q28a', 'Mean', 'Prosjek'],
		['Y11_Q28b', 'Mean', 'Prosjek'],
		['Y11_Q28c', 'Mean', 'Prosjek'],
		['Y11_Q28d', 'Mean', 'Prosjek'],
		['Y11_Q28e', 'Mean', 'Prosjek'],
		['Y11_Q29a', '1--Strongly-agree', 'U potpunosti se slažem'],
		['Y11_Q29a', '2--Agree', 'Slažem se'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Nisam ni suglasan/suglasna ni nesuglasan/nesuglasna'],
		['Y11_Q29a', '4--Disagree', 'Ne slažem se'],
		['Y11_Q29a', '5--Strongly-disagree', 'U potpunosti se ne slažem'],
		['Y11_Q29e', '1--Strongly-agree', 'U potpunosti se slažem'],
		['Y11_Q29e', '2--Agree', 'Slažem se'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Nisam ni suglasan/suglasna ni nesuglasan/nesuglasna'],
		['Y11_Q29e', '4--Disagree', 'Ne slažem se'],
		['Y11_Q29e', '5--Strongly-disagree', 'U potpunosti se ne slažem'],
		['Y11_Q29f', '1--Strongly-agree', 'U potpunosti se slažem'],
		['Y11_Q29f', '2--Agree', 'Slažem se'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Nisam ni suglasan/suglasna ni nesuglasan/nesuglasna'],
		['Y11_Q29f', '4--Disagree', 'Ne slažem se'],
		['Y11_Q29f', '5--Strongly-disagree', 'U potpunosti se ne slažem'],
		['Y11_Q29g', '1--Strongly-agree', 'U potpunosti se slažem'],
		['Y11_Q29g', '2--Agree', 'Slažem se'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Nisam ni suglasan/suglasna ni nesuglasan/nesuglasna'],
		['Y11_Q29g', '4--Disagree', 'Ne slažem se'],
		['Y11_Q29g', '5--Strongly-disagree', 'U potpunosti se ne slažem'],
		['Y11_Q29h', '1--Strongly-agree', 'U potpunosti se slažem'],
		['Y11_Q29h', '2--Agree', 'Slažem se'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Nisam ni suglasan/suglasna ni nesuglasan/nesuglasna'],
		['Y11_Q29h', '4--Disagree', 'Ne slažem se'],
		['Y11_Q29h', '5--Strongly-disagree', 'U potpunosti se ne slažem'],
		['Y11_Q30', 'Mean', 'Prosjek'],
		['Y11_Q36b', '1--Every-day', 'Svaki dan'],
		['Y11_Q36b', '2--Several-days-a-week', 'Nekoliko dana u tjednu'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'Jednom ili dvaput tjedno'],
		['Y11_Q36b', '4--Less-often', 'Manje često'],
		['Y11_Q36b', '5--Never', 'Nikad'],
		['Y11_Q36c', '1--Every-day', 'Svaki dan'],
		['Y11_Q36c', '2--Several-days-a-week', 'Nekoliko dana u tjednu'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'Jednom ili dvaput tjedno'],
		['Y11_Q36c', '4--Less-often', 'Manje često'],
		['Y11_Q36c', '5--Never', 'Nikad'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Više nego Vam pripada'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Ono što Vam pripada'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Manje nego što Vam pripada'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'Na poslu i kod kuće'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Na poslu ili kod kuće'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Nema stresa ili ga je malo'],
		['Y11_Q40a', 'Mean', 'Prosjek'],
		['Y11_Q40b', 'Mean', 'Prosjek'],
		['Y11_Q40c', 'Mean', 'Prosjek'],
		['Y11_Q40d', 'Mean', 'Prosjek'],
		['Y11_Q40e', 'Mean', 'Prosjek'],
		['Y11_Q40f', 'Mean', 'Prosjek'],
		['Y11_Q40g', 'Mean', 'Prosjek'],
		['Y11_Q41', 'Mean', 'Prosjek'],
		['Y11_Q42', '1--Very-good', 'Vrlo dobro'],
		['Y11_Q42', '2--Good', 'Dobro'],
		['Y11_Q42', '3--Fair', 'Korektno'],
		['Y11_Q42', '4--Bad', 'Loše'],
		['Y11_Q42', '5--Very-bad', 'Vrlo loše'],
		['Y11_Q46d_WHO5', 'Mean', 'Prosjek'],
		['Y11_Q47a', '1--Very-difficult', 'Vrlo teško'],
		['Y11_Q47a', '2--A-little-difficult', 'Uz male poteškoće'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Bez poteškoća'],
		['Y11_Q47b', '1--Very-difficult', 'Vrlo teško'],
		['Y11_Q47b', '2--A-little-difficult', 'Uz male poteškoće'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Bez poteškoća'],
		['Y11_Q47c', '1--Very-difficult', 'Vrlo teško'],
		['Y11_Q47c', '2--A-little-difficult', 'Uz male poteškoće'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Bez poteškoća'],
		['Y11_Q47d', '1--Very-difficult', 'Vrlo teško'],
		['Y11_Q47d', '2--A-little-difficult', 'Uz male poteškoće'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Bez poteškoća'],
		['Y11_Q53a', 'Mean', 'Prosjek'],
		['Y11_Q53b', 'Mean', 'Prosjek'],
		['Y11_Q53c', 'Mean', 'Prosjek'],
		['Y11_Q53d', 'Mean', 'Prosjek'],
		['Y11_Q53g', 'Mean', 'Prosjek'],
		['Y11_Q58', '1--With-great-difficulty', 'Uz velike poteškoće'],
		['Y11_Q58', '2--With-difficulty', 'Uz poteškoće'],
		['Y11_Q58', '3--With-some-difficulty', 'Uz određene poteškoće'],
		['Y11_Q58', '4--Fairly-easily', 'Prilično lako'],
		['Y11_Q58', '5--Easily', 'Lako'],
		['Y11_Q58', '6--Very-easily', 'Vrlo lako'],
		['Y11_Q59a', '1--No', 'Ne'],
		['Y11_Q59a', '2--Yes', 'Da'],
		['Y11_Q59b', '1--No', 'Ne'],
		['Y11_Q59b', '2--Yes', 'Da'],
		['Y11_Q59c', '1--No', 'Ne'],
		['Y11_Q59c', '2--Yes', 'Da'],
		['Y11_Q59d', '1--No', 'Ne'],
		['Y11_Q59d', '2--Yes', 'Da'],
		['Y11_Q59e', '1--No', 'Ne'],
		['Y11_Q59e', '2--Yes', 'Da'],
		['Y11_Q59f', '1--No', 'Ne'],
		['Y11_Q59f', '2--Yes', 'Da'],
		['Y11_Q60a', '1--Yes', 'Da'],
		['Y11_Q60a', '2--No', 'Ne'],
		['Y11_Q60b', '1--Yes', 'Da'],
		['Y11_Q60b', '2--No', 'Ne'],
		['Y11_SocExIndex', 'Mean', 'Srednja vrijednost']
	];
var country_
	 = [
	
		['AT', 'Austrija'],
		['BE', 'Belgija'],
		['BG', 'Bugarska'],
		['CY', 'Cipar'],
		['CZ', 'Češka Republika'],
		['DE', 'Njemačka'],
		['DK', 'Danska'],
		['EE', 'Estonija'],
		['EL', 'Grčka'],
		['ES', 'Španjolska'],
		['FI', 'Finska'],
		['FR', 'Francuska'],
		['HR', 'Hrvatska'],
		['HU', 'Mađarska'],
		['IE', 'Irska'],
		['IT', 'Italija'],
		['LT', 'Litva'],
		['LU', 'Luksemburg'],
		['LV', 'Latvija'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Nizozemska'],
		['NO', 'Norveška'],
		['PL', 'Poljska'],
		['PT', 'Portugal'],
		['RO', 'Rumunjska'],
		['SE', 'Švedska'],
		['SI', 'Slovenija'],
		['SK', 'Slovačka'],
		['TR', 'Turska'],
		['UK', 'Ujedinjeno Kraljevstvo'],
		['EuropeanUnion', 'Europska unija']
	];
var question_meta
	 = [
	
		['Y11_Accommproblems', 'Broj problema s uvjetima stanovanja', ''],
		['Y11_Q18', 'Vlasništvo doma', ''],
		['Y11_Q19a', 'Problemi sa smještajem: Manjak prostora', ''],
		['Y11_Q19b', 'Problemi sa smještajem: Propadanje prozora, vrata ili podova', ''],
		['Y11_Q19c', 'Problemi sa smještajem: Vlaga ili propuštanje zidova ili krovišta', ''],
		['Y11_Q19d', 'Problemi sa smještajem: Nepostojanje zahoda s vodom za ispiranje u zatvorenom prostoru', ''],
		['Y11_Q19e', 'Problemi sa smještajem: Nepostojanje kade ili tuša', ''],
		['Y11_Q19f', 'Problemi sa smještajem: Nedostatak prostora za sjedenje na otvorenome', ''],
		['Y11_Q20', 'Kolika je vjerojatnost da ćete trenutačni smještaj napustiti u sljedećih šest mjeseci jer si ga ne možete priuštiti?', ''],
		['Y11_Q23a', 'Nazočnost sastanku sindikata, političke stranke ili djelatne skupine u posljednjih 12 mjeseci', ''],
		['Y11_Q23d', 'Kontaktirao/la političara ili javnog dužnosnika (osim rutinskog kontakta preko javnih službi)', ''],
		['Y11_Q29e', 'Osjećam se isključeno iz društva', ''],
		['Y11_Q29f', 'Život mi je postao toliko složen da jedva pronalazim izlaz', ''],
		['Y11_Q29g', 'Osjećam da vrijednost mojega rada nije prepoznata', ''],
		['Y11_Q29h', 'Neke me osobe omalovažavaju zbog mojega poslovnog položaja ili prihoda', ''],
		['Y11_SocExIndex', 'Indeks socijalne isključenosti', ''],
		['Y11_Q24', 'Biste li rekli da se većini ljudi može vjerovati ili da u odnosu s ljudima dodatan oprez nikad nije naodmet?', ''],
		['Y11_Q25a', 'Percepcija napetosti između bogatih i siromašnih', ''],
		['Y11_Q25b', 'Percepcija napetosti između uprave i radnika', ''],
		['Y11_Q25c', 'Percepcija napetosti između žena i muškaraca', ''],
		['Y11_Q25d', 'Percepcija napetosti između starih i mladih', ''],
		['Y11_Q25e', 'Percepcija napetosti među različitim rasnim i etničkim skupinama', ''],
		['Y11_Q25f', 'Percepcija napetosti među različitim religijskim skupinama', ''],
		['Y11_Q28a', 'Povjerenje u parlament', ''],
		['Y11_Q28b', 'Povjerenje u pravni sustav', ''],
		['Y11_Q28c', 'Povjerenje u novinstvo', ''],
		['Y11_Q28d', 'Povjerenje u policiju', ''],
		['Y11_Q28e', 'Povjerenje u vladu', ''],
		['Y11_Q29a', 'Optimističan/optimistična sam kada je riječ o budućnosti', ''],
		['Y11_Q30', 'Koliko ste trenutačno zadovoljni svojim životom?', ''],
		['Y11_Q40a', 'Zadovoljstvo obrazovanjem', ''],
		['Y11_Q40b', 'Zadovoljstvo sadašnjim zaposlenjem', ''],
		['Y11_Q40c', 'Zadovoljstvo trenutačnim životnim standardom', ''],
		['Y11_Q40d', 'Zadovoljstvo smještajem', ''],
		['Y11_Q40e', 'Zadovoljstvo obiteljskim životom', ''],
		['Y11_Q40f', 'Zadovoljstvo zdravljem', ''],
		['Y11_Q40g', 'Zadovoljstvo društvenim životom', ''],
		['Y11_Q41', 'Uzevši sve u obzir, što biste rekli, koliko ste sretni?', ''],
		['Y11_Q12a', ' Nakon posla stigao/la sam kući preumoran/preumorna za obavljanje kućanskih poslova', ''],
		['Y11_Q12b', 'Ispunjavanje obiteljskih obveza postaje sve zahtjevnije zbog vremena provedenoga na poslu ', ''],
		['Y11_Q12c', 'Zbog obiteljskih se obveza teže usredotočujem na poslu', ''],
		['Y11_Q15', 'Kolika je vjerojatnost da u sljedećih šest mjeseci možete izgubiti posao?', ''],
		['Y11_Q36b', 'Koliko često kuhate ili obavljate kućanske poslove?', ''],
		['Y11_Q36c', 'Koliko često sudjelujete u skrbi za starije članove obitelji i radno nesposobne rođake ili rođake s invaliditetom?', ''],
		['Y11_Q38', 'Što mislite o dijelu kućanskih poslova koji obavljate?', ''],
		['Y11_Q39d_stress', 'Stres uzrokovan pitanjima vezanima za ravnotežu između poslovnog i privatnog života', ''],
		['Y11_Q42', 'Percepcija zdravstvenog statusa', ''],
		['Y11_Q46d_WHO5', 'WHO-5 ljestvica psihičke dobrobiti', ''],
		['Y11_Q47a', 'Otežan posjet liječniku zbog udaljenosti liječničke ordinacije ili bolnice', ''],
		['Y11_Q47b', 'Otežan posjet liječniku zbog odgode dodjele termina', ''],
		['Y11_Q47c', 'Otežan posjet liječniku zbog dugog čekanja susreta s liječnikom na dan dodijeljenog termina', ''],
		['Y11_Q47d', 'Otežan posjet liječniku zbog troškova posjeta liječniku', ''],
		['Y11_Q53a', 'Kako biste ocijenili kvalitetu zdravstvenih usluga u svojoj zemlji?', ''],
		['Y11_Q53b', 'Kako biste ocijenili kvalitetu obrazovnog sustava u svojoj zemlji?', ''],
		['Y11_Q53c', 'Kako biste ocijenili kvalitetu javnog prijevoza u svojoj zemlji?', ''],
		['Y11_Q53d', 'Kako biste ocijenili kvalitetu usluga skrbi za djecu u svojoj zemlji?', ''],
		['Y11_Q53g', 'Kako biste ocijenili kvalitetu državnoga mirovinskog sustava u svojoj zemlji?', ''],
		['Y11_Deprindex', 'Indeks prikraćenosti: broj artikala koje si domaćinstva ne mogu priuštiti', ''],
		['Y11_Q58', 'Spaja li Vaše kućanstvo kraj s krajem?', ''],
		['Y11_Q59a', 'Možete li si priuštiti odgovarajuću razinu zagrijanosti doma?', ''],
		['Y11_Q59b', 'Možete li si jedanput na godinu priuštiti jednotjedni odmor izvan doma?', ''],
		['Y11_Q59c', 'Možete li si priuštiti zamjenu istrošenog namještaja?', ''],
		['Y11_Q59d', 'Možete li si priuštiti mesni ili riblji obrok ili obrok s piletinom svakoga drugog dana (ako ga poželite)?', ''],
		['Y11_Q59e', 'Možete li si priuštiti novu odjeću, a ne rabljenu?', ''],
		['Y11_Q59f', 'Možete li si najmanje jedanput na mjesec priuštiti da pozovete prijatelje ili obitelj na piće ili jelo?', ''],
		['Y11_Q60a', 'Je li Vaše kućanstvo u posljednjih 12 mjeseci bilo u zaostalim dugovima za stanarinu ili hipoteku?', ''],
		['Y11_Q60b', 'Je li Vaše kućanstvo u posljednjih 12 mjeseci bilo u zaostalim dugovima za komunalije?', '']
	];
