//Auto Generated file
var subset_
	 = [
	
		['Y11_Incomequartiles_percapita', 'Dochód'],
		['Y11_HH2a', 'Płeć'],
		['Y11_Agecategory', 'Wiek']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'W każdym wieku'],
		['Y11_Agecategory', '1--18-24y', 'Od 18 do 24 lat'],
		['Y11_Agecategory', '2--25-34y', 'Od 25 do 34 lat'],
		['Y11_Agecategory', '3--35-49y', 'Od 35 do 49 lat'],
		['Y11_Agecategory', '4--50-64y', 'Od 50 do 64 lat'],
		['Y11_Agecategory', '5---64y', 'powyżej 64 roku życia'],
		['Y11_HH2a', 'All', 'Kobiety i mężczyźni'],
		['Y11_HH2a', '1--Female', 'Kobiety'],
		['Y11_HH2a', '2--Male', 'Mężczyźni'],
		['Y11_Incomequartiles_percapita', 'All', 'Dochód na dowolnym poziomie'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Najniższy'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'II poziom'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'III poziom'],
		['Y11_Incomequartiles_percapita', '4--Highest', '4, Najwyższy']
	];
var topic_
	 = [
	
		['', 'Wszystkie (67)'],
		['Jakość społeczeństwa', 'Jakość społeczeństwa (12)'],
		['Opieka zdrowotna i usługi publiczne', 'Opieka zdrowotna i usługi publiczne (11)'],
		['Otoczenie domowe i najbliższa okolica', 'Otoczenie domowe i najbliższa okolica (9)'],
		['Standard życia i deprywacja', 'Standard życia i deprywacja (10)'],
		['Subiektywne samopoczucie', 'Subiektywne samopoczucie (10)'],
		['Wykluczenie społeczne i zaangażowanie społeczne', 'Wykluczenie społeczne i zaangażowanie społeczne (7)'],
		['Zatrudnienie i równowaga między życiem zawodowym a prywatnym', 'Zatrudnienie i równowaga między życiem zawodowym a prywatnym (8)']
	];
var topic_question
	 = [
	
		['Jakość społeczeństwa', 'Y11_Q24', 'Czy uważa Pan(i), że większości ludzi można ufać, czy też, że w kontaktach z ludźmi należy zachować ostrożność?'],
		['Jakość społeczeństwa', 'Y11_Q25a', 'Dostrzegane napięcia między biednymi i bogatymi'],
		['Jakość społeczeństwa', 'Y11_Q25b', 'Dostrzegane napięcia między pracodawcami i pracownikami'],
		['Jakość społeczeństwa', 'Y11_Q25c', 'Dostrzegane napięcia między mężczyznami i kobietami'],
		['Jakość społeczeństwa', 'Y11_Q25d', 'Dostrzegane napięcia między osobami starszymi i młodymi'],
		['Jakość społeczeństwa', 'Y11_Q25e', 'Dostrzegane napięcia między różnymi grupami rasowymi i etnicznymi'],
		['Jakość społeczeństwa', 'Y11_Q25f', 'Dostrzegane napięcia między różnymi grupami religijnymi'],
		['Jakość społeczeństwa', 'Y11_Q28a', 'Zaufanie do parlamentu'],
		['Jakość społeczeństwa', 'Y11_Q28b', 'Zaufanie do systemu prawnego'],
		['Jakość społeczeństwa', 'Y11_Q28c', 'Zaufanie do prasy'],
		['Jakość społeczeństwa', 'Y11_Q28d', 'Zaufanie do policji'],
		['Jakość społeczeństwa', 'Y11_Q28e', 'Zaufanie do rządu'],
		['Opieka zdrowotna i usługi publiczne', 'Y11_Q42', 'Ocena własnego stanu zdrowia'],
		['Opieka zdrowotna i usługi publiczne', 'Y11_Q46d_WHO5', 'Samopoczucie psychiczne według skali WHO-5'],
		['Opieka zdrowotna i usługi publiczne', 'Y11_Q47a', 'Problem z wizytą u lekarza z powodu odległości'],
		['Opieka zdrowotna i usługi publiczne', 'Y11_Q47b', 'Problem z wizytą u lekarza z powodu odległych terminów wizyty'],
		['Opieka zdrowotna i usługi publiczne', 'Y11_Q47c', 'Problem z wizytą u lekarza z powodu czasu oczekiwania w dniu wyznaczonej wizyty'],
		['Opieka zdrowotna i usługi publiczne', 'Y11_Q47d', 'Problem z wizytą u lekarza z uwagi na koszt'],
		['Opieka zdrowotna i usługi publiczne', 'Y11_Q53a', 'Jak oceniłby(-aby) Pan(i) jakość opieki zdrowotnej w Pana(-i) kraju?'],
		['Opieka zdrowotna i usługi publiczne', 'Y11_Q53b', 'Jak oceniłby(-aby) Pan(i) jakość systemu edukacji w Pana(-i) kraju?'],
		['Opieka zdrowotna i usługi publiczne', 'Y11_Q53c', 'Jak oceniłby(-aby) Pan(i) jakość transportu publicznego w Pana(-i) kraju?'],
		['Opieka zdrowotna i usługi publiczne', 'Y11_Q53d', 'Jak oceniłby(-aby) Pan(i) jakość usług opieki nad dziećmi w Pana(-i) kraju?'],
		['Opieka zdrowotna i usługi publiczne', 'Y11_Q53g', 'Jak oceniłby(-aby) Pan(i) jakość państwowego systemu świadczeń emerytalnych/rentowych w Pana(-i) kraju?'],
		['Otoczenie domowe i najbliższa okolica', 'Y11_Accommproblems', 'Liczba problemów z zakwaterowaniem'],
		['Otoczenie domowe i najbliższa okolica', 'Y11_Q18', 'Posiadanie domu/mieszkania'],
		['Otoczenie domowe i najbliższa okolica', 'Y11_Q19a', 'Problemy w miejscu zamieszkania: zbyt mała powierzchnia'],
		['Otoczenie domowe i najbliższa okolica', 'Y11_Q19b', 'Problemy w miejscu zamieszkania: butwiejące okna, drzwi lub podłogi'],
		['Otoczenie domowe i najbliższa okolica', 'Y11_Q19c', 'Problemy w miejscu zamieszkania: wilgoć lub nacieki na ścianach lub przeciekanie dachu'],
		['Otoczenie domowe i najbliższa okolica', 'Y11_Q19d', 'Problemy w miejscu zamieszkania: brak spłukiwanej toalety wewnątrz mieszkania'],
		['Otoczenie domowe i najbliższa okolica', 'Y11_Q19e', 'Problemy w miejscu zamieszkania: brak wanny lub prysznica'],
		['Otoczenie domowe i najbliższa okolica', 'Y11_Q19f', 'Problemy w miejscu zamieszkania: brak miejsca do spędzania czasu na zewnątrz'],
		['Otoczenie domowe i najbliższa okolica', 'Y11_Q20', 'Na ile Pana(-i) zdaniem jest prawdopodobne, że w ciągu najbliższych 6 miesięcy będzie Pan(i) zmuszony(-a) opuścić mieszkanie ze względu na brak pieniędzy na jego utrzymanie?'],
		['Standard życia i deprywacja', 'Y11_Deprindex', 'Wskaźnik deprywacji: Liczba artykułów, na które gospodarstwo nie stać'],
		['Standard życia i deprywacja', 'Y11_Q58', 'Czy Pana(-i) gospodarstwo domowe jest w stanie wiązać koniec z końcem?'],
		['Standard życia i deprywacja', 'Y11_Q59a', 'Czy jest Pan(i) w stanie ogrzać swoje mieszkanie do właściwej temperatury?'],
		['Standard życia i deprywacja', 'Y11_Q59b', 'Czy stać Pana (Panią) na tygodniowy urlop poza domem raz w roku?'],
		['Standard życia i deprywacja', 'Y11_Q59c', 'Czy stać Pana (Panią) na wymianę zużytych mebli?'],
		['Standard życia i deprywacja', 'Y11_Q59d', 'Czy stać Pana (Panią) na posiłek zawierający mięso, drób lub ryby co drugi dzień (jeżeli miałby(-aby) Pan(i) na to ochotę)?'],
		['Standard życia i deprywacja', 'Y11_Q59e', 'Czy stać Pana (Panią) na nowe, a nie używane ubrania?'],
		['Standard życia i deprywacja', 'Y11_Q59f', 'Czy stać Pana (Panią), aby przynajmniej raz w miesiącu zaprosić znajomych lub rodzinę na coś do picia lub do jedzenia?'],
		['Standard życia i deprywacja', 'Y11_Q60a', 'Czy w ciągu ostatnich 12 miesięcy Pana(-i) gospodarstwo domowe miało trudności z terminowym opłacaniem czynszu lub rat za mieszkanie?'],
		['Standard życia i deprywacja', 'Y11_Q60b', 'Czy w ciągu ostatnich 12 miesięcy Pana(-i) gospodarstwo domowe miało trudności z terminowym opłacaniem rachunków za świadczenia?'],
		['Subiektywne samopoczucie', 'Y11_Q29a', 'Optymistycznie patrzę w przyszłość'],
		['Subiektywne samopoczucie', 'Y11_Q30', 'Na ile jest Pan(i) zadowolony(-a) ze swojego obecnego życia?'],
		['Subiektywne samopoczucie', 'Y11_Q40a', 'Zadowolenie z wykształcenia'],
		['Subiektywne samopoczucie', 'Y11_Q40b', 'Zadowolenie z obecnej pracy'],
		['Subiektywne samopoczucie', 'Y11_Q40c', 'Zadowolenie z obecnego poziomu życia'],
		['Subiektywne samopoczucie', 'Y11_Q40d', 'Zadowolenie z warunków mieszkaniowych'],
		['Subiektywne samopoczucie', 'Y11_Q40e', 'Zadowolenie z życia rodzinnego'],
		['Subiektywne samopoczucie', 'Y11_Q40f', 'Zadowolenie ze swojego stanu zdrowia'],
		['Subiektywne samopoczucie', 'Y11_Q40g', 'Zadowolenie z życia towarzyskiego'],
		['Subiektywne samopoczucie', 'Y11_Q41', 'Ogólnie rzecz biorąc, na ile czuje się Pan(i) szczęśliwy(-a)?'],
		['Wykluczenie społeczne i zaangażowanie społeczne', 'Y11_Q23a', 'Udział w spotkaniu związków zawodowych, partii politycznej lub ruchu społecznego w ciągu ostatnich 12 miesięcy'],
		['Wykluczenie społeczne i zaangażowanie społeczne', 'Y11_Q23d', 'Kontakt z politykiem lub urzędnikiem państwowym (oprócz rutynowych kontaktów związanych z załatwianiem spraw urzędowych)'],
		['Wykluczenie społeczne i zaangażowanie społeczne', 'Y11_Q29e', 'Czuję się wyobcowany(-a) ze społeczeństwa '],
		['Wykluczenie społeczne i zaangażowanie społeczne', 'Y11_Q29f', 'Obecnie życie stało się tak skomplikowane, że czuję się zagubiony(-a)'],
		['Wykluczenie społeczne i zaangażowanie społeczne', 'Y11_Q29g', 'Nie czuję, żeby ludzie cenili to, co robię'],
		['Wykluczenie społeczne i zaangażowanie społeczne', 'Y11_Q29h', 'Niektórzy ludzie patrzą na mnie z góry ze względu na moją sytuację zawodową lub dochód'],
		['Wykluczenie społeczne i zaangażowanie społeczne', 'Y11_SocExIndex', 'Wskaźnik wykluczenia społecznego'],
		['Zatrudnienie i równowaga między życiem zawodowym a prywatnym', 'Y11_Q12a', 'Przyszedłem (Przyszłam) z pracy zbyt zmęczony(-a), aby wykonać prace domowe'],
		['Zatrudnienie i równowaga między życiem zawodowym a prywatnym', 'Y11_Q12b', 'Z powodu ilości czasu spędzonego w pracy było mi trudno wypełnić obowiązki rodzinne'],
		['Zatrudnienie i równowaga między życiem zawodowym a prywatnym', 'Y11_Q12c', 'Miałem(-am) trudności ze skoncentrowaniem się w pracy z powodu moich obowiązków rodzinnych'],
		['Zatrudnienie i równowaga między życiem zawodowym a prywatnym', 'Y11_Q15', 'Na ile Pana(-i) zdaniem jest prawdopodobne, że w ciągu najbliższych 6 miesięcy straci Pan(i) pracę?'],
		['Zatrudnienie i równowaga między życiem zawodowym a prywatnym', 'Y11_Q36b', 'Jak często spędza Pan(i) czas na gotowaniu i pracach domowych?'],
		['Zatrudnienie i równowaga między życiem zawodowym a prywatnym', 'Y11_Q36c', 'Jak często spędza Pan(i) czas nad opiece nad starszymi/niepełnosprawnymi członkami rodziny?'],
		['Zatrudnienie i równowaga między życiem zawodowym a prywatnym', 'Y11_Q38', 'Stosunek do obowiązków domowych'],
		['Zatrudnienie i równowaga między życiem zawodowym a prywatnym', 'Y11_Q39d_stress', 'Stres']
	];
var question_
	 = [
	
		['Y11_Q24', 'Czy uważa Pan(i), że większości ludzi można ufać, czy też, że w kontaktach z ludźmi należy zachować ostrożność?'],
		['Y11_Q25a', 'Dostrzegane napięcia między biednymi i bogatymi'],
		['Y11_Q25b', 'Dostrzegane napięcia między pracodawcami i pracownikami'],
		['Y11_Q25c', 'Dostrzegane napięcia między mężczyznami i kobietami'],
		['Y11_Q25d', 'Dostrzegane napięcia między osobami starszymi i młodymi'],
		['Y11_Q25e', 'Dostrzegane napięcia między różnymi grupami rasowymi i etnicznymi'],
		['Y11_Q25f', 'Dostrzegane napięcia między różnymi grupami religijnymi'],
		['Y11_Q28a', 'Zaufanie do parlamentu'],
		['Y11_Q28b', 'Zaufanie do systemu prawnego'],
		['Y11_Q28c', 'Zaufanie do prasy'],
		['Y11_Q28d', 'Zaufanie do policji'],
		['Y11_Q28e', 'Zaufanie do rządu'],
		['Y11_Q42', 'Ocena własnego stanu zdrowia'],
		['Y11_Q46d_WHO5', 'Samopoczucie psychiczne według skali WHO-5'],
		['Y11_Q47a', 'Problem z wizytą u lekarza z powodu odległości'],
		['Y11_Q47b', 'Problem z wizytą u lekarza z powodu odległych terminów wizyty'],
		['Y11_Q47c', 'Problem z wizytą u lekarza z powodu czasu oczekiwania w dniu wyznaczonej wizyty'],
		['Y11_Q47d', 'Problem z wizytą u lekarza z uwagi na koszt'],
		['Y11_Q53a', 'Jak oceniłby(-aby) Pan(i) jakość opieki zdrowotnej w Pana(-i) kraju?'],
		['Y11_Q53b', 'Jak oceniłby(-aby) Pan(i) jakość systemu edukacji w Pana(-i) kraju?'],
		['Y11_Q53c', 'Jak oceniłby(-aby) Pan(i) jakość transportu publicznego w Pana(-i) kraju?'],
		['Y11_Q53d', 'Jak oceniłby(-aby) Pan(i) jakość usług opieki nad dziećmi w Pana(-i) kraju?'],
		['Y11_Q53g', 'Jak oceniłby(-aby) Pan(i) jakość państwowego systemu świadczeń emerytalnych/rentowych w Pana(-i) kraju?'],
		['Y11_Accommproblems', 'Liczba problemów z zakwaterowaniem'],
		['Y11_Q18', 'Posiadanie domu/mieszkania'],
		['Y11_Q19a', 'Problemy w miejscu zamieszkania: zbyt mała powierzchnia'],
		['Y11_Q19b', 'Problemy w miejscu zamieszkania: butwiejące okna, drzwi lub podłogi'],
		['Y11_Q19c', 'Problemy w miejscu zamieszkania: wilgoć lub nacieki na ścianach lub przeciekanie dachu'],
		['Y11_Q19d', 'Problemy w miejscu zamieszkania: brak spłukiwanej toalety wewnątrz mieszkania'],
		['Y11_Q19e', 'Problemy w miejscu zamieszkania: brak wanny lub prysznica'],
		['Y11_Q19f', 'Problemy w miejscu zamieszkania: brak miejsca do spędzania czasu na zewnątrz'],
		['Y11_Q20', 'Na ile Pana(-i) zdaniem jest prawdopodobne, że w ciągu najbliższych 6 miesięcy będzie Pan(i) zmuszony(-a) opuścić mieszkanie ze względu na brak pieniędzy na jego utrzymanie?'],
		['Y11_Deprindex', 'Wskaźnik deprywacji: Liczba artykułów, na które gospodarstwo nie stać'],
		['Y11_Q58', 'Czy Pana(-i) gospodarstwo domowe jest w stanie wiązać koniec z końcem?'],
		['Y11_Q59a', 'Czy jest Pan(i) w stanie ogrzać swoje mieszkanie do właściwej temperatury?'],
		['Y11_Q59b', 'Czy stać Pana (Panią) na tygodniowy urlop poza domem raz w roku?'],
		['Y11_Q59c', 'Czy stać Pana (Panią) na wymianę zużytych mebli?'],
		['Y11_Q59d', 'Czy stać Pana (Panią) na posiłek zawierający mięso, drób lub ryby co drugi dzień (jeżeli miałby(-aby) Pan(i) na to ochotę)?'],
		['Y11_Q59e', 'Czy stać Pana (Panią) na nowe, a nie używane ubrania?'],
		['Y11_Q59f', 'Czy stać Pana (Panią), aby przynajmniej raz w miesiącu zaprosić znajomych lub rodzinę na coś do picia lub do jedzenia?'],
		['Y11_Q60a', 'Czy w ciągu ostatnich 12 miesięcy Pana(-i) gospodarstwo domowe miało trudności z terminowym opłacaniem czynszu lub rat za mieszkanie?'],
		['Y11_Q60b', 'Czy w ciągu ostatnich 12 miesięcy Pana(-i) gospodarstwo domowe miało trudności z terminowym opłacaniem rachunków za świadczenia?'],
		['Y11_Q29a', 'Optymistycznie patrzę w przyszłość'],
		['Y11_Q30', 'Na ile jest Pan(i) zadowolony(-a) ze swojego obecnego życia?'],
		['Y11_Q40a', 'Zadowolenie z wykształcenia'],
		['Y11_Q40b', 'Zadowolenie z obecnej pracy'],
		['Y11_Q40c', 'Zadowolenie z obecnego poziomu życia'],
		['Y11_Q40d', 'Zadowolenie z warunków mieszkaniowych'],
		['Y11_Q40e', 'Zadowolenie z życia rodzinnego'],
		['Y11_Q40f', 'Zadowolenie ze swojego stanu zdrowia'],
		['Y11_Q40g', 'Zadowolenie z życia towarzyskiego'],
		['Y11_Q41', 'Ogólnie rzecz biorąc, na ile czuje się Pan(i) szczęśliwy(-a)?'],
		['Y11_Q23a', 'Udział w spotkaniu związków zawodowych, partii politycznej lub ruchu społecznego w ciągu ostatnich 12 miesięcy'],
		['Y11_Q23d', 'Kontakt z politykiem lub urzędnikiem państwowym (oprócz rutynowych kontaktów związanych z załatwianiem spraw urzędowych)'],
		['Y11_Q29e', 'Czuję się wyobcowany(-a) ze społeczeństwa '],
		['Y11_Q29f', 'Obecnie życie stało się tak skomplikowane, że czuję się zagubiony(-a)'],
		['Y11_Q29g', 'Nie czuję, żeby ludzie cenili to, co robię'],
		['Y11_Q29h', 'Niektórzy ludzie patrzą na mnie z góry ze względu na moją sytuację zawodową lub dochód'],
		['Y11_SocExIndex', 'Wskaźnik wykluczenia społecznego'],
		['Y11_Q12a', 'Przyszedłem (Przyszłam) z pracy zbyt zmęczony(-a), aby wykonać prace domowe'],
		['Y11_Q12b', 'Z powodu ilości czasu spędzonego w pracy było mi trudno wypełnić obowiązki rodzinne'],
		['Y11_Q12c', 'Miałem(-am) trudności ze skoncentrowaniem się w pracy z powodu moich obowiązków rodzinnych'],
		['Y11_Q15', 'Na ile Pana(-i) zdaniem jest prawdopodobne, że w ciągu najbliższych 6 miesięcy straci Pan(i) pracę?'],
		['Y11_Q36b', 'Jak często spędza Pan(i) czas na gotowaniu i pracach domowych?'],
		['Y11_Q36c', 'Jak często spędza Pan(i) czas nad opiece nad starszymi/niepełnosprawnymi członkami rodziny?'],
		['Y11_Q38', 'Stosunek do obowiązków domowych'],
		['Y11_Q39d_stress', 'Stres']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Średnia'],
		['Y11_Deprindex', 'Mean', 'Średnia'],
		['Y11_Q12a', '1--Several-times-a-week', 'Kilka razy w tygodniu'],
		['Y11_Q12a', '2--Several-times-a-month', 'Kilka razy w miesiącu'],
		['Y11_Q12a', '3--Several-times-a-year', 'Kilka razy w roku'],
		['Y11_Q12a', '4--Less-often-rarely', 'Rzadziej'],
		['Y11_Q12a', '5--Never', 'Nigdy'],
		['Y11_Q12b', '1--Several-times-a-week', 'Kilka razy w tygodniu'],
		['Y11_Q12b', '2--Several-times-a-month', 'Kilka razy w miesiącu'],
		['Y11_Q12b', '3--Several-times-a-year', 'Kilka razy w roku'],
		['Y11_Q12b', '4--Less-often-rarely', 'Rzadziej'],
		['Y11_Q12b', '5--Never', 'Nigdy'],
		['Y11_Q12c', '1--Several-times-a-week', 'Kilka razy w tygodniu'],
		['Y11_Q12c', '2--Several-times-a-month', 'Kilka razy w miesiącu'],
		['Y11_Q12c', '3--Several-times-a-year', 'Kilka razy w roku'],
		['Y11_Q12c', '4--Less-often-rarely', 'Rzadziej'],
		['Y11_Q12c', '5--Never', 'Nigdy'],
		['Y11_Q15', '1--Very-likely', 'Bardzo prawdopodobne'],
		['Y11_Q15', '2--Quite-likely', 'Raczej prawdopodobne'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Ani tak, ani nie'],
		['Y11_Q15', '4--Quite-unlikely', 'Raczej nieprawdopodobne'],
		['Y11_Q15', '5--Very-unlikely', 'Zupełnie nieprawdopodobne'],
		['Y11_Q18', '1--Own-without-mortgage', 'Własne mieszkanie/dom nieobciążone hipoteką'],
		['Y11_Q18', '2--Own-with-mortgage', 'Własne mieszkanie/dom obciążone hipoteką'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Mieszkanie socjalne / TBS / komunalne / kwaterunkowe/ spółdzielcze lokatorskie/zakładowe wynajmowane za czynsz'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Mieszkanie wynajmowane za czynsz od prywatnego właściciela'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Mieszkanie udostępnione/użyczone za darmo'],
		['Y11_Q18', '6--Other', 'Inne'],
		['Y11_Q19a', '1--Yes', 'Tak'],
		['Y11_Q19a', '2--No', 'Nie'],
		['Y11_Q19b', '1--Yes', 'Tak'],
		['Y11_Q19b', '2--No', 'Nie'],
		['Y11_Q19c', '1--Yes', 'Tak'],
		['Y11_Q19c', '2--No', 'Nie'],
		['Y11_Q19d', '1--Yes', 'Tak'],
		['Y11_Q19d', '2--No', 'Nie'],
		['Y11_Q19e', '1--Yes', 'Tak'],
		['Y11_Q19e', '2--No', 'Nie'],
		['Y11_Q19f', '1--Yes', 'Tak'],
		['Y11_Q19f', '2--No', 'Nie'],
		['Y11_Q20', '1--Very-likely', 'Bardzo prawdopodobne'],
		['Y11_Q20', '2--Quite-likely', 'Raczej prawdopodobne'],
		['Y11_Q20', '3--Quite-unlikely', 'Raczej nieprawdopodobne'],
		['Y11_Q20', '4--Very-unlikely', 'Zupełnie nieprawdopodobne'],
		['Y11_Q23a', '1--Yes', 'Tak'],
		['Y11_Q23a', '2--No', 'Nie'],
		['Y11_Q23d', '1--Yes', 'Tak'],
		['Y11_Q23d', '2--No', 'Nie'],
		['Y11_Q24', 'Mean', 'Średnio'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Duże napięcie'],
		['Y11_Q25a', '2--Some-tension', 'Pewne napięcie'],
		['Y11_Q25a', '3--No-tension', 'Brak napięcia'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Duże napięcie'],
		['Y11_Q25b', '2--Some-tension', 'Pewne napięcie'],
		['Y11_Q25b', '3--No-tension', 'Brak napięcia'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Duże napięcie'],
		['Y11_Q25c', '2--Some-tension', 'Pewne napięcie'],
		['Y11_Q25c', '3--No-tension', 'Brak napięcia'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Duże napięcie'],
		['Y11_Q25d', '2--Some-tension', 'Pewne napięcie'],
		['Y11_Q25d', '3--No-tension', 'Brak napięcia'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Duże napięcie'],
		['Y11_Q25e', '2--Some-tension', 'Pewne napięcie'],
		['Y11_Q25e', '3--No-tension', 'Brak napięcia'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Duże napięcie'],
		['Y11_Q25f', '2--Some-tension', 'Pewne napięcie'],
		['Y11_Q25f', '3--No-tension', 'Brak napięcia'],
		['Y11_Q28a', 'Mean', 'Średnia'],
		['Y11_Q28b', 'Mean', 'Średnia'],
		['Y11_Q28c', 'Mean', 'Średnia'],
		['Y11_Q28d', 'Mean', 'Średnia'],
		['Y11_Q28e', 'Mean', 'Średnia'],
		['Y11_Q29a', '1--Strongly-agree', 'Zdecydowanie się zgadzam'],
		['Y11_Q29a', '2--Agree', 'Zgadzam się'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Ani się zgadzam, ani się nie zgadzam'],
		['Y11_Q29a', '4--Disagree', 'Nie zgadzam się'],
		['Y11_Q29a', '5--Strongly-disagree', 'Zdecydowanie się nie zgadzam'],
		['Y11_Q29e', '1--Strongly-agree', 'Zdecydowanie się zgadzam'],
		['Y11_Q29e', '2--Agree', 'Zgadzam się'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Ani się zgadzam, ani się nie zgadzam'],
		['Y11_Q29e', '4--Disagree', 'Nie zgadzam się'],
		['Y11_Q29e', '5--Strongly-disagree', 'Zdecydowanie się nie zgadzam'],
		['Y11_Q29f', '1--Strongly-agree', 'Zdecydowanie się zgadzam'],
		['Y11_Q29f', '2--Agree', 'Zgadzam się'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Ani się zgadzam, ani się nie zgadzam'],
		['Y11_Q29f', '4--Disagree', 'Nie zgadzam się'],
		['Y11_Q29f', '5--Strongly-disagree', 'Zdecydowanie się nie zgadzam'],
		['Y11_Q29g', '1--Strongly-agree', 'Zdecydowanie się zgadzam'],
		['Y11_Q29g', '2--Agree', 'Zgadzam się'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Ani się zgadzam, ani się nie zgadzam'],
		['Y11_Q29g', '4--Disagree', 'Nie zgadzam się'],
		['Y11_Q29g', '5--Strongly-disagree', 'Zdecydowanie się nie zgadzam'],
		['Y11_Q29h', '1--Strongly-agree', 'Zdecydowanie się zgadzam'],
		['Y11_Q29h', '2--Agree', 'Zgadzam się'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Ani się zgadzam, ani się nie zgadzam'],
		['Y11_Q29h', '4--Disagree', 'Nie zgadzam się'],
		['Y11_Q29h', '5--Strongly-disagree', 'Zdecydowanie się nie zgadzam'],
		['Y11_Q30', 'Mean', 'Średnio'],
		['Y11_Q36b', '1--Every-day', 'Codziennie'],
		['Y11_Q36b', '2--Several-days-a-week', 'Kilka razy w tygodniu'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'Raz lub dwa razy w tygodniu'],
		['Y11_Q36b', '4--Less-often', 'Rzadziej'],
		['Y11_Q36b', '5--Never', 'Nigdy'],
		['Y11_Q36c', '1--Every-day', 'Codziennie'],
		['Y11_Q36c', '2--Several-days-a-week', 'Kilka razy w tygodniu'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'Raz lub dwa razy w tygodniu'],
		['Y11_Q36c', '4--Less-often', 'Rzadziej'],
		['Y11_Q36c', '5--Never', 'Nigdy'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Większy niż wynikałoby to ze sprawiedliwego podziału obowiązków'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Mniej więcej sprawiedliwy'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Mniejszy niż wynikałoby to ze sprawiedliwego podziału obowiązków'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'W pracy i w domu'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Ani w pracy, ani w domu'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Pewne napięcie lub brak napięcia'],
		['Y11_Q40a', 'Mean', 'Średnia'],
		['Y11_Q40b', 'Mean', 'Średnia'],
		['Y11_Q40c', 'Mean', 'Średnia'],
		['Y11_Q40d', 'Mean', 'Średnia'],
		['Y11_Q40e', 'Mean', 'Średnia'],
		['Y11_Q40f', 'Mean', 'Średnia'],
		['Y11_Q40g', 'Mean', 'Średnia'],
		['Y11_Q41', 'Mean', 'Średnia'],
		['Y11_Q42', '1--Very-good', 'Bardzo dobre'],
		['Y11_Q42', '2--Good', 'Dobre'],
		['Y11_Q42', '3--Fair', 'Średnie'],
		['Y11_Q42', '4--Bad', 'Złe'],
		['Y11_Q42', '5--Very-bad', 'Bardzo złe'],
		['Y11_Q46d_WHO5', 'Mean', 'Średnia'],
		['Y11_Q47a', '1--Very-difficult', 'Bardzo utrudniały'],
		['Y11_Q47a', '2--A-little-difficult', 'Trochę utrudniały'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Wcale nie utrudniały'],
		['Y11_Q47b', '1--Very-difficult', 'Bardzo utrudniały'],
		['Y11_Q47b', '2--A-little-difficult', 'Trochę utrudniały'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Wcale nie utrudniały'],
		['Y11_Q47c', '1--Very-difficult', 'Bardzo utrudniały'],
		['Y11_Q47c', '2--A-little-difficult', 'Trochę utrudniały'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Wcale nie utrudniały'],
		['Y11_Q47d', '1--Very-difficult', 'Bardzo utrudniały'],
		['Y11_Q47d', '2--A-little-difficult', 'Trochę utrudniały'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Wcale nie utrudniały'],
		['Y11_Q53a', 'Mean', 'Średnia'],
		['Y11_Q53b', 'Mean', 'Średnia'],
		['Y11_Q53c', 'Mean', 'Średnia'],
		['Y11_Q53d', 'Mean', 'Średnia'],
		['Y11_Q53g', 'Mean', 'Średnia'],
		['Y11_Q58', '1--With-great-difficulty', 'Bardzo trudno'],
		['Y11_Q58', '2--With-difficulty', 'Trudno'],
		['Y11_Q58', '3--With-some-difficulty', 'Dosyć trudno'],
		['Y11_Q58', '4--Fairly-easily', 'Dosyć łatwo'],
		['Y11_Q58', '5--Easily', 'Łatwo'],
		['Y11_Q58', '6--Very-easily', 'Bardzo łatwo'],
		['Y11_Q59a', '1--No', 'Nie'],
		['Y11_Q59a', '2--Yes', 'Tak'],
		['Y11_Q59b', '1--No', 'Nie'],
		['Y11_Q59b', '2--Yes', 'Tak'],
		['Y11_Q59c', '1--No', 'Nie'],
		['Y11_Q59c', '2--Yes', 'Tak'],
		['Y11_Q59d', '1--No', 'Nie'],
		['Y11_Q59d', '2--Yes', 'Tak'],
		['Y11_Q59e', '1--No', 'Nie'],
		['Y11_Q59e', '2--Yes', 'Tak'],
		['Y11_Q59f', '1--No', 'Nie'],
		['Y11_Q59f', '2--Yes', 'Tak'],
		['Y11_Q60a', '1--Yes', 'Tak'],
		['Y11_Q60a', '2--No', 'Nie'],
		['Y11_Q60b', '1--Yes', 'Tak'],
		['Y11_Q60b', '2--No', 'Nie'],
		['Y11_SocExIndex', 'Mean', 'Średnia']
	];
var country_
	 = [
	
		['AT', 'Austria'],
		['BE', 'Belgia'],
		['BG', 'Bułgaria'],
		['CY', 'Cypr'],
		['CZ', 'Republika Czeska'],
		['DE', 'Niemcy'],
		['DK', 'Dania'],
		['EE', 'Estonia'],
		['EL', 'Grecja'],
		['ES', 'Hiszpania'],
		['FI', 'Finlandia'],
		['FR', 'Francja'],
		['HR', 'Chorwacja'],
		['HU', 'Węgry'],
		['IE', 'Irlandia'],
		['IT', 'Włochy'],
		['LT', 'Litwa'],
		['LU', 'Luksemburg'],
		['LV', 'Łotwa'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Holandia'],
		['NO', 'Norwegia'],
		['PL', 'Polska'],
		['PT', 'Portugalia'],
		['RO', 'Rumunia'],
		['SE', 'Szwecja'],
		['SI', 'Słowenia'],
		['SK', 'Słowacja'],
		['TR', 'Turcja'],
		['UK', 'Zjednoczone Królestwo'],
		['EuropeanUnion', 'Unia Europejska']
	];
var question_meta
	 = [
	
		['Y11_Q24', 'Czy uważa Pan(i), że większości ludzi można ufać, czy też, że w kontaktach z ludźmi należy zachować ostrożność?', ''],
		['Y11_Q25a', 'Dostrzegane napięcia między biednymi i bogatymi', ''],
		['Y11_Q25b', 'Dostrzegane napięcia między pracodawcami i pracownikami', ''],
		['Y11_Q25c', 'Dostrzegane napięcia między mężczyznami i kobietami', ''],
		['Y11_Q25d', 'Dostrzegane napięcia między osobami starszymi i młodymi', ''],
		['Y11_Q25e', 'Dostrzegane napięcia między różnymi grupami rasowymi i etnicznymi', ''],
		['Y11_Q25f', 'Dostrzegane napięcia między różnymi grupami religijnymi', ''],
		['Y11_Q28a', 'Zaufanie do parlamentu', ''],
		['Y11_Q28b', 'Zaufanie do systemu prawnego', ''],
		['Y11_Q28c', 'Zaufanie do prasy', ''],
		['Y11_Q28d', 'Zaufanie do policji', ''],
		['Y11_Q28e', 'Zaufanie do rządu', ''],
		['Y11_Q42', 'Ocena własnego stanu zdrowia', ''],
		['Y11_Q46d_WHO5', 'Samopoczucie psychiczne według skali WHO-5', ''],
		['Y11_Q47a', 'Problem z wizytą u lekarza z powodu odległości od ośrodka zdrowia lub szpitala', ''],
		['Y11_Q47b', 'Problem z wizytą u lekarza z powodu odległych terminów wizyty', ''],
		['Y11_Q47c', 'Problem z wizytą u lekarza z powodu oczekiwania na lekarza w dniu wyznaczonej wizyty', ''],
		['Y11_Q47d', 'Problem z wizytą u lekarza z uwagi na koszt wizyty', ''],
		['Y11_Q53a', 'Jak oceniłby(-aby) Pan(i) jakość opieki zdrowotnej w Pana(-i) kraju?', ''],
		['Y11_Q53b', 'Jak oceniłby(-aby) Pan(i) jakość systemu edukacji w Pana(-i) kraju?', ''],
		['Y11_Q53c', 'Jak oceniłby(-aby) Pan(i) jakość transportu publicznego w Pana(-i) kraju?', ''],
		['Y11_Q53d', 'Jak oceniłby(-aby) Pan(i) jakość usług opieki nad dziećmi w Pana(-i) kraju?', ''],
		['Y11_Q53g', 'Jak oceniłby(-aby) Pan(i) jakość państwowego systemu świadczeń emerytalnych/rentowych w Pana(-i) kraju?', ''],
		['Y11_Accommproblems', 'Liczba problemów z zakwaterowaniem', ''],
		['Y11_Q18', 'Posiadanie domu/mieszkania', ''],
		['Y11_Q19a', 'Problemy w miejscu zamieszkania: zbyt mała powierzchnia', ''],
		['Y11_Q19b', 'Problemy w miejscu zamieszkania: butwiejące okna, drzwi lub podłogi', ''],
		['Y11_Q19c', 'Problemy w miejscu zamieszkania: wilgoć lub nacieki na ścianach lub przeciekanie dachu', ''],
		['Y11_Q19d', 'Problemy w miejscu zamieszkania: brak spłukiwanej toalety wewnątrz mieszkania', ''],
		['Y11_Q19e', 'Problemy w miejscu zamieszkania: brak wanny lub prysznica', ''],
		['Y11_Q19f', 'Problemy w miejscu zamieszkania: brak miejsca do spędzania czasu na zewnątrz', ''],
		['Y11_Q20', 'Na ile Pana(-i) zdaniem jest prawdopodobne, że w ciągu najbliższych 6 miesięcy będzie Pan(i) zmuszony(-a) opuścić mieszkanie ze względu na brak pieniędzy na jego utrzymanie?', ''],
		['Y11_Deprindex', 'Wskaźnik deprywacji: Liczba artykułów, na które gospodarstwo nie stać', ''],
		['Y11_Q58', 'Czy Pana(-i) gospodarstwo domowe jest w stanie wiązać koniec z końcem?', ''],
		['Y11_Q59a', 'Czy jest Pan(i) w stanie ogrzać swoje mieszkanie do właściwej temperatury?', ''],
		['Y11_Q59b', 'Czy stać Pana (Panią) na tygodniowy urlop poza domem raz w roku?', ''],
		['Y11_Q59c', 'Czy stać Pana (Panią) na wymianę zużytych mebli?', ''],
		['Y11_Q59d', 'Czy stać Pana (Panią) na posiłek zawierający mięso, drób lub ryby co drugi dzień (jeżeli miałby(-aby) Pan(i) na to ochotę)?', ''],
		['Y11_Q59e', 'Czy stać Pana (Panią) na nowe, a nie używane ubrania?', ''],
		['Y11_Q59f', 'Czy stać Pana (Panią), aby przynajmniej raz w miesiącu zaprosić znajomych lub rodzinę na coś do picia lub do jedzenia?', ''],
		['Y11_Q60a', 'Czy w ciągu ostatnich 12 miesięcy Pana(-i) gospodarstwo domowe miało trudności z terminowym opłacaniem czynszu lub rat za mieszkanie?', ''],
		['Y11_Q60b', 'Czy w ciągu ostatnich 12 miesięcy Pana(-i) gospodarstwo domowe miało trudności z terminowym opłacaniem rachunków za świadczenia?', ''],
		['Y11_Q29a', 'Optymistycznie patrzę w przyszłość', ''],
		['Y11_Q30', 'Na ile jest Pan(i) zadowolony(-a) ze swojego obecnego życia?', ''],
		['Y11_Q40a', 'Zadowolenie z wykształcenia', ''],
		['Y11_Q40b', 'Zadowolenie z obecnej pracy', ''],
		['Y11_Q40c', 'Zadowolenie z obecnego poziomu życia', ''],
		['Y11_Q40d', 'Zadowolenie z warunków mieszkaniowych', ''],
		['Y11_Q40e', 'Zadowolenie z życia rodzinnego', ''],
		['Y11_Q40f', 'Zadowolenie ze swojego stanu zdrowia', ''],
		['Y11_Q40g', 'Zadowolenie z życia towarzyskiego', ''],
		['Y11_Q41', 'Ogólnie rzecz biorąc, na ile czuje się Pan(i) szczęśliwy(-a)?', ''],
		['Y11_Q23a', 'Udział w spotkaniu związków zawodowych, partii politycznej lub ruchu społecznego w ciągu ostatnich 12 miesięcy', ''],
		['Y11_Q23d', 'Kontakt z politykiem lub urzędnikiem państwowym (oprócz rutynowych kontaktów związanych z załatwianiem spraw urzędowych)', ''],
		['Y11_Q29e', 'Czuję się wyobcowany(-a) ze społeczeństwa ', ''],
		['Y11_Q29f', 'Obecnie życie stało się tak skomplikowane, że czuję się zagubiony(-a)', ''],
		['Y11_Q29g', 'Nie czuję, żeby ludzie cenili to, co robię', ''],
		['Y11_Q29h', 'Niektórzy ludzie patrzą na mnie z góry ze względu na moją sytuację zawodową lub dochód', ''],
		['Y11_SocExIndex', 'Wskaźnik wykluczenia społecznego', ''],
		['Y11_Q12a', 'Przyszedłem (Przyszłam) z pracy zbyt zmęczony(-a), aby wykonać prace domowe', ''],
		['Y11_Q12b', 'Z powodu ilości czasu spędzonego w pracy było mi trudno wypełnić obowiązki rodzinne', ''],
		['Y11_Q12c', 'Miałem(-am) trudności ze skoncentrowaniem się w pracy z powodu moich obowiązków rodzinnych', ''],
		['Y11_Q15', 'Na ile Pana(-i) zdaniem jest prawdopodobne, że w ciągu najbliższych 6 miesięcy straci Pan(i) pracę?', ''],
		['Y11_Q36b', 'Jak często spędza Pan(i) czas na gotowaniu i pracach domowych?', ''],
		['Y11_Q36c', 'Jak często spędza Pan(i) czas nad opiece nad starszymi/niepełnosprawnymi członkami rodziny?', ''],
		['Y11_Q38', 'Co Pan(i) sądzi o swoim udziale w obowiązkach domowych?', ''],
		['Y11_Q39d_stress', 'Stres związany z zachowaniem równowagi między życiem zawodowym a prywatnym', '']
	];
