//Auto Generated file
var subset_
	 = [
	
		['Y11_Agecategory', 'Idade'],
		['Y11_Incomequartiles_percapita', 'Rendimento'],
		['Y11_HH2a', 'Sexo']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Todas as idades'],
		['Y11_Agecategory', '1--18-24y', '18 a 24 anos'],
		['Y11_Agecategory', '2--25-34y', '25 a 34 anos'],
		['Y11_Agecategory', '3--35-49y', '35 a 49 anos'],
		['Y11_Agecategory', '4--50-64y', '50 a 64 anos'],
		['Y11_Agecategory', '5---64y', '> 64 anos'],
		['Y11_HH2a', 'All', 'Ambos os sexos'],
		['Y11_HH2a', '1--Female', 'Feminino'],
		['Y11_HH2a', '2--Male', 'Masculino'],
		['Y11_Incomequartiles_percapita', 'All', 'Todos os níveis de rendimento'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Mais baixo'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'Segundo'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'Terceiro'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Mais elevado']
	];
var topic_
	 = [
	
		['', 'Todos(as) os(as) (67)'],
		['Bem-estar subjetivo', 'Bem-estar subjetivo (10)'],
		['Emprego e conciliação entre vida familiar e vida profissional', 'Emprego e conciliação entre vida familiar e vida profissional (8)'],
		['Exclusão social e participação comunitária', 'Exclusão social e participação comunitária (7)'],
		['Habitação e ambiente local', 'Habitação e ambiente local (9)'],
		['Nível de vida e privação', 'Nível de vida e privação (10)'],
		['Qualidade da sociedade', 'Qualidade da sociedade (12)'],
		['Saúde e serviços públicos', 'Saúde e serviços públicos (11)']
	];
var topic_question
	 = [
	
		['Bem-estar subjetivo', 'Y11_Q29a', 'Estou otimista em relação ao futuro'],
		['Bem-estar subjetivo', 'Y11_Q30', 'Em que medida diria que está satisfeito com a sua vida hoje em dia?'],
		['Bem-estar subjetivo', 'Y11_Q40a', 'Satisfação com a educação'],
		['Bem-estar subjetivo', 'Y11_Q40b', 'Satisfação com o emprego atual'],
		['Bem-estar subjetivo', 'Y11_Q40c', 'Satisfação com o nível de vida atual'],
		['Bem-estar subjetivo', 'Y11_Q40d', 'Satisfação com a casa'],
		['Bem-estar subjetivo', 'Y11_Q40e', 'Satisfação com a vida familiar'],
		['Bem-estar subjetivo', 'Y11_Q40f', 'Satisfação com a saúde'],
		['Bem-estar subjetivo', 'Y11_Q40g', 'Satisfação com a vida social'],
		['Bem-estar subjetivo', 'Y11_Q41', 'Tendo tudo em consideração, em que medida diria que se sente feliz?'],
		['Emprego e conciliação entre vida familiar e vida profissional', 'Y11_Q12a', 'Cheguei do emprego demasiado cansado(a) para fazer qualquer tarefa doméstica'],
		['Emprego e conciliação entre vida familiar e vida profissional', 'Y11_Q12b', 'Tive dificuldades em cumprir as minhas responsabilidades familiares devido ao tempo que passo no emprego '],
		['Emprego e conciliação entre vida familiar e vida profissional', 'Y11_Q12c', 'Tive dificuldades em concentrar-me no trabalho devido às minhas responsabilidades familiares'],
		['Emprego e conciliação entre vida familiar e vida profissional', 'Y11_Q15', 'Qual é a probabilidade de vir a perder o seu emprego nos próximos 6 meses?'],
		['Emprego e conciliação entre vida familiar e vida profissional', 'Y11_Q36b', 'Em média, com que frequência cozinha e/ou faz trabalhos domésticos?'],
		['Emprego e conciliação entre vida familiar e vida profissional', 'Y11_Q36c', 'Em média, com que frequência cuida de familiares idosos ou com alguma deficiência?'],
		['Emprego e conciliação entre vida familiar e vida profissional', 'Y11_Q38', 'Atitude perante a partilha das tarefas domésticas'],
		['Emprego e conciliação entre vida familiar e vida profissional', 'Y11_Q39d_stress', 'Stresse'],
		['Exclusão social e participação comunitária', 'Y11_Q23a', 'Nos últimos 12 meses, assistiu a uma reunião de um sindicato, partido político ou a uma iniciativa de um grupo partidário'],
		['Exclusão social e participação comunitária', 'Y11_Q23d', 'Contactou um político ou um(a) funcionário(a) público(a) (excluindo os contactos de rotina provenientes da utilização de serviços públicos)'],
		['Exclusão social e participação comunitária', 'Y11_Q29e', 'Sinto-me marginalizado(a) pela sociedade'],
		['Exclusão social e participação comunitária', 'Y11_Q29f', 'A vida tornou-se tão complicada, hoje em dia, que quase não encontro uma saída'],
		['Exclusão social e participação comunitária', 'Y11_Q29g', 'Sinto que o valor do que faço não é reconhecido por outras pessoas'],
		['Exclusão social e participação comunitária', 'Y11_Q29h', 'Algumas pessoas desprezam-me por causa da minha situação ou do meu rendimento'],
		['Exclusão social e participação comunitária', 'Y11_SocExIndex', 'Índice de exclusão social'],
		['Habitação e ambiente local', 'Y11_Accommproblems', 'Número de problemas com o alojamento'],
		['Habitação e ambiente local', 'Y11_Q18', 'Habitação própria'],
		['Habitação e ambiente local', 'Y11_Q19a', 'Problemas com a sua casa: falta de espaço'],
		['Habitação e ambiente local', 'Y11_Q19b', 'Problemas com a sua casa: janelas, portas ou chão podres'],
		['Habitação e ambiente local', 'Y11_Q19c', 'Problemas com a sua casa: humidade ou fugas nas paredes ou nos tetos'],
		['Habitação e ambiente local', 'Y11_Q19d', 'Problemas com a sua casa: ausência de sanita com autoclismo dentro de casa'],
		['Habitação e ambiente local', 'Y11_Q19e', 'Problemas com a sua casa: ausência de banheira ou de chuveiro'],
		['Habitação e ambiente local', 'Y11_Q19f', 'Problemas com a sua casa: falta de lugar para estar no exterior'],
		['Habitação e ambiente local', 'Y11_Q20', 'Qual a probabilidade de nos próximos 6 meses ter que deixar a sua casa porque não a pode pagar?'],
		['Nível de vida e privação', 'Y11_Deprindex', 'Índice de privação: Número de artigos que um agregado familiar não pode permitir-se financiar'],
		['Nível de vida e privação', 'Y11_Q58', 'O seu agregado consegue sustentar-se?'],
		['Nível de vida e privação', 'Y11_Q59a', 'A sua situação financeira permite-lhe manter a sua casa aquecida?'],
		['Nível de vida e privação', 'Y11_Q59b', 'A sua situação financeira permite-lhe tirar uma semana de férias por ano, longe de sua casa?'],
		['Nível de vida e privação', 'Y11_Q59c', 'A sua situação financeira permite-lhe substituir alguma mobília que já se encontra velha?'],
		['Nível de vida e privação', 'Y11_Q59d', 'A sua situação financeira permite-lhe fazer uma refeição com carne, frango ou peixe de dois em dois dias, se desejar?'],
		['Nível de vida e privação', 'Y11_Q59e', 'A sua situação financeira permite-lhe comprar roupa nova, em vez de em segunda mão?'],
		['Nível de vida e privação', 'Y11_Q59f', 'A sua situação financeira permite-lhe receber amigos ou familiares em casa para tomar uma bebida ou para comer, pelo menos uma vez por mês?'],
		['Nível de vida e privação', 'Y11_Q60a', 'Alguma vez, durante os últimos 12 meses, o seu agregado se atrasou nos pagamentos da renda ou da prestação da casa?'],
		['Nível de vida e privação', 'Y11_Q60b', 'Alguma vez, durante os últimos 12 meses, o seu agregado se atrasou nos pagamentos dos serviços públicos, como eletricidade, água, gás?'],
		['Qualidade da sociedade', 'Y11_Q24', 'De uma maneira geral, diria que a maioria das pessoas é de confiança, ou que todo o cuidado é pouco no relacionamento com as pessoas?'],
		['Qualidade da sociedade', 'Y11_Q25a', 'Tensão sentida entre os pobres e os ricos'],
		['Qualidade da sociedade', 'Y11_Q25b', 'Tensão sentida entre os dirigentes de empresas e os trabalhadores'],
		['Qualidade da sociedade', 'Y11_Q25c', 'Tensão sentida entre os homens e as mulheres'],
		['Qualidade da sociedade', 'Y11_Q25d', 'Tensão sentida entre as pessoas idosas e os jovens'],
		['Qualidade da sociedade', 'Y11_Q25e', 'Tensão sentida entre os diferentes grupos raciais e étnicos'],
		['Qualidade da sociedade', 'Y11_Q25f', 'Tensão sentida entre os diferentes grupos religiosos'],
		['Qualidade da sociedade', 'Y11_Q28a', 'Confiança no Parlamento'],
		['Qualidade da sociedade', 'Y11_Q28b', 'Confiança no sistema jurídico'],
		['Qualidade da sociedade', 'Y11_Q28c', 'Confiança na imprensa'],
		['Qualidade da sociedade', 'Y11_Q28d', 'Confiança na polícia'],
		['Qualidade da sociedade', 'Y11_Q28e', 'Confiança no governo'],
		['Saúde e serviços públicos', 'Y11_Q42', 'Perceção do estado de saúde'],
		['Saúde e serviços públicos', 'Y11_Q46d_WHO5', 'Escala de bem-estar mental OMS-5'],
		['Saúde e serviços públicos', 'Y11_Q47a', 'Dificuldade em recorrer a um médico devido à distância'],
		['Saúde e serviços públicos', 'Y11_Q47b', 'Dificuldade em recorrer a um médico devido a atraso na marcação de consulta'],
		['Saúde e serviços públicos', 'Y11_Q47c', 'Dificuldade em recorrer a um médico devido ao tempo de espera no dia da consulta'],
		['Saúde e serviços públicos', 'Y11_Q47d', 'Dificuldade em recorrer a um médico devido ao custo da consulta'],
		['Saúde e serviços públicos', 'Y11_Q53a', 'Como avalia a qualidade dos serviços de saúde no seu país?'],
		['Saúde e serviços públicos', 'Y11_Q53b', 'Como avalia a qualidade do sistema educativo no seu país?'],
		['Saúde e serviços públicos', 'Y11_Q53c', 'Como avalia a qualidade dos transportes públicos no seu país?'],
		['Saúde e serviços públicos', 'Y11_Q53d', 'Como avalia a qualidade dos serviços de cuidados infantis no seu país?'],
		['Saúde e serviços públicos', 'Y11_Q53g', 'Como avalia a qualidade do sistema de pensões no seu país?']
	];
var question_
	 = [
	
		['Y11_Q29a', 'Estou otimista em relação ao futuro'],
		['Y11_Q30', 'Em que medida diria que está satisfeito com a sua vida hoje em dia?'],
		['Y11_Q40a', 'Satisfação com a educação'],
		['Y11_Q40b', 'Satisfação com o emprego atual'],
		['Y11_Q40c', 'Satisfação com o nível de vida atual'],
		['Y11_Q40d', 'Satisfação com a casa'],
		['Y11_Q40e', 'Satisfação com a vida familiar'],
		['Y11_Q40f', 'Satisfação com a saúde'],
		['Y11_Q40g', 'Satisfação com a vida social'],
		['Y11_Q41', 'Tendo tudo em consideração, em que medida diria que se sente feliz?'],
		['Y11_Q12a', 'Cheguei do emprego demasiado cansado(a) para fazer qualquer tarefa doméstica'],
		['Y11_Q12b', 'Tive dificuldades em cumprir as minhas responsabilidades familiares devido ao tempo que passo no emprego '],
		['Y11_Q12c', 'Tive dificuldades em concentrar-me no trabalho devido às minhas responsabilidades familiares'],
		['Y11_Q15', 'Qual é a probabilidade de vir a perder o seu emprego nos próximos 6 meses?'],
		['Y11_Q36b', 'Em média, com que frequência cozinha e/ou faz trabalhos domésticos?'],
		['Y11_Q36c', 'Em média, com que frequência cuida de familiares idosos ou com alguma deficiência?'],
		['Y11_Q38', 'Atitude perante a partilha das tarefas domésticas'],
		['Y11_Q39d_stress', 'Stresse'],
		['Y11_Q23a', 'Nos últimos 12 meses, assistiu a uma reunião de um sindicato, partido político ou a uma iniciativa de um grupo partidário'],
		['Y11_Q23d', 'Contactou um político ou um(a) funcionário(a) público(a) (excluindo os contactos de rotina provenientes da utilização de serviços públicos)'],
		['Y11_Q29e', 'Sinto-me marginalizado(a) pela sociedade'],
		['Y11_Q29f', 'A vida tornou-se tão complicada, hoje em dia, que quase não encontro uma saída'],
		['Y11_Q29g', 'Sinto que o valor do que faço não é reconhecido por outras pessoas'],
		['Y11_Q29h', 'Algumas pessoas desprezam-me por causa da minha situação ou do meu rendimento'],
		['Y11_SocExIndex', 'Índice de exclusão social'],
		['Y11_Accommproblems', 'Número de problemas com o alojamento'],
		['Y11_Q18', 'Habitação própria'],
		['Y11_Q19a', 'Problemas com a sua casa: falta de espaço'],
		['Y11_Q19b', 'Problemas com a sua casa: janelas, portas ou chão podres'],
		['Y11_Q19c', 'Problemas com a sua casa: humidade ou fugas nas paredes ou nos tetos'],
		['Y11_Q19d', 'Problemas com a sua casa: ausência de sanita com autoclismo dentro de casa'],
		['Y11_Q19e', 'Problemas com a sua casa: ausência de banheira ou de chuveiro'],
		['Y11_Q19f', 'Problemas com a sua casa: falta de lugar para estar no exterior'],
		['Y11_Q20', 'Qual a probabilidade de nos próximos 6 meses ter que deixar a sua casa porque não a pode pagar?'],
		['Y11_Deprindex', 'Índice de privação: Número de artigos que um agregado familiar não pode permitir-se financiar'],
		['Y11_Q58', 'O seu agregado consegue sustentar-se?'],
		['Y11_Q59a', 'A sua situação financeira permite-lhe manter a sua casa aquecida?'],
		['Y11_Q59b', 'A sua situação financeira permite-lhe tirar uma semana de férias por ano, longe de sua casa?'],
		['Y11_Q59c', 'A sua situação financeira permite-lhe substituir alguma mobília que já se encontra velha?'],
		['Y11_Q59d', 'A sua situação financeira permite-lhe fazer uma refeição com carne, frango ou peixe de dois em dois dias, se desejar?'],
		['Y11_Q59e', 'A sua situação financeira permite-lhe comprar roupa nova, em vez de em segunda mão?'],
		['Y11_Q59f', 'A sua situação financeira permite-lhe receber amigos ou familiares em casa para tomar uma bebida ou para comer, pelo menos uma vez por mês?'],
		['Y11_Q60a', 'Alguma vez, durante os últimos 12 meses, o seu agregado se atrasou nos pagamentos da renda ou da prestação da casa?'],
		['Y11_Q60b', 'Alguma vez, durante os últimos 12 meses, o seu agregado se atrasou nos pagamentos dos serviços públicos, como eletricidade, água, gás?'],
		['Y11_Q24', 'De uma maneira geral, diria que a maioria das pessoas é de confiança, ou que todo o cuidado é pouco no relacionamento com as pessoas?'],
		['Y11_Q25a', 'Tensão sentida entre os pobres e os ricos'],
		['Y11_Q25b', 'Tensão sentida entre os dirigentes de empresas e os trabalhadores'],
		['Y11_Q25c', 'Tensão sentida entre os homens e as mulheres'],
		['Y11_Q25d', 'Tensão sentida entre as pessoas idosas e os jovens'],
		['Y11_Q25e', 'Tensão sentida entre os diferentes grupos raciais e étnicos'],
		['Y11_Q25f', 'Tensão sentida entre os diferentes grupos religiosos'],
		['Y11_Q28a', 'Confiança no Parlamento'],
		['Y11_Q28b', 'Confiança no sistema jurídico'],
		['Y11_Q28c', 'Confiança na imprensa'],
		['Y11_Q28d', 'Confiança na polícia'],
		['Y11_Q28e', 'Confiança no governo'],
		['Y11_Q42', 'Perceção do estado de saúde'],
		['Y11_Q46d_WHO5', 'Escala de bem-estar mental OMS-5'],
		['Y11_Q47a', 'Dificuldade em recorrer a um médico devido à distância'],
		['Y11_Q47b', 'Dificuldade em recorrer a um médico devido a atraso na marcação de consulta'],
		['Y11_Q47c', 'Dificuldade em recorrer a um médico devido ao tempo de espera no dia da consulta'],
		['Y11_Q47d', 'Dificuldade em recorrer a um médico devido ao custo da consulta'],
		['Y11_Q53a', 'Como avalia a qualidade dos serviços de saúde no seu país?'],
		['Y11_Q53b', 'Como avalia a qualidade do sistema educativo no seu país?'],
		['Y11_Q53c', 'Como avalia a qualidade dos transportes públicos no seu país?'],
		['Y11_Q53d', 'Como avalia a qualidade dos serviços de cuidados infantis no seu país?'],
		['Y11_Q53g', 'Como avalia a qualidade do sistema de pensões no seu país?']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Médio'],
		['Y11_Deprindex', 'Mean', 'Médio'],
		['Y11_Q12a', '1--Several-times-a-week', 'Várias vezes por semana'],
		['Y11_Q12a', '2--Several-times-a-month', 'Várias vezes por mês'],
		['Y11_Q12a', '3--Several-times-a-year', 'Várias vezes por ano'],
		['Y11_Q12a', '4--Less-often-rarely', 'Pouca frequência/raramente'],
		['Y11_Q12a', '5--Never', 'Nunca'],
		['Y11_Q12b', '1--Several-times-a-week', 'Várias vezes por semana'],
		['Y11_Q12b', '2--Several-times-a-month', 'Várias vezes por mês'],
		['Y11_Q12b', '3--Several-times-a-year', 'Várias vezes por ano'],
		['Y11_Q12b', '4--Less-often-rarely', 'Pouca frequência/raramente'],
		['Y11_Q12b', '5--Never', 'Nunca'],
		['Y11_Q12c', '1--Several-times-a-week', 'Várias vezes por semana'],
		['Y11_Q12c', '2--Several-times-a-month', 'Várias vezes por mês'],
		['Y11_Q12c', '3--Several-times-a-year', 'Várias vezes por ano'],
		['Y11_Q12c', '4--Less-often-rarely', 'Pouca frequência/raramente'],
		['Y11_Q12c', '5--Never', 'Nunca'],
		['Y11_Q15', '1--Very-likely', 'Muito provável'],
		['Y11_Q15', '2--Quite-likely', 'Algo provável'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Nem provável, nem improvável'],
		['Y11_Q15', '4--Quite-unlikely', 'Algo improvável'],
		['Y11_Q15', '5--Very-unlikely', 'Muito improvável'],
		['Y11_Q18', '1--Own-without-mortgage', 'Proprietário sem empréstimo bancário'],
		['Y11_Q18', '2--Own-with-mortgage', 'Proprietário com empréstimo bancário'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Inquilino, paga a renda de uma habitação social/ voluntária/ camarária'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Inquilino, paga a renda a um senhorio privado'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Habitação gratuita, sem pagar renda'],
		['Y11_Q18', '6--Other', 'Outra'],
		['Y11_Q19a', '1--Yes', 'Sim'],
		['Y11_Q19a', '2--No', 'Não'],
		['Y11_Q19b', '1--Yes', 'Sim'],
		['Y11_Q19b', '2--No', 'Não'],
		['Y11_Q19c', '1--Yes', 'Sim'],
		['Y11_Q19c', '2--No', 'Não'],
		['Y11_Q19d', '1--Yes', 'Sim'],
		['Y11_Q19d', '2--No', 'Não'],
		['Y11_Q19e', '1--Yes', 'Sim'],
		['Y11_Q19e', '2--No', 'Não'],
		['Y11_Q19f', '1--Yes', 'Sim'],
		['Y11_Q19f', '2--No', 'Não'],
		['Y11_Q20', '1--Very-likely', 'Muito provável'],
		['Y11_Q20', '2--Quite-likely', 'Algo provável'],
		['Y11_Q20', '3--Quite-unlikely', 'Algo improvável'],
		['Y11_Q20', '4--Very-unlikely', 'Muito improvável'],
		['Y11_Q23a', '1--Yes', 'Sim'],
		['Y11_Q23a', '2--No', 'Não'],
		['Y11_Q23d', '1--Yes', 'Sim'],
		['Y11_Q23d', '2--No', 'Não'],
		['Y11_Q24', 'Mean', 'Média'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Muita tensão'],
		['Y11_Q25a', '2--Some-tension', 'Alguma tensão'],
		['Y11_Q25a', '3--No-tension', 'Nenhuma tensão'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Muita tensão'],
		['Y11_Q25b', '2--Some-tension', 'Alguma tensão'],
		['Y11_Q25b', '3--No-tension', 'Nenhuma tensão'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Muita tensão'],
		['Y11_Q25c', '2--Some-tension', 'Alguma tensão'],
		['Y11_Q25c', '3--No-tension', 'Nenhuma tensão'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Muita tensão'],
		['Y11_Q25d', '2--Some-tension', 'Alguma tensão'],
		['Y11_Q25d', '3--No-tension', 'Nenhuma tensão'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Muita tensão'],
		['Y11_Q25e', '2--Some-tension', 'Alguma tensão'],
		['Y11_Q25e', '3--No-tension', 'Nenhuma tensão'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Muita tensão'],
		['Y11_Q25f', '2--Some-tension', 'Alguma tensão'],
		['Y11_Q25f', '3--No-tension', 'Nenhuma tensão'],
		['Y11_Q28a', 'Mean', 'Média'],
		['Y11_Q28b', 'Mean', 'Média'],
		['Y11_Q28c', 'Mean', 'Média'],
		['Y11_Q28d', 'Mean', 'Média'],
		['Y11_Q28e', 'Mean', 'Média'],
		['Y11_Q29a', '1--Strongly-agree', 'Concorda totalmente'],
		['Y11_Q29a', '2--Agree', 'Concorda'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Nem concorda nem discorda'],
		['Y11_Q29a', '4--Disagree', 'Discorda'],
		['Y11_Q29a', '5--Strongly-disagree', 'Discorda totalmente'],
		['Y11_Q29e', '1--Strongly-agree', 'Concorda totalmente'],
		['Y11_Q29e', '2--Agree', 'Concorda'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Nem concorda nem discorda'],
		['Y11_Q29e', '4--Disagree', 'Discorda'],
		['Y11_Q29e', '5--Strongly-disagree', 'Discorda totalmente'],
		['Y11_Q29f', '1--Strongly-agree', 'Concorda totalmente'],
		['Y11_Q29f', '2--Agree', 'Concorda'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Nem concorda nem discorda'],
		['Y11_Q29f', '4--Disagree', 'Discorda'],
		['Y11_Q29f', '5--Strongly-disagree', 'Discorda totalmente'],
		['Y11_Q29g', '1--Strongly-agree', 'Concorda totalmente'],
		['Y11_Q29g', '2--Agree', 'Concorda'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Nem concorda nem discorda'],
		['Y11_Q29g', '4--Disagree', 'Discorda'],
		['Y11_Q29g', '5--Strongly-disagree', 'Discorda totalmente'],
		['Y11_Q29h', '1--Strongly-agree', 'Concorda totalmente'],
		['Y11_Q29h', '2--Agree', 'Concorda'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Nem concorda nem discorda'],
		['Y11_Q29h', '4--Disagree', 'Discorda'],
		['Y11_Q29h', '5--Strongly-disagree', 'Discorda totalmente'],
		['Y11_Q30', 'Mean', 'Média'],
		['Y11_Q36b', '1--Every-day', 'Todos os dias'],
		['Y11_Q36b', '2--Several-days-a-week', 'Várias vezes por semana'],
		['Y11_Q36b', '3--Once-or-twice-a-week', '1 ou 2 vezes por semana'],
		['Y11_Q36b', '4--Less-often', 'Menos frequentemente'],
		['Y11_Q36b', '5--Never', 'Nunca'],
		['Y11_Q36c', '1--Every-day', 'Todos os dias'],
		['Y11_Q36c', '2--Several-days-a-week', 'Várias vezes por semana'],
		['Y11_Q36c', '3--Once-or-twice-a-week', '1 ou 2 vezes por semana'],
		['Y11_Q36c', '4--Less-often', 'Menos frequentemente'],
		['Y11_Q36c', '5--Never', 'Nunca'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Mais do que é justo'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'O que é justo'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Menos do que é justo'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'No trabalho e em casa'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'No trabalho ou em casa'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Nenhum ou quase nenhum stresse'],
		['Y11_Q40a', 'Mean', 'Média'],
		['Y11_Q40b', 'Mean', 'Média'],
		['Y11_Q40c', 'Mean', 'Média'],
		['Y11_Q40d', 'Mean', 'Média'],
		['Y11_Q40e', 'Mean', 'Média'],
		['Y11_Q40f', 'Mean', 'Média'],
		['Y11_Q40g', 'Mean', 'Média'],
		['Y11_Q41', 'Mean', 'Média'],
		['Y11_Q42', '1--Very-good', 'Muito boa'],
		['Y11_Q42', '2--Good', 'Boa'],
		['Y11_Q42', '3--Fair', 'Média'],
		['Y11_Q42', '4--Bad', 'Má'],
		['Y11_Q42', '5--Very-bad', 'Muito má'],
		['Y11_Q46d_WHO5', 'Mean', 'Média'],
		['Y11_Q47a', '1--Very-difficult', 'Muito difícil'],
		['Y11_Q47a', '2--A-little-difficult', 'Um pouco difícil'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Nada difícil'],
		['Y11_Q47b', '1--Very-difficult', 'Muito difícil'],
		['Y11_Q47b', '2--A-little-difficult', 'Um pouco difícil'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Nada difícil'],
		['Y11_Q47c', '1--Very-difficult', 'Muito difícil'],
		['Y11_Q47c', '2--A-little-difficult', 'Um pouco difícil'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Nada difícil'],
		['Y11_Q47d', '1--Very-difficult', 'Muito difícil'],
		['Y11_Q47d', '2--A-little-difficult', 'Um pouco difícil'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Nada difícil'],
		['Y11_Q53a', 'Mean', 'Média'],
		['Y11_Q53b', 'Mean', 'Média'],
		['Y11_Q53c', 'Mean', 'Média'],
		['Y11_Q53d', 'Mean', 'Média'],
		['Y11_Q53g', 'Mean', 'Média'],
		['Y11_Q58', '1--With-great-difficulty', 'Com muita dificuldade'],
		['Y11_Q58', '2--With-difficulty', 'Com dificuldade'],
		['Y11_Q58', '3--With-some-difficulty', 'Com alguma dificuldade'],
		['Y11_Q58', '4--Fairly-easily', 'Com alguma facilidade'],
		['Y11_Q58', '5--Easily', 'Facilmente'],
		['Y11_Q58', '6--Very-easily', 'Com muita facilidade'],
		['Y11_Q59a', '1--No', 'Não'],
		['Y11_Q59a', '2--Yes', 'Sim'],
		['Y11_Q59b', '1--No', 'Não'],
		['Y11_Q59b', '2--Yes', 'Sim'],
		['Y11_Q59c', '1--No', 'Não'],
		['Y11_Q59c', '2--Yes', 'Sim'],
		['Y11_Q59d', '1--No', 'Não'],
		['Y11_Q59d', '2--Yes', 'Sim'],
		['Y11_Q59e', '1--No', 'Não'],
		['Y11_Q59e', '2--Yes', 'Sim'],
		['Y11_Q59f', '1--No', 'Não'],
		['Y11_Q59f', '2--Yes', 'Sim'],
		['Y11_Q60a', '1--Yes', 'Sim'],
		['Y11_Q60a', '2--No', 'Não'],
		['Y11_Q60b', '1--Yes', 'Sim'],
		['Y11_Q60b', '2--No', 'Não'],
		['Y11_SocExIndex', 'Mean', 'Médio']
	];
var country_
	 = [
	
		['AT', 'Áustria'],
		['BE', 'Bélgica'],
		['BG', 'Bulgária'],
		['CY', 'Chipre'],
		['CZ', 'República Checa'],
		['DE', 'Alemanha'],
		['DK', 'Dinamarca'],
		['EE', 'Estónia'],
		['EL', 'Grécia'],
		['ES', 'Espanha'],
		['FI', 'Finlândia'],
		['FR', 'França'],
		['HR', 'Croácia'],
		['HU', 'Hungria'],
		['IE', 'Irlanda'],
		['IT', 'Itália'],
		['LT', 'Lituânia'],
		['LU', 'Luxemburgo'],
		['LV', 'Letónia'],
		['MK', 'ARJM'],
		['MT', 'Malta'],
		['NL', 'Países Baixos'],
		['NO', 'Noruega'],
		['PL', 'Polónia'],
		['PT', 'Portugal'],
		['RO', 'Roménia'],
		['SE', 'Suécia'],
		['SI', 'Eslovénia'],
		['SK', 'Eslováquia'],
		['TR', 'Turquia'],
		['UK', 'Reino Unido'],
		['EuropeanUnion', 'União Europeia']
	];
var question_meta
	 = [
	
		['Y11_Q29a', 'Estou otimista em relação ao futuro', ''],
		['Y11_Q30', 'Em que medida diria que está satisfeito com a sua vida hoje em dia?', ''],
		['Y11_Q40a', 'Satisfação com a educação', ''],
		['Y11_Q40b', 'Satisfação com o emprego atual', ''],
		['Y11_Q40c', 'Satisfação com o nível de vida atual', ''],
		['Y11_Q40d', 'Satisfação com a casa', ''],
		['Y11_Q40e', 'Satisfação com a vida familiar', ''],
		['Y11_Q40f', 'Satisfação com a saúde', ''],
		['Y11_Q40g', 'Satisfação com a vida social', ''],
		['Y11_Q41', 'Tendo tudo em consideração, em que medida diria que se sente feliz?', ''],
		['Y11_Q12a', 'Cheguei do emprego demasiado cansado(a) para fazer qualquer tarefa doméstica', ''],
		['Y11_Q12b', 'Tive dificuldades em cumprir as minhas responsabilidades familiares devido ao tempo que passo no emprego ', ''],
		['Y11_Q12c', 'Tive dificuldades em concentrar-me no trabalho devido às minhas responsabilidades familiares', ''],
		['Y11_Q15', 'Qual é a probabilidade de vir a perder o seu emprego nos próximos 6 meses?', ''],
		['Y11_Q36b', 'Em média, com que frequência cozinha e/ou faz trabalhos domésticos?', ''],
		['Y11_Q36c', 'Em média, com que frequência cuida de familiares idosos ou com alguma deficiência?', ''],
		['Y11_Q38', 'O que pensa da parte das tarefas domésticas que lhe cabe?', ''],
		['Y11_Q39d_stress', 'Stresse causado pela necessidade de conciliar vida profissional e pessoal', ''],
		['Y11_Q23a', 'Nos últimos 12 meses, assistiu a uma reunião de um sindicato, partido político ou a uma iniciativa de um grupo partidário', ''],
		['Y11_Q23d', 'Contactou um político ou um(a) funcionário(a) público(a) (excluindo os contactos de rotina provenientes da utilização de serviços públicos)', ''],
		['Y11_Q29e', 'Sinto-me marginalizado(a) pela sociedade', ''],
		['Y11_Q29f', 'A vida tornou-se tão complicada hoje em dia, que quase não encontro uma saída', ''],
		['Y11_Q29g', 'Sinto que o valor do que faço não é reconhecido por outras pessoas', ''],
		['Y11_Q29h', 'Algumas pessoas desprezam-me por causa da minha situação ou do meu rendimento', ''],
		['Y11_SocExIndex', 'Índice de exclusão social', ''],
		['Y11_Accommproblems', 'Número de problemas com o alojamento', ''],
		['Y11_Q18', 'Habitação própria', ''],
		['Y11_Q19a', 'Problemas com a sua casa: falta de espaço', ''],
		['Y11_Q19b', 'Problemas com a sua casa: janelas, portas ou chão podres', ''],
		['Y11_Q19c', 'Problemas com a sua casa: humidade ou fugas nas paredes ou nos tetos', ''],
		['Y11_Q19d', 'Problemas com a sua casa: ausência de sanita com autoclismo dentro de casa', ''],
		['Y11_Q19e', 'Problemas com a sua casa: ausência de banheira ou de chuveiro', ''],
		['Y11_Q19f', 'Problemas com a sua casa: falta de lugar para estar no exterior', ''],
		['Y11_Q20', 'Qual a probabilidade de nos próximos 6 meses ter que deixar a sua casa porque deixa de a poder pagar?', ''],
		['Y11_Deprindex', 'Índice de privação: Número de artigos que um agregado familiar não pode permitir-se financiar', ''],
		['Y11_Q58', 'O seu agregado consegue sustentar-se?', ''],
		['Y11_Q59a', 'A sua situação financeira permite-lhe manter a sua casa aquecida?', ''],
		['Y11_Q59b', 'A sua situação financeira permite-lhe tirar uma semana de férias por ano, longe de sua casa?', ''],
		['Y11_Q59c', 'A sua situação financeira permite-lhe substituir alguma mobília que já se encontra velha?', ''],
		['Y11_Q59d', 'A situação financeira do seu agregado permite-lhe fazer uma refeição com carne, frango ou peixe de dois em dois dias, se desejar?', ''],
		['Y11_Q59e', 'A situação financeira dos membros do seu agregado permite-lhes comprar roupa nova, em vez de em segunda mão?', ''],
		['Y11_Q59f', 'A situação financeira do seu agregado permite-lhe receber amigos ou familiares em casa para tomar uma bebida ou para comer, pelo menos uma vez por mês?', ''],
		['Y11_Q60a', 'Alguma vez, durante os últimos 12 meses, o seu agregado se atrasou nos pagamentos da renda ou da prestação da casa?', ''],
		['Y11_Q60b', 'Alguma vez, durante os últimos 12 meses, o seu agregado se atrasou nos pagamentos dos serviços públicos, como eletricidade, água, gás?', ''],
		['Y11_Q24', 'De uma maneira geral, diria que a maioria das pessoas é de confiança, ou que todo o cuidado é pouco no relacionamento com as pessoas?', ''],
		['Y11_Q25a', 'Tensão sentida entre os pobres e os ricos', ''],
		['Y11_Q25b', 'Tensão sentida entre os dirigentes de empresas e os trabalhadores', ''],
		['Y11_Q25c', 'Tensão sentida entre os homens e as mulheres', ''],
		['Y11_Q25d', 'Tensão sentida entre as pessoas idosas e os jovens', ''],
		['Y11_Q25e', 'Tensão sentida entre os diferentes grupos raciais e étnicos', ''],
		['Y11_Q25f', 'Tensão sentida entre os diferentes grupos religiosos', ''],
		['Y11_Q28a', 'Confiança no Parlamento', ''],
		['Y11_Q28b', 'Confiança no sistema jurídico', ''],
		['Y11_Q28c', 'Confiança na imprensa', ''],
		['Y11_Q28d', 'Confiança na polícia', ''],
		['Y11_Q28e', 'Confiança no governo', ''],
		['Y11_Q42', 'Perceção do estado de saúde', ''],
		['Y11_Q46d_WHO5', 'Escala de bem-estar mental OMS-5', ''],
		['Y11_Q47a', 'Dificuldade em recorrer a um médico devido à distância do consultório do médico ou do hospital/ centro de saúde', ''],
		['Y11_Q47b', 'Dificuldade em recorrer a um médico devido a atraso na marcação de consulta', ''],
		['Y11_Q47c', 'Dificuldade em recorrer a um médico devido ao tempo de espera para ser atendido(a) no dia da consulta', ''],
		['Y11_Q47d', 'Dificuldade em recorrer a um médico devido ao custo da consulta', ''],
		['Y11_Q53a', 'Como avalia a qualidade dos serviços de saúde no seu país?', ''],
		['Y11_Q53b', 'Como avalia a qualidade do sistema educativo no seu país?', ''],
		['Y11_Q53c', 'Como avalia a qualidade dos transportes públicos no seu país?', ''],
		['Y11_Q53d', 'Como avalia a qualidade dos serviços de cuidados infantis no seu país?', ''],
		['Y11_Q53g', 'Como avalia a qualidade do sistema de pensões no seu país?', '']
	];
