//Auto Generated file
var subset_
	 = [
	
		['Y11_HH2a', 'Pohlavie'],
		['Y11_Incomequartiles_percapita', 'Príjem'],
		['Y11_Agecategory', 'Vek']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Všetky vekové skupiny'],
		['Y11_Agecategory', '1--18-24y', 'Od 18 rokov do 24 rokov'],
		['Y11_Agecategory', '2--25-34y', 'Od 25 rokov do 34 rokov'],
		['Y11_Agecategory', '3--35-49y', 'Od 35 rokov do 49 rokov'],
		['Y11_Agecategory', '4--50-64y', 'Od 50 rokov do 64 rokov'],
		['Y11_Agecategory', '5---64y', '> 64 rokov'],
		['Y11_HH2a', 'All', 'Obidve pohlavia'],
		['Y11_HH2a', '1--Female', 'Žena'],
		['Y11_HH2a', '2--Male', 'Muž'],
		['Y11_Incomequartiles_percapita', 'All', 'Všetky príjmové kategórie'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Skupina s najnižšími príjmami'],
		['Y11_Incomequartiles_percapita', '2--2nd', '2.'],
		['Y11_Incomequartiles_percapita', '3--3rd', '3.'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Skupina s najvyššími príjmami']
	];
var topic_
	 = [
	
		['', 'Všetky (67)'],
		['Bydlisko a miestne okolie', 'Bydlisko a miestne okolie (9)'],
		['Kvalita spoločnosti', 'Kvalita spoločnosti (12)'],
		['Sociálne vylúčenie a zapojenie sa do spoločnosti', 'Sociálne vylúčenie a zapojenie sa do spoločnosti (7)'],
		['Subjektívne vnímanie blahobytu', 'Subjektívne vnímanie blahobytu (10)'],
		['Zamestnanie a rovnováha medzi pracovným a osobným životom', 'Zamestnanie a rovnováha medzi pracovným a osobným životom (8)'],
		['Zdravotnícke a verejnoprospešné služby', 'Zdravotnícke a verejnoprospešné služby (11)'],
		['Životná úroveň a úroveň chudoby', 'Životná úroveň a úroveň chudoby (10)']
	];
var topic_question
	 = [
	
		['Bydlisko a miestne okolie', 'Y11_Accommproblems', 'Počet problémov s ubytovaním'],
		['Bydlisko a miestne okolie', 'Y11_Q18', 'Vlastníctvo nehnuteľnosti'],
		['Bydlisko a miestne okolie', 'Y11_Q19a', 'Problémy s bývaním: Nedostatok miesta'],
		['Bydlisko a miestne okolie', 'Y11_Q19b', 'Problémy s bývaním: Rozpadávajúce sa okná, dvere alebo podlahy'],
		['Bydlisko a miestne okolie', 'Y11_Q19c', 'Problémy s bývaním: Vlhké alebo zatekajúce steny alebo strecha'],
		['Bydlisko a miestne okolie', 'Y11_Q19d', 'Problémy s bývaním: v interiéri chýba splachovacie WC'],
		['Bydlisko a miestne okolie', 'Y11_Q19e', 'Problémy s bývaním: chýba vaňa alebo sprcha'],
		['Bydlisko a miestne okolie', 'Y11_Q19f', 'Problémy s bývaním: chýba možnosť sedieť vonku'],
		['Bydlisko a miestne okolie', 'Y11_Q20', 'Aká je pravdepodobnosť, že budete musieť opustiť svoje bývanie v priebehu nasledujúcich 6 mesiacov, lebo si ho nebudete môcť dovoliť?'],
		['Kvalita spoločnosti', 'Y11_Q24', 'Povedali by ste, že väčšine ľudí možno dôverovať, alebo človek nemôže byť pri jednaní s ľuďmi nikdy dosť opatrný?'],
		['Kvalita spoločnosti', 'Y11_Q25a', 'Vnímané napätie medzi chudobnými a bohatými'],
		['Kvalita spoločnosti', 'Y11_Q25b', 'Vnímané napätie medzi manažmentom a zamestnancami'],
		['Kvalita spoločnosti', 'Y11_Q25c', 'Vnímané napätie medzi mužmi a ženami'],
		['Kvalita spoločnosti', 'Y11_Q25d', 'Vnímané napätie medzi starými a mladými'],
		['Kvalita spoločnosti', 'Y11_Q25e', 'Vnímané napätie medzi rôznymi rasovými a národnostnými skupinami'],
		['Kvalita spoločnosti', 'Y11_Q25f', 'Vnímané napätie medzi rozličnými náboženskými skupinami'],
		['Kvalita spoločnosti', 'Y11_Q28a', 'Dôvera parlamentu'],
		['Kvalita spoločnosti', 'Y11_Q28b', 'Dôvera v právny systém'],
		['Kvalita spoločnosti', 'Y11_Q28c', 'Dôvera tlači'],
		['Kvalita spoločnosti', 'Y11_Q28d', 'Dôvera polícii'],
		['Kvalita spoločnosti', 'Y11_Q28e', 'Dôvera vláde'],
		['Sociálne vylúčenie a zapojenie sa do spoločnosti', 'Y11_Q23a', 'Účasť na schôdzi odborárskej organizácie, politickej strany alebo politickej skupiny počas uplynulých 12 mesiacov'],
		['Sociálne vylúčenie a zapojenie sa do spoločnosti', 'Y11_Q23d', 'Kontakt s politikom alebo štátnym úradníkom (iný než bežnýkontakt súvisiaci s využívaním služieb štátnej správy).'],
		['Sociálne vylúčenie a zapojenie sa do spoločnosti', 'Y11_Q29e', 'Cítim sa vylúčený zo spoločnosti'],
		['Sociálne vylúčenie a zapojenie sa do spoločnosti', 'Y11_Q29f', 'V súčasnosti je život taký komplikovaný, že mám problémy sa zorientovať'],
		['Sociálne vylúčenie a zapojenie sa do spoločnosti', 'Y11_Q29g', 'Mám pocit, že iní ľudia neuznávajú hodnotu toho, čo robím'],
		['Sociálne vylúčenie a zapojenie sa do spoločnosti', 'Y11_Q29h', 'Niektorí ľudia sa na mňa pozerajú zhora kvôli mojej pracovnej situácii alebo príjmu'],
		['Sociálne vylúčenie a zapojenie sa do spoločnosti', 'Y11_SocExIndex', 'Index sociálneho vylúčenia'],
		['Subjektívne vnímanie blahobytu', 'Y11_Q29a', 'Budúcnosť vidím optimisticky'],
		['Subjektívne vnímanie blahobytu', 'Y11_Q30', 'Nakoľko ste spokojný(á) so svojím životom v dnešnejdobe?'],
		['Subjektívne vnímanie blahobytu', 'Y11_Q40a', 'Spokojnosť so vzdelaním'],
		['Subjektívne vnímanie blahobytu', 'Y11_Q40b', 'Spokojnosť so súčasným zamestnaním'],
		['Subjektívne vnímanie blahobytu', 'Y11_Q40c', 'Spokojnosť so súčasnou životnou úrovňou'],
		['Subjektívne vnímanie blahobytu', 'Y11_Q40d', 'Spokojnosť s bývaním'],
		['Subjektívne vnímanie blahobytu', 'Y11_Q40e', 'Spokojnosť s rodinným životom'],
		['Subjektívne vnímanie blahobytu', 'Y11_Q40f', 'Spokojnosť so zdravím'],
		['Subjektívne vnímanie blahobytu', 'Y11_Q40g', 'Spokojnosť so spoločenským životom'],
		['Subjektívne vnímanie blahobytu', 'Y11_Q41', 'Ak zvážite všetko ako celok, do akej miery by ste povedali, že ste šťastný(á)?'],
		['Zamestnanie a rovnováha medzi pracovným a osobným životom', 'Y11_Q12a', 'Prišiel(a) som domov z práce taký(á) unavený(á), že som nevládal(a) robiť domáce práce'],
		['Zamestnanie a rovnováha medzi pracovným a osobným životom', 'Y11_Q12b', 'Je pre mňa ťažké splniť si rodinné povinnosti kvôli času strávenému v práci '],
		['Zamestnanie a rovnováha medzi pracovným a osobným životom', 'Y11_Q12c', 'Mal(a) som ťažkosti sústrediť sa na prácu kvôli rodinným povinnostiam'],
		['Zamestnanie a rovnováha medzi pracovným a osobným životom', 'Y11_Q15', 'Aká je pravdepodobnosť, že by ste mohli v priebehu nasledujúcich 6 mesiacov prísť o zamestnanie?'],
		['Zamestnanie a rovnováha medzi pracovným a osobným životom', 'Y11_Q36b', 'Ako často sa podieľate na varení alebo domácich prácach?'],
		['Zamestnanie a rovnováha medzi pracovným a osobným životom', 'Y11_Q36c', 'Ako často sa podieľate na starostlivosti o starších alebo invalidných príbuzných?'],
		['Zamestnanie a rovnováha medzi pracovným a osobným životom', 'Y11_Q38', 'Postoj k podieľaniu sa na domácich prácach'],
		['Zamestnanie a rovnováha medzi pracovným a osobným životom', 'Y11_Q39d_stress', 'Stres'],
		['Zdravotnícke a verejnoprospešné služby', 'Y11_Q42', 'Vnímaný zdravotný stav'],
		['Zdravotnícke a verejnoprospešné služby', 'Y11_Q46d_WHO5', '5-bodová stupnica duševného blahobytu podľa WHO'],
		['Zdravotnícke a verejnoprospešné služby', 'Y11_Q47a', 'Problém s návštevou lekára z dôvodu vzdialenosti'],
		['Zdravotnícke a verejnoprospešné služby', 'Y11_Q47b', 'Problém s návštevou lekára z dôvodu neskorého termínu stretnutia'],
		['Zdravotnícke a verejnoprospešné služby', 'Y11_Q47c', 'Problém s návštevou lekára z dôvodu dlhého čakania v čakárni'],
		['Zdravotnícke a verejnoprospešné služby', 'Y11_Q47d', 'Problém s návštevou lekára z dôvodu nákladov'],
		['Zdravotnícke a verejnoprospešné služby', 'Y11_Q53a', 'Ako by ste ohodnotili kvalitu zdravotníckych služieb vo svojej krajine?'],
		['Zdravotnícke a verejnoprospešné služby', 'Y11_Q53b', 'Ako by ste ohodnotili kvalitu vzdelávacieho systému vo svojej krajine?'],
		['Zdravotnícke a verejnoprospešné služby', 'Y11_Q53c', 'Ako by ste ohodnotili kvalitu verejnej dopravy vo svojej krajine?'],
		['Zdravotnícke a verejnoprospešné služby', 'Y11_Q53d', 'Ako by ste ohodnotili kvalitu služieb starostlivosti o deti vo svojej krajine?'],
		['Zdravotnícke a verejnoprospešné služby', 'Y11_Q53g', 'Ako by ste ohodnotili kvalitu štátneho dôchodkového systému vo svojej krajine?'],
		['Životná úroveň a úroveň chudoby', 'Y11_Deprindex', 'Index deprivácie: počet položiek, ktoré si domácnosť nemôže dovoliť'],
		['Životná úroveň a úroveň chudoby', 'Y11_Q58', 'Vystačí Vám Váš príjem na pokrytie potrieb domácnosti?'],
		['Životná úroveň a úroveň chudoby', 'Y11_Q59a', 'Môžete si dovoliť udržiavať doma primeranú teplotu?'],
		['Životná úroveň a úroveň chudoby', 'Y11_Q59b', 'Môžete si dovoliť zaplatiť každý rok týždňovú dovolenku mimo domu?'],
		['Životná úroveň a úroveň chudoby', 'Y11_Q59c', 'Môžete si dovoliť vymeniť akýkoľvek opotrebovaný kus nábytku?'],
		['Životná úroveň a úroveň chudoby', 'Y11_Q59d', 'Môžete si dovoliť každý druhý deň jedno mäsité jedlo, hydinu alebo rybu (ak by ste chceli)?'],
		['Životná úroveň a úroveň chudoby', 'Y11_Q59e', 'Môžete si dovoliť kupovať si nové, a nie obnosené oblečenie (zo second-handu)?'],
		['Životná úroveň a úroveň chudoby', 'Y11_Q59f', 'Môžete si dovoliť aspoň raz do mesiaca pozvať priateľov alebo rodinu na pohárik alebo obed/večeru?'],
		['Životná úroveň a úroveň chudoby', 'Y11_Q60a', 'Dostali ste sa vo Vašej domácnosti v uplynulých 12 mesiacoch do situácie, že ste neboli schopní načas zaplatiť nájomné alebo splátky hypotéky?'],
		['Životná úroveň a úroveň chudoby', 'Y11_Q60b', 'Dostali ste sa vo Vašej domácnosti v uplynulých 12 mesiacoch do situácie, že ste neboli schopní načas zaplatiť účty za spotrebu energií?']
	];
var question_
	 = [
	
		['Y11_Accommproblems', 'Počet problémov s ubytovaním'],
		['Y11_Q18', 'Vlastníctvo nehnuteľnosti'],
		['Y11_Q19a', 'Problémy s bývaním: Nedostatok miesta'],
		['Y11_Q19b', 'Problémy s bývaním: Rozpadávajúce sa okná, dvere alebo podlahy'],
		['Y11_Q19c', 'Problémy s bývaním: Vlhké alebo zatekajúce steny alebo strecha'],
		['Y11_Q19d', 'Problémy s bývaním: v interiéri chýba splachovacie WC'],
		['Y11_Q19e', 'Problémy s bývaním: chýba vaňa alebo sprcha'],
		['Y11_Q19f', 'Problémy s bývaním: chýba možnosť sedieť vonku'],
		['Y11_Q20', 'Aká je pravdepodobnosť, že budete musieť opustiť svoje bývanie v priebehu nasledujúcich 6 mesiacov, lebo si ho nebudete môcť dovoliť?'],
		['Y11_Q24', 'Povedali by ste, že väčšine ľudí možno dôverovať, alebo človek nemôže byť pri jednaní s ľuďmi nikdy dosť opatrný?'],
		['Y11_Q25a', 'Vnímané napätie medzi chudobnými a bohatými'],
		['Y11_Q25b', 'Vnímané napätie medzi manažmentom a zamestnancami'],
		['Y11_Q25c', 'Vnímané napätie medzi mužmi a ženami'],
		['Y11_Q25d', 'Vnímané napätie medzi starými a mladými'],
		['Y11_Q25e', 'Vnímané napätie medzi rôznymi rasovými a národnostnými skupinami'],
		['Y11_Q25f', 'Vnímané napätie medzi rozličnými náboženskými skupinami'],
		['Y11_Q28a', 'Dôvera parlamentu'],
		['Y11_Q28b', 'Dôvera v právny systém'],
		['Y11_Q28c', 'Dôvera tlači'],
		['Y11_Q28d', 'Dôvera polícii'],
		['Y11_Q28e', 'Dôvera vláde'],
		['Y11_Q23a', 'Účasť na schôdzi odborárskej organizácie, politickej strany alebo politickej skupiny počas uplynulých 12 mesiacov'],
		['Y11_Q23d', 'Kontakt s politikom alebo štátnym úradníkom (iný než bežnýkontakt súvisiaci s využívaním služieb štátnej správy).'],
		['Y11_Q29e', 'Cítim sa vylúčený zo spoločnosti'],
		['Y11_Q29f', 'V súčasnosti je život taký komplikovaný, že mám problémy sa zorientovať'],
		['Y11_Q29g', 'Mám pocit, že iní ľudia neuznávajú hodnotu toho, čo robím'],
		['Y11_Q29h', 'Niektorí ľudia sa na mňa pozerajú zhora kvôli mojej pracovnej situácii alebo príjmu'],
		['Y11_SocExIndex', 'Index sociálneho vylúčenia'],
		['Y11_Q29a', 'Budúcnosť vidím optimisticky'],
		['Y11_Q30', 'Nakoľko ste spokojný(á) so svojím životom v dnešnejdobe?'],
		['Y11_Q40a', 'Spokojnosť so vzdelaním'],
		['Y11_Q40b', 'Spokojnosť so súčasným zamestnaním'],
		['Y11_Q40c', 'Spokojnosť so súčasnou životnou úrovňou'],
		['Y11_Q40d', 'Spokojnosť s bývaním'],
		['Y11_Q40e', 'Spokojnosť s rodinným životom'],
		['Y11_Q40f', 'Spokojnosť so zdravím'],
		['Y11_Q40g', 'Spokojnosť so spoločenským životom'],
		['Y11_Q41', 'Ak zvážite všetko ako celok, do akej miery by ste povedali, že ste šťastný(á)?'],
		['Y11_Q12a', 'Prišiel(a) som domov z práce taký(á) unavený(á), že som nevládal(a) robiť domáce práce'],
		['Y11_Q12b', 'Je pre mňa ťažké splniť si rodinné povinnosti kvôli času strávenému v práci '],
		['Y11_Q12c', 'Mal(a) som ťažkosti sústrediť sa na prácu kvôli rodinným povinnostiam'],
		['Y11_Q15', 'Aká je pravdepodobnosť, že by ste mohli v priebehu nasledujúcich 6 mesiacov prísť o zamestnanie?'],
		['Y11_Q36b', 'Ako často sa podieľate na varení alebo domácich prácach?'],
		['Y11_Q36c', 'Ako často sa podieľate na starostlivosti o starších alebo invalidných príbuzných?'],
		['Y11_Q38', 'Postoj k podieľaniu sa na domácich prácach'],
		['Y11_Q39d_stress', 'Stres'],
		['Y11_Q42', 'Vnímaný zdravotný stav'],
		['Y11_Q46d_WHO5', '5-bodová stupnica duševného blahobytu podľa WHO'],
		['Y11_Q47a', 'Problém s návštevou lekára z dôvodu vzdialenosti'],
		['Y11_Q47b', 'Problém s návštevou lekára z dôvodu neskorého termínu stretnutia'],
		['Y11_Q47c', 'Problém s návštevou lekára z dôvodu dlhého čakania v čakárni'],
		['Y11_Q47d', 'Problém s návštevou lekára z dôvodu nákladov'],
		['Y11_Q53a', 'Ako by ste ohodnotili kvalitu zdravotníckych služieb vo svojej krajine?'],
		['Y11_Q53b', 'Ako by ste ohodnotili kvalitu vzdelávacieho systému vo svojej krajine?'],
		['Y11_Q53c', 'Ako by ste ohodnotili kvalitu verejnej dopravy vo svojej krajine?'],
		['Y11_Q53d', 'Ako by ste ohodnotili kvalitu služieb starostlivosti o deti vo svojej krajine?'],
		['Y11_Q53g', 'Ako by ste ohodnotili kvalitu štátneho dôchodkového systému vo svojej krajine?'],
		['Y11_Deprindex', 'Index deprivácie: počet položiek, ktoré si domácnosť nemôže dovoliť'],
		['Y11_Q58', 'Vystačí Vám Váš príjem na pokrytie potrieb domácnosti?'],
		['Y11_Q59a', 'Môžete si dovoliť udržiavať doma primeranú teplotu?'],
		['Y11_Q59b', 'Môžete si dovoliť zaplatiť každý rok týždňovú dovolenku mimo domu?'],
		['Y11_Q59c', 'Môžete si dovoliť vymeniť akýkoľvek opotrebovaný kus nábytku?'],
		['Y11_Q59d', 'Môžete si dovoliť každý druhý deň jedno mäsité jedlo, hydinu alebo rybu (ak by ste chceli)?'],
		['Y11_Q59e', 'Môžete si dovoliť kupovať si nové, a nie obnosené oblečenie (zo second-handu)?'],
		['Y11_Q59f', 'Môžete si dovoliť aspoň raz do mesiaca pozvať priateľov alebo rodinu na pohárik alebo obed/večeru?'],
		['Y11_Q60a', 'Dostali ste sa vo Vašej domácnosti v uplynulých 12 mesiacoch do situácie, že ste neboli schopní načas zaplatiť nájomné alebo splátky hypotéky?'],
		['Y11_Q60b', 'Dostali ste sa vo Vašej domácnosti v uplynulých 12 mesiacoch do situácie, že ste neboli schopní načas zaplatiť účty za spotrebu energií?']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Stredná hodnota'],
		['Y11_Deprindex', 'Mean', 'Stredná hodnota'],
		['Y11_Q12a', '1--Several-times-a-week', 'Niekoľko krát za týždeň'],
		['Y11_Q12a', '2--Several-times-a-month', 'Niekoľko krát do mesiaca'],
		['Y11_Q12a', '3--Several-times-a-year', 'Niekoľko krát za rok'],
		['Y11_Q12a', '4--Less-often-rarely', 'Menej často / zriedkavo'],
		['Y11_Q12a', '5--Never', 'Nikdy'],
		['Y11_Q12b', '1--Several-times-a-week', 'Niekoľko krát za týždeň'],
		['Y11_Q12b', '2--Several-times-a-month', 'Niekoľko krát do mesiaca'],
		['Y11_Q12b', '3--Several-times-a-year', 'Niekoľko krát za rok'],
		['Y11_Q12b', '4--Less-often-rarely', 'Menej často / zriedkavo'],
		['Y11_Q12b', '5--Never', 'Nikdy'],
		['Y11_Q12c', '1--Several-times-a-week', 'Niekoľko krát za týždeň'],
		['Y11_Q12c', '2--Several-times-a-month', 'Niekoľko krát do mesiaca'],
		['Y11_Q12c', '3--Several-times-a-year', 'Niekoľko krát za rok'],
		['Y11_Q12c', '4--Less-often-rarely', 'Menej často / zriedkavo'],
		['Y11_Q12c', '5--Never', 'Nikdy'],
		['Y11_Q15', '1--Very-likely', 'Veľmi pravdepodobné'],
		['Y11_Q15', '2--Quite-likely', 'Skôr pravdepodobné'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Ani pravdepodobné, ani nepravdepodobné'],
		['Y11_Q15', '4--Quite-unlikely', 'Skôr nepravdepodobné'],
		['Y11_Q15', '5--Very-unlikely', 'Veľmi nepravdepodobné'],
		['Y11_Q18', '1--Own-without-mortgage', 'Vlastné bývanie bez hypotéky'],
		['Y11_Q18', '2--Own-with-mortgage', 'Vlastné bývanie zaťažené hypotékou'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Nájomník, platiaci nájomné v sociálnom / podnikovom / obecnom dome'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Nájomník, platiaci nájomné súkromnému prenajímateľovi'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Ubytovanie je poskytované bez platenia nájomného'],
		['Y11_Q18', '6--Other', 'Iné'],
		['Y11_Q19a', '1--Yes', 'Áno'],
		['Y11_Q19a', '2--No', 'Nie'],
		['Y11_Q19b', '1--Yes', 'Áno'],
		['Y11_Q19b', '2--No', 'Nie'],
		['Y11_Q19c', '1--Yes', 'Áno'],
		['Y11_Q19c', '2--No', 'Nie'],
		['Y11_Q19d', '1--Yes', 'Áno'],
		['Y11_Q19d', '2--No', 'Nie'],
		['Y11_Q19e', '1--Yes', 'Áno'],
		['Y11_Q19e', '2--No', 'Nie'],
		['Y11_Q19f', '1--Yes', 'Áno'],
		['Y11_Q19f', '2--No', 'Nie'],
		['Y11_Q20', '1--Very-likely', 'Veľmi pravdepodobné'],
		['Y11_Q20', '2--Quite-likely', 'Skôr pravdepodobné'],
		['Y11_Q20', '3--Quite-unlikely', 'Skôr nepravdepodobné'],
		['Y11_Q20', '4--Very-unlikely', 'Veľmi nepravdepodobné'],
		['Y11_Q23a', '1--Yes', 'Áno'],
		['Y11_Q23a', '2--No', 'Nie'],
		['Y11_Q23d', '1--Yes', 'Áno'],
		['Y11_Q23d', '2--No', 'Nie'],
		['Y11_Q24', 'Mean', 'Stredná hodnota'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Veľké napätie'],
		['Y11_Q25a', '2--Some-tension', 'Isté napätie'],
		['Y11_Q25a', '3--No-tension', 'Žiadne napätie'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Veľké napätie'],
		['Y11_Q25b', '2--Some-tension', 'Isté napätie'],
		['Y11_Q25b', '3--No-tension', 'Žiadne napätie'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Veľké napätie'],
		['Y11_Q25c', '2--Some-tension', 'Isté napätie'],
		['Y11_Q25c', '3--No-tension', 'Žiadne napätie'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Veľké napätie'],
		['Y11_Q25d', '2--Some-tension', 'Isté napätie'],
		['Y11_Q25d', '3--No-tension', 'Žiadne napätie'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Veľké napätie'],
		['Y11_Q25e', '2--Some-tension', 'Isté napätie'],
		['Y11_Q25e', '3--No-tension', 'Žiadne napätie'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Veľké napätie'],
		['Y11_Q25f', '2--Some-tension', 'Isté napätie'],
		['Y11_Q25f', '3--No-tension', 'Žiadne napätie'],
		['Y11_Q28a', 'Mean', 'Stredná hodnota'],
		['Y11_Q28b', 'Mean', 'Stredná hodnota'],
		['Y11_Q28c', 'Mean', 'Stredná hodnota'],
		['Y11_Q28d', 'Mean', 'Stredná hodnota'],
		['Y11_Q28e', 'Mean', 'Stredná hodnota'],
		['Y11_Q29a', '1--Strongly-agree', 'Rozhodne súhlasím'],
		['Y11_Q29a', '2--Agree', 'Súhlasím'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Ani súhlasím, ani nesúhlasím'],
		['Y11_Q29a', '4--Disagree', 'Nesúhlasím'],
		['Y11_Q29a', '5--Strongly-disagree', 'Rozhodne nesúhlasím'],
		['Y11_Q29e', '1--Strongly-agree', 'Rozhodne súhlasím'],
		['Y11_Q29e', '2--Agree', 'Súhlasím'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Ani súhlasím, ani nesúhlasím'],
		['Y11_Q29e', '4--Disagree', 'Nesúhlasím'],
		['Y11_Q29e', '5--Strongly-disagree', 'Rozhodne nesúhlasím'],
		['Y11_Q29f', '1--Strongly-agree', 'Rozhodne súhlasím'],
		['Y11_Q29f', '2--Agree', 'Súhlasím'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Ani súhlasím, ani nesúhlasím'],
		['Y11_Q29f', '4--Disagree', 'Nesúhlasím'],
		['Y11_Q29f', '5--Strongly-disagree', 'Rozhodne nesúhlasím'],
		['Y11_Q29g', '1--Strongly-agree', 'Rozhodne súhlasím'],
		['Y11_Q29g', '2--Agree', 'Súhlasím'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Ani súhlasím, ani nesúhlasím'],
		['Y11_Q29g', '4--Disagree', 'Nesúhlasím'],
		['Y11_Q29g', '5--Strongly-disagree', 'Rozhodne nesúhlasím'],
		['Y11_Q29h', '1--Strongly-agree', 'Rozhodne súhlasím'],
		['Y11_Q29h', '2--Agree', 'Súhlasím'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Ani súhlasím, ani nesúhlasím'],
		['Y11_Q29h', '4--Disagree', 'Nesúhlasím'],
		['Y11_Q29h', '5--Strongly-disagree', 'Rozhodne nesúhlasím'],
		['Y11_Q30', 'Mean', 'Stredná hodnota'],
		['Y11_Q36b', '1--Every-day', 'Každý deň'],
		['Y11_Q36b', '2--Several-days-a-week', 'Niekoľko krát za týždeň'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'Raz alebo dvakrát za týždeň'],
		['Y11_Q36b', '4--Less-often', 'Menej často'],
		['Y11_Q36b', '5--Never', 'Nikdy'],
		['Y11_Q36c', '1--Every-day', 'Každý deň'],
		['Y11_Q36c', '2--Several-days-a-week', 'Niekoľko krát za týždeň'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'Raz alebo dvakrát za týždeň'],
		['Y11_Q36c', '4--Less-often', 'Menej často'],
		['Y11_Q36c', '5--Never', 'Nikdy'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Väčší, než považujete za spravodlivé'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Spravodlivý'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Menší, než považujete za spravodlivé'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'V práci i doma'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Buď v práci alebo doma'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Malý alebo žiadny stres'],
		['Y11_Q40a', 'Mean', 'Stredná hodnota'],
		['Y11_Q40b', 'Mean', 'Stredná hodnota'],
		['Y11_Q40c', 'Mean', 'Stredná hodnota'],
		['Y11_Q40d', 'Mean', 'Stredná hodnota'],
		['Y11_Q40e', 'Mean', 'Stredná hodnota'],
		['Y11_Q40f', 'Mean', 'Stredná hodnota'],
		['Y11_Q40g', 'Mean', 'Stredná hodnota'],
		['Y11_Q41', 'Mean', 'Stredná hodnota'],
		['Y11_Q42', '1--Very-good', 'Veľmi dobré'],
		['Y11_Q42', '2--Good', 'Dobré'],
		['Y11_Q42', '3--Fair', 'Prijateľné'],
		['Y11_Q42', '4--Bad', 'Zlé'],
		['Y11_Q42', '5--Very-bad', 'Veľmi zlé'],
		['Y11_Q46d_WHO5', 'Mean', 'Stredná hodnota'],
		['Y11_Q47a', '1--Very-difficult', 'Veľmi sťažilo'],
		['Y11_Q47a', '2--A-little-difficult', 'Trochu sťažilo'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Vôbec nesťažilo'],
		['Y11_Q47b', '1--Very-difficult', 'Veľmi sťažilo'],
		['Y11_Q47b', '2--A-little-difficult', 'Trochu sťažilo'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Vôbec nesťažilo'],
		['Y11_Q47c', '1--Very-difficult', 'Veľmi sťažilo'],
		['Y11_Q47c', '2--A-little-difficult', 'Trochu sťažilo'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Vôbec nesťažilo'],
		['Y11_Q47d', '1--Very-difficult', 'Veľmi sťažilo'],
		['Y11_Q47d', '2--A-little-difficult', 'Trochu sťažilo'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Vôbec nesťažilo'],
		['Y11_Q53a', 'Mean', 'Stredná hodnota'],
		['Y11_Q53b', 'Mean', 'Stredná hodnota'],
		['Y11_Q53c', 'Mean', 'Stredná hodnota'],
		['Y11_Q53d', 'Mean', 'Stredná hodnota'],
		['Y11_Q53g', 'Mean', 'Stredná hodnota'],
		['Y11_Q58', '1--With-great-difficulty', 'S veľkými ťažkosťami'],
		['Y11_Q58', '2--With-difficulty', 'S ťažkosťami'],
		['Y11_Q58', '3--With-some-difficulty', 'S určitými ťažkosťami'],
		['Y11_Q58', '4--Fairly-easily', 'Úplne ľahko'],
		['Y11_Q58', '5--Easily', 'Ľahko'],
		['Y11_Q58', '6--Very-easily', 'Veľmi ľahko'],
		['Y11_Q59a', '1--No', 'Nie'],
		['Y11_Q59a', '2--Yes', 'Áno'],
		['Y11_Q59b', '1--No', 'Nie'],
		['Y11_Q59b', '2--Yes', 'Áno'],
		['Y11_Q59c', '1--No', 'Nie'],
		['Y11_Q59c', '2--Yes', 'Áno'],
		['Y11_Q59d', '1--No', 'Nie'],
		['Y11_Q59d', '2--Yes', 'Áno'],
		['Y11_Q59e', '1--No', 'Nie'],
		['Y11_Q59e', '2--Yes', 'Áno'],
		['Y11_Q59f', '1--No', 'Nie'],
		['Y11_Q59f', '2--Yes', 'Áno'],
		['Y11_Q60a', '1--Yes', 'Áno'],
		['Y11_Q60a', '2--No', 'Nie'],
		['Y11_Q60b', '1--Yes', 'Áno'],
		['Y11_Q60b', '2--No', 'Nie'],
		['Y11_SocExIndex', 'Mean', 'Stredná hodnota']
	];
var country_
	 = [
	
		['AT', 'Rakúsko'],
		['BE', 'Belgicko'],
		['BG', 'Bulharsko'],
		['CY', 'Cyprus'],
		['CZ', 'Česká republika'],
		['DE', 'Nemecko'],
		['DK', 'Dánsko'],
		['EE', 'Estónsko'],
		['EL', 'Grécko'],
		['ES', 'Francúzsko'],
		['FI', 'Fínsko'],
		['FR', 'Francúzsko'],
		['HR', 'Chorvátsko'],
		['HU', 'Maďarsko'],
		['IE', 'Írsko'],
		['IT', 'Taliansko'],
		['LT', 'Litva'],
		['LU', 'Luxembursko'],
		['LV', 'Lotyšsko'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Holandsko'],
		['NO', 'Nórsko'],
		['PL', 'Poľsko'],
		['PT', 'Portugalsko'],
		['RO', 'Rumunsko'],
		['SE', 'Švédsko'],
		['SI', 'Slovinsko'],
		['SK', 'Slovensko'],
		['TR', 'Turecko'],
		['UK', 'Spojené kráľovstvo'],
		['EuropeanUnion', 'Európska únia']
	];
var question_meta
	 = [
	
		['Y11_Accommproblems', 'Počet problémov s ubytovaním', ''],
		['Y11_Q18', 'Vlastníctvo nehnuteľnosti', ''],
		['Y11_Q19a', 'Problémy s bývaním: Nedostatok miesta', ''],
		['Y11_Q19b', 'Problémy s bývaním: Rozpadávajúce sa okná, dvere alebo podlahy', ''],
		['Y11_Q19c', 'Problémy s bývaním: Vlhké alebo zatekajúce steny alebo strecha', ''],
		['Y11_Q19d', 'Problémy s bývaním: v interiéri chýba splachovacie WC', ''],
		['Y11_Q19e', 'Problémy s bývaním: chýba vaňa alebo sprcha', ''],
		['Y11_Q19f', 'Problémy s bývaním: chýba možnosť sedieť vonku', ''],
		['Y11_Q20', 'Aká je pravdepodobnosť, že budete musieť opustiť svoje bývanie v priebehu nasledujúcich 6 mesiacov, lebo si ho nebudete môcť dovoliť?', ''],
		['Y11_Q24', 'Povedali by ste, že väčšine ľudí možno dôverovať, alebo človek nemôže byť pri jednaní s ľuďmi nikdy dosť opatrný?', ''],
		['Y11_Q25a', 'Vnímané napätie medzi chudobnými a bohatými', ''],
		['Y11_Q25b', 'Vnímané napätie medzi manažmentom a zamestnancami', ''],
		['Y11_Q25c', 'Vnímané napätie medzi mužmi a ženami', ''],
		['Y11_Q25d', 'Vnímané napätie medzi starými a mladými', ''],
		['Y11_Q25e', 'Vnímané napätie medzi rôznymi rasovými a národnostnými skupinami', ''],
		['Y11_Q25f', 'Vnímané napätie medzi rozličnými náboženskými skupinami', ''],
		['Y11_Q28a', 'Dôvera parlamentu', ''],
		['Y11_Q28b', 'Dôvera v právny systém', ''],
		['Y11_Q28c', 'Dôvera tlači', ''],
		['Y11_Q28d', 'Dôvera polícii', ''],
		['Y11_Q28e', 'Dôvera vláde', ''],
		['Y11_Q23a', 'Účasť na schôdzi odborárskej organizácie, politickej strany alebo politickej skupiny počas uplynulých 12 mesiacov', ''],
		['Y11_Q23d', 'Kontakt s politikom alebo štátnym úradníkom (iný než bežnýkontakt súvisiaci s využívaním služieb štátnej správy).', ''],
		['Y11_Q29e', 'Cítim sa vylúčený zo spoločnosti', ''],
		['Y11_Q29f', 'V súčasnosti je život taký komplikovaný, že mám problémy sa zorientovať', ''],
		['Y11_Q29g', 'Mám pocit, že iní ľudia neuznávajú hodnotu toho, čo robím', ''],
		['Y11_Q29h', 'Niektorí ľudia sa na mňa pozerajú zhora kvôli mojej pracovnej situácii alebo príjmu', ''],
		['Y11_SocExIndex', 'Index sociálneho vylúčenia', ''],
		['Y11_Q29a', 'Budúcnosť vidím optimisticky', ''],
		['Y11_Q30', 'Nakoľko ste spokojný(á) so svojím životom v dnešnejdobe?', ''],
		['Y11_Q40a', 'Spokojnosť so vzdelaním', ''],
		['Y11_Q40b', 'Spokojnosť so súčasným zamestnaním', ''],
		['Y11_Q40c', 'Spokojnosť so súčasnou životnou úrovňou', ''],
		['Y11_Q40d', 'Spokojnosť s bývaním', ''],
		['Y11_Q40e', 'Spokojnosť s rodinným životom', ''],
		['Y11_Q40f', 'Spokojnosť so zdravím', ''],
		['Y11_Q40g', 'Spokojnosť so spoločenským životom', ''],
		['Y11_Q41', 'Ak zvážite všetko ako celok, do akej miery by ste povedali, že ste šťastný(á)?', ''],
		['Y11_Q12a', 'Prišiel(a) som domov z práce taký(á) unavený(á), že som nevládal(a) robiť domáce práce', ''],
		['Y11_Q12b', 'Je pre mňa ťažké splniť si rodinné povinnosti kvôli času strávenému v práci ', ''],
		['Y11_Q12c', 'Mal(a) som ťažkosti sústrediť sa na prácu kvôli rodinným povinnostiam', ''],
		['Y11_Q15', 'Aká je pravdepodobnosť, že by ste mohli v priebehu nasledujúcich 6 mesiacov prísť o zamestnanie?', ''],
		['Y11_Q36b', 'Ako často sa podieľate na varení alebo domácich prácach?', ''],
		['Y11_Q36c', 'Ako často sa podieľate na starostlivosti o starších alebo invalidných príbuzných?', ''],
		['Y11_Q38', 'Čo si myslíte o svojom podiele na domácich prácach?', ''],
		['Y11_Q39d_stress', 'Stres v dôsledku problémov s rovnováhou medzi pracovným a osobným životom', ''],
		['Y11_Q42', 'Vnímaný zdravotný stav', ''],
		['Y11_Q46d_WHO5', '5-bodová stupnica duševného blahobytu podľa WHO', ''],
		['Y11_Q47a', 'Problém s návštevou lekára z dôvodu vzdialenosti lekárskej ambulancie alebo nemocnice', ''],
		['Y11_Q47b', 'Problém s návštevou lekára z dôvodu neskorého termínu stretnutia', ''],
		['Y11_Q47c', 'Problém s návštevou lekára z dôvodu dlhého čakania na vyšetrenie v čakárni v deň vyšetrenia', ''],
		['Y11_Q47d', 'Problém s návštevou lekára z dôvodu nákladov spojených s návštevou lekára', ''],
		['Y11_Q53a', 'Ako by ste ohodnotili kvalitu zdravotníckych služieb vo svojej krajine?', ''],
		['Y11_Q53b', 'Ako by ste ohodnotili kvalitu vzdelávacieho systému vo svojej krajine?', ''],
		['Y11_Q53c', 'Ako by ste ohodnotili kvalitu verejnej dopravy vo svojej krajine?', ''],
		['Y11_Q53d', 'Ako by ste ohodnotili kvalitu služieb starostlivosti o deti vo svojej krajine?', ''],
		['Y11_Q53g', 'Ako by ste ohodnotili kvalitu štátneho dôchodkového systému vo svojej krajine?', ''],
		['Y11_Deprindex', 'Index deprivácie: počet položiek, ktoré si domácnosť nemôže dovoliť', ''],
		['Y11_Q58', 'Vystačí Vám Váš príjem na pokrytie potrieb domácnosti?', ''],
		['Y11_Q59a', 'Môžete si dovoliť udržiavať doma primeranú teplotu?', ''],
		['Y11_Q59b', 'Môžete si dovoliť zaplatiť každý rok týždňovú dovolenku mimo domu?', ''],
		['Y11_Q59c', 'Môžete si dovoliť vymeniť akýkoľvek opotrebovaný kus nábytku?', ''],
		['Y11_Q59d', 'Môže si Vaša domácnosť dovoliť každý druhý deň jedno mäsité jedlo, hydinu alebo rybu (ak by ste chceli)?', ''],
		['Y11_Q59e', 'Môžu si členovia Vašej domácnosti dovoliť kupovať si nové, a nie obnosené oblečenie (zo second-handu)?', ''],
		['Y11_Q59f', 'Môže si Vaša domácnosť dovoliť aspoň raz do mesiaca pozvať priateľov alebo rodinu na pohárik alebo obed/večeru?', ''],
		['Y11_Q60a', 'Dostali ste sa vo Vašej domácnosti v uplynulých 12 mesiacoch do situácie, že ste neboli schopní načas zaplatiť nájomné alebo splátky hypotéky?', ''],
		['Y11_Q60b', 'Dostali ste sa vo Vašej domácnosti v uplynulých 12 mesiacoch do situácie, že ste neboli schopní načas zaplatiť účty za spotrebu energií?', '']
	];
