//Auto Generated file
var subset_
	 = [
	
		['Y11_HH2a', 'Cinsiyet'],
		['Y11_Incomequartiles_percapita', 'Gelir'],
		['Y11_Agecategory', 'Yaş']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Tüm yaşlar'],
		['Y11_Agecategory', '1--18-24y', '18-24 yaş'],
		['Y11_Agecategory', '2--25-34y', '25-34 yaş'],
		['Y11_Agecategory', '3--35-49y', '35-49 yaş'],
		['Y11_Agecategory', '4--50-64y', '50-64 yaş'],
		['Y11_Agecategory', '5---64y', '> 64 yaş'],
		['Y11_HH2a', 'All', 'Her iki cins'],
		['Y11_HH2a', '1--Female', 'Kadın'],
		['Y11_HH2a', '2--Male', 'Erkek'],
		['Y11_Incomequartiles_percapita', 'All', 'Tüm gelir seviyeleri'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'En düşük'],
		['Y11_Incomequartiles_percapita', '2--2nd', '2nci'],
		['Y11_Incomequartiles_percapita', '3--3rd', '3üncü'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'En yüksek']
	];
var topic_
	 = [
	
		['', 'Hepsi (67)'],
		['Ev ve yakın çevre', 'Ev ve yakın çevre (9)'],
		['Hayat ve yoksunluk standardı', 'Hayat ve yoksunluk standardı (10)'],
		['Sağlık ve kamu hizmetleri', 'Sağlık ve kamu hizmetleri (11)'],
		['Sosyal dışlanma ve topluluğa katılım', 'Sosyal dışlanma ve topluluğa katılım (7)'],
		['Subjektif refah', 'Subjektif refah (10)'],
		['Toplum kalitesi', 'Toplum kalitesi (12)'],
		['İstihdam ve iş-yaşam dengesi', 'İstihdam ve iş-yaşam dengesi (8)']
	];
var topic_question
	 = [
	
		['Ev ve yakın çevre', 'Y11_Accommproblems', 'Barınma sorunlarının sayısı'],
		['Ev ve yakın çevre', 'Y11_Q18', 'Ev sahibi olma'],
		['Ev ve yakın çevre', 'Y11_Q19a', 'Barınmayla ilgili sorunlar: Yer darlığı'],
		['Ev ve yakın çevre', 'Y11_Q19b', 'Barınmayla ilgili sorunlar: Pencerelerde, kapılarda veya zeminde çürüme'],
		['Ev ve yakın çevre', 'Y11_Q19c', 'Barınmayla ilgili sorunlar: Duvarlarda ya da çatıda akıntı'],
		['Ev ve yakın çevre', 'Y11_Q19d', 'Barınmayla ilgili sorunlar: Ev içinde çalışır bir tuvalet olmaması'],
		['Ev ve yakın çevre', 'Y11_Q19e', 'Barınmayla ilgili sorunlar: Küvet veya duş olmaması'],
		['Ev ve yakın çevre', 'Y11_Q19f', 'Barınmayla ilgili sorunlar: Dışarıda oturacak yer olmaması'],
		['Ev ve yakın çevre', 'Y11_Q20', 'Önümüzdeki 6 ay içinde maddi olarak karşılayamadığınız için evinizden ayrılmanız ne derece muhtemel?'],
		['Hayat ve yoksunluk standardı', 'Y11_Deprindex', 'Yoksunluk endeksi: Hanenin karşılayamadığı öğelerin sayısı'],
		['Hayat ve yoksunluk standardı', 'Y11_Q58', 'Haneniz geçinebiliyor mu?'],
		['Hayat ve yoksunluk standardı', 'Y11_Q59a', 'Evinizi yeterince sıcak tutabiliyor musunuz?'],
		['Hayat ve yoksunluk standardı', 'Y11_Q59b', 'Ev dışında yılda bir hafta tatil yapma masrafını karşılayabiliyor musunuz?'],
		['Hayat ve yoksunluk standardı', 'Y11_Q59c', 'Eskimiş mobilyanızı yenileyebiliyor musunuz?'],
		['Hayat ve yoksunluk standardı', 'Y11_Q59d', '(İstediğiniz takdirde) her iki günde bir et, tavuk ya da balık içeren bir öğün yiyebiliyor musunuz?'],
		['Hayat ve yoksunluk standardı', 'Y11_Q59e', 'İkinci el yerine yeni kıyafetler alabiliyor musunuz?'],
		['Hayat ve yoksunluk standardı', 'Y11_Q59f', 'Ayda en az bir kez arkadaşlarınızı ya da ailenizi bir şey içmek ya da yemek yemek için ağırlayabiliyor musunuz?'],
		['Hayat ve yoksunluk standardı', 'Y11_Q60a', 'Hanenizin son 12 ay içinde ödenmemiş kira ya da mortgage borcu oldu mu?'],
		['Hayat ve yoksunluk standardı', 'Y11_Q60b', 'Hanenizin son 12 ay içinde ödenmemiş elektrik, su, doğalgaz borcu oldu mu?'],
		['Sağlık ve kamu hizmetleri', 'Y11_Q42', 'Algılanan sağlık durumu'],
		['Sağlık ve kamu hizmetleri', 'Y11_Q46d_WHO5', 'WHO-5 ruhsal sağlık ölçeği'],
		['Sağlık ve kamu hizmetleri', 'Y11_Q47a', 'Uzaklık nedeniyle doktora görünmek zor'],
		['Sağlık ve kamu hizmetleri', 'Y11_Q47b', 'Randevu alımında gecikme nedeniyle doktora görünmek zor'],
		['Sağlık ve kamu hizmetleri', 'Y11_Q47c', 'Randevu günü beklenen süre nedeniyle doktora görünmek zor'],
		['Sağlık ve kamu hizmetleri', 'Y11_Q47d', 'Ücret nedeniyle doktora görünmek zor'],
		['Sağlık ve kamu hizmetleri', 'Y11_Q53a', 'Ülkenizdeki sağlık hizmetlerinin kalitesini nasıl değerlendirirsiniz?'],
		['Sağlık ve kamu hizmetleri', 'Y11_Q53b', 'Ülkenizdeki eğitim sisteminin kalitesini nasıl değerlendirirsiniz?'],
		['Sağlık ve kamu hizmetleri', 'Y11_Q53c', 'Ülkenizdeki toplu taşıma hizmetlerinin kalitesini nasıl değerlendirirsiniz?'],
		['Sağlık ve kamu hizmetleri', 'Y11_Q53d', 'Ülkenizdeki çocuk bakım hizmetlerinin kalitesini nasıl değerlendirirsiniz?'],
		['Sağlık ve kamu hizmetleri', 'Y11_Q53g', 'Ülkenizdeki devlet emekliliği sisteminin kalitesini nasıl değerlendirirsiniz?'],
		['Sosyal dışlanma ve topluluğa katılım', 'Y11_Q23a', 'Son 12 ayda bir sendika, politik parti veya hareket grubunun toplantısına katıldı'],
		['Sosyal dışlanma ve topluluğa katılım', 'Y11_Q23d', 'Bir politikacı ya da kamu görevlisi ile temas kurdu (kamu hizmetleri yoluyla gerçekleşen rutin temaslar hariç)'],
		['Sosyal dışlanma ve topluluğa katılım', 'Y11_Q29e', 'Toplumdan dışlanmış hissediyorum'],
		['Sosyal dışlanma ve topluluğa katılım', 'Y11_Q29f', 'Hayat öyle karmaşık hale geldi ki neredeyse başa çıkamıyorum'],
		['Sosyal dışlanma ve topluluğa katılım', 'Y11_Q29g', 'Yaptığım şeyin değerinin başkaları tarafından anlaşılmadığını düşünüyorum'],
		['Sosyal dışlanma ve topluluğa katılım', 'Y11_Q29h', 'Bazı insanlar iş durumum ya da gelirim nedeniyle beni hor görüyor'],
		['Sosyal dışlanma ve topluluğa katılım', 'Y11_SocExIndex', 'Sosyal Dışlanma Endeksi'],
		['Subjektif refah', 'Y11_Q29a', 'Gelecek konusunda iyimserim'],
		['Subjektif refah', 'Y11_Q30', 'Bu günlerde hayatınızdan ne kadar memnunsunuz?'],
		['Subjektif refah', 'Y11_Q40a', 'Eğitim ile ilgili memnuniyet'],
		['Subjektif refah', 'Y11_Q40b', 'Mevcut iş ile ilgili memnuniyet'],
		['Subjektif refah', 'Y11_Q40c', 'Mevcut yaşam standardı ile ilgili memnuniyet'],
		['Subjektif refah', 'Y11_Q40d', 'Barınma ile ilgili memnuniyet'],
		['Subjektif refah', 'Y11_Q40e', 'Aile hayatı ile ilgili memnuniyet'],
		['Subjektif refah', 'Y11_Q40f', 'Sağlık ile ilgili memnuniyet'],
		['Subjektif refah', 'Y11_Q40g', 'Sosyal yaşam ile ilgili memnuniyet'],
		['Subjektif refah', 'Y11_Q41', 'Tüm bunları göz önüne alarak, ne kadar mutlu olduğunuzu söylersiniz?'],
		['Toplum kalitesi', 'Y11_Q24', 'Sizce insanların çoğuna güvenilebilir mi yoksa insanlara karşı daima şüpheci olmak mı gerekir?'],
		['Toplum kalitesi', 'Y11_Q25a', 'Fakirler ve zenginler arasında algılanan gerilim'],
		['Toplum kalitesi', 'Y11_Q25b', 'Yöneticiler ve çalışanlar arasında algılanan gerilim'],
		['Toplum kalitesi', 'Y11_Q25c', 'Kadınlar ve erkekler arasında algılanan gerilim'],
		['Toplum kalitesi', 'Y11_Q25d', 'Yaşlılar ve gençler arasında algılanan gerilim'],
		['Toplum kalitesi', 'Y11_Q25e', 'Irkları ve etnik kökenleri farklı gruplar arasında algılanan gerilim'],
		['Toplum kalitesi', 'Y11_Q25f', 'Dini gruplar arasında algılanan gerilim'],
		['Toplum kalitesi', 'Y11_Q28a', 'Meclise duyulan güven'],
		['Toplum kalitesi', 'Y11_Q28b', 'Hukuk sistemine duyulan güven'],
		['Toplum kalitesi', 'Y11_Q28c', 'Basına duyulan güven'],
		['Toplum kalitesi', 'Y11_Q28d', 'Polise duyulan güven'],
		['Toplum kalitesi', 'Y11_Q28e', 'Hükümete duyulan güven'],
		['İstihdam ve iş-yaşam dengesi', 'Y11_Q12a', 'İşten eve ev işlerini yapamayacak kadar yorgun geldim'],
		['İstihdam ve iş-yaşam dengesi', 'Y11_Q12b', 'İşte geçirdiğim süre nedeniyle ailevi sorumluluklarımı yerine getirmek zor oldu'],
		['İstihdam ve iş-yaşam dengesi', 'Y11_Q12c', 'Ailevi sorumluluklar nedeniyle işe konsantre olmakta zorlandım'],
		['İstihdam ve iş-yaşam dengesi', 'Y11_Q15', 'Önümüzdeki 6 ay içinde işinizi kaybetme olasılığınız nedir?'],
		['İstihdam ve iş-yaşam dengesi', 'Y11_Q36b', 'Ne sıklıkla ev işleri yapıyor ya da yemek pişiriyorsunuz?'],
		['İstihdam ve iş-yaşam dengesi', 'Y11_Q36c', 'Yaşlı ya da engelli akrabalarınızla ne sıklıkla ilgileniyorsunuz?'],
		['İstihdam ve iş-yaşam dengesi', 'Y11_Q38', 'Ev işlerinin paylaşımına dair tutum'],
		['İstihdam ve iş-yaşam dengesi', 'Y11_Q39d_stress', 'Stres']
	];
var question_
	 = [
	
		['Y11_Accommproblems', 'Barınma sorunlarının sayısı'],
		['Y11_Q18', 'Ev sahibi olma'],
		['Y11_Q19a', 'Barınmayla ilgili sorunlar: Yer darlığı'],
		['Y11_Q19b', 'Barınmayla ilgili sorunlar: Pencerelerde, kapılarda veya zeminde çürüme'],
		['Y11_Q19c', 'Barınmayla ilgili sorunlar: Duvarlarda ya da çatıda akıntı'],
		['Y11_Q19d', 'Barınmayla ilgili sorunlar: Ev içinde çalışır bir tuvalet olmaması'],
		['Y11_Q19e', 'Barınmayla ilgili sorunlar: Küvet veya duş olmaması'],
		['Y11_Q19f', 'Barınmayla ilgili sorunlar: Dışarıda oturacak yer olmaması'],
		['Y11_Q20', 'Önümüzdeki 6 ay içinde maddi olarak karşılayamadığınız için evinizden ayrılmanız ne derece muhtemel?'],
		['Y11_Deprindex', 'Yoksunluk endeksi: Hanenin karşılayamadığı öğelerin sayısı'],
		['Y11_Q58', 'Haneniz geçinebiliyor mu?'],
		['Y11_Q59a', 'Evinizi yeterince sıcak tutabiliyor musunuz?'],
		['Y11_Q59b', 'Ev dışında yılda bir hafta tatil yapma masrafını karşılayabiliyor musunuz?'],
		['Y11_Q59c', 'Eskimiş mobilyanızı yenileyebiliyor musunuz?'],
		['Y11_Q59d', '(İstediğiniz takdirde) her iki günde bir et, tavuk ya da balık içeren bir öğün yiyebiliyor musunuz?'],
		['Y11_Q59e', 'İkinci el yerine yeni kıyafetler alabiliyor musunuz?'],
		['Y11_Q59f', 'Ayda en az bir kez arkadaşlarınızı ya da ailenizi bir şey içmek ya da yemek yemek için ağırlayabiliyor musunuz?'],
		['Y11_Q60a', 'Hanenizin son 12 ay içinde ödenmemiş kira ya da mortgage borcu oldu mu?'],
		['Y11_Q60b', 'Hanenizin son 12 ay içinde ödenmemiş elektrik, su, doğalgaz borcu oldu mu?'],
		['Y11_Q42', 'Algılanan sağlık durumu'],
		['Y11_Q46d_WHO5', 'WHO-5 ruhsal sağlık ölçeği'],
		['Y11_Q47a', 'Uzaklık nedeniyle doktora görünmek zor'],
		['Y11_Q47b', 'Randevu alımında gecikme nedeniyle doktora görünmek zor'],
		['Y11_Q47c', 'Randevu günü beklenen süre nedeniyle doktora görünmek zor'],
		['Y11_Q47d', 'Ücret nedeniyle doktora görünmek zor'],
		['Y11_Q53a', 'Ülkenizdeki sağlık hizmetlerinin kalitesini nasıl değerlendirirsiniz?'],
		['Y11_Q53b', 'Ülkenizdeki eğitim sisteminin kalitesini nasıl değerlendirirsiniz?'],
		['Y11_Q53c', 'Ülkenizdeki toplu taşıma hizmetlerinin kalitesini nasıl değerlendirirsiniz?'],
		['Y11_Q53d', 'Ülkenizdeki çocuk bakım hizmetlerinin kalitesini nasıl değerlendirirsiniz?'],
		['Y11_Q53g', 'Ülkenizdeki devlet emekliliği sisteminin kalitesini nasıl değerlendirirsiniz?'],
		['Y11_Q23a', 'Son 12 ayda bir sendika, politik parti veya hareket grubunun toplantısına katıldı'],
		['Y11_Q23d', 'Bir politikacı ya da kamu görevlisi ile temas kurdu (kamu hizmetleri yoluyla gerçekleşen rutin temaslar hariç)'],
		['Y11_Q29e', 'Toplumdan dışlanmış hissediyorum'],
		['Y11_Q29f', 'Hayat öyle karmaşık hale geldi ki neredeyse başa çıkamıyorum'],
		['Y11_Q29g', 'Yaptığım şeyin değerinin başkaları tarafından anlaşılmadığını düşünüyorum'],
		['Y11_Q29h', 'Bazı insanlar iş durumum ya da gelirim nedeniyle beni hor görüyor'],
		['Y11_SocExIndex', 'Sosyal Dışlanma Endeksi'],
		['Y11_Q29a', 'Gelecek konusunda iyimserim'],
		['Y11_Q30', 'Bu günlerde hayatınızdan ne kadar memnunsunuz?'],
		['Y11_Q40a', 'Eğitim ile ilgili memnuniyet'],
		['Y11_Q40b', 'Mevcut iş ile ilgili memnuniyet'],
		['Y11_Q40c', 'Mevcut yaşam standardı ile ilgili memnuniyet'],
		['Y11_Q40d', 'Barınma ile ilgili memnuniyet'],
		['Y11_Q40e', 'Aile hayatı ile ilgili memnuniyet'],
		['Y11_Q40f', 'Sağlık ile ilgili memnuniyet'],
		['Y11_Q40g', 'Sosyal yaşam ile ilgili memnuniyet'],
		['Y11_Q41', 'Tüm bunları göz önüne alarak, ne kadar mutlu olduğunuzu söylersiniz?'],
		['Y11_Q24', 'Sizce insanların çoğuna güvenilebilir mi yoksa insanlara karşı daima şüpheci olmak mı gerekir?'],
		['Y11_Q25a', 'Fakirler ve zenginler arasında algılanan gerilim'],
		['Y11_Q25b', 'Yöneticiler ve çalışanlar arasında algılanan gerilim'],
		['Y11_Q25c', 'Kadınlar ve erkekler arasında algılanan gerilim'],
		['Y11_Q25d', 'Yaşlılar ve gençler arasında algılanan gerilim'],
		['Y11_Q25e', 'Irkları ve etnik kökenleri farklı gruplar arasında algılanan gerilim'],
		['Y11_Q25f', 'Dini gruplar arasında algılanan gerilim'],
		['Y11_Q28a', 'Meclise duyulan güven'],
		['Y11_Q28b', 'Hukuk sistemine duyulan güven'],
		['Y11_Q28c', 'Basına duyulan güven'],
		['Y11_Q28d', 'Polise duyulan güven'],
		['Y11_Q28e', 'Hükümete duyulan güven'],
		['Y11_Q12a', 'İşten eve ev işlerini yapamayacak kadar yorgun geldim'],
		['Y11_Q12b', 'İşte geçirdiğim süre nedeniyle ailevi sorumluluklarımı yerine getirmek zor oldu'],
		['Y11_Q12c', 'Ailevi sorumluluklar nedeniyle işe konsantre olmakta zorlandım'],
		['Y11_Q15', 'Önümüzdeki 6 ay içinde işinizi kaybetme olasılığınız nedir?'],
		['Y11_Q36b', 'Ne sıklıkla ev işleri yapıyor ya da yemek pişiriyorsunuz?'],
		['Y11_Q36c', 'Yaşlı ya da engelli akrabalarınızla ne sıklıkla ilgileniyorsunuz?'],
		['Y11_Q38', 'Ev işlerinin paylaşımına dair tutum'],
		['Y11_Q39d_stress', 'Stres']
	];
var question_answer
	 = [
	
		['Y11_Accommproblems', 'Mean', 'Ortalama'],
		['Y11_Deprindex', 'Mean', 'Ortalama'],
		['Y11_Q12a', '1--Several-times-a-week', 'Haftada birkaç kez'],
		['Y11_Q12a', '2--Several-times-a-month', 'Ayda birkaç kez'],
		['Y11_Q12a', '3--Several-times-a-year', 'Yılda birkaç kez'],
		['Y11_Q12a', '4--Less-often-rarely', 'Daha az sıklıkla ya da nadir'],
		['Y11_Q12a', '5--Never', 'Asla'],
		['Y11_Q12b', '1--Several-times-a-week', 'Haftada birkaç kez'],
		['Y11_Q12b', '2--Several-times-a-month', 'Ayda birkaç kez'],
		['Y11_Q12b', '3--Several-times-a-year', 'Yılda birkaç kez'],
		['Y11_Q12b', '4--Less-often-rarely', 'Daha az sıklıkla ya da nadir'],
		['Y11_Q12b', '5--Never', 'Asla'],
		['Y11_Q12c', '1--Several-times-a-week', 'Haftada birkaç kez'],
		['Y11_Q12c', '2--Several-times-a-month', 'Ayda birkaç kez'],
		['Y11_Q12c', '3--Several-times-a-year', 'Yılda birkaç kez'],
		['Y11_Q12c', '4--Less-often-rarely', 'Daha az sıklıkla ya da nadir'],
		['Y11_Q12c', '5--Never', 'Asla'],
		['Y11_Q15', '1--Very-likely', 'Çok muhtemel'],
		['Y11_Q15', '2--Quite-likely', 'Oldukça muhtemel'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Ne muhtemel ne değil'],
		['Y11_Q15', '4--Quite-unlikely', 'Pek muhtemel değil'],
		['Y11_Q15', '5--Very-unlikely', 'Hiç muhtemel değil'],
		['Y11_Q18', '1--Own-without-mortgage', 'Mortgage olmadan kendine ait'],
		['Y11_Q18', '2--Own-with-mortgage', 'Mortgage ile kendine ait'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Kiracı, sosyal yardım kurumu veya gönüllü yardım kurumu veya belediyeye kira ödüyor'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Kiracı, ev sahibine kira ödüyor'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Kira ödemeden oturuyor'],
		['Y11_Q18', '6--Other', 'Diğer'],
		['Y11_Q19a', '1--Yes', 'Evet'],
		['Y11_Q19a', '2--No', 'Hayır'],
		['Y11_Q19b', '1--Yes', 'Evet'],
		['Y11_Q19b', '2--No', 'Hayır'],
		['Y11_Q19c', '1--Yes', 'Evet'],
		['Y11_Q19c', '2--No', 'Hayır'],
		['Y11_Q19d', '1--Yes', 'Evet'],
		['Y11_Q19d', '2--No', 'Hayır'],
		['Y11_Q19e', '1--Yes', 'Evet'],
		['Y11_Q19e', '2--No', 'Hayır'],
		['Y11_Q19f', '1--Yes', 'Evet'],
		['Y11_Q19f', '2--No', 'Hayır'],
		['Y11_Q20', '1--Very-likely', 'Çok muhtemel'],
		['Y11_Q20', '2--Quite-likely', 'Oldukça muhtemel'],
		['Y11_Q20', '3--Quite-unlikely', 'Ne muhtemel ne değil'],
		['Y11_Q20', '4--Very-unlikely', 'Pek muhtemel değil'],
		['Y11_Q23a', '1--Yes', 'Evet'],
		['Y11_Q23a', '2--No', 'Hayır'],
		['Y11_Q23d', '1--Yes', 'Evet'],
		['Y11_Q23d', '2--No', 'Hayır'],
		['Y11_Q24', 'Mean', 'Ortalama'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Çok fazla gerilim var'],
		['Y11_Q25a', '2--Some-tension', 'Biraz gerilim var'],
		['Y11_Q25a', '3--No-tension', 'Gerilim yok'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Çok fazla gerilim var'],
		['Y11_Q25b', '2--Some-tension', 'Biraz gerilim var'],
		['Y11_Q25b', '3--No-tension', 'Gerilim yok'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Çok fazla gerilim var'],
		['Y11_Q25c', '2--Some-tension', 'Biraz gerilim var'],
		['Y11_Q25c', '3--No-tension', 'Gerilim yok'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Çok fazla gerilim var'],
		['Y11_Q25d', '2--Some-tension', 'Biraz gerilim var'],
		['Y11_Q25d', '3--No-tension', 'Gerilim yok'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Çok fazla gerilim var'],
		['Y11_Q25e', '2--Some-tension', 'Biraz gerilim var'],
		['Y11_Q25e', '3--No-tension', 'Gerilim yok'],
		['Y11_Q25f', '1--A-lot-of--tension', 'Çok fazla gerilim var'],
		['Y11_Q25f', '2--Some-tension', 'Biraz gerilim var'],
		['Y11_Q25f', '3--No-tension', 'Gerilim yok'],
		['Y11_Q28a', 'Mean', 'Ortalama'],
		['Y11_Q28b', 'Mean', 'Ortalama'],
		['Y11_Q28c', 'Mean', 'Ortalama'],
		['Y11_Q28d', 'Mean', 'Ortalama'],
		['Y11_Q28e', 'Mean', 'Ortalama'],
		['Y11_Q29a', '1--Strongly-agree', 'Kesinlikle katılıyorum'],
		['Y11_Q29a', '2--Agree', 'Katılıyorum'],
		['Y11_Q29a', '3--Neither-agree-nor-disagree', 'Ne katılıyorum ne katılmıyorum'],
		['Y11_Q29a', '4--Disagree', 'Katılmıyorum'],
		['Y11_Q29a', '5--Strongly-disagree', 'Kesinlikle katılmıyorum'],
		['Y11_Q29e', '1--Strongly-agree', 'Kesinlikle katılıyorum'],
		['Y11_Q29e', '2--Agree', 'Katılıyorum'],
		['Y11_Q29e', '3--Neither-agree-nor-disagree', 'Ne katılıyorum ne katılmıyorum'],
		['Y11_Q29e', '4--Disagree', 'Katılmıyorum'],
		['Y11_Q29e', '5--Strongly-disagree', 'Kesinlikle katılmıyorum'],
		['Y11_Q29f', '1--Strongly-agree', 'Kesinlikle katılıyorum'],
		['Y11_Q29f', '2--Agree', 'Katılıyorum'],
		['Y11_Q29f', '3--Neither-agree-nor-disagree', 'Ne katılıyorum ne katılmıyorum'],
		['Y11_Q29f', '4--Disagree', 'Katılmıyorum'],
		['Y11_Q29f', '5--Strongly-disagree', 'Kesinlikle katılmıyorum'],
		['Y11_Q29g', '1--Strongly-agree', 'Kesinlikle katılıyorum'],
		['Y11_Q29g', '2--Agree', 'Katılıyorum'],
		['Y11_Q29g', '3--Neither-agree-nor-disagree', 'Ne katılıyorum ne katılmıyorum'],
		['Y11_Q29g', '4--Disagree', 'Katılmıyorum'],
		['Y11_Q29g', '5--Strongly-disagree', 'Kesinlikle katılmıyorum'],
		['Y11_Q29h', '1--Strongly-agree', 'Kesinlikle katılıyorum'],
		['Y11_Q29h', '2--Agree', 'Katılıyorum'],
		['Y11_Q29h', '3--Neither-agree-nor-disagree', 'Ne katılıyorum ne katılmıyorum'],
		['Y11_Q29h', '4--Disagree', 'Katılmıyorum'],
		['Y11_Q29h', '5--Strongly-disagree', 'Kesinlikle katılmıyorum'],
		['Y11_Q30', 'Mean', 'Ortalama'],
		['Y11_Q36b', '1--Every-day', 'Her gün'],
		['Y11_Q36b', '2--Several-days-a-week', 'Haftada birkaç kez'],
		['Y11_Q36b', '3--Once-or-twice-a-week', 'Haftada bir ya da iki kez'],
		['Y11_Q36b', '4--Less-often', 'Daha az sıklıkla'],
		['Y11_Q36b', '5--Never', 'Asla'],
		['Y11_Q36c', '1--Every-day', 'Her gün'],
		['Y11_Q36c', '2--Several-days-a-week', 'Haftada birkaç kez'],
		['Y11_Q36c', '3--Once-or-twice-a-week', 'Haftada bir ya da iki kez'],
		['Y11_Q36c', '4--Less-often', 'Daha az sıklıkla'],
		['Y11_Q36c', '5--Never', 'Asla'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Adil olarak payınıza düşmesi gerekenden fazla'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Adil olarak payınıza düşmesi gereken kadar'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Adil olarak payınıza düşmesi gerekenden az'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'Evde ve işte'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'İşte veya evde'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Stres az ya da hiç yok'],
		['Y11_Q40a', 'Mean', 'Ortalama'],
		['Y11_Q40b', 'Mean', 'Ortalama'],
		['Y11_Q40c', 'Mean', 'Ortalama'],
		['Y11_Q40d', 'Mean', 'Ortalama'],
		['Y11_Q40e', 'Mean', 'Ortalama'],
		['Y11_Q40f', 'Mean', 'Ortalama'],
		['Y11_Q40g', 'Mean', 'Ortalama'],
		['Y11_Q41', 'Mean', 'Ortalama'],
		['Y11_Q42', '1--Very-good', 'Çok iyi'],
		['Y11_Q42', '2--Good', 'İyi'],
		['Y11_Q42', '3--Fair', 'Fena değil'],
		['Y11_Q42', '4--Bad', 'Kötü'],
		['Y11_Q42', '5--Very-bad', 'Çok kötü'],
		['Y11_Q46d_WHO5', 'Mean', 'Ortalama'],
		['Y11_Q47a', '1--Very-difficult', 'Çok zor'],
		['Y11_Q47a', '2--A-little-difficult', 'Biraz zor'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Hiç zor değil'],
		['Y11_Q47b', '1--Very-difficult', 'Çok zor'],
		['Y11_Q47b', '2--A-little-difficult', 'Biraz zor'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Hiç zor değil'],
		['Y11_Q47c', '1--Very-difficult', 'Çok zor'],
		['Y11_Q47c', '2--A-little-difficult', 'Biraz zor'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Hiç zor değil'],
		['Y11_Q47d', '1--Very-difficult', 'Çok zor'],
		['Y11_Q47d', '2--A-little-difficult', 'Biraz zor'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Hiç zor değil'],
		['Y11_Q53a', 'Mean', 'Ortalama'],
		['Y11_Q53b', 'Mean', 'Ortalama'],
		['Y11_Q53c', 'Mean', 'Ortalama'],
		['Y11_Q53d', 'Mean', 'Ortalama'],
		['Y11_Q53g', 'Mean', 'Ortalama'],
		['Y11_Q58', '1--With-great-difficulty', 'Çok büyük zorlukla'],
		['Y11_Q58', '2--With-difficulty', 'Zorlukla'],
		['Y11_Q58', '3--With-some-difficulty', 'Biraz zorlukla'],
		['Y11_Q58', '4--Fairly-easily', 'Biraz kolaylıkla'],
		['Y11_Q58', '5--Easily', 'Kolaylıkla'],
		['Y11_Q58', '6--Very-easily', 'Çok kolaylıkla'],
		['Y11_Q59a', '1--No', 'Hayır'],
		['Y11_Q59a', '2--Yes', 'Evet'],
		['Y11_Q59b', '1--No', 'Hayır'],
		['Y11_Q59b', '2--Yes', 'Evet'],
		['Y11_Q59c', '1--No', 'Hayır'],
		['Y11_Q59c', '2--Yes', 'Evet'],
		['Y11_Q59d', '1--No', 'Hayır'],
		['Y11_Q59d', '2--Yes', 'Evet'],
		['Y11_Q59e', '1--No', 'Hayır'],
		['Y11_Q59e', '2--Yes', 'Evet'],
		['Y11_Q59f', '1--No', 'Hayır'],
		['Y11_Q59f', '2--Yes', 'Evet'],
		['Y11_Q60a', '1--Yes', 'Evet'],
		['Y11_Q60a', '2--No', 'Hayır'],
		['Y11_Q60b', '1--Yes', 'Evet'],
		['Y11_Q60b', '2--No', 'Hayır'],
		['Y11_SocExIndex', 'Mean', 'Ortalama']
	];
var country_
	 = [
	
		['AT', 'Avusturya'],
		['BE', 'Belçika'],
		['BG', 'Bulgaristan'],
		['CY', 'Kıbrıs'],
		['CZ', 'Çek Cumhuriyeti'],
		['DE', 'Almanya'],
		['DK', 'Danimarka'],
		['EE', 'Estonya'],
		['EL', 'Yunanistan'],
		['ES', 'İspanya'],
		['FI', 'Finlandiya'],
		['FR', 'Fransa'],
		['HR', 'Hırvatistan'],
		['HU', 'Macaristan'],
		['IE', 'İrlanda'],
		['IT', 'İtalya'],
		['LT', 'Litvanya'],
		['LU', 'Lüksemburg'],
		['LV', 'Letonya'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Hollanda'],
		['NO', 'Norveç'],
		['PL', 'Polonya'],
		['PT', 'Portekiz'],
		['RO', 'Romanya'],
		['SE', 'İsveç'],
		['SI', 'Slovenya'],
		['SK', 'Slovakya'],
		['TR', 'Türkiye'],
		['UK', 'Birleşik Krallık'],
		['EuropeanUnion', 'Avrupa Birliği']
	];
var question_meta
	 = [
	
		['Y11_Accommproblems', 'Barınma sorunlarının sayısı', ''],
		['Y11_Q18', 'Ev sahibi olma', ''],
		['Y11_Q19a', 'Barınmayla ilgili sorunlar: Yer darlığı', ''],
		['Y11_Q19b', 'Barınmayla ilgili sorunlar: Pencerelerde, kapılarda veya zeminde çürüme', ''],
		['Y11_Q19c', 'Barınmayla ilgili sorunlar: Duvarlarda ya da çatıda akıntı', ''],
		['Y11_Q19d', 'Barınmayla ilgili sorunlar: Ev içinde çalışır bir tuvalet olmaması', ''],
		['Y11_Q19e', 'Barınmayla ilgili sorunlar: Küvet veya duş olmaması', ''],
		['Y11_Q19f', 'Barınmayla ilgili sorunlar: Dışarıda oturacak yer olmaması', ''],
		['Y11_Q20', 'Önümüzdeki 6 ay içinde maddi olarak karşılayamadığınız için evinizden ayrılmanız ne derece muhtemel?', ''],
		['Y11_Deprindex', 'Yoksunluk endeksi: Hanenin karşılayamadığı öğelerin sayısı', ''],
		['Y11_Q58', 'Haneniz geçinebiliyor mu?', ''],
		['Y11_Q59a', 'Evinizi yeterince sıcak tutabiliyor musunuz?', ''],
		['Y11_Q59b', 'Ev dışında yılda bir hafta tatil yapma masrafını karşılayabiliyor musunuz?', ''],
		['Y11_Q59c', 'Eskimiş mobilyanızı yenileyebiliyor musunuz?', ''],
		['Y11_Q59d', '(İstediğiniz takdirde) her iki günde bir et, tavuk ya da balık içeren bir öğün yiyebiliyor musunuz?', ''],
		['Y11_Q59e', 'İkinci el yerine yeni kıyafetler alabiliyor musunuz?', ''],
		['Y11_Q59f', 'Ayda en az bir kez arkadaşlarınızı ya da ailenizi bir şey içmek ya da yemek yemek için ağırlayabiliyor musunuz?', ''],
		['Y11_Q60a', 'Hanenizin son 12 ay içinde ödenmemiş kira ya da mortgage borcu oldu mu?', ''],
		['Y11_Q60b', 'Hanenizin son 12 ay içinde ödenmemiş elektrik, su, doğalgaz borcu oldu mu?', ''],
		['Y11_Q42', 'Algılanan sağlık durumu', ''],
		['Y11_Q46d_WHO5', 'WHO-5 ruhsal sağlık ölçeği', ''],
		['Y11_Q47a', 'Uzaklık nedeniyle doktora görünmek zor', ''],
		['Y11_Q47b', 'Randevu alımında gecikme nedeniyle doktora görünmek zor', ''],
		['Y11_Q47c', 'Randevu günü beklenen süre nedeniyle doktora görünmek zor', ''],
		['Y11_Q47d', 'Doktoru görmek için verilecek ücret nedeniyle doktora görünmek zor', ''],
		['Y11_Q53a', 'Ülkenizdeki sağlık hizmetlerinin kalitesini nasıl değerlendirirsiniz?', ''],
		['Y11_Q53b', 'Ülkenizdeki eğitim sisteminin kalitesini nasıl değerlendirirsiniz?', ''],
		['Y11_Q53c', 'Ülkenizdeki toplu taşıma hizmetlerinin kalitesini nasıl değerlendirirsiniz?', ''],
		['Y11_Q53d', 'Ülkenizdeki çocuk bakım hizmetlerinin kalitesini nasıl değerlendirirsiniz?', ''],
		['Y11_Q53g', 'Ülkenizdeki devlet emekliliği sisteminin kalitesini nasıl değerlendirirsiniz?', ''],
		['Y11_Q23a', 'Son 12 ayda bir sendika, politik parti veya hareket grubunun toplantısına katıldı', ''],
		['Y11_Q23d', 'Bir politikacı ya da kamu görevlisi ile temas kurdu (kamu hizmetleri yoluyla gerçekleşen rutin temaslar hariç)', ''],
		['Y11_Q29e', 'Toplumdan dışlanmış hissediyorum', ''],
		['Y11_Q29f', 'Hayat öyle karmaşık hale geldi ki neredeyse başa çıkamıyorum', ''],
		['Y11_Q29g', 'Yaptığım şeyin değerinin başkaları tarafından anlaşılmadığını düşünüyorum', ''],
		['Y11_Q29h', 'Bazı insanlar iş durumum ya da gelirim nedeniyle beni hor görüyor', ''],
		['Y11_SocExIndex', 'Sosyal Dışlanma Endeksi', ''],
		['Y11_Q29a', 'Gelecek konusunda iyimserim', ''],
		['Y11_Q30', 'Bu günlerde hayatınızdan ne kadar memnunsunuz?', ''],
		['Y11_Q40a', 'Eğitim ile ilgili memnuniyet', ''],
		['Y11_Q40b', 'Mevcut iş ile ilgili memnuniyet', ''],
		['Y11_Q40c', 'Mevcut yaşam standardı ile ilgili memnuniyet', ''],
		['Y11_Q40d', 'Barınma ile ilgili memnuniyet', ''],
		['Y11_Q40e', 'Aile hayatı ile ilgili memnuniyet', ''],
		['Y11_Q40f', 'Sağlık ile ilgili memnuniyet', ''],
		['Y11_Q40g', 'Sosyal yaşam ile ilgili memnuniyet', ''],
		['Y11_Q41', 'Tüm bunları göz önüne alarak, ne kadar mutlu olduğunuzu söylersiniz?', ''],
		['Y11_Q24', 'Sizce insanların çoğuna güvenilebilir mi yoksa insanlara karşı daima şüpheci olmak mı gerekir?', ''],
		['Y11_Q25a', 'Fakirler ve zenginler arasında algılanan gerilim', ''],
		['Y11_Q25b', 'Yöneticiler ve çalışanlar arasında algılanan gerilim', ''],
		['Y11_Q25c', 'Kadınlar ve erkekler arasında algılanan gerilim', ''],
		['Y11_Q25d', 'Yaşlılar ve gençler arasında algılanan gerilim', ''],
		['Y11_Q25e', 'Irkları ve etnik kökenleri farklı gruplar arasında algılanan gerilim', ''],
		['Y11_Q25f', 'Dini gruplar arasında algılanan gerilim', ''],
		['Y11_Q28a', 'Meclise duyulan güven', ''],
		['Y11_Q28b', 'Hukuk sistemine duyulan güven', ''],
		['Y11_Q28c', 'Basına duyulan güven', ''],
		['Y11_Q28d', 'Polise duyulan güven', ''],
		['Y11_Q28e', 'Hükümete duyulan güven', ''],
		['Y11_Q12a', 'İşten eve ev işlerini yapamayacak kadar yorgun geldim', ''],
		['Y11_Q12b', 'İşte geçirdiğim süre nedeniyle ailevi sorumluluklarımı yerine getirmek zor oldu', ''],
		['Y11_Q12c', 'Ailevi sorumluluklar nedeniyle işe konsantre olmakta zorlandım', ''],
		['Y11_Q15', 'Önümüzdeki 6 ay içinde işinizi kaybetme olasılığınız nedir?', ''],
		['Y11_Q36b', 'Ne sıklıkla ev işleri yapıyor ya da yemek pişiriyorsunuz?', ''],
		['Y11_Q36c', 'Yaşlı ya da engelli akrabalarınızla ne sıklıkla ilgileniyorsunuz?', ''],
		['Y11_Q38', 'Ev işlerinden payınıza düşenler hakkında ne düşünüyorsunuz?', ''],
		['Y11_Q39d_stress', 'İş-yaşam dengesi sorunları nedeniyle stres', '']
	];
