//Auto Generated file
var subset_
	 = [
	
		['Sectorgrp', 'Activity sector'],
		['Size', 'Establishment size']
	];
var subset_subsetValue
	 = [
	
		['Sectorgrp', 'All', 'All'],
		['Sectorgrp', '1--A', 'Agriculture, forestry and fishing'],
		['Sectorgrp', '2--BDEF', 'Construction, waste management, water and electricity supply'],
		['Sectorgrp', '3--C', 'Manufacturing'],
		['Sectorgrp', '4--GHIR', 'Trade, transport, food/accommodation and recreation activities'],
		['Sectorgrp', '5--JKLMNS', 'IT, Finance, Real estate and other technical scientific or personal service activities'],
		['Sectorgrp', '6--O', 'Public administration'],
		['Sectorgrp', '7--PQ', 'Education, human health and social work activities'],
		['Size', 'All', 'All'],
		['Size', '1--5-to-9', '5 to 9 employees'],
		['Size', '2--10-to-49', '10 to 49 employees'],
		['Size', '3--50-249', '50 to 249 employees'],
		['Size', '4--250-', '250 or more employees']
	];
var topic_
	 = [
	
		['', 'All (108)'],
		['Drivers and barriers', 'Drivers and barriers (17)'],
		['Employee participation', 'Employee participation (10)'],
		['Key findings', 'Key findings (24)'],
		['OSH Management', 'OSH Management (60)'],
		['Psychosocial risks and their management', 'Psychosocial risks and their management (21)']
	];
var topic_question
	 = [
	
		['Key findings', 'Q200_1', 'Risk factors present in the establishment: Tiring or painful positions'],
		['Key findings', 'Q200_2', 'Risk factors present in the establishment: Lifting or moving people or heavy loads'],
		['Key findings', 'Q200_3', 'Risk factors present in the establishment: Loud noise'],
		['Key findings', 'Q200_4', 'Risk factors present in the establishment: Repetitive hand or arm movements'],
		['Key findings', 'Q200_5', 'Risk factors present in the establishment: Heat, cold or draught'],
		['Key findings', 'Q200_6', 'Risk factors present in the establishment: Risk of accidents with machines'],
		['Key findings', 'Q200_7', 'Risk factors present in the establishment: Risk of accidents with vehicles in the course of work'],
		['Key findings', 'Q200_8', 'Risk factors present in the establishment: Chemical or biological substances'],
		['Key findings', 'Q200_9', 'Risk factors present in the establishment: Increased risk of slips, trips and falls'],
		['Key findings', 'Q201_1', 'Psychosocial risk factors present in the establishment: Pressure due to time constraints'],
		['Key findings', 'Q201_2', 'Psychosocial risk factors present in the establishment: Poor communication or cooperation'],
		['Key findings', 'Q201_3', 'Psychosocial risk factors present in the establishment: Employees’ lack of influence'],
		['Key findings', 'Q201_4', 'Psychosocial risk factors present in the establishment: Fear of being made redundant'],
		['Key findings', 'Q201_5', 'Psychosocial risk factors present in the establishment: Difficult customers, patients, pupils'],
		['Key findings', 'Q201_6', 'Psychosocial risk factors present in the establishment: Long or irregular working hours'],
		['Key findings', 'Q201_7', 'Psychosocial risk factors present in the establishment: Discrimination'],
		['Key findings', 'Q250', 'Workplace risk assessments'],
		['Key findings', 'Q251', 'Risk assessments mainly conducted by internal staff or external service providers'],
		['Key findings', 'Q264_1', 'Reasons for addressing health and safety in the establishment: Fulfilling a legal obligation'],
		['Key findings', 'Q264_2', 'Reasons for addressing health and safety in the establishment: Meeting employee expectations'],
		['Key findings', 'Q264_4', 'Reasons for addressing health and safety in the establishment: Increasing productivity'],
		['Key findings', 'Q264_5', 'Reasons for addressing health and safety in the establishment: Organisation’s reputation'],
		['Key findings', 'Q264_6', 'Reasons for addressing health and safety in the establishment: Avoiding fines from Health and Safety Inspectors'],
		['Key findings', 'Q307', 'Sufficient information on how to include psychosocial risks in risk assessments'],
		['OSH Management', 'Q150_1', 'Use of health and safety services: An occupational health doctor'],
		['OSH Management', 'Q150_2', 'Use of health and safety services: A psychologist'],
		['OSH Management', 'Q150_3', 'Use of health and safety services: An expert dealing with the ergonomic design and set-up of workplaces'],
		['OSH Management', 'Q150_4', 'Use of health and safety services: A health and safety generalist'],
		['OSH Management', 'Q150_5', 'Use of health and safety services: An expert on accident prevention'],
		['OSH Management', 'Q155', 'Document explaining  responsibilities and procedures on health and safety is available to workers'],
		['OSH Management', 'Q156', 'A specific budget for health and safety measures and equipment set each year'],
		['OSH Management', 'Q158_1', 'Measures for health promotion among employees: Raising awareness of nutrition '],
		['OSH Management', 'Q158_2', 'Measures for health promotion among employees: Raising awareness about preventing addiction'],
		['OSH Management', 'Q158_3', 'Measures for health promotion among employees: Promoting sports activities outside of working hours'],
		['OSH Management', 'Q158_4', 'Measures for health promotion among employees: Promoting physical exercise at work'],
		['OSH Management', 'Q160', 'Routine analysis of absences due to sickness'],
		['OSH Management', 'Q165', 'Visit by the Health and Safety Authority in the last 3 years to check health and safety conditions'],
		['OSH Management', 'Q200_1', 'Risk factors present in the establishment: Tiring or painful positions'],
		['OSH Management', 'Q200_2', 'Risk factors present in the establishment: Lifting or moving people or heavy loads'],
		['OSH Management', 'Q200_3', 'Risk factors present in the establishment: Loud noise'],
		['OSH Management', 'Q200_4', 'Risk factors present in the establishment: Repetitive hand or arm movements'],
		['OSH Management', 'Q200_5', 'Risk factors present in the establishment: Heat, cold or draught'],
		['OSH Management', 'Q200_6', 'Risk factors present in the establishment: Risk of accidents with machines'],
		['OSH Management', 'Q200_7', 'Risk factors present in the establishment: Risk of accidents with vehicles in the course of work'],
		['OSH Management', 'Q200_8', 'Risk factors present in the establishment: Chemical or biological substances'],
		['OSH Management', 'Q200_9', 'Risk factors present in the establishment: Increased risk of slips, trips and falls'],
		['OSH Management', 'Q202_1', 'Lack of information or adequate tools to deal with the risk effectively: Tiring or painful positions'],
		['OSH Management', 'Q202_2', 'Lack of information or adequate tools to deal with the risk effectively: Lifting or moving people or heavy loads'],
		['OSH Management', 'Q202_3', 'Lack of information or adequate tools to deal with the risk effectively: Loud noise'],
		['OSH Management', 'Q202_4', 'Lack of information or adequate tools to deal with the risk effectively: Repetitive hand or arm movements'],
		['OSH Management', 'Q202_5', 'Lack of information or adequate tools to deal with the risk effectively: Heat, cold or draught'],
		['OSH Management', 'Q202_6', 'Lack of information or adequate tools to deal with the risk effectively: Risk of accidents with machines'],
		['OSH Management', 'Q202_7', 'Lack of information or adequate tools to deal with the risk effectively: Risk of accidents with vehicles in the course of work'],
		['OSH Management', 'Q202_8', 'Lack of information or adequate tools to deal with the risk effectively: Chemical or biological substances'],
		['OSH Management', 'Q202_9', 'Lack of information or adequate tools to deal with the risk effectively: Increased risk of slips, trips and falls'],
		['OSH Management', 'Q250', 'Workplace risk assessments'],
		['OSH Management', 'Q251', 'Risk assessments mainly conducted by internal staff or external service providers'],
		['OSH Management', 'Q252_1', 'Aspects evaluated in the workplace risk assessments: The safety of machines, equipment and installations'],
		['OSH Management', 'Q252_2', 'Aspects evaluated in the workplace risk assessments: Dangerous substances'],
		['OSH Management', 'Q252_3', 'Aspects evaluated in the workplace risk assessments: Working postures, physical working demands and repetitive movements'],
		['OSH Management', 'Q252_4', 'Aspects evaluated in the workplace risk assessments: Exposure to noise, vibrations, heat or cold'],
		['OSH Management', 'Q252_5', 'Aspects evaluated in the workplace risk assessments: Supervisor-employee relationships'],
		['OSH Management', 'Q252_6', 'Aspects evaluated in the workplace risk assessments: Organisational aspects'],
		['OSH Management', 'Q254gr', 'Year of last workplace risk assessment'],
		['OSH Management', 'Q255', 'Workplace risk assessment in a documented form'],
		['OSH Management', 'Q256_1', 'People provided with the findings of the workplace risk assessments: Management'],
		['OSH Management', 'Q256_2', 'People provided with the findings of the workplace risk assessments: Safety representatives'],
		['OSH Management', 'Q256_3', 'People provided with the findings of the workplace risk assessments: Statutory employee representation forum or another form of non-union staff association'],
		['OSH Management', 'Q256_4', 'People provided with the findings of the workplace risk assessments: Workplace union representatives'],
		['OSH Management', 'Q256_5', 'People provided with the findings of the workplace risk assessments: Employees themselves'],
		['OSH Management', 'Q259', 'Risk assessments regarded as a useful way of managing health and safety'],
		['OSH Management', 'Q261_1', 'Reasons why workplace risk assessments are not carried out on a regular basis: The dangers and risks are already known'],
		['OSH Management', 'Q261_2', 'Reasons why workplace risk assessments are not carried out on a regular basis: There are no major problems'],
		['OSH Management', 'Q261_3', 'Reasons why workplace risk assessments are not carried out on a regular basis: The procedure is too onerous'],
		['OSH Management', 'Q261_4', 'Reasons why workplace risk assessments are not carried out on a regular basis: The necessary expertise is lacking'],
		['OSH Management', 'Q308_1', 'Preventive measures regarding musculoskeletal problems: Equipment to help with the lifting or moving of loads'],
		['OSH Management', 'Q308_2', 'Preventive measures regarding musculoskeletal problems: Rotation of tasks to reduce physical strain'],
		['OSH Management', 'Q308_3', 'Preventive measures regarding musculoskeletal problems: Encouraging regular breaks for people in uncomfortable or static postures'],
		['OSH Management', 'Q308_4', 'Preventive measures regarding musculoskeletal problems: Provision of ergonomic equipment'],
		['OSH Management', 'Q356_1', 'Training for employees: Proper handling and adjustment of their work equipment and furniture'],
		['OSH Management', 'Q356_2', 'Training for employees: Use of dangerous substances'],
		['OSH Management', 'Q356_3', 'Training for employees: How to prevent psychosocial risks'],
		['OSH Management', 'Q356_4', 'Training for employees: How to lift and move heavy loads or people'],
		['OSH Management', 'Q356_5', 'Training for employees: Emergency procedures'],
		['Psychosocial risks and their management', 'Q201_1', 'Psychosocial risk factors present in the establishment: Pressure due to time constraints'],
		['Psychosocial risks and their management', 'Q201_2', 'Psychosocial risk factors present in the establishment: Poor communication or cooperation'],
		['Psychosocial risks and their management', 'Q201_3', 'Psychosocial risk factors present in the establishment: Employees’ lack of influence'],
		['Psychosocial risks and their management', 'Q201_4', 'Psychosocial risk factors present in the establishment: Fear of being made redundant'],
		['Psychosocial risks and their management', 'Q201_5', 'Psychosocial risk factors present in the establishment: Difficult customers, patients, pupils'],
		['Psychosocial risks and their management', 'Q201_6', 'Psychosocial risk factors present in the establishment: Long or irregular working hours'],
		['Psychosocial risks and their management', 'Q201_7', 'Psychosocial risk factors present in the establishment: Discrimination'],
		['Psychosocial risks and their management', 'Q202_10', 'Lack of information or adequate tools to deal with the risk effectively: Pressure due to time constraints'],
		['Psychosocial risks and their management', 'Q202_11', 'Lack of information or adequate tools to deal with the risk effectively: Poor communication or cooperation'],
		['Psychosocial risks and their management', 'Q202_12', 'Lack of information or adequate tools to deal with the risk effectively: Employees’ lack of influence'],
		['Psychosocial risks and their management', 'Q202_13', 'Lack of information or adequate tools to deal with the risk effectively: Fear of being made redundant'],
		['Psychosocial risks and their management', 'Q202_14', 'Lack of information or adequate tools to deal with the risk effectively: Difficult customers, patients, pupils'],
		['Psychosocial risks and their management', 'Q202_15', 'Lack of information or adequate tools to deal with the risk effectively: Long or irregular working hours'],
		['Psychosocial risks and their management', 'Q300', 'Action plan to prevent work-related stress'],
		['Psychosocial risks and their management', 'Q301', 'Procedures in place to deal with bullying or harassment'],
		['Psychosocial risks and their management', 'Q302', 'Procedure in place to deal with cases of threats, abuse or assault'],
		['Psychosocial risks and their management', 'Q303_1', 'Measures to prevent psychosocial risks in the last three years: Reorganisation of work in order to reduce job demands and work pressure '],
		['Psychosocial risks and their management', 'Q303_2', 'Measures to prevent psychosocial risks in the last three years: Confidential counselling for employees '],
		['Psychosocial risks and their management', 'Q303_3', 'Measures to prevent psychosocial risks in the last three years: Establishment of a conflict resolution procedure'],
		['Psychosocial risks and their management', 'Q303_4', 'Measures to prevent psychosocial risks in the last three years: Intervention if an employee works excessively long or irregular hours'],
		['Psychosocial risks and their management', 'Q307', 'Sufficient information on how to include psychosocial risks in risk assessments'],
		['Drivers and barriers', 'Q264_1', 'Reasons for addressing health and safety in the establishment: Fulfilling a legal obligation'],
		['Drivers and barriers', 'Q264_2', 'Reasons for addressing health and safety in the establishment: Meeting employee expectations'],
		['Drivers and barriers', 'Q264_4', 'Reasons for addressing health and safety in the establishment: Increasing productivity'],
		['Drivers and barriers', 'Q264_5', 'Reasons for addressing health and safety in the establishment: Organisation’s reputation'],
		['Drivers and barriers', 'Q264_6', 'Reasons for addressing health and safety in the establishment: Avoiding fines from Health and Safety Inspectors'],
		['Drivers and barriers', 'Q265_1', 'Main difficulties in addressing health and safety: A lack of time or staff'],
		['Drivers and barriers', 'Q265_2', 'Main difficulties in addressing health and safety: A lack of money'],
		['Drivers and barriers', 'Q265_3', 'Main difficulties in addressing health and safety: A lack of awareness among staff '],
		['Drivers and barriers', 'Q265_4', 'Main difficulties in addressing health and safety: A lack of awareness among management'],
		['Drivers and barriers', 'Q265_5', 'Main difficulties in addressing health and safety: A lack of expertise or specialist support'],
		['Drivers and barriers', 'Q265_6', 'Main difficulties in addressing health and safety: The paperwork'],
		['Drivers and barriers', 'Q265_7', 'Main difficulties in addressing health and safety: The complexity of legal obligations'],
		['Drivers and barriers', 'Q304', 'Measures triggered by actual problems'],
		['Drivers and barriers', 'Q306a_3', 'Difficulties in addressing psychosocial risks: A lack of awareness among staff'],
		['Drivers and barriers', 'Q306a_4', 'Difficulties in addressing psychosocial risks: A lack of awareness among management '],
		['Drivers and barriers', 'Q306a_5', 'Difficulties in addressing psychosocial risks: A lack of expertise or specialist support '],
		['Drivers and barriers', 'Q306a_6', 'Difficulties in addressing psychosocial risks: Reluctance to talk openly about these issues'],
		['Employee participation', 'Q166_1', 'Forms of employee representation: Statutory employee representation forum or another form of non-union staff association'],
		['Employee participation', 'Q166_2', 'Forms of employee representation: Workplace union representative'],
		['Employee participation', 'Q166_3', 'Forms of employee representation: Safety representative'],
		['Employee participation', 'Q166_4', 'Forms of employee representation: Safety committee'],
		['Employee participation', 'Q258b', 'Employees involved in the design of measures following a risk assessment'],
		['Employee participation', 'Q305', 'Employees have a role in the design of measures to prevent psychosocial risks'],
		['Employee participation', 'Q350', 'How often health and safety is discussed between employee representatives and management'],
		['Employee participation', 'Q351', 'How often controversies related to health and safety arise'],
		['Employee participation', 'Q354', 'Safety representatives provided with training during worktime'],
		['Employee participation', 'Q358', 'Health and safety issues discussed in staff or team meetings']
	];
var question_
	 = [
	
		['Q200_1', 'Risk factors present in the establishment: Tiring or painful positions'],
		['Q200_2', 'Risk factors present in the establishment: Lifting or moving people or heavy loads'],
		['Q200_3', 'Risk factors present in the establishment: Loud noise'],
		['Q200_4', 'Risk factors present in the establishment: Repetitive hand or arm movements'],
		['Q200_5', 'Risk factors present in the establishment: Heat, cold or draught'],
		['Q200_6', 'Risk factors present in the establishment: Risk of accidents with machines'],
		['Q200_7', 'Risk factors present in the establishment: Risk of accidents with vehicles in the course of work'],
		['Q200_8', 'Risk factors present in the establishment: Chemical or biological substances'],
		['Q200_9', 'Risk factors present in the establishment: Increased risk of slips, trips and falls'],
		['Q201_1', 'Psychosocial risk factors present in the establishment: Pressure due to time constraints'],
		['Q201_2', 'Psychosocial risk factors present in the establishment: Poor communication or cooperation'],
		['Q201_3', 'Psychosocial risk factors present in the establishment: Employees’ lack of influence'],
		['Q201_4', 'Psychosocial risk factors present in the establishment: Fear of being made redundant'],
		['Q201_5', 'Psychosocial risk factors present in the establishment: Difficult customers, patients, pupils'],
		['Q201_6', 'Psychosocial risk factors present in the establishment: Long or irregular working hours'],
		['Q201_7', 'Psychosocial risk factors present in the establishment: Discrimination'],
		['Q250', 'Workplace risk assessments'],
		['Q251', 'Risk assessments mainly conducted by internal staff or external service providers'],
		['Q264_1', 'Reasons for addressing health and safety in the establishment: Fulfilling a legal obligation'],
		['Q264_2', 'Reasons for addressing health and safety in the establishment: Meeting employee expectations'],
		['Q264_4', 'Reasons for addressing health and safety in the establishment: Increasing productivity'],
		['Q264_5', 'Reasons for addressing health and safety in the establishment: Organisation’s reputation'],
		['Q264_6', 'Reasons for addressing health and safety in the establishment: Avoiding fines from Health and Safety Inspectors'],
		['Q307', 'Sufficient information on how to include psychosocial risks in risk assessments'],
		['Q150_1', 'Use of health and safety services: An occupational health doctor'],
		['Q150_2', 'Use of health and safety services: A psychologist'],
		['Q150_3', 'Use of health and safety services: An expert dealing with the ergonomic design and set-up of workplaces'],
		['Q150_4', 'Use of health and safety services: A health and safety generalist'],
		['Q150_5', 'Use of health and safety services: An expert on accident prevention'],
		['Q155', 'Document explaining  responsibilities and procedures on health and safety is available to workers'],
		['Q156', 'A specific budget for health and safety measures and equipment set each year'],
		['Q158_1', 'Measures for health promotion among employees: Raising awareness of nutrition '],
		['Q158_2', 'Measures for health promotion among employees: Raising awareness about preventing addiction'],
		['Q158_3', 'Measures for health promotion among employees: Promoting sports activities outside of working hours'],
		['Q158_4', 'Measures for health promotion among employees: Promoting physical exercise at work'],
		['Q160', 'Routine analysis of absences due to sickness'],
		['Q165', 'Visit by the Health and Safety Authority in the last 3 years to check health and safety conditions'],
		['Q200_1', 'Risk factors present in the establishment: Tiring or painful positions'],
		['Q200_2', 'Risk factors present in the establishment: Lifting or moving people or heavy loads'],
		['Q200_3', 'Risk factors present in the establishment: Loud noise'],
		['Q200_4', 'Risk factors present in the establishment: Repetitive hand or arm movements'],
		['Q200_5', 'Risk factors present in the establishment: Heat, cold or draught'],
		['Q200_6', 'Risk factors present in the establishment: Risk of accidents with machines'],
		['Q200_7', 'Risk factors present in the establishment: Risk of accidents with vehicles in the course of work'],
		['Q200_8', 'Risk factors present in the establishment: Chemical or biological substances'],
		['Q200_9', 'Risk factors present in the establishment: Increased risk of slips, trips and falls'],
		['Q202_1', 'Lack of information or adequate tools to deal with the risk effectively: Tiring or painful positions'],
		['Q202_2', 'Lack of information or adequate tools to deal with the risk effectively: Lifting or moving people or heavy loads'],
		['Q202_3', 'Lack of information or adequate tools to deal with the risk effectively: Loud noise'],
		['Q202_4', 'Lack of information or adequate tools to deal with the risk effectively: Repetitive hand or arm movements'],
		['Q202_5', 'Lack of information or adequate tools to deal with the risk effectively: Heat, cold or draught'],
		['Q202_6', 'Lack of information or adequate tools to deal with the risk effectively: Risk of accidents with machines'],
		['Q202_7', 'Lack of information or adequate tools to deal with the risk effectively: Risk of accidents with vehicles in the course of work'],
		['Q202_8', 'Lack of information or adequate tools to deal with the risk effectively: Chemical or biological substances'],
		['Q202_9', 'Lack of information or adequate tools to deal with the risk effectively: Increased risk of slips, trips and falls'],
		['Q250', 'Workplace risk assessments'],
		['Q251', 'Risk assessments mainly conducted by internal staff or external service providers'],
		['Q252_1', 'Aspects evaluated in the workplace risk assessments: The safety of machines, equipment and installations'],
		['Q252_2', 'Aspects evaluated in the workplace risk assessments: Dangerous substances'],
		['Q252_3', 'Aspects evaluated in the workplace risk assessments: Working postures, physical working demands and repetitive movements'],
		['Q252_4', 'Aspects evaluated in the workplace risk assessments: Exposure to noise, vibrations, heat or cold'],
		['Q252_5', 'Aspects evaluated in the workplace risk assessments: Supervisor-employee relationships'],
		['Q252_6', 'Aspects evaluated in the workplace risk assessments: Organisational aspects'],
		['Q254gr', 'Year of last workplace risk assessment'],
		['Q255', 'Workplace risk assessment in a documented form'],
		['Q256_1', 'People provided with the findings of the workplace risk assessments: Management'],
		['Q256_2', 'People provided with the findings of the workplace risk assessments: Safety representatives'],
		['Q256_3', 'People provided with the findings of the workplace risk assessments: Statutory employee representation forum or another form of non-union staff association'],
		['Q256_4', 'People provided with the findings of the workplace risk assessments: Workplace union representatives'],
		['Q256_5', 'People provided with the findings of the workplace risk assessments: Employees themselves'],
		['Q259', 'Risk assessments regarded as a useful way of managing health and safety'],
		['Q261_1', 'Reasons why workplace risk assessments are not carried out on a regular basis: The dangers and risks are already known'],
		['Q261_2', 'Reasons why workplace risk assessments are not carried out on a regular basis: There are no major problems'],
		['Q261_3', 'Reasons why workplace risk assessments are not carried out on a regular basis: The procedure is too onerous'],
		['Q261_4', 'Reasons why workplace risk assessments are not carried out on a regular basis: The necessary expertise is lacking'],
		['Q308_1', 'Preventive measures regarding musculoskeletal problems: Equipment to help with the lifting or moving of loads'],
		['Q308_2', 'Preventive measures regarding musculoskeletal problems: Rotation of tasks to reduce physical strain'],
		['Q308_3', 'Preventive measures regarding musculoskeletal problems: Encouraging regular breaks for people in uncomfortable or static postures'],
		['Q308_4', 'Preventive measures regarding musculoskeletal problems: Provision of ergonomic equipment'],
		['Q356_1', 'Training for employees: Proper handling and adjustment of their work equipment and furniture'],
		['Q356_2', 'Training for employees: Use of dangerous substances'],
		['Q356_3', 'Training for employees: How to prevent psychosocial risks'],
		['Q356_4', 'Training for employees: How to lift and move heavy loads or people'],
		['Q356_5', 'Training for employees: Emergency procedures'],
		['Q201_1', 'Psychosocial risk factors present in the establishment: Pressure due to time constraints'],
		['Q201_2', 'Psychosocial risk factors present in the establishment: Poor communication or cooperation'],
		['Q201_3', 'Psychosocial risk factors present in the establishment: Employees’ lack of influence'],
		['Q201_4', 'Psychosocial risk factors present in the establishment: Fear of being made redundant'],
		['Q201_5', 'Psychosocial risk factors present in the establishment: Difficult customers, patients, pupils'],
		['Q201_6', 'Psychosocial risk factors present in the establishment: Long or irregular working hours'],
		['Q201_7', 'Psychosocial risk factors present in the establishment: Discrimination'],
		['Q202_10', 'Lack of information or adequate tools to deal with the risk effectively: Pressure due to time constraints'],
		['Q202_11', 'Lack of information or adequate tools to deal with the risk effectively: Poor communication or cooperation'],
		['Q202_12', 'Lack of information or adequate tools to deal with the risk effectively: Employees’ lack of influence'],
		['Q202_13', 'Lack of information or adequate tools to deal with the risk effectively: Fear of being made redundant'],
		['Q202_14', 'Lack of information or adequate tools to deal with the risk effectively: Difficult customers, patients, pupils'],
		['Q202_15', 'Lack of information or adequate tools to deal with the risk effectively: Long or irregular working hours'],
		['Q300', 'Action plan to prevent work-related stress'],
		['Q301', 'Procedures in place to deal with bullying or harassment'],
		['Q302', 'Procedure in place to deal with cases of threats, abuse or assault'],
		['Q303_1', 'Measures to prevent psychosocial risks in the last three years: Reorganisation of work in order to reduce job demands and work pressure '],
		['Q303_2', 'Measures to prevent psychosocial risks in the last three years: Confidential counselling for employees '],
		['Q303_3', 'Measures to prevent psychosocial risks in the last three years: Establishment of a conflict resolution procedure'],
		['Q303_4', 'Measures to prevent psychosocial risks in the last three years: Intervention if an employee works excessively long or irregular hours'],
		['Q307', 'Sufficient information on how to include psychosocial risks in risk assessments'],
		['Q264_1', 'Reasons for addressing health and safety in the establishment: Fulfilling a legal obligation'],
		['Q264_2', 'Reasons for addressing health and safety in the establishment: Meeting employee expectations'],
		['Q264_4', 'Reasons for addressing health and safety in the establishment: Increasing productivity'],
		['Q264_5', 'Reasons for addressing health and safety in the establishment: Organisation’s reputation'],
		['Q264_6', 'Reasons for addressing health and safety in the establishment: Avoiding fines from Health and Safety Inspectors'],
		['Q265_1', 'Main difficulties in addressing health and safety: A lack of time or staff'],
		['Q265_2', 'Main difficulties in addressing health and safety: A lack of money'],
		['Q265_3', 'Main difficulties in addressing health and safety: A lack of awareness among staff '],
		['Q265_4', 'Main difficulties in addressing health and safety: A lack of awareness among management'],
		['Q265_5', 'Main difficulties in addressing health and safety: A lack of expertise or specialist support'],
		['Q265_6', 'Main difficulties in addressing health and safety: The paperwork'],
		['Q265_7', 'Main difficulties in addressing health and safety: The complexity of legal obligations'],
		['Q304', 'Measures triggered by actual problems'],
		['Q306a_3', 'Difficulties in addressing psychosocial risks: A lack of awareness among staff'],
		['Q306a_4', 'Difficulties in addressing psychosocial risks: A lack of awareness among management '],
		['Q306a_5', 'Difficulties in addressing psychosocial risks: A lack of expertise or specialist support '],
		['Q306a_6', 'Difficulties in addressing psychosocial risks: Reluctance to talk openly about these issues'],
		['Q166_1', 'Forms of employee representation: Statutory employee representation forum or another form of non-union staff association'],
		['Q166_2', 'Forms of employee representation: Workplace union representative'],
		['Q166_3', 'Forms of employee representation: Safety representative'],
		['Q166_4', 'Forms of employee representation: Safety committee'],
		['Q258b', 'Employees involved in the design of measures following a risk assessment'],
		['Q305', 'Employees have a role in the design of measures to prevent psychosocial risks'],
		['Q350', 'How often health and safety is discussed between employee representatives and management'],
		['Q351', 'How often controversies related to health and safety arise'],
		['Q354', 'Safety representatives provided with training during worktime'],
		['Q358', 'Health and safety issues discussed in staff or team meetings']
	];
var question_answer
	 = [
	
		['Q150_1', '1--Yes', 'Yes'],
		['Q150_1', '2--No', 'No'],
		['Q150_2', '1--Yes', 'Yes'],
		['Q150_2', '2--No', 'No'],
		['Q150_3', '1--Yes', 'Yes'],
		['Q150_3', '2--No', 'No'],
		['Q150_4', '1--Yes', 'Yes'],
		['Q150_4', '2--No', 'No'],
		['Q150_5', '1--Yes', 'Yes'],
		['Q150_5', '2--No', 'No'],
		['Q155', '1--Yes', 'Yes'],
		['Q155', '2--No', 'No'],
		['Q155', '3--Yes--but-only-to-some-types-of-employees', 'Yes, but only certain types of employees'],
		['Q156', '1--Yes', 'Yes'],
		['Q156', '2--No', 'No'],
		['Q158_1', '1--Yes', 'Yes'],
		['Q158_1', '2--No', 'No'],
		['Q158_2', '1--Yes', 'Yes'],
		['Q158_2', '2--No', 'No'],
		['Q158_3', '1--Yes', 'Yes'],
		['Q158_3', '2--No', 'No'],
		['Q158_4', '1--Yes', 'Yes'],
		['Q158_4', '2--No', 'No'],
		['Q160', '1--Yes', 'Yes'],
		['Q160', '2--No', 'No'],
		['Q165', '1--Yes', 'Yes'],
		['Q165', '2--No', 'No'],
		['Q166_1', '1--Yes', 'Yes'],
		['Q166_1', '2--No', 'No'],
		['Q166_2', '1--Yes', 'Yes'],
		['Q166_2', '2--No', 'No'],
		['Q166_3', '1--Yes', 'Yes'],
		['Q166_3', '2--No', 'No'],
		['Q166_4', '1--Yes', 'Yes'],
		['Q166_4', '2--No', 'No'],
		['Q200_1', '1--Yes', 'Yes'],
		['Q200_1', '2--No', 'No'],
		['Q200_2', '1--Yes', 'Yes'],
		['Q200_2', '2--No', 'No'],
		['Q200_3', '1--Yes', 'Yes'],
		['Q200_3', '2--No', 'No'],
		['Q200_4', '1--Yes', 'Yes'],
		['Q200_4', '2--No', 'No'],
		['Q200_5', '1--Yes', 'Yes'],
		['Q200_5', '2--No', 'No'],
		['Q200_6', '1--Yes', 'Yes'],
		['Q200_6', '2--No', 'No'],
		['Q200_7', '1--Yes', 'Yes'],
		['Q200_7', '2--No', 'No'],
		['Q200_8', '1--Yes', 'Yes'],
		['Q200_8', '2--No', 'No'],
		['Q200_9', '1--Yes', 'Yes'],
		['Q200_9', '2--No', 'No'],
		['Q201_1', '1--Yes', 'Yes'],
		['Q201_1', '2--No', 'No'],
		['Q201_2', '1--Yes', 'Yes'],
		['Q201_2', '2--No', 'No'],
		['Q201_3', '1--Yes', 'Yes'],
		['Q201_3', '2--No', 'No'],
		['Q201_4', '1--Yes', 'Yes'],
		['Q201_4', '2--No', 'No'],
		['Q201_5', '1--Yes', 'Yes'],
		['Q201_5', '2--No', 'No'],
		['Q201_6', '1--Yes', 'Yes'],
		['Q201_6', '2--No', 'No'],
		['Q201_7', '1--Yes', 'Yes'],
		['Q201_7', '2--No', 'No'],
		['Q202_1', '1--Yes', 'Yes'],
		['Q202_1', '2--No', 'No'],
		['Q202_10', '1--Yes', 'Yes'],
		['Q202_10', '2--No', 'No'],
		['Q202_11', '1--Yes', 'Yes'],
		['Q202_11', '2--No', 'No'],
		['Q202_12', '1--Yes', 'Yes'],
		['Q202_12', '2--No', 'No'],
		['Q202_13', '1--Yes', 'Yes'],
		['Q202_13', '2--No', 'No'],
		['Q202_14', '1--Yes', 'Yes'],
		['Q202_14', '2--No', 'No'],
		['Q202_15', '1--Yes', 'Yes'],
		['Q202_15', '2--No', 'No'],
		['Q202_2', '1--Yes', 'Yes'],
		['Q202_2', '2--No', 'No'],
		['Q202_3', '1--Yes', 'Yes'],
		['Q202_3', '2--No', 'No'],
		['Q202_4', '1--Yes', 'Yes'],
		['Q202_4', '2--No', 'No'],
		['Q202_5', '1--Yes', 'Yes'],
		['Q202_5', '2--No', 'No'],
		['Q202_6', '1--Yes', 'Yes'],
		['Q202_6', '2--No', 'No'],
		['Q202_7', '1--Yes', 'Yes'],
		['Q202_7', '2--No', 'No'],
		['Q202_8', '1--Yes', 'Yes'],
		['Q202_8', '2--No', 'No'],
		['Q202_9', '1--Yes', 'Yes'],
		['Q202_9', '2--No', 'No'],
		['Q250', '1--Yes', 'Yes'],
		['Q250', '2--No', 'No'],
		['Q251', '1--Conducted-mainly-by-internal-staff', 'Conducted mainly by internal staff'],
		['Q251', '2--Contracted-mainly-to-external-providers', 'Contracted mainly to external providers'],
		['Q251', '3--Both-about-equally', 'Both about equally'],
		['Q252_1', '1--Yes', 'Yes'],
		['Q252_1', '2--No', 'No'],
		['Q252_2', '1--Yes', 'Yes'],
		['Q252_2', '2--No', 'No'],
		['Q252_3', '1--Yes', 'Yes'],
		['Q252_3', '2--No', 'No'],
		['Q252_4', '1--Yes', 'Yes'],
		['Q252_4', '2--No', 'No'],
		['Q252_5', '1--Yes', 'Yes'],
		['Q252_5', '2--No', 'No'],
		['Q252_6', '1--Yes', 'Yes'],
		['Q252_6', '2--No', 'No'],
		['Q254gr', '1--2010', '2010'],
		['Q254gr', '2--2011', '2011'],
		['Q254gr', '3--2012', '2012'],
		['Q254gr', '4--2013', '2013'],
		['Q254gr', '5--2014', '2014'],
		['Q254gr', '6--before-2010', 'before 2010'],
		['Q254gr', '7--don-t-know', 'don´t know'],
		['Q255', '1--Yes', 'Yes'],
		['Q255', '2--No', 'No'],
		['Q256_1', '1--Yes', 'Yes'],
		['Q256_1', '2--No', 'No'],
		['Q256_2', '1--Yes', 'Yes'],
		['Q256_2', '2--No', 'No'],
		['Q256_3', '1--Yes', 'Yes'],
		['Q256_3', '2--No', 'No'],
		['Q256_4', '1--Yes', 'Yes'],
		['Q256_4', '2--No', 'No'],
		['Q256_5', '1--Yes', 'Yes'],
		['Q256_5', '2--No', 'No'],
		['Q258b', '1--Yes', 'Yes'],
		['Q258b', '2--No', 'No'],
		['Q258b', '3--That-depends-on-the-type-of-measures', 'That depends on the type of measures'],
		['Q259', '1--Yes', 'Yes'],
		['Q259', '2--No', 'No'],
		['Q259', '3--There-are-conflicting-views-about-this', 'There are conflicting views about this'],
		['Q261_1', '1--Yes', 'Yes'],
		['Q261_1', '2--No', 'No'],
		['Q261_2', '1--Yes', 'Yes'],
		['Q261_2', '2--No', 'No'],
		['Q261_3', '1--Yes', 'Yes'],
		['Q261_3', '2--No', 'No'],
		['Q261_4', '1--Yes', 'Yes'],
		['Q261_4', '2--No', 'No'],
		['Q264_1', '1--Major-reason', 'Major reason'],
		['Q264_1', '2--Minor-reason', 'Minor reason'],
		['Q264_1', '3--Not-a-reason', 'Not a reason at all'],
		['Q264_2', '1--Major-reason', 'Major reason'],
		['Q264_2', '2--Minor-reason', 'Minor reason'],
		['Q264_2', '3--Not-a-reason', 'Not a reason at all'],
		['Q264_4', '1--Major-reason', 'Major reason'],
		['Q264_4', '2--Minor-reason', 'Minor reason'],
		['Q264_4', '3--Not-a-reason', 'Not a reason at all'],
		['Q264_5', '1--Major-reason', 'Major reason'],
		['Q264_5', '2--Minor-reason', 'Minor reason'],
		['Q264_5', '3--Not-a-reason', 'Not a reason at all'],
		['Q264_6', '1--Major-reason', 'Major reason'],
		['Q264_6', '2--Minor-reason', 'Minor reason'],
		['Q264_6', '3--Not-a-reason', 'Not a reason at all'],
		['Q265_1', '1--Major-difficulty', 'Major difficulty'],
		['Q265_1', '2--Minor-difficulty', 'Minor difficulty'],
		['Q265_1', '3--Not-a-difficulty', 'Not a difficulty at all'],
		['Q265_2', '1--Major-difficulty', 'Major difficulty'],
		['Q265_2', '2--Minor-difficulty', 'Minor difficulty'],
		['Q265_2', '3--Not-a-difficulty', 'Not a difficulty at all'],
		['Q265_3', '1--Major-difficulty', 'Major difficulty'],
		['Q265_3', '2--Minor-difficulty', 'Minor difficulty'],
		['Q265_3', '3--Not-a-difficulty', 'Not a difficulty at all'],
		['Q265_4', '1--Major-difficulty', 'Major difficulty'],
		['Q265_4', '2--Minor-difficulty', 'Minor difficulty'],
		['Q265_4', '3--Not-a-difficulty', 'Not a difficulty at all'],
		['Q265_5', '1--Major-difficulty', 'Major difficulty'],
		['Q265_5', '2--Minor-difficulty', 'Minor difficulty'],
		['Q265_5', '3--Not-a-difficulty', 'Not a difficulty at all'],
		['Q265_6', '1--Major-difficulty', 'Major difficulty'],
		['Q265_6', '2--Minor-difficulty', 'Minor difficulty'],
		['Q265_6', '3--Not-a-difficulty', 'Not a difficulty at all'],
		['Q265_7', '1--Major-difficulty', 'Major difficulty'],
		['Q265_7', '2--Minor-difficulty', 'Minor difficulty'],
		['Q265_7', '3--Not-a-difficulty', 'Not a difficulty at all'],
		['Q300', '1--Yes', 'Yes'],
		['Q300', '2--No', 'No'],
		['Q301', '1--Yes', 'Yes'],
		['Q301', '2--No', 'No'],
		['Q302', '1--Yes', 'Yes'],
		['Q302', '2--No', 'No'],
		['Q303_1', '1--Yes', 'Yes'],
		['Q303_1', '2--No', 'No'],
		['Q303_2', '1--Yes', 'Yes'],
		['Q303_2', '2--No', 'No'],
		['Q303_3', '1--Yes', 'Yes'],
		['Q303_3', '2--No', 'No'],
		['Q303_4', '1--Yes', 'Yes'],
		['Q303_4', '2--No', 'No'],
		['Q304', '1--Yes', 'Yes'],
		['Q304', '2--No', 'No'],
		['Q304', '3--Partly', 'Partly'],
		['Q305', '1--Yes', 'Yes'],
		['Q305', '2--No', 'No'],
		['Q306a_3', '1--Yes', 'Yes'],
		['Q306a_3', '2--No', 'No'],
		['Q306a_4', '1--Yes', 'Yes'],
		['Q306a_4', '2--No', 'No'],
		['Q306a_5', '1--Yes', 'Yes'],
		['Q306a_5', '2--No', 'No'],
		['Q306a_6', '1--Yes', 'Yes'],
		['Q306a_6', '2--No', 'No'],
		['Q307', '1--Yes', 'Yes'],
		['Q307', '2--No', 'No'],
		['Q308_1', '1--Yes', 'Yes'],
		['Q308_1', '2--No', 'No'],
		['Q308_2', '1--Yes', 'Yes'],
		['Q308_2', '2--No', 'No'],
		['Q308_3', '1--Yes', 'Yes'],
		['Q308_3', '2--No', 'No'],
		['Q308_4', '1--Yes', 'Yes'],
		['Q308_4', '2--No', 'No'],
		['Q350', '1--Regularly', 'On a regular basis'],
		['Q350', '2--Only-when-particular-issues-arise', 'Only when particular issues arise'],
		['Q350', '3--Not-at-all', 'Not at all'],
		['Q351', '1--Often', 'Often'],
		['Q351', '2--Sometimes', 'Sometimes'],
		['Q351', '3--Practically-never', 'Practically never'],
		['Q354', '1--Yes', 'Yes'],
		['Q354', '2--No', 'No'],
		['Q354', '3--Yes--but-only-some-of-them', 'Yes, but only some of them'],
		['Q356_1', '1--Yes', 'Yes'],
		['Q356_1', '2--No', 'No'],
		['Q356_2', '1--Yes', 'Yes'],
		['Q356_2', '2--No', 'No'],
		['Q356_3', '1--Yes', 'Yes'],
		['Q356_3', '2--No', 'No'],
		['Q356_4', '1--Yes', 'Yes'],
		['Q356_4', '2--No', 'No'],
		['Q356_5', '1--Yes', 'Yes'],
		['Q356_5', '2--No', 'No'],
		['Q358', '1--Yes', 'Yes'],
		['Q358', '2--No', 'No'],
		['Q358', '3--In-some-departments-only', 'In some departments only']
	];
var country_
	 = [
	
		['AL', 'Albania'],
		['AT', 'Austria'],
		['BE', 'Belgium'],
		['BG', 'Bulgaria'],
		['CH', 'Switzerland'],
		['CY', 'Cyprus'],
		['CZ', 'Czech Republic'],
		['DE', 'Germany'],
		['DK', 'Denmark'],
		['EE', 'Estonia'],
		['EL', 'Greece'],
		['ES', 'Spain'],
		['FI', 'Finland'],
		['FR', 'France'],
		['HR', 'Croatia'],
		['HU', 'Hungary'],
		['IE', 'Ireland'],
		['IS', 'Iceland'],
		['IT', 'Italy'],
		['LT', 'Lithuania'],
		['LU', 'Luxembourg'],
		['LV', 'Latvia'],
		['ME', 'Montenegro'],
		['MK', 'FYROM'],
		['MT', 'Malta'],
		['NL', 'Netherlands'],
		['NO', 'Norway'],
		['PL', 'Poland'],
		['PT', 'Portugal'],
		['RO', 'Romania'],
		['RS', 'Serbia'],
		['SE', 'Sweden'],
		['SI', 'Slovenia'],
		['SK', 'Slovakia'],
		['TR', 'Turkey'],
		['UK', 'United Kingdom'],
		['EuropeanUnion', 'European Union']
	];
var question_meta
	 = [
	
		['Q200_1', 'Tiring or painful positions, including sitting for long periods of time', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Tiring or painful positions, including sitting for long periods of time <br><br>(1) Yes<br> (2) No<br> (9) No answer'],
		['Q200_2', 'Lifting or moving people or heavy loads', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Lifting or moving people or heavy loads<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_3', 'Loud noise', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Loud noise<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_4', 'Repetitive hand or arm movements', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Repetitive hand or arm movements<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_5', 'Heat, cold or draught', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Heat, cold or draught<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_6', 'Risk of accidents with machines or hand tools', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Risk of accidents with machines or hand tools<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_7', 'Risk of accidents with vehicles in the course of work but not on the way to and from work', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Risk of accidents with vehicles in the course of work but not on the way to and from work<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_8', 'Chemical or biological substances in the form of liquids, fumes or dust', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Chemical or biological substances in the form of liquids, fumes or dust<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_9', 'Increased risk of slips, trips and falls', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Increased risk of slips, trips and falls<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q201_1', 'Pressure due to time constraints', 'Besides these risks, there may also be health risks resulting from the way work is organised, from social relations at work or from the economic situation at work. Please tell me whether or not each of the following risks is present in the establishment? Pressure due to time constraints<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q201_2', 'Poor communication or cooperation within the organisation', 'Besides these risks, there may also be health risks resulting from the way work is organised, from social relations at work or from the economic situation at work. Please tell me whether or not each of the following risks is present in the establishment? Poor communication or cooperation within the organisation<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q201_3', 'Employees’ lack of influence over the pace of work or work processes', 'Besides these risks, there may also be health risks resulting from the way work is organised, from social relations at work or from the economic situation at work. Please tell me whether or not each of the following risks is present in the establishment? Employees’ lack of influence over the pace of work or work processes<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q201_4', 'Fear of being made redundant', 'Besides these risks, there may also be health risks resulting from the way work is organised, from social relations at work or from the economic situation at work. Please tell me whether or not each of the following risks is present in the establishment? Fear of being made redundant<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q201_5', 'Having to deal with difficult customers, patients, pupils etc.', 'Besides these risks, there may also be health risks resulting from the way work is organised, from social relations at work or from the economic situation at work. Please tell me whether or not each of the following risks is present in the establishment? Having to deal with difficult customers, patients, pupils etc.<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q201_6', 'Long or irregular working hours', 'Besides these risks, there may also be health risks resulting from the way work is organised, from social relations at work or from the economic situation at work. Please tell me whether or not each of the following risks is present in the establishment? Long or irregular working hours<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q201_7', 'Discrimination, for example due to gender, age or ethnicity', 'Besides these risks, there may also be health risks resulting from the way work is organised, from social relations at work or from the economic situation at work. Please tell me whether or not each of the following risks is present in the establishment? Discrimination, for example due to gender, age or ethnicity<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q250', 'Does your establishment carry out workplace risk assessments on a regular basis?', 'Does your establishment carry out workplace risk assessments on a regular basis?<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q251', 'Are workplace risk assessments mainly conducted by internal staff or are they contracted to external service providers?', 'Are workplace risk assessments mainly  conducted by internal staff or are they contracted to external service providers?<br><br> (1) Conducted mainly by internal staff <br>(2) Contracted mainly to external providers<br> (3) Both about equally <br>(9) No answer <br><br>Question asked to those establishments that report carrying out risk assessments regularly.'],
		['Q264_1', 'Fulfilling a legal obligation', 'In your establishment, how important are the following reasons for addressing health and safety? For each reason, please tell me whether it is a major reason, a minor reason or not a reason at all. Fulfilling a legal obligation<br><br>(1) Major reason <br>(2) Minor reason <br>(3) Not a reason at all <br>(9) No answer'],
		['Q264_2', 'Meeting employee expectations or those of their representatives', 'In your establishment, how important are the following reasons for addressing health and safety? For each reason, please tell me whether it is a major reason, a minor reason or not a reason at all. Meeting employee expectations or those of their representatives<br><br>(1) Major reason <br>(2) Minor reason <br>(3) Not a reason at all <br>(9) No answer'],
		['Q264_4', 'Maintaining or increasing productivity', 'In your establishment, how important are the following reasons for addressing health and safety? For each reason, please tell me whether it is a major reason, a minor reason or not a reason at all. Maintaining or increasing productivity<br><br>(1) Major reason <br>(2) Minor reason <br>(3) Not a reason at all <br>(9) No answer'],
		['Q264_5', 'Maintaining the organisation’s reputation ', 'In your establishment, how important are the following reasons for addressing health and safety? For each reason, please tell me whether it is a major reason, a minor reason or not a reason at all. Maintaining the organisation’s reputation <br><br>(1) Major reason <br>(2) Minor reason <br>(3) Not a reason at all <br>(9) No answer'],
		['Q264_6', 'Avoiding fines and sanctions from Health and Safety Inspectors', 'In your establishment, how important are the following reasons for addressing health and safety? For each reason, please tell me whether it is a major reason, a minor reason or not a reason at all. Avoiding fines and sanctions from Health and Safety Inspectors<br><br>(1) Major reason <br>(2) Minor reason <br>(3) Not a reason at all <br>(9) No answer'],
		['Q307', 'Do you have sufficient information on how to include psychosocial risks in risk assessments?', 'Do you have sufficient information on how to include psychosocial risks in risk assessments?<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q150_1', 'An occupational health doctor', 'What health and safety services do you use, be they either in-house or contracted externally? An occupational health doctor<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q150_2', 'A psychologist', 'What health and safety services do you use, be they either in-house or contracted externally? A psychologist<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q150_3', 'An expert dealing with the ergonomic design and set-up of workplaces', 'What health and safety services do you use, be they either in-house or contracted externally? An expert dealing with the ergonomic design and set-up of workplaces<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q150_4', 'A health and safety generalist', 'What health and safety services do you use, be they either in-house or contracted externally? A health and safety generalist<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q150_5', 'An expert on accident prevention', 'What health and safety services do you use, be they either in-house or contracted externally? An expert on accident prevention<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q155', 'Do those working in the establishment have access to a document explaining responsibilities and procedures on health and safety?', 'Do those working in the establishment have access to a document explaining responsibilities and procedures on health and safety?<br><br>(1) Yes <br>(2) No <br>(3) Yes, but only certain types of employees <br>(9) No answer'],
		['Q156', 'Is there a specific budget set each year for health and safety measures and equipment in your establishment?', 'Is there a specific budget set each year for health and safety measures and equipment in your establishment?<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q158_1', 'Raising awareness about healthy nutrition', 'Does your establishment take any of the following measures to promote health among employees? Raising awareness about healthy nutrition<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q158_2', 'Raising awareness about preventing addiction, e.g. to smoking, alcohol or drugs', 'Does your establishment take any of the following measures to promote health among employees? Raising awareness about preventing addiction, e.g. to smoking, alcohol or drugs<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q158_3', 'Promoting sports activities outside of working hours', 'Does your establishment take any of the following measures to promote health among employees? Promoting sports activities outside of working hours<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q158_4', 'Promoting back exercises, stretching or other physical exercise at work', 'Does your establishment take any of the following measures to promote health among employees? Promoting back exercises, stretching or other physical exercise at work<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q160', 'Are absences due to sickness routinely analysed with a view to improving working conditions?', 'Are absences due to sickness routinely analysed with a view to improving working conditions?<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q165', 'Has your establishment been visited by the Health and Safety Authority in the last 3 years in order to check health and safety conditions? ', 'Has your establishment been visited by the Health and Safety Authority in the last 3 years in order to check health and safety conditions?<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_1', 'Tiring or painful positions, including sitting for long periods of time', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Tiring or painful positions, including sitting for long periods of time<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_2', 'Lifting or moving people or heavy loads', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Lifting or moving people or heavy loads<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_3', 'Loud noise', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Loud noise<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_4', 'Repetitive hand or arm movements', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Repetitive hand or arm movements<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_5', 'Heat, cold or draught', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Heat, cold or draught<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_6', 'Risk of accidents with machines or hand tools', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Risk of accidents with machines or hand tools<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_7', 'Risk of accidents with vehicles in the course of work but not on the way to and from work', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Risk of accidents with vehicles in the course of work but not on the way to and from work<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_8', 'Chemical or biological substances in the form of liquids, fumes or dust', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Chemical or biological substances in the form of liquids, fumes or dust<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q200_9', 'Increased risk of slips, trips and falls', 'Depending on the type of work there are different types of risks and dangers. Please tell me for each of the following risk factors whether it is present or not in your establishment, regardless of whether it is currently under control and of the number of employees it affects. Increased risk of slips, trips and falls<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q202_1', 'Tiring or painful positions, including sitting for long periods of time', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]? Tiring or painful positions, including sitting for long periods of time <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q202_2', 'Lifting or moving people or heavy loads', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]? Lifting or moving people or heavy loads <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q202_3', 'Loud noise', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]? Loud noise <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q202_4', 'Repetitive hand or arm movements', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]? Repetitive hand or arm movements <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q202_5', 'Heat, cold or draught', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]? Heat, cold or draught <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q202_6', 'Risk of accidents with machines or hand tools', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]? Risk of accidents with machines or hand tools <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q202_7', 'Risk of accidents with vehicles in the course of work but not on the way to and from work', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]? Risk of accidents with vehicles in the course of work but not on the way to and from work <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q202_8', 'Chemical or biological substances in the form of liquids, fumes or dust', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]? Chemical or biological substances in the form of liquids, fumes or dust <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q202_9', 'Increased risk of slips, trips and falls', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]?  Increased risk of slips, trips and falls <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q250', 'Does your establishment carry out workplace risk assessments on a regular basis?', 'Does your establishment carry out workplace risk assessments on a regular basis?<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q251', 'Are workplace risk assessments mainly conducted by internal staff or are they contracted to external service providers?', 'Are workplace risk assessments mainly  conducted by internal staff or are they contracted to external service providers?<br><br> (1) Conducted mainly by internal staff <br>(2) Contracted mainly to external providers<br> (3) Both about equally <br>(9) No answer <br><br>Question asked to those establishments that report carrying out risk assessments regularly.'],
		['Q252_1', 'The safety of machines, equipment and installations', 'Which of the following aspects are routinely evaluated in these workplace risk assessments? The safety of machines, equipment and installations <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report carrying out risk assessments regularly.'],
		['Q252_2', 'Dangerous chemical or biological substances', 'Which of the following aspects are routinely evaluated in these workplace risk assessments? Dangerous chemical or biological substances <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report carrying out risk assessments regularly.'],
		['Q252_3', 'Working postures, physical working demands and repetitive movements', 'Which of the following aspects are routinely evaluated in these workplace risk assessments? Working postures, physical working demands and repetitive movements<br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report carrying out risk assessments regularly.'],
		['Q252_4', 'Exposure to noise, vibrations, heat or cold', 'Which of the following aspects are routinely evaluated in these workplace risk assessments? Exposure to noise, vibrations, heat or cold <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report carrying out risk assessments regularly.'],
		['Q252_5', 'Supervisor-employee relationships', 'Which of the following aspects are routinely evaluated in these workplace risk assessments? Supervisor-employee relationships <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report carrying out risk assessments regularly.'],
		['Q252_6', 'Organisational aspects such as work schedules, breaks or work shifts', 'Which of the following aspects are routinely evaluated in these workplace risk assessments? Organisational aspects such as work schedules, breaks or work shifts <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report carrying out risk assessments regularly.'],
		['Q254gr', 'In what year was the last workplace risk assessment carried out?', 'In what year was the last workplace risk assessment carried out? <br><br>(Year) <br>(9998) Don’t know <br>(9999) No answer <br><br>Question asked to those establishments that report carrying out risk assessments regularly.'],
		['Q255', 'Has it been documented in written form?', 'Has it been documented in written form? <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having the last workplace risk assessment after 1970.'],
		['Q256_1', 'Management', 'Who has been provided with the findings of the workplace risk assessment? Management <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having the last workplace risk assessment after 1970.'],
		['Q256_2', 'Safety representatives', 'Who has been provided with the findings of the workplace risk assessment? Safety representatives <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having the last workplace risk assessment after 1970 and having safety representatives.'],
		['Q256_3', 'Statutory employee representation forum or another form of non-union staff association', 'Who has been provided with the findings of the workplace risk assessment? Statutory employee representation forum or another form of non-union staff association <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having the last workplace risk assessment after 1970 and having statutory employee representation forum or another form of non-union staff association.'],
		['Q256_4', 'Workplace union representatives', 'Who has been provided with the findings of the workplace risk assessment? Workplace union representatives <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having the last workplace risk assessment after 1970 and having workplace union representatives.'],
		['Q256_5', 'Employees themselves', 'Who has been provided with the findings of the workplace risk assessment? Employees themselves <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having the last workplace risk assessment after 1970.'],
		['Q259', 'In your establishment, is the risk assessment procedure viewed as a useful way of managing health and safety?', 'In your establishment, is the risk assessment procedure viewed as a useful way of managing health and safety? <br><br>(1) Yes <br>(2) No <br>(3) There are conflicting views about this <br>(9) No answer <br><br>Question asked to those establishments that report carrying out risk assessments regularly.'],
		['Q261_1', 'The dangers and risks are already known', 'Are there any particular reasons why workplace risk assessments are not carried out on a regular basis? Please tell me for each of the following whether or not it applies to your establishment? The dangers and risks are already known<br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that don’t report carrying out risk assessments regularly.'],
		['Q261_2', 'There are no major problems', 'Are there any particular reasons why workplace risk assessments are not carried out on a regular basis? Please tell me for each of the following whether or not it applies to your establishment? There are no major problems<br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that don’t report carrying out risk assessments regularly.'],
		['Q261_3', 'The procedure is too onerous', 'Are there any particular reasons why workplace risk assessments are not carried out on a regular basis? Please tell me for each of the following whether or not it applies to your establishment? The procedure is too onerous<br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that don’t report carrying out risk assessments regularly.'],
		['Q261_4', 'The necessary expertise is lacking', 'Are there any particular reasons why workplace risk assessments are not carried out on a regular basis? Please tell me for each of the following whether or not it applies to your establishment? The necessary expertise is lacking<br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that don’t report carrying out risk assessments regularly.'],
		['Q308_1', 'Equipment to help with the lifting or moving of loads or other physically heavy work', 'Now turning to musculoskeletal problems such as pain in the back, neck, arms, hands or legs, are any of the following preventive measures in place in your establishment? Equipment to help with lifting or moving loads or with other physically heavy work<br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report lifting or moving people or heavy loads as a risk factor.'],
		['Q308_2', 'Rotation of tasks to reduce repetitive movements or physical strain', 'Now turning to musculoskeletal problems such as pain in the back, neck, arms, hands or legs, are any of the following preventive measures in place in your establishment? Rotation of tasks to reduce repetitive movements or physical strain<br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report repetitive hand or arm movements as a risk factor.'],
		['Q308_3', 'Encouraging regular breaks for people in uncomfortable or static postures including prolonged sitting', 'Now turning to musculoskeletal problems such as pain in the back, neck, arms, hands or legs, are any of the following preventive measures in place in your establishment? Encouraging regular breaks for people in uncomfortable or static postures including prolonged sitting<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q308_4', 'Provision of ergonomic equipment, such as specific chairs or desks', 'Now turning to musculoskeletal problems such as pain in the back, neck, arms, hands or legs, are any of the following preventive measures in place in your establishment? Provision of ergonomic equipment, such as specific  chairs or desks<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q356_1', 'The proper handling and adjustment of their work equipment and furniture', 'On which of the following topics does your establishment provide employees with training? The proper handling and adjustment of their work equipment and furniture<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q356_2', 'The use of dangerous substances', 'On which of the following topics does your establishment provide employees with training? The use of dangerous substances<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q356_3', 'How to prevent psychosocial risks such as stress or bullying', 'On which of the following topics does your establishment provide employees with training? How to prevent psychosocial risks such as stress or bullying<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q356_4', 'How to lift and move heavy loads or people', 'On which of the following topics does your establishment provide employees with training? How to lift and move heavy loads or people<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q356_5', 'Emergency procedures', 'On which of the following topics does your establishment provide employees with training? Emergency procedures<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q201_1', 'Pressure due to time constraints', 'Besides these risks, there may also be health risks resulting from the way work is organised, from social relations at work or from the economic situation at work. Please tell me whether or not each of the following risks is present in the establishment? Pressure due to time constraints<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q201_2', 'Poor communication or cooperation within the organisation', 'Besides these risks, there may also be health risks resulting from the way work is organised, from social relations at work or from the economic situation at work. Please tell me whether or not each of the following risks is present in the establishment? Poor communication or cooperation within the organisation<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q201_3', 'Employees’ lack of influence over the pace of work or work processes', 'Besides these risks, there may also be health risks resulting from the way work is organised, from social relations at work or from the economic situation at work. Please tell me whether or not each of the following risks is present in the establishment? Employees’ lack of influence over the pace of work or work processes<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q201_4', 'Fear of being made redundant', 'Besides these risks, there may also be health risks resulting from the way work is organised, from social relations at work or from the economic situation at work. Please tell me whether or not each of the following risks is present in the establishment? Fear of being made redundant<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q201_5', 'Having to deal with difficult customers, patients, pupils etc.', 'Besides these risks, there may also be health risks resulting from the way work is organised, from social relations at work or from the economic situation at work. Please tell me whether or not each of the following risks is present in the establishment? Having to deal with difficult customers, patients, pupils etc.<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q201_6', 'Long or irregular working hours', 'Besides these risks, there may also be health risks resulting from the way work is organised, from social relations at work or from the economic situation at work. Please tell me whether or not each of the following risks is present in the establishment? Long or irregular working hours<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q201_7', 'Discrimination, for example due to gender, age or ethnicity', 'Besides these risks, there may also be health risks resulting from the way work is organised, from social relations at work or from the economic situation at work. Please tell me whether or not each of the following risks is present in the establishment? Discrimination, for example due to gender, age or ethnicity<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q202_10', 'Pressure due to time constraints', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]? Pressure due to time constraints <br><br>(1) Yes<br> (2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q202_11', 'Poor communication or cooperation within the organisation', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]? Poor communication or cooperation within the organisation <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q202_12', 'Employees’ lack of influence on the pace of work or work processes', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]? Employees’ lack of influence on the pace of work or work processes <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q202_13', 'Fear of being made redundant', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]? Fear of being made redundant <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q202_14', 'Having to deal with difficult customers, patients, pupils etc.', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]? Having to deal with difficult customers, patients, pupils etc. <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q202_15', 'Long or irregular working hours', 'For which of the risks – if any – is your establishment lacking information or adequate preventive tools [to deal with them effectively]? Long or irregular working hours <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having this risk factor.'],
		['Q300', 'Does your establishment have an action plan to prevent work-related stress?', 'Does your establishment have an action plan to prevent work-related stress? <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments with 20 employees or more.'],
		['Q301', 'Is there a procedure in place to deal with possible cases of bullying or harassment? ', 'Is there a procedure in place to deal with possible cases of bullying or harassment? <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments with 20 employees or more.'],
		['Q302', 'And is there a procedure to deal with possible cases of threats, abuse or assault by clients, patients, pupils or other external persons?', 'And is there a procedure to deal with possible cases of threats, abuse or assault by clients, patients, pupils or other external persons?  <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments with 20 employees or more and that report having to deal with difficult customers, patients, pupils as a risk factor.'],
		['Q303_1', 'Reorganisation of work in order to reduce job demands and work pressure', 'In the last 3 years, has your establishment used any of the following measures to prevent psychosocial risks? Reorganisation of work in order to reduce job demands and work pressure<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q303_2', 'Confidential counselling for employees', 'In the last 3 years, has your establishment used any of the following measures to prevent psychosocial risks? Confidential counselling for employees<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q303_3', 'Establishment of a conflict resolution procedure', 'In the last 3 years, has your establishment used any of the following measures to prevent psychosocial risks? Establishment of a conflict resolution procedure<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q303_4', 'Intervention if an employee works excessively long or irregular hours', 'In the last 3 years, has your establishment used any of the following measures to prevent psychosocial risks? Intervention if an employee works excessively long or irregular hours<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q307', 'Do you have sufficient information on how to include psychosocial risks in risk assessments?', 'Do you have sufficient information on how to include psychosocial risks in risk assessments?<br><br>(1) Yes <br>(2) No <br>(9) No answer'],
		['Q264_1', 'Fulfilling a legal obligation', 'In your establishment, how important are the following reasons for addressing health and safety? For each reason, please tell me whether it is a major reason, a minor reason or not a reason at all. Fulfilling a legal obligation<br><br>(1) Major reason <br>(2) Minor reason <br>(3) Not a reason at all <br>(9) No answer'],
		['Q264_2', 'Meeting employee expectations or those of their representatives', 'In your establishment, how important are the following reasons for addressing health and safety? For each reason, please tell me whether it is a major reason, a minor reason or not a reason at all. Meeting employee expectations or those of their representatives<br><br>(1) Major reason <br>(2) Minor reason <br>(3) Not a reason at all <br>(9) No answer'],
		['Q264_4', 'Maintaining or increasing productivity', 'In your establishment, how important are the following reasons for addressing health and safety? For each reason, please tell me whether it is a major reason, a minor reason or not a reason at all. Maintaining or increasing productivity<br><br>(1) Major reason <br>(2) Minor reason <br>(3) Not a reason at all <br>(9) No answer'],
		['Q264_5', 'Maintaining the organisation’s reputation ', 'In your establishment, how important are the following reasons for addressing health and safety? For each reason, please tell me whether it is a major reason, a minor reason or not a reason at all. Maintaining the organisation’s reputation <br><br>(1) Major reason <br>(2) Minor reason <br>(3) Not a reason at all <br>(9) No answer'],
		['Q264_6', 'Avoiding fines and sanctions from Health and Safety Inspectors', 'In your establishment, how important are the following reasons for addressing health and safety? For each reason, please tell me whether it is a major reason, a minor reason or not a reason at all. Avoiding fines and sanctions from Health and Safety Inspectors<br><br>(1) Major reason <br>(2) Minor reason <br>(3) Not a reason at all <br>(9) No answer'],
		['Q265_1', 'A lack of time or staff', 'What are the main difficulties in addressing health and safety in your establishment? Please tell me for each of the following options whether it is a major difficulty, a minor difficulty, or not a difficulty at all. A lack of time or staff<br><br>(1) Major difficulty <br>(2) Minor difficulty <br>(3) Not a difficulty at all <br>(9) No answer'],
		['Q265_2', 'A lack of money', 'What are the main difficulties in addressing health and safety in your establishment? Please tell me for each of the following options whether it is a major difficulty, a minor difficulty, or not a difficulty at all. A lack of money<br><br>(1) Major difficulty <br>(2) Minor difficulty <br>(3) Not a difficulty at all <br>(9) No answer'],
		['Q265_3', 'A lack of awareness among staff ', 'What are the main difficulties in addressing health and safety in your establishment? Please tell me for each of the following options whether it is a major difficulty, a minor difficulty, or not a difficulty at all. A lack of awareness among staff <br><br>(1) Major difficulty <br>(2) Minor difficulty <br>(3) Not a difficulty at all <br>(9) No answer'],
		['Q265_4', 'A lack of awareness among management', 'What are the main difficulties in addressing health and safety in your establishment? Please tell me for each of the following options whether it is a major difficulty, a minor difficulty, or not a difficulty at all. A lack of awareness among management<br><br>(1) Major difficulty <br>(2) Minor difficulty <br>(3) Not a difficulty at all <br>(9) No answer'],
		['Q265_5', 'A lack of expertise or specialist support', 'What are the main difficulties in addressing health and safety in your establishment? Please tell me for each of the following options whether it is a major difficulty, a minor difficulty, or not a difficulty at all. A lack of expertise or specialist support<br><br>(1) Major difficulty <br>(2) Minor difficulty <br>(3) Not a difficulty at all <br>(9) No answer'],
		['Q265_6', 'The paperwork', 'What are the main difficulties in addressing health and safety in your establishment? Please tell me for each of the following options whether it is a major difficulty, a minor difficulty, or not a difficulty at all. The paperwork<br><br>(1) Major difficulty <br>(2) Minor difficulty <br>(3) Not a difficulty at all <br>(9) No answer'],
		['Q265_7', 'The complexity of legal obligations', 'What are the main difficulties in addressing health and safety in your establishment? Please tell me for each of the following options whether it is a major difficulty, a minor difficulty, or not a difficulty at all. The complexity of legal obligations<br><br>(1) Major difficulty <br>(2) Minor difficulty <br>(3) Not a difficulty at all <br>(9) No answer'],
		['Q304', 'Were the measures taken triggered by actual problems with stress, bullying, harassment or violence in the establishment?', 'Were the measures taken triggered by actual problems with stress, bullying, harassment or violence in the establishment? <br><br>(1) Yes <br>(2) No <br>(3) Partly <br>(9) No answer <br><br>Question asked to those establishments that report some measure used to prevent psychosocial risks in the last 3 years.'],
		['Q306a_3', 'A lack of awareness among staff', 'Considering the situation in your establishment: Do any of the following factors make addressing psychosocial risks more difficult than addressing other health risks? A lack of awareness among staff <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having one of the risk factors listed.'],
		['Q306a_4', 'A lack of awareness among management', 'Considering the situation in your establishment: Do any of the following factors make addressing psychosocial risks more difficult than addressing other health risks? A lack of awareness among management <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having one of the risk factors listed.'],
		['Q306a_5', 'A lack of expertise or specialist support', 'Considering the situation in your establishment: Do any of the following factors make addressing psychosocial risks more difficult than addressing other health risks? A lack of expertise or specialist support <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having one of the risk factors listed.'],
		['Q306a_6', 'Reluctance to talk openly about these issues', 'Considering the situation in your establishment: Do any of the following factors make addressing psychosocial risks more difficult than addressing other health risks? Reluctance to talk openly about these issues <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report having one of the risk factors listed.'],
		['Q166_1', 'Statutory employee representation forum or another form of non-union staff association', 'Which of the following forms of employee representation do you have in this establishment? Statutory employee representation forum or another form of non-union staff association <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to all, size depending on national thresholds for these bodies.'],
		['Q166_2', 'Workplace union representative', 'Which of the following forms of employee representation do you have in this establishment? Workplace union representative <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to all, size depending on national thresholds for these bodies.'],
		['Q166_3', 'Safety representative', 'Which of the following forms of employee representation do you have in this establishment? Safety representative <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to all, size depending on national thresholds for these bodies.'],
		['Q166_4', 'Safety committee', 'Which of the following forms of employee representation do you have in this establishment? Safety committee <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to all, size depending on national thresholds for these bodies.'],
		['Q258b', 'If measures have to be taken following a risk assessment: Are the employees usually involved in their design and implementation?', 'If measures have to be taken following a risk assessment: Are the employees usually involved in their design and implementation?  <br><br>(1) Yes <br>(2) No <br>(3) That depends on the type of measures <br>(9) No answer <br><br>Question asked to those establishments that report carrying out risk assessments regularly.'],
		['Q305', 'Did the employees have a role in the design and set-up of measures to address psychosocial risks?', 'Did the employees have a role in the design and set-up of measures to address psychosocial risks?  <br><br>(1) Yes <br>(2) No <br>(9) No answer <br><br>Question asked to those establishments that report some measure used to prevent psychosocial risks in the last 3 years.'],
		['Q350', 'How often do employee representatives and management come together to discuss health and safety?', 'How often do employee representatives and management come together to discuss health and safety?<br><br>(1) On a regular basis <br>(2) Only when particular issues arise <br>(3) Not at all <br>(7) Does not apply (there are no employee representatives) <br>(9) No answer <br><br>Question asked to those establishments that report some forms of employee representation.'],
		['Q351', 'And how often do controversies related to health and safety arise? Do they arise often, sometimes or practically never?', 'And how often do controversies related to health and safety arise? Do they arise often, sometimes or practically never?<br><br>(1) Often <br>(2) Sometimes <br>(3) Practically never <br>(9) No answer <br><br>Question asked to those establishments reporting that health and safety is discussed between employee representatives and the management.'],
		['Q354', 'Are safety representatives provided with any training during work time to help them perform their health and safety duties?', 'Are safety representatives provided with any training during work time to help them perform their health and safety duties? <br><br>(1) Yes <br>(2) No <br>(3) Yes, but only some of them <br>(9) No answer <br><br>Question asked to those establishments that report having health and safety representatives.'],
		['Q358', 'Are health and safety issues regularly discussed in staff or team meetings?', 'Are health and safety issues regularly discussed in staff or team meetings?<br><br>(1) Yes <br>(2) No <br>(3) In some departments only <br>(9) No answer']
	];
