//Auto Generated file
var subset_
	 = [
	
		['Sectorgrp', 'Sektor djelatnosti'],
		['Size', 'Veličina poslovne jedinice']
	];
var subset_subsetValue
	 = [
	
		['Sectorgrp', 'All', 'Sve'],
		['Sectorgrp', '1--A', 'Poljoprivreda, šumarstvo i ribarstvo'],
		['Sectorgrp', '2--BDEF', 'Građevinarstvo, gospodarenje otpadom, opskrba vodom i električnom energijom'],
		['Sectorgrp', '3--C', 'Proizvodnja'],
		['Sectorgrp', '4--GHIR', 'Trgovina, prijevoz, prehrana/smještaj i rekreacija'],
		['Sectorgrp', '5--JKLMNS', 'Informacijske tehnologije, financije, nekretnine i ostale tehničke znanstvene ili osobne usluge'],
		['Sectorgrp', '6--O', 'Javna uprava'],
		['Sectorgrp', '7--PQ', 'Obrazovanje, zdravstvena zaštita i socijalna skrb'],
		['Size', 'All', 'Sve'],
		['Size', '1--5-to-9', 'od 5 do 9 radnika'],
		['Size', '2--10-to-49', 'od 10 do 49 radnika'],
		['Size', '3--50-249', 'od 50 do 249 radnika'],
		['Size', '4--250-', '250 ili više radnika']
	];
var topic_
	 = [
	
		['', 'Svi (108)'],
		['Ključni rezultati', 'Ključni rezultati (24)'],
		['Poticaji i prepreke', 'Poticaji i prepreke (17)'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Psihosocijalni rizici i upravljanje takvim rizicima (21)'],
		['Sudjelovanje radnika', 'Sudjelovanje radnika (10)'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Upravljanje sigurnošću i zdravljem na radu (60)']
	];
var topic_question
	 = [
	
		['Ključni rezultati', 'Q200_1', 'Čimbenici rizika prisutni u poslovnoj jedinici: Zamorni ili bolni položaji'],
		['Ključni rezultati', 'Q200_2', 'Čimbenici rizika prisutni u poslovnoj jedinici: Podizanje ili premještanje ljudi ili teškog tereta'],
		['Ključni rezultati', 'Q200_3', 'Čimbenici rizika prisutni u poslovnoj jedinici: Velika buka'],
		['Ključni rezultati', 'Q200_4', 'Čimbenici rizika prisutni u poslovnoj jedinici: Ponavljajući pokreti šaka ili ruku'],
		['Ključni rezultati', 'Q200_5', 'Čimbenici rizika prisutni u poslovnoj jedinici: Vrućina, hladnoća ili propuh'],
		['Ključni rezultati', 'Q200_6', 'Čimbenici rizika prisutni u poslovnoj jedinici: Rizik od nesreća sa strojevima'],
		['Ključni rezultati', 'Q200_7', 'Čimbenici rizika prisutni u poslovnoj jedinici: Rizik od nesreća s vozilima tijekom rada'],
		['Ključni rezultati', 'Q200_8', 'Čimbenici rizika prisutni u poslovnoj jedinici: Kemijske ili biološke tvari'],
		['Ključni rezultati', 'Q200_9', 'Čimbenici rizika prisutni u poslovnoj jedinici: Povećani rizik od skliznuća, spoticanja i padova'],
		['Ključni rezultati', 'Q201_1', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Pritisak zbog kratkih vremenskih rokova'],
		['Ključni rezultati', 'Q201_2', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Loša komunikacija ili suradnja'],
		['Ključni rezultati', 'Q201_3', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Nedostatan utjecaj radnika'],
		['Ključni rezultati', 'Q201_4', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Strah od gubitka posla'],
		['Ključni rezultati', 'Q201_5', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Zahtjevni klijenti, pacijenti, učenici'],
		['Ključni rezultati', 'Q201_6', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Dugo ili neujednačeno radno vrijeme'],
		['Ključni rezultati', 'Q201_7', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Diskriminacija'],
		['Ključni rezultati', 'Q250', 'Procjene rizika na radnom mjestu'],
		['Ključni rezultati', 'Q251', 'Procjene rizika uglavnom provodi interno osoblje ili vanjski pružatelji usluga'],
		['Ključni rezultati', 'Q264_1', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Ispunjavanje zakonske obveze'],
		['Ključni rezultati', 'Q264_2', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Ispunjavanje očekivanja radnika'],
		['Ključni rezultati', 'Q264_4', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Povećavanje produktivnosti'],
		['Ključni rezultati', 'Q264_5', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Reputacija organizacije'],
		['Ključni rezultati', 'Q264_6', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Izbjegavanje novčanih kazni inspekcije rada'],
		['Ključni rezultati', 'Q307', 'Dovoljno informacija o tome kako uključiti psihosocijalne rizike u procjene rizika'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q150_1', 'Korištenje usluga zaštite na radu: Liječnik medicine rada'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q150_2', 'Korištenje usluga zaštite na radu: Psiholog'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q150_3', 'Korištenje usluga zaštite na radu: Stručnjak koji se bavi ergonomskim dizajnom i opremanjem radnih mjesta'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q150_4', 'Korištenje usluga zaštite na radu: Stručnjak za opća pitanja zaštite na radu'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q150_5', 'Korištenje usluga zaštite na radu: Stručnjak za prevenciju nesreća'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q155', 'Zaposlenicima je dostupan dokument koji objašnjava odgovornosti i procedure koje se odnose na zaštitu na radu '],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q156', 'Svake godine određuje se proračun za mjere i opremu za zaštitu na radu'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q158_1', 'Mjere za promicanje važnosti zdravog načina života među zaposlenicima: Podizanje svijesti o zdravoj prehrani '],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q158_2', 'Mjere za promicanje važnosti zdravog načina života među zaposlenicima: Podizanje svijesti o prevenciji ovisnosti'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q158_3', 'Mjere za promicanje važnosti zdravog načina života među zaposlenicima: Poticanje na bavljenje sportskim aktivnostima izvan radnog vremena'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q158_4', 'Mjere za promicanje važnosti zdravog načina života među zaposlenicima: Poticanje na izvođenje vježbi za tijelo na radnom mjestu'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q160', 'Rutinska analiza bolovanja'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q165', 'Posjet inspekcije rada u zadnje tri godine radi provjere zdravstvenih i sigurnosnih uvjeta'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q200_1', 'Čimbenici rizika prisutni u poslovnoj jedinici: Zamorni ili bolni položaji'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q200_2', 'Čimbenici rizika prisutni u poslovnoj jedinici: Podizanje ili premještanje ljudi ili teškog tereta'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q200_3', 'Čimbenici rizika prisutni u poslovnoj jedinici: Velika buka'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q200_4', 'Čimbenici rizika prisutni u poslovnoj jedinici: Ponavljajući pokreti šaka ili ruku'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q200_5', 'Čimbenici rizika prisutni u poslovnoj jedinici: Vrućina, hladnoća ili propuh'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q200_6', 'Čimbenici rizika prisutni u poslovnoj jedinici: Rizik od nesreća sa strojevima'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q200_7', 'Čimbenici rizika prisutni u poslovnoj jedinici: Rizik od nesreća s vozilima tijekom rada'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q200_8', 'Čimbenici rizika prisutni u poslovnoj jedinici: Kemijske ili biološke tvari'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q200_9', 'Čimbenici rizika prisutni u poslovnoj jedinici: Povećani rizik od skliznuća, spoticanja i padova'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q202_1', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Zamorni ili bolni položaji'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q202_2', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Podizanje ili premještanje ljudi ili teškog tereta'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q202_3', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Velika buka'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q202_4', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Ponavljajući pokreti šaka ili ruku'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q202_5', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Vrućina, hladnoća ili propuh'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q202_6', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Rizik od nesreća sa strojevima'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q202_7', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Rizik od nesreća s vozilima tijekom rada'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q202_8', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Kemijske ili biološke tvari'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q202_9', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Povećan rizik od skliznuća, spoticanja i padova'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q250', 'Procjene rizika na radnom mjestu'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q251', 'Procjene rizika uglavnom provodi interno osoblje ili vanjski pružatelji usluga'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q252_1', 'Procijenjeni aspekti u procjenama rizika na radnom mjestu: Sigurnost strojeva, opreme i instalacija'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q252_2', 'Procijenjeni aspekti u procjenama rizika na radnom mjestu: Opasne tvari'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q252_3', 'Procijenjeni aspekti u procjenama rizika na radnom mjestu: Držanje tijela pri radu, fizičko opterećenje pri radu i ponavljajući pokreti'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q252_4', 'Procijenjeni aspekti u procjenama rizika na radnom mjestu: Izloženost buci, vibracijama, vrućini ili hladnoći'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q252_5', 'Procijenjeni aspekti u procjenama rizika na radnom mjestu: Odnosi nadređenih i podređenih'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q252_6', 'Procijenjeni aspekti u procjenama rizika na radnom mjestu: Organizacijski aspekti'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q254gr', 'Godina zadnje procjene rizika na radnom mjestu'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q255', 'Procjena rizika na radnom mjestu dokumentirana u pisanom obliku'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q256_1', 'Osobe kojima se dostavljaju rezultati procjena rizika na radnom mjestu: Upravi'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q256_2', 'Osobe kojima se dostavljaju rezultati procjena rizika na radnom mjestu: Povjerenicima radnika za zaštitu na radu'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q256_3', 'Osobe kojima se dostavljaju rezultati procjena rizika na radnom mjestu: Radničkom vijeću'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q256_4', 'Osobe kojima se dostavljaju rezultati procjena rizika na radnom mjestu: Sindikatu'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q256_5', 'Osobe kojima se dostavljaju rezultati procjena rizika na radnom mjestu: Radnicima'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q259', 'Procedure procjena rizika smatraju se korisnim načinom upravljanja zaštitom na radu'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q261_1', 'Razlozi zašto se procjene rizika na radnom mjestu ne provode redovito: Opasnosti i rizici već su poznati'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q261_2', 'Razlozi zašto se procjene rizika na radnom mjestu ne provode redovito: Nema većih problema'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q261_3', 'Razlozi zašto se procjene rizika na radnom mjestu ne provode redovito: Procedura je prenaporna'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q261_4', 'Razlozi zašto se procjene rizika na radnom mjestu ne provode redovito: Nedostatak potrebnog stručnog znanja'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q308_1', 'Preventivne mjere koje se odnose na probleme mišićno-koštanog sustava: Oprema za pomoć pri podizanju ili premještanju tereta'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q308_2', 'Preventivne mjere koje se odnose na probleme mišićno-koštanog sustava: Rotiranje zadataka kako bi se smanjio tjelesni napor'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q308_3', 'Preventivne mjere koje se odnose na probleme mišićno-koštanog sustava: Poticanje redovitih pauza za ljude u neudobnim ili statičnim položajima'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q308_4', 'Preventivne mjere koje se odnose na probleme mišićno-koštanog sustava: Osiguravanje ergonomski oblikovane opreme'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q356_1', 'Obuka radnika: Pravilno korištenje i podešavanje radne opreme i namještaja'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q356_2', 'Obuka radnika: Uporaba opasnih tvari'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q356_3', 'Obuka radnika: Načini sprječavanja psihosocijalnih rizika'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q356_4', 'Obuka radnika: Načini podizanja i premještanja teških tereta ili ljudi'],
		['Upravljanje sigurnošću i zdravljem na radu', 'Q356_5', 'Obuka radnika: Postupci u slučaju opasnosti'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q201_1', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Pritisak zbog kratkih vremenskih rokova'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q201_2', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Loša komunikacija ili suradnja'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q201_3', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Nedostatan utjecaj radnika'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q201_4', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Strah od gubitka posla'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q201_5', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Zahtjevni klijenti, pacijenti, učenici'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q201_6', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Dugo ili neujednačeno radno vrijeme'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q201_7', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Diskriminacija'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q202_10', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Pritisak zbog kratkih vremenskih rokova'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q202_11', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Loša komunikacija ili suradnja'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q202_12', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Nedostatan utjecaj radnika'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q202_13', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Strah od gubitka posla'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q202_14', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Zahtjevni klijenti, pacijenti, učenici'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q202_15', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Dugo ili neujednačeno radno vrijeme'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q300', 'Akcijski plan za prevenciju stresa povezanog s poslom'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q301', 'Procedure za rješavanje slučajeva zlostavljanja ili uznemiravanja'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q302', 'Procedure za rješavanje slučajeva prijetnji, zlostavljanja ili vrijeđanja'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q303_1', 'Mjere za sprječavanje psihosocijalnih rizika u zadnje tri godine: Reorganizacija posla s ciljem smanjenja opterećenosti poslom i pritiska na radnom mjestu'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q303_2', 'Mjere za sprječavanje psihosocijalnih rizika u zadnje tri godine: Povjerljivo savjetovanje za radnike'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q303_3', 'Mjere za sprječavanje psihosocijalnih rizika u zadnje tri godine: Uvođenje postupka za rješavanje sukoba'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q303_4', 'Mjere za sprječavanje psihosocijalnih rizika u zadnje tri godine: Interveniranje u slučaju predugog ili neujednačenog radnog vremena'],
		['Psihosocijalni rizici i upravljanje takvim rizicima', 'Q307', 'Dovoljno informacija o tome kako uključiti psihosocijalne rizike u procjene rizika'],
		['Poticaji i prepreke', 'Q264_1', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Ispunjavanje zakonske obveze'],
		['Poticaji i prepreke', 'Q264_2', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Ispunjavanje očekivanja radnika'],
		['Poticaji i prepreke', 'Q264_4', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Povećavanje produktivnosti'],
		['Poticaji i prepreke', 'Q264_5', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Reputacija organizacije'],
		['Poticaji i prepreke', 'Q264_6', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Izbjegavanje novčanih kazni inspekcije rada'],
		['Poticaji i prepreke', 'Q265_1', 'Glavni problemi u provedbi zaštite na radu: Nedostatak vremena ili osoblja'],
		['Poticaji i prepreke', 'Q265_2', 'Glavni problemi u provedbi zaštite na radu: Nedostatak novca'],
		['Poticaji i prepreke', 'Q265_3', 'Glavni problemi u provedbi zaštite na radu: Nedovoljna osviještenost osoblja'],
		['Poticaji i prepreke', 'Q265_4', 'Glavni problemi u provedbi zaštite na radu: Nedovoljna osviještenost uprave'],
		['Poticaji i prepreke', 'Q265_5', 'Glavni problemi u provedbi zaštite na radu: Nedostatak stručnog znanja ili podrške stručnjaka'],
		['Poticaji i prepreke', 'Q265_6', 'Glavni problemi u provedbi zaštite na radu: Papirologija'],
		['Poticaji i prepreke', 'Q265_7', 'Glavni problemi u provedbi zaštite na radu: Složenost zakonskih obveza'],
		['Poticaji i prepreke', 'Q304', 'Mjere potaknute konkretnim problemima'],
		['Poticaji i prepreke', 'Q306a_3', 'Poteškoće u rješavanju psihosocijalnih rizika: Nedovoljna osviještenost osoblja'],
		['Poticaji i prepreke', 'Q306a_4', 'Poteškoće u rješavanju psihosocijalnih rizika: Nedovoljna osviještenost uprave'],
		['Poticaji i prepreke', 'Q306a_5', 'Poteškoće u rješavanju psihosocijalnih rizika: Nedostatak stručnog znanja ili podrške stručnjaka'],
		['Poticaji i prepreke', 'Q306a_6', 'Poteškoće u rješavanju psihosocijalnih rizika: Nespremnost za otvoreni razgovor o ovim problemima'],
		['Sudjelovanje radnika', 'Q166_1', 'Oblici zastupanja radnika: Radničko vijeće'],
		['Sudjelovanje radnika', 'Q166_2', 'Oblici zastupanja radnika: Sindikat'],
		['Sudjelovanje radnika', 'Q166_3', 'Oblici zastupanja radnika: Povjerenik radnika za zaštitu na radu'],
		['Sudjelovanje radnika', 'Q166_4', 'Oblici zastupanja radnika: Odbor za zaštitu na radu'],
		['Sudjelovanje radnika', 'Q258b', 'Radnici uključeni u osmišljavanje mjera na temelju procjene rizika'],
		['Sudjelovanje radnika', 'Q305', 'Radnici sudjeluju u osmišljavanju mjera za sprječavanje psihosocijalnih rizika'],
		['Sudjelovanje radnika', 'Q350', 'Koliko su česte rasprave o zaštiti na radu između radničkih povjerenika i uprave'],
		['Sudjelovanje radnika', 'Q351', 'Koliko često izbiju nesuglasice zbog zaštite na radu'],
		['Sudjelovanje radnika', 'Q354', 'Povjerenici radnika za zaštitu na radu pohađaju obuku tijekom obavljanja posla'],
		['Sudjelovanje radnika', 'Q358', 'O pitanjima zaštite na radu raspravlja se na sastancima osoblja ili tima']
	];
var question_
	 = [
	
		['Q200_1', 'Čimbenici rizika prisutni u poslovnoj jedinici: Zamorni ili bolni položaji'],
		['Q200_2', 'Čimbenici rizika prisutni u poslovnoj jedinici: Podizanje ili premještanje ljudi ili teškog tereta'],
		['Q200_3', 'Čimbenici rizika prisutni u poslovnoj jedinici: Velika buka'],
		['Q200_4', 'Čimbenici rizika prisutni u poslovnoj jedinici: Ponavljajući pokreti šaka ili ruku'],
		['Q200_5', 'Čimbenici rizika prisutni u poslovnoj jedinici: Vrućina, hladnoća ili propuh'],
		['Q200_6', 'Čimbenici rizika prisutni u poslovnoj jedinici: Rizik od nesreća sa strojevima'],
		['Q200_7', 'Čimbenici rizika prisutni u poslovnoj jedinici: Rizik od nesreća s vozilima tijekom rada'],
		['Q200_8', 'Čimbenici rizika prisutni u poslovnoj jedinici: Kemijske ili biološke tvari'],
		['Q200_9', 'Čimbenici rizika prisutni u poslovnoj jedinici: Povećani rizik od skliznuća, spoticanja i padova'],
		['Q201_1', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Pritisak zbog kratkih vremenskih rokova'],
		['Q201_2', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Loša komunikacija ili suradnja'],
		['Q201_3', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Nedostatan utjecaj radnika'],
		['Q201_4', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Strah od gubitka posla'],
		['Q201_5', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Zahtjevni klijenti, pacijenti, učenici'],
		['Q201_6', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Dugo ili neujednačeno radno vrijeme'],
		['Q201_7', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Diskriminacija'],
		['Q250', 'Procjene rizika na radnom mjestu'],
		['Q251', 'Procjene rizika uglavnom provodi interno osoblje ili vanjski pružatelji usluga'],
		['Q264_1', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Ispunjavanje zakonske obveze'],
		['Q264_2', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Ispunjavanje očekivanja radnika'],
		['Q264_4', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Povećavanje produktivnosti'],
		['Q264_5', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Reputacija organizacije'],
		['Q264_6', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Izbjegavanje novčanih kazni inspekcije rada'],
		['Q307', 'Dovoljno informacija o tome kako uključiti psihosocijalne rizike u procjene rizika'],
		['Q150_1', 'Korištenje usluga zaštite na radu: Liječnik medicine rada'],
		['Q150_2', 'Korištenje usluga zaštite na radu: Psiholog'],
		['Q150_3', 'Korištenje usluga zaštite na radu: Stručnjak koji se bavi ergonomskim dizajnom i opremanjem radnih mjesta'],
		['Q150_4', 'Korištenje usluga zaštite na radu: Stručnjak za opća pitanja zaštite na radu'],
		['Q150_5', 'Korištenje usluga zaštite na radu: Stručnjak za prevenciju nesreća'],
		['Q155', 'Zaposlenicima je dostupan dokument koji objašnjava odgovornosti i procedure koje se odnose na zaštitu na radu '],
		['Q156', 'Svake godine određuje se proračun za mjere i opremu za zaštitu na radu'],
		['Q158_1', 'Mjere za promicanje važnosti zdravog načina života među zaposlenicima: Podizanje svijesti o zdravoj prehrani '],
		['Q158_2', 'Mjere za promicanje važnosti zdravog načina života među zaposlenicima: Podizanje svijesti o prevenciji ovisnosti'],
		['Q158_3', 'Mjere za promicanje važnosti zdravog načina života među zaposlenicima: Poticanje na bavljenje sportskim aktivnostima izvan radnog vremena'],
		['Q158_4', 'Mjere za promicanje važnosti zdravog načina života među zaposlenicima: Poticanje na izvođenje vježbi za tijelo na radnom mjestu'],
		['Q160', 'Rutinska analiza bolovanja'],
		['Q165', 'Posjet inspekcije rada u zadnje tri godine radi provjere zdravstvenih i sigurnosnih uvjeta'],
		['Q200_1', 'Čimbenici rizika prisutni u poslovnoj jedinici: Zamorni ili bolni položaji'],
		['Q200_2', 'Čimbenici rizika prisutni u poslovnoj jedinici: Podizanje ili premještanje ljudi ili teškog tereta'],
		['Q200_3', 'Čimbenici rizika prisutni u poslovnoj jedinici: Velika buka'],
		['Q200_4', 'Čimbenici rizika prisutni u poslovnoj jedinici: Ponavljajući pokreti šaka ili ruku'],
		['Q200_5', 'Čimbenici rizika prisutni u poslovnoj jedinici: Vrućina, hladnoća ili propuh'],
		['Q200_6', 'Čimbenici rizika prisutni u poslovnoj jedinici: Rizik od nesreća sa strojevima'],
		['Q200_7', 'Čimbenici rizika prisutni u poslovnoj jedinici: Rizik od nesreća s vozilima tijekom rada'],
		['Q200_8', 'Čimbenici rizika prisutni u poslovnoj jedinici: Kemijske ili biološke tvari'],
		['Q200_9', 'Čimbenici rizika prisutni u poslovnoj jedinici: Povećani rizik od skliznuća, spoticanja i padova'],
		['Q202_1', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Zamorni ili bolni položaji'],
		['Q202_2', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Podizanje ili premještanje ljudi ili teškog tereta'],
		['Q202_3', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Velika buka'],
		['Q202_4', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Ponavljajući pokreti šaka ili ruku'],
		['Q202_5', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Vrućina, hladnoća ili propuh'],
		['Q202_6', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Rizik od nesreća sa strojevima'],
		['Q202_7', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Rizik od nesreća s vozilima tijekom rada'],
		['Q202_8', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Kemijske ili biološke tvari'],
		['Q202_9', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Povećan rizik od skliznuća, spoticanja i padova'],
		['Q250', 'Procjene rizika na radnom mjestu'],
		['Q251', 'Procjene rizika uglavnom provodi interno osoblje ili vanjski pružatelji usluga'],
		['Q252_1', 'Procijenjeni aspekti u procjenama rizika na radnom mjestu: Sigurnost strojeva, opreme i instalacija'],
		['Q252_2', 'Procijenjeni aspekti u procjenama rizika na radnom mjestu: Opasne tvari'],
		['Q252_3', 'Procijenjeni aspekti u procjenama rizika na radnom mjestu: Držanje tijela pri radu, fizičko opterećenje pri radu i ponavljajući pokreti'],
		['Q252_4', 'Procijenjeni aspekti u procjenama rizika na radnom mjestu: Izloženost buci, vibracijama, vrućini ili hladnoći'],
		['Q252_5', 'Procijenjeni aspekti u procjenama rizika na radnom mjestu: Odnosi nadređenih i podređenih'],
		['Q252_6', 'Procijenjeni aspekti u procjenama rizika na radnom mjestu: Organizacijski aspekti'],
		['Q254gr', 'Godina zadnje procjene rizika na radnom mjestu'],
		['Q255', 'Procjena rizika na radnom mjestu dokumentirana u pisanom obliku'],
		['Q256_1', 'Osobe kojima se dostavljaju rezultati procjena rizika na radnom mjestu: Upravi'],
		['Q256_2', 'Osobe kojima se dostavljaju rezultati procjena rizika na radnom mjestu: Povjerenicima radnika za zaštitu na radu'],
		['Q256_3', 'Osobe kojima se dostavljaju rezultati procjena rizika na radnom mjestu: Radničkom vijeću'],
		['Q256_4', 'Osobe kojima se dostavljaju rezultati procjena rizika na radnom mjestu: Sindikatu'],
		['Q256_5', 'Osobe kojima se dostavljaju rezultati procjena rizika na radnom mjestu: Radnicima'],
		['Q259', 'Procedure procjena rizika smatraju se korisnim načinom upravljanja zaštitom na radu'],
		['Q261_1', 'Razlozi zašto se procjene rizika na radnom mjestu ne provode redovito: Opasnosti i rizici već su poznati'],
		['Q261_2', 'Razlozi zašto se procjene rizika na radnom mjestu ne provode redovito: Nema većih problema'],
		['Q261_3', 'Razlozi zašto se procjene rizika na radnom mjestu ne provode redovito: Procedura je prenaporna'],
		['Q261_4', 'Razlozi zašto se procjene rizika na radnom mjestu ne provode redovito: Nedostatak potrebnog stručnog znanja'],
		['Q308_1', 'Preventivne mjere koje se odnose na probleme mišićno-koštanog sustava: Oprema za pomoć pri podizanju ili premještanju tereta'],
		['Q308_2', 'Preventivne mjere koje se odnose na probleme mišićno-koštanog sustava: Rotiranje zadataka kako bi se smanjio tjelesni napor'],
		['Q308_3', 'Preventivne mjere koje se odnose na probleme mišićno-koštanog sustava: Poticanje redovitih pauza za ljude u neudobnim ili statičnim položajima'],
		['Q308_4', 'Preventivne mjere koje se odnose na probleme mišićno-koštanog sustava: Osiguravanje ergonomski oblikovane opreme'],
		['Q356_1', 'Obuka radnika: Pravilno korištenje i podešavanje radne opreme i namještaja'],
		['Q356_2', 'Obuka radnika: Uporaba opasnih tvari'],
		['Q356_3', 'Obuka radnika: Načini sprječavanja psihosocijalnih rizika'],
		['Q356_4', 'Obuka radnika: Načini podizanja i premještanja teških tereta ili ljudi'],
		['Q356_5', 'Obuka radnika: Postupci u slučaju opasnosti'],
		['Q201_1', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Pritisak zbog kratkih vremenskih rokova'],
		['Q201_2', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Loša komunikacija ili suradnja'],
		['Q201_3', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Nedostatan utjecaj radnika'],
		['Q201_4', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Strah od gubitka posla'],
		['Q201_5', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Zahtjevni klijenti, pacijenti, učenici'],
		['Q201_6', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Dugo ili neujednačeno radno vrijeme'],
		['Q201_7', 'Psihosocijalni čimbenici rizika prisutni u poslovnoj jedinici: Diskriminacija'],
		['Q202_10', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Pritisak zbog kratkih vremenskih rokova'],
		['Q202_11', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Loša komunikacija ili suradnja'],
		['Q202_12', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Nedostatan utjecaj radnika'],
		['Q202_13', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Strah od gubitka posla'],
		['Q202_14', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Zahtjevni klijenti, pacijenti, učenici'],
		['Q202_15', 'Nedostatak informacija ili adekvatnih alata za učinkovito otklanjanje rizika: Dugo ili neujednačeno radno vrijeme'],
		['Q300', 'Akcijski plan za prevenciju stresa povezanog s poslom'],
		['Q301', 'Procedure za rješavanje slučajeva zlostavljanja ili uznemiravanja'],
		['Q302', 'Procedure za rješavanje slučajeva prijetnji, zlostavljanja ili vrijeđanja'],
		['Q303_1', 'Mjere za sprječavanje psihosocijalnih rizika u zadnje tri godine: Reorganizacija posla s ciljem smanjenja opterećenosti poslom i pritiska na radnom mjestu'],
		['Q303_2', 'Mjere za sprječavanje psihosocijalnih rizika u zadnje tri godine: Povjerljivo savjetovanje za radnike'],
		['Q303_3', 'Mjere za sprječavanje psihosocijalnih rizika u zadnje tri godine: Uvođenje postupka za rješavanje sukoba'],
		['Q303_4', 'Mjere za sprječavanje psihosocijalnih rizika u zadnje tri godine: Interveniranje u slučaju predugog ili neujednačenog radnog vremena'],
		['Q307', 'Dovoljno informacija o tome kako uključiti psihosocijalne rizike u procjene rizika'],
		['Q264_1', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Ispunjavanje zakonske obveze'],
		['Q264_2', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Ispunjavanje očekivanja radnika'],
		['Q264_4', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Povećavanje produktivnosti'],
		['Q264_5', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Reputacija organizacije'],
		['Q264_6', 'Razlozi za provedbu zaštite na radu u poslovnoj jedinici: Izbjegavanje novčanih kazni inspekcije rada'],
		['Q265_1', 'Glavni problemi u provedbi zaštite na radu: Nedostatak vremena ili osoblja'],
		['Q265_2', 'Glavni problemi u provedbi zaštite na radu: Nedostatak novca'],
		['Q265_3', 'Glavni problemi u provedbi zaštite na radu: Nedovoljna osviještenost osoblja'],
		['Q265_4', 'Glavni problemi u provedbi zaštite na radu: Nedovoljna osviještenost uprave'],
		['Q265_5', 'Glavni problemi u provedbi zaštite na radu: Nedostatak stručnog znanja ili podrške stručnjaka'],
		['Q265_6', 'Glavni problemi u provedbi zaštite na radu: Papirologija'],
		['Q265_7', 'Glavni problemi u provedbi zaštite na radu: Složenost zakonskih obveza'],
		['Q304', 'Mjere potaknute konkretnim problemima'],
		['Q306a_3', 'Poteškoće u rješavanju psihosocijalnih rizika: Nedovoljna osviještenost osoblja'],
		['Q306a_4', 'Poteškoće u rješavanju psihosocijalnih rizika: Nedovoljna osviještenost uprave'],
		['Q306a_5', 'Poteškoće u rješavanju psihosocijalnih rizika: Nedostatak stručnog znanja ili podrške stručnjaka'],
		['Q306a_6', 'Poteškoće u rješavanju psihosocijalnih rizika: Nespremnost za otvoreni razgovor o ovim problemima'],
		['Q166_1', 'Oblici zastupanja radnika: Radničko vijeće'],
		['Q166_2', 'Oblici zastupanja radnika: Sindikat'],
		['Q166_3', 'Oblici zastupanja radnika: Povjerenik radnika za zaštitu na radu'],
		['Q166_4', 'Oblici zastupanja radnika: Odbor za zaštitu na radu'],
		['Q258b', 'Radnici uključeni u osmišljavanje mjera na temelju procjene rizika'],
		['Q305', 'Radnici sudjeluju u osmišljavanju mjera za sprječavanje psihosocijalnih rizika'],
		['Q350', 'Koliko su česte rasprave o zaštiti na radu između radničkih povjerenika i uprave'],
		['Q351', 'Koliko često izbiju nesuglasice zbog zaštite na radu'],
		['Q354', 'Povjerenici radnika za zaštitu na radu pohađaju obuku tijekom obavljanja posla'],
		['Q358', 'O pitanjima zaštite na radu raspravlja se na sastancima osoblja ili tima']
	];
var question_answer
	 = [
	
		['Q150_1', '1--Yes', 'Da'],
		['Q150_1', '2--No', 'Ne'],
		['Q150_2', '1--Yes', 'Da'],
		['Q150_2', '2--No', 'Ne'],
		['Q150_3', '1--Yes', 'Da'],
		['Q150_3', '2--No', 'Ne'],
		['Q150_4', '1--Yes', 'Da'],
		['Q150_4', '2--No', 'Ne'],
		['Q150_5', '1--Yes', 'Da'],
		['Q150_5', '2--No', 'Ne'],
		['Q155', '1--Yes', 'Da'],
		['Q155', '2--No', 'Ne'],
		['Q155', '3--Yes--but-only-to-some-types-of-employees', 'Da, ali samo nekim kategorijama radnika'],
		['Q156', '1--Yes', 'Da'],
		['Q156', '2--No', 'Ne'],
		['Q158_1', '1--Yes', 'Da'],
		['Q158_1', '2--No', 'Ne'],
		['Q158_2', '1--Yes', 'Da'],
		['Q158_2', '2--No', 'Ne'],
		['Q158_3', '1--Yes', 'Da'],
		['Q158_3', '2--No', 'Ne'],
		['Q158_4', '1--Yes', 'Da'],
		['Q158_4', '2--No', 'Ne'],
		['Q160', '1--Yes', 'Da'],
		['Q160', '2--No', 'Ne'],
		['Q165', '1--Yes', 'Da'],
		['Q165', '2--No', 'Ne'],
		['Q166_1', '1--Yes', 'Da'],
		['Q166_1', '2--No', 'Ne'],
		['Q166_2', '1--Yes', 'Da'],
		['Q166_2', '2--No', 'Ne'],
		['Q166_3', '1--Yes', 'Da'],
		['Q166_3', '2--No', 'Ne'],
		['Q166_4', '1--Yes', 'Da'],
		['Q166_4', '2--No', 'Ne'],
		['Q200_1', '1--Yes', 'Da'],
		['Q200_1', '2--No', 'Ne'],
		['Q200_2', '1--Yes', 'Da'],
		['Q200_2', '2--No', 'Ne'],
		['Q200_3', '1--Yes', 'Da'],
		['Q200_3', '2--No', 'Ne'],
		['Q200_4', '1--Yes', 'Da'],
		['Q200_4', '2--No', 'Ne'],
		['Q200_5', '1--Yes', 'Da'],
		['Q200_5', '2--No', 'Ne'],
		['Q200_6', '1--Yes', 'Da'],
		['Q200_6', '2--No', 'Ne'],
		['Q200_7', '1--Yes', 'Da'],
		['Q200_7', '2--No', 'Ne'],
		['Q200_8', '1--Yes', 'Da'],
		['Q200_8', '2--No', 'Ne'],
		['Q200_9', '1--Yes', 'Da'],
		['Q200_9', '2--No', 'Ne'],
		['Q201_1', '1--Yes', 'Da'],
		['Q201_1', '2--No', 'Ne'],
		['Q201_2', '1--Yes', 'Da'],
		['Q201_2', '2--No', 'Ne'],
		['Q201_3', '1--Yes', 'Da'],
		['Q201_3', '2--No', 'Ne'],
		['Q201_4', '1--Yes', 'Da'],
		['Q201_4', '2--No', 'Ne'],
		['Q201_5', '1--Yes', 'Da'],
		['Q201_5', '2--No', 'Ne'],
		['Q201_6', '1--Yes', 'Da'],
		['Q201_6', '2--No', 'Ne'],
		['Q201_7', '1--Yes', 'Da'],
		['Q201_7', '2--No', 'Ne'],
		['Q202_1', '1--Yes', 'Da'],
		['Q202_1', '2--No', 'Ne'],
		['Q202_10', '1--Yes', 'Da'],
		['Q202_10', '2--No', 'Ne'],
		['Q202_11', '1--Yes', 'Da'],
		['Q202_11', '2--No', 'Ne'],
		['Q202_12', '1--Yes', 'Da'],
		['Q202_12', '2--No', 'Ne'],
		['Q202_13', '1--Yes', 'Da'],
		['Q202_13', '2--No', 'Ne'],
		['Q202_14', '1--Yes', 'Da'],
		['Q202_14', '2--No', 'Ne'],
		['Q202_15', '1--Yes', 'Da'],
		['Q202_15', '2--No', 'Ne'],
		['Q202_2', '1--Yes', 'Da'],
		['Q202_2', '2--No', 'Ne'],
		['Q202_3', '1--Yes', 'Da'],
		['Q202_3', '2--No', 'Ne'],
		['Q202_4', '1--Yes', 'Da'],
		['Q202_4', '2--No', 'Ne'],
		['Q202_5', '1--Yes', 'Da'],
		['Q202_5', '2--No', 'Ne'],
		['Q202_6', '1--Yes', 'Da'],
		['Q202_6', '2--No', 'Ne'],
		['Q202_7', '1--Yes', 'Da'],
		['Q202_7', '2--No', 'Ne'],
		['Q202_8', '1--Yes', 'Da'],
		['Q202_8', '2--No', 'Ne'],
		['Q202_9', '1--Yes', 'Da'],
		['Q202_9', '2--No', 'Ne'],
		['Q250', '1--Yes', 'Da'],
		['Q250', '2--No', 'Ne'],
		['Q251', '1--Conducted-mainly-by-internal-staff', 'Uglavnom interno osoblje'],
		['Q251', '2--Contracted-mainly-to-external-providers', 'Uglavnom vanjski pružatelji usluga'],
		['Q251', '3--Both-about-equally', 'I jedni i drugi podjednako'],
		['Q252_1', '1--Yes', 'Da'],
		['Q252_1', '2--No', 'Ne'],
		['Q252_2', '1--Yes', 'Da'],
		['Q252_2', '2--No', 'Ne'],
		['Q252_3', '1--Yes', 'Da'],
		['Q252_3', '2--No', 'Ne'],
		['Q252_4', '1--Yes', 'Da'],
		['Q252_4', '2--No', 'Ne'],
		['Q252_5', '1--Yes', 'Da'],
		['Q252_5', '2--No', 'Ne'],
		['Q252_6', '1--Yes', 'Da'],
		['Q252_6', '2--No', 'Ne'],
		['Q254gr', '1--2010', '2010'],
		['Q254gr', '2--2011', '2011'],
		['Q254gr', '3--2012', '2012'],
		['Q254gr', '4--2013', '2013'],
		['Q254gr', '5--2014', '2014'],
		['Q254gr', '6--before-2010', 'prije 2010.'],
		['Q254gr', '7--don-t-know', 'Ne znam'],
		['Q255', '1--Yes', 'Da'],
		['Q255', '2--No', 'Ne'],
		['Q256_1', '1--Yes', 'Da'],
		['Q256_1', '2--No', 'Ne'],
		['Q256_2', '1--Yes', 'Da'],
		['Q256_2', '2--No', 'Ne'],
		['Q256_3', '1--Yes', 'Da'],
		['Q256_3', '2--No', 'Ne'],
		['Q256_4', '1--Yes', 'Da'],
		['Q256_4', '2--No', 'Ne'],
		['Q256_5', '1--Yes', 'Da'],
		['Q256_5', '2--No', 'Ne'],
		['Q258b', '1--Yes', 'Da'],
		['Q258b', '2--No', 'Ne'],
		['Q258b', '3--That-depends-on-the-type-of-measures', 'To ovisi o tipu mjera'],
		['Q259', '1--Yes', 'Da'],
		['Q259', '2--No', 'Ne'],
		['Q259', '3--There-are-conflicting-views-about-this', 'Postoje oprečni stavovi o tome'],
		['Q261_1', '1--Yes', 'Da'],
		['Q261_1', '2--No', 'Ne'],
		['Q261_2', '1--Yes', 'Da'],
		['Q261_2', '2--No', 'Ne'],
		['Q261_3', '1--Yes', 'Da'],
		['Q261_3', '2--No', 'Ne'],
		['Q261_4', '1--Yes', 'Da'],
		['Q261_4', '2--No', 'Ne'],
		['Q264_1', '1--Major-reason', 'Važan razlog'],
		['Q264_1', '2--Minor-reason', 'Manje važan razlog'],
		['Q264_1', '3--Not-a-reason', 'Uopće nije razlog'],
		['Q264_2', '1--Major-reason', 'Važan razlog'],
		['Q264_2', '2--Minor-reason', 'Manje važan razlog'],
		['Q264_2', '3--Not-a-reason', 'Uopće nije razlog'],
		['Q264_4', '1--Major-reason', 'Važan razlog'],
		['Q264_4', '2--Minor-reason', 'Manje važan razlog'],
		['Q264_4', '3--Not-a-reason', 'Uopće nije razlog'],
		['Q264_5', '1--Major-reason', 'Važan razlog'],
		['Q264_5', '2--Minor-reason', 'Manje važan razlog'],
		['Q264_5', '3--Not-a-reason', 'Uopće nije razlog'],
		['Q264_6', '1--Major-reason', 'Važan razlog'],
		['Q264_6', '2--Minor-reason', 'Manje važan razlog'],
		['Q264_6', '3--Not-a-reason', 'Uopće nije razlog'],
		['Q265_1', '1--Major-difficulty', 'Veliki problem'],
		['Q265_1', '2--Minor-difficulty', 'Manji problem'],
		['Q265_1', '3--Not-a-difficulty', 'Uopće nije problem'],
		['Q265_2', '1--Major-difficulty', 'Veliki problem'],
		['Q265_2', '2--Minor-difficulty', 'Manji problem'],
		['Q265_2', '3--Not-a-difficulty', 'Uopće nije problem'],
		['Q265_3', '1--Major-difficulty', 'Veliki problem'],
		['Q265_3', '2--Minor-difficulty', 'Manji problem'],
		['Q265_3', '3--Not-a-difficulty', 'Uopće nije problem'],
		['Q265_4', '1--Major-difficulty', 'Veliki problem'],
		['Q265_4', '2--Minor-difficulty', 'Manji problem'],
		['Q265_4', '3--Not-a-difficulty', 'Uopće nije problem'],
		['Q265_5', '1--Major-difficulty', 'Veliki problem'],
		['Q265_5', '2--Minor-difficulty', 'Manji problem'],
		['Q265_5', '3--Not-a-difficulty', 'Uopće nije problem'],
		['Q265_6', '1--Major-difficulty', 'Veliki problem'],
		['Q265_6', '2--Minor-difficulty', 'Manji problem'],
		['Q265_6', '3--Not-a-difficulty', 'Uopće nije problem'],
		['Q265_7', '1--Major-difficulty', 'Veliki problem'],
		['Q265_7', '2--Minor-difficulty', 'Manji problem'],
		['Q265_7', '3--Not-a-difficulty', 'Uopće nije problem'],
		['Q300', '1--Yes', 'Da'],
		['Q300', '2--No', 'Ne'],
		['Q301', '1--Yes', 'Da'],
		['Q301', '2--No', 'Ne'],
		['Q302', '1--Yes', 'Da'],
		['Q302', '2--No', 'Ne'],
		['Q303_1', '1--Yes', 'Da'],
		['Q303_1', '2--No', 'Ne'],
		['Q303_2', '1--Yes', 'Da'],
		['Q303_2', '2--No', 'Ne'],
		['Q303_3', '1--Yes', 'Da'],
		['Q303_3', '2--No', 'Ne'],
		['Q303_4', '1--Yes', 'Da'],
		['Q303_4', '2--No', 'Ne'],
		['Q304', '1--Yes', 'Da'],
		['Q304', '2--No', 'Ne'],
		['Q304', '3--Partly', 'Djelomično'],
		['Q305', '1--Yes', 'Da'],
		['Q305', '2--No', 'Ne'],
		['Q306a_3', '1--Yes', 'Da'],
		['Q306a_3', '2--No', 'Ne'],
		['Q306a_4', '1--Yes', 'Da'],
		['Q306a_4', '2--No', 'Ne'],
		['Q306a_5', '1--Yes', 'Da'],
		['Q306a_5', '2--No', 'Ne'],
		['Q306a_6', '1--Yes', 'Da'],
		['Q306a_6', '2--No', 'Ne'],
		['Q307', '1--Yes', 'Da'],
		['Q307', '2--No', 'Ne'],
		['Q308_1', '1--Yes', 'Da'],
		['Q308_1', '2--No', 'Ne'],
		['Q308_2', '1--Yes', 'Da'],
		['Q308_2', '2--No', 'Ne'],
		['Q308_3', '1--Yes', 'Da'],
		['Q308_3', '2--No', 'Ne'],
		['Q308_4', '1--Yes', 'Da'],
		['Q308_4', '2--No', 'Ne'],
		['Q350', '1--Regularly', 'Redovito'],
		['Q350', '2--Only-when-particular-issues-arise', 'Samo kada se pojavi određeni problem'],
		['Q350', '3--Not-at-all', 'Uopće se ne događaju'],
		['Q351', '1--Often', 'Često'],
		['Q351', '2--Sometimes', 'Ponekad'],
		['Q351', '3--Practically-never', 'Gotovo nikada'],
		['Q354', '1--Yes', 'Da'],
		['Q354', '2--No', 'Ne'],
		['Q354', '3--Yes--but-only-some-of-them', 'Da, ali samo neki od njih'],
		['Q356_1', '1--Yes', 'Da'],
		['Q356_1', '2--No', 'Ne'],
		['Q356_2', '1--Yes', 'Da'],
		['Q356_2', '2--No', 'Ne'],
		['Q356_3', '1--Yes', 'Da'],
		['Q356_3', '2--No', 'Ne'],
		['Q356_4', '1--Yes', 'Da'],
		['Q356_4', '2--No', 'Ne'],
		['Q356_5', '1--Yes', 'Da'],
		['Q356_5', '2--No', 'Ne'],
		['Q358', '1--Yes', 'Da'],
		['Q358', '2--No', 'Ne'],
		['Q358', '3--In-some-departments-only', 'Samo u nekim odjelima']
	];
var country_
	 = [
	
		['AL', 'Albanija'],
		['AT', 'Austrija'],
		['BE', 'Belgija'],
		['BG', 'Bugarska'],
		['CH', 'Švicarska'],
		['CY', 'Cipar'],
		['CZ', 'Češka Republika'],
		['DE', 'Njemačka'],
		['DK', 'Danska'],
		['EE', 'Estonija'],
		['EL', 'Grčka'],
		['ES', 'Španjolska'],
		['FI', 'Finska'],
		['FR', 'Francuska'],
		['HR', 'Hrvatska'],
		['HU', 'Mađarska'],
		['IE', 'Irska'],
		['IS', 'Island'],
		['IT', 'Italija'],
		['LT', 'Litva'],
		['LU', 'Luksemburg'],
		['LV', 'Latvija'],
		['ME', 'Crna Gora'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Nizozemska'],
		['NO', 'Norveška'],
		['PL', 'Poljska'],
		['PT', 'Portugal'],
		['RO', 'Rumunjska'],
		['RS', 'Srbija'],
		['SE', 'Švedska'],
		['SI', 'Slovenija'],
		['SK', 'Slovačka'],
		['TR', 'Turska'],
		['UK', 'Ujedinjeno Kraljevstvo'],
		['EuropeanUnion', 'Europska unija']
	];
var question_meta
	 = [
	
		['Q200_1', 'Zamorni ili bolni položaji, uključujući dugo sjedenje', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Zamorni ili bolni položaji, uključujući dugo sjedenje<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_2', 'Podizanje ili premještanje ljudi ili teškog tereta', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Podizanje ili premještanje ljudi ili teškog tereta<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_3', 'Velika buka', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Velika buka<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_4', 'Ponavljajući pokreti šaka ili ruku', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Ponavljajući pokreti šaka ili ruku<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_5', 'Vrućina, hladnoća ili propuh', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Vrućina, hladnoća ili propuh<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_6', 'Rizik od nesreća prilikom rukovanja strojevima ili ručnim alatima', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Rizik od nesreća prilikom rukovanja strojevima ili ručnim alatima<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_7', 'Rizik od nesreća prilikom korištenja vozila tijekom obavljanja posla, ali ne i prilikom dolaska na radno mjesto i odlaska s njega', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Rizik od nesreća prilikom korištenja vozila tijekom obavljanja posla, ali ne i prilikom dolaska na radno mjesto i odlaska s njega<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_8', 'Kemijske i biološke tvari u obliku tekućine, isparavanja ili praha', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Kemijske i biološke tvari u obliku tekućine, isparavanja ili praha<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_9', 'Povećani rizik od skliznuća, spoticanja i padova', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Povećani rizik od skliznuća, spoticanja i padova<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q201_1', 'Pritisak zbog kratkih vremenskih rokova', 'Osim prethodno navedenih rizika, određeni rizici za zdravlje mogu proizaći iz načina na koji je organizirano poslovanje, društvenih odnosa na radnom mjestu ili gospodarske situacije. Za svaki od čimbenika rizika koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici. Pritisak zbog kratkih vremenskih rokova<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q201_2', 'Loša komunikacija ili suradnja unutar organizacije', 'Osim prethodno navedenih rizika, određeni rizici za zdravlje mogu proizaći iz načina na koji je organizirano poslovanje, društvenih odnosa na radnom mjestu ili gospodarske situacije. Za svaki od čimbenika rizika koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici. Loša komunikacija ili suradnja unutar organizacije<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q201_3', 'Nedostatan utjecaj radnika na brzinu ili tijek izvedbe posla', 'Osim prethodno navedenih rizika, određeni rizici za zdravlje mogu proizaći iz načina na koji je organizirano poslovanje, društvenih odnosa na radnom mjestu ili gospodarske situacije. Za svaki od čimbenika rizika koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici. Nedostatan utjecaj radnika na brzinu ili tijek izvedbe posla<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q201_4', 'Strah od gubitka posla', 'Osim prethodno navedenih rizika, određeni rizici za zdravlje mogu proizaći iz načina na koji je organizirano poslovanje, društvenih odnosa na radnom mjestu ili gospodarske situacije. Za svaki od čimbenika rizika koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici. Strah od gubitka posla<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q201_5', 'Komunikacija sa zahtjevnim klijentima, pacijentima, učenicima itd.', 'Osim prethodno navedenih rizika, određeni rizici za zdravlje mogu proizaći iz načina na koji je organizirano poslovanje, društvenih odnosa na radnom mjestu ili gospodarske situacije. Za svaki od čimbenika rizika koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici. Komunikacija sa zahtjevnim klijentima, pacijentima, učenicima itd.<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q201_6', 'Dugo ili neujednačeno radno vrijeme', 'Osim prethodno navedenih rizika, određeni rizici za zdravlje mogu proizaći iz načina na koji je organizirano poslovanje, društvenih odnosa na radnom mjestu ili gospodarske situacije. Za svaki od čimbenika rizika koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici. Dugo ili neujednačeno radno vrijeme<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q201_7', 'Diskriminacija, na primjer zbog spola, dobi ili etničke pripadnosti', 'Osim prethodno navedenih rizika, određeni rizici za zdravlje mogu proizaći iz načina na koji je organizirano poslovanje, društvenih odnosa na radnom mjestu ili gospodarske situacije. Za svaki od čimbenika rizika koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici. Diskriminacija, na primjer zbog spola, dobi ili etničke pripadnosti<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q250', 'Provodi li redovito vaša poslovna jedinica procjene rizika na radnom mjestu?', 'Provodi li redovito vaša poslovna jedinica procjene rizika na radnom mjestu?<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q251', 'Provodi li procjenu rizika na radnom mjestu interno osoblje ili vanjski pružatelji usluga s kojima je potpisan ugovor?', 'Provodi li procjenu rizika na radnom mjestu interno osoblje ili vanjski pružatelji usluga s kojima je potpisan ugovor?<br><br>(1) Uglavnom interno osoblje <br>(2) Uglavnom vanjski pružatelji usluga <br>(3) I jedni i drugi podjednako <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q264_1', 'Ispunjavanje zakonske obveze', 'Koliko su sljedeći razlozi važni za provedbu zaštite na radu u vašoj poslovnoj jedinici? Za svaki pojedini razlog odgovorite je li to važan razlog, manje važan razlog ili uopće nije razlog. Ispunjavanje zakonske obveze<br><br>(1) Važan razlog <br>(2) Manje važan razlog <br>(3) Uopće nije razlog <br>(9) Nema odgovora'],
		['Q264_2', 'Ispunjavanje očekivanja radnika ili njihovih povjerenika', 'Koliko su sljedeći razlozi važni za provedbu zaštite na radu u vašoj poslovnoj jedinici? Za svaki pojedini razlog odgovorite je li to važan razlog, manje važan razlog ili uopće nije razlog. Ispunjavanje očekivanja radnika ili njihovih povjerenika<br><br>(1) Važan razlog <br>(2) Manje važan razlog <br>(3) Uopće nije razlog <br>(9) Nema odgovora'],
		['Q264_4', 'Održavanje ili povećavanje produktivnosti', 'Koliko su sljedeći razlozi važni za provedbu zaštite na radu u vašoj poslovnoj jedinici? Za svaki pojedini razlog odgovorite je li to važan razlog, manje važan razlog ili uopće nije razlog. Održavanje ili povećavanje produktivnosti<br><br>(1) Važan razlog <br>(2) Manje važan razlog <br>(3) Uopće nije razlog <br>(9) Nema odgovora'],
		['Q264_5', 'Održavanje reputacije organizacije', 'Koliko su sljedeći razlozi važni za provedbu zaštite na radu u vašoj poslovnoj jedinici? Za svaki pojedini razlog odgovorite je li to važan razlog, manje važan razlog ili uopće nije razlog. Održavanje reputacije organizacije<br><br>(1) Važan razlog <br>(2) Manje važan razlog <br>(3) Uopće nije razlog <br>(9) Nema odgovora'],
		['Q264_6', 'Izbjegavanje kazni i sankcija inspekcije rada', 'Koliko su sljedeći razlozi važni za provedbu zaštite na radu u vašoj poslovnoj jedinici? Za svaki pojedini razlog odgovorite je li to važan razlog, manje važan razlog ili uopće nije razlog. Izbjegavanje kazni i sankcija inspekcije rada<br><br>(1) Važan razlog <br>(2) Manje važan razlog <br>(3) Uopće nije razlog <br>(9) Nema odgovora'],
		['Q307', 'Ima li vaša poslovna jedinica dovoljno informacija o tome kako uključiti psihosocijalne rizike u procjene rizika?', 'Ima li vaša poslovna jedinica dovoljno informacija o tome kako uključiti psihosocijalne rizike u procjene rizika?<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q150_1', 'Liječnik medicine rada', 'Koje usluge zaštite na radu koristite, bilo da je riječ o internim ili vanjskim stručnjacima? Liječnik medicine rada<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q150_2', 'Psiholog', 'Koje usluge zaštite na radu koristite, bilo da je riječ o internim ili vanjskim stručnjacima? Psiholog<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q150_3', 'Stručnjak koji se bavi ergonomskim dizajnom i opremanjem radnih mjesta', 'Koje usluge zaštite na radu koristite, bilo da je riječ o internim ili vanjskim stručnjacima? Stručnjak koji se bavi ergonomskim dizajnom i opremanjem radnih mjesta<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q150_4', 'Stručnjak za opća pitanja zaštite na radu', 'Koje usluge zaštite na radu koristite, bilo da je riječ o internim ili vanjskim stručnjacima? Stručnjak za opća pitanja zaštite na radu<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q150_5', 'Stručnjak za prevenciju nesreća', 'Koje usluge zaštite na radu koristite, bilo da je riječ o internim ili vanjskim stručnjacima? Stručnjak za prevenciju nesreća<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q155', 'Je li dokument, koji objašnjava odgovornosti i procedure koje se odnose na zaštitu na radu, dostupan ljudima koji rade u poslovnoj jedinici?', 'Je li dokument, koji objašnjava odgovornosti i procedure koje se odnose na zaštitu na radu, dostupan ljudima koji rade u poslovnoj jedinici?<br><br>(1) Da <br>(2) Ne <br>(3) Da, ali samo nekim kategorijama radnika <br>(9) Nema odgovora'],
		['Q156', 'Postoji li u vašoj poslovnoj jedinici određen proračun svake godine za mjere i opremu za zaštitu na radu?', 'Postoji li u vašoj poslovnoj jedinici određen proračun svake godine za mjere i opremu za zaštitu na radu?<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q158_1', 'Podizanje svijesti o zdravoj prehrani.', 'Provodi li vaša poslovna jedinica neku od sljedećih mjera za promicanje važnosti zdravog načina života među radnicima? Podizanje svijesti o zdravoj prehrani.<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q158_2', 'Podizanje svijesti o prevenciji ovisnosti, npr. pušenju, alkoholu ili drogama', 'Provodi li vaša poslovna jedinica neku od sljedećih mjera za promicanje važnosti zdravog načina života među radnicima? Podizanje svijesti o prevenciji ovisnosti, npr. pušenju, alkoholu ili drogama<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q158_3', 'Poticanje na bavljenje sportskim aktivnostima izvan radnog vremena', 'Provodi li vaša poslovna jedinica neku od sljedećih mjera za promicanje važnosti zdravog načina života među radnicima? Poticanje na bavljenje sportskim aktivnostima izvan radnog vremena<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q158_4', 'Poticanje na izvođenje vježbi za leđa, istezanja ili drugih vježbi za tijelo na radnom mjestu', 'Provodi li vaša poslovna jedinica neku od sljedećih mjera za promicanje važnosti zdravog načina života među radnicima? Poticanje na izvođenje vježbi za leđa, istezanja ili drugih vježbi za tijelo na radnom mjestu<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q160', 'Obavljate li rutinsku analizu bolovanja u svrhu poboljšanja uvjeta rada?', 'Obavljate li rutinsku analizu bolovanja u svrhu poboljšanja uvjeta rada?<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q165', 'Je li vašu poslovnu jedinicu u zadnje 3 godine posjetila inspekcija rada da bi provjerila zdravstvene i sigurnosne uvjete?', 'Je li vašu poslovnu jedinicu u zadnje 3 godine posjetila inspekcija rada da bi provjerila zdravstvene i sigurnosne uvjete?<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_1', 'Zamorni ili bolni položaji, uključujući dugo sjedenje', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Zamorni ili bolni položaji, uključujući dugo sjedenje<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_2', 'Podizanje ili premještanje ljudi ili teškog tereta', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Podizanje ili premještanje ljudi ili teškog tereta<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_3', 'Velika buka', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Velika buka<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_4', 'Ponavljajući pokreti šaka ili ruku', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Ponavljajući pokreti šaka ili ruku<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_5', 'Vrućina, hladnoća ili propuh', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Vrućina, hladnoća ili propuh<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_6', 'Rizik od nesreća prilikom rukovanja strojevima ili ručnim alatima', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Rizik od nesreća prilikom rukovanja strojevima ili ručnim alatima<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_7', 'Rizik od nesreća prilikom korištenja vozila tijekom obavljanja posla, ali ne i prilikom dolaska na radno mjesto i odlaska s njega', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Rizik od nesreća prilikom korištenja vozila tijekom obavljanja posla, ali ne i prilikom dolaska na radno mjesto i odlaska s njega<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_8', 'Kemijske i biološke tvari u obliku tekućine, isparavanja ili praha', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Kemijske i biološke tvari u obliku tekućine, isparavanja ili praha<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q200_9', 'Povećani rizik od skliznuća, spoticanja i padova', 'Svaka vrsta posla nosi sa sobom različite vrste rizika i opasnosti. Za svaki od čimbenika rizika, koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici bez obzira držite li ga trenutno pod nadzorom i neovisno o broju radnika koji su njime zahvaćeni. Povećani rizik od skliznuća, spoticanja i padova<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q202_1', 'Zamorni ili bolni položaji, uključujući dugo sjedenje', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Zamorni ili bolni položaji, uključujući dugo sjedenje<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je taj čimbenik rizika prisutan.'],
		['Q202_2', 'Podizanje ili premještanje ljudi ili teškog tereta', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Podizanje ili premještanje ljudi ili teškog tereta<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je taj čimbenik rizika prisutan.'],
		['Q202_3', 'Velika buka', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Velika buka<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je taj čimbenik rizika prisutan.'],
		['Q202_4', 'Ponavljajući pokreti šaka ili ruku', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Ponavljajući pokreti šaka ili ruku<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je taj čimbenik rizika prisutan.'],
		['Q202_5', 'Vrućina, hladnoća ili propuh', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Vrućina, hladnoća ili propuh<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je taj čimbenik rizika prisutan.'],
		['Q202_6', 'Rizik od nesreća prilikom rukovanja strojevima ili ručnim alatima', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Rizik od nesreća prilikom rukovanja strojevima ili ručnim alatima<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je taj čimbenik rizika prisutan.'],
		['Q202_7', 'Rizik od nesreća prilikom korištenja vozila tijekom obavljanja posla', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Rizik od nesreća prilikom korištenja vozila tijekom obavljanja posla<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je taj čimbenik rizika prisutan.'],
		['Q202_8', 'Kemijske i biološke tvari', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Kemijske i biološke tvari<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je taj čimbenik rizika prisutan.'],
		['Q202_9', 'Povećan rizik od skliznuća, spoticanja i padova', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Povećan rizik od skliznuća, spoticanja i padova<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je taj čimbenik rizika prisutan.'],
		['Q250', 'Provodi li redovito vaša poslovna jedinica procjene rizika na radnom mjestu?', 'Provodi li redovito vaša poslovna jedinica procjene rizika na radnom mjestu?<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q251', 'Provodi li procjenu rizika na radnom mjestu interno osoblje ili vanjski pružatelji usluga s kojima je potpisan ugovor?', 'Provodi li procjenu rizika na radnom mjestu interno osoblje ili vanjski pružatelji usluga s kojima je potpisan ugovor?<br><br>(1) Uglavnom interno osoblje <br>(2) Uglavnom vanjski pružatelji usluga <br>(3) I jedni i drugi podjednako <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q252_1', 'Sigurnost strojeva, opreme i instalacija', 'Koji se od sljedećih aspekata rutinski procjenjuju u tim procjenama rizika na radnom mjestu? Sigurnost strojeva, opreme i instalacija<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q252_2', 'Opasne kemijske i biološke tvari', 'Koji se od sljedećih aspekata rutinski procjenjuju u tim procjenama rizika na radnom mjestu? Opasne kemijske i biološke tvari<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q252_3', 'Držanje tijela pri radu, fizičko opterećenje pri radu i ponavljajući pokreti', 'Koji se od sljedećih aspekata rutinski procjenjuju u tim procjenama rizika na radnom mjestu? Držanje tijela pri radu, fizičko opterećenje pri radu i ponavljajući pokreti<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q252_4', 'Izloženost buci, vibracijama, vrućini ili hladnoći', 'Koji se od sljedećih aspekata rutinski procjenjuju u tim procjenama rizika na radnom mjestu? Izloženost buci, vibracijama, vrućini ili hladnoći<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q252_5', 'Odnosi nadređenih i podređenih', 'Koji se od sljedećih aspekata rutinski procjenjuju u tim procjenama rizika na radnom mjestu? Odnosi nadređenih i podređenih<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q252_6', 'Organizacijski aspekti kao što su rasporedi posla, pauze ili smjene', 'Koji se od sljedećih aspekata rutinski procjenjuju u tim procjenama rizika na radnom mjestu? Organizacijski aspekti kao što su rasporedi posla, pauze ili smjene<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q254gr', 'Koje je godine provedena zadnja procjena rizika na radnom mjestu?', 'Koje je godine provedena zadnja procjena rizika na radnom mjestu?<br><br>(Godina) <br>(9998) Ne znam <br>(9999) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q255', 'Je li to dokumentirano u pisanom obliku?', 'Je li to dokumentirano u pisanom obliku?<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je zadnja procjena rizika na radnom mjestu provedena nakon 1970.'],
		['Q256_1', 'Upravi', 'Kome se dostavljaju rezultati procjene rizika na radnom mjestu? Upravi<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je zadnja procjena rizika na radnom mjestu provedena nakon 1970.'],
		['Q256_2', 'Povjerenicima radnika za zaštitu na radu', 'Kome se dostavljaju rezultati procjene rizika na radnom mjestu? Povjerenicima radnika za zaštitu na radu<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je zadnja procjena rizika na radnom mjestu provedena nakon 1970. te da imaju povjerenike radnika za zaštitu na radu.'],
		['Q256_3', 'Radničkom vijeću', 'Kome se dostavljaju rezultati procjene rizika na radnom mjestu? Radničkom vijeću<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je zadnja procjena rizika na radnom mjestu provedena nakon 1970. te da imaju radnička vijeća.'],
		['Q256_4', 'Sindikatu', 'Kome se dostavljaju rezultati procjene rizika na radnom mjestu? Sindikatu<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je zadnja procjena rizika na radnom mjestu provedena nakon 1970. te da imaju sindikate.'],
		['Q256_5', 'Radnicima', 'Kome se dostavljaju rezultati procjene rizika na radnom mjestu? Radnicima<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je zadnja procjena rizika na radnom mjestu provedena nakon 1970.'],
		['Q259', 'Smatra li se u vašoj poslovnoj jedinici procedura procjene rizika korisnim načinom provođenja zaštite na radu?', 'Smatra li se u vašoj poslovnoj jedinici procedura procjene rizika korisnim načinom provođenja zaštite na radu?<br><br>(1) Da <br>(2) Ne <br>(3) Postoje oprečni stavovi o tome <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q261_1', 'Opasnosti i rizici su već poznati', 'Postoje li neki posebni razlozi zašto se procjene rizika na radnom mjestu ne provode redovito? Za svaki od razloga, koji su navedeni u nastavku, odgovorite odnosi li se na vašu poslovnu jedinicu? Opasnosti i rizici su već poznati<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje nisu navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q261_2', 'Nema većih problema', 'Postoje li neki posebni razlozi zašto se procjene rizika na radnom mjestu ne provode redovito? Za svaki od razloga, koji su navedeni u nastavku, odgovorite odnosi li se na vašu poslovnu jedinicu? Nema većih problema<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje nisu navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q261_3', 'Procedura je prenaporna', 'Postoje li neki posebni razlozi zašto se procjene rizika na radnom mjestu ne provode redovito? Za svaki od razloga, koji su navedeni u nastavku, odgovorite odnosi li se na vašu poslovnu jedinicu? Procedura je prenaporna<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje nisu navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q261_4', 'Nedostatak potrebnog stručnog znanja', 'Postoje li neki posebni razlozi zašto se procjene rizika na radnom mjestu ne provode redovito? Za svaki od razloga, koji su navedeni u nastavku, odgovorite odnosi li se na vašu poslovnu jedinicu? Nedostatak potrebnog stručnog znanja<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje nisu navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q308_1', 'Oprema za pomoć pri podizanju ili premještanju tereta ili kod drugih teških fizičkih poslova', 'Provodite li neke od sljedećih preventivnih mjera u vašoj poslovnoj jedinici kada je riječ o problemima mišićno-koštanog sustava, kao što su bol u leđima, vratu, rukama, šakama ili nogama? Oprema za pomoć pri podizanju ili premještanju tereta ili kod drugih teških fizičkih poslova<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele podizanje ili premještanje ljudi ili teškog tereta kao čimbenik rizika.'],
		['Q308_2', 'Rotiranje zadataka kako bi se smanjilo izvođenje ustaljenih pokreta ili tjelesni napor', 'Provodite li neke od sljedećih preventivnih mjera u vašoj poslovnoj jedinici kada je riječ o problemima mišićno-koštanog sustava, kao što su bol u leđima, vratu, rukama, šakama ili nogama? Rotiranje zadataka kako bi se smanjilo izvođenje ustaljenih pokreta ili tjelesni napor<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele ponavljajuće pokrete šake ili ruku kao čimbenik rizika.'],
		['Q308_3', 'Poticanje redovitih pauza za ljude u neudobnim ili statičnim položajima, uključujući dugo sjedenje', 'Provodite li neke od sljedećih preventivnih mjera u vašoj poslovnoj jedinici kada je riječ o problemima mišićno-koštanog sustava, kao što su bol u leđima, vratu, rukama, šakama ili nogama? Poticanje redovitih pauza za ljude u neudobnim ili statičnim položajima, uključujući dugo sjedenje<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q308_4', 'Osiguravanje ergonomski oblikovanog namještaja, kao što su posebne stolice ili stolovi', 'Provodite li neke od sljedećih preventivnih mjera u vašoj poslovnoj jedinici kada je riječ o problemima mišićno-koštanog sustava, kao što su bol u leđima, vratu, rukama, šakama ili nogama? Osiguravanje ergonomski oblikovanog namještaja, kao što su posebne stolice ili stolovi<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q356_1', 'Pravilno korištenje i podešavanje njihove radne opreme i namještaja', 'Za koja od sljedećih područja vaša poslovna jedinica osigurava obuku radnika? Pravilno korištenje i podešavanje njihove radne opreme i namještaja<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q356_2', 'Uporaba opasnih tvari', 'Za koja od sljedećih područja vaša poslovna jedinica osigurava obuku radnika? Uporaba opasnih tvari<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q356_3', 'Načini sprječavanja psihosocijalnih rizika poput stresa i zlostavljanja', 'Za koja od sljedećih područja vaša poslovna jedinica osigurava obuku radnika? Načini sprječavanja psihosocijalnih rizika poput stresa i zlostavljanja<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q356_4', 'Načini podizanja i premještanja teških tereta ili ljudi', 'Za koja od sljedećih područja vaša poslovna jedinica osigurava obuku radnika? Načini podizanja i premještanja teških tereta ili ljudi<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q356_5', 'Postupci u slučaju opasnosti', 'Za koja od sljedećih područja vaša poslovna jedinica osigurava obuku radnika? Postupci u slučaju opasnosti<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q201_1', 'Pritisak zbog kratkih vremenskih rokova', 'Osim prethodno navedenih rizika, određeni rizici za zdravlje mogu proizaći iz načina na koji je organizirano poslovanje, društvenih odnosa na radnom mjestu ili gospodarske situacije. Za svaki od čimbenika rizika koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici. Pritisak zbog kratkih vremenskih rokova<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q201_2', 'Loša komunikacija ili suradnja unutar organizacije', 'Osim prethodno navedenih rizika, određeni rizici za zdravlje mogu proizaći iz načina na koji je organizirano poslovanje, društvenih odnosa na radnom mjestu ili gospodarske situacije. Za svaki od čimbenika rizika koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici. Loša komunikacija ili suradnja unutar organizacije<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q201_3', 'Nedostatan utjecaj radnika na brzinu ili tijek izvedbe posla', 'Osim prethodno navedenih rizika, određeni rizici za zdravlje mogu proizaći iz načina na koji je organizirano poslovanje, društvenih odnosa na radnom mjestu ili gospodarske situacije. Za svaki od čimbenika rizika koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici. Nedostatan utjecaj radnika na brzinu ili tijek izvedbe posla<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q201_4', 'Strah od gubitka posla', 'Osim prethodno navedenih rizika, određeni rizici za zdravlje mogu proizaći iz načina na koji je organizirano poslovanje, društvenih odnosa na radnom mjestu ili gospodarske situacije. Za svaki od čimbenika rizika koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici. Strah od gubitka posla<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q201_5', 'Komunikacija sa zahtjevnim klijentima, pacijentima, učenicima itd.', 'Osim prethodno navedenih rizika, određeni rizici za zdravlje mogu proizaći iz načina na koji je organizirano poslovanje, društvenih odnosa na radnom mjestu ili gospodarske situacije. Za svaki od čimbenika rizika koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici. Komunikacija sa zahtjevnim klijentima, pacijentima, učenicima itd.<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q201_6', 'Dugo ili neujednačeno radno vrijeme', 'Osim prethodno navedenih rizika, određeni rizici za zdravlje mogu proizaći iz načina na koji je organizirano poslovanje, društvenih odnosa na radnom mjestu ili gospodarske situacije. Za svaki od čimbenika rizika koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici. Dugo ili neujednačeno radno vrijeme<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q201_7', 'Diskriminacija, na primjer zbog spola, dobi ili etničke pripadnosti', 'Osim prethodno navedenih rizika, određeni rizici za zdravlje mogu proizaći iz načina na koji je organizirano poslovanje, društvenih odnosa na radnom mjestu ili gospodarske situacije. Za svaki od čimbenika rizika koji su navedeni u nastavku, odgovorite je li prisutan u vašoj poslovnoj jedinici. Diskriminacija, na primjer zbog spola, dobi ili etničke pripadnosti<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q202_10', 'Pritisak zbog kratkih vremenskih rokova', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Pritisak zbog kratkih vremenskih rokova<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je prisutan taj psihosocijalni čimbenik rizika.'],
		['Q202_11', 'Loša komunikacija ili suradnja unutar organizacije', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Loša komunikacija ili suradnja unutar organizacije<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je prisutan taj psihosocijalni čimbenik rizika.'],
		['Q202_12', 'Nedostatan utjecaj radnika na brzinu ili tijek izvedbe posla', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Nedostatan utjecaj radnika na brzinu ili tijek izvedbe posla<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je prisutan taj psihosocijalni čimbenik rizika.'],
		['Q202_13', 'Strah od gubitka posla', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Strah od gubitka posla<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je prisutan taj psihosocijalni čimbenik rizika.'],
		['Q202_14', 'Komunikacija sa zahtjevnim klijentima, pacijentima, učenicima itd..', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Komunikacija sa zahtjevnim klijentima, pacijentima, učenicima itd..<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je prisutan taj psihosocijalni čimbenik rizika.'],
		['Q202_15', 'Dugo ili neujednačeno radno vrijeme', 'O kojima od navedenih rizika u vašoj organizaciji nisu dostupne dostatne informacije ili za njih ne postoje adekvatne preventivne mjere za njihovo učinkovito otklanjanje? Dugo ili neujednačeno radno vrijeme<br><br>(1) Da <br>(2) Ne<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je prisutan taj psihosocijalni čimbenik rizika.'],
		['Q300', 'Ima li vaša poslovna jedinica akcijski plan za prevenciju stresa uzrokovanog poslom?', 'Ima li vaša poslovna jedinica akcijski plan za prevenciju stresa uzrokovanog poslom?<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama u kojima je zaposleno 20 i više radnika.'],
		['Q301', 'Postoji li procedura za rješavanje slučajeva mogućeg zlostavljanja ili uznemiravanja?', 'Postoji li procedura za rješavanje slučajeva mogućeg zlostavljanja ili uznemiravanja?<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama u kojima je zaposleno 20 i više radnika.'],
		['Q302', 'A postoje li procedure za rješavanje mogućih slučajeva prijetnji, zlostavljanja ili vrijeđanja od strane klijenata, pacijenata, učenika ili drugih osoba izvana?', 'A postoje li procedure za rješavanje mogućih slučajeva prijetnji, zlostavljanja ili vrijeđanja od strane klijenata, pacijenata, učenika ili drugih osoba izvana?<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje imaju 20 i više radnika te koje su navele rad sa zahtjevnim klijentima, pacijentima, učenicima kao čimbenik rizika.'],
		['Q303_1', 'Reorganizacija posla s ciljem smanjenja opterećenosti poslom i pritiska na radnom mjestu', 'Je li vaša poslovna jedinica u zadnje 3 godine provela neku od sljedećih mjera za sprječavanje psihosocijalnih rizika? Reorganizacija posla s ciljem smanjenja opterećenosti poslom i pritiska na radnom mjestu<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q303_2', 'Povjerljivo savjetovanje za radnike', 'Je li vaša poslovna jedinica u zadnje 3 godine provela neku od sljedećih mjera za sprječavanje psihosocijalnih rizika? Povjerljivo savjetovanje za radnike<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q303_3', 'Uvođenje postupka za rješavanje sukoba', 'Je li vaša poslovna jedinica u zadnje 3 godine provela neku od sljedećih mjera za sprječavanje psihosocijalnih rizika? Uvođenje postupka za rješavanje sukoba<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q303_4', 'Interveniranje u slučaju predugog ili neujednačenog radnog vremena', 'Je li vaša poslovna jedinica u zadnje 3 godine provela neku od sljedećih mjera za sprječavanje psihosocijalnih rizika? Interveniranje u slučaju predugog ili neujednačenog radnog vremena<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q307', 'Ima li vaša poslovna jedinica dovoljno informacija o tome kako uključiti psihosocijalne rizike u procjene rizika?', 'Ima li vaša poslovna jedinica dovoljno informacija o tome kako uključiti psihosocijalne rizike u procjene rizika?<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora'],
		['Q264_1', 'Ispunjavanje zakonske obveze', 'Koliko su sljedeći razlozi važni za provedbu zaštite na radu u vašoj poslovnoj jedinici? Za svaki pojedini razlog odgovorite je li to važan razlog, manje važan razlog ili uopće nije razlog. Ispunjavanje zakonske obveze<br><br>(1) Važan razlog <br>(2) Manje važan razlog <br>(3) Uopće nije razlog <br>(9) Nema odgovora'],
		['Q264_2', 'Ispunjavanje očekivanja radnika ili njihovih povjerenika', 'Koliko su sljedeći razlozi važni za provedbu zaštite na radu u vašoj poslovnoj jedinici? Za svaki pojedini razlog odgovorite je li to važan razlog, manje važan razlog ili uopće nije razlog. Ispunjavanje očekivanja radnika ili njihovih povjerenika<br><br>(1) Važan razlog <br>(2) Manje važan razlog <br>(3) Uopće nije razlog <br>(9) Nema odgovora'],
		['Q264_4', 'Održavanje ili povećavanje produktivnosti', 'Koliko su sljedeći razlozi važni za provedbu zaštite na radu u vašoj poslovnoj jedinici? Za svaki pojedini razlog odgovorite je li to važan razlog, manje važan razlog ili uopće nije razlog. Održavanje ili povećavanje produktivnosti<br><br>(1) Važan razlog <br>(2) Manje važan razlog <br>(3) Uopće nije razlog <br>(9) Nema odgovora'],
		['Q264_5', 'Održavanje reputacije organizacije', 'Koliko su sljedeći razlozi važni za provedbu zaštite na radu u vašoj poslovnoj jedinici? Za svaki pojedini razlog odgovorite je li to važan razlog, manje važan razlog ili uopće nije razlog. Održavanje reputacije organizacije<br><br>(1) Važan razlog <br>(2) Manje važan razlog <br>(3) Uopće nije razlog <br>(9) Nema odgovora'],
		['Q264_6', 'Izbjegavanje kazni i sankcija inspekcije rada', 'Koliko su sljedeći razlozi važni za provedbu zaštite na radu u vašoj poslovnoj jedinici? Za svaki pojedini razlog odgovorite je li to važan razlog, manje važan razlog ili uopće nije razlog. Izbjegavanje kazni i sankcija inspekcije rada<br><br>(1) Važan razlog <br>(2) Manje važan razlog <br>(3) Uopće nije razlog <br>(9) Nema odgovora'],
		['Q265_1', 'Nedostatak vremena ili osoblja', 'Koji su glavni problemi u provedbi zaštite na radu u vašoj poslovnoj jedinci? Za svaki pojedini problem odgovorite je li to veliki problem, manji problem ili uopće nije problem. Nedostatak vremena ili osoblja<br><br>(1) Veliki problem <br>(2) Manji problem <br>(3) Uopće nije problem <br>(9) Nema odgovora'],
		['Q265_2', 'Nedostatak novca', 'Koji su glavni problemi u provedbi zaštite na radu u vašoj poslovnoj jedinci? Za svaki pojedini problem odgovorite je li to veliki problem, manji problem ili uopće nije problem. Nedostatak novca<br><br>(1) Veliki problem <br>(2) Manji problem <br>(3) Uopće nije problem <br>(9) Nema odgovora'],
		['Q265_3', 'Nedovoljna osviještenost osoblja', 'Koji su glavni problemi u provedbi zaštite na radu u vašoj poslovnoj jedinci? Za svaki pojedini problem odgovorite je li to veliki problem, manji problem ili uopće nije problem. Nedovoljna osviještenost osoblja<br><br>(1) Veliki problem <br>(2) Manji problem <br>(3) Uopće nije problem <br>(9) Nema odgovora'],
		['Q265_4', 'Nedovoljna osviještenost uprave', 'Koji su glavni problemi u provedbi zaštite na radu u vašoj poslovnoj jedinci? Za svaki pojedini problem odgovorite je li to veliki problem, manji problem ili uopće nije problem. Nedovoljna osviještenost uprave<br><br>(1) Veliki problem <br>(2) Manji problem <br>(3) Uopće nije problem <br>(9) Nema odgovora'],
		['Q265_5', 'Nedostatak stručnog znanja ili podrške stručnjaka', 'Koji su glavni problemi u provedbi zaštite na radu u vašoj poslovnoj jedinci? Za svaki pojedini problem odgovorite je li to veliki problem, manji problem ili uopće nije problem. Nedostatak stručnog znanja ili podrške stručnjaka<br><br>(1) Veliki problem <br>(2) Manji problem <br>(3) Uopće nije problem <br>(9) Nema odgovora'],
		['Q265_6', 'Papirologija', 'Koji su glavni problemi u provedbi zaštite na radu u vašoj poslovnoj jedinci? Za svaki pojedini problem odgovorite je li to veliki problem, manji problem ili uopće nije problem. Papirologija<br><br>(1) Veliki problem <br>(2) Manji problem <br>(3) Uopće nije problem <br>(9) Nema odgovora'],
		['Q265_7', 'Složenost zakonskih obveza', 'Koji su glavni problemi u provedbi zaštite na radu u vašoj poslovnoj jedinci? Za svaki pojedini problem odgovorite je li to veliki problem, manji problem ili uopće nije problem. Složenost zakonskih obveza<br><br>(1) Veliki problem <br>(2) Manji problem <br>(3) Uopće nije problem <br>(9) Nema odgovora'],
		['Q304', 'Jesu li poduzete mjere bile potaknute konkretnim problemima povezanim sa stresom, zlostavljanjem, uznemiravanjem ili nasiljem u poslovnoj jedinici?', 'Jesu li poduzete mjere bile potaknute konkretnim problemima povezanim sa stresom, zlostavljanjem, uznemiravanjem ili nasiljem u poslovnoj jedinici?<br><br>(1) Da <br>(2) Ne <br>(8) Djelomično <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da su u zadnje tri godine upotrijebile određene mjere za sprječavanje psihosocijalnih rizika.'],
		['Q306a_3', 'Nedovoljna osviještenost osoblja', 'S obzirom na stanje u vašoj poslovnoj jedinici, čini li neki od sljedećih čimbenika rješavanje psihosocijalnih rizika težim od rješavanja drugih zdravstvenih rizika? Nedovoljna osviještenost osoblja<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je prisutan jedan od navedenih psihosocijalnih čimbenika rizika.'],
		['Q306a_4', 'Nedovoljna osviještenost uprave', 'S obzirom na stanje u vašoj poslovnoj jedinici, čini li neki od sljedećih čimbenika rješavanje psihosocijalnih rizika težim od rješavanja drugih zdravstvenih rizika? Nedovoljna osviještenost uprave<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je prisutan jedan od navedenih psihosocijalnih čimbenika rizika.'],
		['Q306a_5', 'Nedostatak stručnog znanja ili podrške stručnjaka', 'S obzirom na stanje u vašoj poslovnoj jedinici, čini li neki od sljedećih čimbenika rješavanje psihosocijalnih rizika težim od rješavanja drugih zdravstvenih rizika? Nedostatak stručnog znanja ili podrške stručnjaka<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je prisutan jedan od navedenih psihosocijalnih čimbenika rizika.'],
		['Q306a_6', 'Nespremnost za otvoreni razgovor o ovim problemima', 'S obzirom na stanje u vašoj poslovnoj jedinici, čini li neki od sljedećih čimbenika rješavanje psihosocijalnih rizika težim od rješavanja drugih zdravstvenih rizika? Nespremnost za otvoreni razgovor o ovim problemima<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da je prisutan jedan od navedenih psihosocijalnih čimbenika rizika.'],
		['Q166_1', 'Radničko vijeće', 'Koji od sljedećih oblika zastupanja radnika postoji u ovoj poslovnoj jedinici? Radničko vijeće<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno svima, veličina ovisi o nacionalnim pragovima za navedena tijela.'],
		['Q166_2', 'Sindikat', 'Koji od sljedećih oblika zastupanja radnika postoji u ovoj poslovnoj jedinici? Sindikat<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno svima, veličina ovisi o nacionalnim pragovima za navedena tijela.'],
		['Q166_3', 'Povjerenik radnika za zaštitu na radu', 'Koji od sljedećih oblika zastupanja radnika postoji u ovoj poslovnoj jedinici? Povjerenik radnika za zaštitu na radu<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno svima, veličina ovisi o nacionalnim pragovima za navedena tijela.'],
		['Q166_4', 'Odbor za zaštitu na radu', 'Koji od sljedećih oblika zastupanja radnika postoji u ovoj poslovnoj jedinici? Odbor za zaštitu na radu<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno svima, veličina ovisi o nacionalnim pragovima za navedena tijela.'],
		['Q258b', 'Ako se na temelju procjene rizika moraju poduzeti neke mjere, jesu li radnici obično uključeni u njihovo osmišljavanje i implementaciju?', 'Ako se na temelju procjene rizika moraju poduzeti neke mjere, jesu li radnici obično uključeni u njihovo osmišljavanje i implementaciju?<br><br>(1) Da <br>(2) Ne <br>(4) To ovisi o tipu mjera <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da redovito provode procjene rizika na radnom mjestu.'],
		['Q305', 'Jesu li radnici sudjelovali u osmišljavanju i određivanju mjera za rješavanje psihosocijalnih rizika?', 'Jesu li radnici sudjelovali u osmišljavanju i određivanju mjera za rješavanje psihosocijalnih rizika?<br><br>(1) Da <br>(2) Ne <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da su u zadnje tri godine upotrijebile određene mjere za sprječavanje psihosocijalnih rizika.'],
		['Q350', 'Koliko su česte rasprave o pitanjima zaštite na radu između radničkih povjerenika i uprave? Događaju li se takve rasprave redovito, samo kad se pojavi određeni problem povezan sa zaštitom na radu ili se uopće ne događaju?', 'Koliko su česte rasprave o pitanjima zaštite na radu između radničkih povjerenika i uprave? Događaju li se takve rasprave redovito, samo kad se pojavi određeni problem povezan sa zaštitom na radu ili se uopće ne događaju?<br><br>(1) Redovito <br>(2) Samo kada se pojavi određeni problem <br>(3) Uopće se ne događaju <br>(7) Nije primjenjivo (nema radničkih povjerenika) <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da su prisutni određeni oblici zastupanja radnika.'],
		['Q351', 'A koliko često izbiju nesuglasice zbog zaštite na radu? To se događa često, ponekad ili gotovo nikad?', 'A koliko često izbiju nesuglasice zbog zaštite na radu? To se događa često, ponekad ili gotovo nikad?<br><br>(1) Često <br>(2) Ponekad <br>(3) Gotovo nikada <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da o zaštiti na radu međusobno raspravljaju radnički povjerenici i uprava.'],
		['Q354', 'Pohađaju li povjerenici radnika za zaštitu na radu bilo kakvu obuku tijekom obavljanja posla kako bi lakše izvršavali svoje zadatke koji se tiču zaštite na radu?', 'Pohađaju li povjerenici radnika za zaštitu na radu bilo kakvu obuku tijekom obavljanja posla kako bi lakše izvršavali svoje zadatke koji se tiču zaštite na radu?<br><br>(1) Da <br>(2) Ne <br>(3) Da, ali samo neki od njih <br>(9) Nema odgovora<br><br>Pitanje postavljeno poslovnim jedinicama koje su navele da imaju povjerenike radnika za zaštitu na radu.'],
		['Q358', 'Raspravlja li se redovito o pitanjima zaštite na radu na sastancima osoblja ili tima?', 'Raspravlja li se redovito o pitanjima zaštite na radu na sastancima osoblja ili tima?<br><br>(1) Da <br>(2) Ne <br>(3) Samo u nekim odjelima <br>(9) Nema odgovora']
	];
