//Auto Generated file
var subset_
	 = [
	
		['Sectorgrp', 'Veiklos sektorius'],
		['Size', 'Įmonės dydis']
	];
var subset_subsetValue
	 = [
	
		['Sectorgrp', 'All', 'Visi sektoriai'],
		['Sectorgrp', '1--A', 'Žemės ūkis, miškininkystė ir žvejyba'],
		['Sectorgrp', '2--BDEF', 'Statyba, atliekų tvarkymas, vandens ir elektros energijos tiekimas'],
		['Sectorgrp', '3--C', 'Gamyba'],
		['Sectorgrp', '4--GHIR', 'Prekyba, transportas, maitinimas / apgyvendinimas ir rekreacinė veikla'],
		['Sectorgrp', '5--JKLMNS', 'IT, finansinė, su nekilnojamuoju turtu ir kita technine moksline ar asmeninėmis paslaugomis susijusi veikla'],
		['Sectorgrp', '6--O', 'Viešasis administravimas'],
		['Sectorgrp', '7--PQ', 'Švietimas, žmonių sveikata ir su socialiniu darbu susijusi veikla'],
		['Size', 'All', 'Visų dydžių įmonės'],
		['Size', '1--5-to-9', '5–9 darbuotojai'],
		['Size', '2--10-to-49', '10–49 darbuotojai'],
		['Size', '3--50-249', '50–249 darbuotojai'],
		['Size', '4--250-', '250 ir daugiau darbuotojų']
	];
var topic_
	 = [
	
		['', 'Visi (-os) (108)'],
		['DSS valdymas', 'DSS valdymas (60)'],
		['Darbuotojų dalyvavimas', 'Darbuotojų dalyvavimas (10)'],
		['Pagrindinės išvados', 'Pagrindinės išvados (24)'],
		['Paskatos ir kliūtys', 'Paskatos ir kliūtys (17)'],
		['Psichosocialinė rizika ir jos valdymas', 'Psichosocialinė rizika ir jos valdymas (21)']
	];
var topic_question
	 = [
	
		['Pagrindinės išvados', 'Q200_1', 'Įmonėje egzistuojantys rizikos veiksniai: Varginančios ar skausmingos kūno padėtys'],
		['Pagrindinės išvados', 'Q200_2', 'Įmonėje egzistuojantys rizikos veiksniai: Žmonių arba sunkių krovinių kėlimas ir nešimas'],
		['Pagrindinės išvados', 'Q200_3', 'Įmonėje egzistuojantys rizikos veiksniai: Didelis triukšmas'],
		['Pagrindinės išvados', 'Q200_4', 'Įmonėje egzistuojantys rizikos veiksniai: Pasikartojantys plaštakų arba rankų judesiai'],
		['Pagrindinės išvados', 'Q200_5', 'Įmonėje egzistuojantys rizikos veiksniai: Karštis, šaltis arba skersvėjis'],
		['Pagrindinės išvados', 'Q200_6', 'Įmonėje egzistuojantys rizikos veiksniai: Nelaimingų atsitikimų rizika dirbant su mašinomis'],
		['Pagrindinės išvados', 'Q200_7', 'Įmonėje egzistuojantys rizikos veiksniai: Nelaimingų atsitikimų rizika, susijusi su darbo metu naudojamomis variklinėmis transporto priemonėmis'],
		['Pagrindinės išvados', 'Q200_8', 'Įmonėje egzistuojantys rizikos veiksniai: Cheminės arba biologinės medžiagos'],
		['Pagrindinės išvados', 'Q200_9', 'Įmonėje egzistuojantys rizikos veiksniai: Padidėjusi rizika paslysti, suklupti ar parkristi'],
		['Pagrindinės išvados', 'Q201_1', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Spaudimas dėl laiko stokos'],
		['Pagrindinės išvados', 'Q201_2', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Menkas bendravimas ar bendradarbiavimas'],
		['Pagrindinės išvados', 'Q201_3', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Nepakankamas darbuotojų gebėjimas daryti įtaką'],
		['Pagrindinės išvados', 'Q201_4', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Neužtikrintumas dėl darbo vietos'],
		['Pagrindinės išvados', 'Q201_5', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Darbas su sunkiais klientais, pacientais, mokiniais ir pan.'],
		['Pagrindinės išvados', 'Q201_6', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Ilgos arba nereguliarios darbo valandos'],
		['Pagrindinės išvados', 'Q201_7', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Diskriminacija'],
		['Pagrindinės išvados', 'Q250', 'Su darbo vieta susijusios rizikos vertinimas'],
		['Pagrindinės išvados', 'Q251', 'Su darbo vieta susijusios rizikos vertinimą daugiausia atlieka įmonės darbuotojai arba išorės paslaugų teikėjai'],
		['Pagrindinės išvados', 'Q264_1', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Teisinių įsipareigojimų įvykdymas'],
		['Pagrindinės išvados', 'Q264_2', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbuotojų lūkesčių pateisinimas'],
		['Pagrindinės išvados', 'Q264_4', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbo našumo didinimas'],
		['Pagrindinės išvados', 'Q264_5', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Organizacijos reputacija'],
		['Pagrindinės išvados', 'Q264_6', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbo inspekcijos skiriamų baudų išvengimas'],
		['Pagrindinės išvados', 'Q307', 'Pakankama informacija apie tai, kaip psichosocialinę riziką įtraukti į rizikos vertinimą'],
		['DSS valdymas', 'Q150_1', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Profesinės sveikatos specialistas'],
		['DSS valdymas', 'Q150_2', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Psichologas'],
		['DSS valdymas', 'Q150_3', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Ergonomiško dizaino ir darbo vietų įrengimo specialistas'],
		['DSS valdymas', 'Q150_4', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Plataus profilio sveikatos ir saugos specialistas'],
		['DSS valdymas', 'Q150_5', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Nelaimingų atsitikimų prevencijos specialistas'],
		['DSS valdymas', 'Q155', 'Darbuotojai gali susipažinti su dokumentu, kuriame paaiškintos su sauga ir sveikata susijusios jų pareigos ir procedūros'],
		['DSS valdymas', 'Q156', 'Kasmet numatomos konkrečios išlaidos darbuotojų saugos ir sveikatos priemonėms bei įrangai'],
		['DSS valdymas', 'Q158_1', 'Darbuotojų sveikatai stiprinti skirtos priemonės: Išsamesnės informacijos apie mitybą teikimas '],
		['DSS valdymas', 'Q158_2', 'Darbuotojų sveikatai stiprinti skirtos priemonės: Išsamesnės informacijos apie priklausomybių prevenciją teikimas'],
		['DSS valdymas', 'Q158_3', 'Darbuotojų sveikatai stiprinti skirtos priemonės: Sportinės veiklos ne darbo valandomis skatinimas'],
		['DSS valdymas', 'Q158_4', 'Darbuotojų sveikatai stiprinti skirtos priemonės: Skatinimas darbe atlikti fizinius pratimus'],
		['DSS valdymas', 'Q160', 'Nuolatinė darbuotojų nedarbingumo dėl ligos priežasčių analizė'],
		['DSS valdymas', 'Q165', 'Per pastaruosius 3 metus įmonėje lankėsi Darbo inspekcija, norėdama patikrinti darbuotojų saugos ir sveikatos sąlygas'],
		['DSS valdymas', 'Q200_1', 'Įmonėje egzistuojantys rizikos veiksniai: Varginančios ar skausmingos kūno padėtys'],
		['DSS valdymas', 'Q200_2', 'Įmonėje egzistuojantys rizikos veiksniai: Žmonių arba sunkių krovinių kėlimas ir nešimas'],
		['DSS valdymas', 'Q200_3', 'Įmonėje egzistuojantys rizikos veiksniai: Didelis triukšmas'],
		['DSS valdymas', 'Q200_4', 'Įmonėje egzistuojantys rizikos veiksniai: Pasikartojantys plaštakų arba rankų judesiai'],
		['DSS valdymas', 'Q200_5', 'Įmonėje egzistuojantys rizikos veiksniai: Karštis, šaltis arba skersvėjis'],
		['DSS valdymas', 'Q200_6', 'Įmonėje egzistuojantys rizikos veiksniai: Nelaimingų atsitikimų rizika dirbant su mašinomis'],
		['DSS valdymas', 'Q200_7', 'Įmonėje egzistuojantys rizikos veiksniai: Nelaimingų atsitikimų rizika, susijusi su darbo metu naudojamomis variklinėmis transporto priemonėmis'],
		['DSS valdymas', 'Q200_8', 'Įmonėje egzistuojantys rizikos veiksniai: Cheminės arba biologinės medžiagos'],
		['DSS valdymas', 'Q200_9', 'Įmonėje egzistuojantys rizikos veiksniai: Padidėjusi rizika paslysti, suklupti ar parkristi'],
		['DSS valdymas', 'Q202_1', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Varginančios ar skausmingos kūno padėtys'],
		['DSS valdymas', 'Q202_2', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Žmonių arba sunkių krovinių kėlimas ir nešimas'],
		['DSS valdymas', 'Q202_3', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Didelis triukšmas'],
		['DSS valdymas', 'Q202_4', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Pasikartojantys plaštakų arba rankų judesiai'],
		['DSS valdymas', 'Q202_5', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Karštis, šaltis arba skersvėjis'],
		['DSS valdymas', 'Q202_6', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Nelaimingų atsitikimų rizika dirbant su mašinomis'],
		['DSS valdymas', 'Q202_7', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Nelaimingų atsitikimų rizika, susijusi su darbo metu naudojamomis variklinėmis transporto priemonėmis'],
		['DSS valdymas', 'Q202_8', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Cheminės arba biologinės medžiagos'],
		['DSS valdymas', 'Q202_9', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Padidėjusi rizika paslysti, suklupti ar parkristi'],
		['DSS valdymas', 'Q250', 'Su darbo vieta susijusios rizikos vertinimas'],
		['DSS valdymas', 'Q251', 'Su darbo vieta susijusios rizikos vertinimą daugiausia atlieka įmonės darbuotojai arba išorės paslaugų teikėjai'],
		['DSS valdymas', 'Q252_1', 'Aspektai, kurie vertinami atliekant su darbo vieta susijusios rizikos vertinimą: Mašinų, įrangos ir įrenginių sauga'],
		['DSS valdymas', 'Q252_2', 'Aspektai, kurie vertinami atliekant su darbo vieta susijusios rizikos vertinimą: Pavojingos medžiagos'],
		['DSS valdymas', 'Q252_3', 'Aspektai, kurie vertinami atliekant su darbo vieta susijusios rizikos vertinimą: Laikysena darbe, fizinis darbo krūvis ir pasikartojantys judesiai'],
		['DSS valdymas', 'Q252_4', 'Aspektai, kurie vertinami atliekant su darbo vieta susijusios rizikos vertinimą: Triukšmas, vibracija, karštis ar šaltis'],
		['DSS valdymas', 'Q252_5', 'Aspektai, kurie vertinami atliekant su darbo vieta susijusios rizikos vertinimą: Vadovo ir darbuotojo santykiai'],
		['DSS valdymas', 'Q252_6', 'Aspektai, kurie vertinami atliekant su darbo vieta susijusios rizikos vertinimą: Organizaciniai aspektai'],
		['DSS valdymas', 'Q254gr', 'Metai, kuriais paskutinį kartą buvo atliktas su darbo vieta susijusios rizikos vertinimas'],
		['DSS valdymas', 'Q255', 'Su darbo vieta susijusios rizikos vertinimo įforminimas dokumentuose'],
		['DSS valdymas', 'Q256_1', 'Darbuotojai supažindinti su išvadomis, kuriose pateikiamas su darbo vieta susijusios rizikos vertinimas: Vadovybei'],
		['DSS valdymas', 'Q256_2', 'Darbuotojai supažindinti su išvadomis, kuriose pateikiamas su darbo vieta susijusios rizikos vertinimas: Darbuotojų atstovui saugai ir sveikatai'],
		['DSS valdymas', 'Q256_3', 'Darbuotojai supažindinti su išvadomis, kuriose pateikiamas su darbo vieta susijusios rizikos vertinimas: Darbo tarybai'],
		['DSS valdymas', 'Q256_4', 'Darbuotojai supažindinti su išvadomis, kuriose pateikiamas su darbo vieta susijusios rizikos vertinimas: Profesinės sąjungos atstovams'],
		['DSS valdymas', 'Q256_5', 'Darbuotojai supažindinti su išvadomis, kuriose pateikiamas su darbo vieta susijusios rizikos vertinimas: Patiems darbuotojams'],
		['DSS valdymas', 'Q259', 'Rizikos vertinimas laikomas naudinga darbuotojų saugos ir sveikatos valdymo priemone'],
		['DSS valdymas', 'Q261_1', 'Priežastys, dėl kurių reguliariai neatliekamas su darbo vieta susijusios rizikos vertinimas: Pavojai ir rizika jau žinomi'],
		['DSS valdymas', 'Q261_2', 'Priežastys, dėl kurių reguliariai neatliekamas su darbo vieta susijusios rizikos vertinimas: nėra rimtų problemų'],
		['DSS valdymas', 'Q261_3', 'Priežastys, dėl kurių reguliariai neatliekamas su darbo vieta susijusios rizikos vertinimas: ši procedūra pernelyg sudėtinga'],
		['DSS valdymas', 'Q261_4', 'Priežastys, dėl kurių reguliariai neatliekamas su darbo vieta susijusios rizikos vertinimas: trūksta reikiamų žinių'],
		['DSS valdymas', 'Q308_1', 'Raumenų ir kaulų sistemos sutrikimų prevencinės priemonės: Įranga, skirta padėti kelti ar vežti krovinius'],
		['DSS valdymas', 'Q308_2', 'Raumenų ir kaulų sistemos sutrikimų prevencinės priemonės: Užduočių kaitaliojimas, siekiant sumažinti fizinį krūvį'],
		['DSS valdymas', 'Q308_3', 'Raumenų ir kaulų sistemos sutrikimų prevencinės priemonės: Skatinimas daryti reguliarias pertraukas tiems darbuotojams, kurių kūno padėtis būna nepatogi arba statiška'],
		['DSS valdymas', 'Q308_4', 'Raumenų ir kaulų sistemos sutrikimų prevencinės priemonės: Ergonomiškos įrangos įsigijimas'],
		['DSS valdymas', 'Q356_1', 'Darbuotojų mokymai: Tinkamas įrangos ir baldų naudojimas ir reguliavimas'],
		['DSS valdymas', 'Q356_2', 'Darbuotojų mokymai: Pavojingų medžiagų naudojimas'],
		['DSS valdymas', 'Q356_3', 'Darbuotojų mokymai: Kaip užkirsti kelią psichosocialinei rizikai?'],
		['DSS valdymas', 'Q356_4', 'Darbuotojų mokymai: Kaip kelti ir nešti sunkius krovinius ar žmones?'],
		['DSS valdymas', 'Q356_5', 'Darbuotojų mokymai: Skubios pagalbos procedūros'],
		['Psichosocialinė rizika ir jos valdymas', 'Q201_1', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Spaudimas dėl laiko stokos'],
		['Psichosocialinė rizika ir jos valdymas', 'Q201_2', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Menkas bendravimas ar bendradarbiavimas'],
		['Psichosocialinė rizika ir jos valdymas', 'Q201_3', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Nepakankamas darbuotojų gebėjimas daryti įtaką'],
		['Psichosocialinė rizika ir jos valdymas', 'Q201_4', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Neužtikrintumas dėl darbo vietos'],
		['Psichosocialinė rizika ir jos valdymas', 'Q201_5', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Darbas su sunkiais klientais, pacientais, mokiniais ir pan.'],
		['Psichosocialinė rizika ir jos valdymas', 'Q201_6', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Ilgos arba nereguliarios darbo valandos'],
		['Psichosocialinė rizika ir jos valdymas', 'Q201_7', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Diskriminacija'],
		['Psichosocialinė rizika ir jos valdymas', 'Q202_10', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Spaudimas dėl laiko stokos'],
		['Psichosocialinė rizika ir jos valdymas', 'Q202_11', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Menkas bendravimas ar bendradarbiavimas'],
		['Psichosocialinė rizika ir jos valdymas', 'Q202_12', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Nepakankamas darbuotojų gebėjimas daryti įtaką'],
		['Psichosocialinė rizika ir jos valdymas', 'Q202_13', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Neužtikrintumas dėl darbo vietos'],
		['Psichosocialinė rizika ir jos valdymas', 'Q202_14', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Darbas su sunkiais klientais, pacientais, mokiniais ir pan.'],
		['Psichosocialinė rizika ir jos valdymas', 'Q202_15', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Ilgos arba nereguliarios darbo valandos'],
		['Psichosocialinė rizika ir jos valdymas', 'Q300', 'Numatytas streso darbe prevencijos veiksmų planas'],
		['Psichosocialinė rizika ir jos valdymas', 'Q301', 'Numatyta procedūra patyčių ar priekabiavimo atvejams spręsti'],
		['Psichosocialinė rizika ir jos valdymas', 'Q302', 'Numatyta procedūra grasinimo, užgauliojimo ar smurto atvejams spręsti'],
		['Psichosocialinė rizika ir jos valdymas', 'Q303_1', 'Psichosocialinės rizikos mažinimo priemonės, taikytos per pastaruosius 3 metus: Darbo pertvarkymas, siekiant sumažinti darbo keliamus iššūkius ir įtampą darbe'],
		['Psichosocialinė rizika ir jos valdymas', 'Q303_2', 'Psichosocialinės rizikos mažinimo priemonės, taikytos per pastaruosius 3 metus: Konfidencialus darbuotojų konsultavimas'],
		['Psichosocialinė rizika ir jos valdymas', 'Q303_3', 'Psichosocialinės rizikos mažinimo priemonės, taikytos per pastaruosius 3 metus: Konfliktų sprendimo procedūros sudarymas'],
		['Psichosocialinė rizika ir jos valdymas', 'Q303_4', 'Psichosocialinės rizikos mažinimo priemonės, taikytos per pastaruosius 3 metus: Įsikišimas, jeigu dirbama pernelyg ilgai ar darbo valandos nepastovios'],
		['Psichosocialinė rizika ir jos valdymas', 'Q307', 'Pakankama informacija apie tai, kaip psichosocialinę riziką įtraukti į rizikos vertinimą'],
		['Paskatos ir kliūtys', 'Q264_1', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Teisinių įsipareigojimų įvykdymas'],
		['Paskatos ir kliūtys', 'Q264_2', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbuotojų lūkesčių pateisinimas'],
		['Paskatos ir kliūtys', 'Q264_4', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbo našumo didinimas'],
		['Paskatos ir kliūtys', 'Q264_5', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Organizacijos reputacija'],
		['Paskatos ir kliūtys', 'Q264_6', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbo inspekcijos skiriamų baudų išvengimas'],
		['Paskatos ir kliūtys', 'Q265_1', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Laiko ar darbuotojų trūkumas'],
		['Paskatos ir kliūtys', 'Q265_2', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Pinigų trūkumas'],
		['Paskatos ir kliūtys', 'Q265_3', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Nepakankamas darbuotojų informuotumas'],
		['Paskatos ir kliūtys', 'Q265_4', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Nepakankamas vadovybės informuotumas'],
		['Paskatos ir kliūtys', 'Q265_5', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Kompetencijos ar specialistų paramos stoka'],
		['Paskatos ir kliūtys', 'Q265_6', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Dokumentų tvarkymas'],
		['Paskatos ir kliūtys', 'Q265_7', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Teisinių įsipareigojimų sudėtingumas'],
		['Paskatos ir kliūtys', 'Q304', 'Priemonės, kurių buvo imtasi kilus konkrečioms problemoms'],
		['Paskatos ir kliūtys', 'Q306a_3', 'Sunkumai, kylantys mažinant psichosocialinę riziką: Nepakankamas darbuotojų informuotumas'],
		['Paskatos ir kliūtys', 'Q306a_4', 'Sunkumai, kylantys mažinant psichosocialinę riziką: Nepakankamas vadovybės informuotumas'],
		['Paskatos ir kliūtys', 'Q306a_5', 'Sunkumai, kylantys mažinant psichosocialinę riziką: Kompetencijos ar specialistų paramos stoka'],
		['Paskatos ir kliūtys', 'Q306a_6', 'Sunkumai, kylantys mažinant psichosocialinę riziką: Nenoras atvirai kalbėti apie šias problemas'],
		['Darbuotojų dalyvavimas', 'Q166_1', 'Atstovavimo darbuotojams formos: Darbo taryba'],
		['Darbuotojų dalyvavimas', 'Q166_2', 'Atstovavimo darbuotojams formos: Profesinės sąjungos atstovas'],
		['Darbuotojų dalyvavimas', 'Q166_3', 'Atstovavimo darbuotojams formos: Darbuotojų atstovas saugai ir sveikatai'],
		['Darbuotojų dalyvavimas', 'Q166_4', 'Atstovavimo darbuotojams formos: Darbuotojų sveikatos ir saugos komitetas'],
		['Darbuotojų dalyvavimas', 'Q258b', 'Atlikus rizikos vertinimą, darbuotojai dalyvauja kuriant priemones'],
		['Darbuotojų dalyvavimas', 'Q305', 'Darbuotojai atlieka tam tikrą vaidmenį kuriant psichosocialinės rizikos mažinimo priemones'],
		['Darbuotojų dalyvavimas', 'Q350', 'Kaip dažnai darbuotojų atstovai ir vadovybė aptaria darbuotojų saugos ir sveikatos klausimus?'],
		['Darbuotojų dalyvavimas', 'Q351', 'Kaip dažnai kyla su darbuotojų sveikata ir sauga susijusių ginčų?'],
		['Darbuotojų dalyvavimas', 'Q354', 'Darbuotojų atstovams saugai ir sveikatai darbo metu organizuojami mokymai'],
		['Darbuotojų dalyvavimas', 'Q358', 'Darbuotojų saugos ir sveikatos klausimai aptariami darbuotojų ar komandos susirinkimuose']
	];
var question_
	 = [
	
		['Q200_1', 'Įmonėje egzistuojantys rizikos veiksniai: Varginančios ar skausmingos kūno padėtys'],
		['Q200_2', 'Įmonėje egzistuojantys rizikos veiksniai: Žmonių arba sunkių krovinių kėlimas ir nešimas'],
		['Q200_3', 'Įmonėje egzistuojantys rizikos veiksniai: Didelis triukšmas'],
		['Q200_4', 'Įmonėje egzistuojantys rizikos veiksniai: Pasikartojantys plaštakų arba rankų judesiai'],
		['Q200_5', 'Įmonėje egzistuojantys rizikos veiksniai: Karštis, šaltis arba skersvėjis'],
		['Q200_6', 'Įmonėje egzistuojantys rizikos veiksniai: Nelaimingų atsitikimų rizika dirbant su mašinomis'],
		['Q200_7', 'Įmonėje egzistuojantys rizikos veiksniai: Nelaimingų atsitikimų rizika, susijusi su darbo metu naudojamomis variklinėmis transporto priemonėmis'],
		['Q200_8', 'Įmonėje egzistuojantys rizikos veiksniai: Cheminės arba biologinės medžiagos'],
		['Q200_9', 'Įmonėje egzistuojantys rizikos veiksniai: Padidėjusi rizika paslysti, suklupti ar parkristi'],
		['Q201_1', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Spaudimas dėl laiko stokos'],
		['Q201_2', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Menkas bendravimas ar bendradarbiavimas'],
		['Q201_3', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Nepakankamas darbuotojų gebėjimas daryti įtaką'],
		['Q201_4', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Neužtikrintumas dėl darbo vietos'],
		['Q201_5', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Darbas su sunkiais klientais, pacientais, mokiniais ir pan.'],
		['Q201_6', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Ilgos arba nereguliarios darbo valandos'],
		['Q201_7', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Diskriminacija'],
		['Q250', 'Su darbo vieta susijusios rizikos vertinimas'],
		['Q251', 'Su darbo vieta susijusios rizikos vertinimą daugiausia atlieka įmonės darbuotojai arba išorės paslaugų teikėjai'],
		['Q264_1', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Teisinių įsipareigojimų įvykdymas'],
		['Q264_2', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbuotojų lūkesčių pateisinimas'],
		['Q264_4', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbo našumo didinimas'],
		['Q264_5', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Organizacijos reputacija'],
		['Q264_6', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbo inspekcijos skiriamų baudų išvengimas'],
		['Q307', 'Pakankama informacija apie tai, kaip psichosocialinę riziką įtraukti į rizikos vertinimą'],
		['Q150_1', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Profesinės sveikatos specialistas'],
		['Q150_2', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Psichologas'],
		['Q150_3', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Ergonomiško dizaino ir darbo vietų įrengimo specialistas'],
		['Q150_4', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Plataus profilio sveikatos ir saugos specialistas'],
		['Q150_5', 'Naudojimasis darbuotojų saugos ir sveikatos paslaugomis: Nelaimingų atsitikimų prevencijos specialistas'],
		['Q155', 'Darbuotojai gali susipažinti su dokumentu, kuriame paaiškintos su sauga ir sveikata susijusios jų pareigos ir procedūros'],
		['Q156', 'Kasmet numatomos konkrečios išlaidos darbuotojų saugos ir sveikatos priemonėms bei įrangai'],
		['Q158_1', 'Darbuotojų sveikatai stiprinti skirtos priemonės: Išsamesnės informacijos apie mitybą teikimas '],
		['Q158_2', 'Darbuotojų sveikatai stiprinti skirtos priemonės: Išsamesnės informacijos apie priklausomybių prevenciją teikimas'],
		['Q158_3', 'Darbuotojų sveikatai stiprinti skirtos priemonės: Sportinės veiklos ne darbo valandomis skatinimas'],
		['Q158_4', 'Darbuotojų sveikatai stiprinti skirtos priemonės: Skatinimas darbe atlikti fizinius pratimus'],
		['Q160', 'Nuolatinė darbuotojų nedarbingumo dėl ligos priežasčių analizė'],
		['Q165', 'Per pastaruosius 3 metus įmonėje lankėsi Darbo inspekcija, norėdama patikrinti darbuotojų saugos ir sveikatos sąlygas'],
		['Q200_1', 'Įmonėje egzistuojantys rizikos veiksniai: Varginančios ar skausmingos kūno padėtys'],
		['Q200_2', 'Įmonėje egzistuojantys rizikos veiksniai: Žmonių arba sunkių krovinių kėlimas ir nešimas'],
		['Q200_3', 'Įmonėje egzistuojantys rizikos veiksniai: Didelis triukšmas'],
		['Q200_4', 'Įmonėje egzistuojantys rizikos veiksniai: Pasikartojantys plaštakų arba rankų judesiai'],
		['Q200_5', 'Įmonėje egzistuojantys rizikos veiksniai: Karštis, šaltis arba skersvėjis'],
		['Q200_6', 'Įmonėje egzistuojantys rizikos veiksniai: Nelaimingų atsitikimų rizika dirbant su mašinomis'],
		['Q200_7', 'Įmonėje egzistuojantys rizikos veiksniai: Nelaimingų atsitikimų rizika, susijusi su darbo metu naudojamomis variklinėmis transporto priemonėmis'],
		['Q200_8', 'Įmonėje egzistuojantys rizikos veiksniai: Cheminės arba biologinės medžiagos'],
		['Q200_9', 'Įmonėje egzistuojantys rizikos veiksniai: Padidėjusi rizika paslysti, suklupti ar parkristi'],
		['Q202_1', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Varginančios ar skausmingos kūno padėtys'],
		['Q202_2', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Žmonių arba sunkių krovinių kėlimas ir nešimas'],
		['Q202_3', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Didelis triukšmas'],
		['Q202_4', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Pasikartojantys plaštakų arba rankų judesiai'],
		['Q202_5', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Karštis, šaltis arba skersvėjis'],
		['Q202_6', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Nelaimingų atsitikimų rizika dirbant su mašinomis'],
		['Q202_7', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Nelaimingų atsitikimų rizika, susijusi su darbo metu naudojamomis variklinėmis transporto priemonėmis'],
		['Q202_8', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Cheminės arba biologinės medžiagos'],
		['Q202_9', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Padidėjusi rizika paslysti, suklupti ar parkristi'],
		['Q250', 'Su darbo vieta susijusios rizikos vertinimas'],
		['Q251', 'Su darbo vieta susijusios rizikos vertinimą daugiausia atlieka įmonės darbuotojai arba išorės paslaugų teikėjai'],
		['Q252_1', 'Aspektai, kurie vertinami atliekant su darbo vieta susijusios rizikos vertinimą: Mašinų, įrangos ir įrenginių sauga'],
		['Q252_2', 'Aspektai, kurie vertinami atliekant su darbo vieta susijusios rizikos vertinimą: Pavojingos medžiagos'],
		['Q252_3', 'Aspektai, kurie vertinami atliekant su darbo vieta susijusios rizikos vertinimą: Laikysena darbe, fizinis darbo krūvis ir pasikartojantys judesiai'],
		['Q252_4', 'Aspektai, kurie vertinami atliekant su darbo vieta susijusios rizikos vertinimą: Triukšmas, vibracija, karštis ar šaltis'],
		['Q252_5', 'Aspektai, kurie vertinami atliekant su darbo vieta susijusios rizikos vertinimą: Vadovo ir darbuotojo santykiai'],
		['Q252_6', 'Aspektai, kurie vertinami atliekant su darbo vieta susijusios rizikos vertinimą: Organizaciniai aspektai'],
		['Q254gr', 'Metai, kuriais paskutinį kartą buvo atliktas su darbo vieta susijusios rizikos vertinimas'],
		['Q255', 'Su darbo vieta susijusios rizikos vertinimo įforminimas dokumentuose'],
		['Q256_1', 'Darbuotojai supažindinti su išvadomis, kuriose pateikiamas su darbo vieta susijusios rizikos vertinimas: Vadovybei'],
		['Q256_2', 'Darbuotojai supažindinti su išvadomis, kuriose pateikiamas su darbo vieta susijusios rizikos vertinimas: Darbuotojų atstovui saugai ir sveikatai'],
		['Q256_3', 'Darbuotojai supažindinti su išvadomis, kuriose pateikiamas su darbo vieta susijusios rizikos vertinimas: Darbo tarybai'],
		['Q256_4', 'Darbuotojai supažindinti su išvadomis, kuriose pateikiamas su darbo vieta susijusios rizikos vertinimas: Profesinės sąjungos atstovams'],
		['Q256_5', 'Darbuotojai supažindinti su išvadomis, kuriose pateikiamas su darbo vieta susijusios rizikos vertinimas: Patiems darbuotojams'],
		['Q259', 'Rizikos vertinimas laikomas naudinga darbuotojų saugos ir sveikatos valdymo priemone'],
		['Q261_1', 'Priežastys, dėl kurių reguliariai neatliekamas su darbo vieta susijusios rizikos vertinimas: Pavojai ir rizika jau žinomi'],
		['Q261_2', 'Priežastys, dėl kurių reguliariai neatliekamas su darbo vieta susijusios rizikos vertinimas: nėra rimtų problemų'],
		['Q261_3', 'Priežastys, dėl kurių reguliariai neatliekamas su darbo vieta susijusios rizikos vertinimas: ši procedūra pernelyg sudėtinga'],
		['Q261_4', 'Priežastys, dėl kurių reguliariai neatliekamas su darbo vieta susijusios rizikos vertinimas: trūksta reikiamų žinių'],
		['Q308_1', 'Raumenų ir kaulų sistemos sutrikimų prevencinės priemonės: Įranga, skirta padėti kelti ar vežti krovinius'],
		['Q308_2', 'Raumenų ir kaulų sistemos sutrikimų prevencinės priemonės: Užduočių kaitaliojimas, siekiant sumažinti fizinį krūvį'],
		['Q308_3', 'Raumenų ir kaulų sistemos sutrikimų prevencinės priemonės: Skatinimas daryti reguliarias pertraukas tiems darbuotojams, kurių kūno padėtis būna nepatogi arba statiška'],
		['Q308_4', 'Raumenų ir kaulų sistemos sutrikimų prevencinės priemonės: Ergonomiškos įrangos įsigijimas'],
		['Q356_1', 'Darbuotojų mokymai: Tinkamas įrangos ir baldų naudojimas ir reguliavimas'],
		['Q356_2', 'Darbuotojų mokymai: Pavojingų medžiagų naudojimas'],
		['Q356_3', 'Darbuotojų mokymai: Kaip užkirsti kelią psichosocialinei rizikai?'],
		['Q356_4', 'Darbuotojų mokymai: Kaip kelti ir nešti sunkius krovinius ar žmones?'],
		['Q356_5', 'Darbuotojų mokymai: Skubios pagalbos procedūros'],
		['Q201_1', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Spaudimas dėl laiko stokos'],
		['Q201_2', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Menkas bendravimas ar bendradarbiavimas'],
		['Q201_3', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Nepakankamas darbuotojų gebėjimas daryti įtaką'],
		['Q201_4', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Neužtikrintumas dėl darbo vietos'],
		['Q201_5', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Darbas su sunkiais klientais, pacientais, mokiniais ir pan.'],
		['Q201_6', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Ilgos arba nereguliarios darbo valandos'],
		['Q201_7', 'Įmonėje egzistuojantys psichosocialinės rizikos veiksniai: Diskriminacija'],
		['Q202_10', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Spaudimas dėl laiko stokos'],
		['Q202_11', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Menkas bendravimas ar bendradarbiavimas'],
		['Q202_12', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Nepakankamas darbuotojų gebėjimas daryti įtaką'],
		['Q202_13', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Neužtikrintumas dėl darbo vietos'],
		['Q202_14', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Darbas su sunkiais klientais, pacientais, mokiniais ir pan.'],
		['Q202_15', 'Informacijos arba tinkamų prevencijos priemonių, padedančių efektyviai spręsti problemas, trūkumas: Ilgos arba nereguliarios darbo valandos'],
		['Q300', 'Numatytas streso darbe prevencijos veiksmų planas'],
		['Q301', 'Numatyta procedūra patyčių ar priekabiavimo atvejams spręsti'],
		['Q302', 'Numatyta procedūra grasinimo, užgauliojimo ar smurto atvejams spręsti'],
		['Q303_1', 'Psichosocialinės rizikos mažinimo priemonės, taikytos per pastaruosius 3 metus: Darbo pertvarkymas, siekiant sumažinti darbo keliamus iššūkius ir įtampą darbe'],
		['Q303_2', 'Psichosocialinės rizikos mažinimo priemonės, taikytos per pastaruosius 3 metus: Konfidencialus darbuotojų konsultavimas'],
		['Q303_3', 'Psichosocialinės rizikos mažinimo priemonės, taikytos per pastaruosius 3 metus: Konfliktų sprendimo procedūros sudarymas'],
		['Q303_4', 'Psichosocialinės rizikos mažinimo priemonės, taikytos per pastaruosius 3 metus: Įsikišimas, jeigu dirbama pernelyg ilgai ar darbo valandos nepastovios'],
		['Q307', 'Pakankama informacija apie tai, kaip psichosocialinę riziką įtraukti į rizikos vertinimą'],
		['Q264_1', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Teisinių įsipareigojimų įvykdymas'],
		['Q264_2', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbuotojų lūkesčių pateisinimas'],
		['Q264_4', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbo našumo didinimas'],
		['Q264_5', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Organizacijos reputacija'],
		['Q264_6', 'Darbuotojų saugos ir sveikatos klausimų sprendimo darbovietėje priežastys: Darbo inspekcijos skiriamų baudų išvengimas'],
		['Q265_1', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Laiko ar darbuotojų trūkumas'],
		['Q265_2', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Pinigų trūkumas'],
		['Q265_3', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Nepakankamas darbuotojų informuotumas'],
		['Q265_4', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Nepakankamas vadovybės informuotumas'],
		['Q265_5', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Kompetencijos ar specialistų paramos stoka'],
		['Q265_6', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Dokumentų tvarkymas'],
		['Q265_7', 'Didžiausios problemos, kylančios sprendžiant darbuotojų saugos ir sveikatos klausimus: Teisinių įsipareigojimų sudėtingumas'],
		['Q304', 'Priemonės, kurių buvo imtasi kilus konkrečioms problemoms'],
		['Q306a_3', 'Sunkumai, kylantys mažinant psichosocialinę riziką: Nepakankamas darbuotojų informuotumas'],
		['Q306a_4', 'Sunkumai, kylantys mažinant psichosocialinę riziką: Nepakankamas vadovybės informuotumas'],
		['Q306a_5', 'Sunkumai, kylantys mažinant psichosocialinę riziką: Kompetencijos ar specialistų paramos stoka'],
		['Q306a_6', 'Sunkumai, kylantys mažinant psichosocialinę riziką: Nenoras atvirai kalbėti apie šias problemas'],
		['Q166_1', 'Atstovavimo darbuotojams formos: Darbo taryba'],
		['Q166_2', 'Atstovavimo darbuotojams formos: Profesinės sąjungos atstovas'],
		['Q166_3', 'Atstovavimo darbuotojams formos: Darbuotojų atstovas saugai ir sveikatai'],
		['Q166_4', 'Atstovavimo darbuotojams formos: Darbuotojų sveikatos ir saugos komitetas'],
		['Q258b', 'Atlikus rizikos vertinimą, darbuotojai dalyvauja kuriant priemones'],
		['Q305', 'Darbuotojai atlieka tam tikrą vaidmenį kuriant psichosocialinės rizikos mažinimo priemones'],
		['Q350', 'Kaip dažnai darbuotojų atstovai ir vadovybė aptaria darbuotojų saugos ir sveikatos klausimus?'],
		['Q351', 'Kaip dažnai kyla su darbuotojų sveikata ir sauga susijusių ginčų?'],
		['Q354', 'Darbuotojų atstovams saugai ir sveikatai darbo metu organizuojami mokymai'],
		['Q358', 'Darbuotojų saugos ir sveikatos klausimai aptariami darbuotojų ar komandos susirinkimuose']
	];
var question_answer
	 = [
	
		['Q150_1', '1--Yes', 'Taip'],
		['Q150_1', '2--No', 'Ne'],
		['Q150_2', '1--Yes', 'Taip'],
		['Q150_2', '2--No', 'Ne'],
		['Q150_3', '1--Yes', 'Taip'],
		['Q150_3', '2--No', 'Ne'],
		['Q150_4', '1--Yes', 'Taip'],
		['Q150_4', '2--No', 'Ne'],
		['Q150_5', '1--Yes', 'Taip'],
		['Q150_5', '2--No', 'Ne'],
		['Q155', '1--Yes', 'Taip'],
		['Q155', '2--No', 'Ne'],
		['Q155', '3--Yes--but-only-to-some-types-of-employees', 'Taip, bet tik kai kurias pareigas einantiems darbuotojams'],
		['Q156', '1--Yes', 'Taip'],
		['Q156', '2--No', 'Ne'],
		['Q158_1', '1--Yes', 'Taip'],
		['Q158_1', '2--No', 'Ne'],
		['Q158_2', '1--Yes', 'Taip'],
		['Q158_2', '2--No', 'Ne'],
		['Q158_3', '1--Yes', 'Taip'],
		['Q158_3', '2--No', 'Ne'],
		['Q158_4', '1--Yes', 'Taip'],
		['Q158_4', '2--No', 'Ne'],
		['Q160', '1--Yes', 'Taip'],
		['Q160', '2--No', 'Ne'],
		['Q165', '1--Yes', 'Taip'],
		['Q165', '2--No', 'Ne'],
		['Q166_1', '1--Yes', 'Taip'],
		['Q166_1', '2--No', 'Ne'],
		['Q166_2', '1--Yes', 'Taip'],
		['Q166_2', '2--No', 'Ne'],
		['Q166_3', '1--Yes', 'Taip'],
		['Q166_3', '2--No', 'Ne'],
		['Q166_4', '1--Yes', 'Taip'],
		['Q166_4', '2--No', 'Ne'],
		['Q200_1', '1--Yes', 'Taip'],
		['Q200_1', '2--No', 'Ne'],
		['Q200_2', '1--Yes', 'Taip'],
		['Q200_2', '2--No', 'Ne'],
		['Q200_3', '1--Yes', 'Taip'],
		['Q200_3', '2--No', 'Ne'],
		['Q200_4', '1--Yes', 'Taip'],
		['Q200_4', '2--No', 'Ne'],
		['Q200_5', '1--Yes', 'Taip'],
		['Q200_5', '2--No', 'Ne'],
		['Q200_6', '1--Yes', 'Taip'],
		['Q200_6', '2--No', 'Ne'],
		['Q200_7', '1--Yes', 'Taip'],
		['Q200_7', '2--No', 'Ne'],
		['Q200_8', '1--Yes', 'Taip'],
		['Q200_8', '2--No', 'Ne'],
		['Q200_9', '1--Yes', 'Taip'],
		['Q200_9', '2--No', 'Ne'],
		['Q201_1', '1--Yes', 'Taip'],
		['Q201_1', '2--No', 'Ne'],
		['Q201_2', '1--Yes', 'Taip'],
		['Q201_2', '2--No', 'Ne'],
		['Q201_3', '1--Yes', 'Taip'],
		['Q201_3', '2--No', 'Ne'],
		['Q201_4', '1--Yes', 'Taip'],
		['Q201_4', '2--No', 'Ne'],
		['Q201_5', '1--Yes', 'Taip'],
		['Q201_5', '2--No', 'Ne'],
		['Q201_6', '1--Yes', 'Taip'],
		['Q201_6', '2--No', 'Ne'],
		['Q201_7', '1--Yes', 'Taip'],
		['Q201_7', '2--No', 'Ne'],
		['Q202_1', '1--Yes', 'Taip'],
		['Q202_1', '2--No', 'Ne'],
		['Q202_10', '1--Yes', 'Taip'],
		['Q202_10', '2--No', 'Ne'],
		['Q202_11', '1--Yes', 'Taip'],
		['Q202_11', '2--No', 'Ne'],
		['Q202_12', '1--Yes', 'Taip'],
		['Q202_12', '2--No', 'Ne'],
		['Q202_13', '1--Yes', 'Taip'],
		['Q202_13', '2--No', 'Ne'],
		['Q202_14', '1--Yes', 'Taip'],
		['Q202_14', '2--No', 'Ne'],
		['Q202_15', '1--Yes', 'Taip'],
		['Q202_15', '2--No', 'Ne'],
		['Q202_2', '1--Yes', 'Taip'],
		['Q202_2', '2--No', 'Ne'],
		['Q202_3', '1--Yes', 'Taip'],
		['Q202_3', '2--No', 'Ne'],
		['Q202_4', '1--Yes', 'Taip'],
		['Q202_4', '2--No', 'Ne'],
		['Q202_5', '1--Yes', 'Taip'],
		['Q202_5', '2--No', 'Ne'],
		['Q202_6', '1--Yes', 'Taip'],
		['Q202_6', '2--No', 'Ne'],
		['Q202_7', '1--Yes', 'Taip'],
		['Q202_7', '2--No', 'Ne'],
		['Q202_8', '1--Yes', 'Taip'],
		['Q202_8', '2--No', 'Ne'],
		['Q202_9', '1--Yes', 'Taip'],
		['Q202_9', '2--No', 'Ne'],
		['Q250', '1--Yes', 'Taip'],
		['Q250', '2--No', 'Ne'],
		['Q251', '1--Conducted-mainly-by-internal-staff', 'Daugiausia atlieka darbovietės darbuotojai'],
		['Q251', '2--Contracted-mainly-to-external-providers', 'Daugiausia atlieka išorės paslaugų teikėjai'],
		['Q251', '3--Both-about-equally', 'Maždaug vienodai'],
		['Q252_1', '1--Yes', 'Taip'],
		['Q252_1', '2--No', 'Ne'],
		['Q252_2', '1--Yes', 'Taip'],
		['Q252_2', '2--No', 'Ne'],
		['Q252_3', '1--Yes', 'Taip'],
		['Q252_3', '2--No', 'Ne'],
		['Q252_4', '1--Yes', 'Taip'],
		['Q252_4', '2--No', 'Ne'],
		['Q252_5', '1--Yes', 'Taip'],
		['Q252_5', '2--No', 'Ne'],
		['Q252_6', '1--Yes', 'Taip'],
		['Q252_6', '2--No', 'Ne'],
		['Q254gr', '1--2010', '2010'],
		['Q254gr', '2--2011', '2011'],
		['Q254gr', '3--2012', '2012'],
		['Q254gr', '4--2013', '2013'],
		['Q254gr', '5--2014', '2014'],
		['Q254gr', '6--before-2010', 'iki 2010 m.'],
		['Q254gr', '7--don-t-know', 'Nežino'],
		['Q255', '1--Yes', 'Taip'],
		['Q255', '2--No', 'Ne'],
		['Q256_1', '1--Yes', 'Taip'],
		['Q256_1', '2--No', 'Ne'],
		['Q256_2', '1--Yes', 'Taip'],
		['Q256_2', '2--No', 'Ne'],
		['Q256_3', '1--Yes', 'Taip'],
		['Q256_3', '2--No', 'Ne'],
		['Q256_4', '1--Yes', 'Taip'],
		['Q256_4', '2--No', 'Ne'],
		['Q256_5', '1--Yes', 'Taip'],
		['Q256_5', '2--No', 'Ne'],
		['Q258b', '1--Yes', 'Taip'],
		['Q258b', '2--No', 'Ne'],
		['Q258b', '3--That-depends-on-the-type-of-measures', 'Tai priklauso nuo priemonių rūšies'],
		['Q259', '1--Yes', 'Taip'],
		['Q259', '2--No', 'Ne'],
		['Q259', '3--There-are-conflicting-views-about-this', 'Yra prieštaringų nuomonių'],
		['Q261_1', '1--Yes', 'Taip'],
		['Q261_1', '2--No', 'Ne'],
		['Q261_2', '1--Yes', 'Taip'],
		['Q261_2', '2--No', 'Ne'],
		['Q261_3', '1--Yes', 'Taip'],
		['Q261_3', '2--No', 'Ne'],
		['Q261_4', '1--Yes', 'Taip'],
		['Q261_4', '2--No', 'Ne'],
		['Q264_1', '1--Major-reason', 'Labai svarbi priežastis'],
		['Q264_1', '2--Minor-reason', 'Nelabai svarbi priežastis'],
		['Q264_1', '3--Not-a-reason', 'Visiškai nesvarbi priežastis'],
		['Q264_2', '1--Major-reason', 'Labai svarbi priežastis'],
		['Q264_2', '2--Minor-reason', 'Nelabai svarbi priežastis'],
		['Q264_2', '3--Not-a-reason', 'Visiškai nesvarbi priežastis'],
		['Q264_4', '1--Major-reason', 'Labai svarbi priežastis'],
		['Q264_4', '2--Minor-reason', 'Nelabai svarbi priežastis'],
		['Q264_4', '3--Not-a-reason', 'Visiškai nesvarbi priežastis'],
		['Q264_5', '1--Major-reason', 'Labai svarbi priežastis'],
		['Q264_5', '2--Minor-reason', 'Nelabai svarbi priežastis'],
		['Q264_5', '3--Not-a-reason', 'Visiškai nesvarbi priežastis'],
		['Q264_6', '1--Major-reason', 'Labai svarbi priežastis'],
		['Q264_6', '2--Minor-reason', 'Nelabai svarbi priežastis'],
		['Q264_6', '3--Not-a-reason', 'Visiškai nesvarbi priežastis'],
		['Q265_1', '1--Major-difficulty', 'Didelė problema'],
		['Q265_1', '2--Minor-difficulty', 'Nedidelė problema'],
		['Q265_1', '3--Not-a-difficulty', 'Visai ne problema'],
		['Q265_2', '1--Major-difficulty', 'Didelė problema'],
		['Q265_2', '2--Minor-difficulty', 'Nedidelė problema'],
		['Q265_2', '3--Not-a-difficulty', 'Visai ne problema'],
		['Q265_3', '1--Major-difficulty', 'Didelė problema'],
		['Q265_3', '2--Minor-difficulty', 'Nedidelė problema'],
		['Q265_3', '3--Not-a-difficulty', 'Visai ne problema'],
		['Q265_4', '1--Major-difficulty', 'Didelė problema'],
		['Q265_4', '2--Minor-difficulty', 'Nedidelė problema'],
		['Q265_4', '3--Not-a-difficulty', 'Visai ne problema'],
		['Q265_5', '1--Major-difficulty', 'Didelė problema'],
		['Q265_5', '2--Minor-difficulty', 'Nedidelė problema'],
		['Q265_5', '3--Not-a-difficulty', 'Visai ne problema'],
		['Q265_6', '1--Major-difficulty', 'Didelė problema'],
		['Q265_6', '2--Minor-difficulty', 'Nedidelė problema'],
		['Q265_6', '3--Not-a-difficulty', 'Visai ne problema'],
		['Q265_7', '1--Major-difficulty', 'Didelė problema'],
		['Q265_7', '2--Minor-difficulty', 'Nedidelė problema'],
		['Q265_7', '3--Not-a-difficulty', 'Visai ne problema'],
		['Q300', '1--Yes', 'Taip'],
		['Q300', '2--No', 'Ne'],
		['Q301', '1--Yes', 'Taip'],
		['Q301', '2--No', 'Ne'],
		['Q302', '1--Yes', 'Taip'],
		['Q302', '2--No', 'Ne'],
		['Q303_1', '1--Yes', 'Taip'],
		['Q303_1', '2--No', 'Ne'],
		['Q303_2', '1--Yes', 'Taip'],
		['Q303_2', '2--No', 'Ne'],
		['Q303_3', '1--Yes', 'Taip'],
		['Q303_3', '2--No', 'Ne'],
		['Q303_4', '1--Yes', 'Taip'],
		['Q303_4', '2--No', 'Ne'],
		['Q304', '1--Yes', 'Taip'],
		['Q304', '2--No', 'Ne'],
		['Q304', '3--Partly', 'Iš dalies'],
		['Q305', '1--Yes', 'Taip'],
		['Q305', '2--No', 'Ne'],
		['Q306a_3', '1--Yes', 'Taip'],
		['Q306a_3', '2--No', 'Ne'],
		['Q306a_4', '1--Yes', 'Taip'],
		['Q306a_4', '2--No', 'Ne'],
		['Q306a_5', '1--Yes', 'Taip'],
		['Q306a_5', '2--No', 'Ne'],
		['Q306a_6', '1--Yes', 'Taip'],
		['Q306a_6', '2--No', 'Ne'],
		['Q307', '1--Yes', 'Taip'],
		['Q307', '2--No', 'Ne'],
		['Q308_1', '1--Yes', 'Taip'],
		['Q308_1', '2--No', 'Ne'],
		['Q308_2', '1--Yes', 'Taip'],
		['Q308_2', '2--No', 'Ne'],
		['Q308_3', '1--Yes', 'Taip'],
		['Q308_3', '2--No', 'Ne'],
		['Q308_4', '1--Yes', 'Taip'],
		['Q308_4', '2--No', 'Ne'],
		['Q350', '1--Regularly', 'Reguliariai'],
		['Q350', '2--Only-when-particular-issues-arise', 'Tik iškilus konkrečių problemų'],
		['Q350', '3--Not-at-all', 'Nevyksta visai'],
		['Q351', '1--Often', 'Dažnai'],
		['Q351', '2--Sometimes', 'Kartais'],
		['Q351', '3--Practically-never', 'Beveik niekada'],
		['Q354', '1--Yes', 'Taip'],
		['Q354', '2--No', 'Ne'],
		['Q354', '3--Yes--but-only-some-of-them', 'Taip, bet tik kai kuriems iš jų'],
		['Q356_1', '1--Yes', 'Taip'],
		['Q356_1', '2--No', 'Ne'],
		['Q356_2', '1--Yes', 'Taip'],
		['Q356_2', '2--No', 'Ne'],
		['Q356_3', '1--Yes', 'Taip'],
		['Q356_3', '2--No', 'Ne'],
		['Q356_4', '1--Yes', 'Taip'],
		['Q356_4', '2--No', 'Ne'],
		['Q356_5', '1--Yes', 'Taip'],
		['Q356_5', '2--No', 'Ne'],
		['Q358', '1--Yes', 'Taip'],
		['Q358', '2--No', 'Ne'],
		['Q358', '3--In-some-departments-only', 'Tik kai kuriuose skyriuose']
	];
var country_
	 = [
	
		['AL', 'Albanija'],
		['AT', 'Austrija'],
		['BE', 'Belgija'],
		['BG', 'Bulgarija'],
		['CH', 'Šveicarija'],
		['CY', 'Kipras'],
		['CZ', 'Čekija'],
		['DE', 'Vokietija'],
		['DK', 'Danija'],
		['EE', 'Estija'],
		['EL', 'Graikija'],
		['ES', 'Ispanija'],
		['FI', 'Suomija'],
		['FR', 'Prancūzija'],
		['HR', 'Kroatija'],
		['HU', 'Vengrija'],
		['IE', 'Airija'],
		['IS', 'Islandija'],
		['IT', 'Italija'],
		['LT', 'Lietuva'],
		['LU', 'Liuksemburgas'],
		['LV', 'Latvija'],
		['ME', 'Juodkalnija'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Nyderlandai'],
		['NO', 'Norvegija'],
		['PL', 'Lenkija'],
		['PT', 'Portugalija'],
		['RO', 'Rumunija'],
		['RS', 'Serbija'],
		['SE', 'Švedija'],
		['SI', 'Slovėnija'],
		['SK', 'Slovakija'],
		['TR', 'Turkija'],
		['UK', 'Jungtinė Karalystė'],
		['EuropeanUnion', 'Europos Sąjunga']
	];
var question_meta
	 = [
	
		['Q200_1', 'Varginančios ar skausmingos kūno padėtys, įskaitant ilgą sėdėjimą', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Varginančios ar skausmingos kūno padėtys, įskaitant ilgą sėdėjimą<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_2', 'Žmonių arba sunkių krovinių kėlimas ir nešimas', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Žmonių arba sunkių krovinių kėlimas ir nešimas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_3', 'Didelis triukšmas', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Didelis triukšmas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_4', 'Pasikartojantys plaštakų arba rankų judesiai', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Pasikartojantys plaštakų arba rankų judesiai<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_5', 'Karštis, šaltis arba skersvėjis', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Karštis, šaltis arba skersvėjis<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_6', 'Nelaimingų atsitikimų rizika dirbant su mašinomis arba įrankiais', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Nelaimingų atsitikimų rizika dirbant su mašinomis arba įrankiais<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_7', 'Nelaimingų atsitikimų rizika dirbant su transporto priemonėmis darbo metu, bet ne pakeliui į darbą ar iš darbo', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Nelaimingų atsitikimų rizika dirbant su transporto priemonėmis darbo metu, bet ne pakeliui į darbą ar iš darbo<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_8', 'Skystos, garų arba dulkių pavidalo cheminės ar biologinės medžiagos', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Skystos, garų arba dulkių pavidalo cheminės ar biologinės medžiagos<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_9', 'Padidėjusi rizika paslysti, suklupti ar parkristi', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Padidėjusi rizika paslysti, suklupti ar parkristi<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q201_1', 'Spaudimas dėl laiko stokos', 'Be šios rizikos dar gali būti sveikatos rizika, susijusi su darbo organizavimu, socialiniais santykiais darbe arba ekonomine padėtimi. Nurodykite, ar šie veiksniai egzistuoja Jūsų darbovietėje. Spaudimas dėl laiko stokos<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q201_2', 'Menkas bendravimas ar bendradarbiavimas organizacijoje', 'Be šios rizikos dar gali būti sveikatos rizika, susijusi su darbo organizavimu, socialiniais santykiais darbe arba ekonomine padėtimi. Nurodykite, ar šie veiksniai egzistuoja Jūsų darbovietėje. Menkas bendravimas ar bendradarbiavimas organizacijoje<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q201_3', 'Nepakankamas darbuotojų gebėjimas daryti įtaką darbo tempui arba procesams', 'Be šios rizikos dar gali būti sveikatos rizika, susijusi su darbo organizavimu, socialiniais santykiais darbe arba ekonomine padėtimi. Nurodykite, ar šie veiksniai egzistuoja Jūsų darbovietėje. Nepakankamas darbuotojų gebėjimas daryti įtaką darbo tempui arba procesams<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q201_4', 'Neužtikrintumas dėl darbo vietos', 'Be šios rizikos dar gali būti sveikatos rizika, susijusi su darbo organizavimu, socialiniais santykiais darbe arba ekonomine padėtimi. Nurodykite, ar šie veiksniai egzistuoja Jūsų darbovietėje. Neužtikrintumas dėl darbo vietos<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q201_5', 'Darbas su sunkiais klientais, pacientais, mokiniais ir pan.', 'Be šios rizikos dar gali būti sveikatos rizika, susijusi su darbo organizavimu, socialiniais santykiais darbe arba ekonomine padėtimi. Nurodykite, ar šie veiksniai egzistuoja Jūsų darbovietėje. Darbas su sunkiais klientais, pacientais, mokiniais ir pan.<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q201_6', 'Ilgos arba nereguliarios darbo valandos', 'Be šios rizikos dar gali būti sveikatos rizika, susijusi su darbo organizavimu, socialiniais santykiais darbe arba ekonomine padėtimi. Nurodykite, ar šie veiksniai egzistuoja Jūsų darbovietėje. Ilgos arba nereguliarios darbo valandos<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q201_7', 'Diskriminacija, pavyzdžiui, dėl lyties, amžiaus ar tautybės', 'Be šios rizikos dar gali būti sveikatos rizika, susijusi su darbo organizavimu, socialiniais santykiais darbe arba ekonomine padėtimi. Nurodykite, ar šie veiksniai egzistuoja Jūsų darbovietėje. Diskriminacija, pavyzdžiui, dėl lyties, amžiaus ar tautybės<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q250', 'Ar Jūsų darbovietėje reguliariai atliekamas su darbo vieta susijusios rizikos vertinimas?', 'Ar Jūsų darbovietėje reguliariai atliekamas su darbo vieta susijusios rizikos vertinimas?<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q251', 'Ar su darbo vieta susijusios rizikos vertinimą daugiausia atlieka darbovietės darbuotojai, ar šios paslaugos perkamos iš išorės paslaugų teikėjų?', 'Ar su darbo vieta susijusios rizikos vertinimą daugiausia atlieka darbovietės darbuotojai, ar šios paslaugos perkamos iš išorės paslaugų teikėjų?<br><br>(1) Daugiausia atlieka darbovietės darbuotojai <br>(2) Daugiausia atlieka išorės paslaugų teikėjai <br>(3) Maždaug vienodai <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q264_1', 'Teisinių įsipareigojimų įvykdymas', 'Kiek svarbios Jūsų darbovietėje yra toliau nurodytos priežastys sprendžiant sveikatos ir saugos klausimus? Įvertinti, ar ši priežastis yra labai svarbi, nelabai svarbi, ar visiškai nesvarbi. Teisinių įsipareigojimų įvykdymas<br><br>(1) Labai svarbi priežastis <br>(2) Nelabai svarbi priežastis <br>(3) Visiškai nesvarbi priežastis <br>(9) Neatsakė'],
		['Q264_2', 'Darbuotojų ar jų atstovų lūkesčių pateisinimas', 'Kiek svarbios Jūsų darbovietėje yra toliau nurodytos priežastys sprendžiant sveikatos ir saugos klausimus? Įvertinti, ar ši priežastis yra labai svarbi, nelabai svarbi, ar visiškai nesvarbi. Darbuotojų ar jų atstovų lūkesčių pateisinimas<br><br>(1) Labai svarbi priežastis <br>(2) Nelabai svarbi priežastis <br>(3) Visiškai nesvarbi priežastis <br>(9) Neatsakė'],
		['Q264_4', 'Darbo našumo išlaikymas ar didinimas', 'Kiek svarbios Jūsų darbovietėje yra toliau nurodytos priežastys sprendžiant sveikatos ir saugos klausimus? Įvertinti, ar ši priežastis yra labai svarbi, nelabai svarbi, ar visiškai nesvarbi. Darbo našumo išlaikymas ar didinimas<br><br>(1) Labai svarbi priežastis <br>(2) Nelabai svarbi priežastis <br>(3) Visiškai nesvarbi priežastis <br>(9) Neatsakė'],
		['Q264_5', 'Organizacijos reputacijos išsaugojimas', 'Kiek svarbios Jūsų darbovietėje yra toliau nurodytos priežastys sprendžiant sveikatos ir saugos klausimus? Įvertinti, ar ši priežastis yra labai svarbi, nelabai svarbi, ar visiškai nesvarbi. Organizacijos reputacijos išsaugojimas<br><br>(1) Labai svarbi priežastis <br>(2) Nelabai svarbi priežastis <br>(3) Visiškai nesvarbi priežastis <br>(9) Neatsakė'],
		['Q264_6', 'Darbo inspekcijos baudų ir sankcijų išvengimas', 'Kiek svarbios Jūsų darbovietėje yra toliau nurodytos priežastys sprendžiant sveikatos ir saugos klausimus? Įvertinti, ar ši priežastis yra labai svarbi, nelabai svarbi, ar visiškai nesvarbi. Darbo inspekcijos baudų ir sankcijų išvengimas<br><br>(1) Labai svarbi priežastis <br>(2) Nelabai svarbi priežastis <br>(3) Visiškai nesvarbi priežastis <br>(9) Neatsakė'],
		['Q307', 'Ar darbovietėje yra pakankamai informacijos apie tai, kaip psichosocialinę riziką įtraukti į rizikos vertinimą?', 'Ar darbovietėje yra pakankamai informacijos apie tai, kaip psichosocialinę riziką įtraukti į rizikos vertinimą?<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q150_1', 'Profesinės sveikatos specialistas', 'Kokiomis sveikatos ir saugos paslaugomis naudojatės darbovietėje arba už jos ribų? Profesinės sveikatos specialistas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q150_2', 'Psichologas', 'Kokiomis sveikatos ir saugos paslaugomis naudojatės darbovietėje arba už jos ribų? Psichologas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q150_3', 'Ergonomiško dizaino ir darbo vietų įrengimo specialistas', 'Kokiomis sveikatos ir saugos paslaugomis naudojatės darbovietėje arba už jos ribų? Ergonomiško dizaino ir darbo vietų įrengimo specialistas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q150_4', 'Plataus profilio sveikatos ir saugos specialistas', 'Kokiomis sveikatos ir saugos paslaugomis naudojatės darbovietėje arba už jos ribų? Plataus profilio sveikatos ir saugos specialistas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q150_5', 'Nelaimingų atsitikimų prevencijos specialistas', 'Kokiomis sveikatos ir saugos paslaugomis naudojatės darbovietėje arba už jos ribų? Nelaimingų atsitikimų prevencijos specialistas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q155', 'Ar Jūsų darbovietėje yra darbuotojams prieinamas dokumentas, kuriame paaiškintos jų su sveikata ir sauga susijusios pareigos ir procedūros?', 'Ar Jūsų darbovietėje yra darbuotojams prieinamas dokumentas, kuriame paaiškintos jų su sveikata ir sauga susijusios pareigos ir procedūros?<br><br>(1) Taip <br>(2) Ne <br>(3) Taip, bet tik kai kurias pareigas einantiems darbuotojams <br>(9) Neatsakė'],
		['Q156', 'Ar Jūsų darbovietėje kasmet numatomos konkrečios išlaidos darbuotojų sveikatos ir saugos priemonėms bei įrangai?', 'Ar Jūsų darbovietėje kasmet numatomos konkrečios išlaidos darbuotojų sveikatos ir saugos priemonėms bei įrangai?<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q158_1', 'Teikė daugiau informacijos apie sveiką mitybą', 'Ar Jūsų darbovietė ėmėsi kurių nors iš toliau išvardintų priemonių darbuotojų sveikatai stiprinti? Teikė daugiau informacijos apie sveiką mitybą<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q158_2', 'Teikė daugiau informacijos apie priklausomybių, pvz., rūkymo, alkoholio ar narkotikų vartojimo, prevenciją', 'Ar Jūsų darbovietė ėmėsi kurių nors iš toliau išvardintų priemonių darbuotojų sveikatai stiprinti? Teikė daugiau informacijos apie priklausomybių, pvz., rūkymo, alkoholio ar narkotikų vartojimo, prevenciją<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q158_3', 'Skatino sportinę veiklą ne darbo valandomis', 'Ar Jūsų darbovietė ėmėsi kurių nors iš toliau išvardintų priemonių darbuotojų sveikatai stiprinti? Skatino sportinę veiklą ne darbo valandomis<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q158_4', 'Skatino darbe atlikti pratimus nugarai, tempimo ar kitus fizinius pratimus', 'Ar Jūsų darbovietė ėmėsi kurių nors iš toliau išvardintų priemonių darbuotojų sveikatai stiprinti? Skatino darbe atlikti pratimus nugarai, tempimo ar kitus fizinius pratimus<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q160', 'Ar nuolat analizuojamos darbuotojų nedarbingumo dėl ligos priežastys, siekiant pagerinti darbo sąlygas?', 'Ar nuolat analizuojamos darbuotojų nedarbingumo dėl ligos priežastys, siekiant pagerinti darbo sąlygas?<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q165', 'Ar per pastaruosius 3 metus Jūsų darbovietėje lankėsi Darbo inspekcija, norėdama patikrinti darbuotojų sveikatos ir saugos sąlygas?', 'Ar per pastaruosius 3 metus Jūsų darbovietėje lankėsi Darbo inspekcija, norėdama patikrinti darbuotojų sveikatos ir saugos sąlygas?<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_1', 'Varginančios ar skausmingos kūno padėtys, įskaitant ilgą sėdėjimą', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Varginančios ar skausmingos kūno padėtys, įskaitant ilgą sėdėjimą<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_2', 'Žmonių arba sunkių krovinių kėlimas ir nešimas', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Žmonių arba sunkių krovinių kėlimas ir nešimas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_3', 'Didelis triukšmas', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Didelis triukšmas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_4', 'Pasikartojantys plaštakų arba rankų judesiai', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Pasikartojantys plaštakų arba rankų judesiai<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_5', 'Karštis, šaltis arba skersvėjis', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Karštis, šaltis arba skersvėjis<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_6', 'Nelaimingų atsitikimų rizika dirbant su mašinomis arba įrankiais', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Nelaimingų atsitikimų rizika dirbant su mašinomis arba įrankiais<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_7', 'Nelaimingų atsitikimų rizika dirbant su transporto priemonėmis darbo metu, bet ne pakeliui į darbą ar iš darbo', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Nelaimingų atsitikimų rizika dirbant su transporto priemonėmis darbo metu, bet ne pakeliui į darbą ar iš darbo<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_8', 'Skystos, garų arba dulkių pavidalo cheminės ar biologinės medžiagos', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Skystos, garų arba dulkių pavidalo cheminės ar biologinės medžiagos<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q200_9', 'Padidėjusi rizika paslysti, suklupti ar parkristi', 'Atsižvelgiant į darbo pobūdį egzistuoja įvairių rūšių rizika ir pavojai. Nurodykite, ar kiekvienas iš toliau išvardintų rizikos veiksnių egzistuoja Jūsų darbovietėje, neatsižvelgiant į tai, ar jie šiuo metu kontroliuojami, ir neatsižvelgiant į jį patiriančių darbuotojų skaičių. Padidėjusi rizika paslysti, suklupti ar parkristi<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q202_1', 'Varginančios ar skausmingos kūno padėtys, įskaitant ilgą sėdėjimą', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Varginančios ar skausmingos kūno padėtys, įskaitant ilgą sėdėjimą<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio rizikos veiksnio buvimą.'],
		['Q202_2', 'Žmonių arba sunkių krovinių kėlimas ir nešimas', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Žmonių arba sunkių krovinių kėlimas ir nešimas<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio rizikos veiksnio buvimą.'],
		['Q202_3', 'Didelis triukšmas', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Didelis triukšmas<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio rizikos veiksnio buvimą.'],
		['Q202_4', 'Pasikartojantys plaštakų arba rankų judesiai', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Pasikartojantys plaštakų arba rankų judesiai<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio rizikos veiksnio buvimą.'],
		['Q202_5', 'Karštis, šaltis arba skersvėjis', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Karštis, šaltis arba skersvėjis<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio rizikos veiksnio buvimą.'],
		['Q202_6', 'Nelaimingų atsitikimų rizika dirbant su mašinomis arba įrankiais', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Nelaimingų atsitikimų rizika dirbant su mašinomis arba įrankiais<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio rizikos veiksnio buvimą.'],
		['Q202_7', 'Nelaimingų atsitikimų rizika dirbant su transporto priemonėmis darbo metu', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Nelaimingų atsitikimų rizika dirbant su transporto priemonėmis darbo metu<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio rizikos veiksnio buvimą.'],
		['Q202_8', 'Cheminės ar biologinės medžiagos', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Cheminės ar biologinės medžiagos<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio rizikos veiksnio buvimą.'],
		['Q202_9', 'Padidėjusi rizika paslysti, suklupti ar parkristi', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Padidėjusi rizika paslysti, suklupti ar parkristi<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio rizikos veiksnio buvimą.'],
		['Q250', 'Ar Jūsų darbovietėje reguliariai atliekamas su darbo vieta susijusios rizikos vertinimas?', 'Ar Jūsų darbovietėje reguliariai atliekamas su darbo vieta susijusios rizikos vertinimas?<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q251', 'Ar su darbo vieta susijusios rizikos vertinimą daugiausia atlieka darbovietės darbuotojai, ar šios paslaugos perkamos iš išorės paslaugų teikėjų?', 'Ar su darbo vieta susijusios rizikos vertinimą daugiausia atlieka darbovietės darbuotojai, ar šios paslaugos perkamos iš išorės paslaugų teikėjų?<br><br>(1) Daugiausia atlieka darbovietės darbuotojai <br>(2) Daugiausia atlieka išorės paslaugų teikėjai <br>(3) Maždaug vienodai <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q252_1', 'Mašinų, įrangos ir įrenginių sauga', 'Kurie iš toliau išvardintų aspektų nuolat vertinami, atliekant su darbo vieta susijusios rizikos vertinimą? Mašinų, įrangos ir įrenginių sauga<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q252_2', 'Pavojingos cheminės arba biologinės medžiagos', 'Kurie iš toliau išvardintų aspektų nuolat vertinami, atliekant su darbo vieta susijusios rizikos vertinimą? Pavojingos cheminės arba biologinės medžiagos<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q252_3', 'Laikysena darbe, fizinis darbo krūvis ir pasikartojantys judesiai', 'Kurie iš toliau išvardintų aspektų nuolat vertinami, atliekant su darbo vieta susijusios rizikos vertinimą? Laikysena darbe, fizinis darbo krūvis ir pasikartojantys judesiai<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q252_4', 'Triukšmas, vibracija, karštis ar šaltis', 'Kurie iš toliau išvardintų aspektų nuolat vertinami, atliekant su darbo vieta susijusios rizikos vertinimą? Triukšmas, vibracija, karštis ar šaltis<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q252_5', 'Vadovo ir darbuotojo santykiai', 'Kurie iš toliau išvardintų aspektų nuolat vertinami, atliekant su darbo vieta susijusios rizikos vertinimą? Vadovo ir darbuotojo santykiai<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q252_6', 'Organizaciniai aspektai, pavyzdžiui, darbo grafikai, pertraukos ar pamainos', 'Kurie iš toliau išvardintų aspektų nuolat vertinami, atliekant su darbo vieta susijusios rizikos vertinimą? Organizaciniai aspektai, pavyzdžiui, darbo grafikai, pertraukos ar pamainos<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q254gr', 'Kuriais metais paskutinį kartą buvo atliktas su darbo vieta susijusios rizikos vertinimas?', 'Kuriais metais paskutinį kartą buvo atliktas su darbo vieta susijusios rizikos vertinimas?<br><br>(Metai) <br>(9998) Nežino <br>(9999) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q255', 'Ar tai buvo įforminta rašytiniais dokumentais?', 'Ar tai buvo įforminta rašytiniais dokumentais?<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose su darbo vieta susijęs rizikos vertinimas paskutinį kartą buvo atliktas po 1970 m.'],
		['Q256_1', 'Vadovybei', 'Kam buvo pristatytos su darbo vieta susijusios rizikos vertinimo išvados? Vadovybei<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose su darbo vieta susijęs rizikos vertinimas paskutinį kartą buvo atliktas po 1970 m.'],
		['Q256_2', 'Darbuotojų atstovui saugai ir sveikatai', 'Kam buvo pristatytos su darbo vieta susijusios rizikos vertinimo išvados? Darbuotojų atstovui saugai ir sveikatai<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose su darbo vieta susijęs rizikos vertinimas paskutinį kartą buvo atliktas po 1970 m. ir kuriose yra darbuotojų atstovų saugai ir sveikatai.'],
		['Q256_3', 'Darbo tarybai', 'Kam buvo pristatytos su darbo vieta susijusios rizikos vertinimo išvados? Darbo tarybai<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose su darbo vieta susijęs rizikos vertinimas paskutinį kartą buvo atliktas po 1970 m. ir kuriose veikia darbo taryba.'],
		['Q256_4', 'Profesinės sąjungos atstovams', 'Kam buvo pristatytos su darbo vieta susijusios rizikos vertinimo išvados? Profesinės sąjungos atstovams<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose su darbo vieta susijęs rizikos vertinimas paskutinį kartą buvo atliktas po 1970 m. ir kuriose yra profesinės sąjungos atstovų.'],
		['Q256_5', 'Patiems darbuotojams', 'Kam buvo pristatytos su darbo vieta susijusios rizikos vertinimo išvados? Patiems darbuotojams<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose su darbo vieta susijęs rizikos vertinimas paskutinį kartą buvo atliktas po 1970 m.'],
		['Q259', 'Ar rizikos vertinimo procedūra Jūsų darbovietėje laikoma naudinga darbuotojų sveikatos ir saugos valdymo priemone?', 'Ar rizikos vertinimo procedūra Jūsų darbovietėje laikoma naudinga darbuotojų sveikatos ir saugos valdymo priemone?<br><br>(1) Taip <br>(2) Ne <br>(3) Yra prieštaringų nuomonių <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q261_1', 'pavojai ir rizika vis tiek jau žinomi', 'Ar yra kokių nors ypatingų priežasčių, dėl kurių reguliariai neatliekamas su darbo vieta susijusios rizikos vertinimas? Įvertinkite, ar toliau pateikiami teiginiai yra taikytini Jūsų darbovietei? pavojai ir rizika vis tiek jau žinomi<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose nepranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q261_2', 'nėra rimtų problemų', 'Ar yra kokių nors ypatingų priežasčių, dėl kurių reguliariai neatliekamas su darbo vieta susijusios rizikos vertinimas? Įvertinkite, ar toliau pateikiami teiginiai yra taikytini Jūsų darbovietei? nėra rimtų problemų<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose nepranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q261_3', 'ši procedūra pernelyg sudėtinga', 'Ar yra kokių nors ypatingų priežasčių, dėl kurių reguliariai neatliekamas su darbo vieta susijusios rizikos vertinimas? Įvertinkite, ar toliau pateikiami teiginiai yra taikytini Jūsų darbovietei? ši procedūra pernelyg sudėtinga<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose nepranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q261_4', 'trūksta reikiamų žinių', 'Ar yra kokių nors ypatingų priežasčių, dėl kurių reguliariai neatliekamas su darbo vieta susijusios rizikos vertinimas? Įvertinkite, ar toliau pateikiami teiginiai yra taikytini Jūsų darbovietei? trūksta reikiamų žinių<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose nepranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q308_1', 'Įranga, skirta padėti žmonėms kelti ar vežti krovinius arba atlikti kitą sunkų fizinį darbą', 'Dabar pereikime prie raumenų ir kaulų problemų, pavyzdžiui, nugaros, kaklo, rankų, plaštakų ar kojų skausmo. Ar Jūsų darbovietėje taikomos šios prevencinės priemonės? Įranga, skirta padėti žmonėms kelti ar vežti krovinius arba atlikti kitą sunkų fizinį darbą<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose žmonių arba sunkių krovinių kėlimas ar nešimas priskiriamas prie rizikos veiksnių.'],
		['Q308_2', 'Užduočių kaitaliojimas, siekiant sumažinti pasikartojančius judesius ar fizinį krūvį', 'Dabar pereikime prie raumenų ir kaulų problemų, pavyzdžiui, nugaros, kaklo, rankų, plaštakų ar kojų skausmo. Ar Jūsų darbovietėje taikomos šios prevencinės priemonės? Užduočių kaitaliojimas, siekiant sumažinti pasikartojančius judesius ar fizinį krūvį<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pasikartojantys plaštakų arba rankų judesiai priskiriami prie rizikos veiksnių.'],
		['Q308_3', 'Skatinimas daryti reguliarias pertraukas tiems darbuotojams, kurių kūno padėtis būna nepatogi arba statiška, įskaitant ilgą sėdėjimą', 'Dabar pereikime prie raumenų ir kaulų problemų, pavyzdžiui, nugaros, kaklo, rankų, plaštakų ar kojų skausmo. Ar Jūsų darbovietėje taikomos šios prevencinės priemonės? Skatinimas daryti reguliarias pertraukas tiems darbuotojams, kurių kūno padėtis būna nepatogi arba statiška, įskaitant ilgą sėdėjimą<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q308_4', 'Ergonomiškos įrangos, pavyzdžiui, specialių kėdžių ar stalų įsigijimas', 'Dabar pereikime prie raumenų ir kaulų problemų, pavyzdžiui, nugaros, kaklo, rankų, plaštakų ar kojų skausmo. Ar Jūsų darbovietėje taikomos šios prevencinės priemonės? Ergonomiškos įrangos, pavyzdžiui, specialių kėdžių ar stalų įsigijimas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q356_1', 'Tinkamas įrangos ir kito turto naudojimas ir reguliavimas', 'Kuriomis iš toliau išvardintų temų Jūsų darbovietėje organizuojami darbuotojų mokymai? Tinkamas įrangos ir kito turto naudojimas ir reguliavimas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q356_2', 'Pavojingų medžiagų naudojimas', 'Kuriomis iš toliau išvardintų temų Jūsų darbovietėje organizuojami darbuotojų mokymai? Pavojingų medžiagų naudojimas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q356_3', 'Kelio psichosocialinei rizikai, pavyzdžiui, stresui ar patyčioms, užkirtimas', 'Kuriomis iš toliau išvardintų temų Jūsų darbovietėje organizuojami darbuotojų mokymai? Kelio psichosocialinei rizikai, pavyzdžiui, stresui ar patyčioms, užkirtimas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q356_4', 'Sunkių krovinių ar žmonių kėlimas ir nešimas', 'Kuriomis iš toliau išvardintų temų Jūsų darbovietėje organizuojami darbuotojų mokymai? Sunkių krovinių ar žmonių kėlimas ir nešimas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q356_5', 'Skubios pagalbos procedūros', 'Kuriomis iš toliau išvardintų temų Jūsų darbovietėje organizuojami darbuotojų mokymai? Skubios pagalbos procedūros<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q201_1', 'Spaudimas dėl laiko stokos', 'Be šios rizikos dar gali būti sveikatos rizika, susijusi su darbo organizavimu, socialiniais santykiais darbe arba ekonomine padėtimi. Nurodykite, ar šie veiksniai egzistuoja Jūsų darbovietėje. Spaudimas dėl laiko stokos<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q201_2', 'Menkas bendravimas ar bendradarbiavimas organizacijoje', 'Be šios rizikos dar gali būti sveikatos rizika, susijusi su darbo organizavimu, socialiniais santykiais darbe arba ekonomine padėtimi. Nurodykite, ar šie veiksniai egzistuoja Jūsų darbovietėje. Menkas bendravimas ar bendradarbiavimas organizacijoje<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q201_3', 'Nepakankamas darbuotojų gebėjimas daryti įtaką darbo tempui arba procesams', 'Be šios rizikos dar gali būti sveikatos rizika, susijusi su darbo organizavimu, socialiniais santykiais darbe arba ekonomine padėtimi. Nurodykite, ar šie veiksniai egzistuoja Jūsų darbovietėje. Nepakankamas darbuotojų gebėjimas daryti įtaką darbo tempui arba procesams<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q201_4', 'Neužtikrintumas dėl darbo vietos', 'Be šios rizikos dar gali būti sveikatos rizika, susijusi su darbo organizavimu, socialiniais santykiais darbe arba ekonomine padėtimi. Nurodykite, ar šie veiksniai egzistuoja Jūsų darbovietėje. Neužtikrintumas dėl darbo vietos<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q201_5', 'Darbas su sunkiais klientais, pacientais, mokiniais ir pan.', 'Be šios rizikos dar gali būti sveikatos rizika, susijusi su darbo organizavimu, socialiniais santykiais darbe arba ekonomine padėtimi. Nurodykite, ar šie veiksniai egzistuoja Jūsų darbovietėje. Darbas su sunkiais klientais, pacientais, mokiniais ir pan.<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q201_6', 'Ilgos arba nereguliarios darbo valandos', 'Be šios rizikos dar gali būti sveikatos rizika, susijusi su darbo organizavimu, socialiniais santykiais darbe arba ekonomine padėtimi. Nurodykite, ar šie veiksniai egzistuoja Jūsų darbovietėje. Ilgos arba nereguliarios darbo valandos<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q201_7', 'Diskriminacija, pavyzdžiui, dėl lyties, amžiaus ar tautybės', 'Be šios rizikos dar gali būti sveikatos rizika, susijusi su darbo organizavimu, socialiniais santykiais darbe arba ekonomine padėtimi. Nurodykite, ar šie veiksniai egzistuoja Jūsų darbovietėje. Diskriminacija, pavyzdžiui, dėl lyties, amžiaus ar tautybės<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q202_10', 'Spaudimas dėl laiko stokos', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Spaudimas dėl laiko stokos<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio psichosocialinės rizikos veiksnio buvimą.'],
		['Q202_11', 'Menkas bendravimas ar bendradarbiavimas organizacijoje', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Menkas bendravimas ar bendradarbiavimas organizacijoje<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio psichosocialinės rizikos veiksnio buvimą.'],
		['Q202_12', 'Nepakankamas darbuotojų gebėjimas daryti įtaką darbo tempui arba procesams', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Nepakankamas darbuotojų gebėjimas daryti įtaką darbo tempui arba procesams<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio psichosocialinės rizikos veiksnio buvimą.'],
		['Q202_13', 'Neužtikrintumas dėl darbo vietos', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Neužtikrintumas dėl darbo vietos<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio psichosocialinės rizikos veiksnio buvimą.'],
		['Q202_14', 'Darbas su sunkiais klientais, pacientais, mokiniais ir pan..', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Darbas su sunkiais klientais, pacientais, mokiniais ir pan..<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio psichosocialinės rizikos veiksnio buvimą.'],
		['Q202_15', 'Ilgos arba nereguliarios darbo valandos', 'Apie kurias iš šių rizikų jūsų darbovietėje trūksta informacijos ar tinkamų prevencijos priemonių kad problemos būtų sprendžiamos efektyviai? Ilgos arba nereguliarios darbo valandos<br><br>(1) Taip <br>(2) Ne<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie šio psichosocialinės rizikos veiksnio buvimą.'],
		['Q300', 'Ar Jūsų darbovietėje yra numatytas streso darbe prevencijos veiksmų planas?', 'Ar Jūsų darbovietėje yra numatytas streso darbe prevencijos veiksmų planas?<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose dirba 20 ar daugiau darbuotojų.'],
		['Q301', 'Ar darbovietėje yra numatyta procedūra galimiems patyčių ar priekabiavimo atvejams spręsti?', 'Ar darbovietėje yra numatyta procedūra galimiems patyčių ar priekabiavimo atvejams spręsti?<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose dirba 20 ar daugiau darbuotojų.'],
		['Q302', 'Ar yra numatyta procedūra galimiems grasinimo, užgauliojimo ar smurto iš klientų, pacientų, mokinių ar kitų išorės asmenų atvejams spręsti?', 'Ar yra numatyta procedūra galimiems grasinimo, užgauliojimo ar smurto iš klientų, pacientų, mokinių ar kitų išorės asmenų atvejams spręsti?<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose dirba 20 ar daugiau darbuotojų, o jų darbas su sunkiais klientais, pacientais, mokiniais ir pan. priskiriamas prie rizikos veiksnių.'],
		['Q303_1', 'Darbo pertvarkymas, siekiant sumažinti darbo keliamus iššūkius ir įtampą darbe', 'Ar per pastaruosius 3 metus Jūsų darbovietėje buvo naudojama kuri nors iš toliau išvardintų priemonių, skirtų keliui psichosocialinei rizikai užkirsti? Darbo pertvarkymas, siekiant sumažinti darbo keliamus iššūkius ir įtampą darbe<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q303_2', 'Konfidencialus darbuotojų konsultavimas', 'Ar per pastaruosius 3 metus Jūsų darbovietėje buvo naudojama kuri nors iš toliau išvardintų priemonių, skirtų keliui psichosocialinei rizikai užkirsti? Konfidencialus darbuotojų konsultavimas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q303_3', 'Konfliktų sprendimo procedūros sudarymas', 'Ar per pastaruosius 3 metus Jūsų darbovietėje buvo naudojama kuri nors iš toliau išvardintų priemonių, skirtų keliui psichosocialinei rizikai užkirsti? Konfliktų sprendimo procedūros sudarymas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q303_4', 'Įsikišimas, jeigu dirbama pernelyg ilgai ar darbo valandos nepastovios', 'Ar per pastaruosius 3 metus Jūsų darbovietėje buvo naudojama kuri nors iš toliau išvardintų priemonių, skirtų keliui psichosocialinei rizikai užkirsti? Įsikišimas, jeigu dirbama pernelyg ilgai ar darbo valandos nepastovios<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q307', 'Ar darbovietėje yra pakankamai informacijos apie tai, kaip psichosocialinę riziką įtraukti į rizikos vertinimą?', 'Ar darbovietėje yra pakankamai informacijos apie tai, kaip psichosocialinę riziką įtraukti į rizikos vertinimą?<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė'],
		['Q264_1', 'Teisinių įsipareigojimų įvykdymas', 'Kiek svarbios Jūsų darbovietėje yra toliau nurodytos priežastys sprendžiant sveikatos ir saugos klausimus? Įvertinti, ar ši priežastis yra labai svarbi, nelabai svarbi, ar visiškai nesvarbi. Teisinių įsipareigojimų įvykdymas<br><br>(1) Labai svarbi priežastis <br>(2) Nelabai svarbi priežastis <br>(3) Visiškai nesvarbi priežastis <br>(9) Neatsakė'],
		['Q264_2', 'Darbuotojų ar jų atstovų lūkesčių pateisinimas', 'Kiek svarbios Jūsų darbovietėje yra toliau nurodytos priežastys sprendžiant sveikatos ir saugos klausimus? Įvertinti, ar ši priežastis yra labai svarbi, nelabai svarbi, ar visiškai nesvarbi. Darbuotojų ar jų atstovų lūkesčių pateisinimas<br><br>(1) Labai svarbi priežastis <br>(2) Nelabai svarbi priežastis <br>(3) Visiškai nesvarbi priežastis <br>(9) Neatsakė'],
		['Q264_4', 'Darbo našumo išlaikymas ar didinimas', 'Kiek svarbios Jūsų darbovietėje yra toliau nurodytos priežastys sprendžiant sveikatos ir saugos klausimus? Įvertinti, ar ši priežastis yra labai svarbi, nelabai svarbi, ar visiškai nesvarbi. Darbo našumo išlaikymas ar didinimas<br><br>(1) Labai svarbi priežastis <br>(2) Nelabai svarbi priežastis <br>(3) Visiškai nesvarbi priežastis <br>(9) Neatsakė'],
		['Q264_5', 'Organizacijos reputacijos išsaugojimas', 'Kiek svarbios Jūsų darbovietėje yra toliau nurodytos priežastys sprendžiant sveikatos ir saugos klausimus? Įvertinti, ar ši priežastis yra labai svarbi, nelabai svarbi, ar visiškai nesvarbi. Organizacijos reputacijos išsaugojimas<br><br>(1) Labai svarbi priežastis <br>(2) Nelabai svarbi priežastis <br>(3) Visiškai nesvarbi priežastis <br>(9) Neatsakė'],
		['Q264_6', 'Darbo inspekcijos baudų ir sankcijų išvengimas', 'Kiek svarbios Jūsų darbovietėje yra toliau nurodytos priežastys sprendžiant sveikatos ir saugos klausimus? Įvertinti, ar ši priežastis yra labai svarbi, nelabai svarbi, ar visiškai nesvarbi. Darbo inspekcijos baudų ir sankcijų išvengimas<br><br>(1) Labai svarbi priežastis <br>(2) Nelabai svarbi priežastis <br>(3) Visiškai nesvarbi priežastis <br>(9) Neatsakė'],
		['Q265_1', 'Laiko ar darbuotojų trūkumas', 'Kokios didžiausios problemos Jūsų darbovietėje kyla sprendžiant darbuotojų sveikatos ir saugos klausimus? Įvertinkite, ar tai didelė problema, nedidelė problema, ar visai ne problema. Laiko ar darbuotojų trūkumas<br><br>(1) Didelė problema <br>(2) Nedidelė problema <br>(3) Visai ne problema <br>(9) Neatsakė'],
		['Q265_2', 'Pinigų trūkumas', 'Kokios didžiausios problemos Jūsų darbovietėje kyla sprendžiant darbuotojų sveikatos ir saugos klausimus? Įvertinkite, ar tai didelė problema, nedidelė problema, ar visai ne problema. Pinigų trūkumas<br><br>(1) Didelė problema <br>(2) Nedidelė problema <br>(3) Visai ne problema <br>(9) Neatsakė'],
		['Q265_3', 'Nepakankamas darbuotojų informuotumas', 'Kokios didžiausios problemos Jūsų darbovietėje kyla sprendžiant darbuotojų sveikatos ir saugos klausimus? Įvertinkite, ar tai didelė problema, nedidelė problema, ar visai ne problema. Nepakankamas darbuotojų informuotumas<br><br>(1) Didelė problema <br>(2) Nedidelė problema <br>(3) Visai ne problema <br>(9) Neatsakė'],
		['Q265_4', 'Nepakankamas vadovybės informuotumas', 'Kokios didžiausios problemos Jūsų darbovietėje kyla sprendžiant darbuotojų sveikatos ir saugos klausimus? Įvertinkite, ar tai didelė problema, nedidelė problema, ar visai ne problema. Nepakankamas vadovybės informuotumas<br><br>(1) Didelė problema <br>(2) Nedidelė problema <br>(3) Visai ne problema <br>(9) Neatsakė'],
		['Q265_5', 'Kompetencijos ar specialistų paramos stoka', 'Kokios didžiausios problemos Jūsų darbovietėje kyla sprendžiant darbuotojų sveikatos ir saugos klausimus? Įvertinkite, ar tai didelė problema, nedidelė problema, ar visai ne problema. Kompetencijos ar specialistų paramos stoka<br><br>(1) Didelė problema <br>(2) Nedidelė problema <br>(3) Visai ne problema <br>(9) Neatsakė'],
		['Q265_6', 'Dokumentų tvarkymas', 'Kokios didžiausios problemos Jūsų darbovietėje kyla sprendžiant darbuotojų sveikatos ir saugos klausimus? Įvertinkite, ar tai didelė problema, nedidelė problema, ar visai ne problema. Dokumentų tvarkymas<br><br>(1) Didelė problema <br>(2) Nedidelė problema <br>(3) Visai ne problema <br>(9) Neatsakė'],
		['Q265_7', 'Teisinių įsipareigojimų sudėtingumas', 'Kokios didžiausios problemos Jūsų darbovietėje kyla sprendžiant darbuotojų sveikatos ir saugos klausimus? Įvertinkite, ar tai didelė problema, nedidelė problema, ar visai ne problema. Teisinių įsipareigojimų sudėtingumas<br><br>(1) Didelė problema <br>(2) Nedidelė problema <br>(3) Visai ne problema <br>(9) Neatsakė'],
		['Q304', 'Ar konkrečios problemos, susijusios su stresu, patyčiomis, priekabiavimu ar smurtu lėmė tai, kad buvo imtasi priemonių?', 'Ar konkrečios problemos, susijusios su stresu, patyčiomis, priekabiavimu ar smurtu lėmė tai, kad buvo imtasi priemonių?<br><br>(1) Taip <br>(2) Ne <br>(8) Iš dalies <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie kokios nors psichosocialinės rizikos mažinimo priemonės taikymą per pastaruosius 3 metus.'],
		['Q306a_3', 'Nepakankamas darbuotojų informuotumas', 'Ar atsižvelgiant į padėtį Jūsų darbovietėje, dėl kurių nors iš toliau išvardintų veiksnių tampa sunkiau kovoti su psichosocialine rizika nei kitokia sveikatos rizika? Nepakankamas darbuotojų informuotumas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie vieno iš išvardytų psichosocialinės rizikos veiksnių buvimą.'],
		['Q306a_4', 'Nepakankamas vadovybės informuotumas', 'Ar atsižvelgiant į padėtį Jūsų darbovietėje, dėl kurių nors iš toliau išvardintų veiksnių tampa sunkiau kovoti su psichosocialine rizika nei kitokia sveikatos rizika? Nepakankamas vadovybės informuotumas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie vieno iš išvardytų psichosocialinės rizikos veiksnių buvimą.'],
		['Q306a_5', 'Kompetencijos ar specialistų paramos stoka', 'Ar atsižvelgiant į padėtį Jūsų darbovietėje, dėl kurių nors iš toliau išvardintų veiksnių tampa sunkiau kovoti su psichosocialine rizika nei kitokia sveikatos rizika? Kompetencijos ar specialistų paramos stoka<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie vieno iš išvardytų psichosocialinės rizikos veiksnių buvimą.'],
		['Q306a_6', 'Nenoras atvirai kalbėti apie šias problemas', 'Ar atsižvelgiant į padėtį Jūsų darbovietėje, dėl kurių nors iš toliau išvardintų veiksnių tampa sunkiau kovoti su psichosocialine rizika nei kitokia sveikatos rizika? Nenoras atvirai kalbėti apie šias problemas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie vieno iš išvardytų psichosocialinės rizikos veiksnių buvimą.'],
		['Q166_1', 'Darbo taryba', 'Kurios iš toliau išvardintų atstovavimo darbuotojams formų veikia Jūsų darbovietėje? Darbo taryba<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Visiems užduodamas klausimas; dydis priklauso nuo šioms įstaigoms taikomų nacionalinių ribų.'],
		['Q166_2', 'Profesinės sąjungos atstovas', 'Kurios iš toliau išvardintų atstovavimo darbuotojams formų veikia Jūsų darbovietėje? Profesinės sąjungos atstovas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Visiems užduodamas klausimas; dydis priklauso nuo šioms įstaigoms taikomų nacionalinių ribų.'],
		['Q166_3', 'Darbuotojų atstovas saugai ir sveikatai', 'Kurios iš toliau išvardintų atstovavimo darbuotojams formų veikia Jūsų darbovietėje? Darbuotojų atstovas saugai ir sveikatai<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Visiems užduodamas klausimas; dydis priklauso nuo šioms įstaigoms taikomų nacionalinių ribų.'],
		['Q166_4', 'Darbuotojų sveikatos ir saugos komitetas', 'Kurios iš toliau išvardintų atstovavimo darbuotojams formų veikia Jūsų darbovietėje? Darbuotojų sveikatos ir saugos komitetas<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Visiems užduodamas klausimas; dydis priklauso nuo šioms įstaigoms taikomų nacionalinių ribų.'],
		['Q258b', 'Jei atlikus rizikos vertinimą nustatoma, kad reikia imtis priemonių, ar darbuotojai paprastai dalyvauja jas kuriant ir pritaikant?', 'Jei atlikus rizikos vertinimą nustatoma, kad reikia imtis priemonių, ar darbuotojai paprastai dalyvauja jas kuriant ir pritaikant?<br><br>(1) Taip <br>(2) Ne <br>(4) Tai priklauso nuo priemonių rūšies <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie reguliariai atliekamą rizikos vertinimą.'],
		['Q305', 'Ar darbuotojai dalyvavo kuriant ir priimant psichosocialinės rizikos mažinimo priemones?', 'Ar darbuotojai dalyvavo kuriant ir priimant psichosocialinės rizikos mažinimo priemones?<br><br>(1) Taip <br>(2) Ne <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie kokios nors psichosocialinės rizikos mažinimo priemonės taikymą per pastaruosius 3 metus.'],
		['Q350', 'Kaip dažnai darbuotojų atstovai ir vadovybė aptaria darbuotojų sveikatos ir saugos klausimus? Ar tokios diskusijos vyksta reguliariai, ar tik iškilus konkrečių darbuotojų sveikatos ir saugos problemų, ar visai nevyksta?', 'Kaip dažnai darbuotojų atstovai ir vadovybė aptaria darbuotojų sveikatos ir saugos klausimus? Ar tokios diskusijos vyksta reguliariai, ar tik iškilus konkrečių darbuotojų sveikatos ir saugos problemų, ar visai nevyksta?<br><br>(1) Reguliariai <br>(2) Tik iškilus konkrečių problemų <br>(3) Nevyksta visai <br>(7) Netaikoma (nėra darbuotojų atstovų) <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose pranešama apie tam tikras atstovavimo darbuotojams formas.'],
		['Q351', 'Kaip dažnai kyla su darbuotojų sveikata ir sauga susijusių ginčų? Dažnai, kartais ar beveik niekada?', 'Kaip dažnai kyla su darbuotojų sveikata ir sauga susijusių ginčų? Dažnai, kartais ar beveik niekada?<br><br>(1) Dažnai <br>(2) Kartais <br>(3) Beveik niekada <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose darbuotojų atstovai ir vadovybė aptaria darbuotojų saugos ir sveikatos klausimus'],
		['Q354', 'Ar darbuotojų atstovams sveikatai ir saugai darbo metu organizuojami mokymai, kurie galėtų padėti jiems geriau atlikti su darbuotojų sveikata ir sauga susijusias pareigas?', 'Ar darbuotojų atstovams sveikatai ir saugai darbo metu organizuojami mokymai, kurie galėtų padėti jiems geriau atlikti su darbuotojų sveikata ir sauga susijusias pareigas?<br><br>(1) Taip <br>(2) Ne <br>(3) Taip, bet tik kai kuriems iš jų <br>(9) Neatsakė<br><br>Klausimas užduodamas įmonėse, kuriose yra darbuotojų atstovų saugai ir sveikatai.'],
		['Q358', 'Ar darbuotojų sveikatos ir saugos klausimai reguliariai aptariami darbuotojų ar komandos susirinkimuose?', 'Ar darbuotojų sveikatos ir saugos klausimai reguliariai aptariami darbuotojų ar komandos susirinkimuose?<br><br>(1) Taip <br>(2) Ne <br>(3) Tik kai kuriuose skyriuose <br>(9) Neatsakė']
	];
