//Auto Generated file
var subset_
	 = [
	
		['Size', 'Organisasjonsstørrelse'],
		['Sectorgrp', 'Sektor']
	];
var subset_subsetValue
	 = [
	
		['Sectorgrp', 'All', 'Alle'],
		['Sectorgrp', '1--A', 'Landbruk, skogbruk og fiskeri'],
		['Sectorgrp', '2--BDEF', 'Bygg og anlegg, avfallshåndtering og vann- og strømforsyning'],
		['Sectorgrp', '3--C', 'Produksjonsindustri'],
		['Sectorgrp', '4--GHIR', 'Varehandel, transport, overnattings- og serveringsvirksomhet og kultur- og fritidsrelaterte virksomheter'],
		['Sectorgrp', '5--JKLMNS', 'IT, finans, fast eiendom, annet teknisk eller vitenskapelig arbeid og personlige tjenester'],
		['Sectorgrp', '6--O', 'Offentlig administrasjon'],
		['Sectorgrp', '7--PQ', 'Utdanning og helse- og sosialtjenester'],
		['Size', 'All', 'Alle'],
		['Size', '1--5-to-9', '5-9 ansatte'],
		['Size', '2--10-to-49', '10-49 ansatte'],
		['Size', '3--50-249', '50-249 ansatte'],
		['Size', '4--250-', '250 eller flere ansatte']
	];
var topic_
	 = [
	
		['', 'Alle (108)'],
		['Arbeidstakermedvirkning', 'Arbeidstakermedvirkning (10)'],
		['HMS-styring', 'HMS-styring (60)'],
		['Psykososiale risikoer og håndtering av disse', 'Psykososiale risikoer og håndtering av disse (21)'],
		['Pådrivere og hindringer', 'Pådrivere og hindringer (17)'],
		['Viktige funn', 'Viktige funn (24)']
	];
var topic_question
	 = [
	
		['Viktige funn', 'Q200_1', 'Risikofaktorer som er til stede i organisasjonen: Anstrengende eller smertefulle stillinger'],
		['Viktige funn', 'Q200_2', 'Risikofaktorer som er til stede i organisasjonen: Løfting og flytting av personer eller tung last'],
		['Viktige funn', 'Q200_3', 'Risikofaktorer som er til stede i organisasjonen: Støy'],
		['Viktige funn', 'Q200_4', 'Risikofaktorer som er til stede i organisasjonen: Gjentatte hånd- eller armbevegelser'],
		['Viktige funn', 'Q200_5', 'Risikofaktorer som er til stede i organisasjonen: Varme, kulde eller trekk'],
		['Viktige funn', 'Q200_6', 'Risikofaktorer som er til stede i organisasjonen: Fare for ulykker med maskiner'],
		['Viktige funn', 'Q200_7', 'Risikofaktorer som er til stede i organisasjonen: Fare for ulykker med kjøretøy i arbeidstiden'],
		['Viktige funn', 'Q200_8', 'Risikofaktorer som er til stede i organisasjonen: Kjemiske eller biologiske stoffer'],
		['Viktige funn', 'Q200_9', 'Risikofaktorer som er til stede i organisasjonen: Økt risiko for å skli, snuble og falle'],
		['Viktige funn', 'Q201_1', 'Risikofaktorer som er til stede i organisasjonen: Tidspress'],
		['Viktige funn', 'Q201_2', 'Risikofaktorer som er til stede i organisasjonen: Dårlig kommunikasjon eller samarbeid'],
		['Viktige funn', 'Q201_3', 'Risikofaktorer som er til stede i organisasjonen: Arbeidstakerne mangler innflytelse'],
		['Viktige funn', 'Q201_4', 'Risikofaktorer som er til stede i organisasjonen: Frykt for å miste jobben'],
		['Viktige funn', 'Q201_5', 'Risikofaktorer som er til stede i organisasjonen: Vanskelige kunder, pasienter, elever'],
		['Viktige funn', 'Q201_6', 'Risikofaktorer som er til stede i organisasjonen: Lange arbeidsdager eller uregelmessig arbeidstid'],
		['Viktige funn', 'Q201_7', 'Risikofaktorer som er til stede i organisasjonen: Diskriminering'],
		['Viktige funn', 'Q250', 'Risikovurderinger på arbeidsplassen'],
		['Viktige funn', 'Q251', 'Risikovurderinger utføres hovedsakelig av internt personale eller blir satt bort til eksterne tjenesteleverandører'],
		['Viktige funn', 'Q264_1', 'Grunner for å sette fokus på HMS på arbeidsplassen: Overholde lovpålagte krav'],
		['Viktige funn', 'Q264_2', 'Grunner for å sette fokus på HMS på arbeidsplassen: Imøtekomme forventninger fra arbeidstakerne'],
		['Viktige funn', 'Q264_4', 'Grunner for å sette fokus på HMS på arbeidsplassen: Øke produktiviteten'],
		['Viktige funn', 'Q264_5', 'Grunner for å sette fokus på HMS på arbeidsplassen: Organisasjonens omdømme'],
		['Viktige funn', 'Q264_6', 'Grunner for å sette fokus på HMS på arbeidsplassen: Unngå bøter og sanksjoner fra Arbeidstilsynet'],
		['Viktige funn', 'Q307', 'Tilstrekkelig informasjon om hvordan psykososiale risikoer kan inkluderes i risikovurderinger'],
		['HMS-styring', 'Q150_1', 'Bruk av HMS-tjenester: En bedriftslege'],
		['HMS-styring', 'Q150_2', 'Bruk av HMS-tjenester: En psykolog'],
		['HMS-styring', 'Q150_3', 'Bruk av HMS-tjenester: En ekspert som arbeider med ergonomisk utforming av arbeidsplasser'],
		['HMS-styring', 'Q150_4', 'Bruk av HMS-tjenester: En generalist innen HMS'],
		['HMS-styring', 'Q150_5', 'Bruk av HMS-tjenester: En ekspert på ulykkesforebygging'],
		['HMS-styring', 'Q155', 'Dokument som forklarer ansvar og prosedyrer i forbindelse med HMS, er tilgjengelig for alle på arbeidsplassen'],
		['HMS-styring', 'Q156', 'Et bestemt budsjett for HMS-tiltak og -utstyr på arbeidsplassen fastsettes hvert år'],
		['HMS-styring', 'Q158_1', 'Tiltak for å fremme arbeidstakernes helse: Bevisstgjøring om sunn ernæring '],
		['HMS-styring', 'Q158_2', 'Tiltak for å fremme arbeidstakernes helse: Bevisstgjøring om forebygging av avhengighet'],
		['HMS-styring', 'Q158_3', 'Tiltak for å fremme arbeidstakernes helse: Tilbud om sportsaktiviteter utenom arbeidstiden'],
		['HMS-styring', 'Q158_4', 'Tiltak for å fremme arbeidstakernes helse: Oppmuntring til å utføre fysiske øvelser på jobb'],
		['HMS-styring', 'Q160', 'Rutinemessig analyse av sykefravær'],
		['HMS-styring', 'Q165', 'Besøk av Arbeidstilsynet i løpet av de tre siste årene for å kontrollere HMS-forholdene'],
		['HMS-styring', 'Q200_1', 'Risikofaktorer som er til stede i organisasjonen: Anstrengende eller smertefulle stillinger'],
		['HMS-styring', 'Q200_2', 'Risikofaktorer som er til stede i organisasjonen: Løfting og flytting av personer eller tung last'],
		['HMS-styring', 'Q200_3', 'Risikofaktorer som er til stede i organisasjonen: Støy'],
		['HMS-styring', 'Q200_4', 'Risikofaktorer som er til stede i organisasjonen: Gjentatte hånd- eller armbevegelser'],
		['HMS-styring', 'Q200_5', 'Risikofaktorer som er til stede i organisasjonen: Varme, kulde eller trekk'],
		['HMS-styring', 'Q200_6', 'Risikofaktorer som er til stede i organisasjonen: Fare for ulykker med maskiner'],
		['HMS-styring', 'Q200_7', 'Risikofaktorer som er til stede i organisasjonen: Fare for ulykker med kjøretøy i arbeidstiden'],
		['HMS-styring', 'Q200_8', 'Risikofaktorer som er til stede i organisasjonen: Kjemiske eller biologiske stoffer'],
		['HMS-styring', 'Q200_9', 'Risikofaktorer som er til stede i organisasjonen: Økt risiko for å skli, snuble og falle'],
		['HMS-styring', 'Q202_1', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Anstrengende eller smertefulle stillinger'],
		['HMS-styring', 'Q202_2', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Løfting og flytting av personer eller tung last'],
		['HMS-styring', 'Q202_3', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Støy'],
		['HMS-styring', 'Q202_4', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Gjentatte hånd- eller armbevegelser'],
		['HMS-styring', 'Q202_5', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Varme, kulde eller trekk'],
		['HMS-styring', 'Q202_6', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Fare for ulykker med maskiner'],
		['HMS-styring', 'Q202_7', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Fare for ulykker med kjøretøy i arbeidstiden'],
		['HMS-styring', 'Q202_8', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Kjemiske eller biologiske stoffer'],
		['HMS-styring', 'Q202_9', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Økt risiko for å skli, snuble og falle'],
		['HMS-styring', 'Q250', 'Risikovurderinger på arbeidsplassen'],
		['HMS-styring', 'Q251', 'Risikovurderinger utføres hovedsakelig av internt personale eller blir satt bort til eksterne tjenesteleverandører'],
		['HMS-styring', 'Q252_1', 'Forhold som blir rutinemessig evaluert i risikovurderingene på arbeidsplassen: Sikkerheten til maskiner, utstyr og installasjoner'],
		['HMS-styring', 'Q252_2', 'Forhold som blir rutinemessig evaluert i risikovurderingene på arbeidsplassen: Farlige stoffer'],
		['HMS-styring', 'Q252_3', 'Forhold som blir rutinemessig evaluert i risikovurderingene på arbeidsplassen: Arbeidsstillinger, fysiske arbeidskrav og repetitive bevegelser'],
		['HMS-styring', 'Q252_4', 'Forhold som blir rutinemessig evaluert i risikovurderingene på arbeidsplassen: Eksponering for støy, vibrasjoner, varme eller kulde'],
		['HMS-styring', 'Q252_5', 'Forhold som blir rutinemessig evaluert i risikovurderingene på arbeidsplassen: Forholdet mellom arbeidstaker og overordnet'],
		['HMS-styring', 'Q252_6', 'Forhold som blir rutinemessig evaluert i risikovurderingene på arbeidsplassen: Organisatoriske aspekter'],
		['HMS-styring', 'Q254gr', 'År for siste risikovurdering på arbeidsplassen'],
		['HMS-styring', 'Q255', 'Dokumentert risikovurdering på arbeidsplassen'],
		['HMS-styring', 'Q256_1', 'Hvem som har fått resultatene fra risikovurderingene på arbeidsplassen: Ledelsen'],
		['HMS-styring', 'Q256_2', 'Hvem som har fått resultatene fra risikovurderingene på arbeidsplassen: Verneombudene'],
		['HMS-styring', 'Q256_3', 'Hvem som har fått resultatene fra risikovurderingene på arbeidsplassen: Bedriftsutvalget'],
		['HMS-styring', 'Q256_4', 'Hvem som har fått resultatene fra risikovurderingene på arbeidsplassen: Tillitsvalgte'],
		['HMS-styring', 'Q256_5', 'Hvem som har fått resultatene fra risikovurderingene på arbeidsplassen: Arbeidstakerne selv'],
		['HMS-styring', 'Q259', 'Risikovurderinger blir ansett som en nyttig prosedyre for å håndtere HMS på arbeidsplassen'],
		['HMS-styring', 'Q261_1', 'Grunner til at det ikke jevnlig blir utført risikovurderinger på arbeidsplassen: Farene og risikoene er allerede kjent'],
		['HMS-styring', 'Q261_2', 'Grunner til at det ikke jevnlig blir utført risikovurderinger på arbeidsplassen: Det finnes ikke problemer av betydning'],
		['HMS-styring', 'Q261_3', 'Grunner til at det ikke jevnlig blir utført risikovurderinger på arbeidsplassen: Prosedyren er for belastende'],
		['HMS-styring', 'Q261_4', 'Grunner til at det ikke jevnlig blir utført risikovurderinger på arbeidsplassen: Den nødvendige ekspertisen mangler'],
		['HMS-styring', 'Q308_1', 'Forebyggende tiltak mot muskel- og skjelettlidelser: Utstyr for hjelp til løfting eller flytting av last'],
		['HMS-styring', 'Q308_2', 'Forebyggende tiltak mot muskel- og skjelettlidelser: Rotering av arbeidsoppgaver for å redusere fysisk belastning'],
		['HMS-styring', 'Q308_3', 'Forebyggende tiltak mot muskel- og skjelettlidelser: Oppfordring til å ta jevnlige pauser når arbeidsstillingene er ubehagelige og statiske'],
		['HMS-styring', 'Q308_4', 'Forebyggende tiltak mot muskel- og skjelettlidelser: Anskaffelse av ergonomisk utstyr'],
		['HMS-styring', 'Q356_1', 'Opplæring på arbeidsplassen: Riktig bruk og regulering av arbeidsutstyr og møbler'],
		['HMS-styring', 'Q356_2', 'Opplæring på arbeidsplassen: Bruk av farlige stoffer'],
		['HMS-styring', 'Q356_3', 'Opplæring på arbeidsplassen: Hvordan forebygge psykososiale risikoer'],
		['HMS-styring', 'Q356_4', 'Opplæring på arbeidsplassen: Hvordan løfte tung last eller personer'],
		['HMS-styring', 'Q356_5', 'Opplæring på arbeidsplassen: Nødprosedyrer'],
		['Psykososiale risikoer og håndtering av disse', 'Q201_1', 'Risikofaktorer som er til stede i organisasjonen: Tidspress'],
		['Psykososiale risikoer og håndtering av disse', 'Q201_2', 'Risikofaktorer som er til stede i organisasjonen: Dårlig kommunikasjon eller samarbeid'],
		['Psykososiale risikoer og håndtering av disse', 'Q201_3', 'Risikofaktorer som er til stede i organisasjonen: Arbeidstakerne mangler innflytelse'],
		['Psykososiale risikoer og håndtering av disse', 'Q201_4', 'Risikofaktorer som er til stede i organisasjonen: Frykt for å miste jobben'],
		['Psykososiale risikoer og håndtering av disse', 'Q201_5', 'Risikofaktorer som er til stede i organisasjonen: Vanskelige kunder, pasienter, elever'],
		['Psykososiale risikoer og håndtering av disse', 'Q201_6', 'Risikofaktorer som er til stede i organisasjonen: Lange arbeidsdager eller uregelmessig arbeidstid'],
		['Psykososiale risikoer og håndtering av disse', 'Q201_7', 'Risikofaktorer som er til stede i organisasjonen: Diskriminering'],
		['Psykososiale risikoer og håndtering av disse', 'Q202_10', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Tidspress'],
		['Psykososiale risikoer og håndtering av disse', 'Q202_11', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Dårlig kommunikasjon eller samarbeid'],
		['Psykososiale risikoer og håndtering av disse', 'Q202_12', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Arbeidstakerne mangler innflytelse'],
		['Psykososiale risikoer og håndtering av disse', 'Q202_13', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Frykt for å miste jobben'],
		['Psykososiale risikoer og håndtering av disse', 'Q202_14', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Vanskelige kunder, pasienter, elever'],
		['Psykososiale risikoer og håndtering av disse', 'Q202_15', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Lange arbeidsdager eller uregelmessig arbeidstid'],
		['Psykososiale risikoer og håndtering av disse', 'Q300', 'Handlingsplan for å forebygge arbeidsrelatert stress'],
		['Psykososiale risikoer og håndtering av disse', 'Q301', 'Har på plass prosedyrer for å håndtere tilfeller av mobbing eller trakassering'],
		['Psykososiale risikoer og håndtering av disse', 'Q302', 'Har på plass prosedyrer for å håndtere tilfeller av trusler, sjikane eller angrep'],
		['Psykososiale risikoer og håndtering av disse', 'Q303_1', 'Tiltak for å forebygge psykososiale risikoer i løpet av de siste tre årene: Omorganisering av arbeidet for å redusere høye krav og arbeidspress'],
		['Psykososiale risikoer og håndtering av disse', 'Q303_2', 'Tiltak for å forebygge psykososiale risikoer i løpet av de siste tre årene: Konfidensiell rådgiving for arbeidstakere'],
		['Psykososiale risikoer og håndtering av disse', 'Q303_3', 'Tiltak for å forebygge psykososiale risikoer i løpet av de siste tre årene: Utarbeidelse av en prosedyre for konfliktløsning'],
		['Psykososiale risikoer og håndtering av disse', 'Q303_4', 'Tiltak for å forebygge psykososiale risikoer i løpet av de siste tre årene: Inngripen hvis for lange eller uregelmessige arbeidstider følges'],
		['Psykososiale risikoer og håndtering av disse', 'Q307', 'Tilstrekkelig informasjon om hvordan psykososiale risikoer kan inkluderes i risikovurderinger'],
		['Pådrivere og hindringer', 'Q264_1', 'Grunner for å sette fokus på HMS på arbeidsplassen: Overholde lovpålagte krav'],
		['Pådrivere og hindringer', 'Q264_2', 'Grunner for å sette fokus på HMS på arbeidsplassen: Imøtekomme forventninger fra arbeidstakerne'],
		['Pådrivere og hindringer', 'Q264_4', 'Grunner for å sette fokus på HMS på arbeidsplassen: Øke produktiviteten'],
		['Pådrivere og hindringer', 'Q264_5', 'Grunner for å sette fokus på HMS på arbeidsplassen: Organisasjonens omdømme'],
		['Pådrivere og hindringer', 'Q264_6', 'Grunner for å sette fokus på HMS på arbeidsplassen: Unngå bøter og sanksjoner fra Arbeidstilsynet'],
		['Pådrivere og hindringer', 'Q265_1', 'Viktigste årsaker til at det er vanskelig å ta opp HMS: Mangel på tid eller personale'],
		['Pådrivere og hindringer', 'Q265_2', 'Viktigste årsaker til at det er vanskelig å ta opp HMS: Mangel på penger'],
		['Pådrivere og hindringer', 'Q265_3', 'Viktigste årsaker til at det er vanskelig å ta opp HMS: Manglende kunnskap om HMS blant personalet'],
		['Pådrivere og hindringer', 'Q265_4', 'Viktigste årsaker til at det er vanskelig å ta opp HMS: Manglende kunnskap om HMS i ledelsen'],
		['Pådrivere og hindringer', 'Q265_5', 'Viktigste årsaker til at det er vanskelig å ta opp HMS: Manglende kompetanse eller spesialisthjelp'],
		['Pådrivere og hindringer', 'Q265_6', 'Viktigste årsaker til at det er vanskelig å ta opp HMS: Papirarbeid'],
		['Pådrivere og hindringer', 'Q265_7', 'Viktigste årsaker til at det er vanskelig å ta opp HMS: De lovbestemte pliktene er for omfattende'],
		['Pådrivere og hindringer', 'Q304', 'Tiltak iverksatt på grunn av konkrete problemer'],
		['Pådrivere og hindringer', 'Q306a_3', 'Hindringer for håndtering av psykososiale risikoer: Manglende kunnskap om HMS blant personalet'],
		['Pådrivere og hindringer', 'Q306a_4', 'Hindringer for håndtering av psykososiale risikoer: Manglende kunnskap om HMS i ledelsen'],
		['Pådrivere og hindringer', 'Q306a_5', 'Hindringer for håndtering av psykososiale risikoer: Manglende kompetanse eller spesialisthjelp'],
		['Pådrivere og hindringer', 'Q306a_6', 'Hindringer for håndtering av psykososiale risikoer: Motvilje mot å snakke åpent om slike problemer'],
		['Arbeidstakermedvirkning', 'Q166_1', 'Typer arbeidstakerrepresentasjon: Bedriftsutvalg'],
		['Arbeidstakermedvirkning', 'Q166_2', 'Typer arbeidstakerrepresentasjon: Tillitsvalgt'],
		['Arbeidstakermedvirkning', 'Q166_3', 'Typer arbeidstakerrepresentasjon: Verneombud'],
		['Arbeidstakermedvirkning', 'Q166_4', 'Typer arbeidstakerrepresentasjon: Arbeidsmiljøutvalg (AMU)'],
		['Arbeidstakermedvirkning', 'Q258b', 'Arbeidstakerne er involvert i utformingen av tiltakene etter en risikovurdering'],
		['Arbeidstakermedvirkning', 'Q305', 'Arbeidstakerne deltar i utformingen av tiltak for å forebygge psykososiale risikoer'],
		['Arbeidstakermedvirkning', 'Q350', 'Hvor ofte HMS diskuteres blant de ansattes tillitsvalgte og ledelsen'],
		['Arbeidstakermedvirkning', 'Q351', 'Hvor ofte det oppstår uenighet i forbindelse med HMS-spørsmål'],
		['Arbeidstakermedvirkning', 'Q354', 'Verneombudene får opplæring i arbeidstiden'],
		['Arbeidstakermedvirkning', 'Q358', 'Diskusjon om HMS-spørsmål på personal- eller teammøter']
	];
var question_
	 = [
	
		['Q200_1', 'Risikofaktorer som er til stede i organisasjonen: Anstrengende eller smertefulle stillinger'],
		['Q200_2', 'Risikofaktorer som er til stede i organisasjonen: Løfting og flytting av personer eller tung last'],
		['Q200_3', 'Risikofaktorer som er til stede i organisasjonen: Støy'],
		['Q200_4', 'Risikofaktorer som er til stede i organisasjonen: Gjentatte hånd- eller armbevegelser'],
		['Q200_5', 'Risikofaktorer som er til stede i organisasjonen: Varme, kulde eller trekk'],
		['Q200_6', 'Risikofaktorer som er til stede i organisasjonen: Fare for ulykker med maskiner'],
		['Q200_7', 'Risikofaktorer som er til stede i organisasjonen: Fare for ulykker med kjøretøy i arbeidstiden'],
		['Q200_8', 'Risikofaktorer som er til stede i organisasjonen: Kjemiske eller biologiske stoffer'],
		['Q200_9', 'Risikofaktorer som er til stede i organisasjonen: Økt risiko for å skli, snuble og falle'],
		['Q201_1', 'Risikofaktorer som er til stede i organisasjonen: Tidspress'],
		['Q201_2', 'Risikofaktorer som er til stede i organisasjonen: Dårlig kommunikasjon eller samarbeid'],
		['Q201_3', 'Risikofaktorer som er til stede i organisasjonen: Arbeidstakerne mangler innflytelse'],
		['Q201_4', 'Risikofaktorer som er til stede i organisasjonen: Frykt for å miste jobben'],
		['Q201_5', 'Risikofaktorer som er til stede i organisasjonen: Vanskelige kunder, pasienter, elever'],
		['Q201_6', 'Risikofaktorer som er til stede i organisasjonen: Lange arbeidsdager eller uregelmessig arbeidstid'],
		['Q201_7', 'Risikofaktorer som er til stede i organisasjonen: Diskriminering'],
		['Q250', 'Risikovurderinger på arbeidsplassen'],
		['Q251', 'Risikovurderinger utføres hovedsakelig av internt personale eller blir satt bort til eksterne tjenesteleverandører'],
		['Q264_1', 'Grunner for å sette fokus på HMS på arbeidsplassen: Overholde lovpålagte krav'],
		['Q264_2', 'Grunner for å sette fokus på HMS på arbeidsplassen: Imøtekomme forventninger fra arbeidstakerne'],
		['Q264_4', 'Grunner for å sette fokus på HMS på arbeidsplassen: Øke produktiviteten'],
		['Q264_5', 'Grunner for å sette fokus på HMS på arbeidsplassen: Organisasjonens omdømme'],
		['Q264_6', 'Grunner for å sette fokus på HMS på arbeidsplassen: Unngå bøter og sanksjoner fra Arbeidstilsynet'],
		['Q307', 'Tilstrekkelig informasjon om hvordan psykososiale risikoer kan inkluderes i risikovurderinger'],
		['Q150_1', 'Bruk av HMS-tjenester: En bedriftslege'],
		['Q150_2', 'Bruk av HMS-tjenester: En psykolog'],
		['Q150_3', 'Bruk av HMS-tjenester: En ekspert som arbeider med ergonomisk utforming av arbeidsplasser'],
		['Q150_4', 'Bruk av HMS-tjenester: En generalist innen HMS'],
		['Q150_5', 'Bruk av HMS-tjenester: En ekspert på ulykkesforebygging'],
		['Q155', 'Dokument som forklarer ansvar og prosedyrer i forbindelse med HMS, er tilgjengelig for alle på arbeidsplassen'],
		['Q156', 'Et bestemt budsjett for HMS-tiltak og -utstyr på arbeidsplassen fastsettes hvert år'],
		['Q158_1', 'Tiltak for å fremme arbeidstakernes helse: Bevisstgjøring om sunn ernæring '],
		['Q158_2', 'Tiltak for å fremme arbeidstakernes helse: Bevisstgjøring om forebygging av avhengighet'],
		['Q158_3', 'Tiltak for å fremme arbeidstakernes helse: Tilbud om sportsaktiviteter utenom arbeidstiden'],
		['Q158_4', 'Tiltak for å fremme arbeidstakernes helse: Oppmuntring til å utføre fysiske øvelser på jobb'],
		['Q160', 'Rutinemessig analyse av sykefravær'],
		['Q165', 'Besøk av Arbeidstilsynet i løpet av de tre siste årene for å kontrollere HMS-forholdene'],
		['Q200_1', 'Risikofaktorer som er til stede i organisasjonen: Anstrengende eller smertefulle stillinger'],
		['Q200_2', 'Risikofaktorer som er til stede i organisasjonen: Løfting og flytting av personer eller tung last'],
		['Q200_3', 'Risikofaktorer som er til stede i organisasjonen: Støy'],
		['Q200_4', 'Risikofaktorer som er til stede i organisasjonen: Gjentatte hånd- eller armbevegelser'],
		['Q200_5', 'Risikofaktorer som er til stede i organisasjonen: Varme, kulde eller trekk'],
		['Q200_6', 'Risikofaktorer som er til stede i organisasjonen: Fare for ulykker med maskiner'],
		['Q200_7', 'Risikofaktorer som er til stede i organisasjonen: Fare for ulykker med kjøretøy i arbeidstiden'],
		['Q200_8', 'Risikofaktorer som er til stede i organisasjonen: Kjemiske eller biologiske stoffer'],
		['Q200_9', 'Risikofaktorer som er til stede i organisasjonen: Økt risiko for å skli, snuble og falle'],
		['Q202_1', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Anstrengende eller smertefulle stillinger'],
		['Q202_2', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Løfting og flytting av personer eller tung last'],
		['Q202_3', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Støy'],
		['Q202_4', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Gjentatte hånd- eller armbevegelser'],
		['Q202_5', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Varme, kulde eller trekk'],
		['Q202_6', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Fare for ulykker med maskiner'],
		['Q202_7', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Fare for ulykker med kjøretøy i arbeidstiden'],
		['Q202_8', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Kjemiske eller biologiske stoffer'],
		['Q202_9', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Økt risiko for å skli, snuble og falle'],
		['Q250', 'Risikovurderinger på arbeidsplassen'],
		['Q251', 'Risikovurderinger utføres hovedsakelig av internt personale eller blir satt bort til eksterne tjenesteleverandører'],
		['Q252_1', 'Forhold som blir rutinemessig evaluert i risikovurderingene på arbeidsplassen: Sikkerheten til maskiner, utstyr og installasjoner'],
		['Q252_2', 'Forhold som blir rutinemessig evaluert i risikovurderingene på arbeidsplassen: Farlige stoffer'],
		['Q252_3', 'Forhold som blir rutinemessig evaluert i risikovurderingene på arbeidsplassen: Arbeidsstillinger, fysiske arbeidskrav og repetitive bevegelser'],
		['Q252_4', 'Forhold som blir rutinemessig evaluert i risikovurderingene på arbeidsplassen: Eksponering for støy, vibrasjoner, varme eller kulde'],
		['Q252_5', 'Forhold som blir rutinemessig evaluert i risikovurderingene på arbeidsplassen: Forholdet mellom arbeidstaker og overordnet'],
		['Q252_6', 'Forhold som blir rutinemessig evaluert i risikovurderingene på arbeidsplassen: Organisatoriske aspekter'],
		['Q254gr', 'År for siste risikovurdering på arbeidsplassen'],
		['Q255', 'Dokumentert risikovurdering på arbeidsplassen'],
		['Q256_1', 'Hvem som har fått resultatene fra risikovurderingene på arbeidsplassen: Ledelsen'],
		['Q256_2', 'Hvem som har fått resultatene fra risikovurderingene på arbeidsplassen: Verneombudene'],
		['Q256_3', 'Hvem som har fått resultatene fra risikovurderingene på arbeidsplassen: Bedriftsutvalget'],
		['Q256_4', 'Hvem som har fått resultatene fra risikovurderingene på arbeidsplassen: Tillitsvalgte'],
		['Q256_5', 'Hvem som har fått resultatene fra risikovurderingene på arbeidsplassen: Arbeidstakerne selv'],
		['Q259', 'Risikovurderinger blir ansett som en nyttig prosedyre for å håndtere HMS på arbeidsplassen'],
		['Q261_1', 'Grunner til at det ikke jevnlig blir utført risikovurderinger på arbeidsplassen: Farene og risikoene er allerede kjent'],
		['Q261_2', 'Grunner til at det ikke jevnlig blir utført risikovurderinger på arbeidsplassen: Det finnes ikke problemer av betydning'],
		['Q261_3', 'Grunner til at det ikke jevnlig blir utført risikovurderinger på arbeidsplassen: Prosedyren er for belastende'],
		['Q261_4', 'Grunner til at det ikke jevnlig blir utført risikovurderinger på arbeidsplassen: Den nødvendige ekspertisen mangler'],
		['Q308_1', 'Forebyggende tiltak mot muskel- og skjelettlidelser: Utstyr for hjelp til løfting eller flytting av last'],
		['Q308_2', 'Forebyggende tiltak mot muskel- og skjelettlidelser: Rotering av arbeidsoppgaver for å redusere fysisk belastning'],
		['Q308_3', 'Forebyggende tiltak mot muskel- og skjelettlidelser: Oppfordring til å ta jevnlige pauser når arbeidsstillingene er ubehagelige og statiske'],
		['Q308_4', 'Forebyggende tiltak mot muskel- og skjelettlidelser: Anskaffelse av ergonomisk utstyr'],
		['Q356_1', 'Opplæring på arbeidsplassen: Riktig bruk og regulering av arbeidsutstyr og møbler'],
		['Q356_2', 'Opplæring på arbeidsplassen: Bruk av farlige stoffer'],
		['Q356_3', 'Opplæring på arbeidsplassen: Hvordan forebygge psykososiale risikoer'],
		['Q356_4', 'Opplæring på arbeidsplassen: Hvordan løfte tung last eller personer'],
		['Q356_5', 'Opplæring på arbeidsplassen: Nødprosedyrer'],
		['Q201_1', 'Risikofaktorer som er til stede i organisasjonen: Tidspress'],
		['Q201_2', 'Risikofaktorer som er til stede i organisasjonen: Dårlig kommunikasjon eller samarbeid'],
		['Q201_3', 'Risikofaktorer som er til stede i organisasjonen: Arbeidstakerne mangler innflytelse'],
		['Q201_4', 'Risikofaktorer som er til stede i organisasjonen: Frykt for å miste jobben'],
		['Q201_5', 'Risikofaktorer som er til stede i organisasjonen: Vanskelige kunder, pasienter, elever'],
		['Q201_6', 'Risikofaktorer som er til stede i organisasjonen: Lange arbeidsdager eller uregelmessig arbeidstid'],
		['Q201_7', 'Risikofaktorer som er til stede i organisasjonen: Diskriminering'],
		['Q202_10', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Tidspress'],
		['Q202_11', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Dårlig kommunikasjon eller samarbeid'],
		['Q202_12', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Arbeidstakerne mangler innflytelse'],
		['Q202_13', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Frykt for å miste jobben'],
		['Q202_14', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Vanskelige kunder, pasienter, elever'],
		['Q202_15', 'Mangel på informasjon eller gode forebyggende verktøy for effektiv håndtering av risiko: Lange arbeidsdager eller uregelmessig arbeidstid'],
		['Q300', 'Handlingsplan for å forebygge arbeidsrelatert stress'],
		['Q301', 'Har på plass prosedyrer for å håndtere tilfeller av mobbing eller trakassering'],
		['Q302', 'Har på plass prosedyrer for å håndtere tilfeller av trusler, sjikane eller angrep'],
		['Q303_1', 'Tiltak for å forebygge psykososiale risikoer i løpet av de siste tre årene: Omorganisering av arbeidet for å redusere høye krav og arbeidspress'],
		['Q303_2', 'Tiltak for å forebygge psykososiale risikoer i løpet av de siste tre årene: Konfidensiell rådgiving for arbeidstakere'],
		['Q303_3', 'Tiltak for å forebygge psykososiale risikoer i løpet av de siste tre årene: Utarbeidelse av en prosedyre for konfliktløsning'],
		['Q303_4', 'Tiltak for å forebygge psykososiale risikoer i løpet av de siste tre årene: Inngripen hvis for lange eller uregelmessige arbeidstider følges'],
		['Q307', 'Tilstrekkelig informasjon om hvordan psykososiale risikoer kan inkluderes i risikovurderinger'],
		['Q264_1', 'Grunner for å sette fokus på HMS på arbeidsplassen: Overholde lovpålagte krav'],
		['Q264_2', 'Grunner for å sette fokus på HMS på arbeidsplassen: Imøtekomme forventninger fra arbeidstakerne'],
		['Q264_4', 'Grunner for å sette fokus på HMS på arbeidsplassen: Øke produktiviteten'],
		['Q264_5', 'Grunner for å sette fokus på HMS på arbeidsplassen: Organisasjonens omdømme'],
		['Q264_6', 'Grunner for å sette fokus på HMS på arbeidsplassen: Unngå bøter og sanksjoner fra Arbeidstilsynet'],
		['Q265_1', 'Viktigste årsaker til at det er vanskelig å ta opp HMS: Mangel på tid eller personale'],
		['Q265_2', 'Viktigste årsaker til at det er vanskelig å ta opp HMS: Mangel på penger'],
		['Q265_3', 'Viktigste årsaker til at det er vanskelig å ta opp HMS: Manglende kunnskap om HMS blant personalet'],
		['Q265_4', 'Viktigste årsaker til at det er vanskelig å ta opp HMS: Manglende kunnskap om HMS i ledelsen'],
		['Q265_5', 'Viktigste årsaker til at det er vanskelig å ta opp HMS: Manglende kompetanse eller spesialisthjelp'],
		['Q265_6', 'Viktigste årsaker til at det er vanskelig å ta opp HMS: Papirarbeid'],
		['Q265_7', 'Viktigste årsaker til at det er vanskelig å ta opp HMS: De lovbestemte pliktene er for omfattende'],
		['Q304', 'Tiltak iverksatt på grunn av konkrete problemer'],
		['Q306a_3', 'Hindringer for håndtering av psykososiale risikoer: Manglende kunnskap om HMS blant personalet'],
		['Q306a_4', 'Hindringer for håndtering av psykososiale risikoer: Manglende kunnskap om HMS i ledelsen'],
		['Q306a_5', 'Hindringer for håndtering av psykososiale risikoer: Manglende kompetanse eller spesialisthjelp'],
		['Q306a_6', 'Hindringer for håndtering av psykososiale risikoer: Motvilje mot å snakke åpent om slike problemer'],
		['Q166_1', 'Typer arbeidstakerrepresentasjon: Bedriftsutvalg'],
		['Q166_2', 'Typer arbeidstakerrepresentasjon: Tillitsvalgt'],
		['Q166_3', 'Typer arbeidstakerrepresentasjon: Verneombud'],
		['Q166_4', 'Typer arbeidstakerrepresentasjon: Arbeidsmiljøutvalg (AMU)'],
		['Q258b', 'Arbeidstakerne er involvert i utformingen av tiltakene etter en risikovurdering'],
		['Q305', 'Arbeidstakerne deltar i utformingen av tiltak for å forebygge psykososiale risikoer'],
		['Q350', 'Hvor ofte HMS diskuteres blant de ansattes tillitsvalgte og ledelsen'],
		['Q351', 'Hvor ofte det oppstår uenighet i forbindelse med HMS-spørsmål'],
		['Q354', 'Verneombudene får opplæring i arbeidstiden'],
		['Q358', 'Diskusjon om HMS-spørsmål på personal- eller teammøter']
	];
var question_answer
	 = [
	
		['Q150_1', '1--Yes', 'Ja'],
		['Q150_1', '2--No', 'Nei'],
		['Q150_2', '1--Yes', 'Ja'],
		['Q150_2', '2--No', 'Nei'],
		['Q150_3', '1--Yes', 'Ja'],
		['Q150_3', '2--No', 'Nei'],
		['Q150_4', '1--Yes', 'Ja'],
		['Q150_4', '2--No', 'Nei'],
		['Q150_5', '1--Yes', 'Ja'],
		['Q150_5', '2--No', 'Nei'],
		['Q155', '1--Yes', 'Ja'],
		['Q155', '2--No', 'Nei'],
		['Q155', '3--Yes--but-only-to-some-types-of-employees', 'Ja, men bare for noen typer arbeidstakere'],
		['Q156', '1--Yes', 'Ja'],
		['Q156', '2--No', 'Nei'],
		['Q158_1', '1--Yes', 'Ja'],
		['Q158_1', '2--No', 'Nei'],
		['Q158_2', '1--Yes', 'Ja'],
		['Q158_2', '2--No', 'Nei'],
		['Q158_3', '1--Yes', 'Ja'],
		['Q158_3', '2--No', 'Nei'],
		['Q158_4', '1--Yes', 'Ja'],
		['Q158_4', '2--No', 'Nei'],
		['Q160', '1--Yes', 'Ja'],
		['Q160', '2--No', 'Nei'],
		['Q165', '1--Yes', 'Ja'],
		['Q165', '2--No', 'Nei'],
		['Q166_1', '1--Yes', 'Ja'],
		['Q166_1', '2--No', 'Nei'],
		['Q166_2', '1--Yes', 'Ja'],
		['Q166_2', '2--No', 'Nei'],
		['Q166_3', '1--Yes', 'Ja'],
		['Q166_3', '2--No', 'Nei'],
		['Q166_4', '1--Yes', 'Ja'],
		['Q166_4', '2--No', 'Nei'],
		['Q200_1', '1--Yes', 'Ja'],
		['Q200_1', '2--No', 'Nei'],
		['Q200_2', '1--Yes', 'Ja'],
		['Q200_2', '2--No', 'Nei'],
		['Q200_3', '1--Yes', 'Ja'],
		['Q200_3', '2--No', 'Nei'],
		['Q200_4', '1--Yes', 'Ja'],
		['Q200_4', '2--No', 'Nei'],
		['Q200_5', '1--Yes', 'Ja'],
		['Q200_5', '2--No', 'Nei'],
		['Q200_6', '1--Yes', 'Ja'],
		['Q200_6', '2--No', 'Nei'],
		['Q200_7', '1--Yes', 'Ja'],
		['Q200_7', '2--No', 'Nei'],
		['Q200_8', '1--Yes', 'Ja'],
		['Q200_8', '2--No', 'Nei'],
		['Q200_9', '1--Yes', 'Ja'],
		['Q200_9', '2--No', 'Nei'],
		['Q201_1', '1--Yes', 'Ja'],
		['Q201_1', '2--No', 'Nei'],
		['Q201_2', '1--Yes', 'Ja'],
		['Q201_2', '2--No', 'Nei'],
		['Q201_3', '1--Yes', 'Ja'],
		['Q201_3', '2--No', 'Nei'],
		['Q201_4', '1--Yes', 'Ja'],
		['Q201_4', '2--No', 'Nei'],
		['Q201_5', '1--Yes', 'Ja'],
		['Q201_5', '2--No', 'Nei'],
		['Q201_6', '1--Yes', 'Ja'],
		['Q201_6', '2--No', 'Nei'],
		['Q201_7', '1--Yes', 'Ja'],
		['Q201_7', '2--No', 'Nei'],
		['Q202_1', '1--Yes', 'Ja'],
		['Q202_1', '2--No', 'Nei'],
		['Q202_10', '1--Yes', 'Ja'],
		['Q202_10', '2--No', 'Nei'],
		['Q202_11', '1--Yes', 'Ja'],
		['Q202_11', '2--No', 'Nei'],
		['Q202_12', '1--Yes', 'Ja'],
		['Q202_12', '2--No', 'Nei'],
		['Q202_13', '1--Yes', 'Ja'],
		['Q202_13', '2--No', 'Nei'],
		['Q202_14', '1--Yes', 'Ja'],
		['Q202_14', '2--No', 'Nei'],
		['Q202_15', '1--Yes', 'Ja'],
		['Q202_15', '2--No', 'Nei'],
		['Q202_2', '1--Yes', 'Ja'],
		['Q202_2', '2--No', 'Nei'],
		['Q202_3', '1--Yes', 'Ja'],
		['Q202_3', '2--No', 'Nei'],
		['Q202_4', '1--Yes', 'Ja'],
		['Q202_4', '2--No', 'Nei'],
		['Q202_5', '1--Yes', 'Ja'],
		['Q202_5', '2--No', 'Nei'],
		['Q202_6', '1--Yes', 'Ja'],
		['Q202_6', '2--No', 'Nei'],
		['Q202_7', '1--Yes', 'Ja'],
		['Q202_7', '2--No', 'Nei'],
		['Q202_8', '1--Yes', 'Ja'],
		['Q202_8', '2--No', 'Nei'],
		['Q202_9', '1--Yes', 'Ja'],
		['Q202_9', '2--No', 'Nei'],
		['Q250', '1--Yes', 'Ja'],
		['Q250', '2--No', 'Nei'],
		['Q251', '1--Conducted-mainly-by-internal-staff', 'Hovedsakelig utført av internt personale'],
		['Q251', '2--Contracted-mainly-to-external-providers', 'Hovedsakelig satt bort til eksterne tjenesteleverandører'],
		['Q251', '3--Both-about-equally', 'Begge deler omtrent likt'],
		['Q252_1', '1--Yes', 'Ja'],
		['Q252_1', '2--No', 'Nei'],
		['Q252_2', '1--Yes', 'Ja'],
		['Q252_2', '2--No', 'Nei'],
		['Q252_3', '1--Yes', 'Ja'],
		['Q252_3', '2--No', 'Nei'],
		['Q252_4', '1--Yes', 'Ja'],
		['Q252_4', '2--No', 'Nei'],
		['Q252_5', '1--Yes', 'Ja'],
		['Q252_5', '2--No', 'Nei'],
		['Q252_6', '1--Yes', 'Ja'],
		['Q252_6', '2--No', 'Nei'],
		['Q254gr', '1--2010', '2010'],
		['Q254gr', '2--2011', '2011'],
		['Q254gr', '3--2012', '2012'],
		['Q254gr', '4--2013', '2013'],
		['Q254gr', '5--2014', '2014'],
		['Q254gr', '6--before-2010', 'før 2010'],
		['Q254gr', '7--don-t-know', 'Vet ikke'],
		['Q255', '1--Yes', 'Ja'],
		['Q255', '2--No', 'Nei'],
		['Q256_1', '1--Yes', 'Ja'],
		['Q256_1', '2--No', 'Nei'],
		['Q256_2', '1--Yes', 'Ja'],
		['Q256_2', '2--No', 'Nei'],
		['Q256_3', '1--Yes', 'Ja'],
		['Q256_3', '2--No', 'Nei'],
		['Q256_4', '1--Yes', 'Ja'],
		['Q256_4', '2--No', 'Nei'],
		['Q256_5', '1--Yes', 'Ja'],
		['Q256_5', '2--No', 'Nei'],
		['Q258b', '1--Yes', 'Ja'],
		['Q258b', '2--No', 'Nei'],
		['Q258b', '3--That-depends-on-the-type-of-measures', 'Det er avhengig av type tiltak'],
		['Q259', '1--Yes', 'Ja'],
		['Q259', '2--No', 'Nei'],
		['Q259', '3--There-are-conflicting-views-about-this', 'Det er delt syn på dette'],
		['Q261_1', '1--Yes', 'Ja'],
		['Q261_1', '2--No', 'Nei'],
		['Q261_2', '1--Yes', 'Ja'],
		['Q261_2', '2--No', 'Nei'],
		['Q261_3', '1--Yes', 'Ja'],
		['Q261_3', '2--No', 'Nei'],
		['Q261_4', '1--Yes', 'Ja'],
		['Q261_4', '2--No', 'Nei'],
		['Q264_1', '1--Major-reason', 'Viktig grunn'],
		['Q264_1', '2--Minor-reason', 'Mindre viktig grunn'],
		['Q264_1', '3--Not-a-reason', 'Ingen grunn'],
		['Q264_2', '1--Major-reason', 'Viktig grunn'],
		['Q264_2', '2--Minor-reason', 'Mindre viktig grunn'],
		['Q264_2', '3--Not-a-reason', 'Ingen grunn'],
		['Q264_4', '1--Major-reason', 'Viktig grunn'],
		['Q264_4', '2--Minor-reason', 'Mindre viktig grunn'],
		['Q264_4', '3--Not-a-reason', 'Ingen grunn'],
		['Q264_5', '1--Major-reason', 'Viktig grunn'],
		['Q264_5', '2--Minor-reason', 'Mindre viktig grunn'],
		['Q264_5', '3--Not-a-reason', 'Ingen grunn'],
		['Q264_6', '1--Major-reason', 'Viktig grunn'],
		['Q264_6', '2--Minor-reason', 'Mindre viktig grunn'],
		['Q264_6', '3--Not-a-reason', 'Ingen grunn'],
		['Q265_1', '1--Major-difficulty', 'Stort problem'],
		['Q265_1', '2--Minor-difficulty', 'Lite problem'],
		['Q265_1', '3--Not-a-difficulty', 'Ikke noe problem'],
		['Q265_2', '1--Major-difficulty', 'Stort problem'],
		['Q265_2', '2--Minor-difficulty', 'Lite problem'],
		['Q265_2', '3--Not-a-difficulty', 'Ikke noe problem'],
		['Q265_3', '1--Major-difficulty', 'Stort problem'],
		['Q265_3', '2--Minor-difficulty', 'Lite problem'],
		['Q265_3', '3--Not-a-difficulty', 'Ikke noe problem'],
		['Q265_4', '1--Major-difficulty', 'Stort problem'],
		['Q265_4', '2--Minor-difficulty', 'Lite problem'],
		['Q265_4', '3--Not-a-difficulty', 'Ikke noe problem'],
		['Q265_5', '1--Major-difficulty', 'Stort problem'],
		['Q265_5', '2--Minor-difficulty', 'Lite problem'],
		['Q265_5', '3--Not-a-difficulty', 'Ikke noe problem'],
		['Q265_6', '1--Major-difficulty', 'Stort problem'],
		['Q265_6', '2--Minor-difficulty', 'Lite problem'],
		['Q265_6', '3--Not-a-difficulty', 'Ikke noe problem'],
		['Q265_7', '1--Major-difficulty', 'Stort problem'],
		['Q265_7', '2--Minor-difficulty', 'Lite problem'],
		['Q265_7', '3--Not-a-difficulty', 'Ikke noe problem'],
		['Q300', '1--Yes', 'Ja'],
		['Q300', '2--No', 'Nei'],
		['Q301', '1--Yes', 'Ja'],
		['Q301', '2--No', 'Nei'],
		['Q302', '1--Yes', 'Ja'],
		['Q302', '2--No', 'Nei'],
		['Q303_1', '1--Yes', 'Ja'],
		['Q303_1', '2--No', 'Nei'],
		['Q303_2', '1--Yes', 'Ja'],
		['Q303_2', '2--No', 'Nei'],
		['Q303_3', '1--Yes', 'Ja'],
		['Q303_3', '2--No', 'Nei'],
		['Q303_4', '1--Yes', 'Ja'],
		['Q303_4', '2--No', 'Nei'],
		['Q304', '1--Yes', 'Ja'],
		['Q304', '2--No', 'Nei'],
		['Q304', '3--Partly', 'Delvis'],
		['Q305', '1--Yes', 'Ja'],
		['Q305', '2--No', 'Nei'],
		['Q306a_3', '1--Yes', 'Ja'],
		['Q306a_3', '2--No', 'Nei'],
		['Q306a_4', '1--Yes', 'Ja'],
		['Q306a_4', '2--No', 'Nei'],
		['Q306a_5', '1--Yes', 'Ja'],
		['Q306a_5', '2--No', 'Nei'],
		['Q306a_6', '1--Yes', 'Ja'],
		['Q306a_6', '2--No', 'Nei'],
		['Q307', '1--Yes', 'Ja'],
		['Q307', '2--No', 'Nei'],
		['Q308_1', '1--Yes', 'Ja'],
		['Q308_1', '2--No', 'Nei'],
		['Q308_2', '1--Yes', 'Ja'],
		['Q308_2', '2--No', 'Nei'],
		['Q308_3', '1--Yes', 'Ja'],
		['Q308_3', '2--No', 'Nei'],
		['Q308_4', '1--Yes', 'Ja'],
		['Q308_4', '2--No', 'Nei'],
		['Q350', '1--Regularly', 'Jevnlig'],
		['Q350', '2--Only-when-particular-issues-arise', 'Kun når konkrete problemer oppstår'],
		['Q350', '3--Not-at-all', 'Aldri'],
		['Q351', '1--Often', 'Ofte'],
		['Q351', '2--Sometimes', 'Noen ganger'],
		['Q351', '3--Practically-never', 'Praktisk talt aldri'],
		['Q354', '1--Yes', 'Ja'],
		['Q354', '2--No', 'Nei'],
		['Q354', '3--Yes--but-only-some-of-them', 'Ja, men bare noen av dem'],
		['Q356_1', '1--Yes', 'Ja'],
		['Q356_1', '2--No', 'Nei'],
		['Q356_2', '1--Yes', 'Ja'],
		['Q356_2', '2--No', 'Nei'],
		['Q356_3', '1--Yes', 'Ja'],
		['Q356_3', '2--No', 'Nei'],
		['Q356_4', '1--Yes', 'Ja'],
		['Q356_4', '2--No', 'Nei'],
		['Q356_5', '1--Yes', 'Ja'],
		['Q356_5', '2--No', 'Nei'],
		['Q358', '1--Yes', 'Ja'],
		['Q358', '2--No', 'Nei'],
		['Q358', '3--In-some-departments-only', 'Bare på noen avdelinger']
	];
var country_
	 = [
	
		['AL', 'Albania'],
		['AT', 'Østerrike'],
		['BE', 'Belgia'],
		['BG', 'Bulgaria'],
		['CH', 'Sveits'],
		['CY', 'Kypros'],
		['CZ', 'Tsjekkia'],
		['DE', 'Tyskland'],
		['DK', 'Danmark'],
		['EE', 'Estland'],
		['EL', 'Hellas'],
		['ES', 'Spania'],
		['FI', 'Finland'],
		['FR', 'Frankrike'],
		['HR', 'Kroatia'],
		['HU', 'Ungarn'],
		['IE', 'Irland'],
		['IS', 'Island'],
		['IT', 'Italia'],
		['LT', 'Litauen'],
		['LU', 'Luxembourg'],
		['LV', 'Latvia'],
		['ME', 'Montenegro'],
		['MK', 'FYROM'],
		['MT', 'Malta'],
		['NL', 'Nederland'],
		['NO', 'Norge'],
		['PL', 'Polen'],
		['PT', 'Portugal'],
		['RO', 'Romania'],
		['RS', 'Serbia'],
		['SE', 'Sverige'],
		['SI', 'Slovenia'],
		['SK', 'Slovakia'],
		['TR', 'Tyrkia'],
		['UK', 'Storbritannia'],
		['EuropeanUnion', 'Den europeiske union']
	];
var question_meta
	 = [
	
		['Q200_1', 'Anstrengende eller smertefulle stillinger, inkludert stillesitting i lange perioder', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Anstrengende eller smertefulle stillinger, inkludert stillesitting i lange perioder<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_2', 'Løfting og flytting av personer eller tung last', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Løfting og flytting av personer eller tung last<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_3', 'Støy', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Støy<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_4', 'Gjentatte hånd- eller armbevegelser', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Gjentatte hånd- eller armbevegelser<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_5', 'Varme, kulde eller trekk', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Varme, kulde eller trekk<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_6', 'Fare for ulykker med maskiner eller håndverktøy', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Fare for ulykker med maskiner eller håndverktøy<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_7', 'Fare for ulykker med kjøretøy i arbeidstiden, men ikke på vei til og fra jobb', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Fare for ulykker med kjøretøy i arbeidstiden, men ikke på vei til og fra jobb<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_8', 'Kjemiske eller biologiske stoffer i form av væske, damp eller støv', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Kjemiske eller biologiske stoffer i form av væske, damp eller støv<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_9', 'Økt risiko for å skli, snuble og falle', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Økt risiko for å skli, snuble og falle<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q201_1', 'Tidspress', 'I tillegg til disse risikoene finnes det kanskje også helsefarer som skyldes måten arbeidet er organisert på, sosiale forhold på arbeidsplassen eller den økonomiske situasjonen. Kan du angi for hver av følgende risikoer om de er til stede eller ikke på arbeidsplassen? Tidspress<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q201_2', 'Dårlig kommunikasjon eller dårlig samarbeid i organisasjonen', 'I tillegg til disse risikoene finnes det kanskje også helsefarer som skyldes måten arbeidet er organisert på, sosiale forhold på arbeidsplassen eller den økonomiske situasjonen. Kan du angi for hver av følgende risikoer om de er til stede eller ikke på arbeidsplassen? Dårlig kommunikasjon eller dårlig samarbeid i organisasjonen<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q201_3', 'Arbeidstakerne mangler innflytelse over arbeidstempoet eller arbeidsprosessene', 'I tillegg til disse risikoene finnes det kanskje også helsefarer som skyldes måten arbeidet er organisert på, sosiale forhold på arbeidsplassen eller den økonomiske situasjonen. Kan du angi for hver av følgende risikoer om de er til stede eller ikke på arbeidsplassen? Arbeidstakerne mangler innflytelse over arbeidstempoet eller arbeidsprosessene<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q201_4', 'Frykt for å miste jobben', 'I tillegg til disse risikoene finnes det kanskje også helsefarer som skyldes måten arbeidet er organisert på, sosiale forhold på arbeidsplassen eller den økonomiske situasjonen. Kan du angi for hver av følgende risikoer om de er til stede eller ikke på arbeidsplassen? Frykt for å miste jobben<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q201_5', 'Håndtering av vanskelige kunder, pasienter, elever etc.', 'I tillegg til disse risikoene finnes det kanskje også helsefarer som skyldes måten arbeidet er organisert på, sosiale forhold på arbeidsplassen eller den økonomiske situasjonen. Kan du angi for hver av følgende risikoer om de er til stede eller ikke på arbeidsplassen? Håndtering av vanskelige kunder, pasienter, elever etc.<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q201_6', 'Lange arbeidsdager eller uregelmessig arbeidstid', 'I tillegg til disse risikoene finnes det kanskje også helsefarer som skyldes måten arbeidet er organisert på, sosiale forhold på arbeidsplassen eller den økonomiske situasjonen. Kan du angi for hver av følgende risikoer om de er til stede eller ikke på arbeidsplassen? Lange arbeidsdager eller uregelmessig arbeidstid<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q201_7', 'Diskriminering, for eksempel på grunn av kjønn, alder eller etnisk bakgrunn', 'I tillegg til disse risikoene finnes det kanskje også helsefarer som skyldes måten arbeidet er organisert på, sosiale forhold på arbeidsplassen eller den økonomiske situasjonen. Kan du angi for hver av følgende risikoer om de er til stede eller ikke på arbeidsplassen? Diskriminering, for eksempel på grunn av kjønn, alder eller etnisk bakgrunn<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q250', 'Blir det regelmessig gjennomført risikovurderinger ved arbeidsplassen din?', 'Blir det regelmessig gjennomført risikovurderinger ved arbeidsplassen din?<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q251', 'Blir risikovurderinger hovedsakelig utført av internt personale eller blir de satt bort til eksterne tjenesteleverandører?', 'Blir risikovurderinger hovedsakelig utført av internt personale eller blir de satt bort til eksterne tjenesteleverandører?<br><br>(1) Hovedsakelig utført av internt personale <br>(2) Hovedsakelig satt bort til eksterne tjenesteleverandører <br>(3) Begge deler omtrent likt <br>(9) Intet svar<br><br>Spørsmål stilt til organisasjoner som oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q264_1', 'Overholde lovpålagte krav', 'Hvor viktige er grunnene nedenfor for å sette fokus på HMS på arbeidsplassen din? Angi for hver grunn om det er en viktig, mindre viktig eller ingen grunn i det hele tatt. Overholde lovpålagte krav<br><br>(1) Viktig grunn <br>(2) Mindre viktig grunn <br>(3) Ingen grunn <br>(9) Intet svar'],
		['Q264_2', 'Imøtekomme forventninger fra arbeidstakerne eller deres representanter', 'Hvor viktige er grunnene nedenfor for å sette fokus på HMS på arbeidsplassen din? Angi for hver grunn om det er en viktig, mindre viktig eller ingen grunn i det hele tatt. Imøtekomme forventninger fra arbeidstakerne eller deres representanter<br><br>(1) Viktig grunn <br>(2) Mindre viktig grunn <br>(3) Ingen grunn <br>(9) Intet svar'],
		['Q264_4', 'Opprettholde eller øke produktiviteten', 'Hvor viktige er grunnene nedenfor for å sette fokus på HMS på arbeidsplassen din? Angi for hver grunn om det er en viktig, mindre viktig eller ingen grunn i det hele tatt. Opprettholde eller øke produktiviteten<br><br>(1) Viktig grunn <br>(2) Mindre viktig grunn <br>(3) Ingen grunn <br>(9) Intet svar'],
		['Q264_5', 'Ivareta organisasjonens omdømme', 'Hvor viktige er grunnene nedenfor for å sette fokus på HMS på arbeidsplassen din? Angi for hver grunn om det er en viktig, mindre viktig eller ingen grunn i det hele tatt. Ivareta organisasjonens omdømme<br><br>(1) Viktig grunn <br>(2) Mindre viktig grunn <br>(3) Ingen grunn <br>(9) Intet svar'],
		['Q264_6', 'Unngå bøter og sanksjoner fra arbeidstilsynet', 'Hvor viktige er grunnene nedenfor for å sette fokus på HMS på arbeidsplassen din? Angi for hver grunn om det er en viktig, mindre viktig eller ingen grunn i det hele tatt. Unngå bøter og sanksjoner fra arbeidstilsynet<br><br>(1) Viktig grunn <br>(2) Mindre viktig grunn <br>(3) Ingen grunn <br>(9) Intet svar'],
		['Q307', 'Har du tilstrekkelig informasjon om hvordan psykososiale risikoer kan inkluderes i risikovurderinger?', 'Har du tilstrekkelig informasjon om hvordan psykososiale risikoer kan inkluderes i risikovurderinger?<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q150_1', 'En bedriftslege', 'Hvilke interne eller innleide HMS-tjenester benytter dere? En bedriftslege<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q150_2', 'En psykolog', 'Hvilke interne eller innleide HMS-tjenester benytter dere? En psykolog<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q150_3', 'En ekspert som arbeider med ergonomisk utforming av arbeidsplasser', 'Hvilke interne eller innleide HMS-tjenester benytter dere? En ekspert som arbeider med ergonomisk utforming av arbeidsplasser<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q150_4', 'En generalist innen HMS', 'Hvilke interne eller innleide HMS-tjenester benytter dere? En generalist innen HMS<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q150_5', 'En ekspert på ulykkesforebygging', 'Hvilke interne eller innleide HMS-tjenester benytter dere? En ekspert på ulykkesforebygging<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q155', 'Finnes det et informativt skriv om ansvar og prosedyrer i forbindelse med HMS som er tilgjengelig for alle på arbeidsplassen?', 'Finnes det et informativt skriv om ansvar og prosedyrer i forbindelse med HMS som er tilgjengelig for alle på arbeidsplassen?<br><br>(1) Ja <br>(2) Nei <br>(3) Ja, men bare for noen typer arbeidstakere <br>(9) Intet svar '],
		['Q156', 'Blir det årlig fastsatt et bestemt budsjett for HMS-tiltak og utstyr på arbeidsplassen?', 'Blir det årlig fastsatt et bestemt budsjett for HMS-tiltak og utstyr på arbeidsplassen?<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q158_1', 'Bevisstgjøring om sunn ernæring', 'Blir noen av de følgende tiltakene benyttet på arbeidsplassen for å fremme arbeidstakernes helse? Bevisstgjøring om sunn ernæring<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q158_2', 'Bevisstgjøring om forebygging av avhengighet, f.eks. av røyking, alkohol eller narkotika', 'Blir noen av de følgende tiltakene benyttet på arbeidsplassen for å fremme arbeidstakernes helse? Bevisstgjøring om forebygging av avhengighet, f.eks. av røyking, alkohol eller narkotika<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q158_3', 'Tilbud om sportsaktiviteter utenfor arbeidstiden', 'Blir noen av de følgende tiltakene benyttet på arbeidsplassen for å fremme arbeidstakernes helse? Tilbud om sportsaktiviteter utenfor arbeidstiden<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q158_4', 'Oppmuntring til å utføre ryggøvelser, strekking eller annen fysisk trening på jobb', 'Blir noen av de følgende tiltakene benyttet på arbeidsplassen for å fremme arbeidstakernes helse? Oppmuntring til å utføre ryggøvelser, strekking eller annen fysisk trening på jobb<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q160', 'Blir sykefravær rutinemessig analysert med sikte på å bedre arbeidsforholdene?', 'Blir sykefravær rutinemessig analysert med sikte på å bedre arbeidsforholdene?<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q165', 'Har arbeidsplassen din i løpet av de tre siste årene fått besøk av arbeidstilsynet for å kontrollere HMS-forholdene?', 'Har arbeidsplassen din i løpet av de tre siste årene fått besøk av arbeidstilsynet for å kontrollere HMS-forholdene?<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_1', 'Anstrengende eller smertefulle stillinger, inkludert stillesitting i lange perioder', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Anstrengende eller smertefulle stillinger, inkludert stillesitting i lange perioder<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_2', 'Løfting og flytting av personer eller tung last', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Løfting og flytting av personer eller tung last<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_3', 'Støy', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Støy<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_4', 'Gjentatte hånd- eller armbevegelser', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Gjentatte hånd- eller armbevegelser<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_5', 'Varme, kulde eller trekk', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Varme, kulde eller trekk<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_6', 'Fare for ulykker med maskiner eller håndverktøy', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Fare for ulykker med maskiner eller håndverktøy<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_7', 'Fare for ulykker med kjøretøy i arbeidstiden, men ikke på vei til og fra jobb', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Fare for ulykker med kjøretøy i arbeidstiden, men ikke på vei til og fra jobb<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_8', 'Kjemiske eller biologiske stoffer i form av væske, damp eller støv', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Kjemiske eller biologiske stoffer i form av væske, damp eller støv<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q200_9', 'Økt risiko for å skli, snuble og falle', 'Det finnes forskjellige typer risikoer og farer, avhengig av typen arbeid. Angi for hver av følgende risikofaktorer om de er til stede eller ikke på arbeidsplassen din, uavhengig om de for tiden er under kontroll og uavhengig av antall arbeidstakere de rammer. Økt risiko for å skli, snuble og falle<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q202_1', 'Anstrengende eller smertefulle stillinger, inkludert stillesitting i lange perioder', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Anstrengende eller smertefulle stillinger, inkludert stillesitting i lange perioder<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne risikofaktoren.'],
		['Q202_2', 'Løfting og flytting av personer eller tung last', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Løfting og flytting av personer eller tung last<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne risikofaktoren.'],
		['Q202_3', 'Støy', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Støy<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne risikofaktoren.'],
		['Q202_4', 'Gjentatte hånd- eller armbevegelser', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Gjentatte hånd- eller armbevegelser<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne risikofaktoren.'],
		['Q202_5', 'Varme, kulde eller trekk', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Varme, kulde eller trekk<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne risikofaktoren.'],
		['Q202_6', 'Fare for ulykker med maskiner eller håndverktøy', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Fare for ulykker med maskiner eller håndverktøy<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne risikofaktoren.'],
		['Q202_7', 'Fare for ulykker med kjøretøy i arbeidstiden', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Fare for ulykker med kjøretøy i arbeidstiden<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne risikofaktoren.'],
		['Q202_8', 'Kjemiske eller biologiske stoffer', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Kjemiske eller biologiske stoffer<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne risikofaktoren.'],
		['Q202_9', 'Økt risiko for å skli, snuble og falle', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Økt risiko for å skli, snuble og falle<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne risikofaktoren.'],
		['Q250', 'Blir det regelmessig gjennomført risikovurderinger ved arbeidsplassen din?', 'Blir det regelmessig gjennomført risikovurderinger ved arbeidsplassen din?<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q251', 'Blir risikovurderinger hovedsakelig utført av internt personale eller blir de satt bort til eksterne tjenesteleverandører?', 'Blir risikovurderinger hovedsakelig utført av internt personale eller blir de satt bort til eksterne tjenesteleverandører?<br><br>(1) Hovedsakelig utført av internt personale <br>(2) Hovedsakelig satt bort til eksterne tjenesteleverandører <br>(3) Begge deler omtrent likt <br>(9) Intet svar<br><br>Spørsmål stilt til organisasjoner som oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q252_1', 'Sikkerheten til maskiner, utstyr og installasjoner', 'Hvilke av følgende forhold blir rutinemessig evaluert i risikovurderingene på arbeidsplassen? Sikkerheten til maskiner, utstyr og installasjoner<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q252_2', 'Farlige kjemiske eller biologiske stoffer', 'Hvilke av følgende forhold blir rutinemessig evaluert i risikovurderingene på arbeidsplassen? Farlige kjemiske eller biologiske stoffer<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q252_3', 'Arbeidsstillinger, fysiske arbeidskrav og repetitive bevegelser', 'Hvilke av følgende forhold blir rutinemessig evaluert i risikovurderingene på arbeidsplassen? Arbeidsstillinger, fysiske arbeidskrav og repetitive bevegelser<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q252_4', 'Eksponering for støy, vibrasjoner, varme eller kulde', 'Hvilke av følgende forhold blir rutinemessig evaluert i risikovurderingene på arbeidsplassen? Eksponering for støy, vibrasjoner, varme eller kulde<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q252_5', 'Forholdet mellom arbeidstaker og overordnet', 'Hvilke av følgende forhold blir rutinemessig evaluert i risikovurderingene på arbeidsplassen? Forholdet mellom arbeidstaker og overordnet<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q252_6', 'Organisatoriske aspekter som arbeidsplaner, pauser eller skift', 'Hvilke av følgende forhold blir rutinemessig evaluert i risikovurderingene på arbeidsplassen? Organisatoriske aspekter som arbeidsplaner, pauser eller skift<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q254gr', 'Hvilket år ble siste risikovurdering på arbeidsplassen utført?', 'Hvilket år ble siste risikovurdering på arbeidsplassen utført?<br><br>(År) <br>(9998) Vet ikke <br>(9999) Intet svar<br><br>Spørsmål stilt til organisasjoner som oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q255', 'Har dette blitt dokumentert skriftlig?', 'Har dette blitt dokumentert skriftlig?<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å ha gjennomført siste risikovurdering på arbeidsplassen etter 1970.'],
		['Q256_1', 'Ledelsen', 'Hvem har fått resultatene fra risikovurderingen på arbeidsplassen? Ledelsen<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å ha gjennomført siste risikovurdering på arbeidsplassen etter 1970.'],
		['Q256_2', 'Verneombudene', 'Hvem har fått resultatene fra risikovurderingen på arbeidsplassen? Verneombudene<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å ha gjennomført siste risikovurdering på arbeidsplassen etter 1970 og har verneombud.'],
		['Q256_3', 'Bedriftsutvalget', 'Hvem har fått resultatene fra risikovurderingen på arbeidsplassen? Bedriftsutvalget<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å ha gjennomført siste risikovurdering på arbeidsplassen etter 1970 og har bedriftsutvalg.'],
		['Q256_4', 'Tillitsvalgte', 'Hvem har fått resultatene fra risikovurderingen på arbeidsplassen? Tillitsvalgte<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å ha gjennomført siste risikovurdering på arbeidsplassen etter 1970 og har tillitsvalgte.'],
		['Q256_5', 'Arbeidstakerne selv', 'Hvem har fått resultatene fra risikovurderingen på arbeidsplassen? Arbeidstakerne selv<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å ha gjennomført siste risikovurdering på arbeidsplassen etter 1970.'],
		['Q259', 'Blir risikovurdering ansett som en nyttig prosedyre for å håndtere HMS på arbeidsplassen din?', 'Blir risikovurdering ansett som en nyttig prosedyre for å håndtere HMS på arbeidsplassen din?<br><br>(1) Ja <br>(2) Nei <br>(3) Det er delt syn på dette <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q261_1', 'Farene og risikoene er allerede kjent', 'Er det noen spesielle grunner til at det ikke jevnlig blir utført risikovurderinger på arbeidsplassen? Kan du angi hvorvidt hvert av følgende utsagn er relevant på arbeidsplassen din? Farene og risikoene er allerede kjent<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som ikke oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q261_2', 'Det finnes ikke problemer av betydning', 'Er det noen spesielle grunner til at det ikke jevnlig blir utført risikovurderinger på arbeidsplassen? Kan du angi hvorvidt hvert av følgende utsagn er relevant på arbeidsplassen din? Det finnes ikke problemer av betydning<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som ikke oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q261_3', 'Prosedyren er for belastende', 'Er det noen spesielle grunner til at det ikke jevnlig blir utført risikovurderinger på arbeidsplassen? Kan du angi hvorvidt hvert av følgende utsagn er relevant på arbeidsplassen din? Prosedyren er for belastende<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som ikke oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q261_4', 'Den nødvendige ekspertisen mangler', 'Er det noen spesielle grunner til at det ikke jevnlig blir utført risikovurderinger på arbeidsplassen? Kan du angi hvorvidt hvert av følgende utsagn er relevant på arbeidsplassen din? Den nødvendige ekspertisen mangler<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som ikke oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q308_1', 'Utstyr for hjelp til løfting eller flytting av last eller annet fysisk tungt arbeid', 'Vi retter nå oppmerksomheten mot problemer med muskler og skjelettsystem, f.eks. smerte i rygg, nakke, armer, hender eller bein. Er noen av følgende forebyggende tiltak iverksatt på arbeidsplassen din? Utstyr for hjelp til løfting eller flytting av last eller annet fysisk tungt arbeid<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir løfting og flytting av personer eller tung last som en risikofaktor.'],
		['Q308_2', 'Rotering av arbeidsoppgaver for å redusere repetitive bevegelser eller fysisk belastning', 'Vi retter nå oppmerksomheten mot problemer med muskler og skjelettsystem, f.eks. smerte i rygg, nakke, armer, hender eller bein. Er noen av følgende forebyggende tiltak iverksatt på arbeidsplassen din? Rotering av arbeidsoppgaver for å redusere repetitive bevegelser eller fysisk belastning<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir gjentatte hånd- eller armbevegelser som en risikofaktor.'],
		['Q308_3', 'Oppfordring til å ta jevnlige pauser når arbeidsstillingene er ubehagelige eller statiske, inkludert ved langvarig stillesitting', 'Vi retter nå oppmerksomheten mot problemer med muskler og skjelettsystem, f.eks. smerte i rygg, nakke, armer, hender eller bein. Er noen av følgende forebyggende tiltak iverksatt på arbeidsplassen din? Oppfordring til å ta jevnlige pauser når arbeidsstillingene er ubehagelige eller statiske, inkludert ved langvarig stillesitting<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q308_4', 'Anskaffelse av ergonomisk utstyr, for eksempel bestemte stoler eller skrivebord', 'Vi retter nå oppmerksomheten mot problemer med muskler og skjelettsystem, f.eks. smerte i rygg, nakke, armer, hender eller bein. Er noen av følgende forebyggende tiltak iverksatt på arbeidsplassen din? Anskaffelse av ergonomisk utstyr, for eksempel bestemte stoler eller skrivebord<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q356_1', 'Riktig bruk og regulering av arbeidsutstyr og møbler', 'Hvilke av følgende emner får arbeidstakerne opplæring i på arbeidsplassen? Riktig bruk og regulering av arbeidsutstyr og møbler<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q356_2', 'Bruk av farlige stoffer', 'Hvilke av følgende emner får arbeidstakerne opplæring i på arbeidsplassen? Bruk av farlige stoffer<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q356_3', 'Hvordan psykososiale risikoer som stress eller mobbing kan forebygges', 'Hvilke av følgende emner får arbeidstakerne opplæring i på arbeidsplassen? Hvordan psykososiale risikoer som stress eller mobbing kan forebygges<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q356_4', 'Hvordan tung last eller personer skal løftes og flyttes', 'Hvilke av følgende emner får arbeidstakerne opplæring i på arbeidsplassen? Hvordan tung last eller personer skal løftes og flyttes<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q356_5', 'Nødprosedyrer', 'Hvilke av følgende emner får arbeidstakerne opplæring i på arbeidsplassen? Nødprosedyrer<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q201_1', 'Tidspress', 'I tillegg til disse risikoene finnes det kanskje også helsefarer som skyldes måten arbeidet er organisert på, sosiale forhold på arbeidsplassen eller den økonomiske situasjonen. Kan du angi for hver av følgende risikoer om de er til stede eller ikke på arbeidsplassen? Tidspress<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q201_2', 'Dårlig kommunikasjon eller dårlig samarbeid i organisasjonen', 'I tillegg til disse risikoene finnes det kanskje også helsefarer som skyldes måten arbeidet er organisert på, sosiale forhold på arbeidsplassen eller den økonomiske situasjonen. Kan du angi for hver av følgende risikoer om de er til stede eller ikke på arbeidsplassen? Dårlig kommunikasjon eller dårlig samarbeid i organisasjonen<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q201_3', 'Arbeidstakerne mangler innflytelse over arbeidstempoet eller arbeidsprosessene', 'I tillegg til disse risikoene finnes det kanskje også helsefarer som skyldes måten arbeidet er organisert på, sosiale forhold på arbeidsplassen eller den økonomiske situasjonen. Kan du angi for hver av følgende risikoer om de er til stede eller ikke på arbeidsplassen? Arbeidstakerne mangler innflytelse over arbeidstempoet eller arbeidsprosessene<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q201_4', 'Frykt for å miste jobben', 'I tillegg til disse risikoene finnes det kanskje også helsefarer som skyldes måten arbeidet er organisert på, sosiale forhold på arbeidsplassen eller den økonomiske situasjonen. Kan du angi for hver av følgende risikoer om de er til stede eller ikke på arbeidsplassen? Frykt for å miste jobben<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q201_5', 'Håndtering av vanskelige kunder, pasienter, elever etc.', 'I tillegg til disse risikoene finnes det kanskje også helsefarer som skyldes måten arbeidet er organisert på, sosiale forhold på arbeidsplassen eller den økonomiske situasjonen. Kan du angi for hver av følgende risikoer om de er til stede eller ikke på arbeidsplassen? Håndtering av vanskelige kunder, pasienter, elever etc.<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q201_6', 'Lange arbeidsdager eller uregelmessig arbeidstid', 'I tillegg til disse risikoene finnes det kanskje også helsefarer som skyldes måten arbeidet er organisert på, sosiale forhold på arbeidsplassen eller den økonomiske situasjonen. Kan du angi for hver av følgende risikoer om de er til stede eller ikke på arbeidsplassen? Lange arbeidsdager eller uregelmessig arbeidstid<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q201_7', 'Diskriminering, for eksempel på grunn av kjønn, alder eller etnisk bakgrunn', 'I tillegg til disse risikoene finnes det kanskje også helsefarer som skyldes måten arbeidet er organisert på, sosiale forhold på arbeidsplassen eller den økonomiske situasjonen. Kan du angi for hver av følgende risikoer om de er til stede eller ikke på arbeidsplassen? Diskriminering, for eksempel på grunn av kjønn, alder eller etnisk bakgrunn<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q202_10', 'Tidspress', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Tidspress<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne psykososiale risikofaktoren.'],
		['Q202_11', 'Dårlig kommunikasjon eller dårlig samarbeid i organisasjonen', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Dårlig kommunikasjon eller dårlig samarbeid i organisasjonen<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne psykososiale risikofaktoren.'],
		['Q202_12', 'Arbeidstakerne mangler innflytelse over arbeidstempoet eller arbeidsprosessene', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Arbeidstakerne mangler innflytelse over arbeidstempoet eller arbeidsprosessene<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne psykososiale risikofaktoren.'],
		['Q202_13', 'Frykt for å miste jobben', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Frykt for å miste jobben<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne psykososiale risikofaktoren.'],
		['Q202_14', 'Håndtering av vanskelige kunder, pasienter, elever etc.', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Håndtering av vanskelige kunder, pasienter, elever etc.<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne psykososiale risikofaktoren.'],
		['Q202_15', 'Lange arbeidsdager eller uregelmessig arbeidstid', 'For hvilke av risikoene mangler arbeidsplassen din informasjon eller gode forebyggende verktøy for effektiv håndtering? Lange arbeidsdager eller uregelmessig arbeidstid<br><br>(1) Ja <br>(2) Nei<br><br>Spørsmål stilt til organisasjoner som oppgir å ha denne psykososiale risikofaktoren.'],
		['Q300', 'Finnes det en handlingsplan for å forebygge arbeidsrelatert stress på arbeidsplassen?', 'Finnes det en handlingsplan for å forebygge arbeidsrelatert stress på arbeidsplassen?<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner med 20 eller flere arbeidstakere.'],
		['Q301', 'Finnes det en prosedyre for å håndtere mulige tilfeller av mobbing eller trakassering?', 'Finnes det en prosedyre for å håndtere mulige tilfeller av mobbing eller trakassering?<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner med 20 eller flere arbeidstakere.'],
		['Q302', 'Og finnes det en prosedyre for håndtering av mulige tilfeller av trusler, sjikane eller angrep fra kunder, pasienter, elever eller andre eksterne personer?', 'Og finnes det en prosedyre for håndtering av mulige tilfeller av trusler, sjikane eller angrep fra kunder, pasienter, elever eller andre eksterne personer?<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner med 20 eller flere arbeidstakere som oppgir at de må håndtere vanskelige kunder, pasienter, elever som en risikofaktor.'],
		['Q303_1', 'Omorganisering av arbeidet for å redusere høye krav og arbeidspress', 'I løpet av de siste tre årene, har noen av de følgende tiltakene blitt benyttet for å forebygge psykososiale risikoer på arbeidsplassen? Omorganisering av arbeidet for å redusere høye krav og arbeidspress<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q303_2', 'Konfidensiell rådgiving for arbeidstakere', 'I løpet av de siste tre årene, har noen av de følgende tiltakene blitt benyttet for å forebygge psykososiale risikoer på arbeidsplassen? Konfidensiell rådgiving for arbeidstakere<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q303_3', 'Utarbeidelse av en prosedyre for konfliktløsning', 'I løpet av de siste tre årene, har noen av de følgende tiltakene blitt benyttet for å forebygge psykososiale risikoer på arbeidsplassen? Utarbeidelse av en prosedyre for konfliktløsning<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q303_4', 'Inngripen hvis for lange eller uregelmessige arbeidstider følges', 'I løpet av de siste tre årene, har noen av de følgende tiltakene blitt benyttet for å forebygge psykososiale risikoer på arbeidsplassen? Inngripen hvis for lange eller uregelmessige arbeidstider følges<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q307', 'Har du tilstrekkelig informasjon om hvordan psykososiale risikoer kan inkluderes i risikovurderinger?', 'Har du tilstrekkelig informasjon om hvordan psykososiale risikoer kan inkluderes i risikovurderinger?<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar '],
		['Q264_1', 'Overholde lovpålagte krav', 'Hvor viktige er grunnene nedenfor for å sette fokus på HMS på arbeidsplassen din? Angi for hver grunn om det er en viktig, mindre viktig eller ingen grunn i det hele tatt. Overholde lovpålagte krav<br><br>(1) Viktig grunn <br>(2) Mindre viktig grunn <br>(3) Ingen grunn <br>(9) Intet svar'],
		['Q264_2', 'Imøtekomme forventninger fra arbeidstakerne eller deres representanter', 'Hvor viktige er grunnene nedenfor for å sette fokus på HMS på arbeidsplassen din? Angi for hver grunn om det er en viktig, mindre viktig eller ingen grunn i det hele tatt. Imøtekomme forventninger fra arbeidstakerne eller deres representanter<br><br>(1) Viktig grunn <br>(2) Mindre viktig grunn <br>(3) Ingen grunn <br>(9) Intet svar'],
		['Q264_4', 'Opprettholde eller øke produktiviteten', 'Hvor viktige er grunnene nedenfor for å sette fokus på HMS på arbeidsplassen din? Angi for hver grunn om det er en viktig, mindre viktig eller ingen grunn i det hele tatt. Opprettholde eller øke produktiviteten<br><br>(1) Viktig grunn <br>(2) Mindre viktig grunn <br>(3) Ingen grunn <br>(9) Intet svar'],
		['Q264_5', 'Ivareta organisasjonens omdømme', 'Hvor viktige er grunnene nedenfor for å sette fokus på HMS på arbeidsplassen din? Angi for hver grunn om det er en viktig, mindre viktig eller ingen grunn i det hele tatt. Ivareta organisasjonens omdømme<br><br>(1) Viktig grunn <br>(2) Mindre viktig grunn <br>(3) Ingen grunn <br>(9) Intet svar'],
		['Q264_6', 'Unngå bøter og sanksjoner fra arbeidstilsynet', 'Hvor viktige er grunnene nedenfor for å sette fokus på HMS på arbeidsplassen din? Angi for hver grunn om det er en viktig, mindre viktig eller ingen grunn i det hele tatt. Unngå bøter og sanksjoner fra arbeidstilsynet<br><br>(1) Viktig grunn <br>(2) Mindre viktig grunn <br>(3) Ingen grunn <br>(9) Intet svar'],
		['Q265_1', 'Mangel på tid eller personale', 'Hva er det som gjør det mest vanskelig å ta opp HMS på arbeidsplassen? Kan du for hvert av de følgende alternativene angi om det er et stort problem, et lite problem eller ingen problem i det hele tatt. Mangel på tid eller personale<br><br>(1) Stort problem <br>(2) Lite problem <br>(3) Ikke noe problem <br>(9) Intet svar'],
		['Q265_2', 'Mangel på penger', 'Hva er det som gjør det mest vanskelig å ta opp HMS på arbeidsplassen? Kan du for hvert av de følgende alternativene angi om det er et stort problem, et lite problem eller ingen problem i det hele tatt. Mangel på penger<br><br>(1) Stort problem <br>(2) Lite problem <br>(3) Ikke noe problem <br>(9) Intet svar'],
		['Q265_3', 'Manglende kunnskap om HMS blant personalet', 'Hva er det som gjør det mest vanskelig å ta opp HMS på arbeidsplassen? Kan du for hvert av de følgende alternativene angi om det er et stort problem, et lite problem eller ingen problem i det hele tatt. Manglende kunnskap om HMS blant personalet<br><br>(1) Stort problem <br>(2) Lite problem <br>(3) Ikke noe problem <br>(9) Intet svar'],
		['Q265_4', 'Manglende kunnskap om HMS i ledelsen', 'Hva er det som gjør det mest vanskelig å ta opp HMS på arbeidsplassen? Kan du for hvert av de følgende alternativene angi om det er et stort problem, et lite problem eller ingen problem i det hele tatt. Manglende kunnskap om HMS i ledelsen<br><br>(1) Stort problem <br>(2) Lite problem <br>(3) Ikke noe problem <br>(9) Intet svar'],
		['Q265_5', 'Manglende kompetanse eller spesialisthjelp', 'Hva er det som gjør det mest vanskelig å ta opp HMS på arbeidsplassen? Kan du for hvert av de følgende alternativene angi om det er et stort problem, et lite problem eller ingen problem i det hele tatt. Manglende kompetanse eller spesialisthjelp<br><br>(1) Stort problem <br>(2) Lite problem <br>(3) Ikke noe problem <br>(9) Intet svar'],
		['Q265_6', 'Papirarbeid', 'Hva er det som gjør det mest vanskelig å ta opp HMS på arbeidsplassen? Kan du for hvert av de følgende alternativene angi om det er et stort problem, et lite problem eller ingen problem i det hele tatt. Papirarbeid<br><br>(1) Stort problem <br>(2) Lite problem <br>(3) Ikke noe problem <br>(9) Intet svar'],
		['Q265_7', 'De lovbestemte pliktene er for omfattende', 'Hva er det som gjør det mest vanskelig å ta opp HMS på arbeidsplassen? Kan du for hvert av de følgende alternativene angi om det er et stort problem, et lite problem eller ingen problem i det hele tatt. De lovbestemte pliktene er for omfattende<br><br>(1) Stort problem <br>(2) Lite problem <br>(3) Ikke noe problem <br>(9) Intet svar'],
		['Q304', 'Ble tiltakene iverksatt på grunn av konkrete problemer med stress, mobbing, trakassering eller vold på arbeidsplassen?', 'Ble tiltakene iverksatt på grunn av konkrete problemer med stress, mobbing, trakassering eller vold på arbeidsplassen?<br><br>(1) Ja <br>(2) Nei <br>(8) Delvis <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å ha iverksatt tiltak for å forebygge psykososiale risikoer i løpet av de siste tre årene.'],
		['Q306a_3', 'Manglende kunnskap om HMS blant personalet', 'Situasjonen på arbeidsplassen din tatt i betraktning: Gjør noen av de følgende faktorene det vanskeligere å ta opp psykososiale risikoer enn andre helsefarer? Manglende kunnskap om HMS blant personalet<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å ha en av de oppførte psykososiale risikofaktorene.'],
		['Q306a_4', 'Manglende kunnskap om HMS i ledelsen', 'Situasjonen på arbeidsplassen din tatt i betraktning: Gjør noen av de følgende faktorene det vanskeligere å ta opp psykososiale risikoer enn andre helsefarer? Manglende kunnskap om HMS i ledelsen<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å ha en av de oppførte psykososiale risikofaktorene.'],
		['Q306a_5', 'Manglende kompetanse eller spesialisthjelp', 'Situasjonen på arbeidsplassen din tatt i betraktning: Gjør noen av de følgende faktorene det vanskeligere å ta opp psykososiale risikoer enn andre helsefarer? Manglende kompetanse eller spesialisthjelp<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å ha en av de oppførte psykososiale risikofaktorene.'],
		['Q306a_6', 'Motvilje mot å snakke åpent om slike problemer', 'Situasjonen på arbeidsplassen din tatt i betraktning: Gjør noen av de følgende faktorene det vanskeligere å ta opp psykososiale risikoer enn andre helsefarer? Motvilje mot å snakke åpent om slike problemer<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å ha en av de oppførte psykososiale risikofaktorene.'],
		['Q166_1', 'Bedriftsutvalg', 'Hvilke av følgende typer arbeidstakerrepresentasjon har dere på arbeidsplassen? Bedriftsutvalg<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til alle, størrelsen avhenger av nasjonale terskler for disse organene.'],
		['Q166_2', 'Tillitsvalgt', 'Hvilke av følgende typer arbeidstakerrepresentasjon har dere på arbeidsplassen? Tillitsvalgt<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til alle, størrelsen avhenger av nasjonale terskler for disse organene.'],
		['Q166_3', 'Verneombud', 'Hvilke av følgende typer arbeidstakerrepresentasjon har dere på arbeidsplassen? Verneombud<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til alle, størrelsen avhenger av nasjonale terskler for disse organene.'],
		['Q166_4', 'Arbeidsmiljøutvalg (AMU)', 'Hvilke av følgende typer arbeidstakerrepresentasjon har dere på arbeidsplassen? Arbeidsmiljøutvalg (AMU)<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til alle, størrelsen avhenger av nasjonale terskler for disse organene.'],
		['Q258b', 'Dersom tiltak må iverksettes etter en risikovurdering: Er arbeidstakerne vanligvis involvert i utformingen og implementeringen av disse?', 'Dersom tiltak må iverksettes etter en risikovurdering: Er arbeidstakerne vanligvis involvert i utformingen og implementeringen av disse?<br><br>(1) Ja <br>(2) Nei <br>(4) Det er avhengig av type tiltak <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å gjennomføre risikovurderinger regelmessig.'],
		['Q305', 'Deltok arbeidstakerne i utformingen og iverksettelsen av tiltakene for å håndtere psykososiale risikoer?', 'Deltok arbeidstakerne i utformingen og iverksettelsen av tiltakene for å håndtere psykososiale risikoer?<br><br>(1) Ja <br>(2) Nei <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å ha iverksatt tiltak for å forebygge psykososiale risikoer i løpet av de siste tre årene.'],
		['Q350', 'Hvor ofte diskuteres HMS blant de ansattes tillitsvalgte og ledelsen? Finner slike diskusjoner sted regelmessig, bare når det oppstår konkrete HMS-problemer eller ikke i det hele tatt?', 'Hvor ofte diskuteres HMS blant de ansattes tillitsvalgte og ledelsen? Finner slike diskusjoner sted regelmessig, bare når det oppstår konkrete HMS-problemer eller ikke i det hele tatt?<br><br>(1) Jevnlig <br>(2) Kun når konkrete problemer oppstår <br>(3) Aldri <br>(7) Ikke relevant (det finnes ingen tillitsvalgte) <br>(9) Intet svar<br><br>Spørsmål stilt til organisasjoner som oppgir å ha en form for arbeidstakerrepresentasjon.'],
		['Q351', 'Og hvor ofte oppstår det uenighet i forbindelse med HMS-spørsmål? Er dette ofte, noen ganger eller praktisk talt aldri?', 'Og hvor ofte oppstår det uenighet i forbindelse med HMS-spørsmål? Er dette ofte, noen ganger eller praktisk talt aldri?<br><br>(1) Ofte <br>(2) Noen ganger <br>(3) Praktisk talt aldri <br>(9) Intet svar<br><br>Spørsmål stilt til organisasjoner som oppgir at HMS diskuteres blant de ansattes tillitsvalgte og ledelsen'],
		['Q354', 'Får verneombudene opplæring i arbeidstiden som kan hjelpe dem med å utføre HMS-relaterte oppgaver?', 'Får verneombudene opplæring i arbeidstiden som kan hjelpe dem med å utføre HMS-relaterte oppgaver?<br><br>(1) Ja <br>(2) Nei <br>(3) Ja, men bare noen av dem <br>(9) Intet svar <br><br>Spørsmål stilt til organisasjoner som oppgir å ha verneombud.'],
		['Q358', 'Blir HMS-spørsmål jevnlig diskutert på personal- eller teammøter?', 'Blir HMS-spørsmål jevnlig diskutert på personal- eller teammøter?<br><br>(1) Ja <br>(2) Nei <br>(3) Bare på noen avdelinger <br>(9) Intet svar ']
	];
