//Auto Generated file
var subset_
	 = [
	
		['Sectorgrp', 'Sektor działalności'],
		['Size', 'Wielkość zakładu pracy']
	];
var subset_subsetValue
	 = [
	
		['Sectorgrp', 'All', 'Wszystkie'],
		['Sectorgrp', '1--A', 'Rolnictwo, leśnictwo i rybactwo'],
		['Sectorgrp', '2--BDEF', 'Budownictwo, gospodarowanie odpadami, dostawa wody i zaopatrywanie w energię elektryczną'],
		['Sectorgrp', '3--C', 'Przetwórstwo przemysłowe'],
		['Sectorgrp', '4--GHIR', 'Handel, transport, działalność związana z zakwaterowaniem/usługami gastronomicznymi i rekreacją'],
		['Sectorgrp', '5--JKLMNS', 'IT, finanse, nieruchomości i inna działalność naukowa i techniczna lub usługi osobiste'],
		['Sectorgrp', '6--O', 'Administracja publiczna'],
		['Sectorgrp', '7--PQ', 'Edukacja, opieka zdrowotna i pomoc społeczna'],
		['Size', 'All', 'Wszystkie'],
		['Size', '1--5-to-9', 'od 5 do 9 pracowników'],
		['Size', '2--10-to-49', 'od 10 do 49 pracowników'],
		['Size', '3--50-249', 'od 50 do 249 pracowników'],
		['Size', '4--250-', '250 lub więcej pracowników']
	];
var topic_
	 = [
	
		['', 'Wszystkie (108)'],
		['Czynniki motywujące i bariery', 'Czynniki motywujące i bariery (17)'],
		['Kluczowe ustalenia', 'Kluczowe ustalenia (24)'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Ryzyko psychospołeczne i zarządzanie nim (21)'],
		['Udział pracowników', 'Udział pracowników (10)'],
		['Zarządzanie BHP', 'Zarządzanie BHP (60)']
	];
var topic_question
	 = [
	
		['Kluczowe ustalenia', 'Q200_1', 'Czynniki ryzyka występujące w zakładzie pracy: Męczące lub bolesne pozycje'],
		['Kluczowe ustalenia', 'Q200_2', 'Czynniki ryzyka występujące w zakładzie pracy: Podnoszenia lub przenoszenia ludzi lub znacznych ciężarów'],
		['Kluczowe ustalenia', 'Q200_3', 'Czynniki ryzyka występujące w zakładzie pracy: Hałas'],
		['Kluczowe ustalenia', 'Q200_4', 'Czynniki ryzyka występujące w zakładzie pracy: Powtarzające się ruchy dłoni lub ramion'],
		['Kluczowe ustalenia', 'Q200_5', 'Czynniki ryzyka występujące w zakładzie pracy: Gorąco, zimno lub przeciąg'],
		['Kluczowe ustalenia', 'Q200_6', 'Czynniki ryzyka występujące w zakładzie pracy: Ryzyko wypadków spowodowanych przez maszyny'],
		['Kluczowe ustalenia', 'Q200_7', 'Czynniki ryzyka występujące w zakładzie pracy: Ryzyko wypadków podczas pracy spowodowanych przez pojazdy'],
		['Kluczowe ustalenia', 'Q200_8', 'Czynniki ryzyka występujące w zakładzie pracy: Substancje chemiczne lub biologiczne'],
		['Kluczowe ustalenia', 'Q200_9', 'Czynniki ryzyka występujące w zakładzie pracy: Zwiększone ryzyko poślizgnięcia, potknięcia lub upadku '],
		['Kluczowe ustalenia', 'Q201_1', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Presja czasu  '],
		['Kluczowe ustalenia', 'Q201_2', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Słaba komunikacja lub współpraca'],
		['Kluczowe ustalenia', 'Q201_3', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Brak wpływu pracowników'],
		['Kluczowe ustalenia', 'Q201_4', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Niepewność zatrudnienia  '],
		['Kluczowe ustalenia', 'Q201_5', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Trudni klienci, pacjenci, uczniowie itp.'],
		['Kluczowe ustalenia', 'Q201_6', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Długie lub nieregularne godziny pracy  '],
		['Kluczowe ustalenia', 'Q201_7', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Dyskryminacja'],
		['Kluczowe ustalenia', 'Q250', 'Oceny ryzyka zawodowego w miejscu pracy'],
		['Kluczowe ustalenia', 'Q251', 'Oceny ryzyka przeprowadzane głównie przez pracowników wewnętrznych lub zlecane na zewnątrz'],
		['Kluczowe ustalenia', 'Q264_1', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Spełnienie wymogów prawnych '],
		['Kluczowe ustalenia', 'Q264_2', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Spełnienie oczekiwań pracowników'],
		['Kluczowe ustalenia', 'Q264_4', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Zwiększenie produktywności'],
		['Kluczowe ustalenia', 'Q264_5', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Reputacja organizacji'],
		['Kluczowe ustalenia', 'Q264_6', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Uniknięcie kar Państwowej Inspekcji Pracy'],
		['Kluczowe ustalenia', 'Q307', 'Wystarczające informacje na temat tego, jak uwzględnić w ocenie ryzyka zagrożenia psychospołeczne'],
		['Zarządzanie BHP', 'Q150_1', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: Lekarz medycyny pracy'],
		['Zarządzanie BHP', 'Q150_2', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: Psycholog'],
		['Zarządzanie BHP', 'Q150_3', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: Ekspert w zakresie projektowania ergonomicznego i planowania przestrzennego miejsc pracy'],
		['Zarządzanie BHP', 'Q150_4', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: Specjalista w zakresie bezpieczeństwa i higieny pracy'],
		['Zarządzanie BHP', 'Q150_5', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: Ekspert ds. zapobiegania wypadkom'],
		['Zarządzanie BHP', 'Q155', 'Dostępność dokumentów wyjaśniających obowiązki i procedury BHP dla pracowników'],
		['Zarządzanie BHP', 'Q156', 'Określenie budżetu rocznego przeznaczonego na środki i wyposażenie BHP'],
		['Zarządzanie BHP', 'Q158_1', 'Środki mające na celu promocję zdrowia wśród pracowników: Podnoszenie świadomości na temat zdrowego odżywiania '],
		['Zarządzanie BHP', 'Q158_2', 'Środki mające na celu promocję zdrowia wśród pracowników: Podnoszenie świadomości na temat zapobiegania uzależnieniom'],
		['Zarządzanie BHP', 'Q158_3', 'Środki mające na celu promocję zdrowia wśród pracowników: Promowanie aktywności fizycznej poza godzinami pracy'],
		['Zarządzanie BHP', 'Q158_4', 'Środki mające na celu promocję zdrowia wśród pracowników: Promowanie ćwiczeń fizycznych w czasie pracy'],
		['Zarządzanie BHP', 'Q160', 'Rutynowa analiza nieobecności z powodu choroby'],
		['Zarządzanie BHP', 'Q165', 'Kontrola Państwowej Inspekcji Pracy w ciągu ostatnich 3 lat w celu sprawdzenie warunków BHP'],
		['Zarządzanie BHP', 'Q200_1', 'Czynniki ryzyka występujące w zakładzie pracy: Męczące lub bolesne pozycje'],
		['Zarządzanie BHP', 'Q200_2', 'Czynniki ryzyka występujące w zakładzie pracy: Podnoszenia lub przenoszenia ludzi lub znacznych ciężarów'],
		['Zarządzanie BHP', 'Q200_3', 'Czynniki ryzyka występujące w zakładzie pracy: Hałas'],
		['Zarządzanie BHP', 'Q200_4', 'Czynniki ryzyka występujące w zakładzie pracy: Powtarzające się ruchy dłoni lub ramion'],
		['Zarządzanie BHP', 'Q200_5', 'Czynniki ryzyka występujące w zakładzie pracy: Gorąco, zimno lub przeciąg'],
		['Zarządzanie BHP', 'Q200_6', 'Czynniki ryzyka występujące w zakładzie pracy: Ryzyko wypadków spowodowanych przez maszyny'],
		['Zarządzanie BHP', 'Q200_7', 'Czynniki ryzyka występujące w zakładzie pracy: Ryzyko wypadków podczas pracy spowodowanych przez pojazdy'],
		['Zarządzanie BHP', 'Q200_8', 'Czynniki ryzyka występujące w zakładzie pracy: Substancje chemiczne lub biologiczne'],
		['Zarządzanie BHP', 'Q200_9', 'Czynniki ryzyka występujące w zakładzie pracy: Zwiększone ryzyko poślizgnięcia, potknięcia lub upadku '],
		['Zarządzanie BHP', 'Q202_1', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Męczące lub bolesne pozycje'],
		['Zarządzanie BHP', 'Q202_2', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Podnoszenia lub przenoszenia ludzi lub znacznych ciężarów'],
		['Zarządzanie BHP', 'Q202_3', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Hałas'],
		['Zarządzanie BHP', 'Q202_4', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Powtarzające się ruchy dłoni lub ramion'],
		['Zarządzanie BHP', 'Q202_5', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Gorąco, zimno lub przeciąg'],
		['Zarządzanie BHP', 'Q202_6', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Ryzyko wypadków spowodowanych przez maszyny'],
		['Zarządzanie BHP', 'Q202_7', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Ryzyko wypadków podczas pracy spowodowanych przez pojazdy'],
		['Zarządzanie BHP', 'Q202_8', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Substancje chemiczne lub biologiczne'],
		['Zarządzanie BHP', 'Q202_9', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Zwiększone ryzyko poślizgnięcia, potknięcia lub upadku '],
		['Zarządzanie BHP', 'Q250', 'Oceny ryzyka zawodowego w miejscu pracy'],
		['Zarządzanie BHP', 'Q251', 'Oceny ryzyka przeprowadzane głównie przez pracowników wewnętrznych lub zlecane na zewnątrz'],
		['Zarządzanie BHP', 'Q252_1', 'Aspekty podlegające ocenie ryzyka zawodowego w miejscu pracy: Bezpieczeństwo maszyn, urządzeń i instalacji  '],
		['Zarządzanie BHP', 'Q252_2', 'Aspekty podlegające ocenie ryzyka zawodowego w miejscu pracy: Substancje niebezpieczne'],
		['Zarządzanie BHP', 'Q252_3', 'Aspekty podlegające ocenie ryzyka zawodowego w miejscu pracy: Postawa w czasie pracy, wymagania fizyczne i powtarzające się ruchy '],
		['Zarządzanie BHP', 'Q252_4', 'Aspekty podlegające ocenie ryzyka zawodowego w miejscu pracy: Narażenie na hałas, wibracje, gorąco lub zimno  '],
		['Zarządzanie BHP', 'Q252_5', 'Aspekty podlegające ocenie ryzyka zawodowego w miejscu pracy: Relacje między kierownictwem a pracownikami  '],
		['Zarządzanie BHP', 'Q252_6', 'Aspekty podlegające ocenie ryzyka zawodowego w miejscu pracy: Aspekty organizacyjne'],
		['Zarządzanie BHP', 'Q254gr', 'Rok, w którym po raz ostatni przeprowadzono ocenę ryzyka zawodowego w miejscu pracy'],
		['Zarządzanie BHP', 'Q255', 'Ocena ryzyka zawodowego w miejscu pracy udokumentowana w formie pisemnej'],
		['Zarządzanie BHP', 'Q256_1', 'Osoby, którym przedstawiono wnioski z oceny ryzyka zawodowego w miejscu pracy: Zarządowi  '],
		['Zarządzanie BHP', 'Q256_2', 'Osoby, którym przedstawiono wnioski z oceny ryzyka zawodowego w miejscu pracy: Społecznym inspektorom pracy  '],
		['Zarządzanie BHP', 'Q256_3', 'Osoby, którym przedstawiono wnioski z oceny ryzyka zawodowego w miejscu pracy: Radzie pracowników  '],
		['Zarządzanie BHP', 'Q256_4', 'Osoby, którym przedstawiono wnioski z oceny ryzyka zawodowego w miejscu pracy: Zakładowej organizacji związkowej  '],
		['Zarządzanie BHP', 'Q256_5', 'Osoby, którym przedstawiono wnioski z oceny ryzyka zawodowego w miejscu pracy: Pracownikom  '],
		['Zarządzanie BHP', 'Q259', 'Ocena ryzyka postrzegana jako pożyteczny sposób zarządzania kwestiami bezpieczeństwa i higieny pracy'],
		['Zarządzanie BHP', 'Q261_1', 'Powody, dla których ocena ryzyka zawodowego w miejscu pracy nie jest regularnie przeprowadzana: Zagrożenia i ryzyko są już znane'],
		['Zarządzanie BHP', 'Q261_2', 'Powody, dla których ocena ryzyka zawodowego w miejscu pracy nie jest regularnie przeprowadzana: nie ma większych problemów  '],
		['Zarządzanie BHP', 'Q261_3', 'Powody, dla których ocena ryzyka zawodowego w miejscu pracy nie jest regularnie przeprowadzana: procedura jest zbyt uciążliwa  '],
		['Zarządzanie BHP', 'Q261_4', 'Powody, dla których ocena ryzyka zawodowego w miejscu pracy nie jest regularnie przeprowadzana: brakuje niezbędnej wiedzy fachowej'],
		['Zarządzanie BHP', 'Q308_1', 'Środki zapobiegawcze dotyczące problemów układu mięśniowo-szkieletowego: Sprzęt do pomocy przy podnoszeniu i przenoszeniu ciężarów'],
		['Zarządzanie BHP', 'Q308_2', 'Środki zapobiegawcze dotyczące problemów układu mięśniowo-szkieletowego: Rotacja zadań w celu ograniczenia wysiłku fizycznego'],
		['Zarządzanie BHP', 'Q308_3', 'Środki zapobiegawcze dotyczące problemów układu mięśniowo-szkieletowego: Zachęcanie osób pracujących w niewygodnych lub statycznych pozycjach do regularnych przerw'],
		['Zarządzanie BHP', 'Q308_4', 'Środki zapobiegawcze dotyczące problemów układu mięśniowo-szkieletowego: Zapewnienie ergonomicznego sprzętu'],
		['Zarządzanie BHP', 'Q356_1', 'Szkolenia dla pracowników: Prawidłowe użytkowanie i dostosowanie wyposażenia i mebli do charakteru pracy'],
		['Zarządzanie BHP', 'Q356_2', 'Szkolenia dla pracowników: Używanie substancji niebezpiecznych'],
		['Zarządzanie BHP', 'Q356_3', 'Szkolenia dla pracowników: Zapobieganie zagrożeniom psychospołecznym'],
		['Zarządzanie BHP', 'Q356_4', 'Szkolenia dla pracowników: Sposoby podnoszenia i przenoszenia znacznych ciężarów lub osób'],
		['Zarządzanie BHP', 'Q356_5', 'Szkolenia dla pracowników: Procedury w sytuacjach awaryjnych'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q201_1', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Presja czasu  '],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q201_2', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Słaba komunikacja lub współpraca'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q201_3', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Brak wpływu pracowników'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q201_4', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Niepewność zatrudnienia  '],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q201_5', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Trudni klienci, pacjenci, uczniowie itp.'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q201_6', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Długie lub nieregularne godziny pracy  '],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q201_7', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Dyskryminacja'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q202_10', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Presja czasu  '],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q202_11', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Słaba komunikacja lub współpraca'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q202_12', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Brak wpływu pracowników'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q202_13', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Niepewność zatrudnienia  '],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q202_14', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Trudni klienci, pacjenci, uczniowie itp.'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q202_15', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Długie lub nieregularne godziny pracy  '],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q300', 'Plan zapobiegania stresowi związanemu z pracą'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q301', 'Procedury postępowania na wypadek mobbingu lub molestowania'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q302', 'Procedura postępowania na wypadek gróźb, wykorzystywania czy napaści'],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q303_1', 'Działania stosowane w celu zapobiegania zagrożeniom psychospołecznym w ostatnich trzech latach: Reorganizacja pracy w celu zmniejszenia wymagań i presji '],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q303_2', 'Działania stosowane w celu zapobiegania zagrożeniom psychospołecznym w ostatnich trzech latach: Poufne doradztwo dla pracowników '],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q303_3', 'Działania stosowane w celu zapobiegania zagrożeniom psychospołecznym w ostatnich trzech latach: Ustanowienie procedury rozwiązywania konfliktów '],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q303_4', 'Działania stosowane w celu zapobiegania zagrożeniom psychospołecznym w ostatnich trzech latach: Interwencja w przypadku zbyt długich lub nieregularnych godzin pracy '],
		['Ryzyko psychospołeczne i zarządzanie nim', 'Q307', 'Wystarczające informacje na temat tego, jak uwzględnić w ocenie ryzyka zagrożenia psychospołeczne'],
		['Czynniki motywujące i bariery', 'Q264_1', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Spełnienie wymogów prawnych '],
		['Czynniki motywujące i bariery', 'Q264_2', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Spełnienie oczekiwań pracowników'],
		['Czynniki motywujące i bariery', 'Q264_4', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Zwiększenie produktywności'],
		['Czynniki motywujące i bariery', 'Q264_5', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Reputacja organizacji'],
		['Czynniki motywujące i bariery', 'Q264_6', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Uniknięcie kar Państwowej Inspekcji Pracy'],
		['Czynniki motywujące i bariery', 'Q265_1', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: Brak czasu lub personelu '],
		['Czynniki motywujące i bariery', 'Q265_2', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: Brak pieniędzy'],
		['Czynniki motywujące i bariery', 'Q265_3', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: Brak świadomości na temat tych kwestii wśród pracowników '],
		['Czynniki motywujące i bariery', 'Q265_4', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: Brak świadomości na temat tych kwestii wśród zarządu '],
		['Czynniki motywujące i bariery', 'Q265_5', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: Brak specjalistycznej wiedzy lub pomocy '],
		['Czynniki motywujące i bariery', 'Q265_6', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: Biurokracja '],
		['Czynniki motywujące i bariery', 'Q265_7', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: Złożoność wymogów prawnych'],
		['Czynniki motywujące i bariery', 'Q304', 'Działania podjęte w wyniku wystąpienia konkretnych problemów'],
		['Czynniki motywujące i bariery', 'Q306a_3', 'Trudności w przeciwdziałaniu zagrożeniom psychospołecznym: Brak świadomości na temat tych kwestii wśród personelu '],
		['Czynniki motywujące i bariery', 'Q306a_4', 'Trudności w przeciwdziałaniu zagrożeniom psychospołecznym: Brak świadomości na temat tych kwestii wśród zarządu '],
		['Czynniki motywujące i bariery', 'Q306a_5', 'Trudności w przeciwdziałaniu zagrożeniom psychospołecznym: Brak specjalistycznej wiedzy lub pomocy '],
		['Czynniki motywujące i bariery', 'Q306a_6', 'Trudności w przeciwdziałaniu zagrożeniom psychospołecznym: Niechęć do mówienia otwarcie o tych zagadnieniach'],
		['Udział pracowników', 'Q166_1', 'Formy reprezentacji pracowników: Rada pracowników'],
		['Udział pracowników', 'Q166_2', 'Formy reprezentacji pracowników: Zakładowa organizacja związkowa'],
		['Udział pracowników', 'Q166_3', 'Formy reprezentacji pracowników: Przedstawiciel pracowników ds. BHP np. Społeczny inspektor pracy'],
		['Udział pracowników', 'Q166_4', 'Formy reprezentacji pracowników: Komisja BHP'],
		['Udział pracowników', 'Q258b', 'Pracownicy uczestniczący w planowaniu działań podejmowanych w następstwie przeprowadzonej oceny ryzyka zawodowego'],
		['Udział pracowników', 'Q305', 'Pracownicy odgrywają rolę w planowaniu działań mających przeciwdziałać zagrożeniom psychospołecznym'],
		['Udział pracowników', 'Q350', 'Jak często BHP jest przedmiotem dyskusji między przedstawicielami pracowników a zarządem'],
		['Udział pracowników', 'Q351', 'Jak często pojawiają się nieporozumienia związane z BHP'],
		['Udział pracowników', 'Q354', 'Społeczni inspektorzy pracy uczestniczą w szkoleniach organizowanych w czasie pracy'],
		['Udział pracowników', 'Q358', 'Kwestie BHP są omawiane na zebraniach pracowników lub zebraniach zespołów']
	];
var question_
	 = [
	
		['Q200_1', 'Czynniki ryzyka występujące w zakładzie pracy: Męczące lub bolesne pozycje'],
		['Q200_2', 'Czynniki ryzyka występujące w zakładzie pracy: Podnoszenia lub przenoszenia ludzi lub znacznych ciężarów'],
		['Q200_3', 'Czynniki ryzyka występujące w zakładzie pracy: Hałas'],
		['Q200_4', 'Czynniki ryzyka występujące w zakładzie pracy: Powtarzające się ruchy dłoni lub ramion'],
		['Q200_5', 'Czynniki ryzyka występujące w zakładzie pracy: Gorąco, zimno lub przeciąg'],
		['Q200_6', 'Czynniki ryzyka występujące w zakładzie pracy: Ryzyko wypadków spowodowanych przez maszyny'],
		['Q200_7', 'Czynniki ryzyka występujące w zakładzie pracy: Ryzyko wypadków podczas pracy spowodowanych przez pojazdy'],
		['Q200_8', 'Czynniki ryzyka występujące w zakładzie pracy: Substancje chemiczne lub biologiczne'],
		['Q200_9', 'Czynniki ryzyka występujące w zakładzie pracy: Zwiększone ryzyko poślizgnięcia, potknięcia lub upadku '],
		['Q201_1', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Presja czasu  '],
		['Q201_2', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Słaba komunikacja lub współpraca'],
		['Q201_3', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Brak wpływu pracowników'],
		['Q201_4', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Niepewność zatrudnienia  '],
		['Q201_5', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Trudni klienci, pacjenci, uczniowie itp.'],
		['Q201_6', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Długie lub nieregularne godziny pracy  '],
		['Q201_7', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Dyskryminacja'],
		['Q250', 'Oceny ryzyka zawodowego w miejscu pracy'],
		['Q251', 'Oceny ryzyka przeprowadzane głównie przez pracowników wewnętrznych lub zlecane na zewnątrz'],
		['Q264_1', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Spełnienie wymogów prawnych '],
		['Q264_2', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Spełnienie oczekiwań pracowników'],
		['Q264_4', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Zwiększenie produktywności'],
		['Q264_5', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Reputacja organizacji'],
		['Q264_6', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Uniknięcie kar Państwowej Inspekcji Pracy'],
		['Q307', 'Wystarczające informacje na temat tego, jak uwzględnić w ocenie ryzyka zagrożenia psychospołeczne'],
		['Q150_1', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: Lekarz medycyny pracy'],
		['Q150_2', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: Psycholog'],
		['Q150_3', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: Ekspert w zakresie projektowania ergonomicznego i planowania przestrzennego miejsc pracy'],
		['Q150_4', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: Specjalista w zakresie bezpieczeństwa i higieny pracy'],
		['Q150_5', 'Korzystanie z usług w zakresie bezpieczeństwa i higieny pracy: Ekspert ds. zapobiegania wypadkom'],
		['Q155', 'Dostępność dokumentów wyjaśniających obowiązki i procedury BHP dla pracowników'],
		['Q156', 'Określenie budżetu rocznego przeznaczonego na środki i wyposażenie BHP'],
		['Q158_1', 'Środki mające na celu promocję zdrowia wśród pracowników: Podnoszenie świadomości na temat zdrowego odżywiania '],
		['Q158_2', 'Środki mające na celu promocję zdrowia wśród pracowników: Podnoszenie świadomości na temat zapobiegania uzależnieniom'],
		['Q158_3', 'Środki mające na celu promocję zdrowia wśród pracowników: Promowanie aktywności fizycznej poza godzinami pracy'],
		['Q158_4', 'Środki mające na celu promocję zdrowia wśród pracowników: Promowanie ćwiczeń fizycznych w czasie pracy'],
		['Q160', 'Rutynowa analiza nieobecności z powodu choroby'],
		['Q165', 'Kontrola Państwowej Inspekcji Pracy w ciągu ostatnich 3 lat w celu sprawdzenie warunków BHP'],
		['Q200_1', 'Czynniki ryzyka występujące w zakładzie pracy: Męczące lub bolesne pozycje'],
		['Q200_2', 'Czynniki ryzyka występujące w zakładzie pracy: Podnoszenia lub przenoszenia ludzi lub znacznych ciężarów'],
		['Q200_3', 'Czynniki ryzyka występujące w zakładzie pracy: Hałas'],
		['Q200_4', 'Czynniki ryzyka występujące w zakładzie pracy: Powtarzające się ruchy dłoni lub ramion'],
		['Q200_5', 'Czynniki ryzyka występujące w zakładzie pracy: Gorąco, zimno lub przeciąg'],
		['Q200_6', 'Czynniki ryzyka występujące w zakładzie pracy: Ryzyko wypadków spowodowanych przez maszyny'],
		['Q200_7', 'Czynniki ryzyka występujące w zakładzie pracy: Ryzyko wypadków podczas pracy spowodowanych przez pojazdy'],
		['Q200_8', 'Czynniki ryzyka występujące w zakładzie pracy: Substancje chemiczne lub biologiczne'],
		['Q200_9', 'Czynniki ryzyka występujące w zakładzie pracy: Zwiększone ryzyko poślizgnięcia, potknięcia lub upadku '],
		['Q202_1', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Męczące lub bolesne pozycje'],
		['Q202_2', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Podnoszenia lub przenoszenia ludzi lub znacznych ciężarów'],
		['Q202_3', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Hałas'],
		['Q202_4', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Powtarzające się ruchy dłoni lub ramion'],
		['Q202_5', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Gorąco, zimno lub przeciąg'],
		['Q202_6', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Ryzyko wypadków spowodowanych przez maszyny'],
		['Q202_7', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Ryzyko wypadków podczas pracy spowodowanych przez pojazdy'],
		['Q202_8', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Substancje chemiczne lub biologiczne'],
		['Q202_9', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Zwiększone ryzyko poślizgnięcia, potknięcia lub upadku '],
		['Q250', 'Oceny ryzyka zawodowego w miejscu pracy'],
		['Q251', 'Oceny ryzyka przeprowadzane głównie przez pracowników wewnętrznych lub zlecane na zewnątrz'],
		['Q252_1', 'Aspekty podlegające ocenie ryzyka zawodowego w miejscu pracy: Bezpieczeństwo maszyn, urządzeń i instalacji  '],
		['Q252_2', 'Aspekty podlegające ocenie ryzyka zawodowego w miejscu pracy: Substancje niebezpieczne'],
		['Q252_3', 'Aspekty podlegające ocenie ryzyka zawodowego w miejscu pracy: Postawa w czasie pracy, wymagania fizyczne i powtarzające się ruchy '],
		['Q252_4', 'Aspekty podlegające ocenie ryzyka zawodowego w miejscu pracy: Narażenie na hałas, wibracje, gorąco lub zimno  '],
		['Q252_5', 'Aspekty podlegające ocenie ryzyka zawodowego w miejscu pracy: Relacje między kierownictwem a pracownikami  '],
		['Q252_6', 'Aspekty podlegające ocenie ryzyka zawodowego w miejscu pracy: Aspekty organizacyjne'],
		['Q254gr', 'Rok, w którym po raz ostatni przeprowadzono ocenę ryzyka zawodowego w miejscu pracy'],
		['Q255', 'Ocena ryzyka zawodowego w miejscu pracy udokumentowana w formie pisemnej'],
		['Q256_1', 'Osoby, którym przedstawiono wnioski z oceny ryzyka zawodowego w miejscu pracy: Zarządowi  '],
		['Q256_2', 'Osoby, którym przedstawiono wnioski z oceny ryzyka zawodowego w miejscu pracy: Społecznym inspektorom pracy  '],
		['Q256_3', 'Osoby, którym przedstawiono wnioski z oceny ryzyka zawodowego w miejscu pracy: Radzie pracowników  '],
		['Q256_4', 'Osoby, którym przedstawiono wnioski z oceny ryzyka zawodowego w miejscu pracy: Zakładowej organizacji związkowej  '],
		['Q256_5', 'Osoby, którym przedstawiono wnioski z oceny ryzyka zawodowego w miejscu pracy: Pracownikom  '],
		['Q259', 'Ocena ryzyka postrzegana jako pożyteczny sposób zarządzania kwestiami bezpieczeństwa i higieny pracy'],
		['Q261_1', 'Powody, dla których ocena ryzyka zawodowego w miejscu pracy nie jest regularnie przeprowadzana: Zagrożenia i ryzyko są już znane'],
		['Q261_2', 'Powody, dla których ocena ryzyka zawodowego w miejscu pracy nie jest regularnie przeprowadzana: nie ma większych problemów  '],
		['Q261_3', 'Powody, dla których ocena ryzyka zawodowego w miejscu pracy nie jest regularnie przeprowadzana: procedura jest zbyt uciążliwa  '],
		['Q261_4', 'Powody, dla których ocena ryzyka zawodowego w miejscu pracy nie jest regularnie przeprowadzana: brakuje niezbędnej wiedzy fachowej'],
		['Q308_1', 'Środki zapobiegawcze dotyczące problemów układu mięśniowo-szkieletowego: Sprzęt do pomocy przy podnoszeniu i przenoszeniu ciężarów'],
		['Q308_2', 'Środki zapobiegawcze dotyczące problemów układu mięśniowo-szkieletowego: Rotacja zadań w celu ograniczenia wysiłku fizycznego'],
		['Q308_3', 'Środki zapobiegawcze dotyczące problemów układu mięśniowo-szkieletowego: Zachęcanie osób pracujących w niewygodnych lub statycznych pozycjach do regularnych przerw'],
		['Q308_4', 'Środki zapobiegawcze dotyczące problemów układu mięśniowo-szkieletowego: Zapewnienie ergonomicznego sprzętu'],
		['Q356_1', 'Szkolenia dla pracowników: Prawidłowe użytkowanie i dostosowanie wyposażenia i mebli do charakteru pracy'],
		['Q356_2', 'Szkolenia dla pracowników: Używanie substancji niebezpiecznych'],
		['Q356_3', 'Szkolenia dla pracowników: Zapobieganie zagrożeniom psychospołecznym'],
		['Q356_4', 'Szkolenia dla pracowników: Sposoby podnoszenia i przenoszenia znacznych ciężarów lub osób'],
		['Q356_5', 'Szkolenia dla pracowników: Procedury w sytuacjach awaryjnych'],
		['Q201_1', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Presja czasu  '],
		['Q201_2', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Słaba komunikacja lub współpraca'],
		['Q201_3', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Brak wpływu pracowników'],
		['Q201_4', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Niepewność zatrudnienia  '],
		['Q201_5', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Trudni klienci, pacjenci, uczniowie itp.'],
		['Q201_6', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Długie lub nieregularne godziny pracy  '],
		['Q201_7', 'Czynniki ryzyka psychospołecznego występujące w zakładzie pracy: Dyskryminacja'],
		['Q202_10', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Presja czasu  '],
		['Q202_11', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Słaba komunikacja lub współpraca'],
		['Q202_12', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Brak wpływu pracowników'],
		['Q202_13', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Niepewność zatrudnienia  '],
		['Q202_14', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Trudni klienci, pacjenci, uczniowie itp.'],
		['Q202_15', 'Brak informacji lub odpowiednich narzędzi umożliwiających skuteczne przeciwdziałanie ryzyku: Długie lub nieregularne godziny pracy  '],
		['Q300', 'Plan zapobiegania stresowi związanemu z pracą'],
		['Q301', 'Procedury postępowania na wypadek mobbingu lub molestowania'],
		['Q302', 'Procedura postępowania na wypadek gróźb, wykorzystywania czy napaści'],
		['Q303_1', 'Działania stosowane w celu zapobiegania zagrożeniom psychospołecznym w ostatnich trzech latach: Reorganizacja pracy w celu zmniejszenia wymagań i presji '],
		['Q303_2', 'Działania stosowane w celu zapobiegania zagrożeniom psychospołecznym w ostatnich trzech latach: Poufne doradztwo dla pracowników '],
		['Q303_3', 'Działania stosowane w celu zapobiegania zagrożeniom psychospołecznym w ostatnich trzech latach: Ustanowienie procedury rozwiązywania konfliktów '],
		['Q303_4', 'Działania stosowane w celu zapobiegania zagrożeniom psychospołecznym w ostatnich trzech latach: Interwencja w przypadku zbyt długich lub nieregularnych godzin pracy '],
		['Q307', 'Wystarczające informacje na temat tego, jak uwzględnić w ocenie ryzyka zagrożenia psychospołeczne'],
		['Q264_1', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Spełnienie wymogów prawnych '],
		['Q264_2', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Spełnienie oczekiwań pracowników'],
		['Q264_4', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Zwiększenie produktywności'],
		['Q264_5', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Reputacja organizacji'],
		['Q264_6', 'Przyczyny zajmowania się kwestiami BHP w zakładzie pracy: Uniknięcie kar Państwowej Inspekcji Pracy'],
		['Q265_1', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: Brak czasu lub personelu '],
		['Q265_2', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: Brak pieniędzy'],
		['Q265_3', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: Brak świadomości na temat tych kwestii wśród pracowników '],
		['Q265_4', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: Brak świadomości na temat tych kwestii wśród zarządu '],
		['Q265_5', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: Brak specjalistycznej wiedzy lub pomocy '],
		['Q265_6', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: Biurokracja '],
		['Q265_7', 'Główne kwestie utrudniające zajmowanie się kwestiami BHP: Złożoność wymogów prawnych'],
		['Q304', 'Działania podjęte w wyniku wystąpienia konkretnych problemów'],
		['Q306a_3', 'Trudności w przeciwdziałaniu zagrożeniom psychospołecznym: Brak świadomości na temat tych kwestii wśród personelu '],
		['Q306a_4', 'Trudności w przeciwdziałaniu zagrożeniom psychospołecznym: Brak świadomości na temat tych kwestii wśród zarządu '],
		['Q306a_5', 'Trudności w przeciwdziałaniu zagrożeniom psychospołecznym: Brak specjalistycznej wiedzy lub pomocy '],
		['Q306a_6', 'Trudności w przeciwdziałaniu zagrożeniom psychospołecznym: Niechęć do mówienia otwarcie o tych zagadnieniach'],
		['Q166_1', 'Formy reprezentacji pracowników: Rada pracowników'],
		['Q166_2', 'Formy reprezentacji pracowników: Zakładowa organizacja związkowa'],
		['Q166_3', 'Formy reprezentacji pracowników: Przedstawiciel pracowników ds. BHP np. Społeczny inspektor pracy'],
		['Q166_4', 'Formy reprezentacji pracowników: Komisja BHP'],
		['Q258b', 'Pracownicy uczestniczący w planowaniu działań podejmowanych w następstwie przeprowadzonej oceny ryzyka zawodowego'],
		['Q305', 'Pracownicy odgrywają rolę w planowaniu działań mających przeciwdziałać zagrożeniom psychospołecznym'],
		['Q350', 'Jak często BHP jest przedmiotem dyskusji między przedstawicielami pracowników a zarządem'],
		['Q351', 'Jak często pojawiają się nieporozumienia związane z BHP'],
		['Q354', 'Społeczni inspektorzy pracy uczestniczą w szkoleniach organizowanych w czasie pracy'],
		['Q358', 'Kwestie BHP są omawiane na zebraniach pracowników lub zebraniach zespołów']
	];
var question_answer
	 = [
	
		['Q150_1', '1--Yes', 'Tak'],
		['Q150_1', '2--No', 'Nie'],
		['Q150_2', '1--Yes', 'Tak'],
		['Q150_2', '2--No', 'Nie'],
		['Q150_3', '1--Yes', 'Tak'],
		['Q150_3', '2--No', 'Nie'],
		['Q150_4', '1--Yes', 'Tak'],
		['Q150_4', '2--No', 'Nie'],
		['Q150_5', '1--Yes', 'Tak'],
		['Q150_5', '2--No', 'Nie'],
		['Q155', '1--Yes', 'Tak'],
		['Q155', '2--No', 'Nie'],
		['Q155', '3--Yes--but-only-to-some-types-of-employees', 'Tak, ale tylko niektóre grupy pradowników'],
		['Q156', '1--Yes', 'Tak'],
		['Q156', '2--No', 'Nie'],
		['Q158_1', '1--Yes', 'Tak'],
		['Q158_1', '2--No', 'Nie'],
		['Q158_2', '1--Yes', 'Tak'],
		['Q158_2', '2--No', 'Nie'],
		['Q158_3', '1--Yes', 'Tak'],
		['Q158_3', '2--No', 'Nie'],
		['Q158_4', '1--Yes', 'Tak'],
		['Q158_4', '2--No', 'Nie'],
		['Q160', '1--Yes', 'Tak'],
		['Q160', '2--No', 'Nie'],
		['Q165', '1--Yes', 'Tak'],
		['Q165', '2--No', 'Nie'],
		['Q166_1', '1--Yes', 'Tak'],
		['Q166_1', '2--No', 'Nie'],
		['Q166_2', '1--Yes', 'Tak'],
		['Q166_2', '2--No', 'Nie'],
		['Q166_3', '1--Yes', 'Tak'],
		['Q166_3', '2--No', 'Nie'],
		['Q166_4', '1--Yes', 'Tak'],
		['Q166_4', '2--No', 'Nie'],
		['Q200_1', '1--Yes', 'Tak'],
		['Q200_1', '2--No', 'Nie'],
		['Q200_2', '1--Yes', 'Tak'],
		['Q200_2', '2--No', 'Nie'],
		['Q200_3', '1--Yes', 'Tak'],
		['Q200_3', '2--No', 'Nie'],
		['Q200_4', '1--Yes', 'Tak'],
		['Q200_4', '2--No', 'Nie'],
		['Q200_5', '1--Yes', 'Tak'],
		['Q200_5', '2--No', 'Nie'],
		['Q200_6', '1--Yes', 'Tak'],
		['Q200_6', '2--No', 'Nie'],
		['Q200_7', '1--Yes', 'Tak'],
		['Q200_7', '2--No', 'Nie'],
		['Q200_8', '1--Yes', 'Tak'],
		['Q200_8', '2--No', 'Nie'],
		['Q200_9', '1--Yes', 'Tak'],
		['Q200_9', '2--No', 'Nie'],
		['Q201_1', '1--Yes', 'Tak'],
		['Q201_1', '2--No', 'Nie'],
		['Q201_2', '1--Yes', 'Tak'],
		['Q201_2', '2--No', 'Nie'],
		['Q201_3', '1--Yes', 'Tak'],
		['Q201_3', '2--No', 'Nie'],
		['Q201_4', '1--Yes', 'Tak'],
		['Q201_4', '2--No', 'Nie'],
		['Q201_5', '1--Yes', 'Tak'],
		['Q201_5', '2--No', 'Nie'],
		['Q201_6', '1--Yes', 'Tak'],
		['Q201_6', '2--No', 'Nie'],
		['Q201_7', '1--Yes', 'Tak'],
		['Q201_7', '2--No', 'Nie'],
		['Q202_1', '1--Yes', 'Tak'],
		['Q202_1', '2--No', 'Nie'],
		['Q202_10', '1--Yes', 'Tak'],
		['Q202_10', '2--No', 'Nie'],
		['Q202_11', '1--Yes', 'Tak'],
		['Q202_11', '2--No', 'Nie'],
		['Q202_12', '1--Yes', 'Tak'],
		['Q202_12', '2--No', 'Nie'],
		['Q202_13', '1--Yes', 'Tak'],
		['Q202_13', '2--No', 'Nie'],
		['Q202_14', '1--Yes', 'Tak'],
		['Q202_14', '2--No', 'Nie'],
		['Q202_15', '1--Yes', 'Tak'],
		['Q202_15', '2--No', 'Nie'],
		['Q202_2', '1--Yes', 'Tak'],
		['Q202_2', '2--No', 'Nie'],
		['Q202_3', '1--Yes', 'Tak'],
		['Q202_3', '2--No', 'Nie'],
		['Q202_4', '1--Yes', 'Tak'],
		['Q202_4', '2--No', 'Nie'],
		['Q202_5', '1--Yes', 'Tak'],
		['Q202_5', '2--No', 'Nie'],
		['Q202_6', '1--Yes', 'Tak'],
		['Q202_6', '2--No', 'Nie'],
		['Q202_7', '1--Yes', 'Tak'],
		['Q202_7', '2--No', 'Nie'],
		['Q202_8', '1--Yes', 'Tak'],
		['Q202_8', '2--No', 'Nie'],
		['Q202_9', '1--Yes', 'Tak'],
		['Q202_9', '2--No', 'Nie'],
		['Q250', '1--Yes', 'Tak'],
		['Q250', '2--No', 'Nie'],
		['Q251', '1--Conducted-mainly-by-internal-staff', 'Przeprowadzana głównie przez pracowników tej firmy do tego delegowanych'],
		['Q251', '2--Contracted-mainly-to-external-providers', 'Głównie zlecana na zewnątrz'],
		['Q251', '3--Both-about-equally', 'Oba sposoby mniej więcej po równo'],
		['Q252_1', '1--Yes', 'Tak'],
		['Q252_1', '2--No', 'Nie'],
		['Q252_2', '1--Yes', 'Tak'],
		['Q252_2', '2--No', 'Nie'],
		['Q252_3', '1--Yes', 'Tak'],
		['Q252_3', '2--No', 'Nie'],
		['Q252_4', '1--Yes', 'Tak'],
		['Q252_4', '2--No', 'Nie'],
		['Q252_5', '1--Yes', 'Tak'],
		['Q252_5', '2--No', 'Nie'],
		['Q252_6', '1--Yes', 'Tak'],
		['Q252_6', '2--No', 'Nie'],
		['Q254gr', '1--2010', '2010'],
		['Q254gr', '2--2011', '2011'],
		['Q254gr', '3--2012', '2012'],
		['Q254gr', '4--2013', '2013'],
		['Q254gr', '5--2014', '2014'],
		['Q254gr', '6--before-2010', 'przed 2010 r.'],
		['Q254gr', '7--don-t-know', 'Nie wie'],
		['Q255', '1--Yes', 'Tak'],
		['Q255', '2--No', 'Nie'],
		['Q256_1', '1--Yes', 'Tak'],
		['Q256_1', '2--No', 'Nie'],
		['Q256_2', '1--Yes', 'Tak'],
		['Q256_2', '2--No', 'Nie'],
		['Q256_3', '1--Yes', 'Tak'],
		['Q256_3', '2--No', 'Nie'],
		['Q256_4', '1--Yes', 'Tak'],
		['Q256_4', '2--No', 'Nie'],
		['Q256_5', '1--Yes', 'Tak'],
		['Q256_5', '2--No', 'Nie'],
		['Q258b', '1--Yes', 'Tak'],
		['Q258b', '2--No', 'Nie'],
		['Q258b', '3--That-depends-on-the-type-of-measures', 'To zależy od rodzaju działań'],
		['Q259', '1--Yes', 'Tak'],
		['Q259', '2--No', 'Nie'],
		['Q259', '3--There-are-conflicting-views-about-this', 'Opinie na ten temat są sprzeczne'],
		['Q261_1', '1--Yes', 'Tak'],
		['Q261_1', '2--No', 'Nie'],
		['Q261_2', '1--Yes', 'Tak'],
		['Q261_2', '2--No', 'Nie'],
		['Q261_3', '1--Yes', 'Tak'],
		['Q261_3', '2--No', 'Nie'],
		['Q261_4', '1--Yes', 'Tak'],
		['Q261_4', '2--No', 'Nie'],
		['Q264_1', '1--Major-reason', 'Główna przyczyna'],
		['Q264_1', '2--Minor-reason', 'Mniej ważna przyczyna'],
		['Q264_1', '3--Not-a-reason', 'To nie jest przyczyna'],
		['Q264_2', '1--Major-reason', 'Główna przyczyna'],
		['Q264_2', '2--Minor-reason', 'Mniej ważna przyczyna'],
		['Q264_2', '3--Not-a-reason', 'To nie jest przyczyna'],
		['Q264_4', '1--Major-reason', 'Główna przyczyna'],
		['Q264_4', '2--Minor-reason', 'Mniej ważna przyczyna'],
		['Q264_4', '3--Not-a-reason', 'To nie jest przyczyna'],
		['Q264_5', '1--Major-reason', 'Główna przyczyna'],
		['Q264_5', '2--Minor-reason', 'Mniej ważna przyczyna'],
		['Q264_5', '3--Not-a-reason', 'To nie jest przyczyna'],
		['Q264_6', '1--Major-reason', 'Główna przyczyna'],
		['Q264_6', '2--Minor-reason', 'Mniej ważna przyczyna'],
		['Q264_6', '3--Not-a-reason', 'To nie jest przyczyna'],
		['Q265_1', '1--Major-difficulty', 'Ważne utrudnienie'],
		['Q265_1', '2--Minor-difficulty', 'Mniej ważne utrudnienie'],
		['Q265_1', '3--Not-a-difficulty', 'Nie stanowi utrudnienia'],
		['Q265_2', '1--Major-difficulty', 'Ważne utrudnienie'],
		['Q265_2', '2--Minor-difficulty', 'Mniej ważne utrudnienie'],
		['Q265_2', '3--Not-a-difficulty', 'Nie stanowi utrudnienia'],
		['Q265_3', '1--Major-difficulty', 'Ważne utrudnienie'],
		['Q265_3', '2--Minor-difficulty', 'Mniej ważne utrudnienie'],
		['Q265_3', '3--Not-a-difficulty', 'Nie stanowi utrudnienia'],
		['Q265_4', '1--Major-difficulty', 'Ważne utrudnienie'],
		['Q265_4', '2--Minor-difficulty', 'Mniej ważne utrudnienie'],
		['Q265_4', '3--Not-a-difficulty', 'Nie stanowi utrudnienia'],
		['Q265_5', '1--Major-difficulty', 'Ważne utrudnienie'],
		['Q265_5', '2--Minor-difficulty', 'Mniej ważne utrudnienie'],
		['Q265_5', '3--Not-a-difficulty', 'Nie stanowi utrudnienia'],
		['Q265_6', '1--Major-difficulty', 'Ważne utrudnienie'],
		['Q265_6', '2--Minor-difficulty', 'Mniej ważne utrudnienie'],
		['Q265_6', '3--Not-a-difficulty', 'Nie stanowi utrudnienia'],
		['Q265_7', '1--Major-difficulty', 'Ważne utrudnienie'],
		['Q265_7', '2--Minor-difficulty', 'Mniej ważne utrudnienie'],
		['Q265_7', '3--Not-a-difficulty', 'Nie stanowi utrudnienia'],
		['Q300', '1--Yes', 'Tak'],
		['Q300', '2--No', 'Nie'],
		['Q301', '1--Yes', 'Tak'],
		['Q301', '2--No', 'Nie'],
		['Q302', '1--Yes', 'Tak'],
		['Q302', '2--No', 'Nie'],
		['Q303_1', '1--Yes', 'Tak'],
		['Q303_1', '2--No', 'Nie'],
		['Q303_2', '1--Yes', 'Tak'],
		['Q303_2', '2--No', 'Nie'],
		['Q303_3', '1--Yes', 'Tak'],
		['Q303_3', '2--No', 'Nie'],
		['Q303_4', '1--Yes', 'Tak'],
		['Q303_4', '2--No', 'Nie'],
		['Q304', '1--Yes', 'Tak'],
		['Q304', '2--No', 'Nie'],
		['Q304', '3--Partly', 'Częściowo'],
		['Q305', '1--Yes', 'Tak'],
		['Q305', '2--No', 'Nie'],
		['Q306a_3', '1--Yes', 'Tak'],
		['Q306a_3', '2--No', 'Nie'],
		['Q306a_4', '1--Yes', 'Tak'],
		['Q306a_4', '2--No', 'Nie'],
		['Q306a_5', '1--Yes', 'Tak'],
		['Q306a_5', '2--No', 'Nie'],
		['Q306a_6', '1--Yes', 'Tak'],
		['Q306a_6', '2--No', 'Nie'],
		['Q307', '1--Yes', 'Tak'],
		['Q307', '2--No', 'Nie'],
		['Q308_1', '1--Yes', 'Tak'],
		['Q308_1', '2--No', 'Nie'],
		['Q308_2', '1--Yes', 'Tak'],
		['Q308_2', '2--No', 'Nie'],
		['Q308_3', '1--Yes', 'Tak'],
		['Q308_3', '2--No', 'Nie'],
		['Q308_4', '1--Yes', 'Tak'],
		['Q308_4', '2--No', 'Nie'],
		['Q350', '1--Regularly', 'Regularnie'],
		['Q350', '2--Only-when-particular-issues-arise', 'Tylko wtedy, gdy pojawiają się konkretne problemy'],
		['Q350', '3--Not-at-all', 'Nigdy'],
		['Q351', '1--Often', 'Często'],
		['Q351', '2--Sometimes', 'Czasami'],
		['Q351', '3--Practically-never', 'Praktycznie nigdy'],
		['Q354', '1--Yes', 'Tak'],
		['Q354', '2--No', 'Nie'],
		['Q354', '3--Yes--but-only-some-of-them', 'Tak, ale tylko niektórzy z nich'],
		['Q356_1', '1--Yes', 'Tak'],
		['Q356_1', '2--No', 'Nie'],
		['Q356_2', '1--Yes', 'Tak'],
		['Q356_2', '2--No', 'Nie'],
		['Q356_3', '1--Yes', 'Tak'],
		['Q356_3', '2--No', 'Nie'],
		['Q356_4', '1--Yes', 'Tak'],
		['Q356_4', '2--No', 'Nie'],
		['Q356_5', '1--Yes', 'Tak'],
		['Q356_5', '2--No', 'Nie'],
		['Q358', '1--Yes', 'Tak'],
		['Q358', '2--No', 'Nie'],
		['Q358', '3--In-some-departments-only', 'Tylko w niektórych działach']
	];
var country_
	 = [
	
		['AL', 'Albania'],
		['AT', 'Austria'],
		['BE', 'Belgia'],
		['BG', 'Bułgaria'],
		['CH', 'Szwajcaria'],
		['CY', 'Cypr'],
		['CZ', 'Republika Czeska'],
		['DE', 'Niemcy'],
		['DK', 'Dania'],
		['EE', 'Estonia'],
		['EL', 'Grecja'],
		['ES', 'Hiszpania'],
		['FI', 'Finlandia'],
		['FR', 'Francja'],
		['HR', 'Chorwacja'],
		['HU', 'Węgry'],
		['IE', 'Irlandia'],
		['IS', 'Islandia'],
		['IT', 'Włochy'],
		['LT', 'Litwa'],
		['LU', 'Luksemburg'],
		['LV', 'Łotwa'],
		['ME', 'Czarnogóra'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Holandia'],
		['NO', 'Norwegia'],
		['PL', 'Polska'],
		['PT', 'Portugalia'],
		['RO', 'Rumunia'],
		['RS', 'Serbia'],
		['SE', 'Szwecja'],
		['SI', 'Słowenia'],
		['SK', 'Słowacja'],
		['TR', 'Turcja'],
		['UK', 'Zjednoczone Królestwo'],
		['EuropeanUnion', 'Unia Europejska']
	];
var question_meta
	 = [
	
		['Q200_1', 'Męczące lub bolesne pozycje, w tym siedzenie przez długi czas', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Męczące lub bolesne pozycje, w tym siedzenie przez długi czas<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_2', 'Podnoszenia lub przenoszenia ludzi lub znacznych ciężarów', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Podnoszenia lub przenoszenia ludzi lub znacznych ciężarów<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_3', 'Hałas', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Hałas<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_4', 'Powtarzające się ruchy dłoni lub ramion', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Powtarzające się ruchy dłoni lub ramion<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_5', 'Gorąco, zimno lub przeciąg', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Gorąco, zimno lub przeciąg<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_6', 'Ryzyko wypadków spowodowanych przez maszyny lub narzędzia ręczne ', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Ryzyko wypadków spowodowanych przez maszyny lub narzędzia ręczne <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_7', 'Ryzyko wypadków podczas pracy spowodowanych przez pojazdy, ale nie w drodze do pracy czy z pracy ', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Ryzyko wypadków podczas pracy spowodowanych przez pojazdy, ale nie w drodze do pracy czy z pracy <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_8', 'Substancje chemiczne lub biologiczne w postaci płynów, oparów lub pyłu ', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Substancje chemiczne lub biologiczne w postaci płynów, oparów lub pyłu <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_9', 'Zwiększone ryzyko poślizgnięcia, potknięcia lub upadku ', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Zwiększone ryzyko poślizgnięcia, potknięcia lub upadku <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q201_1', 'Presja czasu  ', 'Oprócz powyższych zagrożeń, istnieją również zagrożenia dla zdrowia wynikające ze sposobu organizacji pracy, z relacji społecznych w miejscu pracy lub z sytuacji ekonomicznej. Przy każdym z następujących czynników zagrożenia, proszę powiedzieć, czy występuje on w zakładzie? Presja czasu  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q201_2', 'Słaba komunikacja lub współpraca w organizacji  ', 'Oprócz powyższych zagrożeń, istnieją również zagrożenia dla zdrowia wynikające ze sposobu organizacji pracy, z relacji społecznych w miejscu pracy lub z sytuacji ekonomicznej. Przy każdym z następujących czynników zagrożenia, proszę powiedzieć, czy występuje on w zakładzie? Słaba komunikacja lub współpraca w organizacji  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q201_3', 'Brak wpływu pracowników na tempo pracy lub proces pracy  ', 'Oprócz powyższych zagrożeń, istnieją również zagrożenia dla zdrowia wynikające ze sposobu organizacji pracy, z relacji społecznych w miejscu pracy lub z sytuacji ekonomicznej. Przy każdym z następujących czynników zagrożenia, proszę powiedzieć, czy występuje on w zakładzie? Brak wpływu pracowników na tempo pracy lub proces pracy  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q201_4', 'Niepewność zatrudnienia  ', 'Oprócz powyższych zagrożeń, istnieją również zagrożenia dla zdrowia wynikające ze sposobu organizacji pracy, z relacji społecznych w miejscu pracy lub z sytuacji ekonomicznej. Przy każdym z następujących czynników zagrożenia, proszę powiedzieć, czy występuje on w zakładzie? Niepewność zatrudnienia  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q201_5', 'Praca z trudnymi klientami, pacjentami, uczniami etc.  ', 'Oprócz powyższych zagrożeń, istnieją również zagrożenia dla zdrowia wynikające ze sposobu organizacji pracy, z relacji społecznych w miejscu pracy lub z sytuacji ekonomicznej. Przy każdym z następujących czynników zagrożenia, proszę powiedzieć, czy występuje on w zakładzie? Praca z trudnymi klientami, pacjentami, uczniami etc.  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q201_6', 'Długie lub nieregularne godziny pracy  ', 'Oprócz powyższych zagrożeń, istnieją również zagrożenia dla zdrowia wynikające ze sposobu organizacji pracy, z relacji społecznych w miejscu pracy lub z sytuacji ekonomicznej. Przy każdym z następujących czynników zagrożenia, proszę powiedzieć, czy występuje on w zakładzie? Długie lub nieregularne godziny pracy  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q201_7', 'Dyskryminacja, na przykład ze względu na płeć, wiek lub pochodzenie etniczne', 'Oprócz powyższych zagrożeń, istnieją również zagrożenia dla zdrowia wynikające ze sposobu organizacji pracy, z relacji społecznych w miejscu pracy lub z sytuacji ekonomicznej. Przy każdym z następujących czynników zagrożenia, proszę powiedzieć, czy występuje on w zakładzie? Dyskryminacja, na przykład ze względu na płeć, wiek lub pochodzenie etniczne<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q250', 'Czy zakład regularnie przeprowadza ocenęryzyka zawodowego w miejscu pracy?', 'Czy zakład regularnie przeprowadza ocenęryzyka zawodowego w miejscu pracy?<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q251', 'Czy ocena ryzyka zawodowego w miejscu pracy jest przeprowadzana głównie przez pracowników tej firmy do tego delegowanych, czy też jest zlecana na zewnątrz?', 'Czy ocena ryzyka zawodowego w miejscu pracy jest przeprowadzana głównie przez pracowników tej firmy do tego delegowanych, czy też jest zlecana na zewnątrz?<br><br>(1) Przeprowadzana głównie przez pracowników tej firmy do tego delegowanych <br>(2) Głównie zlecana na zewnątrz <br>(3) Oba sposoby mniej więcej po równo <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym regularne przeprowadzanie ocen ryzyka zawodowego.'],
		['Q264_1', 'Spełnienie wymogów prawnych ', 'Z jakich głównie przyczyn zakład zajmuje się kwestiami BHP? Dla każdej z przyczyn proszę powiedzieć, czy jest to główna przyczyna, mniej ważna przyczyna, czy nie jest to wcale przyczyna. Spełnienie wymogów prawnych <br><br>(1) Główna przyczyna <br>(2) Mniej ważna przyczyna <br>(3) To nie jest przyczyna <br>(9) Brak odpowiedzi'],
		['Q264_2', 'Spełnienie oczekiwań pracowników lub ich przedstawicieli ', 'Z jakich głównie przyczyn zakład zajmuje się kwestiami BHP? Dla każdej z przyczyn proszę powiedzieć, czy jest to główna przyczyna, mniej ważna przyczyna, czy nie jest to wcale przyczyna. Spełnienie oczekiwań pracowników lub ich przedstawicieli <br><br>(1) Główna przyczyna <br>(2) Mniej ważna przyczyna <br>(3) To nie jest przyczyna <br>(9) Brak odpowiedzi'],
		['Q264_4', 'Utrzymanie lub zwiększenie produktywności', 'Z jakich głównie przyczyn zakład zajmuje się kwestiami BHP? Dla każdej z przyczyn proszę powiedzieć, czy jest to główna przyczyna, mniej ważna przyczyna, czy nie jest to wcale przyczyna. Utrzymanie lub zwiększenie produktywności<br><br>(1) Główna przyczyna <br>(2) Mniej ważna przyczyna <br>(3) To nie jest przyczyna <br>(9) Brak odpowiedzi'],
		['Q264_5', 'Utrzymanie reputacji organizacji ', 'Z jakich głównie przyczyn zakład zajmuje się kwestiami BHP? Dla każdej z przyczyn proszę powiedzieć, czy jest to główna przyczyna, mniej ważna przyczyna, czy nie jest to wcale przyczyna. Utrzymanie reputacji organizacji <br><br>(1) Główna przyczyna <br>(2) Mniej ważna przyczyna <br>(3) To nie jest przyczyna <br>(9) Brak odpowiedzi'],
		['Q264_6', 'Uniknięcie kar i sankcji ze strony Państwowej Inspekcji Pracy', 'Z jakich głównie przyczyn zakład zajmuje się kwestiami BHP? Dla każdej z przyczyn proszę powiedzieć, czy jest to główna przyczyna, mniej ważna przyczyna, czy nie jest to wcale przyczyna. Uniknięcie kar i sankcji ze strony Państwowej Inspekcji Pracy<br><br>(1) Główna przyczyna <br>(2) Mniej ważna przyczyna <br>(3) To nie jest przyczyna <br>(9) Brak odpowiedzi'],
		['Q307', 'Czy posiada Pan/Pani wystarczające informacje na temat tego, jak uwzględnić zagrożenia psychospołeczne w ocenie ryzyka?', 'Czy posiada Pan/Pani wystarczające informacje na temat tego, jak uwzględnić zagrożenia psychospołeczne w ocenie ryzyka?<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q150_1', 'Lekarz medycyny pracy', 'Z jakich usług w zakresie bezpieczeństwa i higieny pracy korzystasz (zarówno usługi zlecane na zewnątrz jak i dostępne na miejscu)? Lekarz medycyny pracy<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q150_2', 'Psycholog', 'Z jakich usług w zakresie bezpieczeństwa i higieny pracy korzystasz (zarówno usługi zlecane na zewnątrz jak i dostępne na miejscu)? Psycholog<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q150_3', 'Ekspert w zakresie projektowania ergonomicznego i planowania przestrzennego miejsc pracy', 'Z jakich usług w zakresie bezpieczeństwa i higieny pracy korzystasz (zarówno usługi zlecane na zewnątrz jak i dostępne na miejscu)? Ekspert w zakresie projektowania ergonomicznego i planowania przestrzennego miejsc pracy<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q150_4', 'Specjalista w zakresie bezpieczeństwa i higieny pracy', 'Z jakich usług w zakresie bezpieczeństwa i higieny pracy korzystasz (zarówno usługi zlecane na zewnątrz jak i dostępne na miejscu)? Specjalista w zakresie bezpieczeństwa i higieny pracy<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q150_5', 'Ekspert ds. zapobiegania wypadkom', 'Z jakich usług w zakresie bezpieczeństwa i higieny pracy korzystasz (zarówno usługi zlecane na zewnątrz jak i dostępne na miejscu)? Ekspert ds. zapobiegania wypadkom<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q155', 'Czy pracownicy zakładu mają dostęp do dokumentu wyjaśniającego obowiązki i procedury BHP?', 'Czy pracownicy zakładu mają dostęp do dokumentu wyjaśniającego obowiązki i procedury BHP?<br><br>(1) Tak <br>(2) Nie <br>(3) Tak, ale tylko niektóre grupy pradowników <br>(9) Brak odpowiedzi'],
		['Q156', 'Czy zakład posiada określony budżet roczny przeznaczony na środki i wyposażenie BHP?', 'Czy zakład posiada określony budżet roczny przeznaczony na środki i wyposażenie BHP?<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q158_1', 'Podnoszenie świadomości na temat zdrowego odżywiania', 'Czy zakład podejmuje któreś z wymienionych środków w celu promocji zdrowia wśród pracowników? Podnoszenie świadomości na temat zdrowego odżywiania<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q158_2', 'Podnoszenie świadomości na temat zapobiegania uzależnieniom, np. od papierosów, alkoholu lub narkotyków', 'Czy zakład podejmuje któreś z wymienionych środków w celu promocji zdrowia wśród pracowników? Podnoszenie świadomości na temat zapobiegania uzależnieniom, np. od papierosów, alkoholu lub narkotyków<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q158_3', 'Promowanie aktywności fizycznej poza godzinami pracy', 'Czy zakład podejmuje któreś z wymienionych środków w celu promocji zdrowia wśród pracowników? Promowanie aktywności fizycznej poza godzinami pracy<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q158_4', 'Promowanie ćwiczeń pleców, rozciągania i innych ćwiczeńw czasie pracy', 'Czy zakład podejmuje któreś z wymienionych środków w celu promocji zdrowia wśród pracowników? Promowanie ćwiczeń pleców, rozciągania i innych ćwiczeńw czasie pracy<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q160', 'Czy nieobecności z powodu choroby są rutynowo analizowane w celu polepszenia warunków pracy? ', 'Czy nieobecności z powodu choroby są rutynowo analizowane w celu polepszenia warunków pracy? <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q165', 'Czy w ciągu ostatnich 3 lat zakład był wizytowany przez Państwową Inspekcję Pracy w celu sprawdzenia warunków BHP?', 'Czy w ciągu ostatnich 3 lat zakład był wizytowany przez Państwową Inspekcję Pracy w celu sprawdzenia warunków BHP?<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_1', 'Męczące lub bolesne pozycje, w tym siedzenie przez długi czas', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Męczące lub bolesne pozycje, w tym siedzenie przez długi czas<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_2', 'Podnoszenia lub przenoszenia ludzi lub znacznych ciężarów', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Podnoszenia lub przenoszenia ludzi lub znacznych ciężarów<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_3', 'Hałas', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Hałas<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_4', 'Powtarzające się ruchy dłoni lub ramion', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Powtarzające się ruchy dłoni lub ramion<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_5', 'Gorąco, zimno lub przeciąg', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Gorąco, zimno lub przeciąg<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_6', 'Ryzyko wypadków spowodowanych przez maszyny lub narzędzia ręczne ', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Ryzyko wypadków spowodowanych przez maszyny lub narzędzia ręczne <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_7', 'Ryzyko wypadków podczas pracy spowodowanych przez pojazdy, ale nie w drodze do pracy czy z pracy ', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Ryzyko wypadków podczas pracy spowodowanych przez pojazdy, ale nie w drodze do pracy czy z pracy <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_8', 'Substancje chemiczne lub biologiczne w postaci płynów, oparów lub pyłu ', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Substancje chemiczne lub biologiczne w postaci płynów, oparów lub pyłu <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q200_9', 'Zwiększone ryzyko poślizgnięcia, potknięcia lub upadku ', 'Różne rodzaje pracy pociągają za sobą różne rodzaje zagrożeń. Przy każdym czynniku zagrożenia, proszę powiedzieć, czy występuje w zakładzie - niezależnie od tego, czy jest on obecnie objęty kontrolą i niezależnie od liczby pracowników, których dotyczy. Zwiększone ryzyko poślizgnięcia, potknięcia lub upadku <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q202_1', 'Męczące lub bolesne pozycje, w tym siedzenie przez długi czas', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Męczące lub bolesne pozycje, w tym siedzenie przez długi czas<br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie danego czynnika ryzyka.'],
		['Q202_2', 'Podnoszenia lub przenoszenia ludzi lub znacznych ciężarów', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Podnoszenia lub przenoszenia ludzi lub znacznych ciężarów<br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie danego czynnika ryzyka.'],
		['Q202_3', 'Hałas', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Hałas<br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie danego czynnika ryzyka.'],
		['Q202_4', 'Powtarzające się ruchy dłoni lub ramion', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Powtarzające się ruchy dłoni lub ramion<br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie danego czynnika ryzyka.'],
		['Q202_5', 'Gorąco, zimno lub przeciąg', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Gorąco, zimno lub przeciąg<br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie danego czynnika ryzyka.'],
		['Q202_6', 'Ryzyko wypadków spowodowanych przez maszyny lub narzędzia ręczne ', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Ryzyko wypadków spowodowanych przez maszyny lub narzędzia ręczne <br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie danego czynnika ryzyka.'],
		['Q202_7', 'Ryzyko wypadków podczas pracy spowodowanych przez pojazdy, ale nie w drodze do pracy czy z pracy ', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Ryzyko wypadków podczas pracy spowodowanych przez pojazdy, ale nie w drodze do pracy czy z pracy <br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie danego czynnika ryzyka.'],
		['Q202_8', 'Substancje chemiczne lub biologiczne w postaci płynów, oparów lub pyłu ', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Substancje chemiczne lub biologiczne w postaci płynów, oparów lub pyłu <br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie danego czynnika ryzyka.'],
		['Q202_9', 'Zwiększone ryzyko poślizgnięcia, potknięcia lub upadku ', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Zwiększone ryzyko poślizgnięcia, potknięcia lub upadku <br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie danego czynnika ryzyka.'],
		['Q250', 'Czy zakład regularnie przeprowadza ocenęryzyka zawodowego w miejscu pracy?', 'Czy zakład regularnie przeprowadza ocenęryzyka zawodowego w miejscu pracy?<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q251', 'Czy ocena ryzyka zawodowego w miejscu pracy jest przeprowadzana głównie przez pracowników tej firmy do tego delegowanych, czy też jest zlecana na zewnątrz?', 'Czy ocena ryzyka zawodowego w miejscu pracy jest przeprowadzana głównie przez pracowników tej firmy do tego delegowanych, czy też jest zlecana na zewnątrz?<br><br>(1) Przeprowadzana głównie przez pracowników tej firmy do tego delegowanych <br>(2) Głównie zlecana na zewnątrz <br>(3) Oba sposoby mniej więcej po równo <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym regularne przeprowadzanie ocen ryzyka zawodowego.'],
		['Q252_1', 'Bezpieczeństwo maszyn, urządzeń i instalacji  ', 'Które z poniższych aspektów podlegają rutynowej ocenie ryzyka zawodowego w miejscu pracy? Bezpieczeństwo maszyn, urządzeń i instalacji  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym regularne przeprowadzanie ocen ryzyka zawodowego.'],
		['Q252_2', 'Niebezpieczne substancje chemiczne lub biologiczne ', 'Które z poniższych aspektów podlegają rutynowej ocenie ryzyka zawodowego w miejscu pracy? Niebezpieczne substancje chemiczne lub biologiczne <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym regularne przeprowadzanie ocen ryzyka zawodowego.'],
		['Q252_3', 'Postawa w czasie pracy, wymagania fizyczne i powtarzające się ruchy ', 'Które z poniższych aspektów podlegają rutynowej ocenie ryzyka zawodowego w miejscu pracy? Postawa w czasie pracy, wymagania fizyczne i powtarzające się ruchy <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym regularne przeprowadzanie ocen ryzyka zawodowego.'],
		['Q252_4', 'Narażenie na hałas, wibracje, gorąco lub zimno  ', 'Które z poniższych aspektów podlegają rutynowej ocenie ryzyka zawodowego w miejscu pracy? Narażenie na hałas, wibracje, gorąco lub zimno  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym regularne przeprowadzanie ocen ryzyka zawodowego.'],
		['Q252_5', 'Relacje między kierownictwem a pracownikami  ', 'Które z poniższych aspektów podlegają rutynowej ocenie ryzyka zawodowego w miejscu pracy? Relacje między kierownictwem a pracownikami  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym regularne przeprowadzanie ocen ryzyka zawodowego.'],
		['Q252_6', 'Aspekty organizacyjne, takie jak harmonogram pracy, przerwy i zmiany', 'Które z poniższych aspektów podlegają rutynowej ocenie ryzyka zawodowego w miejscu pracy? Aspekty organizacyjne, takie jak harmonogram pracy, przerwy i zmiany<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym regularne przeprowadzanie ocen ryzyka zawodowego.'],
		['Q254gr', 'W którym roku po raz ostatni przeprowadzono w zakładzie ocenę ryzyka zawodowego?', 'W którym roku po raz ostatni przeprowadzono w zakładzie ocenę ryzyka zawodowego?<br><br>(Rok) <br>(9998) Nie wie <br>(9999) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym regularne przeprowadzanie ocen ryzyka zawodowego.'],
		['Q255', 'Czy zostało to udokumentowane w formie pisemnej?', 'Czy zostało to udokumentowane w formie pisemnej?<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym przeprowadzenie oceny ryzyka zawodowego w miejscu pracy po raz ostatni po 1970 r.'],
		['Q256_1', 'Zarządowi  ', 'Komu zostały przedstawione wnioski z oceny ryzyka zawodowego w miejscu pracy? Zarządowi  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym przeprowadzenie oceny ryzyka zawodowego w miejscu pracy po raz ostatni po 1970 r.'],
		['Q256_2', 'Społecznym inspektorom pracy  ', 'Komu zostały przedstawione wnioski z oceny ryzyka zawodowego w miejscu pracy? Społecznym inspektorom pracy  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytanie zadawane zakładom pracy deklarującym przeprowadzenie oceny ryzyka po raz ostatni po 1970 i posiadanie przedstawiciela pracowników ds. BHP, np. społecznego inspektora pracy.'],
		['Q256_3', 'Radzie pracowników  ', 'Komu zostały przedstawione wnioski z oceny ryzyka zawodowego w miejscu pracy? Radzie pracowników  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytanie zadawane zakładom pracy deklarującym przeprowadzenie oceny ryzyka po raz ostatni po 1970 r. i posiadanie rady pracowników.'],
		['Q256_4', 'Zakładowej organizacji związkowej  ', 'Komu zostały przedstawione wnioski z oceny ryzyka zawodowego w miejscu pracy? Zakładowej organizacji związkowej  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytanie zadawane zakładom pracy deklarującym przeprowadzenie oceny ryzyka po raz ostatni po 1970 r. i posiadanie zakładowej organizacji związkowej.'],
		['Q256_5', 'Pracownikom  ', 'Komu zostały przedstawione wnioski z oceny ryzyka zawodowego w miejscu pracy? Pracownikom  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym przeprowadzenie oceny ryzyka zawodowego w miejscu pracy po raz ostatni po 1970 r.'],
		['Q259', 'Czy ocena ryzyka zawodowego w zakładzie jest postrzegana jako pożyteczny sposób zarządzania kwestiami bezpieczeństwa i higieny pracy?', 'Czy ocena ryzyka zawodowego w zakładzie jest postrzegana jako pożyteczny sposób zarządzania kwestiami bezpieczeństwa i higieny pracy?<br><br>(1) Tak <br>(2) Nie <br>(3) Opinie na ten temat są sprzeczne <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym regularne przeprowadzanie ocen ryzyka zawodowego.'],
		['Q261_1', 'zagrożenia i tak są wszystkim znane  ', 'Czy są jakieś szczególne powody, dla których ocena ryzyka zawodowego w zakładzie nie jest regularnie przeprowadzana? Przy każdej z wymienionych opcji proszę powiedzieć, czy odnosi się ona do zakładu? zagrożenia i tak są wszystkim znane  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy niezgłaszającym regularnego przeprowadzania ocen ryzyka zawodowego.'],
		['Q261_2', 'nie ma większych problemów  ', 'Czy są jakieś szczególne powody, dla których ocena ryzyka zawodowego w zakładzie nie jest regularnie przeprowadzana? Przy każdej z wymienionych opcji proszę powiedzieć, czy odnosi się ona do zakładu? nie ma większych problemów  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy niezgłaszającym regularnego przeprowadzania ocen ryzyka zawodowego.'],
		['Q261_3', 'procedura jest zbyt uciążliwa  ', 'Czy są jakieś szczególne powody, dla których ocena ryzyka zawodowego w zakładzie nie jest regularnie przeprowadzana? Przy każdej z wymienionych opcji proszę powiedzieć, czy odnosi się ona do zakładu? procedura jest zbyt uciążliwa  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy niezgłaszającym regularnego przeprowadzania ocen ryzyka zawodowego.'],
		['Q261_4', 'brakuje niezbędnej wiedzy fachowej', 'Czy są jakieś szczególne powody, dla których ocena ryzyka zawodowego w zakładzie nie jest regularnie przeprowadzana? Przy każdej z wymienionych opcji proszę powiedzieć, czy odnosi się ona do zakładu? brakuje niezbędnej wiedzy fachowej<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy niezgłaszającym regularnego przeprowadzania ocen ryzyka zawodowego.'],
		['Q308_1', 'Sprzęt do pomocy przy podnoszeniu i przenoszeniu ciężarów lub wykonywaniu innych ciężkich prac fizycznych ', 'A teraz na temat problemów układu mięśniowo-szkieletowego, takich jak bóle pleców, szyi, ramion, rąk i nóg. Czy w zakładzie stosowane są któreś z tych środków zapobiegawczych? Sprzęt do pomocy przy podnoszeniu i przenoszeniu ciężarów lub wykonywaniu innych ciężkich prac fizycznych <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytanie zadawane zakładom pracy zgłaszającym jako czynnik ryzyka podnoszenie lub przenoszenie ludzi lub znacznych ciężarów.'],
		['Q308_2', 'Rotacja zadań w celu ograniczenia powtarzających się ruchów lub wysiłku fizycznego ', 'A teraz na temat problemów układu mięśniowo-szkieletowego, takich jak bóle pleców, szyi, ramion, rąk i nóg. Czy w zakładzie stosowane są któreś z tych środków zapobiegawczych? Rotacja zadań w celu ograniczenia powtarzających się ruchów lub wysiłku fizycznego <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytanie zadawane zakładom pracy zgłaszającym jako czynnik ryzyka powtarzające się ruchy dłoni lub ramion.'],
		['Q308_3', 'Zachęcanie osób pracujących w niewygodnych lub statycznych pozycjach, w tym długotrwałego siedzenia, do regularnych przerw ', 'A teraz na temat problemów układu mięśniowo-szkieletowego, takich jak bóle pleców, szyi, ramion, rąk i nóg. Czy w zakładzie stosowane są któreś z tych środków zapobiegawczych? Zachęcanie osób pracujących w niewygodnych lub statycznych pozycjach, w tym długotrwałego siedzenia, do regularnych przerw <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q308_4', 'Zapewnienie ergonomicznego sprzętu, takiego jak specjalne krzesła czy biurka ', 'A teraz na temat problemów układu mięśniowo-szkieletowego, takich jak bóle pleców, szyi, ramion, rąk i nóg. Czy w zakładzie stosowane są któreś z tych środków zapobiegawczych? Zapewnienie ergonomicznego sprzętu, takiego jak specjalne krzesła czy biurka <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q356_1', 'Prawidłowe użytkowanie i dostosowanie wyposażenia i mebli do pracy ', 'Na które z wymienionych tematów zakład organizuje szkolenia dla pracowników? Prawidłowe użytkowanie i dostosowanie wyposażenia i mebli do pracy <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q356_2', 'Używanie niebezpiecznych substancji', 'Na które z wymienionych tematów zakład organizuje szkolenia dla pracowników? Używanie niebezpiecznych substancji<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q356_3', 'Zapobieganie zagrożeniom psychospołecznym, takim jak stres czy mobbing ', 'Na które z wymienionych tematów zakład organizuje szkolenia dla pracowników? Zapobieganie zagrożeniom psychospołecznym, takim jak stres czy mobbing <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q356_4', 'Sposoby podnoszenia i przenoszenia znacznych ciężarów lub osób ', 'Na które z wymienionych tematów zakład organizuje szkolenia dla pracowników? Sposoby podnoszenia i przenoszenia znacznych ciężarów lub osób <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q356_5', 'Procedury w sytuacjach awaryjnych', 'Na które z wymienionych tematów zakład organizuje szkolenia dla pracowników? Procedury w sytuacjach awaryjnych<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q201_1', 'Presja czasu  ', 'Oprócz powyższych zagrożeń, istnieją również zagrożenia dla zdrowia wynikające ze sposobu organizacji pracy, z relacji społecznych w miejscu pracy lub z sytuacji ekonomicznej. Przy każdym z następujących czynników zagrożenia, proszę powiedzieć, czy występuje on w zakładzie? Presja czasu  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q201_2', 'Słaba komunikacja lub współpraca w organizacji  ', 'Oprócz powyższych zagrożeń, istnieją również zagrożenia dla zdrowia wynikające ze sposobu organizacji pracy, z relacji społecznych w miejscu pracy lub z sytuacji ekonomicznej. Przy każdym z następujących czynników zagrożenia, proszę powiedzieć, czy występuje on w zakładzie? Słaba komunikacja lub współpraca w organizacji  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q201_3', 'Brak wpływu pracowników na tempo pracy lub proces pracy  ', 'Oprócz powyższych zagrożeń, istnieją również zagrożenia dla zdrowia wynikające ze sposobu organizacji pracy, z relacji społecznych w miejscu pracy lub z sytuacji ekonomicznej. Przy każdym z następujących czynników zagrożenia, proszę powiedzieć, czy występuje on w zakładzie? Brak wpływu pracowników na tempo pracy lub proces pracy  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q201_4', 'Niepewność zatrudnienia  ', 'Oprócz powyższych zagrożeń, istnieją również zagrożenia dla zdrowia wynikające ze sposobu organizacji pracy, z relacji społecznych w miejscu pracy lub z sytuacji ekonomicznej. Przy każdym z następujących czynników zagrożenia, proszę powiedzieć, czy występuje on w zakładzie? Niepewność zatrudnienia  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q201_5', 'Praca z trudnymi klientami, pacjentami, uczniami etc.  ', 'Oprócz powyższych zagrożeń, istnieją również zagrożenia dla zdrowia wynikające ze sposobu organizacji pracy, z relacji społecznych w miejscu pracy lub z sytuacji ekonomicznej. Przy każdym z następujących czynników zagrożenia, proszę powiedzieć, czy występuje on w zakładzie? Praca z trudnymi klientami, pacjentami, uczniami etc.  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q201_6', 'Długie lub nieregularne godziny pracy  ', 'Oprócz powyższych zagrożeń, istnieją również zagrożenia dla zdrowia wynikające ze sposobu organizacji pracy, z relacji społecznych w miejscu pracy lub z sytuacji ekonomicznej. Przy każdym z następujących czynników zagrożenia, proszę powiedzieć, czy występuje on w zakładzie? Długie lub nieregularne godziny pracy  <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q201_7', 'Dyskryminacja, na przykład ze względu na płeć, wiek lub pochodzenie etniczne', 'Oprócz powyższych zagrożeń, istnieją również zagrożenia dla zdrowia wynikające ze sposobu organizacji pracy, z relacji społecznych w miejscu pracy lub z sytuacji ekonomicznej. Przy każdym z następujących czynników zagrożenia, proszę powiedzieć, czy występuje on w zakładzie? Dyskryminacja, na przykład ze względu na płeć, wiek lub pochodzenie etniczne<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q202_10', 'Presja czasu  ', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Presja czasu  <br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie tego czynnika ryzyka psychospołecznego.'],
		['Q202_11', 'Słaba komunikacja lub współpraca w organizacji  ', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Słaba komunikacja lub współpraca w organizacji  <br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie tego czynnika ryzyka psychospołecznego.'],
		['Q202_12', 'Brak wpływu pracowników na tempo pracy lub proces pracy  ', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Brak wpływu pracowników na tempo pracy lub proces pracy  <br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie tego czynnika ryzyka psychospołecznego.'],
		['Q202_13', 'Niepewność zatrudnienia  ', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Niepewność zatrudnienia  <br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie tego czynnika ryzyka psychospołecznego.'],
		['Q202_14', 'Praca z trudnymi klientami, pacjentami, uczniami etc.  ', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Praca z trudnymi klientami, pacjentami, uczniami etc.  <br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie tego czynnika ryzyka psychospołecznego.'],
		['Q202_15', 'Długie lub nieregularne godziny pracy  ', 'Odnośnie którego z zagrożeń (o ile istnieją takie zagrożenia) brakuje w zakładzie informacji lub odpowiednich narzędzi prewencyjnych umożliwiających skuteczne działania Długie lub nieregularne godziny pracy  <br><br>(1) Tak <br>(2) Nie<br><br>Pytanie zadawane zakładom pracy zgłaszającym występowanie tego czynnika ryzyka psychospołecznego.'],
		['Q300', 'Czy zakład posiada plan zapobiegania stresowi związanemu z pracą?', 'Czy zakład posiada plan zapobiegania stresowi związanemu z pracą?<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania skierowane do zakładów zatrudniających co najmniej 20 pracowników'],
		['Q301', 'Czy istnieje procedura postępowania na wypadek mobbingu lub molestowania?', 'Czy istnieje procedura postępowania na wypadek mobbingu lub molestowania?<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania skierowane do zakładów zatrudniających co najmniej 20 pracowników'],
		['Q302', 'Czy istnieje procedura postępowania na wypadek gróźb, wykorzystywania czy napaści ze strony klientów, pacjentów, uczniów czy innych osób z zewnątrz?', 'Czy istnieje procedura postępowania na wypadek gróźb, wykorzystywania czy napaści ze strony klientów, pacjentów, uczniów czy innych osób z zewnątrz?<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zatrudniającym co najmniej 20 pracowników i zgłaszającym jako czynnik ryzyka konieczność pracy z trudnymi klientami, pacjentami, uczniami.'],
		['Q303_1', 'Reorganizacja pracy w celu zmniejszenia wymagań i presji ', 'Czy w przeciągu ostatnich 3 lat zakład zastosował któreś z następujących działań w celu zapobiegania zagrożeniom psychospołecznym? Reorganizacja pracy w celu zmniejszenia wymagań i presji <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q303_2', 'Poufne doradztwo dla pracowników ', 'Czy w przeciągu ostatnich 3 lat zakład zastosował któreś z następujących działań w celu zapobiegania zagrożeniom psychospołecznym? Poufne doradztwo dla pracowników <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q303_3', 'Ustanowienie procedury rozwiązywania konfliktów ', 'Czy w przeciągu ostatnich 3 lat zakład zastosował któreś z następujących działań w celu zapobiegania zagrożeniom psychospołecznym? Ustanowienie procedury rozwiązywania konfliktów <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q303_4', 'Interwencja w przypadku zbyt długich lub nieregularnych godzin pracy ', 'Czy w przeciągu ostatnich 3 lat zakład zastosował któreś z następujących działań w celu zapobiegania zagrożeniom psychospołecznym? Interwencja w przypadku zbyt długich lub nieregularnych godzin pracy <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q307', 'Czy posiada Pan/Pani wystarczające informacje na temat tego, jak uwzględnić zagrożenia psychospołeczne w ocenie ryzyka?', 'Czy posiada Pan/Pani wystarczające informacje na temat tego, jak uwzględnić zagrożenia psychospołeczne w ocenie ryzyka?<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi'],
		['Q264_1', 'Spełnienie wymogów prawnych ', 'Z jakich głównie przyczyn zakład zajmuje się kwestiami BHP? Dla każdej z przyczyn proszę powiedzieć, czy jest to główna przyczyna, mniej ważna przyczyna, czy nie jest to wcale przyczyna. Spełnienie wymogów prawnych <br><br>(1) Główna przyczyna <br>(2) Mniej ważna przyczyna <br>(3) To nie jest przyczyna <br>(9) Brak odpowiedzi'],
		['Q264_2', 'Spełnienie oczekiwań pracowników lub ich przedstawicieli ', 'Z jakich głównie przyczyn zakład zajmuje się kwestiami BHP? Dla każdej z przyczyn proszę powiedzieć, czy jest to główna przyczyna, mniej ważna przyczyna, czy nie jest to wcale przyczyna. Spełnienie oczekiwań pracowników lub ich przedstawicieli <br><br>(1) Główna przyczyna <br>(2) Mniej ważna przyczyna <br>(3) To nie jest przyczyna <br>(9) Brak odpowiedzi'],
		['Q264_4', 'Utrzymanie lub zwiększenie produktywności', 'Z jakich głównie przyczyn zakład zajmuje się kwestiami BHP? Dla każdej z przyczyn proszę powiedzieć, czy jest to główna przyczyna, mniej ważna przyczyna, czy nie jest to wcale przyczyna. Utrzymanie lub zwiększenie produktywności<br><br>(1) Główna przyczyna <br>(2) Mniej ważna przyczyna <br>(3) To nie jest przyczyna <br>(9) Brak odpowiedzi'],
		['Q264_5', 'Utrzymanie reputacji organizacji ', 'Z jakich głównie przyczyn zakład zajmuje się kwestiami BHP? Dla każdej z przyczyn proszę powiedzieć, czy jest to główna przyczyna, mniej ważna przyczyna, czy nie jest to wcale przyczyna. Utrzymanie reputacji organizacji <br><br>(1) Główna przyczyna <br>(2) Mniej ważna przyczyna <br>(3) To nie jest przyczyna <br>(9) Brak odpowiedzi'],
		['Q264_6', 'Uniknięcie kar i sankcji ze strony Państwowej Inspekcji Pracy', 'Z jakich głównie przyczyn zakład zajmuje się kwestiami BHP? Dla każdej z przyczyn proszę powiedzieć, czy jest to główna przyczyna, mniej ważna przyczyna, czy nie jest to wcale przyczyna. Uniknięcie kar i sankcji ze strony Państwowej Inspekcji Pracy<br><br>(1) Główna przyczyna <br>(2) Mniej ważna przyczyna <br>(3) To nie jest przyczyna <br>(9) Brak odpowiedzi'],
		['Q265_1', 'Brak czasu lub personelu ', 'Co najbardziej utrudnia zajmowanie się kwestiami BHP w zakładzie? Przy każdej z wymienionych opcji, proszę powiedzieć, czy jest to ważne utrudnienie, mniej ważne utrudnienie, czy to nie stanowi utrudnienia. Brak czasu lub personelu <br><br>(1) Ważne utrudnienie <br>(2) Mniej ważne utrudnienie <br>(3) Nie stanowi utrudnienia <br>(9) Brak odpowiedzi'],
		['Q265_2', 'Brak pieniędzy', 'Co najbardziej utrudnia zajmowanie się kwestiami BHP w zakładzie? Przy każdej z wymienionych opcji, proszę powiedzieć, czy jest to ważne utrudnienie, mniej ważne utrudnienie, czy to nie stanowi utrudnienia. Brak pieniędzy<br><br>(1) Ważne utrudnienie <br>(2) Mniej ważne utrudnienie <br>(3) Nie stanowi utrudnienia <br>(9) Brak odpowiedzi'],
		['Q265_3', 'Brak świadomości na temat tych kwestii wśród pracowników ', 'Co najbardziej utrudnia zajmowanie się kwestiami BHP w zakładzie? Przy każdej z wymienionych opcji, proszę powiedzieć, czy jest to ważne utrudnienie, mniej ważne utrudnienie, czy to nie stanowi utrudnienia. Brak świadomości na temat tych kwestii wśród pracowników <br><br>(1) Ważne utrudnienie <br>(2) Mniej ważne utrudnienie <br>(3) Nie stanowi utrudnienia <br>(9) Brak odpowiedzi'],
		['Q265_4', 'Brak świadomości na temat tych kwestii wśród zarządu ', 'Co najbardziej utrudnia zajmowanie się kwestiami BHP w zakładzie? Przy każdej z wymienionych opcji, proszę powiedzieć, czy jest to ważne utrudnienie, mniej ważne utrudnienie, czy to nie stanowi utrudnienia. Brak świadomości na temat tych kwestii wśród zarządu <br><br>(1) Ważne utrudnienie <br>(2) Mniej ważne utrudnienie <br>(3) Nie stanowi utrudnienia <br>(9) Brak odpowiedzi'],
		['Q265_5', 'Brak specjalistycznej wiedzy lub pomocy ', 'Co najbardziej utrudnia zajmowanie się kwestiami BHP w zakładzie? Przy każdej z wymienionych opcji, proszę powiedzieć, czy jest to ważne utrudnienie, mniej ważne utrudnienie, czy to nie stanowi utrudnienia. Brak specjalistycznej wiedzy lub pomocy <br><br>(1) Ważne utrudnienie <br>(2) Mniej ważne utrudnienie <br>(3) Nie stanowi utrudnienia <br>(9) Brak odpowiedzi'],
		['Q265_6', 'Biurokracja ', 'Co najbardziej utrudnia zajmowanie się kwestiami BHP w zakładzie? Przy każdej z wymienionych opcji, proszę powiedzieć, czy jest to ważne utrudnienie, mniej ważne utrudnienie, czy to nie stanowi utrudnienia. Biurokracja <br><br>(1) Ważne utrudnienie <br>(2) Mniej ważne utrudnienie <br>(3) Nie stanowi utrudnienia <br>(9) Brak odpowiedzi'],
		['Q265_7', 'Złożoność wymogów prawnych', 'Co najbardziej utrudnia zajmowanie się kwestiami BHP w zakładzie? Przy każdej z wymienionych opcji, proszę powiedzieć, czy jest to ważne utrudnienie, mniej ważne utrudnienie, czy to nie stanowi utrudnienia. Złożoność wymogów prawnych<br><br>(1) Ważne utrudnienie <br>(2) Mniej ważne utrudnienie <br>(3) Nie stanowi utrudnienia <br>(9) Brak odpowiedzi'],
		['Q304', 'Czy podjęte działania zostały podjęte w wyniku wystąpienia konkretnych wypadków stresu, mobbingu, molestowania, czy przemocy w zakładzie?', 'Czy podjęte działania zostały podjęte w wyniku wystąpienia konkretnych wypadków stresu, mobbingu, molestowania, czy przemocy w zakładzie?<br><br>(1) Tak <br>(2) Nie <br>(8) Częściowo <br>(9) Brak odpowiedzi<br><br>Pytanie zadawane zakładom pracy zgłaszającym stosowanie dowolnego działania w celu zapobiegania zagrożeniom psychospołecznym w przeciągu ostatnich trzech lat.'],
		['Q306a_3', 'Brak świadomości na temat tych kwestii wśród personelu ', 'Biorąc pod uwagę sytuację w zakładzie: Czy którykolwiek z następujących czynników powoduje, że działania skierowane przeciw zagrożeniom psychospołecznym są trudniejsze niż działania skierowane przeciw innym zagrożeniom dla zdrowia? Brak świadomości na temat tych kwestii wśród personelu <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym występowanie jednego z wymienionych czynników ryzyka psychospołecznego.'],
		['Q306a_4', 'Brak świadomości na temat tych kwestii wśród zarządu ', 'Biorąc pod uwagę sytuację w zakładzie: Czy którykolwiek z następujących czynników powoduje, że działania skierowane przeciw zagrożeniom psychospołecznym są trudniejsze niż działania skierowane przeciw innym zagrożeniom dla zdrowia? Brak świadomości na temat tych kwestii wśród zarządu <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym występowanie jednego z wymienionych czynników ryzyka psychospołecznego.'],
		['Q306a_5', 'Brak specjalistycznej wiedzy lub pomocy ', 'Biorąc pod uwagę sytuację w zakładzie: Czy którykolwiek z następujących czynników powoduje, że działania skierowane przeciw zagrożeniom psychospołecznym są trudniejsze niż działania skierowane przeciw innym zagrożeniom dla zdrowia? Brak specjalistycznej wiedzy lub pomocy <br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym występowanie jednego z wymienionych czynników ryzyka psychospołecznego.'],
		['Q306a_6', 'Niechęć do mówienia otwarcie o tych zagadnieniach', 'Biorąc pod uwagę sytuację w zakładzie: Czy którykolwiek z następujących czynników powoduje, że działania skierowane przeciw zagrożeniom psychospołecznym są trudniejsze niż działania skierowane przeciw innym zagrożeniom dla zdrowia? Niechęć do mówienia otwarcie o tych zagadnieniach<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym występowanie jednego z wymienionych czynników ryzyka psychospołecznego.'],
		['Q166_1', 'Rada pracowników', 'Która z następujących form reprezentacji pracowników istnieje w zakładzie? Rada pracowników<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytanie zadawane wszystkim; wielkość zależy od progów krajowych przyjętych dla podmiotów.'],
		['Q166_2', 'Zakładowa organizacja związkowa', 'Która z następujących form reprezentacji pracowników istnieje w zakładzie? Zakładowa organizacja związkowa<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytanie zadawane wszystkim; wielkość zależy od progów krajowych przyjętych dla podmiotów.'],
		['Q166_3', 'Przedstawiciel pracowników ds. BHP np. Społeczny inspektor pracy', 'Która z następujących form reprezentacji pracowników istnieje w zakładzie? Przedstawiciel pracowników ds. BHP np. Społeczny inspektor pracy<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytanie zadawane wszystkim; wielkość zależy od progów krajowych przyjętych dla podmiotów.'],
		['Q166_4', 'Komisja BHP', 'Która z następujących form reprezentacji pracowników istnieje w zakładzie? Komisja BHP<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytanie zadawane wszystkim; wielkość zależy od progów krajowych przyjętych dla podmiotów.'],
		['Q258b', 'Jeśli działania mają być podjęte w następstwie przeprowadzonej oceny ryzyka zawodowego: Czy pracownicy zazwyczaj w jakikolwiek sposób uczestniczą w ich planowaniu i wdrażaniu?', 'Jeśli działania mają być podjęte w następstwie przeprowadzonej oceny ryzyka zawodowego: Czy pracownicy zazwyczaj w jakikolwiek sposób uczestniczą w ich planowaniu i wdrażaniu?<br><br>(1) Tak <br>(2) Nie <br>(4) To zależy od rodzaju działań <br>(9) Brak odpowiedzi<br><br>Pytania zadawane zakładom pracy zgłaszającym regularne przeprowadzanie ocen ryzyka zawodowego.'],
		['Q305', 'Czy pracownicy brali udział w planowaniu i wdrazaniu środków przeciw zagrożeniom psychospołecznym?', 'Czy pracownicy brali udział w planowaniu i wdrazaniu środków przeciw zagrożeniom psychospołecznym?<br><br>(1) Tak <br>(2) Nie <br>(9) Brak odpowiedzi<br><br>Pytanie zadawane zakładom pracy zgłaszającym stosowanie dowolnego działania w celu zapobiegania zagrożeniom psychospołecznym w przeciągu ostatnich trzech lat.'],
		['Q350', 'Jak często BHP jest przedmiotem dyskusji między przedstawicielami pracowników a zarządem? Czy dyskusje odbywają się regularnie, tylko wtedy, gdy pojawiają się konkretne problemy, czy nigdy?', 'Jak często BHP jest przedmiotem dyskusji między przedstawicielami pracowników a zarządem? Czy dyskusje odbywają się regularnie, tylko wtedy, gdy pojawiają się konkretne problemy, czy nigdy?<br><br>(1) Regularnie <br>(2) Tylko wtedy, gdy pojawiają się konkretne problemy <br>(3) Nigdy <br>(7) Nie dotyczy (nie ma przedstawicieli pracowników) <br>(9) Brak odpowiedzi <br><br>Pytanie zadawane zakładom pracy zgłaszającym jakąś formę reprezentacji pracowników.'],
		['Q351', 'Jak często pojawiają się nieporozumienia związane z BHP? Często, czasami, czy praktycznie nigdy?', 'Jak często pojawiają się nieporozumienia związane z BHP? Często, czasami, czy praktycznie nigdy?<br><br>(1) Często <br>(2) Czasami <br>(3) Praktycznie nigdy <br>(9) Brak odpowiedzi<br><br>Pytanie zadawane zakładom pracy deklarującym, że BHP jest przedmiotem dyskusji między przedstawicielami pracowników a zarządem'],
		['Q354', 'Czy Społeczni inspektorzy pracy uczestniczą w czasie pracy w szkoleniach mających pomóc im w wykonywaniu obowiązków w zakresie BHP?', 'Czy Społeczni inspektorzy pracy uczestniczą w czasie pracy w szkoleniach mających pomóc im w wykonywaniu obowiązków w zakresie BHP?<br><br>(1) Tak <br>(2) Nie <br>(3) Tak, ale tylko niektórzy z nich <br>(9) Brak odpowiedzi<br><br>Pytanie zadawane zakładom pracy zgłaszającym posiadanie przedstawiciela pracowników ds. BHP, np. społecznego inspektora pracy.'],
		['Q358', 'Czy kwestie BHP są regularnie omawiane na zebraniach pracowników lub zebraniach zespołów?', 'Czy kwestie BHP są regularnie omawiane na zebraniach pracowników lub zebraniach zespołów?<br><br>(1) Tak <br>(2) Nie <br>(3) Tylko w niektórych działach <br>(9) Brak odpowiedzi']
	];
