//Auto Generated file
var subset_
	 = [
	
		['Sectorgrp', 'Gospodarska dejavnost'],
		['Size', 'Velikost poslovne enote']
	];
var subset_subsetValue
	 = [
	
		['Sectorgrp', 'All', 'Vse'],
		['Sectorgrp', '1--A', 'Kmetijstvo, gozdarstvo in ribištvo'],
		['Sectorgrp', '2--BDEF', 'Gradbeništvo, ravnanje z odpadki, oskrba z vodo in električno energijo'],
		['Sectorgrp', '3--C', 'Predelovalna dejavnost'],
		['Sectorgrp', '4--GHIR', 'Trgovina, promet, gostinstvo in rekreacijske dejavnosti'],
		['Sectorgrp', '5--JKLMNS', 'IT, finance, poslovanje z nepremičninami in druge tehnične, znanstvene ali storitvene dejavnosti'],
		['Sectorgrp', '6--O', 'Javna uprava'],
		['Sectorgrp', '7--PQ', 'Izobraževanje, zdravstvo in socialno varstvo'],
		['Size', 'All', 'Vse'],
		['Size', '1--5-to-9', '5–9 zaposlenih'],
		['Size', '2--10-to-49', '10–49 zaposlenih'],
		['Size', '3--50-249', '50–249 zaposlenih'],
		['Size', '4--250-', '250 ali več zaposlenih']
	];
var topic_
	 = [
	
		['', 'vse (108)'],
		['Ključne ugotovitve', 'Ključne ugotovitve (24)'],
		['Psihosocialna tveganja in njihovo upravljanje', 'Psihosocialna tveganja in njihovo upravljanje (21)'],
		['Sodelovanje zaposlenih', 'Sodelovanje zaposlenih (10)'],
		['Spodbude in ovire', 'Spodbude in ovire (17)'],
		['Upravljanje varnosti in zdravja pri delu', 'Upravljanje varnosti in zdravja pri delu (60)']
	];
var topic_question
	 = [
	
		['Ključne ugotovitve', 'Q200_1', 'Dejavniki tveganja, prisotni v poslovni enoti: Utrujajoči ali boleči položaji'],
		['Ključne ugotovitve', 'Q200_2', 'Dejavniki tveganja, prisotni v poslovni enoti: Dvigovanje ali premikanje ljudi ali težkih bremen'],
		['Ključne ugotovitve', 'Q200_3', 'Dejavniki tveganja, prisotni v poslovni enoti: Močan hrup'],
		['Ključne ugotovitve', 'Q200_4', 'Dejavniki tveganja, prisotni v poslovni enoti: Ponavljajoči se gibi dlani ali rok'],
		['Ključne ugotovitve', 'Q200_5', 'Dejavniki tveganja, prisotni v poslovni enoti: Vročina, mraz ali prepih'],
		['Ključne ugotovitve', 'Q200_6', 'Dejavniki tveganja, prisotni v poslovni enoti: Nevarnost nezgod pri delu s stroji ali ročnim orodjem'],
		['Ključne ugotovitve', 'Q200_7', 'Dejavniki tveganja, prisotni v poslovni enoti: Tveganje nesreč pri delu z vozili med opravljanjem dela'],
		['Ključne ugotovitve', 'Q200_8', 'Dejavniki tveganja, prisotni v poslovni enoti: Kemične ali biološke snovi'],
		['Ključne ugotovitve', 'Q200_9', 'Dejavniki tveganja, prisotni v poslovni enoti: Povečano tveganje zdrsov, spotikov in padcev '],
		['Ključne ugotovitve', 'Q201_1', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Časovni pritisk    '],
		['Ključne ugotovitve', 'Q201_2', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Slaba komunikacija ali sodelovanje'],
		['Ključne ugotovitve', 'Q201_3', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Zaposleni nimajo vpliva'],
		['Ključne ugotovitve', 'Q201_4', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Negotovost zaposlitve    '],
		['Ključne ugotovitve', 'Q201_5', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Soočanje z zahtevnimi strankami, bolniki, učenci'],
		['Ključne ugotovitve', 'Q201_6', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Dolg ali nereden delovni čas    '],
		['Ključne ugotovitve', 'Q201_7', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Diskriminacija'],
		['Ključne ugotovitve', 'Q250', 'Ocene tveganja na delovnem mestu'],
		['Ključne ugotovitve', 'Q251', 'Ocene tveganja, ki jih večinoma izvaja interno osebje ali zunanji ponudniki storitev'],
		['Ključne ugotovitve', 'Q264_1', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Izpolnjevanje zakonske obveznosti   '],
		['Ključne ugotovitve', 'Q264_2', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Izpolnjevanje pričakovanj zaposlenih'],
		['Ključne ugotovitve', 'Q264_4', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Povečanje produktivnosti'],
		['Ključne ugotovitve', 'Q264_5', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Dober sloves organizacije'],
		['Ključne ugotovitve', 'Q264_6', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Izogibanje globam in sankcijam inšpektorata RS za delo'],
		['Ključne ugotovitve', 'Q307', 'Dovolj informacij o tem, kako psihosocialna tveganja vključiti v ocene tveganja'],
		['Upravljanje varnosti in zdravja pri delu', 'Q150_1', 'Uporaba storitev na področju varnosti in zdravja: Zdravnik specialist medicine dela'],
		['Upravljanje varnosti in zdravja pri delu', 'Q150_2', 'Uporaba storitev na področju varnosti in zdravja: Psiholog'],
		['Upravljanje varnosti in zdravja pri delu', 'Q150_3', 'Uporaba storitev na področju varnosti in zdravja: Strokovnjak za ergonomsko oblikovanje in ureditev delovnega okolja '],
		['Upravljanje varnosti in zdravja pri delu', 'Q150_4', 'Uporaba storitev na področju varnosti in zdravja: Splošni strokovnjak za varnost in zdravje pri delu'],
		['Upravljanje varnosti in zdravja pri delu', 'Q150_5', 'Uporaba storitev na področju varnosti in zdravja: Strokovnjak na področju preprečevanja nezgod pri delu'],
		['Upravljanje varnosti in zdravja pri delu', 'Q155', 'Zaposlenim je na voljo dokument, v katerem so pojasnjeni odgovornosti in postopki v zvezi z varnostjo in zdravjem'],
		['Upravljanje varnosti in zdravja pri delu', 'Q156', 'Vsako leto se dodelijo posebna proračunska sredstva za kritje stroškov izvajanja ukrepov in nakupa opreme za zagotavljanje varnosti in zdravja pri delu'],
		['Upravljanje varnosti in zdravja pri delu', 'Q158_1', 'Ukrepi za promocijo zdravja med zaposlenimi: Ozaveščanje o zdravi prehrani '],
		['Upravljanje varnosti in zdravja pri delu', 'Q158_2', 'Ukrepi za promocijo zdravja med zaposlenimi: Ozaveščanje o preprečevanju zasvojenosti'],
		['Upravljanje varnosti in zdravja pri delu', 'Q158_3', 'Ukrepi za promocijo zdravja med zaposlenimi: Spodbujanje športnih dejavnosti izven delovnega časa'],
		['Upravljanje varnosti in zdravja pri delu', 'Q158_4', 'Ukrepi za promocijo zdravja med zaposlenimi: Spodbujanje telesne vadbe na delovnem mestu'],
		['Upravljanje varnosti in zdravja pri delu', 'Q160', 'Redno analiziranje bolniških odsotnosti z dela'],
		['Upravljanje varnosti in zdravja pri delu', 'Q165', 'Obisk Inšpektorata RS za delo v zadnjih treh letih, da bi preveril razmere na področju varnosti in zdravja pri delu'],
		['Upravljanje varnosti in zdravja pri delu', 'Q200_1', 'Dejavniki tveganja, prisotni v poslovni enoti: Utrujajoči ali boleči položaji'],
		['Upravljanje varnosti in zdravja pri delu', 'Q200_2', 'Dejavniki tveganja, prisotni v poslovni enoti: Dvigovanje ali premikanje ljudi ali težkih bremen'],
		['Upravljanje varnosti in zdravja pri delu', 'Q200_3', 'Dejavniki tveganja, prisotni v poslovni enoti: Močan hrup'],
		['Upravljanje varnosti in zdravja pri delu', 'Q200_4', 'Dejavniki tveganja, prisotni v poslovni enoti: Ponavljajoči se gibi dlani ali rok'],
		['Upravljanje varnosti in zdravja pri delu', 'Q200_5', 'Dejavniki tveganja, prisotni v poslovni enoti: Vročina, mraz ali prepih'],
		['Upravljanje varnosti in zdravja pri delu', 'Q200_6', 'Dejavniki tveganja, prisotni v poslovni enoti: Nevarnost nezgod pri delu s stroji ali ročnim orodjem'],
		['Upravljanje varnosti in zdravja pri delu', 'Q200_7', 'Dejavniki tveganja, prisotni v poslovni enoti: Tveganje nesreč pri delu z vozili med opravljanjem dela'],
		['Upravljanje varnosti in zdravja pri delu', 'Q200_8', 'Dejavniki tveganja, prisotni v poslovni enoti: Kemične ali biološke snovi'],
		['Upravljanje varnosti in zdravja pri delu', 'Q200_9', 'Dejavniki tveganja, prisotni v poslovni enoti: Povečano tveganje zdrsov, spotikov in padcev '],
		['Upravljanje varnosti in zdravja pri delu', 'Q202_1', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Utrujajoči ali boleči položaji'],
		['Upravljanje varnosti in zdravja pri delu', 'Q202_2', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Dvigovanje ali premikanje ljudi ali težkih bremen'],
		['Upravljanje varnosti in zdravja pri delu', 'Q202_3', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Močan hrup'],
		['Upravljanje varnosti in zdravja pri delu', 'Q202_4', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Ponavljajoči se gibi dlani ali rok'],
		['Upravljanje varnosti in zdravja pri delu', 'Q202_5', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Vročina, mraz ali prepih'],
		['Upravljanje varnosti in zdravja pri delu', 'Q202_6', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Nevarnost nezgod pri delu s stroji ali ročnim orodjem'],
		['Upravljanje varnosti in zdravja pri delu', 'Q202_7', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Tveganje nesreč pri delu z vozili med opravljanjem dela'],
		['Upravljanje varnosti in zdravja pri delu', 'Q202_8', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Kemične ali biološke snovi'],
		['Upravljanje varnosti in zdravja pri delu', 'Q202_9', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Povečano tveganje zdrsov, spotikov in padcev '],
		['Upravljanje varnosti in zdravja pri delu', 'Q250', 'Ocene tveganja na delovnem mestu'],
		['Upravljanje varnosti in zdravja pri delu', 'Q251', 'Ocene tveganja, ki jih večinoma izvaja interno osebje ali zunanji ponudniki storitev'],
		['Upravljanje varnosti in zdravja pri delu', 'Q252_1', 'Vidiki, ki se preverjajo v ocenah tveganja na delovnem mestu: Varnost strojev, opreme in naprav    '],
		['Upravljanje varnosti in zdravja pri delu', 'Q252_2', 'Vidiki, ki se preverjajo v ocenah tveganja na delovnem mestu: Nevarne snovi'],
		['Upravljanje varnosti in zdravja pri delu', 'Q252_3', 'Vidiki, ki se preverjajo v ocenah tveganja na delovnem mestu: Telesna drža med delom, telesni napor in ponavljajoči se gibi    '],
		['Upravljanje varnosti in zdravja pri delu', 'Q252_4', 'Vidiki, ki se preverjajo v ocenah tveganja na delovnem mestu: Izpostavljenost hrupu, vibracijam, vročini ali mrazu    '],
		['Upravljanje varnosti in zdravja pri delu', 'Q252_5', 'Vidiki, ki se preverjajo v ocenah tveganja na delovnem mestu: Odnosi med nadzornim osebjem in zaposlenimi    '],
		['Upravljanje varnosti in zdravja pri delu', 'Q252_6', 'Vidiki, ki se preverjajo v ocenah tveganja na delovnem mestu: Organizacijski vidiki'],
		['Upravljanje varnosti in zdravja pri delu', 'Q254gr', 'Leto zadnje ocene tveganja na delovnem mestu'],
		['Upravljanje varnosti in zdravja pri delu', 'Q255', 'Ocena tveganja na delovnem mestu dokumentirana v pisni obliki'],
		['Upravljanje varnosti in zdravja pri delu', 'Q256_1', 'Osebe, ki so prejele ugotovitve ocene tveganja na delovnem mestu: Vodstvo'],
		['Upravljanje varnosti in zdravja pri delu', 'Q256_2', 'Osebe, ki so prejele ugotovitve ocene tveganja na delovnem mestu: Delavski zaupniki za varnost in zdravje pri delu'],
		['Upravljanje varnosti in zdravja pri delu', 'Q256_3', 'Osebe, ki so prejele ugotovitve ocene tveganja na delovnem mestu: Svet delavcev'],
		['Upravljanje varnosti in zdravja pri delu', 'Q256_4', 'Osebe, ki so prejele ugotovitve ocene tveganja na delovnem mestu: Sindikalni zaupniki '],
		['Upravljanje varnosti in zdravja pri delu', 'Q256_5', 'Osebe, ki so prejele ugotovitve ocene tveganja na delovnem mestu: Zaposleni '],
		['Upravljanje varnosti in zdravja pri delu', 'Q259', 'Ocene tveganja se štejejo za koristen način upravljanja varnosti in zdravja pri delu'],
		['Upravljanje varnosti in zdravja pri delu', 'Q261_1', 'Razlogi za neredno izvajanje ocen tveganja na delovnem mestu: Nevarnosti in tveganja so že znani'],
		['Upravljanje varnosti in zdravja pri delu', 'Q261_2', 'Razlogi za neredno izvajanje ocen tveganja na delovnem mestu: Ni večjih težav.   '],
		['Upravljanje varnosti in zdravja pri delu', 'Q261_3', 'Razlogi za neredno izvajanje ocen tveganja na delovnem mestu: Postopek je prevečtežaven.   '],
		['Upravljanje varnosti in zdravja pri delu', 'Q261_4', 'Razlogi za neredno izvajanje ocen tveganja na delovnem mestu: Ni potrebnega strokovnega znanja.'],
		['Upravljanje varnosti in zdravja pri delu', 'Q308_1', 'Preventivni ukrepi za preprečevanje kostno-mišičnih težav: Oprema za pomoč pri dvigovanju ali premikanju bremen'],
		['Upravljanje varnosti in zdravja pri delu', 'Q308_2', 'Preventivni ukrepi za preprečevanje kostno-mišičnih težav: Kroženje oziroma menjavanje zaposlenih pri opravljanju nalog za zmanjšanje telesnega napora'],
		['Upravljanje varnosti in zdravja pri delu', 'Q308_3', 'Preventivni ukrepi za preprečevanje kostno-mišičnih težav: Spodbujanje koriščenja rednih premorov pri opravljanju del v neudobni ali nepremični telesni drži'],
		['Upravljanje varnosti in zdravja pri delu', 'Q308_4', 'Preventivni ukrepi za preprečevanje kostno-mišičnih težav: Zagotovitev ergonomske opreme'],
		['Upravljanje varnosti in zdravja pri delu', 'Q356_1', 'Usposabljanje za zaposlene: Ustrezna raba in prilagoditev delovne opreme in pohištva'],
		['Upravljanje varnosti in zdravja pri delu', 'Q356_2', 'Usposabljanje za zaposlene: Uporaba nevarnih snovi'],
		['Upravljanje varnosti in zdravja pri delu', 'Q356_3', 'Usposabljanje za zaposlene: Kako preprečevati psihosocialna tveganja'],
		['Upravljanje varnosti in zdravja pri delu', 'Q356_4', 'Usposabljanje za zaposlene: Kako dvigati ali premikati težka bremena ali ljudi'],
		['Upravljanje varnosti in zdravja pri delu', 'Q356_5', 'Usposabljanje za zaposlene: Postopki za ravnanje v nujnih primerih'],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q201_1', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Časovni pritisk    '],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q201_2', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Slaba komunikacija ali sodelovanje'],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q201_3', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Zaposleni nimajo vpliva'],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q201_4', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Negotovost zaposlitve    '],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q201_5', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Soočanje z zahtevnimi strankami, bolniki, učenci'],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q201_6', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Dolg ali nereden delovni čas    '],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q201_7', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Diskriminacija'],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q202_10', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Časovni pritisk    '],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q202_11', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Slaba komunikacija ali sodelovanje'],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q202_12', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Zaposleni nimajo vpliva'],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q202_13', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Negotovost zaposlitve    '],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q202_14', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Soočanje z zahtevnimi strankami, bolniki, učenci'],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q202_15', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Dolg ali nereden delovni čas    '],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q300', 'Akcijski načrt za preprečevanje stresa, povezanega z delom'],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q301', 'Postopki, vzpostavljeni za obravnavanje ustrahovanja ali nadlegovanja'],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q302', 'Postopki, vzpostavljeni za obravnavanje primerov groženj, zlorab ali napadov'],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q303_1', 'Ukrepi za preprečevanje psihosocialnih tveganj, sprejeti v zadnjih treh letih: Reorganizacija dela z namenom zmanjšanja zahtev delovnega mesta in pritiska na delu '],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q303_2', 'Ukrepi za preprečevanje psihosocialnih tveganj, sprejeti v zadnjih treh letih: Zaupno svetovanje za zaposlene   '],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q303_3', 'Ukrepi za preprečevanje psihosocialnih tveganj, sprejeti v zadnjih treh letih: Vzpostavitev postopka za reševanje sporov   '],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q303_4', 'Ukrepi za preprečevanje psihosocialnih tveganj, sprejeti v zadnjih treh letih: Posredovanje v primeru dolgega ali nerednega delovnega časa'],
		['Psihosocialna tveganja in njihovo upravljanje', 'Q307', 'Dovolj informacij o tem, kako psihosocialna tveganja vključiti v ocene tveganja'],
		['Spodbude in ovire', 'Q264_1', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Izpolnjevanje zakonske obveznosti   '],
		['Spodbude in ovire', 'Q264_2', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Izpolnjevanje pričakovanj zaposlenih'],
		['Spodbude in ovire', 'Q264_4', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Povečanje produktivnosti'],
		['Spodbude in ovire', 'Q264_5', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Dober sloves organizacije'],
		['Spodbude in ovire', 'Q264_6', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Izogibanje globam in sankcijam inšpektorata RS za delo'],
		['Spodbude in ovire', 'Q265_1', 'Glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu: Pomanjkanje časa ali osebja'],
		['Spodbude in ovire', 'Q265_2', 'Glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu: Pomanjkanje denarja'],
		['Spodbude in ovire', 'Q265_3', 'Glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu: Pomanjkanje ozaveščenosti med osebjem'],
		['Spodbude in ovire', 'Q265_4', 'Glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu: Pomanjkanje ozaveščenosti med vodilnim kadrom '],
		['Spodbude in ovire', 'Q265_5', 'Glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu: Pomanjkanje strokovnega znanja ali podpore strokovnjakov'],
		['Spodbude in ovire', 'Q265_6', 'Glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu: Papirologija'],
		['Spodbude in ovire', 'Q265_7', 'Glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu: Zahtevnost pravnih obveznosti'],
		['Spodbude in ovire', 'Q304', 'Ukrepi, sprejeti kot posledica konkretnih težav'],
		['Spodbude in ovire', 'Q306a_3', 'Težave pri obravnavanju psihosocialnih tveganj: Pomanjkanje ozaveščenosti med osebjem   '],
		['Spodbude in ovire', 'Q306a_4', 'Težave pri obravnavanju psihosocialnih tveganj: Pomanjkanje ozaveščenosti med vodilnim kadrom   '],
		['Spodbude in ovire', 'Q306a_5', 'Težave pri obravnavanju psihosocialnih tveganj: Pomanjkanje strokovnega znanja ali podpore strokovnjakov   '],
		['Spodbude in ovire', 'Q306a_6', 'Težave pri obravnavanju psihosocialnih tveganj: Nepripravljenost na odkrit pogovor o teh težavah'],
		['Sodelovanje zaposlenih', 'Q166_1', 'Oblike delavskega zastopanja: Svet delavcev'],
		['Sodelovanje zaposlenih', 'Q166_2', 'Oblike delavskega zastopanja: Sindikalno zastopanje'],
		['Sodelovanje zaposlenih', 'Q166_3', 'Oblike delavskega zastopanja: Delavski zaupnik za varnost in zdravje pri delu'],
		['Sodelovanje zaposlenih', 'Q166_4', 'Oblike delavskega zastopanja: (A health and safety committee)'],
		['Sodelovanje zaposlenih', 'Q258b', 'Zaposleni so vključeni v oblikovanje ukrepov po oceni tveganja'],
		['Sodelovanje zaposlenih', 'Q305', 'Zaposleni sodelujejo pri oblikovanju ukrepov za preprečevanje psihosocialnih tveganj'],
		['Sodelovanje zaposlenih', 'Q350', 'Kako pogosto sta varnost in zdravje pri delu predmet razprav med predstavniki delavcev in vodstvom'],
		['Sodelovanje zaposlenih', 'Q351', 'Kako pogosto pride do polemik v zvezi z varnostjo in zdravjem pri delu'],
		['Sodelovanje zaposlenih', 'Q354', 'Delavskim zaupnikom za varnost in zdravje pri delu je zagotovljeno usposabljanje med delovnim časom'],
		['Sodelovanje zaposlenih', 'Q358', 'Na sestankih zaposlenih ali sestankih skupin se razpravlja o vprašanjih, povezanih z varnostjo in zdravjem']
	];
var question_
	 = [
	
		['Q200_1', 'Dejavniki tveganja, prisotni v poslovni enoti: Utrujajoči ali boleči položaji'],
		['Q200_2', 'Dejavniki tveganja, prisotni v poslovni enoti: Dvigovanje ali premikanje ljudi ali težkih bremen'],
		['Q200_3', 'Dejavniki tveganja, prisotni v poslovni enoti: Močan hrup'],
		['Q200_4', 'Dejavniki tveganja, prisotni v poslovni enoti: Ponavljajoči se gibi dlani ali rok'],
		['Q200_5', 'Dejavniki tveganja, prisotni v poslovni enoti: Vročina, mraz ali prepih'],
		['Q200_6', 'Dejavniki tveganja, prisotni v poslovni enoti: Nevarnost nezgod pri delu s stroji ali ročnim orodjem'],
		['Q200_7', 'Dejavniki tveganja, prisotni v poslovni enoti: Tveganje nesreč pri delu z vozili med opravljanjem dela'],
		['Q200_8', 'Dejavniki tveganja, prisotni v poslovni enoti: Kemične ali biološke snovi'],
		['Q200_9', 'Dejavniki tveganja, prisotni v poslovni enoti: Povečano tveganje zdrsov, spotikov in padcev '],
		['Q201_1', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Časovni pritisk    '],
		['Q201_2', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Slaba komunikacija ali sodelovanje'],
		['Q201_3', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Zaposleni nimajo vpliva'],
		['Q201_4', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Negotovost zaposlitve    '],
		['Q201_5', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Soočanje z zahtevnimi strankami, bolniki, učenci'],
		['Q201_6', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Dolg ali nereden delovni čas    '],
		['Q201_7', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Diskriminacija'],
		['Q250', 'Ocene tveganja na delovnem mestu'],
		['Q251', 'Ocene tveganja, ki jih večinoma izvaja interno osebje ali zunanji ponudniki storitev'],
		['Q264_1', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Izpolnjevanje zakonske obveznosti   '],
		['Q264_2', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Izpolnjevanje pričakovanj zaposlenih'],
		['Q264_4', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Povečanje produktivnosti'],
		['Q264_5', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Dober sloves organizacije'],
		['Q264_6', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Izogibanje globam in sankcijam inšpektorata RS za delo'],
		['Q307', 'Dovolj informacij o tem, kako psihosocialna tveganja vključiti v ocene tveganja'],
		['Q150_1', 'Uporaba storitev na področju varnosti in zdravja: Zdravnik specialist medicine dela'],
		['Q150_2', 'Uporaba storitev na področju varnosti in zdravja: Psiholog'],
		['Q150_3', 'Uporaba storitev na področju varnosti in zdravja: Strokovnjak za ergonomsko oblikovanje in ureditev delovnega okolja '],
		['Q150_4', 'Uporaba storitev na področju varnosti in zdravja: Splošni strokovnjak za varnost in zdravje pri delu'],
		['Q150_5', 'Uporaba storitev na področju varnosti in zdravja: Strokovnjak na področju preprečevanja nezgod pri delu'],
		['Q155', 'Zaposlenim je na voljo dokument, v katerem so pojasnjeni odgovornosti in postopki v zvezi z varnostjo in zdravjem'],
		['Q156', 'Vsako leto se dodelijo posebna proračunska sredstva za kritje stroškov izvajanja ukrepov in nakupa opreme za zagotavljanje varnosti in zdravja pri delu'],
		['Q158_1', 'Ukrepi za promocijo zdravja med zaposlenimi: Ozaveščanje o zdravi prehrani '],
		['Q158_2', 'Ukrepi za promocijo zdravja med zaposlenimi: Ozaveščanje o preprečevanju zasvojenosti'],
		['Q158_3', 'Ukrepi za promocijo zdravja med zaposlenimi: Spodbujanje športnih dejavnosti izven delovnega časa'],
		['Q158_4', 'Ukrepi za promocijo zdravja med zaposlenimi: Spodbujanje telesne vadbe na delovnem mestu'],
		['Q160', 'Redno analiziranje bolniških odsotnosti z dela'],
		['Q165', 'Obisk Inšpektorata RS za delo v zadnjih treh letih, da bi preveril razmere na področju varnosti in zdravja pri delu'],
		['Q200_1', 'Dejavniki tveganja, prisotni v poslovni enoti: Utrujajoči ali boleči položaji'],
		['Q200_2', 'Dejavniki tveganja, prisotni v poslovni enoti: Dvigovanje ali premikanje ljudi ali težkih bremen'],
		['Q200_3', 'Dejavniki tveganja, prisotni v poslovni enoti: Močan hrup'],
		['Q200_4', 'Dejavniki tveganja, prisotni v poslovni enoti: Ponavljajoči se gibi dlani ali rok'],
		['Q200_5', 'Dejavniki tveganja, prisotni v poslovni enoti: Vročina, mraz ali prepih'],
		['Q200_6', 'Dejavniki tveganja, prisotni v poslovni enoti: Nevarnost nezgod pri delu s stroji ali ročnim orodjem'],
		['Q200_7', 'Dejavniki tveganja, prisotni v poslovni enoti: Tveganje nesreč pri delu z vozili med opravljanjem dela'],
		['Q200_8', 'Dejavniki tveganja, prisotni v poslovni enoti: Kemične ali biološke snovi'],
		['Q200_9', 'Dejavniki tveganja, prisotni v poslovni enoti: Povečano tveganje zdrsov, spotikov in padcev '],
		['Q202_1', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Utrujajoči ali boleči položaji'],
		['Q202_2', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Dvigovanje ali premikanje ljudi ali težkih bremen'],
		['Q202_3', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Močan hrup'],
		['Q202_4', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Ponavljajoči se gibi dlani ali rok'],
		['Q202_5', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Vročina, mraz ali prepih'],
		['Q202_6', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Nevarnost nezgod pri delu s stroji ali ročnim orodjem'],
		['Q202_7', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Tveganje nesreč pri delu z vozili med opravljanjem dela'],
		['Q202_8', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Kemične ali biološke snovi'],
		['Q202_9', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Povečano tveganje zdrsov, spotikov in padcev '],
		['Q250', 'Ocene tveganja na delovnem mestu'],
		['Q251', 'Ocene tveganja, ki jih večinoma izvaja interno osebje ali zunanji ponudniki storitev'],
		['Q252_1', 'Vidiki, ki se preverjajo v ocenah tveganja na delovnem mestu: Varnost strojev, opreme in naprav    '],
		['Q252_2', 'Vidiki, ki se preverjajo v ocenah tveganja na delovnem mestu: Nevarne snovi'],
		['Q252_3', 'Vidiki, ki se preverjajo v ocenah tveganja na delovnem mestu: Telesna drža med delom, telesni napor in ponavljajoči se gibi    '],
		['Q252_4', 'Vidiki, ki se preverjajo v ocenah tveganja na delovnem mestu: Izpostavljenost hrupu, vibracijam, vročini ali mrazu    '],
		['Q252_5', 'Vidiki, ki se preverjajo v ocenah tveganja na delovnem mestu: Odnosi med nadzornim osebjem in zaposlenimi    '],
		['Q252_6', 'Vidiki, ki se preverjajo v ocenah tveganja na delovnem mestu: Organizacijski vidiki'],
		['Q254gr', 'Leto zadnje ocene tveganja na delovnem mestu'],
		['Q255', 'Ocena tveganja na delovnem mestu dokumentirana v pisni obliki'],
		['Q256_1', 'Osebe, ki so prejele ugotovitve ocene tveganja na delovnem mestu: Vodstvo'],
		['Q256_2', 'Osebe, ki so prejele ugotovitve ocene tveganja na delovnem mestu: Delavski zaupniki za varnost in zdravje pri delu'],
		['Q256_3', 'Osebe, ki so prejele ugotovitve ocene tveganja na delovnem mestu: Svet delavcev'],
		['Q256_4', 'Osebe, ki so prejele ugotovitve ocene tveganja na delovnem mestu: Sindikalni zaupniki '],
		['Q256_5', 'Osebe, ki so prejele ugotovitve ocene tveganja na delovnem mestu: Zaposleni '],
		['Q259', 'Ocene tveganja se štejejo za koristen način upravljanja varnosti in zdravja pri delu'],
		['Q261_1', 'Razlogi za neredno izvajanje ocen tveganja na delovnem mestu: Nevarnosti in tveganja so že znani'],
		['Q261_2', 'Razlogi za neredno izvajanje ocen tveganja na delovnem mestu: Ni večjih težav.   '],
		['Q261_3', 'Razlogi za neredno izvajanje ocen tveganja na delovnem mestu: Postopek je prevečtežaven.   '],
		['Q261_4', 'Razlogi za neredno izvajanje ocen tveganja na delovnem mestu: Ni potrebnega strokovnega znanja.'],
		['Q308_1', 'Preventivni ukrepi za preprečevanje kostno-mišičnih težav: Oprema za pomoč pri dvigovanju ali premikanju bremen'],
		['Q308_2', 'Preventivni ukrepi za preprečevanje kostno-mišičnih težav: Kroženje oziroma menjavanje zaposlenih pri opravljanju nalog za zmanjšanje telesnega napora'],
		['Q308_3', 'Preventivni ukrepi za preprečevanje kostno-mišičnih težav: Spodbujanje koriščenja rednih premorov pri opravljanju del v neudobni ali nepremični telesni drži'],
		['Q308_4', 'Preventivni ukrepi za preprečevanje kostno-mišičnih težav: Zagotovitev ergonomske opreme'],
		['Q356_1', 'Usposabljanje za zaposlene: Ustrezna raba in prilagoditev delovne opreme in pohištva'],
		['Q356_2', 'Usposabljanje za zaposlene: Uporaba nevarnih snovi'],
		['Q356_3', 'Usposabljanje za zaposlene: Kako preprečevati psihosocialna tveganja'],
		['Q356_4', 'Usposabljanje za zaposlene: Kako dvigati ali premikati težka bremena ali ljudi'],
		['Q356_5', 'Usposabljanje za zaposlene: Postopki za ravnanje v nujnih primerih'],
		['Q201_1', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Časovni pritisk    '],
		['Q201_2', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Slaba komunikacija ali sodelovanje'],
		['Q201_3', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Zaposleni nimajo vpliva'],
		['Q201_4', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Negotovost zaposlitve    '],
		['Q201_5', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Soočanje z zahtevnimi strankami, bolniki, učenci'],
		['Q201_6', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Dolg ali nereden delovni čas    '],
		['Q201_7', 'Dejavniki psihosocialnega tveganja, prisotni v poslovni enoti: Diskriminacija'],
		['Q202_10', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Časovni pritisk    '],
		['Q202_11', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Slaba komunikacija ali sodelovanje'],
		['Q202_12', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Zaposleni nimajo vpliva'],
		['Q202_13', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Negotovost zaposlitve    '],
		['Q202_14', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Soočanje z zahtevnimi strankami, bolniki, učenci'],
		['Q202_15', 'Pomanjkanje informacij ali ustreznih orodij za učinkovito obvladovanje tveganja: Dolg ali nereden delovni čas    '],
		['Q300', 'Akcijski načrt za preprečevanje stresa, povezanega z delom'],
		['Q301', 'Postopki, vzpostavljeni za obravnavanje ustrahovanja ali nadlegovanja'],
		['Q302', 'Postopki, vzpostavljeni za obravnavanje primerov groženj, zlorab ali napadov'],
		['Q303_1', 'Ukrepi za preprečevanje psihosocialnih tveganj, sprejeti v zadnjih treh letih: Reorganizacija dela z namenom zmanjšanja zahtev delovnega mesta in pritiska na delu '],
		['Q303_2', 'Ukrepi za preprečevanje psihosocialnih tveganj, sprejeti v zadnjih treh letih: Zaupno svetovanje za zaposlene   '],
		['Q303_3', 'Ukrepi za preprečevanje psihosocialnih tveganj, sprejeti v zadnjih treh letih: Vzpostavitev postopka za reševanje sporov   '],
		['Q303_4', 'Ukrepi za preprečevanje psihosocialnih tveganj, sprejeti v zadnjih treh letih: Posredovanje v primeru dolgega ali nerednega delovnega časa'],
		['Q307', 'Dovolj informacij o tem, kako psihosocialna tveganja vključiti v ocene tveganja'],
		['Q264_1', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Izpolnjevanje zakonske obveznosti   '],
		['Q264_2', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Izpolnjevanje pričakovanj zaposlenih'],
		['Q264_4', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Povečanje produktivnosti'],
		['Q264_5', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Dober sloves organizacije'],
		['Q264_6', 'Razlogi za obravnavo vprašanj varnosti in zdravja pri delu v poslovni enoti: Izogibanje globam in sankcijam inšpektorata RS za delo'],
		['Q265_1', 'Glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu: Pomanjkanje časa ali osebja'],
		['Q265_2', 'Glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu: Pomanjkanje denarja'],
		['Q265_3', 'Glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu: Pomanjkanje ozaveščenosti med osebjem'],
		['Q265_4', 'Glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu: Pomanjkanje ozaveščenosti med vodilnim kadrom '],
		['Q265_5', 'Glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu: Pomanjkanje strokovnega znanja ali podpore strokovnjakov'],
		['Q265_6', 'Glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu: Papirologija'],
		['Q265_7', 'Glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu: Zahtevnost pravnih obveznosti'],
		['Q304', 'Ukrepi, sprejeti kot posledica konkretnih težav'],
		['Q306a_3', 'Težave pri obravnavanju psihosocialnih tveganj: Pomanjkanje ozaveščenosti med osebjem   '],
		['Q306a_4', 'Težave pri obravnavanju psihosocialnih tveganj: Pomanjkanje ozaveščenosti med vodilnim kadrom   '],
		['Q306a_5', 'Težave pri obravnavanju psihosocialnih tveganj: Pomanjkanje strokovnega znanja ali podpore strokovnjakov   '],
		['Q306a_6', 'Težave pri obravnavanju psihosocialnih tveganj: Nepripravljenost na odkrit pogovor o teh težavah'],
		['Q166_1', 'Oblike delavskega zastopanja: Svet delavcev'],
		['Q166_2', 'Oblike delavskega zastopanja: Sindikalno zastopanje'],
		['Q166_3', 'Oblike delavskega zastopanja: Delavski zaupnik za varnost in zdravje pri delu'],
		['Q166_4', 'Oblike delavskega zastopanja: (A health and safety committee)'],
		['Q258b', 'Zaposleni so vključeni v oblikovanje ukrepov po oceni tveganja'],
		['Q305', 'Zaposleni sodelujejo pri oblikovanju ukrepov za preprečevanje psihosocialnih tveganj'],
		['Q350', 'Kako pogosto sta varnost in zdravje pri delu predmet razprav med predstavniki delavcev in vodstvom'],
		['Q351', 'Kako pogosto pride do polemik v zvezi z varnostjo in zdravjem pri delu'],
		['Q354', 'Delavskim zaupnikom za varnost in zdravje pri delu je zagotovljeno usposabljanje med delovnim časom'],
		['Q358', 'Na sestankih zaposlenih ali sestankih skupin se razpravlja o vprašanjih, povezanih z varnostjo in zdravjem']
	];
var question_answer
	 = [
	
		['Q150_1', '1--Yes', 'Da'],
		['Q150_1', '2--No', 'Ne'],
		['Q150_2', '1--Yes', 'Da'],
		['Q150_2', '2--No', 'Ne'],
		['Q150_3', '1--Yes', 'Da'],
		['Q150_3', '2--No', 'Ne'],
		['Q150_4', '1--Yes', 'Da'],
		['Q150_4', '2--No', 'Ne'],
		['Q150_5', '1--Yes', 'Da'],
		['Q150_5', '2--No', 'Ne'],
		['Q155', '1--Yes', 'Da'],
		['Q155', '2--No', 'Ne'],
		['Q155', '3--Yes--but-only-to-some-types-of-employees', 'Da, toda samo nekaterim zaposlenim'],
		['Q156', '1--Yes', 'Da'],
		['Q156', '2--No', 'Ne'],
		['Q158_1', '1--Yes', 'Da'],
		['Q158_1', '2--No', 'Ne'],
		['Q158_2', '1--Yes', 'Da'],
		['Q158_2', '2--No', 'Ne'],
		['Q158_3', '1--Yes', 'Da'],
		['Q158_3', '2--No', 'Ne'],
		['Q158_4', '1--Yes', 'Da'],
		['Q158_4', '2--No', 'Ne'],
		['Q160', '1--Yes', 'Da'],
		['Q160', '2--No', 'Ne'],
		['Q165', '1--Yes', 'Da'],
		['Q165', '2--No', 'Ne'],
		['Q166_1', '1--Yes', 'Da'],
		['Q166_1', '2--No', 'Ne'],
		['Q166_2', '1--Yes', 'Da'],
		['Q166_2', '2--No', 'Ne'],
		['Q166_3', '1--Yes', 'Da'],
		['Q166_3', '2--No', 'Ne'],
		['Q166_4', '1--Yes', 'Da'],
		['Q166_4', '2--No', 'Ne'],
		['Q200_1', '1--Yes', 'Da'],
		['Q200_1', '2--No', 'Ne'],
		['Q200_2', '1--Yes', 'Da'],
		['Q200_2', '2--No', 'Ne'],
		['Q200_3', '1--Yes', 'Da'],
		['Q200_3', '2--No', 'Ne'],
		['Q200_4', '1--Yes', 'Da'],
		['Q200_4', '2--No', 'Ne'],
		['Q200_5', '1--Yes', 'Da'],
		['Q200_5', '2--No', 'Ne'],
		['Q200_6', '1--Yes', 'Da'],
		['Q200_6', '2--No', 'Ne'],
		['Q200_7', '1--Yes', 'Da'],
		['Q200_7', '2--No', 'Ne'],
		['Q200_8', '1--Yes', 'Da'],
		['Q200_8', '2--No', 'Ne'],
		['Q200_9', '1--Yes', 'Da'],
		['Q200_9', '2--No', 'Ne'],
		['Q201_1', '1--Yes', 'Da'],
		['Q201_1', '2--No', 'Ne'],
		['Q201_2', '1--Yes', 'Da'],
		['Q201_2', '2--No', 'Ne'],
		['Q201_3', '1--Yes', 'Da'],
		['Q201_3', '2--No', 'Ne'],
		['Q201_4', '1--Yes', 'Da'],
		['Q201_4', '2--No', 'Ne'],
		['Q201_5', '1--Yes', 'Da'],
		['Q201_5', '2--No', 'Ne'],
		['Q201_6', '1--Yes', 'Da'],
		['Q201_6', '2--No', 'Ne'],
		['Q201_7', '1--Yes', 'Da'],
		['Q201_7', '2--No', 'Ne'],
		['Q202_1', '1--Yes', 'Da'],
		['Q202_1', '2--No', 'Ne'],
		['Q202_10', '1--Yes', 'Da'],
		['Q202_10', '2--No', 'Ne'],
		['Q202_11', '1--Yes', 'Da'],
		['Q202_11', '2--No', 'Ne'],
		['Q202_12', '1--Yes', 'Da'],
		['Q202_12', '2--No', 'Ne'],
		['Q202_13', '1--Yes', 'Da'],
		['Q202_13', '2--No', 'Ne'],
		['Q202_14', '1--Yes', 'Da'],
		['Q202_14', '2--No', 'Ne'],
		['Q202_15', '1--Yes', 'Da'],
		['Q202_15', '2--No', 'Ne'],
		['Q202_2', '1--Yes', 'Da'],
		['Q202_2', '2--No', 'Ne'],
		['Q202_3', '1--Yes', 'Da'],
		['Q202_3', '2--No', 'Ne'],
		['Q202_4', '1--Yes', 'Da'],
		['Q202_4', '2--No', 'Ne'],
		['Q202_5', '1--Yes', 'Da'],
		['Q202_5', '2--No', 'Ne'],
		['Q202_6', '1--Yes', 'Da'],
		['Q202_6', '2--No', 'Ne'],
		['Q202_7', '1--Yes', 'Da'],
		['Q202_7', '2--No', 'Ne'],
		['Q202_8', '1--Yes', 'Da'],
		['Q202_8', '2--No', 'Ne'],
		['Q202_9', '1--Yes', 'Da'],
		['Q202_9', '2--No', 'Ne'],
		['Q250', '1--Yes', 'Da'],
		['Q250', '2--No', 'Ne'],
		['Q251', '1--Conducted-mainly-by-internal-staff', 'Izvaja jih predvsem interno osebje.'],
		['Q251', '2--Contracted-mainly-to-external-providers', 'Izvajajo jih predvsem zunanji ponudniki.'],
		['Q251', '3--Both-about-equally', 'Oboji skoraj enakovredno'],
		['Q252_1', '1--Yes', 'Da'],
		['Q252_1', '2--No', 'Ne'],
		['Q252_2', '1--Yes', 'Da'],
		['Q252_2', '2--No', 'Ne'],
		['Q252_3', '1--Yes', 'Da'],
		['Q252_3', '2--No', 'Ne'],
		['Q252_4', '1--Yes', 'Da'],
		['Q252_4', '2--No', 'Ne'],
		['Q252_5', '1--Yes', 'Da'],
		['Q252_5', '2--No', 'Ne'],
		['Q252_6', '1--Yes', 'Da'],
		['Q252_6', '2--No', 'Ne'],
		['Q254gr', '1--2010', '2010'],
		['Q254gr', '2--2011', '2011'],
		['Q254gr', '3--2012', '2012'],
		['Q254gr', '4--2013', '2013'],
		['Q254gr', '5--2014', '2014'],
		['Q254gr', '6--before-2010', 'pred letom 2010'],
		['Q254gr', '7--don-t-know', 'Ne vem.'],
		['Q255', '1--Yes', 'Da'],
		['Q255', '2--No', 'Ne'],
		['Q256_1', '1--Yes', 'Da'],
		['Q256_1', '2--No', 'Ne'],
		['Q256_2', '1--Yes', 'Da'],
		['Q256_2', '2--No', 'Ne'],
		['Q256_3', '1--Yes', 'Da'],
		['Q256_3', '2--No', 'Ne'],
		['Q256_4', '1--Yes', 'Da'],
		['Q256_4', '2--No', 'Ne'],
		['Q256_5', '1--Yes', 'Da'],
		['Q256_5', '2--No', 'Ne'],
		['Q258b', '1--Yes', 'Da'],
		['Q258b', '2--No', 'Ne'],
		['Q258b', '3--That-depends-on-the-type-of-measures', 'To je odvisno od vrste ukrepov.'],
		['Q259', '1--Yes', 'Da'],
		['Q259', '2--No', 'Ne'],
		['Q259', '3--There-are-conflicting-views-about-this', 'Mnenja o tem so si nasprotujoča.'],
		['Q261_1', '1--Yes', 'Da'],
		['Q261_1', '2--No', 'Ne'],
		['Q261_2', '1--Yes', 'Da'],
		['Q261_2', '2--No', 'Ne'],
		['Q261_3', '1--Yes', 'Da'],
		['Q261_3', '2--No', 'Ne'],
		['Q261_4', '1--Yes', 'Da'],
		['Q261_4', '2--No', 'Ne'],
		['Q264_1', '1--Major-reason', 'Zelo pomemben razlog'],
		['Q264_1', '2--Minor-reason', 'Manj pomemben razlog'],
		['Q264_1', '3--Not-a-reason', 'Sploh ni razlog.'],
		['Q264_2', '1--Major-reason', 'Zelo pomemben razlog'],
		['Q264_2', '2--Minor-reason', 'Manj pomemben razlog'],
		['Q264_2', '3--Not-a-reason', 'Sploh ni razlog.'],
		['Q264_4', '1--Major-reason', 'Zelo pomemben razlog'],
		['Q264_4', '2--Minor-reason', 'Manj pomemben razlog'],
		['Q264_4', '3--Not-a-reason', 'Sploh ni razlog.'],
		['Q264_5', '1--Major-reason', 'Zelo pomemben razlog'],
		['Q264_5', '2--Minor-reason', 'Manj pomemben razlog'],
		['Q264_5', '3--Not-a-reason', 'Sploh ni razlog.'],
		['Q264_6', '1--Major-reason', 'Zelo pomemben razlog'],
		['Q264_6', '2--Minor-reason', 'Manj pomemben razlog'],
		['Q264_6', '3--Not-a-reason', 'Sploh ni razlog.'],
		['Q265_1', '1--Major-difficulty', 'Večja težava'],
		['Q265_1', '2--Minor-difficulty', 'Manjša težava'],
		['Q265_1', '3--Not-a-difficulty', 'Sploh ni težava'],
		['Q265_2', '1--Major-difficulty', 'Večja težava'],
		['Q265_2', '2--Minor-difficulty', 'Manjša težava'],
		['Q265_2', '3--Not-a-difficulty', 'Sploh ni težava'],
		['Q265_3', '1--Major-difficulty', 'Večja težava'],
		['Q265_3', '2--Minor-difficulty', 'Manjša težava'],
		['Q265_3', '3--Not-a-difficulty', 'Sploh ni težava'],
		['Q265_4', '1--Major-difficulty', 'Večja težava'],
		['Q265_4', '2--Minor-difficulty', 'Manjša težava'],
		['Q265_4', '3--Not-a-difficulty', 'Sploh ni težava'],
		['Q265_5', '1--Major-difficulty', 'Večja težava'],
		['Q265_5', '2--Minor-difficulty', 'Manjša težava'],
		['Q265_5', '3--Not-a-difficulty', 'Sploh ni težava'],
		['Q265_6', '1--Major-difficulty', 'Večja težava'],
		['Q265_6', '2--Minor-difficulty', 'Manjša težava'],
		['Q265_6', '3--Not-a-difficulty', 'Sploh ni težava'],
		['Q265_7', '1--Major-difficulty', 'Večja težava'],
		['Q265_7', '2--Minor-difficulty', 'Manjša težava'],
		['Q265_7', '3--Not-a-difficulty', 'Sploh ni težava'],
		['Q300', '1--Yes', 'Da'],
		['Q300', '2--No', 'Ne'],
		['Q301', '1--Yes', 'Da'],
		['Q301', '2--No', 'Ne'],
		['Q302', '1--Yes', 'Da'],
		['Q302', '2--No', 'Ne'],
		['Q303_1', '1--Yes', 'Da'],
		['Q303_1', '2--No', 'Ne'],
		['Q303_2', '1--Yes', 'Da'],
		['Q303_2', '2--No', 'Ne'],
		['Q303_3', '1--Yes', 'Da'],
		['Q303_3', '2--No', 'Ne'],
		['Q303_4', '1--Yes', 'Da'],
		['Q303_4', '2--No', 'Ne'],
		['Q304', '1--Yes', 'Da'],
		['Q304', '2--No', 'Ne'],
		['Q304', '3--Partly', 'Delno'],
		['Q305', '1--Yes', 'Da'],
		['Q305', '2--No', 'Ne'],
		['Q306a_3', '1--Yes', 'Da'],
		['Q306a_3', '2--No', 'Ne'],
		['Q306a_4', '1--Yes', 'Da'],
		['Q306a_4', '2--No', 'Ne'],
		['Q306a_5', '1--Yes', 'Da'],
		['Q306a_5', '2--No', 'Ne'],
		['Q306a_6', '1--Yes', 'Da'],
		['Q306a_6', '2--No', 'Ne'],
		['Q307', '1--Yes', 'Da'],
		['Q307', '2--No', 'Ne'],
		['Q308_1', '1--Yes', 'Da'],
		['Q308_1', '2--No', 'Ne'],
		['Q308_2', '1--Yes', 'Da'],
		['Q308_2', '2--No', 'Ne'],
		['Q308_3', '1--Yes', 'Da'],
		['Q308_3', '2--No', 'Ne'],
		['Q308_4', '1--Yes', 'Da'],
		['Q308_4', '2--No', 'Ne'],
		['Q350', '1--Regularly', 'Redno'],
		['Q350', '2--Only-when-particular-issues-arise', 'Samo kadar se pojavijo določene težave. '],
		['Q350', '3--Not-at-all', 'Sploh ne potekajo. '],
		['Q351', '1--Often', 'Pogosto'],
		['Q351', '2--Sometimes', 'Včasih'],
		['Q351', '3--Practically-never', 'Skoraj nikoli'],
		['Q354', '1--Yes', 'Da'],
		['Q354', '2--No', 'Ne'],
		['Q354', '3--Yes--but-only-some-of-them', 'Da, vendar samo nekaterim'],
		['Q356_1', '1--Yes', 'Da'],
		['Q356_1', '2--No', 'Ne'],
		['Q356_2', '1--Yes', 'Da'],
		['Q356_2', '2--No', 'Ne'],
		['Q356_3', '1--Yes', 'Da'],
		['Q356_3', '2--No', 'Ne'],
		['Q356_4', '1--Yes', 'Da'],
		['Q356_4', '2--No', 'Ne'],
		['Q356_5', '1--Yes', 'Da'],
		['Q356_5', '2--No', 'Ne'],
		['Q358', '1--Yes', 'Da'],
		['Q358', '2--No', 'Ne'],
		['Q358', '3--In-some-departments-only', 'Samo v nekaterih oddelkih']
	];
var country_
	 = [
	
		['AL', 'Albanija'],
		['AT', 'Avstrija'],
		['BE', 'Belgija'],
		['BG', 'Bolgarija'],
		['CH', 'Švica'],
		['CY', 'Ciper'],
		['CZ', 'Češka republika'],
		['DE', 'Nemčija'],
		['DK', 'Danska'],
		['EE', 'Estonija'],
		['EL', 'Grčija'],
		['ES', 'Španija'],
		['FI', 'Finska'],
		['FR', 'Francija'],
		['HR', 'Hrvaška'],
		['HU', 'Madžarska'],
		['IE', 'Irska'],
		['IS', 'Islandija'],
		['IT', 'Italija'],
		['LT', 'Litva'],
		['LU', 'Luksemburg'],
		['LV', 'Latvija'],
		['ME', 'Črna gora'],
		['MK', 'FYR of Macedonia'],
		['MT', 'Malta'],
		['NL', 'Nizozemska'],
		['NO', 'Norveška'],
		['PL', 'Poljska'],
		['PT', 'Portugalska'],
		['RO', 'Romunija'],
		['RS', 'Srbija'],
		['SE', 'Švedska'],
		['SI', 'Slovenija'],
		['SK', 'Slovaška'],
		['TR', 'Turčija'],
		['UK', 'Združeno kraljestvo'],
		['EuropeanUnion', 'Evropska unija']
	];
var question_meta
	 = [
	
		['Q200_1', 'Utrujajoči ali boleči položaji, vključno z dolgotrajnim sedenjem', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Utrujajoči ali boleči položaji, vključno z dolgotrajnim sedenjem<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_2', 'Dvigovanje ali premikanje ljudi ali težkih bremen', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Dvigovanje ali premikanje ljudi ali težkih bremen<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_3', 'Močan hrup', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Močan hrup<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_4', 'Ponavljajoči se gibi dlani ali rok', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Ponavljajoči se gibi dlani ali rok<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_5', 'Vročina, mraz ali prepih', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Vročina, mraz ali prepih<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_6', 'Tveganje nesreč s stroji ali ročnim orodjem', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Tveganje nesreč s stroji ali ročnim orodjem<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_7', 'Tveganje nesreč z vozili med opravljanjem dela, vendar ne na poti na delo ali z njega ', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Tveganje nesreč z vozili med opravljanjem dela, vendar ne na poti na delo ali z njega <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_8', 'Kemične ali biološke snovi v obliki tekočin, hlapov ali prahu', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Kemične ali biološke snovi v obliki tekočin, hlapov ali prahu<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_9', 'Povečano tveganje zdrsov, spotikov in padcev ', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Povečano tveganje zdrsov, spotikov in padcev <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q201_1', 'Časovni pritisk    ', 'Poleg teh tveganj lahko obstajajo tudi zdravstvena tveganja, ki so posledica načina organizacije dela, medsebojnih odnosov pri delu ali ekonomskega položaja. Za vsakega izmed naslednjih tveganj mi povejte, ali je prisotno v poslovni enoti ali ne. Časovni pritisk    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q201_2', 'Slaba komunikacija ali sodelovanje znotraj organizacije    ', 'Poleg teh tveganj lahko obstajajo tudi zdravstvena tveganja, ki so posledica načina organizacije dela, medsebojnih odnosov pri delu ali ekonomskega položaja. Za vsakega izmed naslednjih tveganj mi povejte, ali je prisotno v poslovni enoti ali ne. Slaba komunikacija ali sodelovanje znotraj organizacije    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q201_3', 'Zaposleni nimajo vpliva na hitrost svojega dela ali na delovne procese    ', 'Poleg teh tveganj lahko obstajajo tudi zdravstvena tveganja, ki so posledica načina organizacije dela, medsebojnih odnosov pri delu ali ekonomskega položaja. Za vsakega izmed naslednjih tveganj mi povejte, ali je prisotno v poslovni enoti ali ne. Zaposleni nimajo vpliva na hitrost svojega dela ali na delovne procese    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q201_4', 'Negotovost zaposlitve    ', 'Poleg teh tveganj lahko obstajajo tudi zdravstvena tveganja, ki so posledica načina organizacije dela, medsebojnih odnosov pri delu ali ekonomskega položaja. Za vsakega izmed naslednjih tveganj mi povejte, ali je prisotno v poslovni enoti ali ne. Negotovost zaposlitve    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q201_5', 'Soočanje z zahtevnimi strankami, bolniki, učenci itd.    ', 'Poleg teh tveganj lahko obstajajo tudi zdravstvena tveganja, ki so posledica načina organizacije dela, medsebojnih odnosov pri delu ali ekonomskega položaja. Za vsakega izmed naslednjih tveganj mi povejte, ali je prisotno v poslovni enoti ali ne. Soočanje z zahtevnimi strankami, bolniki, učenci itd.    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q201_6', 'Dolg ali nereden delovni čas    ', 'Poleg teh tveganj lahko obstajajo tudi zdravstvena tveganja, ki so posledica načina organizacije dela, medsebojnih odnosov pri delu ali ekonomskega položaja. Za vsakega izmed naslednjih tveganj mi povejte, ali je prisotno v poslovni enoti ali ne. Dolg ali nereden delovni čas    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q201_7', 'Diskriminacija, na primer na podlagi spola, starosti ali narodnosti', 'Poleg teh tveganj lahko obstajajo tudi zdravstvena tveganja, ki so posledica načina organizacije dela, medsebojnih odnosov pri delu ali ekonomskega položaja. Za vsakega izmed naslednjih tveganj mi povejte, ali je prisotno v poslovni enoti ali ne. Diskriminacija, na primer na podlagi spola, starosti ali narodnosti<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q250', 'Ali se v vaši poslovni enoti redno izvajajo ocene tveganja na delovnem mestu?', 'Ali se v vaši poslovni enoti redno izvajajo ocene tveganja na delovnem mestu?<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q251', 'Ali ocene tveganja na delovnem mestu izvaja predvsem interno osebje ali jih izvajajo zunanji ponudniki storitev?', 'Ali ocene tveganja na delovnem mestu izvaja predvsem interno osebje ali jih izvajajo zunanji ponudniki storitev?<br><br>(1) Izvaja jih predvsem interno osebje. <br>(2) Izvajajo jih predvsem zunanji ponudniki. <br>(3) Oboji skoraj enakovredno <br>(9) Brez odgovora<br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da redno izvajajo ocene tveganja.'],
		['Q264_1', 'Izpolnjevanje zakonske obveznosti   ', 'Kako pomembni so v vaši poslovni enoti naslednji razlogi za obravnavo vprašanj varnosti in zdravja pri delu? Za vsak razlog mi, prosim, povejte, ali je to zelo pomemben razlog, manj pomemben razlog ali sploh ni razlog. Izpolnjevanje zakonske obveznosti   <br><br>(1) Zelo pomemben razlog <br>(2) Manj pomemben razlog <br>(3) Sploh ni razlog <br>(9) Brez odgovora '],
		['Q264_2', 'Izpolnjevanje pričakovanj zaposlenih ali njihovih predstavnikov ', 'Kako pomembni so v vaši poslovni enoti naslednji razlogi za obravnavo vprašanj varnosti in zdravja pri delu? Za vsak razlog mi, prosim, povejte, ali je to zelo pomemben razlog, manj pomemben razlog ali sploh ni razlog. Izpolnjevanje pričakovanj zaposlenih ali njihovih predstavnikov <br><br>(1) Zelo pomemben razlog <br>(2) Manj pomemben razlog <br>(3) Sploh ni razlog <br>(9) Brez odgovora '],
		['Q264_4', 'Ohranjanje ali rast produktivnosti   ', 'Kako pomembni so v vaši poslovni enoti naslednji razlogi za obravnavo vprašanj varnosti in zdravja pri delu? Za vsak razlog mi, prosim, povejte, ali je to zelo pomemben razlog, manj pomemben razlog ali sploh ni razlog. Ohranjanje ali rast produktivnosti   <br><br>(1) Zelo pomemben razlog <br>(2) Manj pomemben razlog <br>(3) Sploh ni razlog <br>(9) Brez odgovora '],
		['Q264_5', 'Ohranjanje dobrega slovesa organizacije   ', 'Kako pomembni so v vaši poslovni enoti naslednji razlogi za obravnavo vprašanj varnosti in zdravja pri delu? Za vsak razlog mi, prosim, povejte, ali je to zelo pomemben razlog, manj pomemben razlog ali sploh ni razlog. Ohranjanje dobrega slovesa organizacije   <br><br>(1) Zelo pomemben razlog <br>(2) Manj pomemben razlog <br>(3) Sploh ni razlog <br>(9) Brez odgovora '],
		['Q264_6', 'Izogibanje globam in sankcijam Inšpektorata RS za delo', 'Kako pomembni so v vaši poslovni enoti naslednji razlogi za obravnavo vprašanj varnosti in zdravja pri delu? Za vsak razlog mi, prosim, povejte, ali je to zelo pomemben razlog, manj pomemben razlog ali sploh ni razlog. Izogibanje globam in sankcijam Inšpektorata RS za delo<br><br>(1) Zelo pomemben razlog <br>(2) Manj pomemben razlog <br>(3) Sploh ni razlog <br>(9) Brez odgovora '],
		['Q307', 'Ali imate v vaši poslovni enoti dovolj informacij o tem, kako vključiti psihosocialna tveganja v ocene tveganja?', 'Ali imate v vaši poslovni enoti dovolj informacij o tem, kako vključiti psihosocialna tveganja v ocene tveganja?<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q150_1', 'Zdravnik specialist medicine dela', 'Katere storitve zagotavljanja varnosti in zdravja pri delu uporabljate, bodisi so to interne storitve ali storitve zunanjih izvajalcev? Zdravnik specialist medicine dela<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q150_2', 'Psiholog', 'Katere storitve zagotavljanja varnosti in zdravja pri delu uporabljate, bodisi so to interne storitve ali storitve zunanjih izvajalcev? Psiholog<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q150_3', 'Strokovnjak za ergonomsko oblikovanje in ureditev delovnega okolja ', 'Katere storitve zagotavljanja varnosti in zdravja pri delu uporabljate, bodisi so to interne storitve ali storitve zunanjih izvajalcev? Strokovnjak za ergonomsko oblikovanje in ureditev delovnega okolja <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q150_4', 'Splošni strokovnjak za varnost in zdravje pri delu', 'Katere storitve zagotavljanja varnosti in zdravja pri delu uporabljate, bodisi so to interne storitve ali storitve zunanjih izvajalcev? Splošni strokovnjak za varnost in zdravje pri delu<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q150_5', 'Strokovnjak na področju preprečevanja nezgod pri delu', 'Katere storitve zagotavljanja varnosti in zdravja pri delu uporabljate, bodisi so to interne storitve ali storitve zunanjih izvajalcev? Strokovnjak na področju preprečevanja nezgod pri delu<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q155', 'Ali je dokument, v katerem so pojasnjene odgovornosti in postopki zagotavljanja varnosti in zdravja pri delu na voljo osebam, ki delajo v poslovni enoti?', 'Ali je dokument, v katerem so pojasnjene odgovornosti in postopki zagotavljanja varnosti in zdravja pri delu na voljo osebam, ki delajo v poslovni enoti?<br><br>(1) Da <br>(2) Ne <br>(3) Da, toda samo nekaterim zaposlenim <br>(9) Brez odgovora '],
		['Q156', 'Ali v vaši poslovni enoti vsako leto sprejmete poseben proračun, namenjen kritju stroškov izvajanja ukrepov in nakupa opreme za zagotavljanje varnosti in zdravja pri delu?', 'Ali v vaši poslovni enoti vsako leto sprejmete poseben proračun, namenjen kritju stroškov izvajanja ukrepov in nakupa opreme za zagotavljanje varnosti in zdravja pri delu?<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q158_1', 'Ozaveščanje o zdravi prehrani', 'Ali vaša poslovna enota izvaja katere koli izmed naslednjih ukrepov za promocijo zdravja med zaposlenimi? Ozaveščanje o zdravi prehrani<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q158_2', 'Ozaveščanje o preprečevanju zasvojenosti, npr. s kajenjem, alkoholom ali drogami ', 'Ali vaša poslovna enota izvaja katere koli izmed naslednjih ukrepov za promocijo zdravja med zaposlenimi? Ozaveščanje o preprečevanju zasvojenosti, npr. s kajenjem, alkoholom ali drogami <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q158_3', 'Spodbujanje športnih dejavnosti izven delovnega časa', 'Ali vaša poslovna enota izvaja katere koli izmed naslednjih ukrepov za promocijo zdravja med zaposlenimi? Spodbujanje športnih dejavnosti izven delovnega časa<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q158_4', 'Spodbujanje izvajanja vaj za hrbet, raztezanja ali drugih telesnih vaj na delovnem mestu', 'Ali vaša poslovna enota izvaja katere koli izmed naslednjih ukrepov za promocijo zdravja med zaposlenimi? Spodbujanje izvajanja vaj za hrbet, raztezanja ali drugih telesnih vaj na delovnem mestu<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q160', 'Ali se primeri bolniške odsotnosti z dela redno analizirajo, da bi se izboljšali delovni pogoji?', 'Ali se primeri bolniške odsotnosti z dela redno analizirajo, da bi se izboljšali delovni pogoji?<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q165', 'Ali je vašo poslovno enoto v zadnjih 3 letih obiskal Inšpektorat RS za delo, da bi preveril razmere na področju varnosti in zdravja pri delu?', 'Ali je vašo poslovno enoto v zadnjih 3 letih obiskal Inšpektorat RS za delo, da bi preveril razmere na področju varnosti in zdravja pri delu?<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_1', 'Utrujajoči ali boleči položaji, vključno z dolgotrajnim sedenjem', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Utrujajoči ali boleči položaji, vključno z dolgotrajnim sedenjem<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_2', 'Dvigovanje ali premikanje ljudi ali težkih bremen', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Dvigovanje ali premikanje ljudi ali težkih bremen<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_3', 'Močan hrup', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Močan hrup<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_4', 'Ponavljajoči se gibi dlani ali rok', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Ponavljajoči se gibi dlani ali rok<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_5', 'Vročina, mraz ali prepih', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Vročina, mraz ali prepih<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_6', 'Tveganje nesreč s stroji ali ročnim orodjem', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Tveganje nesreč s stroji ali ročnim orodjem<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_7', 'Tveganje nesreč z vozili med opravljanjem dela, vendar ne na poti na delo ali z njega ', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Tveganje nesreč z vozili med opravljanjem dela, vendar ne na poti na delo ali z njega <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_8', 'Kemične ali biološke snovi v obliki tekočin, hlapov ali prahu', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Kemične ali biološke snovi v obliki tekočin, hlapov ali prahu<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q200_9', 'Povečano tveganje zdrsov, spotikov in padcev ', 'Obstajajo različne vrste tveganj in nevarnosti, ki so odvisne od vrste dela. Za vsakega izmed naslednjih dejavnikov tveganja mi povejte, ali obstaja v vaši poslovni enoti ali ne, in to ne glede na to, ali je trenutno pod nadzorom, in ne glede na število zaposlenih, na katere vpliva. Povečano tveganje zdrsov, spotikov in padcev <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q202_1', 'Utrujajoči ali boleči položaji, vključno z dolgotrajnim sedenjem', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Utrujajoči ali boleči položaji, vključno z dolgotrajnim sedenjem<br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik tveganja.'],
		['Q202_2', 'Dvigovanje ali premikanje ljudi ali težkih bremen', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Dvigovanje ali premikanje ljudi ali težkih bremen<br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik tveganja.'],
		['Q202_3', 'Močan hrup', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Močan hrup<br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik tveganja.'],
		['Q202_4', 'Ponavljajoči se gibi dlani ali rok', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Ponavljajoči se gibi dlani ali rok<br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik tveganja.'],
		['Q202_5', 'Vročina, mraz ali prepih', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Vročina, mraz ali prepih<br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik tveganja.'],
		['Q202_6', 'Tveganje nesreč s stroji ali ročnim orodjem', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Tveganje nesreč s stroji ali ročnim orodjem<br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik tveganja.'],
		['Q202_7', 'Tveganje nesreč z vozili med opravljanjem dela, vendar ne na poti na delo ali z njega ', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Tveganje nesreč z vozili med opravljanjem dela, vendar ne na poti na delo ali z njega <br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik tveganja.'],
		['Q202_8', 'Kemične ali biološke snovi v obliki tekočin, hlapov ali prahu', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Kemične ali biološke snovi v obliki tekočin, hlapov ali prahu<br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik tveganja.'],
		['Q202_9', 'Povečano tveganje zdrsov, spotikov in padcev ', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Povečano tveganje zdrsov, spotikov in padcev <br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik tveganja.'],
		['Q250', 'Ali se v vaši poslovni enoti redno izvajajo ocene tveganja na delovnem mestu?', 'Ali se v vaši poslovni enoti redno izvajajo ocene tveganja na delovnem mestu?<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q251', 'Ali ocene tveganja na delovnem mestu izvaja predvsem interno osebje ali jih izvajajo zunanji ponudniki storitev?', 'Ali ocene tveganja na delovnem mestu izvaja predvsem interno osebje ali jih izvajajo zunanji ponudniki storitev?<br><br>(1) Izvaja jih predvsem interno osebje. <br>(2) Izvajajo jih predvsem zunanji ponudniki. <br>(3) Oboji skoraj enakovredno <br>(9) Brez odgovora<br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da redno izvajajo ocene tveganja.'],
		['Q252_1', 'Varnost strojev, opreme in naprav    ', 'Kateri od naslednjih vidikov se redno preverjajo v teh ocenah tveganja na delovnem mestu? Varnost strojev, opreme in naprav    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da redno izvajajo ocene tveganja.'],
		['Q252_2', 'Nevarnost kemičnih ali bioloških snovi    ', 'Kateri od naslednjih vidikov se redno preverjajo v teh ocenah tveganja na delovnem mestu? Nevarnost kemičnih ali bioloških snovi    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da redno izvajajo ocene tveganja.'],
		['Q252_3', 'Telesna drža med delom, telesni napor in ponavljajoči se gibi    ', 'Kateri od naslednjih vidikov se redno preverjajo v teh ocenah tveganja na delovnem mestu? Telesna drža med delom, telesni napor in ponavljajoči se gibi    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da redno izvajajo ocene tveganja.'],
		['Q252_4', 'Izpostavljenost hrupu, vibracijam, vročini ali mrazu    ', 'Kateri od naslednjih vidikov se redno preverjajo v teh ocenah tveganja na delovnem mestu? Izpostavljenost hrupu, vibracijam, vročini ali mrazu    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da redno izvajajo ocene tveganja.'],
		['Q252_5', 'Odnosi med nadzornim osebjem in zaposlenimi    ', 'Kateri od naslednjih vidikov se redno preverjajo v teh ocenah tveganja na delovnem mestu? Odnosi med nadzornim osebjem in zaposlenimi    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da redno izvajajo ocene tveganja.'],
		['Q252_6', 'Organizacijski vidiki, kot sodelovni razporedi, odmori ali delovne izmene', 'Kateri od naslednjih vidikov se redno preverjajo v teh ocenah tveganja na delovnem mestu? Organizacijski vidiki, kot sodelovni razporedi, odmori ali delovne izmene<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da redno izvajajo ocene tveganja.'],
		['Q254gr', 'Katerega leta je bila opravljena zadnja ocena tveganja na delovnem mestu?', 'Katerega leta je bila opravljena zadnja ocena tveganja na delovnem mestu?<br><br>(Leto) <br>(9998) Ne vem. <br>(9999) Brez odgovora<br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da redno izvajajo ocene tveganja.'],
		['Q255', 'Ali je bila ocena dokumentirana v pisni obliki?', 'Ali je bila ocena dokumentirana v pisni obliki?<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da je bila zadnja ocena tveganja na delovnem mestu opravljena po letu 1970.'],
		['Q256_1', 'Vodstvo', 'Kdo je prejel ugotovitve ocene tveganja na delovnem mestu? Vodstvo<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da je bila zadnja ocena tveganja na delovnem mestu opravljena po letu 1970.'],
		['Q256_2', 'Delavski zaupniki za varnost in zdravje pri delu', 'Kdo je prejel ugotovitve ocene tveganja na delovnem mestu? Delavski zaupniki za varnost in zdravje pri delu<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da je bila zadnja ocena tveganja na delovnem mestu opravljena po letu 1970 in da imajo delavske zaupnike za varnost in zdravje pri delu.'],
		['Q256_3', 'Svet delavcev', 'Kdo je prejel ugotovitve ocene tveganja na delovnem mestu? Svet delavcev<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da je bila zadnja ocena tveganja na delovnem mestu opravljena po letu 1970 in da imajo svet delavcev.'],
		['Q256_4', 'Sindikalni zaupniki ', 'Kdo je prejel ugotovitve ocene tveganja na delovnem mestu? Sindikalni zaupniki <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da je bila zadnja ocena tveganja na delovnem mestu opravljena po letu 1970 in da imajo sindikalno zastopanje.'],
		['Q256_5', 'Zaposleni ', 'Kdo je prejel ugotovitve ocene tveganja na delovnem mestu? Zaposleni <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da je bila zadnja ocena tveganja na delovnem mestu opravljena po letu 1970.'],
		['Q259', 'Ali v vaši poslovni enoti prevladuje mnenje, da je postopek ocene tveganja koristen način upravljanja varnosti in zdravja pri delu?', 'Ali v vaši poslovni enoti prevladuje mnenje, da je postopek ocene tveganja koristen način upravljanja varnosti in zdravja pri delu?<br><br>(1) Da <br>(2) Ne <br>(3) Mnenja o tem so si nasprotujoča. <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da redno izvajajo ocene tveganja.'],
		['Q261_1', 'Nevarnosti in tveganja so tako ali tako že znani.   ', 'Ali obstajajo kakršni koli posebni razlogi za to, da se ocene tveganja na delovnem mestu ne izvajajo redno? Za vsako izmed naslednjih trditev mi povejte, ali velja tudi za vašo poslovno enoto ali ne. Nevarnosti in tveganja so tako ali tako že znani.   <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki niso navedle, da redno izvajajo ocene tveganja.'],
		['Q261_2', 'Ni večjih težav.   ', 'Ali obstajajo kakršni koli posebni razlogi za to, da se ocene tveganja na delovnem mestu ne izvajajo redno? Za vsako izmed naslednjih trditev mi povejte, ali velja tudi za vašo poslovno enoto ali ne. Ni večjih težav.   <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki niso navedle, da redno izvajajo ocene tveganja.'],
		['Q261_3', 'Postopek je prevečtežaven.   ', 'Ali obstajajo kakršni koli posebni razlogi za to, da se ocene tveganja na delovnem mestu ne izvajajo redno? Za vsako izmed naslednjih trditev mi povejte, ali velja tudi za vašo poslovno enoto ali ne. Postopek je prevečtežaven.   <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki niso navedle, da redno izvajajo ocene tveganja.'],
		['Q261_4', 'Ni potrebnega strokovnega znanja.', 'Ali obstajajo kakršni koli posebni razlogi za to, da se ocene tveganja na delovnem mestu ne izvajajo redno? Za vsako izmed naslednjih trditev mi povejte, ali velja tudi za vašo poslovno enoto ali ne. Ni potrebnega strokovnega znanja.<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki niso navedle, da redno izvajajo ocene tveganja.'],
		['Q308_1', 'Oprema za pomočpri dvigovanju ali premikanju bremen ali drugih fizično težkih delih ', 'Ali so v vaši poslovni enoti vzpostavljeni kateri koli izmed naslednjih preventivnih ukrepov za preprečevanje kostno-mišičnih težav, kot so bolečine v hrbtu, vratu, rokah, dlaneh ali nogah? Oprema za pomočpri dvigovanju ali premikanju bremen ali drugih fizično težkih delih <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so kot dejavnik tveganja navedle dvigovanje ali premikanje ljudi ali težkih bremen.'],
		['Q308_2', 'Kroženje oziroma menjavanje zaposlenih pri opravljanju nalog z namenom, da se zmanjša obseg ponavljajočih se gibov ali telesni napor pri posamezniku ', 'Ali so v vaši poslovni enoti vzpostavljeni kateri koli izmed naslednjih preventivnih ukrepov za preprečevanje kostno-mišičnih težav, kot so bolečine v hrbtu, vratu, rokah, dlaneh ali nogah? Kroženje oziroma menjavanje zaposlenih pri opravljanju nalog z namenom, da se zmanjša obseg ponavljajočih se gibov ali telesni napor pri posamezniku <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so kot dejavnik tveganja navedle ponavljajoče se gibe dlani ali rok.'],
		['Q308_3', 'Spodbujanje koriščenja rednih premorov pri opravljanju del v neudobni ali nepremični telesni drži, vključno z dolgotrajnim sedenjem ', 'Ali so v vaši poslovni enoti vzpostavljeni kateri koli izmed naslednjih preventivnih ukrepov za preprečevanje kostno-mišičnih težav, kot so bolečine v hrbtu, vratu, rokah, dlaneh ali nogah? Spodbujanje koriščenja rednih premorov pri opravljanju del v neudobni ali nepremični telesni drži, vključno z dolgotrajnim sedenjem <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q308_4', 'Zagotovitev ergonomske opreme, kot so posebni stoli ali mize', 'Ali so v vaši poslovni enoti vzpostavljeni kateri koli izmed naslednjih preventivnih ukrepov za preprečevanje kostno-mišičnih težav, kot so bolečine v hrbtu, vratu, rokah, dlaneh ali nogah? Zagotovitev ergonomske opreme, kot so posebni stoli ali mize<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q356_1', 'Ustrezna raba delovne opreme in pohištva ter njihove prilagoditve ', 'V zvezi s katerimi izmed naslednjih tem vaša poslovna enota zaposlenim zagotavlja usposabljanje? Ustrezna raba delovne opreme in pohištva ter njihove prilagoditve <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q356_2', 'Uporaba nevarnih snovi', 'V zvezi s katerimi izmed naslednjih tem vaša poslovna enota zaposlenim zagotavlja usposabljanje? Uporaba nevarnih snovi<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q356_3', 'Kako preprečevati psihosocialna tveganja, kot je stres ali ustrahovanje ', 'V zvezi s katerimi izmed naslednjih tem vaša poslovna enota zaposlenim zagotavlja usposabljanje? Kako preprečevati psihosocialna tveganja, kot je stres ali ustrahovanje <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q356_4', 'Kako dvigati ali premikati težka bremena ali ljudi', 'V zvezi s katerimi izmed naslednjih tem vaša poslovna enota zaposlenim zagotavlja usposabljanje? Kako dvigati ali premikati težka bremena ali ljudi<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q356_5', 'Postopki za ravnanje v nujnih primerih', 'V zvezi s katerimi izmed naslednjih tem vaša poslovna enota zaposlenim zagotavlja usposabljanje? Postopki za ravnanje v nujnih primerih<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q201_1', 'Časovni pritisk    ', 'Poleg teh tveganj lahko obstajajo tudi zdravstvena tveganja, ki so posledica načina organizacije dela, medsebojnih odnosov pri delu ali ekonomskega položaja. Za vsakega izmed naslednjih tveganj mi povejte, ali je prisotno v poslovni enoti ali ne. Časovni pritisk    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q201_2', 'Slaba komunikacija ali sodelovanje znotraj organizacije    ', 'Poleg teh tveganj lahko obstajajo tudi zdravstvena tveganja, ki so posledica načina organizacije dela, medsebojnih odnosov pri delu ali ekonomskega položaja. Za vsakega izmed naslednjih tveganj mi povejte, ali je prisotno v poslovni enoti ali ne. Slaba komunikacija ali sodelovanje znotraj organizacije    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q201_3', 'Zaposleni nimajo vpliva na hitrost svojega dela ali na delovne procese    ', 'Poleg teh tveganj lahko obstajajo tudi zdravstvena tveganja, ki so posledica načina organizacije dela, medsebojnih odnosov pri delu ali ekonomskega položaja. Za vsakega izmed naslednjih tveganj mi povejte, ali je prisotno v poslovni enoti ali ne. Zaposleni nimajo vpliva na hitrost svojega dela ali na delovne procese    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q201_4', 'Negotovost zaposlitve    ', 'Poleg teh tveganj lahko obstajajo tudi zdravstvena tveganja, ki so posledica načina organizacije dela, medsebojnih odnosov pri delu ali ekonomskega položaja. Za vsakega izmed naslednjih tveganj mi povejte, ali je prisotno v poslovni enoti ali ne. Negotovost zaposlitve    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q201_5', 'Soočanje z zahtevnimi strankami, bolniki, učenci itd.    ', 'Poleg teh tveganj lahko obstajajo tudi zdravstvena tveganja, ki so posledica načina organizacije dela, medsebojnih odnosov pri delu ali ekonomskega položaja. Za vsakega izmed naslednjih tveganj mi povejte, ali je prisotno v poslovni enoti ali ne. Soočanje z zahtevnimi strankami, bolniki, učenci itd.    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q201_6', 'Dolg ali nereden delovni čas    ', 'Poleg teh tveganj lahko obstajajo tudi zdravstvena tveganja, ki so posledica načina organizacije dela, medsebojnih odnosov pri delu ali ekonomskega položaja. Za vsakega izmed naslednjih tveganj mi povejte, ali je prisotno v poslovni enoti ali ne. Dolg ali nereden delovni čas    <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q201_7', 'Diskriminacija, na primer na podlagi spola, starosti ali narodnosti', 'Poleg teh tveganj lahko obstajajo tudi zdravstvena tveganja, ki so posledica načina organizacije dela, medsebojnih odnosov pri delu ali ekonomskega položaja. Za vsakega izmed naslednjih tveganj mi povejte, ali je prisotno v poslovni enoti ali ne. Diskriminacija, na primer na podlagi spola, starosti ali narodnosti<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q202_10', 'Časovni pritisk    ', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Časovni pritisk    <br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik psihosocialnega tveganja.'],
		['Q202_11', 'Slaba komunikacija ali sodelovanje znotraj organizacije    ', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Slaba komunikacija ali sodelovanje znotraj organizacije    <br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik psihosocialnega tveganja.'],
		['Q202_12', 'Zaposleni nimajo vpliva na hitrost svojega dela ali na delovne procese    ', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Zaposleni nimajo vpliva na hitrost svojega dela ali na delovne procese    <br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik psihosocialnega tveganja.'],
		['Q202_13', 'Negotovost zaposlitve    ', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Negotovost zaposlitve    <br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik psihosocialnega tveganja.'],
		['Q202_14', 'Soočanje z zahtevnimi strankami, bolniki, učenci itd.    ', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Soočanje z zahtevnimi strankami, bolniki, učenci itd.    <br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik psihosocialnega tveganja.'],
		['Q202_15', 'Dolg ali nereden delovni čas    ', 'Za katerega izmed tveganj - če sploh za katerega - vaša poslovna enota nima dovolj informacij ali ustreznih orodij za njegovo preprečevanje ali da bi se z njim učinkovito soočila? Dolg ali nereden delovni čas    <br><br>(1) Da <br>(2) Ne <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo ta dejavnik psihosocialnega tveganja.'],
		['Q300', 'Ali imate v poslovni enoti vzpostavljen akcijski načrt za preprečevanje stresa, povezanega z delom?', 'Ali imate v poslovni enoti vzpostavljen akcijski načrt za preprečevanje stresa, povezanega z delom?<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam z 20 ali več zaposlenimi.'],
		['Q301', 'Ali obstaja postopek za obravnavo morebitnih primerov ustrahovanja in nadlegovanja?', 'Ali obstaja postopek za obravnavo morebitnih primerov ustrahovanja in nadlegovanja?<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam z 20 ali več zaposlenimi.'],
		['Q302', 'Ali obstaja postopek za reševanje morebitnih primerov groženj, zlorab ali napadov s strani strank, pacientov, učencev ali drugih zunanjih oseb?', 'Ali obstaja postopek za reševanje morebitnih primerov groženj, zlorab ali napadov s strani strank, pacientov, učencev ali drugih zunanjih oseb?<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam z 20 ali več zaposlenimi, ki so kot dejavnik tveganja navedle soočanje z zahtevnimi strankami, bolniki, učenci.'],
		['Q303_1', 'Reorganizacija dela z namenom zmanjšanja zahtev delovnega mesta in pritiska na delu ', 'Ali je v zadnjih treh letih vaša poslovna enota uporabila katerega od naslednjih ukrepov za preprečevanje psihosocialnih tveganj? Reorganizacija dela z namenom zmanjšanja zahtev delovnega mesta in pritiska na delu <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q303_2', 'Zaupno svetovanje za zaposlene   ', 'Ali je v zadnjih treh letih vaša poslovna enota uporabila katerega od naslednjih ukrepov za preprečevanje psihosocialnih tveganj? Zaupno svetovanje za zaposlene   <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q303_3', 'Vzpostavitev postopka za reševanje sporov   ', 'Ali je v zadnjih treh letih vaša poslovna enota uporabila katerega od naslednjih ukrepov za preprečevanje psihosocialnih tveganj? Vzpostavitev postopka za reševanje sporov   <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q303_4', 'Posredovanje v primeru dolgega ali nerednega delovnega časa', 'Ali je v zadnjih treh letih vaša poslovna enota uporabila katerega od naslednjih ukrepov za preprečevanje psihosocialnih tveganj? Posredovanje v primeru dolgega ali nerednega delovnega časa<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q307', 'Ali imate v vaši poslovni enoti dovolj informacij o tem, kako vključiti psihosocialna tveganja v ocene tveganja?', 'Ali imate v vaši poslovni enoti dovolj informacij o tem, kako vključiti psihosocialna tveganja v ocene tveganja?<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora '],
		['Q264_1', 'Izpolnjevanje zakonske obveznosti   ', 'Kako pomembni so v vaši poslovni enoti naslednji razlogi za obravnavo vprašanj varnosti in zdravja pri delu? Za vsak razlog mi, prosim, povejte, ali je to zelo pomemben razlog, manj pomemben razlog ali sploh ni razlog. Izpolnjevanje zakonske obveznosti   <br><br>(1) Zelo pomemben razlog <br>(2) Manj pomemben razlog <br>(3) Sploh ni razlog <br>(9) Brez odgovora '],
		['Q264_2', 'Izpolnjevanje pričakovanj zaposlenih ali njihovih predstavnikov ', 'Kako pomembni so v vaši poslovni enoti naslednji razlogi za obravnavo vprašanj varnosti in zdravja pri delu? Za vsak razlog mi, prosim, povejte, ali je to zelo pomemben razlog, manj pomemben razlog ali sploh ni razlog. Izpolnjevanje pričakovanj zaposlenih ali njihovih predstavnikov <br><br>(1) Zelo pomemben razlog <br>(2) Manj pomemben razlog <br>(3) Sploh ni razlog <br>(9) Brez odgovora '],
		['Q264_4', 'Ohranjanje ali rast produktivnosti   ', 'Kako pomembni so v vaši poslovni enoti naslednji razlogi za obravnavo vprašanj varnosti in zdravja pri delu? Za vsak razlog mi, prosim, povejte, ali je to zelo pomemben razlog, manj pomemben razlog ali sploh ni razlog. Ohranjanje ali rast produktivnosti   <br><br>(1) Zelo pomemben razlog <br>(2) Manj pomemben razlog <br>(3) Sploh ni razlog <br>(9) Brez odgovora '],
		['Q264_5', 'Ohranjanje dobrega slovesa organizacije   ', 'Kako pomembni so v vaši poslovni enoti naslednji razlogi za obravnavo vprašanj varnosti in zdravja pri delu? Za vsak razlog mi, prosim, povejte, ali je to zelo pomemben razlog, manj pomemben razlog ali sploh ni razlog. Ohranjanje dobrega slovesa organizacije   <br><br>(1) Zelo pomemben razlog <br>(2) Manj pomemben razlog <br>(3) Sploh ni razlog <br>(9) Brez odgovora '],
		['Q264_6', 'Izogibanje globam in sankcijam Inšpektorata RS za delo', 'Kako pomembni so v vaši poslovni enoti naslednji razlogi za obravnavo vprašanj varnosti in zdravja pri delu? Za vsak razlog mi, prosim, povejte, ali je to zelo pomemben razlog, manj pomemben razlog ali sploh ni razlog. Izogibanje globam in sankcijam Inšpektorata RS za delo<br><br>(1) Zelo pomemben razlog <br>(2) Manj pomemben razlog <br>(3) Sploh ni razlog <br>(9) Brez odgovora '],
		['Q265_1', 'Pomanjkanje časa ali osebja', 'Katere so glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu v vaši poslovni enoti? Za vsako izmed naslednjih možnosti mi, prosim, povejte, ali predstavlja večjo težavo, manjšo težavo ali sploh ni težava. Pomanjkanje časa ali osebja<br><br>(1) Večja težava <br>(2) Manjša težava <br>(3) Sploh ni težava <br>(9) Brez odgovora '],
		['Q265_2', 'Pomanjkanje denarja', 'Katere so glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu v vaši poslovni enoti? Za vsako izmed naslednjih možnosti mi, prosim, povejte, ali predstavlja večjo težavo, manjšo težavo ali sploh ni težava. Pomanjkanje denarja<br><br>(1) Večja težava <br>(2) Manjša težava <br>(3) Sploh ni težava <br>(9) Brez odgovora '],
		['Q265_3', 'Pomanjkanje ozaveščenosti med osebjem', 'Katere so glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu v vaši poslovni enoti? Za vsako izmed naslednjih možnosti mi, prosim, povejte, ali predstavlja večjo težavo, manjšo težavo ali sploh ni težava. Pomanjkanje ozaveščenosti med osebjem<br><br>(1) Večja težava <br>(2) Manjša težava <br>(3) Sploh ni težava <br>(9) Brez odgovora '],
		['Q265_4', 'Pomanjkanje ozaveščenosti med vodilnim kadrom ', 'Katere so glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu v vaši poslovni enoti? Za vsako izmed naslednjih možnosti mi, prosim, povejte, ali predstavlja večjo težavo, manjšo težavo ali sploh ni težava. Pomanjkanje ozaveščenosti med vodilnim kadrom <br><br>(1) Večja težava <br>(2) Manjša težava <br>(3) Sploh ni težava <br>(9) Brez odgovora '],
		['Q265_5', 'Pomanjkanje strokovnega znanja ali podpore strokovnjakov', 'Katere so glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu v vaši poslovni enoti? Za vsako izmed naslednjih možnosti mi, prosim, povejte, ali predstavlja večjo težavo, manjšo težavo ali sploh ni težava. Pomanjkanje strokovnega znanja ali podpore strokovnjakov<br><br>(1) Večja težava <br>(2) Manjša težava <br>(3) Sploh ni težava <br>(9) Brez odgovora '],
		['Q265_6', 'Papirologija', 'Katere so glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu v vaši poslovni enoti? Za vsako izmed naslednjih možnosti mi, prosim, povejte, ali predstavlja večjo težavo, manjšo težavo ali sploh ni težava. Papirologija<br><br>(1) Večja težava <br>(2) Manjša težava <br>(3) Sploh ni težava <br>(9) Brez odgovora '],
		['Q265_7', 'Zahtevnost pravnih obveznosti', 'Katere so glavne težave pri obravnavi vprašanj varnosti in zdravja pri delu v vaši poslovni enoti? Za vsako izmed naslednjih možnosti mi, prosim, povejte, ali predstavlja večjo težavo, manjšo težavo ali sploh ni težava. Zahtevnost pravnih obveznosti<br><br>(1) Večja težava <br>(2) Manjša težava <br>(3) Sploh ni težava <br>(9) Brez odgovora '],
		['Q304', 'Ali so bili sprejeti ukrepi posledica konkretnih težav s stresom, ustrahovanjem, nadlegovanjem ali nasiljem v poslovni enoti?', 'Ali so bili sprejeti ukrepi posledica konkretnih težav s stresom, ustrahovanjem, nadlegovanjem ali nasiljem v poslovni enoti?<br><br>(1) Da <br>(2) Ne <br>(8) Delno <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da so v zadnjih treh letih uvedle katerega od ukrepov za preprečevanje psihosocialnih tveganj.'],
		['Q306a_3', 'Pomanjkanje ozaveščenosti med osebjem   ', 'Če pomislite na stanje v vaši poslovni enoti: Ali je zaradi katerega od naslednjih dejavnikov psihosocialna tveganja težje obravnavati kot druga zdravstvena tveganja? Pomanjkanje ozaveščenosti med osebjem   <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo enega od navedenih dejavnikov psihosocialnega tveganja.'],
		['Q306a_4', 'Pomanjkanje ozaveščenosti med vodilnim kadrom   ', 'Če pomislite na stanje v vaši poslovni enoti: Ali je zaradi katerega od naslednjih dejavnikov psihosocialna tveganja težje obravnavati kot druga zdravstvena tveganja? Pomanjkanje ozaveščenosti med vodilnim kadrom   <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo enega od navedenih dejavnikov psihosocialnega tveganja.'],
		['Q306a_5', 'Pomanjkanje strokovnega znanja ali podpore strokovnjakov   ', 'Če pomislite na stanje v vaši poslovni enoti: Ali je zaradi katerega od naslednjih dejavnikov psihosocialna tveganja težje obravnavati kot druga zdravstvena tveganja? Pomanjkanje strokovnega znanja ali podpore strokovnjakov   <br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo enega od navedenih dejavnikov psihosocialnega tveganja.'],
		['Q306a_6', 'Nepripravljenost na odkrit pogovor o teh težavah', 'Če pomislite na stanje v vaši poslovni enoti: Ali je zaradi katerega od naslednjih dejavnikov psihosocialna tveganja težje obravnavati kot druga zdravstvena tveganja? Nepripravljenost na odkrit pogovor o teh težavah<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo enega od navedenih dejavnikov psihosocialnega tveganja.'],
		['Q166_1', 'Svet delavcev', 'Katero izmed naslednjih oblik delavskega zastopanja imate v tej poslovni enoti? Svet delavcev<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno vsem, velikost je odvisna od nacionalnih pragov za te organe.'],
		['Q166_2', 'Sindikalno zastopanje', 'Katero izmed naslednjih oblik delavskega zastopanja imate v tej poslovni enoti? Sindikalno zastopanje<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno vsem, velikost je odvisna od nacionalnih pragov za te organe.'],
		['Q166_3', 'Delavski zaupnik za varnost in zdravje pri delu', 'Katero izmed naslednjih oblik delavskega zastopanja imate v tej poslovni enoti? Delavski zaupnik za varnost in zdravje pri delu<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno vsem, velikost je odvisna od nacionalnih pragov za te organe.'],
		['Q166_4', '(A health and safety committee)', 'This form of employee representation doesn’t exist in this country.<br><br>Katero izmed naslednjih oblik delavskega zastopanja imate v tej poslovni enoti? (A health and safety committee)<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno vsem, velikost je odvisna od nacionalnih pragov za te organe.'],
		['Q258b', 'Če je treba po oceni tveganja sprejeti ukrepe: Ali zaposleni običajno sodelujejo pri njihovem oblikovanju in izvajanju?', 'Če je treba po oceni tveganja sprejeti ukrepe: Ali zaposleni običajno sodelujejo pri njihovem oblikovanju in izvajanju?<br><br>(1) Da <br>(2) Ne <br>(4) To je odvisno od vrste ukrepov. <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da redno izvajajo ocene tveganja.'],
		['Q305', 'Ali so zaposleni sodelovali pri oblikovanju in vzpostavitvi ukrepov za obvladovanje psihosocialnih tveganj?', 'Ali so zaposleni sodelovali pri oblikovanju in vzpostavitvi ukrepov za obvladovanje psihosocialnih tveganj?<br><br>(1) Da <br>(2) Ne <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da so v zadnjih treh letih uvedle katerega od ukrepov za preprečevanje psihosocialnih tveganj.'],
		['Q350', 'Kako pogosto sta varnost in zdravje pri delu predmet razprav med predstavniki delavcev in vodstvom? Ali takšne razprave potekajo redno, samo kadar se pojavijo določene težave v zvezi z varnostjo in zdravjem pri delu ali pa sploh ne potekajo?', 'Kako pogosto sta varnost in zdravje pri delu predmet razprav med predstavniki delavcev in vodstvom? Ali takšne razprave potekajo redno, samo kadar se pojavijo določene težave v zvezi z varnostjo in zdravjem pri delu ali pa sploh ne potekajo?<br><br>(1) Redno <br>(2) Samo kadar se pojavijo določene težave. <br>(3) Sploh ne potekajo. <br>(7) Ni relevantno (ni predstavnikov delavcev). <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo nekatere oblike delavskega zastopanja.'],
		['Q351', 'In kako pogosto pride do polemik v zvezi z varnostjo in zdravjem pri delu? Se to dogaja pogosto, včasih ali skoraj nikoli?', 'In kako pogosto pride do polemik v zvezi z varnostjo in zdravjem pri delu? Se to dogaja pogosto, včasih ali skoraj nikoli?<br><br>(1) Pogosto <br>(2) Včasih <br>(3) Skoraj nikoli <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da predstavniki delavcev in vodstvo razpravljajo o vprašanjih varnosti in zdravja pri delu.'],
		['Q354', 'Ali je delavskim zaupnikom za varnost in zdravje pri delu zagotovljeno kakršno koli usposabljanje med delovnim časom, ki jim lahko pomaga pri opravljanju njihovih nalog na področju varnosti in zdravja pri delu?', 'Ali je delavskim zaupnikom za varnost in zdravje pri delu zagotovljeno kakršno koli usposabljanje med delovnim časom, ki jim lahko pomaga pri opravljanju njihovih nalog na področju varnosti in zdravja pri delu?<br><br>(1) Da <br>(2) Ne <br>(3) Da, vendar samo nekaterim <br>(9) Brez odgovora <br><br>Vprašanje, zastavljeno poslovnim enotam, ki so navedle, da imajo delavske zaupnike za varnost in zdravje pri delu.'],
		['Q358', 'Ali se o vprašanjih, povezanih z varnostjo in zdravjem pri delu, redno razpravlja na sestankih zaposlenih ali sestankih skupin?', 'Ali se o vprašanjih, povezanih z varnostjo in zdravjem pri delu, redno razpravlja na sestankih zaposlenih ali sestankih skupin?<br><br>(1) Da <br>(2) Ne <br>(3) Samo v nekaterih oddelkih <br>(9) Brez odgovora ']
	];
