//Auto Generated file
var subset_
	 = [
	
		['Size', 'Arbetsplatsens storlek'],
		['Sectorgrp', 'Verksamhetssektor']
	];
var subset_subsetValue
	 = [
	
		['Sectorgrp', 'All', 'Alla'],
		['Sectorgrp', '1--A', 'Jordbruk, skogsbruk och fiske'],
		['Sectorgrp', '2--BDEF', 'Byggverksamhet, avfallshantering, vatten- och elförsörjning'],
		['Sectorgrp', '3--C', 'Tillverkning'],
		['Sectorgrp', '4--GHIR', 'Handel, transport, hotell- och restaurangverksamhet samt fritidsverksamheter'],
		['Sectorgrp', '5--JKLMNS', 'It-verksamhet, finansiell verksamhet, fastighetsverksamhet och andra tekniska och vetenskapliga verksamheter eller personliga tjänster'],
		['Sectorgrp', '6--O', 'Offentlig förvaltning'],
		['Sectorgrp', '7--PQ', 'Utbildning, vård och omsorg samt sociala tjänster'],
		['Size', 'All', 'Alla'],
		['Size', '1--5-to-9', '5 till 9 medarbetare'],
		['Size', '2--10-to-49', '10 till 49 medarbetare'],
		['Size', '3--50-249', '50 till 249 medarbetare'],
		['Size', '4--250-', '250 eller fler medarbetare']
	];
var topic_
	 = [
	
		['', 'Alla (108)'],
		['Arbetsmiljöstyrning', 'Arbetsmiljöstyrning (60)'],
		['Arbetstagarinflytande', 'Arbetstagarinflytande (10)'],
		['De viktigaste resultaten', 'De viktigaste resultaten (24)'],
		['Drivkrafter och hinder', 'Drivkrafter och hinder (17)'],
		['Psykosociala risker och hantering av dem', 'Psykosociala risker och hantering av dem (21)']
	];
var topic_question
	 = [
	
		['De viktigaste resultaten', 'Q200_1', 'Riskfaktorer på arbetsplatsen: Tröttande eller smärtsamma positioner'],
		['De viktigaste resultaten', 'Q200_2', 'Riskfaktorer på arbetsplatsen: Lyftande eller förflyttande av människor eller tunga laster'],
		['De viktigaste resultaten', 'Q200_3', 'Riskfaktorer på arbetsplatsen: Högt buller'],
		['De viktigaste resultaten', 'Q200_4', 'Riskfaktorer på arbetsplatsen: Enformiga hand- eller armrörelser'],
		['De viktigaste resultaten', 'Q200_5', 'Riskfaktorer på arbetsplatsen: Värme, kyla eller drag'],
		['De viktigaste resultaten', 'Q200_6', 'Riskfaktorer på arbetsplatsen: Risk för olycksfall med maskiner eller handverktyg'],
		['De viktigaste resultaten', 'Q200_7', 'Riskfaktorer på arbetsplatsen: Risk för olycksfall med fordon under arbetet'],
		['De viktigaste resultaten', 'Q200_8', 'Riskfaktorer på arbetsplatsen: Kemikalier eller biologiskt material'],
		['De viktigaste resultaten', 'Q200_9', 'Riskfaktorer på arbetsplatsen: Ökad risk för att halka, snubbla och falla'],
		['De viktigaste resultaten', 'Q201_1', 'Psykosociala riskfaktorer på arbetsplatsen: Tidspress'],
		['De viktigaste resultaten', 'Q201_2', 'Psykosociala riskfaktorer på arbetsplatsen: Dålig kommunikation eller dåligt samarbete'],
		['De viktigaste resultaten', 'Q201_3', 'Psykosociala riskfaktorer på arbetsplatsen: Medarbetares brist på inflytande'],
		['De viktigaste resultaten', 'Q201_4', 'Psykosociala riskfaktorer på arbetsplatsen: Otryggt arbete'],
		['De viktigaste resultaten', 'Q201_5', 'Psykosociala riskfaktorer på arbetsplatsen: Svåra kunder, patienter, elever'],
		['De viktigaste resultaten', 'Q201_6', 'Psykosociala riskfaktorer på arbetsplatsen: Långa eller oregelbundna arbetstider'],
		['De viktigaste resultaten', 'Q201_7', 'Psykosociala riskfaktorer på arbetsplatsen: Diskriminering'],
		['De viktigaste resultaten', 'Q250', 'Riskbedömningar av arbetsplatsen'],
		['De viktigaste resultaten', 'Q251', 'Riskbedömningar utförs främst av intern personal eller av externa tjänsteleverantörer'],
		['De viktigaste resultaten', 'Q264_1', 'Anledningar att ta itu med arbetsmiljön: Uppfylla rättsliga förpliktelser'],
		['De viktigaste resultaten', 'Q264_2', 'Anledningar att ta itu med arbetsmiljön: Leva upp till förväntningar från medarbetare'],
		['De viktigaste resultaten', 'Q264_4', 'Anledningar att ta itu med arbetsmiljön: Öka produktiviteten'],
		['De viktigaste resultaten', 'Q264_5', 'Anledningar att ta itu med arbetsmiljön: Organisationens rykte'],
		['De viktigaste resultaten', 'Q264_6', 'Anledningar att ta itu med arbetsmiljön: Undvika böter från arbetsmiljömyndigheten'],
		['De viktigaste resultaten', 'Q307', 'Tillräckligt med information om hur psykosociala risker inkluderas i riskbedömningar'],
		['Arbetsmiljöstyrning', 'Q150_1', 'Användning av tjänster för arbetsmiljö: En företagshälsovårdsläkare'],
		['Arbetsmiljöstyrning', 'Q150_2', 'Användning av tjänster för arbetsmiljö: En psykolog'],
		['Arbetsmiljöstyrning', 'Q150_3', 'Användning av tjänster för arbetsmiljö: En expert som arbetar med ergonomisk design och arbetsplatsergonomi'],
		['Arbetsmiljöstyrning', 'Q150_4', 'Användning av tjänster för arbetsmiljö: En generalist inom hälsa och säkerhet'],
		['Arbetsmiljöstyrning', 'Q150_5', 'Användning av tjänster för arbetsmiljö: En expert inom olycksförebyggande åtgärder'],
		['Arbetsmiljöstyrning', 'Q155', 'Handling  där det redogörs för ansvarsområden och rutiner för arbetsmiljö är tillgänglig för dem som arbetar på arbetsplatsen'],
		['Arbetsmiljöstyrning', 'Q156', 'En särskild budget avsätts varje år för åtgärder och utrustning inom arbetsmiljöområdet'],
		['Arbetsmiljöstyrning', 'Q158_1', 'Åtgärder för att förbättra medarbetarnas hälsa: Åtgärder för att öka medvetenheten om hälsosamma matvanor '],
		['Arbetsmiljöstyrning', 'Q158_2', 'Åtgärder för att förbättra medarbetarnas hälsa: Åtgärder för att öka medvetenheten om hur man kan förebygga beroenden'],
		['Arbetsmiljöstyrning', 'Q158_3', 'Åtgärder för att förbättra medarbetarnas hälsa: Åtgärder för att främja idrottsaktiviteter utanför arbetstid'],
		['Arbetsmiljöstyrning', 'Q158_4', 'Åtgärder för att förbättra medarbetarnas hälsa: Åtgärder för att främja fysiska aktiviteter på arbetet'],
		['Arbetsmiljöstyrning', 'Q160', 'Regelbunden analys av sjukfrånvaro'],
		['Arbetsmiljöstyrning', 'Q165', 'Besök av arbetsmiljömyndigheten under de senaste tre åren i syfte att kontrollera hälso- och säkerhetsförhållandena'],
		['Arbetsmiljöstyrning', 'Q200_1', 'Riskfaktorer på arbetsplatsen: Tröttande eller smärtsamma positioner'],
		['Arbetsmiljöstyrning', 'Q200_2', 'Riskfaktorer på arbetsplatsen: Lyftande eller förflyttande av människor eller tunga laster'],
		['Arbetsmiljöstyrning', 'Q200_3', 'Riskfaktorer på arbetsplatsen: Högt buller'],
		['Arbetsmiljöstyrning', 'Q200_4', 'Riskfaktorer på arbetsplatsen: Enformiga hand- eller armrörelser'],
		['Arbetsmiljöstyrning', 'Q200_5', 'Riskfaktorer på arbetsplatsen: Värme, kyla eller drag'],
		['Arbetsmiljöstyrning', 'Q200_6', 'Riskfaktorer på arbetsplatsen: Risk för olycksfall med maskiner eller handverktyg'],
		['Arbetsmiljöstyrning', 'Q200_7', 'Riskfaktorer på arbetsplatsen: Risk för olycksfall med fordon under arbetet'],
		['Arbetsmiljöstyrning', 'Q200_8', 'Riskfaktorer på arbetsplatsen: Kemikalier eller biologiskt material'],
		['Arbetsmiljöstyrning', 'Q200_9', 'Riskfaktorer på arbetsplatsen: Ökad risk för att halka, snubbla och falla'],
		['Arbetsmiljöstyrning', 'Q202_1', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Tröttande eller smärtsamma positioner'],
		['Arbetsmiljöstyrning', 'Q202_2', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Lyftande eller förflyttande av människor eller tunga laster'],
		['Arbetsmiljöstyrning', 'Q202_3', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Högt buller'],
		['Arbetsmiljöstyrning', 'Q202_4', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Enformiga hand- eller armrörelser'],
		['Arbetsmiljöstyrning', 'Q202_5', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Värme, kyla eller drag'],
		['Arbetsmiljöstyrning', 'Q202_6', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Risk för olycksfall med maskiner eller handverktyg'],
		['Arbetsmiljöstyrning', 'Q202_7', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Risk för olycksfall med fordon under arbetet'],
		['Arbetsmiljöstyrning', 'Q202_8', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Kemikalier eller biologiskt material'],
		['Arbetsmiljöstyrning', 'Q202_9', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Ökad risk för att halka, snubbla och falla'],
		['Arbetsmiljöstyrning', 'Q250', 'Riskbedömningar av arbetsplatsen'],
		['Arbetsmiljöstyrning', 'Q251', 'Riskbedömningar utförs främst av intern personal eller av externa tjänsteleverantörer'],
		['Arbetsmiljöstyrning', 'Q252_1', 'Aspekter som utvärderas i riskbedömningar av arbetsplatsen: Maskin-, utrustnings- och anläggningssäkerhet'],
		['Arbetsmiljöstyrning', 'Q252_2', 'Aspekter som utvärderas i riskbedömningar av arbetsplatsen: Farliga ämnen'],
		['Arbetsmiljöstyrning', 'Q252_3', 'Aspekter som utvärderas i riskbedömningar av arbetsplatsen: Arbetsställningar, fysiska arbetskrav och enformiga rörelser'],
		['Arbetsmiljöstyrning', 'Q252_4', 'Aspekter som utvärderas i riskbedömningar av arbetsplatsen: Exponering för buller, vibrationer, värme eller kyla'],
		['Arbetsmiljöstyrning', 'Q252_5', 'Aspekter som utvärderas i riskbedömningar av arbetsplatsen: Relationer mellan överordnade och andra medarbetare'],
		['Arbetsmiljöstyrning', 'Q252_6', 'Aspekter som utvärderas i riskbedömningar av arbetsplatsen: Organisatoriska aspekter'],
		['Arbetsmiljöstyrning', 'Q254gr', 'År för den senaste riskbedömningen av arbetsplatsen'],
		['Arbetsmiljöstyrning', 'Q255', 'Riskbedömning av arbetsplatsen skriftligt dokumenterad'],
		['Arbetsmiljöstyrning', 'Q256_1', 'Personer som fått ta del av resultaten från riskbedömningar av arbetsplatsen: Ledningen'],
		['Arbetsmiljöstyrning', 'Q256_2', 'Personer som fått ta del av resultaten från riskbedömningar av arbetsplatsen: Skyddsombuden'],
		['Arbetsmiljöstyrning', 'Q256_3', 'Personer som fått ta del av resultaten från riskbedömningar av arbetsplatsen: (The works council)'],
		['Arbetsmiljöstyrning', 'Q256_4', 'Personer som fått ta del av resultaten från riskbedömningar av arbetsplatsen: Fackliga förtroendemän'],
		['Arbetsmiljöstyrning', 'Q256_5', 'Personer som fått ta del av resultaten från riskbedömningar av arbetsplatsen: Medarbetarna själva'],
		['Arbetsmiljöstyrning', 'Q259', 'Riskbedömningar betraktas som ett användbart tillvägagångssätt för att hantera arbetsmiljö'],
		['Arbetsmiljöstyrning', 'Q261_1', 'Anledningar till att riskbedömningar av arbetsplatsen inte genomförs regelbundet: Farorna och riskerna är redan kända'],
		['Arbetsmiljöstyrning', 'Q261_2', 'Anledningar till att riskbedömningar av arbetsplatsen inte genomförs regelbundet: Det finns inte några större problem'],
		['Arbetsmiljöstyrning', 'Q261_3', 'Anledningar till att riskbedömningar av arbetsplatsen inte genomförs regelbundet: Rutinerna är alltför betungande'],
		['Arbetsmiljöstyrning', 'Q261_4', 'Anledningar till att riskbedömningar av arbetsplatsen inte genomförs regelbundet: Den nödvändiga sakkunskapen saknas'],
		['Arbetsmiljöstyrning', 'Q308_1', 'Åtgärder för att förebygga muskel- och skelettbesvär: Utrustning som hjälper till vid lyft eller flytt av laster'],
		['Arbetsmiljöstyrning', 'Q308_2', 'Åtgärder för att förebygga muskel- och skelettbesvär: Arbetsrotation för att minska fysisk ansträngning'],
		['Arbetsmiljöstyrning', 'Q308_3', 'Åtgärder för att förebygga muskel- och skelettbesvär: Uppmaning till regelbundna raster för personer som arbetar i obekväma eller statiska kroppsställningar'],
		['Arbetsmiljöstyrning', 'Q308_4', 'Åtgärder för att förebygga muskel- och skelettbesvär: Tillhandahållande av ergonomisk utrustning'],
		['Arbetsmiljöstyrning', 'Q356_1', 'Utbildning av medarbetare: Korrekt användning och anpassning av arbetsutrustning och möbler'],
		['Arbetsmiljöstyrning', 'Q356_2', 'Utbildning av medarbetare: Hantering av farliga ämnen'],
		['Arbetsmiljöstyrning', 'Q356_3', 'Utbildning av medarbetare: Hur man förebygger psykosociala risker'],
		['Arbetsmiljöstyrning', 'Q356_4', 'Utbildning av medarbetare: Hur man lyfter och flyttar tunga laster eller personer'],
		['Arbetsmiljöstyrning', 'Q356_5', 'Utbildning av medarbetare: Nödfallsrutiner'],
		['Psykosociala risker och hantering av dem', 'Q201_1', 'Psykosociala riskfaktorer på arbetsplatsen: Tidspress'],
		['Psykosociala risker och hantering av dem', 'Q201_2', 'Psykosociala riskfaktorer på arbetsplatsen: Dålig kommunikation eller dåligt samarbete'],
		['Psykosociala risker och hantering av dem', 'Q201_3', 'Psykosociala riskfaktorer på arbetsplatsen: Medarbetares brist på inflytande'],
		['Psykosociala risker och hantering av dem', 'Q201_4', 'Psykosociala riskfaktorer på arbetsplatsen: Otryggt arbete'],
		['Psykosociala risker och hantering av dem', 'Q201_5', 'Psykosociala riskfaktorer på arbetsplatsen: Svåra kunder, patienter, elever'],
		['Psykosociala risker och hantering av dem', 'Q201_6', 'Psykosociala riskfaktorer på arbetsplatsen: Långa eller oregelbundna arbetstider'],
		['Psykosociala risker och hantering av dem', 'Q201_7', 'Psykosociala riskfaktorer på arbetsplatsen: Diskriminering'],
		['Psykosociala risker och hantering av dem', 'Q202_10', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Tidspress'],
		['Psykosociala risker och hantering av dem', 'Q202_11', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Dålig kommunikation eller dåligt samarbete'],
		['Psykosociala risker och hantering av dem', 'Q202_12', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Medarbetares brist på inflytande'],
		['Psykosociala risker och hantering av dem', 'Q202_13', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Otryggt arbete'],
		['Psykosociala risker och hantering av dem', 'Q202_14', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Svåra kunder, patienter, elever'],
		['Psykosociala risker och hantering av dem', 'Q202_15', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Långa eller oregelbundna arbetstider'],
		['Psykosociala risker och hantering av dem', 'Q300', 'Åtgärdsplan för att förebygga arbetsrelaterad stress'],
		['Psykosociala risker och hantering av dem', 'Q301', 'Rutiner för att hantera eventuella fall av mobbning eller trakasserier'],
		['Psykosociala risker och hantering av dem', 'Q302', 'Rutiner för att hantera eventuella fall av hot, övergrepp eller attacker'],
		['Psykosociala risker och hantering av dem', 'Q303_1', 'Åtgärder för att förebygga psykosociala risker under de senaste 3 åren: Utfört en omorganisering av arbete för att minska arbetskravoch belastning'],
		['Psykosociala risker och hantering av dem', 'Q303_2', 'Åtgärder för att förebygga psykosociala risker under de senaste 3 åren: Erbjudit sekretessbelagd rådgivning för medarbetare'],
		['Psykosociala risker och hantering av dem', 'Q303_3', 'Åtgärder för att förebygga psykosociala risker under de senaste 3 åren: Etablerat rutiner för konfliktlösning'],
		['Psykosociala risker och hantering av dem', 'Q303_4', 'Åtgärder för att förebygga psykosociala risker under de senaste 3 åren: Ingripit om någon har arbetat överdrivet länge eller på oregelbundna tider'],
		['Psykosociala risker och hantering av dem', 'Q307', 'Tillräckligt med information om hur psykosociala risker inkluderas i riskbedömningar'],
		['Drivkrafter och hinder', 'Q264_1', 'Anledningar att ta itu med arbetsmiljön: Uppfylla rättsliga förpliktelser'],
		['Drivkrafter och hinder', 'Q264_2', 'Anledningar att ta itu med arbetsmiljön: Leva upp till förväntningar från medarbetare'],
		['Drivkrafter och hinder', 'Q264_4', 'Anledningar att ta itu med arbetsmiljön: Öka produktiviteten'],
		['Drivkrafter och hinder', 'Q264_5', 'Anledningar att ta itu med arbetsmiljön: Organisationens rykte'],
		['Drivkrafter och hinder', 'Q264_6', 'Anledningar att ta itu med arbetsmiljön: Undvika böter från arbetsmiljömyndigheten'],
		['Drivkrafter och hinder', 'Q265_1', 'De största svårigheterna med att hantera arbetsmiljö: Tids- eller personalbrist'],
		['Drivkrafter och hinder', 'Q265_2', 'De största svårigheterna med att hantera arbetsmiljö: Brist på pengar'],
		['Drivkrafter och hinder', 'Q265_3', 'De största svårigheterna med att hantera arbetsmiljö: Bristande medvetenhet bland medarbetarna'],
		['Drivkrafter och hinder', 'Q265_4', 'De största svårigheterna med att hantera arbetsmiljö: Bristande medvetenhet i ledningen'],
		['Drivkrafter och hinder', 'Q265_5', 'De största svårigheterna med att hantera arbetsmiljö: Avsaknad av sakkunskap eller specialiststöd'],
		['Drivkrafter och hinder', 'Q265_6', 'De största svårigheterna med att hantera arbetsmiljö: Pappersarbetet'],
		['Drivkrafter och hinder', 'Q265_7', 'De största svårigheterna med att hantera arbetsmiljö: Komplicerade rättsliga förpliktelser'],
		['Drivkrafter och hinder', 'Q304', 'Åtgärder som utlösts av faktiska problem'],
		['Drivkrafter och hinder', 'Q306a_3', 'Svårigheter att hantera psykosociala risker: Bristande medvetenhet bland medarbetarna'],
		['Drivkrafter och hinder', 'Q306a_4', 'Svårigheter att hantera psykosociala risker: Bristande medvetenhet i ledningen'],
		['Drivkrafter och hinder', 'Q306a_5', 'Svårigheter att hantera psykosociala risker: Avsaknad av sakkunskap eller specialiststöd'],
		['Drivkrafter och hinder', 'Q306a_6', 'Svårigheter att hantera psykosociala risker: Motvilja mot att tala öppet om dessa frågor'],
		['Arbetstagarinflytande', 'Q166_1', 'Former av arbetstagarrepresentation: (A works council)'],
		['Arbetstagarinflytande', 'Q166_2', 'Former av arbetstagarrepresentation: En facklig förtroendeman'],
		['Arbetstagarinflytande', 'Q166_3', 'Former av arbetstagarrepresentation: Ett skyddsombud'],
		['Arbetstagarinflytande', 'Q166_4', 'Former av arbetstagarrepresentation: En arbetsmiljökommitté'],
		['Arbetstagarinflytande', 'Q258b', 'Medarbetare är delaktiga i utformningen av åtgärder efter en riskbedömning'],
		['Arbetstagarinflytande', 'Q305', 'Medarbetare har en roll i utformningen av åtgärder för att förebygga psykosociala risker'],
		['Arbetstagarinflytande', 'Q350', 'Hur ofta diskuteras arbetsmiljö av arbetstagarföreträdare och ledningen'],
		['Arbetstagarinflytande', 'Q351', 'Hur ofta uppstår meningsskiljaktigheter som rör arbetsmiljö'],
		['Arbetstagarinflytande', 'Q354', 'Skyddsombuden erbjuds någon form av utbildning under arbetstid'],
		['Arbetstagarinflytande', 'Q358', 'Arbetsmiljöfrågor diskuteras under personal- eller gruppmöten']
	];
var question_
	 = [
	
		['Q200_1', 'Riskfaktorer på arbetsplatsen: Tröttande eller smärtsamma positioner'],
		['Q200_2', 'Riskfaktorer på arbetsplatsen: Lyftande eller förflyttande av människor eller tunga laster'],
		['Q200_3', 'Riskfaktorer på arbetsplatsen: Högt buller'],
		['Q200_4', 'Riskfaktorer på arbetsplatsen: Enformiga hand- eller armrörelser'],
		['Q200_5', 'Riskfaktorer på arbetsplatsen: Värme, kyla eller drag'],
		['Q200_6', 'Riskfaktorer på arbetsplatsen: Risk för olycksfall med maskiner eller handverktyg'],
		['Q200_7', 'Riskfaktorer på arbetsplatsen: Risk för olycksfall med fordon under arbetet'],
		['Q200_8', 'Riskfaktorer på arbetsplatsen: Kemikalier eller biologiskt material'],
		['Q200_9', 'Riskfaktorer på arbetsplatsen: Ökad risk för att halka, snubbla och falla'],
		['Q201_1', 'Psykosociala riskfaktorer på arbetsplatsen: Tidspress'],
		['Q201_2', 'Psykosociala riskfaktorer på arbetsplatsen: Dålig kommunikation eller dåligt samarbete'],
		['Q201_3', 'Psykosociala riskfaktorer på arbetsplatsen: Medarbetares brist på inflytande'],
		['Q201_4', 'Psykosociala riskfaktorer på arbetsplatsen: Otryggt arbete'],
		['Q201_5', 'Psykosociala riskfaktorer på arbetsplatsen: Svåra kunder, patienter, elever'],
		['Q201_6', 'Psykosociala riskfaktorer på arbetsplatsen: Långa eller oregelbundna arbetstider'],
		['Q201_7', 'Psykosociala riskfaktorer på arbetsplatsen: Diskriminering'],
		['Q250', 'Riskbedömningar av arbetsplatsen'],
		['Q251', 'Riskbedömningar utförs främst av intern personal eller av externa tjänsteleverantörer'],
		['Q264_1', 'Anledningar att ta itu med arbetsmiljön: Uppfylla rättsliga förpliktelser'],
		['Q264_2', 'Anledningar att ta itu med arbetsmiljön: Leva upp till förväntningar från medarbetare'],
		['Q264_4', 'Anledningar att ta itu med arbetsmiljön: Öka produktiviteten'],
		['Q264_5', 'Anledningar att ta itu med arbetsmiljön: Organisationens rykte'],
		['Q264_6', 'Anledningar att ta itu med arbetsmiljön: Undvika böter från arbetsmiljömyndigheten'],
		['Q307', 'Tillräckligt med information om hur psykosociala risker inkluderas i riskbedömningar'],
		['Q150_1', 'Användning av tjänster för arbetsmiljö: En företagshälsovårdsläkare'],
		['Q150_2', 'Användning av tjänster för arbetsmiljö: En psykolog'],
		['Q150_3', 'Användning av tjänster för arbetsmiljö: En expert som arbetar med ergonomisk design och arbetsplatsergonomi'],
		['Q150_4', 'Användning av tjänster för arbetsmiljö: En generalist inom hälsa och säkerhet'],
		['Q150_5', 'Användning av tjänster för arbetsmiljö: En expert inom olycksförebyggande åtgärder'],
		['Q155', 'Handling  där det redogörs för ansvarsområden och rutiner för arbetsmiljö är tillgänglig för dem som arbetar på arbetsplatsen'],
		['Q156', 'En särskild budget avsätts varje år för åtgärder och utrustning inom arbetsmiljöområdet'],
		['Q158_1', 'Åtgärder för att förbättra medarbetarnas hälsa: Åtgärder för att öka medvetenheten om hälsosamma matvanor '],
		['Q158_2', 'Åtgärder för att förbättra medarbetarnas hälsa: Åtgärder för att öka medvetenheten om hur man kan förebygga beroenden'],
		['Q158_3', 'Åtgärder för att förbättra medarbetarnas hälsa: Åtgärder för att främja idrottsaktiviteter utanför arbetstid'],
		['Q158_4', 'Åtgärder för att förbättra medarbetarnas hälsa: Åtgärder för att främja fysiska aktiviteter på arbetet'],
		['Q160', 'Regelbunden analys av sjukfrånvaro'],
		['Q165', 'Besök av arbetsmiljömyndigheten under de senaste tre åren i syfte att kontrollera hälso- och säkerhetsförhållandena'],
		['Q200_1', 'Riskfaktorer på arbetsplatsen: Tröttande eller smärtsamma positioner'],
		['Q200_2', 'Riskfaktorer på arbetsplatsen: Lyftande eller förflyttande av människor eller tunga laster'],
		['Q200_3', 'Riskfaktorer på arbetsplatsen: Högt buller'],
		['Q200_4', 'Riskfaktorer på arbetsplatsen: Enformiga hand- eller armrörelser'],
		['Q200_5', 'Riskfaktorer på arbetsplatsen: Värme, kyla eller drag'],
		['Q200_6', 'Riskfaktorer på arbetsplatsen: Risk för olycksfall med maskiner eller handverktyg'],
		['Q200_7', 'Riskfaktorer på arbetsplatsen: Risk för olycksfall med fordon under arbetet'],
		['Q200_8', 'Riskfaktorer på arbetsplatsen: Kemikalier eller biologiskt material'],
		['Q200_9', 'Riskfaktorer på arbetsplatsen: Ökad risk för att halka, snubbla och falla'],
		['Q202_1', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Tröttande eller smärtsamma positioner'],
		['Q202_2', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Lyftande eller förflyttande av människor eller tunga laster'],
		['Q202_3', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Högt buller'],
		['Q202_4', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Enformiga hand- eller armrörelser'],
		['Q202_5', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Värme, kyla eller drag'],
		['Q202_6', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Risk för olycksfall med maskiner eller handverktyg'],
		['Q202_7', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Risk för olycksfall med fordon under arbetet'],
		['Q202_8', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Kemikalier eller biologiskt material'],
		['Q202_9', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Ökad risk för att halka, snubbla och falla'],
		['Q250', 'Riskbedömningar av arbetsplatsen'],
		['Q251', 'Riskbedömningar utförs främst av intern personal eller av externa tjänsteleverantörer'],
		['Q252_1', 'Aspekter som utvärderas i riskbedömningar av arbetsplatsen: Maskin-, utrustnings- och anläggningssäkerhet'],
		['Q252_2', 'Aspekter som utvärderas i riskbedömningar av arbetsplatsen: Farliga ämnen'],
		['Q252_3', 'Aspekter som utvärderas i riskbedömningar av arbetsplatsen: Arbetsställningar, fysiska arbetskrav och enformiga rörelser'],
		['Q252_4', 'Aspekter som utvärderas i riskbedömningar av arbetsplatsen: Exponering för buller, vibrationer, värme eller kyla'],
		['Q252_5', 'Aspekter som utvärderas i riskbedömningar av arbetsplatsen: Relationer mellan överordnade och andra medarbetare'],
		['Q252_6', 'Aspekter som utvärderas i riskbedömningar av arbetsplatsen: Organisatoriska aspekter'],
		['Q254gr', 'År för den senaste riskbedömningen av arbetsplatsen'],
		['Q255', 'Riskbedömning av arbetsplatsen skriftligt dokumenterad'],
		['Q256_1', 'Personer som fått ta del av resultaten från riskbedömningar av arbetsplatsen: Ledningen'],
		['Q256_2', 'Personer som fått ta del av resultaten från riskbedömningar av arbetsplatsen: Skyddsombuden'],
		['Q256_3', 'Personer som fått ta del av resultaten från riskbedömningar av arbetsplatsen: (The works council)'],
		['Q256_4', 'Personer som fått ta del av resultaten från riskbedömningar av arbetsplatsen: Fackliga förtroendemän'],
		['Q256_5', 'Personer som fått ta del av resultaten från riskbedömningar av arbetsplatsen: Medarbetarna själva'],
		['Q259', 'Riskbedömningar betraktas som ett användbart tillvägagångssätt för att hantera arbetsmiljö'],
		['Q261_1', 'Anledningar till att riskbedömningar av arbetsplatsen inte genomförs regelbundet: Farorna och riskerna är redan kända'],
		['Q261_2', 'Anledningar till att riskbedömningar av arbetsplatsen inte genomförs regelbundet: Det finns inte några större problem'],
		['Q261_3', 'Anledningar till att riskbedömningar av arbetsplatsen inte genomförs regelbundet: Rutinerna är alltför betungande'],
		['Q261_4', 'Anledningar till att riskbedömningar av arbetsplatsen inte genomförs regelbundet: Den nödvändiga sakkunskapen saknas'],
		['Q308_1', 'Åtgärder för att förebygga muskel- och skelettbesvär: Utrustning som hjälper till vid lyft eller flytt av laster'],
		['Q308_2', 'Åtgärder för att förebygga muskel- och skelettbesvär: Arbetsrotation för att minska fysisk ansträngning'],
		['Q308_3', 'Åtgärder för att förebygga muskel- och skelettbesvär: Uppmaning till regelbundna raster för personer som arbetar i obekväma eller statiska kroppsställningar'],
		['Q308_4', 'Åtgärder för att förebygga muskel- och skelettbesvär: Tillhandahållande av ergonomisk utrustning'],
		['Q356_1', 'Utbildning av medarbetare: Korrekt användning och anpassning av arbetsutrustning och möbler'],
		['Q356_2', 'Utbildning av medarbetare: Hantering av farliga ämnen'],
		['Q356_3', 'Utbildning av medarbetare: Hur man förebygger psykosociala risker'],
		['Q356_4', 'Utbildning av medarbetare: Hur man lyfter och flyttar tunga laster eller personer'],
		['Q356_5', 'Utbildning av medarbetare: Nödfallsrutiner'],
		['Q201_1', 'Psykosociala riskfaktorer på arbetsplatsen: Tidspress'],
		['Q201_2', 'Psykosociala riskfaktorer på arbetsplatsen: Dålig kommunikation eller dåligt samarbete'],
		['Q201_3', 'Psykosociala riskfaktorer på arbetsplatsen: Medarbetares brist på inflytande'],
		['Q201_4', 'Psykosociala riskfaktorer på arbetsplatsen: Otryggt arbete'],
		['Q201_5', 'Psykosociala riskfaktorer på arbetsplatsen: Svåra kunder, patienter, elever'],
		['Q201_6', 'Psykosociala riskfaktorer på arbetsplatsen: Långa eller oregelbundna arbetstider'],
		['Q201_7', 'Psykosociala riskfaktorer på arbetsplatsen: Diskriminering'],
		['Q202_10', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Tidspress'],
		['Q202_11', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Dålig kommunikation eller dåligt samarbete'],
		['Q202_12', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Medarbetares brist på inflytande'],
		['Q202_13', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Otryggt arbete'],
		['Q202_14', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Svåra kunder, patienter, elever'],
		['Q202_15', 'Avsaknad av information eller adekvata verktyg för att åtgärda risken på ett effektivt sätt: Långa eller oregelbundna arbetstider'],
		['Q300', 'Åtgärdsplan för att förebygga arbetsrelaterad stress'],
		['Q301', 'Rutiner för att hantera eventuella fall av mobbning eller trakasserier'],
		['Q302', 'Rutiner för att hantera eventuella fall av hot, övergrepp eller attacker'],
		['Q303_1', 'Åtgärder för att förebygga psykosociala risker under de senaste 3 åren: Utfört en omorganisering av arbete för att minska arbetskravoch belastning'],
		['Q303_2', 'Åtgärder för att förebygga psykosociala risker under de senaste 3 åren: Erbjudit sekretessbelagd rådgivning för medarbetare'],
		['Q303_3', 'Åtgärder för att förebygga psykosociala risker under de senaste 3 åren: Etablerat rutiner för konfliktlösning'],
		['Q303_4', 'Åtgärder för att förebygga psykosociala risker under de senaste 3 åren: Ingripit om någon har arbetat överdrivet länge eller på oregelbundna tider'],
		['Q307', 'Tillräckligt med information om hur psykosociala risker inkluderas i riskbedömningar'],
		['Q264_1', 'Anledningar att ta itu med arbetsmiljön: Uppfylla rättsliga förpliktelser'],
		['Q264_2', 'Anledningar att ta itu med arbetsmiljön: Leva upp till förväntningar från medarbetare'],
		['Q264_4', 'Anledningar att ta itu med arbetsmiljön: Öka produktiviteten'],
		['Q264_5', 'Anledningar att ta itu med arbetsmiljön: Organisationens rykte'],
		['Q264_6', 'Anledningar att ta itu med arbetsmiljön: Undvika böter från arbetsmiljömyndigheten'],
		['Q265_1', 'De största svårigheterna med att hantera arbetsmiljö: Tids- eller personalbrist'],
		['Q265_2', 'De största svårigheterna med att hantera arbetsmiljö: Brist på pengar'],
		['Q265_3', 'De största svårigheterna med att hantera arbetsmiljö: Bristande medvetenhet bland medarbetarna'],
		['Q265_4', 'De största svårigheterna med att hantera arbetsmiljö: Bristande medvetenhet i ledningen'],
		['Q265_5', 'De största svårigheterna med att hantera arbetsmiljö: Avsaknad av sakkunskap eller specialiststöd'],
		['Q265_6', 'De största svårigheterna med att hantera arbetsmiljö: Pappersarbetet'],
		['Q265_7', 'De största svårigheterna med att hantera arbetsmiljö: Komplicerade rättsliga förpliktelser'],
		['Q304', 'Åtgärder som utlösts av faktiska problem'],
		['Q306a_3', 'Svårigheter att hantera psykosociala risker: Bristande medvetenhet bland medarbetarna'],
		['Q306a_4', 'Svårigheter att hantera psykosociala risker: Bristande medvetenhet i ledningen'],
		['Q306a_5', 'Svårigheter att hantera psykosociala risker: Avsaknad av sakkunskap eller specialiststöd'],
		['Q306a_6', 'Svårigheter att hantera psykosociala risker: Motvilja mot att tala öppet om dessa frågor'],
		['Q166_1', 'Former av arbetstagarrepresentation: (A works council)'],
		['Q166_2', 'Former av arbetstagarrepresentation: En facklig förtroendeman'],
		['Q166_3', 'Former av arbetstagarrepresentation: Ett skyddsombud'],
		['Q166_4', 'Former av arbetstagarrepresentation: En arbetsmiljökommitté'],
		['Q258b', 'Medarbetare är delaktiga i utformningen av åtgärder efter en riskbedömning'],
		['Q305', 'Medarbetare har en roll i utformningen av åtgärder för att förebygga psykosociala risker'],
		['Q350', 'Hur ofta diskuteras arbetsmiljö av arbetstagarföreträdare och ledningen'],
		['Q351', 'Hur ofta uppstår meningsskiljaktigheter som rör arbetsmiljö'],
		['Q354', 'Skyddsombuden erbjuds någon form av utbildning under arbetstid'],
		['Q358', 'Arbetsmiljöfrågor diskuteras under personal- eller gruppmöten']
	];
var question_answer
	 = [
	
		['Q150_1', '1--Yes', 'Ja'],
		['Q150_1', '2--No', 'Nej'],
		['Q150_2', '1--Yes', 'Ja'],
		['Q150_2', '2--No', 'Nej'],
		['Q150_3', '1--Yes', 'Ja'],
		['Q150_3', '2--No', 'Nej'],
		['Q150_4', '1--Yes', 'Ja'],
		['Q150_4', '2--No', 'Nej'],
		['Q150_5', '1--Yes', 'Ja'],
		['Q150_5', '2--No', 'Nej'],
		['Q155', '1--Yes', 'Ja'],
		['Q155', '2--No', 'Nej'],
		['Q155', '3--Yes--but-only-to-some-types-of-employees', 'Ja, men bara för vissa medarbetarkategorier'],
		['Q156', '1--Yes', 'Ja'],
		['Q156', '2--No', 'Nej'],
		['Q158_1', '1--Yes', 'Ja'],
		['Q158_1', '2--No', 'Nej'],
		['Q158_2', '1--Yes', 'Ja'],
		['Q158_2', '2--No', 'Nej'],
		['Q158_3', '1--Yes', 'Ja'],
		['Q158_3', '2--No', 'Nej'],
		['Q158_4', '1--Yes', 'Ja'],
		['Q158_4', '2--No', 'Nej'],
		['Q160', '1--Yes', 'Ja'],
		['Q160', '2--No', 'Nej'],
		['Q165', '1--Yes', 'Ja'],
		['Q165', '2--No', 'Nej'],
		['Q166_1', '1--Yes', 'Ja'],
		['Q166_1', '2--No', 'Nej'],
		['Q166_2', '1--Yes', 'Ja'],
		['Q166_2', '2--No', 'Nej'],
		['Q166_3', '1--Yes', 'Ja'],
		['Q166_3', '2--No', 'Nej'],
		['Q166_4', '1--Yes', 'Ja'],
		['Q166_4', '2--No', 'Nej'],
		['Q200_1', '1--Yes', 'Ja'],
		['Q200_1', '2--No', 'Nej'],
		['Q200_2', '1--Yes', 'Ja'],
		['Q200_2', '2--No', 'Nej'],
		['Q200_3', '1--Yes', 'Ja'],
		['Q200_3', '2--No', 'Nej'],
		['Q200_4', '1--Yes', 'Ja'],
		['Q200_4', '2--No', 'Nej'],
		['Q200_5', '1--Yes', 'Ja'],
		['Q200_5', '2--No', 'Nej'],
		['Q200_6', '1--Yes', 'Ja'],
		['Q200_6', '2--No', 'Nej'],
		['Q200_7', '1--Yes', 'Ja'],
		['Q200_7', '2--No', 'Nej'],
		['Q200_8', '1--Yes', 'Ja'],
		['Q200_8', '2--No', 'Nej'],
		['Q200_9', '1--Yes', 'Ja'],
		['Q200_9', '2--No', 'Nej'],
		['Q201_1', '1--Yes', 'Ja'],
		['Q201_1', '2--No', 'Nej'],
		['Q201_2', '1--Yes', 'Ja'],
		['Q201_2', '2--No', 'Nej'],
		['Q201_3', '1--Yes', 'Ja'],
		['Q201_3', '2--No', 'Nej'],
		['Q201_4', '1--Yes', 'Ja'],
		['Q201_4', '2--No', 'Nej'],
		['Q201_5', '1--Yes', 'Ja'],
		['Q201_5', '2--No', 'Nej'],
		['Q201_6', '1--Yes', 'Ja'],
		['Q201_6', '2--No', 'Nej'],
		['Q201_7', '1--Yes', 'Ja'],
		['Q201_7', '2--No', 'Nej'],
		['Q202_1', '1--Yes', 'Ja'],
		['Q202_1', '2--No', 'Nej'],
		['Q202_10', '1--Yes', 'Ja'],
		['Q202_10', '2--No', 'Nej'],
		['Q202_11', '1--Yes', 'Ja'],
		['Q202_11', '2--No', 'Nej'],
		['Q202_12', '1--Yes', 'Ja'],
		['Q202_12', '2--No', 'Nej'],
		['Q202_13', '1--Yes', 'Ja'],
		['Q202_13', '2--No', 'Nej'],
		['Q202_14', '1--Yes', 'Ja'],
		['Q202_14', '2--No', 'Nej'],
		['Q202_15', '1--Yes', 'Ja'],
		['Q202_15', '2--No', 'Nej'],
		['Q202_2', '1--Yes', 'Ja'],
		['Q202_2', '2--No', 'Nej'],
		['Q202_3', '1--Yes', 'Ja'],
		['Q202_3', '2--No', 'Nej'],
		['Q202_4', '1--Yes', 'Ja'],
		['Q202_4', '2--No', 'Nej'],
		['Q202_5', '1--Yes', 'Ja'],
		['Q202_5', '2--No', 'Nej'],
		['Q202_6', '1--Yes', 'Ja'],
		['Q202_6', '2--No', 'Nej'],
		['Q202_7', '1--Yes', 'Ja'],
		['Q202_7', '2--No', 'Nej'],
		['Q202_8', '1--Yes', 'Ja'],
		['Q202_8', '2--No', 'Nej'],
		['Q202_9', '1--Yes', 'Ja'],
		['Q202_9', '2--No', 'Nej'],
		['Q250', '1--Yes', 'Ja'],
		['Q250', '2--No', 'Nej'],
		['Q251', '1--Conducted-mainly-by-internal-staff', 'De utförs främst av intern personal'],
		['Q251', '2--Contracted-mainly-to-external-providers', 'De utförs främst av externa tjänsteleverantörer'],
		['Q251', '3--Both-about-equally', 'Både och i ungefär samma utsträckning'],
		['Q252_1', '1--Yes', 'Ja'],
		['Q252_1', '2--No', 'Nej'],
		['Q252_2', '1--Yes', 'Ja'],
		['Q252_2', '2--No', 'Nej'],
		['Q252_3', '1--Yes', 'Ja'],
		['Q252_3', '2--No', 'Nej'],
		['Q252_4', '1--Yes', 'Ja'],
		['Q252_4', '2--No', 'Nej'],
		['Q252_5', '1--Yes', 'Ja'],
		['Q252_5', '2--No', 'Nej'],
		['Q252_6', '1--Yes', 'Ja'],
		['Q252_6', '2--No', 'Nej'],
		['Q254gr', '1--2010', '2010'],
		['Q254gr', '2--2011', '2011'],
		['Q254gr', '3--2012', '2012'],
		['Q254gr', '4--2013', '2013'],
		['Q254gr', '5--2014', '2014'],
		['Q254gr', '6--before-2010', 'före 2010'],
		['Q254gr', '7--don-t-know', 'Vet ej'],
		['Q255', '1--Yes', 'Ja'],
		['Q255', '2--No', 'Nej'],
		['Q256_1', '1--Yes', 'Ja'],
		['Q256_1', '2--No', 'Nej'],
		['Q256_2', '1--Yes', 'Ja'],
		['Q256_2', '2--No', 'Nej'],
		['Q256_3', '1--Yes', 'Ja'],
		['Q256_3', '2--No', 'Nej'],
		['Q256_4', '1--Yes', 'Ja'],
		['Q256_4', '2--No', 'Nej'],
		['Q256_5', '1--Yes', 'Ja'],
		['Q256_5', '2--No', 'Nej'],
		['Q258b', '1--Yes', 'Ja'],
		['Q258b', '2--No', 'Nej'],
		['Q258b', '3--That-depends-on-the-type-of-measures', 'Det beror på vilken typ av åtgärd det gäller'],
		['Q259', '1--Yes', 'Ja'],
		['Q259', '2--No', 'Nej'],
		['Q259', '3--There-are-conflicting-views-about-this', 'Det är delade åsikter om detta'],
		['Q261_1', '1--Yes', 'Ja'],
		['Q261_1', '2--No', 'Nej'],
		['Q261_2', '1--Yes', 'Ja'],
		['Q261_2', '2--No', 'Nej'],
		['Q261_3', '1--Yes', 'Ja'],
		['Q261_3', '2--No', 'Nej'],
		['Q261_4', '1--Yes', 'Ja'],
		['Q261_4', '2--No', 'Nej'],
		['Q264_1', '1--Major-reason', 'Mycket viktig'],
		['Q264_1', '2--Minor-reason', 'Mindre viktig'],
		['Q264_1', '3--Not-a-reason', 'Inte viktig alls'],
		['Q264_2', '1--Major-reason', 'Mycket viktig'],
		['Q264_2', '2--Minor-reason', 'Mindre viktig'],
		['Q264_2', '3--Not-a-reason', 'Inte viktig alls'],
		['Q264_4', '1--Major-reason', 'Mycket viktig'],
		['Q264_4', '2--Minor-reason', 'Mindre viktig'],
		['Q264_4', '3--Not-a-reason', 'Inte viktig alls'],
		['Q264_5', '1--Major-reason', 'Mycket viktig'],
		['Q264_5', '2--Minor-reason', 'Mindre viktig'],
		['Q264_5', '3--Not-a-reason', 'Inte viktig alls'],
		['Q264_6', '1--Major-reason', 'Mycket viktig'],
		['Q264_6', '2--Minor-reason', 'Mindre viktig'],
		['Q264_6', '3--Not-a-reason', 'Inte viktig alls'],
		['Q265_1', '1--Major-difficulty', 'Mycket svårt'],
		['Q265_1', '2--Minor-difficulty', 'Mindre svårt'],
		['Q265_1', '3--Not-a-difficulty', 'Inte alls svårt'],
		['Q265_2', '1--Major-difficulty', 'Mycket svårt'],
		['Q265_2', '2--Minor-difficulty', 'Mindre svårt'],
		['Q265_2', '3--Not-a-difficulty', 'Inte alls svårt'],
		['Q265_3', '1--Major-difficulty', 'Mycket svårt'],
		['Q265_3', '2--Minor-difficulty', 'Mindre svårt'],
		['Q265_3', '3--Not-a-difficulty', 'Inte alls svårt'],
		['Q265_4', '1--Major-difficulty', 'Mycket svårt'],
		['Q265_4', '2--Minor-difficulty', 'Mindre svårt'],
		['Q265_4', '3--Not-a-difficulty', 'Inte alls svårt'],
		['Q265_5', '1--Major-difficulty', 'Mycket svårt'],
		['Q265_5', '2--Minor-difficulty', 'Mindre svårt'],
		['Q265_5', '3--Not-a-difficulty', 'Inte alls svårt'],
		['Q265_6', '1--Major-difficulty', 'Mycket svårt'],
		['Q265_6', '2--Minor-difficulty', 'Mindre svårt'],
		['Q265_6', '3--Not-a-difficulty', 'Inte alls svårt'],
		['Q265_7', '1--Major-difficulty', 'Mycket svårt'],
		['Q265_7', '2--Minor-difficulty', 'Mindre svårt'],
		['Q265_7', '3--Not-a-difficulty', 'Inte alls svårt'],
		['Q300', '1--Yes', 'Ja'],
		['Q300', '2--No', 'Nej'],
		['Q301', '1--Yes', 'Ja'],
		['Q301', '2--No', 'Nej'],
		['Q302', '1--Yes', 'Ja'],
		['Q302', '2--No', 'Nej'],
		['Q303_1', '1--Yes', 'Ja'],
		['Q303_1', '2--No', 'Nej'],
		['Q303_2', '1--Yes', 'Ja'],
		['Q303_2', '2--No', 'Nej'],
		['Q303_3', '1--Yes', 'Ja'],
		['Q303_3', '2--No', 'Nej'],
		['Q303_4', '1--Yes', 'Ja'],
		['Q303_4', '2--No', 'Nej'],
		['Q304', '1--Yes', 'Ja'],
		['Q304', '2--No', 'Nej'],
		['Q304', '3--Partly', 'Delvis'],
		['Q305', '1--Yes', 'Ja'],
		['Q305', '2--No', 'Nej'],
		['Q306a_3', '1--Yes', 'Ja'],
		['Q306a_3', '2--No', 'Nej'],
		['Q306a_4', '1--Yes', 'Ja'],
		['Q306a_4', '2--No', 'Nej'],
		['Q306a_5', '1--Yes', 'Ja'],
		['Q306a_5', '2--No', 'Nej'],
		['Q306a_6', '1--Yes', 'Ja'],
		['Q306a_6', '2--No', 'Nej'],
		['Q307', '1--Yes', 'Ja'],
		['Q307', '2--No', 'Nej'],
		['Q308_1', '1--Yes', 'Ja'],
		['Q308_1', '2--No', 'Nej'],
		['Q308_2', '1--Yes', 'Ja'],
		['Q308_2', '2--No', 'Nej'],
		['Q308_3', '1--Yes', 'Ja'],
		['Q308_3', '2--No', 'Nej'],
		['Q308_4', '1--Yes', 'Ja'],
		['Q308_4', '2--No', 'Nej'],
		['Q350', '1--Regularly', 'Regelbundet'],
		['Q350', '2--Only-when-particular-issues-arise', 'Endast när särskilda hälso- och säkerhetsproblem uppstår'],
		['Q350', '3--Not-at-all', 'Inte alls'],
		['Q351', '1--Often', 'Ofta'],
		['Q351', '2--Sometimes', 'Ibland'],
		['Q351', '3--Practically-never', 'Praktiskt taget aldrig'],
		['Q354', '1--Yes', 'Ja'],
		['Q354', '2--No', 'Nej'],
		['Q354', '3--Yes--but-only-some-of-them', 'Ja, men endast vissa av dem'],
		['Q356_1', '1--Yes', 'Ja'],
		['Q356_1', '2--No', 'Nej'],
		['Q356_2', '1--Yes', 'Ja'],
		['Q356_2', '2--No', 'Nej'],
		['Q356_3', '1--Yes', 'Ja'],
		['Q356_3', '2--No', 'Nej'],
		['Q356_4', '1--Yes', 'Ja'],
		['Q356_4', '2--No', 'Nej'],
		['Q356_5', '1--Yes', 'Ja'],
		['Q356_5', '2--No', 'Nej'],
		['Q358', '1--Yes', 'Ja'],
		['Q358', '2--No', 'Nej'],
		['Q358', '3--In-some-departments-only', 'Endast på vissa avdelningar I']
	];
var country_
	 = [
	
		['AL', 'Albanien'],
		['AT', 'Österrike'],
		['BE', 'Belgien'],
		['BG', 'Bulgarien'],
		['CH', 'Schweiz.'],
		['CY', 'Cypern'],
		['CZ', 'Tjeckien'],
		['DE', 'Tyskland'],
		['DK', 'Danmark'],
		['EE', 'Estland'],
		['EL', 'Grekland'],
		['ES', 'Spanien'],
		['FI', 'Finland'],
		['FR', 'Frankrike'],
		['HR', 'Kroatien'],
		['HU', 'Ungern'],
		['IE', 'Irland'],
		['IS', 'Island'],
		['IT', 'Italien'],
		['LT', 'Litauen'],
		['LU', 'Luxemburg'],
		['LV', 'Lettland'],
		['ME', 'Montenegro'],
		['MK', 'Fyrom'],
		['MT', 'Malta'],
		['NL', 'Nederländerna'],
		['NO', 'Norge'],
		['PL', 'Polen'],
		['PT', 'Portugal'],
		['RO', 'Rumänien'],
		['RS', 'Serbien'],
		['SE', 'Sverige'],
		['SI', 'Slovenien'],
		['SK', 'Slovakien'],
		['TR', 'Turkiet'],
		['UK', 'Storbritannien'],
		['EuropeanUnion', 'Europeiska unionen']
	];
var question_meta
	 = [
	
		['Q200_1', 'Tröttande eller smärtsamma positioner, inklusive stillasittande under längre perioder', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Tröttande eller smärtsamma positioner, inklusive stillasittande under längre perioder<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_2', 'Lyftande eller förflyttande av människor eller tunga laster', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Lyftande eller förflyttande av människor eller tunga laster<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_3', 'Högt buller', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Högt buller<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_4', 'Enformiga hand- eller armrörelser', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Enformiga hand- eller armrörelser<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_5', 'Värme, kyla eller drag', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Värme, kyla eller drag<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_6', 'Risk för olycksfall med maskiner eller handverktyg', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Risk för olycksfall med maskiner eller handverktyg<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_7', 'Risk för olycksfall med fordon under arbetet, men inte på väg till och från arbetet', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Risk för olycksfall med fordon under arbetet, men inte på väg till och från arbetet<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_8', 'Kemikalier eller biologiskt material i form av vätskor, ångor eller damm', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Kemikalier eller biologiskt material i form av vätskor, ångor eller damm<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_9', 'Ökad risk för att halka, snubbla och falla', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Ökad risk för att halka, snubbla och falla<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q201_1', 'Tidspress', 'Förutom dessa risker kan det även förekomma hälsorelaterade risker beroende på hur arbetet är organiserat, sociala relationer på arbetet eller på grund av den ekonomiska situationen. Förekommer någon av följande risker på arbetsplatsen? Tidspress<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q201_2', 'Dålig kommunikation eller dåligt samarbete inom organisationen', 'Förutom dessa risker kan det även förekomma hälsorelaterade risker beroende på hur arbetet är organiserat, sociala relationer på arbetet eller på grund av den ekonomiska situationen. Förekommer någon av följande risker på arbetsplatsen? Dålig kommunikation eller dåligt samarbete inom organisationen<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q201_3', 'Medarbetares brist på inflytande över arbetstakt eller arbetsprocesser', 'Förutom dessa risker kan det även förekomma hälsorelaterade risker beroende på hur arbetet är organiserat, sociala relationer på arbetet eller på grund av den ekonomiska situationen. Förekommer någon av följande risker på arbetsplatsen? Medarbetares brist på inflytande över arbetstakt eller arbetsprocesser<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q201_4', 'Otryggt arbete', 'Förutom dessa risker kan det även förekomma hälsorelaterade risker beroende på hur arbetet är organiserat, sociala relationer på arbetet eller på grund av den ekonomiska situationen. Förekommer någon av följande risker på arbetsplatsen? Otryggt arbete<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q201_5', 'Att behöva hantera svåra kunder, patienter, elever m.m.', 'Förutom dessa risker kan det även förekomma hälsorelaterade risker beroende på hur arbetet är organiserat, sociala relationer på arbetet eller på grund av den ekonomiska situationen. Förekommer någon av följande risker på arbetsplatsen? Att behöva hantera svåra kunder, patienter, elever m.m.<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q201_6', 'Långa eller oregelbundna arbetstider', 'Förutom dessa risker kan det även förekomma hälsorelaterade risker beroende på hur arbetet är organiserat, sociala relationer på arbetet eller på grund av den ekonomiska situationen. Förekommer någon av följande risker på arbetsplatsen? Långa eller oregelbundna arbetstider<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q201_7', 'Diskriminering, till exempel på grund av kön, ålder eller etnisk bakgrund', 'Förutom dessa risker kan det även förekomma hälsorelaterade risker beroende på hur arbetet är organiserat, sociala relationer på arbetet eller på grund av den ekonomiska situationen. Förekommer någon av följande risker på arbetsplatsen? Diskriminering, till exempel på grund av kön, ålder eller etnisk bakgrund<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q250', 'Genomför ni regelbundet riskbedömningar av arbetsplatsen?', 'Genomför ni regelbundet riskbedömningar av arbetsplatsen?<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q251', 'Utförs riskbedömningarna främst av intern personal eller utförs de av externa tjänsteleverantörer?', 'Utförs riskbedömningarna främst av intern personal eller utförs de av externa tjänsteleverantörer?<br><br>(1) De utförs främst av intern personal <br>(2) De utförs främst av externa tjänsteleverantörer <br>(3) Både och i ungefär samma utsträckning <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q264_1', 'Uppfylla rättsliga förpliktelser', 'Hur viktiga är de följande anledningarna för att ta itu med hälsa och säkerhet på din arbetsplats? Ange för varje anledning om den är mycket viktig, mindre viktig eller inte viktig alls. Uppfylla rättsliga förpliktelser<br><br>(1) Mycket viktig <br>(2) Mindre viktig <br>(3) Inte viktig alls <br>(9) Inget svar'],
		['Q264_2', 'Leva upp till förväntningar från medarbetare eller arbetsombud', 'Hur viktiga är de följande anledningarna för att ta itu med hälsa och säkerhet på din arbetsplats? Ange för varje anledning om den är mycket viktig, mindre viktig eller inte viktig alls. Leva upp till förväntningar från medarbetare eller arbetsombud<br><br>(1) Mycket viktig <br>(2) Mindre viktig <br>(3) Inte viktig alls <br>(9) Inget svar'],
		['Q264_4', 'Upprätthålla eller öka produktiviteten', 'Hur viktiga är de följande anledningarna för att ta itu med hälsa och säkerhet på din arbetsplats? Ange för varje anledning om den är mycket viktig, mindre viktig eller inte viktig alls. Upprätthålla eller öka produktiviteten<br><br>(1) Mycket viktig <br>(2) Mindre viktig <br>(3) Inte viktig alls <br>(9) Inget svar'],
		['Q264_5', 'Upprätthålla organisationens rykte', 'Hur viktiga är de följande anledningarna för att ta itu med hälsa och säkerhet på din arbetsplats? Ange för varje anledning om den är mycket viktig, mindre viktig eller inte viktig alls. Upprätthålla organisationens rykte<br><br>(1) Mycket viktig <br>(2) Mindre viktig <br>(3) Inte viktig alls <br>(9) Inget svar'],
		['Q264_6', 'Undvika böter och påföljder från Arbetsmiljöverket', 'Hur viktiga är de följande anledningarna för att ta itu med hälsa och säkerhet på din arbetsplats? Ange för varje anledning om den är mycket viktig, mindre viktig eller inte viktig alls. Undvika böter och påföljder från Arbetsmiljöverket<br><br>(1) Mycket viktig <br>(2) Mindre viktig <br>(3) Inte viktig alls <br>(9) Inget svar'],
		['Q307', 'Har ni tillräckligt med information om hur man inkluderar psykosociala risker i riskbedömningar?', 'Har ni tillräckligt med information om hur man inkluderar psykosociala risker i riskbedömningar?<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q150_1', 'En företagshälsovårdsläkare', 'Vilka tjänster för hälsa och säkerhet använder ni? Det kan vara anställda inom företaget eller inhyrda personer. En företagshälsovårdsläkare<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q150_2', 'En psykolog', 'Vilka tjänster för hälsa och säkerhet använder ni? Det kan vara anställda inom företaget eller inhyrda personer. En psykolog<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q150_3', 'En expert som arbetar med ergonomisk design och arbetsplatsergonomi', 'Vilka tjänster för hälsa och säkerhet använder ni? Det kan vara anställda inom företaget eller inhyrda personer. En expert som arbetar med ergonomisk design och arbetsplatsergonomi<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q150_4', 'En generalist inom hälsa och säkerhet', 'Vilka tjänster för hälsa och säkerhet använder ni? Det kan vara anställda inom företaget eller inhyrda personer. En generalist inom hälsa och säkerhet<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q150_5', 'En expert inom olycksförebyggande åtgärder', 'Vilka tjänster för hälsa och säkerhet använder ni? Det kan vara anställda inom företaget eller inhyrda personer. En expert inom olycksförebyggande åtgärder<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q155', 'Finns det en handling som förklarar ansvarsområden och rutiner för hälsa och säkerhet och som är tillgänglig för de som arbetar på arbetsplatsen?', 'Finns det en handling som förklarar ansvarsområden och rutiner för hälsa och säkerhet och som är tillgänglig för de som arbetar på arbetsplatsen?<br><br>(1) Ja <br>(2) Nej <br>(3) Ja, men bara för vissa medarbetarkategorier <br>(9) Inget svar'],
		['Q156', 'Finns det en särskild budget avsatt varje år för åtgärder och utrustning inom hälsa och säkerhet, på din arbetsplats?', 'Finns det en särskild budget avsatt varje år för åtgärder och utrustning inom hälsa och säkerhet, på din arbetsplats?<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q158_1', 'Åtgärder för att öka medvetenheten om hälsosamma matvanor', 'Vidtar ni några av följande åtgärder för att förbättra medarbetarnas hälsa? Åtgärder för att öka medvetenheten om hälsosamma matvanor<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q158_2', 'Åtgärder för att öka medvetenheten om hur man kan förebygga beroenden, som t.ex. rökning, alkohol eller droger', 'Vidtar ni några av följande åtgärder för att förbättra medarbetarnas hälsa? Åtgärder för att öka medvetenheten om hur man kan förebygga beroenden, som t.ex. rökning, alkohol eller droger<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q158_3', 'Åtgärder för att främja idrottsaktiviteter utanför arbetstid', 'Vidtar ni några av följande åtgärder för att förbättra medarbetarnas hälsa? Åtgärder för att främja idrottsaktiviteter utanför arbetstid<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q158_4', 'Åtgärder för att främja ryggövningar, stretching eller andra fysiska aktiviteter på arbetet', 'Vidtar ni några av följande åtgärder för att förbättra medarbetarnas hälsa? Åtgärder för att främja ryggövningar, stretching eller andra fysiska aktiviteter på arbetet<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q160', 'Analyseras sjukfrånvaro regelbundet med avsikt att förbättra arbetsförhållandena?', 'Analyseras sjukfrånvaro regelbundet med avsikt att förbättra arbetsförhållandena?<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q165', 'Har er arbetsplats haft besök av Arbetsmiljöverket under de senaste 3 åren i syfte att kontrollera hälso- och säkerhetsförhållandena?', 'Har er arbetsplats haft besök av Arbetsmiljöverket under de senaste 3 åren i syfte att kontrollera hälso- och säkerhetsförhållandena?<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_1', 'Tröttande eller smärtsamma positioner, inklusive stillasittande under längre perioder', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Tröttande eller smärtsamma positioner, inklusive stillasittande under längre perioder<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_2', 'Lyftande eller förflyttande av människor eller tunga laster', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Lyftande eller förflyttande av människor eller tunga laster<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_3', 'Högt buller', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Högt buller<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_4', 'Enformiga hand- eller armrörelser', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Enformiga hand- eller armrörelser<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_5', 'Värme, kyla eller drag', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Värme, kyla eller drag<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_6', 'Risk för olycksfall med maskiner eller handverktyg', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Risk för olycksfall med maskiner eller handverktyg<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_7', 'Risk för olycksfall med fordon under arbetet, men inte på väg till och från arbetet', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Risk för olycksfall med fordon under arbetet, men inte på väg till och från arbetet<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_8', 'Kemikalier eller biologiskt material i form av vätskor, ångor eller damm', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Kemikalier eller biologiskt material i form av vätskor, ångor eller damm<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q200_9', 'Ökad risk för att halka, snubbla och falla', 'Beroende på arbetstyp finns det olika sorters faror och risker. Vilken av följande riskfaktorer finns på din arbetsplats? Svara på om de förekommer oavsett om de för närvarande är under kontroll och oavsett av hur många av medarbetarna som berörs av dem. Ökad risk för att halka, snubbla och falla<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q202_1', 'Tröttande eller smärtsamma positioner, inklusive stillasittande under längre perioder', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Tröttande eller smärtsamma positioner, inklusive stillasittande under längre perioder<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna riskfaktor.'],
		['Q202_2', 'Lyftande eller förflyttande av människor eller tunga laster', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Lyftande eller förflyttande av människor eller tunga laster<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna riskfaktor.'],
		['Q202_3', 'Högt buller', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Högt buller<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna riskfaktor.'],
		['Q202_4', 'Enformiga hand- eller armrörelser', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Enformiga hand- eller armrörelser<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna riskfaktor.'],
		['Q202_5', 'Värme, kyla eller drag', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Värme, kyla eller drag<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna riskfaktor.'],
		['Q202_6', 'Risk för olycksfall med maskiner eller handverktyg', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Risk för olycksfall med maskiner eller handverktyg<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna riskfaktor.'],
		['Q202_7', 'Risk för olycksfall med fordon under arbetet', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Risk för olycksfall med fordon under arbetet<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna riskfaktor.'],
		['Q202_8', 'Kemikalier eller biologiskt material', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Kemikalier eller biologiskt material<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna riskfaktor.'],
		['Q202_9', 'Ökad risk för att halka, snubbla och falla', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Ökad risk för att halka, snubbla och falla<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna riskfaktor.'],
		['Q250', 'Genomför ni regelbundet riskbedömningar av arbetsplatsen?', 'Genomför ni regelbundet riskbedömningar av arbetsplatsen?<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q251', 'Utförs riskbedömningarna främst av intern personal eller utförs de av externa tjänsteleverantörer?', 'Utförs riskbedömningarna främst av intern personal eller utförs de av externa tjänsteleverantörer?<br><br>(1) De utförs främst av intern personal <br>(2) De utförs främst av externa tjänsteleverantörer <br>(3) Både och i ungefär samma utsträckning <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q252_1', 'Maskin-, utrustnings- och anläggningssäkerhet', 'Vilka av följande aspekter utvärderas rutinmässigt i samband med dessa riskbedömningar av arbetsplatsen? Maskin-, utrustnings- och anläggningssäkerhet<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q252_2', 'Farliga kemikalier eller biologiskt material', 'Vilka av följande aspekter utvärderas rutinmässigt i samband med dessa riskbedömningar av arbetsplatsen? Farliga kemikalier eller biologiskt material<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q252_3', 'Arbetsställningar, fysiska arbetskrav och enformiga rörelser', 'Vilka av följande aspekter utvärderas rutinmässigt i samband med dessa riskbedömningar av arbetsplatsen? Arbetsställningar, fysiska arbetskrav och enformiga rörelser<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q252_4', 'Exponering för buller, vibrationer, värme eller kyla', 'Vilka av följande aspekter utvärderas rutinmässigt i samband med dessa riskbedömningar av arbetsplatsen? Exponering för buller, vibrationer, värme eller kyla<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q252_5', 'Relationer mellan överordnade och andra medarbetare', 'Vilka av följande aspekter utvärderas rutinmässigt i samband med dessa riskbedömningar av arbetsplatsen? Relationer mellan överordnade och andra medarbetare<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q252_6', 'Organisatoriska aspekter såsom arbetsscheman, raster eller arbetsskift', 'Vilka av följande aspekter utvärderas rutinmässigt i samband med dessa riskbedömningar av arbetsplatsen? Organisatoriska aspekter såsom arbetsscheman, raster eller arbetsskift<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q254gr', 'Vilket år utfördes den senaste riskbedömningen av arbetsplatsen?', 'Vilket år utfördes den senaste riskbedömningen av arbetsplatsen?<br><br>(År) <br>(9998) Vet ej <br>(9999) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q255', 'Har det dokumenterats skriftligt?', 'Har det dokumenterats skriftligt?<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att den senaste riskbedömningen av arbetsplatsen utfördes efter 1970.'],
		['Q256_1', 'Ledningen', 'Vilka har fått ta del av resultaten från riskbedömningen? Ledningen<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att den senaste riskbedömningen av arbetsplatsen utfördes efter 1970.'],
		['Q256_2', 'Skyddsombuden', 'Vilka har fått ta del av resultaten från riskbedömningen? Skyddsombuden<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att den senaste riskbedömningen av arbetsplatsen utfördes efter 1970 och som har skyddsombud.'],
		['Q256_3', '(The works council)', 'This form of employee representation doesn’t exist in this country.<br><br>Vilka har fått ta del av resultaten från riskbedömningen? (The works council)<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>'],
		['Q256_4', 'Fackliga förtroendemän', 'Vilka har fått ta del av resultaten från riskbedömningen? Fackliga förtroendemän<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att den senaste riskbedömningen av arbetsplatsen utfördes efter 1970 och som har fackliga förtroendemän.'],
		['Q256_5', 'Medarbetarna själva', 'Vilka har fått ta del av resultaten från riskbedömningen? Medarbetarna själva<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att den senaste riskbedömningen av arbetsplatsen utfördes efter 1970.'],
		['Q259', 'Anser man på din arbetsplats att rutinerna för riskbedömningar är ett användbart tillvägagångssätt för att hantera hälsa och säkerhet?', 'Anser man på din arbetsplats att rutinerna för riskbedömningar är ett användbart tillvägagångssätt för att hantera hälsa och säkerhet?<br><br>(1) Ja <br>(2) Nej <br>(3) Det är delade åsikter om detta <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q261_1', 'Farorna och riskerna är redan kända', 'Finns det några särskilda anledningar till varför riskbedömningar av arbetsplatsen inte genomförs regelbundet? Ange för vart och ett av de följande påståendena om det gäller för er arbetsplats eller inte. Farorna och riskerna är redan kända<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som inte rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q261_2', 'Det finns inte några större problem', 'Finns det några särskilda anledningar till varför riskbedömningar av arbetsplatsen inte genomförs regelbundet? Ange för vart och ett av de följande påståendena om det gäller för er arbetsplats eller inte. Det finns inte några större problem<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som inte rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q261_3', 'Rutinerna är alltför betungande', 'Finns det några särskilda anledningar till varför riskbedömningar av arbetsplatsen inte genomförs regelbundet? Ange för vart och ett av de följande påståendena om det gäller för er arbetsplats eller inte. Rutinerna är alltför betungande<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som inte rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q261_4', 'Den nödvändiga sakkunskapen saknas', 'Finns det några särskilda anledningar till varför riskbedömningar av arbetsplatsen inte genomförs regelbundet? Ange för vart och ett av de följande påståendena om det gäller för er arbetsplats eller inte. Den nödvändiga sakkunskapen saknas<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som inte rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q308_1', 'Utrustning som hjälper till vid lyft eller flytt av laster eller annat fysiskt tungt arbete', 'Vi går nu vidare till muskel- och skelettbesvär som smärtor i rygg, nacke, armar, händer eller ben. Finns några av följande rutiner för förebyggande åtgärder på arbetsplatsen? Utrustning som hjälper till vid lyft eller flytt av laster eller annat fysiskt tungt arbete<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar lyftande eller förflyttande av människor eller tunga laster som en riskfaktor.'],
		['Q308_2', 'Arbetsrotation för att minska enformiga rörelser eller fysisk ansträngning', 'Vi går nu vidare till muskel- och skelettbesvär som smärtor i rygg, nacke, armar, händer eller ben. Finns några av följande rutiner för förebyggande åtgärder på arbetsplatsen? Arbetsrotation för att minska enformiga rörelser eller fysisk ansträngning<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar enformiga hand- eller armrörelser som en riskfaktor.'],
		['Q308_3', 'Uppmanande till regelbundna raster för personer som arbetar i obekväma eller statiska kroppsställningar, inklusive längre tids stillasittande', 'Vi går nu vidare till muskel- och skelettbesvär som smärtor i rygg, nacke, armar, händer eller ben. Finns några av följande rutiner för förebyggande åtgärder på arbetsplatsen? Uppmanande till regelbundna raster för personer som arbetar i obekväma eller statiska kroppsställningar, inklusive längre tids stillasittande<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q308_4', 'Tillhandahållande av ergonomisk utrustning så som särskilda stolar eller skrivbord', 'Vi går nu vidare till muskel- och skelettbesvär som smärtor i rygg, nacke, armar, händer eller ben. Finns några av följande rutiner för förebyggande åtgärder på arbetsplatsen? Tillhandahållande av ergonomisk utrustning så som särskilda stolar eller skrivbord<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q356_1', 'Korrekt användning och anpassning av arbetsutrustning och möbler', 'Inom vilka av följande områden får medarbetarna på er arbetsplats utbildning? Korrekt användning och anpassning av arbetsutrustning och möbler<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q356_2', 'Hantering av farliga ämnen', 'Inom vilka av följande områden får medarbetarna på er arbetsplats utbildning? Hantering av farliga ämnen<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q356_3', 'Hur man förebygger psykosociala risker som stress och mobbning', 'Inom vilka av följande områden får medarbetarna på er arbetsplats utbildning? Hur man förebygger psykosociala risker som stress och mobbning<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q356_4', 'Hur man lyfter och flyttar tunga laster eller personer', 'Inom vilka av följande områden får medarbetarna på er arbetsplats utbildning? Hur man lyfter och flyttar tunga laster eller personer<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q356_5', 'Nödfallsrutiner', 'Inom vilka av följande områden får medarbetarna på er arbetsplats utbildning? Nödfallsrutiner<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q201_1', 'Tidspress', 'Förutom dessa risker kan det även förekomma hälsorelaterade risker beroende på hur arbetet är organiserat, sociala relationer på arbetet eller på grund av den ekonomiska situationen. Förekommer någon av följande risker på arbetsplatsen? Tidspress<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q201_2', 'Dålig kommunikation eller dåligt samarbete inom organisationen', 'Förutom dessa risker kan det även förekomma hälsorelaterade risker beroende på hur arbetet är organiserat, sociala relationer på arbetet eller på grund av den ekonomiska situationen. Förekommer någon av följande risker på arbetsplatsen? Dålig kommunikation eller dåligt samarbete inom organisationen<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q201_3', 'Medarbetares brist på inflytande över arbetstakt eller arbetsprocesser', 'Förutom dessa risker kan det även förekomma hälsorelaterade risker beroende på hur arbetet är organiserat, sociala relationer på arbetet eller på grund av den ekonomiska situationen. Förekommer någon av följande risker på arbetsplatsen? Medarbetares brist på inflytande över arbetstakt eller arbetsprocesser<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q201_4', 'Otryggt arbete', 'Förutom dessa risker kan det även förekomma hälsorelaterade risker beroende på hur arbetet är organiserat, sociala relationer på arbetet eller på grund av den ekonomiska situationen. Förekommer någon av följande risker på arbetsplatsen? Otryggt arbete<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q201_5', 'Att behöva hantera svåra kunder, patienter, elever m.m.', 'Förutom dessa risker kan det även förekomma hälsorelaterade risker beroende på hur arbetet är organiserat, sociala relationer på arbetet eller på grund av den ekonomiska situationen. Förekommer någon av följande risker på arbetsplatsen? Att behöva hantera svåra kunder, patienter, elever m.m.<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q201_6', 'Långa eller oregelbundna arbetstider', 'Förutom dessa risker kan det även förekomma hälsorelaterade risker beroende på hur arbetet är organiserat, sociala relationer på arbetet eller på grund av den ekonomiska situationen. Förekommer någon av följande risker på arbetsplatsen? Långa eller oregelbundna arbetstider<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q201_7', 'Diskriminering, till exempel på grund av kön, ålder eller etnisk bakgrund', 'Förutom dessa risker kan det även förekomma hälsorelaterade risker beroende på hur arbetet är organiserat, sociala relationer på arbetet eller på grund av den ekonomiska situationen. Förekommer någon av följande risker på arbetsplatsen? Diskriminering, till exempel på grund av kön, ålder eller etnisk bakgrund<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q202_10', 'Tidspress', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Tidspress<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna psykosociala riskfaktor.'],
		['Q202_11', 'Dålig kommunikation eller dåligt samarbete inom organisationen', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Dålig kommunikation eller dåligt samarbete inom organisationen<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna psykosociala riskfaktor.'],
		['Q202_12', 'Medarbetares brist på inflytande över arbetstakt eller arbetsprocesser', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Medarbetares brist på inflytande över arbetstakt eller arbetsprocesser<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna psykosociala riskfaktor.'],
		['Q202_13', 'Otryggt arbete', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Otryggt arbete<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna psykosociala riskfaktor.'],
		['Q202_14', 'Att behöva hantera svåra kunder, patienter, elever m.m.', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Att behöva hantera svåra kunder, patienter, elever m.m.<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna psykosociala riskfaktor.'],
		['Q202_15', 'Långa eller oregelbundna arbetstider', 'För vilken av riskerna - om någon - saknar din organisation information eller adekvata verktyg för att åtgärda dem på ett effektivt sätt? Långa eller oregelbundna arbetstider<br><br>(1) Ja <br>(2) Nej <br><br>Fråga till de arbetsplatser som rapporterar att de har denna psykosociala riskfaktor.'],
		['Q300', 'Finns det någon åtgärdsplan för att förebygga arbetsrelaterad stress?', 'Finns det någon åtgärdsplan för att förebygga arbetsrelaterad stress?<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till arbetsplatser med minst 20 medarbetare.'],
		['Q301', 'Finns det några fastlagda rutiner för att hantera eventuella fall av mobbning eller trakasserier?', 'Finns det några fastlagda rutiner för att hantera eventuella fall av mobbning eller trakasserier?<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till arbetsplatser med minst 20 medarbetare.'],
		['Q302', 'Och finns det några rutiner för att hantera eventuella fall av hot, övergrepp eller attacker från kunder, patienter, elever eller andra externa personer?', 'Och finns det några rutiner för att hantera eventuella fall av hot, övergrepp eller attacker från kunder, patienter, elever eller andra externa personer?<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser med minst 20 medarbetare som rapporterar hantering av svåra kunder, patienter, elever som en riskfaktor.'],
		['Q303_1', 'Utfört en omorganisering av arbete för att minska arbetskravoch belastning', 'Har man på arbetsplatsen, under de senaste 3 åren, vidtagit någon eller några av följande åtgärder för att förebygga psykosociala risker? Utfört en omorganisering av arbete för att minska arbetskravoch belastning<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q303_2', 'Erbjudit sekretessbelagd rådgivning för medarbetare', 'Har man på arbetsplatsen, under de senaste 3 åren, vidtagit någon eller några av följande åtgärder för att förebygga psykosociala risker? Erbjudit sekretessbelagd rådgivning för medarbetare<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q303_3', 'Etablerat rutiner för konfliktlösning', 'Har man på arbetsplatsen, under de senaste 3 åren, vidtagit någon eller några av följande åtgärder för att förebygga psykosociala risker? Etablerat rutiner för konfliktlösning<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q303_4', 'Ingripit om någon har arbetat överdrivet länge eller på oregelbundna tider', 'Har man på arbetsplatsen, under de senaste 3 åren, vidtagit någon eller några av följande åtgärder för att förebygga psykosociala risker? Ingripit om någon har arbetat överdrivet länge eller på oregelbundna tider<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q307', 'Har ni tillräckligt med information om hur man inkluderar psykosociala risker i riskbedömningar?', 'Har ni tillräckligt med information om hur man inkluderar psykosociala risker i riskbedömningar?<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar'],
		['Q264_1', 'Uppfylla rättsliga förpliktelser', 'Hur viktiga är de följande anledningarna för att ta itu med hälsa och säkerhet på din arbetsplats? Ange för varje anledning om den är mycket viktig, mindre viktig eller inte viktig alls. Uppfylla rättsliga förpliktelser<br><br>(1) Mycket viktig <br>(2) Mindre viktig <br>(3) Inte viktig alls <br>(9) Inget svar'],
		['Q264_2', 'Leva upp till förväntningar från medarbetare eller arbetsombud', 'Hur viktiga är de följande anledningarna för att ta itu med hälsa och säkerhet på din arbetsplats? Ange för varje anledning om den är mycket viktig, mindre viktig eller inte viktig alls. Leva upp till förväntningar från medarbetare eller arbetsombud<br><br>(1) Mycket viktig <br>(2) Mindre viktig <br>(3) Inte viktig alls <br>(9) Inget svar'],
		['Q264_4', 'Upprätthålla eller öka produktiviteten', 'Hur viktiga är de följande anledningarna för att ta itu med hälsa och säkerhet på din arbetsplats? Ange för varje anledning om den är mycket viktig, mindre viktig eller inte viktig alls. Upprätthålla eller öka produktiviteten<br><br>(1) Mycket viktig <br>(2) Mindre viktig <br>(3) Inte viktig alls <br>(9) Inget svar'],
		['Q264_5', 'Upprätthålla organisationens rykte', 'Hur viktiga är de följande anledningarna för att ta itu med hälsa och säkerhet på din arbetsplats? Ange för varje anledning om den är mycket viktig, mindre viktig eller inte viktig alls. Upprätthålla organisationens rykte<br><br>(1) Mycket viktig <br>(2) Mindre viktig <br>(3) Inte viktig alls <br>(9) Inget svar'],
		['Q264_6', 'Undvika böter och påföljder från Arbetsmiljöverket', 'Hur viktiga är de följande anledningarna för att ta itu med hälsa och säkerhet på din arbetsplats? Ange för varje anledning om den är mycket viktig, mindre viktig eller inte viktig alls. Undvika böter och påföljder från Arbetsmiljöverket<br><br>(1) Mycket viktig <br>(2) Mindre viktig <br>(3) Inte viktig alls <br>(9) Inget svar'],
		['Q265_1', 'Tids- eller personalbrist', 'Vilka är de största svårigheterna med att hantera hälsa och säkerhet på din arbetsplats? Ange för vart och ett av de följande påståendena om det är mycket svårt, mindre svårt eller inte alls svårt. Tids- eller personalbrist<br><br>(1) Mycket svårt <br>(2) Mindre svårt <br>(3) Inte alls svårt <br>(9) Inget svar'],
		['Q265_2', 'Brist på pengar', 'Vilka är de största svårigheterna med att hantera hälsa och säkerhet på din arbetsplats? Ange för vart och ett av de följande påståendena om det är mycket svårt, mindre svårt eller inte alls svårt. Brist på pengar<br><br>(1) Mycket svårt <br>(2) Mindre svårt <br>(3) Inte alls svårt <br>(9) Inget svar'],
		['Q265_3', 'Bristande medvetenhet bland medarbetarna', 'Vilka är de största svårigheterna med att hantera hälsa och säkerhet på din arbetsplats? Ange för vart och ett av de följande påståendena om det är mycket svårt, mindre svårt eller inte alls svårt. Bristande medvetenhet bland medarbetarna<br><br>(1) Mycket svårt <br>(2) Mindre svårt <br>(3) Inte alls svårt <br>(9) Inget svar'],
		['Q265_4', 'Bristande medvetenhet i ledningen', 'Vilka är de största svårigheterna med att hantera hälsa och säkerhet på din arbetsplats? Ange för vart och ett av de följande påståendena om det är mycket svårt, mindre svårt eller inte alls svårt. Bristande medvetenhet i ledningen<br><br>(1) Mycket svårt <br>(2) Mindre svårt <br>(3) Inte alls svårt <br>(9) Inget svar'],
		['Q265_5', 'Avsaknad av sakkunskap eller specialiststöd', 'Vilka är de största svårigheterna med att hantera hälsa och säkerhet på din arbetsplats? Ange för vart och ett av de följande påståendena om det är mycket svårt, mindre svårt eller inte alls svårt. Avsaknad av sakkunskap eller specialiststöd<br><br>(1) Mycket svårt <br>(2) Mindre svårt <br>(3) Inte alls svårt <br>(9) Inget svar'],
		['Q265_6', 'Pappersarbetet', 'Vilka är de största svårigheterna med att hantera hälsa och säkerhet på din arbetsplats? Ange för vart och ett av de följande påståendena om det är mycket svårt, mindre svårt eller inte alls svårt. Pappersarbetet<br><br>(1) Mycket svårt <br>(2) Mindre svårt <br>(3) Inte alls svårt <br>(9) Inget svar'],
		['Q265_7', 'Komplicerade rättsliga förpliktelser', 'Vilka är de största svårigheterna med att hantera hälsa och säkerhet på din arbetsplats? Ange för vart och ett av de följande påståendena om det är mycket svårt, mindre svårt eller inte alls svårt. Komplicerade rättsliga förpliktelser<br><br>(1) Mycket svårt <br>(2) Mindre svårt <br>(3) Inte alls svårt <br>(9) Inget svar'],
		['Q304', 'Föregicks åtgärderna av faktiska problem med stress, mobbning, trakasserier eller våld på arbetsplatsen?', 'Föregicks åtgärderna av faktiska problem med stress, mobbning, trakasserier eller våld på arbetsplatsen?<br><br>(1) Ja <br>(2) Nej <br>(8) Delvis <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att vissa åtgärder vidtagits för att förebygga psykosociala risker under de senaste tre åren.'],
		['Q306a_3', 'Bristande medvetenhet bland medarbetarna', 'Med tanke på situationen på din arbetsplats, gör någon av de följande faktorerna det svårare att hantera psykosociala risker än andra hälsorisker? Bristande medvetenhet bland medarbetarna<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de har någon av de uppräknade psykosociala riskfaktorerna.'],
		['Q306a_4', 'Bristande medvetenhet i ledningen', 'Med tanke på situationen på din arbetsplats, gör någon av de följande faktorerna det svårare att hantera psykosociala risker än andra hälsorisker? Bristande medvetenhet i ledningen<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de har någon av de uppräknade psykosociala riskfaktorerna.'],
		['Q306a_5', 'Avsaknad av sakkunskap eller specialiststöd', 'Med tanke på situationen på din arbetsplats, gör någon av de följande faktorerna det svårare att hantera psykosociala risker än andra hälsorisker? Avsaknad av sakkunskap eller specialiststöd<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de har någon av de uppräknade psykosociala riskfaktorerna.'],
		['Q306a_6', 'Motvilja mot att tala öppet om dessa frågor', 'Med tanke på situationen på din arbetsplats, gör någon av de följande faktorerna det svårare att hantera psykosociala risker än andra hälsorisker? Motvilja mot att tala öppet om dessa frågor<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de har någon av de uppräknade psykosociala riskfaktorerna.'],
		['Q166_1', '(A works council)', 'This form of employee representation doesn’t exist in this country.<br><br>Vilka av de följande arbetstagarföreträdarna finns på arbetsplatsen? (A works council)<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till alla, storleken beroende av nationella trösklar för dessa organ.'],
		['Q166_2', 'En facklig förtroendeman', 'Vilka av de följande arbetstagarföreträdarna finns på arbetsplatsen? En facklig förtroendeman<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till alla, storleken beroende av nationella trösklar för dessa organ.'],
		['Q166_3', 'Ett skyddsombud', 'Vilka av de följande arbetstagarföreträdarna finns på arbetsplatsen? Ett skyddsombud<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till alla, storleken beroende av nationella trösklar för dessa organ.'],
		['Q166_4', 'En arbetsmiljökommitté', 'Vilka av de följande arbetstagarföreträdarna finns på arbetsplatsen? En arbetsmiljökommitté<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till alla, storleken beroende av nationella trösklar för dessa organ.'],
		['Q258b', 'Om åtgärder måste vidtas efter en riskbedömning, är medarbetarna då vanligtvis delaktiga i deras utformning och implementering?', 'Om åtgärder måste vidtas efter en riskbedömning, är medarbetarna då vanligtvis delaktiga i deras utformning och implementering?<br><br>(1) Ja <br>(2) Nej <br>(4) Det beror på vilken typ av åtgärd det gäller <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de regelbundet genomför riskbedömningar.'],
		['Q305', 'Deltog medarbetarna i utformningen av åtgärderna och hur de ska struktureras för att bemöta psykosociala risker?', 'Deltog medarbetarna i utformningen av åtgärderna och hur de ska struktureras för att bemöta psykosociala risker?<br><br>(1) Ja <br>(2) Nej <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att vissa åtgärder vidtagits för att förebygga psykosociala risker under de senaste tre åren.'],
		['Q350', 'Hur ofta diskuteras hälsa och säkerhet av arbetstagarföreträdare och ledningen? Genomförs dessa diskussioner regelbundet, endast när särskilda hälso- och säkerhetsproblem uppstår eller inte alls?', 'Hur ofta diskuteras hälsa och säkerhet av arbetstagarföreträdare och ledningen? Genomförs dessa diskussioner regelbundet, endast när särskilda hälso- och säkerhetsproblem uppstår eller inte alls?<br><br>(1) Regelbundet <br>(2) Endast när särskilda hälso- och säkerhetsproblem uppstår <br>(3) Inte alls <br>(7) Stämmer inte in (det finns inga arbetstagarföreträdare) <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar någon form av arbetstagarrepresentation.'],
		['Q351', 'Och hur ofta uppstår oenigheter som rör hälsa och säkerhet? Är det ofta, ibland eller praktiskt taget aldrig?', 'Och hur ofta uppstår oenigheter som rör hälsa och säkerhet? Är det ofta, ibland eller praktiskt taget aldrig?<br><br>(1) Ofta <br>(2) Ibland <br>(3) Praktiskt taget aldrig <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att arbetsmiljö diskuteras av arbetstagarföreträdare och ledningen.'],
		['Q354', 'Erbjuds skyddsombuden någon form av utbildning under arbetstid i syfte att hjälpa dem att utföra sina uppgifter inom hälso och säkerhet?', 'Erbjuds skyddsombuden någon form av utbildning under arbetstid i syfte att hjälpa dem att utföra sina uppgifter inom hälso och säkerhet?<br><br>(1) Ja <br>(2) Nej <br>(3) Ja, men endast vissa av dem <br>(9) Inget svar<br><br>Fråga till de arbetsplatser som rapporterar att de har skyddsombud.'],
		['Q358', 'Diskuteras hälso- och säkerhetsfrågor regelbundet under personal- eller gruppmöten?', 'Diskuteras hälso- och säkerhetsfrågor regelbundet under personal- eller gruppmöten?<br><br>(1) Ja <br>(2) Nej <br>(3) Endast på vissa avdelningar I <br>(9) Inget svar']
	];
