//Auto Generated file
var subset_
	 = [
	
		['Y11_HH2a', 'Pohlaví'],
		['Y11_Incomequartiles_percapita', 'Příjem'],
		['Y11_Agecategory', 'Věk']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Osoby každého věku'],
		['Y11_Agecategory', '1--18-24y', '18 až 24 let'],
		['Y11_Agecategory', '2--25-34y', '25 až 34 let'],
		['Y11_Agecategory', '3--35-49y', '35 až 49 let'],
		['Y11_Agecategory', '4--50-64y', '50 až 64 let'],
		['Y11_Agecategory', '5---64y', '> 64 let'],
		['Y11_HH2a', 'All', 'Obě pohlaví'],
		['Y11_HH2a', '1--Female', 'Žena'],
		['Y11_HH2a', '2--Male', 'Muž'],
		['Y11_Incomequartiles_percapita', 'All', 'Všechny výše příjmu'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Nejnižší'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'Druhý'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'Třetí'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Nejvyšší']
	];
var topic_
	 = [
	
		['', 'vše (46)'],
		['Domov a okolí', 'Domov a okolí (6)'],
		['Kvalita společnosti', 'Kvalita společnosti (6)'],
		['Sociální vyloučení a zapojení do komunity', 'Sociální vyloučení a zapojení do komunity (2)'],
		['Subjektivní pohoda', 'Subjektivní pohoda (9)'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Zaměstnanost a rovnováha mezi pracovním a osobním životem (6)'],
		['Zdraví a veřejné služby', 'Zdraví a veřejné služby (8)'],
		['Životní úroveň a deprivace', 'Životní úroveň a deprivace (9)']
	];
var topic_question
	 = [
	
		['Domov a okolí', 'Y11_Q18', 'Vlastnictví domu/bytu'],
		['Domov a okolí', 'Y11_Q19a', 'Problémy s ubytováním/bydlením: nedostatek místa'],
		['Domov a okolí', 'Y11_Q19b', 'Problémy s ubytováním/bydlením: hniloba v oknech, dveřích nebo podlaze'],
		['Domov a okolí', 'Y11_Q19c', 'Problémy s ubytováním/bydlením: vlhkost / zatékání ve zdech nebo ve střeše'],
		['Domov a okolí', 'Y11_Q19d', 'Problémy s ubytováním/bydlením: bez splachovacího záchodu v domě/bytě'],
		['Domov a okolí', 'Y11_Q52', 'Čas strávený na cestě do práce nebo do školy a zpět domů'],
		['Kvalita společnosti', 'Y11_Q24', 'Řekl(a) byste, že většině lidí lze důvěřovat, nebo že člověk nemůže být při jednání s lidmi nikdy dost opatrný?'],
		['Kvalita společnosti', 'Y11_Q25a', 'Vnímané napětí mezi chudými a bohatými lidmi'],
		['Kvalita společnosti', 'Y11_Q25b', 'Vnímané napětí mezi vedoucími pracovníky (managementem) a pracujícími'],
		['Kvalita společnosti', 'Y11_Q25c', 'Vnímané napětí mezi muži a ženami'],
		['Kvalita společnosti', 'Y11_Q25d', 'Vnímané napětí mezi starými a mladými lidmi'],
		['Kvalita společnosti', 'Y11_Q25e', 'Vnímané napětí mezi různými rasovými a etnickými skupinami'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q22_Volunteering', 'Jak často jste v posledních 12 měsících vykonával(a) neplacenou dobrovolnickou práci?'],
		['Sociální vyloučení a zapojení do komunity', 'Y11_Q23d', 'Kontaktoval(a) nějakého politika nebo veřejného činitele (nemyslíme běžný kontakt související s používáním veřejných služeb)'],
		['Subjektivní pohoda', 'Y11_Q30', 'Do jaké míry jste spokojený(á) se svým životem v dnešní době?'],
		['Subjektivní pohoda', 'Y11_Q40a', 'Spokojenost se vzděláním'],
		['Subjektivní pohoda', 'Y11_Q40b', 'Spokojenost se současným zaměstnáním'],
		['Subjektivní pohoda', 'Y11_Q40c', 'Spokojenost se současnou životní úrovní'],
		['Subjektivní pohoda', 'Y11_Q40d', 'Spokojenost s ubytováním/bydlením'],
		['Subjektivní pohoda', 'Y11_Q40e', 'Spokojenost s rodinným životem'],
		['Subjektivní pohoda', 'Y11_Q40f', 'Spokojenost se zdravím'],
		['Subjektivní pohoda', 'Y11_Q40g', 'Spokojenost se společenským životem'],
		['Subjektivní pohoda', 'Y11_Q41', 'Když se vezmou všechny okolnosti, můžete prosím uvést, jak jste šťastný(á)?'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q12a', 'Přišel(a) jsem z práce domů příliš unavený(á) na to, abych mohl(a) dělat domácí práce'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q12b', 'Vzhledem k množství času, které věnuji práci, pro mě bylo těžké plnit povinnosti vůči rodině'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q12c', 'Vzhledem k mým povinnostem v rodině bylo pro mě těžké se soustředit na práci'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q15', 'S jakou pravděpodobností by se mohlo stát, že byste v průběhu následujících 6 měsíců přišel(a) o svou práci?'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q38', 'Postoj k podílu na domácích pracích'],
		['Zaměstnanost a rovnováha mezi pracovním a osobním životem', 'Y11_Q39d_stress', 'Stres'],
		['Zdraví a veřejné služby', 'Y11_Q47a', 'Problém s návštěvou lékaře z důvodu vzdálenosti'],
		['Zdraví a veřejné služby', 'Y11_Q47b', 'Problém s návštěvou lékaře z důvodu dlouhé lhůty objednání'],
		['Zdraví a veřejné služby', 'Y11_Q47c', 'Problém s návštěvou lékaře z důvodu doby strávené v čekárně v den objednání'],
		['Zdraví a veřejné služby', 'Y11_Q47d', 'Problém s návštěvou lékaře z důvodu ceny'],
		['Zdraví a veřejné služby', 'Y11_Q53a', 'Jak byste hodnotil(a) kvalitu zdravotní péče ve Vaší zemi? '],
		['Zdraví a veřejné služby', 'Y11_Q53b', 'Jak byste hodnotil(a) kvalitu vzdělávacího systému ve Vaší zemi? '],
		['Zdraví a veřejné služby', 'Y11_Q53c', 'Jak byste hodnotil(a) kvalitu veřejné dopravy ve Vaší zemi? '],
		['Zdraví a veřejné služby', 'Y11_Q53g', 'Jak byste hodnotil(a) kvalitu státního důchodového systému ve Vaší zemi? '],
		['Životní úroveň a deprivace', 'Y11_Q58', 'Je Vaše domácnost schopna vyjít s penězi?'],
		['Životní úroveň a deprivace', 'Y11_Q59a', 'Můžete si dovolit udržovat v domácnosti přiměřené teplo?'],
		['Životní úroveň a deprivace', 'Y11_Q59b', 'Můžete si dovolit zaplatit ročně za týden dovolené mimo domov?'],
		['Životní úroveň a deprivace', 'Y11_Q59c', 'Můžete si dovolit vyměnit jakýkoliv opotřebovaný nábytek?'],
		['Životní úroveň a deprivace', 'Y11_Q59d', 'Můžete si dovolit mít každý druhý den jídlo s masem, s kuřetem nebo rybou, pokud byste je chtěl(a)?'],
		['Životní úroveň a deprivace', 'Y11_Q59e', 'Můžete si dovolit kupovat si spíše nové oblečení než obnošené oblečení (ze second‐handu)?'],
		['Životní úroveň a deprivace', 'Y11_Q59f', 'Můžete si dovolit alespoň jednou za měsíc pozvat domů přátele nebo rodinu na nějaké pití nebo jídlo?'],
		['Životní úroveň a deprivace', 'Y11_Q60a', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu s placením nájmu nebo hypotéky za bydlení?'],
		['Životní úroveň a deprivace', 'Y11_Q60b', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu s placením účtů za elektřinu, vodu, plyn?']
	];
var question_
	 = [
	
		['Y11_Q18', 'Vlastnictví domu/bytu'],
		['Y11_Q19a', 'Problémy s ubytováním/bydlením: nedostatek místa'],
		['Y11_Q19b', 'Problémy s ubytováním/bydlením: hniloba v oknech, dveřích nebo podlaze'],
		['Y11_Q19c', 'Problémy s ubytováním/bydlením: vlhkost / zatékání ve zdech nebo ve střeše'],
		['Y11_Q19d', 'Problémy s ubytováním/bydlením: bez splachovacího záchodu v domě/bytě'],
		['Y11_Q52', 'Čas strávený na cestě do práce nebo do školy a zpět domů'],
		['Y11_Q24', 'Řekl(a) byste, že většině lidí lze důvěřovat, nebo že člověk nemůže být při jednání s lidmi nikdy dost opatrný?'],
		['Y11_Q25a', 'Vnímané napětí mezi chudými a bohatými lidmi'],
		['Y11_Q25b', 'Vnímané napětí mezi vedoucími pracovníky (managementem) a pracujícími'],
		['Y11_Q25c', 'Vnímané napětí mezi muži a ženami'],
		['Y11_Q25d', 'Vnímané napětí mezi starými a mladými lidmi'],
		['Y11_Q25e', 'Vnímané napětí mezi různými rasovými a etnickými skupinami'],
		['Y11_Q22_Volunteering', 'Jak často jste v posledních 12 měsících vykonával(a) neplacenou dobrovolnickou práci?'],
		['Y11_Q23d', 'Kontaktoval(a) nějakého politika nebo veřejného činitele (nemyslíme běžný kontakt související s používáním veřejných služeb)'],
		['Y11_Q30', 'Do jaké míry jste spokojený(á) se svým životem v dnešní době?'],
		['Y11_Q40a', 'Spokojenost se vzděláním'],
		['Y11_Q40b', 'Spokojenost se současným zaměstnáním'],
		['Y11_Q40c', 'Spokojenost se současnou životní úrovní'],
		['Y11_Q40d', 'Spokojenost s ubytováním/bydlením'],
		['Y11_Q40e', 'Spokojenost s rodinným životem'],
		['Y11_Q40f', 'Spokojenost se zdravím'],
		['Y11_Q40g', 'Spokojenost se společenským životem'],
		['Y11_Q41', 'Když se vezmou všechny okolnosti, můžete prosím uvést, jak jste šťastný(á)?'],
		['Y11_Q12a', 'Přišel(a) jsem z práce domů příliš unavený(á) na to, abych mohl(a) dělat domácí práce'],
		['Y11_Q12b', 'Vzhledem k množství času, které věnuji práci, pro mě bylo těžké plnit povinnosti vůči rodině'],
		['Y11_Q12c', 'Vzhledem k mým povinnostem v rodině bylo pro mě těžké se soustředit na práci'],
		['Y11_Q15', 'S jakou pravděpodobností by se mohlo stát, že byste v průběhu následujících 6 měsíců přišel(a) o svou práci?'],
		['Y11_Q38', 'Postoj k podílu na domácích pracích'],
		['Y11_Q39d_stress', 'Stres'],
		['Y11_Q47a', 'Problém s návštěvou lékaře z důvodu vzdálenosti'],
		['Y11_Q47b', 'Problém s návštěvou lékaře z důvodu dlouhé lhůty objednání'],
		['Y11_Q47c', 'Problém s návštěvou lékaře z důvodu doby strávené v čekárně v den objednání'],
		['Y11_Q47d', 'Problém s návštěvou lékaře z důvodu ceny'],
		['Y11_Q53a', 'Jak byste hodnotil(a) kvalitu zdravotní péče ve Vaší zemi? '],
		['Y11_Q53b', 'Jak byste hodnotil(a) kvalitu vzdělávacího systému ve Vaší zemi? '],
		['Y11_Q53c', 'Jak byste hodnotil(a) kvalitu veřejné dopravy ve Vaší zemi? '],
		['Y11_Q53g', 'Jak byste hodnotil(a) kvalitu státního důchodového systému ve Vaší zemi? '],
		['Y11_Q58', 'Je Vaše domácnost schopna vyjít s penězi?'],
		['Y11_Q59a', 'Můžete si dovolit udržovat v domácnosti přiměřené teplo?'],
		['Y11_Q59b', 'Můžete si dovolit zaplatit ročně za týden dovolené mimo domov?'],
		['Y11_Q59c', 'Můžete si dovolit vyměnit jakýkoliv opotřebovaný nábytek?'],
		['Y11_Q59d', 'Můžete si dovolit mít každý druhý den jídlo s masem, s kuřetem nebo rybou, pokud byste je chtěl(a)?'],
		['Y11_Q59e', 'Můžete si dovolit kupovat si spíše nové oblečení než obnošené oblečení (ze second‐handu)?'],
		['Y11_Q59f', 'Můžete si dovolit alespoň jednou za měsíc pozvat domů přátele nebo rodinu na nějaké pití nebo jídlo?'],
		['Y11_Q60a', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu s placením nájmu nebo hypotéky za bydlení?'],
		['Y11_Q60b', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu s placením účtů za elektřinu, vodu, plyn?']
	];
var question_answer
	 = [
	
		['Y11_Q12a', '1--Several-times-a-week', 'Několikrát týdně'],
		['Y11_Q12a', '2--Several-times-a-month', 'Několikrát měsíčně'],
		['Y11_Q12a', '3--Several-times-a-year', 'Několikrát ročně'],
		['Y11_Q12a', '4--Less-often-rarely', 'Méně často nebo zřídka'],
		['Y11_Q12a', '5--Never', 'Nikdy'],
		['Y11_Q12b', '1--Several-times-a-week', 'Několikrát týdně'],
		['Y11_Q12b', '2--Several-times-a-month', 'Několikrát měsíčně'],
		['Y11_Q12b', '3--Several-times-a-year', 'Několikrát ročně'],
		['Y11_Q12b', '4--Less-often-rarely', 'Méně často nebo zřídka'],
		['Y11_Q12b', '5--Never', 'Nikdy'],
		['Y11_Q12c', '1--Several-times-a-week', 'Několikrát týdně'],
		['Y11_Q12c', '2--Several-times-a-month', 'Několikrát měsíčně'],
		['Y11_Q12c', '3--Several-times-a-year', 'Několikrát ročně'],
		['Y11_Q12c', '4--Less-often-rarely', 'Méně často nebo zřídka'],
		['Y11_Q12c', '5--Never', 'Nikdy'],
		['Y11_Q15', '1--Very-likely', 'Velmi pravděpodobné'],
		['Y11_Q15', '2--Quite-likely', 'Spíše pravděpodobné'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Není to ani pravděpodobné, ani nepravděpodobné'],
		['Y11_Q15', '4--Quite-unlikely', 'Spíše nepravděpodobné'],
		['Y11_Q15', '5--Very-unlikely', 'Velmi nepravděpodobné'],
		['Y11_Q18', '1--Own-without-mortgage', 'Vlastník bez hypotéky'],
		['Y11_Q18', '2--Own-with-mortgage', 'Vlastník s hypotékou'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Nájemník platící nájem v rámci sociálního bydlení nebo v obecním bytě'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Nájemník platící nájem soukromému vlastníkovi nemovitosti'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Ubytování/bydlení je poskytnuto zdarma, bez nutnosti platit nájem'],
		['Y11_Q18', '6--Other', 'Jiné'],
		['Y11_Q19a', '1--Yes', 'Ano'],
		['Y11_Q19a', '2--No', 'Ne'],
		['Y11_Q19b', '1--Yes', 'Ano'],
		['Y11_Q19b', '2--No', 'Ne'],
		['Y11_Q19c', '1--Yes', 'Ano'],
		['Y11_Q19c', '2--No', 'Ne'],
		['Y11_Q19d', '1--Yes', 'Ano'],
		['Y11_Q19d', '2--No', 'Ne'],
		['Y11_Q22_Volunteering', '3--Does-not-volunteer', 'Nevykonává dobrovolnickou činnost'],
		['Y11_Q23d', '1--Yes', 'Ano'],
		['Y11_Q23d', '2--No', 'Ne'],
		['Y11_Q24', 'Mean', 'Střední hodnota'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Velké napětí'],
		['Y11_Q25a', '2--Some-tension', 'Malé napětí'],
		['Y11_Q25a', '3--No-tension', 'Žádné napětí'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Velké napětí'],
		['Y11_Q25b', '2--Some-tension', 'Malé napětí'],
		['Y11_Q25b', '3--No-tension', 'Žádné napětí'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Velké napětí'],
		['Y11_Q25c', '2--Some-tension', 'Malé napětí'],
		['Y11_Q25c', '3--No-tension', 'Žádné napětí'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Velké napětí'],
		['Y11_Q25d', '2--Some-tension', 'Malé napětí'],
		['Y11_Q25d', '3--No-tension', 'Žádné napětí'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Velké napětí'],
		['Y11_Q25e', '2--Some-tension', 'Malé napětí'],
		['Y11_Q25e', '3--No-tension', 'Žádné napětí'],
		['Y11_Q30', 'Mean', 'Střední hodnota'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Více než je spravedlivé'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Tak akorát'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Méně než je spravedlivé'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'V práci a doma'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'V práci nebo doma'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Malý nebo žádný stres'],
		['Y11_Q40a', 'Mean', 'Střední hodnota'],
		['Y11_Q40b', 'Mean', 'Střední hodnota'],
		['Y11_Q40c', 'Mean', 'Střední hodnota'],
		['Y11_Q40d', 'Mean', 'Střední hodnota'],
		['Y11_Q40e', 'Mean', 'Střední hodnota'],
		['Y11_Q40f', 'Mean', 'Střední hodnota'],
		['Y11_Q40g', 'Mean', 'Střední hodnota'],
		['Y11_Q41', 'Mean', 'Střední hodnota'],
		['Y11_Q47a', '1--Very-difficult', 'Velmi obtížné'],
		['Y11_Q47a', '2--A-little-difficult', 'Trochu obtížné'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Vůbec to není obtížné'],
		['Y11_Q47b', '1--Very-difficult', 'Velmi obtížné'],
		['Y11_Q47b', '2--A-little-difficult', 'Trochu obtížné'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Vůbec to není obtížné'],
		['Y11_Q47c', '1--Very-difficult', 'Velmi obtížné'],
		['Y11_Q47c', '2--A-little-difficult', 'Trochu obtížné'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Vůbec to není obtížné'],
		['Y11_Q47d', '1--Very-difficult', 'Velmi obtížné'],
		['Y11_Q47d', '2--A-little-difficult', 'Trochu obtížné'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Vůbec to není obtížné'],
		['Y11_Q52', 'Mean', 'Střední hodnota'],
		['Y11_Q53a', 'Mean', 'Střední hodnota'],
		['Y11_Q53b', 'Mean', 'Střední hodnota'],
		['Y11_Q53c', 'Mean', 'Střední hodnota'],
		['Y11_Q53g', 'Mean', 'Střední hodnota'],
		['Y11_Q58', '1--With-great-difficulty', 'S velkými obtížemi'],
		['Y11_Q58', '2--With-difficulty', 'S obtížemi'],
		['Y11_Q58', '3--With-some-difficulty', 'S určitými obtížemi'],
		['Y11_Q58', '4--Fairly-easily', 'Poměrně snadno'],
		['Y11_Q58', '5--Easily', 'Snadno'],
		['Y11_Q58', '6--Very-easily', 'Velmi snadno'],
		['Y11_Q59a', '1--No', 'Ne'],
		['Y11_Q59a', '2--Yes', 'Ano'],
		['Y11_Q59b', '1--No', 'Ne'],
		['Y11_Q59b', '2--Yes', 'Ano'],
		['Y11_Q59c', '1--No', 'Ne'],
		['Y11_Q59c', '2--Yes', 'Ano'],
		['Y11_Q59d', '1--No', 'Ne'],
		['Y11_Q59d', '2--Yes', 'Ano'],
		['Y11_Q59e', '1--No', 'Ne'],
		['Y11_Q59e', '2--Yes', 'Ano'],
		['Y11_Q59f', '1--No', 'Ne'],
		['Y11_Q59f', '2--Yes', 'Ano'],
		['Y11_Q60a', '1--Yes', 'Ano'],
		['Y11_Q60a', '2--No', 'Ne'],
		['Y11_Q60b', '1--Yes', 'Ano'],
		['Y11_Q60b', '2--No', 'Ne']
	];
var country_
	 = [
	
		['AT', 'Rakousko'],
		['BE', 'Belgie'],
		['BG', 'Bulharsko'],
		['CY', 'Kypr'],
		['CZ', 'Česká republika'],
		['DE', 'Německo'],
		['DK', 'Dánsko'],
		['EE', 'Estonsko'],
		['EL', 'Řecko'],
		['ES', 'Španělsko'],
		['FI', 'Finsko'],
		['FR', 'Francie'],
		['HU', 'Maďarsko'],
		['IE', 'Irsko'],
		['IT', 'Itálie'],
		['LT', 'Litva'],
		['LU', 'Lucembursko'],
		['LV', 'Lotyšsko'],
		['MT', 'Malta'],
		['NL', 'Nizozemsko'],
		['PL', 'Polsko'],
		['PT', 'Portugalsko'],
		['RO', 'Rumunsko'],
		['SE', 'Švédsko'],
		['SI', 'Slovinsko'],
		['SK', 'Slovensko'],
		['TR', 'Turecko'],
		['UK', 'Spojené království'],
		['EuropeanUnion', 'Evropská unie']
	];
var question_meta
	 = [
	
		['Y11_Q18', 'Vlastnictví domu/bytu', ''],
		['Y11_Q19a', 'Problémy s ubytováním/bydlením: nedostatek místa', ''],
		['Y11_Q19b', 'Problémy s ubytováním/bydlením: hniloba v oknech, dveřích nebo podlaze', ''],
		['Y11_Q19c', 'Problémy s ubytováním/bydlením: vlhkost / zatékání ve zdech nebo ve střeše', ''],
		['Y11_Q19d', 'Problémy s ubytováním/bydlením: bez splachovacího záchodu v domě/bytě', ''],
		['Y11_Q52', 'Čas strávený na cestě do práce nebo do školy a zpět domů', ''],
		['Y11_Q24', 'Řekl(a) byste, že většině lidí lze důvěřovat, nebo že člověk nemůže být při jednání s lidmi nikdy dost opatrný?', ''],
		['Y11_Q25a', 'Vnímané napětí mezi chudými a bohatými lidmi', ''],
		['Y11_Q25b', 'Vnímané napětí mezi vedoucími pracovníky (managementem) a pracujícími', ''],
		['Y11_Q25c', 'Vnímané napětí mezi muži a ženami', ''],
		['Y11_Q25d', 'Vnímané napětí mezi starými a mladými lidmi', ''],
		['Y11_Q25e', 'Vnímané napětí mezi různými rasovými a etnickými skupinami', ''],
		['Y11_Q22_Volunteering', 'Jak často jste v posledních 12 měsících vykonával(a) neplacenou dobrovolnickou práci?', ''],
		['Y11_Q23d', 'Kontaktoval(a) nějakého politika nebo veřejného činitele (nemyslíme běžný kontakt související s používáním veřejných služeb)', ''],
		['Y11_Q30', 'Do jaké míry jste spokojený(á) se svým životem v dnešní době?', ''],
		['Y11_Q40a', 'Spokojenost se vzděláním', ''],
		['Y11_Q40b', 'Spokojenost se současným zaměstnáním', ''],
		['Y11_Q40c', 'Spokojenost se současnou životní úrovní', ''],
		['Y11_Q40d', 'Spokojenost s ubytováním/bydlením', ''],
		['Y11_Q40e', 'Spokojenost s rodinným životem', ''],
		['Y11_Q40f', 'Spokojenost se zdravím', ''],
		['Y11_Q40g', 'Spokojenost se společenským životem', ''],
		['Y11_Q41', 'Když se vezmou všechny okolnosti, můžete prosím uvést, jak jste šťastný(á)?', ''],
		['Y11_Q12a', 'Přišel(a) jsem z práce domů příliš unavený(á) na to, abych mohl(a) dělat domácí práce', ''],
		['Y11_Q12b', 'Vzhledem k množství času, které věnuji práci, pro mě bylo těžké plnit povinnosti vůči rodině', ''],
		['Y11_Q12c', 'Vzhledem k mým povinnostem v rodině bylo pro mě těžké se soustředit na práci', ''],
		['Y11_Q15', 'S jakou pravděpodobností by se mohlo stát, že byste v průběhu následujících 6 měsíců přišel(a) o svou práci?', ''],
		['Y11_Q38', 'Co si myslíte o svém podílu na domácích pracích?', ''],
		['Y11_Q39d_stress', 'Stres z důvodu problémů v oblasti rovnováhy mezi pracovním a osobním životem', ''],
		['Y11_Q47a', 'Problém s návštěvou lékaře z důvodu vzdálenosti ordinace nebo nemocnice', ''],
		['Y11_Q47b', 'Problém s návštěvou lékaře z důvodu dlouhé lhůty objednání', ''],
		['Y11_Q47c', 'Problém s návštěvou lékaře z důvodu doby strávené v čekárně čekáním na lékaře v den objednání', ''],
		['Y11_Q47d', 'Problém s návštěvou lékaře z důvodu ceny zaplacené za návštěvu lékaře', ''],
		['Y11_Q53a', 'Jak byste hodnotil(a) kvalitu zdravotní péče ve Vaší zemi? ', ''],
		['Y11_Q53b', 'Jak byste hodnotil(a) kvalitu vzdělávacího systému ve Vaší zemi? ', ''],
		['Y11_Q53c', 'Jak byste hodnotil(a) kvalitu veřejné dopravy ve Vaší zemi? ', ''],
		['Y11_Q53g', 'Jak byste hodnotil(a) kvalitu státního důchodového systému ve Vaší zemi? ', ''],
		['Y11_Q58', 'Je Vaše domácnost schopna vyjít s penězi?', ''],
		['Y11_Q59a', 'Můžete si dovolit udržovat v domácnosti přiměřené teplo?', ''],
		['Y11_Q59b', 'Můžete si dovolit zaplatit ročně za týden dovolené mimo domov?', ''],
		['Y11_Q59c', 'Můžete si dovolit vyměnit jakýkoliv opotřebovaný nábytek?', ''],
		['Y11_Q59d', 'Může si Vaše domácnost dovolit mít každý druhý den jídlo s masem, kuřetem nebo rybou, pokud byste je chtěl(a)?', ''],
		['Y11_Q59e', 'Mohou si členové Vaší domácnosti dovolit kupovat si spíše nové oblečení než obnošené oblečení (ze second‐handu)?', ''],
		['Y11_Q59f', 'Může si Vaše domácnost dovolit alespoň jednou za měsíc pozvat domů přátele nebo rodinu na nějaké pití nebo jídlo?', ''],
		['Y11_Q60a', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu s placením nájmu nebo hypotéky za bydlení?', ''],
		['Y11_Q60b', 'Stalo se někdy v průběhu posledních 12 měsíců, že by Vaše domácnost byla pozadu s placením účtů za elektřinu, vodu, plyn?', '']
	];
