//Auto Generated file
var subset_
	 = [
	
		['Y11_Agecategory', 'Edad'],
		['Y11_Incomequartiles_percapita', 'Ingresos'],
		['Y11_HH2a', 'Sexo']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Todas las edades'],
		['Y11_Agecategory', '1--18-24y', 'Entre 18 y 24 años'],
		['Y11_Agecategory', '2--25-34y', 'Entre 25 y 34 años'],
		['Y11_Agecategory', '3--35-49y', 'Entre 35 y 49 años'],
		['Y11_Agecategory', '4--50-64y', 'Entre 50 y 64 años'],
		['Y11_Agecategory', '5---64y', 'Más de 64 años'],
		['Y11_HH2a', 'All', 'Ambos sexos'],
		['Y11_HH2a', '1--Female', 'Femenino'],
		['Y11_HH2a', '2--Male', 'Masculino'],
		['Y11_Incomequartiles_percapita', 'All', 'Todos los niveles de ingresos'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Más bajo'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'Segundo'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'Tercero'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Más alto']
	];
var topic_
	 = [
	
		['', 'Todas (46)'],
		['Bienestar subjetivo', 'Bienestar subjetivo (9)'],
		['Calidad de la sociedad', 'Calidad de la sociedad (6)'],
		['Empleo y equilibrio entre vida privada y vida laboral', 'Empleo y equilibrio entre vida privada y vida laboral (6)'],
		['Entorno familiar y local', 'Entorno familiar y local (6)'],
		['Exclusión social y participación en la comunidad', 'Exclusión social y participación en la comunidad (2)'],
		['Nivel de vida y privaciones', 'Nivel de vida y privaciones (9)'],
		['Servicios de salud y servicios públicos', 'Servicios de salud y servicios públicos (8)']
	];
var topic_question
	 = [
	
		['Bienestar subjetivo', 'Y11_Q30', 'Qué grado de satisfacción siente con su vida en estos momentos?'],
		['Bienestar subjetivo', 'Y11_Q40a', 'Satisfacción con la educación'],
		['Bienestar subjetivo', 'Y11_Q40b', 'Satisfacción con su empleo actual'],
		['Bienestar subjetivo', 'Y11_Q40c', 'Satisfacción con su nivel de vida actual'],
		['Bienestar subjetivo', 'Y11_Q40d', 'Satisfacción con su vivienda'],
		['Bienestar subjetivo', 'Y11_Q40e', 'Satisfacción con su vida familiar'],
		['Bienestar subjetivo', 'Y11_Q40f', 'Satisfacción con su salud'],
		['Bienestar subjetivo', 'Y11_Q40g', 'Satisfacción con su vida social'],
		['Bienestar subjetivo', 'Y11_Q41', 'En general, valore su grado de felicidad'],
		['Calidad de la sociedad', 'Y11_Q24', 'Considera usted que se puede confiar en la gente o que hay que actuar con mucha cautela al tratar con otras personas?'],
		['Calidad de la sociedad', 'Y11_Q25a', 'Tensión percibida entre ricos y pobres'],
		['Calidad de la sociedad', 'Y11_Q25b', 'Tensión percibida entre la dirección de la empresa y los trabajadores'],
		['Calidad de la sociedad', 'Y11_Q25c', 'Tensión percibida entre hombres y mujeres'],
		['Calidad de la sociedad', 'Y11_Q25d', 'Tensión percibida entre personas mayores y jóvenes'],
		['Calidad de la sociedad', 'Y11_Q25e', 'Tensión percibida entre diferentes grupos étnicos y raciales'],
		['Empleo y equilibrio entre vida privada y vida laboral', 'Y11_Q12a', 'Llego a casa demasiado cansado para hacer labores domésticas'],
		['Empleo y equilibrio entre vida privada y vida laboral', 'Y11_Q12b', 'He tenido dificultades para cumplir mis responsabilidades familiares debido al tiempo que dedico al trabajo '],
		['Empleo y equilibrio entre vida privada y vida laboral', 'Y11_Q12c', 'He tenido dificultades para concentrarme en el trabajo debido a mis responsabilidades familiares'],
		['Empleo y equilibrio entre vida privada y vida laboral', 'Y11_Q15', 'Qué probabilidades tiene de perder su empleo en los próximos seis meses?'],
		['Empleo y equilibrio entre vida privada y vida laboral', 'Y11_Q38', 'Actitud respecto al reparto de las labores domésticas'],
		['Empleo y equilibrio entre vida privada y vida laboral', 'Y11_Q39d_stress', 'Estrés'],
		['Entorno familiar y local', 'Y11_Q18', 'Propiedad de la vivienda'],
		['Entorno familiar y local', 'Y11_Q19a', 'Problemas de vivienda: falta de espacio'],
		['Entorno familiar y local', 'Y11_Q19b', 'Problemas de vivienda: Ventanas, puertas o suelos podridos'],
		['Entorno familiar y local', 'Y11_Q19c', 'Problemas de vivienda: humedad o agujeros en paredes o techo'],
		['Entorno familiar y local', 'Y11_Q19d', 'Problemas de vivienda: falta de un retrete en el interior'],
		['Entorno familiar y local', 'Y11_Q52', 'Tiempo para llegar y regresar del lugar de trabajo o estudio'],
		['Exclusión social y participación en la comunidad', 'Y11_Q22_Volunteering', 'Con qué frecuencia realizó un trabajo voluntario no remunerado en los últimos doce meses?'],
		['Exclusión social y participación en la comunidad', 'Y11_Q23d', 'Contacto con un político o funcionario público (excepto contactos rutinarios a través de servicios públicos)'],
		['Nivel de vida y privaciones', 'Y11_Q58', 'Puede llegar su familia a fin de mes?'],
		['Nivel de vida y privaciones', 'Y11_Q59a', 'Puede permitirse mantener su vivienda a una temperatura adecuada?'],
		['Nivel de vida y privaciones', 'Y11_Q59b', 'Puede permitirse pagar una semana de vacaciones anuales fuera del hogar?'],
		['Nivel de vida y privaciones', 'Y11_Q59c', 'Puede permitirse remplazar el mobiliario desgastado?'],
		['Nivel de vida y privaciones', 'Y11_Q59d', 'Puede permitirse una comida con carne, pollo o pescado cada dos días (si quisiera hacerlo)?'],
		['Nivel de vida y privaciones', 'Y11_Q59e', 'Puede permitirse comprar ropa nueva y no de segunda mano?'],
		['Nivel de vida y privaciones', 'Y11_Q59f', 'Puede permitirse invitar a amigos o familiares a tomar una copa o a comer una vez al mes?'],
		['Nivel de vida y privaciones', 'Y11_Q60a', 'Se ha retrasado su familia en el pago del alquiler o la hipoteca en los últimos doce meses?'],
		['Nivel de vida y privaciones', 'Y11_Q60b', 'Se ha retrasado su familia en el pago de los servicios públicos en los últimos doce meses?'],
		['Servicios de salud y servicios públicos', 'Y11_Q47a', 'Tengo dificultades para acudir al médico debido a la distancia'],
		['Servicios de salud y servicios públicos', 'Y11_Q47b', 'Tengo dificultades para acudir al médico debido a los plazos para recibir una cita'],
		['Servicios de salud y servicios públicos', 'Y11_Q47c', 'Tengo dificultades para acudir al médico debido al tiempo de espera el día de la cita'],
		['Servicios de salud y servicios públicos', 'Y11_Q47d', 'Tengo dificultades para acudir al médico debido al coste'],
		['Servicios de salud y servicios públicos', 'Y11_Q53a', 'Cómo calificaría la calidad de los servicios de salud de su país?'],
		['Servicios de salud y servicios públicos', 'Y11_Q53b', 'Cómo calificaría la calidad del sistema educativo de su país?'],
		['Servicios de salud y servicios públicos', 'Y11_Q53c', 'Cómo calificaría la calidad del transporte público de su país?'],
		['Servicios de salud y servicios públicos', 'Y11_Q53g', 'Cómo calificaría la calidad del régimen de pensiones públicas de su país?']
	];
var question_
	 = [
	
		['Y11_Q30', 'Qué grado de satisfacción siente con su vida en estos momentos?'],
		['Y11_Q40a', 'Satisfacción con la educación'],
		['Y11_Q40b', 'Satisfacción con su empleo actual'],
		['Y11_Q40c', 'Satisfacción con su nivel de vida actual'],
		['Y11_Q40d', 'Satisfacción con su vivienda'],
		['Y11_Q40e', 'Satisfacción con su vida familiar'],
		['Y11_Q40f', 'Satisfacción con su salud'],
		['Y11_Q40g', 'Satisfacción con su vida social'],
		['Y11_Q41', 'En general, valore su grado de felicidad'],
		['Y11_Q24', 'Considera usted que se puede confiar en la gente o que hay que actuar con mucha cautela al tratar con otras personas?'],
		['Y11_Q25a', 'Tensión percibida entre ricos y pobres'],
		['Y11_Q25b', 'Tensión percibida entre la dirección de la empresa y los trabajadores'],
		['Y11_Q25c', 'Tensión percibida entre hombres y mujeres'],
		['Y11_Q25d', 'Tensión percibida entre personas mayores y jóvenes'],
		['Y11_Q25e', 'Tensión percibida entre diferentes grupos étnicos y raciales'],
		['Y11_Q12a', 'Llego a casa demasiado cansado para hacer labores domésticas'],
		['Y11_Q12b', 'He tenido dificultades para cumplir mis responsabilidades familiares debido al tiempo que dedico al trabajo '],
		['Y11_Q12c', 'He tenido dificultades para concentrarme en el trabajo debido a mis responsabilidades familiares'],
		['Y11_Q15', 'Qué probabilidades tiene de perder su empleo en los próximos seis meses?'],
		['Y11_Q38', 'Actitud respecto al reparto de las labores domésticas'],
		['Y11_Q39d_stress', 'Estrés'],
		['Y11_Q18', 'Propiedad de la vivienda'],
		['Y11_Q19a', 'Problemas de vivienda: falta de espacio'],
		['Y11_Q19b', 'Problemas de vivienda: Ventanas, puertas o suelos podridos'],
		['Y11_Q19c', 'Problemas de vivienda: humedad o agujeros en paredes o techo'],
		['Y11_Q19d', 'Problemas de vivienda: falta de un retrete en el interior'],
		['Y11_Q52', 'Tiempo para llegar y regresar del lugar de trabajo o estudio'],
		['Y11_Q22_Volunteering', 'Con qué frecuencia realizó un trabajo voluntario no remunerado en los últimos doce meses?'],
		['Y11_Q23d', 'Contacto con un político o funcionario público (excepto contactos rutinarios a través de servicios públicos)'],
		['Y11_Q58', 'Puede llegar su familia a fin de mes?'],
		['Y11_Q59a', 'Puede permitirse mantener su vivienda a una temperatura adecuada?'],
		['Y11_Q59b', 'Puede permitirse pagar una semana de vacaciones anuales fuera del hogar?'],
		['Y11_Q59c', 'Puede permitirse remplazar el mobiliario desgastado?'],
		['Y11_Q59d', 'Puede permitirse una comida con carne, pollo o pescado cada dos días (si quisiera hacerlo)?'],
		['Y11_Q59e', 'Puede permitirse comprar ropa nueva y no de segunda mano?'],
		['Y11_Q59f', 'Puede permitirse invitar a amigos o familiares a tomar una copa o a comer una vez al mes?'],
		['Y11_Q60a', 'Se ha retrasado su familia en el pago del alquiler o la hipoteca en los últimos doce meses?'],
		['Y11_Q60b', 'Se ha retrasado su familia en el pago de los servicios públicos en los últimos doce meses?'],
		['Y11_Q47a', 'Tengo dificultades para acudir al médico debido a la distancia'],
		['Y11_Q47b', 'Tengo dificultades para acudir al médico debido a los plazos para recibir una cita'],
		['Y11_Q47c', 'Tengo dificultades para acudir al médico debido al tiempo de espera el día de la cita'],
		['Y11_Q47d', 'Tengo dificultades para acudir al médico debido al coste'],
		['Y11_Q53a', 'Cómo calificaría la calidad de los servicios de salud de su país?'],
		['Y11_Q53b', 'Cómo calificaría la calidad del sistema educativo de su país?'],
		['Y11_Q53c', 'Cómo calificaría la calidad del transporte público de su país?'],
		['Y11_Q53g', 'Cómo calificaría la calidad del régimen de pensiones públicas de su país?']
	];
var question_answer
	 = [
	
		['Y11_Q12a', '1--Several-times-a-week', 'Varias veces a la semana'],
		['Y11_Q12a', '2--Several-times-a-month', 'Varias veces al mes'],
		['Y11_Q12a', '3--Several-times-a-year', 'Varias veces al año'],
		['Y11_Q12a', '4--Less-often-rarely', 'Con menor frecuencia / raramente'],
		['Y11_Q12a', '5--Never', 'Nunca'],
		['Y11_Q12b', '1--Several-times-a-week', 'Varias veces a la semana'],
		['Y11_Q12b', '2--Several-times-a-month', 'Varias veces al mes'],
		['Y11_Q12b', '3--Several-times-a-year', 'Varias veces al año'],
		['Y11_Q12b', '4--Less-often-rarely', 'Con menor frecuencia / raramente'],
		['Y11_Q12b', '5--Never', 'Nunca'],
		['Y11_Q12c', '1--Several-times-a-week', 'Varias veces a la semana'],
		['Y11_Q12c', '2--Several-times-a-month', 'Varias veces al mes'],
		['Y11_Q12c', '3--Several-times-a-year', 'Varias veces al año'],
		['Y11_Q12c', '4--Less-often-rarely', 'Con menor frecuencia / raramente'],
		['Y11_Q12c', '5--Never', 'Nunca'],
		['Y11_Q15', '1--Very-likely', 'Muy probable '],
		['Y11_Q15', '2--Quite-likely', 'Bastante probable'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Ni probable ni improbable'],
		['Y11_Q15', '4--Quite-unlikely', 'Bastante improbable'],
		['Y11_Q15', '5--Very-unlikely', 'Muy improbable'],
		['Y11_Q18', '1--Own-without-mortgage', 'Propietario sin hipoteca'],
		['Y11_Q18', '2--Own-with-mortgage', 'Propietario con hipoteca'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Inquilino, pagando un alquiler a un servicio de viviendas sociales/municipales/ de voluntarios'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Inquilino, pagando un alquiler a un casero particular'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'La vivienda está cedida de manera gratuita'],
		['Y11_Q18', '6--Other', 'Otro'],
		['Y11_Q19a', '1--Yes', 'Sí'],
		['Y11_Q19a', '2--No', 'No'],
		['Y11_Q19b', '1--Yes', 'Sí'],
		['Y11_Q19b', '2--No', 'No'],
		['Y11_Q19c', '1--Yes', 'Sí'],
		['Y11_Q19c', '2--No', 'No'],
		['Y11_Q19d', '1--Yes', 'Sí'],
		['Y11_Q19d', '2--No', 'No'],
		['Y11_Q22_Volunteering', '3--Does-not-volunteer', 'Nunca hace labores de voluntariado'],
		['Y11_Q23d', '1--Yes', 'Sí'],
		['Y11_Q23d', '2--No', 'No'],
		['Y11_Q24', 'Mean', 'Media'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Mucha tensión'],
		['Y11_Q25a', '2--Some-tension', 'Algo de tensión'],
		['Y11_Q25a', '3--No-tension', 'No hay tensión'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Mucha tensión'],
		['Y11_Q25b', '2--Some-tension', 'Algo de tensión'],
		['Y11_Q25b', '3--No-tension', 'No hay tensión'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Mucha tensión'],
		['Y11_Q25c', '2--Some-tension', 'Algo de tensión'],
		['Y11_Q25c', '3--No-tension', 'No hay tensión'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Mucha tensión'],
		['Y11_Q25d', '2--Some-tension', 'Algo de tensión'],
		['Y11_Q25d', '3--No-tension', 'No hay tensión'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Mucha tensión'],
		['Y11_Q25e', '2--Some-tension', 'Algo de tensión'],
		['Y11_Q25e', '3--No-tension', 'No hay tensión'],
		['Y11_Q30', 'Mean', 'Media'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Más de lo que me corresponde'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Aproximadamente lo que me corresponde'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Menos de lo que me corresponde '],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'En casa y en el trabajo'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Ni en casa ni en el trabajo'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Poco o nada de estrés'],
		['Y11_Q40a', 'Mean', 'Media'],
		['Y11_Q40b', 'Mean', 'Media'],
		['Y11_Q40c', 'Mean', 'Media'],
		['Y11_Q40d', 'Mean', 'Media'],
		['Y11_Q40e', 'Mean', 'Media'],
		['Y11_Q40f', 'Mean', 'Media'],
		['Y11_Q40g', 'Mean', 'Media'],
		['Y11_Q41', 'Mean', 'Media'],
		['Y11_Q47a', '1--Very-difficult', 'Muy difícil'],
		['Y11_Q47a', '2--A-little-difficult', 'Un poco difícil'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Nada difícil'],
		['Y11_Q47b', '1--Very-difficult', 'Muy difícil'],
		['Y11_Q47b', '2--A-little-difficult', 'Un poco difícil'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Nada difícil'],
		['Y11_Q47c', '1--Very-difficult', 'Muy difícil'],
		['Y11_Q47c', '2--A-little-difficult', 'Un poco difícil'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Nada difícil'],
		['Y11_Q47d', '1--Very-difficult', 'Muy difícil'],
		['Y11_Q47d', '2--A-little-difficult', 'Un poco difícil'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Nada difícil'],
		['Y11_Q52', 'Mean', 'Media'],
		['Y11_Q53a', 'Mean', 'Media'],
		['Y11_Q53b', 'Mean', 'Media'],
		['Y11_Q53c', 'Mean', 'Media'],
		['Y11_Q53g', 'Mean', 'Media'],
		['Y11_Q58', '1--With-great-difficulty', 'Muy difícil'],
		['Y11_Q58', '2--With-difficulty', 'Difícil'],
		['Y11_Q58', '3--With-some-difficulty', 'Un poco difícil'],
		['Y11_Q58', '4--Fairly-easily', 'Algo fácil'],
		['Y11_Q58', '5--Easily', 'Fácil'],
		['Y11_Q58', '6--Very-easily', 'Muy fácil'],
		['Y11_Q59a', '1--No', 'No'],
		['Y11_Q59a', '2--Yes', 'Sí'],
		['Y11_Q59b', '1--No', 'No'],
		['Y11_Q59b', '2--Yes', 'Sí'],
		['Y11_Q59c', '1--No', 'No'],
		['Y11_Q59c', '2--Yes', 'Sí'],
		['Y11_Q59d', '1--No', 'No'],
		['Y11_Q59d', '2--Yes', 'Sí'],
		['Y11_Q59e', '1--No', 'No'],
		['Y11_Q59e', '2--Yes', 'Sí'],
		['Y11_Q59f', '1--No', 'No'],
		['Y11_Q59f', '2--Yes', 'Sí'],
		['Y11_Q60a', '1--Yes', 'Sí'],
		['Y11_Q60a', '2--No', 'No'],
		['Y11_Q60b', '1--Yes', 'Sí'],
		['Y11_Q60b', '2--No', 'No']
	];
var country_
	 = [
	
		['AT', 'Austria'],
		['BE', 'Bélgica'],
		['BG', 'Bulgaria'],
		['CY', 'Chipre'],
		['CZ', 'República Checa'],
		['DE', 'Alemania'],
		['DK', 'Dinamarca'],
		['EE', 'Estonia'],
		['EL', 'Grecia'],
		['ES', 'España'],
		['FI', 'Finlandia'],
		['FR', 'Francia'],
		['HU', 'Hungría'],
		['IE', 'Irlanda'],
		['IT', 'Italia'],
		['LT', 'Lituania'],
		['LU', 'Luxemburgo'],
		['LV', 'Letonia'],
		['MT', 'Malta'],
		['NL', 'Países Bajos'],
		['PL', 'Polonia'],
		['PT', 'Portugal'],
		['RO', 'Rumanía'],
		['SE', 'Suecia'],
		['SI', 'Eslovenia'],
		['SK', 'Eslovaquia'],
		['TR', 'Turquía'],
		['UK', 'Reino Unido'],
		['EuropeanUnion', 'Unión Europea']
	];
var question_meta
	 = [
	
		['Y11_Q30', 'Qué grado de satisfacción siente con su vida en estos momentos?', ''],
		['Y11_Q40a', 'Satisfacción con la educación', ''],
		['Y11_Q40b', 'Satisfacción con su empleo actual', ''],
		['Y11_Q40c', 'Satisfacción con su nivel de vida actual', ''],
		['Y11_Q40d', 'Satisfacción con su vivienda', ''],
		['Y11_Q40e', 'Satisfacción con su vida familiar', ''],
		['Y11_Q40f', 'Satisfacción con su salud', ''],
		['Y11_Q40g', 'Satisfacción con su vida social', ''],
		['Y11_Q41', 'En general, valore su grado de felicidad', ''],
		['Y11_Q24', 'Considera usted que se puede confiar en la gente o que hay que actuar con mucha cautela al tratar con otras personas?', ''],
		['Y11_Q25a', 'Tensión percibida entre ricos y pobres', ''],
		['Y11_Q25b', 'Tensión percibida entre la dirección de la empresa y los trabajadores', ''],
		['Y11_Q25c', 'Tensión percibida entre hombres y mujeres', ''],
		['Y11_Q25d', 'Tensión percibida entre personas mayores y jóvenes', ''],
		['Y11_Q25e', 'Tensión percibida entre diferentes grupos étnicos y raciales', ''],
		['Y11_Q12a', ' Llego a casa demasiado cansado para hacer labores domésticas', ''],
		['Y11_Q12b', 'He tenido dificultades para cumplir mis responsabilidades familiares debido al tiempo que dedico al trabajo ', ''],
		['Y11_Q12c', 'He tenido dificultades para concentrarme en el trabajo debido a mis responsabilidades familiares', ''],
		['Y11_Q15', 'Qué probabilidades tiene de perder su empleo en los próximos seis meses?', ''],
		['Y11_Q38', 'Qué opina de la parte de las labores domésticas que realiza?', ''],
		['Y11_Q39d_stress', 'Estrés debido a problemas relacionados con el equilibrio entre vida privada y vida laboral', ''],
		['Y11_Q18', 'Propiedad de la vivienda', ''],
		['Y11_Q19a', 'Problemas de alojamiento: falta de espacio', ''],
		['Y11_Q19b', 'Problemas de alojamiento: Ventanas, puertas o suelos podridos', ''],
		['Y11_Q19c', 'Problemas de alojamiento: humedad o agujeros en paredes o techo', ''],
		['Y11_Q19d', 'Problemas de alojamiento: falta de un retrete al interior', ''],
		['Y11_Q52', 'Tiempo para llegar y regresar del lugar de trabajo o estudio', ''],
		['Y11_Q22_Volunteering', 'Con qué frecuencia realizó un trabajo voluntario no remunerado en los últimos doce meses?', ''],
		['Y11_Q23d', 'Contacto con un político o funcionario público (excepto contactos rutinarios a través de servicios públicos)', ''],
		['Y11_Q58', 'Puede llegar su familia a fin de mes?', ''],
		['Y11_Q59a', 'Puede permitirse mantener su vivienda a una temperatura adecuada?', ''],
		['Y11_Q59b', 'Puede permitirse pagar una semana de vacaciones anuales fuera del hogar?', ''],
		['Y11_Q59c', 'Puede permitirse remplazar el mobiliario desgastado?', ''],
		['Y11_Q59d', 'Puede su familia permitirse una comida con carne, pollo o pescado cada dos días (si quisiera hacerlo)?', ''],
		['Y11_Q59e', 'Pueden los miembros de su familia permitirse comprar ropa nueva y no de segunda mano?', ''],
		['Y11_Q59f', 'Puede su familia permitirse invitar a amigos o familiares a tomar una copa o a comer una vez al mes?', ''],
		['Y11_Q60a', 'Se ha retrasado su familia en el pago del alquiler o la hipoteca en los últimos doce meses?', ''],
		['Y11_Q60b', 'Se ha retrasado su familia en el pago de los servicios públicos en los últimos doce meses?', ''],
		['Y11_Q47a', 'Tengo dificultades para acudir al médico debido a la distancia a su consultorio o al hospital', ''],
		['Y11_Q47b', 'Tengo dificultades para acudir al médico debido a los plazos para recibir una cita', ''],
		['Y11_Q47c', 'Tengo dificultades para acudir al médico debido al tiempo de espera para ver al médico el día de la cita', ''],
		['Y11_Q47d', 'Tengo dificultades para acudir al médico por el coste que ello representa', ''],
		['Y11_Q53a', 'Cómo calificaría la calidad de los servicios de salud en su país?', ''],
		['Y11_Q53b', 'Cómo calificaría la calidad del sistema educativo en su país?', ''],
		['Y11_Q53c', 'Cómo calificaría la calidad del transporte público en su país?', ''],
		['Y11_Q53g', 'Cómo calificaría la calidad del régimen de pensiones públicas de su país?', '']
	];
