//Auto Generated file
var subset_
	 = [
	
		['Y11_Incomequartiles_percapita', 'Jövedelem'],
		['Y11_Agecategory', 'Kor'],
		['Y11_HH2a', 'Nem']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Minden korcsoport'],
		['Y11_Agecategory', '1--18-24y', '18–24 év'],
		['Y11_Agecategory', '2--25-34y', '25–34 év'],
		['Y11_Agecategory', '3--35-49y', '35–49 év'],
		['Y11_Agecategory', '4--50-64y', '50–64 év'],
		['Y11_Agecategory', '5---64y', '64 év felett'],
		['Y11_HH2a', 'All', 'Minkét nem'],
		['Y11_HH2a', '1--Female', 'Nő'],
		['Y11_HH2a', '2--Male', 'Férfi'],
		['Y11_Incomequartiles_percapita', 'All', 'Az összes jövedelemszint'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Legalacsonyabb'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'második'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'harmadik'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'A legmagasabb']
	];
var topic_
	 = [
	
		['', 'Összes (46)'],
		['A társadalom minősége', 'A társadalom minősége (6)'],
		['Az otthon és környezete', 'Az otthon és környezete (6)'],
		['Egészségügyi és közszolgáltatások', 'Egészségügyi és közszolgáltatások (8)'],
		['Foglalkoztatás, illetve a munka és a magánélet közötti egyensúly', 'Foglalkoztatás, illetve a munka és a magánélet közötti egyensúly (6)'],
		['Szubjektív jólét', 'Szubjektív jólét (9)'],
		['Társadalmi kirekesztés és közösségi szerepvállalás', 'Társadalmi kirekesztés és közösségi szerepvállalás (2)'],
		['Életszínvonal és nélkülözés', 'Életszínvonal és nélkülözés (9)']
	];
var topic_question
	 = [
	
		['A társadalom minősége', 'Y11_Q24', 'Melyik állítással ért egyet: hogy az emberek többségében meg lehet bízni, vagy hogy az emberekkel kapcsolatban nem lehet elég óvatosnak lenni?'],
		['A társadalom minősége', 'Y11_Q25a', 'A gazdagok és a szegények között érzékelt feszültségek'],
		['A társadalom minősége', 'Y11_Q25b', 'A vállalatvezetők és a munkavállalók között érzékelt feszültségek'],
		['A társadalom minősége', 'Y11_Q25c', 'A férfiak és nők között érzékelt feszültségek'],
		['A társadalom minősége', 'Y11_Q25d', 'Az idősek és fiatalok között érzékelt feszültségek'],
		['A társadalom minősége', 'Y11_Q25e', 'A különböző faji és nemzetiségi csoportok között érzékelt feszültségek'],
		['Az otthon és környezete', 'Y11_Q18', 'Lakástulajdon'],
		['Az otthon és környezete', 'Y11_Q19a', 'A lakással kapcsolatos problémák: helyszűke'],
		['Az otthon és környezete', 'Y11_Q19b', 'A lakással kapcsolatos problémák: az ablakok, az ajtók vagy a padló korhadása'],
		['Az otthon és környezete', 'Y11_Q19c', 'A lakással kapcsolatos problémák: nyirkosság vagy beázás a falakon vagy a tetőn'],
		['Az otthon és környezete', 'Y11_Q19d', 'A lakással kapcsolatos problémák: beltéri vízöblítéses WC hiánya'],
		['Az otthon és környezete', 'Y11_Q52', 'A munkába vagy iskolába (és onnan haza) történő eljutással töltött idő'],
		['Egészségügyi és közszolgáltatások', 'Y11_Q47a', 'Az orvosi ellátással kapcsolatos nehézségek a távolság miatt'],
		['Egészségügyi és közszolgáltatások', 'Y11_Q47b', 'Az orvosi ellátással kapcsolatos nehézségek a hosszú várólista miatt'],
		['Egészségügyi és közszolgáltatások', 'Y11_Q47c', 'Az orvosi ellátással kapcsolatos nehézségek a vizsgálatra megbeszélt napon tapasztalt hosszú várakozási idő miatt'],
		['Egészségügyi és közszolgáltatások', 'Y11_Q47d', 'Az orvosi ellátással kapcsolatos nehézségek a költségek miatt'],
		['Egészségügyi és közszolgáltatások', 'Y11_Q53a', 'Hogyan minősítené a magyar egészségügyi szolgáltatásokat?'],
		['Egészségügyi és közszolgáltatások', 'Y11_Q53b', 'Hogyan minősítené a magyar oktatási rendszert?'],
		['Egészségügyi és közszolgáltatások', 'Y11_Q53c', 'Hogyan minősítené a magyarországi tömegközlekedést?'],
		['Egészségügyi és közszolgáltatások', 'Y11_Q53g', 'Hogyan minősítené a magyar állami nyugdíjrendszert?'],
		['Foglalkoztatás, illetve a munka és a magánélet közötti egyensúly', 'Y11_Q12a', 'Túl fáradtan érkezem haza a munkából ahhoz, hogy házimunkát végezzek'],
		['Foglalkoztatás, illetve a munka és a magánélet közötti egyensúly', 'Y11_Q12b', 'Nehéz volt teljesítenem a családi kötelezettségeimet a munkahelyemen töltött idő hossza miatt '],
		['Foglalkoztatás, illetve a munka és a magánélet közötti egyensúly', 'Y11_Q12c', 'Nehezen tudtam összpontosítani a munkámra a családi kötelezettségeim miatt'],
		['Foglalkoztatás, illetve a munka és a magánélet közötti egyensúly', 'Y11_Q15', 'Mennyire tartja valószínűnek, hogy a következő hat hónap során elveszíti az állását?'],
		['Foglalkoztatás, illetve a munka és a magánélet közötti egyensúly', 'Y11_Q38', 'A házimunka megosztására vonatkozó vélemény'],
		['Foglalkoztatás, illetve a munka és a magánélet közötti egyensúly', 'Y11_Q39d_stress', 'Stressz'],
		['Szubjektív jólét', 'Y11_Q30', 'Mennyire elégedett az életével mostanában?'],
		['Szubjektív jólét', 'Y11_Q40a', 'Elégedettség az oktatással'],
		['Szubjektív jólét', 'Y11_Q40b', 'Elégedettség a jelenlegi munkával'],
		['Szubjektív jólét', 'Y11_Q40c', 'Elégedettség a jelenlegi életszínvonallal'],
		['Szubjektív jólét', 'Y11_Q40d', 'Elégedettség a lakhatással'],
		['Szubjektív jólét', 'Y11_Q40e', 'Elégedettség a családi élettel'],
		['Szubjektív jólét', 'Y11_Q40f', 'Elégedettség az egészségi állapottal'],
		['Szubjektív jólét', 'Y11_Q40g', 'Elégedettség a társasági élettel'],
		['Szubjektív jólét', 'Y11_Q41', 'Mindent egybevetve, mennyire érzi boldognak magát?'],
		['Társadalmi kirekesztés és közösségi szerepvállalás', 'Y11_Q22_Volunteering', 'Milyen gyakran végzett fizetetlen önkéntes munkát az elmúlt egy évben?'],
		['Társadalmi kirekesztés és közösségi szerepvállalás', 'Y11_Q23d', 'Kapcsolatba került egy politikussal vagy köztisztviselővel (a közszolgáltatás kapcsán felmerülő szokásos kapcsolatvételen túl)'],
		['Életszínvonal és nélkülözés', 'Y11_Q58', 'Meg tud-e élni háztartása havi jövedelméből?'],
		['Életszínvonal és nélkülözés', 'Y11_Q59a', 'Megengedheti-e magának, hogy kellően melegen tartsa otthonát?'],
		['Életszínvonal és nélkülözés', 'Y11_Q59b', 'Megengedheti-e magának, hogy évente egyszer egy hétre elmenjen nyaralni?'],
		['Életszínvonal és nélkülözés', 'Y11_Q59c', 'Megengedheti-e magának, hogy lecserélje elhasználódott bútorait?'],
		['Életszínvonal és nélkülözés', 'Y11_Q59d', 'Megengedheti-e magának, hogy minden másnap húst, csirkét vagy halat egyen (ha akar)?'],
		['Életszínvonal és nélkülözés', 'Y11_Q59e', 'Megengedheti-e magának, hogy új, és ne használt ruhákat vásároljon?'],
		['Életszínvonal és nélkülözés', 'Y11_Q59f', 'Megengedheti-e magának, hogy havonta legalább egyszer vendégül lássa barátait vagy családját egy italra vagy étkezésre?'],
		['Életszínvonal és nélkülözés', 'Y11_Q60a', 'Előfordult-e a háztartásában az elmúlt 12 hónap során, hogy nem tudta fizetni a lakbért vagy a lakáshitel‐törlesztést?'],
		['Életszínvonal és nélkülözés', 'Y11_Q60b', 'Előfordult-e a háztartásában az elmúlt 12 hónap során, hogy nem tudta fizetni a közüzemi számlákat?']
	];
var question_
	 = [
	
		['Y11_Q24', 'Melyik állítással ért egyet: hogy az emberek többségében meg lehet bízni, vagy hogy az emberekkel kapcsolatban nem lehet elég óvatosnak lenni?'],
		['Y11_Q25a', 'A gazdagok és a szegények között érzékelt feszültségek'],
		['Y11_Q25b', 'A vállalatvezetők és a munkavállalók között érzékelt feszültségek'],
		['Y11_Q25c', 'A férfiak és nők között érzékelt feszültségek'],
		['Y11_Q25d', 'Az idősek és fiatalok között érzékelt feszültségek'],
		['Y11_Q25e', 'A különböző faji és nemzetiségi csoportok között érzékelt feszültségek'],
		['Y11_Q18', 'Lakástulajdon'],
		['Y11_Q19a', 'A lakással kapcsolatos problémák: helyszűke'],
		['Y11_Q19b', 'A lakással kapcsolatos problémák: az ablakok, az ajtók vagy a padló korhadása'],
		['Y11_Q19c', 'A lakással kapcsolatos problémák: nyirkosság vagy beázás a falakon vagy a tetőn'],
		['Y11_Q19d', 'A lakással kapcsolatos problémák: beltéri vízöblítéses WC hiánya'],
		['Y11_Q52', 'A munkába vagy iskolába (és onnan haza) történő eljutással töltött idő'],
		['Y11_Q47a', 'Az orvosi ellátással kapcsolatos nehézségek a távolság miatt'],
		['Y11_Q47b', 'Az orvosi ellátással kapcsolatos nehézségek a hosszú várólista miatt'],
		['Y11_Q47c', 'Az orvosi ellátással kapcsolatos nehézségek a vizsgálatra megbeszélt napon tapasztalt hosszú várakozási idő miatt'],
		['Y11_Q47d', 'Az orvosi ellátással kapcsolatos nehézségek a költségek miatt'],
		['Y11_Q53a', 'Hogyan minősítené a magyar egészségügyi szolgáltatásokat?'],
		['Y11_Q53b', 'Hogyan minősítené a magyar oktatási rendszert?'],
		['Y11_Q53c', 'Hogyan minősítené a magyarországi tömegközlekedést?'],
		['Y11_Q53g', 'Hogyan minősítené a magyar állami nyugdíjrendszert?'],
		['Y11_Q12a', 'Túl fáradtan érkezem haza a munkából ahhoz, hogy házimunkát végezzek'],
		['Y11_Q12b', 'Nehéz volt teljesítenem a családi kötelezettségeimet a munkahelyemen töltött idő hossza miatt '],
		['Y11_Q12c', 'Nehezen tudtam összpontosítani a munkámra a családi kötelezettségeim miatt'],
		['Y11_Q15', 'Mennyire tartja valószínűnek, hogy a következő hat hónap során elveszíti az állását?'],
		['Y11_Q38', 'A házimunka megosztására vonatkozó vélemény'],
		['Y11_Q39d_stress', 'Stressz'],
		['Y11_Q30', 'Mennyire elégedett az életével mostanában?'],
		['Y11_Q40a', 'Elégedettség az oktatással'],
		['Y11_Q40b', 'Elégedettség a jelenlegi munkával'],
		['Y11_Q40c', 'Elégedettség a jelenlegi életszínvonallal'],
		['Y11_Q40d', 'Elégedettség a lakhatással'],
		['Y11_Q40e', 'Elégedettség a családi élettel'],
		['Y11_Q40f', 'Elégedettség az egészségi állapottal'],
		['Y11_Q40g', 'Elégedettség a társasági élettel'],
		['Y11_Q41', 'Mindent egybevetve, mennyire érzi boldognak magát?'],
		['Y11_Q22_Volunteering', 'Milyen gyakran végzett fizetetlen önkéntes munkát az elmúlt egy évben?'],
		['Y11_Q23d', 'Kapcsolatba került egy politikussal vagy köztisztviselővel (a közszolgáltatás kapcsán felmerülő szokásos kapcsolatvételen túl)'],
		['Y11_Q58', 'Meg tud-e élni háztartása havi jövedelméből?'],
		['Y11_Q59a', 'Megengedheti-e magának, hogy kellően melegen tartsa otthonát?'],
		['Y11_Q59b', 'Megengedheti-e magának, hogy évente egyszer egy hétre elmenjen nyaralni?'],
		['Y11_Q59c', 'Megengedheti-e magának, hogy lecserélje elhasználódott bútorait?'],
		['Y11_Q59d', 'Megengedheti-e magának, hogy minden másnap húst, csirkét vagy halat egyen (ha akar)?'],
		['Y11_Q59e', 'Megengedheti-e magának, hogy új, és ne használt ruhákat vásároljon?'],
		['Y11_Q59f', 'Megengedheti-e magának, hogy havonta legalább egyszer vendégül lássa barátait vagy családját egy italra vagy étkezésre?'],
		['Y11_Q60a', 'Előfordult-e a háztartásában az elmúlt 12 hónap során, hogy nem tudta fizetni a lakbért vagy a lakáshitel‐törlesztést?'],
		['Y11_Q60b', 'Előfordult-e a háztartásában az elmúlt 12 hónap során, hogy nem tudta fizetni a közüzemi számlákat?']
	];
var question_answer
	 = [
	
		['Y11_Q12a', '1--Several-times-a-week', 'Hetente többször'],
		['Y11_Q12a', '2--Several-times-a-month', 'Havonta többször'],
		['Y11_Q12a', '3--Several-times-a-year', 'Évente többször'],
		['Y11_Q12a', '4--Less-often-rarely', 'Kevésbé gyakran vagy ritkán'],
		['Y11_Q12a', '5--Never', 'Soha'],
		['Y11_Q12b', '1--Several-times-a-week', 'Hetente többször'],
		['Y11_Q12b', '2--Several-times-a-month', 'Havonta többször'],
		['Y11_Q12b', '3--Several-times-a-year', 'Évente többször'],
		['Y11_Q12b', '4--Less-often-rarely', 'Kevésbé gyakran vagy ritkán'],
		['Y11_Q12b', '5--Never', 'Soha'],
		['Y11_Q12c', '1--Several-times-a-week', 'Hetente többször'],
		['Y11_Q12c', '2--Several-times-a-month', 'Havonta többször'],
		['Y11_Q12c', '3--Several-times-a-year', 'Évente többször'],
		['Y11_Q12c', '4--Less-often-rarely', 'Kevésbé gyakran vagy ritkán'],
		['Y11_Q12c', '5--Never', 'Soha'],
		['Y11_Q15', '1--Very-likely', 'Nagyon valószínű'],
		['Y11_Q15', '2--Quite-likely', 'Elég valószínű'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Nem valószínű, és nem is valószínűtlen'],
		['Y11_Q15', '4--Quite-unlikely', 'Elég valószínűtlen'],
		['Y11_Q15', '5--Very-unlikely', 'Nagyon valószínűtlen'],
		['Y11_Q18', '1--Own-without-mortgage', 'Saját tulajdonú, jelzálogteher nélküli'],
		['Y11_Q18', '2--Own-with-mortgage', 'Saját tulajdonú, jelzáloggal terhelt'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Bérlő vagyok, és szociális, önkormányzati vagy önkéntes szervezet által biztosított lakásban'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Bérlő vagyok, magánszemélynek fizetek bérleti díjat'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Nem fizetek bérleti díjat a lakhatásért'],
		['Y11_Q18', '6--Other', 'Egyéb'],
		['Y11_Q19a', '1--Yes', 'Igen'],
		['Y11_Q19a', '2--No', 'Nem'],
		['Y11_Q19b', '1--Yes', 'Igen'],
		['Y11_Q19b', '2--No', 'Nem'],
		['Y11_Q19c', '1--Yes', 'Igen'],
		['Y11_Q19c', '2--No', 'Nem'],
		['Y11_Q19d', '1--Yes', 'Igen'],
		['Y11_Q19d', '2--No', 'Nem'],
		['Y11_Q22_Volunteering', '3--Does-not-volunteer', 'Nem végez önkéntes munkát'],
		['Y11_Q23d', '1--Yes', 'Igen'],
		['Y11_Q23d', '2--No', 'Nem'],
		['Y11_Q24', 'Mean', 'Átlag'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Sok feszültség'],
		['Y11_Q25a', '2--Some-tension', 'Némi feszültség'],
		['Y11_Q25a', '3--No-tension', 'Nincs feszültség'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Sok feszültség'],
		['Y11_Q25b', '2--Some-tension', 'Némi feszültség'],
		['Y11_Q25b', '3--No-tension', 'Nincs feszültség'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Sok feszültség'],
		['Y11_Q25c', '2--Some-tension', 'Némi feszültség'],
		['Y11_Q25c', '3--No-tension', 'Nincs feszültség'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Sok feszültség'],
		['Y11_Q25d', '2--Some-tension', 'Némi feszültség'],
		['Y11_Q25d', '3--No-tension', 'Nincs feszültség'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Sok feszültség'],
		['Y11_Q25e', '2--Some-tension', 'Némi feszültség'],
		['Y11_Q25e', '3--No-tension', 'Nincs feszültség'],
		['Y11_Q30', 'Mean', 'Átlag'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Több, mint az Önre jutó méltányos rész'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Körülbelül megegyezik az Önre jutó méltányos résszel'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Kevesebb, mint az Önre jutó méltányos rész'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'A munkahelyen és otthon is'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Vagy a munkahelyen vagy otthon'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Kevés vagy semennyi stressz'],
		['Y11_Q40a', 'Mean', 'Átlag'],
		['Y11_Q40b', 'Mean', 'Átlag'],
		['Y11_Q40c', 'Mean', 'Átlag'],
		['Y11_Q40d', 'Mean', 'Átlag'],
		['Y11_Q40e', 'Mean', 'Átlag'],
		['Y11_Q40f', 'Mean', 'Átlag'],
		['Y11_Q40g', 'Mean', 'Átlag'],
		['Y11_Q41', 'Mean', 'Átlag'],
		['Y11_Q47a', '1--Very-difficult', 'Nagyon megnehezítette'],
		['Y11_Q47a', '2--A-little-difficult', 'Kicsit megnehezítette'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Egyáltalán nem nehezítette meg'],
		['Y11_Q47b', '1--Very-difficult', 'Nagyon megnehezítette'],
		['Y11_Q47b', '2--A-little-difficult', 'Kicsit megnehezítette'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Egyáltalán nem nehezítette meg'],
		['Y11_Q47c', '1--Very-difficult', 'Nagyon megnehezítette'],
		['Y11_Q47c', '2--A-little-difficult', 'Kicsit megnehezítette'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Egyáltalán nem nehezítette meg'],
		['Y11_Q47d', '1--Very-difficult', 'Nagyon megnehezítette'],
		['Y11_Q47d', '2--A-little-difficult', 'Kicsit megnehezítette'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Egyáltalán nem nehezítette meg'],
		['Y11_Q52', 'Mean', 'Átlag'],
		['Y11_Q53a', 'Mean', 'Átlag'],
		['Y11_Q53b', 'Mean', 'Átlag'],
		['Y11_Q53c', 'Mean', 'Átlag'],
		['Y11_Q53g', 'Mean', 'Átlag'],
		['Y11_Q58', '1--With-great-difficulty', 'Nagyon nehezen'],
		['Y11_Q58', '2--With-difficulty', 'Valamennyire nehezen'],
		['Y11_Q58', '3--With-some-difficulty', 'Valamennyire nehezen'],
		['Y11_Q58', '4--Fairly-easily', 'Meglehetősen könnyen'],
		['Y11_Q58', '5--Easily', 'Könnyen'],
		['Y11_Q58', '6--Very-easily', 'Nagyon könnyen'],
		['Y11_Q59a', '1--No', 'Nem'],
		['Y11_Q59a', '2--Yes', 'Igen'],
		['Y11_Q59b', '1--No', 'Nem'],
		['Y11_Q59b', '2--Yes', 'Igen'],
		['Y11_Q59c', '1--No', 'Nem'],
		['Y11_Q59c', '2--Yes', 'Igen'],
		['Y11_Q59d', '1--No', 'Nem'],
		['Y11_Q59d', '2--Yes', 'Igen'],
		['Y11_Q59e', '1--No', 'Nem'],
		['Y11_Q59e', '2--Yes', 'Igen'],
		['Y11_Q59f', '1--No', 'Nem'],
		['Y11_Q59f', '2--Yes', 'Igen'],
		['Y11_Q60a', '1--Yes', 'Igen'],
		['Y11_Q60a', '2--No', 'Nem'],
		['Y11_Q60b', '1--Yes', 'Igen'],
		['Y11_Q60b', '2--No', 'Nem']
	];
var country_
	 = [
	
		['AT', 'Ausztria'],
		['BE', 'Belgium'],
		['BG', 'Bulgária'],
		['CY', 'Ciprus'],
		['CZ', 'Csehország'],
		['DE', 'Németország'],
		['DK', 'Dánia'],
		['EE', 'Észtország'],
		['EL', 'Görögország'],
		['ES', 'Spanyolország'],
		['FI', 'Finnország'],
		['FR', 'Franciaország'],
		['HU', 'Magyarország'],
		['IE', 'Írország'],
		['IT', 'Olaszország'],
		['LT', 'Litvánia'],
		['LU', 'Luxemburg'],
		['LV', 'Lettország'],
		['MT', 'Málta'],
		['NL', 'Hollandia'],
		['PL', 'Lengyelország'],
		['PT', 'Portugália'],
		['RO', 'Románia'],
		['SE', 'Svédország'],
		['SI', 'Szlovénia'],
		['SK', 'Szlovákia'],
		['TR', 'Törökország'],
		['UK', 'Egyesült Királyság'],
		['EuropeanUnion', 'Európai Unió']
	];
var question_meta
	 = [
	
		['Y11_Q24', 'Melyik állítással ért egyet: hogy az emberek többségében meg lehet bízni, vagy hogy az emberekkel kapcsolatban nem lehet elég óvatosnak lenni?', ''],
		['Y11_Q25a', 'A gazdagok és a szegények között érzékelt feszültségek', ''],
		['Y11_Q25b', 'A vállalatvezetők és a munkavállalók között érzékelt feszültségek', ''],
		['Y11_Q25c', 'A férfiak és nők között érzékelt feszültségek', ''],
		['Y11_Q25d', 'Az idősek és fiatalok között érzékelt feszültségek', ''],
		['Y11_Q25e', 'A különböző faji és nemzetiségi csoportok között érzékelt feszültségek', ''],
		['Y11_Q18', 'Lakástulajdon', ''],
		['Y11_Q19a', 'A lakással kapcsolatos problémák: helyszűke', ''],
		['Y11_Q19b', 'A lakással kapcsolatos problémák: az ablakok, az ajtók vagy a padló korhadása', ''],
		['Y11_Q19c', 'A lakással kapcsolatos problémák: nyirkosság vagy beázás a falakon vagy a tetőn', ''],
		['Y11_Q19d', 'A lakással kapcsolatos problémák: beltéri vízöblítéses WC hiánya', ''],
		['Y11_Q52', 'A munkába vagy iskolába (és onnan haza) történő eljutással töltött idő', ''],
		['Y11_Q47a', 'Az orvosi ellátással kapcsolatos nehézségek az orvosi rendelőtől vagy a kórháztól való távolság miatt', ''],
		['Y11_Q47b', 'Az orvosi ellátással kapcsolatos nehézségek a hosszú várólista miatt', ''],
		['Y11_Q47c', 'Az orvosi ellátással kapcsolatos nehézségek a vizsgálatra megbeszélt napon tapasztalt hosszú várakozási idő miatt', ''],
		['Y11_Q47d', 'Az orvosi ellátással kapcsolatos nehézségek az orvosi vizsgálat költségei miatt', ''],
		['Y11_Q53a', 'Hogyan minősítené a magyar egészségügyi szolgáltatásokat?', ''],
		['Y11_Q53b', 'Hogyan minősítené a magyar oktatási rendszert?', ''],
		['Y11_Q53c', 'Hogyan minősítené a magyarországi tömegközlekedést?', ''],
		['Y11_Q53g', 'Hogyan minősítené a magyar állami nyugdíjrendszert?', ''],
		['Y11_Q12a', ' Túl fáradtan érkezem haza a munkából ahhoz, hogy házimunkát végezzek', ''],
		['Y11_Q12b', 'Nehéz volt teljesítenem a családi kötelezettségeimet a munkahelyemen töltött idő hossza miatt ', ''],
		['Y11_Q12c', 'Nehezen tudtam összpontosítani a munkámra a családi kötelezettségeim miatt', ''],
		['Y11_Q15', 'Mennyire tartja valószínűnek, hogy a következő hat hónap során elveszíti az állását?', ''],
		['Y11_Q38', 'Mit gondol a házimunka Önre jutó részéről?', ''],
		['Y11_Q39d_stress', 'A munka és a magánélet egyensúlyának megbomlása miatt elszenvedett stressz', ''],
		['Y11_Q30', 'Mennyire elégedett az életével mostanában?', ''],
		['Y11_Q40a', 'Elégedettség az oktatással', ''],
		['Y11_Q40b', 'Elégedettség a jelenlegi munkával', ''],
		['Y11_Q40c', 'Elégedettség a jelenlegi életszínvonallal', ''],
		['Y11_Q40d', 'Elégedettség a lakhatással', ''],
		['Y11_Q40e', 'Elégedettség a családi élettel', ''],
		['Y11_Q40f', 'Elégedettség az egészségi állapottal', ''],
		['Y11_Q40g', 'Elégedettség a társasági élettel', ''],
		['Y11_Q41', 'Mindent egybevetve, mennyire érzi boldognak magát?', ''],
		['Y11_Q22_Volunteering', 'Milyen gyakran végzett fizetetlen önkéntes munkát az elmúlt egy évben?', ''],
		['Y11_Q23d', 'Kapcsolatba került egy politikussal vagy köztisztviselővel (a közszolgáltatás kapcsán felmerülő szokásos kapcsolatvételen túl)', ''],
		['Y11_Q58', 'Meg tud-e élni háztartása havi jövedelméből?', ''],
		['Y11_Q59a', 'Megengedheti-e magának, hogy kellően melegen tartsa otthonát?', ''],
		['Y11_Q59b', 'Megengedheti-e magának, hogy évente egyszer egy hétre elmenjen nyaralni?', ''],
		['Y11_Q59c', 'Megengedheti-e magának, hogy lecserélje elhasználódott bútorait?', ''],
		['Y11_Q59d', 'Megengedheti-e magának, hogy minden másnap húst, csirkét vagy halat egyen (ha akar)?', ''],
		['Y11_Q59e', 'Háztartásának tagjai megengedhetik-e maguknak, hogy új, és ne használt ruhákat vásároljanak?', ''],
		['Y11_Q59f', 'Megengedheti-e magának, hogy havonta legalább egyszer vendégül lássa barátait vagy családját egy italra vagy étkezésre?', ''],
		['Y11_Q60a', 'Előfordult-e a háztartásában az elmúlt 12 hónap során, hogy nem tudta fizetni a lakbért vagy a lakáshitel‐törlesztést?', ''],
		['Y11_Q60b', 'Előfordult-e a háztartásában az elmúlt 12 hónap során, hogy nem tudta fizetni a közüzemi számlákat?', '']
	];
