//Auto Generated file
var subset_
	 = [
	
		['Y11_Incomequartiles_percapita', 'Dohodek'],
		['Y11_HH2a', 'Spol'],
		['Y11_Agecategory', 'Starost']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Vse starosti'],
		['Y11_Agecategory', '1--18-24y', '18 do 24 let'],
		['Y11_Agecategory', '2--25-34y', '25 do 34 let'],
		['Y11_Agecategory', '3--35-49y', '35 do 49 let'],
		['Y11_Agecategory', '4--50-64y', '50 do 64 let'],
		['Y11_Agecategory', '5---64y', '> 64 let'],
		['Y11_HH2a', 'All', 'Oba spola'],
		['Y11_HH2a', '1--Female', 'Ženski'],
		['Y11_HH2a', '2--Male', 'Moški'],
		['Y11_Incomequartiles_percapita', 'All', 'Vse dohodkovne ravni'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Najnižja'],
		['Y11_Incomequartiles_percapita', '2--2nd', 'Druga'],
		['Y11_Incomequartiles_percapita', '3--3rd', 'Tretja'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Najvišja']
	];
var topic_
	 = [
	
		['', 'vse (46)'],
		['Domače in lokalno okolje', 'Domače in lokalno okolje (6)'],
		['Kakovost družbe', 'Kakovost družbe (6)'],
		['Socialna izključenost in vključenost v skupnost', 'Socialna izključenost in vključenost v skupnost (2)'],
		['Subjektivno dobro počutje', 'Subjektivno dobro počutje (9)'],
		['Zaposlitev ter ravnovesje med poklicnim in zasebnim življenjem', 'Zaposlitev ter ravnovesje med poklicnim in zasebnim življenjem (6)'],
		['Zdravstvene in javne storitve', 'Zdravstvene in javne storitve (8)'],
		['Življenjski standard in prikrajšanost', 'Življenjski standard in prikrajšanost (9)']
	];
var topic_question
	 = [
	
		['Domače in lokalno okolje', 'Y11_Q18', 'Lastništvo stanovanja, v katerem živite'],
		['Domače in lokalno okolje', 'Y11_Q19a', 'Težave s stanovanjem, v katerem živite: pomanjkanje prostora'],
		['Domače in lokalno okolje', 'Y11_Q19b', 'Težave s stanovanjem, v katerem živite: trhla okna, vrata ali tla'],
		['Domače in lokalno okolje', 'Y11_Q19c', 'Težave s stanovanjem, v katerem živite: vlaga ali voda, ki pronica skozi stene ali streho'],
		['Domače in lokalno okolje', 'Y11_Q19d', 'Težave s stanovanjem, v katerem živite: ni notranjega stranišča na izplakovanje s tekočo vodo'],
		['Domače in lokalno okolje', 'Y11_Q52', 'Čas, ki ga porabite za pot na delo/v šolo in z dela/iz šole'],
		['Kakovost družbe', 'Y11_Q24', 'Ali menite, da lahko večini ljudi zaupate, ali da pri ravnanju z ljudmi nikoli ne morete biti dovolj previdni?'],
		['Kakovost družbe', 'Y11_Q25a', 'Zaznana nestrpnost med revnimi in bogatimi'],
		['Kakovost družbe', 'Y11_Q25b', 'Zaznana nestrpnost med ljudmi na vodilnih položajih in delavci'],
		['Kakovost družbe', 'Y11_Q25c', 'Zaznana nestrpnost med moškimi in ženskami'],
		['Kakovost družbe', 'Y11_Q25d', 'Zaznana nestrpnost med starimi in mladimi ljudmi'],
		['Kakovost družbe', 'Y11_Q25e', 'Zaznana nestrpnost med različnimi rasnimi in etničnimi skupinami'],
		['Socialna izključenost in vključenost v skupnost', 'Y11_Q22_Volunteering', 'Kako pogosto ste v zadnjih dvanajstih mesecih opravljali neplačano prostovoljno delo?'],
		['Socialna izključenost in vključenost v skupnost', 'Y11_Q23d', 'Stik s politikom ali državnim funkcionarjem (če ne upoštevate običajnih stikov prek javnih služb)'],
		['Subjektivno dobro počutje', 'Y11_Q30', 'Kako ste trenutno zadovoljni s svojim življenjem?'],
		['Subjektivno dobro počutje', 'Y11_Q40a', 'Zadovoljstvo z izobrazbo'],
		['Subjektivno dobro počutje', 'Y11_Q40b', 'Zadovoljstvo s trenutno službo'],
		['Subjektivno dobro počutje', 'Y11_Q40c', 'Zadovoljstvo s trenutnim življenjskim standardom'],
		['Subjektivno dobro počutje', 'Y11_Q40d', 'Zadovoljstvo s stanovanjem'],
		['Subjektivno dobro počutje', 'Y11_Q40e', 'Zadovoljstvo z družinskim življenjem'],
		['Subjektivno dobro počutje', 'Y11_Q40f', 'Zadovoljstvo z zdravjem'],
		['Subjektivno dobro počutje', 'Y11_Q40g', 'Zadovoljstvo z družabnim življenjem'],
		['Subjektivno dobro počutje', 'Y11_Q41', 'Gledano v celoti, kako srečni, bi rekli, da ste?'],
		['Zaposlitev ter ravnovesje med poklicnim in zasebnim življenjem', 'Y11_Q12a', 'Z dela sem se vrnil(-a) preveč utrujen(-a) za gospodinjska opravila.'],
		['Zaposlitev ter ravnovesje med poklicnim in zasebnim življenjem', 'Y11_Q12b', 'Zaradi časa, prebitega v službi, sem s težavo izpolnil(-a) svoje družinske obveznosti.'],
		['Zaposlitev ter ravnovesje med poklicnim in zasebnim življenjem', 'Y11_Q12c', 'Na delovnem mestu sem se s težavo osredotočil(-a) na delo zaradi svojih družinskih obveznosti.'],
		['Zaposlitev ter ravnovesje med poklicnim in zasebnim življenjem', 'Y11_Q15', 'Kako verjetno je, da bi izgubili svojo zaposlitev v naslednjih šestih mesecih?'],
		['Zaposlitev ter ravnovesje med poklicnim in zasebnim življenjem', 'Y11_Q38', 'Odnos do sodelovanja pri gospodinjskih opravilih'],
		['Zaposlitev ter ravnovesje med poklicnim in zasebnim življenjem', 'Y11_Q39d_stress', 'Stres'],
		['Zdravstvene in javne storitve', 'Y11_Q47a', 'Otežen obisk zdravnika zaradi oddaljenosti'],
		['Zdravstvene in javne storitve', 'Y11_Q47b', 'Otežen obisk zdravnika zaradi čakalne dobe do dneva, ko ste bili naročeni'],
		['Zdravstvene in javne storitve', 'Y11_Q47c', 'Otežen obisk zdravnika zaradi čakalnega časa na dan pregleda'],
		['Zdravstvene in javne storitve', 'Y11_Q47d', 'Otežen obisk zdravnika zaradi stroškov'],
		['Zdravstvene in javne storitve', 'Y11_Q53a', 'Kako bi ocenili kakovost zdravstvenih storitev v vaši državi?'],
		['Zdravstvene in javne storitve', 'Y11_Q53b', 'Kako bi ocenili kakovost izobraževalnega sistema v vaši državi?'],
		['Zdravstvene in javne storitve', 'Y11_Q53c', 'Kako bi ocenili kakovost javnega prevoza v vaši državi?'],
		['Zdravstvene in javne storitve', 'Y11_Q53g', 'Kako bi ocenili kakovost državnega pokojninskega sistema v vaši državi?'],
		['Življenjski standard in prikrajšanost', 'Y11_Q58', 'Ali ste se v vašem gospodinjstvu zmožni (finančno) prebiti čez mesec?'],
		['Življenjski standard in prikrajšanost', 'Y11_Q59a', 'Ali si lahko privoščite primerno ogrevan dom?'],
		['Življenjski standard in prikrajšanost', 'Y11_Q59b', 'Ali si lahko privoščite enotedenski letni dopust zunaj domačega kraja?'],
		['Življenjski standard in prikrajšanost', 'Y11_Q59c', 'Ali si lahko privoščite zamenjavo katerega koli dotrajanega kosa pohištva?'],
		['Življenjski standard in prikrajšanost', 'Y11_Q59d', 'Ali si lahko vsak drugi dan privoščite obrok, ki vključuje meso, piščanca ali ribo (če bi to želeli)?'],
		['Življenjski standard in prikrajšanost', 'Y11_Q59e', 'Ali si lahko privoščite nakup novih in nerabljenih oblačil?'],
		['Življenjski standard in prikrajšanost', 'Y11_Q59f', 'Ali si lahko privoščite povabiti prijatelje ali sorodnike na pijačo ali obrok vsaj enkrat na mesec? '],
		['Življenjski standard in prikrajšanost', 'Y11_Q60a', 'Ali ste v vašem gospodinjstvu v zadnjih dvanajstih mesecih kdaj zamujali s plačilom najemnine ali hipoteke?'],
		['Življenjski standard in prikrajšanost', 'Y11_Q60b', 'Ali ste v vašem gospodinjstvu v zadnjih dvanajstih mesecih kdaj zamujali s plačilom računov za komunalne storitve?']
	];
var question_
	 = [
	
		['Y11_Q18', 'Lastništvo stanovanja, v katerem živite'],
		['Y11_Q19a', 'Težave s stanovanjem, v katerem živite: pomanjkanje prostora'],
		['Y11_Q19b', 'Težave s stanovanjem, v katerem živite: trhla okna, vrata ali tla'],
		['Y11_Q19c', 'Težave s stanovanjem, v katerem živite: vlaga ali voda, ki pronica skozi stene ali streho'],
		['Y11_Q19d', 'Težave s stanovanjem, v katerem živite: ni notranjega stranišča na izplakovanje s tekočo vodo'],
		['Y11_Q52', 'Čas, ki ga porabite za pot na delo/v šolo in z dela/iz šole'],
		['Y11_Q24', 'Ali menite, da lahko večini ljudi zaupate, ali da pri ravnanju z ljudmi nikoli ne morete biti dovolj previdni?'],
		['Y11_Q25a', 'Zaznana nestrpnost med revnimi in bogatimi'],
		['Y11_Q25b', 'Zaznana nestrpnost med ljudmi na vodilnih položajih in delavci'],
		['Y11_Q25c', 'Zaznana nestrpnost med moškimi in ženskami'],
		['Y11_Q25d', 'Zaznana nestrpnost med starimi in mladimi ljudmi'],
		['Y11_Q25e', 'Zaznana nestrpnost med različnimi rasnimi in etničnimi skupinami'],
		['Y11_Q22_Volunteering', 'Kako pogosto ste v zadnjih dvanajstih mesecih opravljali neplačano prostovoljno delo?'],
		['Y11_Q23d', 'Stik s politikom ali državnim funkcionarjem (če ne upoštevate običajnih stikov prek javnih služb)'],
		['Y11_Q30', 'Kako ste trenutno zadovoljni s svojim življenjem?'],
		['Y11_Q40a', 'Zadovoljstvo z izobrazbo'],
		['Y11_Q40b', 'Zadovoljstvo s trenutno službo'],
		['Y11_Q40c', 'Zadovoljstvo s trenutnim življenjskim standardom'],
		['Y11_Q40d', 'Zadovoljstvo s stanovanjem'],
		['Y11_Q40e', 'Zadovoljstvo z družinskim življenjem'],
		['Y11_Q40f', 'Zadovoljstvo z zdravjem'],
		['Y11_Q40g', 'Zadovoljstvo z družabnim življenjem'],
		['Y11_Q41', 'Gledano v celoti, kako srečni, bi rekli, da ste?'],
		['Y11_Q12a', 'Z dela sem se vrnil(-a) preveč utrujen(-a) za gospodinjska opravila.'],
		['Y11_Q12b', 'Zaradi časa, prebitega v službi, sem s težavo izpolnil(-a) svoje družinske obveznosti.'],
		['Y11_Q12c', 'Na delovnem mestu sem se s težavo osredotočil(-a) na delo zaradi svojih družinskih obveznosti.'],
		['Y11_Q15', 'Kako verjetno je, da bi izgubili svojo zaposlitev v naslednjih šestih mesecih?'],
		['Y11_Q38', 'Odnos do sodelovanja pri gospodinjskih opravilih'],
		['Y11_Q39d_stress', 'Stres'],
		['Y11_Q47a', 'Otežen obisk zdravnika zaradi oddaljenosti'],
		['Y11_Q47b', 'Otežen obisk zdravnika zaradi čakalne dobe do dneva, ko ste bili naročeni'],
		['Y11_Q47c', 'Otežen obisk zdravnika zaradi čakalnega časa na dan pregleda'],
		['Y11_Q47d', 'Otežen obisk zdravnika zaradi stroškov'],
		['Y11_Q53a', 'Kako bi ocenili kakovost zdravstvenih storitev v vaši državi?'],
		['Y11_Q53b', 'Kako bi ocenili kakovost izobraževalnega sistema v vaši državi?'],
		['Y11_Q53c', 'Kako bi ocenili kakovost javnega prevoza v vaši državi?'],
		['Y11_Q53g', 'Kako bi ocenili kakovost državnega pokojninskega sistema v vaši državi?'],
		['Y11_Q58', 'Ali ste se v vašem gospodinjstvu zmožni (finančno) prebiti čez mesec?'],
		['Y11_Q59a', 'Ali si lahko privoščite primerno ogrevan dom?'],
		['Y11_Q59b', 'Ali si lahko privoščite enotedenski letni dopust zunaj domačega kraja?'],
		['Y11_Q59c', 'Ali si lahko privoščite zamenjavo katerega koli dotrajanega kosa pohištva?'],
		['Y11_Q59d', 'Ali si lahko vsak drugi dan privoščite obrok, ki vključuje meso, piščanca ali ribo (če bi to želeli)?'],
		['Y11_Q59e', 'Ali si lahko privoščite nakup novih in nerabljenih oblačil?'],
		['Y11_Q59f', 'Ali si lahko privoščite povabiti prijatelje ali sorodnike na pijačo ali obrok vsaj enkrat na mesec? '],
		['Y11_Q60a', 'Ali ste v vašem gospodinjstvu v zadnjih dvanajstih mesecih kdaj zamujali s plačilom najemnine ali hipoteke?'],
		['Y11_Q60b', 'Ali ste v vašem gospodinjstvu v zadnjih dvanajstih mesecih kdaj zamujali s plačilom računov za komunalne storitve?']
	];
var question_answer
	 = [
	
		['Y11_Q12a', '1--Several-times-a-week', 'Večkrat na teden'],
		['Y11_Q12a', '2--Several-times-a-month', 'Večkrat na mesec'],
		['Y11_Q12a', '3--Several-times-a-year', 'Večkrat na leto'],
		['Y11_Q12a', '4--Less-often-rarely', 'Manj pogosto ali redko'],
		['Y11_Q12a', '5--Never', 'Nikoli'],
		['Y11_Q12b', '1--Several-times-a-week', 'Večkrat na teden'],
		['Y11_Q12b', '2--Several-times-a-month', 'Večkrat na mesec'],
		['Y11_Q12b', '3--Several-times-a-year', 'Večkrat na leto'],
		['Y11_Q12b', '4--Less-often-rarely', 'Manj pogosto ali redko'],
		['Y11_Q12b', '5--Never', 'Nikoli'],
		['Y11_Q12c', '1--Several-times-a-week', 'Večkrat na teden'],
		['Y11_Q12c', '2--Several-times-a-month', 'Večkrat na mesec'],
		['Y11_Q12c', '3--Several-times-a-year', 'Večkrat na leto'],
		['Y11_Q12c', '4--Less-often-rarely', 'Manj pogosto ali redko'],
		['Y11_Q12c', '5--Never', 'Nikoli'],
		['Y11_Q15', '1--Very-likely', 'Zelo verjetno'],
		['Y11_Q15', '2--Quite-likely', 'Dokaj verjetno'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Niti verjetno niti neverjetno'],
		['Y11_Q15', '4--Quite-unlikely', 'Dokaj neverjetno'],
		['Y11_Q15', '5--Very-unlikely', 'Zelo neverjetno'],
		['Y11_Q18', '1--Own-without-mortgage', 'Lastniško brez hipoteke'],
		['Y11_Q18', '2--Own-with-mortgage', 'Lastniško s hipoteko'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Najemnik, plačujem najemnino za socialno/neprofitno/občinsko stanovanje'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Najemnik, plačujem najemnino zasebniku'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Ne plačujem najemnine'],
		['Y11_Q18', '6--Other', 'Drugo'],
		['Y11_Q19a', '1--Yes', 'Da'],
		['Y11_Q19a', '2--No', 'Ne'],
		['Y11_Q19b', '1--Yes', 'Da'],
		['Y11_Q19b', '2--No', 'Ne'],
		['Y11_Q19c', '1--Yes', 'Da'],
		['Y11_Q19c', '2--No', 'Ne'],
		['Y11_Q19d', '1--Yes', 'Da'],
		['Y11_Q19d', '2--No', 'Ne'],
		['Y11_Q22_Volunteering', '3--Does-not-volunteer', 'Ne opravlja prostovoljnega dela'],
		['Y11_Q23d', '1--Yes', 'Da'],
		['Y11_Q23d', '2--No', 'Ne'],
		['Y11_Q24', 'Mean', 'Povprečje'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Veliko nestrpnosti'],
		['Y11_Q25a', '2--Some-tension', 'Nekaj nestrpnosti'],
		['Y11_Q25a', '3--No-tension', 'Ni nestrpnosti'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Veliko nestrpnosti'],
		['Y11_Q25b', '2--Some-tension', 'Nekaj nestrpnosti'],
		['Y11_Q25b', '3--No-tension', 'Ni nestrpnosti'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Veliko nestrpnosti'],
		['Y11_Q25c', '2--Some-tension', 'Nekaj nestrpnosti'],
		['Y11_Q25c', '3--No-tension', 'Ni nestrpnosti'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Veliko nestrpnosti'],
		['Y11_Q25d', '2--Some-tension', 'Nekaj nestrpnosti'],
		['Y11_Q25d', '3--No-tension', 'Ni nestrpnosti'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Veliko nestrpnosti'],
		['Y11_Q25e', '2--Some-tension', 'Nekaj nestrpnosti'],
		['Y11_Q25e', '3--No-tension', 'Ni nestrpnosti'],
		['Y11_Q30', 'Mean', 'Povprečje'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Več kot menite, da bi morali'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Ravno prav'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Manj kot menite, da bi morali'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'Na delovnem mestu in doma'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Na delovnem mestu ali doma'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Malo ali brez stresa'],
		['Y11_Q40a', 'Mean', 'Povprečje'],
		['Y11_Q40b', 'Mean', 'Povprečje'],
		['Y11_Q40c', 'Mean', 'Povprečje'],
		['Y11_Q40d', 'Mean', 'Povprečje'],
		['Y11_Q40e', 'Mean', 'Povprečje'],
		['Y11_Q40f', 'Mean', 'Povprečje'],
		['Y11_Q40g', 'Mean', 'Povprečje'],
		['Y11_Q41', 'Mean', 'Povprečje'],
		['Y11_Q47a', '1--Very-difficult', 'Zelo otežen'],
		['Y11_Q47a', '2--A-little-difficult', 'Malce otežen'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Sploh ne otežen'],
		['Y11_Q47b', '1--Very-difficult', 'Zelo otežen'],
		['Y11_Q47b', '2--A-little-difficult', 'Malce otežen'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Sploh ne otežen'],
		['Y11_Q47c', '1--Very-difficult', 'Zelo otežen'],
		['Y11_Q47c', '2--A-little-difficult', 'Malce otežen'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Sploh ne otežen'],
		['Y11_Q47d', '1--Very-difficult', 'Zelo otežen'],
		['Y11_Q47d', '2--A-little-difficult', 'Malce otežen'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Sploh ne otežen'],
		['Y11_Q52', 'Mean', 'Povprečje'],
		['Y11_Q53a', 'Mean', 'Povprečje'],
		['Y11_Q53b', 'Mean', 'Povprečje'],
		['Y11_Q53c', 'Mean', 'Povprečje'],
		['Y11_Q53g', 'Mean', 'Povprečje'],
		['Y11_Q58', '1--With-great-difficulty', 'Zelo težko'],
		['Y11_Q58', '2--With-difficulty', 'Težko'],
		['Y11_Q58', '3--With-some-difficulty', 'Z nekaj težavami'],
		['Y11_Q58', '4--Fairly-easily', 'Dokaj lahko'],
		['Y11_Q58', '5--Easily', 'Lahko'],
		['Y11_Q58', '6--Very-easily', 'Zelo lahko'],
		['Y11_Q59a', '1--No', 'Ne'],
		['Y11_Q59a', '2--Yes', 'Da'],
		['Y11_Q59b', '1--No', 'Ne'],
		['Y11_Q59b', '2--Yes', 'Da'],
		['Y11_Q59c', '1--No', 'Ne'],
		['Y11_Q59c', '2--Yes', 'Da'],
		['Y11_Q59d', '1--No', 'Ne'],
		['Y11_Q59d', '2--Yes', 'Da'],
		['Y11_Q59e', '1--No', 'Ne'],
		['Y11_Q59e', '2--Yes', 'Da'],
		['Y11_Q59f', '1--No', 'Ne'],
		['Y11_Q59f', '2--Yes', 'Da'],
		['Y11_Q60a', '1--Yes', 'Da'],
		['Y11_Q60a', '2--No', 'Ne'],
		['Y11_Q60b', '1--Yes', 'Da'],
		['Y11_Q60b', '2--No', 'Ne']
	];
var country_
	 = [
	
		['AT', 'Avstrija'],
		['BE', 'Belgija'],
		['BG', 'Bolgarija'],
		['CY', 'Ciper'],
		['CZ', 'Češka republika'],
		['DE', 'Nemčija'],
		['DK', 'Danska'],
		['EE', 'Estonija'],
		['EL', 'Grčija'],
		['ES', 'Španija'],
		['FI', 'Finska'],
		['FR', 'Francija'],
		['HU', 'Madžarska'],
		['IE', 'Irska'],
		['IT', 'Italija'],
		['LT', 'Litva'],
		['LU', 'Luksemburg'],
		['LV', 'Latvija'],
		['MT', 'Malta'],
		['NL', 'Nizozemska'],
		['PL', 'Poljska'],
		['PT', 'Portugalska'],
		['RO', 'Romunija'],
		['SE', 'Švedska'],
		['SI', 'Slovenija'],
		['SK', 'Slovaška'],
		['TR', 'Turčija'],
		['UK', 'Združeno kraljestvo'],
		['EuropeanUnion', 'Evropska unija']
	];
var question_meta
	 = [
	
		['Y11_Q18', 'Lastništvo stanovanja, v katerem živite', ''],
		['Y11_Q19a', 'Težave s stanovanjem, v katerem živite: pomanjkanje prostora', ''],
		['Y11_Q19b', 'Težave s stanovanjem, v katerem živite: trhla okna, vrata ali tla', ''],
		['Y11_Q19c', 'Težave s stanovanjem, v katerem živite: vlaga ali voda, ki pronica skozi stene ali streho', ''],
		['Y11_Q19d', 'Težave s stanovanjem, v katerem živite: ni notranjega stranišča na izplakovanje s tekočo vodo', ''],
		['Y11_Q52', 'Čas, ki ga porabite za pot na delo/v šolo in z dela/iz šole', ''],
		['Y11_Q24', 'Ali menite, da lahko večini ljudi zaupate, ali da pri ravnanju z ljudmi nikoli ne morete biti dovolj previdni?', ''],
		['Y11_Q25a', 'Zaznana nestrpnost med revnimi in bogatimi', ''],
		['Y11_Q25b', 'Zaznana nestrpnost med ljudmi na vodilnih položajih in delavci', ''],
		['Y11_Q25c', 'Zaznana nestrpnost med moškimi in ženskami', ''],
		['Y11_Q25d', 'Zaznana nestrpnost med starimi in mladimi ljudmi', ''],
		['Y11_Q25e', 'Zaznana nestrpnost med različnimi rasnimi in etničnimi skupinami', ''],
		['Y11_Q22_Volunteering', 'Kako pogosto ste v zadnjih dvanajstih mesecih opravljali neplačano prostovoljno delo?', ''],
		['Y11_Q23d', 'Stik s politikom ali državnim funkcionarjem (če ne upoštevate običajnih stikov prek javnih služb)', ''],
		['Y11_Q30', 'Kako ste trenutno zadovoljni s svojim življenjem?', ''],
		['Y11_Q40a', 'Zadovoljstvo z izobrazbo', ''],
		['Y11_Q40b', 'Zadovoljstvo s trenutno službo', ''],
		['Y11_Q40c', 'Zadovoljstvo s trenutnim življenjskim standardom', ''],
		['Y11_Q40d', 'Zadovoljstvo s stanovanjem', ''],
		['Y11_Q40e', 'Zadovoljstvo z družinskim življenjem', ''],
		['Y11_Q40f', 'Zadovoljstvo z zdravjem', ''],
		['Y11_Q40g', 'Zadovoljstvo z družabnim življenjem', ''],
		['Y11_Q41', 'Gledano v celoti, kako srečni, bi rekli, da ste?', ''],
		['Y11_Q12a', 'Z dela sem se vrnil(-a) preveč utrujen(-a) za gospodinjska opravila.', ''],
		['Y11_Q12b', 'Zaradi časa, prebitega v službi, sem s težavo izpolnil(-a) svoje družinske obveznosti.', ''],
		['Y11_Q12c', 'Na delovnem mestu sem se s težavo osredotočil(-a) na delo zaradi svojih družinskih obveznosti.', ''],
		['Y11_Q15', 'Kako verjetno je, da bi izgubili svojo zaposlitev v naslednjih šestih mesecih?', ''],
		['Y11_Q38', 'Kaj menite o svojem sodelovanju pri gospodinjskih opravilih?', ''],
		['Y11_Q39d_stress', 'Stres, povezan z ravnovesjem med poklicnim in zasebnim življenjem ', ''],
		['Y11_Q47a', 'Otežen obisk zdravnika zaradi oddaljenosti ordinacije ali bolnišnice', ''],
		['Y11_Q47b', 'Otežen obisk zdravnika zaradi čakalne dobe do dneva, ko ste bili naročeni', ''],
		['Y11_Q47c', 'Otežen obisk zdravnika zaradi čakalnega časa na dan pregleda', ''],
		['Y11_Q47d', 'Otežen obisk zdravnika zaradi stroškov', ''],
		['Y11_Q53a', 'Kako bi ocenili kakovost zdravstvenih storitev v vaši državi?', ''],
		['Y11_Q53b', 'Kako bi ocenili kakovost izobraževalnega sistema v vaši državi?', ''],
		['Y11_Q53c', 'Kako bi ocenili kakovost javnega prevoza v vaši državi?', ''],
		['Y11_Q53g', 'Kako bi ocenili kakovost državnega pokojninskega sistema v vaši državi?', ''],
		['Y11_Q58', 'Ali ste se v vašem gospodinjstvu zmožni (finančno) prebiti čez mesec?', ''],
		['Y11_Q59a', 'Ali si lahko privoščite primerno ogrevan dom?', ''],
		['Y11_Q59b', 'Ali si lahko privoščite enotedenski letni dopust zunaj domačega kraja?', ''],
		['Y11_Q59c', 'Ali si lahko privoščite zamenjavo katerega koli dotrajanega kosa pohištva?', ''],
		['Y11_Q59d', 'Ali si lahko vsak drugi dan privoščite obrok, ki vključuje meso, piščanca ali ribo (če bi to želeli)?', ''],
		['Y11_Q59e', 'Ali si lahko privoščite nakup novih in nerabljenih oblačil?', ''],
		['Y11_Q59f', 'Ali si lahko privoščite povabiti prijatelje ali sorodnike na pijačo ali obrok vsaj enkrat na mesec? ', ''],
		['Y11_Q60a', 'Ali ste v vašem gospodinjstvu v zadnjih dvanajstih mesecih kdaj zamujali s plačilom najemnine ali hipoteke?', ''],
		['Y11_Q60b', 'Ali ste v vašem gospodinjstvu v zadnjih dvanajstih mesecih kdaj zamujali s plačilom  računov za komunalne storitve?', '']
	];
