//Auto Generated file
var subset_
	 = [
	
		['Y11_Incomequartiles_percapita', 'Inkomst'],
		['Y11_HH2a', 'Kön'],
		['Y11_Agecategory', 'Ålder']
	];
var subset_subsetValue
	 = [
	
		['Y11_Agecategory', 'All', 'Alla åldrar'],
		['Y11_Agecategory', '1--18-24y', '18 till 24 år'],
		['Y11_Agecategory', '2--25-34y', '25 till 34 år'],
		['Y11_Agecategory', '3--35-49y', '35 till 49 år'],
		['Y11_Agecategory', '4--50-64y', '50 till 64 år'],
		['Y11_Agecategory', '5---64y', '> 64 år'],
		['Y11_HH2a', 'All', 'Båda könen'],
		['Y11_HH2a', '1--Female', 'Kvinna'],
		['Y11_HH2a', '2--Male', 'Man'],
		['Y11_Incomequartiles_percapita', 'All', 'Alla inkomstnivåer'],
		['Y11_Incomequartiles_percapita', '1--Lowest', 'Lägsta'],
		['Y11_Incomequartiles_percapita', '2--2nd', '2:a'],
		['Y11_Incomequartiles_percapita', '3--3rd', '3:e'],
		['Y11_Incomequartiles_percapita', '4--Highest', 'Högsta']
	];
var topic_
	 = [
	
		['', 'Alla (46)'],
		['Anställning och balans arbete–fritid', 'Anställning och balans arbete–fritid (6)'],
		['Hem och närmiljö', 'Hem och närmiljö (6)'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Hälso- och sjukvård samt offentliga tjänster (8)'],
		['Levnadsstandard och fattigdom', 'Levnadsstandard och fattigdom (9)'],
		['Samhällets kvalitet', 'Samhällets kvalitet (6)'],
		['Social utstötning och samhällsengagemang', 'Social utstötning och samhällsengagemang (2)'],
		['Subjektivt välstånd', 'Subjektivt välstånd (9)']
	];
var topic_question
	 = [
	
		['Anställning och balans arbete–fritid', 'Y11_Q12a', 'Jag har kommit hem från arbetet för trött för att utföra hushållssysslor.'],
		['Anställning och balans arbete–fritid', 'Y11_Q12b', 'Jag har haft svårt att uppfylla mitt ansvar mot familjen på grund av mina arbetstider. '],
		['Anställning och balans arbete–fritid', 'Y11_Q12c', 'Jag har haft svårt att koncentrera mig på arbetet på grund av ansvaret gentemot familjen.'],
		['Anställning och balans arbete–fritid', 'Y11_Q15', 'Hur sannolikt är det att du ska förlora jobbet under de kommande sex månaderna?'],
		['Anställning och balans arbete–fritid', 'Y11_Q38', 'Attityd när det gäller att dela på hushållsarbetet.'],
		['Anställning och balans arbete–fritid', 'Y11_Q39d_stress', 'Stress.'],
		['Hem och närmiljö', 'Y11_Q18', 'Bostaden'],
		['Hem och närmiljö', 'Y11_Q19a', 'Problem med bostaden: brist på utrymme.'],
		['Hem och närmiljö', 'Y11_Q19b', 'Problem med bostaden: röta i fönster, dörrar eller golv.'],
		['Hem och närmiljö', 'Y11_Q19c', 'Problem med bostaden: fukt eller läckage i väggar eller tak.'],
		['Hem och närmiljö', 'Y11_Q19d', 'Problem med bostaden: inget wc inomhus.'],
		['Hem och närmiljö', 'Y11_Q52', 'Tid för att ta sig till eller från arbete eller studier.'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q47a', 'Svårt att besöka läkare på grund av avståndet.'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q47b', 'Svårt att besöka läkare på grund av svårigheter med att boka tid.'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q47c', 'Svårt att besöka läkare på grund av långa väntetider på mottagningen den bokade tiden.'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q47d', 'Svårt att besöka läkare på grund av kostnaden.'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q53a', 'Hur skulle du bedöma kvaliteten på hälso- och sjukvården i ditt land?'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q53b', 'Hur skulle du bedöma kvaliteten på utbildningssystemet i ditt land?'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q53c', 'Hur skulle du bedöma kvaliteten på de offentliga transporterna i ditt land?'],
		['Hälso- och sjukvård samt offentliga tjänster', 'Y11_Q53g', 'Hur skulle du bedöma kvaliteten på det statliga pensionssystemet i ditt land?'],
		['Levnadsstandard och fattigdom', 'Y11_Q58', 'Kan ditt hushåll klara av att betala sina utgifter?'],
		['Levnadsstandard och fattigdom', 'Y11_Q59a', 'Har du råd att hålla bostaden tillräckligt varm?'],
		['Levnadsstandard och fattigdom', 'Y11_Q59b', 'Har du råd att resa på en veckas semester?'],
		['Levnadsstandard och fattigdom', 'Y11_Q59c', 'Har du råd att ersätta utslitna möbler?'],
		['Levnadsstandard och fattigdom', 'Y11_Q59d', 'Skulle du ha råd att äta kött, kyckling eller fisk varannan dag (om du vill)?'],
		['Levnadsstandard och fattigdom', 'Y11_Q59e', 'Har du råd att köpa nya i stället för begagnade kläder?'],
		['Levnadsstandard och fattigdom', 'Y11_Q59f', 'Har du råd att bjuda in vänner eller familj på en drink eller måltid minst en gång i månaden?'],
		['Levnadsstandard och fattigdom', 'Y11_Q60a', 'Har ditt hushåll legat efter med hyran eller avbetalningar på bostadslån under de senaste tolv månaderna?'],
		['Levnadsstandard och fattigdom', 'Y11_Q60b', 'Har ditt hushåll legat efter med att betala räkningar för vatten, el etc. under de senaste tolv månaderna?'],
		['Samhällets kvalitet', 'Y11_Q24', 'Anser du att man kan lita på de flesta människor eller att man aldrig kan vara nog försiktig i kontakten med andra?'],
		['Samhällets kvalitet', 'Y11_Q25a', 'Upplevd spänning mellan fattiga och rika.'],
		['Samhällets kvalitet', 'Y11_Q25b', 'Upplevd spänning mellan chefer och anställda.'],
		['Samhällets kvalitet', 'Y11_Q25c', 'Upplevd spänning mellan män och kvinnor.'],
		['Samhällets kvalitet', 'Y11_Q25d', 'Upplevd spänning mellan gamla och unga.'],
		['Samhällets kvalitet', 'Y11_Q25e', 'Upplevd spänning mellan olika raser och etniska grupper.'],
		['Social utstötning och samhällsengagemang', 'Y11_Q22_Volunteering', 'Hur ofta utförde du ideellt arbete under de senaste tolv månaderna?'],
		['Social utstötning och samhällsengagemang', 'Y11_Q23d', 'Kontaktade politiker eller offentlig tjänsteman (förutom rutinkontakt genom offentlig förvaltning).'],
		['Subjektivt välstånd', 'Y11_Q30', 'Hur tillfredsställd är du med ditt liv nuförtiden?'],
		['Subjektivt välstånd', 'Y11_Q40a', 'Tillfredsställelse med utbildning'],
		['Subjektivt välstånd', 'Y11_Q40b', 'Tillfredsställelse med nuvarande arbete'],
		['Subjektivt välstånd', 'Y11_Q40c', 'Tillfredsställelse med nuvarande levnadsstandard'],
		['Subjektivt välstånd', 'Y11_Q40d', 'Tillfredsställelse med bostad'],
		['Subjektivt välstånd', 'Y11_Q40e', 'Tillfredsställelse med familjeliv'],
		['Subjektivt välstånd', 'Y11_Q40f', 'Tillfredsställelse med hälsa'],
		['Subjektivt välstånd', 'Y11_Q40g', 'Tillfredsställelse med umgänge'],
		['Subjektivt välstånd', 'Y11_Q41', 'Om du sammanfattar allt detta, hur lycklig anser du att du är?']
	];
var question_
	 = [
	
		['Y11_Q12a', 'Jag har kommit hem från arbetet för trött för att utföra hushållssysslor.'],
		['Y11_Q12b', 'Jag har haft svårt att uppfylla mitt ansvar mot familjen på grund av mina arbetstider. '],
		['Y11_Q12c', 'Jag har haft svårt att koncentrera mig på arbetet på grund av ansvaret gentemot familjen.'],
		['Y11_Q15', 'Hur sannolikt är det att du ska förlora jobbet under de kommande sex månaderna?'],
		['Y11_Q38', 'Attityd när det gäller att dela på hushållsarbetet.'],
		['Y11_Q39d_stress', 'Stress.'],
		['Y11_Q18', 'Bostaden'],
		['Y11_Q19a', 'Problem med bostaden: brist på utrymme.'],
		['Y11_Q19b', 'Problem med bostaden: röta i fönster, dörrar eller golv.'],
		['Y11_Q19c', 'Problem med bostaden: fukt eller läckage i väggar eller tak.'],
		['Y11_Q19d', 'Problem med bostaden: inget wc inomhus.'],
		['Y11_Q52', 'Tid för att ta sig till eller från arbete eller studier.'],
		['Y11_Q47a', 'Svårt att besöka läkare på grund av avståndet.'],
		['Y11_Q47b', 'Svårt att besöka läkare på grund av svårigheter med att boka tid.'],
		['Y11_Q47c', 'Svårt att besöka läkare på grund av långa väntetider på mottagningen den bokade tiden.'],
		['Y11_Q47d', 'Svårt att besöka läkare på grund av kostnaden.'],
		['Y11_Q53a', 'Hur skulle du bedöma kvaliteten på hälso- och sjukvården i ditt land?'],
		['Y11_Q53b', 'Hur skulle du bedöma kvaliteten på utbildningssystemet i ditt land?'],
		['Y11_Q53c', 'Hur skulle du bedöma kvaliteten på de offentliga transporterna i ditt land?'],
		['Y11_Q53g', 'Hur skulle du bedöma kvaliteten på det statliga pensionssystemet i ditt land?'],
		['Y11_Q58', 'Kan ditt hushåll klara av att betala sina utgifter?'],
		['Y11_Q59a', 'Har du råd att hålla bostaden tillräckligt varm?'],
		['Y11_Q59b', 'Har du råd att resa på en veckas semester?'],
		['Y11_Q59c', 'Har du råd att ersätta utslitna möbler?'],
		['Y11_Q59d', 'Skulle du ha råd att äta kött, kyckling eller fisk varannan dag (om du vill)?'],
		['Y11_Q59e', 'Har du råd att köpa nya i stället för begagnade kläder?'],
		['Y11_Q59f', 'Har du råd att bjuda in vänner eller familj på en drink eller måltid minst en gång i månaden?'],
		['Y11_Q60a', 'Har ditt hushåll legat efter med hyran eller avbetalningar på bostadslån under de senaste tolv månaderna?'],
		['Y11_Q60b', 'Har ditt hushåll legat efter med att betala räkningar för vatten, el etc. under de senaste tolv månaderna?'],
		['Y11_Q24', 'Anser du att man kan lita på de flesta människor eller att man aldrig kan vara nog försiktig i kontakten med andra?'],
		['Y11_Q25a', 'Upplevd spänning mellan fattiga och rika.'],
		['Y11_Q25b', 'Upplevd spänning mellan chefer och anställda.'],
		['Y11_Q25c', 'Upplevd spänning mellan män och kvinnor.'],
		['Y11_Q25d', 'Upplevd spänning mellan gamla och unga.'],
		['Y11_Q25e', 'Upplevd spänning mellan olika raser och etniska grupper.'],
		['Y11_Q22_Volunteering', 'Hur ofta utförde du ideellt arbete under de senaste tolv månaderna?'],
		['Y11_Q23d', 'Kontaktade politiker eller offentlig tjänsteman (förutom rutinkontakt genom offentlig förvaltning).'],
		['Y11_Q30', 'Hur tillfredsställd är du med ditt liv nuförtiden?'],
		['Y11_Q40a', 'Tillfredsställelse med utbildning'],
		['Y11_Q40b', 'Tillfredsställelse med nuvarande arbete'],
		['Y11_Q40c', 'Tillfredsställelse med nuvarande levnadsstandard'],
		['Y11_Q40d', 'Tillfredsställelse med bostad'],
		['Y11_Q40e', 'Tillfredsställelse med familjeliv'],
		['Y11_Q40f', 'Tillfredsställelse med hälsa'],
		['Y11_Q40g', 'Tillfredsställelse med umgänge'],
		['Y11_Q41', 'Om du sammanfattar allt detta, hur lycklig anser du att du är?']
	];
var question_answer
	 = [
	
		['Y11_Q12a', '1--Several-times-a-week', 'Flera gånger i veckan'],
		['Y11_Q12a', '2--Several-times-a-month', 'Flera gånger i månaden'],
		['Y11_Q12a', '3--Several-times-a-year', 'Flera gånger om året'],
		['Y11_Q12a', '4--Less-often-rarely', 'Mindre ofta eller sällan'],
		['Y11_Q12a', '5--Never', 'Aldrig'],
		['Y11_Q12b', '1--Several-times-a-week', 'Flera gånger i veckan'],
		['Y11_Q12b', '2--Several-times-a-month', 'Flera gånger i månaden'],
		['Y11_Q12b', '3--Several-times-a-year', 'Flera gånger om året'],
		['Y11_Q12b', '4--Less-often-rarely', 'Mindre ofta eller sällan'],
		['Y11_Q12b', '5--Never', 'Aldrig'],
		['Y11_Q12c', '1--Several-times-a-week', 'Flera gånger i veckan'],
		['Y11_Q12c', '2--Several-times-a-month', 'Flera gånger i månaden'],
		['Y11_Q12c', '3--Several-times-a-year', 'Flera gånger om året'],
		['Y11_Q12c', '4--Less-often-rarely', 'Mindre ofta eller sällan'],
		['Y11_Q12c', '5--Never', 'Aldrig'],
		['Y11_Q15', '1--Very-likely', 'Mycket sannolikt'],
		['Y11_Q15', '2--Quite-likely', 'Ganska sannolikt'],
		['Y11_Q15', '3--Neither-likely-nor-unlikely', 'Varken sannolikt eller osannolikt'],
		['Y11_Q15', '4--Quite-unlikely', 'Ganska osannolikt'],
		['Y11_Q15', '5--Very-unlikely', 'Mycket osannolikt'],
		['Y11_Q18', '1--Own-without-mortgage', 'Äger utan lån'],
		['Y11_Q18', '2--Own-with-mortgage', 'Äger med lån'],
		['Y11_Q18', '3--Tenant--paying-rent-in-social-voluntary-municipal-housing', 'Hyresgäst, betalar hyra till subventionerad, frivillig eller kommunal bostad'],
		['Y11_Q18', '4--Tenant--paying-rent-to-private-landlord', 'Hyresgäst, betalar hyra till privat hyresvärd'],
		['Y11_Q18', '5--Accommodation-is-provided-rent-free', 'Bostaden hyresfri'],
		['Y11_Q18', '6--Other', 'Övrigt'],
		['Y11_Q19a', '1--Yes', 'Ja'],
		['Y11_Q19a', '2--No', 'Nej'],
		['Y11_Q19b', '1--Yes', 'Ja'],
		['Y11_Q19b', '2--No', 'Nej'],
		['Y11_Q19c', '1--Yes', 'Ja'],
		['Y11_Q19c', '2--No', 'Nej'],
		['Y11_Q19d', '1--Yes', 'Ja'],
		['Y11_Q19d', '2--No', 'Nej'],
		['Y11_Q22_Volunteering', '3--Does-not-volunteer', 'Arbetar aldrig frivilligt'],
		['Y11_Q23d', '1--Yes', 'Ja'],
		['Y11_Q23d', '2--No', 'Nej'],
		['Y11_Q24', 'Mean', 'Genomsnittligt'],
		['Y11_Q25a', '1--A-lot-of--tension', 'Mycket spänning'],
		['Y11_Q25a', '2--Some-tension', 'Viss spänning'],
		['Y11_Q25a', '3--No-tension', 'Ingen spänning'],
		['Y11_Q25b', '1--A-lot-of--tension', 'Mycket spänning'],
		['Y11_Q25b', '2--Some-tension', 'Viss spänning'],
		['Y11_Q25b', '3--No-tension', 'Ingen spänning'],
		['Y11_Q25c', '1--A-lot-of--tension', 'Mycket spänning'],
		['Y11_Q25c', '2--Some-tension', 'Viss spänning'],
		['Y11_Q25c', '3--No-tension', 'Ingen spänning'],
		['Y11_Q25d', '1--A-lot-of--tension', 'Mycket spänning'],
		['Y11_Q25d', '2--Some-tension', 'Viss spänning'],
		['Y11_Q25d', '3--No-tension', 'Ingen spänning'],
		['Y11_Q25e', '1--A-lot-of--tension', 'Mycket spänning'],
		['Y11_Q25e', '2--Some-tension', 'Viss spänning'],
		['Y11_Q25e', '3--No-tension', 'Ingen spänning'],
		['Y11_Q30', 'Mean', 'Genomsnittligt'],
		['Y11_Q38', '1--More-than-your-fair-share', 'Mer än din skäliga andel'],
		['Y11_Q38', '2--Just-about-your-fair-share', 'Ungefär din skäliga andel'],
		['Y11_Q38', '3--Less-than-your-fair-share', 'Mindre än din skäliga andel'],
		['Y11_Q39d_stress', '1--Both-work-and-home-conflict', 'På arbetet och hemma'],
		['Y11_Q39d_stress', '2--Either-work-or-home-conflict', 'Varken på arbetet eller hemma'],
		['Y11_Q39d_stress', '3--No-or-weak-conflict', 'Lite eller ingen stress'],
		['Y11_Q40a', 'Mean', 'Genomsnittligt'],
		['Y11_Q40b', 'Mean', 'Genomsnittligt'],
		['Y11_Q40c', 'Mean', 'Genomsnittligt'],
		['Y11_Q40d', 'Mean', 'Genomsnittligt'],
		['Y11_Q40e', 'Mean', 'Genomsnittligt'],
		['Y11_Q40f', 'Mean', 'Genomsnittligt'],
		['Y11_Q40g', 'Mean', 'Genomsnittligt'],
		['Y11_Q41', 'Mean', 'Genomsnittligt'],
		['Y11_Q47a', '1--Very-difficult', 'Mycket svårt'],
		['Y11_Q47a', '2--A-little-difficult', 'Ganska svårt'],
		['Y11_Q47a', '3--Not-difficult-at-all', 'Inte alls svårt'],
		['Y11_Q47b', '1--Very-difficult', 'Mycket svårt'],
		['Y11_Q47b', '2--A-little-difficult', 'Ganska svårt'],
		['Y11_Q47b', '3--Not-difficult-at-all', 'Inte alls svårt'],
		['Y11_Q47c', '1--Very-difficult', 'Mycket svårt'],
		['Y11_Q47c', '2--A-little-difficult', 'Ganska svårt'],
		['Y11_Q47c', '3--Not-difficult-at-all', 'Inte alls svårt'],
		['Y11_Q47d', '1--Very-difficult', 'Mycket svårt'],
		['Y11_Q47d', '2--A-little-difficult', 'Ganska svårt'],
		['Y11_Q47d', '3--Not-difficult-at-all', 'Inte alls svårt'],
		['Y11_Q52', 'Mean', 'Genomsnittligt'],
		['Y11_Q53a', 'Mean', 'Genomsnittligt'],
		['Y11_Q53b', 'Mean', 'Genomsnittligt'],
		['Y11_Q53c', 'Mean', 'Genomsnittligt'],
		['Y11_Q53g', 'Mean', 'Genomsnittligt'],
		['Y11_Q58', '1--With-great-difficulty', 'Med stor svårighet'],
		['Y11_Q58', '2--With-difficulty', 'Med svårighet'],
		['Y11_Q58', '3--With-some-difficulty', 'Med viss svårighet'],
		['Y11_Q58', '4--Fairly-easily', 'Ganska lätt'],
		['Y11_Q58', '5--Easily', 'Lätt'],
		['Y11_Q58', '6--Very-easily', 'Mycket lätt'],
		['Y11_Q59a', '1--No', 'Nej'],
		['Y11_Q59a', '2--Yes', 'Ja'],
		['Y11_Q59b', '1--No', 'Nej'],
		['Y11_Q59b', '2--Yes', 'Ja'],
		['Y11_Q59c', '1--No', 'Nej'],
		['Y11_Q59c', '2--Yes', 'Ja'],
		['Y11_Q59d', '1--No', 'Nej'],
		['Y11_Q59d', '2--Yes', 'Ja'],
		['Y11_Q59e', '1--No', 'Nej'],
		['Y11_Q59e', '2--Yes', 'Ja'],
		['Y11_Q59f', '1--No', 'Nej'],
		['Y11_Q59f', '2--Yes', 'Ja'],
		['Y11_Q60a', '1--Yes', 'Ja'],
		['Y11_Q60a', '2--No', 'Nej'],
		['Y11_Q60b', '1--Yes', 'Ja'],
		['Y11_Q60b', '2--No', 'Nej']
	];
var country_
	 = [
	
		['AT', 'Österrike'],
		['BE', 'Belgien'],
		['BG', 'Bulgarien'],
		['CY', 'Cypern'],
		['CZ', 'Tjeckien'],
		['DE', 'Tyskland'],
		['DK', 'Danmark'],
		['EE', 'Estland'],
		['EL', 'Grekland'],
		['ES', 'Spanien'],
		['FI', 'Finland'],
		['FR', 'Frankrike'],
		['HU', 'Ungern'],
		['IE', 'Irland'],
		['IT', 'Italien'],
		['LT', 'Litauen'],
		['LU', 'Luxemburg'],
		['LV', 'Lettland'],
		['MT', 'Malta'],
		['NL', 'Nederländerna'],
		['PL', 'Polen'],
		['PT', 'Portugal'],
		['RO', 'Rumänien'],
		['SE', 'Sverige'],
		['SI', 'Slovenien'],
		['SK', 'Slovakien'],
		['TR', 'Turkiet'],
		['UK', 'Storbritannien'],
		['EuropeanUnion', 'Europeiska unionen']
	];
var question_meta
	 = [
	
		['Y11_Q12a', 'Jag har kommit hem från arbetet för trött för att utföra hushållssysslor.', ''],
		['Y11_Q12b', 'Jag har haft svårt att uppfylla mitt ansvar mot familjen på grund av mina arbetstider. ', ''],
		['Y11_Q12c', 'Jag har haft svårt att koncentrera mig på arbetet på grund av ansvaret gentemot familjen.', ''],
		['Y11_Q15', 'Hur sannolikt är det att du ska förlora jobbet under de kommande sex månaderna?', ''],
		['Y11_Q38', 'Vad anser du om den del av hushållsarbetet som du utför?', ''],
		['Y11_Q39d_stress', 'Stress på grund av bristande balans arbete-fritid.', ''],
		['Y11_Q18', 'Bostaden', ''],
		['Y11_Q19a', 'Problem med bostaden: brist på utrymme.', ''],
		['Y11_Q19b', 'Problem med bostaden: röta i fönster, dörrar eller golv.', ''],
		['Y11_Q19c', 'Problem med bostaden: fukt eller läckage i väggar eller tak.', ''],
		['Y11_Q19d', 'Problem med bostaden: inget wc inomhus.', ''],
		['Y11_Q52', 'Tid för att ta sig till eller från arbete eller studier.', ''],
		['Y11_Q47a', 'Svårt att besöka läkare på grund av avståndet till läkarens mottagning eller sjukhuset.', ''],
		['Y11_Q47b', 'Svårt att besöka läkare på grund av svårigheter med att boka tid.', ''],
		['Y11_Q47c', 'Svårt att besöka läkare på grund av långa väntetider innan man får träffa läkaren den bokade tiden.', ''],
		['Y11_Q47d', 'Svårt att besöka läkare på grund av kostnaden för att träffa en läkare.', ''],
		['Y11_Q53a', 'Hur skulle du bedöma kvaliteten på hälso- och sjukvården i ditt land?', ''],
		['Y11_Q53b', 'Hur skulle du bedöma kvaliteten på utbildningssystemet i ditt land?', ''],
		['Y11_Q53c', 'Hur skulle du bedöma kvaliteten på de offentliga transporterna i ditt land?', ''],
		['Y11_Q53g', 'Hur skulle du bedöma kvaliteten på det statliga pensionssystemet i ditt land?', ''],
		['Y11_Q58', 'Kan ditt hushåll klara av att betala sina utgifter?', ''],
		['Y11_Q59a', 'Har du råd att hålla bostaden tillräckligt varm?', ''],
		['Y11_Q59b', 'Har du råd att resa på en veckas semester?', ''],
		['Y11_Q59c', 'Har du råd att ersätta utslitna möbler?', ''],
		['Y11_Q59d', 'Har ditt hushåll råd att äta kött, kyckling eller fisk varannan dag (om ni skulle vilja)?', ''],
		['Y11_Q59e', 'Har medlemmarna i hushållet råd att köpa nya i stället för begagnade kläder?', ''],
		['Y11_Q59f', 'Har ditt hushåll råd att bjuda in vänner eller familj på en drink eller måltid minst en gång i månaden?', ''],
		['Y11_Q60a', 'Har ditt hushåll legat efter med hyran eller avbetalningar på bostadslån under de senaste tolv månaderna?', ''],
		['Y11_Q60b', 'Har ditt hushåll legat efter med att betala räkningar för vatten, el etc. under de senaste tolv månaderna?', ''],
		['Y11_Q24', 'Anser du att man kan lita på de flesta människor eller att man aldrig kan vara nog försiktig i kontakten med andra?', ''],
		['Y11_Q25a', 'Upplevd spänning mellan fattiga och rika.', ''],
		['Y11_Q25b', 'Upplevd spänning mellan chefer och anställda.', ''],
		['Y11_Q25c', 'Upplevd spänning mellan män och kvinnor.', ''],
		['Y11_Q25d', 'Upplevd spänning mellan gamla och unga.', ''],
		['Y11_Q25e', 'Upplevd spänning mellan olika raser och etniska grupper.', ''],
		['Y11_Q22_Volunteering', 'Hur ofta utförde du ideellt arbete under de senaste tolv månaderna?', ''],
		['Y11_Q23d', 'Kontaktade politiker eller offentlig tjänsteman (förutom rutinkontakt genom offentlig förvaltning).', ''],
		['Y11_Q30', 'Hur tillfredsställd är du med ditt liv nuförtiden?', ''],
		['Y11_Q40a', 'Tillfredsställelse med utbildning', ''],
		['Y11_Q40b', 'Tillfredsställelse med nuvarande arbete', ''],
		['Y11_Q40c', 'Tillfredsställelse med nuvarande levnadsstandard', ''],
		['Y11_Q40d', 'Tillfredsställelse med bostad', ''],
		['Y11_Q40e', 'Tillfredsställelse med familjeliv', ''],
		['Y11_Q40f', 'Tillfredsställelse med hälsa', ''],
		['Y11_Q40g', 'Tillfredsställelse med umgänge', ''],
		['Y11_Q41', 'Om du sammanfattar allt detta, hur lycklig anser du att du är?', '']
	];
